### ISSUE TITLE
Wrong Java version default when creating a project from IntelliJ

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1001]
Not sure what is going on here, this seems a little weird...

Before reproing, make sure to `flutter upgrade` as the android templates changed recently.

## Case 1: Create from terminal

Run these steps:

```
flutter create test1
cd test1
idea .
```

Then, in project view navigate to /android/app/.../MainActivity.java and notice that there are no errors shown.

## Case 2: Create from IntelliJ

1. Close all projects, and restart IJ.
1. Create New Project > Flutter > Call it test2

 Then, in project view navigate to /android/app/.../MainActivity.java and notice that you get an error for the `@override` annotation.

You can fix this in module settings by changing to language level8. BUT, why is this needed in this case when it's not needed in case 1?

**Comment by mit-mit** [comment]
cc @skybrian

**Comment by skybrian** [comment]
Reproduced. In case 1, the Project SDK is set to "Android API Platform" in the templates, and, assuming you actually have this SDK defined in IDEA, it will automatically default to the right setting.

In case 2, the Project SDK is not set at all. I suspect we're overwriting these settings in the new Flutter project creation code. I'll take a look.
