### ISSUE TITLE
Device list can become out of sync with extensive use

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter-intellij#1008]
## Steps to Reproduce
I have yet to find a way to get reproduce this consistently, but it happens fairly often to me.  I test on several devices and emulators:
Devices: iPhone7, Gen 3 MotoX, Nexus 5
Simulator: iPhone SE, Pixel

After building enough times to some devices, at some point the device list will just stop updating.  I don't know what causes it exactly though.  But that's the use case.  Best advice I can give is try to build a complete app with flutter with several devices.    The issue can be fixed by restarting the IDE.

## Version info
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 5a9b525146 (4 days ago), 2017-05-05 11:27:15 -0700
    • Engine revision 0071651ecb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.0 (API 24) (emulator)
    • Nexus 5X                  • 0106bcc49c8ca3eb                     • android-arm • Android 7.1.1 (API 25)
    • iPhone SE                 • 046CD453-58EF-4F20-9C95-CDD2713DFADC • ios         • iOS 10.3 (simulator)
```

**Comment by skybrian** [comment]
Sorry to hear that. Apparently we need more logging here.

As another workaround, closing and reopening the project will restart the daemon that updates the menu.

**Comment by pq** [comment]
@skybrian : 👍  -- it would be good to get the kind of logging in place that would help us identify if this problem is on the `flutter tools` or IDE side of things.

Thanks a million for the report @KevinTheGray!

**Comment by skybrian** [comment]
Along with error reporting, I'm going to work on automatically restarting the daemon if it dies.
