### ISSUE TITLE
Have the new project wizard show failure messages from 'flutter create'.

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#1009]
I can't create an application with caps. Lowercase app names work. 

Same goes for the command.
` flutter create ./MyApp`

## Steps to Reproduce
1. Create app with Caps
![screen shot 2017-05-09 at 4 40 24 pm](https://cloud.githubusercontent.com/assets/1326504/25877092/38df5d28-34d6-11e7-8e10-f0fd21e5fe95.png)
2. Notice Failure
![screen shot 2017-05-09 at 4 30 23 pm](https://cloud.githubusercontent.com/assets/1326504/25877096/3f0bc15a-34d6-11e7-8162-5045fea995d2.png)

## Version info
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision 5b18fca053 (60 minutes ago), 2017-05-09 15:41:06 -0700
    • Engine revision cbbf956fcb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • None
```

**Comment by branflake2267** [comment]
Workaround: Use app name with all lowercase characters. 
![screen shot 2017-05-09 at 4 42 19 pm](https://cloud.githubusercontent.com/assets/1326504/25877119/7d7ce5ae-34d6-11e7-88a0-372529e31c47.png)

**Comment by skybrian** [comment]
I believe this is due to a recent change to the "flutter create" command. When I try it from the command line:

```
"MyAppToday2" is not a valid Dart package name.

**DO** use `lowercase_with_underscores` for package names.

From the [Pubspec format description]
(https://www.dartlang.org/tools/pub/pubspec.html):

Package names should be all lowercase, with underscores to separate words,
`just_like_this`. Use only basic Latin letters and Arabic digits: [a-z0-9_].
Also, make sure the name is a valid Dart identifier -- that it doesn't start
```

So one is that we need to display the output when the command fails.

**Comment by eseidelGoogle** [comment]
I believe this was done to avoid bugs on windows.  @goderbauer but is probably too restrictive for non-windows systems.  Windows having a non-case-preserving file system is the oddball these days.

**Comment by devoncarew** [comment]
We may want an option in flutter create, `flutter create --validate-name <foo-name>`, that won't create a project but will run the validation logic. This will allow IntelliJ and flutter_tools to share the same validation logic (currently duplicated, and different).

**Comment by goderbauer** [comment]
The check was added because the project name is also used as the name for the created dart package. For dart packages, the dart style guide heavily recomands using the 'lowercase_with_underscore' style to keep your program portable between case sensitive and case insensitive file systems. We were experiencing some funny bugs when a flutter program not following this style was hot reloaded from a system with case insensitive file system (that's not only Windows, but also Mac OS) into a system with case sensitive file system (android). To avoid those, the check to ensure a valid dart package name as project name was added. 

I don't think we should weaken that check. Instead, IntelliJ just needs to inform the user why the create command failed.

**Comment by pq** [comment]
Thanks for this @branflake2267.  I was looking at some related validation and will do some updating to align project creation with the checks in `flutter create`.  (Incidentally, this is tangentially related to proposals for a shareable validation API tracked in https://github.com/dart-lang/linter/issues/654 and https://github.com/dart-lang/linter/issues/657.)

Cheers!

**Comment by skybrian** [comment]
re: "Instead, IntelliJ just needs to inform the user why the create command failed."

We should do that as a fallback, but IDEA's project wizard checks the project name as you type, so checking it in `flutter create` is too late.
