### ISSUE TITLE
add test launch config

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#101]
@stevemessick, can you add an intellij launch config to running the tests for the flutter plugin? We have something similar for the Dart plugin. Perhaps also add a wiki for how to run the flutter tests, or update the https://github.com/flutter/flutter-intellij/blob/master/CONTRIBUTING.md doc. Thanks!

**Comment by stevemessick** [comment]
I asked Alex for help here. You should be able to right-click on a test class, select the Run item, and it just works. It's fine in the Dart plugin but not Flutter. You should have gotten an error explaining that -Dflutter.sdk needs to be added to the VM options. But yeah, the docs need to explain this.

**Comment by devoncarew** [comment]
Thanks! I was able to run it.

It'd be great to have a launch config checked into `.idea/runConfigurations`, but some quick poking around couldn't yield me one. I'll close, but feel free to re-open if you can figure out how to create one.

**Comment by stevemessick** [comment]
https://github.com/flutter/flutter-intellij/pull/106
