### ISSUE TITLE
Empty project folder after creating new Flutter "module" in IntelliJ 

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1014]
_From @rxlabz on May 11, 2017 10:29_

Nothing happens when I create a new Flutter "module" inside a Intellij existing project. Creating new Flutter project works fine, but File/New/Module => Flutter create a folder with the .iml file alone.

Creating other type of Dart "modules" works fine.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision 2f590eccbc (5 hours ago), 2017-05-10 22:08:27 -0700
    • Engine revision f2581c9bcc
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.6)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.0

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.3 RC)
    • Dart plugin version 171.4006
    • Flutter plugin version 13.1

[-] WebStorm (version 2017.1)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • None
```

_Copied from original issue: flutter/flutter#9990_

**Comment by mit-mit** [comment]
I can repro this on macOS with IntelliJ IDEA Ultimate Edition (version 2017.1.3 RC)

**Comment by mit-mit** [comment]
cc @devoncarew @pq

**Comment by mit-mit** [comment]
@rxlabz, not sure if this is helpful for what you need, but the following workaround seems to work:

1. Right-click Project view > Open Module Settings
1. Click + > New Module
1. Pick Flutter + enter properties as usual

**Comment by rxlabz** [comment]
@mit-mit thanks it helps, it is better than creating a new project and then open the .iml as new module in another project ! :)

**Comment by rxlabz** [comment]
@mit-mit hoops this method seems to have another problem => ( I'm not sure of it is linked, but) after creating a module via the Project settings/+ Module... , it adds the android subfolder as module in my project 
![project_structure](https://cloud.githubusercontent.com/assets/1397248/25946611/3b30d0da-364c-11e7-9eb1-8e644d7089e2.png)

**Comment by pq** [comment]
cc @skybrian for thoughts on the android setup.

**Comment by skybrian** [comment]
I'm not sure what we want to happen here from a user experience perspective? The underlying "flutter create" command actually creates a new Flutter project with two modules in it. (We are doing this from FlutterModuleBuilder which is a bit of a hack, but that's how IDEA does it.) The directories have a fixed structure and we do need both modules if you want editing Android files to work.

So maybe we need to figure out how to disable adding a Flutter module to an existing project? It seems unlikely to do what you want unless the project started out empty.

Another possibility (speculating) might be to have a "Flutter Android" module type that's almost like a Java module, and only allow it to be added to a Flutter module? I don't know if that's possible with IDEA's API.

**Comment by mit-mit** [comment]
@rxlabs can you elaborate on your use case for this? What is the relationship between the several Flutter "modules" that you would like in a single project?

**Comment by rxlabz** [comment]
@mit-mit since I use project as a workspace where I put all my linked modules. I can have one or more main Flutter projects, separated dart libraries, separated flutter libraries... each has it's own git repo, and they are not all in the same file tree. 

example :  here I have a main Flutter app project + a yzl_off_lib flutter library which I need ti keep separated, but which is handy to have in the same workspace. On the top I have a group of dart and flutter libraries modules that I use with in this project and in others...

Is it weird ? :)

![device_prefs_dart_-_yx017-protos_-____projects_ytbx017_protos_](https://cloud.githubusercontent.com/assets/1397248/26010138/091c1c70-374c-11e7-8fea-9126a52e49b2.png)

**Comment by alexander-doroshko** [comment]
I'd support @rxlabz. For those familiar with Eclipse terms: IntelliJ project is similar to Eclipse workspace, IntelliJ module is similar to Eclipse project. It's totally fine to have several projects in Eclipse workspace and it's totally fine to have several modules in IntelliJ project.

**Comment by rxlabz** [comment]
@mit-mit sorry my screenshot was not the best example. There is only one visible Flutter App module visible in the screenshot.
I know start porting another project Flex app in which I have a Teacher App, a Student App and shared libraries. In my mind, iIt will be 2 distinct Flutter App project modules, sharing some libraries, all in the same Intellij project. I hope I'm clear enough.
Of course I can create an Intellij project for each Flutter app, and then import them as modules in a global project, but I was surprised that this suddenly stop working.

**Comment by mit-mit** [comment]
Thanks for providing details, the makes a lot of sense!

**Comment by skybrian** [comment]
If we decide to support this we will have start doing additional testing, and probably change the `flutter create` command to have an option where it doesn't create the .idea directory.

Also the android.iml template should be renamed to something like projectName-android.iml.tmpl.

(And projectName is itself a misnomer here.)

**Comment by skybrian** [comment]
Creating multiple modules should work right in the next release.

Creating a Flutter module automatically creates an "Android" module to go along with it, but it will have a better name that should show the relationship.
