### ISSUE TITLE
Intellij IDEA does not create new project properly, java.io.IOException: CreateProcess error=5, Access is denied

### ISSUE THREAD

**Issue by claudfernandes** [flutter/flutter-intellij#1015]
## What happened

Creating a new Project on IntelliJ IDEA, it show me only 3 files f_demo7.iml, f_demo7.ipr, f_demo.iws.
But if I run Flutter create f_demo7 on the command line, it creates the project normally.

I am using Windows 10, and a new Flutter installation using master branch, and also run flutter doctor.

C:\Users\claud\Development\flutter>where flutter
C:\Users\claud\Development\flutter\bin\flutter
C:\Users\claud\Development\flutter\bin\flutter.bat

### Flutter Doctor result
```
Downloading android-arm-profile tools...              1.2s
Downloading android-arm-release tools...              1.1s
[√] Flutter (on Microsoft Windows [Version 10.0.14393], channel @u)
    • Flutter at C:\Users\claud\Development\flutter
    • Framework revision 2f590eccbc (6 hours ago), 2017-05-10 22:08:27 -0700
    • Engine revision f2581c9bcc
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\claud\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2016.2)
    • Dart plugin version 162.2924
    • Flutter plugin version 12.1

[√] Connected devices
    • ONEPLUS A3003 • a7cd8cad • android-arm • Android 7.1.1 (API 25)
```

## Version information

IntelliJ IDEA `2016.2.5` • Flutter plugin `12.1` • Dart plugin `162.2924`  * Windows 10

Error getting Flutter sdk information.

## Exception

Unable to start process to watch Flutter devices: Cannot run program "C:\Users\claud\Development\flutter\bin\flutter.bat" (in directory "C:\Users\claud\Development\flutter"): CreateProcess error=5, Access is denied

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\Users\claud\Development\flutter\bin\flutter.bat" (in directory "C:\Users\claud\Development\flutter"): CreateProcess error=5, Access is denied
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:358)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at io.flutter.run.daemon.DeviceDaemon$Command.start(DeviceDaemon.java:159)
	at io.flutter.run.daemon.DeviceService.chooseNextDaemon(DeviceService.java:187)
	at io.flutter.utils.Refreshable.runInBackground(Refreshable.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "C:\Users\claud\Development\flutter\bin\flutter.bat" (in directory "C:\Users\claud\Development\flutter"): CreateProcess error=5, Access is denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:368)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:354)
	... 11 more
Caused by: java.io.IOException: CreateProcess error=5, Access is denied
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 13 more
```

**Comment by claudfernandes** [comment]
I also run IntelliJ IDEA as admin, still the same error.

**Comment by mit-mit** [comment]
Your IDEA and Flutter plugins are a little our of date. Can you try with IDEA 2017.1 and Flutter plugin 13.1?

**Comment by claudfernandes** [comment]
I installed again, still got issues on it

-------------------------------------------------------
C:\Users\claud\Development\flutter>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], channel @u)
    • Flutter at C:\Users\claud\Development\flutter
    • Framework revision 2f590eccbc (7 hours ago), 2017-05-10 22:08:27 -0700
    • Engine revision f2581c9bcc
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\claud\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[√] Connected devices
    • None

Some screenshots
![flutter_error](https://cloud.githubusercontent.com/assets/7681091/25949323/0ce8e53e-364f-11e7-8a56-67c4bf5d4e58.PNG)
![flutter_error_1](https://cloud.githubusercontent.com/assets/7681091/25949324/0cf303b6-364f-11e7-81f5-2bfe37c41b28.PNG)


I will see if I can get the error message from this new version

**Comment by mit-mit** [comment]
Very odd, @pq @devoncarew any ideas?

**Comment by claudfernandes** [comment]
This might be related with this issue: https://www.java-forums.org/advanced-java/63494-java-io-ioexception-cannot-run-program-cmd-exe-createprocess-error-5-access-denied.html

I am unistalling java from my computer and reinstalling it again

**Comment by claudfernandes** [comment]
Ok, I solve the issue... it is not flutter or intellijIdea the issue. It has to do with the git version I have installed in my computer, that messes the permissions on flutter folder... I will attach some screenshots...

**Comment by claudfernandes** [comment]
![flutter_git_folder_creation](https://cloud.githubusercontent.com/assets/7681091/25950299/5cbc7bfe-3652-11e7-927a-1d4bc713162d.PNG)

![flutter_git_folder_creation_1](https://cloud.githubusercontent.com/assets/7681091/25950356/9dca2812-3652-11e7-9b3d-289d9581ada3.PNG)


The folder gets created, but doesn't allow me to execute the flutter.bat.

This ticket can be close... thanks for the help

**Comment by mit-mit** [comment]
Ah, great to hear! Just for future support cases: which version of git for windows caused this?

**Comment by claudfernandes** [comment]
It is a weird one:
I just reinstall https://git-scm.com/download/win

git version 2.8.3

I did two tests: I run git clone using Windows CMD.exe and also Git Bash.

![flutter_git_folder_creation_2](https://cloud.githubusercontent.com/assets/7681091/25951555/fa4423e2-3655-11e7-8ddb-b3c40996a0d9.PNG)

Git clone using CMD.exe doesnt work, while git bash works fine, no issues with permissions

**Comment by claudfernandes** [comment]
Using the folder created using git clone on "git bash". All works fine

![flutter_git_folder_creation_3](https://cloud.githubusercontent.com/assets/7681091/25951730/7442f2fe-3656-11e7-9666-9ab5ed972f9e.PNG)

**Comment by mit-mit** [comment]
Thanks!

**Comment by pq** [comment]
Wow.  Thanks @claudfernandes for all the thoughtful follow-up!

cc @alexander-doroshko as an FYI.
