### ISSUE TITLE
"Flutter create command was unsuccessful"

### ISSUE THREAD

**Issue by Timmmm** [flutter/flutter-intellij#1019]
## Steps to Reproduce

1. Start IntelliJ
2. Create a new Flutter project.
3. I get the following error message:

    Flutter create command was unsuccessful

Running `flutter create foo` from the command line works fine.

Who knows what this error is but it would definitely be better if it displayed the command output in the error message so I have a vague clue.

## Version info

```
[√] Flutter (on Microsoft Windows [Version 10.0.15063], channel alpha)
    • Flutter at C:\Users\Tim\Flutter\flutter
    • Framework revision dc4ca8db83 (3 days ago), 2017-05-11 15:33:29 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Tim\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[√] Connected devices
    • None

```

**Comment by Timmmm** [comment]
I believe this is related to #1020. When I created a new project, I had to type the SDK location in, rather than use the browse button because of that bug.

After the `Flutter create command was unsuccessful` error, IntelliJ still creates an empty project. If I then go into the Flutter settings, the SDK path is not filled in! I can fill it in there (this time the browse button works, although it is still way slower than the normal file->open browser; you must be doing something weird with it).

After filling in the SDK path there, when I go to create a new Flutter project it works and doesn't give me the `Flutter create command was unsuccessful` error.

**Comment by Timmmm** [comment]
Ugh, spoke too soon. It seems every time I close and delete previous Flutter projects, IntelliJ forgets the Flutter SDK location. So the only way to successfully create a project is:

1. Create a new Flutter project. It will fail, but will create an empty IntelliJ project.
2. Go to Settings->Flutter and set the SDK path (which will be blank).
3. Create a new Flutter project via File->New Project

Very odd.

**Comment by Timmmm** [comment]
Ok I found out what actually causes this. I don't think it is related to #1020 after all. **You get the error if your project name contains any capital letters.** Something totally crazy is going on there...

**Comment by pq** [comment]
Thanks @Timmmm.  Sorry for the confusion.  It turns out that `flutter create` is pretty defensive and does some draconian name validation.  Take a look at #1009 for a bit of discussion.  On the bright side, this is fixed and will be in the next release. 👍

**Comment by pq** [comment]
(duplicates #1009.)

**Comment by miniBloq** [comment]
I updated to Android Studio 3.3.1 in MacOS and there is no way I can create a new project with it.

**Comment by devoncarew** [comment]
@miniBloq, this is an old issue. Can you open a new one, with the output from `flutter doctor`, and any likely exceptions from the Android Studio logs? Thanks!

**Comment by shaiq-paracha** [comment]
Hey Everyone,
I'm facing an issue that the flutter create command was unsuccessful but I'm facing one more problem that is when I run command (Flutter Doctor) it show that android studio is not installed but I have installed it. I'm working on it for almost 2 days but can't resolve the issue.
