### ISSUE TITLE
Confusion around `pub get` prompt

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter-intellij#1026]
Sometimes, after updating pubspec.yaml in IntelliJ, we just see the Dart banner prompting to update dependencies. The Flutter banner w/ slightly different appearance and wording ("Get Dependencies") never displays. 

My understanding is the vanilla Dart version of the command (`pub get`) is not exactly equivalent to `flutter packages get` which aside from the UX inconsistency, might be a more serious issue. 

## Steps to Reproduce

1. Open pubspec.yaml, either in IntelliJ or in a text editor.
1. Make edits and switch to main.dart in IntelliJ.
1. Sometimes get Dart version of the "update dependencies" banner in IntelliJ, rather than the Flutter version (which is not exactly equivalent).

## Version info

This behavior was seen on the I/O kiosks.

flutter doctor output (from non-kiosk environment):
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision 7154ac48db (4 hours ago), 2017-05-16 09:32:27 -0700
    • Engine revision 6fef702cfa
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/jackson/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/jackson/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    • ios-deploy 1.9.1
    • CocoaPods version 1.0.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.1

[✓] Connected devices
    • iPhone 7 Plus • 5F90A4C3-6F80-446A-88CB-5394635BF8EF • ios • iOS 10.3 (simulator)
```

@collinjackson

**Comment by pq** [comment]
We made some improvements on this while back.  I'll do some investigating to see if we've regressed or just missed a case.

Thanks @LarkAscending !

**Comment by pq** [comment]
I'm puzzled by this one.

@alexander-doroshko: any ideas?

I thought we were short-circuiting this inspection entirely in `com.jetbrains.lang.dart.ide.inspections.DartOutdatedDependenciesInspection#checkFile` with this check:

    if (FlutterUtil.isFlutterPluginInstalled() && FlutterUtil.isFlutterModule(module)) return null;

Is it possible that in some situations (intermittently) the preceding attempt to get the associated module is returning null and this check is passing momentarily?

    final Module module = ModuleUtilCore.findModuleForFile(file, project);

**Comment by alexander-doroshko** [comment]
First of all, IntelliJ IDEA 2016.3.4 and Dart plugin 163.13137 are rather old. I don't remember whether that version contains this short-circuiting code.

`findModuleForFile()` is not known to be unstable.

**Comment by devoncarew** [comment]
> IntelliJ IDEA Community Edition (version 2016.3.4)

@LarkAscending, you'll definitely want to update your local IntelliJ - 2016.3 is older than we want - we want 2017.1 now as our minimum.

**Comment by collinjackson** [comment]
Should we update flutter doctor to require 2017.1? I think it's too late to update the IntelliJ on the kiosks which is where I was seeing this issue, but it should be helpful for people using Flutter at home.

For the code, we could tell them to click a link that says "packages get" or "dependencies get" if they see a banner. That should cover both bases.

**Comment by pq** [comment]
> Flutter plugin version 12.1

Is this what's in the kiosks?  I thought it was 13.1?

**Comment by devoncarew** [comment]
I very much hope (and assume) that 2017.1 is what's on the kiosks. That flutter doctor output above was not from a kiosk machine, but from Elaine's local machine.

+1 to updating flutter doctor do having a min version of 2017.1.

**Comment by collinjackson** [comment]
The test kiosk was a bit out of sync with the actual I/O kiosks so I think someone who has physical access to the codelab area will have to check this. I don't have a badge.

**Comment by LarkAscending** [comment]
Thanks for looking at this!  I am seeing it consistently on a new CE
2017.1.2 on Mac, Dart plugin 171.4424, Flutter plugin 13.1. The whole
Flutter/IntelliJ stack is maybe ~2 weeks old. That flutter doctor output
above is actually from @collinjackson (who sees it too).

   - We didn't give the I/O codelab team a specific version for IntelliJ in
   the spreadsheet.
   - It's new news that we require 2017.x or newer - if there's breakage
   maybe we should update flutter.io <https://flutter.io/intellij-setup/>
   w/this info?
   - At least for Ultimate Edition, it's not 100% possible to upgrade to a
   specific version. Don't know about WebStorm. CE should be more
   version-flexible.
   - Multiple Dart sources have mentioned that the 2 flavors of pub get are
   not equivalent.

I've got multiple machines. Seeing it also on Linux w/a software stack
that's a month old and IntelliJ Ultimate 2016.2.4. In that case both
banners show up.
Can provide detailed logs if that's helpful.

**Comment by devoncarew** [comment]
>   - It's new news that we require 2017.x or newer - if there's breakage
   maybe we should update flutter.io <https://flutter.io/intellij-setup/>
   w/this info?

Yup, we should - I'll open a PR. We _may_ also want to consider removing the explicit versions, and just say 'latest'?

**Comment by LarkAscending** [comment]
OK, but note that I'm seeing it on the newer version of CE as well.

**Comment by LarkAscending** [comment]
Another note: kiosks are running 2017.1.2

**Comment by pq** [comment]
Thanks for all the follow-up.  I can repro here.

**Comment by pq** [comment]
Ok, so this is embarrassing.  I think that the banner you're seeing is actually the one provided by us and does indeed do the right thing after all.  At one point, this had a flutter icon (and slightly different text) and so I was confused (cc @skybrian who may recall when that got swizzled around).

What's also interesting (and confusing) is that I'm seeing 2 notifications.  The banner at the top and an ephemeral toast at the bottom right.

![screen shot 2017-05-17 at 2 54 42 pm](https://cloud.githubusercontent.com/assets/67586/26177971/d4c0bc6a-3b10-11e7-9181-2b9bd8280d0c.png)

Feels like one too many?

cc @devoncarew

**Comment by LarkAscending** [comment]
This is the one we want to see. Instead, we often see the Dart banner, or
both banners.

Yes, I've also seen the prompt below, but not consistently.

**Comment by pq** [comment]
What may be confusing is that the Dart and Flutter banners appear to have the same text (making it hard to know which you've got!)

As for seeing them both, this was definitely a problem but should hopefully have been fixed a ways back.  With the latest Dart Plugin we shouldn't see them both _**ever**_; if we do though please shout!

**Comment by skybrian** [comment]
The toast is in ProjectOpenActivity and I ran across it while refactoring, but didn't rethink whether it's necessary. I think it used to happen only on project creation (import) until recently, and the check now happens on every project open.

**Comment by pq** [comment]
Circling back on this, I haven't been able to repro but want to revisit how confusing it is that these different banners are so easily confused.

Thoughts on rewording or adding (back) the Flutter icon for ours?

cc @devoncarew

**Comment by devoncarew** [comment]
We likely should be showing the flutter icon. Is that the issue, or that the pub one shows for flutter projects, and that we use both the editor notifications and the toast?

**Comment by pq** [comment]
Well, I think there may be a few problems.  The vanilla pub one really should never show for a Flutter project but am having a hard time reproducing.  That said, the icon will make things less confusing down the road so I can jump on that. 👍

**Comment by pq** [comment]
Hmmm...  Looks like I spoke too soon.  It doesn't appear we can add images to inspection problem descriptors.

Could you confirm @alexander-doroshko ?

For reference, here's what I'm trying to spruce up:

https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/inspections/FlutterDependencyInspection.java

If we want more control over presentation I'm guessing we'd need to go to an Editor Notification?  The downside of that I guess is that users couldn't disable the checks as you can w/ inspections.

![image](https://cloud.githubusercontent.com/assets/67586/26797892/67755d28-49e3-11e7-81a5-a25508099ca5.png)

(Or maybe that's not a bad thing?)

**Comment by alexander-doroshko** [comment]
You are right, no icon customization for inspections.
I do not think this reason is strong enough to switch to editor notification :).
I think if both Dart's and Flutter's bars look similar and never shown together then that's ok, it doesn't look like a usability problem to me.

**Comment by pq** [comment]
I'm not able to reproduce.  Optimistically closing; we can re-open if it reappears.
