### ISSUE TITLE
Using capital letters in a project name causes project creation fail

### ISSUE THREAD

**Issue by leafpetersen** [flutter/flutter-intellij#1027]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

File::New Project::Flutter::Next

Choose a project name that contains (or at least starts with) a capital letter, and an error message pops up saying that the flutter create command was unsuccessful, but with no further feedback as to why, or how to proceed from there.  See screenshot.

The project is created, but left in an unusable state (no files or created, and flutter doesn't seem to be properly set up).

## Version info

Tools > Flutter > Flutter Doctor doesn't exist, since flutter create failed... :)

But from a successfully built project (using all lower case):

```
/Users/leafp/codelabs/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel alpha)
    • Flutter at /Users/leafp/codelabs/flutter
    • Framework revision 00214fa7bd (4 hours ago), 2017-05-16 09:31:35 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[-] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Gradle not found.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    • Dart plugin version 171.4249.16
    • Flutter plugin version 13.1

[✓] Connected devices
    • iPhone SE • 97035729-7737-4C07-AF56-DB337A39D7C4 • ios • iOS 10.2 (simulator)

Process finished with exit code 0
```
<img width="689" alt="screen shot 2017-05-16 at 1 54 08 pm" src="https://cloud.githubusercontent.com/assets/8484504/26127879/9a7cb9ea-3a3f-11e7-9d91-cf91c182e8f4.png">

**Comment by pq** [comment]
The rub is that `flutter create` is pretty defensive and does some draconian name validation. Take a look at #1009 and #1019 for a bit more context.  The next plugin release will do the same validation so hopefully this confusion won't persist.

Thanks for the report @leafpetersen!

Duplicates https://github.com/flutter/flutter-intellij/issues/1019 and https://github.com/flutter/flutter-intellij/issues/1009.

**Comment by eseidelGoogle** [comment]
FYI @goderbauer (who added the defensiveness for windows) and @tvolkert who is our current flutter_tools owner.
