### ISSUE TITLE
Two versions popped up, both checked

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#1029]
I installed a new version of IntelliJ, which prompted me to install the Dart plugin. The IDE popped up this message:

<img width="1101" alt="screen shot 2017-05-16 at 4 16 18 pm" src="https://cloud.githubusercontent.com/assets/5479/26132769/53c6cd02-3a57-11e7-8d2e-8e86f62588ca.png">

I'd expect a single version of the plugin? Do I need both? They are both checked.

**Comment by sethladd** [comment]
I assume I want the second item?

**Comment by stevemessick** [comment]
@sethladd Yes, the second one is the latest. I do not know why you'd see two options here, though.

@alexander-doroshko Have you seen this?

**Comment by alexander-doroshko** [comment]
No, I didn't.

**Comment by devoncarew** [comment]
Closing - this looks like an IntelliJ platform bug.
