### ISSUE TITLE
Support the closing labels notification from the analysis server

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter-intellij#1034]
When a constructor is alone on a line, and there's a matching ) on another line, it would be really useful to see the constructor name on the margin of the line with the closing paren.

**Comment by mit-mit** [comment]
I had a customer request this today also. They said the bracket matching isn't enough when your code is long enough that it's scrolled out of view and is "above the fold".

**Comment by pq** [comment]
@alexander-doroshko : I wonder if you have any perspectives on this ask.  Are there any precedents  we can draw on?

**Comment by alexander-doroshko** [comment]
I may be not understanding the request correctly, can you please give an example?

Brace matcher already shows a first line if it is out of screen:
![image](https://cloud.githubusercontent.com/assets/4499789/26359114/3ee9a446-3fdd-11e7-804e-0d50a3154f55.png)

**Comment by pq** [comment]
So it does!

<img width="649" alt="screen shot 2017-05-23 at 7 42 05 am" src="https://cloud.githubusercontent.com/assets/67586/26359832/5adb930a-3f8b-11e7-8918-588bba9dc530.png">

@Hixie, @mit-mit  : looks like you need to move your cursor for that feedback.

Maybe we should promote this feature a little better in our docs?

**Comment by Hixie** [comment]
This is about when the cursor is nowhere near either parenthesis and you have twenty closing parentheses in a row, and you want to know which one matches what.

**Comment by Hixie** [comment]
(XML and HTML do this at the syntax level by requiring the closing parenthesis to have the name of the element they are closing. Bash does this to some effect to with "fi". Some people do the same with comments on every closing bracket.)

**Comment by pq** [comment]
Nice food for thought from vscode: #1252.

**Comment by devoncarew** [comment]
Updated this issue to specify supporting the new 'closing labels' notification from the analysis server. Note that the work for this would happen in the Dart plugin.

**Comment by devoncarew** [comment]
I'm going to close this as a dup of https://github.com/flutter/flutter-intellij/issues/1252.
