### ISSUE TITLE
Not clear what I'm about to run

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#1035]
I opened the flutter repo, which has many run targets. IntelliJ shows me it'll run main.dart. Which main.dart? Can we add some context to this label? Thanks for considering :)

![screen shot 2017-05-17 at 3 28 52 pm](https://cloud.githubusercontent.com/assets/5479/26178975/ace89e92-3b15-11e7-8782-9dae870feee3.png)

**Comment by mit-mit** [comment]
From the screenshot you opened just `flutter_gallery`?

**Comment by pq** [comment]
I'm not sure where the confusion is here.  There's only one `main.dart` in the gallery...

```
[~/src/git/clones/flutter/examples/flutter_gallery] (master) $ find . -path '*/main.dart'
./lib/main.dart
```

But maybe we can use a better label than the file name?

**Comment by mit-mit** [comment]
I suspect @sethladd just opened the wrong folder (thought he had opened all of flutter, but really opened just the gallery?). 

Seth, please reopen with more details if you are still seeing an issue.
