### ISSUE TITLE
locate sdks using the .packages file

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1039]
Similar to https://github.com/Dart-Code/Dart-Code/issues/294, if we're opening a project that has no Flutter SDK set, instead of using the last one set by a previous project for the sdk, we could check for the presence of a .packages file and use it to infer the flutter sdk location.

**Comment by pq** [comment]
I love this idea as it would also help in the case where _no_ SDK is set and could really smooth out the getting your first app running experience 👍 .
