### ISSUE TITLE
Have a move line up/down equivalent for widgets

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#1045]
consider a common pattern like
```dart
const A(
  a_prop: blah,
  child: const B(
    b_prop: blah,
    child: const C(
      c_prop: blah,
      child: [etc etc],
    ),
  ),  
),
```
if I realized that I need to flip the order of part of the tree, it would be great to be able to click on `B` press some key combo like shift-ctrl-up or something and have it automatically change it to
```dart
const B(
  b_prop: blah,
  child: const A(
    a_prop: blah,
    child: const C(
      c_prop: blah,
      child: [etc etc],
    ),
  ),  
),
```
since changes of this nature is so common and manual editing can get really messy and confusing when the ends of the build() can look like
![screen shot 2017-05-19 at 5 00 47 pm](https://cloud.githubusercontent.com/assets/156888/26270948/b9e61e62-3cb4-11e7-8f71-5d199e6e53ff.png)
and is mostly non-value-add busywork.

Would be extra awesome if they key combo can harmonize with the wrapping functionality (similar to the key combo modifier between move line up/down vs copy line up/down) so that a wrap can be like shift-ctrl-alt-up.

**Comment by pq** [comment]
cc @stevemessick

**Comment by scheglov** [comment]
This is called `Swap with parent` and `Swap with child`.

```dart
import 'package:flutter/material.dart';
main() {
  return new Padding(
    padding: const EdgeInsets.all(8.0),
    child: new Center(
      heightFactor: 0.5,
      child: new Text('aaa'),
    ),
  );
}
```

![image](https://user-images.githubusercontent.com/384794/36179092-d8694fae-10cf-11e8-98d8-521a9db7b642.png)

```dart
import 'package:flutter/material.dart';

main() {
  return new Center(
    heightFactor: 0.5,
    child: new Padding(
      padding: const EdgeInsets.all(8.0),
      child: new Text('aaa'),
    ),
  );
}
```

Or, with the same result:
![image](https://user-images.githubusercontent.com/384794/36179245-6f5c8eb2-10d0-11e8-9ffd-ef0c85d458c9.png)
