### ISSUE TITLE
Some ideas on project creation

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#1047]
Here are some ideas I've been thinking about when I walk through the wizard. I think you could get some pretty good bang for the buck on adding some options to the project creation process.  They may have been mentioned somewhere already.

I would suggest adding the creation options to the flutter creation wizard. I would add a few more too. 

![screen shot 2017-05-21 at 12 20 38 pm](https://cloud.githubusercontent.com/assets/1326504/26286808/8bab0656-3e22-11e7-8861-a96a53d00793.png)

**Comment by pq** [comment]
Great feedback.  Thanks @branflake2267 !

**Comment by pq** [comment]
Somewhat related to #535 (wrt to a flow for accessing examples).

**Comment by branflake2267** [comment]
Adding one more idea. I've seen discussion on this around too. 

The android package name, it would be quite nice to set this up in the beginning.

![screen shot 2017-05-22 at 6 51 08 am](https://cloud.githubusercontent.com/assets/1326504/26312171/9c2ce76c-3ebb-11e7-88f8-dcc9d1c89c47.png)

**Comment by branflake2267** [comment]
Any qualms? 

![screen shot 2017-07-22 at 4 30 43 pm](https://user-images.githubusercontent.com/1326504/28495220-859f75f8-6efb-11e7-9450-e20da02f75d8.png)

**Comment by pq** [comment]
This is landed.  Feel free to re-open for refinements.  Thanks again @branflake2267 !
