### ISSUE TITLE
Request to show @required parameters first in code completion.

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#1049]
From: https://github.com/flutter/flutter/issues/10219

If `@required` is present, we could show that first.

Thanks!

**Comment by pq** [comment]
I think it's an open question whether this is best done by sorting at the source level (at least that's what I'm advocating for...)

In any event, let's get this resolved this milestone either way. 👍

**Comment by zoechi** [comment]
related dart-lang/linter#676

**Comment by pq** [comment]
In flutter/flutter#10219, @InMatrix suggested:

> making required parameters more prominent and hard to miss will help users calm down when they deal with any non-required parameters.

Besides order, let's talk about how best to emphasize requiredness.  I see that the completion suggestion API in IDEA supports bold presentation (and italics and strike-through).  We can also add custom tail-text.  We currently don't add a tail for params:

![screen shot 2017-05-23 at 11 11 38 am](https://cloud.githubusercontent.com/assets/67586/26369209/d3468d64-3fa8-11e7-830e-b9bd7abb31e9.png)

but could.  For functions, we append type:

![screen shot 2017-05-23 at 11 12 40 am](https://cloud.githubusercontent.com/assets/67586/26369225/e0efb22e-3fa8-11e7-81d8-24f462c9bb33.png)

We could consider adding a parenthetical `required` tail to required methods?  Alternatively we might consider an icon (like the locks above).

cc @InMatrix @lukechurch @alexander-doroshko

**Comment by pq** [comment]
In flight:

![image](https://user-images.githubusercontent.com/67586/26986195-4b4bb79e-4cfb-11e7-9363-66f890d986d5.png)

https://codereview.chromium.org/2927343002/

👍

**Comment by pq** [comment]
Sort order is fixed in the analysis server.  If we want to further emphasize suggestions (e.g., style text or annotate with an icon), that will have to land in the Dart Plugin.
