### ISSUE TITLE
Android 3.0 Canary breaks Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#1050]
@lukef reports that installing Android Studio 3.0 canary breaks flutter.

@lukef can you paste your error or give more infos?  @devoncarew

**Comment by swavkulinski** [comment]
https://github.com/flutter/flutter/issues/10236

**Comment by lukef** [comment]
Adding here as the other issue seems different...

If using gradle plugin 3.0.0-alpha1 (gradle 4.0-milestone1) then you will get an issue like the following. Note: If you're coming from the previous 2.4 alphas, then keeping the plugin at 2.4.0-alpha7 (gradle < 4.0) will work.

```
Error:Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Failed to transform file 'flutter-x86.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file <build location>/build/app/intermediates/flutter/flutter-x86.jar does not exist.
```

Also quite often you have to first go into android studio to run the appropriate build process before being able to work in IntelliJ.

**Comment by eseidelGoogle** [comment]
Is this just a dupe of https://github.com/flutter/flutter/issues/10236?

**Comment by devoncarew** [comment]
Yes, looks like.

**Comment by apoorvbhatt14** [comment]
Error:Could not resolve all files for configuration ':app:debugAndroidTestRuntimeClasspath'.
> Failed to transform file 'core.jar' to match attributes {artifactType=android-classes} using transform JarTransform
