### ISSUE TITLE
code completion issue with names params and ternary expressions

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1055]
From a demo, we have an issue when completing the value for a named parameter with a ternary expression.

**Comment by pq** [comment]
@danrubel: curious if you've considered this case?  For example, you'd expect completions in the following:

![image](https://user-images.githubusercontent.com/67586/26997964-29c02d5c-4d33-11e7-9954-fd29a4a88734.png)

**Comment by pq** [comment]
@alexander-doroshko: I did some looking into this today and it looks like we're getting completion results in IDEA but they aren't getting presented.

![image](https://user-images.githubusercontent.com/67586/27052489-b2b6ec3a-4f6e-11e7-82bb-c2731399bba3.png)

Also interestingly, we can completion right after the named param, but when we're in the conditional we see nothing.

![jun-12-2017 13-01-41](https://user-images.githubusercontent.com/67586/27052735-84111954-4f6f-11e7-99a9-eee663c5cd05.gif)


Also note that this *does* work in function invocations so there's something specific about the constructor invocation case.

![jun-12-2017 13-14-35](https://user-images.githubusercontent.com/67586/27053138-22a5ec24-4f71-11e7-9ae6-2f60e9584bc3.gif)


Any thoughts greatly appreciated!

**Comment by alexander-doroshko** [comment]
[Here](https://github.com/JetBrains/intellij-plugins/commit/e7151e0f43bcd0b08960b19f591f21f09d2fd5a2#diff-4ce4cf29061284f6d68ae1a969905433) are those 5 magic chars that fix the issue!

**Comment by pq** [comment]
Fantastic.  Thanks a million!
