### ISSUE TITLE
Project creation: Name must have underscores and no camel case.

### ISSUE THREAD

**Issue by albrecht87** [flutter/flutter-intellij#1056]
## Create new Flutter Project in IntelliJ CE 2017.1 

There is no validation/mentioning, that the Project Name has to have underscores for separation.

<img width="947" alt="bildschirmfoto 2017-05-22 um 23 32 36" src="https://cloud.githubusercontent.com/assets/10848556/26329342/1ea04c80-3f47-11e7-84b6-a2de7b14c210.png">

Results in this message. 

<img width="388" alt="bildschirmfoto 2017-05-22 um 23 32 49" src="https://cloud.githubusercontent.com/assets/10848556/26329337/15f68874-3f47-11e7-981d-59a606cc7c45.png">

## Version info
Flutter Plugin 13.1

**Comment by pq** [comment]
Thanks for the report!  A fix for this will be in a fresh plugin release later this week.

(See #609.)
