### ISSUE TITLE
Cannot find Flutter plugin

### ISSUE THREAD

**Issue by nootfly** [flutter/flutter-intellij#1057]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
Go to preference - plugins - browser repositories

## Version info

IntelliJ IDEA (Community Edition) 2017.2 EAP
Build #IC-172.2273.8, built on May 18, 2017
JRE: 1.8.0_152-release-851-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

Please paste the output of running `flutter doctor` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
flutter doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel alpha)
    • Flutter at /Users/user/flutter/flutter
    • Framework revision 973304d5fb (4 days ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/44132848/flutter-plugin-issue-in-intellij-idea-17-2

**Comment by pq** [comment]
@zoechi is right.  (Thanks!)

We've got a bug to track that request open (#400) --- do feel free to chime in there.  Thanks for the report!

**Comment by thisisirfan** [comment]
Try updating your visual studio

**Comment by NguyenPhatBG** [comment]
Do Configure => Settings => Plugin instead of Configure => Plugin

**Comment by Elantaky** [comment]
just check out help> check for updates, and update , it will work

**Comment by Elantaky** [comment]
just check out help> check for updates, and update ,
then try to use plugin it will work
