### ISSUE TITLE
Project name validation for WebStorm.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1059]
As noted by @ksdboasit in https://github.com/flutter/flutter-intellij/issues/1058, the new project name validation code does not seem to apply to WebStorm.

> I tried the same in WebStorm (2017.1.3), and here there was no initial validation. It just failed to create the project when using an upper case letter.

@alexander-doroshko : we're using `io.flutter.module.FlutterModuleBuilder#validateModuleName` here; is there a better approach?  How do you recommend validating names for WebStorm project creation?

**Comment by alexander-doroshko** [comment]
AFAIR validation is done in `DartGeneratorPeer#validate`. PR is welcome or I'll fix it myself some day. Tracked as https://youtrack.jetbrains.com/issue/WEB-15525

**Comment by pq** [comment]
Thanks!

**Comment by pq** [comment]
Actually @alexander-doroshko , https://youtrack.jetbrains.com/issue/WEB-15525 is a little different.  We have even more draconian checks for Flutter projects and need to update `FlutterSmallIDEGeneratorPeer`.  Having said that, I wonder if you could advise.  Is there any way to get access to the project location during validation?  I tried caching `WizardContext` but it's not set and I can't see any other way to access the project name.

Thanks in advance for any pointers!

**Comment by alexander-doroshko** [comment]
Thanks for investigation! Then I'm afraid I do not know. If you can't control WebStorm project name you can normalize it when using it as a Flutter project name.

**Comment by pq** [comment]
@alexander-doroshko : could you elaborate?  I'm not quite sure what you mean by normalizing and not sure when we would do it.  Thanks!

**Comment by alexander-doroshko** [comment]
Do you call a flutter tool to generate sample project content? Does it take a Flutter project name as a parameter or it simply uses the current folder name? In the former case you have a control on the Flutter project name (but not on IntelliJ project name or on folder name).

**Comment by pq** [comment]
Yes.  We do call out to `flutter create`.  It hadn't occurred to me to allow for the project and folder names to be different (since that seems potentially confusing) but I guess it's an option.  Thanks!
