### ISSUE TITLE
display error messages from flutter create when project creation fails

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1064]
Repro steps:

This was found on Windows; I suspect this will rarely happen elsewhere

1. make sure git is not in path
1. file > new project

=>

![image](https://cloud.githubusercontent.com/assets/13644170/26369952/8d8a1478-3ff6-11e7-8450-ab1f0ec913b6.png)

From the command line:
```
C:\Users\mit\tmp>flutter create test2
Error: Unable to find git in your PATH.
```

Shouldn't we be printing that error message also in IJ?

**Comment by devoncarew** [comment]
> Shouldn't we be printing that error message also in IJ?

Yup! We should do.

**Comment by pq** [comment]
We can clean things up but #1081, ensures we don't miss anything useful by reproducing _all_ of stderr.  For example, here's an example where flutter_tools falls over entirely.

![image](https://cloud.githubusercontent.com/assets/67586/26512990/f13782de-421d-11e7-88df-1fdedbaf6d64.png)

A little crude but hopefully only encountered infrequently and at least we have lots of context around the failure.
