### ISSUE TITLE
Auto compete an empty event handler

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#1066]
## Steps to Reproduce

This issue might be specific to IconButton but can use a general fix. When the IconButton's onPressed handler is null, the Icon is grayed out because it's in an inactive state. We've observed that some users' initial reaction was to change the color of the icon, which won't work as long as the event handler is still null. How about we automatically insert an empty function after `onPressed`? 

So instead of `new IconButton(icon: new Icon(Icons.ac_unit), onPressed: null)`, the user will have `new IconButton(icon: new Icon(Icons.ac_unit), onPressed: (){})`, and their icon will be in the color it's supposed to be.

**Comment by eseidelGoogle** [comment]
FYI @Hixie

**Comment by Hixie** [comment]
Already done, see https://github.com/flutter/flutter-intellij/issues/975 :-)

**Comment by InMatrix** [comment]
Nice!
