### ISSUE TITLE
Finished with error: Exception: Unable to locate gradle. Please install Android Studio.

### ISSUE THREAD

**Issue by savita79984** [flutter/flutter-intellij#1070]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

When i am running the build on Intellij idea, it always shows this exception. In their any need to install android studio ?

## Version info

Please paste the output of running `flutter doctor` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by pq** [comment]
Hi @savita79984.  What action are you performing when you see this exception?

**Comment by mit-mit** [comment]
Closing due to lack of customer response.

**Comment by Teovald** [comment]
Got the same issue after installing the flutter sdk @mit-mit

**Comment by Teovald** [comment]
flutter doctor : 

~/code/flutterapps/untitled > flutter doctor                                                                                                                                                     <11:58:45>
[✓] Flutter (on Mac OS X 10.11.6 15G1510, locale en, channel alpha)
    • Flutter at /Users/francois/code/flutter
    • Framework revision d36e2f6191 (13 days ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/francois/Developer/android-sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/francois/Developer/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_66-b17)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew update
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew update
        brew install cocoapods
        pod setup

[✗] Android Studio (not installed)
    • Android Studio not found. Download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Nexus 6P • CVH7N15B04004491 • android-arm • Android 8.0.0 (API 26)

**Comment by Teovald** [comment]
note : I have 3 different versions of AS installed on my system (2.3, 2.4-alpha6, 3.0 alpha 5)

**Comment by Teovald** [comment]
either launching the app in intellij or from the command line results in : 

~/code/flutterapps/untitled > flutter run                                                                                                                                                        <11:58:40>
Launching lib/main.dart on Nexus 6P in debug mode...
Unable to locate gradle. Please install Android Studio.

**Comment by mit-mit** [comment]
I think that has been fixed as a result of https://github.com/flutter/flutter/pull/10928. Unfortunately that change is recent enough that it hasn't made it to the `alpha` channel yet. You could try to run `flutter channel master` followed by `flutter upgrade` followed by `flutter create testapp` and see if that resolves it. To switch back to your current alpha channel, run `flutter channel alpha`.

**Comment by Teovald** [comment]
Yup, it works just fine now.  
It's great that you have switched to the wrapper

Thanks !
