### ISSUE TITLE
Dartdoc links don't work

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1083]
## Steps to Reproduce

1. Create new Flutter project
1. Go-to-decl on `new FloatingActionButton`
1. Place cursor inside `[RaisedButton]` in the top Dartdoc comment, and Go-to-decl

=> Complains 'Cannot find a declaration to go to'

**Comment by pq** [comment]
It looks like we're seeing this for vanilla Dart projects as well.

![image](https://cloud.githubusercontent.com/assets/67586/26607019/36baa25e-4549-11e7-958a-0a3904040eeb.png)

@alexander-doroshko @jwren : any thoughts?  Is this a regression?

**Comment by alexander-doroshko** [comment]
Not a regression, it never worked. Tracked as https://youtrack.jetbrains.com/issue/WEB-26751. Unfortunately no ETA at the moment. We may get closer to the fix during angular plugin integration work.

**Comment by pq** [comment]
Thanks for confirming @alexander-doroshko !

**Comment by alexander-doroshko** [comment]
Fixed in the Dart plugin

**Comment by devoncarew** [comment]
Thanks!

(eta is the next release of IntelliJ - 2017.1)
