### ISSUE TITLE
Packages get doesn't handle nested packages

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter-intellij#1092]
## Steps to Reproduce

1. I cloned [flutter/plugins](https://github.com/flutter/plugins).
2. I opened `packages/firebase_database` in IntelliJ.
3. I got analysis errors after running `packages get`:

<img width="770" alt="screen shot 2017-06-05 at 8 22 20 pm" src="https://cloud.githubusercontent.com/assets/168174/26812465/b8034310-4a2c-11e7-88b6-7a9b031f3a48.png">

I attempted to fix this by double clicking on `example/pubspec.yaml` and hitting `packages get`, but based on the terminal prompt (`Running 'flutter packages get' in firebase_database...`), it looks like it just ran on the root, not the nested package. Right clicking on `example/pubspec.yaml` and clicking `Flutter > Packages Get` did the same thing.

I ended up having to navigate with the command line to resolve this analysis warning.

## Version info

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel alpha)
    • Flutter at /Users/matanl/git/flutter
    • Framework revision 00214fa7bd (3 weeks ago), 2017-05-16 09:31:35 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/matanl/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.3)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[✓] Connected devices
    • None
```

**Comment by pq** [comment]
cc @alexander-doroshko

**Comment by pq** [comment]
Ah, talking to @devoncarew, this looks like a bug on our end.  We're not handling nesting when calling out to `flutter packages get`.

**Comment by matanlurey** [comment]
👍 Thanks @pq and @devoncarew!

**Comment by mit-mit** [comment]
Isn't this https://github.com/flutter/flutter/issues/10015 ?

**Comment by devoncarew** [comment]
This issue is more that IntelliJ wasn't using the closest nested pubspec.yaml. That one is that the command-line dartanalyzer doesn't use the same context creation logic as the analysis server (and the analysis server is the one we want to emulate here).
