### ISSUE TITLE
IDE starts showing ADB not responding

### ISSUE THREAD

**Issue by zringlelabs** [flutter/flutter-intellij#1097]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Connect Android Phone through ADB and install app from the IDE

When doing a hot reload or complete install of app, the IDE throws a message "ADB Not responding" and happens quite frequently.

## Version info

Please paste the output of running `flutter doctor` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by eseidelGoogle** [comment]
Can you add your output from `flutter doctor`?  It's interesting to know what version of the Android toolchain you have, as well as what operating system, etc.  All of that would be covered by the `Tools > Flutter > Flutter Doctor` output.

**Comment by pq** [comment]
Closing as dup of #1096; feel free to re-open if you feel otherwise!
