### ISSUE TITLE
Indentation is wrong

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1098]
## Steps to Reproduce

1. Create new app
1. In `body: Center(...)`, change `child:...` to just  `child: ,`
1. After `child:` type `Pad` and accept the completion
1. Place cursor after `Padding(` and hit enter
1. Cursor is placed too far in!
1. Try to move it back with backspace; it goes to the previous line!

**Comment by alexander-doroshko** [comment]
I think it's already fixed at least in 2017.2 EAP + corresponding Dart plugin

**Comment by mit-mit** [comment]
Ah, great. @pq I'd like to have a tag for bugs that need to be validated once we get new drops of IJ/Dart plugin. WDYT?

**Comment by pq** [comment]
SGTM!
