### ISSUE TITLE
Trouble converting positional argument to named argument

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#1100]
Consider a constructor `A({this.b, this.c})`

If while coding, I wrote `new A([some instance of b type], [some instance of c type])` forgetting that they're named, doing an autocomplete right after new A( doesn't yield any choices. 

Would be nice if it just suggested to add `b:` recognizing that what came after it is of type b.

**Comment by pq** [comment]
Relatedly (or alternatively), it might be nice to add assists in this case.  At the moment, we don't help at all:

![image](https://user-images.githubusercontent.com/67586/26984559-aa93c162-4cf4-11e7-9973-c7720a327199.png)

cc: @bwilkerson @danrubel @scheglov

**Comment by bwilkerson** [comment]
Agreed. Both a fix for the error and completion help would be good to have.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/42860

**Comment by scheglov** [comment]
Ah, I forgot to close the issue.
