### ISSUE TITLE
Assert doesn't autocomplete in constructor initializer

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#1101]
Consider
```dart
A({
  bool a,
  this.b
}) : assert( <- autocomplete here
```

No options appear though both `a` and `b` are valid choices.

**Comment by pq** [comment]
Good catch!

@danrubel : have you looked at this case?

**Comment by pq** [comment]
Confirmed this is still an issue.

![image](https://user-images.githubusercontent.com/67586/31735717-9fac04fc-b3f7-11e7-9ac2-27cb3ab9ffd2.png)

/cc @danrubel

**Comment by danrubel** [comment]
I've been swamped with CFE work and have not had time to dig into this yet.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/40472
