### ISSUE TITLE
Create an initial "Open inspector" action

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1104]
A minimal action to integrate with the initial on-device visual inspector.

cc @jacob314

**Comment by mit-mit** [comment]
Let's put this somewhere not too prominent initially.

**Comment by pq** [comment]
_**UPDATE:** this is hinging on work in flutter proper._

The first enabling PR to watch is https://github.com/flutter/flutter/pull/11147; after that we'll need a change to take advantage of the offstage information in the diagnostics to perform better hit testing.

**Comment by pq** [comment]
PR to watch: https://github.com/flutter/flutter/pull/10332 (_Bare bones widget inspector support_).
