### ISSUE TITLE
When using auto assist to fill possible properties, filter the possible types

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#1107]
When filling in widget properties, and they are expecting an a specific type, such as an enum, it would be really nice and much faster if filtered the types and suggested those as the options. It's pointless to have the entire type list on auto assistance. And to find the type it expects I have to climb into the super class every time.  

Bonus points if you can add the dart docs to the right when hovering over the type options. This is another activity that consumes much time figuring which each option does. 

## Steps to Reproduce

1. Add the property name such as `Wrap.direction` property. 
2. Look at the list it auto suggests. (control + space)

![screen shot 2017-06-14 at 9 38 45 pm](https://user-images.githubusercontent.com/1326504/27165632-1d6f1a98-514a-11e7-92c9-e4930c230d46.png)

Possible List:
```
Axis.horizontal
Axis.vertical
```

## Version info

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision 6f77b4a9a7 (4 hours ago), 2017-06-14 17:27:08 -0700
    • Engine revision 18fdfb86bb
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • iPhone 7 • 458BC4FE-8205-4369-8718-193B9FC88C8B • ios • iOS 10.3 (simulator)

```

**Comment by branflake2267** [comment]
Workaround, while typing property, look at the type...
![screen shot 2017-06-14 at 9 51 41 pm](https://user-images.githubusercontent.com/1326504/27165859-b7fe0b9a-514b-11e7-8459-7da1b7ca5d53.png)

**Comment by devoncarew** [comment]
We could probably improve filtering / sorting here, but keep in mind that you could be completing the first part of an expression that results in the right type. So, `foo.bar.baz` where baz is the right type, or `super.bar`, ...

**Comment by branflake2267** [comment]
It sounds like I may be missing something, are you saying it could be completing some type automatically, and if that's the case, I haven't seen that behavior. Just a thought, that's more aggressive than the other editors I've worked with, but so far it's been convenient with the children for instance. 

I'm used to Eclipse where it will filter based on the parameter type and it helps quite a bit if you're new to the api, or even use it often. 

I'm sure you've seen this and I like how it works better.  Here's what it looks like, let's say I have a constructor with a keyProvider parameter. 
```
public ListStore(ModelKeyProvider<? super M> keyProvider) {
```
So when I look to instantiate the type, and aim to fill in the parameters I look to have auto assist provide the options, narrow them down. So here's what auto assist looks like in Eclipse when I use control space. It feels like it filters the list, or it may just be pre-pending the `ModelKeyProvider` to the top of the list the type of the parameter in the constructor.  And the second half of the view to the right, shows the javadocs, which is a bonus. 

![screen shot 2017-06-15 at 8 07 39 am](https://user-images.githubusercontent.com/1326504/27188151-26439fce-51a2-11e7-9211-759dcad725d3.png)

**Comment by branflake2267** [comment]
Here are a couple more cases where filtering by type inference would be useful. 

1. Instantiating with left type declared
![screen shot 2017-06-17 at 10 15 40 am](https://user-images.githubusercontent.com/1326504/27254847-228541bc-5346-11e7-913f-47f09f17d95d.png)

2. Instantiating when nesting
![screen shot 2017-06-17 at 10 15 55 am](https://user-images.githubusercontent.com/1326504/27254850-2e28e762-5346-11e7-8982-6587c570cef4.png)

3. I'd call this a deductive reference, when working backwards. 
![screen shot 2017-06-17 at 10 18 15 am](https://user-images.githubusercontent.com/1326504/27254858-58fd80ba-5346-11e7-957e-6993672a8a93.png)

**Comment by branflake2267** [comment]
Maybe filtering is a bad way to do it. Instead inferring the argument type, and pre-appending it to the top of the list as the first option is better.

**Comment by pq** [comment]
cc @danrubel

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/52863 switches to prioritizing relevant types.

**Comment by branflake2267** [comment]
Nice job!
