### ISSUE TITLE
Quickly right click and surround code with...

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#1109]
Add surround with to the right click context menu. Shorten the path to adding a try catch to source code. 

![screen shot 2017-06-17 at 10 55 26 am](https://user-images.githubusercontent.com/1326504/27255100-ba3b96aa-534b-11e7-8538-3fe0a611edb9.png)

**Comment by alexander-doroshko** [comment]
Use Alt+Enter, the action is there, it is much faster than right-click :).
Well, if you love using mouse, click the bulb.
![image](https://user-images.githubusercontent.com/4499789/27255190-de37ce06-53a1-11e7-9be1-6dc93f236371.png)

I'm not speaking for the Flutter team, I'm from JetBrains. And in JetBrains we are strongly against adding intention actions and quick fixes to the right-click menu.
My $0.02.

**Comment by branflake2267** [comment]
Hm, nice. That works for me. 

![screen shot 2017-06-17 at 11 18 20 am](https://user-images.githubusercontent.com/1326504/27255221-b8e9dd4a-534e-11e7-8a79-bc0f2b7a5a4c.png)

**Comment by alexander-doroshko** [comment]
![image](https://user-images.githubusercontent.com/4499789/27255405-c43723b2-53a6-11e7-981b-083afe9f9992.png)
