### ISSUE TITLE
Import quick-fix doesn't obey import order

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#1119]
I used the import quickfix `Import library 'package:flutter/services.dart'`, which resulted in the following analyzer warning:

```
info: Place 'package:' imports before relative imports. (directives_ordering at [flutter] lib/src/widgets/gesture_detector.dart:11)
```

Import section after quick-fix:
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/rendering.dart';

import 'basic.dart';
import 'framework.dart';
import 'package:flutter/services.dart';
```

Would be nice if the import quickfix would add the import at the right position to not trigger an analyzer warning.

(not super-high priority, but nice-to-have )

**Comment by pq** [comment]
@scheglov : I thought we did this already...  Or?

**Comment by scheglov** [comment]
Yes, I'm pretty sure we already put newly imported libraries at correct positions.

**Comment by pq** [comment]
Hmmmm.  Confirmed that this does NOT appear to be working as expected.

![jun-26-2017 09-21-55](https://user-images.githubusercontent.com/67586/27549487-f13f1792-5a50-11e7-89a9-ba08f68fb355.gif)

Perhaps a regression somewhere?

cc @alexander-doroshko @jwren

**Comment by pq** [comment]
@scheglov : if the gif doesn't provide enough context, I can demo in person...

**Comment by scheglov** [comment]
OK, thanks, I can reproduce the problem.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2955913002

**Comment by pq** [comment]
Thank you!

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/a2f18fdb7324b3d49c9d43023bd67ab148aa18d6
