### ISSUE TITLE
Flutter test support conflicts w/ running VM tests.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1128]
Trying to run Dart tests for a simple console app

![image](https://user-images.githubusercontent.com/67586/27563930-4fde1eaa-5a89-11e7-9b7b-0308170a4e16.png)

yields an error that a Flutter SDK is not set,

![image](https://user-images.githubusercontent.com/67586/27563895-1cddc046-5a89-11e7-877c-d5321941f1c2.png)

(but one shouldn't be required for a Dart console app).

cc @skybrian

**Comment by devoncarew** [comment]
This is something we'll want to fix before shipping M15.
