### ISSUE TITLE
validate the behavior of running flutter test from IntelliJ on windows

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1137]
`flutter test` is not supported on windows; we should validate that we either don't offer to run flutter tests on windows, or that we fail in a reasonable way.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/8516 is the bug tracking windows support for `flutter test`.

**Comment by devoncarew** [comment]
The current behavior in IntelliJ is reasonable:

```
C:\projects\flutter\flutter\bin\flutter.bat --no-color test --machine test\pesto_test.dart
Testing started at 2:25 PM ...
The test command is currently not supported on Windows: https://github.com/flutter/flutter/issues/8516
```
