### ISSUE TITLE
Create a manual testing doc.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#114]
While trying to debug the deployed plugin to track down the NPE in #109, I was hit with the fact that the plugin is not compatible with my installed EAP.  The rub is I need to test against the latest "stable" which from looking at the gradle build is: "IntelliJ IDEA 2016.2.3 / Build #IC-162.1812.17".  It would be good to add this to a testing doc.

@devoncarew : is this how you're testing?  DO you have a (now old) IDEA 2016.2.3 around that you test against?  I'm probably being thick but do you have a download link?

**Comment by devoncarew** [comment]
+1 to a testing script (here's a nice sample one: https://github.com/Microsoft/vscode/wiki/Smoke-Test)

I am using IntelliJ CE to test - d/l'ed from here: https://www.jetbrains.com/idea/download/.

**Comment by pq** [comment]
As per our discussion, the user journey's doc will serve double-duty as our test script.

**Comment by devoncarew** [comment]
Done?
