### ISSUE TITLE
in the new project wizard, we should always show the 'install sdk' action

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1145]
In the new project wizard, we should always show the 'install sdk' action. When it's not applicable, we might choose to do something like disable/enable the link.

**Comment by pq** [comment]
#1169 plays with enablement as a cue (keeping the action visible always).

Disabled looks like:

![image](https://user-images.githubusercontent.com/67586/27874492-92a20c10-6164-11e7-9dd5-e2f362b45895.png)

vs. enabled like so:

![image](https://user-images.githubusercontent.com/67586/27874503-9decaa9e-6164-11e7-84d1-11c96931b69f.png)
