### ISSUE TITLE
Font used for Flutter setup status messages is hard to read

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1148]
The font used for Flutter setup status messages is hard to read, and looks a little out of place:

![image](https://user-images.githubusercontent.com/13644170/27680384-cb0bb6d0-5cbb-11e7-98e5-4f7ee92874e5.png)

Maybe Windows specific?

**Comment by mit-mit** [comment]
cc @pq

**Comment by pq** [comment]
Oh wow.  That does look terrible.  Thanks for the catch.  I'll take a look. 👍

**Comment by mit-mit** [comment]
I'd recommend switching to Comic Sans 😄
