### ISSUE TITLE
IntelliJ should query flutter_tools for the Android sdk location (and use it when launching android emulators)

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1150]
In latest release candidate from last night: I don't get the new Start Android emulator actions:

![screen shot 2017-06-29 at 11 26 33](https://user-images.githubusercontent.com/13644170/27680959-d6d56428-5cbd-11e7-8b78-f62abeb3ff36.png)

Repros on both macOS and Windows.

**Comment by pq** [comment]
What happens if you do this in a console?

```
> echo $ANDROID_HOME
> $ANDROID_HOME/tools/emulator -list-avds
```

**Comment by devoncarew** [comment]
@mit-mit, it's likely the lack of `ANDROID_HOME`. This is a known limitation of the technique we're currently using. I think we should update the known issues list, and plan to improve the android sdk location (use flutter_tools) for the following release.

**Comment by mit-mit** [comment]
Yes, confirmed that is unset. But why would it be set? I don't see it in our install instructions?

**Comment by devoncarew** [comment]
Probably a good note for when we update the known issues.

**Comment by devoncarew** [comment]
Refactoring this issue to be about querying flutter tools for the android sdk location.

**Comment by devoncarew** [comment]
Note: flutter_tools now supports a `flutter config --machine` option
