### ISSUE TITLE
No Android Emulators in Dropdown

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#1160]
Hello! I was excited to use the new Android Emulator dropdown, but when I first tried it, it didn't work...

## Steps to Reproduce

  1. Download the latest version of the plugin with IntelliJ CE & restart
  2. Oh no! No android emulators show up
  3. Dig through PRs and find this reference to `ANDROID_HOME`: https://github.com/flutter/flutter-intellij/pull/1140/files#diff-ea5ca6788a3794828791e5cb1ef0af2fR203
  4. Realize I'm on a new machine where that isn't configured 
  5. Set it in my `.zshrc` and restart IntelliJ
  6. Profit! (Aka Emulators show up)

## Summary

So, the problem was that I didn't quite have my `ANDROID_HOME` set, but all I saw as a user was a silent failure. Once I configured it, everything ran smoothly.

**Comment by devoncarew** [comment]
Thanks for the report! It's a known issue - with a workaround - but something many users will encounter. We have plans to address :)

Closing in favor of https://github.com/flutter/flutter-intellij/issues/1150.
