### ISSUE TITLE
Project templates should include unit tests

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1171]
In order to help users get going writing unit tests we'd like to get them started w/ templates in newly created projects.  Ideally this might be done in `flutter create`.  Note that there's a correlated issue tracking integration tests (#1172).

**Comment by pq** [comment]
As a straw-man, I'd propose cribbing from the source in the tutorial:

https://flutter.io/testing/#unit-testing

cc @Hixie @devoncarew 

fyi @LarkAscending

**Comment by devoncarew** [comment]
+1 to adding a sample test to the `flutter create` template - having a pattern to copy will help out with getting started with flutter tests / testing

**Comment by pq** [comment]
Fixed w/ https://github.com/flutter/flutter/pull/11304.
