### ISSUE TITLE
Project templates should include integration tests 

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1172]
In order to help users get going writing integration tests we'd like to get them started w/ templates in newly created projects. Ideally this might be done in `flutter create`. Note that there's a correlated issue tracking unit tests (#1171).

**Comment by pq** [comment]
Like #1171, we might look to our docs (https://flutter.io/testing/#integration-testing) for inspiration.  (Note that this would introduce a dev dependency on `flutter_driver` into the template project.)

@Hixie @devoncarew @LarkAscending for thoughts.

**Comment by pq** [comment]
Flutter "drive" test templates are currently generated w/ the `--with-driver-test` option to `flutter create`.

If we want to generate this content by default, we could just pass that argument when we call `flutter create` during project creation.  Alternatively we could consider a checkbox.  If we did that we might consider allowing for configuration of other options to create:

```
Usage: flutter create <output directory>
-h, --help                     Print this usage information.
    --[no-]pub                 Whether to run "flutter packages get" after the project has been created.
                               (defaults to on)

    --[no-]with-driver-test    Also add a flutter_driver dependency and generate a sample 'flutter drive' test.
    --[no-]plugin              Generate a Flutter plugin project.
    --description              The description to use for your new Flutter project. This string ends up in the pubspec.yaml file.
                               (defaults to "A new Flutter project.")

    --org                      The organization responsible for your new Flutter project, in reverse domain name notation.
                               This string is used in Java package names and as prefix in the iOS bundle identifier.
                               (defaults to "com.yourcompany")

-i, --ios-language             [objc (default), swift]
-a, --android-language         [java (default), kotlin]
```

**Comment by devoncarew** [comment]
`--plugin` is a different project type, so may map well to a selector or a different project wizard

Generally, I'd say the fewer options the better.

We could choose not to generate driver tests in the wizard (or have an option for that), and instead have a 'create driver test' action exposed somewhere.

/cc @mit-mit

**Comment by devoncarew** [comment]
Moving out of M17.

@pq, when you get back, could you triage this? It seems like there are a few items here, like adding driver tests to the template project, removing the option to generate unit tests from `flutter create` (and having the tool just always generate unit tests), ...

**Comment by mit-mit** [comment]
I'm not entirely sure always generating all test content by default is a good idea; we already have an overwhelming amount of files in the new project that new developers need to understand.

**Comment by Hixie** [comment]
I think we should encourage our developers to write tests. Having one test file always be included would go a long way towards encouraging that culture, I think.

**Comment by pq** [comment]
@devoncarew:

`flutter create` generates the unit test sample w/o arguments so we're good there.

As for driver tests, they can optionally be generated by specifying the `with-driver-test` option.  Given that we're not completely there with respect to supporting driver test runs from the IDE (#1223) this feels reasonable for now.

**Comment by devoncarew** [comment]
`flutter create` now includes a test; closing this.
