### ISSUE TITLE
Add test annotations to the structure view

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1175]
Related to #1174, we should explore adding test annotations to the structure view a la JUnit:

![image](https://user-images.githubusercontent.com/67586/27887479-d56b6920-6195-11e7-9387-deaf5a9e15cb.png)

**Comment by pq** [comment]
@alexander-doroshko : is there an extension point that allows for contributions along these lines or does it have to happen in the structure model (e.g., `DartStructureViewElement` or somewhere there abouts)?

**Comment by pq** [comment]
It looks like this needs to happen at the Dart Plugin level (most obviously in `AbstractDartComponentImpl#doOverlays`) unless there's some way to decorate Psi Elements via an extension point that I'm not seeing?

**Comment by alexander-doroshko** [comment]
Dart plugin in 2017.3 has switched to Structure View powered by the Analysis Server, which provides test group and test nodes.

**Comment by devoncarew** [comment]
👍
