### ISSUE TITLE
Improve Flutter test console output.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1176]
The observatory link should open a browser on the given URL:

![image](https://user-images.githubusercontent.com/67586/27887944-2f3d98cc-6198-11e7-87d6-fa22b0cff7b9.png)

**EDIT**: full output also includes a line like:

    [{"event":"test.startedProcess","params":{"observatoryUri":"http://127.0.0.1:51770/"}}]

**Comment by devoncarew** [comment]
I think we should elide this text - with this launch config, users will be debugging from the IDE.

Do you know if the text is coming from package:test or `flutter test`? I'm wondering if we can add a cli flag to just not print it out to begin with.

**Comment by pq** [comment]
Great points.  I'm not sure but will rejigger this issue to track console output improvements in general and investigate. 👍

**Comment by pq** [comment]
This is the command we exec

    flutter --no-color test --machine --start-paused test/unit_test.dart

It seems `--machine` should suppress that output?

FWIW, here's the comparable output when we debug a Dart test:

![image](https://user-images.githubusercontent.com/67586/28172457-6e53d888-67a0-11e7-879d-9fd1de568c54.png)

**Comment by pq** [comment]
After some investigating, I think there are two independent steps:

1. update flutter_tools to silence debug status output when in machine mode (https://github.com/flutter/flutter/pull/11228)
1. fix our test event processing in IDEA to elide the observatory port JSON from output
