### ISSUE TITLE
Provide a Flutter plugin for Android Studio

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#1186]
Targeting alpha version of Android Studio, i.e. the version currently under development.

- [ ] New Project must allow creating Flutter projects
- [ ] New Module must allow creating Flutter packages and plugins
- [ ] New File may be extended with first-class Dart file creation
- [ ] The Welcome screen allows creating AS projects, so should also allow Flutter

If the New Project wizard is modified to support Flutter then no additional work needs to be done to fix New Project on the Welcome screen.

The New Module wizard allows choosing from many types of modules. It is likely best to add two new types for Flutter.

**Comment by mit-mit** [comment]
@stevemessick can we mark this complete?

**Comment by stevemessick** [comment]
Yep!
