### ISSUE TITLE
IntelliJ IDEA supports adding additional Dart and Flutter modules to existing projects

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#1188]
When a Flutter plugin is created it contains a sample application that shows how to use it. The sample app should be a separate module, and should appear as such in IntelliJ Ultimate. In general, it should be possible to add additional modules to an existing project. IntelliJ Ultimate supports this, but it is obscure and could probably be simplified for our uses.

IntelliJ CE and Android Studio do not support multiple modules in a single project so a different approach will be required.

**Comment by pq** [comment]
@stevemessick : are you still looking at this?

**Comment by stevemessick** [comment]
Obsolete.
