### ISSUE TITLE
no error when I selecting an invalid flutter sdk dir

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#119]
From the flutter settings page, when I selected an invalid directory for a flutter sdk, I didn't get any feedback telling me I'd selected a bad dir; my selection just wasn't populated in the sdk path field.

**Comment by pq** [comment]
What product?

When I try this in a CE runtime workbench I see:

![screen shot 2016-09-26 at 10 45 31 am](https://cloud.githubusercontent.com/assets/67586/18845393/7b020932-83d6-11e6-8fa1-26c2ada3e754.png)

**Comment by devoncarew** [comment]
Hmm, will close this and re-open if I can repro.
