### ISSUE TITLE
FR: dartfmt on save support

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter-intellij#1205]
I've been using Atom for Flutter development (even without the Flutter plugin) for several months.

My biggest reason for staying is that Atom will run dartfmt when I save.  I haven't had to think about formatting my code since I started using it, and that's a fantastic savings in engineering productivity.

Can we add support to run dartfmt on save to IntelliJ?

**Comment by alexander-doroshko** [comment]
True IntelliJ users rarely perform Save action, but they do frequently use Reformat Code action (Ctrl+Alt+L or Cmd+Alt+L). So in IntelliJ we tied a call to the `dartfmt` tool to its standard and well-known formatting action. This is a new feature of version 2017.2 that has Release Candidate status at the moment and is expected to be released very soon. You may try it [right now]( https://www.jetbrains.com/idea/nextversion/).

**Comment by mit-mit** [comment]
You could also do this with a Macro:

Edit > Macros > Start Macro Recording
Code > Reformat with Dart Style
File > Save All
Edit > Macros > Stop Macro Recording
Name the macro, and hit OK

Next, open Preferences, locate Keymap, search for the macro by the name you gave it, right-click, and assign cmd-s to it.

**Comment by AskYous** [comment]
Thanks @mit-mit!

**Comment by timokz** [comment]
Thanks a lot! Should have thought of that.
