### ISSUE TITLE
double headers show up on pubspec.yaml files

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1225]
We'll need to adjust the logic that the Dart plugin uses to identify flutter projects. Currently, I see:

<img width="762" alt="screen shot 2017-07-20 at 11 13 39 am" src="https://user-images.githubusercontent.com/1269969/28432420-adc61f66-6d3c-11e7-9933-81e14814485c.png">

The Dart plugin has code to ID flutter modules (and suppress it pubspec.yaml file banner) - we'll need to update that code w/ the new flutter module detection logic.

**Comment by jwren** [comment]
This is one of 4 places where the Dart Plugin suppresses itself.

**Comment by jwren** [comment]
PR to fix is in the Dart Plugin is here: https://github.com/JetBrains/intellij-plugins/pull/544

**Comment by devoncarew** [comment]
Landed, and will be available in 2017.2.2.
