### ISSUE TITLE
Add mockito to the test libraries

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#1233]
Add mockito to the test libraries for mocking objects in tests.

**Comment by devoncarew** [comment]
I assume you mean the Java library (not https://pub.dartlang.org/packages/mockito)? No objections here, though I think we'd want it to me motivated by the first set of tests that use the library.

**Comment by branflake2267** [comment]
Yeah, I was thinking of writing a test for the wizards in Java. Which I could do at some point too. For instance I'd like to mock the sdk for the unit test that I had in mind.

**Comment by devoncarew** [comment]
👍

**Comment by pq** [comment]
👍

**Comment by jacob314** [comment]
Closing as obsolete.
