### ISSUE TITLE
Device Selector should show emulator device name (currently generic)

### ISSUE THREAD

**Issue by eturk1** [flutter/flutter-intellij#1244]
## Steps to Reproduce
1. create more than one emulator for testing
2. open two or more
3. all emulators are listed with same name, can't be easily distinguished to control Run
![image](https://user-images.githubusercontent.com/525280/28643824-f90351f0-720b-11e7-8dd5-c0b04b0fe546.png)

Showing device emulated (i.e. Nexus 5X, Nexus 7) would be preferable to support testing on multiple device formats.

## Version info

C:\Users\<name>\IdeaProjects\mary_bp>flutter doctor

[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel alpha)
    • Flutter at C:\Users\erolf\git\flutter
    • Framework revision d36e2f6191 (5 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[√] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at C:\Users\erolf\AppData\Local\Android\sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 4.0.1
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 15.2
    • Dart plugin version 172.3317.48

[√] Connected devices
    • Android SDK built for x86 • emulator-5556    • android-x86 • Android 7.1.1 (API 25) (emulator)
    • Android SDK built for x86 • emulator-5554    • android-x86 • Android 8.0.0 (API 26) (emulator)
    • Nexus 6P                  • 84B5T15A29020348 • android-arm • Android 8.0.0 (API 26)

**Comment by devoncarew** [comment]
We're getting the names of the emulators we can open with `emulator -list-avds`, and the open android devices with `adb devices -l`. I suspect that the avd images could also be updated to change the names they report to adb?

**Comment by eturk1** [comment]
The text after "Open..." in screen shot bottom is what's desired in at top next to phone icon. Possible?

**Comment by devoncarew** [comment]
No, currently you'd need to edit the device name in the AVD image.

**Comment by eturk1** [comment]
what file specifically is current device string coming from? 

"Android SDK built for x86" isn't in:

C:\Users\<user>\.android\avd
Nexus_5_API_26.ini
config.ini
emulator-user.ini
hardware-qemu.ini

and don't see any other file it could be in

![image](https://user-images.githubusercontent.com/525280/28695962-50452ee4-72e7-11e7-97db-72ccf3539191.png)

**Comment by devoncarew** [comment]
These links may provide some hint for getting better device names:
- android/tools/adt/idea/android/src/com/android/tools/idea/run/AndroidDeviceRenderer.java
-
 android/tools/adt/idea/android/src/com/android/tools/idea/explorer/adbimpl/AdbDeviceFileSystemRenderer.java

**Comment by eturk1** [comment]
I'm noticing an improvement in latest Android Studio implementation.
Intellij still lists as reported in OP.

![image](https://user-images.githubusercontent.com/525280/41382957-3b954752-6f23-11e8-8e26-044947d6c298.png)

**Comment by Furgas** [comment]
This [SO answer](https://stackoverflow.com/a/55164379/170403) could be helpful:
```
# adb -s emulator-5554 emu avd name
Pixel_XL_API_28
OK
```
