### ISSUE TITLE
show build method structure in the outline view

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1247]
We should show the `build()` method widget hierarchy in the outline view. This could be a detailed expansion of the build method, or replace the current outline somehow when you're in a build method.

But net-net; we should explore options for showing the widget structure in the outline view.

**Comment by bwilkerson** [comment]
This would be easier to do in the analysis server (because we can use semantic information to identify `build` methods), but we'd have to update the plugin to use server's existing support for outline information.

**Comment by devoncarew** [comment]
Makes sense. I believe the outline view is currently driven by IntelliJ's parsed PSI elements.

**Comment by bwilkerson** [comment]
That is also my understanding. It undoubtedly seemed easier at the time, but it makes it slower for us to update the UI and prevents semantic-based updates.

**Comment by devoncarew** [comment]
We have this now.
