### ISSUE TITLE
Show closing tags in build methods (reference attached)

### ISSUE THREAD

**Issue by aubykhan** [flutter/flutter-intellij#1252]
This is a feature request. Dart Code has added a feature where it shows the closing tags for widgets. See this link: https://twitter.com/dartcode/status/889112590537957376

**Comment by aubykhan** [comment]
IntelliJ plugin for Flutter should have something like this. It's really useful.

**Comment by pq** [comment]
Nice!  See related discussion in #1034.  This is a nice implementation and great food for thought.

**Comment by devoncarew** [comment]
https://github.com/JetBrains/intellij-plugins/pull/550

**Comment by devoncarew** [comment]
Landed upstream in the EAP Dart plugin.
