### ISSUE TITLE
run action not directed to the correct device

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter-intellij#1254]
If you are running an app in IntelliJ on one device, say the iOS simulator, then add a second device, say a Nexus 6P and hit run, the iOS simulator restarts. Nothing happens on the 6P.

**Comment by devoncarew** [comment]
I think what's happening here is that the run command is being passed to the active running app, when the device pulldown has been changed to different device (w/ no current running app).

**Comment by LarkAscending** [comment]
Have also seen this recently...

**Comment by devoncarew** [comment]
Cool; this is something that we'll like fix in a patch release to the current plugin.
