### ISSUE TITLE
in the 'is flutter module' check, we should also check the pubspec

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1261]
From a discussion in person:

- the current 'is flutter module' check will incorrectly think that dart modules, in a project that is using a flutter sdk, are flutter modules
- we should consider additionally seeing if there is a pubspec, and if so, parse it to see if it is using flutter. If not, we can reject. We'd want to make sure the parse is performant.
- this modification to the check would need to be done in the flutter and dart plugins

@jwren, @alexander-doroshko, does this accurately capture the conversation?

**Comment by alexander-doroshko** [comment]
Yes, I think so. If we think we need it at all (as SDK remains per project, not per module).
Implementation in the Dart plugin only (reused in Flutter) sounds sufficient.
For performance reasons we should not reparse until the timestamp is changed.

**Comment by jwren** [comment]
Yes, that sounds accurate.

**Comment by pq** [comment]
Optimistically filing in M17.

**Comment by pq** [comment]
Closing in favor of bugs tracking the specific cases.

See for example: #1441, #1444, and #1445.

As noted in https://github.com/flutter/flutter-intellij/pull/1448#issue-268918487, @alexander-doroshko , @jwren : we'll want to make sure that the Dart Plugin is updated with a similar test in the appropriate places. 👍
