### ISSUE TITLE
must del 'build' dir to see changes in run/debug

### ISSUE THREAD

**Issue by eturk1** [flutter/flutter-intellij#1265]
## Steps to Reproduce
I have to delete the build directory to get code changes to be run/debugged.

A few changes will be pushed to emulator but eventually must delete build.
neither Hot Reload, Run, & Debug update app properly. Even completely stopping & restarting run/debug still runs previous code.

In the attached run window dump, I deleted build, just added '&&' in unfinished statement to force code to fail. Build to debug. Fails as expected. Removed &&, debug, hot, etc. not seen, still fails. Had to again delete build dir to get code running.

And, though the code is edited, the read-only version of main.dart that opens still shows the '&&' old code (reflecting the current failing build that is actually running)

Seems to have started with 16.0 update, but may have been going on before.

thanks for any help!!

## Version info
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel alpha)
    • Flutter at C:\Users\erolf\git\flutter
    • Framework revision bbcfb8d51a (3 days ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\erolf\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[√] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

[run.txt](https://github.com/flutter/flutter-intellij/files/1202025/run.txt)

**Comment by eturk1** [comment]
I'm just starting out at Flutter/Intellij
I'm realizing what's happening is when I run the code, a new read-only window is popping open. I used to be able to edit in the main code window and do a hot reload, see the change. Now these read-only windows appearing and code that's run will only change on deleting 'build' dir.

hope that helps

**Comment by devoncarew** [comment]
@eturk1, thanks for the report! Do you see the same behavior when you run from the command-line?

It looks like you're developing against android devices - just for clarity, are you using an actual device or an emulator?

And, can you delete the app on the device (there may be a few copies), and re-verify?

Depending on your answer to the first question, I'll likely move this issue over to the main flutter (github.com/flutter/flutter) repo.

**Comment by eturk1** [comment]
Thanks for the assist!!

Just fired up again after a few days off.
One symptom I see is that the apk are not being rebuilt on a full run or debug.
(i.e. build\app/outputs/apk/app.apk was 3 days old)
app.apk.sha1 does have current timestamp though

del build\app\outputs folder and apks are rebuilt, but with the old code
del build\app\intermediates and apks are rebuilt from latest code, all is good

note: I can quickly see if it worked because the debug window named "main.dart" that opens is still old. 
lib\main.dart windows shows latest code that is changed


-------------
I don't see errors in build screen dump

> [  +41 ms] [android\] C:\Users\erolf\Google Drive\mary_bp\android\gradlew.bat -q -Ptarget=C:\Users\erolf\Google Drive\mary_bp\lib\main.dart assembleDebug
[+2952 ms] Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
[{"event":"app.progress","params":{"appId":"b4cfd8d2-a261-4542-8973-f4f27e9d8433","id":"2","progressId":null,"finished":true}}]
[  +81 ms] calculateSha: build\app/outputs/apk/app.apk
[ +317 ms] Built build\app/outputs/apk/app-debug.apk (26.3MB).
[        ] C:\Users\name\AppData\Local\Android\sdk\build-tools\25.0.3\aapt dump badging build\app/outputs/apk/app.apk
[  +56 ms] Exit code 0 from: C:\Users\name\AppData\Local\Android\sdk\build-tools\25.0.3\aapt dump badging build\app/outputs/apk/app.apk
[


> Installing build\app/outputs/apk/app.apk...
[{"event":"app.progress","params":{"appId":"b4cfd8d2-a261-4542-8973-f4f27e9d8433","id":"3","progressId":null,"message":"Installing build\\app/outputs/apk/app.apk..."}}]
[  +67 ms] C:\Users\name\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 install -r build\app/outputs/apk/app.apk
[+1971 ms] Success

**Comment by devoncarew** [comment]
assumed stale -
