### ISSUE TITLE
Changes to Dart SDK have no effect

### ISSUE THREAD

**Issue by robertgirschick** [flutter/flutter-intellij#1278]
I would like to change an error message directly in the external libary `dart:io` websockets_impl.dart. I can do this under "External libraries" and at first it seems to work fine. I tested it by changing a method name and I can call the "new" method in my code. But when I run the app the "old" method is called (and so is the old error message) and I get a runtime error.

Why do the changes don't seem to have an effect?

**Comment by devoncarew** [comment]
The dart: libraries sources are included in the dart sdk at build time (as a dart snapshot). You'd need to rebuild the sdk for changes to take effect. There are some details on that here: https://github.com/dart-lang/sdk/wiki/Contributing. Cheers!
