### ISSUE TITLE
Remove a widget from hierarchy

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#1283]
I absolutely love the "wrap with new widget" feature. It's great!

I wish there'd also be the opposite of that, i.e. removing a widget from the hierarchy.

**Comment by stevemessick** [comment]
When you are removing a widget are you also removing its children? Or are you asking for a feature that will promote some child to be the replacement for its parent?

The first case can easily be done using Edit>Extend Selection, but I can see that the second case involves more tricky editing.

**Comment by brianegan** [comment]
Thanks for all the hard work and listening to this request! 

I find myself wishing for this feature more and more... In my case, I'd love Option #2: to be able to "Unwrap" the child Widget / promote it to replace the parent. As you mention, Option #1 seems to be covered by core editor functionality.

### Example

Start with something like this:

```dart
return new Card(
  child: new Container(
    color: Colors.red,
    padding: new EdgeInsets.only(
      top: 12.0, 
      bottom: 12.0,
    ),
    child: new Image.network(
      thumbnailUrl,
      scale: 1.0,
      fit: BoxFit.cover,
    ),
  ),
);
```

In my case, I want to remove the `Container`, but keep the child `Image.network`. The resulting code should look like this:

```dart
return new Card(
  child: new Image.network(
    thumbnailUrl,
    scale: 1.0,
    fit: BoxFit.cover,
  ),
);
```

I could see this working a couple of ways:

  1. Place the cursor over the `Image.network` constructor. Hit `Option-Return`. See two options: `Wrap with new Widget` & `Unwrap Widget`.
  2. Place the cursor over the `Container` widget. Hit `Option-Return`. See a new option: `Replace with Child` (or better language :)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/40240

**Comment by goderbauer** [comment]
Cool! Can't wait to give this a try! 🎉

**Comment by remoteportal** [comment]
How does one use Quick Assists?  Is it in Android Studio? 

I Googled it and can't figure it out.
