### ISSUE TITLE
Two "Pubspec has been edited" bars

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#1288]
When editing https://github.com/flutter/flutter/tree/master/packages/flutter in IntelliJ I often get two "Pubspec has been edited" bars. One would be enough :)

![screen shot 2017-08-17 at 11 31 47 am](https://user-images.githubusercontent.com/1227763/29427815-de357548-833f-11e7-8340-4220a9aab763.png)

**Comment by goderbauer** [comment]
Only one of them works when I click "Get dependencies". The other one produces the following error:

```
Working dir: /Users/goderbauer/dev/flutter/packages/flutter
/Users/goderbauer/dev/flutter/bin/cache/dart-sdk/bin/pub get
Resolving dependencies...
The Flutter SDK is not available.
Depended on by:
- flutter 
Process finished with exit code 69
```

**Comment by devoncarew** [comment]
Thanks for the report! We did land a fix for this - it's a bit upstream in the Dart plugin. We'll need to wait for the fix to hit the stable channel of the Dart plugin. /cc @alexander-doroshko @jwren

**Comment by goderbauer** [comment]
Awesome. Feel free to close this since it is fixed.

**Comment by alexander-doroshko** [comment]
The fix should already be there in 2017.2.2. @goderbauer, what is your IDE version?

**Comment by goderbauer** [comment]
I was on 2017.2.1. Updating now to 2017.2.2.

**Comment by farheen21** [comment]
Hey i am getting this again as i just upgraded my flutter...

![15841945749204921593030317410740](https://user-images.githubusercontent.com/60287642/76683513-a4564c00-662a-11ea-98ac-480ae5992228.jpg)
