### ISSUE TITLE
Settle on flow for "importing" flutter gallery app projects.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#130]
> The simplest thing of just opening the `flutter_gallery` folder doesn't work.
> 
> ```
> Could not find package sky_engine at "../../bin/cache/pkg/sky_engine".
> Depended on by:
> - flutter 0.0.21 
> Process finished with exit code 69
> ```
> 

_**EDIT:** the `pub` issue was fixed..._

**Current Flow:**

* Locally clone Flutter (e.g., to`flutter_repo`)
* From the **Welcome Page** choose, **Create New Project**
* Choose the Flutter Project Type in the **New Project Wizard**
* Fill in the `Flutter SDK path` with the path to your local clone (e.g., `flutter_repo`)
* Click **Next**
* In the `Project location` field, fill in: `flutter_repo/examples/flutter_gallery`
* Click **Finish**

At this point, a new window will open for your project and `flutter create` will be called.

**Comment by sethladd** [comment]
Did the user run "pub get" ?

(Does the IntelliJ plugin prompt the user to run "pub get" if the user needs to? Or, does it auto-run it?)

**Comment by pq** [comment]
Yep.  That error is the result of `pub get`.  But actually, this was a red herring.  After re-building the flutter tools it's now _possible_ to run the gallery from the IDE.   Getting set up is still not smooth...  But maybe smooth enough?  I'll update the flow after a quick run through.

**Comment by pq** [comment]
_Flow 1:_

* Locally clone Flutter (e.g., to`flutter_repo`)
* From the **Welcome Page** choose, **Create New Project**
* Choose the Flutter Project Type in the **New Project Wizard**
* Fill in the `Flutter SDK path` with the path to your local clone (e.g., `flutter_repo`)
* Click **Next**
* In the `Project location` field, fill in: `flutter_repo/examples/flutter_gallery`
* Click **Finish**

At this point, a new window will open for your project and `flutter create` will be called.

_Flow 2 **(not working)**:_

* **Open File or Folder:** `flutter_repo/examples/flutter_gallery`
* Open `lib/main.dart` and "Enable Dart Support"
* Problem: no flutter module defined...

**Comment by sethladd** [comment]
> Fill in the Flutter SDK path with the path to your local clone

This step should also set the Dart SDK as used/downloaded by Flutter.

**Comment by pq** [comment]
> This step should also set the Dart SDK as used/downloaded by Flutter.

👍  https://github.com/flutter/flutter-intellij/issues/121

**Comment by pq** [comment]
FYI @mit-mit @devoncarew for general flow.

**Comment by pq** [comment]
For now updated wiki w/ #131 is probably sufficient.  If down the road we want to streamline gallery app templates we can separately track.
