### ISSUE TITLE
Start Android Emulator action broken

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1303]
Found while testing M17 release candidate:

1. Create an Android Emulator AVD instance
1. Make sure the AVD isn't running
1. Create Flutter project in IJ
1. Open device picker, select AVD, and see it boot up

=> Device is still not shown as the active device

1. Open device picker, select AVD

=> this error:

![screen shot 2017-08-30 at 16 48 00](https://user-images.githubusercontent.com/13644170/29878579-354d0d92-8da3-11e7-8ffb-a757f7f0dcc2.png)

**Comment by devoncarew** [comment]
I don't believe this is a regression, in that this would have happened with the previous release.

In terms of debugging this and figuring out what's going on, were you able to get this back on the rails? Does restarting IntelliJ help?

**Comment by mit-mit** [comment]
I restarted IJ, and I still have this problem. I think you need to have at least two Android emulators configured for it to happen.

**Comment by mit-mit** [comment]
Confirmed that this works with the updated templates in https://github.com/flutter/flutter/pull/12391

**Comment by mit-mit** [comment]
Closing as https://github.com/flutter/flutter/pull/12391 was merged
