### ISSUE TITLE
Plugin project type has non-working run config

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1305]
1. `flutter create --template=plugin myplugin`
1. `cd my plugin`
1. `idea .`

=> project opens, run config is populated, and you can hit Run/Debug

1. Start IJ
1. File > New Project > Flutter > Plugin Project

=> project is created, but run config is missing/broken, and you cannot hit Run/Debug

**Comment by devoncarew** [comment]
I have a fix for this.
