### ISSUE TITLE
Package project type not properly configured

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1306]
1. Start IJ
1. File > New Project > Flutter > Select Package project type
1. After project has been created, open `lib/<pkg name>.dart`

=> get "Dart SDK is not configured error"

![screen shot 2017-08-30 at 16 57 26](https://user-images.githubusercontent.com/13644170/29879053-514a3f00-8da4-11e7-9427-5ebb5fba5d87.png)

**Comment by devoncarew** [comment]
It could be that flutter_tools is not creating all the IntelliJ metadata we'd want.

**Comment by stevemessick** [comment]
Doesn't the Dart SDK have to be set up at some point? If it had not been then this message makes sense.

I don't see this problem, however. When I create a new Package I get a message that Dart support is not enabled for this module. That sounds like some IJ metadata is missing. It only happens for packages, not plugins or applications.

**Comment by devoncarew** [comment]
`packages` is a relatively recent addition to the `flutter create` templates - I suspect we'll need to extend it a bit to add some IntelliJ metadata (.iml files?), like we do for the plugins and app templates.
