### ISSUE TITLE
Plugin parameters not correctly set

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1307]
1. Start IJ
1. File > New Project > Flutter > Plugin Project
1. Set custom values for description, organization, and programming language

-> project is created with the default values, not the specified values

**Comment by devoncarew** [comment]
@stevemessick, would you mind taking a look at this (I know you where in this area recently)?

**Comment by stevemessick** [comment]
Cannot reproduce. I'm using IntelliJ CE + Flutter M17. I changed string values for organization and description, switched languages to Kotlin and Swift, set type to Plugin, and changed the name from "untitled" to something else. All custom values show up where expected in the new project.

**Comment by devoncarew** [comment]
@mit-mit, were you testing against flutter master or alpha?

**Comment by devoncarew** [comment]
Or, did you need to run `flutter upgrade`?

**Comment by mit-mit** [comment]
I'm using IDEA 2017.2.1 and:

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-DK, channel master)
    • Flutter at /Users/mit/dev/flutter
    • Framework revision def0b4203a (29 hours ago), 2017-08-29 20:34:30 -0700
    • Engine revision f9e00a7c72
    • Tools Dart version 1.25.0-dev.11.0
```

But for reasons I cannot explain, I can no longer repro this today... Closing for now.
