### ISSUE TITLE
Opening Observatory is broken

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1308]
1. Create new Flutter app in IJ
1. Hit Run
1. Open the Flutter view
1. Click the 'Open Observatory timeline' button

=> a 'blank' browser window is opened

**Comment by devoncarew** [comment]
@mit-mit, I'm not able to repro this, either run or debug, w/ iOS simulator, android devices, or the android emulator.

**Comment by mit-mit** [comment]
Can someone else try also? I got a consistent repro.

**Comment by devoncarew** [comment]
Does the address look well formed? Does the observatory web ui respond in general? And, can you get the the observatory timeline page when you flutter run from the command-line?

**Comment by mit-mit** [comment]
It's not timeline specific, the general observatory button in the Console doesn't work either. The address is empty, so no. Also, I don't see the observatory URL printed in the Console.

**Comment by mit-mit** [comment]
If I `flutter run` from the terminal, the URL is printed and it opens just fine.

**Comment by devoncarew** [comment]
OK, that should be for the general observatory URL. From that page, can you navigate to the timeline page, and does the url for that match the one that IntelliJ it trying to open?

Is this a 127.0.0.1 / localhost thing?

**Comment by devoncarew** [comment]
> The address is empty

Ok, that sounds like a IntelliJ platform bug. 

https://github.com/flutter/flutter-intellij/blob/4118d2df4b768c3ddf7ebd9b1b82db7d08d4a998/src/io/flutter/run/OpenObservatoryAction.java#L53

We're trying to open the url with any chrome browser (that IntelliJ knows about), and then fallback to any browser.

**Comment by devoncarew** [comment]
@mit-mit, I don't think this is a regression in the plugin per se, so moving out of M17. We can patch the release if we do find an issue in the flutter plugin.

**Comment by mit-mit** [comment]
This is still a 100% repro for me. Can you try in macOS against an iOS Simulator? I do not get an Observatory URL in the console output when running from IJ, and the Observatory button still launches an empty browser tab.

**Comment by devoncarew** [comment]
I'll re-try, but I originally did try macos and ios simulator. What version of IntelliJ are you using? Do you see any obvious issues in your 'Web Browsers' pref page in IntelliJ?

> I do not get an Observatory URL in the console output when running from IJ

You won't - we filter this for less noise (user's can open Observatory other ways).

**Comment by mit-mit** [comment]
I'm using IDEA Community 2017.2.1.

I don't see any issues in the browser preference.

**Comment by devoncarew** [comment]
I'm seeing new behavior (from ~2 weeks ago): https://github.com/flutter/flutter/issues/12048 - I'm not able to get to any observatory pages.

**Comment by mit-mit** [comment]
@devoncarew this appears to still be broken in the M18 RC build

**Comment by stevemessick** [comment]
I just tried this on my Mac using IntelliJ with the M18 RC plugin. Everything seems to work.

I tried both the 'Open Observatory' and 'Observatory Timeline' buttons. The expected pages opened in Chrome.

I set a breakpoint in IntelliJ, ran to it, saw that the Observatory recognized the breakpoint, opened the Observatory debugger, continued. Then something happened that I didn't expect: the IntelliJ debugger did not recognize the program was running, it still showed the stack. The timeline seemed to work. Other than the IJ debugger not getting updated everything was fine.

I did 'flutter upgrade' yesterday so both my Flutter and Dart SDK are current.

**Comment by devoncarew** [comment]
> this appears to still be broken in the M18 RC build

Michael, I've never been able to repro this :( We haven't had reports from users, so I don't think this is a widespread issue.

Do other things that open a browser work? Flutter > Tools > send feedback?

**Comment by mit-mit** [comment]
I did a bit more testing. It works as expected for me on my Windows and home Mac. But still tails on the office Mac.

**Comment by mit-mit** [comment]
Back on the office Mac, it's still failing. *Help > Flutter Plugin Help* and *Tools > Flutter > Submit Feedback* work fine though.

One potential cause: On this machine where it's failing I'm using Chrome Beta (62.0.3202.45).

**Comment by devoncarew** [comment]
> Back on the office Mac, it's still failing. Help > Flutter Plugin Help and Tools > Flutter > Submit Feedback work fine though.

That's good data though - at least that mechanism for launching web pages works. For the observatory, I think we're preferring a chrome browser if we can find one.

**Comment by sgehrman** [comment]
blank on Linux/Chrome/Android.  I'm using VSCode Open Observatory timeline.
