### ISSUE TITLE
Double package prompt

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1329]
I haven't seen this for a while, but seems to consistently re-appear now:

1. Create new Flutter project in IJ
2. Open `pubspec.yaml`

=>
![screen shot 2017-09-12 at 16 38 13](https://user-images.githubusercontent.com/13644170/30331712-cbe23dd8-97d8-11e7-93f8-97aa9bbed373.png)

**Comment by devoncarew** [comment]
Do you have the latest version of the Dart plugin?

**Comment by mit-mit** [comment]
I have `Version: 172.3544.34`

**Comment by devoncarew** [comment]
I have `172.3968.27` locally.

**Comment by mit-mit** [comment]
I had to update to a newer version of IJ (2017.2.4) to get an updated Dart plugin. After doing that, this no longer repros, so closing.
