### ISSUE TITLE
make reload on save the default

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1331]
This is the continuation of the M16 option to hot reload changes on save: https://github.com/flutter/flutter-intellij/issues/563

- [x] make reload on save the default (keep the user preference to disable)
- [ ] update our docs to mention reload on save (@mit)

**Comment by mit-mit** [comment]
I added a note about the docs in https://github.com/flutter/flutter-intellij/issues/1315, closing this for tracking purposes
