### ISSUE TITLE
Plugins Not loading in intelliJ

### ISSUE THREAD

**Issue by TheOnlyCheezIt** [flutter/flutter-intellij#1344]
## Steps to Reproduce
I installed Flutter using the flutter.io tutorial
When i went to get the intelliJ plugin is gave me this error:
List of plugins was not loaded for following hosts: https://github.com/flutter/flutter

Due to the following errors:
'org.xml.sax.SAXParseException; lineNumber: 42; columnNumber: 91; Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.' for 'https://github.com/flutter/flutter'

## Version info
```
[√] Flutter (on Microsoft Windows [Version 10.0.14393], locale en-US, channel alpha)
    • Flutter at C:\Users\brayd\Desktop\Apps\flutter
    • Framework revision 701d534ba9 (8 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[-] IntelliJ IDEA Community Edition (version 2017.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices
    • None
```

**Comment by devoncarew** [comment]
Is this error from the 'Plugins' part of the IntelliJ preferences dialog? You should type 'Flutter' into the search box there. You'll see a link similar to 'search in repositories' - that'll take you to where you can install the Flutter plugin.

**Comment by TheOnlyCheezIt** [comment]
Yes, when i go into settings>plugins>Browse repositories it gave me the error above

**Comment by alexander-doroshko** [comment]
@TheOnlyCheezIt Looks like you've added https://github.com/flutter/flutter as an additional plugin repository. I guess there's no such step in docs, you don't need to add any repository. Flutter plugin is available in the standard JetBrains repo. Just find it in the list that opens (use search field).

**Comment by TheOnlyCheezIt** [comment]
When i search flutter it says nothing to show (i have removed https://github.com/flutter/flutter)

**Comment by devoncarew** [comment]
You should see this for the first page:

![Uploading Screen Shot 2017-09-21 at 8.04.05 AM.png…]()

And then after you click on the link:

<img width="736" alt="screen shot 2017-09-21 at 8 04 10 am" src="https://user-images.githubusercontent.com/1269969/30703081-8d8fa026-9ea3-11e7-8f59-9812912cc14b.png">

**Comment by TheOnlyCheezIt** [comment]
Yes but when i go to browse repositories th
![2017-09-21 1](https://user-images.githubusercontent.com/26682613/30703188-d236cb0a-9ea3-11e7-89f5-b0ac10cdff14.png)
at is not what i see

**Comment by TheOnlyCheezIt** [comment]
![2017-09-21 2](https://user-images.githubusercontent.com/26682613/30703242-fa347be8-9ea3-11e7-8abd-e2261c97629e.png)

**Comment by alexander-doroshko** [comment]
This is IntelliJ IDEA 2017.2 Community Edition, right? Do you see any plugins in the list if you clear search box?

**Comment by TheOnlyCheezIt** [comment]
This is IntelliJ 2017.2.3 and no I do not see any when I clear the box

**Comment by alexander-doroshko** [comment]
This means that the IDE doesn't have internet access. It may be blocked by an OS firewall or incorrectly set HTTP Proxy Settings (the button is on your screenshot) or any other reason.

**Comment by alexander-doroshko** [comment]
@TheOnlyCheezIt The following may help: please find the folder `%USERPROFILE%\.IntelliJIdea2017.2\config\plugins` and remove files `availables.xml.etag` and `availables.xml`. Then open Plugins page in the IDE, plugins will hopefully show up.

**Comment by mit-mit** [comment]
@TheOnlyCheezIt did you get this resolved?

**Comment by TheOnlyCheezIt** [comment]
Yes, I resolved the issue by reinstalling IntelliJ completely thanks for the help I am loving flutter

**Comment by mit-mit** [comment]
Thanks, good to hear!

**Comment by bug081624** [comment]
> @TheOnlyCheezIt The following may help: please find the folder `%USERPROFILE%\.IntelliJIdea2017.2\config\plugins` and remove files `availables.xml.etag` and `availables.xml`. Then open Plugins page in the IDE, plugins will hopefully show up.

solved it,thx
