### ISSUE TITLE
Add validation on 'flutter_test' module name

### ISSUE THREAD

**Issue by rootext** [flutter/flutter-intellij#1352]
## Steps to Reproduce
1. Create a new Flutter project and set module name to 'flutter_test'.
Actual result: Process fails with error: 
A package may not list itself as a dependency.
flutter_test:
^^^^^^^^^^
pub get failed (65)

I understand that package 'flutter_test' already exists and automatically added as dev_dependencies.
So, it isn't an actually issue but validation on module name can improve user experience.

Expected result: Validation on 'flutter_test' module name with the same validation message as for 'flutter'.

## Version info
[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3757.55

**Comment by devoncarew** [comment]
@pq, sounds like we could expand the blacklist for legal project names a bit.
