### ISSUE TITLE
Help app devs with debugging UI jank

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter-intellij#1363]
[Had a talk with @devoncarew this morning about this so filing a tracking issue.]

We need a tool that can help us create actionable items while debugging UI jank. GPU profiling is not likely to yield any results since it is too low level to be accessible for app developers. We realized there were a couple of areas that we often *do the wrong thing*:

- Do a lot of work in the build() fn of the widgets. Some of this work can be done only when state changes.
- Call setState() too often _just in case_
- Somehow cause the existing render tree to be thrown away and rebuilt. This happened initially with charts when they were creating a new object with same params (but no equals override) with every frame of the chart animation which led to a lot of jank.

Some ideas:
- An ability to _record_ widget tree behavior over a short period of time and analyze what happens to it:
 - How many times are we rebuilding?
 - How long is rebuild taking?
 - How many times does a rebuild cause re-render (invalidation of the existing render tree node)?

This information would be very useful to identify potential places where app code (as opposed to framework code) is doing something wrong.

**Comment by mehmetf** [comment]
@Hixie @sethladd @eseidelGoogle FYI

**Comment by Hixie** [comment]
> Call setState() too often just in case
This one should be easy enough to avoid if you just always set the state in the callback, and never call the setState with an empty closure. Eventually I'd love to have a lint that verifies that your build method never uses anything that is set outside of setStates (or initState)

**Comment by Hixie** [comment]
> record widget tree behavior

We could implement something similar to [debugProfilePaintsEnabled](https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/debugProfilePaintsEnabled.html) for the build phase.

**Comment by sethladd** [comment]
This is great. Thanks for writing it up.

**Comment by devoncarew** [comment]
I also had another discussion with @turnidge related to the existing timeline view (and any possible follow-on view).

And, cc'ing @mit-mit and @jacob314 as well. Jacob has a lot of insight into the Flutter rendering architecture at this point and might have opinions about how tooling - even outside the scope of the Flutter inspector - could help here.

**Comment by jacob314** [comment]
It could be interesting to flash dirty widgets and render objects in the inspector tree view similar to how chrome devtools element tree view flashes nodes and attributes that changed.
Taking that a step further, it could be feasible to record the widget tree state as DiagnosticsNode objects allowing scrubbing backward and forward to debug what updates to the tree occurred when. Likely most useful when combined with a regular timeline view.

**Comment by jacob314** [comment]
Implemented widget rebuild indicators and widget rebuild summary stats for Flutter 1.0 that target this case.
