### ISSUE TITLE
Hot Reloading not available

### ISSUE THREAD

**Issue by alexanderniebuhr** [flutter/flutter-intellij#1365]
Hey folks.

I just installed Flutter and followed the docs for the IDE Setup. So far everything is fine.. However if I am running the Flutter Demo App on IOS the Hot Reload Feature (Simulator and real device) is grayed out in IntelliJ IDEA CE on my macbook  any suggestion how to enable hot realoading 

Cheers
Alex

**Comment by alexanderniebuhr** [comment]
Works with master branch and 2017.2.4

Alpha and 2017.2.5 does not work for me

**Comment by devoncarew** [comment]
Hmm, it would be good to narrow the failure down:
- does running from the command line using the alpha branch support hot reloading?
- does using the master branch and 2017.2.5 work?

**Comment by alexanderniebuhr** [comment]
I just did tried 2017.2.5 today, and it seems to work with the master branch.

Alpha branch does not work at all for me, even not with the CL

**Comment by devoncarew** [comment]
OK, it sounds like the issue is in the alpha branch but not in master. alpha was last updated 20 days ago; I'm going to mark this as closed (and, we should likely roll alpha soon). Thanks for the bug report!
