### ISSUE TITLE
IntelliJ didn't show connected device (iPhone 6S) on MacBook Pro

### ISSUE THREAD

**Issue by sarbjithanjra** [flutter/flutter-intellij#1366]
![screen shot 2017-09-30 at 2 12 34 pm](https://user-images.githubusercontent.com/7668520/31044276-d5d1a008-a5e9-11e7-9e72-fbc2d71ff45a.png)
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

My iPhone 6S is connected to MacBook but Intellij didn't display any device but connected iPhone is available in xcode and I am able to run the flutter app on my iPhone. I have try to disconnect and reconnect but intellij did't display any device to run. I am using IntelliJ IDEA CE 2 and flutter plugin version 17. I have attached the screenshot which display XCode and IntelliJ screens.

## Version info

/Users/sarbjithanjra/projects/2018/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en, channel alpha)
    • Flutter at /Users/sarbjithanjra/projects/2018/flutter
    • Framework revision 701d534ba9 (3 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.1)
    • Android SDK at /Users/sarbjithanjra/Library/Android/sdk
    • Platform android-25, build-tools 25.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[-] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at http://brew.sh/.

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] Connected devices
    • None

**Comment by SiarheiFedartsou** [comment]
Have you installed libimobiledevice/ideviceinstaller/ios-deploy? If no try to install it as described here https://flutter.io/setup-macos/#deploy-to-ios-devices

**Comment by devoncarew** [comment]
@sarbjithanjra, it looks like there's a bit more setup necessary on your machine for ios development. I'd run `flutter doctor` from the command line, fix any issues in the 'iOS toolchain' section, and iterate until the ios section is happy.

**Comment by devoncarew** [comment]
Closing this; some remedies would be to do `flutter channel master; flutter upgrade`, or address the  macos issues found my flutter doctor.

**Comment by angelopolotto** [comment]
My Android Studio can't find my IPhone and I got this error when I tried run `flutter doctor` with my IPhone connect:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale pt-BR)
⢿Unhandled exception:
Exception: ideviceinfo returned an error:

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:141:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:156:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:110:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:171:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:99:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:694:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

The most stranger thing is: when I remove the IPhone, `flutter doctor` back work again.
