### ISSUE TITLE
Plugin projects do not work well in Android Studio

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#1369]
Android Studio 3.0 beta 6
Flutter plugin v18 RC

Create a new plugin project. (File>New>New Flutter Project>Flutter App)
Expand the Project view and see that almost all content is either ignored or excluded.

<img width="316" alt="screen shot 2017-10-04 at 10 54 25 am" src="https://user-images.githubusercontent.com/8518285/31191250-6dafe8d4-a8f2-11e7-8d4c-01d712cffa32.png">

Once AS has trashed the iml file the project looks bad in IntelliJ, too. However, creating and editing a plugin project with IntelliJ Ultimate works as expected.

**Comment by devoncarew** [comment]
I don't understand what's ignored or excluded from above? I see the dart code, the ios and android code, and the example sub-project.

**Comment by stevemessick** [comment]
The yellow background means the item is ignored or excluded.

**Comment by Jamesmallon1** [comment]
This is also an issue for me. Would be brilliant to resolve this issue.

**Comment by stevemessick** [comment]
This actually is not an issue. See https://github.com/flutter/flutter-intellij/issues/5596#issuecomment-929643151
