### ISSUE TITLE
the flutter test editor decoration arrow shows up for regular dart projects

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1371]
The flutter test execution editor contribution shows for regular dart projects, and we try and run those tests with `flutter test`.

<img width="377" alt="screen shot 2017-10-04 at 5 11 40 pm" src="https://user-images.githubusercontent.com/1269969/31205600-46801fec-a927-11e7-8dae-188c5bba5004.png">

@pq

**Comment by pq** [comment]
Hmmm.  So this is curious.  I can't repro locally.

![image](https://user-images.githubusercontent.com/67586/31369475-a6d8efb6-ad39-11e7-82fd-f51fbf8db1f4.png)

Is this a vanilla linter checkout?  IDEA?

**Comment by devoncarew** [comment]
This doesn't repro in android studio or my runtime workbench in IntelliJ. It does repro in my regular IntelliJ. I speculatively tried 'invalidate caches' and restarted, but didn't see a change.

**Comment by pq** [comment]
OK.  So I've narrowed this down.  The issue is in how we check for flutteriness. In
`io.flutter.utils.FlutterModuleUtils#isFlutterModule` we use this heuristic:

      // [Flutter support enabled for a module] ===
      // [Dart support enabled && referenced Dart SDK is the one inside a Flutter SDK]

If we want to support vanilla Dart modules using a Flutter Dart SDK we'll need to change this.

**Comment by devoncarew** [comment]
OK, sounds like we'll have to narrow the check somehow. /cc @jwren 

I know this will affect several use cases, so we'll need to do it carefully. Perhaps a narrower check which specific call sites in the code can opt into?
