### ISSUE TITLE
Open in Android Studio action for a plugin project doesn't work

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1372]
## Steps to Reproduce

1. Start IDEA with the M18 RC plugin installed
1. File > New Project, select Plugin type, and Next
1. After IDEA has initialised, right-click the root node in the project view and select Flutter > Open in Android Studio

Actual result: Android Studio starts displays the 'Welcome to Android Studio' dialog
Expected result: Android Studio starts and opens `./example/android/build.gradle/`

**Comment by mit-mit** [comment]
cc @devoncarew

**Comment by mit-mit** [comment]
After running `flutter config --android-studio-dir /Applications/Android\ Studio\ 3.0\ Preview.app/Contents/` this fails even more:

```
10.52	Error Opening: /Users/mit/tmp/plugin10/plugin10_android.iml
```

**Comment by stevemessick** [comment]
Try it without the trailing slash. Yes, it could be more resilient, and I can add that now if you want, but I doubt most people will be aware that you can set that path.

This worked for me:
```bash
flutter config --android-studio-dir "/Applications/Android Studio 3.0 Preview.app/Contents"
```

**Comment by stevemessick** [comment]
AI: Find a way to distinguish the old Android Studio from the 3.0 version and try to recover when the wrong one is found first. Also, check for trailing '/' before launching. Someone could set the path manually using the flutter tool and they might think the trailing slash is needed (it is not).
