### ISSUE TITLE
Refactoring support for seperating part of a build method into a smaller build method

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1374]
Flutter `build()` methods quickly get quite deep. It would be very useful to offer a refactoring to separate out part of a build method into a new build method.

For example, assume the following code:

```
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
```

If a developer uses the Refector > Extract to build method function with the cursor located on `new FloatingActionButton` that should create this new method:

```
Widget buildFloatingActionButton(BuildContext context) {
    return new FloatingActionButton(
      onPressed: _incrementCounter,
      tooltip: 'Increment',
      child: new Icon(Icons.add),
    );
  }
```

and change `floatingActionButton: new FloatingActionButton(...)` to `floatingActionButton: buildFloatingActionButton(context)`.

Similarity, placing the cursor on `new Center` and using the same refactoring should create:
```
Widget buildCenter(BuildContext context) {
    return new Center(
      child: new Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          new Text(
            'You have pushed the button this many times:',
          ),
          new Text(
            '$_counter',
            style: Theme.of(context).textTheme.display1,
          ),
        ],
      ),
    );
  }
```

thus resulting in this nice and small build method:

```
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: buildCenter(context),
      floatingActionButton: buildFloatingActionButton(context),
    );
  }
```

**Comment by mit-mit** [comment]
Actually, this already works:

1. Select the part to extract
1. Invoke Refactor > Extract > Method
1. Enter name of method

**Comment by devoncarew** [comment]
@mit-mit, we are landing a few tweaks to make this work better in a build() method context: https://github.com/JetBrains/intellij-plugins/pull/551 and https://dart-review.googlesource.com/c/sdk/+/11740

The flow I used was to option-up to expand the selection and then option-command-m to extract the method.

I think we could really do with an editing specific doc - we have a lot of functionality, not widely know, and the docs can help overcome discovery issues.

**Comment by mit-mit** [comment]
Agree, more docs would be good, tracking in https://github.com/flutter/flutter-intellij/issues/1382
