### ISSUE TITLE
Can't disable Hot Reload on Save

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#1388]
## Steps to Reproduce

  - Open Flutter settings in IntelliJ
  - Uncheck "Hot Reload on save"
  - Hit apply
  - Cheeky little checkbox goes back to being Checked
  - Hot reload on Save still enabled

## Demo

![cheeky-checkbox](https://user-images.githubusercontent.com/126604/31376905-a9461d06-ada6-11e7-9948-7c89de1535b4.gif)

## Version info

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/phillywiggins/lab/flutter
    • Framework revision 89566feeed (10 days ago), 2017-09-29 17:56:25 -0700
    • Engine revision bdfedcc26f
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/phillywiggins/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/phillywiggins/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.3)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[✓] Connected devices
    • iPhone 8 • 1BF60912-962E-4F2A-B8CF-9BB69E216DB1 • ios • iOS 11.0 (simulator)

**Comment by mit-mit** [comment]
Ugh, sorry to hear @brianegan

**Comment by mit-mit** [comment]
cc @devoncarew

**Comment by brianegan** [comment]
No worries, hope it helps!
