### ISSUE TITLE
flutter project wizard doesn't show up in the list of wizards for webstorm

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#139]
WebStorm support is very low priority for the flutter plugin, but I wonder if this would affect any of the IntelliJ 'small IDE' products.

<img width="202" alt="screen shot 2016-09-22 at 9 33 28 pm" src="https://cloud.githubusercontent.com/assets/1269969/18774293/7629046e-810c-11e6-989b-ccce74cf6eb3.png">

**Comment by pq** [comment]
Good catch! Do we have any of the 'small IDEs' on our list (https://github.com/flutter/flutter-intellij/issues/64)?  We never quite finished that thought but really should.

**Comment by devoncarew** [comment]
Definitely not webstorm, but android studio, when we have cycles.

**Comment by devoncarew** [comment]
I'm going to close this for now; we can re-open similar when webstorm gets on our radar.
