### ISSUE TITLE
wire into the flutter_tools protocol to get soft reload failure messages

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1398]
There's a current UI for this on the CLI.

**Comment by sethladd** [comment]
Where is this documented? I'd like to ask @DanTup if he's interested in adding this to VS Code, too.

**Comment by devoncarew** [comment]
No docs as such, and we'll need to write the pieces still that an IDE could use to get these notifications. I'll update this issue as things progress -

**Comment by LarkAscending** [comment]
FYI a page for flutter.io is in progress...and I believe the Dart VM team has some new messages (either added or about to add).

**Comment by DanTup** [comment]
Assuming this is a solution to #10620, it'd definitely be good to add. We now have the ability to get custom events from the debug adapter to the Code UI too, so whereas previously we were limited to stdout messages, we can now get data back for rendering in things like status bar/notifications which should be convenient for displaying things like this.

**Comment by DanTup** [comment]
Ok, I'll leave as-is for now so I can figure out how best to implement it when there is another use of it. If possible, give me a ping if you add anything :-)
