### ISSUE TITLE
Improve error reporting when project creation fails.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1399]
Attempting to create a project with out of date flutter iOS toolchain bits failed like this:

![image](https://user-images.githubusercontent.com/67586/31681861-4eb338ec-b32d-11e7-911b-1ccb865c9f17.png)

Not a super helpful message!  Of course, `flutter doctor` makes the culprit clear:

```
    ✗ libimobiledevice and ideviceinstaller may require updating. To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
```

The rub is folks may not know to run it. so we should consider improving the error message and/or adding a link to run flutter doctor from the error dialog.

/cc @cbracken 

FYI @devoncarew

**Comment by cbracken** [comment]
For the record, I suspect there's another case to handle here too. Users can also get the lockdownd error message for iPhones that haven't yet been paired with the machine. This should be pretty rare -- only if the phone has never been used for iOS development on the same machine. 

The solution in that case is to run any app once from Xcode.

**Comment by pq** [comment]
A quick cut:

![image](https://user-images.githubusercontent.com/67586/31730531-0508b946-b3e7-11e7-973d-db2461dbccf3.png)

Input welcome!

@devoncarew
