### ISSUE TITLE
Lost Flutter decoration for Flutter project

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1401]
Notice no flutter icon in the project explorer:

![image](https://user-images.githubusercontent.com/67586/31682666-a25176f6-b32f-11e7-83b5-44fe43ae8362.png)

Stepping through `FlutterIconProvider` it looks like the icon is associated... Possibly it's being overwritten by the Dart plugin?

**Comment by pq** [comment]
It looks like the issue is that both the `FlutterIconProvider` and the `DartIconProvider` are contributed as ordered "first":

    <iconProvider implementation="io.flutter.project.FlutterIconProvider" order="first"/>

    <iconProvider implementation="com.jetbrains.lang.dart.projectView.DartIconProvider" order="first"/>

@alexander-doroshko, @jwren  : would it be reasonable for us to change the Dart plugin contribution order to allow for refinement from Flutter?

**Comment by jwren** [comment]
Sounds reasonable to me, what are the other options for `order`?

**Comment by pq** [comment]
Hmmm, so now I'm not sure if I was right.  Look, for example at how the flutter gallery is presented:

![image](https://user-images.githubusercontent.com/67586/31690995-4dbbe26a-b349-11e7-9e19-b6535c8b2f0d.png)

Or maybe when two providers declare first there is some non-determinism?

**Comment by alexander-doroshko** [comment]
> some non-determinism?

I think so. You may catch it in debugger.
You could add `order="before DartIconProvider"`, but it will work only if/when I add `id="DartIconProvider"` to the Dart plugin.xml. Should I add it?

**Comment by pq** [comment]
That sounds great.  Thanks @alexander-doroshko.  Please do! 👍

**Comment by alexander-doroshko** [comment]
Done. Will be available in the 2017.3 EAP next week.
