### ISSUE TITLE
Bad module name

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#1421]
Try typing this into the name field of the new package or module wizard. It hangs on the final '_'.

`a_long_module_name_is_illegal_`

Everything is fine until we get to the 30th character, which is the final underscore (cap 'A' in place of underscore also hangs). The name isn't too long yet, but one more character after the final '_' would be too many.

**Comment by stevemessick** [comment]
Looks like a bad regex. I put it into regex101.com and tested the name. It said:
```
Catastrophic backtracking has been detected and
the execution of your expression has been halted.
```

**Comment by pq** [comment]
Reproduced in CE (but note that validation only runs when you click FINISH, not as you type).
