### ISSUE TITLE
widget_test.dart generates console errors in IntelliJ project

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter-intellij#1429]
## Steps to Reproduce
1. Create a new Flutter project in IntelliJ.
1. Open lib/main.dart and replace the contents of the default sample app MyApp.
1. Get the following errors in the console (because widget_test.dart is referring to class MyApp):
```
error: Undefined class 'MyApp'. (undefined_class at [testing] test/widget_test.dart:15)
error: The constructor returns type 'dynamic' that isn't of expected type 'Widget'. (strong_mode_invalid_cast_new_expr at [testing] test/widget_test.dart:15)
info: Unused import. (unused_import at [testing] test/widget_test.dart:10)
```
Also get red wavy underline under the \<project name\> and the `test` directory. The line in `widget_test.dart` causing the error is:
```
await tester.pumpWidget(new MyApp());
```

This doesn't happen after the equivalent set of steps at the command line (flutter create, replace contents of main.dart, flutter run). No errors are printed to the console in that case.

Note that the app still runs; clicking the Run button on the toolbar still works. Running the app makes the console errors go away. But the red wavy underlines in the left nav persist, and it looks alarming - a new user will think they have to resolve these errors before they can run their first app.

https://github.com/flutter/flutter/pull/11304/files
is where this was introduced.

## Version info
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /usr/local/google/home/eastrue/flutter
    • Framework revision 1c372c6803 (8 weeks ago), 2017-08-31 15:54:45 -0700
    • Engine revision f9e00a7c72
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /usr/local/google/home/eastrue/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio-with-blaze-2.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.2)
    • Android Studio at /usr/local/google/home/eastrue/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[-] IntelliJ IDEA Community Edition (version 2017.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4694.29
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • Nexus 5X • 0048fc9b7c76b7a2 • android-arm • Android 6.0.1 (API 23)

/cc @efortuna

**Comment by LarkAscending** [comment]
Note that the Flutter plugin IS installed though it shows up as missing in flutter doctor - this might be another, separate issue. The plugin version is 18.1.

**Comment by pq** [comment]
Thanks for the report!

The issue here is that we generate a sample test with the sample app.  When you follow the instructions in the tutorial you remove the class `MyApp` that is referenced in the sample test and so you get analysis errors.

I can think of a few approaches to smoothing this out.  The easiest might be to update the tutorial contents to modify the test in one of a few ways.

1. at the outset, instruct folks to remove the test altogether or alter its contents or more ambitiously
2. add instructions to update it to work with the tutorial app (e.g., modify it to reference `MaterialApp` and do something sensible

The first is easiest...

**Comment by LarkAscending** [comment]
Yes, agree on root cause. Any chance there other options for solving it gracefully? 

The question on how to fix it is a macro one, I think, affecting the new user experience. Is this a common workflow? If so "addressing" it with documentation is not likely to smooth the UX.

**Comment by InMatrix** [comment]
I noticed this problem when I was trying out the animation tutorials as well. In addition to being distracting, the mismatch of class names between the test template and the app code also breaks Reload on Save, since the reload won't be performed when there is an analysis error. Can we provide a refactor hint in the IDE or a more actionable error message for this situation through the analysis server? Thanks!

**Comment by devoncarew** [comment]
I think we still have work to do here in terms of improving the visibility of errors.

I'm not sure if this is or isn't a common workflow. I myself would start with the generated app, and probably tweak the build() method incrementally.

Is this a step (replacing the contents of main.dart) in a codelab? If so, can we adjust that step, to also mention renaming the class reference in the test file, or to change the amount of code that's being copied in? I think we generally do want to generate a unit test test as part of the sample app, for pedagogical reasons, and I don't really love the idea of adding a [ ] generate unit test option to the new project wizard - I'd prefer to keep that simple and ask the user as few questions as possible.

**Comment by pq** [comment]
I agree that having tests generated is useful and would be reluctant to make things complicated with extra options for project creation.

@devoncarew and I just chatted and one thought is that we could get around the reload issue by having the check that blocks it filter out analysis issues with tests.  It seems like that might be what we want anyway.

**Comment by LarkAscending** [comment]
Any sample app that you want to use and tweak, you'd do this for. In this case I pasted the step_0 starting point (its main.dart contents) for the Firebase codelab. It also happens at the beginning of the UI codelab. So every codelab user will run into it... and every user who wants to start with one of our examples and build from there.

Note that it's not really our (the team's) use case - we tend to do what @devoncarew describes.

Commenting out the line in widget_test.dart makes the error condition in the nav panel go away...but I'm not able to do a runtime test right now to see what happens.

**Comment by pq** [comment]
> Can we provide a refactor hint in the IDE 

In theory, if we use the refactor action in the IDE, test references should get renamed

![image](https://user-images.githubusercontent.com/67586/32021010-eb1f111a-b986-11e7-8db8-40b58b3fdaa8.png)

Unfortunately it looks like constructor calls in corresponding tests are not getting renamed (though they should be) --- tracking https://github.com/dart-lang/sdk/issues/31224.

**Comment by pq** [comment]
Update: after chatting w/ @scheglov, it looks like the rename refactoring limitation is due to the template using a relative file import; updating to a package uri fixes it.

![image](https://user-images.githubusercontent.com/67586/32022185-7a232d58-b98a-11e7-8f72-8eca9c7ee531.png)


Since this is the preferred style anyway, I'll go ahead and update the template and then we could consider suggesting the rename refactoring if we want to have the test template updated in the tutorial.

**Comment by pq** [comment]
FWIW: test template updated w/ https://github.com/flutter/flutter/commit/2b2b3ab51695206c1c47a8193cb7fe89ce5644c8.

**Comment by InMatrix** [comment]
Just to make sure I understand it correctly, the updated test template helps the user to change the widget name of their main.dart and the widget name in their test the same time through a refactor operation. This is definitely helpful, but the use case in question here involves copying code from a tutorial and replace the app template with the tutorial code. Thus, there won't be an explicit renaming operation performed by the user. 

I'd suggest we exclude errors in tests from blocking Reload on Save. To reduce visual distraction, augment this error message "error: Undefined class 'MyApp'. (undefined_class at [testing] test/widget_test.dart:15)" with something like "error: Undefined class 'MyApp'. (undefined_class at [testing] test/widget_test.dart:15. hint: Make sure your the class name in your test and your main.dart match."

**Comment by pq** [comment]
> Just to make sure I understand it correctly, the updated test template helps the user to change the widget name of their main.dart and the widget name in their test the same time through a refactor operation. 

Correct.

> I'd suggest we exclude errors in tests from blocking Reload on Save.

Agreed.  Tracking: https://github.com/flutter/flutter-intellij/issues/1437

> To reduce visual distraction, augment this error message "error: Undefined class 'MyApp'. (undefined_class at [testing] test/widget_test.dart:15)" with something like "error: Undefined class 'MyApp'. (undefined_class at [testing] test/widget_test.dart:15. hint: Make sure your the class name in your test and your main.dart match."

cc @bwilkerson

**Comment by LarkAscending** [comment]
This sounds great - looking forward to seeing it!

@bwilkerson Could we make the `Undefined class...` message into a warning? The app still runs, and this was surprising. Do we have criteria for when a message is an error vs. warning?

**Comment by devoncarew** [comment]
Closing this one (we addressed the test template change - to fix an issue refactoring, and now no longer block reload if there are analysis issues in `test/`)

**Comment by craiglabenz** [comment]
For what it's worth, I am following tutorials [Codelabs tutorials like this one](https://codelabs.developers.google.com/codelabs/flutter/#3) and began running into this problem immediately. It wasn't until I found this thread that I was certain I wasn't doing something horribly, horribly wrong.

The error does also seem to still lock up hot reloading, requiring a simulator restart.
