### ISSUE TITLE
provide feedback in the new project wizard when the user has entered a correct flutter sdk location

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1436]
Like in the Flutter settings page, when a correct sdk is entered in the new project wizard, we should provide some feedback in the wizard page. The settings page displays the results of running `flutter --version`. Not sure if that is necessary for the project wizard, but some positive feedback would be great.

**Comment by stevemessick** [comment]
Fixed with https://github.com/flutter/flutter-intellij/pull/1469
