### ISSUE TITLE
doctor doesn't report a flutter plugin in Android Studio

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1438]
## Steps to Reproduce

1. Install Android Studio 3.0
1. Install Flutter plugin
1. Run `flutter doctor`

=> the plugin is not reported as installed:

```
[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

```

**Comment by mit-mit** [comment]
@devoncarew I'm tagging this M19 as this will make it really hard for us to troubleshoot, LMK if you disagree

**Comment by devoncarew** [comment]
No, makes sense. I have this on a short-list of my own, off-line.

**Comment by scheglov** [comment]
Fixed in https://github.com/flutter/flutter/pull/16198
