### ISSUE TITLE
Can't run `test` or `testWidget` tests individually inside a `group`

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#1439]
Hey hey, thanks for all the hard work on the plugin :) Getting better and better!

When a `test` or `testWidgets` test is embedded inside a `group` in a Flutter project, the tests cannot be run individually. When I try to run the tests individually, it runs the entire `group`. It would be amazing if the `test` / `testWidgets` could be run / debugged individually.

Overall, there is some funny stuff happening:

In a "Flutter Project" in Webstorm:

  1. `testWidget` tests always shows that it will be run as a group. When "Run button" is clicked, entire group of tests execute.
  2. `test` tests show they will be run individually, but when "Run Button" is clicked, the entire group is in fact executed.
  3. Using the "Run Context Configuration" keyboard shortcut within a `test` or `testWidget` inside a `group` causes the whole `group` to be run.
  4. Importing `package:test/test.dart` instead of `package:flutter_test/flutter_test.dart` had no impact.

In a "Normal Dart" project in Webstorm:

  1. `test` tests do not show "Run buttons", but can in fact be run / debugged individually using the "Run Context Configuration" keyboard shortcut.

## Steps to Reproduce

  1. Create a new flutter project
  2. Create a new file under `test/group_test.dart`
  3. Paste the code below into the file
  4. Attempt to run / debug each test individually using Run Buttons and Keyboard Shortcuts
  5. Do the same thing, but starting from a normal Dart project instead of a Flutter project (removing the `testWidget` test and changing the import to the normal `test` package) to see the difference.

```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('The Entire Group', () {
    test('seems to indicate individual run works fine, but it still runs the whole group.', () {
      expect(true, true);
    });

    testWidgets('always runs in a group', (tester) {
      expect(true, true);
    });
  });
}
```

## Screenshots

<img width="861" alt="screen shot 2017-10-26 at 3 18 23 pm" src="https://user-images.githubusercontent.com/126604/32055085-f094c0ec-ba60-11e7-984c-7a3f394af75a.png">

<img width="866" alt="screen shot 2017-10-26 at 3 18 17 pm" src="https://user-images.githubusercontent.com/126604/32055087-f29365ce-ba60-11e7-98f6-c013a231cea9.png">

## Version info

[✓] Flutter (on Mac OS X 10.13 17A405, locale en-US, channel master)
    • Flutter at /Users/phillywiggins/lab/flutter
    • Framework revision cbfed1960f (23 hours ago), 2017-10-25 07:18:09 -0700
    • Engine revision ec19da1c80
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/phillywiggins/Library/Android/sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/phillywiggins/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.3)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[✓] Connected devices
    • None

**Comment by devoncarew** [comment]
> Hey hey, thanks for all the hard work on the plugin :) Getting better and better!

Thanks for the feedback! Much appreciated :)

/cc'ing @pq for general triage - he's much more familiar with our `flutter test` support

**Comment by pq** [comment]
Thanks for this @brianegan ! The group support is a little fiddly so I'll take a look.

**Comment by brianegan** [comment]
Yay! Thanks for fixing this up :)

**Comment by pq** [comment]
Of course.  Thanks for the report!
