### ISSUE TITLE
'did not reload'-messages overflow

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1440]
<img width="1017" alt="screen shot 2017-10-26 at 16 37 13" src="https://user-images.githubusercontent.com/13644170/32059312-007032b6-ba6c-11e7-8e7d-b1ff92487000.png">

**Comment by devoncarew** [comment]
We'll likely want to tweak the message from the CLI so that is display better both in IntelliJ, and wraps in the terminal as well.
