### ISSUE TITLE
flutter launch configs automatically created for non-flutter projects

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1441]
It looks like we're auto-creating launch configs (for things like lib/main.dart) for projects that are not flutter projects. I think this is another case where we need to have a slightly more specific 'is flutter' check.

I think my set up is a non-flutter dart project, with the flutter sdk set as the dart sdk.

**Comment by devoncarew** [comment]
@pq, do you mind tackling? I suspect the resolution will be the same as the flutter test issue.

**Comment by pq** [comment]
Good catch!  I'll take a look. 👍
