### ISSUE TITLE
back-port flutter check to the dart plugin

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1449]
I think we need to update the Dart plugin's version of the 'is flutter' check. The current Flutter plugin one is here: https://github.com/flutter/flutter-intellij/blob/42c1bf74ca59b41d692b6ab0fa65931aa45fd904/src/io/flutter/pub/PubRoot.java#L277

@jwren is this something you can take care of? My understanding is that this will help out a few things, like double-notification of pubspec.yaml editor header contributions.

(details in https://github.com/flutter/flutter-intellij/issues/1261#issuecomment-339808741)

**Comment by jwren** [comment]
@devoncarew Yes, I'll take it.
