### ISSUE TITLE
.idea/libraries/Flutter_Plugins.xml file is created in non-Flutter project

### ISSUE THREAD

**Issue by alexander-doroshko** [flutter/flutter-intellij#1459]
IntelliJ IDEA 2017.3 EAP (173.3531.6), Flutter plugin 18.3 installed.

I opened a pure Java project and noticed that `.idea/libraries/Flutter_Plugins.xml` has been created with the following content:
```
<component name="libraryTable">
  <library name="Flutter Plugins" type="FlutterPluginsLibraryType">
    <CLASSES />
    <JAVADOC />
    <SOURCES />
  </library>
</component>
```

I guess you want to create this library only for Flutter projects and only when the lib is not empty. 

Probably you also want to auto-add an order entry for Flutter-aware modules pointing to this library, keep library up-to-date as project structure changes, and auto-add/-remove order entries as Flutter-aware module set changes. Or maybe you already do it, I didn't try to create Flutter-aware modules in my Java project :).

**Comment by devoncarew** [comment]
Thanks for the tips! This is the class where we're managing the flutter library entries: 

https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/sdk/FlutterPluginsLibraryManager.java

Sounds like minimally we'll want to scope it to things that are just Flutter modules.
