### ISSUE TITLE
Unclear what to open in firebase codelab

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1480]
RE: https://codelabs.developers.google.com/codelabs/flutter-firebase/#3

It's not clear which directory the developer is expected to open here.

I think the user is expected to open `friendlychat-steps/full_steps/step_0_offline/` ?

Also, is the test comment still relevant now that the user is cloning the github repo to get the files?

**Comment by LarkAscending** [comment]
Clarified to say "step_0_offline", as shown in the previous step.
