### ISSUE TITLE
ask for feedback on the inspector after it's been used n times

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1483]
We should invite the user, via a notification in IJ, to fill out a feedback form when they've used the inspector for more than X times.

/cc @jacob314 @mit-mit @InMatrix @pq

**Comment by jacob314** [comment]
Closing as we got 90+ feedback comment submissions from the inspector feedback link.
We're not likely to want to get more feedback from IntelliJ users but we will want extra feedback from VSCode users.
