### ISSUE TITLE
truncated Flutter icon in the new project wizard in android studio

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1499]
When testing on windows, I notice that the Flutter icon in the header of the new project wizard in android studio is truncated. I don't see this on the mac. Mac image is:

<img width="313" alt="screen shot 2017-11-10 at 1 59 31 pm" src="https://user-images.githubusercontent.com/1269969/32680453-9158a9d4-c61f-11e7-9075-383277b6c528.png">

(will post the windows image shortly).

This _may_ not be a windows / mac thing. The display of the windows device I tested on might not be an HD display. Perhaps the flutter image we're using doesn't support HD and non-HD displays (it doesn't have a fall back image)?

/cc @stevemessick

**Comment by stevemessick** [comment]
That's a good guess. I don't recall making fall-back images.
