### ISSUE TITLE
Closing Labels & Custom Line spacing

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#1514]
Hey hey :) 

The Line Spacing of the Closing Labels does not match the Line Spacing set in my "Color Scheme Font" settings.

Thanks for any help!

## Steps to Reproduce

  * Open Preferences
  * Navigate to Editor > Color Scheme > Color Scheme Font
  * Set a custom line spacing (using 2.0 or greater makes the problem very easy to spot).
  * Close the settings and open a Dart file with Closing Labels
  * Inspect the Closing Labels. They will not sit properly on the same baseline as the editor font.

## Screenshot

Using 2.0 line spacing for effect, but easy to spot with even 1.2 line spacing:

<img width="315" alt="screen shot 2017-11-19 at 12 32 40 pm" src="https://user-images.githubusercontent.com/126604/32990242-7752e014-cd26-11e7-8eff-5db65033f8c1.png">

## Version info

Flutter Doctor only reports the stable version of IntelliJ installed, but I'm using:

IntelliJ IDEA 2017.3 EAP (Community Edition)
Build #IC-173.3727.22, built on November 15, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1
Flutter plugin version: 19.1

**Comment by devoncarew** [comment]
Thanks for the report! You are seeing a new feature (closing labels) from the EAP version of the Dart plugin.

Closing labels are built on text inlays from IntelliJ. The debugger leave behind values also use this feature. I don't see this behavior in the debugger inlays, so they must be accounting for the line spacing:

<img width="472" alt="screen shot 2017-11-19 at 1 09 08 pm" src="https://user-images.githubusercontent.com/1269969/32995549-db29ed86-cd2a-11e7-9de6-ebb131edea2d.png">
