### ISSUE TITLE
Tune the wording of install-Dart-plugin prompt in Android Studio

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter-intellij#1517]
## Steps to Reproduce

Go through workflow to install Flutter plugin in AS. Click install, get this prompt:

![image](https://user-images.githubusercontent.com/23464935/33049940-2cbeacee-ce17-11e7-82e3-d4c721cf7411.png)

Could we change the wording of the text message? To something like:
```The plugin you want to install requires another plugin (Dart) to be installed as well. Proceed?```

**Comment by stevemessick** [comment]
This is reproducible in IntelliJ. Filed:
https://youtrack.jetbrains.com/issue/JRE-583

**Comment by devoncarew** [comment]
Closing in favor of the jetbrains issue.
