### ISSUE TITLE
Error running when no connecting device...

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#152]
I have no connected device but I'd like to use the simulator.

![screen shot 2016-09-26 at 1 19 03 pm](https://cloud.githubusercontent.com/assets/67586/18850313/dcbdce58-83eb-11e6-886b-4f77bf473342.png)

The old flow gave you a prompt to start the simulator (and would do it for you which was awesome since I have no idea where it lives!).  Can we do something similar?

**Comment by devoncarew** [comment]
Perhaps we can add a menu item to the bottom of the device selector pulldown, w/ the option to open the simulator?

**Comment by pq** [comment]
Closing in favor of https://github.com/flutter/flutter-intellij/issues/182
