### ISSUE TITLE
"Open in Xcode..." opens project (not workspace) for plugin projects.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1526]
Currently when opening an Xcode project for a plugin project from IntelliJ, we scan `example/ios/` and look for the first project file.  I *believe* this would work better if we preferred the workspace file (e.g., `Runner.xcworkspace`).

Paging @xster, @collinjackson, or @cbracken to confirm.

**Comment by cbracken** [comment]
@pq the workspace file is definitely what you want to open, if present.

If the logic in question is relatively old, it's possible it dates back to the pre-CocoaPods days when the workspace file may not have been part of our `flutter create` template.

**Comment by pq** [comment]
Awesome.  Thanks a million! 👍
