### ISSUE TITLE
Crash (WidgetInspectorService?)

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#1529]
## What happened

I started using the widget inspector and received an error. Then, after opening the project up again, the error reappeared.

## Version information

IntelliJ IDEA `2017.3` • Flutter plugin `io.flutter 19.1` • Dart plugin `173.3727.69`

Flutter • channel alpha • git@github.com:flutter/flutter.git
Framework • revision e8aa40eddd (6 weeks ago) • 2017-10-17 15:42:40 -0700
Engine • revision 7c4142808c
Tools • Dart 1.25.0-dev.11.0

## Exception
```
Error evaluating expression:
Unhandled exception:
NoSuchMethodError: No top-level getter 'WidgetInspectorService' declared.
Receiver: top-level
Tried calling: WidgetInspectorService
#0      NoSuchMethodError._throwNew (dart:core-patch/dart:core/errors_patch.dart:192)
#1      Eval (evaluate:source:1:11)
```

```
java.lang.Throwable: Error evaluating expression:
Unhandled exception:
NoSuchMethodError: No top-level getter 'WidgetInspectorService' declared.
Receiver: top-level
Tried calling: WidgetInspectorService
#0      NoSuchMethodError._throwNew (dart:core-patch/dart:core/errors_patch.dart:192)
#1      Eval (evaluate:source:1:11)

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at io.flutter.inspector.EvalOnDartLibrary$1.received(EvalOnDartLibrary.java:98)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:456)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by devoncarew** [comment]
> I started using the widget inspector and received an error.

Yup, we need to land a companion PR into the Flutter framework to support some inspector introspection: https://github.com/flutter/flutter/pull/12932

Your best bet for trying out the inspector is to wait for that PR to land. You_could_ try patching `jacob314:inspector_service_review` into your local flutter checkout, but that's going to be a lot more work than just waiting.

/cc @jacob314 @pq

**Comment by jacob314** [comment]
The pull request has landed . The inspector is still pre-alpha but please try it out and let me know what other issues and crashes you hit.
