### ISSUE TITLE
Better messaging on failed connect

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#153]
Saw this in my simulator...

![screen shot 2016-09-26 at 1 25 40 pm](https://cloud.githubusercontent.com/assets/67586/18850679/6856074a-83ed-11e6-8317-7271ac7b301c.png)

and then quite small in my console:

![screen shot 2016-09-26 at 1 29 55 pm](https://cloud.githubusercontent.com/assets/67586/18850687/7311a89c-83ed-11e6-8dd4-7ab22a2e4ce9.png)

Unless this is totally transient, we should probably make this more prominent?

**Comment by pq** [comment]
OK, a few more details:

- restart (of intellij) helped
- @stevemessick suggested that maybe the device list was corrupted...
- I was connecting to the iOS simulator and at least for some time at the beginning had an actual iPhone plugged in...

**Comment by stevemessick** [comment]
For a while you could only successfully launch a flutter app once. Then you had to restart the IDE to reinitialize the daemon manager. That's been fixed.

**Comment by pq** [comment]
Agreed.  It's so much better!

That said, I still think we need better messages when we have issues connecting.  When Observatory times out for example...

Or are you promising that'll never happen? 😉
