### ISSUE TITLE
exception from inspector: FlutterError('Looking up a deactivated widget's ancestor is unsafe')

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1543]
This check is in framework.dart, `_debugCheckStateIsActiveForAncestorLoopkup()`. Not sure of the specific repro steps here, but was inspecting widgets in the device, and then selecting node in the widget tree.

@jacob314

**Comment by jacob314** [comment]
This one is an edge case we should be able to handle better by checking whether widgets are active before we perform certain operations.

**Comment by jacob314** [comment]
This appears to have been related to the lifecycle bug where we were attempting to access a stale widget after a full reload. If you are still able to reproduce please reactivate.
