### ISSUE TITLE
add default implementation when generating override method with @mustCallSuper

### ISSUE THREAD

**Issue by jerrywell** [flutter/flutter-intellij#1551]
@mustCallSuper is pretty good tip in development.

When we generate override method, It would be better if automatically add super.xxxx() statement where this method is marked as @mustCallSuper.

Thanks so much.

**Comment by stevemessick** [comment]
That's a great idea. I think it is something to add to the Dart plugin, though.

@alexander-doroshko

**Comment by pq** [comment]
@alexander-doroshko : is this codegen coming from the Dart plugin or from the server?

**Comment by alexander-doroshko** [comment]
"Override methods" and "Generate" actions are implemented fully on the Dart plugin end. Tracked as https://youtrack.jetbrains.com/issue/WEB-30145

**Comment by devoncarew** [comment]
@pq, will the deps from the Dart plugin be available in this timeframe (M23)? If no, let's bump this now.

**Comment by pq** [comment]
Nope.  Bumped.

**Comment by pq** [comment]
FWIW: this is _partially_ implemented as of `173.4700`.  If you use code completion to generate an overriding method it goes through the analysis server and "just works":

![mar-21-2018 09-19-10](https://user-images.githubusercontent.com/67586/37722322-f9c2b214-2ce8-11e8-869e-88b7b5a94e42.gif)

**Comment by pq** [comment]
Improving generate actions is part of a larger arc of work that will span server and the Dart Plugin.  Closing this issue in favor of tracking in [WEB-30145](https://youtrack.jetbrains.com/issue/WEB-30145).

**Comment by jerrywell** [comment]
@pq, though it's a bit late, thank you for the explanation :)

**Comment by pq** [comment]
My pleasure.  Thanks for the feedback!
