### ISSUE TITLE
Inspect Mode throwing exception after first touch.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#1555]
## What happened

I had turned on "Inspect Mode", and I tapped an item, and after it highlighted, I couldn't tap on anything else, and this threw an exception.

## Version information

IntelliJ IDEA `2017.2.6` • Flutter plugin `io.flutter 19.1` • Dart plugin `172.4343.25`

Flutter • channel unknown • unknown source
Framework • revision ccaa88a5cb (74 minutes ago) • 2017-12-01 13:24:08 -0800
Engine • revision 77d8acb9be
Tools • Dart 1.25.0-dev.11.0

## Exception

```
Error evaluating expression:
Unhandled exception:
NoSuchMethodError: Class 'WidgetInspectorService' has no instance method 'maybeSetSelectionRaw'.
Receiver: Instance of 'WidgetInspectorService'
Tried calling: maybeSetSelectionRaw(Instance of 'RenderParagraph', "intellij_inspector_0")
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Eval (evaluate:source:1:43)
```

```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at io.flutter.inspector.EvalOnDartLibrary$1.received(EvalOnDartLibrary.java:98)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:455)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by devoncarew** [comment]
/cc @jacob314 

What I suspect is happening here is that the 19.1 version of the plugin is talking slightly older inspect protocols; we've updated them for the (not quite yet released) M20 release.

**Comment by pq** [comment]
@jacob314 : I'm thinking this is probably now stale?

**Comment by jacob314** [comment]
Yes this is stale and indicates that the plugin and package:flutter versions are out of sync.
