### ISSUE TITLE
Dart and Flutter actions both showing on Flutter pubspec.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1557]
Sample project.

![image](https://user-images.githubusercontent.com/67586/33522629-fc3b5fb6-d7a5-11e7-9a57-ffdb26b926af.png)

> Android Studio 3.0.1
> Build #AI-171.4443003, built on November 9, 2017
> JRE: 1.8.0_152-release-915-b08 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Mac OS X 10.12.6
> 
> Dart Plugin: 171.442
> Flutter Plugin: 19.1
> 

Note sure if this is specific to AS or not.

/cc @jwren @stevemessick @alexander-doroshko

**Comment by devoncarew** [comment]
I believe this is due to the version of the Dart plugin in Android Studio.

**Comment by pq** [comment]
I think you're right.  Something to validate when it's updated.

**Comment by stevemessick** [comment]
Verified. This issue will be fixed with support for AS 3.1.
