### ISSUE TITLE
inspector icons don't include HD variants

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1558]
The icons for nodes in the inspector look pixelated on HD screens - we should add HD variants.

/cc @pq @jacob314

**Comment by pq** [comment]
As per our conversation, opting to disable the (non HD) category widgets in favor altogether until we have a better, more consistent set.

**Comment by jacob314** [comment]
I'd love to be able to demo with some icons at IO even if they are not ideal. I think the icons add some nice structure to the tree view.
