### ISSUE TITLE
Run config not selected on project creation.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1565]
When creating a new project in IDEA CE 2017.3, the default run config is created (and works) but is no longer selected in the run pull-down.

![image](https://user-images.githubusercontent.com/67586/33612493-89074d56-d986-11e7-9e4e-80e9aa3b4f71.png)

**Comment by pq** [comment]
cc @alexander-doroshko : in case this is the result of a platform change?

**Comment by alexander-doroshko** [comment]
Nothing I'm aware of. Do you call `RunManager.setSelectedConfiguration(settings)` like Dart plugin does?
