### ISSUE TITLE
Inspect icon should not be shown of 'enable inspector' preference is 'off'

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1566]
Right now we always show the inspector icon in the Flutter View toolstrip, and it just doesn't do anything if the preference is off. That is quite confusing.

cc @jacob314 @devoncarew

**Comment by jacob314** [comment]
Actually it does. You still see the inspector UI on device you just don't see the treeview in IntelliJ.

**Comment by mit-mit** [comment]
What would you use that for?

**Comment by jacob314** [comment]
Agreed it isn't nearly as useful without the IntelliJ UI. We can disable it
but that functionality has been available in IntelliJ for a couple
milestones. This isn't a new change.

**Comment by mit-mit** [comment]
I'd like to see the icon button tied to the preference until we feel the inspector is ready for general roll-out.

**Comment by jacob314** [comment]
Ok we'll put the icon back behind the preference.
