### ISSUE TITLE
Plugin builld failing to inject <version> tag in plugin.xml (for AS).

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1576]
When attempting to upload the 3.0 build, I was met with this:

![image](https://user-images.githubusercontent.com/67586/33688361-fa707cc4-da8f-11e7-9ac2-269d7ffeb0eb.png)

@devoncarew confirmed that it's missing.

cc @stevemessick

**Comment by devoncarew** [comment]
Yup :) We'll want to inject a tag similar to `<version>$myVersion</version>`.

**Comment by stevemessick** [comment]
You are not using the --release option, are you? This is WAI. If you were planning to use `plugin deploy` you'd have to use --release.

**Comment by devoncarew** [comment]
@stevemessick, you mean instead of `plugin build`, Phil should run `plugin build --release=20.0` or similar? That that will inject the correct version info (and likely, also do things like ensure that it's being run from a release_20 branch`)?

**Comment by stevemessick** [comment]
@devoncarew Yes, that's what the intent is. If the value is "20.0" then the branch should be "release_20.0". Or, if the branch is "release_20" the command would be `plugin --release=20 build`. The --release option is global so goes before the command. In either case, the actual value of the option would be inserted into the <version> tag.

@pq We can talk about what should be the default. I chose this way just so there'd be fewer chances to mess up the upload. Which, in this case, worked as expected even though it doesn't look like it :) My concern is that I'd accidentally upload when I didn't intend to if --release were not required for deployment. I thought people would want to use `plugin build` somewhat often for local testing. If that's not the case then changing the default would make sense.

**Comment by devoncarew** [comment]
We may want to tweak is slightly so that `20.x` releases must release from a `release_20` branch; as in, each major version gets its own branch, but you can release 20.1 from the `release_20` branch.

An related, we should either fail if `20` is passed to --release, or auto convert to 20.0; thoughts?

**Comment by stevemessick** [comment]
I think this has been resolved with various patches.
