### ISSUE TITLE
Synthetic closing tags don't seem to adhere to line heights

### ISSUE THREAD

**Issue by lukef** [flutter/flutter-intellij#1593]
## Version Info

IntelliJ IDEA 2017.3 (Ultimate Edition)
Build #IU-173.3727.127, built on November 27, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Flutter plugin: 20.0.3

## Editor settings
**NOTE**: *I'm using a hidpi screen so not sure how font sizes translate. windows is set to 200% scaling and resolution is 3000x2000*

Font: Roboto Mono
Text size: 28
Line spacing: 1.7

## Issue

When using the above settings the closing tags do not line up with the source code. See below:

![image](https://user-images.githubusercontent.com/37941/33897397-2daaec44-df1a-11e7-8fad-ab23389c2ffd.png)

**Comment by devoncarew** [comment]
This was fixed here: https://github.com/flutter/flutter-intellij/issues/1514, but the fix may not be in the version of the Dart plugin that you're using. What version are you on? (/cc @alexander-doroshko )

**Comment by lukef** [comment]
I'm using `173.3727.108` of the dart plugin

**Comment by alexander-doroshko** [comment]
Yep, fixed in 2017.3.1 EAP. You may switch to EAP update channel in Settings | Appearance & Behavior | System Settings | Updates.

**Comment by lukef** [comment]
Thanks! closing. sorry for the dupe.
