### ISSUE TITLE
If two simulators are running only one of them hot reloads

### ISSUE THREAD

**Issue by IljaDaderko** [flutter/flutter-intellij#1595]
## Steps to Reproduce
1) Create new project using Intellij
2) Start iOS simulator
3) Start Android simulator
4) Change something in the app

Result: Only Android simulator refreshes

## Version info
```
[✓] IntelliJ IDEA Community Edition (version 2017.3.1)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3942.31
```

![demo](https://i.stack.imgur.com/G6VJ2.gif)

**Comment by devoncarew** [comment]
Thanks for the report! I think what's happening is that you have two separate app instances running, and you're reloading the one that IntelliJ thinks is currently active. You should be able to change that by selecting a different tab in the 'Run' view.

**Comment by Odaym** [comment]
There's already a Stop All button at the far right of the toolbar at the top, see screenshot http://snpy.in/wmryPE

Please have a Run All ? :D
