### ISSUE TITLE
Feature Request: Add Code Folding for Multi-Line Parenthesis

### ISSUE THREAD

**Issue by MarkTechson** [flutter/flutter-intellij#1596]
Hello,

Given the following snippet (in any method):
```
return new Scaffold(
      body: new Column(
        children: <Widget>[
          new Expanded(
            child: new Container(
              decoration: new BoxDecoration(border: new Border.all(color: Colors.black), color: appMainColor),
              child: new Text("Hello, World")
            )
          ),
          
        ],
      )
    );
```
I would like the ability to fold any of the widgets here between the parenthesis. Folding the container widget would yield something like:
```
return new Scaffold(
      body: new Column(
        children: <Widget>[
          new Expanded(
+            child: new Container(...)
          ),
        ],
      )
    );
```

The behavior would work the same as code folding with `{}`
Please let me know if there are any questions.

**Comment by mit-mit** [comment]
cc @devoncarew is this something we can control, or do we need this from the core JB plugin?

**Comment by alexander-doroshko** [comment]
Analysis Server provides 'code folding' feature, but as of now the Dart plugin doesn't use it and implements the feature itself. The plugin also allows configuring what is collapsed by default (Preferenes | Editor | General | Code Folding page).

**Comment by pq** [comment]
cc @bwilkerson @scheglov

**Comment by scheglov** [comment]
That's correct that Analysis Server has API for folding.
But practically it is not implemented for Dart files.

**Comment by bwilkerson** [comment]
It isn't implemented because it isn't used, but I expect it would be easy to implement it, and preferable (IMO) to enhancing the implementation in the IntelliJ-specific plugin.

**Comment by devoncarew** [comment]
@jwren, does the folding you implemented a while ago for constructors cover this?

**Comment by jwren** [comment]
Yes this is a description of the feature added, 2017.2 (I think).

Documentation and key mappings can be found here: https://www.jetbrains.com/help/idea/folding-code-elements.html

**Comment by cyrsis** [comment]
Is it possible add if  else if?

**Comment by jwren** [comment]
What is the question?  Folding of content between {...} in if and if-else statements?

Typically we default to Java behavior (not that we did here) in IntelliJ, which does allow this.

The support is added here: `intellij-plugins/Dart/src/com/jetbrains/lang/dart/folding/DartFoldingBuilder.java`, and is possible.

Creating an issue here:
https://youtrack.jetbrains.com/issue/WEB-40471
