### ISSUE TITLE
Track widget creation locations

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#1597]
Write Kernel transformer to track Widget creation locations and implement IntelliJ support for using the widget creation locations.  
This should give accurate filtering to just widgets created in the user’s project and true “jump to creation location”

**Comment by brianegan** [comment]
Just some user feedback -- this is definitely my #1 feature request for the Inspector.

Amazing work thus far, thanks for making it so cool :)

**Comment by devoncarew** [comment]
@jacob314, is this in for M22 (release being cut today)?

**Comment by jacob314** [comment]
Yes! This is in for M22.
It is in for flutter master (the flutter engine dependency just got updated) as of last night so you won't be able to take advantage of it yet unless your flutter is on master.

To try out run your flutter app with:
--preview-dart-2 --track-widget-creation

We're definitely interested in any cases where your app seems like it is running more slowly or differently with the --track-widget-creation flag as it does change whether certain const widget objects are identical. In practice the impact should be tiny but there is a risk.

**Comment by devoncarew** [comment]
User's would pass `--track-widget-creation` in the additional args flags of their launch configuration?
