### ISSUE TITLE
Filter Widget Inspector by widget category

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#1598]
We have the categories defined here available and we are using them to display icons.
https://flutter.io/widgets/
Support filtering to hide widgets of certain categories. For example, hide all event listener widgets
We need a list of which categories to show icons for on the top of the inspector window.

**Comment by devoncarew** [comment]
Still something we think we should do?

**Comment by jacob314** [comment]
This is no-longer a direction we want to pursue. Closing.
