### ISSUE TITLE
Inspector Property display polish -- default values

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#1603]
Showing default values in gray is not clear. Should switch to showing the word “default” in parens next to properties that match the default value.
We have the UI space to do this and it will reduce user confusion.

**Comment by jacob314** [comment]
Default values are now shown as follows with 
![image](https://user-images.githubusercontent.com/1226812/38893105-353cc18a-423e-11e8-9fd8-962c23188eb1.png)

https://github.com/flutter/flutter-intellij/pull/2094

**Comment by devoncarew** [comment]
this sounds done?
