### ISSUE TITLE
Better status messages when the inspector is not (yet) available.

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#1606]
The inspector panel says “Nothing to show” by default. We should better use this space to show the current state of the inspector (e.g., waiting for files to be sync’ed to the device, etc) and show instructions about how to enter the inspector mode and select element from the on-device UI.

**Comment by devoncarew** [comment]
Some work on this done here: https://github.com/flutter/flutter-intellij/pull/1676. Perhaps enough to close this issue?

**Comment by devoncarew** [comment]
Closing as I think we've addressed the main issue; @jacob314, feel free to re-open if you think there's more work we should do here.
