### ISSUE TITLE
AnsiTerminal not populated correctly in the flutter_tools context for daemon runs

### ISSUE THREAD

**Issue by zzzev** [flutter/flutter-intellij#1614]
Since updating to version 20 of the plug-in, when I run any flutter app in IntelliJ, it launches successfully, but then shows this error in the console (before any output from my app):

```
Error -32603 received from application: Internal error
Error initializing DevFS: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("uri")
Unhandled exception:
NoSuchMethodError: The getter 'supportsColor' was called on null.
Receiver: null
Tried calling: supportsColor
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:79)
#2      _AppRunLogger.printStatus (package:flutter_tools/src/commands/daemon.dart:821)
#3      printStatus (package:flutter_tools/src/globals.dart:39)
#4      FlutterDevice.startEchoingDeviceLog.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:222)
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _DelayedData.perform (dart:async/stream_impl.dart:578)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#17     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:111)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
```

After this error, IntelliJ seems to think the run failed, so even though the app is running fine in the emulator, I cannot see any logged information. Based on the patch notes, I suspect this has to do with "improved console filtering" in version 20.

This does not happen when I run the app from the command line (i.e. not through IntelliJ), so I am almost certain this is an issue with the new version of the plug-in.

## Steps to Reproduce

1. Run any flutter app, observe console

## Version info

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

**Comment by zzzev** [comment]
After repro-ing this consistently all day in IntelliJ, this appears to have fixed itself. I have no idea what changed, but I'll go ahead and close this for now. Apologies for the (potentially?) false alarm.

**Comment by zzzev** [comment]
This is recurring again, though I'm not sure what changed. Would appreciate any insight into how to track this down and fix it.

**Comment by devoncarew** [comment]
As @tvolkert mentioned on an internal thread, it seems likely that `AnsiTerminal` is not being populated in the context for daemon (IDE) runs.

**Comment by devoncarew** [comment]
This issue was moved to flutter/flutter#13993
