### ISSUE TITLE
Response from http.get isn't printed as expected

### ISSUE THREAD

**Issue by elmcrest** [flutter/flutter-intellij#1615]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
I get some JSON from an public api endpoint and print it for playing with the response. It feels like collections or maybe just lists aren't printed in IntelliJ. As you can see in the attached screenshots the Observatory prints it correctly.

Let me know how I could provide further useful information.

![bug_report_android-studio_flutter](https://user-images.githubusercontent.com/931919/34648684-7aa1b1a2-f39e-11e7-8a80-0cfa5bf0ec48.jpeg)

![bug_report_android-studio_flutter2](https://user-images.githubusercontent.com/931919/34648685-7cc0d012-f39e-11e7-8a5c-817464148b73.jpeg)

## Version info

flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale de-DE, channel master)
    • Flutter at /Users/elmcrest/projects/flutter
    • Framework revision e25d881046 (2 days ago), 2018-01-05 09:38:13 -0800
    • Engine revision 43327730a2
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.8d7219a5b6a7c2505ff57f23e7cf80da4c724512

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/elmcrest/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • iPhone X • BE47EA75-6FE5-4D85-BA20-4252D87A2881 • ios • iOS 11.2 (simulator)

**Comment by devoncarew** [comment]
It looks like we may be filtering out stdout that's formatted as json. This could be happening on the `flutter_tools` side; if so it's likely an artifact of the communications channel (we use stdout to send channel commands, in the form `[{...}]`).
