### ISSUE TITLE
remove the preference for the inspector

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1617]
We should remove the preference for the inspector, and just enable it generally. It's the last pref in the experimental section, so we'll want to remove (or hide) that section in the UI.

@jacob314 @pq

**Comment by pq** [comment]
👍 

I'm in there right now so I'll take care of this.

**Comment by devoncarew** [comment]
Cool; https://github.com/flutter/flutter-intellij/pull/1616 landed, which was the 2nd to last option in the experimental pref section.
