### ISSUE TITLE
Trouble running widget tests w/ 2 IDEA instances running

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#1622]
I used to be able to right-click on the code of a flutter test and select "Run \<test name\>" from the context menu. Recently, this started producing the following error in the UI instead of running the test:

```
2:23 PM	Error running 'Semantics tree is populated mid-scroll': @NotNull method io/flutter/run/test/TestLaunchState.startProcess must not return null
```

**Comment by devoncarew** [comment]
@pq, do you mind taking a look?

**Comment by devoncarew** [comment]
@goderbauer, can you include the output of `flutter doctor` (esp. the IntelliJ and Flutter plugin versions)?

**Comment by goderbauer** [comment]
```
[✓] Flutter (on Mac OS X 10.12.6 16G1114, locale en-US, channel unknown)
    • Flutter at /Users/goderbauer/dev/flutter
    • Framework revision d813328de7 (4 hours ago), 2018-01-09 10:39:59 -0800
    • Engine revision 16e365e722
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.5b56dfb77a76e9d8021086c0684b1e8bd9dbca9a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/goderbauer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.1)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3942.31

[✓] Connected devices
    • Nexus 6P • 84B5T15A10012703                         • android-arm • Android 7.1.2 (API 25)
    • iPhone   • f1873c78c265cdc62dc1a2ea99a8e49c364feb2f • ios         • iOS 11.1
```

**Comment by goderbauer** [comment]
Ah! I think I figured this out! I have two instances of IntelliJ running with two different flutter apps. In one IntelliJ I had a test running, which was stoped at a break point. When I now try to run a test in the other IntelliJ instance, I am getting the error mentioned above.

Workaround for me is easy: Just don't have two tests running in parallel.

The error message should probably be clearer, though. And it's kinda unexpected that two IntelliJ instances block each other like that in the first place.

**Comment by pq** [comment]
Interesting.  Thanks for following up @goderbauer! 

What kind of tests are these (e.g., integration, widget or unit)?

**Comment by goderbauer** [comment]
They were widget tests.

**Comment by devoncarew** [comment]
> When I now try to run a test in the other IntelliJ instance, I am getting the error mentioned above.

We should track this down, that interaction is really not expected.

**Comment by pq** [comment]
Thanks @goderbauer!  I'll take a look.  Minimally, we should warn in this case.

**Comment by donaldking** [comment]
Hi guys, I'm getting this same problem now with flutter unit test. Has it been fixed? if so, what's the solution pls?
 
![Screenshot 2020-06-30 at 05 52 19](https://user-images.githubusercontent.com/4445659/86084922-dda9af00-ba95-11ea-88b0-ad118a82148f.png)

![Screenshot 2020-06-30 at 05 51 57](https://user-images.githubusercontent.com/4445659/86084880-d1bded00-ba95-11ea-8421-0360fac18edd.png)
