### ISSUE TITLE
Missing option of moving widgets in a list up and down 

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1638]
We currently show options in the "lightbulb" menu to:

  * Wrap with new widget
  * Change child<->children
  * Move up/down

However, up/down doesn't really move something up or down in a list, it moves something deeper/higher in the tree indentation level.

I suggest we rename 'move down' to 'swap with child', i.e. on this code selecting B and invoking swap with child would swap B and C:

```
A(
  child: B(
      child: C()
   )
)
```

And on the same code, 'swap with parent' on B would swap B and A.

With that, I suggest we also add new 'move up' and 'move down' actions. Invoking them on 2 in the following code would change the order to 2,1,3 and 1,3,2 respectively:

```
A(
   children: <Widget>[
      1
      2
      3
    ]
)
```

**Comment by mit-mit** [comment]
cc @devoncarew

**Comment by alexander-doroshko** [comment]
Just an idea: for some smart up/down moves 'Move Statement' action (Cmd+Shift+Up/Down, powered by the Analysis Server) might be adopted (cc @stevemessick).

**Comment by mit-mit** [comment]
Users are having trouble discovering the myriad of options available to them. I would really like if all the tree based operations were available in a single, consistent way.

**Comment by xster** [comment]
Conflating the 2 might be confusing. I think it might be cleaner for the refactor options to have 2 distinctly named functions:
- 'swap widget with parent / child' 
- and a general 'swap (general dart map/list) item with previous/next sibling'

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/41023

**Comment by scheglov** [comment]
Done.
![image](https://user-images.githubusercontent.com/384794/36178807-fc0e77be-10ce-11e8-9842-e614bd85ff41.png)

**Comment by xster** [comment]
Is the operation performed by 'Move widget up/down' dynamic now? If it's in the middle of a tree of single child widgets, it swaps with parent/child, when it's in a list, it swaps with previous/next sibling?

**Comment by scheglov** [comment]
The operations that were called `Move widget up/down` were replaced with `Swap with parent/child`.

And these new `Move widget up/down` work for siblings.

**Comment by xster** [comment]
Ah cool, awesome.

Thanks for the clarification.
