### ISSUE TITLE
Duplicate pub command bars

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#1641]
Config: Android Studio 3.0.1; Flutter plugin 21.0.1; no updates pending.

To reproduce: open the flutter gallery in Android Studio, close it, upgrade flutter, re-open it. My Dart SDK went from 1.25 to 2.0 so it had been awhile since upgrading Flutter; you'll need a modified gallery.

We're presented with two pub command bars (see screenshot) in the editor. One of them works, the other tells you to use the proper command. It is impossible to tell from the UI which to use.

<img width="1014" alt="screen shot 2018-01-18 at 8 32 25 am" src="https://user-images.githubusercontent.com/8518285/35109349-f67cb5f8-fc2a-11e7-9d94-e27779e45ea7.png">

**Comment by devoncarew** [comment]
I believe this is a known issue w/ older versions of the Dart plugin. It would be good to differentiate though.

With some editor notification we can badge them with an icon. This may not be the kind that we can, but if it is, we should show a flutter icon in ours.

**Comment by stevemessick** [comment]
Duplicate of #1557 

This issue will be fixed with support for AS 3.1.
