### ISSUE TITLE
Selected device should not appear in edit menu

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#166]
Here's how the menu looks with no device selected:
<img width="277" alt="screen shot 2016-09-27 at 3 06 12 pm" src="https://cloud.githubusercontent.com/assets/8518285/18893778/24b77a1e-84c4-11e6-9f55-08932c698526.png">
After making a selection it becomes clear what those two blue tick marks are:
<img width="275" alt="screen shot 2016-09-27 at 3 06 31 pm" src="https://cloud.githubusercontent.com/assets/8518285/18893780/29b8c5a4-84c4-11e6-9b21-1993c6edf7ec.png">

**Comment by pq** [comment]
Oh, ugh.  That's unfortunate.  Looks like a side-effect of how I contributed our drop-down.

**Comment by pq** [comment]
OK.  Got it.  Easy fix.  On the way...

**Comment by pq** [comment]
Great catch BTW.

Should be fixed w/ https://github.com/flutter/flutter-intellij/pull/174


![screen shot 2016-09-28 at 9 12 41 am](https://cloud.githubusercontent.com/assets/67586/18922084/2879310e-855c-11e6-9cd3-406ba0aa1c8a.png)
