### ISSUE TITLE
Inspector: Pan the widget tree when selecting a widget

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1660]
When you select a widget on the device, and we select the corresponding widget in the widget tree, it world be good to push the viewport to have the selected now positioned on the left and centered vertically.

**Comment by jacob314** [comment]
This is generally addressed by https://github.com/flutter/flutter-intellij/pull/2094
which animates all tree scrolls and auto-horizontal scrolls the tree at all times (unless the option is unchecked).
