### ISSUE TITLE
have a global flag to enable --preview-dart-2

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1667]
have a flag in launch configs to enable --preview-dart-2 and --strong

**Comment by devoncarew** [comment]
We should likely implement this as a flag in the preferences (instead of a launch config flag) to opt-into `--preview-dart-2`; that would pass the flag into both the analysis server and `flutter run`.

@alexander-doroshko, do you know if there's a way for the Flutter plugin to inject an additional CLI args into the flags used to start the analysis server? Would we have to do something like set the analysis server flags registry value?

**Comment by alexander-doroshko** [comment]
Yes, there's `dart.server.additional.arguments` Registry property that you can update both manually and programmatically. But it's a bit dangerous as Registry property value is one per app whereas Dart Server is one per project. So if you modify the property you change Dart Server behavior for all projects, not only the current one.
