### ISSUE TITLE
Inspector doesn't work if it is closed when app starts up

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#1679]
## Steps to Reproduce

Open an application with the inspector closed. Open the inspector after the app starts up.

Inspector does not work.

Workaround: make sure the inspector is open before the app arts.

**Comment by jacob314** [comment]
It is no-longer possible to start an application without the inspector open so this bug is fixed. Thanks @devoncarew !

**Comment by devoncarew** [comment]
@jacob314, I believe you said this doesn't repro anymore?

**Comment by devoncarew** [comment]
I'm closing this in anticipation of it no longer being an issue.
