### ISSUE TITLE
at runtime, check for and complain if the dart plugin version is less than our minimum

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#168]
We should show a toast if the Dart plugin version doesn't meet our minimum; currently `162.2233`.

**Comment by pq** [comment]
👍 

I'll take a look.

**Comment by pq** [comment]
👍

**Comment by pq** [comment]
<img width="740" alt="screen shot 2016-10-03 at 6 06 07 am" src="https://cloud.githubusercontent.com/assets/67586/19038239/8a979408-892f-11e6-923f-9e73f92cfd69.png">

Wordsmithing welcome!

/cc @mit-mit

**Comment by mit-mit** [comment]
Looks good! Maybe swap words so: 'Flutter requires a Dart plugin with a minimum version of 1.0 (currently installed: 0.0.0)'?

**Comment by pq** [comment]
Great.  Thanks!
