### ISSUE TITLE
Improve Widget Category Icons in the Inspector

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1683]
Follow-up from: https://github.com/flutter/flutter-intellij/pull/1682, we should review and improve the icons used to identify categories in the inspector.

Current widgets are stored here:

https://github.com/flutter/flutter-intellij/tree/master/resources/icons/inspector

and associated w/ categories here:

https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/inspector/FlutterWidget.java#L35

cc @InMatrix

**Comment by devoncarew** [comment]
This is un-assigned for M22; is this likely to happen in the M22 timeframe (~late next week)? If no, let's remove from the current milestone.

**Comment by pq** [comment]
👍

**Comment by devoncarew** [comment]
closing as likely stale; please re-open if that's not the case -

**Comment by AlexV525** [comment]
The legacy inspector has been removed. Should we close this?
