### ISSUE TITLE
improve discoverability of editing assists

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1691]
We should work on improving discovery of our existing code editing assist. This will likely include things like:

- ‘move statement’ - is this currently accessible via a quick assist?
- make sure all the existing refactorings are available from the quick assist menu; like like move up and move down
- have a Flutter specific context menu to make the assists easy to find

**Comment by mit-mit** [comment]
move up/down as an assist is https://github.com/flutter/flutter-intellij/issues/1638

**Comment by devoncarew** [comment]
I think this is complete now; the `Flutter specific context menu` we can consider to just be the opt-enter menu. We should document all this, to help with discoverability.
