### ISSUE TITLE
show memory usage in IntelliJ

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1698]
This may be dart heap usage, native allocation heap, resident memory process size, or all three. In any case, we want a live view of the memory usage of the user's app to allow them to have casual awareness of how much memory their app is using and whether there's an issue for them to dig into further.

**Comment by devoncarew** [comment]
This would likely show in the inspector view.

**Comment by devoncarew** [comment]
Generally, this seems complete? We can track tweaks and iterations in future issues.

**Comment by pq** [comment]
👍
