### ISSUE TITLE
Flutter Preview UI feedback

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1706]
Freeform feedback on the `Flutter Preview` view; if it's easier to track, we can break this into separate issues.

- ~for non-Dart files, we should show placeholder text in the view - `Nothing to display` or similar (the `Structure` view shows `No structure`)~
- long term, for non-Dart files, we may want to try and load in the provider that the Structure view would use for that file content
- for non-Flutter Dart files, we should disable (or hide) the editing toolbar. One drawback to hiding it would be that the view contents would jump up and down as you switch between Flutter and non-Flutter files
- ~we should sync selection from the editor to the view (currently, we sync from the view to the editor)~
- the selection sync seems off by one ast node (pointing to the end of the previous node)
- there's a lot of horizontal scrolling - we should minimize that as much as possible. That may be eliding text for closures that are attributes, or changing how and where we show attributes (a more custom display, and or a master details area)
- ~when changing the selection in the preview view using cursor keys (up, down, ...) we should sync the text editor position (we already do this for mouse clicks)~

/cc @scheglov

**Comment by scheglov** [comment]
Selection synching and navigation to Dart elements is fixed in https://github.com/flutter/flutter-intellij/pull/1710 . There are probably additional tweaks we want to do - don't scroll the tree on selection in the tree, and maybe expand covering source ranges for widgets (we should discuss it).

**Comment by scheglov** [comment]
Hiding structure and toolbar for non-Dar files is fixed in https://github.com/flutter/flutter-intellij/pull/1711.
