### ISSUE TITLE
Sort @required completion suggestions first.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1714]
Tracking for: https://github.com/flutter/flutter/issues/10219.

This will minimally involve a little server work  with a possible handshake on the Dart Plugin side.

**Comment by scheglov** [comment]
Did you fix this with https://dart-review.googlesource.com/c/sdk/+/38346?

**Comment by pq** [comment]
Yes.  We'll need to verify when a fresh SDK is pulled into Flutter but we can safely close this one.
