### ISSUE TITLE
Docs on inspector written on flutter.io (and / or existing docs updated)

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#1718]
Documents should explain basics of how to use the inspector properly.

Key topics:
* Linked widget and render object trees.
* How to select a widget on the device.
* Jumping to source location widgets were created at.

**Comment by devoncarew** [comment]
@jacob314, is this covered by https://flutter.io/inspector/, or did we want more comprehensive docs?

**Comment by jacob314** [comment]
We still need to add screenshots and text describing jumping to source location.

**Comment by devoncarew** [comment]
@jacob314, @Sfshaza indicated she's planning on working on the next iteration of these docs.

**Comment by Sfshaza** [comment]
This is true!

**Comment by devoncarew** [comment]
@Sfshaza, I'm going to move this out of the current milestone and into the 'On Deck' (pending) one. Please let us know how we can help here - providing notes / screenshots / ideas for what the docs should cover.

**Comment by jacob314** [comment]
https://flutter.github.io/devtools/inspector
Now has up to date documentation.
