### ISSUE TITLE
tracking issue to coordinate back-porting API and changes to the Dart plugin

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1747]
This is a tracking issue to coordinate work (existing and new) that we'd like to back-port to older versions of the Dart plugin. Currently, that means 2017.1, 2017.2 ,2017.3, and the up-coming 2018.1. A goal here is to end up with no reflection used in the Flutter plugin.

- Konstantin’s analysis server api change (https://github.com/JetBrains/intellij-plugins/pull/562)
- a new completion extension point (discussion here: https://youtrack.jetbrains.com/issue/WEB-31129)
- duplicated butter bar (todo: reference the change to back-port)
- DartDebugProcessZ (todo: spec out what we want to have available in order to make this code dup go away)
- the fix to exception breakpoint handlers (https://github.com/JetBrains/intellij-plugins/pull/561)
- `DartAnalysisServerService.getErrors()` and `DartExecutionHelper.displayIssues()` (https://github.com/JetBrains/intellij-plugins/commit/3da83a18a46d64502fda6982662f272a24ce96ec)
- The change to add `id` to `SourceChange` (https://github.com/JetBrains/intellij-plugins/pull/564).

@jwren @alexander-doroshko @pq @scheglov @stevemessick

**Comment by devoncarew** [comment]
@alexander-doroshko, I'm triaging our bugs - do you know which of these changes make it back to older Dart plugin versions? I remember we talked about only backporting as far as 2017.3. Do you have a list (or just some commits to link to)?

**Comment by alexander-doroshko** [comment]
Sorry for the delay with this. I'm going to handle it within a few days and post the details.

**Comment by alexander-doroshko** [comment]
Done. Details by email.

**Comment by devoncarew** [comment]
Thanks!
