### ISSUE TITLE
The horizontal scrollbar of the Inspector treeview is hidden by default on Mac

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#1751]
It's difficult to scroll horizontally on Mac unless I use a touchpad instead of mouse, because the horizontal scrollbar is hidden by default. 
 
![image](https://user-images.githubusercontent.com/348942/35948421-4175303e-0c21-11e8-8aa3-2835ee620faa.png)

**Comment by jacob314** [comment]
Closing as switching to the detail-summary tree model means horizontal scrolling is less crucial.
Automatically horizontal scrolling experiments also suggested that we can get quite far automatically scrolling content into view instead of making users scroll.
