### ISSUE TITLE
Offer contextual action to delete Widget

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter-intellij#1756]
Feature Request:
Currently there are contextual actions to create new Widgets as children, or wrap an existing Widget with a new parent.

It would be equally helpful to have a contextual action to delete a Widget from a given build() configuration.  It can be very tedious to try to extract a Widget in the middle of a deep tree.

**Comment by devoncarew** [comment]
You mean something like delete a widget, but keep it's children?

/cc @scheglov, @mit-mit

**Comment by matthew-carroll** [comment]
Yes, and also keep its parent.  For example:

Widget1
--Widget2
----Widget3 <--- DELETE THIS ONE
------Widget4

**Comment by scheglov** [comment]
Same as https://github.com/flutter/flutter-intellij/issues/1283#issuecomment-333376254, right?

**Comment by matthew-carroll** [comment]
Yeah I think #1283 is the same thing.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/40240
