### ISSUE TITLE
Special characters in Flutter project description break project

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter-intellij#1761]
## Steps to Reproduce

1. Launch the new project wizard
2. Enter a description for the project that includes a colon ":"
3. Create the project.

## Result

Project fails to open in IDEA correctly.  Some kind of error dialog pops up.  I was able to rectify the situation by opening the YAML file and removing the colon from the description and then relaunching the IDE.

## Version info

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter version 0.0.21 at [redacted]
    • Framework revision 2e449f06f0 (12 days ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at [redacted]
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1012-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

**Comment by devoncarew** [comment]
Sounds like we should likely filter the legal chars for the description field (I assume that this is breaking the yaml parser for the pubspec.yaml's `description:` field).

@pq and @stevemessick, who've both worked on the project wizards

**Comment by stevemessick** [comment]
It looks like we can quote the description with single-quotes. Embedded single-quotes need to be doubled. This could be called a Flutter tool issue.
```base
flutter create --description 'new: thing' foox
...
ERR : Error on line 2, column 17 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?
...
pub get failed (65)
```
