### ISSUE TITLE
some preview view labels are extremely long

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1762]
See for example the `items: <BottomNavigationBarItem>[...` param in `main.dart` of the dartconf app. The created label for the widget node is 1000+ chars long. We may want to special case array params (as we do for closures), or choose to elide much (or all?) of the text for labels that contain a newline.

<img width="338" alt="screen shot 2018-02-11 at 10 45 06 am" src="https://user-images.githubusercontent.com/1269969/36076984-09818308-0f19-11e8-9f38-b0eb0a03427f.png">

@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/40560

**Comment by devoncarew** [comment]
fixed
