### ISSUE TITLE
Make the initial view in flutter previewer easier to understand

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1765]
flutter previewer should default to showing a more restricted, easier to understand set of nodes, for example just build methods / methods that return a Widget.

I suggest we control this via a toggle in the tool bar, for example 'Show only UI nodes' that is defaulted to on.

cc @devoncarew

**Comment by devoncarew** [comment]
We could also look into look into eliding - but still showing the top-level of nodes - in the tree (`[ ] ... (21 nodes hidden)`). Not sure how that would work in practice. I'd mostly want to make it very clear and obvious that we weren't showing some content. I think a very real risk is that many users won't every know that we're excluding info.

/cc @scheglov  and @InMatrix

**Comment by InMatrix** [comment]
I can't really understand the problem without seeing some screenshots.

**Comment by devoncarew** [comment]
To update - we have a filter toolbar action, which we can use to evaluate the two options (showing the full file ast vs. just widget nodes).

**Comment by InMatrix** [comment]
@devoncarew Great. We should discuss what we need to measure before this filter ships in the next version.

**Comment by mit-mit** [comment]
@devoncarew what did you guys decide here?

**Comment by devoncarew** [comment]
There's a toggle currently (not yet released?) on the toolbar. When on, it only shows widgets and nodes that have widgets as children. It's defaulted to off, but should give us the tools to either get feedback or to do informal studies. (my personal preference is to show everything, but happy to change it if further data shows widgets only is preferred).

**Comment by mit-mit** [comment]
I thought we had data suggesting a very small percentage of users use outline view (i seem to recall 8%), and thus that seems to suggest we optimize for Flutter widget use cases rather than trying to also be a code outline view?

**Comment by devoncarew** [comment]
We do have that data, but I still have concerns about hiding data from the user by default, w/o them being aware of it. I was hoping some sort of A/B test would help get us clarity. Perhaps worth an in-person discussion.

**Comment by InMatrix** [comment]
From today's demo, I think some styling can be used to make the build method tree stand out from the rest of your code.

**Comment by mit-mit** [comment]
I also made some comments over in https://github.com/flutter/flutter-intellij/issues/1932#issuecomment-374277101

**Comment by scheglov** [comment]
@InMatrix We already show `build` methods in bold. Is there anything also we could do to highlight them?
![image](https://user-images.githubusercontent.com/384794/37935165-66aa42c8-3105-11e8-9963-8db791e2ea56.png)

The data we have about standard `Structure` view is flawed, we record usage only when the view is focused. But this view is "used" by looking and sometimes double clocking to immediately navigate to a new element, and lose focus again.

Anyway, we now show only widgets by default, and send analytics to track the state users use it with.

**Comment by InMatrix** [comment]
@scheglov If we show only widgets by default, then there is no need to further highlight them. I was thinking about giving build methods a light background color to visually separate them from the rest of the code, as a middle ground between showing only widgets and showing all.

**Comment by scheglov** [comment]
FWIW, we can highlight tree items with some background color.
https://github.com/flutter/flutter-intellij/pull/1793

If we don't need this, then I'm closing the issue.
