### ISSUE TITLE
Switch Bazel flag for launching apps

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter-intellij#1772]
https://github.com/flutter/flutter-intellij/blob/d69ce129f0486f481b607e0f762507b94448feb5/src/io/flutter/run/bazel/BazelFields.java#L243

That should be updated to be `"--fat_apk_cpu=" + arch`

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter-intellij/blob/d69ce129f0486f481b607e0f762507b94448feb5/src/io/flutter/run/bazel/BazelFields.java#L219

Similarly, that should be updated to be `"--ios_multi_cpus=" + arch`

**Comment by jwren** [comment]
https://github.com/flutter/flutter-intellij/pull/1775

**Comment by jwren** [comment]
This should be fixed on the master branch with the merge of https://github.com/flutter/flutter-intellij/pull/1775.

**Comment by devoncarew** [comment]
awesome! @tvolkert, users will see this change with the next release, on or around 2/26.

**Comment by tvolkert** [comment]
Thanks!
