### ISSUE TITLE
add a toggle to change the tree we display in the preview view

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1790]
This would toggle between displaying the full file AST, and displaying just the the build() method for the current selection (and likely, it's direct parent nodes).

This toggle would be used mostly for A/B testing the two styles of trees. Long term, we'd probably eliminate the toggle and just ship with one representation.

If on the toolbar with the editing actions, we'd want this toggle separated from the other actions (perhaps right-aligned on the toolbar).

@scheglov

**Comment by scheglov** [comment]
Other approaches:
1. [Highlight background](https://github.com/flutter/flutter-intellij/pull/1793) for Flutter items.
2. [Prefix icons](https://github.com/flutter/flutter-intellij/pull/1796).

**Comment by scheglov** [comment]
The toggle has been implemented.
