### ISSUE TITLE
Migrate project to gradle warning

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1807]
With IntelliJ IDEA 2017.3.4 (Community Edition) on Windows, and a very recent flutter:
```
Flutter 0.1.5-pre.9 • channel master • git@github.com:flutter/flutter.git
Framework • revision 21c514fc56 (29 hours ago) • 2018-02-22 10:11:09 +0100
```

1. Create new Flutter project
1. Wait a bit

![image](https://user-images.githubusercontent.com/13644170/36539904-a356243a-17d8-11e8-816f-7acdc39f76db.png)

**Comment by devoncarew** [comment]
This _is_ an issue, but is not a recent regression.

**Comment by pq** [comment]
👍 This drives me nuts too but is not new...

cc @alexander-doroshko

**Comment by stevemessick** [comment]
Somehow, I don't know how, Android Studio eliminates that prompt because it puts this line in .idea/.workspace.xml during project creation:
```xml
<component name="PropertiesComponent">
  ...
  <property name="show.migrate.to.gradle.popup" value="false" />
  ...
</component>
```
I think deleting all files prior to `flutter create` was a necessary but not sufficient condition to make that happen, but I'm not sure.

**Comment by devoncarew** [comment]
I'm looking into a way to suppress this programmatically at project creation and project open.

**Comment by vjbharani** [comment]
hello ,is the app supposed to open with this warning on android? because mine isin't opening.
is there any solution?
