### ISSUE TITLE
Flutter Outline misc items

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1812]
Some feedback on the flutter outline view:

- [x] we should support a context menu on widget tree nodes that exposes refactoring items (either similar actions to what's visible in the toolbar, or similar to what would be available in the editor's opt-enter menu)
- [ ] consider exposing the 'extract method' refactoring
- [ ] is the convert stateless => stateful refactoring worth exposing as a toolbar item? Or, just as a context menu item in the Outline view?
- [x] it would be nice to proxy undo/redo key bindings through to the editor; if you clicked on 'center widget' in the view, and then hit cmd-z, it would be nice if the operation was undo (likely by just asking the editor to undo the last editing operation)

@scheglov

**Comment by scheglov** [comment]
1. Context menu implemented in 65c7fe8a6dcc20cf82d89e1bd4fd2d075cf11789.
2. Undo/redo implemented in acd06590ee41e2db63556a48cd5b6d32152bd215.

**Comment by scheglov** [comment]
`Extract method` was added in https://github.com/flutter/flutter-intellij/commit/0685afc8634e045746cd2ad88f3938c50557b818.

I think that conversion `stateless => stateful` is probably not as useful to qualify for a toolbar item. Let me know if you disagree, it should be easy to add anyway.

**Comment by devoncarew** [comment]
> is probably not as useful to qualify for a toolbar item

👍
