### ISSUE TITLE
open in android studio open foo_bar_android.iml in a text editor

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1820]
When I select 'Open in Android Studio' on the android/ sub-project in IntelliJ, it opens the entire project (`foo_bar/`) in Android Studio.

<img width="703" alt="screen shot 2018-02-23 at 3 48 08 pm" src="https://user-images.githubusercontent.com/1269969/36622301-4fd8b65e-18b1-11e8-8d3a-ba4491f39b13.png">

When I then select 'Open in Android Studio' on the android/ sub-project in that new Android Studio window, it opens the `foo_bar_android.iml` file in a text editor.

(I do see that the Java code is resolved in the Android studio instance - I can jump to declaration for the PluginRegistry classes)

/cc @stevemessick

**Comment by stevemessick** [comment]
And 'Open in Android Studio' doesn't work if already in Android Studio. The code needs to detect that it is running in AS and just do a normal Open Project.

**Comment by stevemessick** [comment]
@devoncarew Any idea why the menu title is something other than `Open Android module in Android Studio`? PR #1758 changed it (also for iOS), but your screenshot shows the old one.

**Comment by stevemessick** [comment]
Ah. #1758 does not update the template file.

**Comment by stevemessick** [comment]
Fixed with #1863
