### ISSUE TITLE
in Android Studio Beta 4, I see the message "the flutter plugin requires a more recent version of Android Stuido"

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1824]
<img width="558" alt="screen shot 2018-02-24 at 1 50 38 pm" src="https://user-images.githubusercontent.com/1269969/36635464-e619dcfc-1969-11e8-952b-726ad02f7286.png">

I think we want to disallow version less than 3.0, and Canary versions (but allow Betas).
/cc @stevemessick

**Comment by stevemessick** [comment]
Is this Android Studio 3.2 Canary 4? I have 3.1 Beta 3 but can't find Beta 4.

**Comment by devoncarew** [comment]
Android Studio 3.1 Beta 4

**Comment by rock3r** [comment]
Same happens here on AS 3.1 b4:

Android Studio 3.1 Beta 4
Build #AI-173.4615496, built on February 22, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3
