### ISSUE TITLE
Open Browser actions not working w/ Chrome on OS X.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1835]
None of the actions that open browsers using code that looks like this:

    BrowserLauncher.getInstance().browse(url, null);

work for me, opening an empty Chrome window (w/ no URL).

```
IntelliJ IDEA 2017.3.4 (Community Edition)
Build #IC-173.4548.28, built on January 29, 2018
JRE: 1.8.0_144-b01 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Mac OS X 10.13.3
```

To reproduce:

![image](https://user-images.githubusercontent.com/67586/36695495-5a9272c8-1af6-11e8-97a4-76b293484ebd.png)

I looked at my browser settings but found nothing odd:

![image](https://user-images.githubusercontent.com/67586/36695442-3b1d8c48-1af6-11e8-9ba3-96b83e554477.png)

cc @alexander-doroshko for any thoughts.

**Comment by pq** [comment]
FWIW, IDEA-provided browser actions are failing for me too:

![image](https://user-images.githubusercontent.com/67586/36698425-ab665072-1afe-11e8-8975-c174ab61bdbf.png)

**Comment by alexander-doroshko** [comment]
@pq Blind guess: do you have "Google Chrome.app" (with exactly this name) installed in your standard Applications folder?

**Comment by pq** [comment]
@alexander-doroshko : I do!

**Comment by alexander-doroshko** [comment]
@pq I checked on Mac and it works fine for me. What do you have as 'Default Browser' on the Web Browsers page in Preferences?

**Comment by stevemessick** [comment]
@pq I'm wondering if a recent Chrome or Mac OS update broke things? I noticed a lot of empty Chrome windows after trying to open other docs that have Chrome as the default app on Mac.

**Comment by pq** [comment]
Maybe.  My default is indeed chrome and that's what my preferences are pointing too.

![image](https://user-images.githubusercontent.com/67586/36992872-19d44a16-2061-11e8-9d99-635f4d7a7bfd.png)

Interestingly, I can no longer reproduce this... (Though I know at least @devoncarew could at least briefly too.)

Maybe it was a transient chrome thing?

Thanks for following up @alexander-doroshko .  I'll close for now and re-open if it recurs.
