### ISSUE TITLE
Missing Flutter icon for Flutter content roots.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1836]
I *believe* this is a regression.  In any event, it'd be nice to have fixed.  In particular, note the "hello" folder and how it does not show a flutter icon even though you'd think `FlutterIconProvider` should ensure it does.

![image](https://user-images.githubusercontent.com/67586/36697774-e97a2afc-1afc-11e8-8452-d83a7ab14365.png)

Doing a bit of looking around, it appears there are other icon contributors elsewhere --- possibly there's some contention for control over this decoration?

@alexander-doroshko : any thoughts?

**Comment by alexander-doroshko** [comment]
I hope it's easy to debug where the final icon comes from. Let me know if you want me to debug it for you.

**Comment by pq** [comment]
Thanks @alexander-doroshko.  Any ideas would be appreciated.  I'm out of them!

**Comment by alexander-doroshko** [comment]
@pq If I run IntelliJ from master branch sources I see `icons.StudioIcons.Shell.Filetree#ANDROID_MODULE` icon in the Project View
![image](https://user-images.githubusercontent.com/4499789/36735370-17ccf25a-1be7-11e8-9514-9ee96959ca9a.png)
that comes from `com.android.tools.idea.gradle.util.GradleUtil#getModuleIcon()`

**Comment by pq** [comment]
Interesting.  Thanks!  Incidentally, any idea why they're contributing both an `iconProvider` and a `fileIconProvider`?

```
  <iconProvider implementation="com.android.tools.idea.fileTypes.AndroidStudioIconProvider" id="androidStudioIcons" order="before javaDirectory"/>
  <fileIconProvider implementation="com.android.tools.idea.fileTypes.AndroidStudioFileIconProvider" id="androidFileIcons"/>
```

(I thought `iconProvider` was sufficient.)  

Also, could you help me with declaring ordering?  In particular, if I want to make sure the Flutter icon presents for Flutter content roots in IDEA CE/Ultimate and AS, what would you suggest I do?

**Comment by alexander-doroshko** [comment]
Sorry, I didn't have time to debug today.
There's no silver bullet anyway. One needs to set breakpoints and carefully step-by-step debug how the final icon is being chosen and where you can plug into this logic.

**Comment by pq** [comment]
No worries.  Thanks for following up!

**Comment by pq** [comment]
This doesn't repro anymore on EAP.  Optimistically closing.
