### ISSUE TITLE
Unclear: "Enable gradle for this project"

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#1846]
Developer Feedback:

After creating a new Flutter project in Android Studio: It is unclear what to select in the pop-up "Enable gradle for this project".

**Comment by devoncarew** [comment]
Is this popup the same as https://github.com/flutter/flutter-intellij/issues/1807?

**Comment by goderbauer** [comment]
Yes, that is the one!

Does the suppression maybe not work in Android Studio?

**Comment by goderbauer** [comment]
Oh, I see. The change was just submitted recently and might not have been active on this persons machine...

**Comment by devoncarew** [comment]
Yeah, this fix didn't quite make the latest release - it'll be out in next months.

**Comment by goderbauer** [comment]
Feel free to close this as a duplicate then.

**Comment by devoncarew** [comment]
done! (but thanks for the report)
