### ISSUE TITLE
Add keybindings for app reload and restart.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#185]

**Comment by pq** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
`cmd-r` for hot reload
`cmd-shift-r` for restart

**Comment by pq** [comment]
@stevemessick : I've got the incantation but there's a bit of rearchitecting to do.  Net-net, key-bound actions need to have a default constructor and we're using the constructor to inject the `ObservatoryConnector`.  To wit:

```java
  public ReloadFlutterApp(ObservatoryConnector connector) {
    super(connector, FlutterBundle.message("app.reload.action.text"), FlutterBundle.message("app.reload.action.description"),
          FlutterIcons.Flutter);
  }
```

Digging around but any thoughts on a clean way to do that appreciated!

**Comment by devoncarew** [comment]
I wonder how they do some of the debugger actions, like for step-over/in/out?

**Comment by pq** [comment]
OK, I've got a hack to find the connector and I think all's good.

The only issue now is around conflicting keybindings.

@mit-mit (or anyone) maybe take a look at the defined keybindings and come up with something less conflicting?

This [key](https://resources.jetbrains.com/assets/products/intellij-idea/IntelliJIDEA_ReferenceCard.pdf) may come in handy, though it differs a bit from mine which I based on eclipse. 😊

**Comment by stevemessick** [comment]
Well, just to keep things moving, how about this:

> ctrl-f5 or (Mac) cmd-f5 for hot reload
> ctrl-shift-f5 or (Mac) cmd-shift-f5 for restart

IntelliJ likes to put process control stuff on function keys. Cmd-f2 stops the running job in the debugger. F5 is only defined for one other task so there shouldn't be any conflicts with standard keys. No way to predict what other plugins will do, though.
