### ISSUE TITLE
IntelliJ IDEA stuck on "Creating Flutter Project"

### ISSUE THREAD

**Issue by tochanenko** [flutter/flutter-intellij#1855]
## Steps to Reproduce
1. Open IntelliJ IDEA
2. Goto **File->New Project** and select **Flutter** (SDK path is correct)
3. Click on **Next** and **Finish**

Then it starts looping. It has been doing something for about one hour.

## Version info
```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.248], locale ru-RU, channel beta)
    • Flutter version 0.1.4 at C:\Windows\System32\flutter
    • Framework revision f914e701c5 (9 days ago), 2018-02-19 21:12:17 +0000
    • Engine revision 13cf22c284
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0

[√] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at C:\Users\Владислав\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-23, build-tools 23.0.3
    • Java binary at: D:\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at D:\Android\Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30
```

**Comment by tochanenko** [comment]
@devoncarew 
That is quite interesting
{
Creating project foo_bar...
 Writing files
Wrote 66 files.

Running "flutter packages get" in foo_bar...
Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
pub get failed (1)
}

So I tried disabling Kaspersky and that changed a lot

{
Creating project foo_bar_2...
// Writing files
Wrote 66 files.

Running "flutter packages get" in foo_bar_2...       14,2s

[√] Flutter is fully installed. (on Microsoft Windows [Version 10.0.16299.248], locale ru-RU, channel beta)
[√] Android toolchain - develop for Android devices is fully installed. (Android SDK 23.0.3)
[√] Android Studio is fully installed. (version 3.0)
[√] IntelliJ IDEA Community Edition is fully installed. (version 2017.3)
[!] Connected devices is partially installed; more components are available.

Run "flutter doctor" for information about installing additional components.

All done! In order to run your application, type:

  $ cd foo_bar_2
  $ flutter run

Your main program file is lib/main.dart in the foo_bar_2 directory.
}

But creating projects via IntelliJ IDEA is still endless. I looked into log and I found these lines quite strange:

[  17525]   INFO -       ScriptTemplatesProviders - [kts] loading script definitions [] using cp:  
[  17528]   INFO -       ScriptTemplatesProviders - Templates provider KotlinCompilerScriptTemplatesSettings is invalid:  
[  17557]   INFO -       ScriptTemplatesProviders - Templates provider Gradle Kotlin DSL is invalid: Unable to get Gradle home directory 
[  17558]   INFO -       ScriptTemplatesProviders - Templates provider Gradle Kotlin DSL is invalid: Unable to get Gradle home directory 
[  17558]   INFO -       ScriptTemplatesProviders - Templates provider Gradle Script Kotlin is invalid: Unable to get Gradle home directory 

And then it says:
2018-02-28 22:00:37,408 [  19578]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 6554 ms 
2018-02-28 22:00:38,279 [  20449]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 3041ms; general responsiveness: ok; EDT responsiveness: 1/3 sluggish, 1/3 very slow 
2018-02-28 22:00:38,635 [  20805]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 28.02.2018 20:33) 
2018-02-28 22:00:38,651 [  20821]   INFO - j.ide.ui.OptionsTopHitProvider - 165 ms spent to cache options in project 
2018-02-28 22:00:39,571 [  21741]   INFO - CompilerWorkspaceConfiguration - Available processors: 8 
2018-02-28 22:00:41,777 [  23947]   INFO - ellij.project.impl.ProjectImpl - 20 project components initialized in 36 ms 
2018-02-28 22:04:29,358 [ 251528]   INFO - ellij.project.impl.ProjectImpl - 150 project components initialized in 116 ms 
2018-02-28 22:04:29,359 [ 251529]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms 
2018-02-28 22:04:39,793 [ 261963]   INFO - #io.flutter.sdk.FlutterCommand - C:\Windows\System32\flutter\bin\flutter.bat [--no-color, create, --template, app, --description, A new Flutter project., --org, com.yourcompany, untitled2] 


![image](https://user-images.githubusercontent.com/34678912/36810825-8d95e210-1cd4-11e8-9b98-a25c36bd95ee.png)

**Comment by tochanenko** [comment]
@devoncarew 
[idea.log](https://github.com/flutter/flutter-intellij/files/1770902/idea.log)
[threadDump-20180301-091108.txt](https://github.com/flutter/flutter-intellij/files/1770904/threadDump-20180301-091108.txt)
[threadDump-20180301-091103.txt](https://github.com/flutter/flutter-intellij/files/1770905/threadDump-20180301-091103.txt)
[threadDump-20180301-091146.txt](https://github.com/flutter/flutter-intellij/files/1770906/threadDump-20180301-091146.txt)
[threadDump-20180301-130404.txt](https://github.com/flutter/flutter-intellij/files/1770907/threadDump-20180301-130404.txt)
[threadDump-20180301-130359.txt](https://github.com/flutter/flutter-intellij/files/1770908/threadDump-20180301-130359.txt)
[threadDump-20180301-130429.txt](https://github.com/flutter/flutter-intellij/files/1770909/threadDump-20180301-130429.txt)

I hope this information will be helpfull

**Comment by stevemessick** [comment]
I'm not a Windows user and this may be totally irrelevant. Having Flutter installed in

`C:\Windows\System32\flutter`

seems incorrect and could lead to problems.

See [Get Started: Install on Windows.](https://flutter.io/setup-windows/)

**Comment by guyulmaz** [comment]
Running "flutter packages get" in foo_bar...
Connection terminated during handshake
pub get failed (69)

I think firewall is restricting access to some paths.
Do you know for which urls this exception should be added at firewall?

**Comment by handstandsam** [comment]
I finally got around this.  You can diagnose via creating a new project via the command line, and then running an update packages to diagnose proxy issues.  NOTE: I had to set a system wide proxy to make this work.

1) Create a flutter project: `flutter create foo_bar`

2) Run get packages: `flutter packages get -v`

I found out here that my proxy information was bad.  I added an the following to my `~/.bash_profile`, closed the terminal and Android Studio, and then reopened both.
`http_proxy="http://user:pass@myproxy.com:8080"`

**Comment by madarinho** [comment]
Try to "**Run as administrator**" your IDE.
It worked for me on Android Studio.

**Comment by darylrue** [comment]
I have the same issue when creating a new Flutter project while at work, where the network has a man-in-the-middle firewall. Something is being blocked, but instead of failing gracefully, IntelliJ is hanging indefinitely.

**Comment by MishraUdit** [comment]
I had the same issue also. When I connected my system to the internet, it completed the task in a few seconds...
I don't know what's the issue behind it, but I think it requires proper bandwidth while creating new projects.
Might be, it is downloading a few files or authenticating any file each time creating new projects.

**Comment by nabinbhandari** [comment]
I also had the same issue, In my case, I think, it was caused because the process 'dart' was already running in the background. In Linux terminal, I entered `killall dart` to kill the process and then I was able to create a new project.

**Comment by darylrue** [comment]
Using my work computer on my home network I'm now having the same issue. If I run 
`flutter create test_project` 
it hangs here:
`Running "flutter packages get" in test_project...`
If I go to an existing flutter project and run 
`flutter packages get -v`
it hangs here:
`[C:\Users\path_to_project\] c:\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning --verbose get --no-precompile`

**Comment by skyh24** [comment]
> @devoncarew
> [idea.log](https://github.com/flutter/flutter-intellij/files/1770902/idea.log)
> [threadDump-20180301-091108.txt](https://github.com/flutter/flutter-intellij/files/1770904/threadDump-20180301-091108.txt)
> [threadDump-20180301-091103.txt](https://github.com/flutter/flutter-intellij/files/1770905/threadDump-20180301-091103.txt)
> [threadDump-20180301-091146.txt](https://github.com/flutter/flutter-intellij/files/1770906/threadDump-20180301-091146.txt)
> [threadDump-20180301-130404.txt](https://github.com/flutter/flutter-intellij/files/1770907/threadDump-20180301-130404.txt)
> [threadDump-20180301-130359.txt](https://github.com/flutter/flutter-intellij/files/1770908/threadDump-20180301-130359.txt)
> [threadDump-20180301-130429.txt](https://github.com/flutter/flutter-intellij/files/1770909/threadDump-20180301-130429.txt)
> 
> I hope this information will be helpfull

i have the same problem. how did you solve?

**Comment by skyh24** [comment]
it's so wired. i can use flutter create command to generate new project. But i cannot create flutter project in android studio and it stuck

**Comment by tennessine** [comment]
Close the http proxy set on android studio  solved my problem.

**Comment by jwren** [comment]
Closing as obsolete as there is no action item here for the Flutter Plugin
