### ISSUE TITLE
importing other flutter modules into project

### ISSUE THREAD

**Issue by matejthetree** [flutter/flutter-intellij#1873]
Hello,

I have an application made in flutter at `flutterApp/` and library at `flutterLib/`.

Now how do I import library module inside flutterApp project?

If I choose `importModule` from module options, It asks me some unrelated flutter question.

What is the correct way to do it?

**Comment by stevemessick** [comment]
Flutter libraries come in two forms: packages and plugins. A Flutter package is basically a Dart package and has no platform native code; it is device independent. A plugin is a package that has device-dependent code.

The easiest way to get started is to create a Flutter app then add packages and plugins to it. See
[Using Packages](https://flutter.io/using-packages/) and [Developing Packages & Plugins](https://flutter.io/developing-packages/) for more info.

**Comment by matejthetree** [comment]
The question was how to have both projects inside the single intelliJ project, so that I can refactor the package while testing it in sample app without switching project windows.

**Comment by ChakshuGautam** [comment]
There is an example here in the docs. https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by patelkrunal78** [comment]
Similar To [how to use local flutter package in another flutter application?](https://icetutor.com/question/how-to-use-local-flutter-package-in-another-flutter-application)

**Comment by Krunal79-flutter** [comment]
dependencies:
flutter:
sdk: flutter
my_new_package:
path: ./my_new_package

[here](https://icetutor.com/question/how-to-use-local-flutter-package-in-another-flutter-application/) is your example...

**Comment by fmatuszewski** [comment]
This is not the answear to the question. The question is if I have Dependencies on unpublished packages
like it is shown in the example you provide then how to import it to android studio as separate module.
