### ISSUE TITLE
I have imported the project from gist but after extracting files and starting my android studio is showing an error of migrate project to gradle   even new activity option is also not there can someone help  

### ISSUE THREAD

**Issue by AnimeshSomvanshi** [flutter/flutter-intellij#1888]
migrate project to gradle?  what is this 
![gradle](https://user-images.githubusercontent.com/36759954/37085062-23944262-221a-11e8-94d1-e4b4b44e31a3.jpg)
![new actitvity](https://user-images.githubusercontent.com/36759954/37085083-2d6ee9cc-221a-11e8-9b9c-ad1a3cf32b2c.png)

**Comment by stevemessick** [comment]
You can eliminate the "Migrate Project to Gradle?" query by clicking the `Don't show this message again` link.

Your second screen shot shows a context-sensitive menu from a portion of the project hierarchy that is outside the current project. Many of the `New` menu items are not applicable in that context.

Generally, `Import` does some transformation on the project that is not helpful for Flutter. Use `Open` instead or start from a newly-created Flutter project.
