### ISSUE TITLE
Make "Import" work

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#1889]
The "Import Project/Module" function does not work with Flutter projects. This needs to be fixed for both IntelliJ and Android Studio.

**Comment by devoncarew** [comment]
+1

It looks like the android module portion is recognized first, and hinders the import of the dart portion of the project. Perhaps we need to add some type of Flutter module recognizer?

**Comment by devoncarew** [comment]
Possibly we need to implement a `com.intellij.projectImport.ProjectImportProvider`?

**Comment by pq** [comment]
After some exploring with @stevemessick, I think I've got a good bead on this.  Optimistically scheduling.

**Comment by matejthetree** [comment]
please check this out too 
https://github.com/apptreesoftware/letsvote#intellj-multi-module-setup

**Comment by pq** [comment]
Oh wow.  That's complicated.  Thanks for the heads-up @matejthetree!

**Comment by devoncarew** [comment]
From some user feedback, people are having trouble importing Flutter projects into Android Studio; making this easier would be great.

**Comment by pq** [comment]
Quick update: I made some good progress on this today but not close enough to try and land for M23.  Deferring but treating as high priority for M24.
