### ISSUE TITLE
How to install this plugin  with source code for Android studio ?

### ISSUE THREAD

**Issue by wendux** [flutter/flutter-intellij#1896]
I have failed to install flutter plugin several times in  Android studio, because  the network is not available ( I am in China ).  so  I want to know if there is a way to  install this plugin with source code ?

**Comment by pq** [comment]
Try downloading the binary directly from Jetbrains?

https://plugins.jetbrains.com/plugin/9212-flutter

And if you need Dart as well:

https://plugins.jetbrains.com/plugin/6351-dart

Hope that helps!

**Comment by wendux** [comment]
Thanks !
