### ISSUE TITLE
Connect same running app to two devices?

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#1897]
Hey all, I think this is supported by Flutter, but wasn't sure if I could do this in IntelliJ.

What I'd like:

  1. Open iOS simulator and Android Emulator, put em side-by-side
  2. Launch the app from IntelliJ, deploying to both devices
  3. When I make changes and it hot reloads, both devices should show updates.

Is this possible and I missed how to do it? I tried simply launching two different debugging sessions, but when I perform a Hot Reload it only reflects on the most recently run device.

Overall this could be a big time saver for me so I don't have to switch / rebuild to ensure visual changes look good on both platforms!

As always, thanks for the great plugin and listening to our feedback :)

**Comment by pq** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
@brianegan, I think what you're asking for is the same as this request: https://github.com/flutter/flutter-intellij/issues/956; we're hopefully of having that done ~in the next two releases.

**Comment by brianegan** [comment]
@devoncarew Oops, sorry for the duplicate!
