### ISSUE TITLE
exception from widget_inspector.dart: Id does not exist

### ISSUE THREAD

**Issue by Arvoreen** [flutter/flutter-intellij#1898]
## What happened

I was doing the "Test Drive", launched my app, the made the text change and hit save....while hot reload was initializing, I tried to expand the flutter inspector....

## Version information

Android Studio `3.0.1` • Flutter plugin `io.flutter 22.2.1` • Dart plugin `171.4424`

Error getting Flutter sdk information.

## Exception

Error evaluating expression:
Unhandled exception:
```
Id does not exist.
#0      WidgetInspectorService.toObject (package:flutter/src/widgets/widget_inspector.dart:222:7)
#1      WidgetInspectorService.getChildren (package:flutter/src/widgets/widget_inspector.dart:380:34)
#2      Eval (evaluate:source:1:39)
#3      _Closure.hashCode (dart:core-patch/dart:core/function.dart:10)
```

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at io.flutter.inspector.EvalOnDartLibrary$2.received(EvalOnDartLibrary.java:121)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:410)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:99)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

## Version info

C:\Users\eduar\git\flutter\bin\flutter.bat --no-color doctor
[√] Flutter (on Microsoft Windows [Version 10.0.16299.248], locale en-US, channel alpha)
    • Flutter version 0.0.22-pre.1 at C:\Users\eduar\git\flutter
    • Framework revision 553fc4264e (7 days ago), 2018-03-01 09:30:25 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[√] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at C:\Users\eduar\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

**Comment by pq** [comment]
cc @jacob314

**Comment by Arvoreen** [comment]
To add a little more context, I had just started up Intellij, so there was some background indexing still going on, as well as other disk activity that may have led to some strange timeouts or other timing related problems.  I re-launched the app into my emulator shortly after this bug occurred and it all seemed to work fine.

**Comment by pq** [comment]
Thanks for the follow-up @Arvoreen; that'll be useful for debugging.

**Comment by jacob314** [comment]
https://github.com/flutter/flutter-intellij/pull/2094 will fix this.
The problem was there was a case I wasn't thinking of where requests could end up out of order.
