### ISSUE TITLE
Opening XCode Project for a plugin project errors

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1914]
To repro:

1. create a plugin project
2. open `example/ios` in Xcode with the context menu

![image](https://user-images.githubusercontent.com/67586/37431702-37fafd3a-2793-11e8-98c9-039a452b6d7d.png)

and...

![image](https://user-images.githubusercontent.com/67586/37431491-a289c29a-2792-11e8-9b81-3fc13f954720.png)

The second attempt to open is better but fails to run in XCode:

![image](https://user-images.githubusercontent.com/67586/37431826-8a8b983e-2793-11e8-8340-30034fd4d7e6.png)

```
[✓] Flutter (Channel master, v0.1.8-pre.46, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[✓] Connected devices (2 available)

• No issues found!
Process finished with exit code 0

```

**Comment by pq** [comment]
Side note: the issue tracking the initial implementation of the auto-build is https://github.com/flutter/flutter-intellij/issues/1373.  Fairly sure this *used* to work and is a regression.

cc @stevemessick @mit-mit

**Comment by pq** [comment]
Running from the commandline it's clear that the error is related to missing code signing certificates.

```
[~/src/tmp/untitled7_pp12] $ flutter build ios --debug
Building com.yourcompany.untitled7Pp12 for device (ios)...
═══════════════════════════════════════════════════════════════════════════════════
No valid code signing certificates were found
You can connect to your Apple Developer account by signing in with your Apple ID in Xcode
and create an iOS Development Certificate as well as a Provisioning Profile for your project by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- In the 'General' tab, make sure a 'Development Team' is selected. You may need to
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again
  5- Trust your newly created Development Certificate on your iOS device
     via Settings > General > Device Management > [your new certificate] > Trust

For more information, please visit:
  https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html

Or run on an iOS simulator without code signing
═══════════════════════════════════════════════════════════════════════════════════
No development certificates available to code sign app for device deployment
```

A few questions:

1. was this always an error?  And should it be an error?
2. we're running flutter build at the project root; *should* that be sufficient to build in `example/ios` or do we need to explicitly build there?

cc @mravn-google

**Comment by mravn-google** [comment]
@pq Are you working off Flutter master? For posterity, please include `flutter doctor` output.

The first error I believe is fixed on flutter/master via https://github.com/flutter/flutter/pull/15437. The second error about certificates has certainly been around for a long time. Whether it should be an error, I'm not sure.

From the command line, you need to build plugin projects from the `example/` subfolder. Otherwise you don't have a Flutter app, and our current tooling only knows how to build apps.

**Comment by pq** [comment]
Thanks for the quick reply @mravn-google!  Flutter doctor output is in the first comment (`Flutter (Channel master, v0.1.8-pre.46, on Mac OS X 10.13.3 17D102, locale en-US`) but I realize it wasn't verbose:

```
[~/src/repos/linter] (enableAssertInitializer) $ flutter doctor -v
[✓] Flutter (Channel master, v0.1.8-pre.46, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.8-pre.46 at /Users/pquitslund/src/repos/flutter
    • Framework revision f8ac23cd86 (9 days ago), 2018-03-05 23:27:57 +0100
    • Engine revision a00f8e8bc0
    • Dart version 2.0.0-dev.32.0.flutter-ee15c8eb68

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/pquitslund/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Tools/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Tools/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/Tools/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (2 available)
    • rover    • 53c04b73fcc344f4610c0c516b22707e9809e17b • ios • iOS 11.2.6
    • iPhone 8 • C24F72A8-B58F-4F5D-ADC7-DFFF03784999     • ios • iOS 11.2 (simulator)

• No issues found!
```

It looks like I don't have your fix so I'll update; thanks for the heads-up!

As for the error, what's tricky is that we'd like to be able to auto-run the build from within the IDE and know when something _really_ went wrong.  I don't think missing certificates qualifies since you can work without them (and in any event have no way to really remediate within IntelliJ).

Who would be best to loop in on the "should this really be an error" problem?

cc @devoncarew

**Comment by mravn-google** [comment]
@xster wrote https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/code_signing.dart

**Comment by pq** [comment]
In another thread, @mravn-google suggested that checking for a `build/` dir is possibly not the right heuristic to trigger work before opening Xcode and further, that `flutter build` may not be the right thing when we do.

To investigate:

1. check to see if `pod install` is sufficient (and consider an additional `flutter packages get` if not)
2. update the check for `build/` in favor of something better targetted
