### ISSUE TITLE
Make all Google Docs feedback forms linked to by the plugin track Flutter Version and Plugin Version

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#1915]
This lets us filter feedback by version as some features such as the inspector have very different behavior on different versions and depending on whether dart2 is enabled.

Here is an example of how to create a form link that fills in a field:
I got the entry id by inspecting the form in chrome devtools but perhaps there is a smarter way.
I assume the ids are stable but I haven't verified.

https://docs.google.com/forms/d/e/1FAIpQLSe5Fu-AFb2Wmxtr7UWgxZt6Z76B4z9fE0vf-eu4pdKxqJ8DQg/viewform?entry.1032699374=DART_2_ROCKS

@InMatrix who requested this.

**Comment by InMatrix** [comment]
We'll also need to know if the user turned on experimental features via settings.

**Comment by kenzieschmoll** [comment]
Do we want Flutter version, plugin version, and IDE version?

The current form asks for IDE and plugin. This issue description asks for Flutter and plugin. Do we want all 3 or just 2?

**Comment by jacob314** [comment]
Including all 3 sounds good as bugs might be due to all 3.

**Comment by InMatrix** [comment]
Can we add a hint text below each question about how to find version numbers?

**Comment by kenzieschmoll** [comment]
Just sent a [PR](https://github.com/flutter/flutter-intellij/pull/2775) out.

Will update survey once this lands.

Last three fields are automatically filled in.
https://docs.google.com/forms/d/e/1FAIpQLSe5Fu-AFb2Wmxtr7UWgxZt6Z76B4z9fE0vf-eu4pdKxqJ8DQg/viewform?entry.1740350095=0.10.2&entry.1082356620=182.4892.20&entry.1842668120=Idea%202018.2.5.0.0

**Comment by InMatrix** [comment]
Oh, I didn't realize all three version fields can be auto-filled. Sorry about the confusion. :-)
