### ISSUE TITLE
Auto completion for setState, add the anonymous function

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#1916]
When adding setState with auto complete, it would be nice if the autocompletion would add the anonymous function. 

1. type in "setS[control+space]"
2. auto complete with setState(() {}); 
3. Or auto complete with some more verbiage to help
```
// or maybe
setState(() { 
  // change state here
});
```

What it does currently:
![screen shot 2018-03-14 at 8 06 43 pm](https://user-images.githubusercontent.com/1326504/37442385-497eecf8-27c3-11e8-8088-66400b715bff.png)

**Comment by stevemessick** [comment]
@pq had been looking at something similar IIRC.

Have you tried statement completion? I think this is beyond what stmt-complete was designed to do, but it does seem like a natural fit.

**Comment by pq** [comment]
👍 

Adding @scheglov who's been knocking out completion improvements.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/48526

![setstate_completion](https://user-images.githubusercontent.com/384794/38003029-73fe4ab0-31ea-11e8-9e58-2ca665065586.gif)

One rub is that selection will not be set inside the closure in current versions of Dart plugin for IntelliJ. There is one tiny fix we need to make. I will do it soon for the bleeding edge of the plugin, so it will be available in a next EAP.
