### ISSUE TITLE
GeneratedPluginRegistrant.java cannot resolves symbols for flutter plugins

### ISSUE THREAD

**Issue by MarkBriggs2** [flutter/flutter-intellij#1918]
This looks like a config generation issues, a java classpath issue, perhaps. Build fails. 

## Steps to Reproduce

Create a flutter project, include dependencies:
   sqflite: any
  path_provider: 0.4.0
  url_launcher: 3.0.0

GeneratedPluginRegistrant.java contains imports for which symbols cannot be located (packages don't exist): 

import io.flutter.plugins.pathprovider.PathProviderPlugin;
import com.tekartik.sqflite.SqflitePlugin;
import io.flutter.plugins.urllauncher.UrlLauncherPlugin;

External Libraries -> Flutter plugins do contain these packages/classes.

.flutter-plugins file contains the correct locations, e.g:
path_provider=C:\\Users\\Mark\\AppData\\Roaming\\Pub\\Cache\\hosted\\pub.dartlang.org\\path_provider-0.2.2\\
The java path would be /Users/Mark/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/path_provider-0.2.2/android/src/main/java. 
package structure /io/flutter/plugins/pathprovider/PathProviderPlugin.java does exist. 

## Version info

[√] Flutter (Channel dev, v0.2.1, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 0.2.1 at C:\Users\Mark\flutter
    • Framework revision 6f5bcb97a4 (7 days ago), 2018-03-08 15:01:37 -0800
    • Engine revision 24cf8ebd86
    • Dart version 2.0.0-dev.33.0.flutter-b5b8080b2c

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Mark\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!

**Comment by stevemessick** [comment]
This isn't the great editing experience we'd like it to be, currently. To edit Java files you need to open the Android module as a top-level project in Android Studio. More details here:
https://github.com/flutter/flutter-intellij/blob/master/docs/android.md

The problems you describe do not appear when following those directions. For plugins, be sure to open the `example/android` module as a top-level project in Android Studio, where `example` is the example app generated with the plugin.

/cc @mit-mit for posterity

**Comment by MarkBriggs2** [comment]
Hi Steve, I don't know what to make of your response. I shouldn't need to edit the java code, I'm not writing a plugin just trying to use dart libraries which are designated as plugins. Can you at least tell me how these java packages are accessed, or under what circumstances they may not be found. Otherwise, an application that was fine is now completely broken.

**Comment by MarkBriggs2** [comment]
For the moment I've simply moved the appropriate packages into app/src/....

**Comment by arieosdmin** [comment]
I have this same problem but I am unable to solve it. I have installed it on a windows 10 and on a Mac, but on both I get the error that they cannot find the symbol.
/Users/osdm/IdeaProjects/osdm_in/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
If I add the files manually I get even more errors.

**Comment by jifalops** [comment]
I'm getting this error when running `./example/main.dart` on a package (not plugin) that is a Widget.

**Comment by Joggyjagz7** [comment]
I am currently having this error, any help?

**Comment by MarkBriggs2** [comment]
See issue #1929 for more information. 
You should be able to build using flutter build appbunde (or app).

**Comment by kashifg4171** [comment]
I'm facing this issue, any help please

**Comment by MarkBriggs2** [comment]
See issue #1929 linked above. Use the flutter commands from a shell.
