### ISSUE TITLE
Flutter hangs for new Flutter project if not internet

### ISSUE THREAD

**Issue by timekarma** [flutter/flutter-intellij#1923]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
**Creating a new Flutter project, if there is no internet connection, Flutter/Android Studio hangs. Only way out is kill the process & restart**

## Version info
beta
Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
The `flutter create` command never finishes.
```
$ flutter create foo2
Creating project foo2...
  foo2/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  foo2/ios/Runner/Info.plist (created)
...
  foo2/.idea/workspace.xml (created)
Wrote 66 files.

Running "flutter packages get" in foo2...
Could not resolve URL "https://pub.dartlang.org".
pub get failed (69) -- attempting retry 1 in 1 second...
Could not resolve URL "https://pub.dartlang.org".
pub get failed (69) -- attempting retry 2 in 2 seconds...
Could not resolve URL "https://pub.dartlang.org".
pub get failed (69) -- attempting retry 3 in 4 seconds...
Could not resolve URL "https://pub.dartlang.org".
pub get failed (69) -- attempting retry 4 in 8 seconds...
Could not resolve URL "https://pub.dartlang.org".
pub get failed (69) -- attempting retry 5 in 16 seconds...
Could not resolve URL "https://pub.dartlang.org".
pub get failed (69) -- attempting retry 6 in 32 seconds...
Could not resolve URL "https://pub.dartlang.org".
pub get failed (69) -- attempting retry 7 in 64 seconds...
```
I had just created a project named foo1 so pub should not have needed to download anything.

Since the OP didn't include it:
```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.2.1-pre.63, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.1-pre.63 at /Users/messick/src/flutter/flutter
    • Framework revision c8fd99fb33 (4 days ago), 2018-03-12 01:05:23 -0700
    • Engine revision 1d0da77995
    • Dart version 2.0.0-dev.33.0.flutter-b5b8080b2c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/messick/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/default/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio 2.3.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1012-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4548.30
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by stevemessick** [comment]
This won't play well with the feature requested in https://github.com/flutter/flutter/issues/15568

**Comment by devoncarew** [comment]
It looks like we're re-trying pub indefinitely. We should only re-try a few times, and should display progress to the user as we do.

**Comment by stevemessick** [comment]
There's a new --offline option to `flutter create` that could help here.

It would be nice if the flutter tool just assumed it should run offline if `pub get` times out, but it doesn't, so maybe we can check network availability before launching the tool to create a project.

**Comment by pq** [comment]
As per a conversation w/ @stevemessick, we're thinking this really belongs in the flutter tool proper and that `flutter create` (and potentially other network-dependent commands) should be made more robust.

**Comment by pq** [comment]
... And as it would happen, @jcollins-g was just two desks over updating https://github.com/flutter/flutter/issues/15717 which tracks support at the tools level. Serendipity!

Net-net: this does not seem like something to be fixed in the I/O timeframe.

**Comment by pq** [comment]
With #1923 and #2096 we've now got a toggle for offline mode and auto selection in case we're obviously offline.  There's still work to be done to make `flutter create` more smart but I think this covers the IDE for now.

**Comment by Steven-MKN** [comment]
Basically you just need to be connected to the internet when you create a project, same goes with Android Studio. Try that.

**Comment by pq** [comment]
@Steven-MKN : are you in IntelliJ or Android Studio?  For IntelliJ, it should auto-toggle to offline mode.  Similar support is planned for AS: https://github.com/flutter/flutter-intellij/issues/2099.
