### ISSUE TITLE
Enable the Heap Display

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1927]
Depending on how the Inspector UI evolves, the ultimate home for Heap info (and FPS etc and beyond) is still TBD but we'd like to get this enabled somewhere for this iteration.

Concretely, that means:

* [x] Add a preference to enable the display
* [ ] Settle on a home ~(out of the toolbar sparkline likely)~
  * [ ] Implement...

/cc @devoncarew @jacob314

**Comment by pq** [comment]
FWIW, I'm leaning towards a south-docked panel.  Something like:

![image](https://user-images.githubusercontent.com/67586/37537019-8a233088-2909-11e8-9ffb-fe2141f043fa.png)

(Mock samples obviously.)

This also gives us plenty of room to display numbers (e.g., 48 of 54M).

**Comment by jacob314** [comment]
I expect the default location for the inspector will be on the bottom of the screen along these lines.
The lowest risk place to put the memory usage UI would be on the toolbar as there is a ton of room there. If there are issues with that, right bellow the property window is probably fine. I'd just like to try to preserve as much height as feasible for the summary and details view of the widget tree as they work best when they have a lot of room.
![image](https://user-images.githubusercontent.com/1226812/37550024-75ba7d0c-294c-11e8-9113-8f42c6c49ffc.png)

**Comment by devoncarew** [comment]
At the bottom seems like a good place for a vertical display.

For a horizontal display (which sounds like that position will work best for the inspector), there's not as clear-cut of a good place. The toolbar seems reasonable, if a little tight in terms of what we can display. Below the widget tree may also work?

**Comment by pq** [comment]
Given that the inspector looks to headed for a horizontal display, (and that vertical space will be at a premium) we'll stick w/ the toolbar implementation for M23.  This remains of course subject to revision down the line...
