### ISSUE TITLE
plugin packages cannot be located - reprise

### ISSUE THREAD

**Issue by MarkBriggs2** [flutter/flutter-intellij#1929]
Java code for dart packages which have become 'plugins' cannot be located, causing build failure. 
The java code does exist in the library cache, and can be copied to a location in the project so that the build does work, but flutter run will fail due to multiple dex files implementing the same class.

I have simplified this problem so that it should be able to be reproduced easily. 
This is a genuine issue for me, which has prevented my updating an android app on google play, so please don't arbitrarily close it without getting in touch. If this is somehow caused by my environment, I need to know how to address it. 

Additionally, the project structure contains incorrect default locations for AndroidManifest.xml and the resources directory, directly under 'android', but should be under 'android/app/src/main'.

Thanks
Mark
## Steps to Reproduce

Create a new flutter application project. 
Add the following line to pubspec.yaml dependencies:
url_launcher: ^3.0.0

Get packages

edit main.dart as follows:
import 'package:url_launcher/url_launcher.dart';
add function to class _MyHomePageState

  _launch(url) async {
    await launch(url);
  }

Add widgets to the scaffold, prior to existing widgets: 
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text("Goto Flutter Site:"), // added
            new RaisedButton(onPressed: _launch("https://flutter.io"), child: new Icon(Icons.launch),), // added
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),

After setting the project structure config correctly, try a build.
Image below shows the output:
 
![image](https://user-images.githubusercontent.com/37406301/37550330-1a98dd0c-29d7-11e8-939d-a8bc1691e43c.png)

## Version info
[√] Flutter (Channel dev, v0.2.1, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 0.2.1 at C:\Users\Mark\flutter
    • Framework revision 6f5bcb97a4 (8 days ago), 2018-03-08 15:01:37 -0800
    • Engine revision 24cf8ebd86
    • Dart version 2.0.0-dev.33.0.flutter-b5b8080b2c

[√] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    • Android SDK at C:\Users\Mark\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 28.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!

**Comment by stevemessick** [comment]
Cannot reproduce.
@pq perhaps you could take a look?

**Comment by MarkBriggs2** [comment]
Correcting this app by: importing <pre>dart:async</pre> 
and modifying code:
<pre>
Future<Null> _launch() async {
    await launch("https://flutter.io");
}
</pre>
and
<pre>
new RaisedButton(onPressed: _launch, child: new Icon(Icons.launch),),
</pre>
can now externally run:
<pre>
> flutter clean
> flutter build apk
> flutter run
</pre>
It will build and run fine, just not integrated with IntelliJ IDEA.
Other apps with more 'plugin' packages are ok outside of IDE.
Also, uninstalled and installing flutter plugin no difference.  
More of an inconvenience than anything else. 
Thanks

**Comment by arieosdmin** [comment]
Indeed this is exactly what I see and I have tried so many things to solve it. Do not understand where the problem might be.

**Comment by devoncarew** [comment]
I can repro this:
- from IntelliJ, create the std hello world project
- in the pubspec file, add a dependency on a plugin (like `flutter_blue`)
- run `flutter packages get`

Then to see the issue, you can do something like go into `android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java`, or run `Build > Build Project`.

**Comment by arieosdmin** [comment]
Is there a way to fix it? Or is there a reason for this problem?

**Comment by devoncarew** [comment]
I believe this is mostly cosmetic, through something were working to improve.

You should still be able to run your app. If targeting an iOS device or simulator, the run button will drive `flutter run`, which will drive xcode, and perform the platform specific building.

If targeting android devices/emulators, run will drive `flutter run`, which will delegate through to gradle, and build those platform specific artifacts. Either way you'll be able to build and run your flutter app - just the IntelliJ `Build > Build Project` menu won't work (but isn't in the path for flutter projects).

For it to work, you can open the `android/` sub-module in Android Studio (right-click on the folder in IntelliJ, and choose `Flutter > open module in Android Studio`. That sub-module is configured to build with the flutter gradle script - it should build correctly, and set up the classpaths so that the plugin code is editable and navigable.

**Comment by tegarkurniawan** [comment]
![Uploading error.PNG…]()

**Comment by logemann** [comment]
just stumbled over this issue. And yes, it seems cosmetic but i would be really nice to have those dependencies resolve in the main Android Studio Flutter Project, otherwise people get crazy about those red flags like i did.

**Comment by OGmetamonkey** [comment]
> Future _launch() async {
>     await launch("https://flutter.io");
> }

This dart implementation correction seems irrelevant to the underlying plugin registrant problem. Am I missing something? What did you actually do to fix the registrant issue?
