### ISSUE TITLE
Android Studio doesn't work with optional new/const in master channel

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1931]
## Steps to Reproduce

1. Change to master channel and upgrade to latest build (this has Dart 2 by default)

1. `flutter create foobar`

1. In `foobar/lib/main.dart`, change:
    ```
      return new MaterialApp(
          title: 'Flutter Demo',
          theme: new ThemeData(
    ```
    to:
    ```
      return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
    ```

1. Validate that analysis passes: `cd foobar`, `flutter analyze`:
    ```
    Analyzing /Users/mit/tmp/foobar...
    No issues found!
    Ran in 6.0s
    ```

1. Open project in IntelliJ: No analysis issies

1. Open project in Android Studio:
    ```
    error: 'MaterialApp' isn't a function. (invocation_of_non_function at [foobar] lib/main.dart:9)
    error: 'ThemeData' isn't a function. (invocation_of_non_function at [foobar] lib/main.dart:11)
    ```

**Comment by mit-mit** [comment]
cc @devoncarew 

It seems really odd that it works in IJ but not in AS?

**Comment by devoncarew** [comment]
The default for the dart sdk has not yet changed - we're getting this default from the analysis server. The defaults for the dart sdk built by flutter is not in sync with the flutter default (which, we should fix).

> Open project in IntelliJ: No analysis issues

Your IntelliJ instance likely has preview dart 2 set to on somewhere :)

**Comment by devoncarew** [comment]
This skew will be fixed by beta2, but we should address it soonest.

**Comment by mit-mit** [comment]
Is there a bug for this in flutter/flutter ?

**Comment by devoncarew** [comment]
No; we could have a tracking bug there, but the work would happen in the dart sdk.

**Comment by devoncarew** [comment]
See https://github.com/dart-lang/sdk/issues/32566

**Comment by devoncarew** [comment]
Landed: https://dart-review.googlesource.com/c/sdk/+/47122
