### ISSUE TITLE
Add a notification if the currently configured Flutter SDK is too old.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#194]
The rub is that out of date Flutter SDKs can produce unpredictable results (notably debugger issues).  To that end, it would be great to show a toast and probably an error in the preference and project creation pages if this case is detected.

Open question: what from our version info is right to key off?

<img width="595" alt="screen shot 2016-09-29 at 5 39 06 am" src="https://cloud.githubusercontent.com/assets/67586/18954286/1943680c-8607-11e6-98e8-1420860946d6.png">

cc @abarth @sethladd since I think you guys were thinking about this?

**Comment by abarth** [comment]
How do you want to define "too old" ?

**Comment by pq** [comment]
> How do you want to define "too old" ?

I have no idea!

Maybe better to say it'd be great to test if a given SDK has feature "X", which we can derive somehow from it's date.  In SVN days, I'd just check for `>= $REV`.  Not sure what to do here.

**Comment by abarth** [comment]
There's a VERSION file in the root of the SDK.  We could bump that version every time the plugin wanted to make an assumption about a feature existing in the SDK.

**Comment by pq** [comment]
Actually, that would be awesome.  Are there plans to bump this by anyone else that you're aware of?

@devoncarew : that should fit the bill eh?

**Comment by abarth** [comment]
> Are there plans to bump this by anyone else that you're aware of?

Not yet.  We'll still learning what it might be useful for.

**Comment by devoncarew** [comment]
My 0.02: I would put this on the back burner until there are more official releases (an alpha / stable channel).

**Comment by pq** [comment]
SGTM

**Comment by mit-mit** [comment]
@devoncarew for the first public release of the IJ plugin should we not at least check for a specific min version (which is the one we test against)?

**Comment by pq** [comment]
> @devoncarew for the first public release of the IJ plugin should we not at least check for a specific min version (which is the one we test against)?

My gut too.  I think we can punt on the `VERSION` tweaks but it would be great to have some kind of check in place to ensure folks don't get snagged by stale flutter tools.

**Comment by devoncarew** [comment]
It sounds like the intent here is to capture super old installs of Flutter.

**Comment by devoncarew** [comment]
Can we have `flutter_tools` report how old it is?

**Comment by sethladd** [comment]
We say "XX days ago" in --version:

```
~/Code/flutter/examples/flutter_gallery[master*] $ flutter --version
Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision 1b9c1bd2a9 (5 days ago) • 2016-10-06 15:32:03
Engine • revision f97caf271c
Tools • Dart 1.20.0-dev.10.1
```

**Comment by pq** [comment]
@abarth, @sethladd  : after a bunch of discussion I think we converged on bumping the `VERSION` file after all.  Any objections to me doing that today?

**Comment by abarth** [comment]
Go for it.

**Comment by pq** [comment]
Awesome.  Thanks!
