### ISSUE TITLE
Property tooltip docs missing (RESOLVED)

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1994]
This _used_ to work (#1847) but testing in 2018.1, consistently seeing:

![image](https://user-images.githubusercontent.com/67586/37847200-42d6b8ce-2e8d-11e8-8381-bcfc92e0a2b4.png)

**Comment by jacob314** [comment]
Maybe for now we should just not display any tooltip if the result is 
"Unable to find property source". Even when tooltips are working, I think that is the right UI to display as some properties have synthetic names so there will not be a matching property in the source.

**Comment by pq** [comment]
False alarm!

The rub is I had forgotten to add the  `--track-widget-creation` flag.  

![image](https://user-images.githubusercontent.com/67586/37876040-1a321006-2ffc-11e8-8616-19ed2b32d9c8.png)

With that in place, all's well:

![image](https://user-images.githubusercontent.com/67586/37876020-eae29bae-2ffb-11e8-8588-4bf2137c54c7.png)

👍 

Behavior when no docs are available is still open for discussion.

Also, if the flag will be needed for much longer, we should perhaps consider more nudges to help folks discover it.

/cc @devoncarew @jacob314

**Comment by jacob314** [comment]
Strange. I can't think of anything in that code that should depend on track
creation location.
