### ISSUE TITLE
while trying to run my first app i was getting Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.  error in android studio console and running the flutter doctor in command prompt it is showing   Doctor summary (to see all details, run flutter doctor -v): [√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-IN) [!] Android toolchain - develop for Android devices (Android SDK 26.0.2)     X Android SDK file not found: C:\Android\platforms\android-27\android.jar. [√] Android Studio (version 3.0) [!] VS Code (version 1.20.0) [√] Connected devices (1 available) is it neccasary to install sdk 27 

### ISSUE THREAD

**Issue by vivekanandasuggu** [flutter/flutter-intellij#2002]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
The quickest fix is probably to uninstall Flutter then follow the instructions here:
https://flutter.io/setup-windows/
