### ISSUE TITLE
ArgumentError in widget inspector: matrix cannot be inverted

### ISSUE THREAD

**Issue by robertoscaramuzzi** [flutter/flutter-intellij#2012]
## Steps to Reproduce

I run my app and then click on the leftmost icon in Flutter Inspector (the one that's supposed to open the correct place in the tree when you tap on a widget in the app)

When I then tap anywhere in the app, nothing happens except that the following error is displayed in the console

I/flutter (20810): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (20810): The following ArgumentError was thrown while handling a gesture:
I/flutter (20810): Invalid argument (other): Matrix cannot be inverted: Instance of 'Matrix4'
I/flutter (20810): 
I/flutter (20810): When the exception was thrown, this was the stack:
I/flutter (20810): #0      new Matrix4.inverted (package:vector_math/src/vector_math_64/matrix4.dart:226:7)
I/flutter (20810): #1      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:567:33)
I/flutter (20810): #2      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #3      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #4      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #5      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #6      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #7      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #8      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #9      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #10     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #11     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #12     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #13     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #14     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #15     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #16     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #17     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #18     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #19     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #20     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #21     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
I/flutter (20810): #22     _WidgetInspectorState.hitTest (package:flutter/src/widgets/widget_inspector.dart:613:5)
I/flutter (20810): #23     _WidgetInspectorState._inspectAt (package:flutter/src/widgets/widget_inspector.dart:631:41)
I/flutter (20810): #24     _WidgetInspectorState._handlePanDown (package:flutter/src/widgets/widget_inspector.dart:640:5)
I/flutter (20810): #25     DragGestureRecognizer.addPointer.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:123:52)
I/flutter (20810): #26     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (20810): #27     DragGestureRecognizer.addPointer (package:flutter/src/gestures/monodrag.dart:123:9)
I/flutter (20810): #28     RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:602:18)
I/flutter (20810): #29     RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2397:27)
I/flutter (20810): #30     BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (20810): #31     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (20810): #32     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (20810): #33     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (20810): #37     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:136)
I/flutter (20810): #38     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
I/flutter (20810): (elided 3 frames from package dart:async)
I/flutter (20810): 
I/flutter (20810): Handler: onDown
I/flutter (20810): Recognizer:
I/flutter (20810):   PanGestureRecognizer#cb3d6(debugOwner: GestureDetector)
I/flutter (20810): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (20810): Another exception was thrown: Invalid argument (other): Matrix cannot be inverted: Instance of 'Matrix4'

## Version info

[!] Flutter (Channel google3, vnull, on Linux, locale en_US.UTF-8)
    • Flutter version null at //third_party/dart/flutter
    • Framework revision 3352a3fb48 (6 days ago), 2018-03-20T00:00:00.000
    • Engine revision 6280adbfb1
    • Dart version 06949dc985
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5
      

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/google/home/birdo/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio-with-blaze-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-with-blaze-3.0
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • Pixel XL • HT6CP0201879 • android-arm64 • Android 8.0.0 (API 26)

**Comment by stevemessick** [comment]
@jacob314 could you take a look and move this if necessary?

**Comment by jacob314** [comment]
I think the version of the flutter repo you have just doesn't have the fix yet. :(
Hopefully you will get a new version of flutter with the fix in just a few days.
