### ISSUE TITLE
Support for Intellij 2018.1?

### ISSUE THREAD

**Issue by kroikie** [flutter/flutter-intellij#2019]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Updated from Intellij 2017.3.5 to 2018.1 and now the Dart and Flutter plugins are not available.

## Version info
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.2.4-pre.62, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
[✓] VS Code (version 1.21.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
By "not available" do you mean that your previous installation disappeared or that you cannot install them from Plugins Preferences page? They both should be available in the window that pops up after clicking "Browse repositories". 

Any idea why 2018.1 does not show up in your `flutter doctor` report? BTW Android Studio 3.1 also came out today.

**Comment by kroikie** [comment]
By "not available" meaning that they were initially "red" in the plugin browser, so I uninstalled them with the hope of reinstalling them, however I could not find them, they were no longer listed.

I reinstalled the previous version of Intellij 2017.3.5 which was able to recognize my dart/flutter project.

**Comment by stevemessick** [comment]
I just downloaded 2018.1 CE to check this out. I did not import settings. When I opened the plugin preferences, I first installed the Dart plugin and restarted. This is what I see now:
<img width="1025" alt="screen shot 2018-03-28 at 7 37 18 am" src="https://user-images.githubusercontent.com/8518285/38038960-03827c76-3261-11e8-8767-4eec2849c040.png">

I suspect you have an installation problem. `flutter doctor` is pretty good at listing all the IntelliJ/Android Studio installations it can find, and it does not show that you have 2018.1.

**Comment by stevemessick** [comment]
We'll leave this for another day in case any more information surfaces. If not, we will close it as not reproducible.

**Comment by kroikie** [comment]
This was user error, I had to reinstall them for the new version.

**Comment by stevemessick** [comment]
That's good information. Thanks for letting us know! We'll see if there is a way to make this less troublesome.
