### ISSUE TITLE
"Create Constructor" for Widgets

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#2021]
Hey hey :) I find myself creating a lot of Widget constructors, and I end up repeating the same manual process over and over. I thought it might be cool if this could be part of the Flutter IntelliJ plugin!

tl;dr -- "Create Constructor" should produce an idiomatic constructor for Widgets.

Full Steps:

  1. type `stless` to create a Stateless Widget
  2. Add a final field to the Widget
  3. Put cursor over the final field
  4. Alt-Enter
  5. Select "Create Constructor for Final Field", produces: `MyWidget(this.title);`
  6. Change this to conform with the normal Flutter rules: `MyWidget({Key key, this.title}) : super(key: key);`
      - All fields optional
      - Includes a `Key` and proper call to `super`.

Not a huge deal, but I've done it so much recently I thought it'd be nice if it could be generated for me :) Thanks again for all the hard work -- the plugin is getting sooooo good.

**Comment by stevemessick** [comment]
Well, @scheglov what do you think? We already treat Widget subclasses specially in other ways for some assists.

**Comment by scheglov** [comment]
@brianegan Could you please point me out on the "normal Flutter rules", so that I could read more about it?

**Comment by scheglov** [comment]
Ah, I found it.
https://docs.flutter.io/flutter/widgets/StatelessWidget-class.html

> By convention, widget constructors only use named arguments. Named arguments can be marked as required using @required. Also by convention, the first argument is key, and the last argument is child, children, or the equivalent.

**Comment by brianegan** [comment]
Yep, that's it! Sorry about the slow response, appreciate ya taking a look at it :)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/48700

![flutter_createconstructor](https://user-images.githubusercontent.com/384794/38051483-516762c2-3283-11e8-84f9-d1eb1e9d3d52.gif)

**Comment by brianegan** [comment]
Omg, amazing. Thanks so much!

**Comment by leslieharland** [comment]
How can I view the light bulb? It does not appear on Android Studio on highlight.

**Comment by devxpy** [comment]
@leslieharland  Alt + Enter

**Comment by rune007** [comment]
My newly installed Android Studio / Flutter / Dart does not generate Widget constructors in accordance with Flutter rules, how can I make it do that?
[https://stackoverflow.com/questions/62524041/can-i-make-android-studio-generate-dart-constructors-code-with-named-parameters](https://stackoverflow.com/questions/62524041/can-i-make-android-studio-generate-dart-constructors-code-with-named-parameters)

**Comment by Astonished2see** [comment]
> https://dart-review.googlesource.com/c/sdk/+/48700
> 
> ![flutter_createconstructor](https://user-images.githubusercontent.com/384794/38051483-516762c2-3283-11e8-84f9-d1eb1e9d3d52.gif)

Really useful but no one talks about this and I have seen most people doing this manually which is really strange, don't people like auto-completion?
