### ISSUE TITLE
Not able to create flutter project on Android Studio

### ISSUE THREAD

**Issue by Rissmon** [flutter/flutter-intellij#2025]
I am getting the view below when I create flutter project on Android Studio:
![flutterissue](https://user-images.githubusercontent.com/28339332/38089049-c237ada6-337b-11e8-9cf8-cae7ea72c80f.png)

I am facing this issue since when I tried to import a flutter sample project from the directory
`E:\RD\Flutter\flutter\examples`. I am not able to create a single new project after that.
When creating a new flutter project I tried changing the directory path for the same. The project path doesn't get changed, the project is created on one specific path `E:\RD\Flutter\flutter\examples`.

Please see the log below:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 6.3.9600], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.1)
[!] Connected devices
    ! No devices available

**Comment by stevemessick** [comment]
Two questions:
 - Have you done `flutter doctor --android-licenses` (in a terminal window)?
 - Do you have write access to the target directory?

Also, don't use "Import", use "Open" instead.

**Comment by stevemessick** [comment]
For completeness, this also has some good info that may be applicable for recovering a Gradle version mismatch: 
https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1

**Comment by Rissmon** [comment]
Thank you. It's working

**Comment by stevemessick** [comment]
Thanks for letting us know. The licensing issue needs improvement.
