### ISSUE TITLE
move to just supporting 2017.3 and Android Studio 3.1 as the lower bounds of our supported IDEs

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2027]
We should update our build systems to just produce 2017.3/AS 3.1 and 2018.1 builds. This will allow us to remove most or all of the places where we currently have to use reflection.

**Comment by alexander-doroshko** [comment]
I guess you mean **2017.3**/AS 3.1 and 2018.1

**Comment by devoncarew** [comment]
Yup! Updated above.

**Comment by devoncarew** [comment]
fixed by https://github.com/flutter/flutter-intellij/issues/2027
