### ISSUE TITLE
bug in AS 3.1 affects the inspector

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2029]
There's a bug in AS 3.1 which is impacting the inspector. The tab the we use to display "no running devices" in the inspector doesn't get removed when an app runs. It makes it look like the inspector just never recognized that an app launched:

<img width="243" alt="screen shot 2018-03-29 at 2 50 53 pm" src="https://user-images.githubusercontent.com/1269969/38115468-017a027c-3361-11e8-901b-c2cd624c7786.png">

<img width="252" alt="screen shot 2018-03-29 at 2 50 59 pm" src="https://user-images.githubusercontent.com/1269969/38115476-06c81098-3361-11e8-9cca-f73d06bc7f29.png">

<img width="298" alt="screen shot 2018-03-29 at 2 51 08 pm" src="https://user-images.githubusercontent.com/1269969/38115479-0b749c7e-3361-11e8-8d35-85fa0b18ba56.png">

We should find a workaround to the issue, or remove the "no running devices" initial tab, at least for Android Studio 3.1.

@jacob314 @stevemessick

**Comment by stevemessick** [comment]
Quick work-around is to tap the device name.

<img width="428" alt="screen shot 2018-03-29 at 3 27 00 pm" src="https://user-images.githubusercontent.com/8518285/38116609-b96f4636-3365-11e8-85c7-be44941ed14c.png">

**Comment by devoncarew** [comment]
Yeah, makes sense. When it first saw this, I didn't notice the device tab, just the 'no running apps' text.
