### ISSUE TITLE
Help users identify the source of the box-constraints/size of a widget

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2032]
When I use the inspector to debug a layout problem, I often need to find out what makes my widget so tall or wide, etc. However, it's not obvious how I'd tell what decides the size and box constraints of the widget I'm looking at, unless I carefully examine the rendering tree and properties. It would be great if the inspector can help me find out. Here are some ideas:

1. Show the layout behavior of the selected widget. The doc [Dealing with box constraints in Flutter
](https://flutter.io/layout/) says:

> Generally, there are three kinds of boxes, in terms of how they handle their constraints:
> 
> * Those that try to be as big as possible. For example, the boxes used by Center and ListView.
> * Those that try to be the same size as their children. For example, the boxes used by Transform and Opacity.
> * Those that try to be a particular size. For example, the boxes used by Image and Text.

Can we identify the layout behavior employed by the widget and show it via the inspector?

2. Visualize the layout process by building the subtree under the currently selected widget one widget a time. For example, I wants to understand what makes the Card so tall in the following code. Is it the default behavior or the Card or something else? Let's try to have an empty card and see what happens.

```dart
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Card(
        child: new Column(
          // To solve the problem, add the following line:
          // mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            new Text(
              'Heading',
            ),
            new ListView(
              shrinkWrap: true,
              children: <Widget>[
                new Text('Item 1'),
                new Text('Item 2'),
                new Text('Item 3'),
                new Text('Item 4'),
              ],
            )
          ],
        ),
      ),
    );
  }

```

To start, I ask the inspector to "step through" tree nodes starting from the Card:
![image](https://user-images.githubusercontent.com/348942/38119139-4e3586dc-3374-11e8-9753-e099c91a8fc2.png)
It’s clear that the Card does not seek to take all the available space. Instead, it takes as little space as possible to accomodate its content. 

Then, I ask the inspector to keep going and add the Column widget to the widget tree (and it will do a hot reload to refresh the UI).

![image](https://user-images.githubusercontent.com/348942/38119213-ee9defd8-3374-11e8-8a74-0ee8b620ee8d.png)
Now, it's pretty easy to see that the Column caused the Card to be tall.

**Comment by jacob314** [comment]
Moved to https://github.com/flutter/devtools/issues/461
as experimental inspector features will be added to devtools first.
