### ISSUE TITLE
Feature request: make definition of widget tree node be found easily in Flutter Inspector

### ISSUE THREAD

**Issue by jerrywell** [flutter/flutter-intellij#2034]
Currently, the widget tree is separated by it's class type, which means if we want to update a value for a widget (e.g. style), we must to traverse many nodes to find the custom widgets to see the definition in the build function block. 
so if there is a way that show build block for a bunch of sub tree nodes, it would be very useful to trace back to the code definition. 

for example:

```
class C {
  ...
  @override
  Widget build(BuildContext context) {
    return L1(
      child: L2(
        child: L3(
          child: L4(Colors.black)
        )
      ) 
    );
  }
}
```

the widget tree will show
C -> L1 -> L2 -> L3 -> .. lots of child widgets in L3 -> L4 -> .., which L1-L4 are Flutter widgets. We need to find the C to change the value of L1-L4. The idea is:

```
C -> C[L1 -> L2 -> L3 -> .. lots of child widgets in L3 -> L4 -> ..]
```
so tracking will become easier.

Another case is, our designer will use inspector to quickly find the definition of styling and change it, which works very efficiently in our validation process in website design.

**Comment by stevemessick** [comment]
@jacob314 @pq for consideration.

**Comment by InMatrix** [comment]
@jerrywell If I understand it correctly, you're looking for a way to jump to the line of code that instantiated the widget you're inspecting. This feature is available, if you run your project with these additional arguments: `--preview-dart-2 --track-widget-creation`. Please let me know if it doesn't work for you or I misunderstood your request.

**Comment by jerrywell** [comment]
yes. that's my idea. thanks for much, @InMatrix :)))

**Comment by InMatrix** [comment]
@jerrywell Glad that worked for you. I'm interested in learning how your designer interacts with Flutter code. Please let us know if the designer runs into any difficulties.
