### ISSUE TITLE
Flutter Inspector "Jump To Source" menu is disabled

### ISSUE THREAD

**Issue by uenx** [flutter/flutter-intellij#2038]
## Steps to Reproduce
1) Click on an item of widget tree to open the context menu. 
2) The menu action "Jump to Source" could not be selected.

Please let me know if this feature is currently supported or not.

![flutter_inspector_jump_to_source_disabled](https://user-images.githubusercontent.com/3197265/38159568-fe9cb028-34e5-11e8-8ccf-67a0e1f7810b.jpg)

## Version info

$ flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D47, locale ja-JP)
    • Flutter version 0.1.5 at /Users/ngominhtri/flutter
    • Framework revision 3ea4d06340 (5 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/ngominhtri/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.10.0

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.

**Comment by devoncarew** [comment]
That feature depends on some work that's not yet enabled by default. In order to enable it, you need to opt-into the Dart 2 preview (from the Flutter preferences page), and in your launch config pass `--track-widget-creation` into the additional args setting.

@jacob314

**Comment by jacob314** [comment]
To avoid confusion we can hide instead of just disabling the menu item when we know on startup that the feature is not supported.

**Comment by devoncarew** [comment]
I'm closing this - with the M24 release `--track-widget-creation` is much easier to enable.

**Comment by wheymajor** [comment]
I am new to this and I dont really get where to enable --track-widget-creation.
I am starting the app from android studio, is it possible to use the command from there too or only from the command line?

**Comment by rodelrebucas** [comment]
@wheymajor, Android studio>file>settings>flutter, Check run application with --track-widget-creation.
Make you sure you have the flutter plugin installed.

**Comment by HeinKhantZaw** [comment]
I have done everything but still can't jump to source from inspector

**Comment by HeinKhantZaw** [comment]
I have done everything but still can't jump to source from inspector.

**Comment by sylvaindiv** [comment]
Any news about it ? It's not working at all for me..
