### ISSUE TITLE
outline view should show tests for flutter code

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2055]
We currently show tests in the outline view if they match the pattern `group()` / `test()`. Flutter uses `testWidgets('name', () { }`, and other micro test frameworks layered on top of package:test have other patterns for the test name (`testUsingContext()`, ...). It would be nice to support these patterns as well.

**Comment by devoncarew** [comment]
From some discussion, in order to be able to identify tests accurately, it would be good to have a `@isTest` or similar annotation - something that will tell us that `test()`, `testWidgets()`, `testWithContext()` ... are test definitions. The annotation would need to live somewhere general, and would be applied at the definition of the test method (not the use site - not on individual users tests).

**Comment by grouma** [comment]
Having an annotation seems like a reasonable approach to me. I don't have strong feelings where the annotation lives. Maybe @natebosch or @jakemac53 have opinions?

**Comment by natebosch** [comment]
I'd be in favor of having an annotation in `package:meta` and _using_ the annotation in `package:test`.  I like the idea of this being a general Dart concept with `package:test` being one particular usage.

**Comment by grouma** [comment]
On second thought, I think it makes more sense to reside in package:meta. I assume whatever tool is used to parse these annotations doesn't currently depend on package:test (in a non-dev context). Since package:test has tons of other dependencies it will be preferable to depend on package:meta only.

**Comment by scheglov** [comment]
Pulling in many dependencies is a valid concern, but it seems to me that places that will use these new annotations (`@isTest` and `@isTestGroup`) already reference `package:test`. These are either helper methods in the `test` folder of a package, or in the `lib` folder of a specialized test package, like `package:flutter_test`. In any case, they already call `group()` or `test()`.

As for general concepts, it could be not the idea that there are alternative testing frameworks, but the idea that there are invocations of methods similar to `test()` that we want to show in the outline. But it is not `@isTest`, it is more like `@OutlineItem(kind, textArgumentIndex)` and `const isTest = const OutlineItem('test', 0)` is just one instance, declared in `package:test`. This way, if we get to the point when there is a need for general concept, we can generalize. But for now, I think `@isTest` and `isTestGroup` should live in `package:test`.
