### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by abhiisinghh** [flutter/flutter-intellij#2065]
✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

If have also set the Android Home PATH in .bashrc file, like below:
export ANDROID_HOME=/root/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

But Still getting same error

**Comment by pq** [comment]
Could you run flutter doctor and paste the results here?  You can run it from the command-line via `flutter doctor`, and from IntelliJ via `Tools > Flutter > Flutter Doctor`.  Thanks!

**Comment by abhiisinghh** [comment]
Hi,
Thanks for your reply, but my issue has been resolved.

**Comment by pq** [comment]
Great to hear.  Thanks for following up!

**Comment by abhiisinghh** [comment]
I have one issue , in Android studio Flutter detecting the Android device
contacted via usb but it’s not detection my iPhone, could you please help
me out in this.

I’m using Ubuntu 16.04Lts

**Comment by pq** [comment]
Yeah, this is unfortunately a limitation of the platform. You can't run the iOS simulator on linux. ☹️

**Comment by abhiisinghh** [comment]
I’m using physical iPhone connected via usb.
So what’s the way could I run my flutter apps on iOS device.

**Comment by pq** [comment]
Whoops.  I was too quick in responding.  Unfortunately, the answer is basically the same.  To build for and run Flutter on iOS we need Xcode and there's no supported path for that on linux unfortunately.  Not a substitute obviously, but you *can* toggle the platform in the inspector and that will give you a taste of your app on IOS.

![image](https://user-images.githubusercontent.com/67586/38574608-14c63354-3cae-11e8-8b8a-4e23c927f0ca.png)

For the real iOS heavy lifting you'll need XCode though.

**Comment by abhiisinghh** [comment]
It’s means I need a Mac device for this.

**Comment by pq** [comment]
That's correct.

**Comment by abhiisinghh** [comment]
In mac, android studio able to detect iPhone?

In Ubuntu could I able to generate the iOS release or debug app?

**Comment by pq** [comment]
> In mac, android studio able to detect iPhone?

Android Studio on the Mac should detect an iPhone.

> In Ubuntu could I able to generate the iOS release or debug app?

I'm not aware of any way to do this.
