### ISSUE TITLE
Drive 'flutter build' from Build menu

### ISSUE THREAD

**Issue by acrozes** [flutter/flutter-intellij#2072]
## Steps to Reproduce

After the creation of a new project, the default project run, but if we try to "Build Project" there are some errors: 

```
Information:java: Errors occurred while compiling module 'testnew1_android'
Information:javac 1.8.0_152-release was used to compile java sources
Information:10/04/2018 02:31 - Compilation completed with 6 errors and 0 warnings in 26s 37ms
C:\flutter\testnew1\android\app\src\main\java\com\yourcompany\testnew1\MainActivity.java
Error:(3, 18) java: package android.os does not exist
Error:(8, 8) java: cannot access android.view.accessibility.AccessibilityManager
  class file for android.view.accessibility.AccessibilityManager not found
Error:(10, 27) java: cannot find symbol
  symbol:   class Bundle
  location: class com.yourcompany.testnew1.MainActivity
Error:(9, 3) java: method does not override or implement a method from a supertype
Error:(11, 5) java: cannot find symbol
  symbol:   variable super
  location: class com.yourcompany.testnew1.MainActivity
Error:(12, 44) java: cannot find symbol
  symbol:   variable this
  location: class com.yourcompany.testnew1.MainActivity
```

## Version info

IntelliJ IDEA 2018.1 (Community Edition)
Build #IC-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3

C:\flutter\flutter\bin\flutter.bat --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [version 6.3.9600], locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by pq** [comment]
Thanks for the report.  We had a discussion about a similar issue but I can't find it (maybe @mit-mit can recall?) . The rub is that "building" doesn't make sense for Dart projects... That said, building the Java bits for android should _just work_.

cc @stevemessick who may have ideas.

**Comment by stevemessick** [comment]
You don't build Flutter project. They are automatically built when run.

**Comment by acrozes** [comment]
Maybe a "Build project" should create an apk without running it ...

**Comment by stevemessick** [comment]
Actually, that's a good idea. We should rewrite the Build menu to drive Flutter's builder.

**Comment by devoncarew** [comment]
Thanks for the feedback! We have a related issue here: https://github.com/flutter/flutter-intellij/issues/989 w/ some discussion; I'm going to close this issue in favor of the existing one.
