### ISSUE TITLE
Android studio seems to be executing an old version of my app

### ISSUE THREAD

**Issue by goleary** [flutter/flutter-intellij#2077]
## Steps to Reproduce

I have a simple app that uses an android alarm to print something to console every minute.  I started with the example from flutter/plugins for `android_alarm_manager`.  After changing the alarm and restarting the app (using the play button) the app is continuing to output the content of the previous build of my app.

![image](https://user-images.githubusercontent.com/16123225/38595128-ba944528-3cfe-11e8-9e70-353dd551f29d.png)

## Version info

```
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.2.3 at C:\Users\olear\flutter
    • Framework revision 5a58b36e36 (4 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\olear\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.22.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.2

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by pq** [comment]
Thanks for the report @goleary.

cc @devoncarew: I know something similar is being tracked but I can't find the relevant issue; maybe you can update?

**Comment by devoncarew** [comment]
You're on the beta channel, `v0.2.3`. I believe there are some issues with that release in terms of correctly determining when to re-compile kernel files.

Deleting your build/ directory (`flutter clean) should solve the immediate issue. You could also try switching to the dev channel to see if the issue is resolved.

**Comment by chrisogonas** [comment]
> flutter clean

This worked for me like a charm. Thanks @devoncarew .
