### ISSUE TITLE
Locale null countryCode in flutter internationalization

### ISSUE THREAD

**Issue by MarkBriggs2** [flutter/flutter-intellij#2093]
Question about  #internationalization
Working through the tutorial at https://flutter.io/tutorials/internationalization/<br>
Source at: 
https://github.com/flutter/website/tree/master/_includes/code/internationalization/intl/<br>
If supportedLocales parameter to MaterialApp constructor is as follows:
<pre>
supportedLocales: [
    const Locale('en', 'US'), 
    const Locale('es', 'ES'), 
  ],
</pre>
this initially works. If country codes are omitted: 
<pre>
supportedLocales: [
    const Locale('en'), 
    const Locale('es'), 
  ],
</pre>
 then the countryCode getter of the Locale object passed to DemoLocalizations.load() or GlobalMaterializations._computeLocaleName(Locale locale) (material_localizations.dart line 134) will be null so any attempt to access locale.countryCode.isEmpty will generate a NoSuchMethodError. <br>
Is this as intended?<br>
Thanks

**Comment by pq** [comment]
This issue was moved to flutter/flutter#16667
