### ISSUE TITLE
IntelliJ idea can't find android studio

### ISSUE THREAD

**Issue by bowojori7** [flutter/flutter-intellij#2113]
Having a problem with intellij idea. I have a Flutter project that's not finding some plugins (same issue in this thread #2089). So, I tried to right-click on the android folder -> Flutter -> Open Android module in Android Studio as described in this thread #1929, but that resulted in an error: Error opening Android Studio. Unable to locate Android Studio. I have Android Studio installed though so I don't know what the problem is. Is there a way to show intellij idea where android studio is located??

# Version info
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.2.8 at C:\Users\bowoj\flutter
    • Framework revision b397406561 (3 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\bowoj\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.1
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.3544.34

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Users\bowoj\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\181.4096.5
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4096.12

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by devoncarew** [comment]
@bowojori, you can tell flutter_tools where android studio is located, and that will likely help here:

```
flutter config --android-studio-dir <path/to/android/studio>
```

**Comment by bowojori7** [comment]
Thank you @devoncarew. This worked
