### ISSUE TITLE
flutter plugin NPE

### ISSUE THREAD

**Issue by ArthurYuCN** [flutter/flutter-intellij#2117]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.1.1` • Flutter plugin `io.flutter 23.1.2` • Dart plugin `173.4700`

Flutter 0.2.9-pre.6 • channel unknown • unknown source
Framework • revision 1a87c3a4b7 (3 weeks ago) • 2018-04-04 22:30:27 +0800
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

## Exception

null

```
java.lang.NullPointerException
	at com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcessZ$2.logError(DartVmServiceDebugProcessZ.java:162)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:99)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by pq** [comment]
I think this is fixed w/ https://github.com/flutter/flutter-intellij/pull/2083?

/cc @devoncarew

**Comment by devoncarew** [comment]
I believe so.

**Comment by xxnjdlys** [comment]
Thanks 👍
