### ISSUE TITLE
tracking issue for feedback on M24 plugin testing

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2123]
This is a tracking issue for feedback on the M24 plugin release candidate.

The testing script is here: https://github.com/flutter/flutter-intellij/blob/master/docs/testing.md

**Comment by stevemessick** [comment]
`Open in Android Studio` is always disabled for me. Need to check whether it has something to do with project structure (which I'm modifying) or is related to recent changes.

**Comment by devoncarew** [comment]
Notes on the release_24 branch:

It's currently up to date with 38a262f97.

We'll want to patch in:
- 76ba9a4d3

**Comment by devoncarew** [comment]
One issue found here: https://github.com/flutter/flutter-intellij/issues/2134, but this is known, and the resolution is not in the IntelliJ plugin.

**Comment by stevemessick** [comment]
Validate project creation location: https://github.com/flutter/flutter-intellij/pull/2140

**Comment by stevemessick** [comment]
Disallow installing into C12: https://github.com/flutter/flutter-intellij/pull/2141

**Comment by devoncarew** [comment]
I see lots of flashing in the FPS display - we should move back to double-buffering that.
