### ISSUE TITLE
Flutter plugin no auto-completion in IDE

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter-intellij#2126]
_From @pauldemarco on June 4, 2017 23:13_

## Steps to Reproduce

Create a new plugin:

> flutter create --org com.example --plugin hello

Open the new plugin directory with IntelliJ

Navigate to the android folder: 

> android/src/main/java/com/example/hello/HelloPlugin.java 

Attempt to view definition of _MethodCallHandler_

Notice there is no auto-completion or javadoc for these files.

This makes the learning curve just a little steeper for Plugin creation. Anything to ease this process would be beneficial to the Flutter ecosystem.

_Copied from original issue: flutter/flutter#10497_

**Comment by devoncarew** [comment]
We are working on a solution here; /cc @stevemessick

**Comment by stevemessick** [comment]
@justin-vanwinkle You can navigate in IntelliJ or Android Studio to the android module in the Project view, then use the menu option to open it in Android Studio. We're working on something better.

**Comment by gosoares** [comment]
I'm having the same issue. And if i open the android module of a plugin i got this:
![screenshot_20180828_135300](https://user-images.githubusercontent.com/9306656/44737972-dac08a80-aac9-11e8-8a65-4012baccff73.png)

**Comment by rohitranjan1991** [comment]
Same Issue. Any update on this ??

**Comment by JulianAssmann** [comment]
For me it's still not working. Are there any updates?
When I open the android portion of the plugin, it looks like this:

![image](https://user-images.githubusercontent.com/15306765/78880064-16b52300-7a55-11ea-902b-ffce386e5edb.png)

**Comment by janoschpelzer** [comment]
Any progress?

**Comment by ayRatul** [comment]
> @justin-vanwinkle You can navigate in IntelliJ or Android Studio to the android module in the Project view, then use the menu option to open it in Android Studio. We're working on something better.

This is the correct way of doing it. Open the plugin in android studio (you should have the flutter/dart plugin installed),then right click in the project android folder and select flutter>open Android module in android studio. The completion works.

**Comment by invingagan1** [comment]
Any progress in this. I have tried the steps given in the above comments but still not able to get the code intelligence.

**Comment by stevemessick** [comment]
Closing as obsolete. There are two ways to solve the problem:
- Open the Android module as its own project
- Enable the option that turns on Gradle syncing and indexing for Kotlin and Java
