### ISSUE TITLE
IntelliJ gives poor error message for "flutter create" with bad name

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter-intellij#2127]
_From @smrtsmrf on June 13, 2017 18:0_

## Steps to Reproduce
Attempt to create new Flutter project in Webstorm with capital letter (i.e "friendlyChat")

The IDE gives the error "Error creating project: Failed to run flutter create."

When trying to create the project with ```flutter create friendlyChat```, a very helpful error message is produced, identifying the capital letter as the culprit.

It would sure be nice if the IDE error was explanatory like the command line error.

_Copied from original issue: flutter/flutter#10662_

**Comment by pq** [comment]
We've improved this a bit since the report.

![image](https://user-images.githubusercontent.com/67586/39216505-cadd0708-47d0-11e8-95ea-0fbeea20e237.png)

The CLI is still a bit more verbose:

```
"zApO" is not a valid Dart package name.


From the [Pubspec format description](https://www.dartlang.org/tools/pub/pubspec.html):

**DO** use `lowercase_with_underscores` for package names.

Package names should be all lowercase, with underscores to separate words,
`just_like_this`.  Use only basic Latin letters and Arabic digits: [a-z0-9_].
Also, make sure the name is a valid Dart identifier -- that it doesn't start
with digits and isn't a reserved word.

```

but I think we're close enough, short of some deeper changes to project creation.
