### ISSUE TITLE
Flutter Swift plugins require cocoapods 1.5.0 (but we don't require it).

### ISSUE THREAD

**Issue by ksdboasit** [flutter/flutter-intellij#2134]
When I create a new project of type plugin and select swift as iOS language, I get the following error in the console:
```
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
Running Xcode clean...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET t18042415 OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/t18042415-umbrella.h"
            ^
    [...]/IdeaProjects/t18042415/example/ios/Pods/Target Support Files/t18042415/t18042415-umbrella.h:13:9: error: include of non-modular header inside framework module 't18042415': '[...]/IdeaProjects/t18042415/ios/Classes/T18042415Plugin.h'
    #import "T18042415Plugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 't18042415'
Could not build the application for the simulator.
Error launching application on iPhone X.
```
Can't really tell if it's just a local issue, so please let me know if you are able to reproduce it.

## Steps to Reproduce

1. Open IntelliJ or Android Studio
2. Create new flutter plugin project and select Swift as iOS language
3. Open iOS simulator (I used iOS 11.2, but I don't think that's relevant here)
4. Run example/lib/main.dart with iPhone Simulator selected as device

## Version info

[✓] Flutter (Channel master, v0.3.4-pre.17, on Mac OS X 10.13.1 17B1003, locale en-DK)
    • Flutter version 0.3.4-pre.17 
    • Framework revision c7ee37a0d8 (9 hours ago), 2018-04-23 21:26:51 -0700
    • Engine revision ec611470b5
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4203.498

[✓] Connected devices (1 available)
    • iPhone X • 1D826152-F576-4495-AB95-E7EECBE193A6 • ios • iOS 11.2 (simulator)

**Comment by pq** [comment]
Verified.  I see the same error against beta.

> [✓] Flutter (Channel master, v0.3.4-pre.2, on Mac OS X 10.13.3 17D102, locale en-US)

/cc @mravn-google

**Comment by pq** [comment]
Moreover, running in Xcode is similarly unhappy:

![image](https://user-images.githubusercontent.com/67586/39199854-57cbe378-479f-11e8-82f8-e5129bfca061.png)

**Comment by mravn-google** [comment]
You should upgrade Cocoapods to 1.5.0 and redo pod install.

**Comment by pq** [comment]
Bingo.  That worked.  Should `flutter doctor` flag this?

**Comment by mravn-google** [comment]
Yes, it should. Just haven't gotten around to that yet. Need to ensure we
have 1.5.0 installed on test bots first.

**Comment by pq** [comment]
Thanks.

A few related bugs for reference:

https://github.com/flutter/flutter/issues/15173
https://github.com/flutter/flutter/issues/16049

Should I open a fresh issue to track updating flutter doctor or repurpose one of those?

**Comment by mravn-google** [comment]
If you don't mind opening a fresh issue, that would be awesome. Thanks!
