### ISSUE TITLE
Customize names shown on recent projects, or reuse window for both Kotlin and Dart coding

### ISSUE THREAD

**Issue by fmatosqg** [flutter/flutter-intellij#2164]
My recent projects menu is quite hard to use

- I have to open multiple windows for developing an app (1) in parallel with a package's dart code (2) and its java code (3). Also I'd need to open example android submodule (4).

Each one of those windows gives me 1st class support on something (add flutter.jar dependency, or show git in the gutter, or support either gradle or dart). Althouth from window (1) I can access most files, it's quite hard to write anything other than trivial code.

A low hanging fruit may be to put meaningful names when creating projects or at least when showing in recent projects. See my screenshot after a couple of weeks of using flutter. The blurred names are pure Android projects, note that occasionally I also have to jump from one to another, so I expect this practice to continue with flutter.  

A second low hanging fruit could be opening a project or package's android project and a) applying a plugin that brings us flutter.jar (not happening for packages) and also b) allowing us to edit dart files belonging to the parent folder.

I don't mind much missing the dart console or analyzer panels, as long as I have logcat. 

As a side benefit this could consume a lot less memory, which is a scarce resource for some people. XCode can eat quite a lot without any encouragement.

EDIT: The context of the toughest problem is when overriding the dependencies with a folder, as in
```
dependency_overrides:
  flutter_blue:
    path: '~/code/android/flutter/flutter_blue'
```
![image](https://user-images.githubusercontent.com/5360753/39346512-dc9ce2b6-4a31-11e8-8370-367d24391542.png)

**Comment by stevemessick** [comment]
Yeah, those recent project menu names are not very descriptive. We want to make it so you only need to open a single project window per app, but that won't address the lack of specificity in that menu.

**Comment by fmatosqg** [comment]
Less windows is the golden goal, I just assumed it was harder.
