### ISSUE TITLE
Auto-format code breaks when missing parenthesis.

### ISSUE THREAD

**Issue by agrosner** [flutter/flutter-intellij#2167]
## Steps to Reproduce

Expected: Code formatting will remain intact and the editor will highlight the issue. I can format code and it will leave other UI builder code from outside widgets intact. 
Actual: Create widget. Accidentally forget a parenthesis somewhere in the hierarchy. CMD-Option-L for reformat (on Mac OS). Observe that a lot of the code further down the chain of UI code "flattens" and displays very broken.

before
```dart
@override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: AppBar(
          title: Text(job.getUIName()),
        ),
        body: SingleChildScrollView(
          child: Container(
              padding: EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Text(
                    buildInfo.displayName,
                    style: textStyleLarge,
                  ),
                  Text(
                    buildInfo.getDisplayTime(),
                    style: textStyleLarge,
                  ),
                  Text(
                    buildInfo.getCause(),
                    style: textStyleMedium, // <---------- Missing parenthesis
                  Padding(
                      padding: EdgeInsets.fromLTRB(0.0, 16.0, 0.0, 8.0),
                      child: Text(
                        "Artifacts",
                        style: textStyleMedium,
                      )),
                  _renderArtifacts(context),
                  _renderCommitButton(context),
                  _renderSectionTitle("Feature Changelog"),
                  _renderFeatureChangelog(context),
                  _renderSectionTitle("Jira ChangeLog"),
                  _renderJiraChangeLog(context),
                ].where((w) => w != null).toList(),
              )),
        ));
  }
```
After:
```dart
@override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: AppBar(
          title: Text(job.getUIName()),
        ),
        body: SingleChildScrollView(
          child: Container(
              padding: EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                Text(
                buildInfo.displayName,
                style: textStyleLarge,
              ),
              Text(
                buildInfo.getDisplayTime(),
                style: textStyleLarge,
              ),
              Text(
                  buildInfo.getCause(),
                  style: textStyleMedium,
                  Padding(
                      padding: EdgeInsets.fromLTRB(0.0, 16.0, 0.0, 8.0),
                      child: Text(
                        "Artifacts",
                        style: textStyleMedium,
                      )),
                  _renderArtifacts(context),
                  _renderCommitButton(context),
                  _renderSectionTitle("Feature Changelog"),
                  _renderFeatureChangelog(context),
                  _renderSectionTitle("Jira ChangeLog"),
                  _renderJiraChangeLog(context), 
                  ] // <---- this happens most of the time. sometimes it consumes a lot more.
                  .
                  where
                  (
                  (
                  w) => w != null).toList(),
        )),)
    );
  }
```

## Version info

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.3.5, on Mac OS X 10.13.4 17E199, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
[✓] Connected devices (3 available)

Dart Intellij Plugin: 181.4668.60
Flutter Plugin:  24.0.2

**Comment by devoncarew** [comment]
@agrosner, thanks for the report! I think this is a dup of https://github.com/flutter/flutter-intellij/issues/1413.

The issue here is that on broken code, IntelliJ uses its internal parser to format code instead of dartfmt. If the parser fails to recover somewhere in the file, you'll see formatting issues from that point on. We've improved the recovery of the parser for specific issues in the past. We may want to do that here as well, or decide to move to 1) not formatting files with syntax issues, or 2) always shelling out to dartfmt for full-file formats.

/cc @alexander-doroshko

**Comment by bwilkerson** [comment]
`dartfmt` made the explicit decision to _not_ produce results when there are syntactic errors. I think that was the right decision and one the IntelliJ should also follow.

**Comment by alexander-doroshko** [comment]
Thank you for the bug report!
I've fixed it in the Dart plugin. 
I believe my fix covers all cases when a syntactic error appears directly in the argument list. Should you see similar formatting problems (token per line) with syntactically invalid code, feel free to paste the sample code [here](https://youtrack.jetbrains.com/issue/WEB-32559), I'll check that all such cases are fixed.

**Comment by devoncarew** [comment]
closing in favor of https://github.com/flutter/flutter-intellij/issues/1413

@alexander-doroshko, I am able to get this formatting behavior to happen fairly reliably when editing code; I'm using 2018.1.2. We may want to re-open https://youtrack.jetbrains.com/issue/WEB-32559, or have a new issue to use to append snippets of code that don't format well.

**Comment by alexander-doroshko** [comment]
Fix for WEB-32559 is not yet available, the fix is in master branch only. You may add code samples as comments of that issue and I'll check if it needs an additional fix.

**Comment by AleksandarFaraj** [comment]
I believe if you sent out a survey about developer satisfaction with flutter, this is going to be one of the biggest pain points with flutter development. This issue is worse than anything language/framework specific I've had to deal with before.

**Comment by alexander-doroshko** [comment]
@AleksandarFaraj, as far as I know, all known issues like this are already fixed in the latest releases. Please paste a problematic code sample and IDE / Dart plugin version that you use. Thanks!
