### ISSUE TITLE
Imports added via quick fix should be added below license

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#2169]
When I add an import via a quick fix (hover over an unresolved simple and select 'Import xyz' from the hover menu) the import sometimes is added above the license header. Imports should always be added below it.

The import is usually added above the license header when the quick fix tries to add a `dart:` import to a file that does not have any `dart:` imports listed yet.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/52940
