### ISSUE TITLE
Improve plugin repository metadata.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#217]
![screen shot 2016-09-30 at 10 33 05 am](https://cloud.githubusercontent.com/assets/67586/19000816/6c957fb6-86f9-11e6-8f13-eca43e6e31f0.png)

Notably:
* N/A?
* missing Changelog and other details

**Comment by devoncarew** [comment]
Some of this may be due to our use of the third-party plugin repo.

**Comment by pq** [comment]
> Some of this may be due to our use of the third-party plugin repo.

Maybe.  Something to investigate.

**Comment by pq** [comment]
Change info is inlined like so:

```
  <change-notes><![CDATA[
    <ul>
    <li>Added inspection for title & underline length math (PY-10998)</li>
    </ul>
]]></change-notes>
```
