### ISSUE TITLE
Unable to list devices: Unable to discover Android devices. Please run "flutter doctor" to diagnose potential issues

### ISSUE THREAD

**Issue by JokerHYC** [flutter/flutter-intellij#2171]
Unable to list devices: Unable to discover Android devices. Please run "flutter doctor" to diagnose potential issues
---------------------------------------------------------------------------------------------------------------

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Linux, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] Connected devices (2 available)
 No issues found!

---------------------------------------------------------------------------------------------------------------

flutter devices
2 connected devices:

MI 6                         • 191d2aae      • android-arm64 • Android 8.0.0 (API 26)
Android SDK built for x86 64 • emulator-5554 • android-x64   • Android 8.0.0 (API 26) (emulator)

---------------------------------------------------------------------------------------------------------------

command line 'flutter run' works. but the plugin unable to list devices....

**Comment by devoncarew** [comment]
@JokerHYC, this is often due to issues in the PATH that IntelliJ / Android Studio is able to see. You can try running `flutter config`, and passing it the explicit path to the android sdk. That will ensure that IntelliJ knows where the android sdk is, and can use it to list android devices.
