### ISSUE TITLE
Derived parameters in libraries won't compile in latest Dart/Flutter version?

### ISSUE THREAD

**Issue by MarkBriggs2** [flutter/flutter-intellij#2195]
After flutter upgrade cipher libraries no longer compile. See https://github.com/flutter/flutter/issues/17239
I realize this isn't an intellij issue, but there's been no response yet on the Flutter forum, so I thought someone may have encountered this issue and have some advice. 
Specifically could:<ul>
<li>Revert to an earlier version of Dart/Flutter? Is that possible?
<li>Compile unchecked? But even build apk --release fails in the same way.
<li>Change library signatures myself in the short term until libraries are fixed. Arggh!
</ul>
Any advice is welcome.

**Comment by devoncarew** [comment]
@MarkBriggs2, you can try checking for an updated version of package:cipher (or issues filed against that package), and short-term, see if building in `--no-preview-dart-2` mode addresses the issue. the flutter gitter channel is also a good place to ask questions.

**Comment by MarkBriggs2** [comment]
Hi Devon, 
No updated cipher package yet, but I'll try your other suggestions. 
Thanks
