### ISSUE TITLE
Clear console on hot-restart

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2199]
## Steps to Reproduce

- Run a Flutter app in IntelliJ
- hot-restart

The console keeps the log from the previous run and it is difficult to see what log is from the current run.

## Version info

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.3.5, on Mac OS X 10.13.4 17E202, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.2)
[✓] Connected devices (2 available)

If others want the console content to persist adding settings to enable/disable might make sense.

**Comment by pq** [comment]
Thanks for the feedback!

As it happens, we'll be looking at an improved logging experience in the coming weeks so this is especially timely. 👍 

I opened up an issue for brainstorming (#2200); please feel free to chime in there!

**Comment by devoncarew** [comment]
@zoechi, can you provide a bit more details on how to repro? I'm trying to locally, and do see us clearing the console for both hot reload and hot restart.

**Comment by zoechi** [comment]
@devoncarew it's a feature request.
I want the console be cleared in hot reload the same as with hot restart.

Especially when working on UI errors are often printed dozens of times
and then it's hard to find which errors were before or after the last code changes.

**Comment by devoncarew** [comment]
I do see the console being cleared both for hot reloads and for hot restarts (full restarts). Is this not what you're seeing?

**Comment by devoncarew** [comment]
Ah, you have the verbose logging option on. We don't clear the console if that setting is enabled - we assume that people want the full history of the output for debugging reasons.

**Comment by zjw1918** [comment]
hi, how to "disabling verbose logging"?

**Comment by zjw1918** [comment]
After updated to flutter 12 stable (1.12.13+hotfix.5), the previous full history logs will be shown in the console every time when i run "flutter run".

ps:
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.914], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at ...
    • Framework revision 27321ebbad (2 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

**Comment by devoncarew** [comment]
> After updated to flutter 12 stable (1.12.13+hotfix.5), the previous full history logs will be shown in the console every time when i run "flutter run".

@zjw1918, can you file a new issue for this? I think this should be filed at the flutter/flutter repo, as this might be due to changes in how we scrape flutter logs.

**Comment by zjw1918** [comment]
Yea. Just realized the repo is intellij. Thanks.

**Comment by Ehtasha** [comment]
@zoechi  From where we disable verbose option ?
