### ISSUE TITLE
Make the flutter --track-widget-creation transformer handle windows paths more gracefully

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#2217]
The transformer should use local operating system paths instead of attempting to convert them
into valid URIs. Currently we have to use workarounds in the intellij plugin to make paths work.

**Comment by jacob314** [comment]
Sending paths in both formats shouldn't break anything. Feel free to do that if you want to make the transition easier in the future.

**Comment by jacob314** [comment]
We're switching the transformer to only return package: URLS instead of absolute paths making this issue obsolete.

**Comment by DanTup** [comment]
Does that mean we don't need to call `setPubRootDirectories` at all?

**Comment by jacob314** [comment]
you will still need to call it but the pub root directory needs to be in terms of the package: urls instead of absolute paths to be consistent.
