### ISSUE TITLE
gradle build is failing

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#222]
The gradle build needs to be updated for the latest version of the gradle-intellij-plugin (0.2.0-dev).

https://travis-ci.org/flutter/flutter-intellij/builds/164545798

**Comment by devoncarew** [comment]
@pq, @stevemessick, I temporarily turned off the gradle build until this is resolved -

**Comment by mit-mit** [comment]
Putting on the backlog for now; we can rely for manual builds even though painful...

**Comment by devoncarew** [comment]
This is obsolete now (as of https://github.com/flutter/flutter-intellij/pull/579)
