### ISSUE TITLE
Editing assists still add new

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#2224]
I thought we had a resolved but for this, but cannot find it. Looks like the editing assists still add the new keyword? cc @devoncarew

**Comment by devoncarew** [comment]
We had to revert, and decided to leave this off for now, and to re-enable near term.

We may also want a configuration option to control this behavior in the analysis options file.

**Comment by bwilkerson** [comment]
I would prefer not to have a short-lived option, but...
