### ISSUE TITLE
Open iOS Simulator doesn't work after cmd-w'ing the Simulator

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#2234]
## Steps to Reproduce

1. Start a single Android emulator
1. Stop all iOS Simualtors
1. Create Flutter project and select that Android in the device picker
1. Select iOS in the device picker
1. In the Simulator, hit `cmd-w` (not `cmd-q)
1. Select iOS in the device picker

Actual result: nothing happens
Expected result: iOS simulator is started

**Comment by pq** [comment]
I'm trying to repro.  When I close the simulator window, I don't see it any more in the device selector.

![image](https://user-images.githubusercontent.com/67586/39830252-ab38e664-5375-11e8-801a-bb90a5cc9313.png)

Are you still seeing it?

**Comment by pq** [comment]
It's true though when I select "Open iOS Simulator" I still don't get a device to show up.  I need to set up my device in the simulator as well.


![image](https://user-images.githubusercontent.com/67586/39830337-feb3ec6c-5375-11e8-82d1-3e1c477506da.png)

Is that the issue you're seeing?

**Comment by maryx** [comment]
Correct, when you close using ctrl w, it shows that there is no longer a device running. So a user may think "Let me press the iOS Simulator dropdown option". This results in no visual changes, and so, some confusion.

Note that while you're still in the Simulator program (the Simulator program is still in your cmd + tab lineup), once you cmd + q, and then select iOS as the device, the simulator starts up again visually without any problems.

**Comment by pq** [comment]
Awesome.  Thanks @maryx!

It looks like there are some hooks to interact with simulators from the command-line (`xcrun simctl`!) so I'll do a bit of digging.  While I've got your attention, I'd be curious what you would _expect_ to have happen in this case?

**Comment by pq** [comment]
After some digging it looks like we can query `simctl` for booted devices and take an action if there are none.  Unfortunately, it does not look like we can ask it for a "default" or have any way of knowing what the Simulator.app will boot on a fresh launch so I think rather than guessing (which I take it could be very surprising) I suggest we fall back on:

1. a notification suggesting they select a device in the Simulator and possibly also
2. offering to restart the simulator (which should "just work") or
3. just restarting the simulator (hoping this "just works" and is not surprising)

I'm in favor of 1 and possibly 2 but very open to ideas.

/cc @DanTup

**Comment by pq** [comment]
As a jumping off point, #2238 implements option 1.

![image](https://user-images.githubusercontent.com/67586/39841834-0745fb40-5399-11e8-80e1-2d62889857ce.png)

Word-smithing welcome. 😄

**Comment by DanTup** [comment]
I just did some testing, and it seems that if you pass `-n` to `open` it always does the right thing? If simulator is already running, it just switches to it. If it's running without a device, it seems to force it to spawn a device? Unless I'm misunderstanding, it's a perfect solution? :)

**Comment by DanTup** [comment]
Actually, not quite perfect... in the case where it's already running, it doesn't come to the foreground. However a simple fix could be to call it again without the `-n`?

**Comment by DanTup** [comment]
I've implemented this in `flutter emulator` and it seems to work; PR at https://github.com/flutter/flutter/pull/17460.

**Comment by pq** [comment]
Oh wow.  This is a MUCH better solution.  Thanks @DanTup!  I'll do some testing and update my PR.  Cheers! 🍻

**Comment by pq** [comment]
I did some testing this works great.  Much better flow.  Thanks @DanTup !

When #2238 lands, it should "just work"!

**Comment by pq** [comment]
Fixed w/ #2238.
