### ISSUE TITLE
Swap with parent fails

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#2249]
1. Create new flutter app
1. Replace main.dart with this: https://gist.github.com/mit-mit/2ae5e67a8e23f021596c0192e07ffb57
1. Do *not* reformat (then it doesn't repro)
1. Invoke Swap with Parent on line 22 (`new Expanded`)

=> code no longer passes analysis

**Comment by mit-mit** [comment]
cc @nfrydenholm, filed this for the issue you experienced

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/55268
