### ISSUE TITLE
Flutter actions should not show for non-dart files?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#2251]
I just saw this tweet:
https://twitter.com/bajicdusko/status/996463112260935680
from @bajicdusko.  Presumably that's just a bug in our IntelliJ plugin @devoncarew?

**Comment by bajicdusko** [comment]
Although mentioned by mistake above, still, I've tried on my side as well. 

Environment:
Flutter plugin 22.2.1 
Android Studio: 3.0.1 and 3.1.2

Mentioned behavior does not show up in the context menu, regardless of Kotlin or Java file. I'm sure Danny will provide an additional info.

**Comment by jwren** [comment]
I don't think that if IntelliJ lets us specify not to show such actions only for Flutter or Dart.

@pq @stevemessick ?

**Comment by jwren** [comment]
Assigning to you Steve for when your IDE sources get untangled.

**Comment by Aidanvii7** [comment]
I sent the screenshot to @dpreussler, my current setup is:
Android Studio: 3.1.2
Flutter plugin: 24.2.1

This happens with other file types (android layout xml files etc)

![image](https://user-images.githubusercontent.com/5406413/40110520-725d2c02-5900-11e8-8a8e-3f37f195d29e.png)

The refactor button on the popup for creating a widget does nothing at least :D

**Comment by stevemessick** [comment]
Unassigning so @pq and @scheglov don't think they need to wait for me in case they have a chance to fix it soon.,

**Comment by pq** [comment]
I see what's up here.  Taking a look at a fix...
