### ISSUE TITLE
Sample domain value should be example.com

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#2253]
Currently Flutter -> New Project in A.S. uses `yourcompany.com`, which is a commercial entity. Please change to `example.com`, which is reserved for example purposes.

**Comment by pq** [comment]
👍

**Comment by pq** [comment]
@mit-mit : is there a companion issue tracking changes in `flutter` proper?  Grepping around I see lots of uses of `yourcompany` in the examples.
