### ISSUE TITLE
Autocompletion without new

### ISSUE THREAD

**Issue by stychu** [flutter/flutter-intellij#2256]
When creating new widget and typing the new keyword before it for e.x. `new Conta` and clicking tab I do get the full completion for that widget (`new Container()`). When I don't use the `new` keyword and try to tab for autocomplete a just get the widget name like so `Container`

**Comment by bwilkerson** [comment]
Thanks for the report. That has been fixed in the bleeding edge version of Dart, and will be available in Flutter after Flutter has updated to a later build of the SDK.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/55506
