### ISSUE TITLE
Implement the "Implementations(s)" action

### ISSUE THREAD

**Issue by StokeMasterJack** [flutter/flutter-intellij#2258]
I love this feature of IntelliJ and use it all the time for Java and Kotlin.  It would  be hugely useful for Dart. 
 For my key mapping  it's Alt-Command B and has this description:

"Implementations(s) action: Navigate to the implementations(s) of selected class or method"

**Comment by scheglov** [comment]
There is such feature in Dart plugin for IntelliJ.

For example this code:
```dart
class A {
  void foo() {}
  void bar() {}
}

class B extends A {
  @override
  void foo() {}
}

class C extends B {
  @override
  void foo() {}

  @override
  void bar() {}
}
```

...gets annotations for extended / implemented classes, and overridden / implemented methods, both ways - to sub- and super- classes.

![image](https://user-images.githubusercontent.com/384794/40289743-018a7c10-5c6f-11e8-9d3a-85ab14f7b89f.png)

You also get the same navigation on a hot key, without pressing on an icon.
I use different keyboard shortcuts, but the menu icon should be similar for you.

![image](https://user-images.githubusercontent.com/384794/40289823-779ac720-5c6f-11e8-8a60-18ebf62a367f.png)
![image](https://user-images.githubusercontent.com/384794/40289790-48d53e52-5c6f-11e8-9b89-b67db5e5efa2.png)
![image](https://user-images.githubusercontent.com/384794/40289801-50d6e38a-5c6f-11e8-8c76-de15a8b7407f.png)

**Comment by StokeMasterJack** [comment]
It does not work, if the subclasses are part of the Dart API. Suppose I want to find all RenderBox subclasses. That case does not work:

![image](https://user-images.githubusercontent.com/123349/40325421-7acd0954-5cf0-11e8-864a-579075e62754.png)

**Comment by StokeMasterJack** [comment]
That to me is the more important part of this feature. I already know the subclasses for _my_ project. But this feature is really handy when trying to figure out how 3rd party libraries work.

**Comment by alexander-doroshko** [comment]
Agree, this is an important feature. It is tracked as https://github.com/dart-lang/sdk/issues/26762, and one more related: https://github.com/dart-lang/sdk/issues/29112

**Comment by scheglov** [comment]
WIP https://dart-review.googlesource.com/c/sdk/+/57760

![image](https://user-images.githubusercontent.com/384794/40816257-c676f87a-6500-11e8-9019-397f868745dc.png)
Note, that yellow items are in packages, not in the project.
