### ISSUE TITLE
Inspector: Long values are just cut off with no obvious way to view them

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#2266]
<img width="644" alt="screen shot 2018-05-23 at 10 04 57 am" src="https://user-images.githubusercontent.com/1227763/40439804-ec2bbcae-5e70-11e8-84cd-78911b199aa9.png">

I am interested in the exact value of `geometry` and `constraints` of a `SliverList`, but I can't see the full value because it's just cut-off by the edge of the screen (see pic above). there is no scrollbar or no other means to see the full value (my laptop screen is also too small to resize the inspector window to a size that shows the full value).

/cc @jacob314

**Comment by jacob314** [comment]
Would wrapping the values solve your use case? We'll also soon be supporting right clicking on properties/widgets/and render objects to open them in a full dart debugger view which will also let you get to the full exact value.

**Comment by goderbauer** [comment]
Wrapping would probably be good for now. Also, if it would have an option to copy that value, that would be nice, too. That would allow me to hand-format the value in my editor of choice and compare it easier to other values.

**Comment by jacob314** [comment]
I'll add a one click copy value. You'll also be able to copy the value from the debugger view of an object but that will require an extra step when all you want is the value.

**Comment by goderbauer** [comment]
Awesome! Looking forward to it.

**Comment by stevemessick** [comment]
This appears to be fixed. Please re-open if not.
