### ISSUE TITLE
Flutter Inspector is just blank on my Arch Linux Computer

### ISSUE THREAD

**Issue by faris** [flutter/flutter-intellij#2278]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Just attempt to open the flutter inspector from the menu ends up giving me this:

https://imgur.com/a/lyc02Z8

All i get is a blank Flutter Inspector with zero options.

I don't know if this helps or not but im using this tutorial to learn: https://www.youtube.com/watch?time_continue=141&v=ZwN7stRkwFs

## Version info

[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.4 at /opt/flutter
    • Framework revision f9bb4289e9 (2 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • ONEPLUS A5000 • cdecac4c • android-arm64 • Android 8.1.0 (API 27)

Thanks alot for the great plugin and I hope you guys can fix this easily :)

**Comment by jacob314** [comment]
It appears the Flutter application is not yet running or was not run from within Android Studio. The inspector window will be empty until an application is running. We should put text in the window that makes it clearer that is what is going. If the application is running you should also see a debugger window within Android Studio as well. Please reopen if you do not see the inspector after you get the app running from IntelliJ.

**Comment by Faris-Mohamed** [comment]
Thanks Jacob, my apologies this made it work perfectly.
