### ISSUE TITLE
Wish for a way to refactor a selection into a new Widget

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#2283]
Consider the code in https://gist.githubusercontent.com/Sfshaza/c07c91a4061fce4b5eacaaf4d82e4993/raw/4001a72c0133b97c8e16bdeb3195ca03525696bd/main.dart from the get-started codelab https://flutter.io/get-started/codelab/.

Consider the case where you want to refactor the logic for the 'Saved Suggestions' UI into a new widget.

If you place the cursor on line 107 (`return new Scaffold`) you can use the current Refactor>New Widget just fine. However, the lines above calculating `tiles` and `divided` really belong to that widget, so I think you would want to select lines 90-112 (starting with `final tiles = _saved.map(`, ending with `);`), and move all those lines to a new widget?

**Comment by mit-mit** [comment]
cc @scheglov WDYT?

**Comment by scheglov** [comment]
Hm... If we support for extracting selection, with several statements, it will resemble `Extract Method` refactoring even more. Not a bad thing per se, just more complex than it is now. I will look at some point.

BTW, there is also kind of refactoring (not implemented for Dart yet) - [Inline Parameter](https://www.jetbrains.com/help/resharper/Refactorings__Inline_Parameter.html).

**Comment by mit-mit** [comment]
I think it's OK that this is somewhat similar to Extract Method...

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/57704

**Comment by scheglov** [comment]
To be able to use it, we would need a small change to the IntelliJ plugin.
https://github.com/flutter/flutter-intellij/pull/2300
