### ISSUE TITLE
Consider having "Convert to Stateful Widget" move everything to State

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter-intellij#2287]
Currently if I use the context menu on a StatelessWidget and say "Convert to Stateful Widget", the resulting conversion keeps almost everything in the Widget instead of placing it in the new State Object.

However, in each case where I've wanted to convert a StatelessWidget to a StatefulWidget, I've wanted almost everything in my StatelessWidget to move to the State Objects.  Since the State Object will now build the Widget hierarchy, all of my intermediate calculations in the StatelessWidget now make much more sense in the State Object.

The only exception to this, for me, has been the public input parameters which obviously need to be taken into the Widget constructor and not the State objects.

I think this behavior would be more useful if it was altered to err on the side of putting too much in the State Object versus too little.

**Comment by scheglov** [comment]
I agree, it is good idea to move not just `build()`, but also things that it uses.

However I don't know Flutter well enough to know what is useful to move. Some members obviously cannot be moved: fields assigned in the widget constructors, overridden members (except `build()`); something else? Can Flutter widgets have getters that just combine values of input fields, and are used outside of the Widget/State, by other widgets?

We could either try to move everything that can be moved, or we could trace what is transitively used from `build()` and can be moved.

For example, we could wither move `area`, or keep it in the widget. Again, I don't know if there even is such pattern in Flutter.

```dart
class MyWidget extends StatelessWidget {
  final int width;
  final int height;

  int get area => width * height;

  @override
  Widget build(BuildContext context) {
    return new Text('$width * $height');
  }
}
```

**Comment by matthew-carroll** [comment]
As you've identified, speaking in generalities on this is a bit tricky.  But if we take your specific example, I would definitely move `area` to the State Object.

In Flutter, Widgets are immutable, temporary Objects that are composed with constructors.  Therefore, mutation methods will never be called on a Widget, and query methods generally only make sense when they're used directly or transitively from the `build()` method, which is in the State Object of a StatefulWidget.  So I'd say move everything possible to the State Object without breaking the build.  Constructor arguments to the Widget can remain, the rest should probably go.

I'll solicit other Flutter team members to check this out and offer insights if they have any.

**Comment by jonahwilliams** [comment]
It seems completely reasonable to move almost everything to the State class.  Like @matthew-carroll  said, mutating values on a Widget isn't an expected behavior that we need to support.

- class fields need to stay on the Widget
- getters could be left on the Widget or moved to State, I would default to moving but I don't see heavy use of getters.  Most values that are calculated on demand are either done in `build` or calculated on specific life cycle events which a stateless widget won't have.
- setters hopefully don't exist.
- methods are often used to split up the `build` method, so having them close to the `build` method is preferable.

**Comment by Hixie** [comment]
the StatelessWidget subclasses should only have constructors, and fields set by those constructors, the createState method, and static `of` methods (but those are unlikely to exist yet if you're still changing your mind about whether it stateful or stateless).

**Comment by InMatrix** [comment]
A related issue I haven't seen discussed above is that moving variables from the StatefulWidget class to the State class will make some of them not friendly to hot reload. Here is an example:

* Hot reload won't update the font size. 
```dart
class RandomWordsState extends State<RandomWords> {
  final _suggestions = <WordPair>[];
  final TextStyle _biggerFont = new TextStyle(fontSize: 18.0);
}
```

* Hot reload will update the font size. 
```dart
class RandomWords extends StatefulWidget {
  final TextStyle _biggerFont = new TextStyle(fontSize: 18.0);
  @override
  createState() => new RandomWordsState();
}
```

It's my opinion that if a variable is not supposed to change its value (e.g., _biggerFont) during the lifecycle of the widget, then it conceptually does not belong to the State class.

**Comment by matthew-carroll** [comment]
I'm a little confused. Are you worried about hot-reload (something that occurs when values change), or immutable members?

In your example, I would opt to place `_biggerFont` in the State Object because I tend to treat the Widget as a public API.  It's the stuff that I want a caller to be aware of and use.  Everything else I push below the public surface into the State Object.  There may be cases that go either way, but I have to imagine that the majority of the time anything that's not a constructor parameter to the Widget should exist in the State instead.  And we should enable the common case here, right?

**Comment by InMatrix** [comment]
I'm primarily worried about hot reload. By moving a member from the StatefulWidget class to the State class, the IDE will preclude changes to that member from hot reload.

**Comment by Hixie** [comment]
Having the values on the widget only updates them in a hot reload if the widget itself is recreated (e.g. by the parent widget's build method) during the reassemble. If it's on a State, the values would get reloaded if they were constants.

If a variable is not supposed to change its value during the life of the widget, it should be a constant.

**Comment by InMatrix** [comment]
@Hixie Thanks for the explanation. So in the example I provided above, I guess a better way to declare _biggerFont would be `static const TextStyle _biggerFont = new TextStyle(fontSize: 18.0);` Then modifying the value of fontSize will be reloadable when it's a member of the State class. 

Nonetheless, I suspect many immutable members are declared using `final` instead of `const` in reality. The example I provided actually came from our own [codelab](https://flutter.io/get-started/codelab/#step-4-create-an-infinite-scrolling-listview). Maybe we can add a lint to warn the user?

**Comment by scheglov** [comment]
@InMatrix we have two related lints: http://dart-lang.github.io/linter/lints/prefer_const_constructors.html and http://dart-lang.github.io/linter/lints/prefer_const_declarations.html . There is no lint for exactly this situation (that the `final` field could be `static const`) AFAIK.

```dart
class A {
  const A();
}

class B {
  final A a = const A();
}
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/60221

**Comment by tieorange** [comment]
+1
