### ISSUE TITLE
meta issue for releasing M25

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2288]
This is the tracking issue for releasing M25.

**Comment by devoncarew** [comment]
When run in Android Studio (3.1), the Project view opens with the `Android`  filter applied, and no Dart files are visible. You have to switch over to the `Project` filter to see your source files (and, many users are unlikely to know to do this).

<img width="294" alt="screen shot 2018-05-30 at 7 10 36 am" src="https://user-images.githubusercontent.com/1269969/40725641-c9752fa2-63d8-11e8-84c1-d2c0af5407f8.png">

**Comment by devoncarew** [comment]
After selecting the `Ffutter > Open module in Android Studio` menu, I see a gradle upgrade message:

<img width="562" alt="screen shot 2018-05-30 at 7 22 56 am" src="https://user-images.githubusercontent.com/1269969/40726373-72ef672c-63da-11e8-9d5b-050e76882554.png">

**Comment by devoncarew** [comment]
@stevemessick, I'm not able to get the new `Flutter commands` editor command bar to show up. I'm opening Java files from within the android/ directory of a Flutter project.

**Comment by devoncarew** [comment]
It's not possible to disable the --track-widget-creation flag now (I'll look at this).

**Comment by stevemessick** [comment]
@devoncarew In 3.2 the Project Structure menu item is not visible unless a project system is defined. For Flutter that is implemented by FlutterProjectSystem. Not sure why it would be an issue for 3.1. Has there been a new 3.1 release that possibly added that API?

**Comment by devoncarew** [comment]
> In 3.2 the Project Structure menu item is not visible unless a project system is defined. For Flutter that is implemented by FlutterProjectSystem. Not sure why it would be an issue for 3.1

Hey - I'm not 100% sure this _is_ an issue, but was going through our smoke test script, noticed that the Project Structure menu item wasn't visible in some places, and mentioned it here. Sounds like - in 3.1 - this is expected.

**Comment by stevemessick** [comment]
One thing we need to work on for 3.2 is a really good Project Structure editor. And I have a branch somewhere that starts that. But I think for 3.1 it should at least be visible from the menu. I cannot recall it not being there for 3.1, but it definitely is an issue for 3.2.

That and the missing command bar are problems that I would not expect to see in 3.1. As far as the missing command bar is concerned, that could easily be affected by non-obvious changes. It is very sensitive to changes in the algorithm to display the parent menu item.

IIRC I adde that item to the test script to give us early warning to API changes. Perhaps it is working as intended :)

Sorry, I don't have easy access to the full code base. i can take a look after returning to the office next week.

**Comment by ksdboasit** [comment]
Found this issue while testing M25 #2298 
Also got an exception when trying to create a new project in IntelliJ 2018.2 EAP, which pointed to the plugin. I filed a bug report through IntelliJ. Want one here as well?

**Comment by devoncarew** [comment]
@ksdboasit 

> Want one here as well?

Yes, please :) If you can file a new issue - and reference it here - that would be great.

**Comment by ksdboasit** [comment]
@devoncarew sorry for the slow response.
Here it is: #2302

**Comment by pq** [comment]
Thanks @ksdboasit!

**Comment by devoncarew** [comment]
>  sorry for the slow response.

No, thanks much for testing on EAP :)

**Comment by devoncarew** [comment]
Released: https://plugins.jetbrains.com/plugin/9212-flutter
