### ISSUE TITLE
Creating a new Flutter project with IntelliJ Ultimate looses the flutter root directory

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#2289]
## Steps to Reproduce
Open IntelliJ Ultimate 2018.1 build 5087
This issue does not reproduces in IntelliJ Community Edition.

File -> New Project -> Flutter
Select a valid Flutter SDK path
project is created but when the project opens the flutter sdk path is not set.

If the user sets the Flutter SDK manually to the same directory specified in the new project dialog path works fine but requires an extra step.

Worse, users are pushed down the wrong path as instead of getting a warning that their flutter sdk is not configured they get a warning that the Dart SDK is not configured which pushes them down the wrong path of setting the Dart SDK.
![image](https://user-images.githubusercontent.com/1226812/40739870-289a2de8-63fc-11e8-9849-495f4ce3e572.png)

## Version info

jacobr-macbookpro2:cache jacobr$ flutter doctor -v
[✓] Flutter (Channel unknown, v0.5.1-pre.23, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.5.1-pre.23 at /Users/jacobr/git/flutter/3/flutter
    • Framework revision c65e9d19a4 (3 hours ago), 2018-05-30 16:51:25 +0200
    • Engine revision 16f5cd8106
    • Dart version 2.0.0-dev.59.0.flutter-ff815d05a5

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jacobr/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin installed
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[!] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 181.4892.1
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5556                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • C338D5B9-AB50-4F81-8D6B-2188082E87F9 • ios         • iOS 11.3 (simulator)

! Doctor found issues in 2 categories.

@alexander-doroshko  might have an idea why we are seeing different behavior on Ultimate and CE fr this issue. Both @pq and I are able to reproduce the issue only occurring with ultimate.

**Comment by stevemessick** [comment]
@pq @jacob314 Does this still occur? If not, perhaps you can close it.
