### ISSUE TITLE
flutter doctor should test for IntelliJ not Atom

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#229]
Current output:

```
$ flutter doctor
...
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38
```

**Comment by pq** [comment]
cc @danrubel

**Comment by mit-mit** [comment]
@danrubel thinking more about this, I actually think we should do the new IntelliJ checks for fishfood so that we catch config issues for new users there. Looks like pq already tagged it. Does that sound reasonable?

**Comment by danrubel** [comment]
https://github.com/flutter/flutter/issues/5875

**Comment by mit-mit** [comment]
@danrubel should we consolidate those two bugs?

**Comment by pq** [comment]
@danrubel : is this reasonably on track for this week or should  we push it to the next milestone?

**Comment by danrubel** [comment]
[Detecting IntelliJ on Linux](https://github.com/flutter/flutter/pull/6227) has landed. Working on detecting it on Mac today.

**Comment by pq** [comment]
🎉

**Comment by pq** [comment]
@danrubel : I think this was close for the Mac right?

<img width="470" alt="screen shot 2016-10-13 at 6 19 15 am" src="https://cloud.githubusercontent.com/assets/67586/19350519/f93142da-910c-11e6-9f12-969e829ca2da.png">

Still only seeing Atom...

**Comment by danrubel** [comment]
It's close. Got distracted on other things. Need to address review comments for https://github.com/flutter/flutter/pull/6262, land it, then we'll have support for Mac.

**Comment by pq** [comment]
Cool!  

Question.  After a sync, I'm not seeing anything.  Does this mean it cannot find my IntelliJ installation(s)?

```
[~/src/git/clones/flutter] (master) $ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/pquitslund/src/git/clones/flutter
    • Framework revision e20ee045ba (44 minutes ago), 2016-10-13 10:44:20
    • Engine revision cf774d580c
    • Tools Dart version 1.20.0-dev.10.2

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[-] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.37

[✓] Connected devices
    • iPhone 6s Plus • 0D7C1CC6-767A-469B-B98E-6D2A295E8CDD • ios (simulator)
```

**Comment by danrubel** [comment]
Where do you have it installed?
If you email me the exact path, I can check that I'm searching the right directories.

**Comment by pq** [comment]
```/Application/Tools` is where I have all my IDEs but I'm guessing that's not standard.  Of course, what _is_ standard?

**Comment by danrubel** [comment]
The standard (when you run the IntelliJ `*.dmg`) is for it to be installed in `/Applications` and that's where the code checks. Should it scan `/Application` subfolders as well?

**Comment by pq** [comment]
Makes sense!

> Should it scan /Application subfolders as well?

I don't think it's unreasonable.  At least one level deep.  It's pretty common for folks to do a little management of their Apps directory.

**Comment by pq** [comment]
Landed. 🎉
