### ISSUE TITLE
the Flutter commands editor command bar doesn't display for files in android/, ios/

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2291]
The new Flutter commands editor command bar doesn't display for files in the android/ directory. For files in the ios/ directory, it displays, but the command name is `null`.

**Comment by devoncarew** [comment]
(for people following along, the impl is in `NativeEditorNotificationProvider`)

**Comment by pq** [comment]
Taking a look this evening.  Chime in if anyone else already is! 👍
