### ISSUE TITLE
Emulate AS Instant Run button for debugger & hot reload

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#230]
From @mit-mit 
Try to change the debug icon appearance and behavior to match Android Studio:

![android-studio-intant-run](https://cloud.githubusercontent.com/assets/8518285/19076423/91331200-89fd-11e6-8f50-526e7a1a0082.gif)

Clicking Debug starts the debugging session and changes the Debug icon to a "Debug Refresh" icon. Hitting this would do a hot reload for Flutter. Clicking stop ends the session.

Search for "Instant Run" to get started in AS sources.

**Comment by stevemessick** [comment]
Let's use standard abbreviations.

**Comment by mit-mit** [comment]
Tentatively tagging this for the parity milestone.

**Comment by devoncarew** [comment]
@stevemessick - you've looked at this - do you have a sense for approx. how much work this is? I'm wondering if it's small/medium/large. Thanks!

**Comment by stevemessick** [comment]
Actually, I haven't had a chance to do any more than the quick search I described. I don't know what's really involved in implementing it. It sounds like UI work, and not something standard in IntelliJ, so it could be a big job even though it seems small-ish. I would de-prioritize it until we were actually trying to integrate with AS. Is that happening now?

**Comment by stevemessick** [comment]
I made some progress on this, since it would also solve #332 and #334. See https://github.com/flutter/flutter-intellij/tree/enablement

It is blocked on flutter #6400.

**Comment by mit-mit** [comment]
@stevemessick and @johnmccutchan can you please sync on this today, Friday? Even if we cannot resolve this by early next week for 0.1, I think we really need this fixed in 0.2.

**Comment by devoncarew** [comment]
@mit-mit - would you say this is covered by https://github.com/flutter/flutter-intellij/issues/407?

**Comment by mit-mit** [comment]
Covered by #407
