### ISSUE TITLE
Unable to run flutter from Android Studio- Entry point isn't within current project

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2307]
_From @Sahas on March 3, 2018 19:8_

I created a new project using flutter, added english_words package as mentioned in the quick app guide. As the package contents were not reflecting, I restarted the Android Studio. Before restarting, the flutter run was working properly. After restart, I'm facing the below issue.

![image](https://user-images.githubusercontent.com/1641300/36938181-11fbdb10-1f44-11e8-9586-ebe4b6ca816b.png)

_Copied from original issue: flutter/flutter#15111_

**Comment by devoncarew** [comment]
_From @Hixie on May 31, 2018 17:44_

cc @devoncarew IDE bug

**Comment by devoncarew** [comment]
Thanks for the report - I'm not quite sure why this would be happening. Is there anything obvious different about the file paths for the project and the main.dart file?

You could try deleting that launch configuration and recreating one to see if the issue is with the specific launch config, and not w/ running that specific file.

**Comment by stevemessick** [comment]
What version of Android Studio are you using? Please attach a `flutter doctor -v` report.

**Comment by berkantkz** [comment]
I've the same issue. What additional information should I give in order to have a fix?

**Comment by HPH92** [comment]
I had this problem! 
The way I fixed it was clicking: File -> Project Structure -> Module 
And then add the root folder, then it will build and work again.

**Comment by MohamedRoushdy** [comment]
@HPH92 This solved the problem for me, Thanks.

**Comment by Sakshi492** [comment]
> I had this problem!
> The way I fixed it was clicking: File -> Project Structure -> Module
> And then add the root folder of the project, then it will detect that its a flutter app again, and then build and work again.

Worked for me as well. Thanks

**Comment by darthzulder** [comment]
> I had this problem!
> The way I fixed it was clicking: File -> Project Structure -> Module
> And then add the root folder of the project, then it will detect that its a flutter app again, and then build and work again.

I have the same problem 
![image](https://user-images.githubusercontent.com/38354552/54394948-beaac200-4684-11e9-9138-d8e0e198a3b9.png)


I tryed to do this, but I can´t find the Project Structure in File.
![Untitled](https://user-images.githubusercontent.com/38354552/54394476-54455200-4683-11e9-8f6f-35aac32a3b87.jpg)

my project is in D:\Desarrollo\Flutter\flutter_homework_01 but in android studio in project view is D:\Desarrollo\Flutter\flutter_homework_01\ **android** . before was OK (the first path) but now have ...\android. 
I dont know what happen and how to fix it.

please help.

![image](https://user-images.githubusercontent.com/38354552/54394778-3b896c00-4684-11e9-92f8-d3905eddb07b.png)

![image](https://user-images.githubusercontent.com/38354552/54394839-65429300-4684-11e9-8db6-ac93d5fc94f1.png)

**Comment by JaeW** [comment]
Same problem as @darthzulder.  If I create a new Flutter project, the File -> Project Structure option is visible.  In the Flutter project with issue, File -> Project Structure is not a listed option.  Also, in the Tools menu, the Flutter is no longer a menu option, and the Flutter toolbar options are missing.

**Comment by w3ggy** [comment]
The followings steps helped me:
1. In Android Studio click File > Sync Project With Gradle files.
2. Open *.dart file and click "Enable Dart Support for this Project".

**Comment by darthzulder** [comment]
> The followings steps helped me:
> 
> 1. In Android Studio click File > Sync Project With Gradle files.
> 2. Open *.dart file and click "Enable Dart Support for this Project".

![image](https://user-images.githubusercontent.com/38354552/55593207-057e5b80-5709-11e9-866f-09d42c1a8785.png)
 
there is no File > Sync Project With Gradle files.

**Comment by w3ggy** [comment]
> > The followings steps helped me:
> > 
> > 1. In Android Studio click File > Sync Project With Gradle files.
> > 2. Open *.dart file and click "Enable Dart Support for this Project".
> 
> 
> there is no File > Sync Project With Gradle files.

Try to import project via gradle again.

Latest releases of the Android Studio working bad with Flutter projects.
The debugger doesn't work, after re-opening project AS can't compile it.

**Comment by googleliyang** [comment]
There is a  simple way, just upload your code to git, then clone, reopen project with androidstuio, It will work fine. no thanks

**Comment by polenvinagre** [comment]
> The followings steps helped me:
> 
> 1. In Android Studio click File > Sync Project With Gradle files.
> 2. Open *.dart file and click "Enable Dart Support for this Project".

Works for me. Tks

**Comment by praveenb** [comment]
> I had this problem!
> The way I fixed it was clicking: File -> Project Structure -> Module
> And then add the root folder of the project, then it will detect that its a flutter app again, and then build and work again.

For Right click on Project -> Select Open Module Settings or F4 -> If any Exist there, delete and  Then then add the root content folder -> then set Edit Configurations -> Select Flutter Template> Select main.dart -> Then Enable And set Dart SDK path.

Solved the issue

Hope it helps.
![image](https://user-images.githubusercontent.com/592596/60336571-575c1800-99be-11e9-8926-4eaab976d2fd.png)

**Comment by RodacK** [comment]
this works for me

https://stackoverflow.com/a/56835790/8782229

**Comment by htaryuswe** [comment]
Thanks guys. All of you save my day

**Comment by esanthosh28** [comment]
Thanks...! works like charm...!!!!!!

**Comment by incker** [comment]
> File -> Project Structure -> Module

I have no `Module` in `Project Structure` =(

**Comment by Entschuldigung** [comment]
@praveenb Thanks!

**Comment by GoodLuck-GL** [comment]
I can't find Project Structure either.
But I fixed it by this way: File -> Invalidate Cache / Restart. 
It work! haha.

**Comment by heinzan** [comment]
I have same error in mac but cann't solve.Please help me someone.

**Comment by harshitlakhani777** [comment]
> I had this problem!
> The way I fixed it was clicking: File -> Project Structure -> Module
> And then add the root folder of the project, then it will detect that its a flutter app again, and then build and work again.

Where to find the root folder??

**Comment by ThePredators** [comment]
For me the solution was to delete the folder .idea/ that is located in the root folder of the flutter project. 

Then i restarted Android Studio and everything was fine !

Im using Android Studio 4.1 Canary 1

**Comment by Mtconcept** [comment]
> was

This works fine

**Comment by zubair538** [comment]
> For me the solution was to delete the folder .idea/ that is located in the root folder of the flutter project.
> 
> Then i restarted Android Studio and everything was fine !
> 
> Im using Android Studio 4.1 Canary 1

i delete .idea file and work for me

**Comment by Emred360** [comment]
It didn't work permanently, just temporary... And it doesn't work again thou all is set but still showing "entypoint isn't within the current project"

**Comment by BinTofajjal** [comment]
In my case.

I just added the code after 

import 'package:flutter/material.dart';

```
void main() {
  runApp(MyApp());
}
```

**Comment by AbdullahAli1993** [comment]
> For me the solution was to delete the folder .idea/ that is located in the root folder of the flutter project.
> 
> Then i restarted Android Studio and everything was fine !
> 
> Im using Android Studio 4.1 Canary 1

Thanks, man you saved my day

**Comment by swaroopmaddu** [comment]
Deleting .idea filder inside flutter project helped me.

**Comment by ErrorFo7nd** [comment]
add 

void main(){ runApp(MyApp());}

in your main.dart file // replace MyApp with your Class Name.

**Comment by vishnu-r-nair** [comment]
> Deleting .idea filder inside flutter project helped me.

This helped. Thanks for sharing.

**Comment by charmingQin** [comment]
> For me the solution was to delete the folder .idea/ that is located in the root folder of the flutter project.
> 
> Then i restarted Android Studio and everything was fine !
> 
> Im using Android Studio 4.1 Canary 1

This helped for me！

**Comment by nikkijuk** [comment]
After trying several hours quite some strange things I read something more from here, tried it, and now it works. Still: What exactly brought my project back to right state and why it suddenly wasn't dart/flutter project anymore is to me mystery.

**Comment by pmartinsons** [comment]
Re-selecting Dart entrypoint file (in the file selection dialog navigate again to main.dart) in the Run Configurations dialog solved the issue. Oddly enoug, old and new new paths were the same. Seems that somewhere some configuration got updated.

**Comment by Ethan-4u** [comment]
What worked for me:
(1) Uninstall android studio COMPLETELY and redownload android studio Beta 4.2 or higher, preferably.
(2)Do a custom installation and set the path to your flutter file on your c drive (c:).

**Comment by dungne** [comment]
> Deleting .idea filder inside flutter project helped me.

This helped. Thank you!

**Comment by Cristhianveal** [comment]
Si está utilizando vsCode, pruebe
este método : Eliminar la carpeta .vscode en el directorio del proyecto y volver a ejecutar el programa desde AndroiStudio

**Comment by BrightCode1** [comment]
> For me the solution was to delete the folder .idea/ that is located in the root folder of the flutter project.
> 
> Then i restarted Android Studio and everything was fine !
> 
> Im using Android Studio 4.1 Canary 1

Thank you very much cause it worked

**Comment by FaizanAhmad127** [comment]
> 
> 
> I had this problem!
> The way I fixed it was clicking: File -> Project Structure -> Module
> And then add the root folder of the project, then it will detect that its a flutter app again, and then build and work again.

It worked for me but I have to do it every time I restart my IDE(android studio). Any permanent solution?

**Comment by JuliaOP** [comment]
Open:  File -> Project Structure -> Modules 
and check the Dart box
it solved the issue for me 

![Screen Shot 2021-04-01 at 16 26 35](https://user-images.githubusercontent.com/2522105/113344105-0d2c6700-9307-11eb-9a0a-92379f2aad5f.png)

**Comment by asidt** [comment]
Removing .idea worked for me:

https://github.com/flutter/flutter-intellij/issues/2307#issuecomment-627768384

**Comment by dwitio** [comment]
> For me the solution was to delete the folder .idea/ that is located in the root folder of the flutter project.
> 
> Then i restarted Android Studio and everything was fine !
> 
> Im using Android Studio 4.1 Canary 1

Thank you very much, this work for me

**Comment by IbrahimYildirim** [comment]
I was having this issue and tried everything (Deleting `.idea/` folder updating project structure) and nothing was working.

Then i realised that the `pubspec.yaml` was not in the project. So i restored it with git and everything was working again.

**Comment by Panagiss** [comment]
Even if I create a new flutter project it will still say the "Entrypoint is not a Dart file"

**Comment by Moon-Ahn** [comment]
This brought me an exact solution.

**Comment by Moon-Ahn** [comment]
> 나에게 해결책은 flutter 프로젝트의 루트 폴더에 있는 .idea/ 폴더를 삭제하는 것이었습니다.
> 
> 그런 다음 Android Studio를 다시 시작했는데 모든 것이 정상이었습니다!
> 
> 저는 Android Studio 4.1 Canary 1을 사용하고 있습니다.

This brought me an exact solution.

**Comment by Moon-Ahn** [comment]
https://github.com/flutter/flutter-intellij/issues/2307#issuecomment-627768384

**Comment by pabloalencar** [comment]
I had this problem because I renamed the Flutter Project at VS Code and when I opened at Android Studio, the old name was coming from .idea files. 

To fix, I closed Android Studio and I deleted the .idea directory. Works for me.

**Comment by ramzieus** [comment]
I had the same problem because of the AGP Upgrade, the solution is to accept android licences
`flutter doctor --android-licenses`
