### ISSUE TITLE
Wireless Debugging does not work with Android Studio

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2308]
_From @phumberdroz on March 2, 2018 17:7_

## Steps to Reproduce

connect iPhone via usb
Open xcode -> window -> devices & Simulators -> select correct device and enable connect via network
Network Symbol is shown in the list to the left
disconnect iPhone

Android Studio shows devices but if you try to run it it is in an endless waiting loop without visual indication 

If you then connect the devices via USB it continues on

## Logs
https://gist.github.com/phumberdroz/9700d43d2bc9f5e510bebc6dab9b509c
## Flutter Doctor

[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.5 at /Users/phumberdroz/flutter
    • Framework revision 3ea4d06340 (8 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/phumberdroz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.20.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.2

[✓] Connected devices (2 available)
    • Pierre’s iPhone • ec754a5c0607923df2a99ccd051938e0045dee6b • ios • iOS 11.2.6
    • iPhone 7        • 5001A557-2FB6-49EB-8C5C-ABC8396F19E9     • ios • iOS 11.2 (simulator)

• No issues found!
> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

_Copied from original issue: flutter/flutter#15072_

**Comment by devoncarew** [comment]
_From @Hixie on May 30, 2018 22:37_

cc @devoncarew IDE bug

**Comment by es-RajatYadav** [comment]
`flutter run` is not showing my iPhone 11 (wirelessly connected), I'm on macOS Sonoma Developer beta.
