### ISSUE TITLE
Search in preferences doesn't work for Flutter plugin settings

### ISSUE THREAD

**Issue by filiph** [flutter/flutter-intellij#2309]
## Steps to Reproduce

1. Go to Android Studio preferences
2. Search for "widget"

This doesn't find the `Run applications with --track-widget-creation` checkbox.

![intellij_preferences_bug mp4](https://user-images.githubusercontent.com/919717/40865304-7db93344-65ac-11e8-94c7-5d49ba9b4bfb.gif)

This is the case for all options for the Flutter (and I think even the Dart) plugin — not just the option shown above. 

It's interesting that when I'm on that page and I start typing "widget", it'll highlight the option for a while, but then it will auto-update the list of relevant pages on the left panel, and it won't have that page there.

## Version info

[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2018.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)

**Comment by jacob314** [comment]
Generally the bug is to make sure all our options show up in the quick search not just that this specific one does.

**Comment by stevemessick** [comment]
@alexander-doroshko I noticed the Dart plugin settings are also not searchable. Any idea how to fix it?

**Comment by alexander-doroshko** [comment]
Dart plugin settings are probably not searchable in Android Studio and IntelliJ IDEA Community Edition but searchable in Ultimate Edition and WebStorm. I don't know exact steps to fix it at the moment. I think we need to debug the logic in IntelliJ Platform that searches for the settings. The fix might require changes in the Platform. We have a similar issue on our issue tracker: https://youtrack.jetbrains.com/issue/WEB-35257

**Comment by alexander-doroshko** [comment]
@stevemessick @jacob314 I've found `SearchableOptionContributor` extension point in IntelliJ Platform that seems to allow fixing this on the plugin end. Here's how I made 'dart closing labels' and some other options searchable: https://github.com/JetBrains/intellij-plugins/commit/4c64def4de519fa8507564b54e664e2395fcb859
