### ISSUE TITLE
Dart not always enabled for new Flutter Projects created from source.

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#231]
I created a new Flutter project on existing sources and found that it did not have Dart support enabled. I had to open the pubspec.yaml file and enable it there. It should have been done as part of project creation.

**Comment by pq** [comment]
Strange!  What steps did you use to create the project?

Using [these steps](https://github.com/flutter/flutter-intellij/wiki/User-Journeys#create-a-flutter-project-based-on-existing-source) that should _just work_.

**Comment by stevemessick** [comment]
That's what I did.

**Comment by pq** [comment]
Did `flutter create` get called?

**Comment by stevemessick** [comment]
How can I tell? Is there a log file somewhere?

BTW this was a big Flutter project, sync'd to pristine state. It had not had flutter doctor or pub get done on it previously. It took a long time to do pub get. I think I restarted the IDE at one point, but I'm currently single-stepping through (some of) the code.

**Comment by pq** [comment]
There should be a message pane at the bottom chrome:

<img width="440" alt="screen shot 2016-10-04 at 9 13 48 am" src="https://cloud.githubusercontent.com/assets/67586/19082417/ebfc5c40-8a12-11e6-85ea-23b48608b317.png">

**Comment by pq** [comment]
Updated title and add a bug label to indicate that this is expected to work.

**Comment by stevemessick** [comment]
That message is long gone. I believe I restarted IntelliJ at one point.

**Comment by stevemessick** [comment]
This is straightforward to reproduce. 
1. Get a pristine version of flutter/examples/flutter_gallery. `git status` should report no modifications.
2. Create a new Flutter project in IntelliJ pointing to that directory.
3. Open lib/main.dart
4. See the prompt to enable Dart support, as in the screen shot.

<img width="1096" alt="screen shot 2016-10-05 at 3 52 03 pm" src="https://cloud.githubusercontent.com/assets/8518285/19134646/194fe750-8b14-11e6-9a40-658481e0c92f.png">

I don't know if you're supposed to be opening the flutter_gallery directory like that. If not, I bet I won't be the only one who does. The message about obtaining a lock might be a clue.

**Comment by pq** [comment]
This is helpful thanks.  That message is definitely interesting!

**Comment by pq** [comment]
A few quick thoughts.

1. We set the Dart "nature" _after_ `flutter create` returns.  If you open a file before it returns, I'd expect to see this.  --- An easy fix is to queue up the nature assignment before we do the wait.  I'll look at that.
2. Besides that there's a larger issue of whether we should be calling `flutter create` for a project created from sources _in the first place_.  The trouble is, you _might_ so I'd hate to just turn it off in case, for example, the target directory exists.  Maybe we should provide a checkbox in the project wizard?  (Something like "Create sample Flutter App content"?)

All of this is just a reminder that we really want to flesh out the "create a project from source" flow...  

cc @mit-mit

**Comment by mit-mit** [comment]
Do we actually call `flutter create` when you create a new Flutter IJ project on a dir that already has flutter files?

**Comment by pq** [comment]
We do which is clearly a bug.

@devoncarew: did you do anything in Atom to decide when (not) to run `create`?  Is a non-empty directory a good-enough heuristic?

**Comment by devoncarew** [comment]
We probably want to differentiate between creating a new project and importing an existing one (that may not yet have all the intellij metadata). That probably maps to these two menu items?

<img width="513" alt="screen shot 2016-10-06 at 6 08 08 am" src="https://cloud.githubusercontent.com/assets/1269969/19153428/6ac47296-8b8b-11e6-8a09-6c41d3cec009.png">

**Comment by pq** [comment]
Ideally yeah.

The trouble is there doesn't appear to be any way for us to contribute to the "Project from Existing Sources..." flow and it's very much about importing eclipse, maven or gradle projects.

![screen shot 2016-10-06 at 6 20 03 am](https://cloud.githubusercontent.com/assets/67586/19153861/fe9e36c2-8b8c-11e6-8c62-bf9d7c71ed85.png)


Unless I'm overlooking something?

**Comment by devoncarew** [comment]
Hmm, ok. Not sure where the best place for us to plug in is then for importing existing projects. Perhaps we can adapt the 'create' flow to not call out to flutter create if there's a pubspec or flutter.yaml file? (This sounds similar to what you suggest above).

**Comment by pq** [comment]
I think for starters I'll use a *really* simple heuristic and just not call create if the directory is non-empty.

As for where to plugin long-term, we could adapt the existing New Flutter Project wizard to allow a user to specify that they are importing from existing sources (vs. creating new).  If we do that we could allow them to specify `main` and so on so that we can create a reasonable run config for them.

cc @mit-mit for thoughts.

**Comment by stevemessick** [comment]
Isn't 'flutter create' safe to reuse?

**Comment by pq** [comment]
> Isn't 'flutter create' safe to reuse?

Depends on what you mean.  The issue is that it creates a bunch of files for you that in the case where you're opening an existing project you don't want.
