### ISSUE TITLE
Enable selection of widgets in the inspector from within IntelliJ

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#2314]
Show a mirror of the device within intellij and allow selection from the mirror.
In particular, this will improve selection when dealing with physical devices.

**Comment by stevemessick** [comment]
@devoncarew @jacob314 This has been moved to five milestones. Do we think it will actually make it into M31? It looks like a new feature to me, so maybe we should be moving it out later.

**Comment by jacob314** [comment]
This item will be experimented with in the devtools instead of IntelliJ. In devtools there is more space so this layout makes more sense.
