### ISSUE TITLE
Device selection should be per-window, not global

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#232]
Open two Flutter projects (on separate code bases). Attach two devices. Select one device in one window, select the other device in the other window. Return to the first window and see that the device selection has counter-intuitively changed to what is current in the second window.

**Comment by devoncarew** [comment]
Makes sense. Looking at the code, the action surfacing the pulldown is setting and getting its info from the `FlutterDaemonService`. That's a singleton for the app:

```
FlutterDaemonService service = FlutterDaemonService.getInstance();
```

We'd need to either make one daemon instance per window (probably a good idea) or have a device selection service, and have one instance of that per window.
