### ISSUE TITLE
Externally focused documentation

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#233]
Checklist:

**New docs**:
  - [x] Add new "Developing apps in IntelliJ" page to the docs, mentioning:
     - [x] Setup and configuration (including system requirements, like version of Java, etc)
     - [x] Creating new projects
     - [x] Creating new projects from existing sources
     - [x] Editing source code and How to view and interpret "problems view" and the list of errors and warnings
     - [x] Running the app (in emulators and hardware)
     - [x] Debugging an app (in emulators and hardware)
     - [x] Hot Reloading and Restarting
     - [x] How to view device/emulator logs
     - [x] Observatory (basics of opening, and cross link to dart docs)
     - [x] How to file feedback/bugs
     - [x] How to upgrade the plugin(s)
     - [x] What the plugin doesn't do (and when to use flutter tool. e.g. upgrading Flutter?)
  - [x] Add a link in the top-level menu to the new Developing... page under How-Tos

**Updates to existing Flutter.io docs**:
  - [x] Update [Flutter Setup](https://flutter.io/setup/) replacing Atom with IJ
  - [x] Update [Flutter Getting started](https://flutter.io/setup/) replacing Atom with IJ
  - [x] Update [Flutter FAQ](https://flutter.io/faq/) replacing Atom with IJ: https://github.com/flutter/flutter/issues/6376
  - [x] Update [Flutter Debugging](https://flutter.io/debugging/) replacing Atom with IJ
Flutter-repo) replacing Atom with IJ
  - [x] Update [Flutter Bug reports](https://flutter.io/bug-reports/) replacing Atom with IJ (this is just the doctor output sample)

**Updates to wiki pages**:
  - [x] Update [Flutter WIKI: Styleguide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo)
  - [x] Update [hot reload wiki](https://github.com/flutter/flutter/wiki/Hot-Reload) replacing Atom with IJ

**Comment by pq** [comment]
Regarding IDE integration, I don't think there's a good story for hosting plugin docs _within_ the IDEA help system FWIW.  (See this [support topic]( https://intellij-support.jetbrains.com/hc/en-us/community/posts/206760095-how-do-i-plug-into-the-main-idea-help-system-).)

A good middle ground might be to add an action to open our docs to the top-level help menu:

![screen shot 2016-10-04 at 10 39 01 am](https://cloud.githubusercontent.com/assets/67586/19085371/f3910224-8a1e-11e6-86d7-8ce6ebb030ee.png)

**Comment by devoncarew** [comment]
Hopefully something on flutter.io?

We hosted the atom plugin docs separately from flutter (on github web hosting), but that didn't have a super coordinated experience w/ flutters docs.

**Comment by pq** [comment]
flutter.io would be great.

@sethladd : thoughts, reactions?

**Comment by mit-mit** [comment]
I agree. Seth, is your docs process for flutter.io described somewhere?

**Comment by sethladd** [comment]
Repo is here: https://github.com/flutter/website

Please send PR's and once merged, they get auto-deployed. Thanks!

**Comment by devoncarew** [comment]
I think we should also have an entry in the faq (flutter.io/faq) about editor choice and recomendations.

**Comment by sethladd** [comment]
Filed https://github.com/flutter/flutter/issues/6376 to track

**Comment by mit-mit** [comment]
I updated the first entry in this bug to contain a checklist of all the changes I plan on making over the next two days. @devoncarew @pq @stevemessick @sethladd please review and see if you think I am missing something!

**Comment by stevemessick** [comment]
No obvious omissions from my perspective.

**Comment by pq** [comment]
LGTM!

**Comment by sethladd** [comment]
Added a few items. Good list!

**Comment by stevemessick** [comment]
I just ran into a problem that should not affect many people, but might be worth mentioning.

With the latest version you cannot continue working on a project that was created with an earlier version of the Flutter plugin. The problem is that we only recently started marking Flutter projects with a module type and old projects do not have that. The solution is to create a new project pointing to the same source directory, and overwrite existing files (.idea, *.iml). The symptom is that there is no device selector in the tool bar.

**Comment by pq** [comment]
> With the latest version you cannot continue working on a project that was created with an earlier version of the Flutter plugin. 

Tracking bug filed: #341

**Comment by mit-mit** [comment]
flutter.io updates drafted, please review! https://github.com/flutter/website/pull/290

**Comment by pq** [comment]
Awesome.

Make @sethladd and @qchong happy and it works for me!

**Comment by mit-mit** [comment]
Completed
