### ISSUE TITLE
Show Icons for Custom Icon Packages

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#2334]
Not sure if this is possible, but it would be amazing if custom Icons were displayed in the IDE in the same way the MaterialIcons show up. This means when you're auto-completing, you would see the icon on the right-hand side of the pop-up window. Once it's set, you'd see the icon in the Gutter next to the Breakpoint indicators.

For example, it would be really cool if something like the [`font_awesome_flutter`](https://pub.dartlang.org/packages/font_awesome_flutter) package I've published, or a custom Icon set created by end-users would display a preview of their own icons.

The MaterialIcons preview feature is really handy, so it'd be cool to see this functionality available for all icons!

**Comment by pq** [comment]
@devoncarew had ideas for doing the render more dynamically and if we did that this would be a snap.  Not sure where he got with that idea though...

**Comment by brianegan** [comment]
Cool, thanks for your time and attention @pq :) Hope all is well!

**Comment by matejthetree** [comment]
This would be amasing

**Comment by StefanLobbenmeier** [comment]
Another package that would probably appreciate is this: https://github.com/ziofat/material_design_icons_flutter/issues/7

**Comment by lalmanzar** [comment]
This would be a really nice enhancement. It is kinda weird seeing the wrong icon when using a custom iconpack.

**Comment by cirediew** [comment]
If this were implemented I'd love if it could work with my own custom font as well.

**Comment by stevemessick** [comment]
See `com.intellij.psi.util.ProjectIconsAccessor` for hints on resolving the correct icon files.

**Comment by stevemessick** [comment]
Work on this has started. See #5504 for the current discussion, and chime if you have an opinion on it.
