### ISSUE TITLE
Display testGestures in the Structure view

### ISSUE THREAD

**Issue by edman** [flutter/flutter-intellij#2341]
The plugin is currently unaware of testGesture methods. In test files like `drag_test.dart` all you get in the structure view is a lonely main function. You also lose support for "Run only this test".

![screenshot from 2018-06-08 19-02-13](https://user-images.githubusercontent.com/1776440/41170897-acd5acd2-6b4e-11e8-9cc4-1437d6ed8212.png)

**Comment by edman** [comment]
Actually, structure view already displays that information in test files. Is it a bug that it is not reporting the test file structure correctly for me in `drag_test.dart`, or am I doing something wrong?

**Comment by edman** [comment]
Ok, I now notice the plugin is specifically unaware of `testGesture` tests.

**Comment by devoncarew** [comment]
If you edit the definition of `testGesture` to have an `@isTest` annotation, do the tests show up in the structure view?

**Comment by devoncarew** [comment]
(see the definition of `testWidgets`)

**Comment by edman** [comment]
Yes, that fixes the structure view. I still don't get the "Run tests in method" though.

**Comment by devoncarew** [comment]
Awesome!

@edman, you may want to create a PR against the flutter repo w/ the annotation change.

The logic for test execution is handling in the Flutter IntelliJ plugin (/cc @pq); the test display info is coming from the analysis server

**Comment by edman** [comment]
Will do! Thanks!

**Comment by devoncarew** [comment]
Closing (PR out at https://github.com/flutter/flutter/pull/18311)
