### ISSUE TITLE
Look for the `emulator` ADB tool first in emulator/, then in tools/

### ISSUE THREAD

**Issue by g123k** [flutter/flutter-intellij#2351]
Hello,

When I launch some Android emulators from the Flutter plugin on my Mac, I have the following error:
`PANIC: Missing emulator engine program for 'x86' CPU.`

![](http://i64.tinypic.com/15gs46r.png)

It can easily be reproduced with the Android tools:

```shell
tools/emulator -avd "Nexus_5X_API_27"
PANIC: Missing emulator engine program for 'x86' CPU.
```

However if I launch the emulator with the binary in the `emulator` folder, it will then works:
```shell
emulator/emulator -avd  "Nexus_5X_API_27"
```

I think the plugin should use the binary in the `emulator` folder instead of the one in the `tools`.

**Comment by devoncarew** [comment]
Thanks for the report (and time spent investigating!). @DanTup, which binary does flutter_tools use to launch, and does the above sound reasonable?

**Comment by DanTup** [comment]
In Flutter we prefer the one in `emulator` (which is the new one) but we'll fall back if it's not there (see below).

I didn't realise it was the `tools` one that caused this error - I always wondered why it seemed a bit hit and miss to me!

So I guess IntelliJ probably should move over to either using `flutter emulators` or at least preferring the one from the `emulators` folder.

```dart
  String getEmulatorPath() {
    final String binaryName = platform.isWindows ? 'emulator.exe' : 'emulator';
    // Emulator now lives inside "emulator" but used to live inside "tools" so
    // try both.
    final List<String> searchFolders = <String>['emulator', 'tools'];
    for (final String folder in searchFolders) {
      final String path = fs.path.join(directory, folder, binaryName);
      if (fs.file(path).existsSync())
        return path;
    }
    return null;
  }
```

**Comment by devoncarew** [comment]
We should likely update our search logic soonest, and plan to move over to the flutter_tools functionality after that.
