### ISSUE TITLE
Logging view: filter panel layout issues

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2353]
After patching in #2350, a few things to fix:

* notice the behavior on re-size
* ~also notice that the event count is no longer updating~ (likely unrelated)

![filter_resize](https://user-images.githubusercontent.com/67586/41249297-9d0aa21e-6d68-11e8-8612-9388779d1da1.gif)

/cc @quangson91

**Comment by pq** [comment]
@quangson91 : let me know if you're up for taking a look; otherwise I'm happy to.

**Comment by quangson91** [comment]
@pq let me fix that problem.

**Comment by quangson91** [comment]
@pq, Do you know how to inspect layout while development plugin ?
(I mean how we inspect layout of filter-actions?)

**Comment by pq** [comment]
Thanks @quangson91!

> (I mean how we inspect layout of filter-actions?)

Sorry, I don't. ☹️

**Comment by quangson91** [comment]
@pq I created a new PR here: https://github.com/flutter/flutter-intellij/pull/2361
Please take a look!

**Comment by pq** [comment]
Merged.  Thanks!

**Comment by pq** [comment]
Fixed w/ #2361
