### ISSUE TITLE
Odd logging error message with IntelliJ, "log: Must be admin to run 'stream' command"

### ISSUE THREAD

**Issue by csterritt** [flutter/flutter-intellij#2360]
## Steps to Reproduce

Ran `flutter create first_try`, cd'd into that directory.  `flutter run` works, comes up fine in the iOS emulator.  I can run in IntelliJ with the "Run" command (green triangle), but no hot-reload.

If I run with "Debug" command (green bug), I get the empty white screen on the iOS emulator, and the following output:

    Launching lib/main.dart on iPhone X in debug mode...
    log: Must be admin to run 'stream' command
    Script started, output file is /dev/null

    Script done, output file is /dev/null
    Starting Xcode build...
    Xcode build done.

## Version info

$ flutter doctor -v
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.4.4 at /Volumes/Second/Chris/hacks/flutter/flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Users/chris/hacks/flutter/jdk-10.0.1.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 10.0.1+10)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Users/chris/Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.24.0)
    • VS Code at /Users/chris/Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • iPhone X • D34D5096-B3F9-4930-822B-48D3BD71B83D • ios • iOS 11.4 (simulator)

! Doctor found issues in 3 categories.

**Comment by devoncarew** [comment]
@xster, @cbracken, re: the:

```
log: Must be admin to run 'stream' command
```

Do you have a sense for where this is coming from?

**Comment by xster** [comment]
More interesting was for me:
`Script started, output file is` but that string (or parts of it) don't appear in our repo. Was this on a custom fork branch?

**Comment by csterritt** [comment]
@xster Not sure if this is useful to your question, but I just downloaded the Mac installer from flutter.io, I didn't build from github or anything like that.

Thanks for the quick responses!

**Comment by devoncarew** [comment]
I suspect this is coming from a native tool that we're invoking? In anticipation of that, I'm going to route this to the flutter/flutter repo as a flutter_tools issue.
