### ISSUE TITLE
run/debug support (internal)

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#237]

**Comment by mit-mit** [comment]
Moving shim part to #239

**Comment by devoncarew** [comment]
After some discussions, this will consist of:

- an IntelliJ launch configuration that supports launching bazel run targets
- changes to the flutter tool to make the stdut/stdin streams from flutter run toolable, i.e. they should support json input and output as well as the regular user facing output

**Comment by devoncarew** [comment]
https://github.com/flutter/flutter-intellij/issues/392

**Comment by devoncarew** [comment]
closing this in favor of more granular issues
