### ISSUE TITLE
Flutter app freezes after Toggle Widget Select Mode

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter-intellij#2370]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Launch a flutter app (e.g., flutter gallery) from IntelliJ on my gLinux deskop and then click the Toggle Widget Select Mode button.

## Version info

````
[✓] Flutter (Channel master, v0.5.5-pre.14, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.5-pre.14 at /usr/local/google/home/liyuqian/flutter/flutter
    • Framework revision b401e76554 (2 hours ago), 2018-06-13 09:20:19 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/google/home/liyuqian/android/Sdk/
    • Android NDK at /usr/local/google/home/liyuqian/android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/google/home/liyuqian/android/Sdk/
    • Java binary at: /opt/android-studio-with-blaze-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-with-blaze-3.0
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[✓] Connected devices (2 available)
    • Nexus 5X                  • 00d6d019424cc952 • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by liyuqian** [comment]
cc @jacob314 @devoncarew : maybe my desktop just have the wrong settings. I would really appreciate if you can help me figure out what's wrong and how to fix it.

**Comment by liyuqian** [comment]
BTW, the flutter and dart plugins are actually installed and usable in Android Studio. I've no idea why flutter doctor keeps telling me that they're not installed.

**Comment by jacob314** [comment]
If you click on the device what happens? When widget select mode is enabled clicks on the app are supposed to trigger inspection changes instead of triggering the app to behave normally which may make it feel like the app is frozen depending on what kind of interaction you are trying to have with the app. If you can send screenshots of your IDE and your emulator assuming you are suing the emulator not the nexus 5x.

**Comment by liyuqian** [comment]
Please see the attached screenshot. I understand what should happen as the Toggle Widget Select Mode is working fine on my Macbook Pro. On my desktop, the app has absolutely 0 response to anything.

![screenshot from 2018-06-13 11-12-00](https://user-images.githubusercontent.com/22987568/41369802-c3ca730a-6efa-11e8-9f03-77596a8a05ce.png)

**Comment by liyuqian** [comment]
BTW, the command line "flutter run" + "i" works fine on my gLinux desktop.

**Comment by jacob314** [comment]
Interesting. When you click on a different widget in IntelliJ does the selected widget on the device update or not not?
If you use a physical android device instead of the emulator does it work?
If you exit inspector select mode from IntelliJ does the device does the device recover or stay frozen?

**Comment by liyuqian** [comment]
No for all three questions...

**Comment by liyuqian** [comment]
Switching to beta does fix the problem! Should I close this issue for "not going to fix it"?

**Comment by jacob314** [comment]
Closing as 
https://github.com/flutter/flutter/issues/18573
tracks the same issue.
A fix for the hang is in progress but there are still issues that mean you should stay on beta for now. Hopefully there will soon be a full fix.
