### ISSUE TITLE
improvements to analytics for hot reload

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2372]
@InMatrix, I investigated our current analytics. Currently, we sent:
- analytics events for hot reload and hot restart actions
- analytics timings for when reloads or restarts finish
- analytics 'workflow' events at the end of an app run, to mark a run as either using the hot reload workflow, the hot restart workflow, or neither

We do not send events for:
- hot reloads when performed via reload-on-save
- hot restarts when invoked from the run or debug buttons (clicking on the run button for an already running app)
- (we do send post-reload / restart timings for the above however)

Going forward, we want to track the ratio of reloads to restarts per user per day. I think this means:
- after a run session, or cumulatively per day, send a `reloadRestarts` ratio metric
- have the end of a run session count as one restart
- fix the bug where we don't send a ping for hot restarts when done through the run/debug button
- continue to not send individual analytics pings for reload-on-save

**Comment by InMatrix** [comment]
As we discussed in person, it might be easier to view the results if we can send the ratio metric to the Flutter Tool GA account.

**Comment by devoncarew** [comment]
Will plan to move (and update the issue w/ the latest, in terms of the time buckets to use).
