### ISSUE TITLE
Code folding on build() methods doesn't show folding sections when using optional new and const

### ISSUE THREAD

**Issue by pavel-ismailov** [flutter/flutter-intellij#2373]
## Steps to Reproduce

Open that code in Android Studio

```dart
    Container(
      child: Column(
        children: [
          Row(
            children: [Text("")],
          ),
          Row(
            children: [Text("")],
          ),
          Row(
            children: [Text("")],
          ),
        ],
      ),
    );

```

You can NOT see collapse / expand buttons at the left.
Then add "new" words everywhere.
You can DO see  collapse / expand buttons at the left.

```dart
    new Container(
      child: new Column(
        children: [
          new Row(
            children: [Text("")],
          ),
          new Row(
            children: [Text("")],
          ),
          new Row(
            children: [Text("")],
          ),
        ],
      ),
    );
```

## Expected behavior

See collapse / expand buttons in both the cases (with and without "new" words)

## Version info

```
[✓] Flutter (Channel master, v0.5.5-pre.5, on Mac OS X 10.13.3 17D102, locale ru-RU)
    • Flutter version 0.5.5-pre.5 at /Users/pavel/Development/flutter
    • Framework revision d1aaa406ac (2 days ago), 2018-06-12 11:04:49 +0200
    • Engine revision d33bbff470
    • Dart version 2.0.0-dev.60.0.flutter-a5e41681e5

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/pavel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • SM N920C • 83f0464f54334432 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 2 categories.
```

**Comment by devoncarew** [comment]
Thanks for the report!

@jwren, I believe the folding here is done by IntelliJ (and not the analysis server). Do you see a way to add support for optional new + const (w/o also showing folding section for every method call)?

**Comment by jwren** [comment]
No, the Dart PSI elements only know that they are constructors because of the new and const keywords.  To preserve the functionality here, we'd probably choose to fold on methods that start with a capitalized letter, which is not ideal, but would probably be sufficient.

What is worse is that gathering up all the method invocations takes time, for some Dart developers with larger files, we'd be adding more cost (in the form of lag), than value (folding of constructor invocations.)

We definitely shouldn't leave it as is, if we don't fold `Foo(...);`, we shouldn't be folding `new Foo(...);`.

I don't have any strong opinion here either way, but am happy to do this task.

**Comment by bwilkerson** [comment]
Note that the analysis server supports code folding and _does_ know whether the thing being invoked is a constructor.

**Comment by MilkBiscuit** [comment]
Please fix this ASAP, this code folding feature for DART is a must have for me...

**Comment by jwren** [comment]
Closing.  This should be fixed in the 2019.1 release of the Dart Plugin.

**Comment by tolotrasamuel** [comment]
How to install the 2019.1 release of the Dart Plugin? 
@jwren It says that this is not compatible . I used android studio 3.3

**Comment by jwren** [comment]
This feature was patched into the 182.5215 (2018.2.5 -- aka IntelliJ version used by Android Studio 3.3) a few hours ago, and released, https://plugins.jetbrains.com/plugin/6351-dart by @alexander-doroshko 

Updating to the latest Dart Plugin (Setting > Plugins > Dart) should give you this feature.

**Comment by FrenzyNwoba** [comment]
Code Folding Not Showing For Sub Sections In 2020
![Screenshot - 13_05_2020 , 7_59_15 PM](https://user-images.githubusercontent.com/64613243/81853374-3e1b7600-9554-11ea-9bce-a93b11df6406.png)

**Comment by alexander-doroshko** [comment]
@FrenzyNwoba, folding regions work fine for me, see screenshot. What's your IDE version? Could you paste the whole file text?
![image](https://user-images.githubusercontent.com/4499789/81855783-77f67780-9568-11ea-939c-0e652959b15b.png)

**Comment by FrenzyNwoba** [comment]
> IDE version

Android Studio 3.1.4
Build #AI-173.4907809, built on July 23, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**THE TEMPORARY FIX I'M USING**
Select The Code Area You Want To Fold Then Press ( Ctrl + . ) **Hold Ctrl the Tap Period (.)**

![Screenshot - 13_05_2020 , 9_55_11 PM](https://user-images.githubusercontent.com/64613243/81864381-732fc480-9564-11ea-877e-96acc38c40fd.png)

**Comment by alexander-doroshko** [comment]
@FrenzyNwoba, Android Studio 3.1.4 is extremely outdated. You'll get this folding feature as well as tons of other features and bugfixes if you update to the most recent Android Studio or IntelliJ IDEA version.
