### ISSUE TITLE
hot reload support - flutter_tools shim

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#238]

**Comment by stevemessick** [comment]
What still needs to be done?

**Comment by mit-mit** [comment]
These are just placeholders to make sure we don't forget, @danrubel is going to review them and close if he concludes there is no work

**Comment by danrubel** [comment]
WRT hot reload support, I'm happy to address any shim related work in flutter_tools as necessary... unless someone gets there first. I have not had time to look into it yet.

**Comment by devoncarew** [comment]
We decided not to go the shim route.
