### ISSUE TITLE
Inspect assets not exists in pubspec.yaml is not correct.

### ISSUE THREAD

**Issue by quangson91** [flutter/flutter-intellij#2384]
It seems to inspect assets not found in pubspec.yaml is not correct.
See image bellow:

<img width="731" alt="1" src="https://user-images.githubusercontent.com/6185205/41497461-feaac1f0-717f-11e8-8e78-e65ceb79abe4.png">

Another, the suggestion to fix that problem is also wrong.
<img width="416" alt="2" src="https://user-images.githubusercontent.com/6185205/41497467-1a1d976e-7180-11e8-8e57-ec7e277e3410.png">

After select the suggestion, the tools will put `// ignore: asset_does_not_exist` in the pubspec.yaml.
That comment is wrong format of `yaml`.
It should be `# ignore: asset_does_not_exist`, I thought.

<img width="339" alt="3" src="https://user-images.githubusercontent.com/6185205/41497468-1fe20216-7180-11e8-8d6e-1781847bf0b3.png">

**Comment by devoncarew** [comment]
I think there are two issues here.

It looks like asset references (`assets/graphics/`) can now include directories: https://flutter.io/assets-and-images/. We should update the analysis server validation to support this.

And, IntelliJ is suggesting suppression comments for these validations. I don't believe that the analysis server supports comments suppressions for pubspec files, so we shouldn't suggest here (and if we eventually support comment suppressions, we'd need IntelliJ to insert `# comments`. @jwren @alexander-doroshko

**Comment by alexander-doroshko** [comment]
I've pushed a fix to make sure that 'Suppress...' actions do not show up in non-Dart files.

**Comment by devoncarew** [comment]
Awesome! I filed an issue for the analysis server verification, so will close this issue in favor of that one.

**Comment by dnfield** [comment]
You can ignore it like this in `analysis_options.yaml`

This ignores it for now - in analysis_options.yaml

```yaml
analyzer:
  errors:
    # allow for asset_does_not_exist
    unrecognized_error_code: ignore
    # ignore this in pubspec.yaml
    asset_does_not_exist: ignore
```
