### ISSUE TITLE
Folding is not supported for the shorthand (=>) syntax

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter-intellij#2386]
I am able to fold any function or method in IntelliJ / Android Studio if it uses curly brackets:

```dart
Widget foldable() {
  return Very(
    child: Long(
      child: Widget(
        child: Tree(),
      ),
    ),
  );
}
```

I cannot fold a function that uses shorthand syntax (single expression)

```dart
Widget unfoldable() => Very(
    child: Long(
      child: Widget(
        child: Tree(),
      ),
    ),
  );
```

This is a problem in *Flutter* because I usually have these long widget trees and would really like to use the shorthand version.

**Comment by devoncarew** [comment]
Yes, this does sound asymmetric. Generally, the shorthand syntax is used for very short (1-2 line) functions, so it's likely less critical that we support folding here.

/cc'ing @jwren for FYI

**Comment by creativecreatorormaybenot** [comment]
@devoncarew I am just very used to it because this kind of folding is supported for Kotlin in IntelliJ.

**Comment by creativecreatorormaybenot** [comment]
You can now fold every widget itself and thus, this is not necessary anymore.
