### ISSUE TITLE
Make log level less LOUD.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2392]
Following up on https://github.com/flutter/flutter-intellij/pull/2391#pullrequestreview-130015082, a few options:

Lower-case:

![image](https://user-images.githubusercontent.com/67586/41606386-66f5ae54-7398-11e8-9c25-1e5734e7c48e.png)

Grayed:

![image](https://user-images.githubusercontent.com/67586/41606380-631262e6-7398-11e8-8fbb-8bdf4927b82b.png)

Versus current:

![image](https://user-images.githubusercontent.com/67586/41606442-8dbd9dda-7398-11e8-9929-63565740ac73.png)

/cc @devoncarew @quangson91

**Comment by pq** [comment]
I lean mildy towards Grayed but don't feel strongly...

**Comment by devoncarew** [comment]
I have a slight preference for lowercase, esp. in the body if the log row entry; UPPERCASE stands out quite a bit :)

When no severity filter is set (`NONE`), should we instead do something like have an empty string for the text?
