### ISSUE TITLE
Finish wiring up the Flutter Log Color page

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2396]
Follow-up from: #2394.

For `M26`, we'll want to:

-  [x]  update log color by getting setting from FlutterLogColorPage
-  [x] set default color for logging (by level)

Alternatively, we can comment-out the contribution in `plugin.xml` and resume w/ `M27`.

/cc @quangson91

**Comment by quangson91** [comment]
Default color can be found in this document: https://www.jetbrains.org/intellij/sdk/docs/reference_guide/color_scheme_management.html
(I'm working on this)

**Comment by quangson91** [comment]
I implement default color scheme for flutter color log.
Ref: https://github.com/flutter/flutter-intellij/pull/2394/commits/4642f0805912362c39b42c612c2dd4ff523d09e0

**Comment by quangson91** [comment]
I also found the way to get config
```
    Arrays.stream(ColorSettingsPages.getInstance().getRegisteredPages())
      .filter(page -> page instanceof FlutterLogColorPage)
      .findFirst().ifPresent(page -> {
      final List<AttributesDescriptor> attributeDescriptors = ColorSettingsUtil.getAllAttributeDescriptors(page);        
    });
```

`attributeDescriptors` will contain setting color for foreground/background and so on.

BUT I don't know why those variables are `null` :|

**Comment by quangson91** [comment]
> update log color by getting setting from FlutterLogColorPage

I did it in this PR: https://github.com/flutter/flutter-intellij/pull/2399

**Comment by quangson91** [comment]
@pq, @devoncarew as the pr #2399 already merged.
So I think we should close this issue.
