### ISSUE TITLE
Debug single app on multiple devices simultaneously

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#240]
The plugin should allow a developer to attach multiple devices or simulators and use all of them at the same time while working on a single app. They should be able to set breakpoints that are active in all sessions, individually single step the debugger for a single device, resume and exit the app on each device without affecting other devices.

One could imagine setting a breakpoint on a per-device level but I don't think the IJ UX supports that so, for now, breakpoints are universal. Although we should see what AS does in this case.

(The case of multiple apps is already supported since each app appears as its own IJ project window. If we find projects that contain multiple apps we will need to test them.)

**Comment by eseidelGoogle** [comment]
We used to have a feature in earlier versions of flutter run/flutter listen which would run a single app across all connected devices simultaneously.  As I recall, @devoncarew and company found the resulting flutter_tools code sometimes confusing and my understanding was the run-everywhere part wasn't used much other than for sexy demos.  Without further context, a run-a-single-app-on-multiple-devices feature wouldn't be very high on my asks list, but I may also be misunderstanding the bug.

**Comment by devoncarew** [comment]
> They should be able to set breakpoints that are active in all sessions, individually single step the debugger for a single device, resume and exit the app on each device without affecting other devices.

+1 to the above. Atom had a limit of only being able to debug one flutter app at a time, but this was an artificial limit of the arch. and not really intended. I think this feature is about being able to independently debug an app on multiple devices.

**Comment by stevemessick** [comment]
@eseidelGoogle I think IntelliJ has a UX in place for multiple debuggers on the same program. Expert IntelliJ users will want it. However, I added this to the only milestone that has no delivery date on it. :)

**Comment by devoncarew** [comment]
This works now - I can start an app up on one device, debug it, start an app up on another device, debug that, and switch back and forth between the two debug sessions.
