### ISSUE TITLE
Too many dart processes running (more than 15)

### ISSUE THREAD

**Issue by fmatosqg** [flutter/flutter-intellij#2427]
After a few cycles of edit code and hot reload the machine starts getting slower, and I notice up to 10 dart processes near the top of the list when ordering all processes by memory, all of those using about 250 MB (the number is pretty close for all of them). Other processes show further down.

## Steps to Reproduce

Normal development: edit code, hot reload. Rinse and repeat. 
Once a day I usually open and compile an android project, also I may open and run a second flutter project.

My setup involves manually changing the flutter folder every time I open to a folder that points to flutter master. This is not the default flutter folder in my PC, and I haven't verified if it's related to the problem so far. Occasionally i run `flutter clean`  on console with binaries coming from the same folder but for this experiment I'm keeping it down to a minimum.

## Version info

OS X

```
> flutter --version
Flutter 0.5.1-pre.18 • channel master • https://github.com/flutter/flutter.git
Framework • revision a2d1d27f79 (4 weeks ago) • 2018-05-29 18:04:13 -0700
Engine • revision 16f5cd8106
Tools • Dart 2.0.0-dev.59.0.flutter-ff815d05a5
```

Verified on Android studio 3.1.3, but I suspect it also happens on Canary and 3.1.2.
Currently verified on Android Studio 3.1.3 flutter plugin 25.0.1. 

After rolling back to flutter plugin 24.2.1 it seems to be much much better. Also I started noticing problems a week ago when I updated from 24.2.1 to 25.0.1. The only obvious difference I can notice is that the last version can almost always render the "flutter outline preview" while the former never can, I'd use that as a starting point for investigating.

At this moment everything is normal and I have 4 dart processes using 368, 290, 196 and 96 MB of memory as reported by OS X Activity Monitor.

**Comment by devoncarew** [comment]
> Flutter 0.5.1-pre.18 • channel master • https://github.com/flutter/flutter.git
> Framework • revision a2d1d27f79 (4 weeks ago) • 2018-05-29 18:04:13 -0700

Thanks for the report! It looks like you're on the master channel from about 4 weeks ago. Do you mind updating and see if the problem still occurs?

Also, it would be useful to know what script the dart processes are running (the analysis server, flutter_tools, something else) - something like `ps -A | grep dart` should give you that info. That will help us narrow down where the issue it.

**Comment by jacob314** [comment]
Closing as there isn't a repro and the issue is likely long stale. Please re-open if there are repro steps that use a recent flutter build.

**Comment by iampawan** [comment]
Facing same issue 

> 95407 ??         0:23.75 /Users/pawankumar/Desktop/flutter/flutter/bin/cache/dart-sdk/bin/dart /Users/pawankumar/Desktop/flutter/flutter/bin/cache/flutter_tools.snapshot daemon
95435 ??         4:34.58 /Users/pawankumar/Desktop/flutter/flutter/bin/cache/dart-sdk/bin/dart /Users/pawankumar/Desktop/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Android-Studio --client-version=AI-183.5429.30 --useAnalysisHighlight2
96484 ??         0:00.01 bash /Users/pawankumar/Desktop/flutter/flutter/bin/flutter --no-color run --machine --track-widget-creation --device-id=23349D6B-0B81-4C8E-B8C5-434F76C8A04C --start-paused lib/main.dart
96499 ??         0:18.76 /Users/pawankumar/Desktop/flutter/flutter/bin/cache/dart-sdk/bin/dart /Users/pawankumar/Desktop/flutter/flutter/bin/cache/flutter_tools.snapshot --no-color run --machine --track-widget-creation --device-id=23349D6B-0B81-4C8E-B8C5-434F76C8A04C --start-paused lib/main.dart
96755 ??         4:33.85 /Users/pawankumar/Library/Developer/CoreSimulator/Devices/23349D6B-0B81-4C8E-B8C5-434F76C8A04C/data/Containers/Bundle/Application/43AFB594-8E11-4D41-815F-8716C9200CA1/Runner.app/Runner --enable-dart-profiling --enable-checked-mode --verify-entry-points --start-paused --observatory-port=0
96758 ??         1:01.65 /Users/pawankumar/Desktop/flutter/flutter/bin/cache/dart-sdk/bin/dart /Users/pawankumar/Desktop/flutter/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/pawankumar/Desktop/flutter/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build/app.dill.track.dill --packages /Users/pawankumar/Desktop/dart/mobile/qart/.packages --track-widget-creation
 5750 ttys002    0:00.00 grep dart
