### ISSUE TITLE
Flutter log color settings only partially configurable.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2431]
It looks like only the foreground color actually get picked up by the renderers

![image](https://user-images.githubusercontent.com/67586/41931043-b67797be-7931-11e8-9331-d4ac5c253961.png)

/cc @quangson91

**Comment by quangson91** [comment]
@pq, Right.
Currently, I just setting foreground color.
We should update font style & other attributes too.

**Comment by quangson91** [comment]
@pq, I'm working on this issue.
I will create an PR soon.

**Comment by pq** [comment]
Fantastic.  Thanks @quangson91!

**Comment by pq** [comment]
Super.  Thank you!

**Comment by devoncarew** [comment]
I this addressed? Or, should we move it to the next milestone?

**Comment by quangson91** [comment]
@devoncarew, I think this already addressed.

**Comment by devoncarew** [comment]
Thanks! Closing -
