### ISSUE TITLE
release tracking the M26 release

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2432]
A meta issue to track the M26 release.

**Comment by devoncarew** [comment]
cherry-picks:
- [ ] changelog notes

**Comment by devoncarew** [comment]
In flutter on the master channel, we see frequent crashes in the debugger due to an expression eval issue. This is fixed in the sdk, but has not yet rolled into flutter/engine => flutter/flutter, due to rolls being blocked by the internal flutter roll.

**Comment by ksdboasit** [comment]
Found this issue: #2447

**Comment by pq** [comment]
We're shipped! 🚀
