### ISSUE TITLE
Empty project folder after creating new Flutter "Project" in Android Studio

### ISSUE THREAD

**Issue by Eng-MohamedGadala** [flutter/flutter-intellij#2443]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Nothing happens when I create a new Flutter "Project" with project name nflutterpro in an Android Studio only folder is created with name nflutterpro and contain 2 folders named (.idea,android).
dart plugin and flutter are installed.

 Creating new Flutter project works fine using flutter cmd console  (flutter create nflutterpro) works fine.

## Version info
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
    • Flutter version 0.5.1 at C:\flutter
    • Framework revision c7ea3ca377 (4 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at E:\androidsdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • ANDROID_HOME = E:\androidsdk
    • Java binary at: E:\Instolation App Work\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at E:\Instolation App Work\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 1 category.

**Comment by devoncarew** [comment]
Can you check and see if there are any exceptions in your log file? I think you can find it from the `Help` menu in Android Studio.

@stevemessick

**Comment by Eng-MohamedGadala** [comment]
thanks for your response I found the solution in StackOverflow. 
the problem in Zip file  I don't know what is it but this solves this problem.
[https://stackoverflow.com/questions/50776550/flutter-mysql-is-not-recognized-as-an-internal-or-external-command](url)
Unfortunately, the Zip provided on flutter.io gave me a problem. To avoid this error, I had to use the GitHub repository following the following procedure.

Go to C:\ Drive and create a folder called flutter.
Go to that folder and start git bash
Type git clone -b beta https://github.com/flutter/flutter.git and enter
After its complete, add the path C:\flutter\flutter\bin in environment variables
Finally, start CMD and type flutter doctor and the error is disappeared

**Comment by Eng-MohamedGadala** [comment]
fixed #2443

**Comment by nb312** [comment]
I also have this problem and use the project from git.

**Comment by Qing-cpu** [comment]
Do not install Flutter in a directory like C:\Program Files\ that requires elevated privileges.
