### ISSUE TITLE
Confirm project formatting settings

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2444]
Follow-up from https://github.com/flutter/flutter-intellij/pull/2439#discussion_r198508474.

@quangson91 and I differ on how auto-format treats:

```java
        for (String s : new ArrayList<String>()) {

        }
```

Could someone chime in with there results?

/cc @scheglov @devoncarew @stevemessick @jacob314 ...

**Comment by pq** [comment]
Related tangentially to #2232.

**Comment by devoncarew** [comment]
Hmm, formatting for me doesn't change the above for loop.

**Comment by pq** [comment]
OK, then I'm probably the outlier.  I wonder if we shouldn't be versioning these settings?  (Not exactly sure where even they are! )

**Comment by pq** [comment]
Hmm, ok, found it:

![image](https://user-images.githubusercontent.com/67586/41980716-03432dec-79dc-11e8-962f-979b828f8682.png)

No idea where these settings are persisted; or why mine diverged?

**Comment by stevemessick** [comment]
I'm using Android Studio developer settings. It adds the space before the colon if I delete it. I'm pretty sure I have always (since Eclipse days) put a space before and after the colon in for-each statements. Sorry, but I don't currently have the Flutter or Dart projects configured to easily check the formats they use. Also see:
https://google.github.io/styleguide/javaguide.html#s4.6-whitespace

**Comment by pq** [comment]
What's odd is that's my preference too and can't imagine ever intending otherwise!  Anyway, I'll close this for now; if someone figures out how to best share these settings, we can tack that on to #2232 or similar.

Thanks for verifying!

**Comment by stevemessick** [comment]
It might even depend on IntelliJ version. I'm using 2018.1 and cannot find "space before colon in foreach" anywhere in preferences.

**Comment by pq** [comment]
Aha!  That must be it.  I'm on EAP 2018.2 and I'm guessing it's a new setting that defaults to `false`.   Thanks for tracking that down!
