### ISSUE TITLE
Consider supporting filtering on category

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2445]
Follow-up from a [review conversation](https://github.com/flutter/flutter-intellij/pull/2441/files/19c5be2995c0bdeaf073757db4953a2513d9ccf8..42970d91e04f387b492a2b51786768084886f108#r198509909), where @devoncarew wrote:

>GC events are printed at a slightly more verbose setting than the default. While using the logging view, I found GC events noisy and not adding a ton of value.
>
>We should either filter them out by severity, or add the ability to show and hide categories (gc event, network events, ...).

I've been thinking something similar.

A few quick considerations:

1. you might want to see an arbitrary number of categories
2. not all categories are known in advance; new ones could appear at any time

Ideas welcome!

/cc @devoncarew @quangson91

**Comment by devoncarew** [comment]
Closing as this is related to the experimental logging view.
