### ISSUE TITLE
Breakpoints do not persist after hot reload

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#2446]
Version: Android Studio 3.1.3
Plugin: 26.0.1

1. Create a project.
2. Set a breakpoint.
3. Run to breakpoint.
5. Modify the code.
5. Hot reload.
6. Resume.
7. Run again.

Breakpoint is ignored.

I'm using the default project with breakpoint and code mods as per test script.

**Comment by jacob314** [comment]
Do you have details on whether this started with a specific version of flutter or with the M26 flutter intellij plugin? If it is with a specific version of the intellij plugin it is my issue.

**Comment by stevemessick** [comment]
I think things actually work better now :)

I reverted to Flutter 0.4.4 and plugin 25.0.1. The sequence of stop-at-breakpoint, modify-code, hot-reload, continue is totally broken. It takes about 20s for hot reload to complete, after which the app is unresponsive and the UI change made before hot reload is not visible.

@devoncarew @pq Have you noticed anything like this?

**Comment by jacob314** [comment]
the refactor of the debugger integration wasn't in 25.0.1. Have you made sure you have blown away any dill files in your build or ios directories? It is possible that some files left over from the 0.5.1 build are messing up the 0.4.4 build.

**Comment by stevemessick** [comment]
Right, I suspect no one has tested this pathway. FWIW I always start with a freshly-created Flutter project.

**Comment by jacob314** [comment]
This issue has been fixed.
