### ISSUE TITLE
Visually mark reload and restarts in the Log View.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2458]
Exploring custom rendering of restart and reload entries to make it easier to see them at a glance.

---

More blue sky: 

* we might also consider showing reload/restart landmarks in the scrollbar.  As done in the editor:

    ![image](https://user-images.githubusercontent.com/67586/42177378-6c4249fa-7de1-11e8-94ae-f71972a9f284.png)

* also related: potential actions to quickly navigate to previous/next restart/reload.

**Comment by zoechi** [comment]
Perhaps a dropdown that allows to select a specific run?
I find continuous logs from multiple runs cumbersome if not properly separated.
There doesn't seem to way with the new log view to get logs purged automatically on reload/rerun.

**Comment by pq** [comment]
> There doesn't seem to way with the new log view to get logs purged automatically on reload/rerun.

👍 I was thinking we'd want this on restart for sure; do you think we want to support configuration for both?

**Comment by zoechi** [comment]
Yes, restart, hot restart, hot reload, should purge the log with an option to not purge at all. 
Others might see this differently though.

I'm usually not interested in logs before any of these events and find it always cumbersome to find the start of the relevant log output.

**Comment by pq** [comment]
Fodder for discussion a PR is out that adds some simple delineation.

![image](https://user-images.githubusercontent.com/67586/45509770-4b63da00-b74d-11e8-831e-34bc83a1e9ae.png)

![image](https://user-images.githubusercontent.com/67586/45509764-49018000-b74d-11e8-8310-e774a85300d0.png)

(See: #2605.)

**Comment by pq** [comment]
Implemented w/ https://github.com/flutter/flutter-intellij/pull/2605/commits/1ceca4c8b3b7210b5c4cbcd27f437bf4244e8c06
