### ISSUE TITLE
Disable unmodifiable attributes in the flutter log color settings page.

### ISSUE THREAD

**Issue by quangson91** [flutter/flutter-intellij#2460]
> Regarding the attributes that are not working, is there any way we can remove them from the UI as options? (I'm guessing this would be possibly trickier than getting them to work but just have to ask.)

=> We may disable those attributes setting if it doesn't work.

Ref: https://github.com/flutter/flutter-intellij/pull/2451#issuecomment-401822905

**Comment by pq** [comment]
Thanks for the tracking issue @quangson91 !

**Comment by quangson91** [comment]
@pq, I already double check this problem.
But it looks hard to decide.
Reason:
There is only one attribute doesn't work well.
That attribute is `Effect`.

There are some `Effect` like `Dotted line `, `Underwaved` some of them work, and some doesn't work well. (See: https://github.com/flutter/flutter-intellij/pull/2451)

So I don't know what should we do next :|,

**Comment by pq** [comment]
Thanks for following up.  Am I right that some effects DO work as expected and it's just that some don't work as well?

**Comment by quangson91** [comment]
Yes, you right.
Effect type is work.
But Effect color doesn't work.
For example:
Effect `Bold underscored` -> bold + underscored WORKED. Color effect doesn't work.

**Comment by quangson91** [comment]
Also, there is setting `strip mark color`. That setting seems related to this issue: https://github.com/flutter/flutter-intellij/issues/2458

**Comment by pq** [comment]
Great.  If it's common that folks try a color effect (though I expect it won't be) we can explore further or add a popup warning them that the setting won't have any effect.

Besides that, I think we can close this as done?

**Comment by quangson91** [comment]
Yeap, I think so.
