### ISSUE TITLE
Consider removing hidden columns from text output when copy/pasting log

### ISSUE THREAD

**Issue by quangson91** [flutter/flutter-intellij#2461]
Currently, when copy log we also get information about hiding columns.
We should remove those data/information in copy data.

**Comment by devoncarew** [comment]
We may also just want to copy in a standardize format, irrespective of the column visibility state. Something like:

```
[flutter.fooCategory] My message here.
```

**Comment by pq** [comment]
Thinking on this a bit more, I'm leaning towards preserving all log contents (irrespective of hidden content).  In practice, it seems easy enough to cut out what you don't want.  (Harder to add it in! 😄)

I don't feel super strongly though...

**Comment by quangson91** [comment]
@pq, @devoncarew So we will keep full log content when user copy?
If that, we will close this issue.

**Comment by pq** [comment]
I think that's a good plan for now.  We can always revisit.

Thanks!
