### ISSUE TITLE
Validate android package names with multiple dots

### ISSUE THREAD

**Issue by g123k** [flutter/flutter-intellij#2468]
Hello,

Thanks for your amazing work, but I think I have found a tiny bug.

With the new project -> Flutter -> plugin dialog, you have to choose an organization.
If by mistake, there is a dot at the end of it, such as `com.example.`, it will generate a broken Android project : https://imgur.com/a/BzoAVbh

In my example, the Android package name will then be `com.example..test_plugin`, which is incorrect and won't compile.

A warning or an error message would be helpful here to prevent the generation of an incorrect Android project.

**Comment by pq** [comment]
Great suggestion @g123k.  Thanks for the report!

**Comment by Ruban2205** [comment]
Hello there, I've created a flutter project with the package name in.rubangino.newproject , But It throws an error called "Android resource linking failed" while compiling. But when I try with a new package name in new project like com.rubangino.newproject1 , It compiles and run without errors. As I am learning flutter, I can't able to rectify this issue. Can You please suggest me a solution to this error?
