### ISSUE TITLE
Empty Android folder when creating a new plugin

### ISSUE THREAD

**Issue by g123k** [flutter/flutter-intellij#2471]
Hello,

I have found a bug with the Flutter plugin when a new plugin is created.
The content of the src/main folder of the Android seems empty with the Project view.
The files are on the filesystem, but invisible in IntelliJ : https://imgur.com/a/NZrj2jg

## Steps to reproduce

1. File -> New Project
2. Select Flutter
3. Choose a "Plugin" project type
4. Click on Finish

**Comment by pq** [comment]
What version of the plugin and Android Studio are you using?  Could you include the output from `flutter doctor`?

Thanks!

/cc @stevemessick

**Comment by g123k** [comment]
Hi,

I am using both the dev and beta channels of Flutter and I can reproduce the problem.
That's also the case with IntelliJ : the stable version (2018.1.5) and the beta.
The version of the Flutter plugin is 26.0.2.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[!] VS Code (version 1.23.1)
[!] Connected devices
    ! No devices available
```

If you need a screencast of the problem, don't hesitate to ask.

**Comment by devoncarew** [comment]
@stevemessick, I believe this is what you were seeing in AS 3.2?

**Comment by stevemessick** [comment]
@devoncarew When I looked into it I thought the details were so different it was not related to that. However, I am hopeful that #2504 will fix this problem.

**Comment by devoncarew** [comment]
Given that, should we consider that PR for the release?

**Comment by pq** [comment]
@stevemessick: now that #2504 has landed can we treat this as fixed?

**Comment by stevemessick** [comment]
This problem isn't fixed. I'm just hoping whatever broke in AS is fixed by the stable release. It IS fixed in canary.

**Comment by stevemessick** [comment]
I believe this was fixed a/o RC3, and stayed fixed in 3.2 stable. Please reopen if you find otherwise.

**Comment by TheKashe** [comment]
I don't see any folders under /android/src.main when creating a new flutter plugin. Happened in AS 3.4, stays the same under 3.5

**Comment by hieuseesaa** [comment]
> I don't see any folders under /android/src.main when creating a new flutter plugin. Happened in AS 3.4, stays the same under 3.5.
> 
> Creating plugin with flutter create and opening the project in AS results in the same -> no java files visible.

Same problem
