### ISSUE TITLE
Code changes don't take effect when not explicitly saved. 

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2472]
## Steps to Reproduce

When I modify the code and then press a button (or keyboard shortcut) to 

- hot reload
- hot restart
- re-run tests

the code changes are not reflected in the running app (or I get a build error because of that if the previous code status was invalid).

This does not happen (or at least much less often) when I explicitly save the changes before
invoking hot reload, hot restart, re-run tests, ...  

When I forgot to save before run, I have to run `flutter clean` to actually get the latest changes again.

## Version info

[✓] Flutter (Channel master, v0.5.7-pre.65, on Mac OS X 10.13.5 17F77, locale en-AT)
    • Flutter version 0.5.7-pre.65 at /Users/zoechi/flutter/flutter
    • Framework revision 5cbbd2831c (5 hours ago), 2018-07-09 11:56:39 +0200
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by jacob314** [comment]
Are you positive the issue occurs more when you forget to manually save first?

The first thing we do when hot reloading or hot restarting is save all files in the project so it is quite surprising if saving all files locally yourself first triggers different behavior.
Potentially, performing multiple restarts is masking
flutter/flutter#19132
saving will give you one restart and then restarting again will give you a second.

**Comment by jacob314** [comment]
I double checked the core IntelliJ code and it really seems like there can't be a race condition at least not in IntelliJ. It is possible there is a race condition in Flutter Tools.
Are you using your Android Studio or IntelliJ client?
Is it possible to see if you can reproduce the bug when on the beta channel of flutter instead of the master branch?

**Comment by jacob314** [comment]
Let me know what you see using beta.

**Comment by jacob314** [comment]
Are you by any chance using the live preview mode of the Flutter Outline view? There is a known bug with concurrent flutter runs that could explain the behavior you are seeing.

**Comment by zoechi** [comment]
@jacob314 I have enabled it recently but wasn't able to make it work and ignored it since then.
I'll disable and observe.

**Comment by zoechi** [comment]
@jacob314 It's not related to outline view. I wasn't yet able to find time to test with beta.

**Comment by zoechi** [comment]
This seems to work now with

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.109, on Mac OS X 10.13.6 17G65, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
