### ISSUE TITLE
Don't scroll to bottom when scrolled away from bottom manually

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2487]
The logging output should stay where it is when manually scrolled away from bottom.
Currently a log output scrolls to the bottom every time a new log output happens.

This makes it impossible to check previous log output while the app is running.

Scrolling to bottom (manually or using a scroll-to-end button) should restore the current behavior.

**Comment by quangson91** [comment]
Ah, I understood @zoechi  problem.
It seems we have to detect if the log scroll-up => we will disable `auto scroll to end` action.

**Comment by quangson91** [comment]
I created a new PR to fix this problem: https://github.com/flutter/flutter-intellij/pull/2488

**Comment by zoechi** [comment]
@quangson91 
and you should detect when scrolled back to the end to re-enable `auto scroll to end`.
Does your fix include that?

**Comment by quangson91** [comment]
My fix don't include that.
But I think for that action -> user just clicks action `auto-scroll to end`.

**Comment by quangson91** [comment]
>  you should detect when scrolled back to the end to re-enable auto scroll to end

=> To fix that, we just need check new scroll value = 100 => we re-enable `auto scroll to end`.

Ah, I will fix that. I tested on Intellij, after user scroll to end -> `auto scroll to end` must re-enable

**Comment by quangson91** [comment]
@zoechi I updated this PR: https://github.com/flutter/flutter-intellij/pull/2488

now when user scroll update -> disable auto scroll to end.
when user scroll to the end (bottom) -> re-enable `auto scroll to end`.

**Comment by zoechi** [comment]
@quangson91 that sounds great. Thanks a lot!

**Comment by pq** [comment]
Fixed w/ #2488 🎉
