### ISSUE TITLE
Logging support for dart:developer.inspect(..)

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2491]
_Tracking issue for [`dart:developer.inspect(..)`](https://api.dartlang.org/stable/1.24.3/dart-developer/inspect.html) logger integration._

@jacob314 and I did some quick investigations and while I don't have anything ready to land there's enough sketched out to start a conversation.

The thinking is to make calls to `inspect(..)` work very much like `console.log(obj)` in the Chrome dev console.   A quick first cut is promising.

![image](https://user-images.githubusercontent.com/67586/42846206-20eb43ec-89cd-11e8-9c76-220ef3017a90.png)

Observations:

* we need to track the state of entries whose instances are no longer valid (after a restart)
* we should consider some way to identify isolates corresponding to log entries
* timing is tricky (entries arrive before VM debug callbacks meaning we can't, for example, do an `eval` for the String value of inspected objects right away)
* adding an **Inspect...** menu item was expedient but inlined objects (like in dev console) would be _much nicer_

**Comment by jacob314** [comment]
Some notes: the intent of this bug still applies but the implementation should be a bit different.
developer:inspect should only change inspector selection.
debugPrint will have a kernel transform apply to it so that in debug builds we get object references for everything.

**Comment by devoncarew** [comment]
Closing as this is related to the experimental logging view.
