### ISSUE TITLE
Widget tree

### ISSUE THREAD

**Issue by kabir19** [flutter/flutter-intellij#2501]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

I am leaning "Build your own Widget" in 1st Lesson of Flutter framework from Udacity.

I am not able to view Widget tree and Render tree in the tabs in the Flutter Inspector window.
I have checked and installed the necessary flutter and dart plugins.
Please guide me to view widget tree in Flutter Inspector window.

## Version info
C:\Users\admin\AndroidStudioProjects>flutter doctor -v
[ΓêÜ] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 6.1.7601], lo
cale en-US)
    ΓÇó Flutter version 0.5.1 at C:\src\flutter
    ΓÇó Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    ΓÇó Engine revision 1ed25ca7b7
    ΓÇó Dart version 2.0.0-dev.58.0.flutter-f981f09760

Unhandled exception:
SocketException: Write failed (OS Error: The pipe is being closed.
, errno = 232), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)

#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_pa
tch.dart:113)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isol
ate_patch.dart:166)
![flutter inspector](https://user-images.githubusercontent.com/31826553/43206919-6d370812-9044-11e8-9339-7a066dd3c854.JPG)

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
@jacob314 @pq Is the version of Flutter used here compatible with the widget inspector?

**Comment by kabir19** [comment]
Hi Steve,

Well I am a complete novice when it comes to Flutter and widgets. Besides I
have mentioned flutter version and Android studio version i am using in the
version details.

Also enlighten me on how can I check whether my flutter version is
compatible with widget inspector.

Regards,
Kashyap Wadekar

**Comment by pq** [comment]
Sorry for the slow response!

That's a pretty old build.

@jacob314: could you advise?

**Comment by jacob314** [comment]
Let me know if you can reproduce with the latest beta and plugin and I'll investigate. Thanks!

**Comment by stevemessick** [comment]
@kabir19 I don't see any indication of which version of Android Studio or the Flutter plugin you are using. The `flutter doctor -v` output appears to be incomplete. To expand on the suggestion @jacob314 made, please install the latest version of Flutter, the latest stable version of Android Studio, and then add both the Dart and Flutter plugins to AS. That will solve any versioning problems. If you still see this issue, respond here.
