### ISSUE TITLE
Flutter stanim live template is missing on two computers - Intellij and Android Studio

### ISSUE THREAD

**Issue by Sun3** [flutter/flutter-intellij#2502]
## Steps to Reproduce
1. Create a new dart file in a Flutter Project
2. Type stanim and the live template is not there.

I have tried this on two different Macs with same result.

## Version info

flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.1 at /Users/marco/Development/flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/marco/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • 705E75D9-7E01-4AB5-948A-226B8AFD9F8A • ios         • iOS 11.4 (simulator)

! Doctor found issues in 1 category.

Thank you.

**Comment by stevemessick** [comment]
Sorry about that. `stanim` was inadvertently removed in M26. It will be restored in M27, which should be released "soonish".

**Comment by Sun3** [comment]
Great... thanks.
