### ISSUE TITLE
Analyzer Error

### ISSUE THREAD

**Issue by littlemarc2011** [flutter/flutter-intellij#2505]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.3684.101`
- `1.24.3`
- `IU-182.3684.101, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1920x1080, 1600x900`

# Exception

Please append the contents of:
file://C:\Users\marc\AppData\Local\Temp\report2.txt

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: C:\Users\marc\IdeaProjects\hairsaloon\test\widget_test.dart
Invalid argument(s): Cannot serialize an instance of GenericFunctionTypeImpl
#0      AbstractConstExprSerializer.serializeTypeName (package:analyzer/src/summary/summarize_const_expr.dart:211)
#1      AbstractConstExprSerializer._serializeListLiteral (package:analyzer/src/summary/summarize_const_expr.dart:550)
#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:356)
#3      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#4      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:557)
#5      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:755)
#6      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:828)
#7      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:1029)
#8      _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1210)
#9      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#10     _SummarizeAstVisitor.serializeClass (package:analyzer/src
```

**Comment by littlemarc2011** [comment]
Here is a screenshot of the error that it seems to come from:
![error](https://user-images.githubusercontent.com/13179783/43349329-96c7ec9c-91c4-11e8-85ee-0f195cc6c1f3.png)

**Comment by stevemessick** [comment]
Thanks for the report!

@bwilkerson Could you say whether this is a problem in Dart 2 land?

**Comment by devoncarew** [comment]
Hi @littlemarc2011, thanks for the report. I see that you're using a `1.24` version of Dart with Flutter. That's a pretty old version of Dart from Flutter's perspective. You should probably:

- make sure IntelliJ and the Flutter IntelliJ plugin are up-to-date
- get the latest version of Flutter (`flutter upgrade` from the command line, or Tools > Flutter from the IDE
- make sure that the Flutter IntelliJ plugin is using the Flutter SDK (not the regular Dart SDK) - https://github.com/flutter/flutter-intellij#quick-start
