### ISSUE TITLE
meta issue for the M27 release

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2510]
This is the tracking issue for the M27 release - we can use it to gather feedback on the release candidate.

**Comment by jacob314** [comment]
Landed in master.
Enable --track-widget-creation
https://github.com/flutter/flutter-intellij/commit/b43d9f7fd9d289b65663a2ea2c5ed0efd7120dc5

**Comment by jacob314** [comment]
Landed in master:
Fix exception thrown when restarting an app.
https://github.com/flutter/flutter-intellij/commit/d230d80e8c11ecb044052508834b24ccc9bb5035

**Comment by pq** [comment]
Another to cherry-pick:

https://github.com/flutter/flutter-intellij/commit/6c36c3230fb61febc4a82cad7d0f05fe54a82c42

FYI @stevemessick, @devoncarew

**Comment by stevemessick** [comment]
I have added all current cherry-picks to release_27 and pushed it to github.

**Comment by devoncarew** [comment]
One more to cherry-pick:
- d9be215146532c6ccb57324b08343378be26fd7a

**Comment by stevemessick** [comment]
The release_27 branch has been updated with all recent cherry-picks. To be clear, everything merged to master through d9be215146532c6ccb57324b08343378be26fd7a is included in release_27 at this point.

**Comment by devoncarew** [comment]
It's released!
