### ISSUE TITLE
'flutter create' plugin template issue

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#2519]
The template for plugins (used by `flutter create`) does not include any indication that example/lib is a source folder. It should. The .iml file needs to be updated in the Flutter repos.

**Comment by pq** [comment]
Tangentially related, we don't treat `example/lib` as a source root when resolving links in the console either #2518.

**Comment by pq** [comment]
Looking closer, this is not tangential at all.  The way we resolve links is based on content roots so #2518 would get fixed by this.  That said, adding `example` as a content root doesn't "just work" since it's nested below the base content root which is disallowed.
