### ISSUE TITLE
Support for DartDoc macros

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#2524]
When jumping to the definition of a function or property within the flutter framework I often see something like the following:

```dart
  /// {@macro flutter.widgets.widgetsApp.color}
  final Color color;

  /// {@macro flutter.widgets.widgetsApp.locale}
  final Locale locale;
```

It would be great if IntelliJ would offer some sort of support for these DartDoc macros. I'd love it if IntelliJ would just show inline what the macro is referencing. Or at least provide a link to the referenced location.

**Comment by scheglov** [comment]
When you say "show inline", do you mean Quick Documentation feature of IntelliJ?
![image](https://user-images.githubusercontent.com/384794/43727885-1c8b8722-9958-11e8-9994-357cb05b14d4.png)

This should be easy to do, although very Flutter specific (not a bad thing, we love Flutter :-)). We could index all templates in FileState in unlinked summary and extend AnalysisDriver to search templates by id.

**Comment by goderbauer** [comment]
@scheglov I did not have a specific UI in mind, but that would work. Although it might be hard to discover?

**Comment by xster** [comment]
Or just go-to-definition clicking a `@macro` going to the `@template` would be nice too.

**Comment by dnfield** [comment]
How about if we just scanned the Flutter repo (like we do for Snippets) and generated a (JSON?) file with key/value pairs for template name and template content?  Or just create a directory with a bunch of files named after their macros.

IDEs could then just access that file/files and render the content that way without re-inventing an analysis server for docs.

**Comment by jcollins-g** [comment]
Dartdoc is already loading all the macro definitions internally and could write that out as part of normal operation.  It's substantially simpler than the already existing snippet support as you don't have to keep track of where things are.  Maybe add a bug to dartdoc for that?

**Comment by dnfield** [comment]
Yeah, after discussing further it seems like this wouldn't be a great solution.

Another thought I have is doing something like 

```
{@macro flutter.macro.name.whatever ref=[Class.member]}
```

Dartdoc would ignore the ref, and IDEs could use the ref to just put `See also: [Class.member]`

**Comment by devoncarew** [comment]
This functionality has been rolled into the analysis server - dartdoc hovers in IDEs now show the in-lined content from macros.

**Comment by hacker1024** [comment]
It would be nice to be able to ctrl+click them as well in the source code.

**Comment by christopherfujino** [comment]
> It would be nice to be able to ctrl+click them as well in the source code.

that would be a IDE plugin feature request.
