### ISSUE TITLE
idea "updating indices"

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter-intellij#2530]
I to do new Flutter Project on Idea, 
idea repeated hints "updating indices",

my other Java Project is not this Situation.

my idea is latest version.

my development environment is Mac OS 10.13.1

help me, please!

**Comment by pq** [comment]
Thanks for the report!  Are you on the latest Flutter plugin (27.0)?  If so and the problem persists, try invalidating your IDEA caches and restarting.

![image](https://user-images.githubusercontent.com/67586/43723110-b7d54f68-994b-11e8-854e-30d954ece812.png)

(Last option in the restart dialog.)

Let us know if that works!
