### ISSUE TITLE
variable is showing "Collecting data..."

### ISSUE THREAD

**Issue by jiangzhixiao** [flutter/flutter-intellij#2532]
## Steps to Reproduce

i'm debuging ,and some value is not showing 
these four values : iterator,specifiedType,result,serializer shows "Collecting data..."
![image](https://user-images.githubusercontent.com/7273487/43696159-5026b9e6-996f-11e8-86f6-f6dc7f9e61da.png)

## Version info

[√] Flutter (Channel dev, v0.5.6, on Microsoft Windows [Version 10.0.17134.165], locale zh-CN)
    • Flutter version 0.5.6 at D:\sdk\flutter\v0.5.6-dev
    • Framework revision 472bbccf75 (6 weeks ago), 2018-06-26 17:01:46 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\sdk\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\sdk\Android
    • Java binary at: D:\dev-tools\android-studio-3.2-pre\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b05)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at D:\dev-tools\android-studio-3.1
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Android Studio (version 3.0)
    • Android Studio at D:\dev-tools\android-studio3-preview
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.2)
    • Android Studio at D:\dev-tools\android-studio-3.2-pre
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b05)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at D:\dev-tools\jetbrains\IntelliJ IDEA 2017.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\dev-tools\jetbrains\IntelliJ IDEA 2018.1.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 3 categories.

**Comment by stevemessick** [comment]
This is fixed in recent versions of the flutter engine.

**Comment by jiangzhixiao** [comment]
@stevemessick thanks  stevemessick
