### ISSUE TITLE
Verify reload and restart analytics data

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2543]
We have three questions:
* When the user performs a hot reload or a restart in IntelliJ, will the event end up in Flutter Tool's Google Analytics account?
* How about VS Code?
* If a user uses both the command line tool and IntelliJ, will the user has two separate client ids on her machine?

**Comment by InMatrix** [comment]
@DanTup, do you have any insights into how the VS Code plugin send reload and restart events to Google Analytics? Does it go through Flutter Tool?

**Comment by devoncarew** [comment]
> When the user performs a hot reload or a restart in IntelliJ, will the event end up in Flutter Tool's Google Analytics account?

Yes - I confirmed in the source code - flutter_tools does send analytics events, whether the reload/restart is triggered via an IDE or from the CLI.

> If a user uses both the command line tool and IntelliJ, will the user has two separate client ids on her machine?

Yes, they'll have separate IDs from the Flutter IntelliJ's analytics (store in IntelliJ metadata), and from the flutter_tools analytics (stored in `~/.flutter`).

**Comment by InMatrix** [comment]
> Yes - I confirmed in the source code - flutter_tools does send analytics events, whether the reload/restart is triggered via an IDE or from the CLI.

> Yes, they'll have separate IDs from the Flutter IntelliJ's analytics (store in IntelliJ metadata), and from the flutter_tools analytics (stored in ~/.flutter).

Just to verify my understanding, does the above mean if I perform a hot reload in IntelliJ, this event will generate a record in the Flutter Plugin for JetBrain's analytics with one ClientID _and_ another record in Flutter Tool's analytics with a _different_ Client ID?

**Comment by devoncarew** [comment]
Yes to the above :)

The same event will generate two different records, into separate analytics properties, w/ unrelated client IDs.

**Comment by devoncarew** [comment]
Yes, VS Code reloads should end up in the flutter_tools analytics stream as well.

> My takeaway is that we only need to look at reload and restart events in Flutter Tool's analytics to calculate reload fraction.

Sounds right (and, I think we can close this issue now).
