### ISSUE TITLE
Automatically rename the State object when its StatefulWidget object is renamed

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2545]
## Steps to Reproduce

* Create a StatefulWidget using the IntelliJ template. 
* Rename the StatefulWidget using the refactoring feature 
* Its State object is not renamed.

## Version info

[✓] Flutter (Channel master, v0.5.9-pre.33, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.9-pre.33 at /Users/taodong/Code/flutter_repos/flutter
    • Framework revision 7762e45115 (2 days ago), 2018-08-14 10:24:17 -0700
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/taodong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 181.4203.498

[!] VS Code (version 1.25.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Nexus 5   • 07e84ccb010aa11a                     • android-arm • Android 6.0.1 (API 23)
    • iPhone 6s • 0A3B39BC-A044-4A35-87C4-07825D48E220 • ios         • iOS 11.4 (simulator)

**Comment by devoncarew** [comment]
cc @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/76080
