### ISSUE TITLE
No WISIWIG Editor for Flutter

### ISSUE THREAD

**Issue by ckakunje** [flutter/flutter-intellij#2547]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

The flutter is very promising , however the GUI coding has to be done manually is outdated concept. Would like to see a nice drag and drop feature with a property editor support soon..

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by zoechi** [comment]
Dup of #2347

**Comment by devoncarew** [comment]
@zoechi, thanks for tracking down the dup.

@ckakunje, the Flutter team currently doesn't offer a GUI editor. We're focusing on making the experience of building your UI in code as good as possible. There is at least one third-party GUI builder available that I'm aware of.
