### ISSUE TITLE
document how to install the plugin

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#255]
For early dogfooding purposes, from our alpha site.

**Comment by pq** [comment]
As per https://github.com/flutter/flutter-intellij/issues/233, have we decided that this will live on flutter.io?

**Comment by devoncarew** [comment]
That would be great; for early dogfood perhaps also have some instructions in the readme or wiki?

**Comment by pq** [comment]
> for early dogfood perhaps also have some instructions in the readme or wiki?

👍 

To start, let's do things here.  When we feel good about them we can upstream to flutter.io.

Is this a good root?

https://github.com/flutter/flutter-intellij/tree/master/docs

next to `alpha`?

Maybe a new directory called `user`?

```
docs/
  alpha/
    updatePlugins.xml
  user/
    README.md
    getting_started.md
    images/
      ...
```

**Comment by pq** [comment]
As per #261, I'm actually feeling inclined to just put this in the top-level `README`.

Thoughts?

**Comment by devoncarew** [comment]
The readme.md sgtm.

Currently, items in the `docs/` folder are served out over [flutter.github.io/flutter-intellij](https://flutter.github.io/flutter-intellij/readme.md) (and any markdown files are run through jekyll).

**Comment by pq** [comment]
> Currently, items in the docs/ folder are served out over flutter.github.io/flutter-intellij (and any markdown files are run through jekyll).

I just noticed that.  Neat!

I'll put together some plugin install docs for the `readme`.

👍
