### ISSUE TITLE
Respect ANSI color codes in log entries.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2552]
If log entries include ANSI color escapes, we should respect them.

Corresponding issue in the flutter repo: https://github.com/flutter/flutter/issues/20663.

(An open question is how this can/should interact with category colors.)

/cc @quangson91

**Comment by jaumard** [comment]
Having Colorize package working with this plugin might be interesting for people/teams that are using both IDE and command line to run the app
