### ISSUE TITLE
Error:java: invalid source release: 10

### ISSUE THREAD

**Issue by jdipina** [flutter/flutter-intellij#2555]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment]
@jdipina, can you describe the conditions under which you saw this issue? And, can you paste the output of running `flutter doctor` from the command line? Thanks!

**Comment by piranchu** [comment]
I have the same issue.
I have cloned the following project: > git clone https://github.com/spring-guides/gs-crud-with-vaadin.git
Imported the project into idea, and then tryied to build the project. 
Thanks.

**Comment by Naw-alhmw** [comment]
I have the same issue; however, I've just downgraded my Java SDK from 11 to 8u201 and this is my IntelliJ software version:

> IntelliJ IDEA 2018.3.3 (Community Edition)
> Build #IC-183.5153.38, built on January 9, 2019
> JRE: 1.8.0_152-release-1343-b26 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

**Comment by Naw-alhmw** [comment]
My AndroidManifest.xml was wrongly located in the File > Project Structure by the IDE, so I had manually edited it to its actual correct path. Furthermore, this titled error had emerged as a result.

**Comment by anupverma20** [comment]
FIX:

1. Go to File > Project Structure 
2. Select Project on the left
3. Select appropriate "Project language level"
