### ISSUE TITLE
'convert to async function body' doesn't grok abstract accessor functions properly.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#2558]
If you have the following class:

```dart
abstract class Thingy {
  String get accessor;
}
```

And you select the 'convert to async function body' action on the "accessor" member, the result is:

```dart
abstract class Thingy {
  Future<String> get accessorasync ;
}
```
(Note the missing space between `accessor` and `async`, and the extra space after the async)

In the case of an abstract function, it should just change the return type, and not add `async`.

**Comment by devoncarew** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/71560
