### ISSUE TITLE
Android Studio, Flutter not showing typos warning in String literals. However it shows typos for fields and methods.

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2573]
@dark-chocolate commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/21118)

Demo image. 
![image](https://user-images.githubusercontent.com/40364434/44732518-1af02f00-ab03-11e8-93f2-132d5cc88d62.png)

Settings image
![image](https://user-images.githubusercontent.com/40364434/44732411-d795c080-ab02-11e8-99c1-c8b1db33b882.png)

---

@zoechi commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/21118#issuecomment-416644524)

I think that should be reported in https://youtrack.jetbrains.com/
(same in my IntelliJ). It's an AS/IntelliJ feature, not a Dart or Flutter plugin feature.

---

@dark-chocolate commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/21118#issuecomment-416683323)

Do you know how to solve it? I although added it to Google Tracker issues. Last time I reported something, they took around 45 days to get back to me. Don't know how much time will they take now?

---

@zoechi commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/21118#issuecomment-416705459)

Reporting in a repo that is not related to the software that is rsponsible for the issue won't improve response time ;-)

---

@dark-chocolate commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/21118#issuecomment-416706333)

How to delete the issue then? I can't see any option of deleting it here on Github. 

---

@zoechi commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/21118#issuecomment-416706669)

Closing should do.

---

@dark-chocolate commented on [Thu Aug 30 2018](https://github.com/flutter/flutter/issues/21118#issuecomment-417211739)

I got the reply from the Android Studio team. This is what they said, 

![image](https://user-images.githubusercontent.com/40364434/44835125-ca86e780-ac50-11e8-9453-8cadda80e10f.png)

---

@zoechi commented on [Thu Aug 30 2018](https://github.com/flutter/flutter/issues/21118#issuecomment-417255937)

Could you please post the link to the youtrack issue?

**Comment by stevemessick** [comment]
If this is going to be addressed it will probably be by the Dart Analyzer, which does all the static error analysis for Dart and Flutter code. Perhaps @bwilkerson could say whether this issue ought to be moved to the analyzer project?

**Comment by devoncarew** [comment]
It sounds like this might be an issue in the Dart plugin (and would be best to track in youtrack)?

**Comment by zoechi** [comment]
I suggested youtrack already and they sent him back :-/

**Comment by zoechi** [comment]
I see. can you post a link? Youtrack would be https://youtrack.jetbrains.com/ (as posted in my first comment above)

**Comment by dark-chocolate** [comment]
I am sorry due to some issues (internally) I can't share Google Tracker link, however I just posted a new issue to youtrack on your say and here is the link for that. 
https://youtrack.jetbrains.com/issue/IDEA-198218

**Comment by stevemessick** [comment]
This is tracked as a Dart plugin issue, 198218

**Comment by dark-chocolate** [comment]
I can't see any link of Dart plugin issue 198218.

**Comment by zoechi** [comment]
@dark-chocolate That's the link you posted in your previous comment.

**Comment by dark-chocolate** [comment]
@zoechi Got it! Thanks, but that issue hasn't been solved on youtrack. Does it mean if it will be solved it will only be solved in youtrack and github can't do anything in my issue. Only youtrack is the last resort?

**Comment by zoechi** [comment]
@dark-chocolate I assume that's the plan, otherwise it would be closed as "won't-fix".

 > tracked as a Dart plugin issue

There is no point in tracking one issue in multiple places and Dart plugin issues are tracked there.
