### ISSUE TITLE
'Import Module' project type shows in the IntelliJ project wizard w/o a description

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2575]
The new `Import Module` project type shows as an option in the IntelliJ project wizard. After selecting it and creating the project, the project type can't run (flutter gives an error about missing iOS resources).

This may be expected given the module is fragment of a project. I think the main actionable item from the bug report is that we have 4 project types available in the project type pulldown, but only have descriptive text for 3 of them; we should add a description about the Import Module type.

cc @stevemessick

**Comment by stevemessick** [comment]
This was fixed in https://github.com/flutter/flutter-intellij/pull/2568

"Import Module" only makes sense in an Android app, and should never show in a Flutter project.
