### ISSUE TITLE
filter for the new logging view doesn't apply on first open

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2576]
When using the new logging view, I have the filter set to 'config', but am seeing garbage collection events (in the 'finer' category). When I change the filter, it does properly filter in and out the finer events, so I think this is an issue w/ the view when it's first opened.

@pq

**Comment by quangson91** [comment]
@devoncarew I fixed this issue in this PR: https://github.com/flutter/flutter-intellij/pull/2584

**Comment by devoncarew** [comment]
Awesome, thanks!
