### ISSUE TITLE
Collapse doc comments does not work for .dart files

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter-intellij#2577]
Not sure if this is a dart plugin bug or a flutter plugin bug.

## Steps to Reproduce

1. Open a file with doc comments, such as tab_controller.dart
2. Right click the text area, and select: Folding > Collapse doc comments

expected:
doc comments collapse

actual:
doc comments do not collapse

notes:
The doc comments are recognized as collapsable because the + and - icon appears in the gutter, and pressing those do work, it just seems that the collapse (all) doc comments is broken.

## Version info

[✓] Flutter (Channel raw-material-slider, v0.6.1-pre.34, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.6.1-pre.34 at /Users/antrob/git/flutter
    • Framework revision 87ac96b664 (2 days ago), 2018-08-29 16:20:21 -0400
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/antrob/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4203.498

[✓] Connected devices (2 available)

**Comment by jwren** [comment]
First verify that there aren't any parse errors in the file using the Dart Analysis view.

After than, open an issue in JetBrain's YouTrack with "Dart" as the "Subsystem", assign to me (Jaime Wren) or Alexander Doroshko.   Also include the syntax of the comment.

**Comment by jwren** [comment]
https://youtrack.jetbrains.com/issues?q=%23dart%20%23Unresolved
