### ISSUE TITLE
Pubspec.yaml assets in AndroidStudio should suggest auto-completions

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2581]
@d-silveira commented on [Tue Aug 14 2018](https://github.com/flutter/flutter/issues/20570)

I expected the AndroidStudio flutter plugin to suggest auto-completions when adding an asset, from the asset files present in the flutter project. 
No matter what I expected, this is a really useful feature, to keep us from having to memorize the exact asset path/name, every time we add one.

---

@zoechi commented on [Wed Aug 22 2018](https://github.com/flutter/flutter/issues/20570#issuecomment-415103350)

Is this not covered by #20571 already?

---

@d-silveira commented on [Mon Aug 27 2018](https://github.com/flutter/flutter/issues/20570#issuecomment-416254695)

@zoechi this one is the other half of the coin, the other one is, while in code, suggestions from what's in the pubspec.yaml, in this issue I request that while filing the pubspec.yaml, suggestions appear from the files available in the project folders

---

@zoechi commented on [Mon Aug 27 2018](https://github.com/flutter/flutter/issues/20570#issuecomment-416272541)

You are aware that you can use wildcards (glob) and don't need to list every asset individually anymore?

---

@d-silveira commented on [Mon Aug 27 2018](https://github.com/flutter/flutter/issues/20570#issuecomment-416274436)

@zoechi I am not, can you point me to the doc page if you please?
If that works as I expect it to work, I still think this enhancement request is desirable, although a bit less important, for when you want finer control over what you include in your app

---

@zoechi commented on [Mon Aug 27 2018](https://github.com/flutter/flutter/issues/20570#issuecomment-416277337)

I only know about https://github.com/flutter/flutter/pull/16413
Seems it's not globs, but directory paths that get scanned for content.
https://github.com/flutter/flutter/pull/16413#issuecomment-385124929

**Comment by d-silveira** [comment]
The pull request you mention is very useful, and does relax the need for what I requested, 
still, I'd only consider this issue closed with a link to the docs where that feature is mentioned, at least. 
At most I would say that this is a slightly different request

**Comment by jwren** [comment]
This support would come from the Analysis Server, the duplicate issue for this is https://github.com/dart-lang/sdk/issues/28534
