### ISSUE TITLE
Consolidate (and count) repeated logging messages.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2588]
(For inspiration we could look at the dev tools console.)

**Comment by quangson91** [comment]
@pq, could you explain more ?

**Comment by pq** [comment]
Sure.  When the same message is repeated, it would be nice to have only one entry but with a count of occurrences.  For example, the dev console does it like this:

![image](https://user-images.githubusercontent.com/67586/45268271-4b529a00-b42e-11e8-888a-5444cc4ebfc7.png)

**Comment by quangson91** [comment]
I understood. 
I will try to implement this :)
Thank you!
