### ISSUE TITLE
Flutter SDK is not found in the specified location in Android Studio - fl doctor gives clean bill

### ISSUE THREAD

**Issue by egg15463114** [flutter/flutter-intellij#2596]
Hi there,

I am installing Flutter and everything is good exept one thing, specified above.

Flutter doctor says this:

`$ flutter doctor -v
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale nl-NL)
    • Flutter version 0.7.3 at C:\Flutter\flutter_windows_new\flutter
    • Framework revision 3b309bda07 (13 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\iwijsman\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.2
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[√] Connected devices (1 available)
    • Pixel 2 • FA83P1A01724 • android-arm64 • Android 9 (API 28)

• No issues found!`

I've added the requested path to variables, didn't know if it had to be the top one or bottom so added both
![image](https://user-images.githubusercontent.com/25908545/45301704-c17bfd00-b511-11e8-91b5-ffc7a045ec1f.png)

And in Androidstudio the plugins are in stalled and applied 
![image](https://user-images.githubusercontent.com/25908545/45301751-da84ae00-b511-11e8-9b14-ddbbde76a5eb.png)

And than I get this:
![image](https://user-images.githubusercontent.com/25908545/45301839-0bfd7980-b512-11e8-9343-53e75d82f014.png)

please help me, where am I going wrong??

**Comment by egg15463114** [comment]
Answer provided, this was one thing I haven't seen anywhere as far as I can tell.

Menu > Tools > SDK Manager > Android SDK (left side of the dialog) > SDK Tools (tab)

Ensure that this line is enabled
https://i.stack.imgur.com/q6iLx.png
With [OK] it should be installed.

https://stackoverflow.com/a/52259863/9005245 

issue fixed

**Comment by stevemessick** [comment]
According to the screenshots you provided, you set the Flutter SDK path (in the plugin) to the same path used in the system binary lookup path. The SDK path should end in 'flutter' not 'flutter/bin'.

**Comment by egg15463114** [comment]
I actually didn't edit the path further but downloaded the NDK which I didn't know I needed to download and now everything works. But thanks so much for the answer @stevemessick
