### ISSUE TITLE
"Navigate to testdata" does not work

### ISSUE THREAD

**Issue by maksimr** [flutter/flutter-intellij#2597]
## Steps to Reproduce

- Create a new project `flutter create foo`
- Open file `foo/test/widget_test.dart`
- Change line 18 to `expect(find.text('1'), findsOneWidget)`
- Run tests using "Flutter test run configuration"
- Try to navigate on the failed test from 'Run' panel 

## Version info

[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✗] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.3)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

**Comment by pq** [comment]
I've got this reproducing on the latest source and will take a look.

Thanks for the report @maksimr!
