### ISSUE TITLE
Android Studio 3.2 RC 3 is not working correctly with the Flutter plugin

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2600]
@creativecreatorormaybenot commented on [Tue Sep 11 2018](https://github.com/flutter/flutter/issues/21700)

*Everytime opening a Flutter project*, no matter what I have tried, I will have to do either or multiple of the following things:

   1. Reassign the `Flutter SDK path`: 
![](https://i.imgur.com/chInLbR.png)

   1. Enable Dart support for the project: 
![](https://i.imgur.com/vldv3oZ.png)

   1. Sync project with Gradle Files.

Before that, the project view looks like this: 
![](https://i.imgur.com/zth0M6h.png)
That means that I am unable to access any project directories (`android`, `ios` or `lib`) because the Flutter plugin is not connected properly (until I fix it with the necessary steps described above).  
This also disables all code analysis and completion features (if I open a file externally because I cannot access it from inside the workspace before enabling support and syncing) & the ability to run the application from within Android Studio.

### I have tried

Reinstalling from [the Android Studio Preview website](https://developer.android.com/studio/preview/) and `flutter upgrade`..

### Doctor

```
flutter doctor -v
[√] Flutter (Channel master, v0.8.3-pre.28, on Microsoft Windows [Version 10.0], locale en-US)
    • Flutter version 0.8.3-pre.28 at flutterRoot
    • Framework revision 0e8103ff13 (4 hours ago), 2018-09-11 18:16:21 +0200
    • Engine revision 9a173a8dc8
    • Dart version 2.1.0-dev.4.0.flutter-ef72098353

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at sdkRoot
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: javaRoot
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.

[√] Android Studio (version 3.2)
    • Android Studio at studioRoot
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by devoncarew** [comment]
@stevemessick

**Comment by stevemessick** [comment]
I have not been able to reproduce this problem.

Are these new or existing projects? If old, do you see a balloon notification that an Android framework was detected? Having once gotten a project to open properly, does it open in a good or bad state after closing and re-opening it?

Also, does `flutter doctor --android-licenses` change anything?

**Comment by stevemessick** [comment]
OK, thanks for the info. Unfortunately, I don't have any easy solution. I think the quickest way for you to get going with RC3 would be to create a new Flutter project and copy your files from the old project to the new one. Not ALL files, just the ones needed to make your Flutter project. For example, don't copy .idea, or any .* file unless you edited it (like .gitignore), or any *.iml file.

**Comment by stevemessick** [comment]
I guess that worked, so we'll close this issue.

**Comment by creativecreatorormaybenot** [comment]
@stevemessick Sorry that it took me so long. I am having the same problem when creating new Flutter projects, so migrating all my data to a new project would not work. As of now, I am running Android Studio 3.2.

**Comment by creativecreatorormaybenot** [comment]
@stevemessick Actually, I realised that it is bound to the working directory. When I create a new project in a different directory it works fine. Maybe this will give you some clue on how I could resolve this issue.

**Comment by creativecreatorormaybenot** [comment]
@stevemessick Apparently, I cannot *create a project, which has the **same name** as the **upper directory** (`...\name\name`)*.  
Also, renaming the directory of a project created with the same name as its parent directory, i.e. e.g. renaming `...\name\name` into `...\name\other` **after** creation *does not* solve the issue.  

Another strange thing: The project that *suddenly* (when I first issued this problem) encountered this does *not show **any** project directories on start up* (as described above), but if I create a `...\name\name` Flutter project *now, it will recognize the **`name_android`** project directory*, however, not the base one.

Still on Windows, but now using Android Studio 3.2.
