### ISSUE TITLE
Flutter blinking light bulb

### ISSUE THREAD

**Issue by BerndWessels** [flutter/flutter-intellij#2607]
For some time now the little lightbulb that helps you with suggestions and things like instant wrapping of the selected widget in code with another one blinks almost like the cursor. This makes it insanely hard to click it :(

Android Studio 3.1.4
Build #AI-173.4907809, built on July 24, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.7.2, on Microsoft Windows [Version 10.0.17134.285], locale en-NZ)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] Connected devices (1 available)

• No issues found!

**Comment by pq** [comment]
Oh!

I wonder if this is a platform thing.

Possibly a known issue?

/cc @alexander-doroshko @stevemessick

**Comment by pq** [comment]
Sorry, missed https://github.com/flutter/flutter-intellij/issues/2017 which has some likely relevant context.

**Comment by alexander-doroshko** [comment]
Sorry, no idea.

**Comment by stevemessick** [comment]
This was a problem in Android Studio that was fixed with 3.2.
