### ISSUE TITLE
make it easier to see FPS

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2609]
We should make it easier to see FPS when running an app. Right now the FPS display is in a tab of the inspector - we should consider moving it out from behind a tab and visible when the app is running.

**Comment by jacob314** [comment]
Another option is to make the perf tab of the inspector start open whenever you launch a profile build.
That will help with current user confusion about profile builds. "I did a profile build but now instead of seeing profiling tools I see fewer tools"

**Comment by devoncarew** [comment]
That sounds great to open perf related UI automatically when running in profile mode.

Generally, will some or most of the content in the profile tab move to a new top-level tool window? @jacob314 @terrylucas

**Comment by jwren** [comment]
This will be covered by future DevTools work.
