### ISSUE TITLE
create or repurpose an alpha doc README

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#261]
We've got a bunch of information spread across issues, wikis and internal docs.  We should consolidate what we need for fishfood into a single `README`.

**Comment by pq** [comment]
@devoncarew @mit-mit : I feel tempted to fill-out our main `README` which we left intentionally sparse.

https://github.com/flutter/flutter-intellij/blob/master/README.md

WDYT?

**Comment by pq** [comment]
Actually, after chatting w/ @devoncarew, I think the plan of action is to update `docs/readme.md` w/ install instructions:

https://github.com/flutter/flutter-intellij/blob/master/docs/readme.md

This will get slingshotted to flutter.io.

The top-level `README` can be more focused on the source base (e.g., build status, etc.)

Having said that, as I intend to put some time into docs this week, @mit-mit a wish list would be welcome.

**Comment by mit-mit** [comment]
Sounds good. Should the "user journeys" wiki page be converted to a .md
page here?

**Comment by pq** [comment]
Closing in favor of more targeted follow-ups.
