### ISSUE TITLE
No exception information for analysis server errors

### ISSUE THREAD

**Issue by rtolar** [flutter/flutter-intellij#2611]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
Adding new code to make an HTTP call.
Had just added `import 'package:http/http.dart' as http;` and then started typing the line below.

```
Future<String> _backgroundJob(int dummy) async {
  print("starting backgroundJob");
  var client = http.C    // HERE.  Was typing this line when the Dart Analyzer error occurred
  while (true) {
    Future<http.Resposne>
    print("in backgroundJob");
    sleep(Duration(seconds: 10));
  }
  return "done";
}

```
I got the following error:

"
9:35 AM	Dart Analyzer Error
				Encountered a Dart Analysis Server error.
				Open issue submission form?
"

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

flutter doctor -v
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.7.3 at C:\Users\rtola\dev\flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\rtola\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

C:\Users\rtola\AndroidStudioProjects\EmporosFlutter>

**Comment by devoncarew** [comment]
@rtolar, was there an exception associated with the report?

**Comment by rtolar** [comment]
I don't see an exception/stack trace of any kind, sorry.

The only thing it shows is:
"9:35 AM	Dart Analyzer Error
				Encountered a Dart Analysis Server error.
				Open issue submission form?
"

**Comment by devoncarew** [comment]
OK, ideally when you click on the `Open issue submission form` button, it should open a github issue web page pre-populated with some of the exception info, and a reference to a file with more complete information. If you're seeing that message in the IntelliJ log, it's probably lacking context to open the page correctly (it would work from the initial error message toast).

**Comment by rtolar** [comment]
Clicking 'Open issue submission form' opened a browser with no URL populated.
e.g. blank page

**Comment by devoncarew** [comment]
@stevemessick, I think we've seen a few instances of the browser page being populated w/ incomplete info - it'd be worth investigating, to see if there are any URL encoding issues, or other places things might be going wrong.

**Comment by pq** [comment]
> I think we've seen a few instances of the browser page being populated w/ incomplete info 

Since this seems the most actionable part of this, I'll rename the issue to track investigation.

Thanks @rtolar!

**Comment by rtolar** [comment]
The problem is reproducible.
I created a skeleton app to reproduce:
https://github.com/rtolar/flutter_intellij_2611

Basically:
1) add dependency to http in pubspec.yaml:    http: ^0.11.3+17
2) add import in main.dart  `import 'package:http/http.dart' as http;`
3) start typing `var client = http.C`

I only get the error the first time I type that.
Restart Android Studio to get it to happen again.

**Comment by devoncarew** [comment]
Thanks for the repo! I think we should file a separate issue for that on the dart-lang/sdk repo - this issue can track not getting data consistently plumbed through the browser url.

**Comment by stevemessick** [comment]
When I reproduce this problem using the versions of Flutter and Dart as specified, I get a valid issue submission form (appended). The referenced file exists and has a full stack trace. It looks like a Windows problem so maybe a Windows hacker could take a look.

-----------
```
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.1 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/yg/474plv091g1cqnz98j05v0y4003j5d/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 11, method: edit.isPostfixCompletionApplicable, params: {file: /Users/messick/Downloads/flutter_intellij_2611-master/lib/main.dart, offset: 519, key: .return}, clientRequestTime: 1542311338206}
NoSuchMethodError: The method 'isSubtypeOf' was called on null.
Receiver: null
Tried calling: isSubtypeOf(Instance of 'InterfaceTypeImpl')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      PostfixCompletionProcessor._findOuterExpression.<anonymous closure> (package:analysis_server/src/services/completion/postfix/postfix_completion.dart:566:16)
#2      _ListBase
```

**Comment by stevemessick** [comment]
I created an issue for the Dart plugin:
https://youtrack.jetbrains.com/issue/IDEA-202563

We can't fix it in the Flutter plugin, so I'm closing this issue.

**Comment by tangxiucai2** [comment]
I found some error just like : 
class A{
  A({this.prop, this.onAction(String id)});
  String prop;
  VoidCallback onAction;
}

because this function is error, but android studio dart plugin check also cause   Encountered a Dart Analysis Server error.
