### ISSUE TITLE
Cannot find declaration to go to

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter-intellij#2615]
## Steps to Reproduce

Try to Cmd+Click on any declaration. Result:
![image](https://user-images.githubusercontent.com/441756/45652580-e7614e80-ba89-11e8-888a-7151a75aa276.png)

This seems to be different from #2404 because everything else seems to be working fine: I can see Structure information and can navigate through code base as well.

Also show quick help (`F1`) isn't working as well.

## Version info

Tried both on current stable version of Android Studio as well as beta version 3.2 RC3.

```
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G2307, locale en-US)
    • Flutter version 0.6.0 at /Users/anatoly/Projects/flutter
    • Framework revision 9299c02cf7 (5 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/anatoly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by pulyaevskiy** [comment]
Ah, ok. This seems like analyzer issue. If I add `new` keyword in the above snippet it works normally again.

**Comment by devoncarew** [comment]
> Ah, ok. This seems like analyzer issue. If I add new keyword in the above snippet it works normally again.

Thanks for diagnosing; I see that you're running flutter beta `0.6.0` - it might be worth re-checking with a more recent build to see if you still see the analyzer issue w/ `new`.

**Comment by pulyaevskiy** [comment]
Thanks for getting back on this. I'll give it a shot and report back if it improved.

**Comment by pulyaevskiy** [comment]
I've just updated to latest beta (0.7.3) and this still seems to be an issue.

**Comment by JamesChenX** [comment]
@pulyaevskiy I have solved the exactly same problem by this way:
https://stackoverflow.com/questions/37282285/intellij-cannot-find-any-declarations

> 1. Exit IDE
> 2. Recursively delete all .iml files from project directory del /s /q "C:\Dev\trunk\*.iml"
> 3. Find and delete all .idea folders
> 4. Delete contents of the caches, index, and LocalHistory folders under .IntelliJIdea2017.2\system
> 5. Open Idea and import project ....

**Comment by pulyaevskiy** [comment]
@JamesChenX the issue I had was only about specific types (in the above example it was `StreamController`, while everything else was working fine.

I just rechecked and this seems still unresolved:
![kapture 2019-01-09 at 21 42 49](https://user-images.githubusercontent.com/441756/50948540-da8ebd80-14b3-11e9-9d68-5ebd1e3136b3.gif)

I'm on Flutter stable 1.0.0

Not sure if this should be re-opened or transferred to analyzer issues...

**Comment by basilmariano** [comment]
For me: 
1. I tried to clean the flutter cache
flutter > bin > cache
2. Restart the IDE
3. Terminal `flutter clean`
