### ISSUE TITLE
Android Studio flutter and dart plugins not recognized by flutter doctor , but plugins are installed

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2620]
@ZayniddinMamarasulov commented on [Fri Sep 14 2018](https://github.com/flutter/flutter/issues/21881)

Hello everybody , I am trying to install flutter on ubuntu , android studio flutter and dart plugins have been installed , but `flutter doctor` said that they are not installed. At the beginning flutter doctor didn't find my android studio and sdk even if they are installed, then fixed this problems by configuring custom directories for android studio and sdk with this commands : 
```
flutter config --android-studio-dir=/my/local/path/for/android/studio
flutter config --android-sdk=/my/local/path/for/sdk
``` 
but couldn't find any solution how to show android studio installed plugins directory for flutter doctor
```
[✓] Flutter (Channel beta, v0.7.3, on Linux, locale en_US.UTF-8)
    • Flutter version 0.7.3 at /home/zayniddin/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /home/zayniddin/Documents/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /home/zayniddin/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio
    • Android Studio at /home/zayniddin/Documents/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /home/zayniddin/Documents/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /snap/intellij-idea-community/77
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.27.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

```
any solutions ?, please help me 

---

@evelyne24 commented on [Fri Sep 14 2018](https://github.com/flutter/flutter/issues/21881#issuecomment-421481907)

Hey, I'm on Mac but I had to install the Flutter and Dart plugin in Android Studio, by going to `Preferences > Plugins > Browse Repositories > find the plugins, install and restart`.  Have you tried that?

<img width="1023" alt="screen shot 2018-09-14 at 23 54 02" src="https://user-images.githubusercontent.com/239384/45574733-a4c92780-b879-11e8-8077-7c808fd34605.png">

---

@ZayniddinMamarasulov commented on [Sat Sep 15 2018](https://github.com/flutter/flutter/issues/21881#issuecomment-421528659)

> Hey, I'm on Mac but I had to install the Flutter and Dart plugin in Android Studio, by going to `Preferences > Plugins > Browse Repositories > find the plugins, install and restart`. Have you tried that?
> 
> <img alt="screen shot 2018-09-14 at 23 54 02" width="1023" src="https://user-images.githubusercontent.com/239384/45574733-a4c92780-b879-11e8-8077-7c808fd34605.png">

yes I installed plugins , but flutter doctor didn't recognize

---

@zoechi commented on [Sat Sep 15 2018](https://github.com/flutter/flutter/issues/21881#issuecomment-421549438)

`flutter doctor -v` also doesn't show your Android Studio version

```
[✓] Android Studio (version 3.1)
```

What Android Studio version do you have installed?

---

@febs commented on [Tue Sep 18 2018](https://github.com/flutter/flutter/issues/21881#issuecomment-422395091)

I got that very same behavior on Android Studio 3.2 RC3:

`[✓] Android Studio (version 3.2)`
`    • Android Studio at /home/fabio/DevTools/beta/android-studio`
`    ✗ Flutter plugin not installed; this adds Flutter specific functionality.`
`    ✗ Dart plugin not installed; this adds Dart specific functionality.`
`    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)`

---

@zoechi commented on [Wed Sep 19 2018](https://github.com/flutter/flutter/issues/21881#issuecomment-422831238)

Try with Flutter from `master` channel. I think to remember there was a fix recently to make the plugins compatible with Android Studio 3.2. 

---

@febs commented on [Thu Sep 20 2018](https://github.com/flutter/flutter/issues/21881#issuecomment-423100931)

That partially solved the issue. Now both my copies of Android Studio (3.1 and 3.2beta) are recognized and they plug-ins also are.
But :-D the flutter doctor now also identifies a non-existent third Android Studio installation (with no version attached according to it) and the missing plugins.

Here's the output:

```
 [✓] Android Studio (version 3.1)
    • Android Studio at /home/fabio/android-studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
[✓] Android Studio (version 3.2)
    • Android Studio at /home/fabio/DevTools/beta/android-studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[✓] Android Studio
    • Android Studio at /home/fabio/DevTools/beta/android-studio/
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /home/fabio/DevTools/beta/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by stevemessick** [comment]
It looks like you're having trouble getting the flutter CLI tool to work with non-standard installation directories. That should be reported on the appropriate forum:
https://github.com/flutter/flutter/issues

**Comment by zoechi** [comment]
I reopened the original issue according to your comment @stevemessick
