### ISSUE TITLE
Consider de-emphasizing log level severity

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2624]
Feedback from @devoncarew:

> I mostly didn't want to filter based on severity level but based on kind (don't show gc, don't show frames, do show stdout, ...). We may consider de-emphasizing severity, removing it, or making it a category instead (verbose items?)

👍 

This is supported by the move away from capturing severity in the flutter logging API (https://github.com/flutter/flutter/pull/22041).

**Comment by jaumard** [comment]
So I'm 100% for a combobox with categories parse from our logs inside, 
But I find the log level combo box still useful to not pollute logs when you are not searching for any particular bugs. I generally change this value when I finally wants to get deeper in something specific (that's were the category combobox might help) so for me both would be great ! My 2 cts

**Comment by pq** [comment]
After a bunch of discussion (and the restoration of the combo chooser), I think this is **_considered_** enough to close without any further action....

Let's track any thoughts for how we can best take advantage of levels and categories in follow-up issues.
