### ISSUE TITLE
Improve Logging Channel UI

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2641]
Follow-up from https://github.com/flutter/flutter-intellij/pull/2640#issuecomment-425538031, regarding the current logging channel UI:

> I think we've generally found the gear menu hard to discover (at least for the Inspector), so we may want to look at ways to expose many or most of the logging channels checkboxs along the toolbar?

👍 👍 👍

**Comment by devoncarew** [comment]
Closing as this is related to the experimental logging view.
