### ISSUE TITLE
Feature: navigate to intervals in observatory from the perf timeline

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2656]
Chatting w/ @matthewtsmith, he suggested we have some way to navigate from the performance view to corresponding data in observatory.  (Watching his workflow, I agree this'd be pretty great.)

Food for thought!

/cc @johnpryan @jacob314 @terrylucas

**Comment by jacob314** [comment]
Closing this as we're achieving the same effect by making package:devtools support all the functionality from the observatory and intellij.
