### ISSUE TITLE
Hot restart and "rerun main" buttons have same icon – makes things confusing.

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter-intellij#2662]
Both are a curved green arrow w/ a gray box.

I was "rerunning" and was wondering why everything is so slow!

![flutter_hot_restart](https://user-images.githubusercontent.com/17034/46443215-60ff6a80-c721-11e8-86a6-3635baedf7df.png)
![rerun_main](https://user-images.githubusercontent.com/17034/46443217-61980100-c721-11e8-9614-f26f9cfc3643.png)

## Version info

[✓] Flutter (Channel dev, v0.9.5, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.5 at /Users/kevmoo/source/github/flutter
    • Framework revision 020fd590b0 (7 days ago), 2018-09-26 14:28:26 -0700
    • Engine revision 38a646e14c
    • Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/kevmoo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by stevemessick** [comment]
@devoncarew do you think this is something we should fix in the next release?

**Comment by devoncarew** [comment]
Yes - icons are always hard, but I didn't realize we were using the same one for different actions.

**Comment by devoncarew** [comment]
Thoughts?

<img width="523" alt="screen shot 2018-10-04 at 11 26 14 am" src="https://user-images.githubusercontent.com/1269969/46494721-6a8fdd80-c7c8-11e8-9828-cb6568c88dda.png">

<img width="81" alt="screen shot 2018-10-04 at 11 26 21 am" src="https://user-images.githubusercontent.com/1269969/46494723-6a8fdd80-c7c8-11e8-9be9-7495996a663e.png">

It's at least distinct from the process restart icon. Likely should continue to iterate.

We have this one as well:

https://github.com/flutter/flutter-intellij/blob/master/resources/icons/restart%402x.png

but if I remember it didn't look great in context.

**Comment by kevmoo** [comment]
I like it!

**Comment by stevemessick** [comment]
👍
