### ISSUE TITLE
Only display device list for Flutter projects

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#267]
If the Flutter plugin is installed the device list pull-down is displayed in the tool bar unconditionally. It should be possible to adapt that behavior so the pull-down is only displayed when the current project is a Flutter project.

**Comment by alexander-doroshko** [comment]
Or may be only when currently selected run configuration in the neighbor combo box is the Flutter one.

**Comment by pq** [comment]
@alexander-doroshko : you mentioned maybe just swapping in a transparent pane (or something).  Can you point me towards anywhere else in the IDE where something similar is done "the right way?"  It'd be great to have a reasonable point of reference.

Thanks!

**Comment by alexander-doroshko** [comment]
A guess with empty panel was wrong. 
DeviceSelectorAction is a standard Action, you control its visibility inside `update()` method using standard `e.getPresentation().setVisible()`.

**Comment by pq** [comment]
Ah!  That's much easier.  Thanks!
