### ISSUE TITLE
Flutter Project Directory

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2674]
@bipin-adh commented on [Sat Oct 06 2018](https://github.com/flutter/flutter/issues/22758)

/home/bpn8adh/AndroidStudioProjects/android-architecture-todo-mvp/flutter_app
This is the default project location of a new project , flutter_app being the project name. 
Even though i changed the location to a new one, the application files moves this very same default directory.

Note: This problem arises when i create a new flutter project from android studio itself. It works fine if i use terminal to create a new project . 

i.e.  flutter create test_app worked fine . I was able to create a project in my desired location.

**Comment by zoechi** [comment]
@bipin-adh Please add the output of `flutter doctor -v`.

**Comment by stevemessick** [comment]
@bipin-adh A screenshot of the dialog window that sets the project directory would be helpful. Without it this will be hard to debug.
