### ISSUE TITLE
White screen on iOS simulator in debug

### ISSUE THREAD

**Issue by muirandy** [flutter/flutter-intellij#2675]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
I'm running through the getting started exercise: https://flutter.io/get-started/codelab/
I wanted to hot-reload the app (as the exercise says), but in the iOS simulator, I get a white screen.

## Version info
I'm using IntelliJ Ultimate 2018.2.4
Flutter plugin 29.0.4

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[✓] Connected devices (1 available)

• No issues found!
Process finished with exit code 0

**Comment by muirandy** [comment]
Here's the output from InteliJ console:
```
Launching lib/main.dart on iPhone XS in debug mode...
log: Must be admin to run 'stream' command
Script started, output file is /dev/null

Script done, output file is /dev/null
Starting Xcode build...
Xcode build done.

```

**Comment by jwren** [comment]
To be clear here, this was in Step 2, Use an External Package.

Did you see the content?:

Problems?
If your app is not running correctly, look for typos. If needed, use the code at the following links to get back on track.

pubspec.yaml
lib/main.dart

**Comment by muirandy** [comment]
Indeed, its in step 2. I've no problem with the code itself, as it works fine if I simply "Run" the app - it displays the white screen if I "Debug" it. 
When I'm "Running" the app, the "Flutter Hot Reload" button is greyed out" - I'd read that maybe it needs to be running in debug. 
(I've also moved on through the exercise with no issues, other than not being able to debug or hot reload!)

**Comment by jwren** [comment]
Assigning this to @devoncarew to triage.

**Comment by muirandy** [comment]
I've created a(nother) new Flutter project in IntelliJ and without touching the code, I'm seeing exactly the same behavior - running in debug just gives me a white screen on the iOS simulator, while 'run' gives me the application running fine (though I can't use the debugger or hot reload).

**Comment by devoncarew** [comment]
@muirandy, I don't know if there's a resolution for this, but it looks like you're hitting the same issue as https://github.com/flutter/flutter/issues/18409. I'll close this issue in favor of that one.

**Comment by sjayadeep** [comment]
I faced the same issue.
Try to upgrade flutter to the latest.
`flutter upgrade`

then clean the project.
`flutter clean`

Try running again

**Comment by ahmdmhasn** [comment]
Thanks @sjayadeep... `flutter clean` did the job
