### ISSUE TITLE
Pass reload reasons to Flutter tools

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter-intellij#2682]
The reload/restart messages in Flutter Daemon can now be passed a `reason` (to provide better stats on user-initiated hot reloads/restarts versus things triggered automatically):

https://github.com/flutter/flutter/pull/21983

In VS Code, we're sending [the strings `save` and `manual`](https://github.com/Dart-Code/Dart-Code/blob/55687223bd2d9085b8fd37043d22d6f9e36799d9/src/constants.ts#L1-L2) depending on whether it was a reload triggered by the user saving, or an explicit action (toolbar button, executing command, explicit keybind - we can't tell the difference between any of those in VS Code):

https://github.com/Dart-Code/Dart-Code/pull/1243

```
[10:31:23 AM]: ==> [{"id":"8","method":"app.restart","params":{"appId":"711d65de-0764-49da-8103-cd8d756d1876","fullRestart":false,"pause":true,"reason":"manual"}}]

[10:31:37 AM]: ==> [{"id":"9","method":"app.restart","params":{"appId":"711d65de-0764-49da-8103-cd8d756d1876","fullRestart":false,"pause":true,"reason":"save"}}]
```

**Comment by jwren** [comment]
Assigning to @devoncarew to triage

**Comment by pq** [comment]
@devoncarew : are you looking at this one?

**Comment by devoncarew** [comment]
hey - no, not currently.
