### ISSUE TITLE
remove asset file from pubspec.yml

### ISSUE THREAD

**Issue by ColorFuzzy** [flutter/flutter-intellij#2683]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

1. add a file to `assets:` header of `pubsepc.yml`
2. then remove the file & code line in `pubspec.yml`
3. there still exist infomation in `ios/Flutter/flutter_assets/AssetManifest.json`

## Version info

[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.9.4 at /Users/lvyiwang/Bin/flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

**Comment by jwren** [comment]
@pq Is this a flutter tooling issue? Any idea who should own it?

**Comment by devoncarew** [comment]
> there still exist infomation in ios/Flutter/flutter_assets/AssetManifest.json

@ColorFuzzy, you likely need to trigger something in the flutter tool to rebuild the ios version of the assets manifest; perhaps `flutter run`ing your app?
