### ISSUE TITLE
[ColorIcons] Color icons not showing for consts with func scope

### ISSUE THREAD

**Issue by willlarche** [flutter/flutter-intellij#2684]
In [themes.dart from flutter gallery](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/themes.dart)

See image. The consts `primaryColor` and `secondaryColor` are not showing a color icon on the left.

Nice to have: since they are consts, it would be great it it showed the same icon where they are consumed like line 34-35.

![screen shot 2018-10-11 at 12 13 41 pm](https://user-images.githubusercontent.com/1271525/46818641-bfdf6800-cd4f-11e8-9e2d-2643555f311b.png)

**Comment by jwren** [comment]
Assigned to Devon to triage, I don't know who did this initial work.

**Comment by devoncarew** [comment]
This was me; `on deck` seems right.

**Comment by devoncarew** [comment]
Thanks for the report! This was addressed for the Nov. release.
