### ISSUE TITLE
Gradle Issue

### ISSUE THREAD

**Issue by NagarjunaReddyP** [flutter/flutter-intellij#2691]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by NagarjunaReddyP** [comment]
Launching lib\main.dart on SM G900H in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: D:\NewFlutter\App\testapp\flutter_app\android\gradlew.bat app:properties:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find gradle.jar (com.android.tools.build:gradle:3.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

Finished with error: Please review your Gradle project setup in the android/ folder.

Facing this issue in windows 10 flutter.

**Comment by jwren** [comment]
Please provide information on what the Gradle issue is.

**Comment by NagarjunaReddyP** [comment]
Hi @jwren  this is the error am getting when am running my first flutter program.

Initializing gradle...

Resolving dependencies...

Error running Gradle: Exit code 1 from: D:\NewFlutter\App\testapp\flutter_app\android\gradlew.bat app:properties:
FAILURE: Build failed with an exception.

What went wrong: A problem occurred configuring root project 'android'.

Could not resolve all files for configuration ':classpath'. Could not find gradle.jar (com.android.tools.build:gradle:3.1.2). Searched in the following locations: https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.jar

Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 21s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by devoncarew** [comment]
@NagarjunaReddyP, the main issue seems to be gradle related:

> Could not resolve all files for configuration ':classpath'. Could not find gradle.jar (com.android.tools.build:gradle:3.1.2). Searched in the following locations: https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.jar

I would try and google for a reasonable solution to that issue. If nothing turns up, you may try asking in the gitter room for Flutter, or file an issue against the main flutter repo (flutter/flutter). Thanks!

**Comment by NagarjunaReddyP** [comment]
@devoncarew , this is working fine after updating gradle version.
