### ISSUE TITLE
create missing switch branches alt+enter not showing up

### ISSUE THREAD

**Issue by akalinxy** [flutter/flutter-intellij#2695]
When creating a empty switch block intellij will warn you that there are missing branches, but upon clicking alt+enter the expected behavior is that it should display a option for intellij to automatically insert the missing branches, as is done with a java project, but nothing shows up.

**Comment by pq** [comment]
Thanks for the feedback @akalinxy!

It looks like the Dart analysis server isn't providing an assist here (where it could).

@scheglov: is this a known opportunity?  Should I transfer this issue to the sdk repo?
