### ISSUE TITLE
Could not get Flutter Wizard in Android Studio (Stable v3.2.1)

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2696]
@RohitSurwase commented on [Mon Oct 15 2018](https://github.com/flutter/flutter/issues/23086)

Tried a lot of different ways. But still could not get the Flutter Wizard in Android Studio.
1. Removed All versions, Stable + Preview.
2. Tried with Stable only
3. Tried with Preview only
4. Tried restarting several times and at several stages.
5. Tried changing install sequence of Dart and Flutter plugin.
6. And so on...

Nothing worked so far.

version: stable 3.2.1
system: MacOS High Sierra.

Here, are the details:
```
MacBook-Pro-4:~ rohitsurwase$ flutter doctor --verbose
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.9.4 at /Users/rohitsurwase/Library/Android/sdk/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/rohitsurwase/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rohitsurwase/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • HTC One X9 dual sim • LC66RBK06370 • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 2 categories.
```

---

@zoechi commented on [Mon Oct 15 2018](https://github.com/flutter/flutter/issues/23086#issuecomment-429732060)

Can you please try in `dev` or `master` channel. I think there was a related issue fixed very recently.

What exactly does this mean anyway?

> But still could not get the Flutter Wizard in Android Studio

---

@RohitSurwase commented on [Mon Oct 15 2018](https://github.com/flutter/flutter/issues/23086#issuecomment-429733788)

@zoechi Thanks for replying! There is no option to create a new Flutter Project in Android Studio. I am using command `flutter create project_name` for now.

How can I try in dev or master channel?

---

@zoechi commented on [Mon Oct 15 2018](https://github.com/flutter/flutter/issues/23086#issuecomment-429736019)

Run in a terminal
```
flutter channel master
flutter doctor
```

---

@RohitSurwase commented on [Mon Oct 15 2018](https://github.com/flutter/flutter/issues/23086#issuecomment-429742614)

@zoechi  Tried with `master` and `dev` channel, still no luck. Also tried removing and re-installing plugins. Nothing worked.

---

@RohitSurwase commented on [Mon Oct 15 2018](https://github.com/flutter/flutter/issues/23086#issuecomment-429743317)

Latest master version that I tried

[✓] Flutter (Channel master, v0.10.1-pre.40, on Mac OS X 10.13.6 17G65, locale
    en-IN)
    • Flutter version 0.10.1-pre.40 at
      /Users/rohitsurwase/Library/Android/sdk/flutter
    • Framework revision 8e2ca93f52 (2 days ago), 2018-10-12 21:07:55 -0700
    • Engine revision 50c2e69daf
    • Dart version 2.1.0-dev.7.0.flutter-b99bcfd309

---

@RohitSurwase commented on [Mon Oct 15 2018](https://github.com/flutter/flutter/issues/23086#issuecomment-429745922)

Hey! The issue resolved. 
I was importing Android Studio settings from the previous version every time. Just tried deleting and creating fresh new settings and it worked.
Thanks for helping.

**Comment by pq** [comment]
Thanks for the feedback!

I'm not sure the stale settings issue is likely to hit other folks (or how anomalous it was)... 

Optimistically closing but @stevemessick do feel free to re-open if you have any insights.

**Comment by brianegan** [comment]
Just wanted to chime in here: @filiph and I are running a workshop one of our attendees ran into this same problem: No wizard appeared or options to create a new flutter project. 

Installing / reinstalling didn't work, and deleting their settings wasn't a viable option since they use Android Studio as their primary IDE for work projects.

Creating a project from the command line and using Android Studio to open the project worked fine.

We looked at the IntelliJ logs and didn't see any errors related to Flutter. Overall, we might not be able to stay in touch with this person, but wanted to let you know it was happening for new users as well.

**Comment by RohitSurwase** [comment]
Though you are not looking for a temporary solution here are the steps for it-
(For anyone looking for a quick fix)

Cause- We are importing settings from the previous version of Android Studio as a general practice.

Solution-
Step 1: Remove Flutter and Dart plugin from Studio.
Step 2: In the command line
flutter channel master (switch to master branch)
flutter doctor (get updates from master branch)

Step 3: Close AS and delete all previous settings folders (AndroidStudio3.1, AndroidStudio3.2 ...) Now, start AS with fresh new settings.

Step 4: Install Dart plugin first, restart AS. Install Flutter Plugin, restart AS.
And your Android Studio is ready for Flutter. :)

**Comment by stevemessick** [comment]
> No wizard appeared or options to create a new flutter project

Not clear what this means. If "no wizard appeared" when you did something to cause a wizard to appear, what was it that you did?

If "options to create" were not present then did you do something that should have invoked the wizard?

By "wizard" are we talking about the New Project Wizard that is used to create Flutter projects in Android Studio?

There are two ways to invoke the New Project Wizard in Android Studio. If no project window is open the Welcome Screen has as its second option "Start a new Flutter project". Was that present or absent? The other option is from the main menu: File > New > New Flutter Project. Was that present or absent?

**Comment by RohitSurwase** [comment]
@stevemessick I request you go through the previous comments because the answers that you are looking for are already there.

**Comment by brianegan** [comment]
Hi @stevemessick -- I'll try to answer each question!

  * By "wizard" are we talking about the New Project Wizard that is used to create Flutter projects in Android Studio? - Exactly. The Wizard you get by clicking on "Start a new Flutter Project" from the Welcome screen.
  * Not clear what this means. If "no wizard appeared" when you did something to cause a wizard to appear, what was it that you did? -- User had Android studio installed and working for normal android projects. They install Flutter, Flutter Plugin, and Dart Plugin. On the "Welcome" screen, there is no option to "Start a new flutter project" nor is the "New Flutter Project" available in the File > New menu. There was just no way to create a Flutter project.

**Comment by stevemessick** [comment]
@brianegan Thanks for the clarification! I'm trying to understand if the plugin was activated or not. Do you recall if the device selector was visible? It is in the menu bar, toward the right-hand side. It is the `<no-devices>` drop-down in this image.

<img width="342" alt="screen shot 2018-11-07 at 7 35 26 am" src="https://user-images.githubusercontent.com/8518285/48141463-d1893200-e25f-11e8-9ab7-b927a9a45dd7.png">

It is possible your workshop attendee had a version of Android Studio for which the plugin did not fully function. There was a build problem, since fixed, that prevented AS-specific features from being activated in some of the later 3.2 preview versions.

@RohitSurwase The information is ambiguous.

**Comment by filiph** [comment]
The attendee's version was the same as my own, a stable 3.2.1.
