### ISSUE TITLE
Open lib\main.dart automatically for new project

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#270]
When the user creates a new project, we should automatically open lib\main.dart in the main editor window, to guide them to where to start editing code.

**Comment by pq** [comment]
Are you creating a fresh project or opening an existing one?  (The former should be implemented and if it isn't working, it's a bug!)

**Comment by mit-mit** [comment]
Sorry, it does open, just a bit later (I was using a slow VM)
