### ISSUE TITLE
Select widget button in flutter inspector is grayed out

### ISSUE THREAD

**Issue by SUPERETDUPER** [flutter/flutter-intellij#2704]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
I ran an app and the flutter inspector shows the widget tree but pressing on the select widget mode does nothing and it looks like the button is grayed out.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

```
[✓] Flutter (Channel master, v0.10.1-pre.74, on Linux, locale en_CA.UTF-8)
    • Flutter version 0.10.1-pre.74 at /opt/flutter
    • Framework revision 44c0080a3c (5 hours ago), 2018-10-17 16:45:03 -0400
    • Engine revision 04c860fa1d
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/superetduper/Applications/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /home/superetduper/Applications/Android/sdk
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /home/superetduper/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-2/183.3795.13
    • Flutter plugin version 29.0.5
    • Dart plugin version 183.3283.3

[✓] Connected device (1 available)
    • Mi A1 • 008f25770804 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by pq** [comment]
Hey there @SUPERETDUPER: we've done a few releases of the plugin since the one you have installed.  Could you update and see if that makes things better?

Please re-open if that doesn't do the trick.

Thanks!

**Comment by pq** [comment]
Thanks for checking.

@jacob314 : any ideas?

**Comment by jacob314** [comment]
https://github.com/flutter/flutter/pull/23272
fixes this.
Thanks for reporting!
