### ISSUE TITLE
Preview lacking for CupertinoIcons

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/flutter-intellij#2711]
## Steps to Reproduce

The Material icons get a lovely preview in IntelliJ:

![image](https://user-images.githubusercontent.com/969662/47242797-cb144280-d3a4-11e8-8d58-a51ff7f38f2b.png)

But the [Cupertino Icons](https://github.com/flutter/cupertino_icons) do not.

![image](https://user-images.githubusercontent.com/969662/47242810-d10a2380-d3a4-11e8-8308-363e427afc96.png)

Now that I'm spending a good bit of time on a Cupertino, this is bumming me out. Is it an issue with the cupertino_icons package, or is there custom IntelliJ code at work for Material's icons?

## Version info

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
[!] VS Code (version 1.24.1)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.

**Comment by pq** [comment]
IIRC we bundle up all the material icons in the plugin (though I recall Devon having played with a better idea). We'd have to do something similar for Cupertino (or better still, fix them both a better way).

/cc @devoncarew for thoughts.
