### ISSUE TITLE
Error running 'main.dart': not implemented

### ISSUE THREAD

**Issue by chenkangcrack** [flutter/flutter-intellij#2713]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by pq** [comment]
Hi @chenkangcrack.  We need a bit more context to help with this report...  Was there a stacktrace in the console?

**Comment by expl0r3rgu1** [comment]
I got this error too

**Comment by expl0r3rgu1** [comment]
I got this error just recently developing in intellij idea. I don't really
know the causes. I just tried to run the default flutter project (The one
with the tap counter). I hope you will help me. I really want to develop in
flutter!

Il giorno Sab 3 Nov 2018, 16:01 no-response[bot] <notifications@github.com>
ha scritto:

**Comment by aravindara** [comment]
i got this error

**Comment by lishuhao** [comment]
#### I got this error too
I make this[ video](https://giant.gfycat.com/BackEvenBluebottle.webm)
####Flutter doctor
```bash
👉  ~ flutter doctor -v
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
    • Flutter version 0.11.3 at /Users/hao/Documents/flutter
    • Framework revision 72bf075e8d (6 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/hao/Library/Android/sdk
    • Android NDK at /Users/hao/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/hao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • ONE E1001 • bb72222f • android-arm • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by lishuhao** [comment]
@pq

**Comment by DDDrop** [comment]
I got the same problem too. And I fixed this by reset IntelliJ IDEA settings.

Maybe [this page](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) will help you.

**Comment by praveen-francium** [comment]
> I got the same problem too. And I fixed this by reset IntelliJ IDEA settings.
> 
> (Maybe [this page](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) will help you to find locations of IntelliJ IDEA settings)

i am facing the same issue but what i change i need to be done.Could you clarify with your answer

**Comment by PeterCaballero** [comment]
> > I got the same problem too. And I fixed this by reset IntelliJ IDEA settings.
> > (Maybe [this page](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) will help you to find locations of IntelliJ IDEA settings)
> 
> i am facing the same issue but what change i need to be done.Could you clarify with your answer

I understood that you have to remove all the directories that are listed in the link.
They are listed depending on your OS.  I did it and it fixed the 'main.dart': not implemented error.

**Comment by HenryWangCoo** [comment]
@PeterCaballero  I'm follow you step, rm all directories, but not work for me.  i'm mac os , cloud tell me some details about it , thanks a lot~!

**Comment by PeterCaballero** [comment]
> @PeterCaballero I'm follow you step, rm all directories, but not work for me. i'm mac os , cloud tell me some details about it , thanks a lot~!

:) 

Hello Henry, I'm also working on macOS (Mojave) and my version of Intellij is 2018.3:

- removed dart and flutter plugins directly from Preferences menu, then i closed the IDE, removed all the directories  and then when i opened Intellij again it looks like i've never opened  a single project or either work with the software.

- Installed plugins again and thats all, i could run my app without problems.



--------------------------------------------------------------------------
PD. Probably you could also search 'How to restart intellij default settings' but probably you will find something related to these instructions.

Good Luck

**Comment by HenryWangCoo** [comment]
> > @PeterCaballero I'm follow you step, rm all directories, but not work for me. i'm mac os , cloud tell me some details about it , thanks a lot~!
> 
> :)
> 
> Hello Henry, I'm also working on macOS (Mojave) and my version of Intellij is 2018.3:
> 
> * I removed dart and flutter plugins directly from Preferences menu, then i closed the IDE, removed all the directories  and then when i opened Intellij again it looks like i've never opened  a single project or either work with the software.
> * Installed plugins again and thats all, i could run my app without problems.
> 
> PD. Probably you could also search 'How to restart intellij default settings' but probably you will find something related to these instructions.
> 
> Good Luck

@PeterCaballero it works , thanks.

**Comment by MrinalKantiGhosh2196** [comment]
I faced this issue too but unable to resolve it. For now, I have to run my application every time from the terminal using `flutter run`.

**Comment by zouzhenglu** [comment]
> I got the same problem too. And I fixed this by reset IntelliJ IDEA settings.
> 
> (Maybe [this page](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) will help you to find locations of IntelliJ IDEA settings)

I fixed this problem in this way

**Comment by zouzhenglu** [comment]
> I faced this issue too but unable to resolve it. For now, I have to run my application every time from the terminal using `flutter run`.

I think it's a bug from idea , I delete all setting dirs and restart , install flutter plugin again, and it's successful.
If you're  fail , how about uninstall and reinstall again?
