### ISSUE TITLE
Failed to get http library (0.12.0) because flutter test depends on http version 0.12.0

### ISSUE THREAD

**Issue by adadion** [flutter/flutter-intellij#2719]
## Steps to Reproduce

I recently just adding the latest http library to the pubspec.yaml for the first time for my current project.
When I run flutter packages get from the IDE (Android Studio 3.2.1), there is an error. 

![error](https://user-images.githubusercontent.com/14196587/47362035-a9e18800-d6fd-11e8-8d0b-745ad3fce23a.png)

So far, I only can verify some files that related about this issue.
My .packages file
![packages](https://user-images.githubusercontent.com/14196587/47362711-4193a600-d6ff-11e8-8db4-f8f55e6741f4.png)

And External libraries
![external-lib](https://user-images.githubusercontent.com/14196587/47362743-51ab8580-d6ff-11e8-9d09-15899f820a3d.png)

## Version info
Android Studio 3.2.1
Flutter Plugin 29.1.1
Dart Plugin 181.5656

The output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.4 at /home/adadion/FlutterKu/flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/adadion/Android/Sdk
    • Android NDK at /home/adadion/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • Redmi Note 4 • 5426d6360903 • android-arm64 • Android 7.0 (API 24)

• No issues found!

**Comment by jacob314** [comment]
I don't think the issue you are seeing is related to Flutter intellij.
Here is some background info to describe how version constraints work in Dart.
You can't always use the very latest version of all pub packages with Flutter as package:flutter has version constraints which you need to be consistent with.
https://www.dartlang.org/tools/pub/versioning

Pub related bugs should be filed here:
https://github.com/dart-lang/sdk/issues
Flutter doctor issues should be filed here:
https://github.com/flutter/flutter/issues
