### ISSUE TITLE
Missing logcat tab in Android Studio

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2724]
@anderscheow commented on [Thu Oct 25 2018](https://github.com/flutter/flutter/issues/23497)

Logcat tab does not appear in Flutter project but visible in Android project

## Logs

```
[✓] Flutter (Channel dev, v0.10.1, on Mac OS X 10.14 18A391, locale en-MY)
    • Flutter version 0.10.1 at /Users/anders/flutter
    • Framework revision 6a3ff018b1 (5 days ago), 2018-10-18 18:38:26 -0400
    • Engine revision 3860a43379
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/anders/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM T815Y                  • 3300ffc315341365                         • android-arm • Android 7.0 (API 24) (emulator)
    • HM 1S                     • d0925617                                 • android-arm • Android 4.4.4 (API 19)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 4.4.2 (API 19) (emulator)
    • Anders’ iPhone X          • fb459deb33528e3571bfac0a2e555307cc879773 • ios         • iOS 12.0.1

! Doctor found issues in 2 categories.
```

**Comment by stevemessick** [comment]
@anderscheow: This is what I expect to see. You can open it in a Flutter project but when you do it reports: "Please configure Android SDK", which seems confusing to me.

**Comment by stevemessick** [comment]
We're taking no action here since logcat can be opened when needed.

**Comment by ascmp** [comment]
@stevemessick could you please explain me how to "open it when needed"? I've two windows of Android Studio opened, both Flutter projects, and one show me the logcat tab, but the other one doesn't. In both the Android SDK is configured correctly. The window which doesn't show the logcat tab doesn't even list it under View -> Tool Windows (see attachment).
The window which shows it is for a project recently created, while the one which doesn't show it is for a project created about 6 months ago, not sure if it can makes a difference.

![Screenshot from 2019-07-10 12-41-26](https://user-images.githubusercontent.com/9590466/60959100-44c3d600-a310-11e9-8a63-e6ebd8f5653d.png)
![Screenshot from 2019-07-10 12-39-29](https://user-images.githubusercontent.com/9590466/60959101-455c6c80-a310-11e9-96b7-b5c5b77bba88.png)

**Comment by stevemessick** [comment]
Here is the documentation for the logcat tool:
https://developer.android.com/studio/debug/am-logcat

What follows is speculation. (I'm not too familiar with Android Studio internals.)

I think the old project doesn't show it because it was created from a template that did not enable logcat. Recent projects do enable it. It appears to be controlled by the ToolWindowManager section of the workspace config file (.idea/workspace.xml). Try comparing the workspace config files of your two projects and changing the one that does not include logcat to include it like the newer one does. You might get it enabled by deleting the workspace config file, but make a backup in case it doesn't work.

**Comment by ascmp** [comment]
Thanks, I did, but no luck. I also grep'd into both the folders, and the only references to logcat are in that one line you point out. I guess it's some higher level that prevents logcat tab to show, like it would be disabled or not supported. Not sure how or why, it was there before and then it disappeared. Any help to get the tab back is appreciated.

**Comment by henkhenken** [comment]
I have the same issue. When I create a project myself (Windows) there is a logcat window in Android Studio. When I open a project from someone else (Mac) the logcat is missing.

**Comment by ascmp** [comment]
If anyone interested, I eventually solved creating a new Flutter project and then overwriting all my 'data' into it, in details folder: android, fonts, images, ios, lib, test, .git, and then the files: .gitignore, README.md, pubspec.yaml . Everything else gets generated from Studio. After this trick, I see the logcat tab again.

**Comment by klaszlo8207** [comment]
My flutter project suddenly doenst find the Logcat tab :D I jut pulled the new source from github, and voila, Logcat tab is missing. And any View/Tool Windows ... LogCat tab.. Any way to show that Logcat again? :D

**Comment by vladaman** [comment]
I am having same issue. When I open project in Android Studio it does not show anything in Logcat window and it says to configure Android SDK.

Then I open another project which is properly configured in new window and the logcat begins to work in both windows. This is clearly misconfiguration in particular project.
I also don't see option in menu "Tools>Flutter>Open Android project" which I think it's related.

**Comment by xiehongxin** [comment]
click “Event Log”

it will show
“”“
2019-10-11
10:10	Frameworks Detected
			Android framework is detected.
			Configure
”“”

click “Configure”， and it will show logcat

**Comment by ride4sun** [comment]
@xiehongxin  It worked like u described but the option in the Event Log did show only when an update in Android was triggered. e.g. a plugin was updated. I still would call this a defect and I am not sure why this was closed. This happen already a few time and I think it should be addressed and not ignored. 

And the statement is wrong (by @stevemessick) that Logcat can be openend when needed. Logcat is not visible in the Tool menu. Please reopen @stevemessick

**Comment by amigax** [comment]
I cant get this to work at all, this is infuriating, need logcat badly.

**Comment by the-kool-sk** [comment]
I too cannot get this working ... anyone can help here.
there is no Event like Android Framework detected it only show : The project 'xyz' is not a Gradle-based project. 
Logcat is the basic need of development. Need to get it working. Also it is not showing emulator in tool window. Need a fix for this.

**Comment by amigax** [comment]
still cant find logcat!!!! WTF is going on guys

**Comment by amigax** [comment]
only solution is to load another instance of AS where it does work...

**Comment by lsuhov** [comment]
Please reopen ticket. Issue is still happening.

**Comment by ullasuk** [comment]
I also had the same issue . Android logcat disappeared suddenly .  What i did to fix it was remove all .idea/ .gradle folders , .iml files and then tried  using Import Project(Gradle ,Eclipse , ADT ) in Android studio startup to load project folder .  Well i also did flutter clean , invalid before importing , not sure if that made any difference
 After going through few configuration steps , i can see logcat again in the flutter project

**Comment by MaximilianFrick** [comment]
Had same issue until i did this:

Go to Project Structure -> Facets -> "+" Android -> Select Project -> voilá :)

**Comment by MisterWeeMan** [comment]
> Had same issue until i did this:
> 
> Go to Project Structure -> Facets -> "+" Android -> Select Project -> voilá :)

This worked for me. Thank you @MaximilianFrick

**Comment by dalriada33** [comment]
I had the same issue on MacOs, and what helped me is: File > Project Settings > Modules > adding new Android module, everything with defaults. Then LogCat showed up.

**Comment by EverGreeff** [comment]
I'm with the same issue, nothing here helped me... i have two flutter projects, only in one of them logcat works fine... in another notebook the logcat works fine with both... idk what to do

**Comment by xiehongxin** [comment]
您好，谢泓鑫已收到您的邮件，查收后会尽快给您答复，辛苦您了，祝好！

**Comment by amigax** [comment]
> 

nothing you can do, keep open the project where logcat works and use that purely for logging, if you have multiscreens its doable. Massive flaw in AS and flutter though.
