### ISSUE TITLE
The Flutter Inspector's "Toggle select widget mode" button is not enabled (Ubuntu 18.04)

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2732]
@ZzZxL commented on [Sun Oct 28 2018](https://github.com/flutter/flutter/issues/23640)

## Steps to Reproduce

The 'Toggle select widget mode' button has been disabled, always disabled, I tried reinstalling the plugin, but the problem still exists, my OS system is Ubuntu 18.04, my Android Studio version is 3.2.1.
## Logs
![button was disabled](https://i.stack.imgur.com/pjAZK.jpg)

## Flutter Doctor
![Flutter Doctor](https://i.stack.imgur.com/c2Wl7.jpg)

**Comment by devoncarew** [comment]
@jacob314, can you triage this?

@ZzZxL; I believe there was a regression recently wrt the service protocol extension the Inspector uses. Can you try updating your version of Flutter and see if that addresses the issue?

**Comment by ZzZxL** [comment]
@devoncarew ;My flutter version is up-to-date, but I tried to change the dev channel to Beta, em... finally it works. Thanks for your prompt and help.

**Comment by zoechi** [comment]
Sounds like this can be closed then.
Thanks for the update @ZzZxL
