### ISSUE TITLE
tracking issue for M30

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2743]
This is a general tracking issue for M30 - feedback on the release and issues we find.

@stevemessick @jwren @pq @terrylucas @jacob314

**Comment by devoncarew** [comment]
I see an issue where the checkboxs in the Inspector (for repaint rainbow and and the perf overlay) self-toggle continuously after you toggle them once. I don't see it all the time, but once it starts happening, they toggle on / off a few times a second - you have to restart IntelliJ to stop it.

**Comment by jacob314** [comment]
Pull requests for M30
https://github.com/flutter/flutter-intellij/pull/2749 <-- turn on track-widget-creation on 0.10.2 and later (includes tip of trunk)
https://github.com/flutter/flutter-intellij/pull/2748 <-- fix performance tip url for opacity animation

https://github.com/flutter/flutter-intellij/pull/2750 <-- fix flickering checkbox bug. Fix is a bit overly paranoid as I couldn't create a true local repro.

**Comment by stevemessick** [comment]
#2745 Add a AS Canary build

**Comment by Christian-AT** [comment]
Issue launching Android Studio from IntelliJ. Gradle not working?

Mac OSX.
IntelliJ IDEA Community 2018.2.4 with Flutter plugin v. 30.0.2.
Android Studio 3.3 Beta version 1 with Flutter plugin v. 30.0.2.
Flutter v. 0.9.4.

To reproduce:
In IntelliJ, create new Flutter project, project type: plugin, "Open Android module in Android Studio".

Result: Android Studio opens as it should, code completion works, but code analysis hangs at "Performing code analysis  No problems found so far", and error highlighting does not appear.
Error logs indicate problems with Gradle.

When a new Flutter project is created in Android Studio, code analysis and error highlighting works fine.

[Exception in Studio core.txt](https://github.com/flutter/flutter-intellij/files/2542426/Exception.in.Studio.core.txt)
[Exception in plugin IntelliLang.txt](https://github.com/flutter/flutter-intellij/files/2542427/Exception.in.plugin.IntelliLang.txt)
[Exception in Studio core 2.txt](https://github.com/flutter/flutter-intellij/files/2542429/Exception.in.Studio.core.2.txt)
[Exception in Studio core 3.txt](https://github.com/flutter/flutter-intellij/files/2542430/Exception.in.Studio.core.3.txt)
