### ISSUE TITLE
Use the refresh button in the inspector doesn't update performance data

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2755]
The refresh button in the inspector currently has no effect on the data generated from the experimental widget rebuild profiler. Its current placement makes it appear to be applicable to all the three areas in the inspector. We need to either make it refresh perf data or change it's location so the user knows it's specific to the widget/render tree. 

![image](https://user-images.githubusercontent.com/348942/47884216-24409500-dded-11e8-9936-1e7390f9a053.png)

**Comment by kenzieschmoll** [comment]
The performance tab was moved to its own tool window, making this issue obsolete.
