### ISSUE TITLE
Problem with code analysis when launching Android Studio from IntelliJ

### ISSUE THREAD

**Issue by Christian-AT** [flutter/flutter-intellij#2756]
Issue launching Android Studio from IntelliJ. Gradle not working?

## Steps to Reproduce

In IntelliJ, create new Flutter project, project type: plugin, "Open Android module in Android Studio".

Result: Android Studio opens as it should, code completion works, but code analysis hangs at "Performing code analysis No problems found so far", and error highlighting does not appear.
Error logs indicate problems with Gradle.

When a new Flutter project is created in Android Studio, code analysis and error highlighting works fine.

## Version info

flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-DK)
    • Flutter version 0.9.4 at /Users/cat/Flutter/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/cat/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.3 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4323.44

[✓] Connected devices (1 available)
    • iPhone X • 06535A6F-7839-404D-968F-1D3C916E2D9B • ios • iOS 11.4 (simulator)
[Exception in Studio core 2.txt](https://github.com/flutter/flutter-intellij/files/2542620/Exception.in.Studio.core.2.txt)

[Exception in Studio core.txt](https://github.com/flutter/flutter-intellij/files/2542617/Exception.in.Studio.core.txt)
[Exception in plugin IntelliLang.txt](https://github.com/flutter/flutter-intellij/files/2542623/Exception.in.plugin.IntelliLang.txt)
[Exception in Studio core 2.txt](https://github.com/flutter/flutter-intellij/files/2542625/Exception.in.Studio.core.2.txt)
[Exception in Studio core 3.txt](https://github.com/flutter/flutter-intellij/files/2542626/Exception.in.Studio.core.3.txt)

**Comment by stevemessick** [comment]
Thanks for the report! I do see some errors when I try this, but I don't have any problems with analysis hanging. Were you prompted to upgrade the Gradle plugin?

At this time, I don't think we need to hold the release for this; I don't think the errors are caused by anything in the Flutter plugin.

**Comment by Christian-AT** [comment]
Indeed I was. The above reported error appeared when I declined the upgrade. When accepting the upgrade, I get an error message stating:
ERROR: Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
Open File

**Comment by stevemessick** [comment]
Thanks for the update.
