### ISSUE TITLE
Fade out rebuild indicators

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2757]
## Steps to Reproduce

The rebuild indicators disappeared too quickly when the rebuild activity was short. You can reproduce what I saw using the default counter app. Here is a screencast: https://www.youtube.com/watch?v=Aqk8GXBXqIc&feature=youtu.be

**Comment by jacob314** [comment]
Fixed by
https://github.com/flutter/flutter-intellij/commit/61ad4879d408182b88cbc76d413b2caef47e0f28
