### ISSUE TITLE
Show the cause of red spikes from the UI graph

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2759]
We had two study participants (P01 and P06) so far expecting to see details about what cause red spikes when examining the UI graph in the Performance tab of the inspector. We should consider supporting this need. 

Specific proposal is TBD, but one idea is to show the rebuild stats table for the current route at the selected timestamp. This will require the IDE to record rebuild stats for hundreds of past frames, and also the ability to pause the timeline when there is an active animation in order to make the selection.

**Comment by kenzieschmoll** [comment]
This issue is and will continue to be addressed in DevTools - see https://github.com/flutter/devtools/issues/476
