### ISSUE TITLE
The UI graph in the inspector can be difficult to read

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2761]
The study participant (P06) today found the UI graph difficult to understand.

![image](https://user-images.githubusercontent.com/348942/47948434-833a0300-deee-11e8-9311-4d1974610236.png)

Based on my observation, there are a few issues:
1. It's unclear whether the Y axis shows FPS or time, since one label was shown on the left end of the chart and the other label was shown  the right end of the graph. In fact, the Y axis here is the time used to render each frame. FPS is actually derived from this data. I'd make FPS look more separate from this chart. 
2. The graph doesn't have a title. For the uninitiated, what is it showing me? 
3. The first FPS probably should be spelled out.
4. The dotted line needs to be annotated.  
5. The tooltip over a bar should be more descriptive. For example, "This frame took 16ms to render. "
6. When there is a red spike, the tooltip should provide additional explanation about why it's red. For example, "This frame took 18.3ms to render, which can cause frame rate to drop below 60 per second."

**Comment by devoncarew** [comment]
Some of this work can be done in the M31 timeframe.
