### ISSUE TITLE
Let users know the inspector needs a running project

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2762]
When the user opens the inspector without a running Flutter project, there is no explanation about why there is nothing displayed. We can add some information in this state such as: "Run your project to use the inspector." We could consider adding more information there, and effectively use that space as an on-boarding UI.

![image](https://user-images.githubusercontent.com/348942/47956260-f0857c80-df5e-11e8-9ccb-a18b06595bf9.png)

This was seen in user studies early on but reported again by a user recently on Twitter.

**Comment by devoncarew** [comment]
We'd had this in earlier versions, but ran into a platform bug (since addressed?) where the content for a newly launched app wasn't auto-selected - even with an app running, the user would see the blank, 'no running apps' message.
