### ISSUE TITLE
Clearly mark experimental features and Flutter version requirements

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2765]
The Rebuild Indicators setting is grayed out when using the latest version of the plugin with the latest version of Flutter in the beta channel. This has caused user confusion (e.g., #2760).

This feature requires a recent commit to Flutter's master branch. We should consider a hotfix to mark it as experimental and state the minimum Flutter version required.

**Comment by jacob314** [comment]
Closed as obsolete.
In the future we should have buttons be hidden instead of just greyed out whenever we have cases where features are available on some versions but not others.
