### ISSUE TITLE
Direct user attention when rebuild indicators are enabled for the first time

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2766]
In a recent UX study, the rebuild indicators failed to draw the participant's attention when he enabled them for the first time. One of the barriers is that those indicators are displayed in the left margin of the code editor, an area far away from the inspector where the setting for rebuild indicators is located. We'll experiment with new UI tweaks to address this issue.

**Comment by jacob314** [comment]
I think the rebuild indicator table that now displays right next to the checkbox with its own animated icons helps solve this issue. Feel free to reactivate if you have other ideas on how we can fix this.
