### ISSUE TITLE
Add ChangJoo-Park to AUTHORS

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2770]
Thanks again for #2768 @ChangJoo-Park!  We'd like to add you to [AUTHORS](https://github.com/flutter/flutter-intellij/blob/master/AUTHORS).  What's a good name / email we can use for attribution?

**Comment by ChangJoo-Park** [comment]
Thanks @pq !
I'll PR to README.md with my email

**Comment by pq** [comment]
Fixed w/ https://github.com/flutter/flutter-intellij/commit/8bdb005e922cc78ba8bb2d30c2caa831600d3e13.
