### ISSUE TITLE
Ineffective icon in the inspector for additional tools

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2771]
Feedback from a study participant today: the second gear icon (circled in red below) in the inspector was not a useful signifier for additional tools. He thought it’s usually for finding settings. Can we use a different icon such as the vertical three dots icon in Chrome, ">>", or a label such as "More tools"? 
 
![image](https://user-images.githubusercontent.com/348942/48036946-41dc6a00-e11f-11e8-8b83-6773ba661cf4.png)

**Comment by pq** [comment]
+1.  The pile-up of gears is confusing.

Happy to take a look at this one.

**Comment by pq** [comment]
Looking at the IntelliJ Icon palette, there is an ellipsis, which might suit?

![image](https://user-images.githubusercontent.com/67586/48070195-2491b500-e18c-11e8-80f1-647111775c0e.png)


/cc @InMatrix

**Comment by jacob314** [comment]
I would worry `...` is too subtle and will be ignored.
Perhaps optimize for discovery over appearance and have it look like a Menu which it what it is.
For example make it look like a menu with a down arrow like the project menu.

Options ▼

<img width="97" alt="screen shot 2018-11-06 at 8 37 34 am" src="https://user-images.githubusercontent.com/1226812/48078948-3b8dd280-e19f-11e8-8830-952ee6229d23.png">

 - U+25BC BLACK DOWN-POINTING TRIANGLE

**Comment by pq** [comment]
Sounds good to me.

I wonder if this is clear enough?

![image](https://user-images.githubusercontent.com/67586/48081300-88c07300-e1a4-11e8-8bcd-ad7b0db48fec.png)

**Comment by pq** [comment]
Or:

![image](https://user-images.githubusercontent.com/67586/48082137-9c6cd900-e1a6-11e8-8403-e02415dd1c17.png)

**Comment by devoncarew** [comment]
The gear icon does blend in a bit, but it's the std menu icon in IntelliJ tool windows. Agree 100% that we need to improve discovery here.

**Comment by pq** [comment]
> The gear icon does blend in a bit, but it's the std menu icon in IntelliJ tool windows.

That's a good point.  That said, what it usually contains is more "window"-specific.  For example:

![image](https://user-images.githubusercontent.com/67586/48084241-089e0b80-e1ac-11e8-9334-5eb76887d224.png)

In this case we're not quite showing a tool window menu.

![image](https://user-images.githubusercontent.com/67586/48084571-efe22580-e1ac-11e8-95ad-41a951f60e7f.png)


Also note that the "real tool window" menu is just above.

**Comment by devoncarew** [comment]
> Also note that the "real tool window" menu is just above.

Ah, good point.

**Comment by pq** [comment]
Here goes:

![image](https://user-images.githubusercontent.com/67586/48087552-73ebdb80-e1b4-11e8-965a-43a035515657.png)
