### ISSUE TITLE
Flicker in logging view when window is narrow

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#2776]
If the log window is too small for the UI the # of items in the log flickers. It would be best to just hide the # of items or show it consistently on top of the other UI when the the log window is too narrow.

![flicker](https://user-images.githubusercontent.com/1226812/48080477-9ecd3400-e1a2-11e8-83c2-234095be8b89.gif)

**Comment by devoncarew** [comment]
Closing as this is related to the experimental logging view.
