### ISSUE TITLE
update new project wizard images

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2784]
In Android Studio, we have ~3 images for the new project wizards:

<img width="727" alt="screen shot 2018-11-07 at 11 04 17 am" src="https://user-images.githubusercontent.com/1269969/48154224-e9bb7a00-e27c-11e8-9cf1-278522ba45ae.png">

we should update the 'plugin' and 'package' one w/ new images; this may just be as simple as using icon badges that are slightly larger. Several possible material design svgs are available here: https://material.io/tools/icons/?style=baseline.

**Comment by stevemessick** [comment]
@devoncarew The module template is still in use.

**Comment by devoncarew** [comment]
Gotcha - thanks; not easy to keep up with the latest here :) We should have an updated image for that as well then.
