### ISSUE TITLE
The UI graph in the inspector shows nothing in profile mode

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2789]
## Steps to Reproduce

Run flutter_gallery in profile mode. 

![image](https://user-images.githubusercontent.com/348942/48168445-1040db80-e2a4-11e8-9d09-f13215f8cfe3.png)

## Version info
[✓] Flutter (Channel master, v0.10.3-pre.134, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.10.3-pre.134 at /Users/taodong/Development/flutter/flutter
    • Framework revision 50fb729609 (3 hours ago), 2018-11-07 12:28:22 -0800
    • Engine revision 2494abdda7
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/taodong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • Nexus 5 • 07e84ccb010aa11a • android-arm • Android 6.0.1 (API 23)

**Comment by stevemessick** [comment]
@jacob314

**Comment by devoncarew** [comment]
@InMatrix, do you remember what conditions you saw this under? I saw this after hitting https://github.com/flutter/flutter-intellij/issues/2774 (an exception while setting up connections to the running app). When I hot restarted the app (I was running in debug mode), I started seeing the FPS info again.

**Comment by InMatrix** [comment]
I don't remember seeing this exception. However, my IDE's connection to the device was more flaky than usual when I was trying to reproduce this bug. I tried a few times before I ran the app in profile mode without losing connection. 

When the app (Flutter Gallery) was in profile mode. I could show the Performance Overlay on the device, but there was no data in the UI graph in the IDE.

**Comment by InMatrix** [comment]
This bug still exists and was ran into by the study participant today.

**Comment by devoncarew** [comment]
Jacob - assigning to you as I believe you're already looking at this (we can re-assign as well if necessary). I _think_ this is the only release blocker.

**Comment by jacob314** [comment]
Fixed
