### ISSUE TITLE
I'm running flutter on android studio and keep getting timeouts at random times when running the app on debug

### ISSUE THREAD

**Issue by SelloN** [flutter/flutter-intellij#2806]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by jwren** [comment]
Please use `flutter doctor` to attach flutter and intellij versions.  How are the timeouts manifesting themselves?  Is there some source code that prompts this?  Does it happen with one or all of the samples?
