### ISSUE TITLE
Support creating flutter samples directly from the Flutter IntelliJ code when browsing Flutter docs

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#2807]
You can create samples from the command line as follows
`flutter create --sample=chip.DeletableChipAttributes.onDeleted`

And see the samples when browsing dart docs.

https://master-docs-flutter-io.firebaseapp.com/flutter/material/Chip/onDeleted.html

It would be great if from IntelliJ you could create a project with a sample with a single click while browsing docs.

**Comment by jacob314** [comment]
@gspencergoog  worked on support for the feature in the Flutter repo that we should leverage to implement IDE support.

An ideal implementation would show a clickable button in the Dart source code that would execute the flutter create and open a new intellij project in a separate window with the result of the create.

**Comment by jacob314** [comment]
@stevemessick who is the expert on the project creation portions of the flutter intellij plugin.

**Comment by stevemessick** [comment]
@jacob314 you give me too much credit :) Pretty sure it was @pq that implemented project creation for the original plugin. I just did the version for Android Studio.
>It would be great if from IntelliJ you could create a project with a sample with a single click while browsing docs.
...
An ideal implementation would show a clickable button in the Dart source code that would execute the flutter create and open a new intellij project in a separate window with the result of the create.

Could you expand on that a bit? Is that new button visible when viewing code in the browser? IntelliJ?

**Comment by jacob314** [comment]
The current support is in the browser. It would be nice to add support to IntelliJ as well.

**Comment by stevemessick** [comment]
See my comments in #2708. I think this would work very well with the (proposed) tutorial.

**Comment by pq** [comment]
Superseded by https://github.com/flutter/flutter-intellij/issues/2968
