### ISSUE TITLE
Change plugin name

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#281]
The plugin should be named "Flutter" instead of "flutter-intellij" (see screen shot). I'm not sure what "N/A" underneath the plugin name refers to but it could probably be improved.

<img width="228" alt="screen shot 2016-10-11 at 2 55 01 pm" src="https://cloud.githubusercontent.com/assets/8518285/19290119/f9bf5ae8-8fc2-11e6-9645-180a5e1d45ec.png">

**Comment by devoncarew** [comment]
Fixed by https://github.com/flutter/flutter-intellij/pull/284 (@pq, I didn't see you grabbed this until I pushed my PR!)

**Comment by pq** [comment]
No worries!

**Comment by pq** [comment]
FWIW, according to Alex, 

> Category is selected in plugin.jetbrains.com site when you add a plugin.

Things should look a little better when we're not host the repo ourselves.
