### ISSUE TITLE
closing the iOS simulator didn't clear out the devices pulldown

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#283]
The iOS simulator (`iPhone SE`) still showed in the pulldown.

**Comment by devoncarew** [comment]
Re-opening the simulator, and exiting it again did clear the pulldown.

**Comment by mit-mit** [comment]
@devoncarew how often do you hit this? I was wondering if we can punt to the 0.2 milestone?

**Comment by pq** [comment]
I'm guessing this is equally true for other disconnected devices?

**Comment by stevemessick** [comment]
I just tried to repro this and failed. Both my Nexus 5X and iOS Simulator were automatically removed from the list when they were no longer available.

**Comment by stevemessick** [comment]
I think we can close this. The daemon management architecture had a huge operational change a few days ago (https://github.com/flutter/flutter-intellij/pull/306). My guess is this problem arose after the device polling daemon got stopped when it should not have, and that is less likely to happen now that every job has its own daemon.

**Comment by pq** [comment]
Awesome!  Let's reopen if we see it again.
