### ISSUE TITLE
identify the urls that we rely on, localize them somehow, and check that they still exist via a travis build job

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2831]
In order to prevent url references in the plugin from going dead, we should identify the urls that we rely on, localize them somehow, and check that they still exist via a travis build job.

**Comment by pq** [comment]
I actually played around with something like this the other day (using `curl` though and now that I think about it, this test might live better in Dart w/ the Dart plugin tests).

@devoncarew assuming you aren't already tackling this, happy to finish my thought...

**Comment by devoncarew** [comment]
> assuming you aren't already tackling this, happy to finish my thought...

No, feel free. I'd tentatively considered using a `grind` task to validate a separate l14n properties file, but lots of ways to approach this.

**Comment by pq** [comment]
Fixed as of #2874
