### ISSUE TITLE
can't fold multi-line parenthesis without new keyword

### ISSUE THREAD

**Issue by orangedays** [flutter/flutter-intellij#2836]
As shown in figure：
<img width="690" alt="gitissue" src="https://user-images.githubusercontent.com/11648898/48698539-4b3afb80-ec22-11e8-880d-2bee1c613ebf.png">
I want to know that there's a way to fold code without new keyword. 
Thanks.

**Comment by pq** [comment]
@alexander-doroshko : I'm guessing the code folding model is handled in the Dart Plugin?  If so, should we re-open and track on your side?

Thanks @orangedays!

**Comment by alexander-doroshko** [comment]
Yes, this is handled in the Dart plugin (thanks to the [PR](https://github.com/JetBrains/intellij-plugins/pull/533) from @jwren).

**Comment by pq** [comment]
Done: https://youtrack.jetbrains.com/issue/WEB-35830.

Thanks!
