### ISSUE TITLE
Support Auto Import like Java/Kotlin in the IDE for flutter apps

### ISSUE THREAD

**Issue by pranayairan** [flutter/flutter-intellij#2860]
Flutter plugin for IntelliJ is limited in auto importing dart files, currently, if you don't specify the imports manually you can't reference that class in your dart file. IDE auto-suggest doesn't work if the import is missing. 

## Steps to Reproduce

- Create a new Dart class in a flutter project - Foo. 
- Open Foo.dart and type Class Foo extends 
- Say this is a flutter widget and you want to extend StatelessWidget. If you do Command Space 2 times ideally IDE should start suggesting you. But this doesn't work. 
- If you manually import the package, then auto suggest will work. 

## Ideal case
- Since I already have all the dependencies in my pubspec.yaml, IntelliJ should auto suggest everything possible. 
- This is the default behavior when you code in java/kotlin. I have never added an import manually while working on android apps. 
- Also, manual import is very crude, if you have a package Foo and then a dart file inside it say bar.dart, you can not just type bar.dart and try to autocomplete at importing. IntelliJ will not recognize that there is a bar.dart in foo package. You need to first autocomplete foo and then it will suggest you other files inside it. It is just like a command line model where you need to know the absolute path for doing anything. 

## Version info

[✓] Flutter (Channel beta, v0.11.8, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.11.8 at /Users/pairan/flutter
    • Framework revision f5b02e3c05 (27 hours ago), 2018-11-20 07:49:29 -0800
    • Engine revision 1baf081343
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/pairan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/pairan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.2

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.6)
    • IntelliJ at /Users/pairan/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.4129.13

[✓] VS Code (version 1.29.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

**Comment by pq** [comment]
Hi @pranayairan.  This feature would have to be implemented in the analysis server (since that's where completion results come from).

Feel free to chime in on the tracking issue there:

https://github.com/dart-lang/sdk/issues/25820

Cheers!
