### ISSUE TITLE
In flutter outline,preview not work.

### ISSUE THREAD

**Issue by yljjiava** [flutter/flutter-intellij#2864]
![1213](https://user-images.githubusercontent.com/10340521/48896030-956de800-ee81-11e8-8fa0-8d2f9e98c910.png)

I have add code to my widget like this:
...
  ReceiverGet();

  factory ReceiverGet.forDesignTime() {
    // TODO: add arguments
    return new ReceiverGet();
  }
...

**Comment by neiljaywarner** [comment]
@pq will live preview leave experimental this quarter and have some documentation/publicity?
I almost forgot about it ...

Thanks

**Comment by pq** [comment]
> will live preview leave experimental this quarter and have some documentation/publicity?

@devoncarew, @scheglov ?

**Comment by devoncarew** [comment]
Good question. We should determine if we're going to push it forward a bit, and graduate it from experimental status, or remove it from the UI.

**Comment by neiljaywarner** [comment]
Hoping it graduates rather than leaves please :)

**Comment by Konrad-Morawski** [comment]
I confirm the problem on Android Studio (3.3.2 / Windows 10).

**Comment by mfarkan** [comment]
im working with 3.3.2 android studio and W10 i have same problem.

**Comment by natanfudge** [comment]
Any update on this?

**Comment by devoncarew** [comment]
This feature has since been removed.
