### ISSUE TITLE
show info about why a user would enable widget rebuild counts

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2868]
From @InMatrix:

Before the rebuild information is enabled, we probably can show a description of the feature in place of the rebuild stats table, assuming that space is empty. We can say something like this: "Widget rebuild information tells you what widgets have been recently rebuilt on your current screen and in the code file you're editing. It also provides you with relevant performance advices based on the behavior of your UI."

**Comment by jacob314** [comment]
Landed this feature.

**Comment by vnagendra** [comment]
Just a small observation
>  It also provides you with relevant performance advices based on the behavior of your UI.

1. *advices* should be replaced with *advice*
2. I don't actually see any advice. I see the table, but there is no advice. So do we need this line at all?

**Comment by jacob314** [comment]
The advice only shows up if a possible performance problem is detected in
the running app.
