### ISSUE TITLE
Ensure inspector/perf windows are WAI for flutter attach use case

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#2873]
As of this [PR](https://github.com/flutter/flutter-intellij/pull/2871), service extensions are added/restored after a Flutter.FirstFrame event has been received.

This may be problematic for the flutter attach use case if we do not get the Flutter.FirstFrame event.

**Comment by jacob314** [comment]
Made this excessively robust with
https://github.com/flutter/flutter-intellij/pull/2920
