### ISSUE TITLE
Show introductory text in the Perf window when there is no active app

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2879]
The new Performance window shows an empty space, when there is no active app. We can add some introductory text there to help the user understand what to expect in the Perf window. I'd suggest the following text:

> ### No active app running
> 
> The Performance window provides a variety of tools and information, including UI rendering time for each frame, memory usage, widget rebuild information, and access points to more advanced performance profiling tools. 

Feel free to edit the text to reflect the features in the actual release.

**Comment by jacob314** [comment]
We could also provide a link to launch the app in profile mode.

**Comment by jacob314** [comment]
Closing as we're now making the perf window show as disabled unless your application is actually running so the perf and inspector windows never really show up in an empty mode for more than a couple frames.
https://github.com/flutter/flutter-intellij/pull/3320
