### ISSUE TITLE
Editor Field doesn't fold the block

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#2894]
## Steps to Reproduce

Select a piece of code

 ```
myDialog.showDialog(context);
 String one = "one";
 String two = "two";
```

Press `cmd + opt + t` and choose 8 to enable folding. Above code is now wrapped as

```
//<editor-fold desc="fold it">
myDialog.showDialog(context);
String one = "one";
String two = "two";
//</editor-fold>

```

Now if you press `option  -` to fold this block, the entire function/method (in which this code is put) gets folded instead of folding this particular code

## Flutter doctor

```
[✓] Flutter (Channel beta, v0.11.9, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

```

**Comment by jacob314** [comment]
This looks like a dart plugin issue.  You can file a corresponding issue for the dart plugin here.
https://youtrack.jetbrains.com/issues/WEB?q=Subsystem:%20Dart

**Comment by dark-chocolate** [comment]
https://youtrack.jetbrains.com/issue/WEB-36087
