### ISSUE TITLE
View>External Documentation takes you to the root of the dart doc 

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#290]
If I select "AppBar" in the code and then click External Documentation from the View menu, the browser will open this URL: https://api.dartlang.org/stable/1.20.0/index.html#id_AppBar

**Comment by pq** [comment]
Thanks!

It looks like the Dart plugin hardcodes the documentation root to point to  `"http://api.dartlang.org/docs/releases/latest/"` as it's base root (`com.jetbrains.lang.dart.ide.documentation.DartDocumentationProvider#constructDocUrl`).

cc @alexander-doroshko for thoughts on how we might make documentation resolution a bit more retargetable.

**Comment by devoncarew** [comment]
Perhaps the dart plugin should complain if the library is not a `dart:` one?

**Comment by pq** [comment]
@alexander-doroshko: any thoughts?

**Comment by alexander-doroshko** [comment]
Should be fixed in dart plugin. related: https://youtrack.jetbrains.com/issue/WEB-18284. //cc @jwren

**Comment by pq** [comment]
Cool!  To be clear though, these are flutter docs.  Is there logic to redirect to `docs.flutter.io`?

**Comment by alexander-doroshko** [comment]
It is `DartDocumentationProvider` class. Either it can be updated or flutter-specific added right to the Flutter plugin. In the latter case need to make sure that they do not fight with each other for the same PsiElement.

**Comment by devoncarew** [comment]
fixed upstream
