### ISSUE TITLE
Idea: Add option for Refactor > Move/Extract Selection to New File

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter-intellij#2906]
Context: When selecting a variable/ widget or anything else eligible, the move option should/ could offer to move the selection to a new file, provided it can be refactored properly. In the photo below, I have a widget that I extracted from the above widget tree successfully, meaning it's refactorable.
I want to now move that widget to its own file while refactoring the code to account for the change.  This can also be an option in the Refactor > Extract > Widget dialog.
<img width="1440" alt="screen shot 2018-11-30 at 12 15 19 pm" src="https://user-images.githubusercontent.com/23037821/49312661-a201ca00-f499-11e8-9985-ad61d9be21b6.png">

**Comment by stevemessick** [comment]
I think this is a dup of #2429. @scheglov do you agree?

**Comment by scheglov** [comment]
Yes, looks like a dup.

**Comment by ThinkDigitalRepair** [comment]
Oops. Sorry :D

**Comment by stevemessick** [comment]
No worries! We appreciate you taking the time to file an issue.
