### ISSUE TITLE
the latest Flutter version v0.11.13  still stop at "Waiting for observatory port to be available" on a Android 22 device.

### ISSUE THREAD

**Issue by Cookies2015** [flutter/flutter-intellij#2908]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
when i run my flutter project on a Android 5.1 device(Coolpad Dashen Note3).it stoped at "Waiting for observatory port to be available..." ,and nothing will happened.
I have kept my flutter version up-to-date, that problem was still .but when i use my another Android O device(Xiaomi 6),there is no such problem.here is the end part of my console log on Android 5.1 device.
>[{"event":"app.progress","params":{"appId":"c1797c57-e175-456e-9c65- 
   22b0f12a3b1a","id":"3","progressId":null,"finished":true}}]
> [   +6 ms] executing: D:\Local\Android\Sdk\platform-tools\adb -s 8676-A01-0x03a14866 shell echo -n 
    b38be0a60bcaeef4ed7b0790f3c04553fd2c0cbf > /data/local/tmp/sky.com.demo.registertool.sha1
>[  +26 ms] 8676 A01 startApp
>[   +1 ms] executing: D:\Local\Android\Sdk\platform-tools\adb -s 8676-A01-0x03a14866 shell am start 
    -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart- 
   profiling true --ez enable-checked-mode true --ez start-paused true 
    com.demo.registertool/com.demo.registertool.MainActivity
>[ +834 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 
    cmp=com.demo.registertool/.MainActivity (has extras) }
>[        ] Waiting for observatory port to be available...
Does anyone knows where the problem is?
## Version info
[√] Flutter (Channel beta, v0.11.13, on Microsoft Windows [Version 6.1.7600], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

**Comment by stevemessick** [comment]
Since the app works with one version of Android and not another, this sounds like a platform issue rather than something in the IDE. You'll probably get better support if you file an issue at github.com/flutter/flutter

/cc @Hixie -- I know issues can easily be moved from flutter to flutter-intellij but don't know how to go the other way.

**Comment by Cookies2015** [comment]
thx

**Comment by Hixie** [comment]
@stevemessick Check for "Transfer this issue" on the right.

**Comment by stevemessick** [comment]
I don't see "Transfer this issue" . @devoncarew do you know who to talk to about setting this up?

In the help docs that feature has a beta label. Do I need to do something to enable it? I couldn't find anything in the docs. It might fall under Github Actions.

**Comment by devoncarew** [comment]
@stevemessick - it perhaps has to do with membership in flutter/flutter; you can also add a comment (`/move to flutter` or `/move to flutter-intellij` to move between repos)
