### ISSUE TITLE
Show widget rebuild info doesn't work with `flutter attach`

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#2918]
I have a user who can only launch his project from the command line. It would be great to allow him to use the widget rebuild profiler in IntelliJ.

## Steps to Reproduce

* Open the Flutter Gallery project
* Click the `Flutter Attach` button
* Run Flutter Gallery in debug mode
* The "Show widget rebuild information" checkbox is grayed out. 

## Version info

[✓] Flutter (Channel master, v1.0.1-pre.1, on Mac OS X 10.14.1 18B75, locale
    en-US)
    • Flutter version 1.0.1-pre.1 at /Users/taodong/Development/flutter/flutter
    • Framework revision a226c0f0d9 (5 days ago), 2018-11-30 16:18:18 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/taodong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • Nexus 5 • 07e84ccb010aa11a • android-arm • Android 6.0.1 (API 23)

**Comment by InMatrix** [comment]
Cc: @jacob314 @kenzieschmoll

**Comment by jacob314** [comment]
Fixed by
https://github.com/flutter/flutter-intellij/pull/2920
