### ISSUE TITLE
Hang when Rerun app

### ISSUE THREAD

**Issue by abarth** [flutter/flutter-intellij#292]
When I click the "Rerun" app (on Mac with iOS simulator), IntelliJ hangs until my app reloads.

**Comment by abarth** [comment]
The stop button has the same hang, which makes me thing its the stop action that's causing the trouble.

**Comment by pq** [comment]
cc @stevemessick

**Comment by stevemessick** [comment]
@abarth Is this after starting the app via Run or Debug?

**Comment by abarth** [comment]
Run.  (Assuming that what happens when I press the green triangle.)

**Comment by stevemessick** [comment]
Yes, it is. FWIW you can see the names of buttons by hovering the mouse pointer over the button for a few seconds.

I can reproduce this problem.

**Comment by pq** [comment]
🤘

**Comment by abarth** [comment]
Thanks!
