### ISSUE TITLE
"wrap with new widget" option disappears from IntelliJ

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter-intellij#2930]
## Steps to Reproduce

Move the cursor to a widget, there's no lightbulb; nothing happens with `Alt+Enter`, and even `Ctrl-Shift-A` can't find any of such action...

## Version info

```
liyuqian@liyuqian:~/flutter/flutter$ flutter doctor -v
[✓] Flutter (Channel doc_url, v1.0.1-pre.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.1-pre.3 at /usr/local/google/home/liyuqian/flutter/flutter
    • Framework revision 667cf69156 (66 minutes ago), 2018-12-07 11:51:17 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/google/home/liyuqian/android/Sdk/
    • Android NDK at /usr/local/google/home/liyuqian/android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/google/home/liyuqian/android/Sdk/
    • Java binary at: /opt/android-studio-with-blaze-3.2/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-with-blaze-3.0
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio-with-blaze-3.2
    • Flutter plugin version 23.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /opt/intellij-ce-2018.1
    • Flutter plugin installed
    • Dart plugin version 181.5656

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /opt/intellij-ce-2018.2
    • Flutter plugin version 31.1.3
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • Moto G 4 • ZY223ZXCJV • android-arm • Android 7.0 (API 24)
```
I'm using IntelliJ 2018.2

**Comment by jacob314** [comment]
@scheglov Any ideas?

**Comment by scheglov** [comment]
Nope, works for me.
Make sure that Analysis Server works, not dead.
Try to `Restart Dart Analysis Server` in the `Dart Analysis` view.
![image](https://user-images.githubusercontent.com/384794/49672524-48147d80-fa20-11e8-8668-c6aa009795d5.png)

**Comment by liyuqian** [comment]
`Dart Analysis` seems to be working fine as I can still see the format and compile error. I also tried `Restart Dart Analysis Server` but the problem is still there.

**Comment by jacob314** [comment]
@liyuqian can you provide some more detailed repro steps?

**Comment by liyuqian** [comment]
I couldn't remember what I did that made them disappear. It happened since several weeks ago. Maybe I can give you the remote desktop access for debugging?

**Comment by liyuqian** [comment]
This seems to be fixed in newer versions.

**Comment by Errichamonda** [comment]
I have the same issue, all menu from Wrap with Widget and switch to relative import are gone. already tried to reinstall android studio but nothing

**Comment by johandanmo** [comment]
I am using Visual Studio Code but could be the same issue. When you click on a widget, a yellow lightbulb should appear to the left. If you click on the lightbulb all options should be there.

**Comment by devsingh1234** [comment]
> I am using Visual Studio Code but could be the same issue. When you click on a widget, a yellow lightbulb should appear to the left. If you click on the lightbulb all options should be there.

was this issue solved as i am also facing the problem

**Comment by devsingh1234** [comment]
> I have the same issue, all menu from Wrap with Widget and switch to relative import are gone. already tried to reinstall android studio but nothing.
> 
> https://i.imgur.com/cqaQsKY.png

was your issue resolved if yes! then please let me know how

**Comment by Errichamonda** [comment]
> > I have the same issue, all menu from Wrap with Widget and switch to relative import are gone. already tried to reinstall android studio but nothing.
> > https://i.imgur.com/cqaQsKY.png
> 
> was your issue resolved if yes! then please let me know how

Yes, somehow I clicked something in the context menu and I disabled Dart quick actions. It's in the Android Studio settings somewhere I don't remember.

**Comment by NSDPK37** [comment]
Go to android studio 
Settings/Intentions/

and make sure

Dart/Quick assist powered by the Dart Analysis Server

is checked


or simply type " Analysis server " in search bar on settings, then click on Intentions And you can find 
Dart/Quick assist powered by the Dart Analysis Server

try This
