### ISSUE TITLE
Terminal window doesn't update

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#2933]
## Steps to Reproduce
Say you have a button with print statement, if you press the button say 10 times within like 2 seconds, then the terminal window shows the print statement just once. 

```
void _handleClick() {
  print("Button got clicked");
}
```

## Flutter doctor
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by jwren** [comment]
Is this still an issue, is there something actionable for the Flutter IJ plugin here?
