### ISSUE TITLE
Cannot un-set Flutter SDK path

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#294]
Initial state: fully configured IntelliJ + Flutter plugin, which can be used to run and debug Flutter apps.

Steps to reproduce: open the preferences and try to change the path to the Flutter SDK to something other than what is set. It won't accept the change. Maybe if I had two Flutter SDK locations I might be able to change from one to the other, but what I want to do is set a bad SDK path.

**Comment by pq** [comment]
Validation forbids you from setting a bad path.  Setting to another valid path works though.  I *think* this is a feature not a bug?

If you're just trying to test a clean install, follow these instructions?

https://github.com/flutter/flutter-intellij/wiki/Development

**Comment by stevemessick** [comment]
I think I ought to be able to tell it where I plan to install the SDK, even before having done so. So that makes this feature a bug for me. I could get into an equivalent state by changing the name of one of the directories in the path, so it is not like prohibiting the change is preventing any problems.

**Comment by pq** [comment]
Hmmmm.  I think this complicates things a bit since we'd need to listen for external events in order to know when the set value becomes valid and then set the SDK path, start the daemon, etc.

For perspective, I don't think this kind of validation is unusual either.  For example, you can't point to a bogus Java SDK location either.

<img width="525" alt="screen shot 2016-10-13 at 9 40 17 am" src="https://cloud.githubusercontent.com/assets/67586/19358036/161521f2-9129-11e6-9454-35b04f084906.png">

**Comment by devoncarew** [comment]
I think being able to remove the setting makes sense - we just need to broaden our definition of a 'valid sdk path' a bit, from valid flutter sdk's, and no sdk path.

**Comment by pq** [comment]
> I think being able to remove the setting makes sense

I almost agree but that doesn't address @stevemessick 's concern which I think is around the UX idea of unnecessary "premature commitment".

Besides testing, what's the motivation for un-setting a Flutter SDK?

**Comment by pq** [comment]
@alexander-doroshko : I'm guessing this will not be possible with your refactoring?

**Comment by alexander-doroshko** [comment]
Yes, at the moment you can't unset the Flutter SDK. The same as you can't unset the Dart SDK. You can only disable Dart support.
When per-module SDK settings are done this problem (if it is a problem at all) will be addressed.

**Comment by stevemessick** [comment]
This may just be a philosophy-of-life question. Back in the day, you had the authoritarian attitude of Microsoft versus the libertarian attitude of Unix (and Apple was just a veneer over Unix, pre-iPhone). I never liked the MS way of doing things. And that's probably what the problem is here: I don't want to be told not to do something just because it is hard to implement. But that's just me...

**Comment by alexander-doroshko** [comment]
I think similar.
With SDK per module configuration I'll have to implement SDK management, so you'll get full control on SDKs adding, removing and renaming.
