### ISSUE TITLE
Bug: Widgets code actions are available on fields too!

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2942]
@rrousselGit commented on [Wed Oct 17 2018](https://github.com/flutter/flutter/issues/23213)

Consider the following code:

```dart
class Foo extends StatelessWidget {
  final Widget child;

}
```

When focusing `child`  and attempting to use refactoring tools, the IDE will suggest the usual widget refactoring stuff:

![image](https://user-images.githubusercontent.com/20165741/47100047-e06b5e80-d236-11e8-9876-eb293600352d.png)

This obviously doesn't make sense. And using them leads to an invalid code.

---

@zoechi commented on [Wed Oct 17 2018](https://github.com/flutter/flutter/issues/23213#issuecomment-430726860)

Please add the output of `flutter doctor -v`.

---

@zoechi commented on [Wed Oct 17 2018](https://github.com/flutter/flutter/issues/23213#issuecomment-430755434)

a bit outdated, but I wouldn't expect changes in this area since then.

---

@rrousselGit commented on [Wed Oct 17 2018](https://github.com/flutter/flutter/issues/23213#issuecomment-430761233)

Ah indeed, I was on my fork.

I upgraded to latest on master. Still happens

```
[✓] Flutter (Channel master, v0.10.1-pre.72, on Mac OS X 10.13.6 17G65, locale en-FR)
    • Flutter version 0.10.1-pre.72 at /Users/remirousselet/dev/libs/flutter
    • Framework revision b95b67a66b (4 hours ago), 2018-10-17 23:25:46 +0800
    • Engine revision 08272ee6aa
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/remirousselet/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.
```

**Comment by devoncarew** [comment]
cc @scheglov

**Comment by scheglov** [comment]
I cannot reproduce this on bleeding edge of Analysis Server.
Looks like duplicate.
https://github.com/flutter/flutter-intellij/issues/2714
