### ISSUE TITLE
consider hiding the logging details pane behind a setting

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2947]
With the work for structured logging events somewhat on hold, we might consider hiding the details pane behind a preference.  Alternatively, we might think about making it appear conditionally (e.g., only  if there are logged events with details?)

![image](https://user-images.githubusercontent.com/67586/49828297-5f18df80-fd40-11e8-9de6-c1c712d5ce27.png)

**Comment by InMatrix** [comment]
The logging details pane probably can be hidden by default and brought up on demand, based on user input (e.g., clicking a link in the main error display) or specific elements in the error.
