### ISSUE TITLE
No devices in Flutter Project

### ISSUE THREAD

**Issue by AugustoMarcelo** [flutter/flutter-intellij#2952]
Whenever I open a flutter project in android studio no device is found
I ran the Flutter doctor -v command on the command line and the following messages appeared:

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [versÃ£o 10.0.17763.134], locale pt-BR)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (12 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

-CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 não é um aplicativo Win32 válido.

  Command: C:\Users\Marcelo Augusto\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l
0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:488:7)
1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:633:18)
2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:326:48)
5      runSync (package:flutter_tools/src/base/process.dart:300:10)
6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:542:12)
7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:55:53)
<asynchronous suspension>
8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:166:52)
<asynchronous suspension>
9      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:94:46)
<asynchronous suspension>
10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:687:54)
<asynchronous suspension>
11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
13     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
16     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
19     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
20     _rootRunUnary (dart:async/zone.dart:1132:38)
21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
22     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
24     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
25     Future._complete (dart:async/future_impl.dart:476:7)
26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
27     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
28     _rootRun (dart:async/zone.dart:1124:13)
29     _CustomZone.run (dart:async/zone.dart:1021:19)
30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
33     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
34     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by AugustoMarcelo** [comment]
Guys, I solved the problem. I noticed that the flutter was fetching the adb from another directory, one that contained the user name with spacing.
I used the flutter config command --android-sdk path / to / skd / and finally the devices were recognized.

**Comment by devoncarew** [comment]
> I used the flutter config command --android-sdk path / to / skd / and finally the devices were recognized.

Thanks for the report, and good to hear that things are resolved :)
