### ISSUE TITLE
Cannot Toggle "Flutter Outline" nor "Flutter Inspector"

### ISSUE THREAD

**Issue by RedChallenger4** [flutter/flutter-intellij#2954]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
1) Downloaded Flutter 1.0
2) Created a new Flutter project in Intellij-IDEA, Community Version 2018.3.1. 
3) Ran (already given) sample code on an Android phone
4) When it was still running, I tried clicking "Flutter Outline" and "Flutter Inspector." But, they don't open a taskbar window.

_Please tell us what you were doing and what went wrong_
I was trying to toggle "Flutter Outline" and "Flutter Inspector." But, they remain unresponsive.

## Version info

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.0.0 at /Library/Flutter/flutter
    • Framework revision 5391447fae (13 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/macpro/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4588.61

[✓] Connected device (1 available)
    • Moto G 4 • ZY223C34MB • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by devoncarew** [comment]
@RedChallenger4, thanks for the report! Do you still see this after restarting the IDE?

And if so, are there any exceptions in the IntelliJ logs? You can see the log from `Help > Show log in Finder`.

**Comment by devoncarew** [comment]
Ah, good to hear!
