### ISSUE TITLE
Support for Fuchsia devices

### ISSUE THREAD

**Issue by keertip** [flutter/flutter-intellij#2959]
The Flutter plugin should support run/attach for Fuchsia devices. Even though flutter_tools says device attached, the plugin reports no devices connected and the attach icon is disabled.

**Comment by devoncarew** [comment]
Checking into the code, I see few assumptions about the text name of the device type. Perhaps the daemon mode device reporting doesn't work for fuchsia devices? I'll check the flutter_tools code.

**Comment by devoncarew** [comment]
cc @jonahwilliams

**Comment by devoncarew** [comment]
We'll need to add support for fuchsia device discovery into the daemon mode: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/daemon.dart#L570

**Comment by jonahwilliams** [comment]
On it

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/pull/25344

**Comment by devoncarew** [comment]
I believe this is done now.
