### ISSUE TITLE
flutter plugin won't be installed

### ISSUE THREAD

**Issue by yossefEl** [flutter/flutter-intellij#2966]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by pq** [comment]
Thanks for the report @yossefEl.

Could you run flutter doctor (`flutter doctor -v` in a terminal) and paste the output here?

**Comment by yossefEl** [comment]
thank you very much brother @pq, i had this problem yesterday. it is working now.
