### ISSUE TITLE
Switch statement for enum should create all the cases

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#2969]
## Steps to Reproduce
```
enum Phone {
  samsung,
  google,
}

Phone phone = Phone.samsung;

void method() {
 switch(phone) {
   
 }
}
```
 
When you hover over to the `switch(phone)`, it will tell you to implement all the cases for `Phone` enum, now there should be a way/shortcut that will let IDE to create all the cases in 1 click. 

### Screenshot
<img width="490" alt="screenshot 2018-12-17 at 10 18 22 pm" src="https://user-images.githubusercontent.com/40364434/50101856-affd6c00-0249-11e9-9e57-6fc617a786f7.png">

### Version info
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by alexander-doroshko** [comment]
Looks like https://github.com/dart-lang/sdk/issues/28154

**Comment by devoncarew** [comment]
@dark-chocolate thanks for the report! I think this is a dup of the above sdk issue.

**Comment by dark-chocolate** [comment]
@devoncarew Yes, it is a duplicate. Actually, when I searched I didn't find that issue. So, I created it by my own. Is there any to delete my issue on Github? I can't find a way to do that. I am new here so any advice would be appreciated. Thanks

**Comment by devoncarew** [comment]
No way to delete an issue, but having it closed is enough. It'll show up in searches, and makes a reference to the open issue.
