### ISSUE TITLE
Issue with wrapping with new widget if selected widget is being assigned

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter-intellij#2972]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

Trying to wrap a widget that's being assigned to a variable using the Flutter plugin.
## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
$ flutter doctor -v
[✓] Flutter (Channel master, v1.1.2-pre.45, on Mac OS X 10.14.2 18C54, locale
    en-US)
    • Flutter version 1.1.2-pre.45 at /Users/thinkdigital/development/flutter
    • Framework revision 632e21b40b (7 hours ago), 2018-12-17 12:38:14 -0800
    • Engine revision 5af435098d
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Users/thinkdigital/Applications/JetBrains Toolbox/IntelliJ
      IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPad Pro (9.7-inch)       • 06D0CF21-E801-4795-A744-5A3120142E16 • ios
      • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.

**Comment by jwren** [comment]
Can you please include a before and after widget of the widget wrapping?

**Comment by ThinkDigitalRepair** [comment]
I'm sorry, I didn't notice the notification. I'll paste an example

**Comment by ThinkDigitalRepair** [comment]
for example, I had some code that said,

```dart
if (role.contains(“teacher”))
    roleBasedHomeWidget = Container();
```

when trying to wrap the `Container` in a new widget, it wrapped the whole line instead.
I’m not by my computer to post a photo/ video of it

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/105180

**Comment by ThinkDigitalSoftware** [comment]
Thank you, @scheglov
