### ISSUE TITLE
Support for creating sample content in the New Project Wizard (AS)

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#2975]
Sub-task from #2968 and the corollary in Android Studio to IDEA support in #2974.

The Android Studio project creation flow provides a few places to add hooks.

Candidate places:

## 1. project configuration (first page)

<img width="912" alt="screen shot 2018-12-18 at 5 38 34 am" src="https://user-images.githubusercontent.com/67586/50157820-40a66d00-0287-11e9-9f22-194dd66b1150.png">

## 2. project configuration (second page)

<img width="912" alt="screen shot 2018-12-18 at 5 38 46 am" src="https://user-images.githubusercontent.com/67586/50157827-43a15d80-0287-11e9-8469-ef9eba033f5c.png">

@stevemessick: thoughts?

**Comment by stevemessick** [comment]
Do you want to allow for samples using the package template? That form of the wizard currently has only one page.

**Comment by pq** [comment]
> Do you want to allow for samples using the package template? 

I think we want to limit this to applications.  (At least to start?)

**Comment by stevemessick** [comment]
That would cover the greatest number of users, I suppose. But I'd prefer to see samples for all project types, especially plugins. The thing is, I don't know what the future of Module and Application are, in light of add2app. One of them may be going away.

**Comment by pq** [comment]
If we did support sample templates in package projects, would the content need to be any different?  (I guess I imagined it might but maybe that was over-thinking.)

**Comment by stevemessick** [comment]
I just assumed all project types would have different samples. I have not
thought about it in detail.

**Comment by pq** [comment]
I imagined that too.

/cc @gspencergoog who surely knows more...

**Comment by gspencergoog** [comment]
There are currently only samples for applications.  The Module type has been merged into the app type anyhow, for add2app.  An app is now basically a module that has has its hidden directories instantiated.

We could make samples for plugins, but there's a bit of work we'd have to do to make new templates for them.

**Comment by terrylucas** [comment]
Another user #3131 suggested a more useful sample, instead of our default calculator class, would be a subclass widget or some other fluttery thing - seem more useful than Calculator.

**Comment by stevemessick** [comment]
Fixed with https://github.com/flutter/flutter-intellij/pull/3134
