### ISSUE TITLE
Add device name to debugger tab

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#298]
When debugging an app on multiple devices simultaneously there is no way to tell which debugger tab controls which device, other than running the app and observing state changes on the devices. The current name of the tab is just the name of the app; the name of the device it is running on should be added to the tab name -- or perhaps the device name should replace the app name since in this UI the app name will always be the same. In the screen shot there are two tabs named `myapp` and no indication which runs on the currently-attached Nexus 5X or the iOS Simulator.

<img width="476" alt="screen shot 2016-10-13 at 1 04 30 pm" src="https://cloud.githubusercontent.com/assets/8518285/19365033/a2ac4be2-9145-11e6-896f-452336d8de45.png">

**Comment by devoncarew** [comment]
Closing as this is not a common use case; we can revisit as necessary.
