### ISSUE TITLE
Add a tooltip suggesting to add trailing commas

### ISSUE THREAD

**Issue by galeyang** [flutter/flutter-intellij#2980]
From a recent UX study, one participant was frustrated by the reformat feature, because it didn’t always work with her programming style, i.e., not using trailing commas. 
![image](https://user-images.githubusercontent.com/5102864/50189930-28147200-02dc-11e9-9aae-4897d68f6188.png)

New Flutter user may not know --

> [optional trailing commas](https://flutter.io/docs/development/tools/formatting#using-trailing-commas) help the automatic formatter to insert an appropriate amount of line breaks for Flutter-style code. 

Can we add a tooltip suggesting to add trailing commas?

cc: @jayoung-lee @InMatrix

**Comment by pq** [comment]
This is a great idea.  If we agree that this should be enforced for Flutter projects generally, I'd say we implement a [lint rule](http://dart-lang.github.io/linter/lints/) and add it to the template for new Flutter projects.  If we get even more ambitious we could implement a quick fix in the analysis server which adds the trailing commas on demand too. 👍

**Comment by pq** [comment]
I opened a lint request https://github.com/dart-lang/linter/issues/1338; feedback there welcome! 👍

**Comment by InMatrix** [comment]
As a simpler alternative to lint rules, can we consider showing a tip in a dialog window when the user tried to format code that misses trailing commas? We could potentially reuse the Tip of the Day dialog in IntelliJ. WDYT? @pq

**Comment by jwren** [comment]
Closing this issue, https://github.com/dart-lang/linter/issues/1338 is closed.
