### ISSUE TITLE
Infra - Unit tests

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#30]
Build out the framework for unit testing with IntelliJ.

**Comment by devoncarew** [comment]
I think this is done?

**Comment by stevemessick** [comment]
I'd like to see a few more tests running. There may be performance problems
or other issues due to the test set up procedure.

**Comment by pq** [comment]
@stevemessick : I'm happy to help wrap this up. 

> I'd like to see a few more tests running. There may be performance problems
or other issues due to the test set up procedure.

Can you elaborate?  Or maybe give a sense for what would give you confidence?

**Comment by pq** [comment]
@stevemessick could elaborate on what you had in mind here?

**Comment by mit-mit** [comment]
Closing in favor of potentially creating more specific tracking items as needed
