### ISSUE TITLE
Limit uses of `LOG.error|warning|info`

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#300]
In summary, `LOG.error` should be reserved for failed assertions and `warning` and `info` only sparingly since all they write goes into the `.log`.  For debugging output, we should use `debug` which only produces output when debugging is explicitly turned on.

**Comment by pq** [comment]
I took a quick pass over the SDK and module config bits (https://github.com/flutter/flutter-intellij/pull/304). 

@stevemessick would you mind taking a crack at logging in debugging?

**Comment by stevemessick** [comment]
I didn't see any problems.
