### ISSUE TITLE
Why is there no Console Tab in Run?

### ISSUE THREAD

**Issue by xjf1128** [flutter/flutter-intellij#3004]
Why is there no Console Tab in Run?It can still be shown the other day. I've tried to restart the computer.
Android Studio: 3.2.1
<img width="1228" alt="321" src="https://user-images.githubusercontent.com/17099561/50547478-213f1500-0c75-11e9-85f4-db110b28c588.png">

**Comment by xjf1128** [comment]
It can be compiled and installed, but there is no console information.And I run the Andorid native project to display the running console information.

**Comment by xjf1128** [comment]
It should be like this.
<img width="801" alt="123" src="https://user-images.githubusercontent.com/17099561/50547517-a7f3f200-0c75-11e9-844b-bc8a331724b5.png">

**Comment by xjf1128** [comment]
The problem has been solved：
1. Focus "Run" tab (click on tab header, not on its body)
2. Ctrl+Shift+A, find and click "Restore Layout"

**Comment by valerybodak** [comment]
> 1. Focus "Run" tab (click on tab header, not on its body)
> 2. Ctrl+Shift+A, find and click "Restore Layout"

Does not work for me. Android Studio 3.4.1

**Comment by xjf1128** [comment]
> > 1. 聚焦“运行”选项卡（单击选项卡标题，而不是其标题）
> > 2. 按Ctrl + Shift + A，找到并单击“恢复布局”
> 
> 对我不起作用。Android Studio 3.4.1

<img width="716" alt="11" src="https://user-images.githubusercontent.com/17099561/58694610-fb55a200-83c5-11e9-92ab-ab45324f8832.png">

**Comment by valerybodak** [comment]
> > > 1. 聚焦“运行”选项卡（单击选项卡标题，而不是其标题）
> > > 2. 按Ctrl + Shift + A，找到并单击“恢复布局”
> > 
> > 
> > 对我不起作用。Android Studio 3.4.1
> 
> <img alt="11" width="716" src="https://user-images.githubusercontent.com/17099561/58694610-fb55a200-83c5-11e9-92ab-ab45324f8832.png">

It works. Thank you!
