### ISSUE TITLE
Having an Http monitoring panel 

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3035]
Would be awesome to have a panel to see http(s) requests directly from IDE :) 
I didn't find any issue about this but remember reading something about this somewhere ^^

The idea would be to have something similar of what we have in the web developer tools
<img width="1198" alt="capture d ecran 2019-01-03 a 11 49 10" src="https://user-images.githubusercontent.com/2970449/50634069-bbd97580-0f4d-11e9-9601-8a91832277ac.png">
<img width="1678" alt="capture d ecran 2019-01-03 a 11 49 52" src="https://user-images.githubusercontent.com/2970449/50634071-bda33900-0f4d-11e9-87a0-903152a4a140.png">

So a list of calls with possibility to see the content in plain text (or if json in parsed format with collapse/expand), the request and the response. And why not cookies also. 

And if we want cherry on top of the cake I'll add the possibility to delay an http response to see how our app handle long requests, possibility to force an error, or even the possibility to edit request and response on the fly ^^

**Comment by jaumard** [comment]
@pq is there any docs on how this plugin works? I might be interested in working on this :) but for example I don't know how retrieve http info from the app. So any info on how the dialog between plugin and the app might be good to know to work on this :)

**Comment by jaumard** [comment]
Hey @pq is this something similar to create test and will need dart analyser update to be able to retrieve http calls data?

**Comment by pq** [comment]
I don't think so.  It *may* require (or at least benefit) from Flutter framework hooks though...

**Comment by jaumard** [comment]
Hey @pq ! So ok my idea:

It will not involve any changes on Flutter side.
Create a wrapper around IOClient, this wrapper will basically use the IDE as a proxy and send http request to the IDE plugin. Then the plugin can execute request and show data but also interact with the requests (delay, change requests/responses).

Another solution to at least quickly having http reporting is that this IOClient wrapping just log all http information in a specific format, then the plugin can extract them to just show them under `Http monitoring` tab.

The developers would have to use this IOClient wrapper to see http reporting into their IDE. It could be as easy as `final ioClient = isProductionEnv ? IOClient() : ProxyIdeIoClient()`.
What do you think ?

**Comment by pq** [comment]
👍 

We actually played with something something similar (in https://github.com/pq/logs) and you're right, for http strictly, no framework changes are needed.  Maybe you can use that as a jumping off point?

If you're curious, here's an example of how you'd use it.

1. start w/ some source that makes an http call (I used https://flutter.io/docs/cookbook/networking/fetch-data#complete-example)

2. add a new package dependency on `logs`:

```
  logs:
    git: https://github.com/pq/logs.git
```

3. call the enable logging function in main:

```dart
  enableLogging('http');
```

4. run in debug mode

Doing that you should see some basic http logging in the console:

![image](https://user-images.githubusercontent.com/67586/51074125-15b5fb80-1630-11e9-9181-9729b95b1428.png)

Here's the full source of the associated `main.dart` if you want to repro exactly:

```dart
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:logs/logs.dart';

Future<Post> fetchPost() async {
  final response =
  await http.get('https://jsonplaceholder.typicode.com/posts/1');

  if (response.statusCode == 200) {
    // If the call to the server was successful, parse the JSON
    return Post.fromJson(json.decode(response.body));
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load post');
  }
}

class Post {
  final int userId;
  final int id;
  final String title;
  final String body;

  Post({this.userId, this.id, this.title, this.body});

  factory Post.fromJson(Map<String, dynamic> json) {
    return Post(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
      body: json['body'],
    );
  }
}

void main() {
  enableLogging('http');
  runApp(MyApp(post: fetchPost()));
}

class MyApp extends StatelessWidget {
  final Future<Post> post;

  MyApp({Key key, this.post}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Fetch Data Example'),
        ),
        body: Center(
          child: FutureBuilder<Post>(
            future: post,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return Text(snapshot.data.title);
              } else if (snapshot.hasError) {
                return Text("${snapshot.error}");
              }

              // By default, show a loading spinner
              return CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }
}
```

Feedback welcome!

**Comment by pq** [comment]
> One thing that is not clear yet on my mind is how the app and the IDE can exchange the data... If we use logs as you did then no possibility to delay or change request/response later...

Could you elaborate on this?  I think I know what you have in mind but if you described a scenario that'd be useful to make sure we're on the same page.

Thanks!

**Comment by jaumard** [comment]
Sure !!! So some use cases would be: 

Playing with my app and see on http monitoring panel that one request is giving me a 400, click right on it and select "Breakpoint request", then play with the app to retry the call, IDE is intercepting the request and show me a popup with the request data, I'm changing the header `Content-type` because it was not correct and click "ok", request is done and successful this time. I'm happy and can change the code accordingly to set the correct header.

I have same case for "Breakpoint response" that will show a popup for me to edit the response before it goes to the app. 

Another case is just to "add request delay" like this I can add 1 minutes before the response is sent to the app, like this I can test the case where network is really low and see how it's handled on my app. 

Clear enough @pq  ?

**Comment by jaumard** [comment]
I just tried your http logs with https://github.com/pq/logs ! Works great ! I personally miss the data sent/received during POST/PUT....

**Comment by devoncarew** [comment]
DevTools is getting a networking page.
