### ISSUE TITLE
logging view not respecting `package:logging` levels

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3036]
Moving from https://github.com/flutter/flutter-intellij/issues/2200#issuecomment-451169194:

> @pq following our discussion here #3034 (comment)

>> that corresponds to levels as defined by messages reported using the Dart package:logging

> Is the current version also reporting message uses by package:logging because I'm using it and it give me the previous screenshot (it's doesn't report Fine but info).

>> Could you elaborate on this? It would be great to know what we could do to line this view up with your imagined use cases. What does the simple text view allow you to do that this view doesn't? Thanks in advance!

>I mean for now the console give me:
>timestamp, info, flutter.tools, [11:11:11 FINE CartRepository] my custom log...
>But what I really want is:
>timestamp, fine, CartRepository, my custom log...

>So maybe I'm not using package:logging like I should... but from what I understand it should be the case right ? That why I'm saying that the text console is better because with this one it doesn't offer me anything more... is there something special to do with the logger ?

/cc @jaumard

**Comment by pq** [comment]
@jaumard: are you using `'dart:developer'` to log entries?

**Comment by jaumard** [comment]
No I don't... just `debugPrint` so I guess that's why I don't get good results 
But it is mention somewhere that I should use this one ? Because on flutter docs (https://flutter.io/docs/testing/debugging#print-and-debugprint-with-flutter-logs) or on `package:logging` readme it's never mention this one. We might want to have this information available somewhere. Or I just miss the info :D 

I'll try to use it and get back to you about this :)

**Comment by jaumard** [comment]
No problem at all :) I was just wondering how people could get pretty logs lol 

Ok now we're talking ! Perfect :) that was the missing part ^^

<img width="1296" alt="capture d ecran 2019-01-03 a 16 29 58" src="https://user-images.githubusercontent.com/2970449/50645865-decb5000-0f74-11e9-8d06-217850e1cac3.png">

PS: just miss a selector to select from which level I want to see ^^

**Comment by pq** [comment]
Great.  Though the clipping is bad (https://github.com/flutter/flutter-intellij/issues/3037 to track).   I've opened another issue to create better docs (#3038) and will close this one for now but please to re-open or create a new issue with any other feedback.  It's still in active development so input now is especially welcome!
