### ISSUE TITLE
make logging view level column size dynamically (or resizable)

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3037]
See for example the clipping in https://github.com/flutter/flutter-intellij/issues/3036#issuecomment-451178148:

![image](https://user-images.githubusercontent.com/67586/50646407-ccc4bf80-0f2a-11e9-9915-c0cfe0438024.png)

**Comment by jaumard** [comment]
Also change the order might be interesting :) I don't know why you didn't put sequence number as first row ^^ but feels weird :p if we can change the order no more problem ^^ low priority but can be useful
