### ISSUE TITLE
document how to use 'dart:developer' for logging

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3038]
As observed by @jaumard in https://github.com/flutter/flutter-intellij/issues/3036, using `debugPrint ` as recommended in https://flutter.io/docs/testing/debugging#print-and-debugprint-with-flutter-logs doesn't yield the best results in the logging view.  We should (minimally) have a doc capturing best practices.

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?

**Comment by pq** [comment]
You might find https://flutter.github.io/devtools/logging.html useful?

**Comment by devoncarew** [comment]
Those docs have now moved here: https://flutter.dev/docs/development/tools/devtools/logging.
