### ISSUE TITLE
NPE from WidgetPerfSummaryView.<init>(WidgetPerfSummaryView.java:48)

### ISSUE THREAD

**Issue by zancheng** [flutter/flutter-intellij#3041]
---

## What happened

(please describe what you were doing when this exception occurred)
Run main.dart

## Version information

IntelliJ IDEA `2018.3.2` • Flutter plugin `io.flutter 31.3.4` • Dart plugin `183.4886.3`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.view.WidgetPerfSummaryView.<init>(WidgetPerfSummaryView.java:48)
	at io.flutter.view.InspectorPerfTab.buildUI(InspectorPerfTab.java:252)
	at io.flutter.view.InspectorPerfTab.<init>(InspectorPerfTab.java:82)
	at io.flutter.view.FlutterPerfView.addPerformanceTab(FlutterPerfView.java:217)
	at io.flutter.view.FlutterPerfView.addPerformanceViewContent(FlutterPerfView.java:174)
	at io.flutter.view.FlutterPerfView.debugActive(FlutterPerfView.java:101)
	at io.flutter.view.FlutterPerfViewFactory.lambda$initPerfView$1(FlutterPerfViewFactory.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by kangwang1988** [comment]
Paster full log for `flutter -v doctor -v`.
Besides, the reproduce procedure.
@zancheng

**Comment by zancheng** [comment]
Duplicate of #

> 贴纸完整日志`flutter -v doctor -v`。
> 此外，重现程序。

`
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.319], locale zh-CN)
    • Flutter version 1.0.0 at E:\flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 14)
    • IntelliJ at D:\新建文件夹\IntelliJ IDEA 14.1.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 141.1586
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at E:\soft\IntelliJ IDEA 2018.3.1
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[√] Connected device (1 available)
    • NX512J • 6672e01c • android-arm64 • Android 5.1.1 (API 22)

! Doctor found issues in 2 categories.

F:\2018\flutter\myflutter>flutter -v doctor -v
[  +42 ms] executing: [E:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +118 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[        ] executing: [E:\flutter\] git rev-parse --abbrev-ref HEAD
[  +79 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [E:\flutter\] git ls-remote --get-url origin
[  +74 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [E:\flutter\] git log -n 1 --pretty=format:%H
[  +77 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [E:\flutter\] git log -n 1 --pretty=format:%ar
[  +76 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 weeks ago
[        ] executing: [E:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +79 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[+1032 ms] java -version
[ +258 ms] [√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.319], locale zh-CN)
[   +9 ms]     • Flutter version 1.0.0 at E:\flutter
[        ]     • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
[        ]     • Engine revision 7375a0f414
[        ]     • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
-[   +3 ms] executing: D:\Android\android-sdk\platform-tools\adb devices -l
[  +81 ms] Exit code 0 from: D:\Android\android-sdk\platform-tools\adb devices -l
[        ] List of devices attached
           6672e01c               device product:NX512J model:NX512J device:NX512J transport_id:1
[  +18 ms] D:\Android\android-sdk\platform-tools\adb -s 6672e01c shell getprop                                  /
[ +219 ms] ro.hardware = qcom
[  +42 ms] executing: D:\Android\android-sdk\tools\bin\sdkmanager --licenses                                    [
+2924 ms] [!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[        ]     • Android SDK at D:\Android\android-sdk
[   +3 ms]     • Android NDK location not configured (optional; useful for native profiling support)
[   +1 ms]     • Platform android-28, build-tools 28.0.3
[   +1 ms]     • ANDROID_HOME = D:\Android\android-sdk
[   +1 ms]     • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[        ]     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[   +2 ms] [√] Android Studio (version 3.2)
[        ]     • Android Studio at D:\Program Files\Android\Android Studio
[        ]     • Flutter plugin version 31.3.1
[        ]     • Dart plugin version 181.5656
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[        ] [!] IntelliJ IDEA Ultimate Edition (version 14)
[        ]     • IntelliJ at D:\新建文件夹\IntelliJ IDEA 14.1.3
[        ]     X Flutter plugin not installed; this adds Flutter specific functionality.
[   +1 ms]     • Dart plugin version 141.1586
[        ]     • For information about installing plugins, see
[        ]       https://flutter.io/intellij-setup/#installing-the-plugins
[        ]     X This install is older than the minimum recommended version of 2017.1.0.
[   +3 ms] [√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[        ]     • IntelliJ at E:\soft\IntelliJ IDEA 2018.3.1
[        ]     • Flutter plugin version 31.3.4
[        ]     • Dart plugin version 183.4886.3
[        ] [√] Connected device (1 available)
[        ]     • NX512J • 6672e01c • android-arm64 • Android 5.1.1 (API 22)
[        ] ! Doctor found issues in 2 categories.
[  +13 ms] "flutter doctor" took 4,487ms.

`

**Comment by zancheng** [comment]
@kangwang1988  看一下

**Comment by jacob314** [comment]
This was fixed by
https://github.com/flutter/flutter-intellij/pull/3182
