### ISSUE TITLE
improve discoverability of flutter attach

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter-intellij#3044]
The Dart plugin can connect to remote debug sessions ("Dart Remote Debug" run configuration).

But I can't find a "Flutter Remote Debug" run configuration that calls ```flutter attach``` to connect to flutter processes that were not started in IntelliJ.

This would make google/flutter-desktop-embedding a viable alternative to debugging in a simulator (on macOS at least) and a Flutter Remote Debug configuration is the only missing piece for making that possible.

**Comment by devoncarew** [comment]
There is 'flutter attach' toolbar button, and a menu item on the 'Run' menu.

A launch config for 'flutter attach' may improve discoverability - it's worth considering.

cc @stevemessick @DaveShuckerow

**Comment by modulovalue** [comment]
MacOS targets are now supported natively so this isn't needed anymore for me. 
Even if this might be interesting for other unsupported platforms, it still wouldn't be the optimal solution for that problem so I'm going to close this.
