### ISSUE TITLE
Restore breakpoints after hot reload

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#305]
When the Hot Reload button is clicked the code on the selected device is updated but the breakpoints are lost for that device. If multiple devices are connected only the breakpoints on the reloaded device are lost. The breakpoint locations are not changing in this case (I just changed one character in a string to test that). This needs to be solved by the IDE since the daemon has no information about breakpoints.

**Comment by stevemessick** [comment]
Oddly, doing a full app restart seems to preserve breakpoints.

**Comment by devoncarew** [comment]
Yeah, we'll need some API changes to enable us to preserve (or re-set) breakpoints during a hot reload.

**Comment by stevemessick** [comment]
Can't we just use the observatory, as we already do to set and unset them? I'm actually wondering why the breakpoints do not get lost on a restart. Maybe the daemon should be doing something different, and this isn't even an IDE issue. @danrubel could that be the case?

**Comment by devoncarew** [comment]
The resolution from this issue: https://github.com/flutter/flutter-intellij/issues/273 will help us out. I think the steps will be:

- we send in `reloadSources(pause: true)` via the daemon protocol
- the VM reloads; we get a new event type back (`kPausePostRequest`)
- on receipt of that event, we should manually restore all previous breakpoints

**Comment by eseidelGoogle** [comment]
FYI @johnmccutchan

**Comment by devoncarew** [comment]
This is currently blocked on https://github.com/flutter/flutter/issues/6890 (a crash in the runtime).

/cc @johnmccutchan, @turnidge I see this crash on both the iOS simulator and with Android devices.

**Comment by johnmccutchan** [comment]
https://github.com/flutter/flutter/issues/6890 is fixed.

**Comment by devoncarew** [comment]
PR for the Dart plugin out here: https://github.com/JetBrains/intellij-plugins/pull/457

**Comment by devoncarew** [comment]
This is in progress in the Dart plugin; moving it out of the 0.1.8 milestone.

**Comment by devoncarew** [comment]
This has landed in both the Flutter and Dart plugins.
