### ISSUE TITLE
Test not found when plain-name contain non escaped characters

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3058]
Hey me again :D lol 

If I have a test named `test('Login not full merchant doesn\'t emit currency', () async` you can't click right on it and run it. It will say `No test found`. 

The command is 
```
/Users/jaumard/flutter/bin/flutter --no-color test --machine --start-paused --plain-name "Login not full merchant doesn\'t emit currency" test/merchant/bloc/merchant_bloc_test.dart
```

Problem is that the command who works is : 
```
/Users/jaumard/flutter/bin/flutter --no-color test --machine --start-paused --plain-name "Login not full merchant doesn't emit currency" test/merchant/bloc/merchant_bloc_test.dart
```

So if `'` is escaped then my test is found, I guess similar case will append with `"`.

**Comment by devoncarew** [comment]
Ah, cool, thanks for the report!
