### ISSUE TITLE
ensure that flutter run output has appropriate hyperlinks

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3060]
We should ensure that error messages and stack traces from flutter run output, that contain source file references, have appropriate hyperlinks in the console.

We may already do much of this, but we should verify, and fill in gaps if any.

@pq, this may line up with some of your expected error message work?

**Comment by devoncarew** [comment]
related to https://github.com/Dart-Code/Dart-Code/issues/1380

**Comment by DanTup** [comment]
FWIW, the Dart Code changes are specifically for stack traces right now (the regex expects something like `#nnn xxx (package|file|dart):xxxxxx:nn:nn`). If there's other output that might contain things we can reliably link, please ping me an example and I can add that too.
