### ISSUE TITLE
reconcile severity-driven log coloring w/ framework-provided error styling

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3063]
The current support for entry coloring based on severity interferes with the framework provided styling we're exploring.

![image](https://user-images.githubusercontent.com/67586/50973519-ebcccf80-149d-11e9-9263-d9fca55dc6e8.png)

![image](https://user-images.githubusercontent.com/67586/50974030-25520a80-149f-11e9-9f60-d7461a88c01f.png)

Probably the easiest thing would be to simply ignore/override severity styling for the message portion of entries that have structured styling info from the framework.

/cc @InMatrix for thoughts.

**Comment by devoncarew** [comment]
Tentatively re-triaging into M36.
