### ISSUE TITLE
Method not available: ext.flutter.inspector.getRootWidgetSummaryTree

### ISSUE THREAD

**Issue by rebootcode** [flutter/flutter-intellij#3069]
## Steps to Reproduce

Saved the code and reloaded the app, not sure what specific action was done

## Version info

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.3.1` • Dart plugin `181.5656`

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (6 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

## Exception

java.util.concurrent.CompletionException: java.io.IOException: error from app.callServiceExtension: "method not available: ext.flutter.inspector.getRootWidgetSummaryTree"
"#0      AppDomain.callServiceExtension (package:flutter_tools/src/commands/daemon.dart:502:7)\n<asynchronous suspension>\n#1      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:193:34)\n#2      new Future.sync (dart:async/future.dart:224:31)\n#3      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:191:9)\n#4      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:147:26)\n#5      _rootRunUnary (dart:async/zone.dart:1132:38)\n#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)\n#11     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)\n#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)\n#13     _rootRunUnary (dart:async/zone.dart:1132:38)\n#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#18     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)\n#19     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)\n#20     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)\n#21     _rootRunUnary (dart:async/zone.dart:1132:38)\n#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)\n#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)\n#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)\n#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)\n#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)\n#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)\n#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)\n#33     _rootRunUnary (dart:async/zone.dart:1132:38)\n#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)\n#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)\n#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)\n#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)\n#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)\n#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)\n#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)\n#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)\n#46     _rootRunUnary (dart:async/zone.dart:1132:38)\n#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)\n#52     _StreamController._add (dart:async/stream_controller.dart:639:7)\n#53     _StreamController.add (dart:async/stream_controller.dart:585:5)\n#54     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)\n#55     _rootRunUnary (dart:async/zone.dart:1136:13)\n#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)\n#61     _StreamController._add (dart:async/stream_controller.dart:639:7)\n#62     _StreamController.add (dart:async/stream_controller.dart:585:5)\n#63     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)\n#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)\n#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)\n#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)\n#67     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)\n#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)\n"

```
java.lang.Throwable: java.util.concurrent.CompletionException: java.io.IOException: error from app.callServiceExtension: "method not available: ext.flutter.inspector.getRootWidgetSummaryTree"
"#0      AppDomain.callServiceExtension (package:flutter_tools/src/commands/daemon.dart:502:7)\n<asynchronous suspension>\n#1      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:193:34)\n#2      new Future.sync (dart:async/future.dart:224:31)\n#3      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:191:9)\n#4      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:147:26)\n#5      _rootRunUnary (dart:async/zone.dart:1132:38)\n#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)\n#11     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)\n#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)\n#13     _rootRunUnary (dart:async/zone.dart:1132:38)\n#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#18     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)\n#19     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)\n#20     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)\n#21     _rootRunUnary (dart:async/zone.dart:1132:38)\n#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)\n#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)\n#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)\n#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)\n#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)\n#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)\n#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)\n#33     _rootRunUnary (dart:async/zone.dart:1132:38)\n#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)\n#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)\n#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)\n#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)\n#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)\n#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)\n#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)\n#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)\n#46     _rootRunUnary (dart:async/zone.dart:1132:38)\n#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)\n#52     _StreamController._add (dart:async/stream_controller.dart:639:7)\n#53     _StreamController.add (dart:async/stream_controller.dart:585:5)\n#54     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)\n#55     _rootRunUnary (dart:async/zone.dart:1136:13)\n#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)\n#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)\n#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)\n#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)\n#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)\n#61     _StreamController._add (dart:async/stream_controller.dart:639:7)\n#62     _StreamController.add (dart:async/stream_controller.dart:585:5)\n#63     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)\n#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)\n#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)\n#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)\n#67     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)\n#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)\n"
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at io.flutter.view.InspectorPanel.lambda$recomputeTreeRoot$5(InspectorPanel.java:575)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$69(InspectorService.java:872)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pq** [comment]
Possibly related to https://github.com/flutter/flutter-intellij/issues/2366?

/cc @jacob314

**Comment by jacob314** [comment]
Was a breakpoint by any chance hit when you restarted the application?
We recently fixed some cases where you would get timeout exceptions if a breakpoint was hit.

**Comment by rebootcode** [comment]
Hi @jacob314 - I have lost the track of bug, it's a way too old bug for me to hold and review again.

I will update my flutter, intellij today and will report in the future When I get a similar error again.

/closing it for now.
