### ISSUE TITLE
Update debugger stack when app is paused

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#307]
Clicking the Pause Program button does pause execution of the Flutter app but it does not update the debugger's view of the stack. When used on a Java program the debugger stack is updated, so if it is possible to do so we should do the same for Flutter.

**Comment by mit-mit** [comment]
@stevemessick @pq I can't seem to repro this, but maybe I am misunderstanding something. When I hit a breakpoint, the 'Frames' pane seems to be up to date?

**Comment by stevemessick** [comment]
I think this was from using the Pause button in IntelliJ, which I have not
tried lately. Breakpoints have always worked.

**Comment by mit-mit** [comment]
Yes, I can repro it now with the Pause button in the Debug pane.

**Comment by mit-mit** [comment]
From discussion: The behavoir here is correct (the program is idle, so there is nothing to show), but we could have a better message in the Debugger UI (it currently says "Frames are not available", could say something like "Program is idle.")

**Comment by devoncarew** [comment]
Closing this as WAI.
