### ISSUE TITLE
Implement flutter tool execution

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#31]
We need a general way to invoke the flutter tool.
This is probably the same as #36

**Comment by stevemessick** [comment]
Also see https://github.com/flutter/flutter-intellij/pull/85

**Comment by devoncarew** [comment]
Do we have this already?

**Comment by pq** [comment]
> Do we have this already?

Enough yeah.  Closing in favor of more targeted follow-ups.
