### ISSUE TITLE
Autoindent fights me when I'm trying to write constructor cascades

### ISSUE THREAD

**Issue by abarth** [flutter/flutter-intellij#310]
Here's what I'm trying to type:

```dart
      new MaterialApp(
        home: new Scaffold(
          body: new ScrollableViewport(
            child: new Container(
              decoration: const BoxDecoration(
                backgroundColor: Colors.amber[500],
              ),
              height: 5000.0,
            ),
          ),
        ),
      ),
```

Every time I press "enter", the next line is indented four spaces, but I only want it to be indented two spaces.  When I press "backspace", all four spaces are removed.  What I need to do is move earlier in the line an right-delete two spaces to get the indent I'm looking for.

Notice that the above code is formatted properly according to `dartfmt`.

**Comment by stevemessick** [comment]
I'll take a look. We may be able to make it less annoying. It is unlikely to ever be perfect. The built-in IntelliJ formatter is rule-driven. There is limited access to non-local state. You can make the rules arbitrarily complex (Java code) but they have to run fast, can't block the event loop. I think newline processing is done in the event loop.

I think a lot of Dart programmers ignore formatting while typing then clean it up with `Code` > `Reformat with Dart Style` which runs `dartfmt`. To get around the smart-delete I sometimes use shift-left arrow to select some space characters then start typing.

**Comment by abarth** [comment]
If that's the case, the simplest thing might be to intent by two spaces rather than by four spaces in this case and have backspace operate in units of two spaces.  That's not going to give you the correct indent in every case, but it will at least let you type correctly formatted code without tricky delete sequences.

**Comment by stevemessick** [comment]
@abarth Since changes to the Dart plugin typically appear with IntelliJ releases you might want to change a preference setting now, to get the kind of delete-key behavior you want.

Go to this page: `Preferences>Editor>General>Smart Keys`
Change the `Unindent` selection to `To nearest indent position`

Let us know if that helps. If it does, we might want to find a way to make it easier to communicate with users that setting can be changed. @jwren FYI

**Comment by devoncarew** [comment]
moved to https://youtrack.jetbrains.com/issue/WEB-23958

**Comment by alexander-doroshko** [comment]
Will cherry-pick to 2106.3.1

**Comment by devoncarew** [comment]
\o/
