### ISSUE TITLE
file://xxx links in Flutter app console do not work

### ISSUE THREAD

**Issue by alexander-doroshko** [flutter/flutter-intellij#3106]
When clicking on a link in a stack trace error, for example:
```
I/flutter ( 2684): #1 MealRowState.build.<anonymous closure> (file:///Users/thinkdigital/GoogleDrive/Development/IdeaProjects/teddycare/lib/src/app/teacher/manage/meals/view.dart:469:62)
```
an error is shown: 
![image](https://user-images.githubusercontent.com/4499789/51468662-99828d00-1d80-11e9-8d88-de10600f1af4.png)
On Windows:
![image](https://user-images.githubusercontent.com/4499789/51468689-a43d2200-1d80-11e9-86b4-6d3c38c77bc1.png)

More details: https://youtrack.jetbrains.com/issue/WEB-36613

**Comment by alexander-doroshko** [comment]
One of the possible fixes is to enable [DartConsoleFilter](https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/ide/runner/DartConsoleFilter.java) for Flutter apps. Another is to update [FlutterConsoleFilter](https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/console/FlutterConsoleFilter.java) accordingly. See also [DartConsoleFilterTest](https://github.com/JetBrains/intellij-plugins/blob/master/Dart/testSrc/com/jetbrains/lang/dart/ide/runner/DartConsoleFilterTest.java).

**Comment by devoncarew** [comment]
Thanks for moving the issue, and for the code pointers!
