### ISSUE TITLE
<no device>

### ISSUE THREAD

**Issue by erikaemma** [flutter/flutter-intellij#3116]
Version: 1.0.0

Stage 1: Flutter can't connect to my emulator android studio.
Try 1: run 'flutter config' to set android and android studio root dir, but it cause 'flutter doctor' failed, so I unset it.
Try 2: run 'adb shell' or 'adb devices', it infor me 'device unauthorized', so I try to clear authorization (My android sdk is Completely re-downloaded, but I still want to try it) and it failed.
Try 3: 'export ANDROID_HOME=/path/to/android/sdk', on Android Studio can show 'no device' and 'open xxx(my emulator name)', I select second and my emulator start but flutter just can't connect.
Try 4: I create second emulator (the first is Nexus_5X_API_28, and I create Nexus_6X_API_28), then Android Studio and flutter work well.
Try 4.9: I delete Nexus_6X_API_28 and  Nexus_5X_API_28 works well.

Stage 2: Flutter can connect but Android Studio shows 'no device' and no 'open xxx'.
Today I just open my notebook and run Android Studio and find the question.
ANDROID_HOME yesterday I write to .bashrc and today it is not disappear.
Then I find the result of 'flutter doctor' is different between [Android Studio - tools - flutter - flutter doctor] and Ubuntu Shell.
But I run 'flutter doctor' on Android Studio's terminal, the result is the same to Ubuntu Shell.
IT INFOR 'Unable to locate Android SDK.'

--------------------------------------------------------
In Stage 1 Try1, if I don't set or unset those, flutter doctor work well, if I set those paths as 'flutter doctor -v' shows, then flutter docotr will info me I do NOT install plugins (flutter and dart) and have no android sdk install.
And now, because I have export ANDROID_HOME on .bashrc, so I must run Android Studio (studio.sh) on shell in order to use Flutter Plugin.

**Comment by devoncarew** [comment]
> Then I find the result of 'flutter doctor' is different between [Android Studio - tools - flutter - flutter doctor] and Ubuntu Shell.

This is probably a cause of some of the issues you saw. I see the you used `flutter config` and then unset it. I'd try running that again - `flutter config --android-sdk=/your/path` - it'll tell flutter where the android sdk is on your machine, and ensure that the Flutter plugin is using the same Android SDK.

**Comment by erikaemma** [comment]
> > Then I find the result of 'flutter doctor' is different between [Android Studio - tools - flutter - flutter doctor] and Ubuntu Shell.
> 
> This is probably a cause of some of the issues you saw. I see the you used `flutter config` and then unset it. I'd try running that again - `flutter config --android-sdk=/your/path` - it'll tell flutter where the android sdk is on your machine, and ensure that the Flutter plugin is using the same Android SDK.

I use this command to set android and android sdk path, then flutter doctor infor me I do NOT install flutter plugin and dart plugin, then I unset it, and all are okay

**Comment by erikaemma** [comment]
> There's likely a copy of Android Studio on your machine which doesn't have the dart and flutter plugins installed. This isn't an issue if you're not using that version of the IDE for Flutter development.

Please, YOU DON'T SEE MY DESCRIPTION, I just have to run it by other way.
