### ISSUE TITLE
Infinite loop when organizing directives on save

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter-intellij#3117]
Copied from https://github.com/dart-lang/dart_style/issues/767

Not sure what kind of info i can give, but i'm almost sure this is a formatter problem.

I have a code like this:

```dart
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcon
///      fonts:
///       - asset: fonts/AppIcon.ttf
///
///
///

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcon';

  static const IconData icon = IconData(0xe800, fontFamily: _kFontFam);
}
```

When the formatter is ran it end up duplicating the comment section indefinitely.
Pressing ctrl+s (save) on AS just makes the file grow indefinitely, pressing ctrl+alt+l (format) duplicates the comment one time.

I think that what causes the problem is the import below the comment, when i move it to the begin of the file everything works fine.

Some info that may help:
Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Dart 2.1.0-dev.9.4
Flutter 1.0.0

---

Anyway, this is a Android Studio problem, when the "Organize imports on save" option is checked the problem happens

![](https://user-images.githubusercontent.com/7496871/51642713-4dd30d80-1f51-11e9-8cb1-ca1f7bb06fbc.png)

**Comment by DanTup** [comment]
I can repro the duplication of comments in VS Code, but only once. So I believe that's an analyzer bug, which I've opened https://github.com/dart-lang/sdk/issues/35744 for. However, if AS is getting into a loop, that sounds like it may be a different (but maybe related/dependent) bug.

**Comment by terrylucas** [comment]
Needs to be looked at probably a result of the analyzer bug that is ref'd https://github.com/dart-lang/sdk/issues/35744

**Comment by Grohden** [comment]
dart-lang/sdk#35744 is closed, and I can't repro this anymore in AS (beta 4.2) and latest dart SDK versions (2.12.0-177.0.dev) so.. it may be solved?

**Comment by DanTup** [comment]
Seems like it, thanks!
