### ISSUE TITLE
support file uri hyperlinks in log message contents

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3124]
Would be nice if the log is containing a path:
- to have it entirely 
- to make it a link for easy copy/paste and open on the IDE
- Bonus -> if not a file supported by IDE, open it on OS file explorer (finder on Mac) ? 

My use case is that I print the path to the iOS SQLite Database because it's always a nightmare to find it. Would be perfect if when I click on the path it will open the folder on the finder for me to copy/paste the database where I need for debugging.

```
10:42:49.711 6 info DatabaseProvider Database is: /Users/jaumard/Library/Developer/CoreSimulator/Devices/B9C382ED-425A-48A3-9DDA-B1C15D7BA485/data/Containers/Data/Ap...
```

<img width="1295" alt="capture d ecran 2019-01-25 a 10 43 16" src="https://user-images.githubusercontent.com/2970449/51737959-449b8b00-208e-11e9-91bc-456b2961ba4b.png">

**Comment by pq** [comment]
Thanks for this @jaumard!

To confirm:

1. it looks like you're logging via a `developer:log` call?, and
2. the message is getting truncated, leading to an incomplete file URI?

**Comment by jaumard** [comment]
Yes I'm using `developer:log`, message is truncated and it's not a link so I can't click or copy/paste it

**Comment by jaumard** [comment]
@pq on last plugin version you pushed few days ago it's not truncated anymore but it's still not a link 
<img width="1047" alt="capture d ecran 2019-01-28 a 16 14 56" src="https://user-images.githubusercontent.com/2970449/51845554-044f3d80-2318-11e9-9be2-4e9789dfd853.png">

**Comment by pq** [comment]
Ok, great.  I'm glad things aren't truncating.  I'll update this issue to reflect the request for hyperlink support in message cell rendering.  Thanks!

**Comment by devoncarew** [comment]
Closing as this is related to the experimental logging view.
