### ISSUE TITLE
Consider formatting JSON in smart log entry popup

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3133]
When clicking on a line in the console, it show a popup with the full log entry on it.
That's nice ! But would be nice if the data is JSON to have it formatted to be easily readable (and why not expand/collapsable)
<img width="896" alt="capture d ecran 2019-01-28 a 16 20 05" src="https://user-images.githubusercontent.com/2970449/51845830-96efdc80-2318-11e9-8d6b-911197ce9f8f.png">

**Comment by jaumard** [comment]
also having the possibility to resize the popup would be nice

**Comment by terrylucas** [comment]
Interesting idea either automatically or user when logging could use a custom formatter for JSON?

**Comment by jaumard** [comment]
When you receive data from a backend as JSON you might use an http library that hide you the JSON part and in that case (that my case ^^, I just put a interceptor to log the data response/request) using a custom JSON formatter would be quite complicate/painful to setup. 
If the IDE plugin does it, it might also also some capabilities to expand/collapse objects, arrays. Copy only one key or value that a custom JSON formatter on dart side will not be able to provide
