### ISSUE TITLE
How to make android resource directory in flutter project??

### ISSUE THREAD

**Issue by MistryHiral** [flutter/flutter-intellij#3136]
When i create xml resource directory in res folder then display  error 'Cannot find resource directory for module Module:'. how to resolve this error??

**Comment by kenzieschmoll** [comment]
@stevemessick should this be solved by "Open Android module in Android Studio"?

**Comment by stevemessick** [comment]
Probably, if the res folder is part of the Android module.

**Comment by kenzieschmoll** [comment]
@MistryHiral could you post the output of `flutter doctor`?

**Comment by Undefitied** [comment]
Absolutely the same problem. 
I'm trying to add new layout for the service in android, and can't create `layout` folder `(res/layout)`
picture: https://prnt.sc/ovygpo

**Comment by fushilu** [comment]
Absolutely the same problem

![image](https://user-images.githubusercontent.com/55873696/68301432-ec90bb00-00da-11ea-8169-a76b9fe2e029.png)


![image](https://user-images.githubusercontent.com/55873696/68301467-fc100400-00da-11ea-8436-0a2cae640b89.png)

**Comment by fushilu** [comment]
open flutter module 
![image](https://user-images.githubusercontent.com/55873696/68301741-9112fd00-00db-11ea-82a6-c512d31f0afe.png)

**Comment by am1994** [comment]
I had the same problem and i fixed it by adding the directory and  XML file manually :
![show_in_file](https://user-images.githubusercontent.com/17643446/84716490-28daa280-af6b-11ea-869b-7bb90f001f89.png)
![add_file_to_android2](https://user-images.githubusercontent.com/17643446/84716507-37c15500-af6b-11ea-9de2-5e0dc2fc3981.png)
![add_file_to_android](https://user-images.githubusercontent.com/17643446/84716527-43148080-af6b-11ea-9bb0-a6fb4d9e3a33.png)

**Comment by root458** [comment]
Any solutions gathered so far? I'm also having issues creating a raw resource directory

**Comment by zainosta** [comment]
.

**Comment by ollydixon** [comment]
I never get the option for "New resource file" in Flutter projects and adding it manually doesn't work 🙈 (Android 🤕)

<img width="686" alt="Screenshot 2022-05-26 at 14 15 24" src="https://user-images.githubusercontent.com/6940726/170485913-43062547-3b22-4ff8-94b9-787d217a6bd1.png">
