### ISSUE TITLE
(Android Studio) Banner notifications for source files containing runnable samples

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3143]
Companion to https://github.com/flutter/flutter-intellij/issues/2976 which adds support to IDEA.

@stevemessick : does that banner contribution work for Android Studio?

**Comment by stevemessick** [comment]
You're referring to #3113, right? I tested it in Android Studio. It even puts the sample projects in the right place. 🥇

**Comment by pq** [comment]
Awesome.  Thank you!
