### ISSUE TITLE
AVD Manager not available in IDE plugin, yet `flutter doctor` says everything is OK

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#3146]
@gspencergoog commented on [Tue Dec 12 2017](https://github.com/flutter/flutter/issues/13514)

## Steps to Reproduce

When going through the codelab, I got to this page: https://codelabs.developers.google.com/codelabs/flutter/#2

In the "iOS Simulator or Android Emulator" section, it says to run the Android Emulator with  Tools > Android > AVD Manager, but when I do that, the AVD Manager is greyed out and unavailable.  Flutter doctor reports nothing missing.

![Screenshot of Menu](https://user-images.githubusercontent.com/8867023/33900638-02750cee-df24-11e7-936d-e1d160db5557.png)

I'm not sure if a step is missing from the instructions, or if there's a problem with the IntelliJ plugins.

I am able to run an already configured emulator from the devices pulldown.

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel unknown)
    • Flutter at /usr/local/google/home/gspencer/code/release/flutter
    • Framework revision 8f65fec5f5 (11 minutes ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Android NDK at /usr/local/google/home/gspencer/Android/Sdk/ndk-bundle
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /usr/local/google/home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio-with-blaze-2.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 18.4
    • Dart plugin version 171.4694.29

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Flutter plugin version 18.2
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Nexus 6P • 84B7N15A07007628 • android-arm • Android 8.0.0 (API 26)
```

---

@sethladd commented on [Tue Dec 12 2017](https://github.com/flutter/flutter/issues/13514#issuecomment-351135802)

cc @LarkAscending @mjohnsullivan 

---

@LarkAscending commented on [Tue Dec 12 2017](https://github.com/flutter/flutter/issues/13514#issuecomment-351143609)

@sethladd  Seems like a product issue to me WDYT?

---

@sethladd commented on [Tue Dec 12 2017](https://github.com/flutter/flutter/issues/13514#issuecomment-351146961)

Hm, good question.

cc @devoncarew is there a symptom around "AVD Manager is greyed out" ? Does that indicate something that can be fixed by a user?

According to https://stackoverflow.com/questions/41290134/android-studio-avd-manager-button-is-disabled maybe the Android SDK is misconfigured or missing? If so, then maybe `flutter doctor` isn't doing to right thing, as it should complain here.

https://stackoverflow.com/questions/44015671/android-studio-2-3-avd-manager-greyed-out seems to hint that maybe some project files are missing?

In either case, I think the codelab doesn't need to add any explicit steps here, but we might need to make `flutter doctor` a bit smarter here to catch a potential project misconfiguration.

---

@rockingdice commented on [Tue Aug 21 2018](https://github.com/flutter/flutter/issues/13514#issuecomment-414565004)

For anyone who still meets this issue on mac with Intellij idea, you can try create a new project of 'Android', it may tell you android sdk is not installed, but if you try to install it, the ide will find the sdk and nothing will change but it recognized the sdk. After that you can use AVDManager.

**Comment by stevemessick** [comment]
Haven't looked into this yet, but it is possible that the AVD manager cannot be run unless the open project is an Android project. If it _can_ be run from a Flutter project, we might want to see about adding "Open AVD Manager" to the device selector, for compatibility with Android Studio. AS also has "Troubleshoot device connections" under it, which might be worth investigating for inclusion in Flutter projects.

**Comment by kenzieschmoll** [comment]
I just checked and I am able to open the AVD manager in Android Studio for both an Android project and a Flutter project. In this issue report, if AVD manager was also unavailable for an open Android project, then seems like this may have been an issue with the AS configuration.

I'll open a separate issue with @stevemessick's suggestion to consider adding "Open AVD Manager" and "Troubleshoot device connections" to the device selector.

**Comment by kenzieschmoll** [comment]
@stevemessick do you think there is anything we could be doing here to make `flutter doctor` detect something like this in the AS configuration?

**Comment by stevemessick** [comment]
The IDE and plugin versions are really out of date. We don't support versions 18 and 20 anymore.
