### ISSUE TITLE
Need to clean up launch AS toolbar

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#3148]
The beta and canary channels of Android Studio have added toolbar functions that are confusingly similar to Flutter's: device selector, apply changes, apply code changes. We need to clean this up so Flutter users are not confused by Android Studio features that do not apply to Flutter. (The alternative would be to make Flutter's toolbar look like AS, but I think that has branding issues.)

<img width="764" alt="screen shot 2019-01-30 at 1 04 04 pm" src="https://user-images.githubusercontent.com/8518285/52012647-fb817780-248f-11e9-82e5-e765ef1cb194.png">

In this image, if the users clicks the run button the app will launch on the iPhone simulator, but someone could certainly think it would launch on the Pixel 2 emulator.

**Comment by devoncarew** [comment]
@stevemessick - for this release or the next one?

**Comment by stevemessick** [comment]
I think it will have to be M34. I spent a little time looking into what it takes.

The implementation of the drop-down is in `DeviceAndSnapshotComboBoxAction`. Unfortunately, it is declared `final` so we can't use the override trick like we do for `AndroidConnectDebuggerAction`.

There's another trick that may work, based on:
`StudioFlags.SELECT_DEVICE_SNAPSHOT_COMBO_BOX_VISIBLE.override(Boolean.FALSE);`
That sorta works, but you have to be careful to set the proper value for every project that gets opened (it's global). It also causes some flashing, since the box first appears then disappears in a Flutter project. My confidence in getting that right this close to M33 is too low to proceed. Aside from flashing, there may be indeterminacy when AS is shut down and restarted with both a Flutter and Android project open in separate windows.

Hopefully, some third option will present itself. Have to keep looking :)

**Comment by stevemessick** [comment]
Closing in favor of #4272
