### ISSUE TITLE
Search for Dart and get Flutter

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#3149]
Open the new IntelliJ plugin manager.
Search for Dart.
Install it.
Look at related plugins.
Flutter should show up. At least one plugin with "Flutter" in its name does.

**Comment by alexander-doroshko** [comment]
I guess you need to have 'dart' word anywhere in the plugin description.

**Comment by stevemessick** [comment]
Sounds like a simple fix. Thanks!

**Comment by stevemessick** [comment]
That worked, the new Flutter plugin shows up when searching for Dart. Thanks!
