### ISSUE TITLE
support AppCode

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#315]
This is a longer term tracking issue, to know what work we'd need to do to support AppCode:
- [ ] Flutter is not suggested in New Project Wizard (IntelliJ IDEA-specific extension points do not work there)
- [ ] AppCode can open only those projects that have *.xcodeproj or *.xcworkspace in the root folder, next to .idea, and it is not the case for flutter projects

**Comment by jaumard** [comment]
Can't we have at least an option "open to AppCode" ? Or it will not work also ?

**Comment by quangson91** [comment]
Since App Code end of sale. So I think we can close this issue https://blog.jetbrains.com/appcode/2022/12/appcode-2022-3-release-and-end-of-sales-and-support/

**Comment by bartekpacia** [comment]
https://www.jetbrains.com/objc

> AppCode is no longer available as a commercial product as of December 14, 2022.
