### ISSUE TITLE
IntelliJ and Android Studio can't find io.flutter packages in Flutter plugin project

### ISSUE THREAD

**Issue by silverAndroid** [flutter/flutter-intellij#3153]
I'm trying to write the Android portion of a Flutter plugin but it's difficult because IntelliJ and Android Studio doesn't know where to look for the dependencies and I don't know where to point them to.

## Steps to Reproduce

1. Create new Flutter project (set plugin as project type) from Android Studio or IntelliJ (Set Java or Kotlin as Android language)
1. Open the generated Android plugin class inside the src.main folder under the android section.

I open the *Plugin.java class and I'm greeted with a bunch of errors
![Greeted with a bunch of errors](https://user-images.githubusercontent.com/5651666/52165683-e4ca6300-26d1-11e9-808c-83b83118a136.png)

## Version info

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.292], locale en-US)
    • Flutter version 1.0.0 at D:\dev\SDKs\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\dev\SDKs\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\dev\SDKs\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\Rushil\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.3

**Comment by stevemessick** [comment]
We do not do a regular Gradle build because it takes a long time and most people would not find it useful. For those like yourself who need this functionality we have a work-around. In the Project pane select the directory named `android` and right-click. Choose the menu item `Flutter > Open Android module in Android Studio`. That will open a new window that will build the Android project with Gradle and support editing Java/Kotlin files.

You could also try turning on the experimental option that enables code completion for Java, etc. but that might have problems with a Flutter plugin.

**Comment by rmawatson** [comment]
Using intelliJ IDEA and importing the android folder as a new gradle project appears to work (File -> New Project From Existing Sources). I'm new to IntelliJ IDEA, but I suspect the problem lies with the IntelliJ project not being able to be both a 'gradle' and 'flutter' project at the same time?

**Comment by rmawatson** [comment]
@kenzieschmoll totally not solved, but closed anyway?

**Comment by stevemessick** [comment]
@rmawatson I recommended closing it because it is a known problem, solutions are being evaluated, and no new action will be taken at this time. I mentioned two work-arounds in my previous response. Your way of opening the project is equivalent to using the "Open in Android Studio" menu item that I suggested. We know this is not a perfect solution but it is as close as we can get today.

**Comment by mateusfccp** [comment]
No solution for this yet? I got this situation today.

**Comment by rmawatson** [comment]
@stevemessick Sweep under the rug. Gotcha.

**Comment by Icosa2050** [comment]
I suffer from this for two years. The suggested workarounds did not help me anymore. At least a clearer documentation somewhere would be appreciated. Closing is not fixing. At least somewhere the solution must be described in detail. Bad.

**Comment by Icosa2050** [comment]
Ok. Googling around: and thinking a bit. What is missing is a flutter.jar  in the project, to at least find missing symbols. 
https://github.com/flutter/flutter/issues/19830
My workaround (Linux)
Added a symbolic link in project folder.
cd  <myproject>/android/src
ln -s <path_to>/flutter.jar .  "don't forget the point at the end
But which flutter.jar version: guess your version from flutter/bin/cache/artifacts/engine/android-XYX/flutter.jar
From Studio: right click on the linked flutter.jar,  "Add as library". Now at least the symbols are found. 
Problem: The library is not generic :-(. That could mean trouble down the road.

**Comment by escamoteur** [comment]
This is definitely not solved in any useful way, therefore I reopen this issue. I was bitten by this today and I'm totally surprised that this is happened

**Comment by escamoteur** [comment]
Hi @stevemessick, it wasn't my intention to upset you. I'm sorry that I did. In the `flutter/flutter` repo reopening an issue is quite normal so I didn't think much about it. 
As this issue a problem that can catch developers doing Android native plugins pretty cold and I also haven't found any docs on it besides this issue, I would be appreciate if we could keep it open so that if does not get forgotten.

**Comment by devoncarew** [comment]
Hi @escamoteur - thanks for your follow-up and note!

> As this issue a problem that can catch developers doing Android native plugins pretty cold and I also haven't found any docs on it besides this issue, I would be appreciate if we could keep it open so that if does not get forgotten.

I definitely agree that some easily discoverable docs w/ the issue description and most up to date info would be a good idea.

**Comment by escamoteur** [comment]
Isn't there a better way to handle this possible?

**Comment by stevemessick** [comment]
The docs at flutter.dev do mention how to edit the platform-specific code, both for [Android](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-2b-add-android-platform-code-ktjava) and [iOS](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-swifthm). But they don't have much detail, and I think assume too much background knowledge about the IDEs. Opening an issue in [flutter/flutter](https://github.com/flutter/flutter/issues) would be appropriate.

@escamoteur asked:
> Isn't there a better way to handle this possible?

Maybe.

If someone wants to do some experimentation, there may be a better way to solve the problem. I don't have time right now, but the basic idea is to convert the plugin project to a Gradle project and open it in Android Studio. @rmawatson hinted at this earlier but at the time I didn't think it was possible. (Obviously, this won't work for iOS.)

The experiment:
- Create a Flutter module
- Make a copy of it
- Make a copy of your plugin project, too
- Create an Android project using the `Basic Activity` template
- Import the Flutter module into the Android project (File > New > New Module... > Import Flutter Module)
- Compare the before and after versions of the module to see what changed
- Try making similar changes to your plugin (_use the copy_) to make it look like a Gradle project, by adding one or more files
  - `build.gradle`
  - `settings.gradle` -- probably need to do `include ':android'` here
  - `gradle.properties`
- Open the plugin in Android Studio as a Gradle project, let sync finish, then see if the Android files have proper editing support

If that actually works, then opening a feature request here with details would be appropriate.

For more info about Flutter modules, see the [add-to-app docs](https://flutter.dev/docs/development/add-to-app/android/project-setup).

**Comment by escamoteur** [comment]
Awesome! I will try to do that over the weekend. Indeed especially on how to debug native plugins there is little docs. will make an issue on the Flutter Repo. On iOS it's a bit easier because you don't have to open the same project twice in different ways
