### ISSUE TITLE
Error check before hot reload will cause reloads to fail if a clean app is in a bigger project with separate failures

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter-intellij#3168]
1. Introduce an error to test code (say a line that has no semicolon).
2. Run the app
3. Reloading the app fails.

The lines below cause this to happen:
https://github.com/flutter/flutter-intellij/blob/a1748e99fd093697946b4cbbfa975bc33cc57d52/src/io/flutter/run/FlutterReloadManager.java#L199-L205

I'm looking into removing those and letting the flutter daemon tell us if it's safe to reload the app.  The parent to this issue is https://github.com/flutter/flutter/issues/27618

**Comment by devoncarew** [comment]
We should consider removing the check for analysis errors before performing a reload on save.

**Comment by devoncarew** [comment]
fixed by https://github.com/flutter/flutter-intellij/pull/4327
