### ISSUE TITLE
Running/Debugging tests gives error "No Bazel target set"

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter-intellij#3169]
Normally when Running or Debugging Flutter tests I have no issues. When you click Run or Debug the test should start as expected. Recently, this started happening.

## Steps to Reproduce
Run a test in one of the following ways. (Using Run or Debug)
- Right Click menu after right clicking on code in a test file.
- Right Click menu after right clicking on a file in a test folder in Project view
- Right Click menu after right clicking on a test in the Run window (Test Results)

## Steps to NOT Reproduce (works correctly this way)
- Right Click menu after right clicking a test folder in Project view

## Version info
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale en-CA)
    • Flutter version 1.1.8 at /Users/jrai/dev/flutter
    • Framework revision 985ccb6d14 (4 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jrai/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jrai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPad Air 2 • 5AD11829-1F07-439E-BA80-70CFDDB4B2A0 • ios • iOS 12.1 (simulator)

Here is a screenshot of what happens when I did: Right Click on job_manager_tests.dart > Run Tests
![screen shot 2019-02-07 at 9 07 28 am](https://user-images.githubusercontent.com/7351329/52416546-d4dac680-2ab7-11e9-9c6a-3f0bf00242fa.png)

**Comment by devoncarew** [comment]
@jwren @DaveShuckerow I think new launch configs that are created via right-clicking and running on a test file are now defaulting to bazel launch configs. We should bisect this to verify, and if its the case, we'll want to address before the next release.

**Comment by DaveShuckerow** [comment]
I'm able to see the following:
![image](https://user-images.githubusercontent.com/14947366/52435321-63564480-2ac6-11e9-9dc0-54de59b46114.png)

The bazel run option is coming up above the pub run option.  I'll check that the bazel configuration factory knows to verify it's part of a bazel workspace before it provides any run configuration.

**Comment by devoncarew** [comment]
Thanks! Sounds good. There may also be an implicit ordering based on the order they're declared in plugin.xml, but I haven't verified that.

**Comment by MisterJimson** [comment]
Just a note I am seeing this behaviour inconsistently. Sometimes will only the bazel option, sometimes only pub, sometimes both.

Here is an example video of the behaviour being inconsistent.

https://drive.google.com/open?id=1BE9frMPJKxxfgOZo2PJm5qEWH4KN1L3E

**Comment by DaveShuckerow** [comment]
@MisterJimson can you show an example of where you would see both options?

**Comment by MisterJimson** [comment]
Sure let me see. I definitely have seen it doing the same things I did in the that video.

**Comment by MisterJimson** [comment]
Here is a good one. You can see me clicking in the exact same test and file but getting different results back to back.

https://drive.google.com/open?id=1li7TNoSrrwV017xczFBVyFnEQnf08CxE

**Comment by thphuc** [comment]
I'm still getting this error today. @MisterJimson Did you manage to fix it?

**Comment by MisterJimson** [comment]
This is resolved for me as of the 33.0.1 release.

**Comment by thphuc** [comment]
Thanks @MisterJimson I updated to 33.0.1 and it is solved also. Cheers!

**Comment by martipello** [comment]
just for anyone coming to this now, i tried to run my tests and was greeted with this error i then updated flutter but still had this error i had to delete my test file and create a new one and then everything is awesome
