### ISSUE TITLE
Request to place cursor on top of null values on code completion 

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter-intellij#3172]
## Steps to Reproduce

_Create a Padding()
![image](https://user-images.githubusercontent.com/29230303/52477187-86fab700-2bba-11e9-92cc-f2a818574512.png)

-Using Alt+Enter click add required argument 'padding' for code completion
![image](https://user-images.githubusercontent.com/29230303/52477349-fbcdf100-2bba-11e9-8218-1603cf560eb6.png)

-Cursor does not move on top of the null value but stays there.
![image](https://user-images.githubusercontent.com/29230303/52477373-14d6a200-2bbb-11e9-810b-68e038ac0760.png)

-Feature Requested: 
![image](https://user-images.githubusercontent.com/29230303/52477473-70a12b00-2bbb-11e9-8983-c6b6e7af728e.png)

## Version info

-Flutter plugin 32.0.1
-Dart plugin 182.5215
-Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-MU)
-Android Studio 3.3.1

**Comment by kenzieschmoll** [comment]
@scheglov FYI

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/92520
