### ISSUE TITLE
report logged flutter errors to analytics

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3175]
If folks have opted into sharing analytics, we should log framework errors.

To start we can use a string-based error ID.  Once we have some data, we can evaluate whether that's sufficient and amenable for data analysis.

/cc @jacob314 @InMatrix

**Comment by devoncarew** [comment]
We'll know more re: this bug later today.

**Comment by devoncarew** [comment]
@pq do you know if we're getting these framework errors reported to us now?

**Comment by pq** [comment]
Not yet.  This is part of the structured error work which is just now revving back up.

**Comment by devoncarew** [comment]
This is complete now.
