### ISSUE TITLE
sample projects come with Dart SDK unset

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3187]
To reproduce, create a project w/ sample contents.  You'll be greeted w/

![image](https://user-images.githubusercontent.com/67586/52718435-51f2b980-2f58-11e9-831d-0edf37aabd43.png)

😦

**Comment by pq** [comment]
I expect this has to do with our work-around for https://github.com/flutter/flutter-intellij/issues/3120:

https://github.com/flutter/flutter-intellij/blob/7803ceb18b687babf38ed271d7d25dfe0820eea9/src/io/flutter/sdk/FlutterSdk.java#L358-L367

and we need to either not do this file delete work-around or (re)set the Dart SDK.

**Comment by alexander-doroshko** [comment]
I'm afraid I don't have much to say without diving deep into the problem. 
Working directly with IDE project files definitely looks hacky. And if files in `.idea` folder are managed both by `flutter` tool and the plugin then its _hackiness_ doubles. But I understand that this comment is useless. Sorry about that.

**Comment by pq** [comment]
Not useless at all.  A useful reminder that our metadata management deserves a revisit.

Thanks for the confirmation!

**Comment by pq** [comment]
Closing for now as unable to repro.
