### ISSUE TITLE
Add code folding for if statements

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter-intellij#3191]
## Steps to Reproduce
I noticed that Dart does not fold code inside curly brackets for if statements which is very inconvenient. I use Intellij IDE to develop Javascript, Java and Python but it is the first time I noticed that if statement code folding is not supported.

![image](https://user-images.githubusercontent.com/29230303/52739153-b873e800-2fe9-11e9-8444-953af1428de8.png)

## Version info

Android studio 3.3.1
Dart plugin 182.5215

**Comment by stevemessick** [comment]
It also does not catch the body of a lambda, like the argument of this call to setState:
```dart
  void _select(Choice choice) {
    setState(() {
      // Causes the app to rebuild with the new _selectedChoice.
      _selectedChoice = choice;
    });
  }
```

**Comment by stevemessick** [comment]
@alexander-doroshko In case you hadn't seen this.

**Comment by DanTup** [comment]
I suspect this was fixed by https://github.com/dart-lang/sdk/issues/37582. In Android Studio I see folding regions here:

<img width="259" alt="Screenshot 2021-01-20 at 12 29 54" src="https://user-images.githubusercontent.com/1078012/105174999-43858300-5b1b-11eb-8c88-929eb7f804a4.png">

**Comment by DanTup** [comment]
Actually, it's not using the server - but looks like this was done in https://github.com/JetBrains/intellij-plugins/pull/683.

**Comment by stevemessick** [comment]
Thanks @DanTup !
