### ISSUE TITLE
"default" new test run config is Flutter (bazel) for Dart project

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3194]
To reproduce, right-click and run a test in a vanilla Dart project.

![image](https://user-images.githubusercontent.com/67586/52811840-f7865580-304a-11e9-8b7e-4ecdb191b12c.png)

It will default to a creating a Bazel Flutter Test

![image](https://user-images.githubusercontent.com/67586/52811917-24d30380-304b-11e9-9132-19311338eeb2.png)

Which won't work (and isn't what you want).

![image](https://user-images.githubusercontent.com/67586/52811885-11279d00-304b-11e9-8c42-9752b6d827c6.png)

My guess is we're being too eager in our contribution of Flutter Test configs...

/cc @DaveShuckerow

**Comment by devoncarew** [comment]
Hmm, I think we were hoping this was addressed by https://github.com/flutter/flutter-intellij/pull/3170.

**Comment by DaveShuckerow** [comment]
Is this coming from the M33 build?

**Comment by pq** [comment]
Running from latest sources.

**Comment by DaveShuckerow** [comment]
I looked into using a test in a vanilla Dart server test and wasn't able to reproduce this:

![image](https://user-images.githubusercontent.com/14947366/52822503-b56b0d00-3066-11e9-9a32-378f904a4556.png)

I also am not able to reproduce this in the tests for the Flutter gallery app:

![image](https://user-images.githubusercontent.com/14947366/52822605-f82ce500-3066-11e9-9756-351994466414.png)

These are both generating Pub-based test targets.  Let's discuss further over chat.

**Comment by pq** [comment]
OK, cool.  Thanks for following up!  I just update to 2019.1 and the latest built plugin and I can no longer repro.  Optimistically closing.
