### ISSUE TITLE
the Go link on the sample creation editor header can be hard to read

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3197]
The contrast can be low with the background color:

<img width="348" alt="screen shot 2019-02-15 at 2 02 56 am" src="https://user-images.githubusercontent.com/1269969/52849476-f8a89880-30c5-11e9-8851-cd711324851e.png">

<img width="392" alt="screen shot 2019-02-15 at 2 01 54 am" src="https://user-images.githubusercontent.com/1269969/52849485-fe05e300-30c5-11e9-9bb0-27d51c19d2ac.png">

cc @pq

**Comment by pq** [comment]
Ok wow.  This got worse somehow.  I'm seeing the same on 2019.1.  I'll take a look.  Thanks!

**Comment by pq** [comment]
Weird.  And now I can't repro. 🤔 

![image](https://user-images.githubusercontent.com/67586/52864076-3c16fd00-30ee-11e9-8ca9-a00d7c239706.png)

Does this happen consistently?  What IDE?

I wonder if there's a race condition somewhere that's affecting how theming gets propagated to the Swing UI Toolkit...

/cc @alexander-doroshko in case you've seen anything like this before?  (It's a `JBLabel` with hyperlink contents.)

**Comment by alexander-doroshko** [comment]
> @alexander-doroshko in case you've seen anything like this before?

I haven't

**Comment by stevemessick** [comment]
I see this bad contrast problem occasionally in other contexts so it may not be specific to this link.

**Comment by devoncarew** [comment]
I see this in 2018.3 w/ the release candidate plugin installed, but don't see it when I'm running the plugin from sources.

**Comment by pq** [comment]
OK.  That's curious @devoncarew.  Thanks for that lead.

Looking at work-arounds...
