### ISSUE TITLE
Auto import of dart file does not work with mixins declared with mixin keyword.

### ISSUE THREAD

**Issue by RussellZornes** [flutter/flutter-intellij#3204]
## Steps to Reproduce
When you attempt to auto import a class name that is declared with the mixin keyword, the name of the file does not appear in the popup.

```
// some_mixin.dart
mixin SomeMixin {}

// foo.dart
class Foo extends Object with SomeMixin <- option return on mixin name

```
Expected:
The file some_mixin.dart would appear in popup so you can add the import.

Results:
No file appears in popup to auto import.

Notes:
It works if the mixin is declared as an abstract class rather than with the mixin keyword however.

## Version info

[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.2.0 at C:\dev\libraries\flutter2\flutter
    • Framework revision 06b979c4d5 (3 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\dev\libraries\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\dev\libraries\android-sdk
    • Java binary at: C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700

**Comment by stevemessick** [comment]
@scheglov Does this sound familiar?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/93376
https://dart-review.googlesource.com/c/sdk/+/93641
