### ISSUE TITLE
Flutter Plugin not working correctly with AS 3.3.1

### ISSUE THREAD

**Issue by shreemp** [flutter/flutter-intellij#3209]
Hello, my problem might be related to #2600, but I'm using Android Studio 3.3.1 .

## Steps to Reproduce

I don't really know how to reproduce it but the problem is that I don't have the "Open for editing in Android Studio".
It doesn't appear, either when I'm editing a file inside Android/ folder (build.gradle for example) nor inside the tools/flutter/ option in the menu bar.

## Version info
```
[√] Flutter (Channel master, v1.2.2-pre.21, on Microsoft Windows [version 10.0.17134.590], locale fr-FR)
    • Flutter version 1.2.2-pre.21 at C:\src\flutter
    • Framework revision 035e0765cc (3 days ago), 2019-02-16 01:48:28 -0500
    • Engine revision f37b09a11b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\echevalier\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\echevalier\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code, 64-bit edition (version 1.17.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
![image](https://user-images.githubusercontent.com/19266454/53008665-2bda8700-343a-11e9-862a-f2f77e0e3932.png)

**Comment by stevemessick** [comment]
Is this a new project? If not, you might try creating a new project and copying your project's sources into it. There have been a number of changes in the IntelliJ meta-data that could cause the menu to not show up.

**Comment by shreemp** [comment]
It worked when I created a new project.
Thank you.

**Comment by stevemessick** [comment]
Great! Thanks for the update.

**Comment by hpoul** [comment]
@stevemessick is there some documentation which metadata files are required for that menu to show up? afaik by default the `.gitignore` ignores all `*.iml` files.. and my short testing seems like those are required for the menu to show up? i'm a bit confused as to what to commit to version control..

**Comment by stevemessick** [comment]
I know you have to have an Android module defined. Until now, I would have said the top-level .iml file should be committed. I'm puzzled by its presence in the .gitignore. However, I think IntelliJ is pretty good at recreating modules based on directory content, so it may create an Android module when it loads the `android` directory.

@devoncarew I think we need to look into this a bit, so I'm re-opening it.

**Comment by stevemessick** [comment]
Closing as obsolete.
