### ISSUE TITLE
publish 33.1

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3210]
We should issue a patch release to M33, containing:

- 0ea8ef5d405c72d8be95ac2681a866c91652baf9 (update the product matrix)
- 185695573f983f595c8cf3e699e8222e053ca0a0 (add the ability to install and open DevTools)
- e6846ff61aa5c303443905c9a3e83026833ff375 (Fix Gradle sync error for 3.3.1)
- 59a4fb94b54f8111a3bac6bba866f823d4c4a176 (Fix versions)
- b015485cdd51d8b6a268aa73106a50595cae6897 (work around link rendering issues)

--

@stevemessick, do we also need 59a4fb94b54f8111a3bac6bba866f823d4c4a176? b015485cdd51d8b6a268aa73106a50595cae6897?

**Comment by stevemessick** [comment]
@devoncarew yes to both. Also, what about #3201 once it is merged?

**Comment by devoncarew** [comment]
Yup! added to the list above.
