### ISSUE TITLE
Update plugin icon

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#3211]
The new plugin management page can show an icon for a plugin. We don't have one but Dart does.

<img width="211" alt="screen shot 2019-02-19 at 11 29 48 am" src="https://user-images.githubusercontent.com/8518285/53053972-c9907f00-3457-11e9-9e3d-bc5a57ac1e75.png">

Details [in the Jetbrains docs](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html)

Base logo available [from the Flutter site](https://drive.google.com/corp/drive/folders/1aeGJ3MmU5IDLobrqQqwYlIzil-pCF-1R)

(If I had a decent SVG editor this would be done already.)

**Comment by devoncarew** [comment]
I don't know what size we need, but here's an svg:


[flutter.svg.zip](https://github.com/flutter/flutter-intellij/files/2882555/flutter.svg.zip)

**Comment by stevemessick** [comment]
It needs to be 40x40. I tried dropping in the 1000px original and that didn't work (the instructions are not precise on that point). My graphics editor (acorn) won't open the file correctly. I could try building GIMP I suppose but that gets to be really low priority.

**Comment by stevemessick** [comment]
Oops! I take that back. The 1000px does work. I just needed to find the right zip file when I installed the plugin. (I'm in the middle of the 33.1 build right now and have many to choose from!)
