### ISSUE TITLE
Android Studio can't debug breakpoints when FlutterActivity isn't 1st startup Activity 

### ISSUE THREAD

**Issue by SupSaiYaJin** [flutter/flutter-intellij#3212]
At this situation, IDE can't debug breakpoints.
Also, flutter run --start-paused is invalid too. Flutter won't wait for the debugger to attach.

**Comment by stevemessick** [comment]
Breakpoints work.
'flutter run --start-paused' works.
https://github.com/flutter/flutter/issues/21382 covers launching.
