### ISSUE TITLE
Flutter performance (memory) show GB instead of MB

### ISSUE THREAD

**Issue by MathiasTech** [flutter/flutter-intellij#3218]
**##Issue**

Flutter performance shows GB at top and MB in graph.. knowing that my phone has less than 70GB of ram I'm guessing this is a bug.  (see screenshot below)

**## Steps to Reproduce**

open Android Studio > Using any flutter app, launch app (debug or not, doesn't matter) > open flutter performance 'tab' > select memory > Shows GB at the top and MB in graph representation  (see screenshot below)

**## Version info**

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.0.0 at C:\Users\Mathieu\Documents\Dev\Flutter\flutter_base
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Mathieu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\Mathieu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.0

[√] Connected device (1 available)
    • Mi A1 • 2850b26b0604 • android-arm64 • Android 9 (API 28)

![image](https://user-images.githubusercontent.com/29813490/53157086-1348a900-35c1-11e9-8730-442c5c82b1e3.png)

**Comment by stevemessick** [comment]
@terrylucas

**Comment by devoncarew** [comment]
@terrylucas, I suspect that this will be a pretty quick fix?

**Comment by potatoker** [comment]
hi @terrylucas  I found that some times flutter performance shows a different result with android studio profiler, the detail is in #29782. Is there any problem with this plugin or Android studio profiler?

**Comment by terrylucas** [comment]
DevTools has all the functionality for Flutter memory profiling.  Please use this tool as memory profiling in Intellij will be deprecated.  See https://github.com/flutter/devtools/blob/master/README.md

**Comment by terrylucas** [comment]
Forgot to mention this problem has been fixed in DevTool.
