### ISSUE TITLE
Unnecessary Flutter / Dart code inteli-sense or suggestions when adding documentation or TODOs.

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#3231]
@SV27 commented on [Tue Feb 26 2019](https://github.com/flutter/flutter/issues/28483)

Hi Team,

   Whenever I put a fullstop/period (.) in my code documentation or todo comments, android studio unnecessarily showing Dart code suggestions. It is very frustrating. I need to press escape key immediately after typing Period sign (.) every time.

Attached the screenshot for your reference. I was coding for a flutter application on Mac when taking this screen shot.

<img width="639" alt="android_studio_unnecessary_suggestion" src="https://user-images.githubusercontent.com/34560264/53381587-3c5d9680-393f-11e9-8838-71520045c530.png">

_Additional Notes:_ I reported this issue in Google Issues tracker for Android Studio. But, they asked me to report this in Flutter. Here is the Google issues tracker Link : https://issuetracker.google.com/125088418

---

@jonahwilliams commented on [Tue Feb 26 2019](https://github.com/flutter/flutter/issues/28483#issuecomment-467263196)

cc @devoncarew

**Comment by zoechi** [comment]
It's an analyzer issue that probably should go to dart-lang/sdk but I can only move within flutter/xxx.
I got the impression that such issues find the right people here as well.

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#36037
