### ISSUE TITLE
Android studio writes Dart code inside XML files

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter-intellij#3232]
## Steps to Reproduce

When I open styles.xml or AndroidManifest.xml I see Dart codes. This happens sporadically and I am still trying to figure out when exactly it happens. 
It happened 3 times so far at random point. 

![image](https://user-images.githubusercontent.com/29230303/53436601-01c62d80-3a15-11e9-964f-b13f4392546e.png)

## Version info

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590],
    locale en-MU)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

**Comment by devoncarew** [comment]
Thanks for the report! We haven't gotten other reports of this, so I'm curious how it's happening. Please let us know as you get more details.

**Comment by stevemessick** [comment]
Have you enabled the experimental option to make code completion, etc. work for Java code in the Android module? If not, I'd recommend opening the Android module in a new project to edit files in the 'android' directory. Just click the `Open for editing in Android Studio` button in the screenshot.

Did the Dart code completely replace the original XML content? Is there any chance a spurious keyboard command may have gotten processed by the XML editor?

**Comment by xtfgq** [comment]
Steps to Reproduce
When I open xml or .java  i see Dart codes. Close  or uninstall，but i see Dart codes.This happens sporadically and I am still trying to figure out when exactly it happens.

**Comment by yavac** [comment]
Currently something similar happens to me, and it happens randomly. Instead of Dart code, XML appears. I was forced to use VSC.
![capture](https://user-images.githubusercontent.com/11871438/62962880-71fb1c80-bdc5-11e9-84a3-c82286d1f8cf.JPG)

**Comment by YPBS** [comment]
I got the same problem as above. When I opened my flutter project, there was a popup "Android Framework is detected". I clicked on 'Configure' link and it overwrote dart files with XML. 

I removed the project from Android studio, deleted .idea folder inside the project and re-imported the project but issue was still there. 

Then I again removed the project, deleted .idea and .AndroidStudio folder and re-imported, this time it worked. I lost all custom settings and had to reinstall flutter and dart plugins.

**Comment by stevenosse** [comment]
> 
> 
> Currently something similar happens to me, and it happens randomly. Instead of Dart code, XML appears. I was forced to use VSC.
> ![capture](https://user-images.githubusercontent.com/11871438/62962880-71fb1c80-bdc5-11e9-84a3-c82286d1f8cf.JPG)

I have the same problem!
I just can't understand why does this actually happen!
Anybody has some suggestion for me ?

**Comment by jvlichai** [comment]
I have the same problem. Because I have plugged flutter.

**Comment by tharwatsamy** [comment]
i have the same problem and i was forced to use vsc , anybody knows why this is happening ?

**Comment by tharwatsamy** [comment]
> i have the same problem and i was forced to use vsc , anybody knows why this is happening ?
> 
> > > Currently something similar happens to me, and it happens randomly. Instead of Dart code, XML appears. I was forced to use VSC.
> > > ![capture](https://user-images.githubusercontent.com/11871438/62962880-71fb1c80-bdc5-11e9-84a3-c82286d1f8cf.JPG)
> > 
> > 
> > I have the same problem!
> > I just can't understand why does this actually happen!
> > Anybody has some suggestion for me ?

it was solved after resetting android studio

**Comment by acharyabro123** [comment]
i am getting this type of code instead of dart code in android studio:
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="AutoImportSettings">
    <option name="autoReloadType" value="NONE" />
  </component>
  <component name="ChangeListManager">
    <list default="true" id="ea35eced-eda9-4e51-85bd-99c9c7aec599" name="Default Changelist" comment="" />
    <option name="SHOW_DIALOG" value="false" />
    <option name="HIGHLIGHT_CONFLICTS" value="true" />
    <option name="HIGHLIGHT_NON_ACTIVE_CHANGELIST" value="false" />
    <option name="LAST_RESOLUTION" value="IGNORE" />
  </component>
  <component name="FileTemplateManagerImpl">
    <option name="RECENT_TEMPLATES">
      <list>
        <option value="Dart File" />
      </list>
    </option>
  </component>
  <component name="ProjectId" id="1xCqMFBDtIVEc1mmZPHMqNSihom" />
  <component name="ProjectViewState">
    <option name="hideEmptyMiddlePackages" value="true" />
    <option name="showLibraryContents" value="true" />
  </component>
  <component name="PropertiesComponent">
    <property name="RunOnceActivity.OpenProjectViewOnStart" value="true" />
    <property name="android.sdk.path" value="$USER_HOME$/AppData/Local/Android/Sdk" />
    <property name="dart.analysis.tool.window.visible" value="false" />
    <property name="io.flutter.reload.alreadyRun" value="true" />
    <property name="last_opened_file_path" value="$PROJECT_DIR$/assets" />
    <property name="settings.editor.selected.configurable" value="preferences.pluginManager" />
    <property name="show.migrate.to.gradle.popup" value="false" />
  </component>
  <component name="RecentsManager">
    <key name="CopyFile.RECENT_KEYS">
      <recent name="E:\flutter_provider\ecommerce_fruits\assets" />
      <recent name="E:\flutter_provider\ecommerce_fruits\lib" />
    </key>
  </component>
  <component name="RunManager">
    <configuration name="main.dart" type="FlutterRunConfigurationType" factoryName="Flutter">
      <option name="filePath" value="$PROJECT_DIR$/lib/main.dart" />
      <method v="2" />
    </configuration>
  </component>
  <component name="SpellCheckerSettings" RuntimeDictionaries="0" Folders="0" CustomDictionaries="0" DefaultDictionary="application-level" UseSingleDictionary="true" transferred="true" />
  <component name="TaskManager">
    <task active="true" id="Default" summary="Default task">
      <changelist id="ea35eced-eda9-4e51-85bd-99c9c7aec599" name="Default Changelist" comment="" />
      <created>1629869410038</created>
      <option name="number" value="Default" />
      <option name="presentableId" value="Default" />
      <updated>1629869410038</updated>
    </task>
    <servers />
  </component>
  <component name="WindowStateProjectService">
    <state x="463" y="125" key="FileChooserDialogImpl" timestamp="1631065523637">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state x="463" y="125" key="FileChooserDialogImpl/0.0.1366.768@0.0.1366.768" timestamp="1631065523637" />
    <state width="1306" height="137" key="GridCell.Tab.0.bottom" timestamp="1631108863300">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state width="1306" height="137" key="GridCell.Tab.0.bottom/0.0.1366.768@0.0.1366.768" timestamp="1631108863300" />
    <state width="1306" height="137" key="GridCell.Tab.0.center" timestamp="1631108863299">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state width="1306" height="137" key="GridCell.Tab.0.center/0.0.1366.768@0.0.1366.768" timestamp="1631108863299" />
    <state width="1306" height="137" key="GridCell.Tab.0.left" timestamp="1631108863299">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state width="1306" height="137" key="GridCell.Tab.0.left/0.0.1366.768@0.0.1366.768" timestamp="1631108863299" />
    <state width="1306" height="137" key="GridCell.Tab.0.right" timestamp="1631108863300">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state width="1306" height="137" key="GridCell.Tab.0.right/0.0.1366.768@0.0.1366.768" timestamp="1631108863300" />
    <state x="258" y="67" key="new project wizard" timestamp="1631065544236">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state x="258" y="67" key="new project wizard/0.0.1366.768@0.0.1366.768" timestamp="1631065544236" />
  </component>
</project>

**Comment by acharyabro123** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="AutoImportSettings">
    <option name="autoReloadType" value="NONE" />
  </component>
  <component name="ChangeListManager">
    <list default="true" id="ea35eced-eda9-4e51-85bd-99c9c7aec599" name="Default Changelist" comment="" />
    <option name="SHOW_DIALOG" value="false" />
    <option name="HIGHLIGHT_CONFLICTS" value="true" />
    <option name="HIGHLIGHT_NON_ACTIVE_CHANGELIST" value="false" />
    <option name="LAST_RESOLUTION" value="IGNORE" />
  </component>
  <component name="FileTemplateManagerImpl">
    <option name="RECENT_TEMPLATES">
      <list>
        <option value="Dart File" />
      </list>
    </option>
  </component>
  <component name="ProjectId" id="1xCqMFBDtIVEc1mmZPHMqNSihom" />
  <component name="ProjectViewState">
    <option name="hideEmptyMiddlePackages" value="true" />
    <option name="showLibraryContents" value="true" />
  </component>
  <component name="PropertiesComponent">
    <property name="RunOnceActivity.OpenProjectViewOnStart" value="true" />
    <property name="android.sdk.path" value="$USER_HOME$/AppData/Local/Android/Sdk" />
    <property name="dart.analysis.tool.window.visible" value="false" />
    <property name="io.flutter.reload.alreadyRun" value="true" />
    <property name="last_opened_file_path" value="$PROJECT_DIR$/assets" />
    <property name="settings.editor.selected.configurable" value="preferences.pluginManager" />
    <property name="show.migrate.to.gradle.popup" value="false" />
  </component>
  <component name="RecentsManager">
    <key name="CopyFile.RECENT_KEYS">
      <recent name="E:\flutter_provider\ecommerce_fruits\assets" />
      <recent name="E:\flutter_provider\ecommerce_fruits\lib" />
    </key>
  </component>
  <component name="RunManager">
    <configuration name="main.dart" type="FlutterRunConfigurationType" factoryName="Flutter">
      <option name="filePath" value="$PROJECT_DIR$/lib/main.dart" />
      <method v="2" />
    </configuration>
  </component>
  <component name="SpellCheckerSettings" RuntimeDictionaries="0" Folders="0" CustomDictionaries="0" DefaultDictionary="application-level" UseSingleDictionary="true" transferred="true" />
  <component name="TaskManager">
    <task active="true" id="Default" summary="Default task">
      <changelist id="ea35eced-eda9-4e51-85bd-99c9c7aec599" name="Default Changelist" comment="" />
      <created>1629869410038</created>
      <option name="number" value="Default" />
      <option name="presentableId" value="Default" />
      <updated>1629869410038</updated>
    </task>
    <servers />
  </component>
  <component name="WindowStateProjectService">
    <state x="463" y="125" key="FileChooserDialogImpl" timestamp="1631065523637">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state x="463" y="125" key="FileChooserDialogImpl/0.0.1366.768@0.0.1366.768" timestamp="1631065523637" />
    <state width="1306" height="137" key="GridCell.Tab.0.bottom" timestamp="1631108863300">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state width="1306" height="137" key="GridCell.Tab.0.bottom/0.0.1366.768@0.0.1366.768" timestamp="1631108863300" />
    <state width="1306" height="137" key="GridCell.Tab.0.center" timestamp="1631108863299">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state width="1306" height="137" key="GridCell.Tab.0.center/0.0.1366.768@0.0.1366.768" timestamp="1631108863299" />
    <state width="1306" height="137" key="GridCell.Tab.0.left" timestamp="1631108863299">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state width="1306" height="137" key="GridCell.Tab.0.left/0.0.1366.768@0.0.1366.768" timestamp="1631108863299" />
    <state width="1306" height="137" key="GridCell.Tab.0.right" timestamp="1631108863300">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state width="1306" height="137" key="GridCell.Tab.0.right/0.0.1366.768@0.0.1366.768" timestamp="1631108863300" />
    <state x="258" y="67" key="new project wizard" timestamp="1631065544236">
      <screen x="0" y="0" width="1366" height="768" />
    </state>
    <state x="258" y="67" key="new project wizard/0.0.1366.768@0.0.1366.768" timestamp="1631065544236" />
  </component>
</project>
    i also got xml file instead of dart code in android studio.
