### ISSUE TITLE
Add const hints

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3233]
It would be nice to have some smart warnings (like the yellow light bulb) for when we forget to call a `const` constructor using the `const` keyword, saying something like  

>add  `const` before the constructor call to improve your app's performance.

**Comment by pq** [comment]
@feinstein: maybe the [prefer_const_constructors lint](http://dart-lang.github.io/linter/lints/prefer_const_constructors.html) is what you have in mind?

**Comment by feinstein** [comment]
Maybe... Is it on by default and I am not getting the lint hints on Flutter then?

**Comment by pq** [comment]
To enable that lint for your project, you'll need to add it to your `analysis_options.yaml` file.

See: https://github.com/dart-lang/linter/#usage

As a point of reference, this is the options file used to inform analysis of the Flutter repo:

https://github.com/flutter/flutter/blob/master/analysis_options.yaml

**Comment by feinstein** [comment]
Hmm I see, I will try this, thanks!

**Comment by pq** [comment]
Cool!  I'll close this one for now.  Feel free to re-open or file any feature requests on the linter (https://github.com/dart-lang/linter).

🍻

**Comment by feinstein** [comment]
I am starting to regret haha the code becomes harder to read with all those `const` before `Padding`, `Color`, `Text` and etc. I think I understand now why it was removed from the dafault lint options.

Speaking about them, where can I find the default lint options, so I won't redefine them myself on `analysis_options.yaml`?

**Comment by pq** [comment]
Yeah, `const` does add a bunch of noise. 😬 

The closest to a default set of rules that the ecosystem has are those defined in `package:pedantic`.  A bit more context here:

https://www.dartlang.org/guides/language/analysis-options#default-google-rules-pedantic

**Comment by feinstein** [comment]
Yeah, do you know if there's a compile option to insert const where it can be as an optimization phase (but no changing the actual code)?
