### ISSUE TITLE
Print out plugin version numbers

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#324]
#229 added support in `flutter doctor` for determining if the developer has the Dart and Flutter IntelliJ plugins installed.

This bug tracks an enhancement to also print out version numbers of those plugins, similarily to how we do for Atom:

```
$ flutter doctor
...
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38
```

CC @danrubel

**Comment by mit-mit** [comment]
@devoncarew what is the canonical way of determining the version of a .jar file?

**Comment by mit-mit** [comment]
Tentatively adding alpha milestone

**Comment by alexander-doroshko** [comment]
Plugin version is specified as a `<version>` tag (child of the root `<idea-plugin>` tag) in the `plugin.xml` file. 
`plugin.xml` is in the `META-INF` folder inside the plugin JAR.

**Comment by mit-mit** [comment]
Not critical for first milestone, bumping

**Comment by pq** [comment]
@danrubel is this on your radar?

**Comment by danrubel** [comment]
Yes, just not at the top of the list.

**Comment by pq** [comment]
Cool.  Thanks for the update!

**Comment by mit-mit** [comment]
@danrubel did you have a chance to look at this one?

**Comment by danrubel** [comment]
I just looked into this and we need to, as stated above, extract the version information from the `*.jar` file. Unfortunately, [the `package:archive` implementation](https://pub.dartlang.org/packages/archive) requires me to read the entire ~5Meg file into memory in order to extract a 2K text file from which I will extract the version information. I wish Dart had a lazy-load-from-file implementation that only read the information it needed from disk to access a single file. Maybe it does?

**Comment by mit-mit** [comment]
Doesn't look like it? https://github.com/brendan-duncan/archive/issues/12

Perhaps you could extract to a tmp dir, read the plugin.xml file, and then delete the tmp files again?

**Comment by mit-mit** [comment]
Actually reading the above again, I think it's only extracting the text file, not the full archive:

> Archive archive = new ZipDecoder().decodeBytes(zipBytes);
will decode the zip and store it in archive. However, the contents of the zip will not have been decompressed. When you access the content of a file in the Archive, such as
List jpg = archive.findFile('cat.jpg').content;

**Comment by danrubel** [comment]
Correct. Its reading ~5M of compressed data into memory, then decompressing 2K from that. Still not ideal but at some point, if it becomes important, we could help update `package:archive` to read compressed data from disk on demand.

**Comment by mit-mit** [comment]
Are you sure? Lasse mentioned that zip is designed so that you can decode a zip and get the list of included files without having to read the whole archive.

**Comment by danrubel** [comment]
No, not sure. Just glanced at the code and it seemed that's what I needed to do. Happy to have someone look over the PR above and make suggestions anytime.
