### ISSUE TITLE
Create a tool for getting the size of a Widget on a device

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3240]
It would be very helpful to have a tool that could measure a Widget in a running App.

Sometimes I have `RaisedButton` and its size isn't matching the one in my Designs Specs, so I would like to easily get its dimensions, but this isn't simple using Flutter Inspector.

**Comment by devoncarew** [comment]
cc @jacob314 for fyi

**Comment by jacob314** [comment]
Moved to the devtools repro as that is the place it is quicker for us to add experimental inspector features.

**Comment by jacob314** [comment]
https://github.com/flutter/devtools/issues/460
