### ISSUE TITLE
Flutter Inspector Jump to Source is disabled

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3241]
Flutter Inspector Jump to Source was working just fine, but now its disabled.

Since I upgraded my tools and Flutter to the latest version I am seeing some instability.

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git Framework • revision 8661d8aecd (2 weeks ago) • 2019-02-14 19:19:53 -0800 Engine • revision 3757390fa4 Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by devoncarew** [comment]
cc @jacob314 

> Flutter Inspector Jump to Source was working just fine, but now its disabled

@feinstein, just to be clear, the action in the Inspector is not enabled?

**Comment by feinstein** [comment]
Yes, I think this is related to how my flutter app was running, the Run green triangle didn't have the light green circle on it, but hot reload was working fine.

Maybe it was working as expected, I had to hit the Run button to enable it, if that's so, then I think a tooltip message explaining this would be welcome. 

I restarted IntelliJ, clicked to Run the app and it came back to work.

**Comment by devoncarew** [comment]
> I restarted IntelliJ, clicked to Run the app and it came back to work.

OK, thanks for the info. I think we'll close this issue as you're not seeing the problem an more, but we'll keep an eye out for similar reports.
