### ISSUE TITLE
New Flutter project not compatible with AndroidX

### ISSUE THREAD

**Issue by nitingupta910** [flutter/flutter-intellij#3244]
## Steps to Reproduce

- Create new Flutter project in Android Studio: File -> New -> New Flutter Project ...
- Add these dependencies to pubspec.yaml
```
  google_sign_in: ^4.0.1+1
  firebase_auth: 0.8.1+3
```

With these deps added, build fails since the new flutter project template does not create a project that is compatible with AndroidX and requires a manual migration to AndroidX to make it work.

Please fix the new project template so it creates an AndroidX compatible project.

## Version info
```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.2.1 at /Users/ngupta/flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ngupta/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ngupta/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/ngupta/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API
      28) (emulator)
    • iPhone XR                 • AAA759E2-C83D-41D6-9364-73565EA0CE72 • ios         • iOS 12.1
      (simulator)

• No issues found!
```

**Comment by devoncarew** [comment]
Thanks for the report! I think this is a known issue for the current version of Flutter; @cbracken might have more context.

Chris, should we move this over to flutter/flutter, or is there a better issue over there to track this?

**Comment by cbracken** [comment]
@mklim can provide the existing bug. 

We've also got b/126595196 open with the Android team on this.

**Comment by YulianD** [comment]
I have same problem

**Comment by Saifallak** [comment]
as per the merged PR (https://github.com/flutter/flutter/pull/31028) followed with (https://github.com/flutter/flutter/pull/34066) now templates have option to create with androidX support, can we get this option in intellij Plugin? for now i can create projects with androidX support or not using ```--[no-]androidx``` but it would be nice if it's in the GUI,

**Comment by devoncarew** [comment]
I opened an issue to track exposing this in Android Studio and IntelliJ: https://github.com/flutter/flutter-intellij/issues/3616

**Comment by devoncarew** [comment]
Closing in favor of #3616.
