### ISSUE TITLE
Track general usage with Google Analytics

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#325]

**Comment by mit-mit** [comment]
Assigning to self to get this specified.

**Comment by mit-mit** [comment]
PDD under review.

**Comment by mit-mit** [comment]
PDD was approved, Devon over to you for implementation!

**Comment by devoncarew** [comment]
\o/

**Comment by eseidelGoogle** [comment]
For those looking for Google Analytics with Flutter, check out https://github.com/flutter/plugins/tree/master/packages/firebase_analytics
