### ISSUE TITLE
Provide shortcuts for Theme.of() and similar

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3256]
Flutter doesn't have many boilerplate code, but still sometimes we need to do a lot of repetitive code such as `Theme.of(context)`, and many other with this same pattern.

It would be nice to have some templates ready for this, such as `stless` does for creating a new `StatelessWidget` class.

**Comment by pq** [comment]
Great idea.  Thanks @feinstein!

**Comment by feinstein** [comment]
My pleasure.

Thinking more about it, I think it would be useful to have several templates for the framework's `of(context)`, that would expand something like `thof` to `Theme.of(context)` and one for facilitating user implemented `InheritedWidget` that would expand `ihof` to `[complete-here].of`.
