### ISSUE TITLE
G3 Tracker for M34 Release

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter-intellij#3258]
Close when https://github.com/flutter/flutter-intellij/milestone/45 is closed.

**Comment by devoncarew** [comment]
Dave, feel free to create an M35 milestone, and add this issue to that.

**Comment by devoncarew** [comment]
Ping - is this on track for M35?

**Comment by DaveShuckerow** [comment]
Yes.  M34 is out.  Closing.

**Comment by devoncarew** [comment]
Ah, it'd thought this issues was about removing the user preference for the new bazel test runner. Do we have an issue for that?

**Comment by DaveShuckerow** [comment]
That one I think is simple enough to just solve: https://github.com/flutter/flutter-intellij/pull/3371
