### ISSUE TITLE
Confusing Android message

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#326]
Whenever I open a flutter project in IJ for the first time, I get this confusing message about Android:

![screen shot 2016-10-19 at 13 01 03](https://cloud.githubusercontent.com/assets/13644170/19516383/0c390900-95fc-11e6-9c2d-6b74290454b9.png)

```
12:59	Frameworks detected: Android framework is detected in the project Configure
```

Can we suppress this?

**Comment by mit-mit** [comment]
My bad, this only happens when you open a new project using `File->Open...`, not when you use `File->Create...`

**Comment by mit-mit** [comment]
@alexander-doroshko is there some way we can make the `File->Open...` workflow work for Flutter projects?

**Comment by alexander-doroshko** [comment]
Yep, ProjectOpenProcessor extension point should help. Devon filed https://github.com/flutter/flutter-intellij/issues/316 on behalf of me to track it.

**Comment by mit-mit** [comment]
Thanks, closing this bug then
