### ISSUE TITLE
Call stack stuck on "Loading...." when at a breakpoint in a Dart script in Android Studio

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter-intellij#3260]
I don't have IntelliJ installed, so I used Android Studio to run a simple Dart script while trying to track down another issue. I put a breakpoint on line 26, but when I hit it, the stack frames list just says "Loading...". I was trying to figure out whether the bug in VS Code was specific to something I'm doing, or if you have it too, but couldn't tell because I couldn't navigate the stack ;(

<img width="946" alt="screenshot 2019-03-07 at 2 43 23 pm" src="https://user-images.githubusercontent.com/1078012/53964625-9ac90880-40e7-11e9-8563-5997c1360a43.png">

The code I was running (with Dart v2.2.0):

```dart
void main() async {
  final func = "main";
  await func1();
}

Future<void> func1() async {
  final func = "func1";
  await Future.delayed(Duration(milliseconds: 1));
  await func2();
}

Future<void> func2() async {
  final func = "func2";
  await Future.delayed(Duration(milliseconds: 1));
  await func3();
}

Future<void> func3() async {
  final func = "func3";
  await Future.delayed(Duration(milliseconds: 1));
  await func4();
}

Future<void> func4() async {
  final func = "func4";
  await Future.delayed(Duration(milliseconds: 1));
}
```

**Comment by devoncarew** [comment]
What version of the dart plugin are you using? This sounds like the issue we had w/ an now on no sources for dart: libraries.

If it the same issue, this is addressed in a newer version of the plugin.

**Comment by DanTup** [comment]
Doh! I can even see a notification about an update in the screenshot now 😳 Indeed, it works on latest, thanks!
