### ISSUE TITLE
File descriptor leak in PluginConfig.load()

### ISSUE THREAD

**Issue by rsauciuc** [flutter/flutter-intellij#3263]
Android Studio 3.5 Canary 6 with Flutter plugin v33.3.2 runs out of file descriptors on Mac, subsequently failing every I/O call with "Too many open files".

A quick lsof inspection of the process showed ~10K entries for `config/intellij-plugins/flutter.json`.

One idea: does PluginConfig.load() close the InputStreamReader, or should that be a try-with-resources in 
https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/bazel/PluginConfig.java#L75 
(I don't know if GSON.fromJson() is supposed to close it.)

**Comment by devoncarew** [comment]
Thanks for the (very precise!) report. It does look like we're leading resources there.

**Comment by pq** [comment]
Super report.  That you @rsauciuc!

**Comment by Tywholland** [comment]
Nice! Thanks for the quick fix!
What's a good way to track which version of the Flutter plugin this fix will be in? I'd like to verify this is the root cause of another issue I've been seeing.

**Comment by pq** [comment]
It should be in the next release which will be 34.0.

You can see versions with changelogs here:

https://plugins.jetbrains.com/plugin/9212-flutter

**Comment by devoncarew** [comment]
Depending on @DaveShuckerow eval of the fix, if may be worth doing a patch release to capture this fix.

**Comment by DaveShuckerow** [comment]
I'm checking open files with `lsof -p <aswb pid> | wc -l` to count the number of open files.

Here's my results with the fix pulled down:

```
➜  google3 lsof -p 71205 | wc -l     
     140
➜  google3 lsof -p 71205 | wc -l
     140
➜  google3 lsof -p 71205 | wc -l
     145
➜  google3 lsof -p 71205 | wc -l
     145
➜  google3 lsof -p 71205 | wc -l
     142
➜  google3 lsof -p 71205 | wc -l
     140
```

I'm running ASWB 3.4 Beta 4.

**Comment by DaveShuckerow** [comment]
I think we should cherrypick this.

**Comment by devoncarew** [comment]
@DaveShuckerow, do you mind driving the cherry-pick and publishing process? I think it's documented enough, and you should have sufficient access; if not, please let me know and we can correct; thanks!
