### ISSUE TITLE
Unable to wrap widgets on function expressions "=>" - only works for function bodies. 

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3265]
Annoying use case I encounter a lot is this: 
<img width="566" alt="capture d ecran 2019-03-08 a 18 08 27" src="https://user-images.githubusercontent.com/2970449/54043643-6596e600-41cd-11e9-92fe-c94c8bf4ae11.png">

I want to wrap my `KiwiScaffold` into whatever widget, I can't because the IDE doesn't let me have the quick actions, I have to transform it into "block body" to be able to have those: 
<img width="386" alt="capture d ecran 2019-03-08 a 18 12 36" src="https://user-images.githubusercontent.com/2970449/54043809-c6262300-41cd-11e9-9492-3194e10888d6.png">

I should be able to do that into an expression body too.

**Comment by terrylucas** [comment]
Yep this is a problem.

For a example open the project flutter/examples/flutter_gallery

Open the file lib/gallery/demo.dart @ line 57

```
  void _showExampleCode(BuildContext context) {
    final String tag =
        demos[DefaultTabController.of(context).index].exampleCodeTag;
    if (tag != null) {
      Navigator.push(context, MaterialPageRoute<FullScreenCodeDialog>(
          builder: (BuildContext context) => FullScreenCodeDialog(exampleCodeTag: tag)
      ));
    }
  }

```
 this line will outline the problem

`          builder: (BuildContext context) => FullScreenCodeDialog(exampleCodeTag: tag)
`

click on the name FullScreenCodeDialog press ALT+ENTER,  displays the "Show intention actions Improve or optimize a code construct" menu.  Select "Add padding" nothing happens.  Functions with the "array syntax" will not change with the code construct menu - exactly as Jaumard states eliminating the => and using a function block {  ...  } then the "Add padding" item work.

```
          builder: (BuildContext context) {
             FullScreenCodeDialog(exampleCodeTag: tag);
         }

```
then the expected result of "Add padding" is:

```
          builder: (BuildContext context) {
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: FullScreenCodeDialog(exampleCodeTag: tag),
        );
      }

```

**Comment by stevemessick** [comment]
@scheglov

**Comment by scheglov** [comment]
Looks like https://github.com/flutter/flutter-intellij/issues/3500
Fixed in https://dart-review.googlesource.com/c/sdk/+/103563
