### ISSUE TITLE
Show some loading affordance when widget inspector is loading

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#3266]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

The widget inspector UI looks too firmly like nothing will happen when it's just loading. 

After running an app and opening the panel, the content just firmly says there are no running Flutter apps. 

After a second or 2, it'll then say the widget tree will be displayed here.

Then after another second or 2, it finally shows the actual tree. But along the process, it's essentially encouraging the user to leave since it seems like nothing will appear without any sort of indication that things are loading.

## Version info

[✓] Flutter (Channel tab-scaffold-tree-shape, v1.3.9-pre.17, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.3.9-pre.17 at /Users/xster/development/flutter
    • Framework revision dd5b566ce2 (15 hours ago), 2019-03-07 19:45:19 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xster/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xster/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[✓] Connected device (2 available)
    • PH 1   • PM1LHMA792602008                         • android-arm64 • Android 9 (API 28)
    • iPhone • cdcd493527f1f25a0ac91106540cf58186f2b4f0 • ios           • iOS 12.1.2

**Comment by pq** [comment]
Thanks for this @xster.

@jacob314: maybe something to consider for DevTools too?

**Comment by jacob314** [comment]
https://github.com/flutter/flutter-intellij/commit/9476dd80a9a5dbe1f0cde8797b11498efb75e8c7
Fixes the issue. Now the Inspector does not open until IntelliJ actually has a VM Service connecting to the application. At that point it should be a fraction of a second before the inspector populates. 
Let me know if it still feels slow and I'll add some loading UI.
Devtools doesn't have this issue as DevTools doesn't show up until there is actually a running VM Service.
