### ISSUE TITLE
Observatory button is enabled but doesn't work when running in release mode

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#327]
If you run a Flutter app with the Run button ("play" icon in the toolbar), then the Observatory button is enabled. However, clicking the Observatory button opens a browser tab on `about:blank`.

I think the Observatory button should be disabled when you are not debugging.

**Comment by stevemessick** [comment]
If you run a flutter app from the console you can open the observatory from the link printed to the console. We just need to change it so the URI isn't computed until after flutter has gotten connected. This should be a lot simpler that what we had to do to get the debugger connected.

**Comment by mit-mit** [comment]
Sounds good!

**Comment by stevemessick** [comment]
What I wrote above is misleading. `flutter run` launches the app in debug mode and the observatory is available. `flutter run --release` launches in release mode and there is no observatory. The IDE's Run button launches in release mode so we should not even have a button on the UI for the observatory.

The caveat is that for some targets, like simulators, there is no release mode, per se. It always runs in debug mode. I think we can ignore that case, keeping the story simple.

**Comment by stevemessick** [comment]
This is another consideration when resolving #362

**Comment by devoncarew** [comment]
I'm going to close this, since I believe this will be resolved as part of a refactor of the run and debug buttons.
