### ISSUE TITLE
Wrap with StreamBuilder should place caret at Type.

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3270]
The shortcut `wrap with StreamBuilder` generates a `StreamBuilder<Object>`. It would be nice to have the caret automatically at `<Object>` so we could fill in the type.

**Comment by pq** [comment]
Thanks for the input @feinstein.  This looks like an assist that's coming from the Dart Analysis Server.  @bwilkerson, @scheglov: I'm guessing this would just be a matter of updating the assist to use a linked edit?  (If it's not already?)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/96865

**Comment by feinstein** [comment]
That was quick :)
