### ISSUE TITLE
Clicking on test failure locations doesn't go to the location.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#3278]
## Steps to Reproduce

1) Run a flutter test that has a failure in it.
2) Look for the blue link to the failure location
3) Click (or Ctrl-click) on the link
4) Notice that nothing happens.

I think this used to take me to the location in the code where the test failed, but it currently doesn't. Here's a screenshot of what the link looks like that I'm expecting to work:

![image](https://user-images.githubusercontent.com/8867023/54226728-9e7bd700-44bb-11e9-96f5-87ebbdd87f35.png)

As it is now, I need to look at the output, find the line number and locate the file myself.

## Version info

```
[✓] Flutter (Channel focus_tree, v1.3.10-pre.30, on Linux, locale en_US.UTF-8)
    • Flutter version 1.3.10-pre.30 at /usr/local/google/home/gspencer/code/flutter
    • Framework revision bde12b6226 (19 hours ago), 2019-03-11 16:26:29 -0700
    • Engine revision 5ccee95373
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/google/home/gspencer/Android/Sdk
    • Java binary at: /usr/bin/X11/java
    • Java version OpenJDK Runtime Environment (build 9.0.4+12-Debian-4)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /opt/my-intellij-ce-2018.3
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[✓] Connected device (1 available)
    • Nexus 6P • 84B7N15A07007628 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by devoncarew** [comment]
What type of launch config are you using to run the test (we have 2 different launch configs for flutter tests I believe)?

Are there any suspicions exceptions in the IntelliJ log?

**Comment by gspencergoog** [comment]
The launch config claims to be a "Flutter Test" config.

The "Event Log" (which I think is the IntelliJ log you mean) doesn't have any exceptions in it.

**Comment by stevemessick** [comment]
This looks like https://github.com/flutter/flutter-intellij/issues/3106. The same logic from there should be added to the test result window.

**Comment by gspencergoog** [comment]
This is still happening to me.  Is there any more information I can provide?  It's slowing down my productivity. :-)
