### ISSUE TITLE
Dead code in src/io/flutter/actions/ReloadFlutterApp.java?

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter-intellij#3286]
From inspecting the reload app action, the shouldRestart pathway appears to never be used.

https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/actions/ReloadFlutterApp.java#L42

The RestartFlutterApp action handles the shift modifier key press, and I suspect that letting it do that is the more appropriate pattern to follow.

**Comment by devoncarew** [comment]
I'm able to hit that code path; from the 'hot reload' icon in the main toolbar, hold down shift when you hit it.

We'd added this UI affordance before we added the feature where you can do a hot restart via hitting the run/debug buttons for an app that's already running.

**Comment by DaveShuckerow** [comment]
That makes sense; closing.
