### ISSUE TITLE
Autocompletion freeze on "Colors."

### ISSUE THREAD

**Issue by Kriskev** [flutter/flutter-intellij#3289]
The choice of colors example "Colors.red" or something else blocks the IDE for 2 minutes, the autocompletion starts to lagg. I have an i7 processor so it's not my configuration the problem.

**Comment by devoncarew** [comment]
@Kriskev, is this every code completion for `Colors.red`, or just the first one after the IDE is started?

**Comment by Kriskev** [comment]
@devoncarew , No, it's only for the choice of a color. When I type "Colors." the IDE freeze.

**Comment by stevemessick** [comment]
Dup of https://github.com/flutter/flutter-intellij/issues/3202
