### ISSUE TITLE
Revisit/refactor Flutter project structure.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#329]
There's an ongoing conversation around Flutter project structure and in particular our choice to use an application library to track the Flutter SDK location.  This is a placeholder for a revisit of that decision.

/cc @alexander-doroshko

**Comment by alexander-doroshko** [comment]
https://github.com/flutter/flutter-intellij/pull/355

**Comment by pq** [comment]
Closing as work is under way in https://github.com/flutter/flutter-intellij/pull/361
