### ISSUE TITLE
Keybinding to "command-." (command period) binds as "command-A".

### ISSUE THREAD

**Issue by patniemeyer** [flutter/flutter-intellij#3295]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

Trying to bind command-. (command period, e.g. as one might want to bind for Run->Stop) to an action displays "A" in the keyboard shortcut dialog.  Strangely it functions as command-. but also triggers on lower case "a"!

## Version info

Latest Intellij IDEA Ultimate with the Flutter plugin.  Not sure if this is really a flutter issue but this is where it sent me.

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
I can reproduce this. It looks like a bug in the IntelliJ keyboard shortcut editor. The place to report such bugs is youtrack.jetbrains.com. And, it has already been reported and apparently a fix will be available soon: https://youtrack.jetbrains.com/issue/IDEA-183341
