### ISSUE TITLE
Device picker is missing

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#330]
After upgrading to 0.1.1, I no longer see the device picker:
![screen shot 2016-10-19 at 14 53 53](https://cloud.githubusercontent.com/assets/13644170/19519522/ac753834-960c-11e6-974a-d2bf4e0b07eb.png)

**Comment by mit-mit** [comment]
Environment info:

```
mit-macbookpro2:test1 mit$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/mit/dev/github/flutter
    • Framework revision 2cfc040572 (7 hours ago), 2016-10-18 22:41:09
    • Engine revision 269fd75d56
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/mit/Library/Android/sdk
    • Platform android-N, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[✓] IntelliJ IDEA Ultimate Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • Nexus 5X • 00ca05b380789730 • android-arm
mit-macbookpro2:test1 mit$
```

**Comment by pq** [comment]
Out of curiosity, do you see it if you open the "toolbar" view?

<img width="359" alt="screen shot 2016-10-19 at 6 04 33 am" src="https://cloud.githubusercontent.com/assets/67586/19519690/ea36d312-95c1-11e6-81b7-fda3ae4c016a.png">

**Comment by mit-mit** [comment]
Yup, if I toggle that 'on' I see it. If I toggle it to 'off' I also still see it, but after a restart of IJ it's gone again.

**Comment by pq** [comment]
Hmmmm.  I'm wondering if there isn't a condition where I can't reliably query the action for it's associated project.  (Possibly a race condition?)

cc @alexander-doroshko 

In the meantime, for local development, a work-around is to comment out lines 84-89 in `DeviceSelectorAction`.  I'll get this fixed pronto.

**Comment by alexander-doroshko** [comment]
In `update()` you have `setVisible(false)` somewhere but nowhere `setVisible(true)`, so once hidden it won't appear ever. Make sure that each logical branch in `update()` is sufficient.

**Comment by pq** [comment]
Yep, just caught that misstep. Thanks!
