### ISSUE TITLE
Flutter SDK and/or Dart SDK settings keep changing while Android Studio is running

### ISSUE THREAD

**Issue by Stargator** [flutter/flutter-intellij#3307]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

1. Running Android Studio on Mac
1. Change Dart SDK from flutter installed version to Homebrew installed 2.2.0. Click Apply and then OK.
1. After some time, maybe restart the IDE, notice that the `skip` parameter for a test method is not recognized as defined.
1. I will go to the settings and see that either the Dart SDK reverts back to the version used by flutter and/or the Flutter SDK is set as empty or undefined.

Manually changing the Dart SDK back to the version used by flutter may not correct the issue seen in the IDE. Going back to the setting, the Flutter SDK may have been changed by the IDE/plugin or the Dart SDK is re-set to the non-flutter installed version.

It's very hard to understand the logic. For the Dart SDK, I may even set it to look for updates on the Stable channel only and even that would get undone when the Dart SDK gets auto changed.

Look at the following screenshots (look at the time stamps to see how quickly the settings change on their own.

*  at 6:11:57 PM
<img width="909" alt="Screen Shot 2019-03-20 at 6:11:57 PM" src="https://user-images.githubusercontent.com/7527155/54723282-805a4a80-4b3d-11e9-841b-5aa289e3968b.png">

 *  at 6:12:06 PM
<img width="644" alt="Screen Shot 2019-03-20 at 6:12:06 PM" src="https://user-images.githubusercontent.com/7527155/54723283-805a4a80-4b3d-11e9-94af-ec5f8ef42390.png">

* at 6:12:18 PM I changed the Flutter SDK
<img width="672" alt="Screen Shot 2019-03-20 at 6:12:18 PM" src="https://user-images.githubusercontent.com/7527155/54723285-805a4a80-4b3d-11e9-9c01-6f8e11834a9d.png">

* at 6:12:43 PM, noticed it had no impact and the IDE still reported the same issue (`skip` not defined)
<img width="353" alt="Screen Shot 2019-03-20 at 6:12:43 PM" src="https://user-images.githubusercontent.com/7527155/54723287-80f2e100-4b3d-11e9-87f8-a6084f58289a.png">

* at 6:12:51 PM - Flutter remains unchanged
<img width="591" alt="Screen Shot 2019-03-20 at 6:12:51 PM" src="https://user-images.githubusercontent.com/7527155/54723288-80f2e100-4b3d-11e9-9535-591e8431af62.png">

* at 6:12:59 PM - The Dart SDK setting changed with no user input
<img width="758" alt="Screen Shot 2019-03-20 at 6:12:59 PM" src="https://user-images.githubusercontent.com/7527155/54723289-80f2e100-4b3d-11e9-9fff-553424d9fbb4.png">

* at 6:13:27 PM - Flutter is set as empty/undefined with no user input
<img width="741" alt="Screen Shot 2019-03-20 at 6:13:27 PM" src="https://user-images.githubusercontent.com/7527155/54723290-80f2e100-4b3d-11e9-94e5-6467d330e7aa.png">

## Version info
flutter doctor --verbose
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/User/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/User/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 183.5912.23

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by Stargator** [comment]
Note, I cannot try to reproduce this on IntelliJ Ultimate because it seems the flutter plugin is not compatible with the latest version of that IDE.

**Comment by stevemessick** [comment]
The Flutter SDK contains a Dart SDK that it is designed to work with. Manually setting the Dart SDK is not supported when the Flutter plugin is installed.

**Comment by Stargator** [comment]
@stevemessick, so can the flutter plugin disable changing the dart sdk?

**Comment by stevemessick** [comment]
Unfortunately, no.

**Comment by gregsheen** [comment]
@stevemessick I am having this same problem currently:
```
The current Dart SDK version is 2.10.0-4.0.dev.flutter-06cb010247.

Because flutter_tools depends on collection >=1.15.0-nnbd <1.15.0-nullsafety.2 which requires SDK version >=2.9.0-18.0 <=2.9.10, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)
Command 'pub upgrade' still failed after 10 tries, giving up.
```

I must have accidentally updated Dart SDK without updating Flutter. 

Do you know how I can resolve this?

**Comment by stevemessick** [comment]
> I must have accidentally updated Dart SDK without updating Flutter.

Interesting. I don't know how you would do that, but it does seem like it happened, from the version solving problem. Here's something that might work.

Open the preferences/settings for the Dart plugin. Clear the Dart SDK field and save. Then open settings/preferences for the Flutter plugin. Clear the Flutter SDK field and apply changes (you may have to save and re-open, not sure). Delete your Flutter SDK and re-install it to restore the embedded Dart SDK. Then set the Flutter SDK field to the new Flutter SDK. That will reset the Dart SDK to the one embedded in Flutter.

**Comment by gregsheen** [comment]
@stevemessick I am using VS Code and can't see how to clear the Dart SDK. 

Do you think deleting the Flutter SDK and just reinstalling it would work?

**Comment by stevemessick** [comment]
Possibly. I'm not familiar with VS Code, but getting a new SDK was the key point of my previous remark.
