### ISSUE TITLE
Switch statement cases not showing syntax error if a case is already present

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#3311]
## Steps to Reproduce
```
void test(){
  int a = 10;
  switch(a) {
    case 0: // looks OK
      break;
    case 0: // not OK, it should show syntax error
      break;
  }
}
```

## Version info
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by pq** [comment]
In Dart, that's not a syntax error...  The [no_duplicate_case_values](https://dart-lang.github.io/linter/lints/no_duplicate_case_values.html) lint flags the issue though.

Do you have any lints enabled in your project `analysis_options.yaml`?  (Some details in the [analysis options docs](https://www.dartlang.org/guides/language/analysis-options#the-analysis-options-file).)

**Comment by dark-chocolate** [comment]
@pq I don't have anything like `no_duplicate_case_values` in my `analysis_options_user.yaml` file.

**Comment by pq** [comment]
Perfect.  If you add a line to the `rules:` list,

 ```
    - no_duplicate_case_values
```

you should be good to go!

**Comment by dark-chocolate** [comment]
Did the trick. Thank you :)

**Comment by pq** [comment]
You're welcome!

> Edit: I wonder why it wasn't included in the file by default, and if I need to find more rules like this, where can I find them?

It looks like you derived your rules from Flutter project defaults.  That list is curated by the Flutter team and is based off the lints available a while back.  My guess is it's just fallen behind.

/cc @a14n
