### ISSUE TITLE
Usually get baffling Compiler message

### ISSUE THREAD

**Issue by LeesimEverglow** [flutter/flutter-intellij#3312]
![image](https://user-images.githubusercontent.com/13388550/54894160-4221aa00-4ef4-11e9-97b6-20169666d8b7.png)

just like this one , addAutomaticKeepAlives is used in 'package:flutter/src/widgets/scroll_view.dart'. Compiler tell me to correct it. this is baffling.

**Comment by jacob314** [comment]
Have you by any chance accidentally edited content in package:flutter?
Also, can you provide some details of what else you were doing recently.
For example, is addRepaintBoundaries listed in your watch window?
Did you recently update your flutter version?
What version of Flutter are you using and which OS are you on?
