### ISSUE TITLE
android studio inspector

### ISSUE THREAD

**Issue by lisong15** [flutter/flutter-intellij#3313]
![flutter-error](https://user-images.githubusercontent.com/15123628/54898663-245e4000-4f08-11e9-8c57-a14bcd8a3ae5.png)

In Android studio, start debugging widgets with errors and cancel without errors
![flutter-as](https://user-images.githubusercontent.com/15123628/54898784-769f6100-4f08-11e9-831b-c6f07fe45669.png)

**Comment by jacob314** [comment]
Thanks for the bug report. The fix needs to made on the package:flutter side.
https://github.com/flutter/flutter/issues/25707
