### ISSUE TITLE
The closing label comment shouldn't occupy space for the cursor

### ISSUE THREAD

**Issue by fibbers** [flutter/flutter-intellij#3314]
## Steps to Reproduce

See the screenshot: if I navigate through my code, the cursor is placed _after_ the closing comments. This means I have to navigate to the left to place the cursor between the `,` and the closing `// Text`. I'd expect that I wouldn't be able to navigate the cursor before and after the closing label comment.

![image](https://user-images.githubusercontent.com/138112/54914530-79448b00-4ef5-11e9-81ce-69703179991e.png)

To place this in context:
When debugging, the values are placed in comment labels in a similar fashion, but I _can't_ place the cursor after them, just like I would expect:
![image](https://user-images.githubusercontent.com/138112/54914654-bb6dcc80-4ef5-11e9-86ee-b2e5be56a3f7.png)

## Version info
IntelliJ:
```
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```

Flutter:
```
[✓] Flutter (Channel master, v1.3.14-pre.66, on Mac OS X 10.14.3 18D109, locale en-NL)
    • Flutter version 1.3.14-pre.66 at /opt/flutter
    • Framework revision 91b71ba964 (15 hours ago), 2019-03-24 16:18:43 -0400
    • Engine revision dcc72c7176
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

...
• No issues found!
```
And:
- Flutter plugin version: v33.4.2
- Dart plugin version: v183.5912.23

**Comment by stevemessick** [comment]
@devoncarew were you involved with this feature? If not, do you know who was?

**Comment by devoncarew** [comment]
@fibbers, I agree w/ your feedback here re: the cursor and closing labels. This is unfortunately the behavior we get from the underlying IntelliJ platform however. I'll close this issue (and cc @alexander-doroshko so he's aware of the feedback).
