### ISSUE TITLE
Autocompletion not working on VSCode after update to 1.3.8

### ISSUE THREAD

**Issue by Ibtesam-Mahmood** [flutter/flutter-intellij#3317]
I recently updated to Flutter version 1.3.8, after updating the auto completion on VSCode stopped working. However, this was working before the update.

<img width="637" alt="Screen Shot 2019-03-26 at 6 17 18 PM" src="https://user-images.githubusercontent.com/29645101/55037232-6f08b680-4ff3-11e9-92db-e039f4d297fe.png">

My flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.3.8, on Mac OS X 10.14.2 18C54, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[✓] VS Code (version 1.32.3)
[!] Connected device
    ! No devices available

**Comment by Ibtesam-Mahmood** [comment]
sorry this was posted in the wrong place

**Comment by jacob314** [comment]
No worries. Closing this issue as it is a VSCode bug.
