### ISSUE TITLE
Creating a plugin sample fails confusingly

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#3330]
Repro steps:
Open IntelliJ 2019 CE
Create a new project selecting the card Sample
You get this error
<img width="455" alt="Screen Shot 2019-03-28 at 12 58 46 PM" src="https://user-images.githubusercontent.com/1226812/55188806-6a5e1280-5159-11e9-8883-be2390925d0b.png">
And then rather being prompted to select a different sample, you get an empty project with no content.
<img width="929" alt="Screen Shot 2019-03-28 at 1 00 45 PM" src="https://user-images.githubusercontent.com/1226812/55188845-8792e100-5159-11e9-8246-9570fafe9d63.png">

Fyi @pq

**Comment by stevemessick** [comment]
I can reproduce this problem.

This command worked:
`flutter create --sample=material.Card.1 foo`

**Comment by devoncarew** [comment]
@DanTup, I believe @pq is out right now. Does this sound familiar? Did an index change, or do we need to update one?

**Comment by DanTup** [comment]
My guess is that this is a mismatch between the index being fetched by the plugin (from stable) and the docs your Flutter version is trying to download from (master). This is why we did https://github.com/flutter/flutter/pull/28938 - to avoid having to duplicate the branch-selection logic that's inside Flutter (it checks which channel you're on to try and use the best hostname) inside the editors.

This will likely only happen if you're on `master` flutter, and it will go away once https://github.com/flutter/flutter-intellij/issues/3303 is done.

**Comment by DanTup** [comment]
(the reason for the mismatch is that the IDs of the samples changed as part of https://github.com/flutter/flutter/pull/27793 to support multiple - they now have index numbers appended to the end)

**Comment by devoncarew** [comment]
closing in favor of https://github.com/flutter/flutter-intellij/issues/3303
