### ISSUE TITLE
auto import can't working when 'new' or 'const' appears in front

### ISSUE THREAD

**Issue by xiao-po** [flutter/flutter-intellij#3339]
## Steps to Reproduce

when i use auto import , i found some wrong condition. why plugin can't working when 'new' or 'const' appears in front ?  or it's a feature ?

![](https://github.com/xiao-po/readme_image/blob/master/image/flutter_auto_wrong_import_2.gif?raw=true)

## Version info

[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.17134.648], locale zh-CN)
    • Flutter version 1.3.8 at C:\Users\wly19\AppData\Local\flutter
    • Framework revision e5b1ed7a7f (3 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

dart plugin version : v191.6183.87
flutter plugin version: v33.4.3

**Comment by scheglov** [comment]
It was fixed with:
https://dart-review.googlesource.com/c/sdk/+/98161
https://dart-review.googlesource.com/c/sdk/+/94980

![image](https://user-images.githubusercontent.com/384794/55345733-7ef61f80-5465-11e9-9188-943d76e6cfea.png)

**Comment by stevemessick** [comment]
Thanks! That's a very recent fix, so it won't be available to Flutter until that version of the Dart SDK is incorporated into the Flutter SDK.
