### ISSUE TITLE
Missing console output when doing a Restart

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#334]
Repro steps:
1. Open some flutter app in IJ
2. Start a debugging session
3. Press hot reload button

Actual and expected: A small status update (`Reloaded 1 of ...`) is printed in the console.
1. Press restart ('Full Application Restart') button

Expected: A similar status update (`Restart performed in xxx ms.`) is printed
Actual: Nothing at all is printed to the console

**Comment by mit-mit** [comment]
Tagging 0.1 as this is what lead me to #332

**Comment by pq** [comment]
@stevemessick : is this on our side or is there a missing notification from the daemon?

**Comment by stevemessick** [comment]
This is working as designed. There is no console output from the daemon for a Restart. Doing a Hot Reload will print a line displaying the number of libraries that got reloaded. Eventually, it also displays how much time the reload took, but currently that's kinda broken -- it isn't emitted until after the next event and so the reload times are quite ludicrously long. See https://github.com/flutter/flutter/issues/6400 for a description of the intermittent problem I discovered.

We could add an artificial log message if that would help. Or we could get the daemon maintainers to add logging for restart.

**Comment by pq** [comment]
> We could add an artificial log message if that would help. Or we could get the daemon maintainers to add logging for restart.

@mit-mit : what do you think?

**Comment by mit-mit** [comment]
Sounds like this would be a pretty easy fix in the daemon? If not, lets as the artificial message on our side.

**Comment by mit-mit** [comment]
One additional inconsistency: If you to both reload and starts when not debugging (which is possible using keyboard shortcuts), then you get a message saying the app is not running *only* for reload. I find that odd, as this message is coming from the plugin, not the daemon:

[RestartFlutterAppKeyAction.java](https://github.com/flutter/flutter-intellij/blob/c943c8248808967d4b3c01b978c0677caf39bbc3/src/io/flutter/actions/RestartFlutterAppKeyAction.java)
[HotReloadFlutterAppKeyAction.java](https://github.com/flutter/flutter-intellij/blob/c943c8248808967d4b3c01b978c0677caf39bbc3/src/io/flutter/actions/HotReloadFlutterAppKeyAction.java)

**Comment by stevemessick** [comment]
Blocked on flutter/flutter#6400

**Comment by devoncarew** [comment]
Done! (fixed in flutter_tools)
