### ISSUE TITLE
Show color preview for Color.fromARGB and Color.fromRGBO

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#3347]
## Steps to Reproduce

Use the `Color.fromARGB` method or `Color.fromRGBO` method in your Flutter project. See an example below:

![image](https://user-images.githubusercontent.com/348942/55512396-e2c04a00-5617-11e9-86ff-57e77668dd18.png)

## Version info

[✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.3.13 at /Users/taodong/Development/flutter/flutter
    • Framework revision 59ce7d6bff (2 weeks ago), 2019-03-18 11:20:10 -0700
    • Engine revision e75f6de01f
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/taodong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 183.6156.11

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[!] Connected device
    ! No devices available

**Comment by tirth-aubergine** [comment]
Doesn't work in Android Studio too!

**Comment by devoncarew** [comment]
Fixed by https://github.com/flutter/flutter-intellij/pull/4695.
