### ISSUE TITLE
Remove FlutterCommand.localWebDevExe

### ISSUE THREAD

**Issue by jwren** [flutter/flutter-intellij#3348]
https://github.com/flutter/flutter-intellij/issues/3293

After the webdev lands in the Dart SDK in the Flutter SDK, remove the `FlutterCommand.localWebDevExe` field and associated code, test that the command line from `FlutterSdk.flutterRunWeb` works.

**Comment by devoncarew** [comment]
@jwren, has this landed? We roll the Dart sdk into Flutter fairly frequently.

**Comment by jwren** [comment]
Not that I know of, pinging folks that would know.

**Comment by DanTup** [comment]
What's the work that's required in the SDK? I thought it was all in the webdev pub package?

**Comment by jacob314** [comment]
webdev is a separate package but ddc work is part of the sdk.
To clarify, what functionality are you looking to have be part of the sdk?

**Comment by DanTup** [comment]
Ah, gotcha.

@jwren FWIW, I've been testing this using Flutter master, which currently has a Dart SDK from only a few days ago. I'm using a local clone of the webdev package to get latest changes, though there is a pre-release version on Pub that's about 6 days old.

**Comment by devoncarew** [comment]
related to https://github.com/flutter/flutter-intellij/issues/3293

**Comment by devoncarew** [comment]
I'm going to close this and track via the main issue.
