### ISSUE TITLE
Add flag supports into the webdev support

### ISSUE THREAD

**Issue by jwren** [flutter/flutter-intellij#3349]
After webdev has landed, add support for additional needed flags, i.e. if (mode == RunMode.DEBUG) { args.add("--debug"); }

https://github.com/flutter/flutter-intellij/blob/ab8a89b2c42e45ea914329e249bc1459edfef9c8/src/io/flutter/sdk/FlutterSdk.java#L279

**Comment by devoncarew** [comment]
related to https://github.com/flutter/flutter-intellij/issues/3293

**Comment by devoncarew** [comment]
I'm going to close this and track via the main issue.
