### ISSUE TITLE
Default keyboard shortcuts don't work

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#335]
Our default keybindings for hot reload and restart don't seem to work well:

_On macOS 10.11.6:_
- Hot reload:
  - Defaults to `cmd-F5`.
  - This launches the Mac 'VoiceOver' app for me.
- Restart:
  - Defaults to `cmd-shift-F5`.
  - This works.

**On Linux:**
- Hot reload:
  - Defaults to `ctrl-F5`.
  - Doesn't do anything at all
- Restart:
  - Defaults to `ctrl-shift-F5`.
  - Doesn't do anything at all

**Comment by mit-mit** [comment]
Suggestions for new keys. These work for me on both macOS and Linux:

* Hot reload:
  * Bind to `alt-r`.
* Restart:
  * Bind to `alt-e` (as in rEstart, also conveniently right next to `r`).

**Comment by mit-mit** [comment]
I am wondering if we go with `r` and `e`, would we then also change the shortcuts in `flutter run`. CC @johnmccutchan

**Comment by alexander-doroshko** [comment]
Hint: when looking for a vacant shortcut you can open IntelliJ IDEA Ultimate (with all plugins enabled), go to Preferences | Keymap and click 'Find Actions by Shortcut' button. It won't guarantee absence of conflicts with other Keymaps, other OSes and other plugins, but still may help to catch some conflicts.

**Comment by mit-mit** [comment]
@alexander-doroshko great tip, thanks. Just checked and the ones I proposed look free. Actually, doesn't look like alt is used much for shortcuts. Is there a reason to avoid using it?

**Comment by alexander-doroshko** [comment]
I've heard that Mac OS X by default handles Alt+Letter itself and doesn't delegate keypress to the app.

**Comment by stevemessick** [comment]
Confirming what Alex said:

I just test alt-r by binding it to Move Caret Backward a Paragraph and that seems to work. (Restart is currently broken in my dev env or I would have tested with that.)

It does not work with alt-e though. That inserts the acute accent prior to performing the keybinding action.

Using alt-anything on Mac may be confusing to people who are accustomed to typing in languages that require accents and other diacritical marks.

**Comment by mit-mit** [comment]
OK, new suggestions. Confirmed that these work on both macOS and Linux:

* Hot reload:
  * macOS: `ctrl-z`.
  * Linux: `alt-z`.
* Restart:
  * macOS: `ctrl-shift-z`.
  * Linux: `alt-shift-z`.

Perhaps not the most natural letter, but there are almost no unbound keys left on cmd and ctrl.

**Comment by johnmccutchan** [comment]
ctrl-z is "undo"

**Comment by mit-mit** [comment]
Not on a mac; it uses `cmd-z`.

**Comment by alexander-doroshko** [comment]
But you are going to add shortcuts to all keymaps, so with Ctrl+Z you may disable Undo action for Linux and Windows users.

**Comment by mit-mit** [comment]
I don't understand, are the keymaps not platform specific? I see lots of
keys being different across the two (e.g., the one for Debug)

**Comment by alexander-doroshko** [comment]
They are if plugin developer cares about it :)
Your current code in `plugin.xml` [contributes the same shortcut to all keymaps](https://github.com/flutter/flutter-intellij/blob/master/resources/META-INF/plugin.xml#L45).

**Comment by alexander-doroshko** [comment]
And on Windows/Linux Keymap choice is much bigger:
![image](https://cloud.githubusercontent.com/assets/4499789/19565724/8ddc58e6-96f0-11e6-8faf-0d7c74332ff6.png)

**Comment by sethladd** [comment]
just ran into this. I started "voiceover" on my mac :)

**Comment by johnmccutchan** [comment]
The default keyboard short cuts in IntelliJ are so bad that I feel like this is going to negatively impact the perception of Flutter.

A great example: CTRL+W does not close the open editor tab/window instead it "expands your text selection".

**A good developer experience requires sane and common keyboard shortcuts out of the box.**

**Comment by johnmccutchan** [comment]
Just to be clear my comment above is not specific to the plugin itself.

**Comment by devoncarew** [comment]
I suspect they won't blame the Flutter UX for IntelliJ keyboard shortcut choices.

I had some keyboard shortcuts to learn when I started using IntelliJ, but these were mostly things that are IDE actions, with different shortcuts per IDE. The platform shortcuts largely did what I expected. If things are behaving wildly different from what you expect you may want to change your keymap set. I have mine set to the default for the mac platform:

<img width="240" alt="screen shot 2016-11-04 at 11 13 44 am" src="https://cloud.githubusercontent.com/assets/1269969/20017279/1ec1b884-a280-11e6-8ee4-3288b4b39e6a.png">

**Comment by alexander-doroshko** [comment]
@johnmccutchan What is your OS / Keymap? Default keymap for Mac is "Mac OS X 10.5+" and it has Cmd+W for closing editor tab and Alt+Up for Extend Selection.

**Comment by johnmccutchan** [comment]
> I suspect they won't blame the Flutter UX for IntelliJ keyboard shortcut choices.

@devoncarew I strongly disagree. We are telling our users to download, install, and use IntelliJ with the Flutter plugin. If IntelliJ offers a bad UX, it is our problem.

@alexander-doroshko I run Linux why would I select Mac OS X keyboard shortcuts?

**Comment by johnmccutchan** [comment]
For the record, using Mac OS X keyboard mapping on Linux provides an even worse experience because everything is mapped to COMMAND+ instead of CTRL+. Why does IntelliJ even let users select keyboard map on Linux?

**Comment by alexander-doroshko** [comment]
> @alexander-doroshko I run Linux why would I select Mac OS X keyboard shortcuts?

Did someone advise you to use Mac OS X keymap on Linux? I do not think it is worth trying. Indeed, unlikely you have Command button. I'm afraid I do not know why there's an option to select Mac specific keymap on Linux.

For closing active editor tab I got used to `Ctrl+F4` shortcut, which seems to be pretty common.

As for `Ctrl+W` that stands for 'Extend selection' I think that the reasons are historical. This action and shortcut were introduced in IntelliJ IDEA in 2000 and I believe at that time `Ctrl+W` was not that common for closing active tab in other apps. Probably JetBrains doesn't want to change the meaning of this shortcut, in order not to surprise existing users who got used to it.

**Comment by raju-bitter** [comment]
Mac keymap on Linux: Those setups might make sense \if you use a Mac keyboard (e.g. external) with Linux running on a Macbook. Or virtualized Linux running in OS X. But it's still ugly.

**Comment by mit-mit** [comment]
OK, latest (and greatest?) suggestion:

* Hot reload:
  * macOS & Linux: `ctrl-,`.
* Restart:
  * macOS & Linux: `ctrl-shift-,`.

Tested with both the 'Mac OS' and 'Default for XWin' keymaps.

@pq WDYT?
