### ISSUE TITLE
Flutter outline doesn't work when the widget is wrapped into builder 

### ISSUE THREAD

**Issue by humazed** [flutter/flutter-intellij#3357]
## Steps to Reproduce

when wrapping my widget tree with any widget that uses the builder pattern like `StreamBuilder` the flutter outline fails to show the descendant of that widget.

![image](https://user-images.githubusercontent.com/8838182/55682141-99ca0780-592f-11e9-9c46-85bd79b38e05.png)

without `StreamBuilder` it works as expected.

![image](https://user-images.githubusercontent.com/8838182/55682162-e6154780-592f-11e9-80bd-5b1f62b39ac5.png)

## Version info

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
    • Flutter version 1.2.1 at D:\AS\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AS\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\AS\sdk
    • Java binary at: C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\191.5375575\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\AS\as_stable
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5400832
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\191.5375575
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\183.6156.11
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.6183.87
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

**Comment by jacob314** [comment]
Making the analyzer support showing the build outline for cases like this would also help a lot for the build method guide feature we are working on.

**Comment by devoncarew** [comment]
done?
