### ISSUE TITLE
Flutter Inspector is not showing 

### ISSUE THREAD

**Issue by DevToDipesh** [flutter/flutter-intellij#3359]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

When I install Flutter in the android studio. It only shows Flutter outline. Flutter Inspector is disabled and I unable to open it. 

![Screenshot (2)](https://user-images.githubusercontent.com/38078787/55687007-96fa0180-5985-11e9-84d6-f548f98b2645.png)

Please help me for the same I want to see and learn the preview of activities. I am attaching the screenshot for the same.

## Version info
       Android Studio (version 3.3)
    •   Flutter plugin version 34.0.1
    • Dart plugin version 182.5215

**Comment by stevemessick** [comment]
The inspector and memory profiler should be available when a Flutter app is running. I can't tell from the screenshot if it is. Try restarting your app. If that doesn't help please append the output of `flutter doctor -v`.

/cc @jacob314

**Comment by Mosamisa** [comment]
I am experiencing the same issue: the flutter inspector won't appear.  It is not even possible to select it in the Tool Window http://prntscr.com/np3vlt 

Flutter version 1.5.4-hotfix.2 
Framework revision 7a4c33425d
Engine revision 52c7a1e849
Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by StefanBols** [comment]
I've the excact same problem,

I'm running Windows 10 Pro and have an Android app started on an emulator. The Flutter Inspector seems to be disabled.

When starting the app I get this result in the console:
`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:54783/9ycl9WsP0Eo=/ws`

Maybe this is related?
Android Studio and plugins are updated to latest versions.

Flutter doctor command result
`flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.116], locale en-DK)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[!] VS Code (version 1.34.0)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.`

CC: @stevemessick, @jacob314

**Comment by GasparPizarro** [comment]
@StefanBols And which is that workaround? did you use an real device? because I ran my code in one and the Flutter inspector is still disabled.

**Comment by lim-enhui** [comment]
i am facing same issue too...

**Comment by lim-enhui** [comment]
android studio -> preferences -> languages & frameworks -> flutter -> App Execution ->Open Flutter Inspector view on launch

**Comment by StefanBols** [comment]
> @StefanBols And which is that workaround? did you use an real device? because I ran my code in one and the Flutter inspector is still disabled.

@GasparPizarro I just created a new emulator with "Emulated Performance" setting set to "Auto" and the SDK as Pie instead og Q. Then it worked for me.

**Comment by Emy101** [comment]
> > @StefanBols And which is that workaround? did you use an real device? because I ran my code in one and the Flutter inspector is still disabled.
> 
> @GasparPizarro I just created a new emulator with "Emulated Performance" setting set to "Auto" and the SDK as Pie instead of Q. Then it worked for me.

This worked for me; flutter outline tab finally activated

**Comment by rookie-12** [comment]
you have to just wipe data by right clicking on emulator in avd manager

**Comment by pandeyvineet** [comment]
"I just created a new emulator with "Emulated Performance" setting set to "Auto" and the SDK as Pie instead of Q. Then it worked for me" doesn't work ,Flutter inspector still not showing.

**Comment by AntonyLeons** [comment]
okay I think I found the solution, I think the problem is android studio does not detect flutter run in the terminal.

using the green play button or shift +  F10 fixed this for me.

**Comment by EArminjon** [comment]
Have the problem since intelij 2021, no view => tool window => flutter related things...
