### ISSUE TITLE
Unwanted scroll on auto code formatting

### ISSUE THREAD

**Issue by humazed** [flutter/flutter-intellij#3364]
## Steps to Reproduce

When formatting a dart file the cursor jumps up 10 lines or so, this doesn't happen in all dart files, I notice it happens in a file that contains many Flutter widgets.

I could provide a video if there a problem with reproducing this behavior.

## Version info

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
    • Flutter version 1.2.1 at D:\AS\flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AS\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\AS\sdk
    • Java binary at: C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\191.5375575\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\AS\as_stable
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5400832
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\191.5375575
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\183.6156.11
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Users\huma\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.6183.87
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.32.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.0

**Comment by devoncarew** [comment]
Thanks for the feedback! This is likely an IntelliJ platform issue. It looks like you have several versions of IntelliJ and Android Studio installed; which IDE and version were you seeing this with?

**Comment by humazed** [comment]
I'm currently using android studio 3.3

However I remember having the same problem in other version but I'm not
sure, I will test with another version to see if the same problem exist.

**Comment by jsa-nic** [comment]
I'm on Android Studio 3.3.2 and experience the issue perhaps once an hour or so, I haven't been able to identify a way to reproduce the issue. I thought it always jumped to the bottom of the file, but I'm unsure.

**Comment by humazed** [comment]
I found a solution, go to `C:\Users\<your user name>\AndroidStudio3.4\config\codestyles\Default.xml`

and search for dart and any custom attributes there.

for me was only a LINE_BREAK attribute.

I won't close this issue as it needs to be fixed but at least there is a solution for anyone who is struggling with it.

**Comment by stevemessick** [comment]
The formatter has been replaced, making this issue obsolete.
