### ISSUE TITLE
No autocomplete support for the 'break' keyword in switch statements

### ISSUE THREAD

**Issue by ShivamArora** [flutter/flutter-intellij#3367]
## Steps to Reproduce
Use a switch statement for any logic.
Example:
```dart
switch(priority){
  case 1:
       //do something
       break;
  case 2:
      //do something
    break;
  default:
    //do something
}
```

## What went wrong_
There's no autocomplete support for the `switch`, `case`, `default`, `return` and `break` keywords.

## Version info
Flutter version: 1.2.1
Flutter Plugin version: 34.0.1

**Comment by devoncarew** [comment]
Thanks for the feedback! I'll move this to the dart sdk repo - this would be addressed in the analysis server.

Can you provide the IDE that you're using and the version. When reproing this myself, I see completion for all but the `break` keyword.

**Comment by ShivamArora** [comment]
@devoncarew I'm using Android Studio v3.3.2
