### ISSUE TITLE
File links in crash logs are not working as expected

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3368]
When I get a crash, logs normally allow me to click on related file to open them directly on the right file / line number. 

Problem is that most of the time it didn't open the file, or not the right one :( 

I made a video to show you the problem:  
[logs.mov.zip](https://github.com/flutter/flutter-intellij/files/3068780/logs.mov.zip)

I'm using:
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale fr-FR)
    • Flutter version 1.2.1 at /Users/jaumard/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

• No issues found!

```

**Comment by devoncarew** [comment]
Thanks for the report!

@pq, it looks like the logging console might have issues with jumping to source locations. From the video, it does look like it correctly identifies stack trace lines, but - perhaps after the first click - doesn't always jump to a location when clicked, or doesn't jump to the correct location.

<img width="840" alt="Screen Shot 2019-04-14 at 7 57 28 PM" src="https://user-images.githubusercontent.com/1269969/56105184-cf529000-5eef-11e9-888b-c30b8c634152.png">

**Comment by pq** [comment]
Thanks for the report @jaumard.  Will take a look!

**Comment by jaumard** [comment]
Any news on that one ? :) it never open the right file when it actually open one lol pretty annoying ^^ thanks :)

**Comment by pq** [comment]
Sorry, no progress just yet.  Have added it to our current milestone though and will take a look.

**Comment by jaumard** [comment]
Thanks @pq ! :)
