### ISSUE TITLE
Flutter Device selector disappeareed

### ISSUE THREAD

**Issue by genesiscz** [flutter/flutter-intellij#3369]
Hello. I somehow made the device selector disappear. In Customise Menus and toolbars I do see Flutter.DeviceSelector in place, but it does not show next to entry file. It is possible that it happened after trying to migrate the project to Windows from MacOS (was playing with some project settings), but I have no idea how. What might be the possible cause?

If i run `flutter emulators`, I see the iPhone simulator in place and I can `flutter run` after `flutter simulators --launch apple_ios_simulator`.

**Comment by genesiscz** [comment]
I've been struggling with this issue for few hours and I just fixed it now - my Flutter SDK path was set to empty, probably because of the Windows. Some ideas on how can I share the project for both without having to re-setup everything (currently using Dropbox)?

**Comment by devoncarew** [comment]
@genesiscz, what I think happened was that either the project metadata contained a path to the flutter sdk from the previous machine, or that the project metadata didn't travel along to the new computer. Sounds like setting the flutter sdk addressed this.

The `.gitignore` that `flutter create` creates is correct wrt intellij metadata. You should just need to commit the project to git, and then in a clone, set the sdk for the IDE using that close.
