### ISSUE TITLE
Device selector does not appear for newly created project

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#337]
I'm testing the create/first-run flow in IntelliJ, and I don't seem to get a device popup for my newly created project.

![screen shot 2016-10-19 at 8 28 12 am](https://cloud.githubusercontent.com/assets/11857803/19525542/1f133792-95d6-11e6-8409-ca86469a8127.png)

I don't have any devices connected or simulators.

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /src/flutter
    • Framework revision 4c9b275d93 (9 weeks ago), 2016-08-15 16:10:57
    • Engine revision 269fd75d56
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • None
```

**Comment by eseidelGoogle** [comment]
Maybe the device selector has just been removed.  I launched a simulator and then turned the debug button green and seems to know how to run things on it. :)

**Comment by pq** [comment]
Not removed!  Just suppressed by mistake (#330).  Fixed plugin now available for your enjoyment.  Update and all should be well! 👍
