### ISSUE TITLE
Refresh Widget Info doesn't

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#3370]
Start the sample Flutter app, as if testing a release candidate. Open the Inspector and select row 6, the first Text widget (0-based). Note the text in the details pane matches the editor.

Find the text for that widget in the editor and change it. Click `Hot Reload` and see that the text on the text device is updated. Go the the Inspector and click the `Refresh Widget Info` button.

Expected: details pane text matches the editor
Observed: details pane text is unchanged from before editing

I'm using Android Studio 3.3.2 with Flutter plugin 34.0.1.

**Comment by devoncarew** [comment]
@jacob314 - it sounds like the information in the inspector is not up-to-date, even after an explicit `Refresh Widget`

**Comment by stevemessick** [comment]
Closing as likely obsolete.
