### ISSUE TITLE
Intellij 2019, Intellisense is not working as expected

### ISSUE THREAD

**Issue by esenmx** [flutter/flutter-intellij#3376]
I was able to use 2018 version without any problem for Flutter development. After the 2019 update now intellisense is not working as expected.

It's suggesting everything by alphabetically instead of checking relations between parents/fields first then alphabetically.

[YouTrack Issue Page](https://youtrack.jetbrains.com/issue/IDEA-209983).

May be we need some fix on Flutter plugin too.

## Version info

Intellij 2019.1 & Intellij 2019.1 + JBR 11
MacOS Mojave & Ubuntu 18.10 & Solus 4 (I test it on couple of Linux distros and two different macs)
Flutter 1.2.1
Latest Flutter and Dart Plugins

## Flutter Doctor:

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/esen/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/esen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/esen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/esen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0
      (API 27) (emulator)

• No issues found!

**Comment by pq** [comment]
@softronaut: could you attach a screenshot of the completions you're seeing?  Also, paste the output of running `flutter doctor -v` ?

Thanks!

**Comment by softronaut** [comment]
> @softronaut: could you attach a screenshot of the completions you're seeing? Also, paste the output of running `flutter doctor -v` ?
> 
> Thanks!

Done, I'm developing in Android Studio right now , I can create another doctor log for Intellij if you want.

**Comment by pq** [comment]
Thanks @softronaut.  Could you send a screenshot of the code completions you're seeing?

**Comment by softronaut** [comment]
I just got two new screenshots.
This guy is the popular one form YouTrack: :) 
<img width="1920" alt="Screen Shot 2019-04-17 at 5 43 31 PM" src="https://user-images.githubusercontent.com/43244505/56297209-9e18d080-6138-11e9-8c68-9779fd26eb90.png">

This is another simple example:
<img width="1920" alt="Screen Shot 2019-04-17 at 5 43 57 PM" src="https://user-images.githubusercontent.com/43244505/56297328-d02a3280-6138-11e9-8e97-efac68a85393.png">

**Comment by alexander-doroshko** [comment]
'flutter doctor' seems to be from one computer but screenshots - from another. @softronaut am I right?
- I guess the problem on the first screenshot is that items like `ThemeData.xxx()` are not at the top of the completion list (or maybe not in the list at all?)
- As for the second screenshot, I don't see any problem. I think it has always been the same.

**Comment by softronaut** [comment]
> 'flutter doctor' seems to be from one computer but screenshots - from another. @softronaut am I right?
> 
> * I guess the problem on the first screenshot is that items like `ThemeData.xxx()` are not at the top of the completion list (or maybe not in the list at all?)
> * As for the second screenshot, I don't see any problem. I think it has always been the same.

@alexander-doroshko same computer.
I launched Intellij for demonstrating the problem but I was using Android Studio while creating flutter doctor log, I think that's why you thought it was different computer.

- Yes, I just realized it's not even available in the list and take this like symbolic. In every widget we have same problem.

- Same project, almost same scroll level in Android Studio:
<img width="1920" alt="Screen Shot 2019-04-17 at 6 47 31 PM" src="https://user-images.githubusercontent.com/43244505/56301866-5f3b4880-6141-11e9-9b48-1645da68f16d.png">

**Comment by alexander-doroshko** [comment]
`flutter doctor` should list all IDEs, it doesn't care if it is launched or not. Ok, nevermind.

I guess, missing items like `ThemeData.xxx()` at the top of the completion list after `darkTheme:` is a question for @scheglov

**Comment by alexander-doroshko** [comment]
As for the 2nd screenshot, I see a problem with the `Widget` item. It appears 3 times in the list (with different package info) but in fact, it's the same `Widget` class. //cc @scheglov for ideas.

**Comment by scheglov** [comment]
1. Suggesting constructors (is this the problem with `ThemeData.xxx()`?) was implemented / restored in https://github.com/dart-lang/sdk/commit/9b77e4c507f28b730599b6386ddde989a0ad93dd
2. Showing `Widget` 3 times with different potential imports was thought as a feature - you can choose how to import. The library that is already imported is on the top. It might also be possible to refine this some more, for example do suggest other libraries when the class is already available in an already imported library. But I have not thought yet implications for amounts of data to transfer and computation to do. I will need to make an experiment at some point.

**Comment by adaamohi** [comment]
i have same problem here,
When creating new widget and typing the new keyword before it for e.x. new Conta and clicking tab I do get the full completion for that widget (new Container()). When I don't use the new keyword and try to tab for autocomplete a just get the widget name like so Container
this happen in intellij 2019.1>>>

![Screenshot (19)](https://user-images.githubusercontent.com/33015580/56756782-d6e92300-6792-11e9-96f1-75424c6d0111.png)

when press tab 
here we go 
![Screenshot (8)](https://user-images.githubusercontent.com/33015580/56756800-e5373f00-6792-11e9-928e-15aa94220245.png)

i just want to this only 

![Screenshot (20)](https://user-images.githubusercontent.com/33015580/56756826-f1bb9780-6792-11e9-93ba-a56135461895.png)
 no need other item or package one just what i mark

**Comment by alexander-doroshko** [comment]
@adaamohi, as far as I understand, your question is about class name completion vs constructor completion. According to @scheglov, the latter will be back with the next flutter sdk update.

**Comment by adaamohi** [comment]
> @adaamohi, as far as I understand, your question is about class name completion vs constructor completion. According to @scheglov, the latter will be back with the next flutter sdk update.

https://github.com/flutter/flutter-intellij/issues/3415
check here please for what i mean

**Comment by siddharth952** [comment]
I was able to fix the problem by moving to the beta channel. You can do so by

```
flutter channel beta
flutter update --force
```

**Comment by softronaut** [comment]
> I was able to fix the problem by moving to the beta channel. You can do so by
> 
> ```
> flutter channel beta
> flutter update --force
> ```

Nice to know, but I can't do that because I'm working as fulltime Flutter developer in a company :( At home will do surely!

**Comment by softronaut** [comment]
> I was able to fix the problem by moving to the beta channel. You can do so by
> 
> ```
> flutter channel beta
> flutter update --force
> ```

I forgot to inform, this does not work for me still. I think we need wait for Andorid Studio 3.5 update since it's based on IntelliJ 2019, and back by Google :)

**Comment by softronaut** [comment]
With Dart 2.5 ML code completion added. So is that means we won't have IDE based suggestion/completion anymore?
