### ISSUE TITLE
Update change-notes (for 0.1.1 and 0.1.2).

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#338]
I'd like to see us get into a habit of doing this in general.

**Comment by pq** [comment]
Should we include issue numbers where appropriate?  I generally do this but curious what you all think.

/cc @mit-mit @devoncarew @stevemessick

**Comment by pq** [comment]
As a point of reference, here's what the `0.1.2` update looks like in the IDE:

![screen shot 2016-10-19 at 9 01 34 am](https://cloud.githubusercontent.com/assets/67586/19526843/a063170a-95da-11e6-9f5b-4ce2d6d5ed0d.png)

**Comment by devoncarew** [comment]
+1 to release notes - a very nice feature for users when they see there's a new update

> Should we include issue numbers where appropriate?

I'm not sure they add value, over just having a concise description of the user facing change
