### ISSUE TITLE
Support for adding Flutter Module Type to existing projects.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#341]
From #233, @stevemessick notes:

> With the latest version you cannot continue working on a project that was created with an earlier version of the Flutter plugin. The problem is that we only recently started marking Flutter projects with a module type and old projects do not have that. The solution is to create a new project pointing to the same source directory, and overwrite existing files (.idea, *.iml). The symptom is that there is no device selector in the tool bar.

FWIW, the Dart plugin supports this in it's preference page.

<img width="789" alt="screen shot 2016-10-19 at 9 32 29 am" src="https://cloud.githubusercontent.com/assets/67586/19527949/f40d56aa-95de-11e6-9f06-6e7fcae7c463.png">

Depending on how we settle #329, we might consider doing something similar.

/cc @alexander-doroshko

**Comment by alexander-doroshko** [comment]
Dart support doesn't care about module type, so nothing in common here with Flutter unless you decide to get rid of Flutter module type for some reason.
Flutter is closer to Go plugin in this regard. See [WrongModuleTypeNotificationProvider](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/671943ad70ec7f1c4e2b59662cdb06d84f81cf1c/src/com/goide/inspections/WrongModuleTypeNotificationProvider.java).

**Comment by pq** [comment]
> Dart support doesn't care about module type, so nothing in common here with Flutter unless you decide to get rid of Flutter module type for some reason.

Sorry, wasn't clear...  What I mean is that the Dart plugin, in Preferences, provides a means to add Dart support to existing projects.

Having said that, I like Go's solution.  An inspection would be perfect here actually.

Thanks! 👍

**Comment by alexander-doroshko** [comment]
> Sorry, wasn't clear... What I mean is that the Dart plugin, in Preferences, provides a means to add Dart support to existing projects.

Sorry for not being clear, I meant that there can be nothing in common in the implementation of 'Enable support' feature (regardless of #329), because it is not possible to change module type on the fly, you need to reload project.

**Comment by pq** [comment]
Great clarification.  Thanks!  Unfortunate that a restart is required but I still think it's very much the right approach.  In particular, I'd like to take your cue from Go and add an inspection that asks the user if they want to "Enable Flutter support", when a project is detected that

  * does not already have the Flutter module type, and
  * looks Fluttery which I take to be:
    * having a `flutter.yaml` file in the root directory

This should address @stevemessick's initial issue and has the added advantage of not adding a bunch of (potentially unneeded) UI in preferences or elsewhere.
