### ISSUE TITLE
Flutter device selection dissapeared

### ISSUE THREAD

**Issue by rayhvh** [flutter/flutter-intellij#3416]
Flutter device selection dissapeared, Project not regonized as flutter ?
Good project. as should be
<img width="993" alt="Schermafbeelding 2019-04-25 om 08 54 43" src="https://user-images.githubusercontent.com/7458738/56717483-066d4080-673d-11e9-884a-527d52f4d551.png">
Bugged project. 
<img width="993" alt="Schermafbeelding 2019-04-25 om 08 56 11" src="https://user-images.githubusercontent.com/7458738/56717512-171db680-673d-11e9-93ec-de3945720609.png">

## Steps to Reproduce

1. create flutter project on Android studio, newest version. OSX in documents ->flutter -> project name.
And code some stuff. run some stuff
2. create folder with same name in documents -> github -> project name
Close IDE, Move all files. also hidden ones. into this new folder.
3. Open IDE. Open folder of project form github folder

Things I tried: Moving back the folder and everything to original location. 
Playing with .gitnore. 

no results. I don't want to re-create a flutter project just to move its location and copy all of my code and settings manually.. 

## Version info
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale nl-NL)
    • Flutter version 1.2.1 at /Users/raymond/dev/flutter
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/raymond/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPad (6th generation) • 23F7853B-BD8C-45E4-9519-72C7C6583FAF • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

**Comment by stevemessick** [comment]
From the screen shots, it appears the real issue is changing the app name. Flutter does not have a way to change the name of a project. Currently it is a manual process as described in https://stackoverflow.com/questions/51534616/how-to-change-package-name-in-flutter
