### ISSUE TITLE
Make Observatory wait time configurable

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#342]
The amount of time allowed by the plugin to establish communication with the Observatory keeps growing. It started at 10s and almost immediately jumped to 30s. Then it changed to 60s and is now 90s. That suggests to me that it needs to be configurable by the user. We could add a place in the preference page to adjust it.

**Comment by alexander-doroshko** [comment]
Instead of a configurable setting IDE could wait for connection for a very long time showing some cancelable progress to the user. This way user understands what is going on, has control on the process and doesn't have to think about 'What is this option a about and what should I set it to'.

**Comment by stevemessick** [comment]
I have seem a modal progress indicator that would work, except that it is modal. Is there a non-modal one as well? If so, that sounds even better than an obscure preference setting.

**Comment by devoncarew** [comment]
It seems like we could wait a long time, and the user could use the 'stop' debugger/process button if things weren't progressing?

**Comment by alexander-doroshko** [comment]
It can be a modal progress, non-modal progress, some spinner right in the Debug tool window or simply a text (I think 'Trying to connect the Dart VM' is already showing). Yes, Stop button is there and I hope it works.

**Comment by devoncarew** [comment]
I believe we've handled this is other ways.
