### ISSUE TITLE
Desktop embedding: device doesn't show up

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter-intellij#3426]
In the new desktop embedding the computer shows up as a normal flutter devices:
```
$ flutter devices
2 connected devices:

Nexus 5 • 043f5475251bc8f5 • android-arm • Android 8.1.0 (API 27)
Linux   • Linux            • linux-x64   • Linux
```

Why doesn't this device show up in the list? Apparently the list is filtered. To make the computer appear, only this filter has to be adjusted. No new command syntax is introduced.

**Comment by kenzieschmoll** [comment]
Thanks for the feedback. I'm not sure I understand your problem here. Are you saying that there is another device you expect to be in the list that is not there? 

Or is the sample you provided the output after you "adjusted the filter"? If so, what exactly did you do to "adjust the filter"?

Additionally, if you could run `flutter doctor` and copy the output to this issue, that would be helpful. Thanks!

**Comment by jld3103** [comment]
I mean the desktop device doesn't show up in the device list.
My assumption was that the devices get filtered.

**Comment by devoncarew** [comment]
We need to do some work to figure out the right UX for persistent devices (like desktop devices). That discussion is planned but hasn't happened yet.

cc @jonahwilliams @stuartmorgan

**Comment by stuartmorgan** [comment]
See also https://github.com/flutter/flutter/issues/30724 for some discussion.

As for the specific question in the original report:
> Why doesn't this device show up in the list?

The specific answer right now is that desktop devices only show up if `ENABLE_FLUTER_DESKTOP` is set to `true` in the environment; if it's showing up when you run `flutter devices` but not in your IDE, then you have the environment variable set for your terminal, but not for the context where your IDE is running the Flutter daemon.

**Comment by jld3103** [comment]
Where do I set this environment variable? I have already set it in .bashrc

**Comment by stuartmorgan** [comment]
Assuming the IDE isn't scrubbing the environment variables when it launches the daemon (@devoncarew, do you know if that's the case offhand?), you'd set it wherever you would normally set environment variables that you want to be set for UI processes. That varies by OS, and potentially with the details of how you are launching the IDE. (For instance, on macOS, `.bashrc` variables definitely don't get set for applications, and there's a completely different mechanism for that.)

You'd need to look for documentation/support resources for your specific OS to find out how to set environment variables for UI processes.

**Comment by jld3103** [comment]
I tried putting it in ```/etc/environment``` and it worked

**Comment by modulovalue** [comment]
For those looking to make it work in IntelliJ & Mojave
Putting `setenv ENABLE_FLUTTER_DESKTOP=true` in `/etc/launchd.conf` did the trick for me.

**Comment by shayneoneill** [comment]
Not getting a lot of luck here:
$ export ENABLE_FLUTTER_DESKTOP=true
shayneoneill@Shaynes-MacBook-Pro ~/Downloads/test 
$ flutter devices
1 connected device:

iPhone 11 Pro Max • 995A71AB-F7C4-4348-8E3F-B32D6D47CBD8 • ios •
com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
shayneoneill@Shaynes-MacBook-Pro ~/Downloads/test

**Comment by stuartmorgan** [comment]
For the benefit of anyone else finding this after the fact: everything discussed above is obsolete, and if you follow [the current instructions](http://flutter.dev/desktop#tooling) desktop devices will show up in IDEs without any extra steps.
