### ISSUE TITLE
timing issues w/ initial attempt to list samples

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3429]
Follow-up from https://github.com/flutter/flutter-intellij/issues/3404#issuecomment-486848338, where @stevemessick notes:

> This happened while connected to the corp network. I see it at home, but that's not surprising. My home network is slow. Corp should be fast.
> <img width="308" alt="Screen Shot 2019-04-25 at 2 38 26 PM" src="https://user-images.githubusercontent.com/8518285/56770083-f028aa00-6767-11e9-8cb9-70187c0e7247.png">

The initial listing can take a while (if, for example, the flutter tool triggers SDK and engine downloads).  This can be reflected in the UI as an empty list of sample selections.

**Comment by vvinogradsky** [comment]
I would say my home network is pretty fast, but I am experiencing the empty drop-down issue.
![image](https://user-images.githubusercontent.com/7515118/57115582-cb12d900-6d1d-11e9-9b7b-1a0ebb6a784d.png)

**Comment by pq** [comment]
Thanks @vvinogradsky.  Could you paste the output from `flutter doctor -v`?  My guess is your version of flutter does not (yet) have the logic we depend on and I failed to check and fallback. Sorry for the confusion!

**Comment by pq** [comment]
FWIW: the minimum supporting SDK is `1.3.10`...

**Comment by vvinogradsky** [comment]
Thanks for looking into this.
That must be it. My Flutter is at 1.2.1, and it doesn't want to upgrade. Has there been no upgrades on the stable channel?

D:\flutter\bin\flutter.bat --no-color upgrade
Upgrading Flutter from D:\flutter...
From https://github.com/flutter/flutter
   1d91bd258..39d660be7  master     -> origin/master
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (3 months ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by vvinogradsky** [comment]
I see, looks like these changes haven't made it to the stable channel yet, available only on the beta channel.

**Comment by skaterdude** [comment]
I'm getting this same issue on the latest version.  I just installed Android Studio + Flutter plug-in.  It runs, compiles, configures emulators, etc.  But when I try to create a new project and generate samples, the list of samples is blank, as shown above.  Here's doctor output:
F:\src\flutter\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at F:\src\flutter\flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Skaterdude\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

Here's a screenshot:
![MissingSamples](https://user-images.githubusercontent.com/749221/57665765-3afd4b00-75cb-11e9-9aac-8ac09e49c6cf.png)

I'm following the AppBrewery course (which was developed with a previous version, so not all the menus line up).

**Comment by devoncarew** [comment]
addressed by recent changes
