### ISSUE TITLE
Hot reload command gives confusing error during "run" session instead of "debug" session

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#344]
"No flutter app currently running".

Well, there is one, I just started it with the "debug" button instead of the "run" button.

![screen shot 2016-10-19 at 3 03 23 pm](https://cloud.githubusercontent.com/assets/11857803/19539260/4cfba8f6-960d-11e6-8293-992f38f6d00c.png)

**Comment by pq** [comment]
cc @stevemessick

**Comment by stevemessick** [comment]
@eseidelGoogle I'm having trouble understanding what's going on here, but let me make a guess. You started the app with the debug button, clicked the Hot Reload or Restart button before the app was fully initialized, then restarted the app using the Run button. The screen shot shows the app running via Run (there's a little green dot on the Run button). But there was this annoying flashy thing in the bottom-right corner so you clicked that and it shows this error. Is that sequence accurate? If it is then I'm working on a solution to this problem that will disable the reload and restart buttons while flutter is initializing the app. But I ran into a problem with the daemon (and created issue #6400) that it isn't reporting status properly all the time.

**Comment by eseidelGoogle** [comment]
My understanding was that I just did:
1.  Clicked Run button.
2.  command-R (my binding for hot reload)
3.  Saw error message.

I don't know if I had accidentally started a debug session before those.

**Comment by stevemessick** [comment]
Thanks. The keybindings should be disabled when not applicable. Reload and restart are only usable when the app is started in debug mode. @pq

**Comment by mit-mit** [comment]
This is solved as part of the run button changes, see #407
