### ISSUE TITLE
User feedback: decouple hot reload on save from ignore errors on hot reload

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter-intellij#3442]
I've gotten some feedback from g3 users that like to save more often than they like to hot reload that they want to ignore errors on hot reload even when they do not want to hot reload on save.

**Comment by devoncarew** [comment]
To clarify, they want to be able to hit the reload button even when there are analysis errors? I believe they can do that today.

**Comment by kenzieschmoll** [comment]
My interpretation of this is that g3 users want to be able to save without their app automatically hot reloading?

**Comment by DaveShuckerow** [comment]
@devoncarew you're right, this is the current behavior.  I wrote this down as a concern that this wouldn't be the same when the settings change that disables the error check when hot reload on save is turned off was shipped.  Trying it from master, this works today.
