### ISSUE TITLE
UI Guides don't work inside closures in build methods

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter-intellij#3446]
Just updated to latest version (35.2.3) and UI guides don't work when inside a build method, like the StreamBuilder:

![image](https://user-images.githubusercontent.com/1146982/57102862-c7218f80-6cfa-11e9-9069-6d6669f1852d.png)

See the ui lines working fine on the top of the images (BlocProvider) but stop working inside the LazyStreamBuilder.

**Comment by jacob314** [comment]
Thanks for trying out this feature!
We will support this case as soon as the Dart Analysis Server supports it. Let us know if you see any cases that look odd. We are in particular interested in any cases where the data we display is inconsistent with what you see in the Flutter Outline View. If it is inconsistent it means we have a bug, otherwise it means there is an opportunity for the outline view to include outline trees for additional data.

@scheglov when do you think the analysis server will support outlines within closures? It would be really nice to support build trees inside closures for the builder case and the ListView case among others.

**Comment by devoncarew** [comment]
@scheglov, is this something you think you can get to in the near term?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/103900

![image](https://user-images.githubusercontent.com/384794/58496565-fcb96d00-812e-11e9-9576-1a12a48701cf.png)

**Comment by shinayser** [comment]
You guys are fast! When will we be able to see that in production?

**Comment by jacob314** [comment]
The UI guides for this example look nice but I worry they are misleading as some nodes that are not children show up as children.
For example, the `header` in that example definitely isn't a child of the OrientationBuilder. It is referenced more deeply in the widget tree.
What do you think of adding an intermediate `builder: (BuildContext context ...)` node
to the flutter outline with a node type so I can detect it? That way we can still show UI guides for widget trees within build methods and potentially indicate that the closure is the source of the children of the OrientationBuilder but avoid making claims that all widgets referenced within a closure are children of the parent widget?

@InMatrix any thoughts about what guides make sense for this case from a UX perspective?

**Comment by scheglov** [comment]
Well, we never can be `100%` sure that this is a parent-child association. Even in case of named parameters like `child:` - it is just a convention. The widget that accepts this arguments can do just anything with it. What Flutter Outline shows is just a syntactic structure, not the semantic one. It is a reasonable guess that if you give a Widget in a constructor argument, it will be shown as a child. And similarly, if something is returned from a builder, it is a reasonable guess that it will be shown inside the enclosing constructed widget.

That said, I'm not against of inserting an intermediate node here, and as @bwilkerson mentioned in the review also for UI-as-code structures.

**Comment by InMatrix** [comment]
I agree `header` should not be identified as a child. If adding an intermediate node is not sufficient, I wonder if we can correct the UI guides using data from the inspector once the user runs the code.
