### ISSUE TITLE
Color picker is not clickable in Android Studio

### ISSUE THREAD

**Issue by harounhajem** [flutter/flutter-intellij#3448]
### Actual:
Clicking the color box, see picture, does nothing.
### Expected:
Clicking the color box should open the _**Color Picker**_ in _Android Studio_. 

![bild](https://user-images.githubusercontent.com/17148955/57127586-27631080-6d91-11e9-909d-8cd5eaaf8435.png)

**Comment by vanlooverenkoen** [comment]
This should be added. 

In the meanwhile use this: https://stackoverflow.com/questions/52589643/android-studio-where-is-color-picker-for-flutter-plugin
