### ISSUE TITLE
Search in Logger performance

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3449]
When I'm trying to search something in the logging search bar, the all IDE freeze and I have to force close it :/ 

It's a simple text search with no regex and no match case, I just have to type one letter and boom everything is freeze.
  
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale fr-FR)
    • Flutter version 1.2.1 at /Users/jaumard/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

```

**Comment by pq** [comment]
Oh!  Does this happen regardless of how many items are in the list?

**Comment by jaumard** [comment]
If I have no log no problem ^^ but once log start coming it freezes, no need to have much in my case. But append every time

**Comment by pq** [comment]
Great.  Thanks for the report!

**Comment by jaumard** [comment]
Still no news on this ? not being able to search on log is quite annoying :/ if you need more stuff that I can provide I'll gladly provide it :) that search bar is totally useless for now :/ surprise I'm the only on complaining about it lol

**Comment by pq** [comment]
Sorry @jaumard.  We've been focussing on language features over the last few quarters (and that's where my attention will be for the foreseeable future).  We've have picked up some work to improve the standard console output since this experimental view is maybe a little further away from being fully production ready.  Not sure if that's useful to you...

Thanks for the nudge!

**Comment by jaumard** [comment]
Hey @pq some news :) still happening with the new version you deployed if you're wondering ^^

**Comment by pq** [comment]
Yeah, that'd be my expectation unfortunately.

Have you tried the standard view recently?  It's missing some of the niceties of the structured one but @devoncarew has been adding improvements (most notably to support structured error reporting).

**Comment by jaumard** [comment]
Standard view doesn't have search feature. But I haven't since you put the nice one lool but I've test that structured error reporting and it's quite nice ! :)
