### ISSUE TITLE
Code formatting style 

### ISSUE THREAD

**Issue by harounhajem** [flutter/flutter-intellij#3455]
### Actual
Runs auto format and gets this crazy alignment with helper lines, see picture. 
![BAD](https://user-images.githubusercontent.com/17148955/57193349-4cdf4e00-6f3a-11e9-9252-2e3a35132e1d.jpg)

### Expected
Runs auto format and gets helper lines that align properly.

## Steps to Reproduce

Run auto format with "Reformat code with Dart fmt" or "Reformat code", on this code: 

```
class _MyHomePageState extends State<MyHomePage> {
  int numTaps = 0, numDoubleTaps = 0, numLongPress = 0;
  double posX = 0.0, posY = 0.0, boxSize = 150.0;

  @override
  Widget build(BuildContext context) {
    if (posX == 0) {
      setCenter(context);
    }
    return Scaffold(
      appBar: AppBar(
        title: Text("Gestures and Animations"),
      ),
      bottomNavigationBar: Material(
        color: Theme.of(context).primaryColorLight,
        child: Padding(
          padding: EdgeInsets.all(15),
          child: Center(
              heightFactor: 1,
              child: Text(
                  "Taps: $numTaps - Double taps: $numDoubleTaps - Longpress: $numLongPress",
                  style: TextStyle(color: Colors.black, fontSize: 18))),
        ),
      ),
      body: GestureDetector(
        onTap: () {
          setState(() {
            numTaps++;
          });
        },
        onDoubleTap: () {
          setState(() {
            numDoubleTaps++;
          });
        },
        onLongPress: () {
          setState(() {
            numLongPress++;
          });
        },
        child: Stack(
          children: <Widget>[
            Positioned(
                top: posY,
                left: posX,
                child: Container(
                  width: boxSize,
                  height: boxSize,
                  decoration: BoxDecoration(color: Colors.orangeAccent),
                ))
          ],
        ),
      ),
    );
  }

  void setCenter(BuildContext context) {
    posX = (MediaQuery.of(context).size.width / 2 - boxSize / 2);
    posY = (MediaQuery.of(context).size.height / 2 -
        boxSize / 2 -
        80 /*Top- and bottom-size*/);
    setState(() {
      posX = posX;
      posY = posY;
    });
  }
}
```
**_This issue happens more and more often and is very distracting._** 

## Version info
Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.475], locale en-GB)
Android toolchain - develop for Android devices (Android SDK version 28.0.3)
Android Studio (version 3.4)
Flutter plugin 35.1 
Dart v.183.6270

**Comment by adaamohi** [comment]
Android Studio > settings > Languages & Frameworks > Flutter > UI Guides disable it

**Comment by jacob314** [comment]
Thank you for reporting the error. We'd like to track in down. The UI guides are supposed to never display broken guides like the ones you are seeing. Unfortunately, I'm having trouble reproducing the issue.
Can you upgrade your plugin to V35.2 and let me know if you still see the error? We fixed a bug it V35.1 that might be related.
Also watch for a flashing red icon in the bottom right corner of your screen indicating that our code threw an exception. If you can include a stack trace of what went wrong it will make it much easier for us to fix it.
When I run dartfmt on the example you gave everything looks good:
<img width="616" alt="Screen Shot 2019-05-06 at 9 53 13 AM" src="https://user-images.githubusercontent.com/1226812/57241016-e6fbd080-6fe4-11e9-912a-badb3f0054be.png">

**Comment by alekskuzmin** [comment]
Might be related https://github.com/flutter/flutter-intellij/issues/3462

**Comment by harounhajem** [comment]
> 
> 
> Might be related #3462

Didn't get any exceptions. But i use the same version of Flutter Plugin and Dart Plugin on Android Studio 3.4.

**Comment by harounhajem** [comment]
> 
> 
> Thank you for reporting the error. We'd like to track in down. The UI guides are supposed to never display broken guides like the ones you are seeing. Unfortunately, I'm having trouble reproducing the issue.
> Can you upgrade your plugin to V35.2 and let me know if you still see the error? We fixed a bug it V35.1 that might be related.
> Also watch for a flashing red icon in the bottom right corner of your screen indicating that our code threw an exception. If you can include a stack trace of what went wrong it will make it much easier for us to fix it.
> When I run dartfmt on the example you gave everything looks good:
> <img alt="Screen Shot 2019-05-06 at 9 53 13 AM" width="616" src="https://user-images.githubusercontent.com/1226812/57241016-e6fbd080-6fe4-11e9-912a-badb3f0054be.png">

I have updated the Flutter Plugin and will investigate if this happens again.

**Comment by harounhajem** [comment]
> 
> 
> Might be related #3462

I've got the same error. Get the same exception in my IDE.

**Comment by jacob314** [comment]
With 35.2 you may still see a flicker of strange indent guides after the format. 
In the next release we will fix the flicker of strange indents as well.
Here's a beta plugin you can try to verify it helps.
With the beta plugin at worst you will see a few indent guides temporarily disappear on code format until a new valid "Flutter Outline" is computed.
![repro](https://user-images.githubusercontent.com/1226812/57322841-622eb680-70b9-11e9-8cef-7571504c3273.gif)
Android Studio 3.4 version of the Flutter plugin.
[flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/3154013/flutter-intellij.zip)

**Comment by harounhajem** [comment]
> 
> 
> With 35.2 you may still see a flicker of strange indent guides after the format.
> In the next release we will fix the flicker of strange indents as well.
> Here's a beta plugin you can try to verify it helps.
> With the beta plugin at worst you will see a few indent guides temporarily disappear on code format until a new valid "Flutter Outline" is computed.
> ![repro](https://user-images.githubusercontent.com/1226812/57322841-622eb680-70b9-11e9-8cef-7571504c3273.gif)
> Android Studio 3.4 version of the Flutter plugin.
> [flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/3154013/flutter-intellij.zip)

Ok thanks for the fast support, great work and looking forward to the next update.

**Comment by xgqfrms** [comment]
https://github.com/dart-lang/dart_style/issues/932

**Comment by giaur500** [comment]
Problem is still not solved:

![image](https://user-images.githubusercontent.com/26817206/115380413-d2657280-a1d2-11eb-8498-17640e5e51fa.png)

https://github.com/dart-lang/dart_style/issues/1021 

Still crazy ouput with brogen guide outlines
