### ISSUE TITLE
Inline docs do not seem to understand dartdoc?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#346]
https://www.jetbrains.com/help/idea/2016.2/viewing-inline-documentation.html

![screen shot 2016-10-19 at 8 07 27 pm](https://cloud.githubusercontent.com/assets/11857803/19544997/ae419ae2-9637-11e6-9bf9-392058824dec.png)

Not sure if it's possible to.

**Comment by devoncarew** [comment]
Perhaps only supported for javadoc? @alexander-doroshko

**Comment by alexander-doroshko** [comment]
Sorry, what's the question? 
Quick doc popup (F1 or Ctrl+J or Ctrl+button_2) shows dartdoc using info from the Analysis Server:
![image](https://cloud.githubusercontent.com/assets/4499789/19968321/1f6f5264-a1e5-11e6-9bff-18cab04b7d04.png)

**Comment by pq** [comment]
OK, I misunderstood.  I thought this was about opening external documentation (but that's another issue tracked elsewhere).  It looks like @eseidelGoogle's inline docs weren't working.  I wonder if this was a symptom of not having the right SDK set up (e.g., Dart and not Flutter Dart).

Seems to work for Flutter docs for me.


<img width="641" alt="screen shot 2016-11-03 at 6 54 47 am" src="https://cloud.githubusercontent.com/assets/67586/19968588/7468127c-a192-11e6-8ae2-6452c1b160d7.png">

**Comment by pq** [comment]
Optimistically closing.

@eseidelGoogle : feel free to re-open if problem persists.
