### ISSUE TITLE
M35.3 cherry-picks

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3467]
- b1b942abb8d4815aba21910faaeacf4eef3f084f ; fix for the AS 3.5 Beta; possibly this commit depends on 5ec88bba4354276f6322deadab4a7d526d6fe85b ? (yes)
- https://github.com/flutter/flutter-intellij/commit/3bc6f2f861b6d5d89cd9f50393bccbf536ad273f ; survey prompt
- 5c1881c553332052d5d53cd4bff97a534be07ad8 ; fix crash pugs with latest Dart plugin
- 50154802b52899bec160085f09972d6eb0ac1720 Fix crashes in widget indent guides.
- 58299c620aa07faccd1f5f2012508e3522616db1 Fixes an exception due to accessing a disposed project.

**Comment by jacob314** [comment]
Added widget indent guides bug to the list of cherrypicks.
