### ISSUE TITLE
External documentation takes you to Dart API docs instead of docs.flutter.io

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#347]
https://www.jetbrains.com/help/idea/2016.2/viewing-external-documentation.html

For example, shift-f1 on FlutterLogoDecoration takes you to:

https://api.dartlang.org/stable/1.20.1/index.html#id_FlutterLogoDecoration

**Comment by InMatrix** [comment]
This is the same issue as #290.

**Comment by devoncarew** [comment]
Closing as a dup.
