### ISSUE TITLE
Git branch switching doesn't invalidate the code in the analysis server

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#348]
This may be in the dart plugin more generally - feel free to move.

I had a project with an old reference '../lib/run_command_new.dart'. I fixed that elsewhere, and have switched to the branch with the fix (the import is now 'run_command_new.dart' which is correct.)

However the state in IJ is stale. The error is still reported in the status bar, and a location is highlighted that doesn't make sense, but the correct code is shown.

<img width="857" alt="screen shot 2016-10-20 at 11 57 31" src="https://cloud.githubusercontent.com/assets/2978182/19557306/1562ce0a-96bd-11e6-8e67-8ca56602ff77.png">

**Comment by pq** [comment]
cc @alexander-doroshko

**Comment by alexander-doroshko** [comment]
Definitely not a flutter-plugin issue. Might be Dart plugin, but most likely a server issue. 'Reanalyze' in the Dart Analysis tool window should help.
A reliable reproducible case is needed to process the issue.

**Comment by pq** [comment]
cc @scheglov who I think tackled something similar a while back.

**Comment by lukechurch** [comment]
I've just run into this again. It's pretty confusing when it occurs. @scheglov do you have any pointers to what you need to help debug?

**Comment by scheglov** [comment]
Turn on instrumentation to file with `--instrumentation-log-file=/path/to/the/log` in `dart.server.additional.arguments` in IDEA Registry. This might help to see which notifications are send from DAS when you switch branches.

**Comment by mit-mit** [comment]
@lukechurch did you manage to grab some logs?

**Comment by lukechurch** [comment]
I haven't managed to have the logging on and repro the issue yet. I'll keep trying

**Comment by devoncarew** [comment]
Closing this as I believe this will be addressed by the new analysis driver work.
