### ISSUE TITLE
HANG AFTER UPDATE

### ISSUE THREAD

**Issue by Paschal9090** [flutter/flutter-intellij#3482]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Launching lib\main.dart on ALP L29 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.

## Version info
C:\src\flutter\bin\flutter.bat --no-color upgrade
Upgrading Flutter from C:\src\flutter...
From https://github.com/flutter/flutter
   23baae0e4..e0943c426  master     -> origin/master
Updating b593f5167..7a4c33425
 11 files changed, 488 insertions(+), 83 deletions(-)

Upgrading engine...

Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (9 days ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!
Process finished with exit code 0

**Comment by jacob314** [comment]
Thanks for reporting the issue. Do you see the hang if you launch the app from the command line?
e.g.
`flutter run`
If you see the error there as well, it is a flutter bug.

**Comment by enasellithy** [comment]
i have same problem in Channel stable, v1.5.4-hotfix.2
