### ISSUE TITLE
error _channel

### ISSUE THREAD

**Issue by Paschal9090** [flutter/flutter-intellij#3483]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
lib/main.dart:98:25: Error: Getter not found: '_channel'.
                  await _channel.invokeMethod<String>('getStorageDirectory');
                        ^^^^^^^^
lib/main.dart:98:25: Error: The getter '_channel' isn't defined for the class 'HomeState'.
 - 'HomeState' is from 'package:flutter_brss/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_channel'.
                  await _channel.invokeMethod<String>('getStorageDirectory');
                        ^^^^^^^^
Compiler failed on C:\src\FlutterProjects\flutter_brss\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

## Version info

C:\src\flutter\bin\flutter.bat --no-color upgrade
Upgrading Flutter from C:\src\flutter...
Updating b593f5167..7a4c33425
 11 files changed, 488 insertions(+), 83 deletions(-)

Upgrading engine...

Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (9 days ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] Android Studio (version 3.5)
[√] Connected device (2 available)

• No issues found!
Process finished with exit code 0

**Comment by jacob314** [comment]
If you define a getter named `_channel` in the class `HomeState` the error should go away.
