### ISSUE TITLE
Flutter plugin contributes targets for dart projects

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#350]
See the below (complete with typo):

<img width="858" alt="screen shot 2016-10-20 at 12 17 42" src="https://cloud.githubusercontent.com/assets/2978182/19557790/4a282804-96bf-11e6-94f3-a48b3ddf63b0.png">

This implies that pressing the run button will run 'main.dart' (a normal dart project) on a iPhone. However what actually happens is that it launches it as a normal command line app. 

Consider removing the flutter deployment target UI for normal Dart projects.

**Comment by pq** [comment]
Thanks Luke!

Did you have any Flutter apps/projects open when this happened?  The device selector should only appear when a Flutter Module is open so if that's not the case, it's a bug.  That said, it may be confusing even on a good day.

We've talked, in general, about a desire to improve our UI around running and debugging and this comment fits right in.  Perhaps something we can kick around when we're all together.

cc @stevemessick @mit-mit @devoncarew

**Comment by lukechurch** [comment]
np!

I had Flutter apps open in other windows, but not in that one (I have IntelliJ configured to show each project in a new window). Full window screenshot attached

<img width="1144" alt="screen shot 2016-10-20 at 14 31 40" src="https://cloud.githubusercontent.com/assets/2978182/19561819/fca0e5b8-96d1-11e6-9423-72e3308fb3d2.png">

**Comment by stevemessick** [comment]
@lukechurch Which version of the flutter plugin did you have installed?

**Comment by lukechurch** [comment]
@stevemessick I think 0.1.

Is there an easy way of me getting you the answer to that? The version details in the flutter plugin config doesn't seem to list the version of the plugin.

**Comment by pq** [comment]
An update wouldn't hurt.

<img width="219" alt="screen shot 2016-10-20 at 6 41 50 am" src="https://cloud.githubusercontent.com/assets/67586/19562191/41075706-9690-11e6-813b-9ae12e5e0a25.png">

`0.1.2` is a wee bit better though I think you'll see this same behavior.

**Comment by lukechurch** [comment]
@pq Yup, now updated, thanks. FWIW, I didn't know there was an update available until I went to find the version in preferences. I'm sure the UI was telling me somewhere, but I didn't notice it. In the early days when we're cycling the plugin quickly we might want to make it a bit louder.

**Comment by mit-mit** [comment]
I get a pretty "loud" prompt in the lower, left corner whenever there is an update. But I have heard of others that also don't get that.

@alexander-doroshko can you elaborate on how the update prompting works in IJ?

**Comment by pq** [comment]
At a minimum you want update checking on in your preferences...

![screen shot 2016-10-20 at 6 53 10 am](https://cloud.githubusercontent.com/assets/67586/19562624/dbb0dcea-9691-11e6-8149-fa03da94b936.png)

But besides that, I'd love to know if there's more that can be done.

**Comment by lukechurch** [comment]
<img width="663" alt="screen shot 2016-10-20 at 14 54 59" src="https://cloud.githubusercontent.com/assets/2978182/19562704/38445f5c-96d5-11e6-8390-138e36e65883.png">

I don't know why it's 'never'.

**Comment by pq** [comment]
Ok, well, that's not good!  Curious if @alexander-doroshko has ideas...

**Comment by pq** [comment]
PS: dude, how can you not be using the darcula theme.  I mean all the kids are into black these days!

**Comment by alexander-doroshko** [comment]
> all the kids are into black these days

someone has to test that you do not [hardcode Darcula-specific colors](https://github.com/flutter/flutter-intellij/pull/343/commits/623680a8b801d77e54ac2f6e07dcef3a90a66cea)! :)

No idea why Never checked for updates for Luke. Someone need to browse that piece of code in IntelliJ Community sources.

**Comment by pq** [comment]
> someone has to test that you do not hardcode Darcula-specific colors! :)

FYI @devoncarew --- I may have done this but I know you were in there too.

**Comment by devoncarew** [comment]
All I can say is, Darcula is awesome!

@lukechurch with the latest plugin we should just show the pulldown for projects with flutter apps in them. OK to close this issue?

**Comment by lukechurch** [comment]
@devoncarew: Yup, just tested on 0.1.2, this seems fixed. Thanks!

![image](https://cloud.githubusercontent.com/assets/2978182/19588187/fde0e56a-975b-11e6-8471-e62b69a89d08.png)

@pq Happy with my aesthetics now? :)

**Comment by pq** [comment]
> @pq Happy with my aesthetics now? :)

Much! :dancing_men:
