### ISSUE TITLE
Show Intention Actions does not work for the root widget of a build method when using lambda syntax.

### ISSUE THREAD

**Issue by chris37879** [flutter/flutter-intellij#3500]
## Steps to Reproduce

1. Create a new flutter app.
2. Change the build method for `_MyHomePageState` from a normal method body to a lambda.
3. Invoking the Show Intention Actions shortcut in Android Studio will no longer bring up the menu with options like "Wrap in a new widget, Wrap in a Column, Wrap in a Row" and so on.

## Version info
[✓] Flutter (Channel beta, v1.5.4-hotfix.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.1 at /home/aldian/Developer/flutter
    • Framework revision 09cbc34a0b (2 weeks ago), 2019-04-30 15:44:27 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/aldian/Developer/android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = /home/aldian/Developer/android-sdk
    • Java binary at:
      /home/aldian/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.54
      52501/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at
      /home/aldian/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.54
      52501
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

• No issues found!

**Comment by chris37879** [comment]
Sorry for the close and re-open. I accidentally pressed Ctrl+Enter which apparently submits an issue form...

**Comment by devoncarew** [comment]
Thanks for the report! cc @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/103563
