### ISSUE TITLE
Intellij Dart/Flutter plugin changed `import` to `mport` on save file.

### ISSUE THREAD

**Issue by quangson91** [flutter/flutter-intellij#3501]
## Steps to Reproduce

This issue only happened on one file in my project.
The last `import` will be wrong after I press `CMD + S` to save the file.

The error is the `import` is changed to `mport`.
So, now I can't run project.
There is a workaround that I have to quit intellij idea, then open it again (without touch to that file).

## Version info

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/uos/Software/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/uos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ ideviceinstaller is not installed; this is used to discover connected iOS devices.
      To install with Brew, run:
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.1

[✓] Connected device (1 available)
    • SM G925F • 1215fc7c520f2b05 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 2 categories.
```

![dart_format_error_when_save_file](https://user-images.githubusercontent.com/6185205/57963905-e30d6e00-7955-11e9-84a6-fff8f11a48d9.gif)

**Comment by quangson91** [comment]
`WORKAROUND`
1. original code `import 'package:shared/entity/content_data.dart';`
2. remove the `;`
``import 'package:shared/entity/content_data.dart'`
3. save the file.
4. add `;` at the end of the line again.
5. then save file -> now that problem is not happening.

----
To make the error happen again:
1. original:
```dart
import 'package:shared/entity/command.dart';
import 'package:shared/entity/content_data.dart'; // This is last line import
```
2. add blank lin between those two import
```dart
import 'package:shared/entity/command.dart';

import 'package:shared/entity/content_data.dart';
```
3. Now try save file -> error.
```dart
import 'package:shared/entity/command.dart';
mport 'package:shared/entity/content_data.dart'; // ERROR ON THIS LINE. THE IMPORT become MPORT.
```

**Comment by jacob314** [comment]
If you run dartfmt on the file from the command line does the word import change to mport?
Do you have a source file you can share that reproduces this issue? I expect that just adding those two imports by themselves to a file will not trigger the problem.

**Comment by quangson91** [comment]
Sorry for the late reply.
I just try open my project on VS Code (with flutter plugin).
=> It worked well.
So I don't think the problem is about the dartfmt.

My project is private, so I can't share.
But you can try to create a new project with two classes then import those files.
Like:
```dart
import './entity/file1.dart';



import './entity/file2.dart';
```
Please note that there are some spaces between the two imports.
Then you press `CMD + S` many times -> the format may be wrong.

I think the problem is about concurrency problem (guess).

**Comment by quangson91** [comment]
It seemed the problem happens because of I use line ending CRLF (on Mac).
// Because that problem was created on windows.

After change line ending to LF -> I can't reproduce this issue anymore.

**Comment by JonasPoli** [comment]
Same problem here!

**Comment by JonasPoli** [comment]
when that happens i move the wrong line to the beginning of the imports section
