### ISSUE TITLE
Show closing labels in Dart source code preferences not saving between Android Studio launches.

### ISSUE THREAD

**Issue by jimbrayrcp** [flutter/flutter-intellij#3502]
**## Steps to Reproduce**

**Issue `#1` Closing Labels**
I truly enjoy using this software. However, I have an annoyance with one thing. 

I have noticed after setting the preferences to allow the Android Studio to **_Show closing labels in Dart source code_,** this setting does not stay set. The next time I open Android Studio, the allowance has to be rechecked. 

I found another user suffering from the same annoyance in regards to the "Show closing Labels setting" - @MargrietPB who may also be willing to provide you with some feedback on this issue if needed.

**Issue `#2` Copyright Settings**
I also noticed a similar issue with the copyright settings. I put the copyright profile into the preferences and the next time the software is opened, only the scope setting from the profile remain. 

I am not completely sure this next statement has anything to do with the issue but while looking for an answer to correct this problem, I came across an uninstall guide for Android Studio that mentions these preferences files which are supposed to be located in the Library. 

~/Library/Preferences/AndroidStudio
~/Library/Preferences/com.google.android
~/Library/Preferences/com.android

However, I did not find any of these files from the list on my Mac.

I am curious if this is happening because of something I have failed to do or if there may be some other solution to this issue. 

<img width="648" alt="Code01" src="https://user-images.githubusercontent.com/46821346/57987508-dff2aa80-7a47-11e9-9a9b-c29f8b12b92d.png">

<img width="935" alt="Settings01" src="https://user-images.githubusercontent.com/46821346/57987510-f567d480-7a47-11e9-8de1-5f86601e65fc.png">

<img width="654" alt="Settings02" src="https://user-images.githubusercontent.com/46821346/57987514-fdc00f80-7a47-11e9-9a31-aa962f953515.png">

<img width="710" alt="Setting03" src="https://user-images.githubusercontent.com/46821346/57987517-0284c380-7a48-11e9-9c16-58af60e0b23f.png">

**## Version info**
Android Studio 3.4.1

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/jimbray/Developer/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jimbray/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone Xs • ADFCB658-5F95-4639-BC60-2B1FFEA128F0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
Process finished with exit code 0

Thank you
Jim Bray

**Comment by grillop** [comment]
Happening to me as well.

C:\devapps\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\devapps\flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at 
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = ../Android/Sdk
    • Java binary at:...\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by bjbrogan** [comment]
Ditto.  Preferences -> Editor -> General -> Appearance -> "Show closing labels in dart source code" checkbox value does not persist.

E:\M710\Flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at E:\M710\Flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:/Users/bryce/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:/Users/bryce/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.6156.10

[√] VS Code, 64-bit edition (version 1.33.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.0.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by MargrietPB** [comment]
Me also, also the Asset Image maker isn't working since update.

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale nl-NL)
    • Flutter version 1.5.4-hotfix.2 at /Users/mp/Developer/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
! No devices available

• No issues found!
Process finished with exit code 0

**Comment by paulHN** [comment]
The same Problem at my Mac. I have to mark "show closing labels ..." each time I open AS anew.

**Comment by lc1200** [comment]
Same here.. Occurs on both my Macbook and Windows.  "Show closing labels" will not save

Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 1, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by YannickBiet** [comment]
Thanks for reporting, i was getting mad about this one, and why it didn't persisted :) glad to have search before breaking my laptop !

**Comment by devoncarew** [comment]
Thanks for all the reports! This is due to an interaction with the new UI Guides feature. User feedback from UI Guides has been good, and as UI Guides and closing labels attempt to solve the same problem - better awareness of where your widgets are in code - we don't think it makes sense to have them both enabled at the same time. The logic to disable closing labels when UI Guides was enabled is a bit aggressive and doesn't respect the actual closing labels settings.

We're going to dial this back for the next release, eta hopefully end of this week.

**Comment by epipheus** [comment]
Oh awesome, it's not just me -- I was going nuts there for a sec.

**Comment by epipheus** [comment]
@jimbrayrcp awesomely thorough bug filing from first post.

**Comment by YannickBiet** [comment]
Flutter plugin has been updated yesterday and seems to contain the bug fix !

**Comment by jimbrayrcp** [comment]
It’s working fine now! Thanks for fixing it for us.
