### ISSUE TITLE
After a crash the run button no longer works

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#351]
Please see:

<img width="1788" alt="screen shot 2016-10-20 at 13 05 11" src="https://cloud.githubusercontent.com/assets/2978182/19559072/e54c8324-96c5-11e6-97b3-a6f52e0f4a6f.png">

This circumstance is caused by running a flutter app, which then crashes due to a bug in the app.

Pressing the green run button at this point has no effect and gives no feedback. The only way to restart the app appears to be stop + start.

**Comment by pq** [comment]
Good catch.  Thanks Luke!

cc @stevemessick

**Comment by stevemessick** [comment]
@lukechurch I'm unable to reproduce this. Probably because "crash" is not well-defined. Can you give me more specific instructions?

**Comment by lukechurch** [comment]
@stevemessick The setup is somewhat complicated. If it doesn't reproduce easily for you, let me see first of all whether it reproduces on 0.1.2.

**Comment by lukechurch** [comment]
This no longer reproduces on 0.1.2. Apologies for the noise.
