### ISSUE TITLE
Show closing labels in Android Studio not saving and impossible to keymap

### ISSUE THREAD

**Issue by Widelx** [flutter/flutter-intellij#3519]
## Steps to Reproduce

When opening a new flutter project, I need to (re)check the "Show closing labels in Dart source code" box.

<img width="755" alt="Closing labels  Android Studio" src="https://user-images.githubusercontent.com/51048232/58412886-b3f2ad00-8077-11e9-8cb5-fc8aacf30b66.PNG">

The issue is known and some advised that we should keymap it. I searched for a long time in the "keymap browser". 

<img width="756" alt="Closing labels in keymap browser  Android Studio" src="https://user-images.githubusercontent.com/51048232/58413119-527f0e00-8078-11e9-9de1-89fe56815adf.PNG">

I just could'nt find it. So i ask for you help. Thanks

## Version info

Android Studio (version 3.4)

**Comment by Widelx** [comment]
Sorry i saved it because of a missclick
Going to delete or edit to do a good issue report

**Comment by pq** [comment]
See also :#3502.

**Comment by devoncarew** [comment]
closing as a dup of https://github.com/flutter/flutter-intellij/issues/3502

**Comment by Widelx** [comment]
All right thanks !
Did not see : #3502
