### ISSUE TITLE
Command to make bug reporting easier

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#352]
@pq @devoncarew @mit-mit 

The Atom plugin's single command to file issue on GitHub was very much appreciated. Esp. now there are many different version numbers in play (IntelliJ, dart, flutter, dart plugin, flutter plugin, OS). It would really help if we could have a one button or hot key to create a new issue auto populated with version details.

**Comment by mit-mit** [comment]
Tagging for potentially including in 0.2
