### ISSUE TITLE
ADD support for IntelliJ IDEA 2019.2 EAP

### ISSUE THREAD

**Issue by allanlaal** [flutter/flutter-intellij#3521]
basically a rehash of https://github.com/flutter/flutter-intellij/issues/2602 (and https://github.com/flutter/flutter-intellij/commit/752a664df0aea4885795fc1890f97f98aaf0a3e1)

## Steps to Reproduce

 * Install IntelliJ IDEA 2019.2 EAP Ultimate Edition
 * see that its not available in Plugin search
 * try to install plugin manually, get error: `Plugin 'Flutter' is incompatible with this installation`

## Version info

$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /opt/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /opt/Android/SDK
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /opt/IDEA
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 192.4205.33
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

**Comment by pq** [comment]
@stevemessick, looking at the product matrix, it **_looks_** like 2019.2 EAP should be supported but reading https://github.com/flutter/flutter-intellij/pull/3221 maybe it would have to read 2019.3 EAP for that?

**Comment by devoncarew** [comment]
I believe we support 2019.2 EAP now.

**Comment by allanlaal** [comment]
can confirm. the Flutter plugin is now visible in Plugin Marketplace and installable in 2019.2 EAP
