### ISSUE TITLE
Memory profiling is only available in Android Studio.

### ISSUE THREAD

**Issue by chenenyu** [flutter/flutter-intellij#3547]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
![image](https://user-images.githubusercontent.com/6647088/58678390-2d4d1100-8392-11e9-90c7-cb110aea058c.png)
![image](https://user-images.githubusercontent.com/6647088/58678409-405fe100-8392-11e9-9252-24ff1217d822.png)
![image](https://user-images.githubusercontent.com/6647088/58678444-5ec5dc80-8392-11e9-8cea-c778a10165ef.png)

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment]
Hi, thanks for the feedback. We' re moved much of the functionality from the memory profiler in Android Studio into DevTools. Docs on its capabilities and how to use it are at https://flutter.github.io/devtools/.
