### ISSUE TITLE
simplify integration with dartdoc code samples

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3562]
Our current integration with the dartdoc code samples are:

- we show an option to create them in our new project wizards
- we show an editor banner to create them when on a page that contains them

We've learned a bit more about how user's typically interact with these samples, and will have more options in the future (i.e. FlutterPad). I have some suggestions for an update of our UI:

- remove the ability to create the samples in new project wizards (I believe the samples are intended to be more 'in the moment' samples than canonical examples)
- change the editor banner code to regex the current file to locate dartdoc samples
- possibly, have one banner per sample in the file (the current pulldown in the editor banner is easy to miss)

With the above changes, we won't need to download a samples index per flutter sdk (and won't see the issues with the samples pulldown in project wizards not being populated - reported on this issue tracker, as well as on flutter/flutter; https://github.com/flutter/flutter/issues/31916).

@pq @InMatrix for thoughts

**Comment by InMatrix** [comment]
Sounds reasonable. In addition, it would be really useful to cache a preview image of a sample and show it somewhere in the IDE as the user encounters the sample code via Go to Definition, in a spirit similar to showing color and icon previews in the gutter. We can remove the friction of "I'm not sure if this sample will be useful unless I run it to find out."

**Comment by devoncarew** [comment]
What's left on this issue:

- change the editor banner code to regex the current file to locate dartdoc samples

After that, we should be able to remove the code that uses's flutter to enumerate the list of samples.

**Comment by devoncarew** [comment]
Ah, this has landed.
