### ISSUE TITLE
Provide a way to run flutter tests with extra command line flags from IntelliJ

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#3570]
It is possible to launch a flutter application with custom arguments but not a test. It would be nice to also support launching a test with custom arguments for cases where a test failure only reproduces with certain flags set.
Launch an app:
<img width="743" alt="Screen Shot 2019-06-11 at 2 47 28 PM" src="https://user-images.githubusercontent.com/1226812/59309209-e0055500-8c57-11e9-88c4-1d4db4c9a989.png">
Launch a test:
<img width="747" alt="Screen Shot 2019-06-11 at 2 48 24 PM" src="https://user-images.githubusercontent.com/1226812/59309255-fdd2ba00-8c57-11e9-98bc-e275381178a2.png">

Fyi @goderbauer who ran into this issue.

**Comment by daniel-v** [comment]
Would work well together once https://github.com/flutter/flutter/issues/32836 lands

**Comment by pinyin** [comment]
Is it the time to rise the priority of this issue? It's necessary when testing null-safety flutter applications.
