### ISSUE TITLE
Code reformatted incorrectly when using ifs with no brackets

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter-intellij#3571]
I apologize for the horrible naming and horrible placement, but I'm drawing a huge blank on terminology, so please rename and move this for me.

The issue is explained easily with this gif.
![2019-06-11 15 58 14](https://user-images.githubusercontent.com/23037821/59312585-89514880-8c62-11e9-83af-b81155efd5ef.gif)

Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
type an if statement like so:
`if(true) return false;`
insert an open curly brace and press enter and the closing bracket will place itself after the following word regardless of what's actually there.
if(true)**{|** return false;
turns to 
```dart
 if(true){
      return
    } false;
```
_Please tell us what you were doing and what went wrong_
Minding my own business when next thing I knew, this happened!

## Version info
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/thinkdigital/development/flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android
      Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Users/thinkdigital/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • SM G975U • R58M23BRC7J • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
[thinkdigital@ThinkDigitalsMBP teddycare] 2019-06-10 18:08:06$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/thinkdigital/development/flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android
      Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Users/thinkdigital/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone X • AA9863F4-FD5E-403D-BD7B-3303F6928AF9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

**Comment by devoncarew** [comment]
Thanks for the feedback! The work to address this would likely happen in the Dart plugin for IntelliJ

I can repro something similar to your above screenshot in Dart code. When I do the same in Java, IntelliJ does put the matching `}` in a location you'd expect (the curly braces are balanced appropriately). 

cc @jwren @alexander-doroshko

**Comment by ThinkDigitalSoftware** [comment]
My pleasure. Someone please move it to the appropriate place. It's hard to
figure out and place issues in the correct place. I'm just proud of myself
for getting this up here

**Comment by ThinkDigitalSoftware** [comment]
Found another one. 
![2019-06-13 17 44 25](https://user-images.githubusercontent.com/23037821/59475944-25b25100-8e03-11e9-8ca9-3d2b3e017724.gif)

**Comment by alexander-doroshko** [comment]
@ThinkDigitalSoftware, I failed to reproduce the issue in IntelliJ IDEA 2019.1.3 with the following code
```
main() {
  if (true) return false;
}
````
I also tried with something similar to the gif from the issue description, but still no luck. Could you paste a minimal file to reproduce?

**Comment by jacob314** [comment]
I can't reproduce either. @devoncarew any tips on how you reproduced the issue?

**Comment by devoncarew** [comment]
I was able to repro via:

```
      if (true) /*caret*/return;
```

However, I did see correct behavior in other situations:

```
      if (!serviceManager.hasConnection) /*caret*/toast('Device connection lost.');
```
