### ISSUE TITLE
update tools

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter-intellij#3575]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
**Could you please:**
update the Android Gradle plugin to version 3.4.1 and gradle to version 5.1.1 and ext.kotlin_version to 3.1.1
**Could you please also** update  the Android 9.+ (Q) as it seems to be 'partially installed

## Version info

C:\Users\xxxxxxxx\flutter\bin\flutter.bat --no-color upgrade
Upgrading Flutter from C:\Users\xxxxxx\flutter...
Updating b593f5167..7a4c33425
 11 files changed, 488 insertions(+), 83 deletions(-)

**Upgrading engine...**

Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (6 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Running flutter doctor...**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [version 10.0.17763.557], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

• No issues found!
Process finished with exit code 0

**flutter doctor -v**
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [version 10.0.17763.557], locale fr-FR)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\xxxxxx\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\xxxxxx\bmc_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_SDK_ROOT = C:\User\sxxxxxxx\bmc_sdk
    • Java binary at: C:\Users\xxxxxxxxx\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\xxxxxx\bmc_android
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by kenzieschmoll** [comment]
cc @stevemessick

**Comment by stevemessick** [comment]
We don't have control over any of these components.
Some might get updated if you update Android Studio to 3.4.1.

**Comment by benedicte69** [comment]
Thanks for answering, each time I create a flutter app I have to upgrade. Can't it be done for once, ? Can't flutter stuff be synchronised with Android Studio stuff? If I create an Android app, I don't need to do that so why when creating a flutter one, files are always undergraded? 

Envoyé depuis Yahoo Mail pour Android 
 
  Le jeu., juin 13, 2019 à 21:05, stevemessick<notifications@github.com> a écrit :   
We don't have control over any of these components.
Some might get updated if you update Android Studio to 3.4.1.

**Comment by benedicte69** [comment]
Please, can you pass the matter to the right team?  As Android Studiio is also an Intellij 'product I thought you could help. Thanks

Envoyé depuis Yahoo Mail pour Android 
 
  Le jeu., juin 13, 2019 à 21:15, Benedicte<notifications@github.com> a écrit :   Thanks for answering, each time I create a flutter app I have to upgrade. Can't it be done for once, ? Can't flutter stuff be synchronised with Android Studio stuff? If I create an Android app, I don't need to do that so why when creating a flutter one, files are always undergraded? 

Envoyé depuis Yahoo Mail pour Android 
 
 Le jeu., juin 13, 2019 à 21:05, stevemessick<notifications@github.com> a écrit : 
We don't have control over any of these components.
Some might get updated if you update Android Studio to 3.4.1.
