### ISSUE TITLE
Code pane shows a lot of extra issues on parser problem not in the errors view

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#358]
Plugin 0.1.2

To reproduce:

Create new app using sample. Delete the last ")" on line 39, making it:

```
            'Button tapped $_counter time${ _counter == 1 ? '' : 's' }.',
```

Here the errors and warnings displays the correct "Expected to find )" message.

However the editor pane contains an additional 15 red squiggles that are not shown in the errors and warnings pane.

<img width="529" alt="screen shot 2016-10-21 at 06 41 32" src="https://cloud.githubusercontent.com/assets/2978182/19587916/f917b420-9759-11e6-8ded-0b5ea640d3fd.png">

The message on hover over is not especially easy to understand

<img width="538" alt="screen shot 2016-10-21 at 06 41 43" src="https://cloud.githubusercontent.com/assets/2978182/19587933/1e577b12-975a-11e6-9ef9-18c00a96f57a.png">

If we want to keep this error message, basically we need to move it to the end of line 39 and make it read "expected to find ')'"

**Comment by pq** [comment]
cc @alexander-doroshko 

I think this is coming from the Dart Plugin's parser?

**Comment by alexander-doroshko** [comment]
Yes, it is Dart plugin's parser. Doesn't look like a big (or any) problem to me. It's clear that there are syntax errors that must be fixed.

**Comment by pq** [comment]
Thanks for the confirmation.  I'll leave it to @lukechurch to chime in on how much of a problem it is but it seems less than ideal to me.  Looking at the red squiggles it's not at all obvious what a user is supposed to do to fix the source and the hover is not terribly helpful.  In analyzer (cc @bwilkerson) a lot of care is taken to add error recovery to the parser so that good errors can be surfaced, ideally with actionable messages.  This is, of course, still an ongoing process of improvement!

I'm not sure how feasible it is to add error recovery to the Dart plugin parser but it would be an interesting thing to explore.

**Comment by alexander-doroshko** [comment]
Both recovery and better error messages are doable using Grammar-Kit. Something is easy, other things are rather complicated. Not sure how much time I can spend on it now.

**Comment by pq** [comment]
Cool.  Let's be sure to spend some time with @lukechurch at the Summit so that he can motivate what matters and why.

**Comment by lukechurch** [comment]
@alexander-doroshko @pq yeah - let's talk at the summit. This kind of thing does matter as it misguides users. 

It's important (roughly in priority order)

- that the two views are consistent in what errors they report
- that the errors are reported as proximally to the location of the problem as possible (both systems could use some improvement here)
- that the errors have actionable messages for guiding how the developer fixes them

Let's chat at the summit about what is doable with a reasonable amount of effort.

**Comment by alexander-doroshko** [comment]
@lukechurch From what you say it looks like we should simply disable reporting all parsing-related errors generated by the Dart plugin and leave only errors reported by the Analysis Server, and this way all responsibility goes to its side. Well, may be it makes sense.

**Comment by lukechurch** [comment]
That sounds like a great idea to me.

Anyone have any data on the downsides of doing so?

**Comment by danrubel** [comment]
+1 

The only downside I see is communication latency with the Analysis Server. That downside can be mitigated by having the Analysis Server prioritize returning syntax errors for the priority sources before anything else.

**Comment by bwilkerson** [comment]
Does the plugin's parser find errors that server should be finding and reporting, but isn't, or is it essentially equivalent and/or a subset, but just reporting things differently? If it's the former, then we should fix the bugs in server.

**Comment by alexander-doroshko** [comment]
In files that server processes and where it reports parser errors Dart plugin is not doing it better.

Dart plugin parser wins for cases not handled by the server, like:
- typing Dart code in Evaluate Expression field while debugging, or when adding a Watch expression
- typing Dart code in Log Evaluated Expression field of a breakpoint properties
- other cases of Dart code that is not in a file like:
 - Compare Clipboard with whatever
 - Diff view
 - Git commit history view
 - etc.
- Dart scratch file
- Any Dart file that does not belong to the project
- Looking/editing Dart without enabling Dart support (and/or wihtout Dart SDK installed at all)

Not sure if it is easy to skip showing Dart plugin's parser errors in some cases and keep showing in another. Need to check.

**Comment by pq** [comment]
> Not sure if it is easy to skip showing Dart plugin's parser errors in some cases and keep showing in another. Need to check.

@alexander-doroshko : did you get the chance to look into this?

**Comment by alexander-doroshko** [comment]
Not yet, tracked as https://youtrack.jetbrains.com/issue/WEB-23979

**Comment by pq** [comment]
Great.  Thanks for the update!

**Comment by mit-mit** [comment]
Hi @alexander-doroshko any news on this one?

**Comment by alexander-doroshko** [comment]
No news so far.

**Comment by pq** [comment]
@alexander-doroshko : any fresh thoughts on this one?

**Comment by alexander-doroshko** [comment]
`HighlightErrorFilter` allows to do the trick

**Comment by pq** [comment]
Oh cool!

Does that mean we should consider doing that on the Flutter end by contributing a `com.intellij.highlightErrorFilter` extension?

**Comment by alexander-doroshko** [comment]
I think you want me to do it at [Dart plugin end](https://youtrack.jetbrains.com/issue/WEB-23979).

**Comment by pq** [comment]
OK, cool.  Thanks!

**Comment by devoncarew** [comment]
Landed in the JetBrains repo!

**Comment by mit-mit** [comment]
Tagging for validation for once this reaches us.
