### ISSUE TITLE
INTELLIJ IDEA Exception when clicking on "Open for editing in Android Studio"

### ISSUE THREAD

**Issue by Ale-Digitale** [flutter/flutter-intellij#3585]
## Steps to Reproduce

**1.** Open any Android source file inside your FLUTTER PROJECT on INTELLIJ IDEA.

**2.** Click on the command "Open for Editing in Android Studio" at the top right of INTELLIJ IDEA Editor.

**You immediately get an IDE Error: "Exception: Cannot run program "C:\Program Files\Android\Android Studio": CreateProcess error=5, Access is denied".
And obviously nothing opens up.**

( please see attached screenshot of the error )

**Expected**: INTELLIJ IDEA launches Android Studio, opening this file.

I found a "workaround":

From the command prompt, if you change the FLUTTER config with:

**"flutter config --android-studio-dir PATH-TO-THE-ANDROID-STUDIO-EXECUTABLE-INSTEAD-OF-DIR"**

**making it pointing to the ANDROID STUDIO'S EXECUTABLE instead of the path dir, IT WORKS... and INTELLIJ launches ANDROID STUDIO correctly.**

But this can't be the right way of doing things... because this workaround "breaks" the flutter config.... causing flutter doctor to fail.

There must be sort of a bug somewhere... please investigate it.

## Version info

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Versione 10.0.17134.829], locale it-IT)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\aledi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA
    • Flutter plugin version 35.3.2
    • Dart plugin version 191.7019

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[√] Connected device (1 available)

![error](https://user-images.githubusercontent.com/39025003/59544499-5634e080-8f12-11e9-9916-fc4c2a68254a.png)

**Comment by pq** [comment]
@stevemessick: do you have any thoughts on this one?

**Comment by stevemessick** [comment]
It looks like an IntelliJ on Windows issue. I doubt it occurs in Android Studio, since we just open a project rather than launching the program.

**Comment by Ale-Digitale** [comment]
I reported this to the JetBrain team: https://youtrack.jetbrains.com/issue/IDEA-216200

They said this should be a Flutter-plugin issue.

Hmmm.... are we playing pass the buck ? :-)

**Comment by devoncarew** [comment]
My first thought here is that we may be forming the path to the Android Studio executable (`C:\Program Files\Android\Android Studio`) incorrectly on windows.
