### ISSUE TITLE
Plugin is not found in IntelliJ IDEA on Windows 10

### ISSUE THREAD

**Issue by douglasstarnes** [flutter/flutter-intellij#3595]
On Windows 10 Home, IntelliJ IDEA Community is unable to find the Flutter plugin when searching under File -> Settings -> Plugins.  It still works inside of Android Studio.  I also attempted to install the plugin manually but am unable to get IntelliJ to recognize the plugin. 
![D9XmWALX4AAO2z4](https://user-images.githubusercontent.com/1081484/59723219-7226d380-91eb-11e9-90e4-b8a58cbb30b6.jpg)

**Comment by eseidelGoogle** [comment]
@pq  might know if there has been any change.

**Comment by devoncarew** [comment]
@douglasstarnes, what version of IntelliJ are you using?

@stevemessick, I think we need better awareness of what version ranges are covered in our https://github.com/flutter/flutter-intellij/blob/master/product-matrix.json file. That could be https://github.com/flutter/flutter-intellij/pull/3407 or something like it - some validation of our version ranges, and awareness of when we have gaps.

**Comment by stevemessick** [comment]
I suspect we still don't understand all the rules used by JetBrains' distro matching algorithm, which was why #3407 had problems. Current hypothesis: the installation is not up to date and we're being hit by another rule we didn't know about regarding downward compatibility. The plugin does show up in all up-to-date installations I have available.
