### ISSUE TITLE
Incorrect offsets

### ISSUE THREAD

**Issue by giengus** [flutter/flutter-intellij#3612]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Not entirely sure, I was in the middle of debugging a project I'm working on, and then got distracted and when I came back to it (the debugger was running for nearly an hour at this point) the IDE was showing that I had experienced the error.

## Version info

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at c:\sdk\flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\gieng\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Users\gieng\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\191.7479.19
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by stevemessick** [comment]
Thanks for the report. It is difficult to be sure, but I think this will be fixed in our next release, M37. It will be out next week. If that doesn't fix it for you, please open a new issue with a stack trace or more detailed steps to repro the problem.
