### ISSUE TITLE
the Flutter outline 'remove widget' button is always disabled

### ISSUE THREAD

**Issue by yizems** [flutter/flutter-intellij#3615]
![image](https://user-images.githubusercontent.com/16949474/60061585-4e521900-9728-11e9-82d7-d710dcb6bbdf.png)

![image](https://user-images.githubusercontent.com/16949474/60061629-6a55ba80-9728-11e9-9fed-146a41941b9c.png)

remove widget button disable

**Comment by devoncarew** [comment]
cc @scheglov

**Comment by scheglov** [comment]
https://github.com/flutter/flutter-intellij/pull/3622

**Comment by stevemessick** [comment]
This will be fixed in M37, due out next week.
