### ISSUE TITLE
support androidx in the project wizards

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3616]
`flutter create` has a new CLI flag:

```
--[no-]androidx            Generate a project using the AndroidX support libraries
```

We should support a checkbox in the project wizards, and passing in `—androidx` if that checkbox is set.

Going forward we may want to be conservative about adding flags to flutter create.

**Comment by stevemessick** [comment]
The UI change will be temporary. AS 3.6 no longer allows projects to be created the old way; it always uses AndroidX. When it goes stable we should remove the flag from flutter_tools.
