### ISSUE TITLE
Clarify run / debug behavior

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#362]
I'd like to clarify what we expect to happen with the run / debug behavior and how that maps to various flutter run modes.

IntelliJ has a run and a debug button.

flutter tools supports debug, profile, and release modes when running, and the debug mode itself supports running in hot and non-hot modes.

We currently map the IntelliJ debug button to the flutter run debug mode. This seems sensible. We may want to add an option in the launch configuration for a flutter app to specify running in hot or non-hot mode. Then the debug button in IntelliJ would map to both hot and non-hot variants of the debug run mode.

We then need to figure out what exactly we map the run button in inteliij to. Our options are:
- flutter run --release
- flutter run (--debug), but we don't try and hook up a debugger and set breakpoints

Do users need to be able to run release mode apps on their phones from intelliJ? Is this a use case that can be handled solely by the CLI? What is the user intention when they hit run? Do they just want to see their app running on the phone but not be bothered by breakpoints? Would they be surprised if a more deploy-mode time app runs when they hit the run button?

thoughts @flutter/intellij-contribs?

**Comment by stevemessick** [comment]
I think the purpose of the IntelliJ Run button is to get your application running in the same fashion as if it were deployed, regardless of which platform you are developing for. You want to see how well it performs when there is no debugging overhead. This mode is needed for final system testing. The fact that Flutter does not currently have a release mode for simulators is a deficiency they may need to address but I don't believe that should affect our design.

I am curious what motivates this question, though. Why would we want to make the Run button launch in debug mode with no debugger connected?

IntelliJ also has a "Run with Coverage" button which I had been assuming would eventually be connected to the Profile mode.

**Comment by mit-mit** [comment]
It would be good to allow this to be configured via run configurations, but I feel the default *should* differentiate in the type of app they build. I think developers will find it really odd if running gives they an app in 'slow mode'. However, that would not work on simulators currently:
https://github.com/flutter/flutter/issues/6208

**Comment by mit-mit** [comment]
I discussed this with Eric, and we arrived at the following:

1. Map the Debug action to Debug mode, i.e. `flutter run`
1. Map the Run action to Release mode, i.e. `flutter run --release`
1. Disable the Run action when the current target device is a simulator, and state in the tooltip that release mode currently only works on physical devices

@devoncarew sounds good to you?

**Comment by stevemessick** [comment]
So, a tooltip like "Please select a physical device to launch in Run mode"?

I think this sounds good. Let me know if you want different wording.

**Comment by mit-mit** [comment]
I'd make the label

   "Run ''<config name> in release mode." when a physical device is
connected, and

   "Run ''<config name> in release mode (requires a physical device
target)." when not.

-- M

**Comment by mit-mit** [comment]
I'd make the label

   `Run '<config name>' in release mode.` when a physical device is connected, and

   `Run '<config name>' in release mode (requires a physical device target).` when not.

**Comment by devoncarew** [comment]
I think the decision is whether to map the `run` button to `flutter run --release` or `flutter run --debug` but w/ disabled breakpoints. Sound like you and Eric prefer the 1st option; that works for me.

In terms of the UX:

> Disable the Run action when the current target device is a simulator, and state in the tooltip that release mode currently only works on physical devices

I'm fine if the run button stays enabled, but fast fails w/ appropriate messaging when the user hits run on an unsupported device. That error message can come from flutter_tools, but be presented well by IntelliJ. This keeps the release supported device knowledge in flutter_tools instead of IntelliJ.

**Comment by stevemessick** [comment]
That's an interesting point, keeping Flutter internals to Flutter. In this case, I'd vote for a clean UX over good system design. IOW I'd prefer to disable the Run button and take the risk of getting it out-of-sync with Flutter capabilities. I think the risk is low since we have high-bandwidth communication between the projects. But the implementation effort isn't going to be too great in either case.

**Comment by sethladd** [comment]
We are sitting in a User Study, and the instinct of the user was to click the green Run button. That doesn't put the user on the best development experience. We had to manually instruct that "Debug means edit/refresh".

The Debug icon means "I want to debug my app". That is often not what the user intends when they want to edit/refresh.

Suggest that Solid Green Run button means the exact same thing as `flutter run`. They are both "run".

**Comment by stevemessick** [comment]
If we do as Seth suggests then we don't have to worry about disabling the button when the target is a simulator. That would simplify things a bit, which is always nice.

I'd like to know what an experienced user expects. Is it OK to tell developers they must use the command-line tool to see how their app performs "for real"?

**Comment by pq** [comment]
I know it was suggested but in light of the recent conversation, I'm curious how an option in the run config sits with folks?  

    [ ] run in release mode

To make it more obvious what run configs are release configs, we could decorate them with an icon?

**Comment by mit-mit** [comment]
Here is my suggestion:

1. In run config, add a 'Build type' combo box with two values 'Debug mode' and 'Release mode'
1. When a new project is created, create now one but two build configs:
  * One called 'Debug': Like the current one, and with the combo box set to 'Debug mode'
  * One called 'Release': Like the current one, and with the combo box set to 'Release mode'
1. Default the run config box to 'Debug'
1. The Run and Debug actions only differ in whether breakpoints are enabled or not
1. The Run and Debug actions take the build type setting of the active build config into account:
  * Build config == Debug: They `flutter run`
  * Build config == Release: They `flutter run --release`
1. If a user hits Run and Debug, and the current config is set to release, and the current target is a simulator, then the action simply fails and a meaningful error is printed to the Console (i.e., no fancy disabling and enabling of buttons)

WDYT?


This seems most consistent with how other IDEs do it.

**Comment by mit-mit** [comment]
One more comment: If we think most developers are going to do their development with the Run action, we should probably have the Run->Run Refresh behavoir on that icon button just like we are discussing here for the Debug button: https://github.com/flutter/flutter-intellij/issues/230

**Comment by sethladd** [comment]
> Default the run config box to 'Debug'

I like this for two reasons: hot reload is the default, and the word 'debug' is the same as the default mode for `flutter run`.

How does a user know what "build config mode" they are in, given the UI of the IDE? Is that visible in any way?

**Comment by mit-mit** [comment]
Yup, there is a build mode selector right next to the Run and Debug buttons:

![screen shot 2016-11-02 at 16 52 48](https://cloud.githubusercontent.com/assets/13644170/19936143/d14b7fa4-a11c-11e6-8d3d-d84724f0531e.png)

**Comment by pq** [comment]
In general I like this but (and I think @lukechurch makes this point elsewhere) is the dichotomy not actually better between **run** and **_release_**?

**Comment by sethladd** [comment]
Ah, on mine it's blank :) We should watch the UX video to see what the participant had selected here. Not sure the word "Debug" is super clear, but that might be linked to "ok, I want to debug my app". Did we consider "Develop" , which might match the user's intent more?

**Comment by sethladd** [comment]
@pq fwiw the flutter tool has debug, profile, and release as the different modes for "run". As in, "run in debug", "run in profile", and "run in release".

I think it's more confusing in the IDE context because the action "Debug" is overloaded to often mean "enable breakpoints and open the debugger and do actions like step over".

**Comment by alexander-doroshko** [comment]
Since there may be more than one entry points (apps) in a project we usually prefer to give names to the  run configurations that describe the app configured inside it. For example 'foo_app' if entry point is 'foo_app.dart', or 'Debug foo_app' if you want to reflect launch mode.

That's true that "Debug" in the IDE usually means "enable breakpoints and open the debugger and do actions like step over".

**Comment by pq** [comment]
@sethladd can you debug a release build?

**Comment by sethladd** [comment]
No. A release build is not debuggable/profilable.

**Comment by mit-mit** [comment]
Seth wrote:
> Did we consider "Develop" , which might match the user's intent more?

Yes, I did. But I wanted to be consistent with other IDEs (I have never use an IDE where the default configs were not Debug and Release), and with the Flutter tool itself that has debug, release, and profile.

In any case, this is just a string, so should be very easy to change later if needed.

**Comment by mit-mit** [comment]
Alexander wrote:
> Since there may be more than one entry points (apps) in a project we usually prefer to give names to the run configurations that describe the app configured inside it. 

Sure, good point, so perhaps we change them to `MyApp (debug)` and `MyApp (release)` where MyApp is whatever the developer picked as the module name. We could also do that in a following CL.

**Comment by sethladd** [comment]
> default configs were not Debug and Release

Fair enough. Those are the names we use in the CLI, so consistency makes sense here.

**Comment by devoncarew** [comment]
Hey all, thanks for all the feedback and ideas! We had a discussion in person based on the comments on this issue and evaluated the behavior of Android Studio's hot reload functionality. What we plan to execute on:

## the debug button

- is based on flutter run --hot and allows debugging
- is very similar to the current behavior, modulo:
- when an app is running, the debug button becomes a hot reload action

## the run button

- is also based on flutter run --hot
- it _does not_ support debugging; no breakpoints are hit and it will not break on exceptions
- when an app is running, the run button becomes a hot reload action

For both of the above, we will change the state of the run and debug buttons for running apps:

- we'll change the enablement when the button is applicable but not currently supported (the run button becomes disabled when the app is starting up)
- we'll change the icon image when an app is running. The run button will change from a simple play image to a play image with a lighting bolt decoration

This closely matches the behavior of android studio and I think is a reasonable mapping of the IntelliJ UI on flutter's execution behavior.

![unnamed_1](https://cloud.githubusercontent.com/assets/1269969/19950496/141e0ca0-a115-11e6-8b65-26dea6cdf90f.png)

![unnamed_2](https://cloud.githubusercontent.com/assets/1269969/19950495/141ce30c-a115-11e6-99e4-3f172b7215e7.png)

We'll likely rely on users using the CLI for the less frequently used run options (`--release`). Going forward we may create a separate launch configuration type (`Flutter Release` or some such) that allows users to see the deployment build behavior of their app.

**Comment by devoncarew** [comment]
Tracking the implementation of the above here: https://github.com/flutter/flutter-intellij/issues/407

**Comment by mit-mit** [comment]
Now that #407 tracks updating the Run and Debug buttons so that they both are non `--release`, and both support hot reload, we need something to track support `--release`. I opened #410 for that.

Closing this.
