### ISSUE TITLE
The plugin cannot be found when using 'flutter doctor'

### ISSUE THREAD

**Issue by laolarou726** [flutter/flutter-intellij#3633]
I'm using the latest version of the Intellij (2019.1.3), and I install the flutter & dart plugin on it. When I using 'flutter doctor', it shows the program cannot found these two plugins. Is this a compatibility problem?

Environment:
OS: MACOS Mojave 10.14.5
Flutter Version: flutter_macos_v1.5.4-hotfix.2-stable
Intellij IDEA: 2019.1.3
Dart plugin: 191.7830
Flutter plugin: 36.2.1

This is the console screenshot:
![image](https://user-images.githubusercontent.com/25716486/60392214-e8530080-9b30-11e9-8508-0730a8598d81.png)

This is the image of the versions of my plugins:
![image](https://user-images.githubusercontent.com/25716486/60392205-a9bd4600-9b30-11e9-9db4-c3160173a2d9.png)

**Comment by stevemessick** [comment]
Have you changed the location of IntelliJ's config files? If you have you probably used the instructions here:
https://intellij-support.jetbrains.com/hc/en-us/articles/207240985

Flutter doesn't know all the internals of various IDEs. It looks for the plugins in this location:
```dart
path.join(homeDirPath, 'Library', 'Application Support', '$id$major.$minor')
```
If you've changed the location then they won't be found by `flutter doctor`. If you think that's a bug you might want to report it in the flutter repo (https://github.com/flutter/flutter/issues)

**Comment by laolarou726** [comment]
I didn't change the path of the configuration file. Also, I found this folder in this location "path.join(homeDirPath, 'Library', 'Application Support', '$id$major.$minor')":

![image](https://user-images.githubusercontent.com/25716486/60477771-d26d4900-9cb2-11e9-9853-022ccba52bd2.png)

**Comment by stevemessick** [comment]
OK, at least everything is consistent. There is no Dart or Flutter plugin. Is the path to IntelliJ shown in the first screenshot correct? Do the plugins work? That is, can you create a new Flutter project and run it?

@alexander-doroshko do you have any idea what might be going on here? It appears the plugins got installed somewhere unusual (and undocumented), assuming they actually work.

**Comment by alexander-doroshko** [comment]
All ways to look for the plugins folder are in [PathManager.getPluginsPath()](https://upsource.jetbrains.com/idea-ce/file/idea-ce-be6247932aa9414ddf7831c0e3becba6940f4839/platform/util/src/com/intellij/openapi/application/PathManager.java?nav=8806:9346:focused&line=493&preview=false), so it's either one of the properties or a standard location.

**Comment by stevemessick** [comment]
Thanks, Alex!

**Comment by laolarou726** [comment]
I'm trying to reinstall the software..

**Comment by stevemessick** [comment]
Thanks for the update! Please let us know how it goes.
