### ISSUE TITLE
Alt+Enter has stopped working

### ISSUE THREAD

**Issue by lukef** [flutter/flutter-intellij#3637]
Plugin: `v37.0.3`
OS: Linux (Ubuntu)
Flutter: `1.7.12-pre.40`
Channel: `master`
IntelliJ: `2019.1 (Ultimate)`

I'm not really sure why or how to debug it (honestly) but Alt+Enter has stopped working for me on most projects. I've taken a look in the IntelliJ logs and I can't see anything that looks like the likely culprit.

I've tried deleting my `.iml` files and the `.idea` directory and recreating the project but no luck.

It's a bit of a bummer because I can't use the `Widget` re-parenting functions at all.

Quick fixes DO still work for things like the linter though (e.g.: "Suppress 'xx' warning", etc).

Let me know how I can help diagnose.

**Comment by stevemessick** [comment]
Are you getting analysis errors reported in the console? Does code completion work?

My first thought is there is something wrong with the Dart analysis server. You might try looking for rogue java processes that have dart in the name: `ps xa | grep [Dd]art`
Kill them and restart the analysis server in IntelliJ. To be more sure, shut down IJ, kill the processes, and restart IJ. If you're still having trouble after that, and everything else works, then maybe something changed in your keymap.

You can check that by adding "Show Intention Actions" to an existing menu. I added it to Help, just to see if it works. After adding it, select the name of some widget and choose that item from the menu. If the server is working you'll see the normal widget-editing fixes, and that suggests your keymap for alt-enter is not working.

**Comment by lukef** [comment]
I found the issue while checking what you asked. Let me know how to debug it for you because the IntelliJ logs, the Event Log and System logs aren't showing any errors. It might be user error also.

Here is the setup:

1. I'm working on a Flutter library project (https://github.com/lukef/qr.flutter). It has the library at the root level and an `example` folder with a Flutter app inside there. 
1. I have two `analysis_options.yaml` files: one at the root level and one in `example`.
1. The root level `analysis_options.yaml` file has an `exclude` section that excludes the `example` directory (along with others) like:
```
  exclude:
    - '.idea/**'
    - 'android/**'
    - 'assets/**'
    - 'build/**'
    - 'ios/**'
    - 'res/**'
    - 'example/**'
```

If I remove the `- 'example/**'` line then it all works. :confused: 

I've tried removing the `example/analysis_options.yaml` file and various other combinations but it seems like if I exclude example from the main analysis file then the whole thing will stop working.

Any ideas?

**Comment by stevemessick** [comment]
IIUC the alt-enter problem only occurs for code in the example directory? Everything works as expected for the library code?

Here is the analysis options doc:
https://dart.dev/guides/language/analysis-options

To me, it seems you are trying to do something that isn't supported, although I may be mistaken about that. I'd place the example program in a separate project if it needed to be totally separate. The Flutter `plugin` template does create an example project as a subdir of the Flutter plugin project, but it uses the analysis options of the main plugin. By adding the `example/**` exclude you are telling the analyzer to ignore your example. If you want it to have separate options it will need to be in a different project.

If you think every directory that has a pubspec should also allow analysis options then you should discuss that with the Dart SDK engineers: https://github.com/dart-lang/sdk/issues

**Comment by stevemessick** [comment]
Oh, there is another option. You could open your example in its own project window. Then the analyzer would see the example analysis options.

**Comment by lukef** [comment]
Actually, the issue is for both. I can't use alt+enter in the library project at all.

The issue is still there if i delete the second `analysis_options.yaml` file in the `example` folder.

So long as there is that `exclude` line for the `example` folder, the alt+enter functions wont work anywhere in the project. I think if i opened the `example` folder independently then it would work but i haven't tried.

If i remove that single line the everything works. To me that seems like a bug.

I'm happy to remove the example out also, but I don't think that's the issue.

**Comment by stevemessick** [comment]
It does sound like something odd is happening. I think it is an analyzer issue so I'm moving it to the Dart SDK. Maybe @bwilkerson can help.
