### ISSUE TITLE
Android Studio "generate sample content" dropdown empty

### ISSUE THREAD

**Issue by sam-bong** [flutter/flutter-intellij#3638]
Posted on reddit for help. Link here:
https://www.reddit.com/r/FlutterDev/comments/c7q1km/generate_sample_content_dropdown_empty_in_android/

v1.5.4-hotfix.2, on Mac OS X 10.14.5

**Comment by pq** [comment]
Thanks for this!  There's a known timing issue with sample listing (see also #3492).   In the latest plugin we've removed the drop-down from the new project wizard while we explore options and an improved workflow.  Sorry for the confusion in the meantime!
