### ISSUE TITLE
FlutterWidgetPerfTest failure

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#3647]
This looks like a new failure. Perhaps something in the library changed?
```
 io.flutter.perf.FlutterWidgetPerfTest
    ✔ testFileStatsCalculation
    ✘ testOverallStatsCalculation
      java.lang.AssertionError: expected:<18> but was:<26>
          at io.flutter.perf.FlutterWidgetPerfTest.testOverallStatsCalculation(FlutterWidgetPerfTest.java:492)
```
@jacob314 may be most familiar with this test.

**Comment by stevemessick** [comment]
Yep, something changed. Earlier today this test passed locally. After `flutter upgrade` it fails with the same assertion error. It would be good if the test could be made less dependent on Flutter implementation details.

**Comment by devoncarew** [comment]
I think that test runs independently of the actual flutter framework - it's mocked out.

I bisected this to fb50615d6eaceac70830ead0c783be65a3673dc6; cc @DaveShuckerow

**Comment by stevemessick** [comment]
Ah, could be. I updated everything, including the plugin sources. And didn't look at the source code of the test...
