### ISSUE TITLE
Add notification to install Flutter when it's not

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#365]
If you open a Dart file, and the Dart plugin is not installed, you get a notification inviting you to install Dart.  We should do the same for Flutter when a Flutter Module is encountered but the Flutter plugin is not installed.

@alexander-doroshko: curious where this logic gets contributed?

**Comment by alexander-doroshko** [comment]
JetBrains plugin repository is scanned for plugins that declare `FileType`s. Unfortunately not applicable for Flutter plugin.

**Comment by pq** [comment]
Ah.  That makes sense.  I suppose we could add something to the Dart plugin if we really wanted but not sure how weird that would be (and would create a kind of bidirectional dependency besides).

**Comment by sethladd** [comment]
Yes! Was just going to file this issue. :)

**Comment by devoncarew** [comment]
It's not commonly opened, but perhaps we could register for the flutter.yaml file?

**Comment by sethladd** [comment]
Hm, so it's only triggered to prompt a plugin if the user opens a file? Bummer we can't prompt for a plugin when the user imports a new project.

Could we prompt for the Flutter plugin if they open a .dart file with an import to 'package:flutter' or 'dart:ui' ?

**Comment by pq** [comment]
Ah!  I tried to answer this over on #364.  We totally could do something like that in the Dart plugin or maybe elsewhere?

@alexander-doroshko how does framework detection like Android work?  Can we do more than attach to an editor notification?

**Comment by alexander-doroshko** [comment]
> so it's only triggered to prompt a plugin if the user opens a file?

No, just the presence of a file in a project is enough, but it won't work for Flutter, see below

> perhaps we could register for the flutter.yaml file?

'flutter.yaml' is a file name, not a file type, you can't register for it. There are no flutter-specific file types.

> how does framework detection like Android work?

It is `FrameworkDetector` class + extension point. In theory it could be used instead of editor notification that suggests to change module type to flutter and reload project. But I'm not sure it is better.

**Comment by sethladd** [comment]
So if we have a .flutter file in the project, that would work? You need a unique file extension?

**Comment by devoncarew** [comment]
Sounds like the user would need to open that file type.

All flutter projects should now be created with the correct IntelliJ metadata. This includes a module file with the flutter module type.

I wonder if we could extend the platform to let plugins register as handlers for specific module types? Then if could say something like "you've opened a flutter project; would you like to install the flutter plugin?"

**Comment by sethladd** [comment]
> Sounds like the user would need to open that file type.

ah, gotcha

> All flutter projects should now be created with the correct IntelliJ metadata.

Should we add that to the Gallery?

**Comment by devoncarew** [comment]
It's there now, and for the hello_world app as well. It's the .iml file in the directory (on mobile, but I think that's the file extension).

**Comment by alexander-doroshko** [comment]
Please do not implement dirty hacks like registering *.flutter file type :)

**Comment by alexander-doroshko** [comment]
> let plugins register as handlers for specific module types?

Your plugin already does  register module type. If user opens confgured Flutter project without Flutter plugin installed he gets a warning that FLUTTER_MODULE_TYPE is unknown.

**Comment by pq** [comment]
> Your plugin already does register module type. If user opens confgured Flutter project without Flutter plugin installed he gets a warning that FLUTTER_MODULE_TYPE is unknown.

Right but wouldn't it be even cooler if the platform said, "It looks like you're trying to edit a Flutter module but you don't have the Flutter plugin, would you like to install it?"

**Comment by mit-mit** [comment]
Current status is you get this dialog if you File->Open a Flutter project (such as `/flutter/examples/hello_world/`) without having the Flutter plugin installed:
![screen shot 2016-12-08 at 09 57 39](https://cloud.githubusercontent.com/assets/13644170/21003655/e1f79104-bd2c-11e6-9a1e-dda5c5841177.png)

If you click 'Configure plugins' you do get the Flutter plugin suggested.

@alexander-doroshko the text here seems a bit confusing, and I missed at first that it had a concrete suggestion for me. Can we say something like this?

- "Unknown feature (<feature>) detected. This is supported by the non-bundled plugin 'Flutter'. Click 'Configure plugins' to install it"?

**Comment by alexander-doroshko** [comment]
Feel free to submit an issue or a pull request to https://github.com/JetBrains/intellij-community/. The latter has better chances to be addressed quickly.

**Comment by mit-mit** [comment]
PR submitted: https://github.com/JetBrains/intellij-community/pull/496

**Comment by pq** [comment]
Nice! 👍

**Comment by devoncarew** [comment]
Very cool!

**Comment by mit-mit** [comment]
PR was merged!

**Comment by pq** [comment]
Awesome!
