### ISSUE TITLE
support community2019.1.3

### ISSUE THREAD

**Issue by crazecoder** [flutter/flutter-intellij#3651]
## Steps to Reproduce

flutter-plugins code is not prompted, and entity class parenthesis is not automatically completed

## Version info

```
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830
```

**Comment by pq** [comment]
Could you include the rest of the `flutter doctor` output?  Are there any errors in the IDE?

Thanks!

**Comment by crazecoder** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.36.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by stevemessick** [comment]
It sounds like you're asking for two new features but I don't understand the details. Could you provide examples, please?

**Comment by crazecoder** [comment]
## flutter-plugin code can't be found in code hints
flutter_webview_plugin as an example 

![](https://i.imgur.com/IcQyySw.png)

The following picture shows that the plugin is successfully imported.

![](https://i.imgur.com/lwvNn8z.png)

## When I select an entity class from the code hint, I don't fill the parentheses

![](https://i.imgur.com/1T23awi.png)
![](https://i.imgur.com/MPitoIC.png)

what I want
```dart
Cartoon _cartoon = Cartoon()
```
