### ISSUE TITLE
Cannot run on Android Q emulator

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#3652]
Using IntelliJ or Android Studio, the IDE cannot connect to a Flutter app when it is run on an Android Q emulator (API 29). After launching the app, the console output shows these lines:
```
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:54187/npotfcBn3Lc=/ws
```
The same IDE/app works fine with a P emulator (API 28). The app is just the sample that gets generated with a new project.

Edit: I forgot to mention that the app gets disconnected from the IDE after the error message is printed.

**Comment by devoncarew** [comment]
I see this from the command line as well:

```
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri =http://127.0.0.1:49519/RhD31eDJPa0=/ws
```

**Comment by stevemessick** [comment]
See https://github.com/flutter/flutter/issues/33050
