### ISSUE TITLE
Launching an app to the iOS simulator loses the connection.

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter-intellij#3670]
## Steps to Reproduce

Running an app against the latest on flutter/flutter master to an iOS simulator causes the connection to be lost after the app starts up:

```
14:34:41.550 4 info flutter.tools Xcode build done.                                           21.7s
14:34:50.956 5 info flutter.tools Syncing files to device iPhone Xs...
14:35:00.318 6 info flutter.tools Lost connection to device.
14:35:00.325 7 info flutter.tools vm-service: Error: Unhandled exception:
14:35:00.325 8 info flutter.tools Unrecognized response: null
14:35:00.326 9 info flutter.tools #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
14:35:00.326 10 info flutter.tools #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
14:35:00.326 11 info flutter.tools #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
14:35:00.326 12 info flutter.tools #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
14:35:00.326 13 info flutter.tools [VERBOSE-2:dart_isolate.cc(814)] Unhandled exception:
14:35:00.327 14 info flutter.tools Unrecognized response: null
14:35:00.327 15 info flutter.tools #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
14:35:00.327 16 info flutter.tools #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
14:35:00.327 17 info flutter.tools #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
14:35:00.328 18 info flutter.tools #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

According to @devoncarew, the problem is that the plugin is using a API that no longer exists on master: `_registerService / registerService` API.

## Version info

$ flutter doctor -v
[✓] Flutter (Channel master, v1.7.5-pre.249, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.7.5-pre.249 at /Users/darrenaustin/dev/flutter
    • Framework revision 102ab1e6d9 (6 hours ago), 2019-07-15 09:22:29 -0700
    • Engine revision 919e353236
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/darrenaustin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/darrenaustin/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M337n
    • CocoaPods version 1.6.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (3 available)
    • iPhone Xs • 39AF1FB4-A93D-427E-9B98-EFA6101A3F4B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • macOS     • macOS                                • darwin-x64     • Mac OS X 10.14.5 18F132
    • Chrome    • chrome                               • web-javascript • Google Chrome 75.0.3770.142 

• No issues found!

**Comment by devoncarew** [comment]
Thanks for the report! This has been fixed in https://github.com/flutter/flutter-intellij/pull/3669. We'll publish a version of the plugin with the fix shortly.
