### ISSUE TITLE
Widget tree drawings dependent on `new` keyword

### ISSUE THREAD

**Issue by jwren** [flutter/flutter-intellij#3671]
![mis-behaving-tree-painting](https://user-images.githubusercontent.com/1533520/61252158-79b99980-a711-11e9-9034-449db5909a52.png)

It is possible to have the widget tree drawings in the editor misbehave by adding and  removing the `new` keyword.  In the screenshot adding and removing `new` before the `Expanded` widget adds and removes the tree lines in the editor.

**Comment by jwren** [comment]
@jacob314 @scheglov

**Comment by jacob314** [comment]
Do you have a repro project? That is a bug. It looks like the outline view is fine so the bug is probably in the logic rendering the ui guides from the outline view.

**Comment by jwren** [comment]
Best information for a repo is the LHS of the screenshot.  I typed out these widgets in one session.  Latest Flutter version and Flutter IJ versions

**Comment by stevemessick** [comment]
@helin24 Is this fixed? If not, could you add the `bug` label?

**Comment by helin24** [comment]
This seems to no longer be an issue, in DevTools or in the Java inspector.
