### ISSUE TITLE
New Flutter Project wizard: descriptions can be in the incorrect state (black vs gray text)

### ISSUE THREAD

**Issue by mileskrell** [flutter/flutter-intellij#3679]
## Steps to Reproduce

1. Open Android Studio.
2. Click "Start a new Flutter project".
3. Click and drag from the fourth option ("Flutter Module"), releasing when the cursor is above the first option ("Flutter Application").
4. Observe how the description for the fourth item is black, even though the first item is selected.
4. Click and drag from the first option, releasing when the cursor is above the third option ("Flutter Package").
5. Observe how, instead of only the description for the third item being black, the descriptions for the first, third, and fourth items are all black.

## Expected behavior

The description for the currently selected item should always be black. The others should be gray, indicating that they are not selected.

## Notes

This appears to be only a (very minor) visual bug. If you click "Continue" after following the above steps, the dialog continues with the "Flutter Package" option.

## Version info

[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.7.8+hotfix.3 at /Users/mileskrell/flutter
    • Framework revision b712a172f9 (9 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/mileskrell/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/mileskrell/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by stevemessick** [comment]
Thanks for the report! I can reproduce it.
