### ISSUE TITLE
Getting Started mentions a flutter_plugin.zip, where do I get that?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#368]
I'm trying to install the Flutter plugin. I'm on https://github.com/flutter/flutter-intellij/wiki/Getting-Started but it doesn't seem to link me to where I can get the plugin?

Are there newer instructions?

Thanks!

**Comment by sethladd** [comment]
cc @pq

**Comment by sethladd** [comment]
Ah, I really want to look at https://github.com/flutter/flutter-intellij/blob/master/getting_started.md

Should we delete the Wiki page?

**Comment by pq** [comment]
> Should we delete the Wiki page?

Yes! Nagged myself about this earlier: #360  

Would that I'd gotten around to it already!

**Comment by pq** [comment]
Deleted.
