### ISSUE TITLE
Allow hiding "Flutter commands"

### ISSUE THREAD

**Issue by JakubKoralewski** [flutter/flutter-intellij#3708]
## Steps to Reproduce

Please allow to turn the "Flutter commands of" for certain messages:

![image](https://user-images.githubusercontent.com/43069023/62044437-38da7e00-b203-11e9-8394-5b23c53af96a.png)

I am working in IntelliJ IDEA and I have this message constantly "Open for editing in Android Studio" even though I got gradle to work and Android Studio is useless and I want to hide that message.

## Version info

```
[√] Android Studio (version 3.4)
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at F:\PROGRAMY\jetBRAINS\IDEA\IntelliJ IDEA 2018.3.2
    • Flutter plugin version 37.1.4
    • Dart plugin version 192.5728.98

```

**Comment by jacob314** [comment]
@stevemessick does it make sense to suppress this message for users who have a IDEA Ultimate environment that supports Android?

**Comment by stevemessick** [comment]
@JakubKoralewski wrote:
> I got gradle to work

Can you tell me more about that? I'm working to make editing of Flutter modules in Android projects at the same time. Code completion, highlighting, etc. all work for Java/Kotlin/Dart/Flutter/XML. I'd like to know how you got that to work.

**Comment by JakubKoralewski** [comment]
@stevemessick Mostly trial and error, clicked lots of things. I remember going inside the project panel right clicking the build.gradle file inside the app or android folder and choosing either to build or synchronize the module. It has its quirks with the build failing, but code completion etc. all work. I even found out you can start Flutter in debug, then attach the android debugger to the android device to be able to debug the android code. Pretty neat.

**Comment by stevemessick** [comment]
Thanks for the info. Your process sounds like mine.

@pq We should add something like a "Hide notification" button to the banner.

**Comment by frextrite** [comment]
@pq Can I take a dig at this? As @stevemessick said, I can create a "Hide notification" hyperlink on the Notification Panel, and whenever it is clicked, it will remove all the similar notifications. Does it sound good?

**Comment by pq** [comment]
@frextrite: happy to take a look. I'm out of town for the next week+ but will try and find some time after I'm back.
