### ISSUE TITLE
Plugin active in non-flutter project

### ISSUE THREAD

**Issue by RdeWilde** [flutter/flutter-intellij#372]
Great plugin.

I experienced a problem with this plugin though. I was not working on a flutter project, just some other dart project, but this plugin was freezing my instance somehow.

It kept moaning about an unauthorized device (which is my phone I am charging). I noticed it every 4 seconds or so in the logs;

```
2016-10-24 22:31:54,673 [3179484]   INFO - r.run.daemon.FlutterAppManager - Device 55a2e1b9 is not authorized.
You might need to check your device for an authorization dialog. 
```

I don't think the plugin needs to be active when there's no flutter enabled project?

Idea community edition 2016.2.4 and flutter intellij 0.1.0. 
Will test 0.1.3 later (I just authorized my device, then I noticed the update....)

**Comment by pq** [comment]
Hey thanks for taking a look and for the report!  Spot on that the daemon shouldn't be started for non-Flutter apps.  We'll take a look.

/cc @stevemessick

**Comment by pq** [comment]
\o/
