### ISSUE TITLE
UI Guides not working after v38 upgrade

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3729]
## Steps to Reproduce

After I upgraded the Flutter plugin to version 38, the UI Guides stopped working. I then decided to update IntelliJ as a whole to 2019.2 but it still doesn't work. I also tried Flutter Clean and a full build but it didn't change.

![image](https://user-images.githubusercontent.com/8120472/62421489-e1ac3180-b678-11e9-8f48-962adfe3ec81.png)

![image](https://user-images.githubusercontent.com/8120472/62421503-2041ec00-b679-11e9-803a-31dc3c250078.png)

Also, this "Show wher build methods are on the scrollbar" doesn't appear to have any effect.

## Version info

[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale pt-BR)
    • Flutter version 1.7.8+hotfix.4 at C:\Programacao\Flutter\sdk\flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Programacao\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1
    • Flutter plugin version 38.1.4
    • Dart plugin version 192.5728.98

[√] VS Code (version 1.35.1)
    • VS Code at C:\Users\My User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Connected device (1 available)
    • ONEPLUS A5000 • bc18175a • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by stevemessick** [comment]
@jacob314

**Comment by jacob314** [comment]
I can reproduce the failure on windows. I should have a fix shortly. I expect something went wrong in the logic to deal with windows files sometimes not matching the outline length.
Fyi @DaveShuckerow

**Comment by feinstein** [comment]
Could you release this fix as a 38.0.1 and not wait until v39? I see this was added to the 39 Milestone.

**Comment by jacob314** [comment]
We will release this fix shortly.

**Comment by feinstein** [comment]
Thanks
