### ISSUE TITLE
Code navigation from in bin/ is not working

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter-intellij#373]
When I control + click on an import statement or a symbol in a file inside the `bin/` directory I get a red bubble saying "Cannot find declaration to go to".

```
IntelliJ IDEA 2016.2.4
Build #IC-162.2032.8, built on September 9, 2016
JRE: 1.8.0_112-release-b343 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

Dart plugin version: 162.2485

flutter doctor:

```
[✓] Flutter (on Linux, channel unknown)
    • Flutter at ...
    • Framework revision c560047888 (19 hours ago), 2016-10-24 16:14:48
    • Engine revision db12c5e621
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at ...
    • Platform android-22, build-tools 22.0.1
    • OpenJDK Runtime Environment (...)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38

[-] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin installed
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[... skipped other unused versions ...]

[✓] Connected devices
    • Nexus 5 • 0489410543877bdb • android-arm
```

Logging here because I'm using the Dart SDK bundled with Flutter.

**Comment by pq** [comment]
Is this in public flutter repo source?  (Can we easily set up a comparable project?)

**Comment by devoncarew** [comment]
If this is in a package in the flutter repo, you have to open the individual packages in `//packages/` as separate IntelliJ modules. If you just open the entire repo in IntelliJ, there is an IntelliJ project and individual modules already defined.

**Comment by yjbanov** [comment]
This is in public Flutter repo. To reproduce, open `dev/devicelab` as an IntelliJ module. Then try navigating from `bin/run.dart` to `package:flutter_devicelab/framework/manifest.dart` import.

**Comment by devoncarew** [comment]
I'm able to reproduce this; if I make an edit to the file then I do see navigation start to work. This is using `1.21.0-dev.0.0` of the dart sdk.

@bwilkerson @scheglov

**Comment by bwilkerson** [comment]
Does the navigation information that server sent IntelliJ include a navigation region for the URI? Is there an error indicating that server couldn't resolve the URI?

**Comment by yjbanov** [comment]
@bwilkerson 

Where do I get this information? (assuming the question was directed at me)

**Comment by bwilkerson** [comment]
I'll take an answer from anyone who has an answer :-)

If you've configured the IntelliJ registry entry `dart.server.additional.arguments` to include a command line argument starting with `--instrumentation-log-file=`, then the file you specified will contain all of the communication between IntelliJ and server. (But only for the current session, so if you've restarted IntelliJ since the problem occurred you'll need to reproduce the bug in order to get the data recorded again.) Search for a line containing the text `"event"::"analysis.navigation"`. There should be a parameter of the form `"file"::"/a/b/c/d.dart", where the file path is the path on your machine to the file containing the URI from which you couldn't navigate. If you can send me that line (in an e-mail, because it might contain sensitive data), that would help.

**Comment by pq** [comment]
> If you've configured the IntelliJ registry entry dart.server.additional.arguments to include a command line argument starting with --instrumentation-log-file=

@bwilkerson, @jwren : are there user docs any where for instrumentation?  If not, should there be?

**Comment by jwren** [comment]
https://docs.google.com/document/d/1s4PTof1x7RyxXYX1yO31ByvZsQoDMM7edFIW1SKP25U/edit

**Comment by pq** [comment]
Thanks Jaime!  This doc is great.

@devoncarew @mit-mit : I wonder if we shouldn't update it and publicize it some more?

**Comment by mit-mit** [comment]
I think we should convert this to markdown and put in the [sdk wiki](https://github.com/dart-lang/sdk/wiki).

**Comment by bwilkerson** [comment]
Ok. We figured out why this is happening. When analyzer is asked to analyze code in a given directory, it looks in that directory for an analysis options file. If one isn't found, it will look in the parent directory, parent's parent directory, etc. In this case, we find the file in the root of the flutter directory. That file contains the lines
```
exclude:
    - 'bin/**'
```
This means that we won't analyze the file `bin/run.dart`, so we have no information to use to provide navigation.

@Hixie Is this exclude directive needed, or can it be removed?

**Comment by yjbanov** [comment]
Is there a way to exclude files from linting but still get analysis for navigation/code-completion purposes? These are two orthogonal aspects, one is for our own productivity, the other is to ensure code quality for our users.

**Comment by bwilkerson** [comment]
I don't understand the question. I initially assumed you meant that navigation/code-completion is for our own productivity, but I don't understand how excluding files from linting ensures code quality, so I assume I'm not understanding what you're saying.

**Comment by devoncarew** [comment]
That exclude is meant to apply to `//bin/cache/` - we should probably just update that exclude.

**Comment by Hixie** [comment]
Yeah that's just supposed to exclude the Dart SDK itself from Flutter's analysis. It shouldn't exclude any files actually in the Flutter SDK.
