### ISSUE TITLE
Duplicate log 

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3732]
All my logs are duplicate like this: 
<img width="1421" alt="Capture d’écran 2019-08-05 à 11 31 28" src="https://user-images.githubusercontent.com/2970449/62454522-c3c3f700-b774-11e9-9c28-32becf6dd62c.png">

Version:
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale fr-FR)
    • Flutter version 1.7.8+hotfix.4 at /Users/jaumard/flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 38.1.4
    • Dart plugin version 192.5728.98

**Comment by devoncarew** [comment]
Yup, possibly.

**Comment by jaumard** [comment]
Still happening with the new release, any update on this ?

**Comment by devoncarew** [comment]
No, but for now, you can disable the experimental logging view setting in the preferences.

**Comment by sososdk** [comment]
Is there an update? This is very important to me.
