### ISSUE TITLE
Option to "Convert to Stateless Widget"

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter-intellij#3734]
Can we have the option to convert to a stateless widget if all variables if any are immutable?

**Comment by stevemessick** [comment]
@scheglov Does this seem like a reasonable request? I'd be concerned that our list of actions might get too large if we do everything.

**Comment by ThinkDigitalSoftware** [comment]
I figured it would be natural to add the companion. Also, it wouldn't be
present at the same time as the convert to stateful, so the list length
would stay the same

**Comment by scheglov** [comment]
@ThinkDigitalSoftware could you please provide a couple of example when it should happen, and when not?

**Comment by ThinkDigitalSoftware** [comment]
Sure. In this case, it should show up, since this is an easy conversion with no possible side effects. I.E. move the build function and delete the createState.
```dart
class SampleWidget extends StatefulWidget {
  @override
  _SampleWidgetState createState() => _SampleWidgetState();
}

class _SampleWidgetState extends State<SampleWidget> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

In this case, all variables are immutable. No setState calls.
```dart
class SampleWidget extends StatefulWidget {
  @override
  _SampleWidgetState createState() => _SampleWidgetState();
}

class _SampleWidgetState extends State<SampleWidget> {
  final variableA = 7;
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```
no variables are reassigned here, no setState calls. variable can be made immutable and moved over.
```dart
class SampleWidget2 extends StatefulWidget {
  @override
  _SampleWidget2State createState() => _SampleWidget2State();
}

class _SampleWidget2State extends State<SampleWidget2> {
  String aString = "Hello, world";
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```
The cases where it shouldn't show up are all the cases not shown here. If a widget has state that's internally managed, it's not available for that refactor. If setState is used...

My use case is that I switched to managing the state of my widget to outside of the widget. I moved out all the mutable variables and then had to cut, paste and delete (and change Stateful to Stateless) to get it done.
