### ISSUE TITLE
Hanginig IntelliJ after update

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3739]
I updated IntelliJ to version 2019.2 and the plugin to version 38, after that I am experiencing Intellij to hang and not recover. This happens randomly, multiple times a day.

[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale pt-BR)
    • Flutter version 1.7.8+hotfix.4 at C:\Programacao\Flutter\sdk\flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Programacao\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1
    • Flutter plugin version 38.1.4
    • Dart plugin version 192.5728.98

[√] VS Code (version 1.35.1)
    • VS Code at C:\Users\My User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Connected device (1 available)
    • ONEPLUS A5000 • bc18175a • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
Have you contacted Jetbrains about this? Without better repro info there's not much we can do.

**Comment by feinstein** [comment]
No, I didn't. I suspect is some interaction between IntelliJ and the Dart server.

Every time I saved my file IntelliJ would crash, so I closed IntelliJ and the dart.exe process, opened my file on a text editor, edited it, saved it, restarted my PC (as a precaution) and so far the problem hasn't surfaced again. 

For the way IntelliJ was behaving I imagine maybe the file was in a bad state, something conflicting in IntelliJ cache maybe and the dart analysis server was deadlocking it in some way when it tried to analyze the files new content.

**Comment by feinstein** [comment]
It just happened again. Since I think this is dart related, could you please include here someone at IntelliJ that deals with the dart plugin?

**Comment by stevemessick** [comment]
Wow, sorry about that. Let's bring @devoncarew and @jwren in for some brainstorming. Also @alexander-doroshko might have some insight.

**Comment by feinstein** [comment]
Please, because I am losing a ton of work with the failure, basically everything I typed since my last save point.

**Comment by feinstein** [comment]
FYI this is my monitor right now (its supposed to be an IntelliJ Window):

![image](https://user-images.githubusercontent.com/8120472/62554944-71eca100-b848-11e9-8bd1-f0c819f31702.png)

**Comment by stevemessick** [comment]
You might want to go back to 2019.1 to keep from losing work.

**Comment by jwren** [comment]
Go grab and attach relevant logs, they can be found at `Help` > `Show Log in <OS Finder equivalent>`

I'm guessing the IntelliJ from your log that is causing concern is this one, `IntelliJ IDEA Ultimate Edition (version 2019.2)`, it looks like the settings & preference directory that is being used is from 2019.1-  just something to rectify to rule it out.

**Comment by alexander-doroshko** [comment]
Right, logs and auto-saved thread dumps should help. Use Help -> Compress Logs... and attach the resulting zip here.

**Comment by feinstein** [comment]
As those might contain sensitive data I will delete them in an hour, if anyone else needs it, please do let me know. 

[idea-logs-20190806-130134.zip](https://github.com/flutter/flutter-intellij/files/3473108/idea-logs-20190806-130134.zip)

**Comment by alexander-doroshko** [comment]
@feinstein Thank you for the logs! It looks like there's a problem with the Dart Structure View. An infinite loop may happen. I'll fix this ASAP and publish the updated Dart plugin. As a workaround, you may keep the Structure tool window closed.

**Comment by feinstein** [comment]
ohh thanks for the quick fix!

**Comment by alexander-doroshko** [comment]
Filed an issue here: https://youtrack.jetbrains.com/issue/WEB-40544 and fixed. Dart plugin build is in progress.

**Comment by jwren** [comment]
Thank you @alexander-doroshko.

After the dart plugin is pushed, record the version here so we can close this issue.

**Comment by feinstein** [comment]
@alexander-doroshko while you are at it, could you take a look at dart tests?

IIRC when I opened a test file, IntelliJ would give me test shortcuts (Run/Debug Arrows) right next to the `test` and `group` blocks, but they are all gone now. Maybe this was never added and I am just getting confused with Java?

(Do you prefer that I open this at youtrack? I just thought here the triage will be quicker).

**Comment by alexander-doroshko** [comment]
Dart plugin updates with the fix are available: version 191.8369 and 192.6262.13.
