### ISSUE TITLE
M38 patch

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3740]
- [x] PR: https://github.com/flutter/flutter-intellij/pull/3738
- [x] PR: https://github.com/flutter/flutter-intellij/pull/3726
- [x] issue: https://github.com/flutter/flutter-intellij/issues/3736
- [x] issue: #3741 (verified: addressed by #3738)
- [x] issue: https://github.com/flutter/flutter-intellij/issues/3737
- [x] PR #3748

cc @stevemessick @kenzieschmoll @DaveShuckerow

**Comment by devoncarew** [comment]
cc @jacob314

**Comment by stevemessick** [comment]
Should we include #3741?

**Comment by devoncarew** [comment]
Yup, makes sense.

**Comment by devoncarew** [comment]
I _think_ we have all the fixes landed for this?

**Comment by stevemessick** [comment]
Published 39.2 to Jetbrains.
