### ISSUE TITLE
Android Studio Cant run individual Tests

### ISSUE THREAD

**Issue by jonnytest1** [flutter/flutter-intellij#3741]
Similar to https://github.com/flutter/flutter-intellij/issues/3398
but only since updating to flutter plugin version 38.0

## Steps to Reproduce

1. upgrade to flutter plugin version 38.0 in Android Studio (I explicitly looked out for this since my colleagues also had the problem)
2. Gutter Icons (Run/Debug Individual tests/goups) missing
3. right clicking on the testWidgets/groups methods only yields the 'run Tests' for the entire File

## Version info

[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale de-DE)
    • Flutter version 1.7.8+hotfix.3 at C:\Users\jonathan.heindl.BRAND-AD\Documents\flutter\flutter
    • Framework revision b712a172f9 (4 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\jonathan.heindl.BRAND-AD\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\jonathan.heindl.BRAND-AD\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by devoncarew** [comment]
@DaveShuckerow, can you look into this?

**Comment by DaveShuckerow** [comment]
#3738 may have fixed this.

**Comment by stevemessick** [comment]
Fixed by #3738 (the individual test part; still no gutter icons but that's got its own issue)

**Comment by DaveShuckerow** [comment]
@stevemessick what is the separate issue for no gutter icons?  We should fix that as part of the patch release too.

**Comment by stevemessick** [comment]
@DaveShuckerow #3398. It might be good to add to M39, but it wasn't targeted for any milestone yet.
