### ISSUE TITLE
Not creating a Test configuration on new projects

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3745]
IIRC when I created a new project, it came with a test configuration as well for running the sample test, but I just created a new project and there's no test configuration there, so I had to create one myself. Not the end of the world, but it should be included.

**Comment by stevemessick** [comment]
@pq has the plugin ever created test configs?

**Comment by pq** [comment]
Hmmmm, maybe we had that as part of our template content?  Trying to recall...

**Comment by feinstein** [comment]
Maybe my memory is failing and I am thinking about some open source project I opened.

In any case, I think it would be nice if the built-in test came ready to run by IntelliJ

**Comment by stevemessick** [comment]
No, we've never done that, I'm pretty sure. If you open the Project window context menu with the test file selected you'll be able to run it immediately. It auto-generates a test run config.

**Comment by feinstein** [comment]
No, it doesn't, but I think it's related to #3398

**Comment by stevemessick** [comment]
Project view. Pop-up menu. Debug. Then you have the option to save the auto-generated config.

**Comment by feinstein** [comment]
Do you mean here?

![image](https://user-images.githubusercontent.com/8120472/62638940-dd03a980-b914-11e9-962a-c44c7a77dd7b.png)

**Comment by stevemessick** [comment]
<img width="695" alt="Screen Shot 2019-08-07 at 9 18 52 AM" src="https://user-images.githubusercontent.com/8518285/62639542-98681600-b8f4-11e9-9ac0-90329d47d0ce.png">

**Comment by feinstein** [comment]
Oh ok, thanks steve.

**Comment by stevemessick** [comment]
Sure!
