### ISSUE TITLE
Flutter Performance should have a Pause button

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3754]
It would be nice to have a pause button in Flutter Performance and a Record Button, so this way we can do some action on the phone and then calmly analyse the graph generated at that time.

**Comment by stevemessick** [comment]
@jacob314 for consideration.

**Comment by kenzieschmoll** [comment]
@feinstein thanks for the report! We recommend that you shell out to DevTools to do performance analysis. 
![Screen Shot 2019-08-09 at 8 05 29 AM](https://user-images.githubusercontent.com/43759233/62788803-887b3e00-ba7c-11e9-870f-7d664a6e37c1.png)

In DevTools, we have a Timeline that lets you pause the recording, analyze frames, and even view a CPU profile for specific timeline events within a frame.
![image](https://user-images.githubusercontent.com/43759233/62788884-ad6fb100-ba7c-11e9-82c5-58256189b71a.png)

We also have a CPU profiler on the Performance page, where you can record a profile and analyze CPU performance.
![image](https://user-images.githubusercontent.com/43759233/62788966-ced09d00-ba7c-11e9-928b-d50c28f70b59.png)

**Comment by feinstein** [comment]
I was exploring the Flutter tools yesterday, after I opened this issue I went to try the DevTools, but I couldn't get it to work #3753.
