### ISSUE TITLE
Can't turn Flutter Inspector on anymore

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#3759]
After upgrading the IntelliJ Flutter plugin I can't turn on the Inspector. The tab itself opens, but its empty. There are no errors in IntelliJ 's Event Log.

--------------------------

>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] Connected device (1 available)

• No issues found!

**Comment by stevemessick** [comment]
@marcglasberg Is your Flutter app running? Please attach the output of `flutter doctor -v`. Thanks!

**Comment by marcglasberg** [comment]
Yes, it's running. I can select widgets, The buttons like "Enable Select Widget Mode", "Show Performance Overlay", "Show Paint Baseline" etc, work.

>flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale pt-BR)
    • Flutter version 1.7.8+hotfix.4 at c:\flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Marcelo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.6156.11

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6262.13

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by stevemessick** [comment]
Thanks for the update.

@jacob314 @kenzieschmoll might want to investigate further.

**Comment by marcglasberg** [comment]
@jacob314 @stevemessick I also noticed the entire widget tree is being printed to the console. It's 21 thousand lines. Something along the lines of:

`[{"id":21,"result":{"result":{"description":"[root]","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-1473","valueId":"inspector-1","summaryTree":true,"locationId":0,"creationLocation":{"file":"file:///C:/flutter/packages/flutter/lib/src/widgets/binding.dart","line":732,"column":26,"parameterLocations":[{"file":null,"line":733,"column":7,"name":"container"},{"file":null,"line":734,"column":7,"name":"debugShortDescription"},{"file":null,"line":735,"column":7,"name":"child"}]},"children":[{"description":"Bipp","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-1474","valueId":"inspector-3","summaryTree":true,"locationId":1,"creationLocation":`

**Comment by devoncarew** [comment]
> I also noticed the entire widget tree is being printed to the console. It's a lot of lines. It starts like this

That issue - the output to stdout - is now fixed, and will be in the next release (~end of the month).

**Comment by marcglasberg** [comment]
@devoncarew Thanks, but have you fixed only the output to stdout, or have you fixed the Flutter Inspector crash that is generating said output? When this output appears is when the inspector stops working. And my problem is the crash itself, not the output.

Also, where can I see the inspector's error logs?

**Comment by devoncarew** [comment]
It's likely that the output to stdout and the inspector no longer working were related - half on an inspector request likely got cut off.

You can view the intellij logs via `Help > Show logs`; the inspector view just writes issues there, as with the rest of the flutter plugin.

**Comment by marcglasberg** [comment]
I searched the logs for the word "inspector" and couldn't find anything there.

**Comment by marcglasberg** [comment]
Finally, I got the error in a small project. You can run it yourself if you need: https://github.com/marcglasberg/indexed_list_view/blob/master/example/lib/main_page_storage_key.dart

I don't know if you need this to fix it, but here is the complete tree printed to the console:

`[{"id":56,"result":{"result":{"description":"[root]","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-0","valueId":"inspector-1","summaryTree":true,"locationId":0,"creationLocation":{"file":"file:///C:/flutter/packages/flutter/lib/src/widgets/binding.dart","line":732,"column":26,"parameterLocations":[{"file":null,"line":733,"column":7,"name":"container"},{"file":null,"line":734,"column":7,"name":"debugShortDescription"},{"file":null,"line":735,"column":7,"name":"child"}]},"children":[{"description":"MaterialApp","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-2","valueId":"inspector-3","summaryTree":true,"locationId":1,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":7,"column":23,"parameterLocations":[{"file":null,"line":7,"column":35,"name":"home"}]},"createdByLocalProject":true,"children":[{"description":"HomePage","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-4","valueId":"inspector-5","summaryTree":true,"locationId":2,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":7,"column":41,"parameterLocations":[]},"createdByLocalProject":true,"children":[{"description":"Scaffold","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-6","valueId":"inspector-7","summaryTree":true,"locationId":3,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":22,"column":12,"parameterLocations":[{"file":null,"line":23,"column":7,"name":"appBar"},{"file":null,"line":27,"column":7,"name":"body"}]},"createdByLocalProject":true,"children":[{"description":"Column","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-8","valueId":"inspector-9","summaryTree":true,"locationId":4,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":29,"column":13,"parameterLocations":[{"file":null,"line":30,"column":15,"name":"children"}]},"createdByLocalProject":true,"children":[{"description":"Expanded","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-10","valueId":"inspector-11","summaryTree":true,"locationId":5,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":31,"column":17,"parameterLocations":[{"file":null,"line":32,"column":19,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"IndexedListView-[String <'myKey'>]","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-12","valueId":"inspector-13","summaryTree":true,"locationId":6,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":32,"column":42,"parameterLocations":[{"file":null,"line":33,"column":21,"name":"key"},{"file":null,"line":34,"column":21,"name":"controller"},{"file":null,"line":35,"column":21,"name":"itemBuilder"}]},"createdByLocalProject":true,"children":[{"description":"Card","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-14","valueId":"inspector-15","summaryTree":true,"locationId":7,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":66,"column":49,"parameterLocations":[{"file":null,"line":67,"column":11,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Container","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-16","valueId":"inspector-17","summaryTree":true,"locationId":8,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":67,"column":18,"parameterLocations":[{"file":null,"line":68,"column":13,"name":"height"},{"file":null,"line":69,"column":13,"name":"color"},{"file":null,"line":70,"column":13,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Center","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-18","valueId":"inspector-19","summaryTree":true,"locationId":9,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":20,"parameterLocations":[{"file":null,"line":70,"column":27,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-20","valueId":"inspector-21","summaryTree":true,"locationId":10,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":34,"parameterLocations":[{"file":null,"line":70,"column":52,"name":"data"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"Center","stateful":false}],"widgetRuntimeType":"Container","stateful":false}],"widgetRuntimeType":"Card","stateful":false},{"description":"Card","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-22","valueId":"inspector-23","summaryTree":true,"locationId":7,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":66,"column":49,"parameterLocations":[{"file":null,"line":67,"column":11,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Container","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-24","valueId":"inspector-25","summaryTree":true,"locationId":8,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":67,"column":18,"parameterLocations":[{"file":null,"line":68,"column":13,"name":"height"},{"file":null,"line":69,"column":13,"name":"color"},{"file":null,"line":70,"column":13,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Center","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-26","valueId":"inspector-27","summaryTree":true,"locationId":9,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":20,"parameterLocations":[{"file":null,"line":70,"column":27,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-28","valueId":"inspector-29","summaryTree":true,"locationId":10,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":34,"parameterLocations":[{"file":null,"line":70,"column":52,"name":"data"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"Center","stateful":false}],"widgetRuntimeType":"Container","stateful":false}],"widgetRuntimeType":"Card","stateful":false},{"description":"Card","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-30","valueId":"inspector-31","summaryTree":true,"locationId":7,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":66,"column":49,"parameterLocations":[{"file":null,"line":67,"column":11,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Container","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-32","valueId":"inspector-33","summaryTree":true,"locationId":8,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":67,"column":18,"parameterLocations":[{"file":null,"line":68,"column":13,"name":"height"},{"file":null,"line":69,"column":13,"name":"color"},{"file":null,"line":70,"column":13,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Center","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-34","valueId":"inspector-35","summaryTree":true,"locationId":9,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":20,"parameterLocations":[{"file":null,"line":70,"column":27,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-36","valueId":"inspector-37","summaryTree":true,"locationId":10,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":34,"parameterLocations":[{"file":null,"line":70,"column":52,"name":"data"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"Center","stateful":false}],"widgetRuntimeType":"Container","stateful":false}],"widgetRuntimeType":"Card","stateful":false},{"description":"Card","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-38","valueId":"inspector-39","summaryTree":true,"locationId":7,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":66,"column":49,"parameterLocations":[{"file":null,"line":67,"column":11,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Container","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-40","valueId":"inspector-41","summaryTree":true,"locationId":8,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":67,"column":18,"parameterLocations":[{"file":null,"line":68,"column":13,"name":"height"},{"file":null,"line":69,"column":13,"name":"color"},{"file":null,"line":70,"column":13,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Center","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-42","valueId":"inspector-43","summaryTree":true,"locationId":9,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":20,"parameterLocations":[{"file":null,"line":70,"column":27,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-44","valueId":"inspector-45","summaryTree":true,"locationId":10,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":34,"parameterLocations":[{"file":null,"line":70,"column":52,"name":"data"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"Center","stateful":false}],"widgetRuntimeType":"Container","stateful":false}],"widgetRuntimeType":"Card","stateful":false},{"description":"Card","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-46","valueId":"inspector-47","summaryTree":true,"locationId":7,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":66,"column":49,"parameterLocations":[{"file":null,"line":67,"column":11,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Container","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-48","valueId":"inspector-49","summaryTree":true,"locationId":8,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":67,"column":18,"parameterLocations":[{"file":null,"line":68,"column":13,"name":"height"},{"file":null,"line":69,"column":13,"name":"color"},{"file":null,"line":70,"column":13,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Center","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-50","valueId":"inspector-51","summaryTree":true,"locationId":9,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":20,"parameterLocations":[{"file":null,"line":70,"column":27,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-52","valueId":"inspector-53","summaryTree":true,"locationId":10,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":34,"parameterLocations":[{"file":null,"line":70,"column":52,"name":"data"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"Center","stateful":false}],"widgetRuntimeType":"Container","stateful":false}],"widgetRuntimeType":"Card","stateful":false},{"description":"Card","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-54","valueId":"inspector-55","summaryTree":true,"locationId":7,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":66,"column":49,"parameterLocations":[{"file":null,"line":67,"column":11,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Container","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-56","valueId":"inspector-57","summaryTree":true,"locationId":8,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":67,"column":18,"parameterLocations":[{"file":null,"line":68,"column":13,"name":"height"},{"file":null,"line":69,"column":13,"name":"color"},{"file":null,"line":70,"column":13,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Center","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-58","valueId":"inspector-59","summaryTree":true,"locationId":9,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":20,"parameterLocations":[{"file":null,"line":70,"column":27,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-60","valueId":"inspector-61","summaryTree":true,"locationId":10,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":34,"parameterLocations":[{"file":null,"line":70,"column":52,"name":"data"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"Center","stateful":false}],"widgetRuntimeType":"Container","stateful":false}],"widgetRuntimeType":"Card","stateful":false},{"description":"Card","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-62","valueId":"inspector-63","summaryTree":true,"locationId":7,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":66,"column":49,"parameterLocations":[{"file":null,"line":67,"column":11,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Container","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-64","valueId":"inspector-65","summaryTree":true,"locationId":8,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":67,"column":18,"parameterLocations":[{"file":null,"line":68,"column":13,"name":"height"},{"file":null,"line":69,"column":13,"name":"color"},{"file":null,"line":70,"column":13,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Center","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-66","valueId":"inspector-67","summaryTree":true,"locationId":9,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":20,"parameterLocations":[{"file":null,"line":70,"column":27,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-68","valueId":"inspector-69","summaryTree":true,"locationId":10,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":34,"parameterLocations":[{"file":null,"line":70,"column":52,"name":"data"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"Center","stateful":false}],"widgetRuntimeType":"Container","stateful":false}],"widgetRuntimeType":"Card","stateful":false},{"description":"Card","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-70","valueId":"inspector-71","summaryTree":true,"locationId":7,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":66,"column":49,"parameterLocations":[{"file":null,"line":67,"column":11,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Container","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-72","valueId":"inspector-73","summaryTree":true,"locationId":8,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":67,"column":18,"parameterLocations":[{"file":null,"line":68,"column":13,"name":"height"},{"file":null,"line":69,"column":13,"name":"color"},{"file":null,"line":70,"column":13,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Center","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-74","valueId":"inspector-75","summaryTree":true,"locationId":9,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":20,"parameterLocations":[{"file":null,"line":70,"column":27,"name":"child"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-76","valueId":"inspector-77","summaryTree":true,"locationId":10,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":70,"column":34,"parameterLocations":[{"file":null,"line":70,"column":52,"name":"data"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"Center","stateful":false}],"widgetRuntimeType":"Container","stateful":false}],"widgetRuntimeType":"Card","stateful":false}],"widgetRuntimeType":"IndexedListView","stateful":true}],"widgetRuntimeType":"Expanded","stateful":false},{"description":"Container","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-78","valueId":"inspector-79","summaryTree":true,"locationId":11,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":38,"column":17,"parameterLocations":[{"file":null,"line":38,"column":27,"name":"height"},{"file":null,"line":38,"column":40,"name":"color"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Container","stateful":false},{"description":"RawMaterialButton","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-80","valueId":"inspector-81","summaryTree":true,"locationId":12,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":39,"column":17,"parameterLocations":[{"file":null,"line":40,"column":19,"name":"materialTapTargetSize"},{"file":null,"line":41,"column":19,"name":"padding"},{"file":null,"line":42,"column":19,"name":"fillColor"},{"file":null,"line":43,"column":19,"name":"constraints"},{"file":null,"line":44,"column":19,"name":"child"},{"file":null,"line":45,"column":19,"name":"onPressed"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-82","valueId":"inspector-83","summaryTree":true,"locationId":13,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":44,"column":26,"parameterLocations":[{"file":null,"line":44,"column":31,"name":"data"},{"file":null,"line":44,"column":42,"name":"style"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"RawMaterialButton","stateful":true}],"widgetRuntimeType":"Column","stateful":false},{"description":"AppBar","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-84","valueId":"inspector-85","summaryTree":true,"locationId":14,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":23,"column":15,"parameterLocations":[{"file":null,"line":24,"column":9,"name":"title"},{"file":null,"line":25,"column":9,"name":"backgroundColor"}]},"createdByLocalProject":true,"children":[{"description":"Text","type":"_ElementDiagnosticableTreeNode","style":"dense","hasChildren":true,"allowWrap":false,"objectId":"inspector-86","valueId":"inspector-87","summaryTree":true,"locationId":15,"creationLocation":{"file":"file:///C:/Users/indexed_list_view/example/lib/main_page_storage_key.dart","line":24,"column":22,"parameterLocations":[{"file":null,"line":24,"column":27,"name":"data"}]},"createdByLocalProject":true,"children":[],"widgetRuntimeType":"Text","stateful":false}],"widgetRuntimeType":"AppBar","stateful":true}],"widgetRuntimeType":"Scaffold","stateful":true}],"widgetRuntimeType":"HomePage","stateful":true}],"widgetRuntimeType":"MaterialApp","stateful":true}],"widgetRuntimeType":"RenderObjectToWidgetAdapter<RenderBox>","stateful":false},"type":"_extensionType","method":"ext.flutter.inspector.getRootWidgetSummaryTree"}}]`

**Comment by jacob314** [comment]
Thank you for finding a simple repro!
