### ISSUE TITLE
The IntelliJ is often very laggy when editing package:flutter/src/foundation/diagnostics.dart

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#3760]
The IntelliJ is often very laggy when editing `package:flutter/src/foundation/diagnostics.dart`
There can be a 1 or 2 second pause before typing a character and changes showing up in the IDE. Even if the analyzer is a bit slow due to the number of files invalidated by this change, we should not be blocking text input.

Suggested fix: verify we are not performing unexpected blocking work on the UI thread.

**Comment by devoncarew** [comment]
Some investigation here: https://youtrack.jetbrains.com/issue/WEB-40646.

**Comment by devoncarew** [comment]
I'm going to close this optimistically based on a few PRs we landed. We'll re-investigate after the next plugin release if we see user feedback in this area.

cc @gspencergoog
