### ISSUE TITLE
Android license status unknown.

### ISSUE THREAD

**Issue by ErwinLeoSinaga1761** [flutter/flutter-intellij#3779]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:/Users/erwin/AppData/Local/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Users/erwin/AppData/Local/Android/sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment]
@ErwinLeoSinaga1761 - I'm not sure what error you're reporting here. Is this something you saw as feedback from the Flutter plugin, or the flutter command-line tool?

**Comment by ErwinLeoSinaga1761** [comment]
![masalah 02](https://user-images.githubusercontent.com/42212413/62989725-78e06880-be73-11e9-84cd-cf3e59761b88.png)
![masalah 01](https://user-images.githubusercontent.com/42212413/62989726-7978ff00-be73-11e9-8d32-cdf4c4fe7872.png)

sorry, you are not understand, because i write the problem incomplete. so i already attach screenshot .

**Comment by ErwinLeoSinaga1761** [comment]
whether "exited abnormally" is caused by android status licences unknown. so how to fix "android status licences "

**Comment by devoncarew** [comment]
@ErwinLeoSinaga1761 - the android command line tools require that you agree to a license before they work. I'd google about how to run the android tools from the command line, and / or agree to the license. The page here may give you pointers - https://flutter.dev/docs/get-started/install/windows#install-android-studio; it looks like you already have android studio installed.
