### ISSUE TITLE
update the plugin metadata to specify IntelliJ CE and Ultimate

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#378]
We should update the plugin metadata to specify that we support IntelliJ CE and Ultimate. Right now I believe we say that we support all IDE types.

**Comment by pq** [comment]
👍 

And while we're at it, we should update other bits too.  For example, look at [scala](https://plugins.jetbrains.com/plugin/1347?pr=idea):

<img width="370" alt="screen shot 2016-10-26 at 3 33 32 pm" src="https://cloud.githubusercontent.com/assets/67586/19727919/a82eb3e2-9b91-11e6-8cc1-7a42f037a51f.png">

Issues and website would be great for sure.

**Comment by pq** [comment]
OK, so I think this is done?

I also added a few links:

<img width="307" alt="screen shot 2016-10-26 at 4 47 10 pm" src="https://cloud.githubusercontent.com/assets/67586/19730892/e9771ed4-9b9b-11e6-97ab-f23db33aac28.png">


(Docs point to `getting_started.md`.)

We could also inline some basic usage instructions and add a screenshot but I don't feel too strongly.

cc @devoncarew @mit-mit

**Comment by mit-mit** [comment]
I would rather not inline usage instructions, too many duplicates to maintain.

**Comment by pq** [comment]
SGTM.

**Comment by pq** [comment]
> (Docs point to getting_started.md.)

On second thought, updated to point to the `README`.

@devoncarew : can we close this?  Looks like you've updated the IDEA platform details.

**Comment by devoncarew** [comment]
We should also update the plugin.xml to specify the supported platforms.

**Comment by pq** [comment]
> We should also update the plugin.xml to specify the supported platforms.

@alexander-doroshko I did some poking around but couldn't find a way to do this.  Can you advise?

**Comment by alexander-doroshko** [comment]
http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html

**Comment by alexander-doroshko** [comment]
Make sure to read and understand all the info in http://www.jetbrains.org/intellij/sdk/docs/index.html. :) 
I didn't check, but hope that all the info there is correct. Ask me if anything is not clear.

**Comment by pq** [comment]
Thanks @alexander-doroshko !

In our case, since we want to specify IDEA CE and Ultimate, is it sufficient to specify shared `java` support?:

```
  <depends>com.intellij.modules.java</depends>
```

(The doc states "(t)he following modules are only available in specific products" but I assume Ultimate is a super-set that contains `com.intellij.modules.java`?)

**Comment by alexander-doroshko** [comment]
Yes.
Also check what Android Studio thinks about `<depends>com.intellij.modules.java</depends>` plugins, I guess it may accept it too.

**Comment by pq** [comment]
Hmmm.  In that case, is there a good way to specify NOT Android Studio?  Or a better way to specify specifically only UE and CE?

Or maybe it's OK for now since it's on the roadmap...

**Comment by alexander-doroshko** [comment]
I may be wrong. According to the docs Android Studio shouldn't match. Please check manually.

**Comment by pq** [comment]
OK.  Thank you!
