### ISSUE TITLE
Grammar for the 'Replace widget with its children' refactoring

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter-intellij#3787]
You can't replace a widget with its children since multiple widgets can't replace a single widget. So since this seems to only show up when there's only one widget left in the list, "Replace widget with its child" seems to be appropriate.
<img width="478" alt="Screen Shot 2019-08-14 at 7 00 49 PM" src="https://user-images.githubusercontent.com/23037821/63067953-2a0fee80-bec6-11e9-97be-acf7e4517032.png">
Note: I'm cleaning up someone else's code :D
## Steps to Reproduce

Try to Replace a widget with its children.

## Version info

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/thinkdigital/development/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Users/thinkdigital/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 70B5B4AE-4D46-4F9D-AD5C-4141D1AE8F53 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.

```

**Comment by devoncarew** [comment]
@scheglov, is it true that this refactoring only applies when there's one child? The refactoring is just deleting the current widget, and retaining what's pointed to by `child:`?

**Comment by scheglov** [comment]
This refactoring can be applied to a container with multiple children, when the container itself is in another container which accepts multiple children. See [the test](https://github.com/dart-lang/sdk/blob/8eed45d0b5d42f83cbc1673dcb9a961b76c60237/pkg/analysis_server/test/src/services/correction/assist/flutter_remove_widget_test.dart#L183).

**Comment by devoncarew** [comment]
Gotcha, thanks.

@ThinkDigitalSoftware - thanks for the feedback here. Based on how the command operates, I think we'll keep the name the same.

**Comment by ThinkDigitalSoftware** [comment]
If the container accepts another container, that second container is still a single widget. I don't know of any place where multiple widgets can replace a single. Even a single child scrollview has a child and not a children property.

**Comment by ThinkDigitalSoftware** [comment]
I'm sorry, I wish I understood the test code. If you don't mind, can you provide an example where you can put a list (aka children) in the place of a single widget? I see what you're saying. Like if I have a row and one of its children is a row and we use this refactor, it'll move the children into the parent row. This is grammatically correct only in this case, no? Shouldn't it be grammatically correct in all cases?

**Comment by scheglov** [comment]
If a `Row` has two `Text` children, and this `Row` is in `children` of a `Column`, then the `Row` can be replaced with its `Text` children in the `children` of the `Column`.

```dart
import 'package:flutter/material.dart';

main() {
  Column(
    children: <Widget>[
      Text('aaa'),
      Row(
        children: <Widget>[
          Text('bbb'),
          Text('ccc'),
        ],
      ),
      Text('ddd'),
      Text('eee'),
    ],
  );
}
```

![image](https://user-images.githubusercontent.com/384794/63122450-a99bcd00-bf5b-11e9-8d77-433f9bb9346b.png)

![image](https://user-images.githubusercontent.com/384794/63122466-b28c9e80-bf5b-11e9-81f7-b0ff71d8d140.png)

![image](https://user-images.githubusercontent.com/384794/63122479-b9b3ac80-bf5b-11e9-810e-da22c9dafcb3.png)

**Comment by ThinkDigitalSoftware** [comment]
Ok. But when this is not the case, like if there's one child, it should say child, and children when it can refactor for children. Maybe I'm nick picking :)

**Comment by matthiassolomon** [comment]
So does it mean "Replace widget with its children" a replacement of the "Remove Widget"???

**Comment by ThinkDigitalSoftware** [comment]
> So does it mean "Replace widget with its children" a replacement of the "Remove Widget"???

Yes
