### ISSUE TITLE
Flutter inspector jump to source not working

### ISSUE THREAD

**Issue by rashedoz** [flutter/flutter-intellij#3794]
Flutter inspector doesn't jump to source. nothing happens when I select the jump to source. It worked perfectly fine before. 
<img width="1206" alt="Screenshot 2019-08-17 at 2 42 02 AM" src="https://user-images.githubusercontent.com/12187788/63197231-0c46b300-c099-11e9-89a9-145865a86e4b.png">

## Version info

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-GB)
    • Flutter version 1.7.8+hotfix.4 at /Users/rashedoz/softwares/Softs/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rashedoz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone Xʀ                 • EDBCC724-4854-471E-AC48-D9A0A66242EB • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

**Comment by devoncarew** [comment]
This is for a recent version of flutter (`1.7.8+hotfix.4`).

@rashedoz, can you give us a bit more details? You're running your app from IntelliJ on a mac? You do not have the 'disable tracking widget creation locations' setting enabled?

<img width="301" alt="Screen Shot 2019-08-16 at 3 11 38 PM" src="https://user-images.githubusercontent.com/1269969/63200986-45027000-c038-11e9-9f6a-5d41ea4d1242.png">

Did anything change between when you last saw this working? Does deleting the `build/` directory in your project, and re-running the app, help at all?

**Comment by rashedoz** [comment]
I had two projects with the same issue. But now completely rebuilding the projects fixed the issue. Thanks!!

**Comment by rashedoz** [comment]
> This is for a recent version of flutter (`1.7.8+hotfix.4`).
> 
> @rashedoz, can you give us a bit more details? You're running your app from IntelliJ on a mac? You do not have the 'disable tracking widget creation locations' setting enabled?
> 
> <img alt="Screen Shot 2019-08-16 at 3 11 38 PM" width="301" src="https://user-images.githubusercontent.com/1269969/63200986-45027000-c038-11e9-9f6a-5d41ea4d1242.png">
> 
> Did anything change between when you last saw this working? Does deleting the `build/` directory in your project, and re-running the app, help at all?

And i think it was not for the recent version of flutter as i had the issue before upgrading to 1.7.8 too!

**Comment by Pratik325** [comment]
> I had two projects with the same issue. But now completely rebuilding the projects fixed the issue. Thanks!!

Thanks it worked..

**Comment by BlackFireAlex** [comment]
I have this problem, can't seem to fix it.

**Comment by ocakliemre** [comment]
I'm having the same problem too. While it works normally on VsCode, it does not work on Android Studio.

**Comment by suyie001** [comment]
same issue on android studio, how to fix it? where is the "disable tracking widget creation locations"  setting option? I can not find it.

**Comment by MohammedShehata** [comment]
Hey Guys, 
Any one figure a solution about this issue?
