### ISSUE TITLE
On windows, attempt to execute adb by flutter_tools fails with "%1 is not a valid win32 application"

### ISSUE THREAD

**Issue by aman246149** [flutter/flutter-intellij#3795]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by aman246149** [comment]
![Screenshot (93)](https://user-images.githubusercontent.com/53884276/63206082-b63f3300-c0cb-11e9-963c-89915ef259aa.png)
this is the error

**Comment by devoncarew** [comment]
Thanks for the feedback; it looks like the underlying issue may be more related to the flutter CLI than the IDE.
