### ISSUE TITLE
make sure the plugin works well with the flutter repo

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#38]
This one: https://github.com/flutter/flutter

From looking at it:

- we analyze things in `bin/cache/` (like the copy of the dart sdk), which we shouldn't
- we don't analyze the packages in `packages/` - the analysis server thinks those projects are within a symlink

**Comment by pq** [comment]
@devoncarew: could you elaborate on what we're shooting for here?

Are we looking for a single project at the flutter repo root (e.g., containing all the packages and examples)?

**Comment by devoncarew** [comment]
Yeah, people being able to open the root of the repo, and see analysis working for everything in `//examples/` and `//packages`. I believe the first issue (analyzing bin/cache) is fixed. The second issue is still open - the analysis server doesn't traverse into directories named `packages`.

This is behavior specified in the `.packages` file spec I believe. We either need to adjust the behavior of the analysis server, changes the name of the `packages` directory in the flutter repo, or re-adjust our expectation that we should be able to analyze code in `//packages/`.

**Comment by pq** [comment]
Paging @bwilkerson re: analysis server smarts 😄 .

@devoncarew : could you remind me what you did for Atom?  Did you look for a sentinel file and use that to inform how you setup content roots?  Is something like that feasible here without reaching too deeply into the Dart Plugin?

**Comment by devoncarew** [comment]
In atom, we started from the opened dir, recorded down looking for dart projects, and sent in n analysis roots to the analysis server.

IntelliJ just sends in the opened dir to the analysis server as the single analysis root, and let's it work out where the sub dart projects are.

**Comment by pq** [comment]
>IntelliJ just sends in the opened dir to the analysis server as the single analysis root, and let's it work out where the sub dart projects are.

And I guess we could do what Atom does but that would mean exposing more internals of the Dart Plugin.  😢 Better, I think, to address the root issue which is that the Flutter repo structure is confusing in the context of the Dart URI resolution algorithm that treats `packages` dirs as special...

Conversation kicked off on a rename here: https://github.com/flutter/flutter/issues/6202.

**Comment by pq** [comment]
Update: it looks as if the resistance to change the name is pretty strong which suggests we should look into IDE- or server- side options.

**Comment by devoncarew** [comment]
One resolution here could be to require people working on the flutter repo to open individual projects as intellij modules. They'd need to do that once, but could then maintain a project w/ all those modules for use when working on the flutter repo.

**Comment by pq** [comment]
I was thinking just this but we should really try it.  I wonder also, assuming it works, if the config could be shared?  That is, what if it was as simple as checking a project file into the repo and telling folks to create a project from existing sources and have it "just work"?

**Comment by devoncarew** [comment]
+1 to sharing - parts of that could live in something like dev/intellij
