### ISSUE TITLE
Add ability to specify options(--local-engine, f.e.) for `flutter test`

### ISSUE THREAD

**Issue by aam** [flutter/flutter-intellij#3835]
I would like to be able to specify options for `flutter test` when I run flutter tests from IJ/AS.
Specifically I need to be able to override the engine when running tests - use option `--local-engine`.

**Comment by aam** [comment]
cc @rusino who raised this

**Comment by kenzieschmoll** [comment]
@stevemessick

**Comment by gspencergoog** [comment]
Yeah, I'd love this too, and it would bring the test running to parity with the `flutter run` support.

**Comment by adriano-moreira** [comment]
I'm trying use non-nullable dart feature,
and now I need this feature to pass these flags, to run my tests
```
--enable-experiment=non-nullable --no-sound-null-safety
```

**Comment by adriano-moreira** [comment]
I found a workaround

manually edit `.idea/workspace.xml` and add below tag on my test
```
      <option name="VMOptions" value="--enable-experiment=non-nullable --no-sound-null-safety" />
```

so I can use Android Studio debug on my test

**Comment by codegrue** [comment]
@adriano-moreira  where in workspace.xml do you put that option tag?
