### ISSUE TITLE
error: Target of URI doesn't exist: 'dart:html'

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3837]
Is there anything to do to avoir seing this(here in IntelliJ): 
<img width="703" alt="Capture d’écran 2019-08-31 à 14 53 57" src="https://user-images.githubusercontent.com/2970449/64064250-2d61e480-cbff-11e9-809c-5de98e222b3a.png">
because everything works as it should be the IDE doesn't do any autocomplete and put in red everything related to `dart:html`

Maybe I miss some configuration. Let me know

```
[✓] Flutter (Channel master, v1.9.8-pre.35, on Mac OS X 10.14.6 18G87, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[✓] Connected device (2 available)

• No issues found!

```

**Comment by devoncarew** [comment]
Nothing currently, but solutions are being discussed here: https://github.com/flutter/flutter/issues/35588.
