### ISSUE TITLE
support android studio

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#384]
We should support installing the plugin into and developing from Android Studio.

We'll have some versioning issues with the IntelliJ API to deal with (Android Studio is on an older version of the APIs). Similarly, we'll probably be using an older version of the Dart plugin. And we'll need to add some UI bits specific to Android Studio (for instance, contributing to their project wizard).

**Comment by stevemessick** [comment]
Fixed with https://github.com/flutter/flutter-intellij/pull/1353 and others.

**Comment by devoncarew** [comment]
🍾

**Comment by pvh** [comment]
Hi there! It seems the documentation hasn't quite caught up with the issue tracker here. I don't see the flutter plugin in the Android Studio plugins lists. Do I need to add a new source, or wait for a new AS release or something?

**Comment by stevemessick** [comment]
If you'd like to use it now you can clone this repos and build your own *.zip file, then install that from disk. It would be great to have more people testing it :)

**Comment by pvh** [comment]
Sure thing, Steve. I haven't done anything with intelliJ plugins before, so I'm muddling along here. After some dead ends I managed to find a shell command in the build.xml that appears to be doing something. Would you like me to attempt to write up a section for the README.md on how to build the plugin for Android Studio or would it be just as easy for you or someone else to take care of that?

**Comment by devoncarew** [comment]
We do hope to ship Android Studio support with the next release, hopefully this week. It may be easier to wait for the release instead of building it from source; definitely appreciate feedback on the release either way.

The plugin will require the latest Android Studio (the 3.0 preview release).
