### ISSUE TITLE
Too many repetitive hints

### ISSUE THREAD

**Issue by 39499740** [flutter/flutter-intellij#3845]
Android Studio 3.5
Flutter plugin v38.2.3
Dart plugin v191.8423

There is too many repetitive hints

![image](https://user-images.githubusercontent.com/29425312/64162365-bda76000-ce71-11e9-8e1f-e782b84b13f4.png)

how to fix it?

**Comment by pq** [comment]
See also: #3415.

/cc @scheglov @lambdabaa

**Comment by devoncarew** [comment]
@39499740 can you include the version of flutter (and the included dart version) that you're on? `flutter --version`

**Comment by 39499740** [comment]
> @39499740 can you include the version of flutter (and the included dart version) that you're on? `flutter --version`

Flutter 1.5.4-hotfix.2 • channel unknown • unknown source
Framework • revision 7a4c33425d (4 months ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by lambdabaa** [comment]
This is actually working as intended. @scheglov and I made a couple of changes to improve this situation (only including one copy if you already have a version imported and making sure to display package info to help differentiate). I can for sure see the value in showing only one library in this case, but we haven't agreed on doing that or what the selection heuristic should be.

**Comment by 39499740** [comment]
> I believe this is actually working as intended. @scheglov and I made a couple of changes to improve this situation (only including one copy if you already have a version imported and making sure to display package info to help differentiate). I can for sure see the value in showing only one library per symbol, but we haven't agreed on doing that or what the selection heuristic should be.

But I remember there were only two tips before the upgrade.

**Comment by 39499740** [comment]
When I upgraded the version, BUG was fixed.

Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (7 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
