### ISSUE TITLE
When running framework tests, stack traces are not linked to source code.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#3851]
When I run a test in the flutter framework, I should be able to click on the error locations in a stack trace and open it in the editor.

For instance, here's a screenshot of what I see when I run a test.  I'm expecting all of the `package:` bits in parens to be links, but they're not.
![image](https://user-images.githubusercontent.com/8867023/64369731-d2026e80-cfd1-11e9-8274-273676d6ca65.png)

```
[✓] Flutter (Channel route_focus2, v1.9.8-pre.99, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.8-pre.99 at /usr/local/google/home/gspencer/code/flutter
    • Framework revision 108035623b (18 hours ago), 2019-09-04 17:33:52 -0700
    • Engine revision e7f9ef6aa0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /opt/my-intellij-ce-current
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6459
```

**Comment by gspencergoog** [comment]
FYI, I have "Show structured errors for Flutter framework issues" checked in the preferences, and I have the experiment "Replace the Run and Debug console output with a custom Flutter Logging view" unchecked.

**Comment by kenzieschmoll** [comment]
@devoncarew @jacob314

**Comment by gspencergoog** [comment]
I realized that maybe I was remembering incorrectly: I'm probably remembering the `file:` links, but in any case it would be super useful to be able to link to `package:` links, if that's possible.

**Comment by jacob314** [comment]
we should support linking to package: urls in all our tools.

**Comment by gspencergoog** [comment]
@jacob314 was that "should" meaning that it should be a feature request, or that it should already work?

**Comment by jacob314** [comment]
updated my comment to be clearer. we don't support this yet.
