### ISSUE TITLE
Options for named param aren't helpful

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#386]
Trying to figure out what goes into a textTheme. Here's what I saw:

![screen shot 2016-10-27 at 1 12 30 pm](https://cloud.githubusercontent.com/assets/5479/19765141/1e10bff0-9c47-11e6-9a31-4520327f3a9b.png)

In the above, not sure that "const" and "false" are that useful here.

![screen shot 2016-10-27 at 1 12 41 pm](https://cloud.githubusercontent.com/assets/5479/19765140/1da99064-9c47-11e6-81f9-bacd1046d9ab.png)

In the above, "AboutDialog" probably isn't what I want.

**Comment by lukechurch** [comment]
+1!

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/sdk#27687
