### ISSUE TITLE
How to use live coverage feature - undocumented?

### ISSUE THREAD

**Issue by daniel-v** [flutter/flutter-intellij#3860]
Related to #2091 .

It is exactly what I'd like to use, run tests, see coverage information, have my IDE update automagically. However, I have no idea how to get started with it. Any pointers? Maybe @devoncarew could shed some light on that?

**Comment by jacob314** [comment]
That feature was experimental and added to try to make hot reload easier to understand. We have removed it from the Flutter IntelliJ plugin for now. Thanks for the feedback that you would find such a feature useful for tracking your coverage running tests.
Fyi @grouma

**Comment by daniel-v** [comment]
@jacob314 thank you for adding it to the backlog. Until this or a similar feature lands, do you have any tips on how to display coverage info in editor?

Currently, I have to resort to 3rd party tools to convert `lcov` to human readable format `genhtml`.

**Comment by daniel-v** [comment]
Seems like this came up again. Do you think, @jacob314 or @grouma , we could see something out of this in the near future?

**Comment by grouma** [comment]
I don't anticipate working on this in the near future. Note that `package:coverage` supports viewing coverage results in a human readable format through the `format_coverage` command and `-r` flag.

**Comment by stevemessick** [comment]
I think this is fixed in #5463. If that is not what is requested, please re-open with more detail.
