### ISSUE TITLE
Flutter plugin does not work with Android Studio canary 11

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#3869]
This will be fixed in the next release.

**Comment by bertonha** [comment]
With Flutter plugin on version `39.0.4` everything was ok on Android Studio 4.6 Canary 11.
But when I did update to Flutter plugin `39.0.5` then the Android Studio stopped to open.

**Comment by mofada** [comment]
But if I open `flutter\packages\flutter` as a project, it is normal.
![l4f6HF53o6](https://user-images.githubusercontent.com/22286246/64974666-d7b85800-d8df-11e9-91fc-0fa1238e2c71.gif)

I updated the flutter plugin yesterday, and this happened today, then I went to [flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) to download the latest version, I thought the latest The version will fix this problem, but there is still a problem with the latest plugin installed.

**Comment by mofada** [comment]
> With Flutter plugin on version `39.0.4` everything was ok on Android Studio 4.6 Canary 11.

Is the mistake entered incorrectly? 4.6?

**Comment by bertonha** [comment]
My bad,  Android Studio 3.6 Canary 11. thanks for the spot.

**Comment by ArcherEmiya05** [comment]
Can we know when is the next release? Manually downloading flutter-intellij and putting it inside plugin folder doesn't work too. It says that its not compatible with the current version.

**Comment by mofada** [comment]
> Can we know when is the next release? Manually downloading flutter-intellij 39.0.4 and putting it inside plugin folder doesn't work too. It says that its not compatible with the current version.

I think you have the wrong version, 39.0.4 does not support Android Studio canary 11/12, pay attention to your Android studio version, you can view it in `About`. I downloaded the corresponding version or not,

![IJ7TJJG36GHNXO5EJ D~RMC](https://user-images.githubusercontent.com/22286246/65681579-c1528f00-e08b-11e9-9238-9814f61aeace.png)

**Comment by ArcherEmiya05** [comment]
> > Can we know when is the next release? Manually downloading flutter-intellij 39.0.4 and putting it inside plugin folder doesn't work too. It says that its not compatible with the current version.
> 
> I think you have the wrong version, 39.0.4 does not support Android Studio canary 11/12, pay attention to your Android studio version, you can view it in `About`. I downloaded the corresponding version or not,
> 
> ![IJ7TJJG36GHNXO5EJ D~RMC](https://user-images.githubusercontent.com/22286246/65681579-c1528f00-e08b-11e9-9238-9814f61aeace.png)

Ahh because the 39.0.5 is not allowing Android Studio Canary is not finishing the loading screen that is why I tried to downgrade it to 39.0.4 but as you have said it doesn't support it so do we already have fix for startup issue in Canary 11 with 39.0.5?

**Comment by mofada** [comment]
You have to look at the build number that follows, 39.0.4 only supports 192.6261
