### ISSUE TITLE
Code complete named param should be a String, but is offered a Typography

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#387]
![screen shot 2016-10-27 at 4 23 04 pm](https://cloud.githubusercontent.com/assets/5479/19771047/d6d6478e-9c61-11e6-978f-f36936218c45.png)

`fontFamily` is what I'm trying to complete. It can take a String. Notice how the first option is a Typography. If I hit enter, Typography is inserted.

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/sdk#27688
