### ISSUE TITLE
Is there any solution generate code like this in Visual Studio Code?

### ISSUE THREAD

**Issue by wtrungvu** [flutter/flutter-intellij#3882]
![69352116_1958967980869844_674813605006278656_n](https://user-images.githubusercontent.com/33633989/64904622-b47e8480-d6f6-11e9-915b-7536f09770ee.jpg)
The feature above is in Android Studio. How to do like this in Visual Studio Code?

**Comment by stevemessick** [comment]
That's a question for @DanTup

**Comment by DanTup** [comment]
These are not currently available in VS Code - there's an issue tracking it here:

https://github.com/Dart-Code/Dart-Code/issues/1616

Unfortunately it's not that simple for VS Code - we don't do any language parsing so we can only provide features like this that are implemented by the analyzer. IntelliJ *does* parse the Dart code itself, so it's able to provide additional refactors "client-side".

I would recommend adding a 👍 (and/or subscribing) to the above issue. If there seems to be enough demand (so far it hasn't had very many 👍's)  then it may make sense to consider adding in the analyzer. Thanks!
