### ISSUE TITLE
Android 3.6 Canary 11 start failed

### ISSUE THREAD

**Issue by mofada** [flutter/flutter-intellij#3883]
Install the flutter plugin, it will be stuck in the startup interface, and the plugin can be started after deleting the plugin, as shown below.  

![start failed](https://user-images.githubusercontent.com/22286246/64924689-c442b980-d819-11e9-8a53-2394c5c5fa89.png)

When I go to the user directory to delete the plugin, it will open normally.  
![start](https://user-images.githubusercontent.com/22286246/64924632-57c7ba80-d819-11e9-8ddb-a8ae65dce766.png)

**Comment by stevemessick** [comment]
This is a dup of #3869. Leaving it open since it includes the recovery technique.

**Comment by mofada** [comment]
Ok, I am updating

![image](https://user-images.githubusercontent.com/22286246/66023223-1a567300-e523-11e9-96e1-ed525b67ad31.png)
