### ISSUE TITLE
Cannot view implementation class

### ISSUE THREAD

**Issue by mofada** [flutter/flutter-intellij#3884]
I updated the flutter plugin, and now I can't view the implementation class, I can't go in.

![jLHBquwkb3](https://user-images.githubusercontent.com/22286246/64931246-e2380a80-d869-11e9-8a80-76f9db23400f.gif)

I can only view my own implementation class, I can't see the system implementation class.

![Y0Z8XAn6qk](https://user-images.githubusercontent.com/22286246/64931289-37741c00-d86a-11e9-8e4b-3d4f3bf9474a.gif)

**Comment by stevemessick** [comment]
It looks like your Dart analysis server isn't connected. Try restarting it. If that doesn't work the next quickest check is to restart the IDE. Can't tell if that is IntelliJ or Android Studio. While it is shut down also make sure no rogue Dart analysis processes are running. If neither of those work then please append the output of `flutter doctor -v` and a screen shot of the Dart Analysis view.

**Comment by mofada** [comment]
This is Android Studio.

## flutter doctor -v
```
C:\Users\fada>flutter doctor -v
[√] Flutter (Channel master, v1.10.3-pre.44, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)
    • Flutter version 1.10.3-pre.44 at D:\flutter
    • Framework revision b76813411d (10 hours ago), 2019-09-16 12:33:50 +0800
    • Engine revision 31e5149a80
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 d0052c1b31)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\Android\android-studio canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.5)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\Community
    • Visual Studio Community 2019 version 16.2.29306.81

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Android Studio (version 3.6)
    • Android Studio at D:\Android\android-studio canary
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 192.6262.58
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[√] Connected device (4 available)
    • Redmi 4X • c1f5972a7d74 • android-arm64  • Android 7.1.2 (API 25)
    • Windows  • Windows      • windows-x64    • Microsoft Windows [Version 10.0.18362.356]
    • Chrome   • chrome       • web-javascript • Google Chrome 77.0.3865.75
    • Server   • web          • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by mofada** [comment]
Now I can't see the implementation class of the system, it's very bad

**Comment by mofada** [comment]
I tried restarting Android Studio, also tried `File->Invalidate Caches/Restart ...`. I am using Android Studio 3.5 version, Android Studio 3.6 canary 11 can't use flutter plugin #3883 , but I don't have flutter plugin Android Studio 3.6 can view the implementation class

**Comment by stevemessick** [comment]
Thanks for the update.

Did you make sure no rogue Dart analysis processes are running?

Does it work if you use IntelliJ?

What's in the Dart Analysis view?

**Comment by mofada** [comment]
This is Android Studio.

## Android Studio About
![image](https://user-images.githubusercontent.com/22286246/64973213-316b5300-d8dd-11e9-994d-cb847b1c8bcb.png)

## plugin version
![image](https://user-images.githubusercontent.com/22286246/64973269-4d6ef480-d8dd-11e9-8fff-352b03dd6c0f.png)



## Dart Analysis
![x8rapXyeaN](https://user-images.githubusercontent.com/22286246/64973177-1ef11980-d8dd-11e9-9e37-6535dcb2b8a4.gif)

**Comment by mofada** [comment]
This is IDEA.

## IDEA About
![image](https://user-images.githubusercontent.com/22286246/64973409-8b6c1880-d8dd-11e9-8dc6-b1837b39ea59.png)

## Plugin Version
![image](https://user-images.githubusercontent.com/22286246/64973436-98890780-d8dd-11e9-9181-ab56a8f1b5d7.png)

## Dart Analysis
![QaiHqUlSnH](https://user-images.githubusercontent.com/22286246/64973506-bb1b2080-d8dd-11e9-80b2-14458f15a664.gif)

**Comment by mofada** [comment]
But if I open flutter\packages\flutter as a project, it is normal.
![l4f6HF53o6](https://user-images.githubusercontent.com/22286246/64974731-fa4a7100-d8df-11e9-927b-13ae226841bb.gif)


I updated the flutter plugin yesterday, and this happened today, then I went to flutter plugin to download the latest version, I thought the

**Comment by mofada** [comment]
Ok, I tried to downgrade the flutter plugin. It's still the same. Is it because of flutter? I also updated flutter.

![image](https://user-images.githubusercontent.com/22286246/64975031-adb36580-d8e0-11e9-910b-3a9365b9c1c3.png)

**Comment by mofada** [comment]
He suddenly is fine, I am confused.

![image](https://user-images.githubusercontent.com/22286246/65016200-3b7d6800-d956-11e9-96a1-af0332fcb04f.png)

**Comment by mofada** [comment]
My God, he can't do it anymore, I am confused.

**Comment by kenzieschmoll** [comment]
If you update your IDEs and upgrade the flutter-intelliJ plugin, are you still seeing this issue?

**Comment by mofada** [comment]
Sorry, I am late, I updated the plugin and it will be fine, thank you.
