### ISSUE TITLE
Don't tip

### ISSUE THREAD

**Issue by a47781402** [flutter/flutter-intellij#3887]
![1](https://user-images.githubusercontent.com/35242745/65024808-1e519500-d968-11e9-9e1c-1066e92ad023.png)
![2](https://user-images.githubusercontent.com/35242745/65024816-21e51c00-d968-11e9-94ea-ab25edeb18ec.png)
I'm missing some hints in Dart.

**Comment by stevemessick** [comment]
Please provide some context so we can try to reproduce the problem.

A code snippet with expected completions would help. Also include the output of `flutter doctor -v`
