### ISSUE TITLE
Flutter gradle

### ISSUE THREAD

**Issue by shiyaamsundar** [flutter/flutter-intellij#3899]
* Error running Gradle:
ProcessException: Process "C:\Users\Lenovo\Music\flash-chat-flutter-master\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Lenovo\Music\flash-chat-flutter-master\android\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: C:\Users\Lenovo\Music\flash-chat-flutter-master\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by devoncarew** [comment]
Hi @shiyaamsundar, this unfortunately isn't the best place to report gradle issues. You may see if there's more information available from other output / error text, and check stackoverflow or other - like Flutter issues (https://github.com/flutter/flutter/issues) to see if others are having similar problems.
