### ISSUE TITLE
Plugin should use flutter packages get instead of pub get

### ISSUE THREAD

**Issue by Pacane** [flutter/flutter-intellij#390]
When editing the pubspec file, intelliJ tries to run `pub get` to update deps, and by doing so, the following error gets output:

```
Resolving dependencies...
The Flutter SDK is not available.
Depended on by:
- flutter_sample
```

Instead of running pub get, it should run `flutter packages get` / `upgrade`

**Comment by pq** [comment]
Thanks for the report!  Could you check what version of the Dart plugin your have?  It should be fixed as of plugin version `162.2233`.

**Comment by Pacane** [comment]
It says v.0.1.4 here.

**Comment by pq** [comment]
Oh sorry, I mean what version is the _**Dart**_ plugin?

**Comment by Pacane** [comment]
163.6512.13

**Comment by pq** [comment]
Well, that looks good...

What does your Dart SDK path look like?  (**Preferences>Languages & Frameworks>Dart**)?

For example, here's mine:

<img width="748" alt="screen shot 2016-10-31 at 4 33 06 pm" src="https://cloud.githubusercontent.com/assets/67586/19860136/ee59c01a-9f87-11e6-8798-e790749170bc.png">

**Comment by Pacane** [comment]
![image](https://cloud.githubusercontent.com/assets/2762440/19860669/f40877f4-9f5f-11e6-946f-9fc360d4418a.png)

**Comment by pq** [comment]
Hmmm, thanks.  That looks good too.  

@alexander-doroshko: any thoughts?

**Comment by RdeWilde** [comment]
I am experiencing the same problem, though it was working fine a few days ago.

I did a `flutter upgrade` but that did not help either.
Checked updates for IDEAJ, none left.

**Comment by pq** [comment]
Thanks for chiming in @RdeWilde!

That actually exactly what I'd expect.  I was hoping that @Pacane had a similar misalignment but looking at the screenshots suggests that the SDK setting is correct.

> I am experiencing the same problem, though it was working fine a few days ago.

Regarding this, are you aware of having *changed* your SDK settings in the meantime?  (Between when it worked and when it broke?)

**Comment by RdeWilde** [comment]
@pq Not aware, but I've been experimenting a lot, so may have been any upgrade or whatsoever.

**Comment by ScottPierce** [comment]
I'm having the same issue. I have the same issue when I run `pub get` from the command line though.

**Comment by ScottPierce** [comment]
Pointing the intellij dart plugin to use flutters sdk seems to have resolved this for me.

**Comment by alexander-doroshko** [comment]
@pq I'll be reminding every day that my [pull request](https://github.com/flutter/flutter-intellij/pull/361) fixes the issue of diverged Dart and Flutter SDKs. :) 
With it applied you may completely remove `SdkConfigurationNotificationProvider`, it won't be ever triggered any more.

**Comment by alexander-doroshko** [comment]
For IntelliJ IDEA 2016.3 EAP minimal Dart plugin version that does 'pub get' correctly for Flutter is 163.6957.3, @Pacane please update.

**Comment by Pacane** [comment]
It's effectively fixed after updating the dart plugin. Thanks!

**Comment by pq** [comment]
Thanks @Pacane!

Last question: how dependent on using the EAP are you?

**Comment by Pacane** [comment]
Well a lot I guess, since I've been using EAP without license for 2 years now, lol.

**Comment by pq** [comment]
Ha!  OK, that's great to know thanks!

**Comment by thebarunsharma** [comment]
Thanks @RdeWilde , `flutter upgrade` worked for me.
