### ISSUE TITLE
Support Webstorm IDE

### ISSUE THREAD

**Issue by asaarnak** [flutter/flutter-intellij#391]
Feature request to support Webstorm IDE.

I discovered, that in Webstorm the flutter plugin is not found in plugins search. 
But the plugin can be installed manually by downloading https://plugins.jetbrains.com/plugin/9212
If manually installed in Webstorm the Create new project > Flutter is not visible.
Also flutter doctor dosn't check for Webstorm IDE.

**Comment by deftomat** [comment]
Also not found in PhpStorm's plugins search.

**Comment by Martaver** [comment]
Also +1ing my request for WebStorm support.

**Comment by mit-mit** [comment]
@devoncarew can we close this?

**Comment by devoncarew** [comment]
done!

**Comment by devoncarew** [comment]
We no long build the plugin for WebStorm - it didn't offer the best support once flutter added the ability to have native (android / iOS) plugins. I'd suggest trying IntelliJ Community Edition or Android Studio.

**Comment by weihongyu12** [comment]
Now Flutter already supports web development, but also support Webstorm?

**Comment by beansoft** [comment]
@weihongyu12 My personal effort on Flutter supports on WebStorm: https://plugins.jetbrains.com/plugin/14718-flutter-storm
