### ISSUE TITLE
(Android Studio) Case sensitivity in Alt-Enter help

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter-intellij#3920]
It seems that 'Import library' help only gets activated when the class name under cursor exactly matches in char case. E.g. `PropertyModel` has this option but `propertymodel `does not.

Is there a setting to control this?
May I suggest adding this as an option?

**Comment by terrylucas** [comment]
Typing

`import 'l`
will display a list of suggestions known packages that contain an l in the name if no names are displayed or the package you want then the name is not known.  Typing in

`import 'L
`
would display the list of known packages and the one that starts with a capital L

**Comment by duzenko** [comment]
@terrylucas 
Please reopen this ticket or provide appropriate explanation.
It's about the help tooltips called from "Alt+Enter".
