### ISSUE TITLE
Error in my SDK

### ISSUE THREAD

**Issue by EdelcioBatista** [flutter/flutter-intellij#3928]
/home/edelcio/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/edelcio/development/flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/edelcio/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /app/extra/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 3.4)
    • Android Studio at /app/extra
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 3.5)
    • Android Studio at /app/extra/android-studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • ASUS Z012DC • H1AZB600E826FW5 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.

**Comment by pq** [comment]
Hi!  It looks like you've for an out of date Android Studio.  Have you tried updating or reinstalling?
