### ISSUE TITLE
Device recognized, but run buttons not enabled

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#394]
I plugged in my moto g4 and the plugin discovered the device (yay!), but none of the run buttons are enabled:

![screen shot 2016-11-01 at 2 22 37 pm](https://cloud.githubusercontent.com/assets/5479/19908052/c28798ec-a03e-11e6-9726-31e299045e30.png)

I would expect that once a device is recognized, I'd be able to run on it.

Can we enable hot reload and run after I plug in a device?

**Comment by devoncarew** [comment]
There's no launch configuration selected - to tell IntelliJ which app to run.

**Comment by pq** [comment]
> There's no launch configuration selected - to tell IntelliJ which app to run.

I wonder why?  (And whether we should pick one on enablement?)

@sethladd : does this project have any run configurations?  Did you create it with the new project wizard or import it from elsewhere?

**Comment by lukechurch** [comment]
I've just had this problem as well.

- I 'Imported Folder' to load the Flutter/examples/flutter_gallery folder
- IJ asked me to 'enable the Flutter module' or some such. I accepted and it reopened the project.
- Ran Pub Get

I have the project displayed, and the iPhone simulator is correctly discovered, but no run button.

**Comment by stevemessick** [comment]
If restarting IntelliJ causes the buttons to be enabled then Luke's problem will be fixed with https://github.com/flutter/flutter-intellij/pull/393

I'm not sure that will solve Seth's problem, though.

I have another branch ("enablement") I'm working on that will re-jigger buttons, so we'll need to loop back here once that's finished to see if the problem persists. That's still waiting on Flutter #6400 to be fixed (and we're working on that today).

**Comment by sethladd** [comment]
> I wonder why?

I opened the gallery. Not sure if that matters.

> does this project have any run configurations?

Not sure how to tell?

**Comment by pq** [comment]
> Not sure how to tell?

If you click the little chevron, are there any run configurations to choose from?

**Comment by sethladd** [comment]
Nope:

![screen shot 2016-11-02 at 9 32 27 am](https://cloud.githubusercontent.com/assets/5479/19937643/4c042e50-a0df-11e6-9e6e-f58280ee3b98.png)

I think @devoncarew suggested that we auto-populate that list for new projects (with Debug, Profile, and Release, to match the current `flutter run` modes).

**Comment by pq** [comment]
@devoncarew : are there run configs in the gallery IML files?

**Comment by alexander-doroshko** [comment]
Run configs are stored in .idea/worksapce.xml (if not shared) or in ./idea/runConfigurations/ folder (if shared). 

If Seth opened existing project there shouldn't be any run configs as New project wizard has not been invoked.

**Comment by devoncarew** [comment]
There is a run configuration committed in //examples/flutter_gallery. But more generally, I think the use case of newly created projects (`flutter create`) is covered; the flutter tool creates a launch config.

**Comment by sethladd** [comment]
Can we create two default config when you import a new project?

**Comment by alexander-doroshko** [comment]
There are no run configurations committed in /examples/flutter_gallery, and no .idea folder, i.e. no project. That means that if Seth opened /examples/flutter_gallery folder he effectively has CREATED a new project and it contains no run configurations.
But I see that there's .idea folder in the root of the flutter repo, i.e. there's an existing project configured, and this project has some run configurations committed.

**Comment by sethladd** [comment]
Thanks Alex.

Sounds we have two things to do:

* When importing a Flutter project, auto-create common run configs

* Check-in the intellij project files for the Gallery

**Comment by devoncarew** [comment]
I believe this was fixed by https://github.com/flutter/flutter/commit/71900776afbf42eb184d855cad563e39e81c2ab7?
