### ISSUE TITLE
[Android studio] Flutter menu item inactive on Android subproject

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter-intellij#3942]
For some reason the Flutter menu that I used to open the android subproject in a new window is no longer active.
![image](https://user-images.githubusercontent.com/1481807/59421985-41ecc880-8dd8-11e9-97e3-639941eb7cc1.png)

**Comment by terrylucas** [comment]
+stevemessick

Should issue https://github.com/flutter/flutter-intellij/pull/3909 fix this problem too?

**Comment by stevemessick** [comment]
@terrylucas I think so. But an old project may have bad metadata.

**Comment by terrylucas** [comment]
Could you re-create your old project file it probably contains stale or bad metadata that wasn't conversion between either various version of AS or metadata that the plugin add.  This should fix the problem and hopefully won't happen again.  If this problem still occurs re-open this issue.

**Comment by duzenko** [comment]
> 
> 
> Could you re-create your old project file it probably contains stale or bad metadata that wasn't conversion between either various version of AS or metadata that the plugin add. This should fix the problem and hopefully won't happen again. If this problem still occurs re-open this issue.

- This issue is not resolved. Please reopen the ticket.

- How do I re-create the project? Please link to the step-by-step walkthrough.

- Are you sure this is the end-user's problem and there is nothing to fix on your side?

**Comment by terrylucas** [comment]
Here are two links on what is a project in IntelliJ/Flutter and how to create a project from existing source code.

[What is an .idea directory](https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-
)
[Creating a Flutter project from existing source code](https://flutter.dev/docs/development/tools/android-studio#creating-a-new-project-from-existing-source-code)
