### ISSUE TITLE
Can't see my iOS device in IntelliJ running on macOS Catalina?

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter-intellij#3950]
Last night I got an update and I update my machine to  macOS Catalina. Then I upgrade my Xcode to 11. My app already on App Store and Google Play since April. Today I try to update my app and while trying to test on my iPhone 6 and iPhone X, I can't see my iOS device in IntelliJ. I run my app on iOS simulator and it was okay. Then I open the Xcode and run my app from there using my connected iPhone 6 and iPhone X. Its install my app on device with white screen. Than I kill my app and tab an run again an my app opens and works on my iOS device.

When will we can get a same option before that I can see my connected iOS device on IntelliJ? Thanks.

**My flutter doctor -v output:**

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
```
Niyazi-MBP:my_app_name niyazitoros$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale tr-TR)
    • Flutter version 1.9.1+hotfix.4 at /Users/niyazitoros/flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.1.4
    • Dart plugin version 192.6817.14

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by RECKK1** [comment]
Go to Preferences then Languages & Frameworks. Then click on Flutter. You need to update your Flutter SDK path....

**Comment by NTMS2017** [comment]
@RECKK1 Preferences then Languages & Frameworks shows my correct flutter path. there is no flutter option in Schemas and DTDs.

**Comment by WeyanApp** [comment]
I am facing the same problem .. no iphone device .. I can open the simulator from intelli j but no connect iPhones .. connected android phone is Ok.

This started to happend after Catalina Upgrade

**Comment by stevemessick** [comment]
Sorry for the lack of updates here. We don't yet have access to Catalina and I don't know when it is coming, so we can't really do anything currently.

**Comment by AirborneEagle** [comment]
I was having this issue. However, I had already been running it successfully on Catalina. Something got an update and I could no longer user iOS sims.

My solution was found by flutter doctor:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[!] Connected device
    ! No devices available
```

I already had xcode installed and updated for quite a while, so I just ran `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` . and the problem was solved. :)

**Comment by ohhfreddypleaseno** [comment]
> I was having this issue. However, I had already been running it successfully on Catalina. Something got an update (pretty sure it was xcode) and I could no longer user iOS sims.
> 
> My solution was found by flutter doctor:
> 
> ```
> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-US)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [!] Xcode - develop for iOS and macOS
>     ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
>       Download at: https://developer.apple.com/xcode/download/
>       Or install Xcode via the App Store.
>       Once installed, run:
>         sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
> [✓] Android Studio (version 3.5)
> [✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
> [!] Connected device
>     ! No devices available
> ```
> 
> I already had xcode installed and updated for quite a while, so I just ran `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` . and the problem was solved. :)

Working for me, thanks)

**Comment by calebpitan** [comment]
This solved it for me—turning on developer mode

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale
    en-NG)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
    ! Error: To use Caleb’s iPhone for development, enable Developer Mode in
      Settings → Privacy & Security.  (code 6)
[✓] HTTP Host Availability
```
