### ISSUE TITLE
Flutter plugin does not work with Android Studio 3.6 Beta 1

### ISSUE THREAD

**Issue by hydeparkk** [flutter/flutter-intellij#3972]
## What happened

Latest version of Flutter plugin does not work with Android Studio 3.6 Beta 1. Recommended update to 39.0.5 does not work either (as described at #3965)

![image](https://user-images.githubusercontent.com/5124005/66740540-b8c3cc00-ee73-11e9-9a86-a5edbce19148.png)

## Version info

[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale pl-PL)
    • Flutter version 1.9.1+hotfix.4 at .flutterSDK
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android Studio
    • Android Studio at /192.5916306/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 40.1.5
    • Dart plugin version 192.6603.23
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by devoncarew** [comment]
@stevemessick - I'm seeing this as well. It looks like AS 3.6 Beta 1 is selecting 39.0.5 of the Flutter plugin as the most recent compatible version. We may need to adjust the compatible platform version range of the plugin?

AS 3.6.1 shows as

```
Android Studio 3.6 Beta 1
Build #AI-192.6603.28.36.5916306, built on October 2, 2019
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
```

in the about dialog.
