### ISSUE TITLE
VSCode print() not showing in Debug Console

### ISSUE THREAD

**Issue by dimitristaufer** [flutter/flutter-intellij#3975]
My `print()` statements are not showing up anymore in the Debug Console of VSCode when running a Flutter application on an iOS device. However when running through Xcode directly they show in the Xcode console.

**All I get in the VSCode Debug Console after running is the following:**

```
Launching lib/main.dart on Dimitri Staufer in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 955FC8LSJ3
Xcode build done.                                           29.7s
Checking for advertised Dart observatories...
Checking for available port on com.dimitristaufer.awesomeappname._dartobservatory._tcp.local
Checking for authentication code for com.dimitristaufer.awesomeappname._dartobservatory._tcp.local
```

**Flutter Doctor:**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.1)
[✓] Connected device (2 available)

• No issues found!
```
Could very likely be some setting, that I haven't found yet. But I cannot find any similar issue on Github. Thanks in advance.

**Comment by maltsavkiryl** [comment]
I have this exact same problem. Problem only occurs when debugging through VS Code using a physical device. 

it does work when using XCode or a simulator.

**Comment by DanTup** [comment]
I can, but this one is a Flutter issue - see https://github.com/flutter/flutter/issues/41133.

(@kenzieschmoll I've added you to the Dart-Code org so /move should work in future)

**Comment by isira-adithya** [comment]
I found a solution (Temporary) (Windows 10) ,
1 > Open the Command Prompt
2 > Type "adb logcat | findstr flutter" to get the output of the flutter application.

** Hint, You can save below line in a *.bat file to make things easier.
"cls && adb logcat | findstr flutter"

** For Linux, 
Run "adb logcat | grep flutter"

**Comment by shivansh-magnus** [comment]
> adb logcat | findstr flutter

what's the alternative for Mac users . please tell . cause I am getting error -  command not found: adb
