### ISSUE TITLE
Right mouse click causes source to jump 1 line

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#399]
Please see attached video.

![ij screen jumping](https://cloud.githubusercontent.com/assets/2978182/19935573/6f7f4cd8-a112-11e6-9a58-d97964a79b0f.gif)

On right click, the screen jumps up one line, and then displays the menu. It doesn't occur on other software, and only sometimes on IJ. However, it is pretty frustrating when it does happen.

It is probably unrelated, but the first time I started seeing this was after the update of the Dart and Flutter plugins earlier today.

About IJ:

```
IntelliJ IDEA 2016.2.5
Build #IU-162.2228.15, built on October 14, 2016
Licensed to dartlang.org / Luke Church
Subscription is active until May 30, 2017
For non-commercial open source development only.
JRE: 1.8.0_112-release-287-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by devoncarew** [comment]
@alexander-doroshko, do you know if this is a known issue?

It may not be related, but I've seen this frequently in the project explorer view.

**Comment by alexander-doroshko** [comment]
Looks like already fixed: https://youtrack.jetbrains.com/issue/IDEA-162490

**Comment by devoncarew** [comment]
👍 thanks for checking!
