### ISSUE TITLE
IntelliJ Early Access Preview (EAP) Support

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#400]
See: https://github.com/flutter/flutter-intellij/issues/390

Some folks are using the EAP.  If we don't officially support it we should at least document known limitations.

**Comment by alexander-doroshko** [comment]
You do support it, it is 163 branch, still in range both in the repo and in the published plugin build.
EAPs for 171 will start not earlier than in 2 months.

**Comment by alexander-doroshko** [comment]
Not sure you test it against 2016.3 though :)

**Comment by mit-mit** [comment]
@pq is this bug stale?

**Comment by pq** [comment]
Nope.  We're still only supporting `STABLE`.  We don't have a plan in place yet for supporting `HEAD` or `EAP`.

**Comment by mit-mit** [comment]
OK, let's keep it on the backlog for now.

**Comment by pq** [comment]
This will require some build work; closing for now in favor of future targeted issues.

**Comment by devoncarew** [comment]
Re-opening to track general support for EAP releases.
