### ISSUE TITLE
build method guides settings

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4001]
In looking at the preferences we have for build method guides:

- 92.97% of users have build method guides enabled

of those:

- 1.62% have showMultipleChildrenGuides enabled
- 1.49% have showBuildMethodsOnScrollbarKey enabled

I think we should remove the two sub-settings for build methods guides - we should decide to have them always enabled or disabled. I believe that users generally don't change defaults. Our two most popular opt-in settings - format code on save and open the inspector on app launch - have opt-in rates of 7.9% and 3.4% respectively. So lower opt-in values for the two build method guides config options aren't necessarily strong indications of the value of the features.

@jacob314, @InMatrix - thoughts on removing `showMultipleChildrenGuides` and `showBuildMethodsOnScrollbarKey`, and whether they should be on or off?

**Comment by InMatrix** [comment]
Probably fine to turn them off. I think we might want to create some process on launching and shutting down experimental features in the future, including how we communicate with users who have experimental features on.
