### ISSUE TITLE
Enable Dart and Flutter Source

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter-intellij#4003]
In opening flutter project, always needed to `Enable Dart` and specify flutter location on `Flutter SDK path` in flutter setting.

**Comment by jacob314** [comment]
I can't reproduce running Flutter create on the command line and opening the project in IntelliJ? Can you provide more details on how you are created the Flutter project, which IDE you are using, and what version of Flutter and IntelliJ/AndroidStudio you are using?

**Comment by aliyazdi75** [comment]
Creating flutter project is fine but when I download a flutter project on Github for example and wanna open the project directory from Android Studio, this happens:

> In opening flutter project, always needed to Enable Dart and specify flutter location on Flutter SDK path in flutter setting.

Here is my `flutter doctor`:
```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale fa-IR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.39.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by jacob314** [comment]
I'm not sure how much we can do to fix this given it is likely general IntelliJ behavior not something we really have control over.

**Comment by aliyazdi75** [comment]
Oh, that's ok but it's suffering.
You can close it if you want.

**Comment by stevemessick** [comment]
@aliyazdi75 Can you give us more detail on how you download and open a project? I do that frequently and never see your problem. But there are many ways to download and open a project, and maybe you have found one that isn't working right. If there is a specific example we could try, that would be helpful.

**Comment by aliyazdi75** [comment]
@stevemessick 
For example, if you download this [repository ](https://github.com/aliyazdi75/flutter_media_notification)and then unzip it, you have to do some stuffs to reach first state of opening flutter project.
I've got screenshots step by step:
![1](https://user-images.githubusercontent.com/20153831/67615437-8c943d80-f7d9-11e9-89a5-e3eb2b73bf54.jpg)
![2](https://user-images.githubusercontent.com/20153831/67615438-8f8f2e00-f7d9-11e9-8907-aa3f77e7ad00.jpg)
![3](https://user-images.githubusercontent.com/20153831/67615441-9158f180-f7d9-11e9-9036-7897018e9b6b.jpg)
![4](https://user-images.githubusercontent.com/20153831/67615442-9322b500-f7d9-11e9-9bba-c7f709e120d9.jpg)
![5](https://user-images.githubusercontent.com/20153831/67615443-961da580-f7d9-11e9-850f-31db9bdae740.jpg)
I hope this explanation would be helpful.

**Comment by aliyazdi75** [comment]
I think it's not bad to mention that also in creating flutter project, `use AndroidX Artifacts` is checked but the created project is not `AndroidX` supported. It's a bug or my `Android Studio` doesn't work well?

**Comment by stevemessick** [comment]
I wonder if you found a bug that has already been fixed. When I open your `example` project it is recognized as a Flutter project. The source has a prompt to do `pub get` and the highlighting is Dart style.

Try updating Android Studio and its plugins. Let us know how it goes.

**Comment by aliyazdi75** [comment]
It was updated as you see my `flutter doctor` log before.
This happens just on my windows android studio in my office but in my ubuntu it works well.
I don't know maybe I should reinstall my windows android studio.
Thanks for your replies.
