### ISSUE TITLE
Update IntelliJ to use flutter run rather than flutter daemon

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter-intellij#401]
Once [flutter run --machine](https://github.com/flutter/flutter/pull/6645) lands, we should
* [support launching bazel targets](https://github.com/flutter/flutter-intellij/issues/392)
* update other launch targets to use `flutter run --machine` rather than `flutter daemon`

**Comment by pq** [comment]
When we do this should we bump the version of flutter tools and up our minimum requirement?  Or should we support the old and the new worlds?

@danrubel @devoncarew

**Comment by danrubel** [comment]
I recommend bumping the flutter tools version and requiring that version in IJ.

**Comment by pq** [comment]
Sounds good.  Can we bump it when you have the (unrelated) new events work landed?  Or should we do it sooner?

**Comment by danrubel** [comment]
I'll address https://github.com/flutter/flutter/issues/6665 first, determine if there is anything else we need for this, then bump the number.
