### ISSUE TITLE
Analyzer is running very slowly in IntelliJ

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#4012]
## Steps to Reproduce

As I edit the Flutter repo code, the responsiveness of the analyzer integration in IntelliJ seems to get worse and worse.  It helps some to "clear caches and restart", but only for a little while. My memory limit for IntelliJ are boosted (`-Xms512m -Xmx6144m -XX:ReservedCodeCacheSize=512m`), so I don't think that's the issue, or if it is, it's using an awful lot of memory... 

It's slow enough that as I edit code, I can watch the syntax highlighting update about once every two to 15 seconds, which is far to slow to be useful.  The suggestions dialog takes 3-4 seconds to show up, and another second or two to populate, sometimes showing the little in-menu spinner for ten seconds before showing any information, and sometimes it just gives up after 20 seconds or so with "No Suggestions" when I know for sure that there are valid suggestions to make.

Is there any information I can collect for you that will help you fix this? It's really hampering my productivity.

I captured a CPU profiling snapshot while this was happening, if that helps.

## Version info
```
✓] Flutter (Channel add_macos_platform, v1.10.15-pre.240, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.15-pre.240 at [redacted]
    • Framework revision 5a512e325c (2 hours ago), 2019-10-24 08:46:54 -0700
    • Engine revision f56623d65e
    • Dart version 2.6.0 (build 2.6.0-dev.8.1 d43cd7e909)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /opt/my-intellij-ce-current
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402
```

**Comment by alexander-doroshko** [comment]
CPU snapshot would definitely help. Also, logs and auto-collected thread dumps (Help -> Compress Logs...)

**Comment by gspencergoog** [comment]
OK, can I email them to you instead of posting them here?  (I have your jetbrains email).

**Comment by alexander-doroshko** [comment]
@gspencergoog Yes, you can send it directly to me. Even better, open an issue on [YouTrack](https://youtrack.jetbrains.com/issues/WEB?q=%23dart) (Project: Web, Subsystem: Dart) and attach your snapshot and logs to the issue. To keep files private you should mark attachments as visible to `jetbrains-team`.
![image](https://user-images.githubusercontent.com/4499789/67563075-a1fd5f00-f728-11e9-911e-4b27bf61ff3e.png)

**Comment by gspencergoog** [comment]
OK, the issue is https://youtrack.jetbrains.com/issue/WEB-42137

**Comment by alexander-doroshko** [comment]
Thanks, I've analysed the logs, the threaddumps and the CPU snapshot. The problem is with Flutter's `TestLineMarkerContributor` and/or `declaresFlutter()` and such.
![image](https://user-images.githubusercontent.com/4499789/67855606-ccce2580-fb23-11e9-9461-1290daccc751.png)

**Comment by alexander-doroshko** [comment]
Also, there are millions of log entries like this:
```
WARN - eInsight.daemon.LineMarkerInfo - Performance warning: LineMarker is supposed to be registered for leaf elements only, but got: CALL_EXPRESSION (class com.jetbrains.lang.dart.psi.impl.DartCallExpressionImpl) instead. First child: REFERENCE_EXPRESSION (class com.jetbrains.lang.dart.psi.impl.DartReferenceExpressionImpl)
```
See [https://github.com/JetBrains/intellij-plugins/commit/119a83c38584353e69198d84a045e8c9179ca9dc#diff-a76215a1c6ae432db07153fb9706713d this commit] as an example of a proper fix.

**Comment by gspencergoog** [comment]
Yes, that's what I see on the Plugins page: `40.2.4`

**Comment by devoncarew** [comment]
Yes, from looking at the code we're re-parsing the pubspec file on each query (we have some caching for this, but this particular code path is effectively bypassing the cache).

**Comment by devoncarew** [comment]
Moved the 2nd issue to https://github.com/flutter/flutter-intellij/issues/4036.

**Comment by marcglasberg** [comment]
I believe this issue should be reopened. The analyzer is still running very slowly in IntelliJ, for large projects.
 I also opened this one: https://github.com/flutter/flutter-intellij/issues/4142

**Comment by marcglasberg** [comment]
https://youtrack.jetbrains.com/issue/WEB-42685

**Comment by devoncarew** [comment]
> I believe this issue should be reopened. The analyzer is still running very slowly in IntelliJ, for large projects.

I believe the fix here _should_ address the issue. It was committed after the last release and will go out as part of the next one, expected in early December.
