### ISSUE TITLE
we should disable the reload buttons while we’re reloading

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#402]
This will require new events / better progress messages from the flutter command-line tools.

**Comment by stevemessick** [comment]
Could you clarify which buttons you mean? This sounds like something I hoped to accomplished in the enablement branch, but had not actually started coding since it wasn't possible. This will be possible with the daemon api extension we discussed, right?

**Comment by devoncarew** [comment]
Yeah, this is just capturing what we discussed Wed. We have progress tasks that cover the entirety of reload/restart now. We need to change them from app.log to app.progress, and add a stable name for each progress (`flutter.reload` or some such) so that the IDE can ID a certina type of progress.

**Comment by pq** [comment]
Fixed w/ https://github.com/flutter/flutter-intellij/commit/49f79369c3e9e7c0efe591c5ceafdffa5d269a61
