### ISSUE TITLE
"Run" button confusion

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter-intellij#404]
There are (at least) four ways to launch an app in IntelliJ.

There's a very attractive green ▶ button in the toolbar. It does something you basically never want, which is run the app in release mode without assertions or anything.

There's a scary-looking 🐞 icon in the toolbar. It runs the app in debug mode, which is what you want, but even if you already have it running, it restarts the app from the top.

There's an icon that looks like ⚡▶ half-way down the screen. This, I believe, does a hot reload. It's what you usually want.

There's also an ⤿ icon next to it which I guess does a restart.

There are other icons (e.g. a Dart, the triangle to resume the debugger, another circular arrow in the debugger toolbar).

In the P4 and P5 usability studies for Flutter, we saw the following:

- P4 hit the attractive green button multiple times, and would have continued doing that, getting no checked mode assertion development aids and suffering full rebuild load times rather than hot reload, if we hadn't intervened and suggested they try other options. IIRC, after the prompt, they used the bug icon over and over and never experienced hot reload.

- P5 did eventually figure out hot reload but they too were initially confused.

I think the current UI is a non-starter. Watching the participants try to use our current UI is painful.

----

Personally, I would propose the following design:

A single ▶ button that launches the app in debug mode if necessary, and does a hot reload if it's already running.

A drop-down menu next to that button that offers the following options:
* Hot reload (debug mode)
* Restart (debug mode)
* Profile mode
* Release mode

**Comment by b-strauss** [comment]
The arrow and bug buttons do the same thing they do on other Intellij project types, run and debug. Wouldn't it be wrong to change the meaning of these if that is the common pattern on the platform?

As a heavy Intellij user, I would be surprised if they wouldn't do run and debug. Maybe another set of icons would work better?

**Comment by Hixie** [comment]
Neither of the two users in the usability study understood it, and they were both previous IntelliJ users. I don't really care what is standard for IntelliJ if that standard is incomprehensible. :-)

We should care about what is best for our users. If we're successful, our users will be using IntelliJ more for Flutter than for other languages.

Also, if what we do is a substantial improvement over what the standard is (which I think my proposal would be), then I would not be surprised if the rest of the IntelliJ ecosystem followed suit. Let's be leaders and aim higher than the mediocre status quo. Don't be happy with what came before if it sucks. :-)

**Comment by mit-mit** [comment]
Hixie, we are already working on this as per #362 and #407. Both the Run and Debug buttons will correspond to flutter run (without --release), and both buttons will morph into 'reload' buttons (as in Android Studio 'instant run') while you are running (see #230).

Closing this as I believe this has been addressed.

**Comment by Hixie** [comment]
Great! I look forward to seeing how this plays out next time we do usability studies.
