### ISSUE TITLE
"convert to line documentation comment" not showing up

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter-intellij#4063]
I'm not sure if this is the correct place to report it, but there seems to be an issue with `slash_for_doc_comments` + `convert to line documentation comment`.
Fail:
![image](https://user-images.githubusercontent.com/351125/68417597-74c39e80-0175-11ea-80f4-d9db8d210116.png)
Ok: ![image](https://user-images.githubusercontent.com/351125/68417733-b3f1ef80-0175-11ea-9191-ad788898a078.png)

Fail:
```dart
/**
      Human-friendly HSL conversion utility class.
      final number must match the original"
   **/
```
Ok:
```
 /**
   * HSLuv values are ranging in [0;360], [0;100] and [0;100] and RGB in [0;1].
   * @param tuple An array containing the color's HSL values in HSLuv color space.
   * @return An array containing the resulting color's RGB coordinates.
   **/
```

It seems `slash_for_doc_comments` is tied to /** **/ but the fix from intellij is tied to * * *.

**Comment by devoncarew** [comment]
I can repro this - it looks like the `convert to line doc comment` quick assist isn't enabled unless the doc comment is well formed - unless the comment starts with `/**`, ends with `*/`, and the other lines start with ` *`.

I assume this is a bug, as anything within `/**` ... `*/` is a dart doc comment.
