### ISSUE TITLE
IllegalArgumentException from FlutterBuildActionGroup.build()

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4065]
`41.0.2`, `Android Studio/3.5.2`

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'root' of io/flutter/sdk/FlutterSdk.flutterBuild must not be null
 	at io.flutter.sdk.FlutterSdk.$$$reportNull$$$0(FlutterSdk.java)
 	at io.flutter.sdk.FlutterSdk.flutterBuild(FlutterSdk.java)
 	at io.flutter.actions.FlutterBuildActionGroup.build(FlutterBuildActionGroup.java:33)
 	at io.flutter.module.FlutterModuleModel$FlutterGradleLinker.linkNewModule(FlutterModuleModel.java:115)
 	at io.flutter.module.FlutterModuleModel$FlutterGradleLink...
```

**Comment by devoncarew** [comment]
Hmm, @stevemessick, I have a fix for this, but I'm not sure why we can't find the PubRoot in the method `FlutterGradleLinker.linkNewModule(FlutterModuleModel.java:115)`, or what an early exit will mean in terms of the work that the linkNewModule() method is trying to do.

**Comment by devoncarew** [comment]
@stevemessick, do you know if this was address by https://github.com/flutter/flutter-intellij/pull/4097?

**Comment by stevemessick** [comment]
I don't believe it was.

**Comment by stevemessick** [comment]
That was incorrect; #4097 deleted the code that caused this exception.
