### ISSUE TITLE
java.nio.charset.MalformedInputException: Input length = 1 from FlutterModuleImporter.editFileContent(FlutterModuleImporter.java:114)

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4069]
`41.0.2`, `Android Studio/3.5.2`

```
java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
 	at java.io.BufferedReader$1.hasNext(BufferedReader.java:574)
 	at java.util.Iterator.forEachRemaining(Iterator.java:115)
 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
 	at io.flutter.module.FlutterModuleImporter.editFileContent(FlutterModuleImporter.java:114)
 	at io.flutter.module.FlutterModuleI...
```

@stevemessick, from a brief look at the code, it looks like one of the two files we're reading can sometimes be of length 1, and the char encoding we're passing into `Files.newBufferedReader` doesn't like that. I don't know if that means we should change the encoding we're using to read the file (the other Files.newBufferedReader method uses UTF-8), or find some other way to read the contents.

**Comment by stevemessick** [comment]
I'm changing it to use StandardCharsets.UTF_8.

**Comment by devoncarew** [comment]
You may want to test how that reacts to a 1-char long file. And - it looks like we read two files w/ the `editFileContent()` method - are they both expected to be in UTF8?

**Comment by devoncarew** [comment]
Fixed in https://github.com/flutter/flutter-intellij/pull/4097
