### ISSUE TITLE
update the behavior of the run and debug buttons

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#407]
We should update the behavior of the run and debug buttons to address some UX issues:

- [x] the run button should be changed from executing `flutter run --release` to `flutter run` (just like the current debug button) (#445)
- [x] the run button should not set breakpoints and not break on exceptions (it's the same as the debug button, but without debuggability)
- [ ] we contribute a hot reload and a restart app button to the run toolbar; these should likely be visible when the currently selected config is hot reloadable (or when the device chooser is visible)
- [x] when an app is executing, the run and debug buttons become disabled (the launch config reports that it can't run if any running apps were launched from that config)

**Comment by mit-mit** [comment]
Details of the 'lightning bolt' behavior are discussed in https://github.com/flutter/flutter-intellij/issues/230

**Comment by alexander-doroshko** [comment]
Make sure that you do not modify Run/Debug icons and behavior if currently selected run configuration in the combo box is not the one that you want to hot reload or whatever. It is a valid use case:
- select 'MyFlutterApp1 (debug)' in the combo box, Debug it
- select not related 'Some Java Server' run config, Run or Debug it
- etc.
- select 'MyFlutterApp1 (debug)' again. Hot reload it

**Comment by sethladd** [comment]
Nice! Thanks for writing out this plan. sgtm, looking forward to trying it out.

**Comment by devoncarew** [comment]
@pq, possibly for `0.1.5`?

**Comment by mit-mit** [comment]
Closing #230 as a covered by this, so including the Android Studio screenshot here:

![android-studio-intant-run](https://cloud.githubusercontent.com/assets/8518285/19076423/91331200-89fd-11e6-8f50-526e7a1a0082.gif)

**Comment by pq** [comment]
I did some digging into this on Friday and I see some challenges on the UI front.  In particular, it doesn't look like hijacking the run/debug button icons and tooltips is straightforward.  I'm guessing this is a place where AS hacked the platform.

Curious if @alexander-doroshko has any thoughts?

**Comment by alexander-doroshko** [comment]
I didn't look into AS source code, but I haven't heard of a legal way to manipulate Run/Debug icons, tooltips, etc.

**Comment by alexander-doroshko** [comment]
You might be interested in looking how Android plugin in IntelliJ IDEA behaves. It may have different UI tricks than AS itself.

**Comment by devoncarew** [comment]
Broke part of this issue out specifically to target 0.1.6.

Moving to `On Deck`, but we should spent time during the 0.1.6 release to explore customizing the buttons.

**Comment by devoncarew** [comment]
Just some continued discussion: the remaining issue is one of discoverability of the reload and restart buttons. We could solve this a few ways - updating the icons for the main run and debug buttons, adding additional icons to the toolbar when we're running, ...

**Comment by pq** [comment]
Regarding discovery, I've been experimenting w/ adding buttons to the main toolbar.  It looks like maybe the best we can do is add to the end (or start) of a button group.  Here's what it looks like if we add them to the end of the `RunGroup`:

<img width="651" alt="screen shot 2016-12-08 at 6 34 34 pm" src="https://cloud.githubusercontent.com/assets/67586/21035624/36343d1a-bd75-11e6-89da-fedbb69c1672.png">

Might be a good start anyway.

Curious what you guys think.

@devoncarew @mit-mit

**Comment by devoncarew** [comment]
I like it! Logically in terms of ordering, they should likely go between the starting buttons (run and debug) and the stop button, in order to follow a lifecycle-like order. Sounds like that's not immediately feasible; perhaps we put a new JSeparator between the stop button and the reload+restart, in order to make the ordering not seem random? Or at least, something else to experiment with, to find out which feels most natural.

**Comment by mit-mit** [comment]
Yeah, looks pretty good if we add a separator
![car](https://cloud.githubusercontent.com/assets/13644170/21041806/c9044784-bded-11e6-80ce-ca2389844a3a.png)
:

**Comment by pq** [comment]
Cool.  A separator is easy.

<img width="473" alt="screen shot 2016-12-09 at 6 12 06 am" src="https://cloud.githubusercontent.com/assets/67586/21051728/71f7c5a4-bdd6-11e6-9cf8-429e82630a9f.png">

Looking now at refactoring the way that state is tracked so we get the desired enablement semantics which is a little trickier...

**Comment by sethladd** [comment]
What's the thinking for how to guide developers over to the green+bolt button (which I think is Hot Reload?). Do we gray-out the green button after you initially run the app? 

Is it possible to swap icons of the button (changing green run button to green+bolt once you have an app up and running) ?

**Comment by pq** [comment]
> Is it possible to swap icons of the button (changing green run button to green+bolt once you have an app up and running) ?

Unfortunately, no.   Or at least not easily.  Once active, the button gets a little dot.

<img width="162" alt="screen shot 2016-12-09 at 10 33 08 am" src="https://cloud.githubusercontent.com/assets/67586/21060176/ef909724-bdfa-11e6-92fa-ab09fa3c1520.png">

Actively exploring other refinements.  Needless to say, ideas welcome!

**Comment by sethladd** [comment]
Gray-out the green run button once pressed?

**Comment by devoncarew** [comment]
I updated the main description above to list what we've already done here and what more is planned.

**Comment by pq** [comment]
Screenshot with snazzy new icons.

<img width="408" alt="screen shot 2016-12-20 at 1 01 08 pm" src="https://cloud.githubusercontent.com/assets/67586/21367812/7371ded8-c6b4-11e6-8b4a-4997349ae1fa.png">


Still WIP but closing in!
