### ISSUE TITLE
Provide widget suggestions as part of the "wrap with new widget" workflow

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#4082]
## Problem
Users have difficulty recalling widget names and discovering useful new widgets. 

## Proposal
As a short-term enhancement, we can extend the existing "wrap with new widget" refactor assist to suggest widgets that are more likely to be parent of the selected widget. In the long run, a visual widget editor can provide better affordances for applying modifications to a given widget without having the user explicitly decide whether they want to wrap it in a new widget or changing its properties.

**Comment by jwren** [comment]
Closing as not planned, any and all functionality in this space is being handled by the Dart DevTools UX. @elliette @kenzieschmoll
