### ISSUE TITLE
Expose --release and --profile modes

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#410]
Currently both the `Run > Run` and `Run > Debug` actions  produce a debug build, i.e. they correspond to `flutter run --debug` (historical background is in #362 and #404).

Thus there is no way of running `--release` or `--profile` from IntelliJ. This is concerning as developers who use just the IDE might get the impression that all flutter apps are slow, and it means that release testing and profiling is not possible from the IDE. We should find some way of exposing these from IntelliJ.

***Note***: Developers can use this workaround until this is fixed:

To run in release mode, enter this in the terminal:
```
cd <location of app>
flutter run --release
```

To run in profile mode, enter this in the terminal:
```
cd <location of app>
flutter run --profile
```

**Comment by stevemessick** [comment]
I think this has been suggested elsewhere, but in case it hasn't you could extend the launch configuration to include a `Build mode`. Flutter actually has three options: debug, release, and profile. You'd need to ensure the Debug button was disabled if a Release mode launch configuration was selected.

**Comment by mit-mit** [comment]
Yes, I can think of at least three different ways of doing this:

1. Add a build mode option to launch config, and create a default config for each of those
1. Add a custom build mode option box next to the Run/Debug buttons
1. Add  'Install release mode app' / 'Install profile mode app' actions somewhere in the menu / toolbar

**Comment by skybrian** [comment]
Also, the FAQ is out of date:

"If you are using the Flutter plugin for IntelliJ, you can disable Slow Mode by using the Run>Run action rather than Run>Debug."

https://flutter.io/faq/#my-app-has-a-slow-mode-bannerribbon-in-the-upper-right-why-am-i-seeing-that

**Comment by mit-mit** [comment]
FAQ updated in https://github.com/flutter/website/pull/444. 

Remember to update that again when this bug is resolved.

**Comment by mit-mit** [comment]
@pq @devoncarew now that we have other Flutter actions in the Run menu, I think a variant of option 3 above seems natural:

* Add 'Run in release mode' and 'Run in profile mode' menu items below the current 'Full App Restart' item ?

**Comment by pq** [comment]
I lean towards adding options to the Run Config to start as I worry that the menu is already kind of overwhelming.  Don't feel too strongly though!

**Comment by devoncarew** [comment]
A good place to start here would be to add two new menu items to the Run menu (we already have a contributed Flutter section):

- `Run in profile mode...`
- `Run in release mode...`

**Comment by pq** [comment]
WIP:

![screen shot 2017-04-10 at 2 27 31 pm](https://cloud.githubusercontent.com/assets/67586/24883464/dfee59f0-1df9-11e7-9609-b0c533dc14fa.png)

(Still playing with icons.)

**Comment by devoncarew** [comment]
👍 

Perhaps the 'run in release mode' icon should just be a run icon?

**Comment by pq** [comment]
Sure thing!

![screen shot 2017-04-10 at 3 27 43 pm](https://cloud.githubusercontent.com/assets/67586/24885254/50a9e8aa-1e02-11e7-8013-8b30128b5aaa.png)
