### ISSUE TITLE
[Request] Show widget back-tree like Kotlin does

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter-intellij#4103]
When I am inside a method, I wish I could see the back-history/tree like Kotlin does. When you click, it scrolls back to the starting of the method. This is more a Dart request than Flutter, but long chain of widgets is something frequent in Flutter, not Dart.

Example:
![image](https://user-images.githubusercontent.com/351125/68782678-8b0ba780-0618-11ea-810f-ac8f079fd178.png)
in
![image](https://user-images.githubusercontent.com/351125/68695742-5afdcf00-055a-11ea-8aaa-d4fbff99fc88.png)

**Comment by alexander-doroshko** [comment]
Thanks for the feature request!
The feature is called 'breadcrumbs' and is tracked as #3576 and also https://youtrack.jetbrains.com/issue/WEB-33823

**Comment by bernaferrari** [comment]
lol, would have never guessed it, thanks!
