### ISSUE TITLE
NoSuchMethodError from FlutterProjectStep.onWizardStarting, Android Studio/4.0 Canary 1

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4106]
`41.1.3`, `Android Studio/4.0 Canary 1`

```
java.lang.NoSuchMethodError: com.android.tools.adtui.validation.ValidatorPanel.registerValidator(Lcom/android/tools/idea/observable/ObservableValue;Lcom/android/tools/adtui/validation/Validator;)V
 	at io.flutter.project.FlutterProjectStep.onWizardStarting(FlutterProjectStep.java:148)
 	at com.android.tools.idea.wizard.model.ModelWizard.<init>(ModelWizard.java:124)
 	at com.android.tools.idea.wizard.model.ModelWizard.<init>(ModelWizard.java:47)
 	at com.android.tools.idea.wizard.model.ModelWizard$Builder.build(...
```

FYI @stevemessick, it looks like we'll need to update the wizard pages API use for the AS 4.0 canary.

**Comment by stevemessick** [comment]
There is more to it than that. We can't distribute a build for canary until our dev channel is in place. I'm not planning to have this for M42. There are a lot of API changes in ADS4.

**Comment by devoncarew** [comment]
We may need to do something around messaging in the IDE then. We are seeing people using Canary and the Flutter plugin. This exception, and the one below, are being reported:

`41.2.3`, `Android Studio/4.0 Canary 3`

```
java.lang.NoSuchMethodError: org.jetbrains.android.facet.AndroidFacet.getProperties()Lorg/jetbrains/jps/android/model/impl/JpsAndroidModuleProperties;
 	at io.flutter.project.FlutterProjectCreator.disableUserConfig(FlutterProjectCreator.java:233) 	at io.flutter.FlutterStudioStartupActivity.runActivity(FlutterStudioStartupActivity.java:63)
 	at c.i.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:205)
 	at c.i.ide.startup.impl.StartupManagerImpl.lambda$null$1(StartupManagerImpl.java:181)
 	...
```

**Comment by stevemessick** [comment]
We already have this:
<img width="379" alt="Screen Shot 2019-11-15 at 1 18 57 PM" src="https://user-images.githubusercontent.com/8518285/68976471-aa3a3e80-07aa-11ea-9cd4-7171b1ee8006.png">

I haven't found a (good) way to prevent the plugin from being installed in ADS4. The build it is based on is the same as the beta (192.6817.14.36). I had been trying to prevent it, but as you can see in the OP it loaded the newer beta version of the plugin in the older canary. So I just loosened the "until" build so we won't have to keep re-releasing new versions of the plugin each time a new beta comes out.

**Comment by stevemessick** [comment]
Oops, trackpad slipped, accidentally hit the Close and comment button.

**Comment by devoncarew** [comment]
> We already have this:
> <img alt="Screen Shot 2019-11-15 at 1 18 57 PM" width="379" src="https://user-images.githubusercontent.com/8518285/68976471-aa3a3e80-07aa-11ea-9cd4-7171b1ee8006.png">

Ah, yes, I'd forgotten.

**Comment by stevemessick** [comment]
Closing as obsolete.
