### ISSUE TITLE
Consider a different icon for launching observatory

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#414]
Right now the icon is the Dart logo, which is fairly overloaded icon. I wonder if we can make a specific icon for Observatory.

strawman: Perhaps a telescope?

**Comment by sethladd** [comment]
cc @johnmccutchan for ideas here

**Comment by stevemessick** [comment]
Totally agree the Dart icon is overloaded in IntelliJ. Sorry I don't have any better suggestions yet.

**Comment by sethladd** [comment]
Hm, I wonder if part of the challenge here is that "Open Observatory" is really a solution to many different user intents: CPU Profile, VM Debug, Memory profile, etc. We could have icons for each one of those, which would be a bit more specific.

In the meantime, https://material.io/icons/#ic_developer_board is an idea.

I'm happy to commission an icon, too. The literal idea that comes to mind: "an observatory with a telescope".

What do yall think?

**Comment by stevemessick** [comment]
The developer board is similar to what my mental picture was. I also thought of a microscope because the tool is sorta dissecting your program and putting it under a microscope (but not really). Other things to consider:
- IDEA has buttons for Run, Debug, Profile that people are familiar with that could provide visual clues
- The button launches you out of IntelliJ, into the browser where the Observatory UI runs

Perhaps you're thinking of something [like this,](https://d18gmz9e98r8v5.cloudfront.net/ptr/20140703201303_938669017_1148_9.jpg) using the structure as inspiration for an icon.

**Comment by johnmccutchan** [comment]
+1 to developer board
+1 to an observatory / telescope / microscope

**Comment by sethladd** [comment]
If developer board works, then I don't need to commision a new icon. So let me know if that doesn't work. :)

**Comment by johnmccutchan** [comment]
go with developer board.

**Comment by mit-mit** [comment]
@devoncarew can we use the material icons, such as the https://material.io/icons/#ic_developer_board one, as-is?

**Comment by devoncarew** [comment]
Yeah, or we could colorize it a bit if that would help it fit in better with the other icons.

**Comment by devoncarew** [comment]
Hmm, it doesn't grab me:

<img width="127" alt="screen shot 2016-12-13 at 6 56 44 pm" src="https://cloud.githubusercontent.com/assets/1269969/21194074/6b8e0a82-c1e3-11e6-8927-27ccc9c225a0.png">

<img width="161" alt="screen shot 2016-12-13 at 6 57 00 pm" src="https://cloud.githubusercontent.com/assets/1269969/21194075/6b972392-c1e3-11e6-8f2c-5865e54b40bb.png">

I'm not sure that there's an icon that would jump out at me as a 'click to open the observatory' icon.

**Comment by mit-mit** [comment]
Just got a new idea, how about an 'eye' icon?
https://material.io/icons/#ic_remove_red_eye

**Comment by devoncarew** [comment]
OK, like the eye of Sauron?

There's also this guy: https://material.io/icons/#ic_wb_incandescent

**Comment by devoncarew** [comment]
https://material.io/icons/#ic_timer ?

**Comment by mit-mit** [comment]
I like eye and timer. Incandescent seems hard to decode.

**Comment by devoncarew** [comment]
And, cycling back to this comment:

> if part of the challenge here is that "Open Observatory" is really a solution to many different user intents: CPU Profile, VM Debug, Memory profile, etc. We could have icons for each one of those, which would be a bit more specific

I do think that we would be better off offering different entry-points for specific actions that a user wants to take, and not a big-bucket "Open Observatory" action.
