### ISSUE TITLE
Provide feedback when a user configures a partially setup Flutter SDK

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#415]
Follow-up from #361:

> Perhaps we can suggest some user actions to remedy a partially set up flutter sdk. Something like:
> * recognize that it is a valid flutter sdk, but one that does not yet have its dart-sdk provisioned
> * respond w/ an error when the user tries to set it as the flutter sdk, but say something like 'Please run the flutter command-line tool to finish set up of the flutter sdk'.

**Comment by alexander-doroshko** [comment]
#428
