### ISSUE TITLE
Support Android Studio 4.0

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4166]
We should add support for Android Studio 4.0 once it comes out of Canary (support Beta and on). cc @stevemessick 

https://github.com/flutter/flutter-intellij/issues/4136 (and related) for context

**Comment by devoncarew** [comment]
@stevemessick - is this likely for this milestone?

**Comment by stevemessick** [comment]
Yes, I think it will be required.

**Comment by jld3103** [comment]
Is that related to IntelliJ IDEA 2020? Because the plugin is also incompatible with the latest EAP of IntelliJ IDEA.

**Comment by sumanthratna** [comment]
Android Studio 4 was just released. Is there an ETA on when the flutter plugin will gain support? When I click Check for Updates in Android Studio, this is what I see:

![Screen Shot 2020-05-28 at 13 48 19](https://user-images.githubusercontent.com/31281983/83175471-ee0ee880-a0e9-11ea-9d9f-4f1216a1ce78.png)

**Comment by devoncarew** [comment]
Can you try updated and restarting? You may then see a prompt about new plugin versions being available.

**Comment by sumanthratna** [comment]
Oh, you're right; that worked! Thanks!

**Comment by devoncarew** [comment]
Great, thanks for checking.

**Comment by paulpjoby** [comment]
> Android Studio 4 was just released. Is there an ETA on when the flutter plugin will support 4.0? When I click Check for Updates in Android Studio, this is what I see:
> 
> ![Screen Shot 2020-05-28 at 13 48 19](https://user-images.githubusercontent.com/31281983/83175471-ee0ee880-a0e9-11ea-9d9f-4f1216a1ce78.png)

What a timing man .... I was about to ask this question awesom

**Comment by omkarghurye1998** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://stackoverflow.com/questions/62897458/flutter-plugins-not-recognized-in-android-studio-4-0&ved=2ahUKEwi3vIeBls3qAhVQzDgGHQUrDysQFjADegQICRAB&usg=AOvVaw3-Pv0VDpdAOzUh167imp7G&cshid=1594744863124
