### ISSUE TITLE
Android studio 

### ISSUE THREAD

**Issue by moga111** [flutter/flutter-intellij#4185]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
After updating to latest android studio version 3.5.3, additional window is opened if the project is flutter. Opening a normal Android project does not cause this.

_Please tell us what you were doing and what went wrong_
I restarted to install latest gradle version, then after that additional window per flutter project was opened that I couldn't close.

The reason I think its caused by the plugin is because its happening only on flutter project.

## Version info
Android: 3.5.3
Gradle: 3.5.3
Flutter plugin: 42.0.1

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, v1.12.13+hotfix.2, on Mac OS X 10.15.1 19B88, locale en-CA)
    • Flutter version 1.12.13+hotfix.2 at /Users/moga/Development/flutter
    • Framework revision 4f54e46f56 (2 days ago), 2019-12-04 09:20:18 -0800
    • Engine revision 6955b06ced
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/moga/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/moga/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 191.7830
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Nexus 5 • 035571002169e21e • android-arm • Android 6.0.1 (API 23)

**Comment by Zazo032** [comment]
Reproduced here aswell, just upgraded to latest Android Studio (3.5.3) and latest Flutter plugin version (42.0.1). After running some commands (like `flutter clean` or `flutter packages get`), a new blank window is opened, and if you close it, it closes every Android Studio window.

**Comment by Zazo032** [comment]
Still happening on latest 42.1.1

**Comment by Zazo032** [comment]
This might be _a bit_ annoying, as if you close any of the open instances, all of them close at once... Not happening before 42.0.1, so this is likely a regression. This is after ~2.5 hours of work.

![image](https://user-images.githubusercontent.com/2807712/70709017-31140580-1cdc-11ea-9069-e74457538d6d.png)

**Comment by terrylucas** [comment]
Do you have other plugins installed?

Can you open flutter_gallery and run or create a simple Flutter application and run?

**Comment by Zazo032** [comment]
These are the plugins I have installed, but the issue started after updating only the Flutter plugin:

![image](https://user-images.githubusercontent.com/2807712/70792838-5cf5c080-1d9a-11ea-86a5-6f9bf713ecc8.png)

It happens on every Flutter project, Android projects work as inteded

**Comment by MiloHwb** [comment]
Same here.

**Comment by pq** [comment]
Is this the same issue as #4217?

**Comment by Zazo032** [comment]
The final result seems similar (blank windows opening from time to time) but I don't have any error log on the console

**Comment by stevemessick** [comment]
Fixed by #4271
