### ISSUE TITLE
Meaningless message

### ISSUE THREAD

**Issue by sctajc** [flutter/flutter-intellij#4186]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
If I run Flutter Upgrade I get:

C:\src\flutter\bin\flutter.bat --no-color upgrade
Your flutter checkout has local changes that would be erased by upgrading. If you want to keep these changes, it is recommended that you stash them via "git stash" or else commit the changes to a local branch. If it is okay to remove local changes, then re-run this command with --force.
Process finished with exit code 1

I have no local changes. Or if I do, I don't want them and want to remove them.  Sure I can run with --force but I would sooner fix the problem. For some reason Android Studio wants me to use gradle version 4.10.?? and not the latest. 

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
Microsoft Windows [Version 10.0.18362.476]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\sctaj\AndroidStudioProjects\todoey_with_firebase>
C:\Users\sctaj\AndroidStudioProjects\todoey_with_firebase>C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\src\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\sctaj\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

C:\Users\sctaj\AndroidStudioProjects\todoey_with_firebase>
C:\Users\sctaj\AndroidStudioProjects\todoey_with_firebase>

**Comment by terrylucas** [comment]
This happens (usually because of beta or tip of trunk).  Using the Dev channel should help or using git stash.  if you use git status what files are returned?

```
  (use "git add <file>..." to include in what will be committed)
	android/.uuid
	android/gradle/.uuid
```

See the solutions [https://github.com/flutter/flutter/issues/18893]( https://github.com/flutter/flutter/issues/18893)
