### ISSUE TITLE
Add vertical parameter view

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#4195]
Flutter has widgets with lots of options, so when I am creating a new `RaiserButton` and I want to see its parameters with `Ctrl+P`, I get this:

![image](https://user-images.githubusercontent.com/8120472/70563137-731e3980-1b6c-11ea-9c45-167d4413a20d.png)

Which isn't much helpful to look at the options and find which ones I want.

It would be nice to have a way to show this same list as a vertical list, something close to this:

![image](https://user-images.githubusercontent.com/8120472/70563226-9d6ff700-1b6c-11ea-8b20-32b517cfceb7.png)

Which is the way Flutter is actually coded, because it's a lot easier to read and follow.

Maybe hitting `Ctrl+P` once brigs the list as vertical and hitting again toggles between vertical and horizontal?

**Comment by devoncarew** [comment]
cc @jwren

**Comment by jwren** [comment]
The action you want is `Ctrl + Q`, when I went to test this however a bug was exposed.  I just uploaded a PR to fix the bug: https://github.com/JetBrains/intellij-plugins/pull/748.

![hover](https://user-images.githubusercontent.com/1533520/70575017-5aa52380-1b5a-11ea-86a0-4aa3e35f2fe3.png)

**Comment by feinstein** [comment]
`Ctrl+Q` gives me this:

![image](https://user-images.githubusercontent.com/8120472/70575627-a620f700-1b85-11ea-8bcd-083c4fb9b653.png)

Also, I don't think `Ctrl+Q` provides highlighting of the current parameter (onHighlightChanged in my first picture.... pun not intended, just a coincidence haha), as `Ctrl+P` does.

**Comment by jwren** [comment]
Correct, `Ctrl+Q` will give you the stack, but not the highlight.

Your request for a vertical stack for the parameter info can be tracked here: https://youtrack.jetbrains.com/issue/IJSDK-754
