### ISSUE TITLE
flutter is not working correctly

### ISSUE THREAD

**Issue by alitasawar** [flutter/flutter-intellij#4197]
My flutter doctor is saying no issues found,,
but my android studio is just showing loading  when i click dropdown emulator( which is connect is there {adb devices}),by clicking on in fires up the emulator 
Note i resolved all issues 
but when i hit play button it shows error {no Connected devices found}
while it is showing emulator in cmds & flutter doctor 

if u know any possible solution plz reply i wasted a lot of time on this but no solution is found yet

**Comment by terrylucas** [comment]
You might want to try a 'Wipe Data' of the emulator or delete and recreate the emulator using Anddroid Studio's AVD (Android Virtual Device Manager).  I have found that sometimes the emulator gets in a wedged state.

If that doesn't work 

attach the out from 'flutter emulators' and flutter doctor
