### ISSUE TITLE
Not showing "Open for editing in Android Studio" and disabled Flutter menu

### ISSUE THREAD

**Issue by PatrykKot** [flutter/flutter-intellij#4204]
## Steps to Reproduce

1. Create new project by File -> New Flutter project...
2. Run `git init`, commit and push project to GIT repository
3. Clone project from repository and open in Android Studio
4. .iml files do not exist anymore (because of generated .gitignore file) . "Open for editing in Android Studio" does not show and Flutter menu is disabled after right mouse click on "android" directory .

## Version info

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available
```

**Comment by terrylucas** [comment]
This is more of a git issues.  When you committed your PR is the iml file in your repository?  After you cloned the project did the iml exist in your local branch?

Was the iml there before you opened your cloned project in Android Studio?

What is the contents of your .gitignore file?

**Comment by PatrykKot** [comment]
When I created a new Flutter project, it contained two iml files: one in root directory and one in _android_ directory. Content of the .gitignore file in root directory below:
```
# Miscellaneous
*.class
*.log
*.pyc
*.swp
.DS_Store
.atom/
.buildlog/
.history
.svn/

# IntelliJ related
*.iml
*.ipr
*.iws
.idea/

# The .vscode folder contains launch configuration and tasks you configure in
# VS Code which you may wish to be included in version control, so this line
# is commented out by default.
#.vscode/

# Flutter/Dart/Pub related
**/doc/api/
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.packages
.pub-cache/
.pub/
/build/

# Web related
lib/generated_plugin_registrant.dart

# Exceptions to above rules.
!/packages/flutter_tools/test/data/dart_dependencies_test/**/.packages
```

As you can see, git has been told to ignore all .iml files. So after commiting project to the repository, the repository does not contain iml files anymore. When I clone this repository and open in Android Studio, iml files are not generated again. The problem is that Android Studio (Flutter plugin) needs the iml files (at least in _android_ directory) to show _Open for editing in Android Studio_ and to enable Flutter menu. I don't think it's a git issue.

**Comment by PatrykKot** [comment]
Why is this closed? Every time I create new project I have to change .gitignore file to not ignore .iml files? This is just an inconsistency of the project generation mechanism and plugin operation logic.
