### ISSUE TITLE
"Wrap with Center" and "Wrap with Padding" are not active in Flutter Outline Tool panel

### ISSUE THREAD

**Issue by hiikanych** [flutter/flutter-intellij#4212]
## Steps to Reproduce

I try wrap Row widget with Center (or Padding) widget by button in Flutter Outline Tool panel, but this button is not active.

![Image 1](https://user-images.githubusercontent.com/58398607/70782324-ce803f80-1d97-11ea-88c7-afda686008d7.jpg)

## Version info
C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18363.476], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\src\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\xxx\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Google Pixel 2 • 192.168.226.102:5555 • android-x86 • Android 9 (API 28)

• No issues found!
Process finished with exit code 0

**Comment by terrylucas** [comment]
You need to define

        `factory MyWidget.forDesignTime() `

inside of your DicePage widget.

see [Live Widget Preview](https://medium.com/flutter/flutter-outline-hot-reload-and-the-implementation-of-a-live-widget-preview-69abd39aa3bb)
