### ISSUE TITLE
3rd Party package stop working when i update to flutter 1.12 and not is not working for 1.9  says cant go to target url

### ISSUE THREAD

**Issue by girish54321** [flutter/flutter-intellij#4222]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by pq** [comment]
Hi!  Could you provide a little more context?  What package?

Can you give us a simple reproduction of what you're seeing?
