### ISSUE TITLE
Android Studio RC1 stuck at loading page

### ISSUE THREAD

**Issue by MiloHwb** [flutter/flutter-intellij#4227]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I just update Android Studio to 3.6 RC1，Android Studio stuck at loading page. When I delete all the plugins I installed Android Studio open normally. Then I tried just install flutter and dart plugin and Android Studio stuck again.

![2019-12-18 102425](https://user-images.githubusercontent.com/19384393/71050531-68712f00-2180-11ea-8f62-a4566079a14b.png)

## Version info

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at C:\develop\flutter
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\develop\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\develop\Android\SDK
    • Java binary at: C:\develop\Android\Android Studio Beta\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\develop\Android\Android Studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.6)
    • Android Studio at C:\develop\Android\Android Studio Beta
    • Flutter plugin version 42.1.3
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • MI MAX 3 • 4735a055 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by devoncarew** [comment]
Thanks for the report! This is a dup of https://github.com/flutter/flutter-intellij/issues/4228.
