### ISSUE TITLE
Flutter i18n plugin not working with intellij 2019.3

### ISSUE THREAD

**Issue by DhavalRKansara** [flutter/flutter-intellij#4232]
After upgrading my Intellij to the latest version 2019.3, [flutter i18n](https://plugins.jetbrains.com/plugin/10128-flutter-i18n/) plugin is not working properly. Even when I am trying to import [flutter i18n](https://plugins.jetbrains.com/plugin/10128-flutter-i18n/) from disk it gives me the below error:

<img width="400" alt="Screen Shot 2019-12-19 at 1 16 29 PM" src="https://user-images.githubusercontent.com/44993081/71154561-c9246880-2261-11ea-814a-697262d72fa7.png">

Also, after installing the plugin from Marketplace, `i18n.dart` file is not auto-generating in my project.

It was working fine till the flutter version 2019.2.

**Comment by devoncarew** [comment]
Thanks for the report! That plugin is developed by the community, and not by the Flutter team directly. I'd open an issue on their issue tracker.

If it looks like it's no longer maintained (I don't have data either way), please open an issue on this repo w/ some details about the use cases you were using it for. Thanks!

**Comment by DhavalRKansara** [comment]
@devoncarew Is there any update on this?

**Comment by devoncarew** [comment]
Hi @DhavalRKansara - the same as my last message. I'd encourage you to file an issue on the repo for that plugin, or, open a new issue here w/ some details about a feature request wrt internationalization.
