### ISSUE TITLE
assembleDebug takes forever

### ISSUE THREAD

**Issue by deadpoolglitch** [flutter/flutter-intellij#4236]
This is the first time i am commenting i have the same problem(assembleDebug takes forever)and when i run flutter run -v it stops to download htttps://services.gradle.org/distributions/gradle-5.6.2-all.zip its a 137 mb file as of now . Due to network issue i need another way to download this on my android phone and later extract it to pc and resolve issues such as Path or anything that comes later could anyone help. The network issue is that i see java.exe using all the internet and so im confused as if it is downloading what i need or just wasting my internet data.

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by pq** [comment]
Likely a dup of https://github.com/flutter/flutter/issues/47603 ?

/cc @jacob314

**Comment by jacob314** [comment]
Looks like a dupe to me.

**Comment by deadpoolglitch** [comment]
Never mind i solved it by changing gradle version in wrapper.properties to what a running new project would use(hope this helps someone)
