### ISSUE TITLE
CTRL-Shift-N (find files) is now totally broken in IntelliJ. Must fix ASAP.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#4238]
CTRL-Shift-N is now totally broken in IntelliJ. It tries to find the letter I type in any random order in the file name. So it never finds what I want, and shows a lot of useless files. You are now forcing me to type the whole name of the files.

For example, I have a file named "agendaDiagram.dart". I type "agd" and it finds "incremental_kernel_generator.dart"  It's even looking inside of the path, where it finds the letter "a". Whaat?

This makes absolutely no sense. It should only find stuff **in the order that you type**, never in any random order. And it must respect camel case. And it must NOT look the path of the file, only the file name itself. The old way was the correct one, exactly as IntelliJ does for Java. 

Is this a bug or a new "feature"? Please go back to the way it was, **it's making life hell**.

**Comment by alexander-doroshko** [comment]
@marcglasberg IDE version (Help -> About, press Ctrl+C / Cmd+C)?
Also, check scope (probably should be Project Files).
Or, could the project be misconfigured and the file you are looking for is not within the project roots?
![image](https://user-images.githubusercontent.com/4499789/71405497-ab327b80-2646-11ea-9452-dd5c880851a4.png)

**Comment by marcglasberg** [comment]
@alexander-doroshko  Yes, Project Files is the scope. These problems started after the last upgrade.

I should not have said it doesn't find the file. What I really meant is that the file I want is drowned in a lot of other less important files, since it now searches within the complete path of the file, and that's not what I want. I want just to search by the file name itself.

I'll give you a more precise example. I want to find a file called "reserva_de_mesa". So I type, like I always did, "redm". The first file it finds is "day_month_year_keyboard.png" because it's inside of a directory called "ref_images". It's finding "re" from "ref_images" and then "dm" from "day_month". It's finding 5 more files with crazy combinations of letters from the path and from the filename. And the file I want is the sixth (in this case). 

Please note, the file paths are sometimes too long and varied. It's very easy for a computer to find a lot of matches in these letter rich paths... But as a human I don't know the paths, I just barely remember the file names. I'm not forcing myself to type the whole filenames, instead of relying in camel-case search, which always worked well in the past.

In the Settings, is there a way to turn off searching the whole file path? If not, please fix this, is hurting my whole team's productivity. Thanks.

-------------------------------------------
IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Subscription is active until March 24, 2020
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1813M
Cores: 12
Registry: debugger.click.disable.breakpoints=true, ide.editor.tabs.open.at.the.end=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, io.flutter, com.chrisrm.idea.MaterialThemeUI

**Comment by alexander-doroshko** [comment]
Thanks for the update! 
This is tracked as https://youtrack.jetbrains.com/issue/IDEA-229305 and will be fixed ASAP.

**Comment by pq** [comment]
Thanks for the quick follow-up @alexander-doroshko !
