### ISSUE TITLE
remove uses of Project.getBaseDir() and Project.getBasePath()

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#424]
There are 3 usages of `Project.getBaseDir()` and 2 more usages of `Project.getBasePath()` methods in the flutter-intellij plugin source code.

JetBrains has discussed removing these methods as nobody reads javadoc and those who read still hope that these methods would work for them. The problem is that in most cases these methods do what you expect, but it should be treated just as a coincidence. Good plugin should not rely on some specific project structure.

Long story short:
- There's no such thing as 'Project root' in IntelliJ world.
- You never need Project.getBaseDir() and Project.getBasePath(), they do not do what you expect, see javadoc
- In most cases what you may need instead is:
  - Flutter project root. Effectively it is a parent folder of the flutter.yaml file
  - Module content root. Note that module may contain 0, 1, 2 or more content roots.

Make sure that you do manual or automated testing with more complex scenarios than single-module project with one content root in a module that is at the same time a Flutter project root and at the same time it is a parent of .idea folder. Always keep in mind the most complicated scenarios:
- There may be 0, 1, 2 and more modules in the project
- There may be 0, 1, 2 and more content roots in each module
- There may be 0, 1, 2 or more Flutter project in each content root, at any level in the content root folder structure
- Location of .idea folder is not anyhow connected with the location of module content roots. `Project.getBaseDir()` may be on a different physical drive than the content roots and project files

**Comment by pq** [comment]
Grabbing this since I started looking at it last night. 👍
