### ISSUE TITLE
Show Context Actions not work when use sub plugins/packages

### ISSUE THREAD

**Issue by gsy13213009** [flutter/flutter-intellij#4241]
## Steps to Reproduce
- Thanks for your attention. I have a problem when use the keymap of `Other/Show Context Actions`
- In the past we are only have a flutter project. And can use the `Show Context Actions` to fix some problem such as `import some file` quickly. 
- But now we had separate all business and then every business is a package. Not only that, There have some plugins in our project. 
- Because of that, Now we can't use `Show Context Actions` to import quickly. It is really difficult when developing. 
- By the way, The `Main menu/Code/Completion/Basic` is also not work
- It is the `Main menu/Code/Completion/Basic`. It show `No suggestion` when I want auto complete

![image](https://user-images.githubusercontent.com/15923034/71405082-58b98500-266f-11ea-944a-545b50ef0ab0.png)

- It is the `Show Context Actions`. There are no `import` select item In the suggestion 

![image](https://user-images.githubusercontent.com/15923034/71405219-bea60c80-266f-11ea-945e-03a73da9994a.png)

## Version info
- It is the version

```
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.2
    • Dart plugin version 192.7761
```

- It is my flutter doctor

```
$ flutter_release doctor -v                   
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale en-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/siyi.guo/flutter_release/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/siyi.guo/Library/Android/sdk
    • Android NDK at /Users/siyi.guo/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/siyi.guo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.2
    • Dart plugin version 192.7761

[✓] Connected device (2 available)
    • Pixel XL • FA68S0309515 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome   • chrome       • web-javascript • Google Chrome 79.0.3945.79 


! Doctor found issues in 1 category.

```

**Comment by pq** [comment]
Could you share some details about your project structure?  Where are the sub-packages in relation to the project root directory?  Do the context actions show up for any Dart files in the project?  (At the top-level?)

**Comment by gsy13213009** [comment]
### Hello. Thanks your reply. Here is our project structure
```
└── project_demo
    ├── lib
    │   └── main.dart
    ├── module
    │   ├── module_one
    │   │   ├── lib
    │   │   └── pubspec.yaml
    │   └── module_two
    │       ├── lib
    │       └── pubspec.yaml
    ├── module_base
    │   ├── lib
    │   └── pubspec.yaml
    ├── plugins
    │   └── grab_logger
    │       ├── lib
    │       │   └── log_utils.dart
    │       └── pubspec.yaml
    └── pubspec.yaml
```
- And with this structure, We can't use any `context actions` of all plugin/package.

### The real phenomenon
- Oh. Now I know why it can't work. We dependent all `base plugin` in `module_base`. and all `module` depend `module_base`. So the `context actions` is work at `module_base` but not work at all `module`

### Expect
- Very thanks your attention. Could you please help us to optimize it? We are developing too difficultly. 
- Very very thanks~

**Comment by gsy13213009** [comment]
- Hi @liyuqian . Can you pay attention to this issue?
- If `A -> B -> C`. We can't use `context actions` of C in A. It difficult to work because that. 
- Thanks for your attention

**Comment by liyuqian** [comment]
@gsy13213009 : thank you for reporting the issue! It would tremendously help us identify and fix this issue if you can upload a sample setup to Github.

For example,
1. Create a directory `root/` with 3 Dart packages `root/A`, `root/B`, `root/C`.
2. Setup dependencies locally so it will reproduce your issue.
3. Upload `root` to Github.
4. Check that one can `git clone` your `root` directory, and reproduce your issue on a new environment.

**Comment by szyi-builton** [comment]
you can change "Dart : Quick assist powered by the Dart Analysis Server."
