### ISSUE TITLE
improve editing speed for internal users

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4248]
Related to https://github.com/flutter/flutter-intellij/issues/4142 and https://github.com/flutter/flutter-intellij/pull/4164, we need to fix a significant editing performance slowdown for internal users (involving annotations for test methods). We worked around the issue for external users, but need to come up with a solution for internal users.

cc @DaveShuckerow @jacob314

**Comment by devoncarew** [comment]
@jacob314, was this addressed by https://github.com/flutter/flutter-intellij/pull/4295, or was that orthogonal to the editing performance issue?

**Comment by jacob314** [comment]
Yes. Forgot to close this.
