### ISSUE TITLE
迅雷

### ISSUE THREAD

**Issue by john960** [flutter/flutter-intellij#4251]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment]
Closing as there doesn't seem to be an issue here, but please re-open with details if there is a problem.
