### ISSUE TITLE
resolve the race condition with enabling the flutter framework's structured errors

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4256]
There's a race condition at app startup (and after a hot restart) to enable the flutter framework's structured errors. If we will the race (which er do for most errors) then IDEs can display the errors in a easy to consume format. If we loose the race, then errors display as 800+ lines of text.

cc @jacob314 in case he has ideas about how best to solve this

**Comment by DanTup** [comment]
I think this was resolved by #4587? 

However - I noticed today in VS Code that we're now showing duplicate errors - one from the structured error event, and one from the standard output (stderr?) output too.

I tested in Android Studio and see the same:

<img width="1044" alt="Screenshot 2020-07-16 at 11 25 03" src="https://user-images.githubusercontent.com/1078012/87660489-0c42ad80-c757-11ea-8300-e337dd7f11a5.png">

Is there something the editors are supposed to be doing to suppress these, or is Flutter supposed to not send them when structured errors are enabled? (@helin24 @jacob314 ?)

**Comment by helin24** [comment]
I see this too... we want flutter to not send the stderr output, looking into this.

**Comment by helin24** [comment]
@DanTup the change I made for duplicate errors is part of [flutter 1.21.0-5.0.pre](https://github.com/flutter/flutter/releases/tag/1.21.0-5.0.pre)

I think we can close this issue since we've made the changes on the flutter side and in the IntelliJ plugin.

**Comment by DanTup** [comment]
@helin24 sgtm, thanks!
