### ISSUE TITLE
Quick fix to create an equals() method

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4264]
We should add a quick fix to create an equals method when hashCode is already overridden (a quick fix for hash_and_equals).

```
Override `==` if overriding `hashCode`. (hash_and_equals at [nnbd] lib/model.dart:25)
```

**Comment by devoncarew** [comment]
Re-opening so we can track in this milestone.

**Comment by pq** [comment]
Fixed w/ https://github.com/dart-lang/sdk/commit/9e9c14cae3871de3d41285080c6149f1cb835d8d.
