### ISSUE TITLE
Flutter is displaying No device connected in my android studio. My android projects is debugging successfully on device.

### ISSUE THREAD

**Issue by abubakarDeveloper** [flutter/flutter-intellij#4265]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by jacob314** [comment]
Are you able to reliably reproduce the issue?
Can you paste in the output of running
`flutter doctor -v`

**Comment by abubakarDeveloper** [comment]
yes

**Comment by abubakarDeveloper** [comment]
it is displaying me two issues
[image: dev.PNG]

**Comment by jacob314** [comment]
I looks like something went wrong pasting dev.PNG. Can you try to include the image again?
Thanks,
Jacob
