### ISSUE TITLE
Only display Flutter UI elements on projects that have a Flutter module

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#4269]
This was initially reported as #267 and it mostly works. But my Flutter dev project has the Flutter device selector showing for some reason. The project that is open is intellij.idea.community.main and does not have any Flutter modules, but it does have Java modules named 'flutter-intellij-community' and 'flutter-studio'.

Also, 'Flutter Inspector', 'Flutter Outline', and 'Flutter Performance' should not be visible on non-Flutter projects. They do show up on Android projects and Java projects today.

**Comment by devoncarew** [comment]
@stevemessick, https://github.com/flutter/flutter-intellij/pull/4281 address part of this issue.

Can you add a bit more details about why the device selector shows up in some non-Flutter projects? From reading the code, that should only happen if the `flutter deamon` process has been started for that project. This may be a degenerate case? `flutter-intellij-community` is likely a valid Dart project, and the Dart SDK you used for it might be the dart vended into the flutter sdk.

**Comment by stevemessick** [comment]
I think you are right, it only shows up in that one project. Not worth the trouble to track down why.

**Comment by devoncarew** [comment]
See the closed, partial PR for this: https://github.com/flutter/flutter-intellij/pull/4281.
