### ISSUE TITLE
Need a menu item to open dev tools

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#4270]
Add `Tools > Flutter > Open Dart DevTools` to the main menu bar.

It should always be visible but only enabled if a Flutter app is running.

**Comment by devoncarew** [comment]
> It should always be visible but only enabled if a Flutter app is running.

I didn't mention on the PR, but when implementing this I chose to have the menu always be enabled. It's a good entry point to devtools even if an app isn't running - I think it'll help overall discoverability of how to launch devtools.
