### ISSUE TITLE
Replace DeviceSelector with DeviceAndSnapshotComboBoxAction in Android Studio

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#4272]
See `DeviceAndSnapshotComboBoxAction.DEPLOYS_TO_LOCAL_DEVICE` in AS sources, which has this comment:
```java
  /**
   * Run configurations that aren't {@link AndroidRunConfiguration} or {@link AndroidTestRunConfiguration} can use this key
   * to express their applicability for DeviceAndSnapshotComboBoxAction by setting it to true in their user data.
   */
```
ASWB does `configuration.putUserData(DEPLOYS_TO_LOCAL_DEVICE, true);` to use the Android Studio device selector. I think we could do the same, but we'd have to hide our DeviceSelector when running in Android Studio (but not IntelliJ). It might need reflection-based access to make it work, or some extra-clever code in the flutter-studio module.

Supersedes #3148

**Comment by devoncarew** [comment]
We do also need to support showing non-android devices in the device selector; iOS devices, flutter web, flutter desktop, ...

**Comment by stevemessick** [comment]
Good point. DeviceAndSnapshotComboBoxAction is no longer final, though, so we might be able to use a subclass. Anyway, something to consider when we're thinking about how to clean up the tool bar.

**Comment by stevemessick** [comment]
DeviceAndSnapshotComboBoxAction is final again.
