### ISSUE TITLE
Ability to switch between multiple Flutter SDK with different version

### ISSUE THREAD

**Issue by greymag** [flutter/flutter-intellij#4286]
Hello. Thanks for the great plugin! It would be nice if we also have ability to use multiple Flutter SDK and configure SDK for project, not the whole IDE.

That the case: I have old project with previous Flutter version (can't be upgraded) and the new one - with the latest version. During development I need to switches between two project, but they have different version of Flutter, so I need to change SDK path (or call `flutter version {version}` manually every time.

**Comment by alexander-doroshko** [comment]
AFAIK nothing prevents you from having two separate installations of Flutter SDK on your computer. 
In the IDE Flutter SDK is configured per-project, so you'll simply set different SDK paths in different projects.

**Comment by greymag** [comment]
Oh, my mistake! I thought that common setting, not for project. Thanks a lot!
