### ISSUE TITLE
VS code no device

### ISSUE THREAD

**Issue by balajis-13395** [flutter/flutter-intellij#4287]
Hi,
I had installed flutter latest SDK and I setup VS code with flutter extension as my IDE.

The problem I am facing is whenever I tried to launch the flutter app from vs code. it shows 'no device available' message.

I had executed 'flutter doctor' and 'flutter device' commands .Everything was fine.

I was able to see the connected devices in 'Android Studio' . But my VS code is not recognizing the connected .

Please help me to resolve this issue .Thanks in advance

**Comment by stevemessick** [comment]
Dup of https://github.com/Dart-Code/Dart-Code/issues/2222
