### ISSUE TITLE
UI Guides' lines not auto-updating

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#4297]
Sometimes I start composing my widgets and the UI Guides' lines don't update and I get some weird behavior like this:

![image](https://user-images.githubusercontent.com/8120472/72575193-5df2a400-38aa-11ea-9400-79b33a9d16ad.png)

I have to go to the specific line, hit `Enter` then `Backspace` again in order to get it right:

![image](https://user-images.githubusercontent.com/8120472/72575237-7bc00900-38aa-11ea-9cc4-e1f162228ee6.png)

**Comment by devoncarew** [comment]
cc @jacob314; possibly race conditions wrt when we process analysis server outline events?

@feinstein, can you check out IntelliJ logs for any suspect exceptions when this occurs? This would be exceptions near the end of the log that contain class from `io.flutter.` on the stack trace.

**Comment by feinstein** [comment]
Ok, next time it happens I will take a look.

**Comment by jacob314** [comment]
Thanks for the repro. The fact that you have to hit enter and backspace suggests this is a bug in how we are computing equality of existing ui guide markers.

**Comment by feinstein** [comment]
Another clue into the puzzle: This happens when I highlight the whole widget and do a `Ctrl+Alt+L` (auto indent).
