### ISSUE TITLE
Can no longer run "All in file"

### ISSUE THREAD

**Issue by ejain** [flutter/flutter-intellij#4298]
## Steps to Reproduce

When I try to create a "Flutter Test" run configuration, and choose either _All in file_ (or _Tests in file, filtered by name_), the following error is shown: "Test file isn't within a flutter pub root". Meanwhile, no issues with _All in directory_.

![run](https://user-images.githubusercontent.com/1323903/72576017-45bb5e80-3883-11ea-8a02-1c8832c88fdf.png)

This problem appeared in a project that used to work, and without doing any updates.

## Version info
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\Users\Eric\AppData\Roaming\Flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Eric\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Users\Eric\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\Eric\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Users\Eric\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.6015.22
    • Flutter plugin version 42.0.4
    • Dart plugin version 193.5731

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Nexus 5X                  • 024c2ee09981cdc4 • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by stevemessick** [comment]
Try running the menu item `Tools > Flutter > Flutter Packages Upgrade`. Let us know if that helps.

**Comment by ejain** [comment]
Just did a _Flutter Packages Upgrade_, doesn't look like that helps.

**Comment by stevemessick** [comment]
Thanks. Does the path to your test file contain any symbolic links?

**Comment by ejain** [comment]
> Does the path to your test file contain any symbolic links?

There are no symbolic links in the path.

Thanks for fixing the title 🤦

**Comment by stevemessick** [comment]
I'm running out of ideas :( The code looks like everything should work if your pubspec.yaml and .packages are valid, and that's what we checked with `flutter packages upgrade`. We've had weird problems with symlinks in the past, but that's not the issue here. I can't reproduce it on my Mac, but that doesn't mean everything works as expected on Windows. We'll have to try it with Windows, but that's going to be a few days at least.

If you feel like experimenting, and really want to fix this, there is one more thing to try. That is: recreate your Flutter project by creating a new project and copying all the files you created or edited to it. And do `flutter pub get`.

**Comment by ejain** [comment]
Created a new project, copied over all the files (incl `.idea`), and strangely enough everything works now.

**Comment by stevemessick** [comment]
Thanks for the update!
