### ISSUE TITLE
File Sync on Debug is taking too long

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#4307]
I don't know what has happened, I don't remember updating anything. When I click to "Debug" on Android, the APK is compiled and installed successfully, then my console says: `Syncing files to device Android...` and it takes a long time to sync, but if I decide to not wait for it and just hit `Ctrl+S` and trigger a Hot Reload, the sync is immediate and works just fine.

**Comment by devoncarew** [comment]
I wonder if the initial sync isn't completing, or if it's completing and just not indicating that correctly?

Can you include your flutter sdk version? Does this issue consistently reproduce?

Some verbose logs would be great. In the Flutter IntelliJ settings, there's an `enable verbose logs` setting. If you check that and re-run your app, you should get a sense as to what command things are hanging at. Attaching those logs here you be useful.

cc @jonahwilliams

**Comment by feinstein** [comment]
> if it's completing and just not indicating that correctly?

It's not completing because my screen goes blank and just shows my widgets once its synched.

> Can you include your flutter sdk version? Does this issue consistently reproduce?

Yep, it happens all the time, both on my AVD and my phone. 

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (6 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

> Some verbose logs would be great. 

I took a look at the verbose logs and those are the entries that take longer to execute:

[+1009 ms] AOSP on IA Emulator startApp
[+1061 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.myapp.myapp/.MainActivity (has extras) }
[+4154 ms] Observatory URL on device: http://127.0.0.1:35454/maiH_a7thkQ=/
[+9065 ms] Updating files
[+3792 ms] Sending to VM service: ext.flutter.platformOverride({isolateId: isolates/1804630581053347})


The clear ones for me were: `[+9065 ms] Updating files` and `[+3792 ms] Sending to VM service: ext.flutter.platformOverride({isolateId: isolates/1804630581053347})`.

**Comment by feinstein** [comment]
Ok, I am almost sure it's hanging on the splash-screen because of a Firebase Auth Stream issue, which happens on the first Debug compilation after a new login.

This is unrelated with the timings I sent before, if they are normal, then I will close this issue. Thanks guys.

**Comment by devoncarew** [comment]
@feinstein - is there still an issue here?

(and, from memory, I believe that the times reported for a log entry line actually apply to the preceding line; we emit the current text, as well as the time from when we wrote the preceding text to now)

**Comment by feinstein** [comment]
No more issues, I found a bug and reported it on the main repo, but those timings still persists. So I will close it for now and if someone wants to investigate this further, feel free to reopen it.
