### ISSUE TITLE
Surface VM connection status in the IDE to prevent reload failure

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#4309]
In the Q4 2019 user survey, some users reported unexpected hot reload behavior likely due to loss of connection between the IDE and the app:

- “I exited the app and opened it again”
- “putting my machine to sleep and coming back to an open emulator later on”

The IDE can probably display the status of the connection and warn the user when they try to reload a disconnected app. There is an [old issue](https://github.com/flutter/website/issues/2056) requesting documentation, but I think just mentioning this limitation in docs won't be sufficient.

**Comment by devoncarew** [comment]
If there's no vm connection, we should show the process as terminated; the reload button should become disabled, the run button should lose it's 'active' badge, and the run tool window should also change to a terminated state.

Perhaps this was a specific bug, or, related to a specific run target?

**Comment by InMatrix** [comment]
I tried to reproduce this issue. As @devoncarew mentioned, the IDE does change the status of the hot reload button when the app is disconnected. The console also prints out this message "Lost connection to device." I guess the two users reported the issue were used to reload on save and didn't notice the change of connection status. The only thing I'd suggest is to make the lost connection message a bit more prominent, e.g., displaying it in red.
