### ISSUE TITLE
Breakpoint is ignored after code is edited (no reload).

### ISSUE THREAD

**Issue by turnidge** [flutter/flutter-intellij#433]
Steps to reproduce:

1. Create a new flutter application with the demo app.
2. Set a breakpoint on the line with "_counter++;"

![screen shot 2016-11-10 at 1 35 50 pm](https://cloud.githubusercontent.com/assets/4804200/20195595/12189244-a74c-11e6-86c7-1fd5d65850ad.png)

3. Debug "main.dart.
4. Add 6 lines of comments above the breakpoint.  Do not save or reload.

![screen shot 2016-11-10 at 1 47 35 pm](https://cloud.githubusercontent.com/assets/4804200/20195649/44180a04-a74c-11e6-9f8d-38a8875800aa.png)

5. Click the (+) button in the demo app.

![screen shot 2016-11-10 at 1 48 10 pm](https://cloud.githubusercontent.com/assets/4804200/20195670/5553814a-a74c-11e6-9a06-3284b649aa14.png)

EXPECTED: Program stops at breakpoint in the original, unedited source code.  This source code is known to the vm and is available through the vm service.
ACTUAL: Breakpoint is apparently ignored.

cc'ing @johnmccutchan

**Comment by johnmccutchan** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
@pq is this the same as https://github.com/flutter/flutter-intellij/issues/305 even though there is no reload in this case?

**Comment by johnmccutchan** [comment]
@mit-mit This is a different issue. It appears that as the programmer modifies their source code the plugin is telling the VM to move breakpoints. This confuses the VM because it is running the *unmodified* source code. The plugin must always update source code + breakpoints atomically.

**Comment by mit-mit** [comment]
>  It appears that as the programmer modifies their source code the plugin is telling the VM to move breakpoints. This confuses the VM because it is running the unmodified source code. The plugin must always update source code + breakpoints atomically.

I agree this is unexpected. The plugin should not push breakpoint updates until the developer pushes code changes to target (i.e., when the developer hits reload or restart) -- I believe this is #305.

> EXPECTED: Program stops at breakpoint in the original, unedited source code. This source code is known to the vm and is available through the vm service.

I am not convinced this is expected. I think it would be perfectly find to have the program stop at `counter++` still showing the comment lines that were added above.

**Comment by pq** [comment]
@skybrian : while you're looking at debugging in general, could you take a poke at this updating the status of this one?

**Comment by skybrian** [comment]
This is looking tricky. IDEA doesn't do this for other languages and the debugger code isn't entirely under our control - it's split between the Flutter plugin, Dart plugin, and the IDEA framework. So we're probably going to put this off.

Instead, I think we should show some kind of warning when the code is out of date, maybe with a button for the user to hot reload. (Not sure about the UI, though.)

**Comment by johnmccutchan** [comment]
@skybrian Can you please document your findings and recommendation and then we can discuss it at tomorrow's devtools meeting?

**Comment by skybrian** [comment]
Sure. I don't see this meeting on my calendar. Could you send me an invite?

**Comment by johnmccutchan** [comment]
@skybrian You've been invited.

**Comment by skybrian** [comment]
I don't believe anything has changed. As I'll be on leave, unassigning for triage.

**Comment by stevemessick** [comment]
Closing this since it now works as it should: stops at the breakpoint in the edited code.
