### ISSUE TITLE
Incompatible with IntelliJ 2020.x

### ISSUE THREAD

**Issue by pavanpodila** [flutter/flutter-intellij#4333]
Plugin is not compatible with the IntelliJ 2020.x versions.

**Comment by devoncarew** [comment]
Thanks for the report!

**Comment by pavanpodila** [comment]
Awesome!...when will it be available? Thanks for the speedy turnaround.

**Comment by devoncarew** [comment]
We do ~ calendar monthly releases and track their progress via github milestones. We expect the next one (https://github.com/flutter/flutter-intellij/milestone/54) out around the end of next week.
