### ISSUE TITLE
Support idea 2020.1

### ISSUE THREAD

**Issue by leaxoy** [flutter/flutter-intellij#4341]
IDEA 2020.1 has been in eap channel, it's awesome if this plugin support it.

**Comment by pq** [comment]
@stevemessick:  is this as easy as updating our product matrix?

**Comment by devoncarew** [comment]
On mobile now, but our upcoming release will support EAP.

**Comment by pq** [comment]
Ah, yes.  I should have looked.  Should be addressed w/ https://github.com/flutter/flutter-intellij/pull/4335 and available w/ the next release.  Thanks!
