### ISSUE TITLE
App not terminated when project is closed

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#4349]
Closing a project while a Flutter app is running does not work as expected.

- Start debugging a Flutter app
- Close the project
- Choose to terminate the process when prompted
- Project closes but app continues running

If stopped at a breakpoint, it is even worse. A big, empty window is re-opened after the project is closed. It can be closed to restore sanity. This reminds me of the problem fixed in https://github.com/flutter/flutter-intellij/pull/4271.

If the app is launched via `Run` (not `Debug`) then it works as expected; the app is terminated.

@devoncarew for guidance on whether we need to fix this in M43.

**Comment by stevemessick** [comment]
Forgot to mention I was using the iOS simulator. It works the same in IntelliJ and Android Studio.

**Comment by terrylucas** [comment]
Does it work correctly with the Android emulator?  This fix should be in the 44 milestone.
