### ISSUE TITLE
print() output displays in console twice when debugging

### ISSUE THREAD

**Issue by turnidge** [flutter/flutter-intellij#435]
Steps to reproduce:

1. Edit the starter app so that it prints something when the counter is incremented:

![screen shot 2016-11-10 at 2 49 27 pm](https://cloud.githubusercontent.com/assets/4804200/20197527/e5ea22ec-a754-11e6-99db-c388e0477ee5.png)

2. *debug* ![screen shot 2016-11-10 at 1 53 19 pm](https://cloud.githubusercontent.com/assets/4804200/20197561/0824281c-a755-11e6-8d86-7acd9f3eb07c.png) the program.

3. Click on the (+) button in the starter app.

EXPECTED: "incrementing counter" appears once.
ACTUAL: "incrementing counter" appears twice.

![screen shot 2016-11-10 at 2 51 27 pm](https://cloud.githubusercontent.com/assets/4804200/20197586/3046cac0-a755-11e6-90a6-a55cf3f8a7bf.png)

Note that this bug *does not* occur when running the release version of the app.

**Comment by devoncarew** [comment]
Thanks for the report! This has been fixed in master - we should have a new release out early next week (~Tuesday). /cc @pq
