### ISSUE TITLE
[AndroidStudio wizard] Changing a "Package name" field works with bug

### ISSUE THREAD

**Issue by nailgilaziev** [flutter/flutter-intellij#4352]
Editing the "Package name" field working with bug. Generated gradle file and xcode project contains applicationID/BundleId with original project name mixed with changed company domain. Next screenshots describing the way to represent error:

## Steps to Reproduce
Open wizard
![](https://user-images.githubusercontent.com/2749021/71534624-22029980-2911-11ea-8a92-d891639ae0c6.png)

Fill the fields -> Press Next

![](https://user-images.githubusercontent.com/2749021/71534632-2d55c500-2911-11ea-96a3-1848f44abad6.png)
Here you see - Default values (ru.gs.flutter_app2)

![](https://user-images.githubusercontent.com/2749021/71534640-36df2d00-2911-11ea-97f5-52ddf193febf.png)
Press Edit button, change Package name and press Done Button and then Finish button
[ru.gs.flutter_app2 changed to ru.gs2.app2]

![](https://user-images.githubusercontent.com/2749021/71534687-79a10500-2911-11ea-99f5-283461cbc15c.png)
Open xcode workspace and see the bug - BundleID not changed
[Let's be specific: the first part (company domain) is changed, the last is not]

![](https://user-images.githubusercontent.com/2749021/71534732-d3093400-2911-11ea-954d-879b723e43cc.png)
Open app gradle file - ApplicationId not changed(same in manifest.xml)
[Let's be specific: the first part (company domain) is changed, the last is not]

![](https://user-images.githubusercontent.com/2749021/71534769-22e7fb00-2912-11ea-96b8-aea8a64b9718.png)

## Version info

[✓] Flutter (Channel dev, v1.14.6, on Mac OS X 10.15.2 19C57, locale en-RU)
    • Flutter version 1.14.6 at /Users/n/Tools/flutter
    • Framework revision fabeb2a16f (5 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/n/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by kenzieschmoll** [comment]
cc @stevemessick
