### ISSUE TITLE
Structure error missing parts when displayed in IntelliJ

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#4363]
The error message in IntelliJ miss many parts such as hints and description:

![image](https://user-images.githubusercontent.com/348942/74075801-3b473d00-49c9-11ea-9d2e-39f997912be2.png)

This is the same message displayed by VS Code: 

![image](https://user-images.githubusercontent.com/348942/74075785-2ff41180-49c9-11ea-8608-e15343bb6569.png)

Did the logic for showing the structure error message in IntelliJ change recently?

## Steps to Reproduce

Run the example at https://github.com/InMatrix/flutter_error_studies/blob/master/lib/renderflex_overflow_error.dart

## Version info

[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.7 at /Users/xxx/Development/flutter/flutter
    • Framework revision 9f5ff2306b (12 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one
        being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • EF7A6DBC-8ED4-4217-AB38-01F805FD487D • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

**Comment by terrylucas** [comment]
@devoncarew @stevemessick 
Should this be on our list of fixes for next milestone or on deck?

**Comment by devoncarew** [comment]
> Did the logic for showing the structure error message in IntelliJ change recently?

It hasn't, but we should figure out why we're showing something different from VS Code here.

**Comment by devoncarew** [comment]
@InMatrix - for the screenshot from IntelliJ, it's showing the 7th caught instance of that error?  VS Code may be showing the 1st caught instance of it?

**Comment by InMatrix** [comment]
I took a closer look at it. IntelliJ seems to produce the right error display when I go straight to the RenderFlex Overflow error in the linked demo app. However, when I go to the RenderFlex Overflow error after triggering the Missing Material error, I got the shortened version of the error in the screenshot above. It seems that something in the Missing Material error changed the  error display configuration.

**Comment by devoncarew** [comment]
I think you're correct, and is likely something we're doing deliberately (but would have to check the code). If so, we can change the rendering to not use the shorter format for subsequent errors.

**Comment by InMatrix** [comment]
I see. I think this shorter format is useful when the subsequent errors are second-order effects of the first error. However, in this case, the second error is independent from the first one. I wonder if there is a way we can distinguish these two different kinds of errors.

**Comment by devoncarew** [comment]
Looking at this now, we might be able to use information like frame start events to reset whether we're summarizing errors.

I'm not able to repro this case in the flutter_error_studies app - when I visit the Missing Material page, I get in a state where I can't navigate back to the main set of pages. What's the best way to repro this?

**Comment by InMatrix** [comment]
Once you get into the Missing Material page, you can actually grab the left border the page and drag it to the right to get back to the list of errors. Let me know if it works for you.
