### ISSUE TITLE
Running Gradle task 'assembleDebug'... forever linux

### ISSUE THREAD

**Issue by matheust3** [flutter/flutter-intellij#4366]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

 flutter build apk -v          
                               
[  +58 ms] executing: [/home/matheus/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5f4658973be1ad10a59a0a278b6cdf41b10fe7f6
[        ] executing: [/home/matheus/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +23 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.15.2-45-g5f4658973
[  +13 ms] executing: [/home/matheus/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/matheus/development/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +86 ms] executing: [/home/matheus/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +65 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +21 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +318 ms] Found plugin flutter_facebook_login at /home/matheus/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
[  +36 ms] Found plugin flutter_statusbarcolor at /home/matheus/.pub-cache/hosted/pub.dartlang.org/flutter_statusbarcolor-0.2.3/
[  +19 ms] Found plugin geolocator at /home/matheus/.pub-cache/hosted/pub.dartlang.org/geolocator-5.2.1/
[   +7 ms] Found plugin google_api_availability at /home/matheus/.pub-cache/hosted/pub.dartlang.org/google_api_availability-2.0.2/
[   +3 ms] Found plugin google_sign_in at /home/matheus/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.1.1/
[  +16 ms] Found plugin google_sign_in_web at /home/matheus/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/
[  +30 ms] Found plugin location_permissions at /home/matheus/.pub-cache/hosted/pub.dartlang.org/location_permissions-2.0.4+1/
[  +25 ms] Found plugin path_provider at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.0/
[  +30 ms] Found plugin sqflite at /home/matheus/.pub-cache/hosted/pub.dartlang.org/sqflite-1.2.0/
[ +272 ms] Found plugin flutter_facebook_login at /home/matheus/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
[   +2 ms] Found plugin flutter_statusbarcolor at /home/matheus/.pub-cache/hosted/pub.dartlang.org/flutter_statusbarcolor-0.2.3/
[  +15 ms] Found plugin geolocator at /home/matheus/.pub-cache/hosted/pub.dartlang.org/geolocator-5.2.1/
[   +2 ms] Found plugin google_api_availability at /home/matheus/.pub-cache/hosted/pub.dartlang.org/google_api_availability-2.0.2/
[   +1 ms] Found plugin google_sign_in at /home/matheus/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.1.1/
[   +2 ms] Found plugin google_sign_in_web at /home/matheus/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/
[  +14 ms] Found plugin location_permissions at /home/matheus/.pub-cache/hosted/pub.dartlang.org/location_permissions-2.0.4+1/
[   +9 ms] Found plugin path_provider at /home/matheus/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.0/
[  +12 ms] Found plugin sqflite at /home/matheus/.pub-cache/hosted/pub.dartlang.org/sqflite-1.2.0/
[ +139 ms] Generating /mnt/d/Dev/Flutter/super_app_foods/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +78 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[        ] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK
size.
[   +2 ms]     To generate an app bundle, run:
[        ]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[        ]         Learn more on: https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[        ]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[        ]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +38 ms] Running Gradle task 'assembleRelease'...
[   +6 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /mnt/d/Dev/Flutter/super_app_foods/android/gradlew.
[   +1 ms] /mnt/d/Dev/Flutter/super_app_foods/android/gradlew mode: 33261 rwxr-xr-x.
[  +27 ms] executing: /opt/android-studio/jre/bin/java -version
[ +251 ms] Exit code 0 from: /opt/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[  +10 ms] executing: [/mnt/d/Dev/Flutter/super_app_foods/android/] /mnt/d/Dev/Flutter/super_app_foods/android/gradlew -Pverbose=true
-Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true -Ptarget-platform=android-arm,android-arm64,android-x64
assembleRelease

## >>

flutter build apk -v
[  +30 ms] executing: [/home/matheus/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +35 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [/home/matheus/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +5 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.7-0-g9f5ff2306
[  +10 ms] executing: [/home/matheus/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/matheus/development/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +55 ms] executing: [/home/matheus/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +41 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +233 ms] Found plugin flutter_keyboard_visibility at
/home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[  +29 ms] Found plugin flutter_statusbarcolor at
/home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_statusbarcolor-0.2.3/
[  +14 ms] Found plugin geolocator at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-5.2.0/
[   +5 ms] Found plugin google_api_availability at
/home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-2.0.2/
[  +22 ms] Found plugin image_cropper at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.1.2/
[   +3 ms] Found plugin image_picker at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.2+3/
[   +9 ms] Found plugin location_permissions at
/home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/location_permissions-2.0.4+1/
[  +20 ms] Found plugin path_provider at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/
[  +24 ms] Found plugin sqflite at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.2.0/
[ +217 ms] Found plugin flutter_keyboard_visibility at
/home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[   +1 ms] Found plugin flutter_statusbarcolor at
/home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_statusbarcolor-0.2.3/
[   +3 ms] Found plugin geolocator at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-5.2.0/
[   +1 ms] Found plugin google_api_availability at
/home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-2.0.2/
[   +6 ms] Found plugin image_cropper at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.1.2/
[        ] Found plugin image_picker at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.2+3/
[   +2 ms] Found plugin location_permissions at
/home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/location_permissions-2.0.4+1/
[  +10 ms] Found plugin path_provider at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/
[  +14 ms] Found plugin sqflite at /home/matheus/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.2.0/
[  +89 ms] Generating /mnt/d/Dev/Flutter/DeliveryParceiro/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +51 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[        ] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK
size.
[        ]     To generate an app bundle, run:
[        ]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[        ]         Learn more on: https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[        ]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[        ]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +32 ms] Running Gradle task 'assembleRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /mnt/d/Dev/Flutter/DeliveryParceiro/android/gradlew.
[  +17 ms] executing: /home/matheus/development/android-studio/jre/bin/java -version
[ +167 ms] Exit code 0 from: /home/matheus/development/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +6 ms] executing: [/mnt/d/Dev/Flutter/DeliveryParceiro/android/] /mnt/d/Dev/Flutter/DeliveryParceiro/android/gradlew
-Pverbose=true -Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true
-Ptarget-platform=android-arm,android-arm64,android-x64 assembleRelease
[+4068 ms] Starting a Gradle Daemon, 2 busy and 1 incompatible and 2 stopped Daemons could not be reused, use --status for details
[+17785 ms] > Task :app:compileFlutterBuildRelease
[        ] [  +33 ms] executing: [/home/matheus/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +38 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] [   +1 ms] executing: [/home/matheus/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +7 ms] [   +6 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.7-0-g9f5ff2306
[        ] [  +11 ms] executing: [/home/matheus/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/matheus/development/flutter/] git ls-remote --get-url origin
[        ] [   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +54 ms] executing: [/home/matheus/development/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +24 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +165 ms] Initializing file store
[        ] [   +4 ms] Done initializing file store
[ +883 ms] [+1967 ms] kernel_snapshot: Starting due to {InvalidatedReason.inputChanged}
[        ] [  +16 ms] /home/matheus/development/flutter/bin/cache/dart-sdk/bin/dart
/home/matheus/development/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/matheus/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter
-Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=true --bytecode-options=source-positions --aot
--tfa --packages /mnt/d/Dev/Flutter/DeliveryParceiro/.packages --output-dill
/mnt/d/Dev/Flutter/DeliveryParceiro/.dart_tool/flutter_build/7396d9944a66153207e8f6126956129e/app.dill --depfile
/mnt/d/Dev/Flutter/DeliveryParceiro/.dart_tool/flutter_build/7396d9944a66153207e8f6126956129e/kernel_snapshot.d
package:rango_parceiro/main.dart

## Version info

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.3-pre.45, on Linux, locale pt_BR.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

**Comment by matheust3** [comment]
It returned to work after changing the linux kernel. It seems that after the update linux-zen did not work well with the flutter. The build froze after a while. The solution was to switch to linux-lts.

**Comment by kenzieschmoll** [comment]
@matheust3 Are you still having an issue or is this resolved?

@stevemessick FYI

**Comment by matheust3** [comment]
@kenzieschmoll  It's solved for me. But I don't know if the problem I had is related to the kernel or the flutter

**Comment by matheust3** [comment]
Closing
