### ISSUE TITLE
Need to enable dart support everytime

### ISSUE THREAD

**Issue by 3dvirtuallabs** [flutter/flutter-intellij#4371]
## Steps to Reproduce

Whenever I restart IDE I need to enable dart support over and over. A screenshot is attached for reference.
![image](https://user-images.githubusercontent.com/2582649/74215027-b3617b80-4cc5-11ea-8559-b810a0b1810b.png)
 

## Version info

![image](https://user-images.githubusercontent.com/2582649/74215058-cd02c300-4cc5-11ea-83e5-9544505dd3aa.png)

![image](https://user-images.githubusercontent.com/2582649/74215084-e0159300-4cc5-11ea-880b-4264d8e44f0b.png)

Please help.

**Comment by kenzieschmoll** [comment]
When you restart the IDE, are you also invalidating caches?
<img width="612" alt="Screen Shot 2020-02-11 at 8 53 40 AM" src="https://user-images.githubusercontent.com/43759233/74259000-0a5a5700-4cac-11ea-80a8-86944a93431e.png">

**Comment by 3dvirtuallabs** [comment]
No, I'm not invalidating caches.

**Comment by kenzieschmoll** [comment]
@stevemessick any ideas why dart support settings wouldn't be persisting?

**Comment by stevemessick** [comment]
Gradle sync will disable Dart support. There's some discussion here: 
- https://youtrack.jetbrains.com/issue/WEB-40082
- https://youtrack.jetbrains.com/issue/WEB-23541

In the (currently beta) Android Studio 3.6 the Flutter plugin detects this problem and fixes it. If you can give the beta version a try we'd like to know if that fixes your problem.

**Comment by 3dvirtuallabs** [comment]
Let me try that and will get back if that worked or not.

**Comment by stevemessick** [comment]
@3dvirtuallabs ping :)

**Comment by 3dvirtuallabs** [comment]
Really sorry I was away from work but I'm still facing the same issue on
ever restart.

**Comment by stevemessick** [comment]
If you're installed any plugins other than Dart and Flutter try disabling them to see if that fixes the problem.

Is Gradle sync running in your Android Studio? Use `Help > Show Log in Finder` to locate the log files. Search in those files for `GradleSyncState`.

Of course, this may have nothing to do with Gradle. If that's the case you could try resetting the IDE metadata. Make a copy of your .idea directory, then quit Android Studio. Delete the .idea directory from your Flutter project and restart Android Studio.

Also, make sure you are using Android Studio 3.5.3 with Flutter plugin version 44.

**Comment by 3dvirtuallabs** [comment]
It's not in android studio it's happening in intellij ide ultimate edition।

**Comment by stevemessick** [comment]
It is odd that `flutter doctor -v` did not report IntelliJ.

My suggestions still apply. Just substitute "IntelliJ" for "Android Studio". Have you enabled the experimental setting that provides editing support like code completion and syntax highlighting for Java? (It is at the bottom of the Flutter settings page.)

**Comment by pablichoka** [comment]
I have solved my issue just clicking on Repair IDE option of IntelliJ and reaching step 3, which basically closes and reopen the project (not the IDE)
