### ISSUE TITLE
2 APIs we're using may be removed in 2020.3

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4387]
From the plugin publishing validations:

<img width="1188" alt="Screen Shot 2020-02-18 at 3 36 32 PM" src="https://user-images.githubusercontent.com/1269969/74787642-859baa00-5264-11ea-979c-ede9c2adb0e5.png">

Two of the referenced classes (`com.intellij.util.containers.hash.HashMap` and `com.intellij.util.containers.hash.HashSet`) may be removed in 2020.1

cc @stevemessick, as it looks like they're referenced from the android studio support code.

**Comment by stevemessick** [comment]
Partially fixed in #4390. The change to #doOpenProject needs more investigation.

**Comment by devoncarew** [comment]
Steve, do we think this is still an issue for 2020.1?

**Comment by stevemessick** [comment]
No, we're good for 2020.1. The remaining change is due to disappear in 2021.3.

**Comment by hacker1024** [comment]
2020.3 has just hit EAP.

**Comment by devoncarew** [comment]
It looks like our current product matrix does not yet support 2019.3 EAP (https://github.com/flutter/flutter-intellij/blob/master/product-matrix.json).

@helin24, @stevemessick - can you of you look at adding it to our matrix, to see if we do have issues w/ the next version? Thanks!

**Comment by stevemessick** [comment]
I added 2020.3 EAP. The deprecated API only affects Android Studio. I expect the new project wizard re-write will solve that problem long before Android Studio is based on 2020.3.
