### ISSUE TITLE
Create run configurations during project creation

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#44]

**Comment by mit-mit** [comment]
I'd really like to see this; it was confusing having to create this manually.

**Comment by pq** [comment]
Questions on a few defaults:

* Config name. (Same as project?)
* Dart file?  (`lib/main.dart` if found, or?)
* Working dir?  (Project root?)

**Comment by devoncarew** [comment]
Should we solve this by having `flutter create` emit the right intellij metadata? So IntelliJ doesn't create the launch config when opening an existing flutter project, but flutter projects (created by `flutter create`) just have all the bootstrapping info from the get go?

**Comment by mit-mit** [comment]
That is a good point Devon! We do that today with the .atom folder, and could just as well create a .idea folder with the config! CC @danrubel WDYT?

It looks like .idea folder is preferred over the .ipf file format:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206915235-IPR-vs-IDEA

**Comment by mit-mit** [comment]
As for config, I think we roughly need:

1. To enable Dart support
2. To have lib/main.dart open in an editor tab
3. To expand the lib folder in the project list
4. To create a config
  - Name: `Flutter`
  - Dart file: `<project dir>/lib.main.dart`
  - Checked mode: `disabled`

**Comment by mit-mit** [comment]
I went through an experiment making the changes I described above, and between each change made a commit to git. The resulting [commit log](https://github.com/flutter/flutter-intellij/files/511148/IdeaFileChanges.pdf) shows a pretty staggering set of changes :-|

**Comment by mit-mit** [comment]
@pq I was thinking that this is not blocking for fishfood (we can provide config instructions), but that it blocks the [external alpha](https://github.com/flutter/flutter-intellij/milestone/7) instead. WDYT?

**Comment by pq** [comment]
> @pq I was thinking that this is not blocking for fishfood 

👍  

That said, I got it mostly working yesterday so I should have a PR later this AM. 

> 1. To enable Dart support
> 2. To have lib/main.dart open in an editor tab
> 3. To expand the lib folder in the project list
> 4. To create a config
>   - Name: `Flutter`
>   - Dart file: `<project dir>/lib.main.dart`
>   - Checked mode: `disabled`

Hits all these high points. 😄

**Comment by mit-mit** [comment]
Excellent!

**Comment by pq** [comment]
Re-framing this issue back to being about run config generation.  We can open another to track other template generation ideas.

**Comment by pq** [comment]
PR https://github.com/flutter/flutter-intellij/pull/243:

<img width="1395" alt="screen shot 2016-10-05 at 1 43 21 pm" src="https://cloud.githubusercontent.com/assets/67586/19130804/b9009c4e-8b01-11e6-9173-27d2fd36528e.png">

🤘
