### ISSUE TITLE
Need to use Java 11

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#4404]
We need to change the build from Java 8 to Java 11. IntelliJ 2020.1 EAP no longer supports Java 8.

**Comment by devoncarew** [comment]
Just to clarify, we have to compile against the Java 11 APIs? The class files we generate need to target a Java 11 JVM?

**Comment by stevemessick** [comment]
I'm not sure yet how much work is involved. Java 8 is no longer supported so we need to change our build process to use Java 11. At minimum we need to verify the ant script works, change travis to use Java 11, and change kokoro. At some point, we also need to switch from ant to gradle to allow using Kotlin in the plugin code; depending on how much work is required in the ant script, this might be the time to switch to gradle. I'll look into it further after M44 is out.

**Comment by stevemessick** [comment]
Android Studio 4.2 canary 8 is using Java 11, at least partly. You still need the 1.8 JDK but you also need a Java 11 JDK.

**Comment by stevemessick** [comment]
At the current time (M50) we need to use Java 8 to compile for Android Studio 4.0 and 4.1. Java 11 is required for 4.2 and IntelliJ 2020.3 EAP.
