### ISSUE TITLE
send in the --platforms cli option for flutter create

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4414]
We should start sending in the --platform` cli option for `flutter create`. This is only for the `plugin` project template. We'll need to update the IntelliJ project wizard, the Android Studio project wizard (cc @stevemessick), and ensure that we don't send in the flag for older versions of Flutter.

There may be a chicken and the egg problem wrt testing the flutter framework version; that data doesn't exist until the flutter sdk has bootstrapped itself a bit. We can likely do something like show the options in the UI for any framework version, but in the project creation phase, first test the flutter version (`flutter --version --machine`). If that comes back as recent enough to send the `--platforms` flag we can send that in to flutter create (else we just rely on the default create platforms).

cc @amirh 

@jonahwilliams, re: the flutter sdk bootstrapping. What things need to initialize themselves before `flutter --version` runs? Is that just downloading the dart sdk? Does it also include downloading all the engine artifacts? If the 2nd part as well, can we not require the engine artifacts to be available before `--version` works? Omitting that step may also be useful for `flutter create` to work as well.

**Comment by jonahwilliams** [comment]
flutter --version should only require the Dart SDK:

```
jonahwilliams-macbookpro2:adashasdasd jonahwilliams$ rm -rf flutter/bin/cache/
jonahwilliams-macbookpro2:adashasdasd jonahwilliams$ flutter/bin/flutter --version
Downloading Dart SDK from Flutter engine 5e474ee860a3dfa5970a6c54b1cb584152f9c86f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  212M  100  212M    0     0  18.4M      0  0:00:11  0:00:11 --:--:-- 16.1M
Building flutter tool...
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Flutter 1.15.4-pre.253 • channel master • git@github.com:flutter/flutter.git
Framework • revision 8df3e057b2 (19 hours ago) • 2020-03-03 00:29:02 +0000
Engine • revision 5e474ee860
Tools • Dart 2.8.0 (build 2.8.0-dev.10.0 fbe9f6115d)
```

**Comment by devoncarew** [comment]
Waiting on a flutter tool change for this one; we'll likely create sub-commands of `flutter create`:

- `flutter create app <dir>`
- `flutter create plugin --platforms=... <dir>`
- `flutter create package <dir>`

**Comment by stevemessick** [comment]
This was fixed a while ago.
