### ISSUE TITLE
Dart ternary operation formatting not following code style

### ISSUE THREAD

**Issue by bergamin** [flutter/flutter-intellij#4418]
If I'm reporting this at the wrong place, let me know. I really don't know if Android Studio already had Dart support before adding this plugin.

## Steps to Reproduce

* Set dart code style as follows:  
![image](https://user-images.githubusercontent.com/14339291/75912405-ed8aec80-5e2f-11ea-96b9-83735f2e3cfa.png)
* Expectation:  
  ![image](https://user-images.githubusercontent.com/14339291/75912546-2a56e380-5e30-11ea-9f0c-75d15750cc37.png)
* Reality:  
![image](https://user-images.githubusercontent.com/14339291/75912720-6db15200-5e30-11ea-8d5b-516ce5685858.png)

This is what the preview example shows (which is still not exactly what I want, but it is also not what `Ctrl+Alt+L` is doing):
![image](https://user-images.githubusercontent.com/14339291/75912447-ff6c8f80-5e2f-11ea-8af5-3d1c41999726.png)

## Version info

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [versÃ£o 10.0.17134.1246], locale pt-BR)
    • Flutter version 1.12.13+hotfix.7 at C:\Flutter
    • Framework revision 9f5ff2306b (5 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\10087138\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.42.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>

**Comment by devoncarew** [comment]
In-lining your versions here:

`Android Studio (version 3.6)`; `Flutter plugin version 44.0.2`; `Dart plugin version 192.7761`

> Set dart code style as follows:

In a newer version of the Dart plugin you won't see the standard IntelliJ options for formatting within dart files. We now delegate everything to `dartfmt` which doesn't allow for configuring the formatting behavior. There are many threads on that decision - the main reason being for consistency across Dart code generally.

Thanks for the feedback; I believe this is working as intended.

**Comment by bergamin** [comment]
Oh well, alright then. I'll use their formatting.

Android Studio does show there is an update but when I click in "Update All (1)", nothing happens. I will try contacting Android Studio support for that.

Thanks!
