### ISSUE TITLE
[Suggestion] New constructor to follow Flutter conventions

### ISSUE THREAD

**Issue by scopendo** [flutter/flutter-intellij#4421]
When adding a new constructor via cmd+N, it is added at the end of the class.  This seems odd as constructors tend to be at the beginning of a class, with the Flutter classes seeming to follow the convention of adding the constructor at the top of the class:

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#constructors-come-first-in-a-class

It would seem sensible for the constructor to either be added at the beginning, or at the caret position.

**Comment by devoncarew** [comment]
Makes sense; cc @scheglov (a can also punt this issue to dart-lang/sdk if you like).

**Comment by scheglov** [comment]
Yeah, we always put constructors (or methods) at the end of the class, which is suboptimal.
Yes, please move it do SDK, for better tracking as analysis server / quick fix improvement.
