### ISSUE TITLE
Flutter Inspector is not showing the Widget tree of application

### ISSUE THREAD

**Issue by ivan-horchakov** [flutter/flutter-intellij#4426]
## Preconditions: 
1. Put the check-mark on the "Open Flutter Inspector view on app launch".
2. "Disable tracking widget creation locations" check-mark must be UN-CHECKED.

## Steps to Reproduce
1. Run the "main.dart" file via clicking on the "Run" button. 
2. Wait till the "Run" will be finished & Flutter Inspector bar automatically opens.

Expected result: FLutter Inspector shows the "Widget tree" of an application.
Actual result: FLutter Inspector does not show the "Widget tree" of an application. 

## Version info
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.19041.153], locale ru-UA)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Java\AdoptOpenJDK\jdk-8.0.242.08-hotspot\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
    • All Android licenses accepted.
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Users\ivan_\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\193.6494.35
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53
[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\ivan_\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1
[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
! Doctor found issues in 1 category.

**Important note:** I'm facing this issue on Win & Mac versions of IntelliJ IDEA CE, I've reproduced it on the IntelliJ IDEA 2020.1 EAP. Also if after the 2nd step you click on the "Dart DevTools" (it will show you the "Widget tree" into browser properly) and then close the browser's tab - Widget tree will appear into IntelliJ's Flutter inspector.

**Comment by kenzieschmoll** [comment]
@jacob314

**Comment by devoncarew** [comment]
@Ivan-Gorchakov - is this for a flutter mobile or flutter web app?

**Comment by Ivan-Gorchakov** [comment]
@devoncarew it is a flutter mobile app.

**Comment by Ivan-Gorchakov** [comment]
@devoncarew BTW, I've created new clean flutter project in IntelleJ - inspector works properly (running main.dart opens inspector tab with loading whole tree). So it can be related to the fact, that we are using Redux in ours.

**Comment by mahmoudsalah37** [comment]
> @Ivan-Gorchakov - is this for a flutter mobile or flutter web app?
 in flutter web not work too (visual studio code)

**Comment by Ivan-Gorchakov** [comment]
> > @Ivan-Gorchakov - is this for a flutter mobile or flutter web app?
>  in flutter web not work too (visual studio code)

This is mobile.

**Comment by muneebahmad0600** [comment]
I am having the same issue.. I am working on an app previously built by someone else. when I launch the flutter inspector, it show the widget tree slot empty. Now I don't know if it's the code or a third party library interfering with this or what.. but it sure is annoying.. please help... !!!

**Comment by jacob314** [comment]
Please uncheck the "Disable tracking widget creation locations" setting and let me know if you still see the issue. We should make the inspector still work somewhat when widget creation locations are disabled but that setting is crucial for the inspector to work well.

**Comment by ivan-horchakov** [comment]
It shows me a widget tree from time to time (if I left it alone for a few minutes), I guess it depends on the app complexity - maybe it needs more time to load. But I'm not 100% sure about this.

**Comment by ivan-horchakov** [comment]
Ha-ha, looks like I've jinxed it via my previous post - this is how Flutter Inspector looks like for me now 
![image](https://user-images.githubusercontent.com/30525592/97972176-cfb1c500-1dcc-11eb-9c49-46fe54019685.png)

**Comment by ivan-horchakov** [comment]
@jacob314 should I create a separate issue for the current Flutter Inspector tab behavior (from my comment above)? I'm facing it on Mac & Win IntelliJ:
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19042.572], locale ru-UA)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (not installed)
[√] VS Code, 64-bit edition (version 1.50.1)
[√] Connected device (1 available)
! Doctor found issues in 1 category.

**Comment by pratamatama** [comment]
Same issue happened here on Windows.

```
PS C:\Users\Fukka\Documents\getx_prismahr> flutter doctor
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19042.572], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.50.1)
[√] Connected device (1 available)

• No issues found!
```

![image](https://user-images.githubusercontent.com/42239243/98506237-9cb87700-228d-11eb-84bb-e5aac0c59a99.png)

**Comment by statsss** [comment]
аналогичная проблема

**Comment by lukaszciastko** [comment]
I have a problem with the widget inspector both inside VS Code and in the browser. With complex views, the widget inspector only shows the top app widget and the app bar - the body/content is gone. When i open a simpler view, the body/content is visible again.

**Comment by jacob314** [comment]
Any chance you have a repro you can share with us?

**Comment by shoxter** [comment]
I'm also getting this with the latest version of IntelliJ and the Flutter/Dart plugins... :(

**Comment by ishan0805** [comment]
I did a flutter clean and its start working again

**Comment by zyllus17** [comment]
This helped me get it back to work in VSCode.

1. Stop the emulator if you are running the app.
2. Run `flutter clean` in your terminal
3. Run the app again.
4. Open Command Palette in VS Code by pressing `F1`
5. Search for `Dart: Open Dev Tools` and click enter
6. Click `Open Widget Inspector Page`

The Widget Inspector will now display the Widget Tree.

**Comment by nabeelkv** [comment]
Better solution: [Flutter Widget Inspector - Not displaying](https://stackoverflow.com/questions/51181774/flutter-widget-inspector-not-displaying)

**Comment by correiarangel** [comment]
I had the same error after several tests, comparing the configuration files I realized that the error was in my launch.json configuration file.

   "version": "0.2.0",
     "settings": [
         {
             "name": "main",
             "type": "dart",
             "request": "launch",
             "program": "lib/main.dart"
         },
         {
             "name": "portal_amazonas Debug",
             "request": "launch",
             "type": "dart",
             "args": [
                 "--flavor",
                 "portal_amazonas"
             ],
             "program": "lib/flavors/main_portal_amazonas.dart"
         },
         {
             "name": "portal_amazonas",
             "request": "launch",
             "type": "dart",
             "flutterMode": "profile",
             "args": [
                 "--flavor",
                 "portal_amazonas"
             ],
             "program": "lib/flavors/main_portal_amazonas.dart"
         },
         {
             "name": "control_care Debug",
             "request": "launch",
             "type": "dart",
             "args": [
                 "--flavor",
                 "control_care"
             ],
             "program": "lib/flavors/main_control_care.dart",
         },
         {
             "name": "control_care",
             "request": "launch",
             "type": "dart",
             "flutterMode": "profile",
             "args": [
                 "--flavor",
                 "control_care"
             ],
             "program": "lib/flavors/main_control_care.dart",
         },

         {
             "name": "Run all tests",
             "type": "dart",
             "request": "launch",
             "program": "test/",
         },
     ]
}

See that the parameter "flutterMode": "profile" which could be "flutterMode": "debug", or "flutterMode": "release",

After removing this parameter everything returned to normal.

OBS: in my case I have flavors configured
