### ISSUE TITLE
simplify adding a single-child parent Widget

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#443]
_From @HansMuller on February 19, 2016 0:13_

This comes up all the time as one realizes that a widget needs padding, or a border, or a background, etc.

Say I start with this:

```
  return new Foo(
    child: new Column(
      justifyContent: FlexJustifyContent.start,
      children: <Widget>[
        ...
      ]
    )
  );
```

and I want to end up with this:

```
return new Foo(
  child: new Padding(
    padding: const EdgeDims.all(16.0),
    child: new Column(
      justifyContent: FlexJustifyContent.start,
      children: <Widget>[
        ...
      ]
    )
  )
);
```

I'd like to be able to put the cursor inside the Column(), press a magic key to get:

```
return new Foo(
  child: new TBD(
    child: new Column(
      justifyContent: FlexJustifyContent.start,
      children: <Widget>[
        ...
      ]
    )
  )
);
```

which is easily finished by changing TBD to Padding and add the padding: parameter.

_Copied from original issue: flutter/flutter#2016_

**Comment by mit-mit** [comment]
_From @sethladd on February 19, 2016 0:18_

@pq will the analyzer plugins allow us to add Quick Fixes? If so, we should be able to do this fairly straight forwardly, yes?

cc @scheglov @kevmoo for ideas, too

**Comment by mit-mit** [comment]
_From @scheglov on February 19, 2016 0:28_

Yes, DAS has [the extension point](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/plugin/edit/fix/fix.dart) for fixes.

**Comment by mit-mit** [comment]
_From @sethladd on February 19, 2016 0:29_

Nice! Looking forward to using them :)

**Comment by mit-mit** [comment]
_From @sethladd on November 14, 2016 23:8_

Should we move this, and other "affects: jetbrains-plugin" to their issue tracker?

cc @mit-mit

**Comment by mit-mit** [comment]
_From @pq on November 14, 2016 23:26_

> Should we move this, and other "affects: jetbrains-plugin" to their issue tracker?

SGTM. 

Incidentally, IDEA has it's own mechanism for code boiler-plate.  An alternative to using a DAS plugin, would be to contribute some [live code templates](https://blog.jetbrains.com/webide/2012/10/high-speed-coding-with-custom-live-templates/) to the Flutter plugin.  Not as smart since they can't leverage all that the analyzer but maybe in this case that's OK?

**Comment by mit-mit** [comment]
_From @sethladd on November 14, 2016 23:31_

Yeah, I think we need something like "smart" live code templates. We need to know if we're wrapping with something that takes a single child or multiple children.

**Comment by mit-mit** [comment]
> Should we move this, and other "affects: jetbrains-plugin" to their issue tracker?

I think that only makes sense for things that apply to "general Dart"? This seems Flutter specific (it would be odd to get this completion while typing Dart for Web or Server code).

@pq shouldn't this (and other Flutter specific issues) go to https://github.com/flutter/flutter-intellij/issues?

**Comment by mit-mit** [comment]
_From @sethladd on November 15, 2016 16:25_

> https://github.com/flutter/flutter-intellij/issues

Sorry, that's what I meant.

**Comment by mit-mit** [comment]
_From @pq on November 15, 2016 16:53_

SGTM 👍

**Comment by scheglov** [comment]
I strongly believe that this functionality should live in DAS and its plugins.

I can imagine a lint for Flutter, which for example will complain when you have `children` with a single widget, when you could use `child`. A Quick Fix for this lint is a bit more complex than AFAIK IntelliJ code templates allow, so you would implement it in DAS.

But then why to have some code transformations in IntelliJ, and some in DAS? And of course these Quick Assists are very resolution specific - it would be sad to pollute assist menu with actions that don't make sense in the context.

**Comment by mit-mit** [comment]
Hi @scheglov I am not familiar with the experience you get from DAS assists, can you give an example of a current one and how to 'trigger it'?

**Comment by devoncarew** [comment]
@scheglov, we can consider this a tracking issue for the functionality, and the implementation can live elsewhere. This would be a good use-case for a flutter specific analysis server plugin.

**Comment by scheglov** [comment]
@mit-mit 

![image](https://cloud.githubusercontent.com/assets/384794/20396331/b1617548-ac9a-11e6-9b5e-69a6393f3672.png)

Your keyboard shortcut may be different.
![image](https://cloud.githubusercontent.com/assets/384794/20396425/fc82b686-ac9a-11e6-89e8-77cdc9c0706b.png)

**Comment by mit-mit** [comment]
Thanks @scheglov looks good.

**Comment by sethladd** [comment]
> I strongly believe that this functionality should live in DAS and its plugins.

Yes, please!

**Comment by stevemessick** [comment]
I heard this feature was shown in a recent demo.

**Comment by pq** [comment]
> I heard this feature was shown in a recent demo.

It was and went over great! 👍
