### ISSUE TITLE
[Problem] import packages issues

### ISSUE THREAD

**Issue by JAICHANGPARK** [flutter/flutter-intellij#4430]
## Steps to Reproduce

I am importing material.dart but it is not loaded automatically.

![image](https://user-images.githubusercontent.com/19484515/77019654-9145d200-69c4-11ea-8685-8951dcf601fe.png)

## Version info

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18363.720], locale ko-KR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.42.1)
[√] Connected device (3 available)

• No issues found!

**Comment by KlausJokinen** [comment]
Try cleaning IDE cache

`Select File | Invalidate Caches/Restart from the main menu.`

**Comment by jacob314** [comment]
Did clearing the cache fix the issue?

**Comment by JAICHANGPARK** [comment]
@KlausJokinen  @jacob314 
Thank you for comment ! 
It's works for me~
