### ISSUE TITLE
Android emulator(Nexus 6 ) option is missing from Select devices only  Chrome(Web) and Web Server  options are apperar. 

### ISSUE THREAD

**Issue by pspatel011** [flutter/flutter-intellij#4441]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
After updating flutter for web development my android emulator (Nexus 6 ) is missing from S**elect Device Option**. Only two option shows currently **1. Chrome (Web) and 2. Web Server (Web).**

![Screenshot from 2020-03-28 03-44-14](https://user-images.githubusercontent.com/62777867/77809266-fbd9ca80-70b4-11ea-8e55-322587e3a8d7.png)
 
## Version info
[✓] Flutter (Channel beta, v1.15.17, on Linux, locale en_US.UTF-8)
    • Flutter version 1.15.17 at /home/parth/Softwares/flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/parth/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/parth/Softwares/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/parth/Softwares/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by jacob314** [comment]
If you type ` flutter emulators` on the command line, what do you see?
You should be able to also manually launch an emulator on the command line by typing
`flutter emulators --launch your_emulator_name`
I suspect there might be something going wrong with emulators on your machine based on the permissions error in the emulators dialog in the screenshot.
![Screen Shot 2020-03-30 at 9 31 43 AM](https://user-images.githubusercontent.com/1226812/77937636-777c7880-7269-11ea-9705-237c850b4a08.png)

**Comment by alanscot** [comment]
Device for Emulator not showing in dropdown
![ANdroid_Studio_Fails_to_show_Device](https://user-images.githubusercontent.com/7455851/81628502-af70f280-93b5-11ea-8c42-f3d1ff6192c3.JPG)
