### ISSUE TITLE
Hot relod is not working ?

### ISSUE THREAD

**Issue by pspatel011** [flutter/flutter-intellij#4442]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
As Flutter Documentation says you did not rerun your code just click relode but when i click on relode just relode successfully appear but i need to rerun the app every time when i  change the  code.

## Version info

[✓] Flutter (Channel beta, v1.15.17, on Linux, locale en_US.UTF-8)
    • Flutter version 1.15.17 at /home/parth/Softwares/flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/parth/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/parth/Softwares/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/parth/Softwares/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!

**Comment by mvpmvh** [comment]
to add on to this issue..instead of performing a hot reload, intellij always performs a hot restart.

IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Registry: 
Non-Bundled Plugins: Dart, io.flutter

**Comment by devoncarew** [comment]
@pspatel011, re:

> As Flutter Documentation says you did not rerun your code just click relode but when i click on relode just relode successfully appear but i need to rerun the app every time when i change the code.

We'd need more info about the changes you're making. Many types of changes can be hot reloaded, some cannot. There is some documentation about that here: https://flutter.dev/docs/development/tools/hot-reload#limitations

@mvpmvh:

> instead of performing a hot reload, intellij always performs a hot restart

You may not be seeing the same issue as what's reported here. Can you provide more details, such as the version of flutter that you're using, and the version of the Flutter IntelliJ plugin?

**Comment by mvpmvh** [comment]
@devoncarew - i'm currently using Flutter 1.15.7 channel beta; flutter plugin 44.0.3
