### ISSUE TITLE
Add info on how to enroll on beta/dev channel

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter-intellij#4448]
Since this plugin has a beta/dev releasing channel, there should be some guidance (README, wiki...) on how to enroll on such channel.

**Comment by jacob314** [comment]
@stevemessick

**Comment by stevemessick** [comment]
We agree; now that it appears to be working properly we're going to get the word out. For now, you can see the instructions in the release notes:
https://groups.google.com/forum/#!topic/flutter-announce/tTgQcTgqrKg

**Comment by stevemessick** [comment]
I added the instructions to our [wiki](https://github.com/flutter/flutter-intellij/wiki)
