### ISSUE TITLE
the run button should execute flutter run (--debug)

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#445]
Change the run button from executing flutter run --release to flutter run (just like the current debug button).

**Comment by devoncarew** [comment]
We should investigate doing this as part of a patch to 0.1.5.

**Comment by mit-mit** [comment]
@pq any news?

**Comment by pq** [comment]
Still exploring options.  Unfortunately, it's looking a bit more involved than a simple patch.

**Comment by pq** [comment]
Not pretty behind the scenes but here's the current state of the world.

<img width="1073" alt="screen shot 2016-11-22 at 8 22 20 am" src="https://cloud.githubusercontent.com/assets/67586/20531863/ea23ca7a-b08c-11e6-9c96-91ea2cffe885.png">

This is the run view re-worked as debug less breakpoint management and variable and frame views.  The approach is pretty hacky and still a WIP but _**progress**_ nonetheless!

**Comment by devoncarew** [comment]
🎆

**Comment by devoncarew** [comment]
done?

**Comment by pq** [comment]
Yep.  Modulo bugs. 👍
