### ISSUE TITLE
Autocompletion does not work for dependency package.

### ISSUE THREAD

**Issue by abhishekredspace** [flutter/flutter-intellij#4451]
## Steps to Reproduce
I am recently moving to FLutter and started with Codelabs. I am not seeing the autocomplete working in Android Studio for the dependent class. For example. using the CodeLab, I imported the 
`import 'package:english_words/english_words.dart';` in my class. I do not see the autocomplete working correctly for this package. Only when I type the complete class name, I see the methods in the class. 
Example:
![Screen Shot 2020-03-31 at 9 47 38 AM](https://user-images.githubusercontent.com/16784627/78028043-bf1c0680-7334-11ea-8929-de31a3428b17.png)
On line number 9, I had to type the whole class name and for demo purpose, I am showing the issue on line number 10 where you can see the autocomplete does not work. 

## Version info
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-CA)
    • Flutter version 1.12.13+hotfix.8 at /Users/asharma/Library/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/asharma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/asharma/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 4 categories.
```

**Comment by jacob314** [comment]
Have you tried these two steps?
1. Make sure you run `flutter pub get`
https://flutter.dev/docs/get-started/codelab#step-2-use-an-external-package

2. If that doesn't work, try restarting the analysis server.
https://www.jetbrains.com/help/idea/dart-analysis-tool-window.html
  | Restart Dart Analysis Server | Click this button to kill the Dart Analysis server and then start it.

If step 1 fixes the issue then there isn't a bug. You will need to run `flutter pub get` after adding new dependencies.
If step 2 fixes the issue then there is a bug in the analysis server and we can move the bug to 
https://github.com/dart-lang/sdk/issues

**Comment by abhishekredspace** [comment]
Thanks for your reply.

Step 1 did not help. I still see the issue.
Step 2, I do not see `Restart Dart Analysis Server` button.
![Screen Shot 2020-04-02 at 12 48 19 PM](https://user-images.githubusercontent.com/16784627/78269770-638e7c00-74e0-11ea-9ee8-264490d52e76.png)

**Comment by stevemessick** [comment]
It is the top icon in your screen shot. The red curved arrows. Let us know if that helps.

**Comment by abhishekredspace** [comment]
@stevemessick The documentation over here 
https://www.jetbrains.com/help/idea/dart-analysis-tool-window.html shows a different icon for 
Restart Dart Analysis Server 

<img width="919" alt="Screen Shot 2020-04-06 at 12 44 08 PM" src="https://user-images.githubusercontent.com/16784627/78577522-90a29d80-7804-11ea-9192-b0e028ba23d7.png">

The one you are referring to is mentioned as "Reanalyze Dart Sources". I have tried clicking this one, but no help.

**Comment by stevemessick** [comment]
Looks like the documentation is out of date.

I'm going to try moving this issue. If that doesn't work please file it at the link @jacob314 mentioned above.

/move https://github.com/dart-lang/sdk/issues

**Comment by stevemessick** [comment]
One more try.

/move dart-lang/sdk

**Comment by dm8tr** [comment]
> Have you tried these two steps?
> 
> 1. Make sure you run `flutter pub get`
>    https://flutter.dev/docs/get-started/codelab#step-2-use-an-external-package
> 2. If that doesn't work, try restarting the analysis server.
>    https://www.jetbrains.com/help/idea/dart-analysis-tool-window.html
>      | Restart Dart Analysis Server | Click this button to kill the Dart Analysis server and then start it.
> 
> If step 1 fixes the issue then there isn't a bug. You will need to run `flutter pub get` after adding new dependencies.
> If step 2 fixes the issue then there is a bug in the analysis server and we can move the bug to
> https://github.com/dart-lang/sdk/issues

Damnnn !!!!!
I threw my time in the air for over three months and had no idea of Dart Analysis possibility. Take off your mask, we recognized you, you're a hero.

**Comment by qfournetworks** [comment]
Make sure to put your dependencies to 'dependencies' not to 'dev_dependencies'.
