### ISSUE TITLE
TextField cursor problem with TextDirection.rtl

### ISSUE THREAD

**Issue by Zewe1995** [flutter/flutter-intellij#4452]
TextField and TextFormField cursor not moved with text in RTL direction... please solve this bug...

**Comment by jacob314** [comment]
Do you have any details on where in the IntelliJ UI you experienced this bug?

**Comment by Zewe1995** [comment]
Yes, I used TextField and TextFormField on flutter web... When I change
TextDirection to rtl and typing with Arabic and persian character, the
cursor moved between position 0 and 1, I compiled this project (on channel
beta,dev,master) and test it on chrome, mozila, edge chromium and opera..
but all has this problem... I hope the flutter teem solve this..

در تاریخ پنجشنبه ۲ آوریل ۲۰۲۰،‏ ۱۹:۴۰ Jacob Richman <
notifications@github.com> نوشت:
