### ISSUE TITLE
"Attach debugger to Android process" icon is disappeared in Android Studio

### ISSUE THREAD

**Issue by YunanChen** [flutter/flutter-intellij#4458]
I include a flutter_module as submodule to my existed android project. The structure is like following:
-android project
--app
--other_module
--flutter_module

With this structure, I can both edit android native code and dart code,  run Android app and hot reload dart code. However, when I want to debug the android code, I can't find the "Attach debugger to Android process" icon. 

The tools panel at Android studio:
![image](https://user-images.githubusercontent.com/13514469/78221276-aa3aa100-74f5-11ea-8753-85dadd2c49cd.png)

I have found the same issue at https://github.com/flutter/flutter/issues/45836. So I disable the flutter-plugin at Android Studio and then it works. But I think it is not elegant. As a result , I create this issue. Looking forward to your help.

**Comment by tomrozb** [comment]
Hey guys this is a real problem. There's no option to attach a debugger to a running android process to debug the native app. Not only the icon dissapeared, but the attach debugger window is completely different for me.

<img width="374" alt="Screenshot 2020-04-04 at 14 14 21" src="https://user-images.githubusercontent.com/4646706/78450424-c584e800-767e-11ea-9b78-844523e78040.png">

**Comment by stevemessick** [comment]
Sorry about that. In the days before add-to-app we disabled that action because it didn't make sense in a Flutter project. We'll add it back.

**Comment by philpowers** [comment]
@stevemessick You said that this "doesn't make sense in a Flutter project."

Can you clarify this?

I'm trying to debug Android platform code, as documented here: https://flutter.dev/docs/testing/oem-debuggers

Which specifically says to use the the "Attach debugger to Android process" functionality. Am I missing something here (very well could be the case). 

Also, is there a way to upgrade the Flutter plugin within Android Studio to a version with the fix?
