### ISSUE TITLE
Web dev: debug mode debuggy(web service no response that just stuck at the white screen)

### ISSUE THREAD

**Issue by JohnGu9** [flutter/flutter-intellij#4462]
## Steps to Reproduce

web service no response that just stuck at the white screen (the html title is the same as the project title, not the title of MaterialApp) but profile mode is fine.
By create new project issue still exists.

## Version info
Flutter 1.15.17 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2294d75bfa (4 weeks ago) • 2020-03-07 00:28:38 +0900
Engine • revision 5aff311948
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.15.17 at D:\Flutter\flutter
    • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Android-Studio-IDE\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android-Studio-IDE
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by stevemessick** [comment]
We need more information to reproduce the problem. Please be more specific.

**Comment by JohnGu9** [comment]
What's more information? I just can't lunch debug mode web application. In debug mode, JavaScript doesn't work ta all that stuck at white screen (the empty HTML). I try to fix it, reinstalled flutter and create a new project. But that also doesn't work. My computer just running docker, one container occpy the 5000 port. But it should not matter, because the last version doesn't have this issue but this version does.

**Comment by stevemessick** [comment]
@pq could this be related to https://github.com/flutter/flutter-intellij/pull/4469?

**Comment by JohnGu9** [comment]
![Sequence 03_1](https://user-images.githubusercontent.com/31389215/78877253-23e90680-7a83-11ea-9cac-91e492c1be3e.gif)

**Comment by JohnGu9** [comment]
Just like this. Debug mode doesn't work since the recent beta update. I can only use profile mode but profile mode doesn't output print() info.

**Comment by pq** [comment]
@JohnGu9: is this still an issue? (Sorry for the lag in response!)

**Comment by JohnGu9** [comment]
Seem new version of flutter fix this issue. Now it work fine.
