### ISSUE TITLE
android studio totally frozen with Flutter plugin v45  

### ISSUE THREAD

**Issue by EngDjango** [flutter/flutter-intellij#4463]
installing Flutter plugin v45 in android studio 192.7142 makes it totally frozen for about 20 seconds when switching editor dart tabs,
switching back Flutter plugin to v44 solved the problem.

**Comment by stevemessick** [comment]
I can't reproduce this. Does it happen it you switch back to M45? If so, is there any other indicator of what's happening? Maybe a message in the bottom status bar, a notification balloon, or anything else changing in the UI?

**Comment by abduqodirov** [comment]
In my case it's not working well again after 20 seconds.

**Comment by abduqodirov** [comment]
In my case it has been frozen for 34 minutes.

**Comment by abduqodirov** [comment]
> installing Flutter plugin v45 in android studio 192.7142 makes it totally frozen for about 20 seconds when switching editor dart tabs,
> switching back Flutter plugin to v44 solved the problem.

How did you install v44. I'm having a problem when I tried to install from disk

**Comment by pq** [comment]
@abduqodirov or @EngDjango: do either of you have a proxied network?

**Comment by EngDjango** [comment]
@stevemessick no sir, no indicator of any kind, and if i minimize android studio window -on windows- to the taskbar and restore it -during the freeze- i get black screen untill the freeze end;
and i've switched back and forth between 45 and 44 many times but did not solve it;

**Comment by pq** [comment]
Sorry for the hassle here.  I see some issues in some networking code I added in M45.  Working on a fix right now.

**Comment by EngDjango** [comment]
@pq i do set custom DNS server in my network adapter, but i don't know if that the problem;

**Comment by pq** [comment]
Good to know.  Thank you!
