### ISSUE TITLE
Project Structure vanishes after Git-committing and Git-cloning a new project

### ISSUE THREAD

**Issue by MateusRodCosta** [flutter/flutter-intellij#4464]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

The simplest steps to reproduce seem to be as follow:

1. Create a project with the Android Studio "New Flutter Project" option
2. Commit all files on the project (`git add .` and `git commit`) and push them to a repo (e.g. https://gitlab.com/MateusRodCosta/flutter-test-app)
3. Clone the repo in a new folder
4. Open the new cloned project with Android Studio
5. If the IDE offers you the option, run pub get (note that it didn't make any difference for me)

Expected result:

- Correct project metadata (.iml files are actually generated)
- The option to "Open Android module in Android Studio" appears on the Flutter sub-menu
- "Project Structure" dialog is always accessible
- Some level of autocomplete on Java/Kotlin files (when using root of flutter project) 

Actual results:

- No metadata seems to be actually created
- option to "Open Android module in Android Studio" isn't present on the Flutter sub-menu
- "Project Structure" option disappears at times
- No autocomplete at all on Kotlin/Java files (when using root of flutter project) 

As an example, here is what the Project Structure looks on a freshly-created project:

![Screenshot from 2020-04-05 15-16-47](https://user-images.githubusercontent.com/24463334/78506764-4b259800-7752-11ea-9e9a-68f62858406b.png)
![Screenshot from 2020-04-05 15-16-56](https://user-images.githubusercontent.com/24463334/78506765-4f51b580-7752-11ea-972a-9af56fef3644.png)
![Screenshot from 2020-04-05 15-34-11](https://user-images.githubusercontent.com/24463334/78506856-f5052480-7752-11ea-860d-bed61d12c813.png)

And on the same project after being cloned:

![Screenshot from 2020-04-05 15-30-13](https://user-images.githubusercontent.com/24463334/78506778-6b555700-7752-11ea-8a4c-1c17df576870.png)
![Screenshot from 2020-04-05 15-30-17](https://user-images.githubusercontent.com/24463334/78506783-6f817480-7752-11ea-9348-a12cb055c16e.png)
![Screenshot from 2020-04-05 15-34-50](https://user-images.githubusercontent.com/24463334/78506864-03534080-7753-11ea-9cad-3d5bffc75e84.png)

Metadata should be created but isn't. And there seems to be no way to create it except by doing it manually.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.7, on Linux, locale en_US.utf8)
    • Flutter version 1.12.13+hotfix.7 at /home/mateusrc/flutter
    • Framework revision 9f5ff2306b (2 months ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/mateusrc/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/mateusrc/Android/Sdk
    • Java binary at: /home/mateusrc/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/mateusrc/Android/android-studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/mateusrc/idea-IC-192.5728.98
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.25

[✓] Connected device (1 available)
    • moto g 7 • 0055562019 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by stevemessick** [comment]
The project template is incorrect. It should not have `*.iml` in the `.gitignore`. Here's what JetBrains has to say about source control:
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems
