### ISSUE TITLE
Stop logging derivative Flutter runtime errors

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#4466]
I believe our current error analytics include all the runtime errors the Flutter framework reports to the IDE. However, a substantial amount of those errors are likely to be triggered by the primary error the user really needs to deal with in their own code (e.g., https://github.com/flutter/flutter-intellij/pull/4447). Can we log the primary error only, perhaps using the same logic from the PR mentioned above? 

Cc: @devoncarew @jayoung-lee

**Comment by devoncarew** [comment]
👍 sgtm

**Comment by InMatrix** [comment]
I'm looking into the ‘Renderbox was not laid out’ error and found that this one might be often derived from primary errors such as:
* "vertical viewport was given an unbounded height"
*  "An InputDecorator, which is typically created by a TextField, cannot have an unbounded width"

It would be helpful to get this issue resolved to avoid getting those primary errors buried by the sheer amount of generic, derivative errors.
