### ISSUE TITLE
Clarify generic error names in analytics

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#4467]
The Flutter framework error analytics include some rather generic and sometimes vague names such as:
* 'package
* rangeerror
* invalid-argument
* exception

Does each name refer to a unique type of error? Can you clarify what are those errors? Thanks!

**Comment by devoncarew** [comment]
This is due to our extremely ad-hoc method for converting error messages into IDs. We could improve the heuristic, but I wonder if we should continue to iterate on that system, or just have real IDs for error messages.

**Comment by devoncarew** [comment]
cc @jacob314

**Comment by devoncarew** [comment]
Here's the current logic: https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/logging/FlutterErrorHelper.java#L30

**Comment by devoncarew** [comment]
@InMatrix - what are the current generic error names we're seeing (and, any idea about how to narrow down the source errors we're seeing them from)? Our series of regexs unfortunately essentially obfuscates the original error text. 

This would be more reliable with actual error codes. cc @csells

**Comment by InMatrix** [comment]
I think the only one that appears to be a parsing issue is the error logged as `'package` in our analytics. The other ones I mentioned in the original post seems to be just generic in its source, like `exception` and `invalid-argument`.

**Comment by devoncarew** [comment]
From some investigation, we produce the `'package` ID when we encounter an error from an assert statement, used without an assert message:

```
assert(1 != 2);
```

`assert(1 != 2, 'my assert test`)` we would be able the create a good error id for.

**Comment by InMatrix** [comment]
I'm still seeing "'package" logged as an error id in the framework errors dashboard, when I set the date range to the last seven days. Is there a way to verify if this fix worked? Cc: @jayoung-lee to check if the dashboard has been refreshed with the latest data.
