### ISSUE TITLE
Android Studio freezes with flutter when changing files

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter-intellij#4471]
Copied from @Elsrougy report at https://github.com/flutter/flutter/issues/54222:

I had flutter with android studio for a while now and everything is working great until one day in any flutter project when I try to open any file android studio freezes for few minutes. For example, if I was in the main.dart file and then switched/opened another file the freezing occurs, and that happens in any file not just main. This freezing doesn't happen with normal android studio projects only with flutter

it's worth mentioning that in android studio plugins it always says can't load marketplace and to check the connection but I don't know when did that started and if it is related or not.

Also flutter analyze is taking a long time with no output. I tried reinstalling flutter, reinstalling android studio, reinstalling flutter (stable and beta), installing android studio beta instead of stable and nothing happened still the same problem

attached is idea.log and threadDumps-freeze that android studio generates.

```
flutter doctor -v output:
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at E:\src\flutter
    • Framework revision f139b11009 (8 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: E:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at E:\Android Studio
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

```
[logs.zip](https://github.com/flutter/flutter/files/4446727/logs.zip)

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/54222#issuecomment-611118500

It looks like the survey contents are being [read on the main thread](https://github.com/flutter/flutter-intellij/blob/a88784769ade1897f45bff5aa4b06c1e31af594a/src/io/flutter/survey/FlutterSurveyService.java#L56)?
```
	at java.net.URL.openStream(URL.java:1068)
	at io.flutter.survey.FlutterSurveyService.readString(FlutterSurveyService.java:71)
	at io.flutter.survey.FlutterSurveyService.fetchSurveyContent(FlutterSurveyService.java:59)
	at io.flutter.survey.FlutterSurveyService.getLatestSurveyContent(FlutterSurveyService.java:50)
	at io.flutter.survey.FlutterSurveyNotifications.checkForDisplaySurvey(FlutterSurveyNotifications.java:76)
	at io.flutter.survey.FlutterSurveyNotifications.access$000(FlutterSurveyNotifications.java:31)
```

**Comment by devoncarew** [comment]
Thanks for the report! This was fixed by @pq yesterday in https://github.com/flutter/flutter-intellij/pull/4469.

@stevemessick, I think we'll need to release a new version with the fix for this.

**Comment by pq** [comment]
@jmagman: super sorry for the hassle here.

@stevemessick kicked off a dev build with the fix.  If you want to give that a whirl, the instructions are in the wiki here:

https://github.com/flutter/flutter-intellij/wiki/Dev-Channel

Having added the channel, you should see an update that looks like this:

![image](https://user-images.githubusercontent.com/67586/78835938-ed898980-79a5-11ea-858e-d9c2d12b8b59.png)

**Comment by devoncarew** [comment]
> @stevemessick kicked off a dev build with the fix. If you want to give that a whirl, the instructions are in the wiki here:

I do think that we need to release a patch to the stable release channel as well, otherwise users will have to wait a month for the fix.

**Comment by Elsrougy** [comment]
> @jmagman, @Elsrougy: super sorry for the hassle here.
> 
> @stevemessick kicked off a dev build with the fix. If you want to give that a whirl, the instructions are in the wiki here:
> 
> https://github.com/flutter/flutter-intellij/wiki/Dev-Channel
> 
> Having added the channel, you should see an update that looks like this:
> 
> ![image](https://user-images.githubusercontent.com/67586/78835938-ed898980-79a5-11ea-858e-d9c2d12b8b59.png)

That was a really fast response, Thank You!

**Comment by pq** [comment]
@Elsrougy: did you have a chance to try the dev channel build?

**Comment by angwandi** [comment]
Microsoft Windows [Version 10.0.18363.815]
(c) 2019 Microsoft Corporation. All rights reserved.
i\myjiji_flutter>flutter doctor -v
[√] Flutter (Channel beta, v1.17.0-3.3.pre, on Microsoft Windows [Version 10.0.18363.815], locale en-GB)
    • Flutter version 1.17.0-3.3.pre at C:\Users\demad\flutter
    • Framework revision 0da1ab0922 (3 days ago), 2020-04-28 11:02:34 -0700
    • Engine revision 376ad6a64b
    • Dart version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\demad\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1-dev.3
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\demad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.0

[√] Connected device (4 available)
    • moto g 6 plus • ZY32389KCQ         • android-arm64  • Android 9 (API 28)
    • TV358DVB      • 192.168.88.95:5555 • android-arm64  • Android 8.0.0 (API 26)
    • Chrome        • chrome             • web-javascript • Google Chrome 81.0.4044.129
    • Web Server    • web-server         • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

Completely freezing my system when a run a flutter project.

**Comment by remarkked** [comment]
Android studio just dies when I change code in the exact specific file.

**Comment by jmagman** [comment]
@remarkked This is an ancient, closed issue.  Please file a new issue describing what you're seeing.
