### ISSUE TITLE
Native Code Inside Flutter showing wrong errors

### ISSUE THREAD

**Issue by vinay-khatri** [flutter/flutter-intellij#4472]
![Screenshot (21)](https://user-images.githubusercontent.com/49782298/78878193-9e0f9000-7a6f-11ea-9211-bec7fb844a25.png)
Just wrote some kotlin code inside flutter app and android studio filled my MainActivity.kt with red squiggly lines all over the place. Even it refused to accept android package. On hover over, it showed "Unresolved reference: android" and as a result every line of kotlin code is underlined red. I wasted 2 days to figure out whats wrong with my code but today i decided to run my app and it ran absolutely fine. So all those errors were fake. Plz solve it. It makes code unreadable. And i think its something to do with android sdk build-tools.

Build: AI-192.7142.36.36.6308749, 202003181856, 

AI-192.7142.36.36.6308749, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale
    en-IN)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (10 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\vinay\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\vinay\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\vinay\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

**Comment by stevemessick** [comment]
There are two solutions:
- Menu `Flutter > Open Android module in Android Studio`
- Setting `Enable code completion, navigation, etc. for Java / Kotlin`
