### ISSUE TITLE
Errors might get logged when they came from automated tests

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#4474]
I suspect Flutter runtime errors are getting logged when they are generated from running widget tests within the IDE. If that's the case, I'd like to request their exclusion or special handling, since it adds noise to the data.

**Comment by devoncarew** [comment]
From looking at this, I don't believe we're logging events from `flutter test` runs in the IDE. We only log errors tests from flutter app runs - `flutter run -d foo_device`.

Do you see something in the analytics stream that makes you think we're logging from tests?

**Comment by devoncarew** [comment]
Closing as I don't think we're logging flutter errors from tests, but please re-open if you see examples of otherwise.
