### ISSUE TITLE
Flutter web app option not found under dart templates while creating new dart project

### ISSUE THREAD

**Issue by DhavalRKansara** [flutter/flutter-intellij#4477]
**Version info**
**flutter doctor -v:**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15 19A582a,
    locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/dhavalkansara/flutter
    • Framework revision f139b11009 (11 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dhavalkansara/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761

[!] Connected device
    ! No devices available
```

I want to create a new flutter web application and for that, I don't found any option as under the dart template as **Flutter Web App -  a simple Flutter Web App**.

**Expected result:** 

<img width="679" alt="Screen Shot 2020-04-10 at 6 20 21 PM" src="https://user-images.githubusercontent.com/44993081/78992151-384b0300-7b58-11ea-9c68-f2a606057e1b.png">

**Dart templates in my Intellij Idea:**

<img width="796" alt="Screen Shot 2020-04-10 at 6 20 34 PM" src="https://user-images.githubusercontent.com/44993081/78992216-63355700-7b58-11ea-9c03-f62bafc311dc.png">

**Comment by devoncarew** [comment]
Thanks for the feedback! The way to create a flutter web project is now through the `Flutter` project wizard - you can just create a regular flutter project.

**Comment by DhavalRKansara** [comment]
@devoncarew But how I can run a regular flutter project as a web application?

**Comment by devoncarew** [comment]
Many Flutter apps will just run on the web, modulo which plugins are in use. https://flutter.dev/docs/get-started/web has some getting started info.
