### ISSUE TITLE
Dev Flutter/Latest Dart plugin and 2020.1 IntelliJ seems to be awfully "flashy".

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#4478]
## Steps to Reproduce

I was just editing along, and had the feeling that I needed sunglasses. :-)

Each time I type a character, the code flashes between syntax highlighted and fully analyzer highlighted:

![flashy](https://user-images.githubusercontent.com/8867023/79019415-230baf80-7b2b-11ea-8923-6bcad4ad0780.gif)

I've tried uninstalling and re-installing both plugins, clearing cache and restarting, and removed my .dartServer directory and restarted.

## Version info

I'm on the dev channel for the Flutter plugin.  Not sure why `doctor` says I don't have the plugins installed, because I do, the Flutter plugin says it is at 46.0.3-dev.1, and the Dart plugin says it is at 201.6668.124.

```
[✓] Flutter (Channel fix_highlight_mode, v1.18.0-5.0.pre.72, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.18.0-5.0.pre.72 at /Users/gspencer/code/flutter
    • Framework revision a18eb81069 (26 minutes ago), 2020-04-10 12:38:20 -0700
    • Engine revision 9101b63f98
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 114752421d)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gspencer/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/gspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome                    • chrome        • web-javascript • Google Chrome 81.0.4044.92
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by stevemessick** [comment]
Yikes! You've got a lot of highlighting and it really illustrates the problem. I can reproduce it very simply. Create a Flutter app and open main.dart. Scroll down to where it creates the Scaffold. Start typing in a comment (plenty to choose from :) and watch the line `title: Text(widget.title),`. It flashes the most.

If I disable the Flutter plugin it still flashes, so this looks like something that the Dart plugin or IntelliJ is doing for us. @alexander-doroshko have you seen this?

**Comment by gspencergoog** [comment]
I just switched to 2020.1, and didn't notice it before then, so perhaps that's it.

**Comment by alexander-doroshko** [comment]
Thanks, reproduced. Thinking on a fix. Tracked as https://youtrack.jetbrains.com/issue/WEB-44896.

**Comment by alexander-doroshko** [comment]
The issue has been fixed. Dart plugin update with the fix will be available within few days. Thanks for reporting!

**Comment by alexander-doroshko** [comment]
The Dart plugin build with the fix has been published. It's compatible with IDE v 2020.1 and 2020.1.1 Preview. IDE will suggest to update it automatically, or click Help -> Check for Updates.

**Comment by gspencergoog** [comment]
OMG. So. Much. Better.

**Comment by stevemessick** [comment]
Thanks @alexander-doroshko !
