### ISSUE TITLE
Impossibile to open new project

### ISSUE THREAD

**Issue by DAStoica** [flutter/flutter-intellij#4485]
I installed latest version of Android studio and Flutter, I tried to "open new flutter project" but after select nothing happen, it seems like I didn't try to start a new project because doesn't appear an error message. the folder is automatically created but  the window where I should work never opens.
I tried using also a virtual machine and vs code.

**Comment by pq** [comment]
Hi @DAStoica.  Could your run `flutter doctor -v` in a terminal and paste the output?
