### ISSUE TITLE
Using Flutter inspector kills the app

### ISSUE THREAD

**Issue by nknezevicpr** [flutter/flutter-intellij#4487]
## Steps to Reproduce

Precondition: Use android emulator (Android 9, API 28) and flutter inspector in browser

1. Run app from editor (IntelliJ)
2. Open Flutter inspector
3. Click on Select Widget Mode button from inspector
4. Click on any widget in the app you are running on emulator

Actual result: App running process is terminated and app is closed

## Version info

Here's output from flutter doctor

[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-dev.5.0 at /home/radno4/Devel/flutter
    • Framework revision 7f56b53de4 (2 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/radno4/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/radno4/Android/Sdk
    • Java binary at: /home/radno4/newAndroidStudio/android-studio-ide-193.6264773-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.1)
    • Android Studio at /home/radno4/newAndroidStudio/android-studio-ide-193.6264773-linux/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /home/radno4/IntelliJ/ideaIC-2019.1.1/idea-IC-191.6707.61
    • Flutter plugin version 41.0.1
    • Dart plugin version 191.8593

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
Closing as this is likely obsolete. Please re-open if the problem occurs again.
