### ISSUE TITLE
Pubspec.yaml should highlight outdated packages

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter-intellij#4488]
I think it would be nice, if this plugin could highlight all the packages within the pubspec.yaml file that are outdated. This way you don't have to check for new versions via the command line anymore.

Android Studio is already doing it in their gradle files and it feels a bit like a downgrade when you were used to that feature and switch over to flutter and don't have it anymore.

It would also be cool if you could rightclick on the packages and update them automatically.

**Comment by pq** [comment]
See also https://github.com/dart-lang/linter/issues/34 which tracks a lint request for outdated package dependencies.

**Comment by pq** [comment]
/fyi @alexander-doroshko @jwren (as this is really a vanilla Dart Plugin request)

**Comment by lazylazyllama** [comment]
True .. didn't think about this, but yes a dart wide solution would be much better.

**Comment by jwren** [comment]
See the upcoming support for this in https://youtrack.jetbrains.com/issue/WEB-44567, IDEA platform version 2020.1.1.

**Comment by pq** [comment]
Awesome @jwren !!!

**Comment by alexander-doroshko** [comment]
Well, https://youtrack.jetbrains.com/issue/WEB-44567 is not about highlighting, still better than nothing.
