### ISSUE TITLE
Plugin 'flutter' is incompatible with this installation Android Studio 3.6.3 (Windows 10 1909)

### ISSUE THREAD

**Issue by Maxrang** [flutter/flutter-intellij#4490]
I am trying to install flutter and dart into Android studio and for [reasons beyond my comprehension ](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008086019-Android-Studio-Plugins-marketplace-not-working) i cannot use the plugins marketplace online so i have to download the plugins manually by the browser from [the marketplace](https://plugins.jetbrains.com/androidstudio) and add the plugins from disk.

So I've downloaded both flutter and dart zip files versions as following
[Dart: 201.6668.156 ](https://plugins.jetbrains.com/plugin/6351-dart/update/83642)
[Flutter: 45.1.3](https://plugins.jetbrains.com/plugin/9212-flutter/update/83331)

when try to "Install Plugin from disk..." an error message appears stating 
"Plugin 'flutter' is incompatible with this installation"
same issue occurs when installing dart plugin

if they're not compatible then which dart/flutter versions are compatible with the latest android studio version?

This is my Android Studio About 

> Android Studio 3.6.3
> Build #AI-192.7142.36.36.6392135, built on April 14, 2020
> Runtime version: 1.8.0_212-release-1586-b04 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1237M
> Cores: 8
> Registry: documentation.show.toolbar=true, ide.new.welcome.screen.force=true, debugger.watches.in.variables=false
> Non-Bundled Plugins: com.jetbrains.ChooseRuntime, pl.charmas.parcelablegenerator

**Comment by stevemessick** [comment]
Android Studio 3.6.3
Dart plugin 192.7761
Flutter plugin 45.1.1

**Comment by DhaniTrianggara86** [comment]
- Dwonload and update sdk flutter stable  version.

- put sdk flutter in folder android studio.

- update flutter plugin within android studio.
