### ISSUE TITLE
Load .profile on unix - macosx / Or set environment variables

### ISSUE THREAD

**Issue by numito** [flutter/flutter-intellij#4496]
Flutter don't load the .profile, only paths on startup. Therefor when you run flutter doctor from the IDE you have errors, event though it works fine when launched from the terminal.

## Steps to Reproduce

Have multiple JDK and Ruby versions using RVM, and JENV.
Even though you configure all required versions correctly using rvm and jenv, the plugin doesn't load the .profile. So it can't find the correct jdk or ruby version. 
So you have flutter doctor in your terminal that tells you everything is ok and flutter doctor in the ide that tells you cocoapods is not configured, java version is incorrect etc...

## Steps to repair
Load .profile at the beginning of the flutter script. 
The .profile should set correct JDK_HOME, ANDROID_HOME, ruby version etc...

```
. ~/.profile
```

## Version info

Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G4032, locale fr-CH)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31

**Comment by devoncarew** [comment]
We have trouble discovering paths if we're launched in a different shell than the terminal default. You might try starting IntelliJ from the command line and see if that resolves the issue.
