### ISSUE TITLE
Running flutter app in emulator freezes windows

### ISSUE THREAD

**Issue by varunreddy3** [flutter/flutter-intellij#4497]
## Steps to Reproduce

1. Create a sample flutter project in the IDE.
2. Create a virtual device in AVD Manager
![image](https://user-images.githubusercontent.com/45891730/79860903-1417dd80-8406-11ea-8f56-9fa5dda34840.png)
![image](https://user-images.githubusercontent.com/45891730/79861002-3b6eaa80-8406-11ea-955a-c118c2b8d576.png)
![image](https://user-images.githubusercontent.com/45891730/79878923-98775a00-8420-11ea-8d05-c2ced95333b0.png)

3. Run the app on the emulator. Windows Just freezes. Only option left to restart the system using the power button.

4. Just starting the emulator in the AVD Manager takes up lot of time. Below issues are recorded in the event log with running the app. 
`7:30 PM	Emulator: glTexImage2D: got err pre :( 0x502 internal 0x1908 format 0x1908 type 0x1401

7:30 PM	Emulator: glTexImage2D: got err :( 0x502 internal 0x1908 format 0x1908 type 0x1401

7:30 PM	Emulator: glTexImage2D: got err pre :( 0x502 internal 0x1908 format 0x1908 type 0x1401

7:30 PM	Emulator: glTexImage2D: got err :( 0x502 internal 0x1908 format 0x1908 type 0x1401

7:30 PM	Emulator: C:\buildbot\src\android\emu-master-dev\external\qemu\android\android-emugl\host\libs\Translator\GLES_V2\GLESv2Imp.cpp:glPixelStorei:3024 error 0x501

7:30 PM	Emulator: glTexImage2D: got err pre :( 0x502 internal 0x1908 format 0x1908 type 0x1401

7:30 PM	Emulator: C:\buildbot\src\android\e

7:30 PM	Emulator: mu-master-dev\external\qemu\android\android-emugl\host\libs\Translator\GLES_V2\GLESv2I

7:30 PM	Emulator: mp.cpp:glGetAttachedShaders:1763 error 0x501

7:30 PM	Emulator: C:\buildbot\src\android\emu-master-dev\exter

7:30 PM	Emulator: nal\qemu\android\android-emugl\host\libs\Translator\GLES_V2\GLESv2Imp.cpp:glGetAttachedShaders:1763 error 0x501

7:30 PM	Emulator: C:\buildbot\src\android\emu-master-dev\external\qemu\android\android-emugl\host\libs\Translator\GLES_V2\GLESv2Imp.cpp:glDeleteProgram:1220 error 0x501

7:30 PM	Emulator: C:\buildbot\src\android\emu-master-dev\external\qemu\

7:30 PM	Emulator: android\android-emugl\host\libs\Translator\GLES_V2\GLESv2Imp.cpp:glDeleteProgram:1220 error 0x501

7:46 PM	Emulator: Process finished with exit code 0

7:48 PM	Emulator: emulator: ERROR: VkCommonOperations.cpp:496: Failed to create Vulkan instance.

7:51 PM	Emulator: emulator: INFO: QtLogger.cpp:68: Critical: Uncaught TypeError: Cannot read property 'update' of undefined (qrc:/html/js/common.js:130, (null))

7:53 PM	Emulator: emulator: ERROR: AdbHostServer.cpp:83: adb protocol fault (couldn't read status len

7:53 PM	Emulator: gth)

8:27 PM	Emulator: emulator: ERROR: detected a hanging thread 'QEMU2 CPU0 thread'. No response for 15153 ms

8:30 PM	Emulator: emulator: ERROR: detected a hanging thread 'QEMU2 CPU0 thread'. No response for 15001 ms

10:37 PM	Emulator: Process finished with exit code 255`

5. Trying to run the app just freezes whole windows and need to power cycle
6. SDK versions
![image](https://user-images.githubusercontent.com/45891730/79862764-2a736880-8409-11ea-9482-022e0e257698.png)

## Version info

[√] Flutter (Channel master, v1.18.0-6.0.pre.82, on Microsoft Windows [Version 10.0.17763.1098], locale en-US)
    • Flutter version 1.18.0-6.0.pre.82 at C:\src\flutter
    • Framework revision f35b673f2b (3 days ago), 2020-04-19 02:45:01 +0530
    • Engine revision a5e0b2f2f2
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 5b19445d9c)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.4.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.4.29806.167

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.1)
    • VS Code at C:\Users\527980\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • Windows                   • Windows       • windows-x64 • Microsoft Windows [Version 10.0.17763.1098]

• No issues found!

**Comment by AyushAgrawal25** [comment]
I am also having the same problem.

**Comment by firestormza** [comment]
Having the same issue. Where do I find the log files?

**Comment by firestormza** [comment]
> Having the same issue. Where do I find the log files?

Got it sorted out.  I deleted the /.dart_tool, /.idea and /build (everything inside) folders from my project directory and everything started working again.

**Comment by adityasreebysani** [comment]
I observed it to happen when gradle updates to a new version. Deleting the project build folder solves the issue.

**Comment by sohelakhtar23** [comment]
Having similar kind of problem
I dont know why its happening but i guess after an update it is causing

**Comment by pq** [comment]
@stevemessick: do you know if this is an ongoing issue?

**Comment by stevemessick** [comment]
@pq I don't know. It sounds like a problem with Flutter upgrading and not clearing its cache. Doesn't sound like an IDE issue.

**Comment by pq** [comment]
Got it.  Thanks.

@sohelakhtar23, @adityasreebysani, @firestormza: are any of you still seeing this?

**Comment by firestormza** [comment]
I've only had the problem once.

**Comment by adityasreebysani** [comment]
No I haven't faced the problem in recent times. However, lately I have
started using VS Code and I am no longer using Android Studio due to
general performance issues.

So not sure if the problem was in IDE or Flutter.

**Comment by Muhammadwahab** [comment]
I am facing smilar issue unable to run app on emulator screen is freez after run the project i am using latest fluttersdk
