### ISSUE TITLE
Spell Check does not work on string literals

### ISSUE THREAD

**Issue by rmargolinross** [flutter/flutter-intellij#4498]
## Steps to Reproduce

Create a new dart file, and then a stateless widget with a centered text element. For the string put a typo in the literal. It does not get marked as a typo.

## Version info

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/rmargolinross/dev/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/rmargolinross/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • sdk gphone x86 • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • iPhone         • 07da1517197bd6155d47de15a47759f492e42c8d • ios         • iOS 13.1.3

**Comment by pq** [comment]
Thanks for the feedback.  @alexander-doroshko, @jwren: I'm guessing this would best be tracked on the Dart Plugin (if it's not already?)

**Comment by alexander-doroshko** [comment]
This has been [fixed recently](https://youtrack.jetbrains.com/issue/WEB-34709) in the Dart plugin compatible with IntelliJ IDEA 2020.1. I think we can backport the fix to the version compatible with Android Studio 3.6.

**Comment by pq** [comment]
Super.  Thanks @alexander-doroshko!

**Comment by rmargolinross** [comment]
Yes, thank you @alexander-doroshko !
