### ISSUE TITLE
[question] How setup IntelliJ IDEA to develop and run run (test) this project?

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter-intellij#4501]
I want to know do I configure my enviroment to run this project on my machine for development purpose.

I get it and when I open it says:

`Run Configuration Error: No SDK specified for plugin module 'flutter-intellij'`

**Comment by pq** [comment]
Hi @pedromassango!  Thanks for the interest...  Are you still trying to get this to work?

Did you try the updated instructions in https://github.com/flutter/flutter-intellij/blob/master/CONTRIBUTING.md?

**Comment by pedromassango** [comment]
Yes. I actualy didn't tried these instructions. I will try it today. Thanks.

**Comment by pq** [comment]
Good deal.  @helin24 just went through this so may be able to advise.

**Comment by pedromassango** [comment]
I tried to follow the steps but it is not very clear. And after all the steps when I run a new instance of IntelliJ with the Flutter plugin it does not recognize .dart files and I already did all the steps.

**Comment by pq** [comment]
Sorry to hear that.

@helin24: any advice?

**Comment by helin24** [comment]
@pedromassango thanks for trying the steps - if there were any particular steps that were confusing as you tried to execute them, let me know and I can try to clarify them in our doc.

In your new instance of IntelliJ, can you post what your preferences for plugins looks like? e.g. this is mine:
![screenshot result](https://user-images.githubusercontent.com/6379305/85065201-a10ab900-b161-11ea-9090-b832662822dc.jpg)

And also what you have for Dart language support? e.g.:
![Screen Shot 2020-06-18 at 12 29 11 PM](https://user-images.githubusercontent.com/6379305/85064022-d1515800-b15f-11ea-90ee-6dadd90abcf4.jpg)

**Comment by stevemessick** [comment]
The Dart plugin needs to be installed in the IDE you use for editing the Flutter plugin. Yeah, it is confusing but there isn't really a good vocabulary for this topic.

The installation instructions in CONTRIBUTING.md have recently been updated for IntelliJ 2020.3 and Java 11.
