### ISSUE TITLE
error: Undefined name 'Brightness'.       error: Undefined name 'TextAlign'. 

### ISSUE THREAD

**Issue by clinicialtoy** [flutter/flutter-intellij#4504]
error: Undefined name 'Brightness'.       
error: Undefined name 'TextAlign'. 

![image](https://user-images.githubusercontent.com/63962253/80214931-3d3aa700-866e-11ea-9c06-e942006de6fd.png)

![image](https://user-images.githubusercontent.com/63962253/80215008-56dbee80-866e-11ea-96a1-c50ccfa6d424.png)

![image](https://user-images.githubusercontent.com/63962253/80215090-77a44400-866e-11ea-8788-11f2c52622ea.png)

![image](https://user-images.githubusercontent.com/63962253/80215144-8ee33180-866e-11ea-8a8d-7f8231247c80.png)

![image](https://user-images.githubusercontent.com/63962253/80215194-a15d6b00-866e-11ea-972b-0479f0dc34cd.png)

**Comment by devoncarew** [comment]
What version of the Flutter SDK are you using? If the analyzer is able to resolve TextField, it should be able to resolve TextAlign. Are you importing material? `import 'package:flutter/material.dart';`
