### ISSUE TITLE
Attach to custom embedder running

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter-intellij#4506]
I'm writing a plugin for a [custom embedder](https://github.com/go-flutter-desktop/go-flutter) and I need the flutter plugin to attach to my running flutter app. I get the observatory URI and all necessary parameters to generate a command line attach (`sdkFields.createFlutterSdkAttachCommand`: `/home/jld3103/flutter/bin/flutter --no-color attach --machine --device-id=flutter-tester --debug-uri=http://127.0.0.1:50300/ lib/main_desktop.dart`). 
 That command works when I run it in the console.  
In the plugin I use some code derived from [this](https://github.com/flutter/flutter-intellij/blob/f429dea3134a4f046776ac796c2c75641b1f938a/src/io/flutter/actions/AttachDebuggerAction.java#L82-L117).
It gives me a dialog saying that no device was found.

So my question is how to attach the flutter plugin from another plugin to a flutter app running a custom embedder?

**Comment by jld3103** [comment]
This seems to be resolved. I don't know how, but I updated IntelliJ and the Dart plugin and now it works.

**Comment by pq** [comment]
@devoncarew: any thoughts?

**Comment by pq** [comment]
@devoncarew: any ideas on this one?

**Comment by jacob314** [comment]
Supporting Why is the device-id flutter-tester? If you can make your device show up like a regular flutter desktop device that might be a better path to integration with the intellij plugin.

**Comment by jld3103** [comment]
Sounds good, but is there a way to do it?

**Comment by stevemessick** [comment]
Flutter 2.0 has native desktop support.

**Comment by jld3103** [comment]
This was a feature request for custom embedders and not the official ones. They obviously work, but there is (maybe was didn't check recently) no way to attach to a custom embedder...

**Comment by stevemessick** [comment]
We would be happy to review a PR if you find a solution that requires changing the Flutter plugin. Another possibility might be to check (or modify) the flutter_tools project in the Flutter repo.
