### ISSUE TITLE
New templates should include the cupertino_icons: ^0.1.3

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#4514]
When I create a new project the `pubspec.yaml` comes with `cupertino_icons: ^0.1.2` instead of the `cupertino_icons: ^0.1.3`.

**Comment by Amitbhave** [comment]
Can I take a look at this?

**Comment by Amitbhave** [comment]
Have created a PR. Still as per pubspec, ^0.1.2 will also pick latest version till version 0.2.0 right?

**Comment by devoncarew** [comment]
Is this two separate issues? @feinstein, does the new project template for `flutter create` need to be updated? It may already be on the latest in master: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/pubspec.yaml.tmpl#L41

@Amitbhave, we might need to update our icon previews in IntelliJ if the underlying packages have rev'd.

**Comment by feinstein** [comment]
@devoncarew why 2 issues?

It appears to be already updated in master indeed so I am going to close this.

**Comment by Amitbhave** [comment]
@devoncarew in the IconGenerator's pubspec.yaml right? Can you review the PR?

**Comment by devoncarew** [comment]
@feinstein - thanks for the report.

@Amitbhave - that's the right location for sure, but after that change you need to re-run the icon generator. That's a Flutter app that runs on an iOS simulator, a generally produces a large commit. I'm going to run that myself locally, but thanks for the contribution!

**Comment by Amitbhave** [comment]
@devoncarew oh, okay unfortunately I have windows machine, so no ios simulator..
