### ISSUE TITLE
support expression evaluation for Flutter web apps

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4519]
This is a tracking issue to support expression evaluation for Flutter web apps.

**Comment by annagrin** [comment]
Expression evaluation should work properly in IntelliJ (with --enable-web-expression-evaluation flag for flutter) after the following PR merges:

https://github.com/flutter/flutter/pull/56958

**Comment by annagrin** [comment]
@devoncarew the PR above has merged, is this enough to close this issue?

**Comment by devoncarew** [comment]
Yup, I think we can consider this complete now.

**Comment by Freundschaft** [comment]
im not sure if I completely understand how to use the --enable-web-expression-evaluation flag, how do I configure it in Android Studio?

**Comment by devoncarew** [comment]
Sure, there are two things you need to do:
- enable flutter web on the master, dev, and beta channels: https://flutter.dev/docs/get-started/web#set-up
- when running an app, run with the `--enable-web-expression-evaluation` flag to `flutter run`; In IntelliJ, this can be passed in in the run/debug launch configuration dialog

<img width="342" alt="Screen Shot 2020-05-26 at 8 20 47 AM" src="https://user-images.githubusercontent.com/1269969/82918648-e0126980-9f29-11ea-86d4-2358108b0fe7.png">

**Comment by Freundschaft** [comment]
thats what I tried, but I get

> Could not find an option named "enable-web-expression-evaluation".
> 
> Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

this is my config

![image](https://user-images.githubusercontent.com/5065616/82919174-f9d99e00-9f75-11ea-8048-4096eff8c5e5.png)

**Comment by devoncarew** [comment]
Ah, it should be `--web-enable-expression-evaluation` (not `--enable-web-expression-evaluation`); I'll update the instructions above.

**Comment by Freundschaft** [comment]
perfect, works now, thanks!

**Comment by stuz5000** [comment]
Any reason why this isn't the default. Hands up who debugs their web apps?

**Comment by annagrin** [comment]
We had to work out a few bugs before making it default. It should be default now in flutter master channel.
