### ISSUE TITLE
There is a bug for "Flutter attach" button. It can't work with flavor param.

### ISSUE THREAD

**Issue by xingchenxuanfeng** [flutter/flutter-intellij#4521]
## Steps to Reproduce

There is a bug for "Flutter attach" button.

When i set the "Build flavor" in "Run/Debug Configurations" window, the "Flutter attach" button can't work.

After click the button, IDE print 
"Could not find an option named "flavor".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
" .

Flavor param is necessary for my project, without it I can't compile my project.
However, the "Flutter attach" button can't work with flavor param .
It's a conflict，and annoying！
![image](https://user-images.githubusercontent.com/7694736/80559428-0d91f300-8a10-11ea-8e83-d9f4f60385ad.png)

## Version info

[✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/xc/project/FlutterProject/kl-flutter-biz/.flutter
    • Framework revision 0b8abb4724 (3 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/xc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/xc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.31

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • MIX 2      • 56e9c1db   • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by stevemessick** [comment]
There are many articles about using flavors with Flutter.
https://flutter.dev/docs/deployment/flavors

I don't know when the option was added but I suspect it was in a later version of the Flutter SDK than you have. Try upgrading, or switching to another channel.

I'm closing this since it isn't an IDE issue.

**Comment by acoutts** [comment]
Did you ever find the solution to this? I found a bug in vscode which produces this error, I wonder if something similar is in Intellij too: https://github.com/Dart-Code/Dart-Code/issues/2525

**Comment by Jemshi101** [comment]
Im also having the same issue. My flutter sdk is the latest Master as of today.

**Comment by imReker** [comment]
@stevemessick Why close this with a useless doc link? This is a bug, and it still exists in master channel of SDK and latest Intellij plugin.
