### ISSUE TITLE
Flutter / Dart plugin not installed

### ISSUE THREAD

**Issue by galen211** [flutter/flutter-intellij#4523]
The flutter and dart plugins for Intellij Ultimate 2020.1 are not working.  Flutter doctor does not recognize the plugins as being installed.

## Steps to Reproduce
1. Ran [common workarounds](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues)
2. Uninstalled the flutter and dart intellij plugin
3. Ran flutter upgrade
4. Re-installed the flutter and dart intellij plugin
5. In preferences -> plugins, the below are listed as installed and enabled:
`Dart 201.7223.43`
`Flutter 45.1.3`

## Version info
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/galen/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/galen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
Process finished with exit code 0
```

**Comment by pq** [comment]
I can confirm that `flutter doctor` isn't reporting correctly on Ultimate 2020.1 despite the plugins being installed.

![image](https://user-images.githubusercontent.com/67586/80816633-b5c8c880-8b84-11ea-8341-6937a0d2aa22.png)

Server is working for me though.

**Comment by galen211** [comment]
I'm a bit confused because code completion is cutting in and out.  Not sure if this is an intellij issue, but it's baffling:

<img width="657" alt="Screen Shot 2020-05-02 at 3 19 21 PM" src="https://user-images.githubusercontent.com/4350963/80875409-c498a380-8c88-11ea-9bae-c1b322f9cc89.png">

**Comment by alaadahmed** [comment]
I have the same issue, Flutter plugin and Dart plugin both are installed on Intellij 2020.1.1 (Ultimate Edition) and `flutter doctor` reports that they are not installed.

**Comment by KasunHasanga** [comment]
![Screenshot from 2020-10-17 00-28-07](https://user-images.githubusercontent.com/44415252/96299806-3b94df00-1012-11eb-80e7-fe5620c359c5.png)

I have Got the Same Question after updating the android studio to version 4.1. How to resolve it

**Comment by wisnuwijo** [comment]
> ![Screenshot from 2020-10-17 00-28-07](https://user-images.githubusercontent.com/44415252/96299806-3b94df00-1012-11eb-80e7-fe5620c359c5.png)
> 
> I have Got the Same Question after updating the android studio to version 4.1. How to resolve it

same here, did anyone managed to solve it?

**Comment by lcortier** [comment]
Same here, with all the latest versions on OSes without previous installs of flutter, Android Studio and Android SDK on both Windows 10 and OS X Catalina 10.15.7
<img width="743" alt="Screenshot 2020-10-23 073209" src="https://user-images.githubusercontent.com/85623/96960170-f8e77100-1501-11eb-8943-66ba6760ec6c.png">

**Comment by wilburlua910** [comment]
Same issues here, using Android Studio 4.1.0. 
![image](https://user-images.githubusercontent.com/25751618/97004217-4f3ec900-156f-11eb-939c-64a1cf8489dd.png)
![image](https://user-images.githubusercontent.com/25751618/97004303-75fcff80-156f-11eb-9690-4f3a31f8f594.png)

**Comment by epetrenko** [comment]
Same issue here on Windows 10 with Android Studio 4.1.

**Comment by edmundbuzor** [comment]
Same Issues here with Windows 10 and Android studio latest update 4.1. Any solutions so far?

**Comment by mstrkn** [comment]
Same issue on Windows 10 just after the upgrade to Android 4.1

**Comment by mstrkn** [comment]
Same issue on Windows 10 just after the upgrade to Android Studio 4.1

**Comment by brandnewx** [comment]
![2020-10-26 09_57_33-PhsarMessenger – main dart  PhsarMessenger  Android Studio](https://user-images.githubusercontent.com/7624681/97129548-b62bd000-1771-11eb-867b-1fed3e756452.png)

I have this exact issue with Android Studio 4.1 too. I also can't attach Flutter to running process on phone.

**Comment by lcortier** [comment]
> ![2020-10-26 09_59_11-PhsarMessenger – main dart PhsarMessenger Android Studio]
> 
> I have this exact issue with Android Studio 4.1 too. I also can't attach Flutter to running process on phone.
Your issue is the Android SDK isn't properly installed.

In my case, both on macOS and Windows 10, the Flutter and Dart plugin not installed message from flutter doctor -v doesn't stop me from building flutter apps nor running them on the emulators or stimulators from VS Code.

**Comment by lcortier** [comment]
I believe this issue is a bug in flutter doctor, as it is platform independent.

Do you guys actually use Android Studio to compile and run your flutter apps ? Does it work for you as it does for me in VS Code ?

**Comment by brandnewx** [comment]
> @brandnewx
> 
> > I have this exact issue with Android Studio 4.1 too. I also can't attach Flutter to running process on phone.
> 
> Your issue is the Android SDK isn't properly installed.
> 
> In my case, both on macOS and Windows 10, the Flutter and Dart plugin not installed message from flutter doctor -v doesn't stop me from building flutter apps nor running them on the emulators or stimulators from VS Code.

I'm running and debugging Flutter with IntelliJ just fine, on the same computer. This bug is in Flutter or Dart plugins for Android Studio 4.1.

**Comment by zywj** [comment]
I have the same issue.
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1016], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.50.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)
```

**Comment by dumuller** [comment]
I have the same issue after update Android Studio 4.1. Have solution a problem?

**Comment by prashantdwivedi** [comment]
I have the same issue. `flutter doctor -v` does not find the plugin installed on an android studio.
![image](https://user-images.githubusercontent.com/6306052/97412942-38f68b80-1928-11eb-843f-7d8826588c1c.png)

**Comment by mrxiruo** [comment]
For Android Studio 4.1+，It is in a different directory now, I solved by this command:

ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

**Comment by mrxiruo** [comment]
For Android Studio 4.1+，It is in a different directory now, I solved by this command:

ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

**Comment by prashantdwivedi** [comment]
> For Android Studio 4.1+，It is in a different directory now, I solved by this command:
> 
> ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

that directory you mention not show 👎

**Comment by Islamdiab** [comment]
> For Android Studio 4.1+，It is in a different directory now, I solved by this command:
> 
> ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

it works brilliantly, Thank you so much 👍

**Comment by chanchanbn** [comment]
> For Android Studio 4.1+，It is in a different directory now, I solved by this command:
> 
> ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

It works. Thank you 👍

**Comment by Symyon** [comment]
Flutter Dev channel has fixed this issue, not yet in stable though. You can switch to Dev for now:
`flutter channel beta`
`flutter upgrade`
That will work for Windows too (as the above solution is for MacOS).

Taken from here: https://stackoverflow.com/a/64417280/503226

**Comment by gusta-of** [comment]
> Flutter Dev channel has fixed this issue, not yet in stable though. You can switch to Dev for now:
> `flutter channel beta`
> `flutter upgrade`
> That will work for Windows too (as the above solution is for MacOS).
> 
> Taken from here: https://stackoverflow.com/a/64417280/503226

- This solution worked for me also on windows, thank you very much

**Comment by menaayoub** [comment]
Safe fix for MacOs (Android studio 4.1+) It is in a different directory now, but symlink helps.

Just run in the Terminal this command

ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

**Comment by AuthenticPerception** [comment]
> For Android Studio 4.1+，It is in a different directory now, I solved by this command:
> 
> ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

I'm very new to all of this and I dont understand what i'm suppose to do execute this. Can you tell exactly how I'm suppose to do it? Sorry for the noob question.

**Comment by sbkatn22** [comment]
> > For Android Studio 4.1+，It is in a different directory now, I solved by this command:
> > ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1
> 
> I'm very new to all of this and I dont understand what i'm suppose to do execute this. Can you tell exactly how I'm suppose to do it? Sorry for the noob question.

I am new to this as well and I am unsure what to do with this. I tried copying and pasting it to the local terminal in Android Studio, but then this error showed up: '-s' is not recognized as an internal or external command, operable program or batch file.

The same error showed up in my Command Prompt

**Comment by irawanDB** [comment]
> 
> 
> Flutter Dev channel has fixed this issue, not yet in stable though. You can switch to Dev for now:
> `flutter channel beta`
> `flutter upgrade`
> That will work for Windows too (as the above solution is for MacOS).
> 
> Taken from here: https://stackoverflow.com/a/64417280/503226

this work for me on Windows 10 too.
Thank you so much

**Comment by iamthenewking** [comment]
> Flutter Dev channel has fixed this issue, not yet in stable though. You can switch to Dev for now:
> `flutter channel beta`
> `flutter upgrade`
> That will work for Windows too (as the above solution is for MacOS).
> 
> Taken from here: https://stackoverflow.com/a/64417280/503226

this also works for me

**Comment by serwer20** [comment]
> Flutter Dev channel has fixed this issue, not yet in stable though. You can switch to Dev for now:
> `flutter channel beta`
> `flutter upgrade`
> That will work for Windows too (as the above solution is for MacOS).
> 
> Taken from here: https://stackoverflow.com/a/64417280/503226

Works for me too [Windows 10 Pro x64] [AMD] Thanks!
