### ISSUE TITLE
IntelliJ shows different output than flutter analyze

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter-intellij#4529]
Exclude from `analysis_options.yaml`:
```yaml
analyzer:
  errors:
    ...
  exclude:
    - lib/generated/**

linter:
  rules:
    ...
```

Dart Analysis window from Android Studio:
![image](https://user-images.githubusercontent.com/2807712/81074456-4d157f00-8ee9-11ea-805a-3e38908f6db5.png)

Output from `flutter analyze`:
```
Analyzing <elided>...
No issues found! (ran in 17.1s)
```

## Version info

```
[✓] Flutter (Channel master, 1.18.0-9.0.pre.122, on Microsoft Windows [VersiÃ³n 10.0.19041.208], locale es-ES)
    • Flutter version 1.18.0-9.0.pre.122 at C:\flutter
    • Framework revision 9a99403ad2 (11 hours ago), 2020-05-04 22:29:02 -0400
    • Engine revision 95ecd9a405
    • Dart version 2.9.0 (build 2.9.0-5.0.dev e7bebea059)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\crist\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1-dev.4
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Connected device (3 available)
    • Pixel 3 XL • 192.168.1.33:5555 • android-arm64  • Android 10 (API 29)
    • Web Server • web-server        • web-javascript • Flutter Tools
    • Chrome     • chrome            • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
```

**Comment by stevemessick** [comment]
Thanks for using the Flutter dev channel!

Is it possible you are using a different Flutter SDK in the IDE than in the command line?

It looks like your analysis options file is being ignored. @bwilkerson do you have any ideas what might be going on?

**Comment by Zazo032** [comment]
I only have a Flutter version located at `C:\flutter`, as stated in `flutter doctor` output. The output in the `Dart Analysis` tab sometimes is missing until I open a file from the ignored directory. My `analysis_option.yaml` file is working as those warnings in the IDE are because of some rules I specified. I can paste the full file here in case it's needed. The part that is being ignored is the `analyzer > exclude` one, I tried different formats just in case that was the cause, but `Dart Analysis` keeps reporting them.

**Comment by stevemessick** [comment]
@stereotype441 Do you have any idea what's wrong here?

**Comment by bwilkerson** [comment]
Sorry, I missed the earlier ping.

> ... until I open a file from the ignored directory.

This sounds like a longstanding bug. When an ignored file is opened it is analyzed as if it hadn't been ignored, and server sends the analysis results to the client. Server either needs to not do that, or it needs to send updated information to the client to remove the results when the file is closed. But at the moment it doesn't do either one.

You should be able to work around it by restarting the analysis server after the file is closed. If that doesn't work, please let us know because it might be a different issue than the one we're aware of.

**Comment by stevemessick** [comment]
Thanks! I'll close this since it is an analyzer issue.

Any follow up should be in the dartlang/sdk repo.
