### ISSUE TITLE
Failed to extract manifest from APK: ProcessException: The command failed

### ISSUE THREAD

**Issue by mahatodebashish** [flutter/flutter-intellij#4531]
Launching lib\main.dart on SM J710FN in debug mode...
Failed to extract manifest from APK: ProcessException: The command failed
  Command: C:/Users/Debashish/AppData/Local/Android/sdk\build-tools\29.0.0\aapt dump xmltree E:\Android\FlutterApps\alertu\build\app\outputs\apk\app.apk AndroidManifest.xml.
No application found for TargetPlatform.android_arm.
Is your project missing an android\app\src\main\AndroidManifest.xml?
Consider running "flutter create ." to create one.

**Comment by kenzieschmoll** [comment]
@stevemessick does this look like a Flutter issue or a plugin issue?

**Comment by stevemessick** [comment]
That looks like the output of launching a run config. The plugin uses the Flutter command line tool to do that. I'd guess this is a tool issue. The way to confirm that is to verify that using the command line tool to run the app causes the same problem.

**Comment by mahatodebashish** [comment]
@kenzieschmoll @stevemessick  Thanks for your input . It was merely due Android Q ( 10 ) SDK. I just removed it . Hence closing this..

**Comment by sayan-dot** [comment]
hy can you tell me how did you solved this i am currently facing the same issue
