### ISSUE TITLE
Develop Flutter plugin with Android code in single window

### ISSUE THREAD

**Issue by markfili** [flutter/flutter-intellij#4536]
Hello,
it is already possible to create a Flutter Plugin in Android Studio by using one window for Flutter/root project and the other for the Android part of the plugin, but can someone please confirm that this setup below enables you to edit both in the same window?

### 1. Import project
a) from Git repository

 - open File -> New -> Project from version control -> Git
 - paste your git project link and confirm

b) from local existing project

 - open File -> New -> Import project
 - find your project and confirm

### 2. Import options
 - If asked to "Create Android Studio project?" -> click Yes
 - Select "Import project from external model" -> select "Gradle"

### 4. Fetch Flutter dependencies
 - Run "flutter pub get" in terminal or click on "Get dependencies" in Android Studio as many times as it requires

### 5. Setup Android SDK and dependencies
 - Go to folder "/example/android/" -> right click on "build.gradle" -> select "Import Gradle project"

### 6. Run project
 - green arrow
 - or run configuration with "example/lib/main.dart" as entry point

**Comment by kenzieschmoll** [comment]
@stevemessick do you have some insight here?

**Comment by stevemessick** [comment]
In the settings/preferences for the Flutter plugin there is an experimental option to enable code completion, etc for Java and Kotlin. That's what you need to do everything in a single window.

**Comment by markfili** [comment]
now that seems much better than what I went through. ok, thank you all!
