### ISSUE TITLE
Why the widget tree shows widgets of previous pages ? How can I disable it.

### ISSUE THREAD

**Issue by wull8** [flutter/flutter-intellij#4538]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
1. Launch the main page, the widget tree shows the widgets of main page
2. Navigate to other pages of the app, the widget tree still shows widgets of main page

How can I disable that ?

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by kenzieschmoll** [comment]
If you click the "Refresh Widget Info" button in the Inspector, the widget tree will refresh with the widgets currently on screen.

**Comment by wull8** [comment]
@kenzieschmoll 

Thanks for the information.  "Refresh Widget Info" does give me the widgets tree of current page, but the problem is that it also shows the widget tree of last page.  It looks like the widget tree caches the all widgets in the "page stack".

Example: My application has two pages, one is the main page, another one is a child page which I can jump to via clicking a button on the main page. And on the child page, I can return back to main page by clicking the navigation back button on the AppBar.

When I launch the app and open the main page, the widget tree displays the widgets defined for main page.  When I jumps to the child page and clicks the "Refresh Widget Info", the widget tree shows widgets defined for both main page and child page.   And I want the widget tree to be truly real-time, without caching the widgets of last pages from where I could navigate to current page.

Thanks
