### ISSUE TITLE
A blank window is displayed when creating a new project

### ISSUE THREAD

**Issue by vvVenom** [flutter/flutter-intellij#4539]
## Steps to Reproduce

When I select the Flutter tab from `File-> New-> Project`, it shows blank

![image](https://user-images.githubusercontent.com/58068445/81471749-f4feb580-9225-11ea-8bbf-7257cf332f62.png)
And I asked my friend, it's the same version of intellij as me, also has this problem.

## Version info

[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.19.0-0.0.pre at /Users/dracula/Library/Android/sdk/flutter
    • Framework revision a849daf283 (33 hours ago), 2020-05-07 18:59:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/dracula/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/dracula/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 4.1
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.1 Preview.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • E45B52B2-E55F-44A6-82C4-DFC97E474D54 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
WAI. Adjust the path to the Flutter SDK, if needed, and click `Next`.

**Comment by vvVenom** [comment]
> WAI. Adjust the path to the Flutter SDK, if needed, and click `Next`.

Sorry for the delay. Yes, the correct sdk path is also blank, because the above picture is actually someone else's, now I provide you with my intellij look
![image](https://user-images.githubusercontent.com/58068445/82582366-85dd7580-9bc4-11ea-986d-8cd9a9342bca.png)
