### ISSUE TITLE
Would be nice to see icons in autocomplete

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#454]
I don't know if this is even possible in IntelliJ, but in Atom we implemented our dartdocs for Material Icons such that they would show up in autocomplete:

<img width="561" alt="screen shot 2016-11-17 at 1 23 37 pm" src="https://cloud.githubusercontent.com/assets/11857803/20408178/29dd971c-acc9-11e6-9adb-7fbe22c9a853.png">

If it's easy to bring that back in IntelliJ would be nice.

**Comment by eseidelGoogle** [comment]
IntelliJ looks like this:
<img width="700" alt="screen shot 2016-11-17 at 1 26 23 pm" src="https://cloud.githubusercontent.com/assets/11857803/20408247/7768b958-acc9-11e6-9efe-9e307d184d6d.png">

**Comment by alexander-doroshko** [comment]
Technically it is possible because lookup element rendering is fully customizable by calling  `lookup.withRenderer()` in `DartServerCompletionContributor#createLookupElement`.

**Comment by pq** [comment]
Proposed fix in flight: https://github.com/JetBrains/intellij-plugins/pull/563

![image](https://user-images.githubusercontent.com/67586/35770737-a9c62d90-08d5-11e8-8e64-39f61fff3be1.png)

Adds colors too!

![image](https://user-images.githubusercontent.com/67586/35770734-9cac93e2-08d5-11e8-847b-bf4a7a303474.png)

👍

**Comment by pq** [comment]
Update: this fix won't land as is.  The plan moving forward is to contribute this functionality via a new extension point in the Dart Plugin.  Once the new extension gets back-ported to a 171-compatible plugin, we're good to proceed. 👍 

Back-porting tracked: https://github.com/flutter/flutter-intellij/issues/1747.

**Comment by pq** [comment]
New API has landed in 173.* and I've got it working locally.  Cheers @alexander-doroshko!

![image](https://user-images.githubusercontent.com/67586/37730266-80773e34-2cfc-11e8-8af1-33a5a5c1b39a.png)

![image](https://user-images.githubusercontent.com/67586/37730277-890b7376-2cfc-11e8-949c-9c500aa1a996.png)

Need to puzzle through a back-port of the extension point API but once we do, this should be available for 173-based IDEAs and up. 👍
