### ISSUE TITLE
Device explorer for android is not available in flutter project

### ISSUE THREAD

**Issue by InvertedX** [flutter/flutter-intellij#4542]
Device explorer in android studio is pretty good for viewing file system. 
but if we open flutter in android studio, it wont give us option to open device explorer

**Comment by stevemessick** [comment]
It works for me. Perhaps it got removed from the sidebar. Did you try the menu
 `View > Tool Windows > Device File Explorer`?

**Comment by InvertedX** [comment]
no. if the project is flutter based studio wont show `Device File Explorer` option 

![image](https://user-images.githubusercontent.com/6897265/82243427-35b0aa00-995d-11ea-81a5-82e5cc0f2378.png)

**Comment by stevemessick** [comment]
Your `Tool Windows` menu doesn't show Logcat or Build Variants either. I don't see any Android Studio tool windows.

I wonder if something is wrong with your project metadata. Here's something to try:
- Make a backup of your entire project
- Shut down Android Studio
- Delete the `android` and `.android` directories from your project (whichever you have)
- Open a terminal emulator and navigate to the directory containing your project
- Do `ls` in the terminal and confirm that `<project_name>` is listed
- Do `flutter create <project_name>` in the terminal
- Restart Android Studio and re-open the project

To be clear, when I open a Flutter project in Android Studio I see all the Android tools listed in the `Tool Windows` menu.

**Comment by InvertedX** [comment]
Seems like this happens only for older projects, i created a new project and itseems working fine.. i tried deleting .idea folder in older projects but that didn't worked either

**Comment by stevemessick** [comment]
The procedure I outlined is supposed to convert an old project to the new format.

**Comment by AntonyLeons** [comment]
This is better resolved by pressing configure in event log when android framework is detected. This should be in documentation.
