### ISSUE TITLE
Absolute import path generates if long subfolder hierarchy

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter-intellij#4551]
![image](https://user-images.githubusercontent.com/12999702/82116357-dd698480-9771-11ea-81d1-4a860c6b8236.png)

## Steps to Reproduce

1. Create a new project.
2. Create 'widgets' folder and any subfolder like 'auth'.
3. Create a dart file inside this folder with some classes.
4. Mention these classes in another dart file and press 'Enter'. It should auto-generate an 'import' line.

**Expected results:** 
Project relative path generated:
import 'package:chatapp/widgets/auth/auth_form.dart';

**Actual results:**
Absolute disk path generated:
import 'file:///D:/Flutter/chat_app/lib/widgets/auth/auth_form.dart';

Obviously if you move your project to the other folder this path would be wrong. Thus it's not a appropriate behaviour.

**Comment by DanTup** [comment]
If IntelliJ handles this the same as VS Code, this is likely coming from the analysis server. (@bwilkerson @scheglov)

**Comment by bwilkerson** [comment]
Yes, this looks like an issue in the analysis server. Please move this issue to the sdk repository.
