### ISSUE TITLE
A blank window is displayed when creating a new project

### ISSUE THREAD

**Issue by vvVenom** [flutter/flutter-intellij#4563]
Supplement to closed issues: https://github.com/flutter/flutter-intellij/issues/4539
**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Android Studio
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.45.0)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

```
In fact, I have installed the flutter intellij plugin, but no matter how many times I restart and reinstall, the doctor fails to check, and the new window is blank
![image](https://user-images.githubusercontent.com/58068445/82582621-ed93c080-9bc4-11ea-9fe7-d916d34bb7b4.png)
![image](https://user-images.githubusercontent.com/58068445/82583609-d5707100-9bc5-11ea-8ba9-32cdf845373b.png)

**Comment by stevemessick** [comment]
The window isn't blank. Click Next.
