### ISSUE TITLE
How to create flutter module in intellij idea?

### ISSUE THREAD

**Issue by vvVenom** [flutter/flutter-intellij#4565]
Like:
![image](https://user-images.githubusercontent.com/58068445/82628208-d97cad00-9c1e-11ea-873b-59bf57bae9ab.png)
But there are only three options in intellij idea:
![image](https://user-images.githubusercontent.com/58068445/82628310-134db380-9c1f-11ea-9a75-c7d151fd0fe2.png)

**Comment by stevemessick** [comment]
Right, modules are not supported in IntelliJ.
