### ISSUE TITLE
Whitespace trailing - whitespace automatic deletion on SAVE TURN OFF

### ISSUE THREAD

**Issue by brobee** [flutter/flutter-intellij#4570]
## Steps to Reproduce

I'm unable to turn of whitespace trailing, or white space deletion on SAVE. Everything is turned off in android studio, but your plugin just continuously bothering, annoying me with this stupid feature.

It's supposed to be TURNED OFF by default, or enable to configure this STUPID feature.

## Version info
LATEST.

**Comment by brobee** [comment]
Oh Intellij support is telling me, it's turned off, nothing to do there, so obviously it's plugin related. Only solution is turn back to visual studio code.

**Comment by stevemessick** [comment]
Trailing spaces are removed by the Dart plugin.
