### ISSUE TITLE
Flutter App crash when it runs 

### ISSUE THREAD

**Issue by hashika2** [flutter/flutter-intellij#4571]
F/AS.ASSERTION-FAILED(18834): 19:34:08.661[50862] invoke trace - java.lang.Exception: invoke trace
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.common.appertizers.a.a(SourceFile:27)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.common.appertizers.a.a(SourceFile:35)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.common.appertizers.a.a(SourceFile:42)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.upgrade.c.d(SourceFile:264)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.upgrade.c.d(SourceFile:291)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.upgrade.d.e(SourceFile:45)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.upgrade.d.c(SourceFile:103)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.worker.category.HighPriorityWork.c(SourceFile:162)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.worker.category.HighPriorityWork.b(SourceFile:102)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.worker.category.HighPriorityWork.a(SourceFile:67)
F/AS.ASSERTION-FAILED(18834):   at com.ushareit.longevity.worker.AliveWorker.doWork(SourceFile:26)
F/AS.ASSERTION-FAILED(18834):   at androidx.work.Worker$1.run(SourceFile:85)
F/AS.ASSERTION-FAILED(18834):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
F/AS.ASSERTION-FAILED(18834):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
F/AS.ASSERTION-FAILED(18834):   at java.lang.Thread.run(Thread.java:818)

**Comment by stevemessick** [comment]
This is not related to the Flutter plugin.

**Comment by Zahra-H** [comment]
i have the same problem

**Comment by MohamedMahmoud10** [comment]
how you solved it ??
