### ISSUE TITLE
Android Studio code reformat on switching windows

### ISSUE THREAD

**Issue by kanczler** [flutter/flutter-intellij#4572]
## Steps to Reproduce
Make a Flutter project in Android Studio. Have 'format code on save' ticked in the settings. Start writing code in a .dart file, create a few empty lines, have an unfinished line of code - and then switch to another application. When you return to Android Studio, the code have been reformatted without the user actually saving the file.

Expectation: When I switch to another application (for example a browser to look up a code sample) and return to Android Studio, my code is just as I left it - probably half-finished, extra empty lines, unformatted.

Observation: When I switch to another application (for example a browser to look up a code sample) and return to Android Studio, my code has been reformatted just as if I pressed command+S (or manually saved the file).
  
## Version info
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/andrew/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andrew/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 9C273367-2A8F-4F93-8E1B-868E86BB6A24 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

**Comment by alexander-doroshko** [comment]
Android Studio saves files not only on `Cmd+S` keypress but also in some other cases. So, `Format on save` works on some other cases as well. You may switch off 'Save files on frame diactivation' option in Preferences -> Appearance & Behavior -> System Settings.

**Comment by kanczler** [comment]
You are a lifesaver, this was driving me insane. Thank you!
