### ISSUE TITLE
Don't use extra underscore when creating a State object for a private widget

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter-intellij#4577]
When using the "stf" template to autogenerate a stateful widget, we typically see something like:

```
class MyWidget extends StatefulWidget {...}

class _MyWidgetState extends State<MyWidget> {...}
```

However, sometimes I want a widget class to be file-private, and in those cases I end up with names like the following:

```
class _MyWidget extends StatefulWidget {...}

class __MyWidgetState extends State<_MyWidget> {...}
```

Notice the double underscore prefixing the `State` subclass. I would still expect only a single underscore, but I end up with two underscores.

In my opinion this is a bug, but if it's not considered a bug then I would still recommend changing this behavior as a feature request.

**Comment by devoncarew** [comment]
Thanks for the report! I agree that the double underscore isn't helpful here.

Those templates are defined in this metadata file: https://github.com/flutter/flutter-intellij/blob/master/resources/liveTemplates/flutter_miscellaneous.xml

We may not get to this right away, but if you see a way to adjust the template so that double underscores can be avoided, contributions are welcome.

**Comment by pq** [comment]
FWIW this should be doable but with a custom Live Template function which I gather will require a custom macro.

See discussion here: https://stackoverflow.com/questions/12156205/how-can-i-add-custom-expression-functions-for-live-templates-in-intellij

There are some existing macros in the  Dart plugin here:

https://github.com/JetBrains/intellij-plugins/tree/master/Dart/src/com/jetbrains/lang/dart/ide/template/macro

**Comment by spkersten** [comment]
There is a `regularExpression(<String>, <Pattern>, <Replacement>)` macro [1] that could perhaps be used something like `regularExpression("_$NAME", "^__", "_")`.

[1] https://www.jetbrains.com/help/idea/template-variables.html#predefined_functions
