### ISSUE TITLE
Flutter plugin not compatible with 4.0 stable Android studio

### ISSUE THREAD

**Issue by linuxjet** [flutter/flutter-intellij#4581]
![Screen Shot 2020-05-28 at 6 52 45 PM](https://user-images.githubusercontent.com/378474/83205577-8b7f1200-a114-11ea-97b4-90fe4f2f9823.png)
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

4.0 stable update process.

**Comment by alexander-doroshko** [comment]
This is a false alarm, sorry about that. Update and restart, Android Studio will suggest to update to the compatible versions of the Dart and Flutter plugin.

**Comment by devmgs** [comment]
Check. https://github.com/flutter/flutter-intellij/issues/4166. Just update and restart and then update plugins

**Comment by devmgs** [comment]
It is working

Flutter 1.17.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f21edf8b6 (17 hours ago) • 2020-05-28 12:44:12 -0700
Engine • revision b851c71829
Tools • Dart 2.8.3

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.43.0)
[!] Connected device
    ! No devices available

**Comment by linuxjet** [comment]
great thx.

**Comment by sagar0701** [comment]
Just Update Plugins Flutter and Dart. And Restart Android Studio Its Working.

**Comment by BigNateBombBomb** [comment]
It might help some out there to know that you might have to follow the following alternate instructions to make it work
- Uninstall the plugin FIRST (tried several times to just update after restart with no luck)
- Restart Android Studio
- Install Dart plugin again
