### ISSUE TITLE
FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp

### ISSUE THREAD

**Issue by Mhood98** [flutter/flutter-intellij#4582]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

You shall fix the fontfamily in the yaml file, even the same code won't run again.
FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
This might be a Flutter engine problem, but I'm not really sure.
Try reporting it here:
https://github.com/flutter/flutter/issues
