### ISSUE TITLE
Flutter Inspector sometimes not works (Android Studio)

### ISSUE THREAD

**Issue by saturov** [flutter/flutter-intellij#4583]
## Steps to Reproduce

I actively use Android Studio as my main IDE for Flutter development and for a couple of months I see that so-called DevTools that included inside Inellij Idea Flutter plugin are not stable enough (unlike web DevTools). 

Steps to reproduce are pretty simple for me:
1. Run the application in dev mode
2. Watch Flutter Inspector that doesn't work

Sometimes Flutter Inspector... like it doesn't see the running application. It looks like that. You can see nothing but only the "Widget tree for the running app" label.
![image](https://user-images.githubusercontent.com/2971723/83231012-75646680-a193-11ea-9d05-df1d56ec6774.png)

Take a look at the Dart DevTools at the same moment. I didn't even restart the app (nor Hot Restart neither Hot Reload). Dart DevTools was started only after the moment I took the previous screenshot.
![image](https://user-images.githubusercontent.com/2971723/83231207-cd02d200-a193-11ea-8ca4-1ec10a6ffd25.png)

This issue is not related to some current Android Studio version, I faced it both on 3.6 and 4.0.

I don't know how to help you with specifying some useful logs or something, so please welcome to ask me about any additional information you need from me.

## Version info

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale ru-RU)
    • Flutter version 1.17.2 at /Users/saturov/Library/flutter
    • Framework revision 5f21edf8b6 (11 hours ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/saturov/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • SM G973F • RF8M31ADENP • android-arm64 • Android 10 (API 29)
```

**Comment by jwren** [comment]
Please re-open with reproducible steps with recent versions if this is still and issue.
