### ISSUE TITLE
issue using --dart-define in run configurations with a value that has a space

### ISSUE THREAD

**Issue by samandmoore** [flutter/flutter-intellij#4588]
## Steps to Reproduce

* Create a flutter app, the template counter app will do
* Create a run configuration and add the following to the "additional arguments"
```
--dart-define='SOMETHING=cool: thing'
```
* Run the app using the configuration
* Instead of setting the value in the ENV for `SOMETHING='cool: thing'` the run configuration fails with an error like this:
```
Target file "thing'" not found.
```

**Note: this works just fine via the flutter command line**
```
flutter run --dart-define='SOMETHING=cool: thing' -t lib/main.dart
```

And the value is available in the ENV as expected.

If you remove the empty space character between `cool:` and `thing` then it works just fine. Is there some escaping approach for this in Android Studio? Is this an issue with the plugin or Android Studio itself?

## Version info

```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at /Users/sam/flutter
    • Framework revision d3ed9ec945 (8 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sam/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • iPhone 11 Pro • BD24122A-D14B-472C-8A26-A436A43E3583 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS         • macOS                                • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Chrome        • chrome                               • web-javascript • Google
      Chrome 83.0.4103.61
    • Web Server    • web-server                           • web-javascript • Flutter
      Tools

• No issues found!
```

**Comment by stevemessick** [comment]
I suspect we're doing: `args.split(" ")`. We need to add string detection.

**Comment by stevemessick** [comment]
Yep, SdkFields line 129 does exactly that.

Fixing this issue requires adding an argument parser. @devoncarew for prioritization.
https://github.com/remkop/picocli/wiki/CLI-Comparison

**Comment by feinstein** [comment]
@devoncarew can we up the priority on this? This issue is impacting one of our projects at the bank and it seems like a small fix. Thanks :)

**Comment by feinstein** [comment]
@devoncarew many thanks! :)

**Comment by samandmoore** [comment]
thanks!

**Comment by daadu** [comment]
When is it releasing?

**Comment by matecode** [comment]
upvote

**Comment by feinstein** [comment]
Usually they do monthly releases.

**Comment by devoncarew** [comment]
Yup, we almost always release based on calendar month - it makes planning simple and is predictable for users (modulo the end of the year - we generally don't ship a Dec. release).

You can also see the est. ship date via our milestones in this repo.

**Comment by haashem** [comment]
This issue still persists in VSCode!

**Comment by dmitry-fbm** [comment]
Still doesn't work:
```
flutter/bin/flutter build ios --no-codesign --dart-define='DEF_APP_NAME=anything with spaces'
Target file "with" not found.
```
Flutter 2.0.4
Dart 2.12.2

**Comment by feinstein** [comment]
I don't remember te syntax by memory and an I not at my computer, but try it like: 

--dart-define=DEF_APP_NAME="anything with spaces"

Let me know if it doesn't work, I have it working on my project.

**Comment by dmitry-fbm** [comment]
> Let me know if it doesn't work, I have it working on my project.

It doesn't. Works fine on Windows but not on Mac.

**Comment by feinstein** [comment]
There's one person on my team working on a Mac with Android Studio and he didn't complain, he's building for Android though.

**Comment by dmitry-fbm** [comment]
We build with Jenkins for both iOS and Android so that's pretty different setup. Both builds fail with the same error, not just Android. Generally we need it working from Mac CLI.

**Comment by sbatezat** [comment]
I've got a similar issue when usine define_env tool (see https://github.com/ibrahim-mubarak/define-env/issues/11)

Relevant working samples:

flutter build web --dart-define=KEY1=VALUE1 --dart-define=KEY2="VALUE2 WITH SPACE"
flutter build web '--dart-define=KEY2="VALUE2 WITH SPACE"'
flutter build web '--dart-define=KEY1=VALUE1' '--dart-define=KEY2="VALUE2 WITH SPACE"'

Relevant NOT working samples:

flutter build web '--dart-define=KEY1=VALUE1 --dart-define=KEY2="VALUE2 WITH SPACE"'
=> output "Target file "WITH" not found."

Is there anything you can do to have the last instruction working?
