### ISSUE TITLE
Unable to run Android Emulator, not applicable for “main.dart” configuration

### ISSUE THREAD

**Issue by rmirayk** [flutter/flutter-intellij#4589]
When I click on my device Pixel 3, I get a message like "Not applicable for main.dart configuration". I also displayed the device selection tab, there is an option for "Open Android Emulator: Pixel 3 API 29" but I couldn't run my project, it still prompts "no device selected". I'm sure that Project and Module SDKs are alright, I have enabled the Virtualization(VT), and installed HAXM a long time ago. Flutter doctor output is here, it's issueless. 

```
C:\Users\rmira>flutter doctor -v
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.18.0-11.1.pre at C:\flutter
    • Framework revision 2738a1148b (2 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\rmira\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\rmira\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!

```

**Comment by helin24** [comment]
Can you post a screenshot of your toolbar with the device menus?

After clicking "Open Android Emulator: Pixel 3 API 29", does your emulator open? If so, also check if the flutter device menu to the left of your configurations has a new option of the emulator.

**Comment by rmirayk** [comment]
I just fixed this problem as reinstalling Android Studio and toolchain for many times, it wasn't locating adb. Thanks though.

**Comment by liyiwei979621500** [comment]
@rmacnak-google HI.How did you solve this? I have tried reinstalling many time.
How to set correct adb?

**Comment by Ali1067** [comment]
facing same issue. is there nay one who resolved this?

**Comment by rmiraykurt2** [comment]
Try reinstalling SDK tools. Check your SDK configurations from Project Structure > Project and then from Module. It may be helpful.

**Comment by wilsonsf** [comment]
Hey, guys, I went through the same error, fixed by adding the SDK into the IntelliJ project configuration, through the following:

First, you must add the Android SDK into the IntelliJ:  
`Project Structure > Project > Settings Project > Project SDK`
-  Add SDK > Android SDK

You should use `C:\Users\rmira\AppData\Local\Android\sdk`, as it was shown in the `flutter doctor` command, as for my computer, the path was `/Users/%user%/Library/Android/sdk`.

Second, you must fix the modules SDK:  
`Project Structure > Modules > Select module > Dependencies tab > Module SDK > Project SDK`

After confirming, a few tasks will run and after they are done, you'll be able to run both emulators.

**Comment by Ali1067** [comment]
Solved by these.
- Make Sure SDK is configured properly.
- Make Sure Dart in installed.
- install any Android/iOS emulators & run them. (emu/simulator must be running before you write run flutter or flutter run
- after that in terminal write "run flutter"

i hope it'll help someone.

**Comment by Horrible122** [comment]
Close **Android Studio** and Run again as Administrator
