### ISSUE TITLE
unable to select my avd...can't use main.dart confriguaiton

### ISSUE THREAD

**Issue by deepankerpandey7** [flutter/flutter-intellij#4592]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17763.615], locale en-US)Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[√] Android Studio (version 3.6)
[!] Connected device
    ! No devices available

**Comment by helin24** [comment]
It looks like there could be an issue with Android emulators - did you follow the Android SDK re-installation instructions and the flutter setup instructions? Are you able to launch an Android emulator?

For the Android licenses status, you may need to do `flutter doctor --android-licenses` to accept licenses (see https://github.com/flutter/flutter/issues/16025).
