### ISSUE TITLE
Dart runtime has started to eat all RAM when building flutter project

### ISSUE THREAD

**Issue by reducedcarpet** [flutter/flutter-intellij#4597]
## Steps to Reproduce

I had updated the dart plugin today, but then this evening when I went to work on a project, I started to continuously have Android eat all the RAM it could, 12gb approx and then the computer would freeze. It didn't matter if I was building for an emulator or for a real device, I tried Invalidate Caches and Restart and it did the same. I reverted any code changes I had made, but nothing worked and I had to reboot my computer each time, for a total of four times. 

Honestly I should have probably tried compiling a smaller test project, but naturally I wanted to build what I was working on. 

## Version info

flutter doctor -v
[√] Flutter (Channel dev, 1.19.0-1.0.pre, on Microsoft Windows [Version 10.0.18362.836], locale en-GB)
    • Flutter version 1.19.0-1.0.pre at C:\Users\micha\AppData\Local\flutter_1.5.4
    • Framework revision 456d80b9dd (3 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\micha\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\micha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (3 available)
    • SM G965F   • 21a97bb0230c7ece • android-arm64  • Android 10 (API 29)
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.61

• No issues found!

**Comment by devoncarew** [comment]
Can you see if you're running into this issue: https://github.com/dart-lang/sdk/issues/40243#issuecomment-635816583, and check whether the indicated workaround works for you?

**Comment by reducedcarpet** [comment]
It was because (I think) I had made a strings.xml and was referencing one the the strings in the manifest, it complained one time about being unable to link resources and that it was going to try jetifier. I didn't get a screenshot or anything because my computer was frozen. But when I destroyed the strings.xml file and just hardcoded them in the manifest it no longer seemed to hate me so hard. And it also compiled and didn't crash my computer. 

I don't know if those other issues are the same, they seem to have a responsive computer such that they get output. But thanks for the info, and I hope my info helps a little. I can try and make a simplifed test case to see if it was actually the problem at the weekend if you would like?

**Comment by stevemessick** [comment]
@reducedcarpet Yes, if you can provide a repro project, that would be great. It sounds like the issue may not involve the Flutter plugin, but we'd like to take a look.

**Comment by KlausJokinen** [comment]
Flutter clean will solve this issue (temporary fix).

**Comment by reducedcarpet** [comment]
Yup, I redix the string resource that was causeing the problem and i couldn't replicate the issue. It was either fixed by flutter clean, or it was because the resource was misnamed in the Manifest and resource linking failed. With a correct link it was fine. 

I even tried it was an incorrect link in the manifest and it still compiled, strangely. No runaway ram usage. So I assume it's one of those weird problems where you have just made the strings.xml file but android studio hasn't indexed it yet.

**Comment by stevemessick** [comment]
@reducedcarpet Thanks for the response. It sounds like this is fixed, and probably not something we could help with, so I'll close this.
