### ISSUE TITLE
android studio 4.0 get stuck after flutter run on a iphone simulator

### ISSUE THREAD

**Issue by chenenyu** [flutter/flutter-intellij#4599]
## Steps to Reproduce

When `flutter run` on a iphone simulator, studio get stuck but the iphone simulator works well.
 
## Version info

```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/chenenyu/development/flutter
    • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chenenyu/development/AndroidSDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/chenenyu/development/AndroidSDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • MI 8 UD • 6ef9f1d3 • android-arm64 • Android 10 (API 29)

• No issues found!
```
studio thread dump: 
[dump1.txt](https://github.com/flutter/flutter-intellij/files/4722761/dump1.txt)

**Comment by chenenyu** [comment]
btw, it works well in a demo project.  😢

**Comment by chenenyu** [comment]
It's an entirely flutter project with many flutter modules and plugins.
All plugins of the android studio:
![image](https://user-images.githubusercontent.com/6647088/83706068-20b86400-a649-11ea-920b-39df78936413.png)

Monitor about cpu/memory:
![image](https://user-images.githubusercontent.com/6647088/83705786-6c1e4280-a648-11ea-8e7a-2083880e1c2c.png)
![image](https://user-images.githubusercontent.com/6647088/83705707-442edf00-a648-11ea-8cce-174a2f5bf56d.png)

When `flutter run` on android devices, the studio works well.

**Comment by stevemessick** [comment]
The "Console filters" thread looks suspicious. Any chance you could copy (or screenshot) the Flutter console? I suspect an error message is causing the regexp to hit a performance problem. The error might not have been printed yet, though. When you run it in a terminal emulator do you see any error messages? If so, can you attach them (nothing proprietary)?

**Comment by chenenyu** [comment]
It's ok when execute `flutter run` in the studio's built-in terminal, and the verbose log seems normal.
[build-verbose.log](https://github.com/flutter/flutter-intellij/files/4733634/build-v.log)

**Comment by stevemessick** [comment]
Thanks for the log file! It does look like there may be a problem with a new regexp.

**Comment by HugoHeneault** [comment]
Same here! Really annoying as I can't even work on iPhones anymore :(

@stevemessick when would this regexp have been added? So I can revert to a working version while you're working on a fix 🤞 

Thanks a lot 🍻

**Comment by stevemessick** [comment]
Yep, it was added in 46, so 45 should work. The fix should be available in the next dev channel build, which will be out June 14.

https://github.com/flutter/flutter-intellij/wiki/Dev-Channel

**Comment by wahyubaskara** [comment]
Same here, before i run iphone emulator it works as expected, but when i start iphone emulator and type something it will freeze even i should close android studio by Force Quit app

**Comment by stevemessick** [comment]
This was fixed with #4605, and will be in the next dev channel build (as mentioned before).

Leaving this open until then .

**Comment by chenenyu** [comment]
@stevemessick Thanks! 👍

**Comment by chenenyu** [comment]
`47.0.2-dev.3` doesn't work. 😢
