### ISSUE TITLE
Color constants in our Editor should be color-coded

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#460]
_From @Hixie on April 29, 2016 16:32_

I saw @jimbe has the [pigments plugin](https://atom.io/packages/pigments) in Atom that colorizes any hex string that it sees. We should totally do that for any Color literal in Flutter code.

cc @devoncarew 

_Copied from original issue: flutter/flutter#3628_

**Comment by mit-mit** [comment]
@alexander-doroshko is this possible in IJ?

**Comment by alexander-doroshko** [comment]
@mit-mit Do you mean special highlighting of special Dart string literals? Yes, it's possible. Standard way for color literals in IntelliJ is a gutter icon, for example, see example from CSS:
![image](https://cloud.githubusercontent.com/assets/4499789/20475836/c8d4b6da-afde-11e6-96af-286743a762e2.png)
Clicking on this color square opens a powerful color selection dialog with recent colors, color picker, etc. Selection of another color in the dialog updates the source code.
![image](https://cloud.githubusercontent.com/assets/4499789/20475931/5de3860c-afdf-11e6-93de-d16bb2084a62.png)

**Comment by mit-mit** [comment]
@alexander-doroshko that is exactly what I meant. The gutter approach looks good. How do we enable that?

**Comment by alexander-doroshko** [comment]
Implement `com.intellij.openapi.editor.markup.GutterIconRenderer`
