### ISSUE TITLE
flutter hang 

### ISSUE THREAD

**Issue by gameorised** [flutter/flutter-intellij#4600]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
C:\src\flutter\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
    • Flutter version 1.17.1 at C:\src\flutter\flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

## Version info

C:\src\flutter\flutter\bin>flutter doctor -v
Waiting for another flutter command to release the startup lock...
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
    • Flutter version 1.17.1 at C:\src\flutter\flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\MAHFOOZ-PC\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    X Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by gameorised** [comment]
• Platform android-29, build-tools 29.0.3
X Android SDK file not found: adb.
not able to resolve this problem

**Comment by helin24** [comment]
Hello! Is flutter hanging when you run `flutter doctor -v` or when you're doing something in Android Studio? If the latter, can you describe what you were trying to do and any output in Android Studio?

If you're seeing `Waiting for another flutter command to release the startup lock...` it looks like there could be another flutter process running that failed. You may be able to try stopping all processes and restarting as mentioned [here](https://stackoverflow.com/questions/51679269/waiting-for-another-flutter-command-to-release-the-startup-lock).

**Comment by gameorised** [comment]
C:\src\flutter\flutter\bin>flutter doctor -v
Waiting for another flutter command to release the startup lock...
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
• Flutter version 1.17.1 at C:\src\flutter\flutter
• Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
• Engine revision 6bc433c6b6
• Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at C:\Users\MAHFOOZ-PC\AppData\Local\Android\sdk
• Platform android-29, build-tools 29.0.3
X Android SDK file not found: adb.
• Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 46.0.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
! No devices available

! Doctor found issues in 2 categories.

Please paste the output of running flutter doctor -v here (available from the command
line or from Tools > Flutter > Flutter Doctor). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment]
@gameorised, I'm not quite sure what you're doing; is this when you're running the Flutter plugin in IntelliJ? Is the hang happening when running apps? When editing code?
