### ISSUE TITLE
Add-to-app module import settings line added twice

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#4608]
## Steps to Reproduce

Did the flutter module import flow. It added the same line twice in the settings.gradle.
<img width="892" alt="Screen Shot 2020-06-06 at 10 40 05 PM" src="https://user-images.githubusercontent.com/156888/83961327-c4229800-a846-11ea-9bf0-9c5068322f84.png">

## Version info

[✓] Flutter (Channel master, 1.19.0-4.0.pre.92, on Mac OS X 10.15.5 19F101, locale en)
    • Flutter version 1.19.0-4.0.pre.92 at /Users/xster/development/flutter
    • Framework revision c0091b289e (8 hours ago), 2020-06-06 17:53:01 -0400
    • Engine revision ff6462e457
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 249cb9c974)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xster/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = /Users/xster/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • sdk gphone x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

**Comment by devoncarew** [comment]
cc @stevemessick

**Comment by stevemessick** [comment]
@xster I did the import during M46 testing last week. I didn't get a duplicate line. I used freshly created Android and Flutter projects. Did you do something different?

**Comment by stevemessick** [comment]
@xster I just did this with no duplicates:
- Create a Flutter module
- Create an Android project
- Import the module
- Import the module, again

I can't reproduce your problem. Do you have repro steps?

**Comment by xster** [comment]
umm those are the steps I followed too. Maybe I was doing something weird. Let's close this for now (I think it's not a grave issue either way). I'll keep an eye out and re-open if I run into this again.

**Comment by stevemessick** [comment]
SGTM, thanks!
