### ISSUE TITLE
moving widgets up or down in the tree

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#461]
_From @HansMuller on March 8, 2016 17:31_

Say I have this:

```
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new GestureDetector(
        onTap: () { startResize(); },
        child: new Center(
          child: new Container(
            width: 200.0,
            height: 300.0,
            decoration: new BoxDecoration(backgroundColor: const Color(0xFF00FF00))
          )
        )
      )
    );
  }
```

And I want to move the GestureDetector "down" so that it wraps its Container descendant.

```
  Widget build(BuildContext context) {
    return new Scaffold(
       body: new Center(
        child: new GestureDetector(
          onTap: () { startResize(); },
          child: new Container(
            width: 200.0,
            height: 300.0,
            decoration: new BoxDecoration(backgroundColor: const Color(0xFF00FF00))
          )
        )
      )
    );
  }

```

Currently this is a pretty tedious manual process, particularly when the tree the widget is within is relatively complex.

Changes like this are very common in Flutter application building. 

I wish Widget tree operations like this were relatively trivial. For example if there was a graphical view of the corresponding tree, then one could just drag and drop nodes. 

_Copied from original issue: flutter/flutter#2486_

**Comment by mit-mit** [comment]
@stevemessick how is this exposed?

**Comment by devoncarew** [comment]
This landed in the analysis server, and will need a new dart dev sdk, and for that sdk to be rolled into flutter, in order to see.

<img width="487" alt="screen shot 2017-02-24 at 2 44 46 pm" src="https://cloud.githubusercontent.com/assets/1269969/23409139/540fe812-fd7f-11e6-9ba8-c60141e782c2.png">

This would be accessed through option-enter / alt-enter in IntelliJ.

**Comment by devoncarew** [comment]
Really, really excited to see this land :)
