### ISSUE TITLE
Allow non-dartfmt auto-formatting on save

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter-intellij#4617]
Not everyone is happy with dartfmt's rigid formatting approach.
Please add an option to use the integrated formatting (in Settings - Editor - Code Style - Dart) on file save.
Please allow the option to be per-project.

**Comment by stevemessick** [comment]
Formatting is controlled by the Dart plugin, not Flutter. Your request has been discussed, and I don't think it is likely to happen. Recent discussion is here:
https://youtrack.jetbrains.com/issue/WEB-45838

**Comment by duzenko** [comment]
@stevemessick 
What does this option do in Flutter? (Format code on save)
Does it call dartfmt explicitly or redirect to the dart plugin?
![image](https://user-images.githubusercontent.com/1481807/84643448-825cb600-af06-11ea-8836-54ed87c42ddc.png)

**Comment by stevemessick** [comment]
Interestingly, that option calls the same service that the Dart plugin uses to format code (the Dart analysis server). So, technically, it is controlled by the Flutter plugin. I had assumed that option used the Dart plugin. It should probably be changed to do that.

**Comment by duzenko** [comment]
Don't you feel that 'our way or no way' is sheer arrogance on dart/flutter side?

**Comment by stevemessick** [comment]
> Don't you feel that 'our way or no way' is sheer arrogance on dart/flutter side?

Nope. I've been writing software a long time. Early on, there were long, complicated, emotional conversations about how the code should be formatted. For a while, tool authors sought to satisfy everyone with hugely complex formatting options. Lead architects spent many man-months defining exact formatting standards. And then, one language decided to buck that trend and said only one formatting standard would be provided. Anyone wanting something different was on their own. That  proved to be surprisingly uncontroversial. Slowly, other languages started adopting the same strategy. It's becoming the industry standard, especially for new languages.

I see you've already seen the comments by @alexander-doroshko in the [issue](https://youtrack.jetbrains.com/issue/WEB-45838) on the Jetbrains tracker. I suggest re-reading that thread. He answers most of your recent questions. He also provides a link to the [dartfmt FAQ](https://github.com/dart-lang/dart_style/wiki/FAQ). You should check it out. In particular, note the following quote:
> This may be surprising, but the goal of dartfmt is not to automatically make your code look the way you like. It's to make everyone's Dart code look the same. The primary goal of dartfmt is to improve the quality of the Dart ecosystem. That transitively improves the live's of each Dart developer as well—you get more code to reuse, more consistent code, it's easier to read and contribute to each other's code, etc. But it does that at the expense of individual preference.

You can always write your own formatter. The FAQ linked above has a link to an article by the author of `dartfmt` about how it is implemented. No one on the Dart or Flutter teams has the time to write and maintain another formatter.

**Comment by duzenko** [comment]
> 
> 
> > Don't you feel that 'our way or no way' is sheer arrogance on dart/flutter side?
> 
> Nope. I've been writing software a long time. Early on, there were long, complicated, emotional conversations about how the code should be formatted. For a while, tool authors sought to satisfy everyone with hugely complex formatting options. Lead architects spent many man-months defining exact formatting standards. And then, one language decided to buck that trend and said only one formatting standard would be provided. Anyone wanting something different was on their own. That proved to be surprisingly uncontroversial. Slowly, other languages started adopting the same strategy. It's becoming the industry standard, especially for new languages.
> 
> I see you've already seen the comments by @alexander-doroshko in the [issue](https://youtrack.jetbrains.com/issue/WEB-45838) on the Jetbrains tracker. I suggest re-reading that thread. He answers most of your recent questions. He also provides a link to the [dartfmt FAQ](https://github.com/dart-lang/dart_style/wiki/FAQ). You should check it out. In particular, note the following quote:
> 
> > This may be surprising, but the goal of dartfmt is not to automatically make your code look the way you like. It's to make everyone's Dart code look the same. The primary goal of dartfmt is to improve the quality of the Dart ecosystem. That transitively improves the live's of each Dart developer as well—you get more code to reuse, more consistent code, it's easier to read and contribute to each other's code, etc. But it does that at the expense of individual preference.
> 
> You can always write your own formatter. The FAQ linked above has a link to an article by the author of `dartfmt` about how it is implemented. No one on the Dart or Flutter teams has the time to write and maintain another formatter.

That all sounds good in theory, but my experience with flutter plugins is: it uses (and forces on contributors) their own formatting, incompatible with dartfmt.
Double frustrating.

**Comment by duzenko** [comment]
What I also wanted to express and failed above

It seems that the main problem Dart wanted to solve by offering itself to the wide audience was to overcome various JavaScript shortcomings.

I'm sure a lot of people switching from JS to Dart had no problem with dartfmt because they had no previous habit of code formatting. They might have never used an IDE before too. So you kinda achieved that noble goal, getting all those folks automatically formatting their code from now on. 

But I personally, coming from 'developed' languages and IDE's, have my own ideas about code formatting that I did not invent myself, but learned from other, more distinguished figures. Every now and then, when I look at dartfmt output, it hurts.

I wonder if you want to live in a world where all houses look identical, and cars, etc. You know, to improve the quality of ecosystem, and so on.

**Comment by duzenko** [comment]
The last point I want to make on this subject.

>>  That transitively improves the live's of each Dart developer as well—you get more code to reuse, more consistent code, it's easier to read and contribute to each other's code, etc. But it does that at the expense of individual preference.

They talk about 'individual preference' being sacrificed as something natural and worthwhile. I wonder how much of their own preference they are used to be giving up regularly. The default rules of dartfmt weren't written on stone tablets by a deity. Someone like you and me was allowed (or probably self-appointed) to very much indulge in their individual preference when they wrote that dartfmt draft, weren't they? Of course, under condition that absolutely everybody else was now given no choice but give up their own individual preference.

You don't see the irony in that? Nor historical precedends?

**Comment by stevemessick** [comment]
> you kinda speak on their behalf, right?

Not at all. I'm not on the Flutter team although we work closely together.

If you have an issue with `flutter/plugins` you should bring it up there. I only speak for `flutter/flutter-intellij` and occasionally `dart-lang/sdk`.

Source code doesn't compare well to houses. Reading code is more like reading text. In any given book I expect the formatting to be consistent throughout. I don't expect the same format in every book.

The other formatter you refer to just gathers up all the Dart files and then runs `flutter format ...`, which in turn runs `dartfmt`.

The [Dart style guide](https://dart.dev/guides/language/effective-dart/style), which is implemented by `dartfmt`, went through a lengthy review process with almost every one on the Dart team contributing feedback.

You're not forced to use `dartmt`. There is no issue of giving up choice. You can write your own formatter or do manual formatting.

As I said before, no one on the Dart or Flutter teams is going to write another formatter. Continuing to try to change that is just going to lead to more frustration for you.
