### ISSUE TITLE
Hide sidebar elements in non flutter projects.

### ISSUE THREAD

**Issue by jkoenig134** [flutter/flutter-intellij#4618]
The sidebar elements "Flutter Inspector", "Flutter Outline", and "Flutter Performace" are shown in non Flutter projects. On every startup I have to hide them manually. 
Other plugins (e.g. maven and gradle) manage to hide the elements if there is no current (maven/ gradle) project available.

**Comment by stevemessick** [comment]
FWIW this is a known issue. See the discussion here:
https://github.com/flutter/flutter-intellij/pull/4281

**Comment by jkoenig134** [comment]
@stevemessick i am sorry, i tried to search for an issue but couldn't find one.

**Comment by stevemessick** [comment]
To be fair, I guess we had never created an issue, just the PR. Thanks!

**Comment by helin24** [comment]
Fixed by https://github.com/flutter/flutter-intellij/pull/5622
