### ISSUE TITLE
Show extensions function in suggestions ide

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter-intellij#4627]
Current. All extensions don't show if not import them yet. I think it should be smarter by pre suggest :D

**Comment by pq** [comment]
There's a related tracking issue in the SDK but I can't seem to find it.

@bwilkerson @jwren: maybe you have it handy?

**Comment by tbm98** [comment]
I was create an issue in flutter/flutter but they close it and suggest me
put it into here

Vào 22:35 Th 3, 16 thg 6 2020 Phil Quitslund <notifications@github.com> đã
viết:
