### ISSUE TITLE
Android Studio Flutter - Virtual Device in Loading or stuck

### ISSUE THREAD

**Issue by anirudhsharma392** [flutter/flutter-intellij#4638]
When opening Android Studio and trying to run my first demo app of flutter. The device section continues to show loading; even when the emulator is on.

![image](https://user-images.githubusercontent.com/36081049/85124440-8e6aaf80-b247-11ea-8b2a-bf4c28c4c305.png)

I have also uninstalled android studio completely and then reinstalled it.But this issue appears again.
I thing this is somehow related to the flutter/dart plugin in android studio.

**Comment by anirudhsharma392** [comment]
Also I have reinstalled everything to the latest version.It's still giving me same error.
Also ever

**Comment by stevemessick** [comment]
Dup of #3892, #4632
