### ISSUE TITLE
recognize extends StatelessComponent, extends StatefulComponent

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#465]
_From @HansMuller on February 19, 2016 0:11_

If I type `class Foo extends StatelessComponent` Atom appends `{}`. It would be even more helpful if it appended an empty build() method.

Similarly, if I type `class Foo extends StatefulComponent` Atom could generate a _FooState class and all the rest of the boilerplate.

_Copied from original issue: flutter/flutter#2015_

**Comment by mit-mit** [comment]
_From @sethladd on February 19, 2016 0:26_

Our plugin could make it easier to discover "quick fixes", which in this case can add missing methods like build(). Try Control-1, I think.

We can also argue that the analyzer should just add those methods anyway. If your class isn't abstract, and you just defined it, just fill in all the required methods. Filed https://github.com/dart-lang/sdk/issues/25817 to track.

cc @kevmoo

**Comment by pq** [comment]
This is related to the question about aggressive constructor code completion (#1005) and would benefit from some experiments.

**Comment by scheglov** [comment]
Is this still an issue?

Steve [implemented](https://github.com/flutter/flutter-intellij/issues/800#issuecomment-288826966) live templates `stless`, `stful` and `stanim` to generate `StatelessWidget` or `StatefulWidget` boilerplate. It is even more convenient than partial code generation after `extends StatefulWidget` completion. Although you need to know that this feature exists.

**Comment by stevemessick** [comment]
With #800 and dart-lang/sdk#25817 I don't think we need this any longer. If work is going to be done it will be in the analyzer.
