### ISSUE TITLE
[Feature Request] Show preview of FontAwesomeIcons in editor gutters 

### ISSUE THREAD

**Issue by jlubeck** [flutter/flutter-intellij#4663]
I just saw that you added support for displaying CupertinoIcons in the gutters. 

Is there any way to add FontAwesomeIcons as well?

Thanks!

**Comment by stevemessick** [comment]
Sorry, that's a commercial product.

**Comment by jlubeck** [comment]
Hey @stevemessick they do have a commercial upgrade, but the base of it is free and opensource

https://fontawesome.com/v4.7.0/license/

https://github.com/FortAwesome/Font-Awesome

**Comment by stevemessick** [comment]
Ah, I missed that. I'll leave this open. If it gets enough upvotes then we'll see about it.

**Comment by stevemessick** [comment]
Fixed with the Sept release.
