### ISSUE TITLE
Test execution hanging on 47.0.2

### ISSUE THREAD

**Issue by amantoux** [flutter/flutter-intellij#4666]
## Steps to Reproduce

Open a flutter project, run test on all files in a directory or a specific file
=> **The IDE hangs forever** and no progress on the tests

This started happening when I updated the plugin to 47.0.2

`flutter test` command works as expected
Plugin 46.0.2 works as expected

## Version info
```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale fr-FR)
    • Flutter version 1.17.4 at /Users/alanmantoux/flutter
    • Framework revision 1ad9baa8b9 (10 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alanmantoux/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```

**Comment by devoncarew** [comment]
@helin24 - any change this is related to the work we did to change run operations to pause at start?

cc @jacob314

**Comment by kroikie** [comment]
I'm seeing this as well, when I Debug the tests however they run as expected as well

**Comment by helin24** [comment]
> @helin24 - any change this is related to the work we did to change run operations to pause at start?
> 
> cc @jacob314

It looks like it was due to https://github.com/flutter/flutter-intellij/pull/4622, I'll look into what we should do here.

**Comment by helin24** [comment]
Reverting and we will be releasing this soon: https://github.com/flutter/flutter-intellij/pull/4673

For those that are still having this problem, you can use an older version of the [flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter/versions) (before v 47) or run tests in debug mode.

**Comment by amantoux** [comment]
Thanks!

**Comment by cohenadair** [comment]
This is still happening for me in v48.0.2.

**Comment by helin24** [comment]
@cohenadair thanks for this report. There are two issues here, not being able to run all tests in a project (can follow here - https://github.com/flutter/flutter-intellij/issues/4737) and the debug option being greyed out (can follow here - https://github.com/flutter/flutter-intellij/issues/4742). Hoping to make progress on both of these soon.
