### ISSUE TITLE
Observatory Warning & Test Hanging post 47.0.3 install

### ISSUE THREAD

**Issue by rayk** [flutter/flutter-intellij#4667]
Receiving the following warning, when attempting to run test from within the IDE. Running test from the Command Line still work fine.

```
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.
```

After installing 47.0.3

```
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
Licensed to Ray King
Subscription is active until November 9, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: dart.server.additional.arguments=--enable-completion-model
Non-Bundled Plugins: Dummy Text Generator, Key Promoter X, String Manipulation, com.fwdekker.randomness, com.giancarlocode.built-value-snippets, com.github.lppedd.idea-conventional-commit, mobi.hsz.idea.gitignore, com.herbert.george.flutter-snippets, com.mallowigi, com.paperetto.dash, com.spidev.pubassist, lermitage.intellij.extra.icons, Dart, com.localizely.flutter-intl, com.mobiledi.flutter_plugins, io.flutter, com.chenenyu.intellij.widgetgenerator, org.jetbrains.kotlin, de.mariushoefler.flutter_enhancement_suite, izhangzhihao.rainbow.brackets, zielu.gittoolbox, intellij.prettierJS, org.sylfra.idea.plugins.linessorter, org.toml.lang, org.rust.lang
```

Also reported on [StackOverflow](https://stackoverflow.com/questions/62589342/error-you-should-set-silent-observatory-to-true-when-debugging-the-vm) by @nzxcvbnm

**Comment by franferri** [comment]
Same here, when running the tests.

I have reinstall android studio, flutter channel stable...

MacOS.

Also there is no way of setting the damn variable, is a bug, where a bit more information https://twitter.com/franciscoferri/status/1277246156368678913, it cracked me in the middle of a training...

What a bug.

I have default flutter app, no coverage or additional stuff enabled, just simple tests that I was running in Android Studio.

**Comment by gmcdowell** [comment]
I too have run into this issue.

Turns out this behaviour is intentional - see [release notes](https://plugins.jetbrains.com/plugin/9212-flutter) - checkout the **8th item in the list**.

What I don't understand is why?
It makes when debugging, however if you simply want to run tests, then why set the `--start-paused` flag?

Will try to install the previous version, however initial attempts have proven unsuccessful :(

**Comment by gmcdowell** [comment]
here's the [culprit issue](https://github.com/flutter/flutter-intellij/pull/4622)

**Comment by blasko** [comment]
Having the same issue.
____________________

IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Runtime version: 11.0.7+10-b765.53 x86_64
Flutter plug-in v47.0.3
Flutter version 1.17.4
Dart version 2.8.4
macOS 10.15.5

**Comment by rayk** [comment]
Can confirm that the revert done as part of M47.1 release fixed the issue.
Thanks @stevemessick

**Comment by franferri** [comment]
Indeed! thanks!

**Comment by NaseerUllahAwan** [comment]
I have the same problem, And I am using Visual Studio Code.
Anyone Knows Why it happens?
