### ISSUE TITLE
Android Studio Crash on code completion with flutter plugin

### ISSUE THREAD

**Issue by shashkiranr** [flutter/flutter-intellij#4675]
## Steps to Reproduce

Code completion freezes android studio. 

# The worst part is already saved code is lost !! 

## Version info

Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (12 days ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

## Studio Build

Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false
Non-Bundled Plugins: Dart, com.google.services.firebase, com.thoughtworks.gauge, io.flutter, org.intellij.plugins.markdown

## StackTrace
[full trace link](https://drive.google.com/file/d/1y8IR6-BN-odUnU-0gMtSM9ZJk6hmsb9s/view?usp=sharing)

**Comment by shashkiranr** [comment]
Any Update on this? Is there a workaround? kindly let me know

**Comment by stevemessick** [comment]
Please append the output of `flutter doctor -v`. If you are not already using version 47.1 of the plugin then I suggest upgrading.

Is it a freeze or a crash? Do you have to kill the IDE process or does it exit unexpectedly?

This is not a general problem so we will need more information to determine what the specific problem is. Let's start with steps to reproduce it. Do you have a sample project that demonstrates the problem? How can someone else make this problem occur?

**Comment by shashkiranr** [comment]
Here is. Yes I need to kill the IDE manually. I reinstalled flutter sdk, android studio ide but still facing the issue. Only when code is already running and I change the code does the IDE crash else it works fine. But it is annoying that I have to stop the process change the code and start it again. I cannot find the root cause to this issue.
```
 flutter doctor -v
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.19.0-4.3.pre at /Users/shashi/flutter
    • Framework revision 8fe7655ed2 (2 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shashi/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

! Doctor found issues in 3 categories.

```

**Comment by shashkiranr** [comment]
Same issue if I change the channel to stable

**Comment by stevemessick** [comment]
Thanks. Knowing it only happens while the app is running is interesting. However, I do not have any issues with code completion while the app is running.

This may be a lot to ask, but if you can reliably reproduce the problem, then while the IDE is frozen it might be helpful to get some data. The Mac Activity Monitor app could tell you if any process is using all the CPU time, and if any process is sending or receiving huge amounts of data. Unfortunately, I couldn't find anything useful in the stack trace. Except that it was blocked for 52 seconds (IIRC).

Do you have Dart DevTools open when it hangs?

**Comment by shashkiranr** [comment]
Dart Tools are not open when it happens. I have attached the below screen shot and took a sample from the Activity Monitor app. It hangs over and over again. I would have to force quit it and when i open again the code which was edited while hot reload would be lost. 
<img width="671" alt="Screen Shot 2020-07-16 at 2 38 53 PM" src="https://user-images.githubusercontent.com/4161647/87709517-64d37400-c772-11ea-904d-fbc4c3f6df2c.png">
[Sample of Android Studio - Jul 16 2020.txt](https://github.com/flutter/flutter-intellij/files/4933499/Sample.of.Android.Studio.-.Jul.16.2020.txt)

**Comment by stevemessick** [comment]
Could you try using an older version of Flutter?
https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_1.17.4-stable.zip
(Or 1.17.3 if you already have 1.17.4)

Is your mouse cursor on the same spot that you are trying to get completion? Has any hover-text evaluation appeared?

**Comment by shashkiranr** [comment]
Hover Text Appears and it gets stuck. Sometimes I take screenshot of what I have updated and again code it. thats how I have been completing my work.

**Comment by shashkiranr** [comment]
I will try to use older version and let you know. I hope you got enough info from logs.

**Comment by stevemessick** [comment]
BTW you should be able to force the files to be written to disk with Cmd-S.
