### ISSUE TITLE
Android Studio device list shows "loading" and no devices connected

### ISSUE THREAD

**Issue by tim-teacher** [flutter/flutter-intellij#4681]
Android Studio device list shows "loading" and no devices connected. I received "Waiting for another flutter command to release the startup lock..." for the latest flutter version. It seems it is the same as https://github.com/flutter/flutter-intellij/issues/3892.

## Steps to Reproduce

Nothing was doing by me. Just opened the project.

## Version info

flutter doctor -v - doesnt work, can't run any flutter command.

Flutter version is 47.1.2

**Comment by Renesanse** [comment]
Try:  https://github.com/flutter/flutter-intellij/issues/4682

**Comment by tim-teacher** [comment]
> Try: #4682
not worked. I fixed it by rebooting laptop...

**Comment by stevemessick** [comment]
This is fixed in the Flutter SDK 1.17.5
