### ISSUE TITLE
Android Studio UI freezes when creating new project

### ISSUE THREAD

**Issue by rs5173** [flutter/flutter-intellij#4683]
It takes a long time to return to normal

**Comment by rs5173** [comment]
Flutter Doctor

C:\Users\Administrator>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.836], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code
[!] Connected device
    ! No devices available

**Comment by rs5173** [comment]
Flutter idea Plugin version is 47.1.2

**Comment by mofengme** [comment]
The same to me. 

#### Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

#### Android Studio version 
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Dart, com.google.services.firebase, io.flutter

#### Flutter Plugin version
47.1.2

#### OS version
MacOS 10.14.6

#### Others
My Idea Ultimate Edition has installed the Flutter plugin And Dart plugin but the `flutter doctor` says not!

**Comment by stevemessick** [comment]
@rs5173, @mofengme a couple questions:

Does this happen every time you create a new project, or just the first time?

Creating a project downloads a bunch of stuff. Is your network overloaded?

It sounds like the project gets created, which points to an issue with downloading.

In case this is useful: https://flutter.dev/community/china

**Comment by mofengme** [comment]
@stevemessick Yes, just the first time!  Even I configuring Flutter to use a mirror site, it will take a  long time when i click ` Start a new  Flutter project` on a new computer.

**Comment by stevemessick** [comment]
Thanks @mofengme. I suggest filing an issue with the [Flutter SDK](https://github.com/flutter/flutter/issues). It seems like it is downloading a lot of stuff as needed, rather than when the SDK is installed. It is hard to provide feedback so people know what is happening. You can use the MacOS Activity Monitor to watch how much data is being transferred.

**Comment by AkshayAvhad** [comment]
I'm facing same issue. My android studio on Windows 11 would freeze on a loading screen when I create a new flutter project. It freezes at same point that is on loading screen every time I create a new flutter project and not only the first time. The only solution I am left with is to force close android studio from task manager. Screen recorded the issue. As video is not uploading I'm providing a google drive link to the video.

Gdrive Link: https://drive.google.com/file/d/1WRNcYJfwvo_AFl2Ew4RsyYV-lcCxIAoV/view?usp=sharing

Was about to create a new issue but found this thread here with the same description with reason that no response from user hence adding comment. Please if anyone from the team sees this and needs a new issue to be created for this just let me know and I'll create a new issue.

Hope the video helps in some or the other way.

####################################################

Following is my Flutter Doctor output. Just for reference if needed.

[√] Flutter (Channel stable, 3.27.3, on Microsoft Windows [Version 10.0.26100.2894], locale en-US)
    • Flutter version 3.27.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c519ee916e (2 weeks ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\aksha\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\Users\aksha\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12508038-b607.1)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12508038-b607.1)

[√] VS Code (version 1.94.2)
    • VS Code at C:\Users\aksha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.2894]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 132.0.6834.160
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.51

[√] Network resources
    • All expected network resources are available.

####################################################

Thank you in advance.

**Comment by emir9922** [comment]
I have same problem how can I fix
