### ISSUE TITLE
Android java sub-project intellij/Android studio cannot resolve imports.

### ISSUE THREAD

**Issue by vekexasia** [flutter/flutter-intellij#4696]
It seems i cannot edit java code with proper intellisense due to imports failing. Not sure what is wrong with that and project structure does not show anything "wrong"?

## Steps to Reproduce
Just create a new project with flutter (java) not sure if kotlin has the same issue.

_Please tell us what you were doing and what went wrong_
![image](https://user-images.githubusercontent.com/200523/87163806-36fcb400-c2c8-11ea-879e-d3754440c11c.png)

## Version info

[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.1.pre at /home/andrea/git/flutter
    • Framework revision f994b76974 (4 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/andrea/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/andrea/android-sdk
    • Java binary at: /home/andrea/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/andrea/Desktop/android-studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • Pixel 3a   • 9B9AY1HXDU • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

**Comment by stevemessick** [comment]
Open Settings > Flutter. Enable the experimental option that turns on indexing of Java and Kotlin.
