### ISSUE TITLE
Support Go To  → Super method

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter-intellij#4700]
`Go To → Declaration or usages` (cmd/ctrl + click, cmd/ctrl + b) works great and I use it all the time. It's very useful to quickly navigate code.

`Go To  → Super method` is not yet supported. It would be a welcome addition because documentation is almost always written with the super method. 

| File a | File b  |
|---|---|
| ```   @override void doX() {...}```|   ``` // This method does X. Side effects are...``` <br /> ```void doX()```  |

Navigating from File a to File b is currently a manual and cumbersome, especially dealing with large, complex classes.

**Comment by stevemessick** [comment]
What exactly is not supported? It works for me. Both the context menu (in the editor) and the green-circle-arrow icon in the left gutter do this.

If there really is something missing you'll have better success filing an issue at youtrack.jetbrains.com. This is functionality implemented by the Dart plugin.

**Comment by guidezpl** [comment]
Ahh thanks. For some reason I had the gutter icons disabled.
