### ISSUE TITLE
Will the flutter support a layout similar to Android ConstraintLayout with a visual editor, That would be great!

### ISSUE THREAD

**Issue by zeplee** [flutter/flutter-intellij#4701]
Will the flutter support a layout similar to Android ConstraintLayout with a visual editor,
That would be great! It will greatly reduce the number of unaccountable UI errors, for example, sometimes reporting errors is simply a matter of using fewer widgets. And this feature makes layout easier, so developers don't have to worry about a lot of widgets
https://github.com/flutter/flutter/issues/59040

**Comment by stevemessick** [comment]
Dup of #2347
