### ISSUE TITLE
Running the flutter framework tests fails with 'Directory is not in a pub root'

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter-intellij#4707]
## Steps to Reproduce

I am using IntelliJ IDEA to work in the flutter framework itself and have a run configuration setup to run all the tests for the framework. However, it recently stopped working and the configuration dialog has the error 'Directory is not in a pub root'. I don't fully understand this error, as there is a pubspec.yaml in the parent directory of the test folder. Is there some other mechanism that defines the directory as a pub root? The configuration looks like:

<img width="746" alt="Screen Shot 2020-07-20 at 6 48 37 PM" src="https://user-images.githubusercontent.com/19588/88003410-ab4e0900-cab9-11ea-9198-a379c005f7cd.png">

I can run the tests fine from the command line, so I am not sure what is going on here. Not sure if it matters, but IDEA project was generated with the `flutter ide-config --overwrite` command.

## Version info

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.21.0-2.0.pre.66 at /Users/darren/dev/flutter
    • Framework revision 54c9441723 (3 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/darren/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.8538.45

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.5 19F101

• No issues found!
```

**Comment by stevemessick** [comment]
This sounds like #4692. If so, it is fixed in the [dev channel](https://github.com/flutter/flutter-intellij/wiki/Dev-Channel).

**Comment by ivan-horchakov** [comment]
I've also faced this issue trying to create the "All in directory" Flutter Test run configuration. 

My version info:
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/ivan_horchakov/development/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ivan_horchakov/Android
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by lagivan** [comment]
I'm facing the same issue on the latest Android Studio (Build #AI-221.6008.13.2211.9514443, built on January 21, 2023).

I have a multi-package project, e.g.:
```
project-root
- package1
-- test
- package2
-- test
```

So it seems multi-package projects are not supported.

**Comment by JulianBissekkou** [comment]
Can someone reopen this?

**Comment by madicd** [comment]
I also have a multi-package project. Opening directly one of the packages as an Android studio project allowed me to run all tests from the test directory.

**Comment by mateusfccp** [comment]
I am also having this issue with multi-package project.
