### ISSUE TITLE
AndroidSutdio can not recognize flutter sdk in latest idea-flutter-plugs

### ISSUE THREAD

**Issue by s949492225** [flutter/flutter-intellij#4708]
androidStudio 4.0.1 can not recognize flutter sdk ,dart sdk,I do manual configuration is also not recognized.
This is a serious bug.
This bug will cause the latest version of androidStudio to fail to run project Flutter. Please update the plugin as soon as possible to fix this problem.

flutter run doctor -v 

![image](https://user-images.githubusercontent.com/7496283/88028404-34714880-cb6b-11ea-98e9-41140ba0aa8a.png)

**Comment by helin24** [comment]
Thanks for the report - unfortunately I cannot reproduce the problem with your settings. Could you have a slightly different build of Android Studio 4.0? Below is mine:
<img width="641" alt="Screen Shot 2020-07-21 at 9 24 38 AM" src="https://user-images.githubusercontent.com/6379305/88080547-12100880-cb34-11ea-9e41-6187c5ed5693.png">

You could try uninstalling and reinstalling both plugins or Android Studio itself. If you have any other additional logs reflecting the bug, that could be helpful too.

**Comment by stevemessick** [comment]
I have Android Studio 4.0.1 and Flutter stable 1.17.5. Everything works as expected.

**Comment by s949492225** [comment]
![image](https://user-images.githubusercontent.com/7496283/88122448-371b7e80-cbfb-11ea-9917-38422a1db6ad.png)

**Comment by s949492225** [comment]
In addition to this problem, the plug-ins within IntelliJ IDEA have not been identified.

**Comment by s949492225** [comment]
The problem did exist, but no error was found

**Comment by helin24** [comment]
@s949492225 since we're unable to reproduce this issue, I don't think there's anything else we can suggest, other than completely reinstalling Android Studio and potentially trying different versions.
