### ISSUE TITLE
Missing create flutter project in latest version of Android Studio plugin

### ISSUE THREAD

**Issue by mingsai** [flutter/flutter-intellij#4709]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Update Android Studio to 4.0.1
Update Flutter plugin to 47.1.2
Open Android Studio to create new flutter project
Found the Create New Flutter Project option is no longer listed on the startup dialog

**Current Workaround**
Workaround create flutter on command line
Import project from Gradle,...

## Version info

[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Mac OS X 10.15.6 19G73,
    locale en-US)
    • Flutter version 1.21.0-2.0.pre.66 at /opt/flutter
    • Framework revision 54c9441723 (4 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0-rc2)
    • Android SDK at /opt/android/sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • ANDROID_HOME = /opt/android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.89

**Comment by stevemessick** [comment]
I cannot reproduce this problem.

<img width="664" alt="Screen Shot 2020-07-21 at 8 48 54 AM" src="https://user-images.githubusercontent.com/8518285/88076631-2a315900-cb2f-11ea-9dbd-a59e54e1f5f2.png">

You can try deleting and re-installing the plugin.

**Comment by fairholmed** [comment]
You may need the flutter plugin.  Try going to Plugins -> Marketplace -> search for Flutter and install this and Dart.  Then restart android studio
