### ISSUE TITLE
Flutter (attach) expects NO_PROXY Environment Variable to be comma separated list on Windows.

### ISSUE THREAD

**Issue by rakeshdn** [flutter/flutter-intellij#4716]
While launching a flutter app from Android Studio , the flutter attach stage failed 
with a HttpException complaining about a failure to upgrade to websocket for connection 
to Dart observatory url  on the loopback address 127.0.0.1
The end result is that flutter inspector,outline and performance tabs remain blank 
and hot reload buttons stay disabled. 

To get this to work ( unfortunately after wasting two days searching forums and trying many things.. ) 
I had to change NO_PROXY windows system environment variable value from 
127.0.0.1;localhost to 
127.0.0.1,localhost.
Windows convention is to separate tokens with semicolons rather than commas. 
So this is likely to break other windows applications.

Note that Flutter doctor -v is happy with either comma or semicolon, and does not report any issues.

The root cause of problem could be the hard coded "," in code below  (from http_impl.dart)
being new to Flutter and Dart, I am not even sure whether the code below is being used....

```
static String _findProxyFromEnvironment(
      Uri url, Map<String, String> environment) {
    checkNoProxy(String option) {
      if (option == null) return null;
      Iterator<String> names = option.split(",").map((s) => s.trim()).iterator;
```

Other related issues: (but not Windows specific) 
https://github.com/flutter/flutter/issues/25112
https://github.com/flutter/flutter/issues/16875
https://github.com/flutter/flutter/issues/52096

My tool chain version details below.

Microsoft Windows [Version 10.0.18362.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\sesa319166\AndroidStudioProjects\mi_card_flutter>flutter doctor -v
[√] Flutter (Channel @u, v1.17.5, on Microsoft Windows [Version 10.0.18362.836], locale en-GB)
    • Flutter version 1.17.5 at C:\flsdk\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\sesa319166\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\sesa319166\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

• No issues found!

**Comment by helin24** [comment]
Thanks for this report! I'm not sure if this is an IDE issue or a Flutter issue. The lines you mentioned are in Flutter, but I also see `urllib.py` in the plugin, which includes:
```
    # check if the host ends with any of the DNS suffixes
    no_proxy_list = [proxy.strip() for proxy in no_proxy.split(',')]
```

Are you able to run flutter attach in the CLI or in VSCode?

**Comment by rakeshdn** [comment]
Once I change no_proxy to be comma separated (or override it using set noproxy=127.0.0.1 within the shell) I can run flutter attach from CLI.  I am not using VSCode for development at the moment. Thanks.

**Comment by helin24** [comment]
Okay, thanks for the detail. I suspect if the CLI doesn't work until you change your NO_PROXY comma, then this should be moved to the flutter repo.
