### ISSUE TITLE
asemble debug exit code -1

### ISSUE THREAD

**Issue by ahmedmohiuddinkabir** [flutter/flutter-intellij#4717]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by ahmedmohiuddinkabir** [comment]
every time flutter not able to find android sdk folder but when i run tools/sdkManager from android studio it shows sdk uptodate

**Comment by helin24** [comment]
Is this the problem you're having? https://stackoverflow.com/questions/49175231/flutter-does-not-find-android-sdk

Please let us know if you've already tried that fix (or any other fixes) and attach the output from `flutter doctor -v` if you're still having problems.
