### ISSUE TITLE
Plugin is constantly having bugs

### ISSUE THREAD

**Issue by crtl** [flutter/flutter-intellij#4726]
## Steps to Reproduce

I am having a couple of issues, I dont know when they started nor do I have any reliable debug information (which is another issue).
The plugin crashes constantly and I have to manually kill the process or restart linting for it to work.
Most times when I create an interface the only method to generate these signatures in the actual implementation is to click on the classname and select the dialog options which are shown by android studio (Select classname > Alt + Enter > Create X missing overrides).
"Implement methods" (STRG + I) and
"Override methods" (STRG + O) are also not working (No methods found to override / implement).

In every example I have tried to create for this issue, it is working.
So it seems to be related to my project or maybe some fragments from earlier versions but I cannot get any debug information or help except this issue board.

Ive tried this on channels `master` and `stable`. Both are not working.

## Version info

```

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-DE)
    • Flutter version 1.17.5 at D:\dev\flutter\sdk
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)


```

**Comment by stevemessick** [comment]
I believe this is tracked as https://youtrack.jetbrains.com/issue/WEB-40469

**Comment by devoncarew** [comment]
@crtl, thanks for the report. I believe that the above issue covers the overrides problem you described. I'm closing this issue as a dup; if there are other aspects of this issue you'd like to track, can you re-file as separate issues? Thanks!

**Comment by crtl** [comment]
Thanks for your answer.
Arent flutter dev tools etc. developed by flutter team?
How can the IntelliJ be responsible for it?

Also from other issues related to code competion:

> These actions are called Quick Fixes. They come from the Dart Analysis Server, a tool from the Dart SDK. IDE only does what server asks it to do. So the fix should be implemented on the server end it will apper in the IDE as soon as it is implemented there. Please file a request in https://github.com/dart-lang/sdk/issues/.
