### ISSUE TITLE
Create a New Flutter Project wizard missing in Android Studio 4.0.1

### ISSUE THREAD

**Issue by teekamsuthar** [flutter/flutter-intellij#4727]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

Since the Android Studio 4 got released, the startup dialog is missing the option to create a new flutter project in my android studio. I've tried all of the solutions mentioned here

[new-flutter-project-wizard-not-showing-on-android-studio-3-0-1](https://stackoverflow.com/questions/49405321/new-flutter-project-wizard-not-showing-on-android-studio-3-0-1)

But still no luck! All plugins are updated and enabled in android studio.

## Version info
```
Flutter plugin -> 47.1.2
Dart Plugin -> 193.7361
```

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

```
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.0-7.2.pre at C:\src\flutter
    • Framework revision a2bde82fbd (11 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\teeka\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\teeka\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\teeka\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 83.0.478.61

• No issues found!
```

**Comment by stevemessick** [comment]
I cannot reproduce this problem. I have Android Studio 4.0.1 and Flutter plugin 47.1.2. 

You must have a local configuration issue. A lot can go wrong with IntelliJ (and therefore Android Studio). The stackoverflow link you provided has a *lot* of suggestions. Double-check that you tried everything.

**Comment by teekamsuthar** [comment]
> I cannot reproduce this problem. I have Android Studio 4.0.1 and Flutter plugin 47.1.2.
> 
> You must have a local configuration issue. A lot can go wrong with IntelliJ (and therefore Android Studio). The stackoverflow link you provided has a _lot_ of suggestions. Double-check that you tried everything.

Yes, I am sure. I've tried each and every solution provided on stackoverflow.com. This was not happening before Android Studio v4 released.

**Comment by teekamsuthar** [comment]
Okay, Fixed this by deleting old android studio config folder and letting it create a new one in next launch.

**Comment by aghazadehm** [comment]
This solution worked to me 
https://stackoverflow.com/a/55221639/7080431

**Comment by codemaker2015** [comment]
If you are sure to have both Dart and Flutter plugins correctly installed, check again your Plugins and be sure that Android APK Support is enabled. If not then enable it.

For more: https://stackoverflow.com/questions/49405321/new-flutter-project-wizard-not-showing-on-android-studio-3-0-1
