### ISSUE TITLE
Code completion for extension methods

### ISSUE THREAD

**Issue by ChessMax** [flutter/flutter-intellij#4729]
It would be nice to have completion for Dart extension methods. Now it works only (I think so, but I'm not 100% sure) if the specified extension has been imported. It would be much better if completion would show all extension methods with auto-import selected extension.

**Comment by tbm98** [comment]
pls upvote this issue here https://github.com/dart-lang/sdk/issues/42359

**Comment by ChessMax** [comment]
Upvoted)

**Comment by tbm98** [comment]
@ChessMax I was created a similar issue https://github.com/flutter/flutter-intellij/issues/4627 and it is moved to https://github.com/flutter/flutter-intellij/issues/4729

**Comment by ChessMax** [comment]
I see

**Comment by devoncarew** [comment]
Thanks for the feedback! Closing in favor of https://github.com/dart-lang/sdk/issues/42359.
