### ISSUE TITLE
IDE not update/reindexing when a file is generated by generator plugin

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter-intellij#4731]
## Steps to Reproduce

When I coding, usually I also open a terminal tab and run `flutter pub run build_runner watch --delete-conflicting-outputs`

problem appear when a file is generated but IDE was not detected it.

only solution right now is restart  IDE for it reindexing new files.

in vscode, just click to open file that is generated and it work.

**Comment by tbm98** [comment]
I found reason. My analysis_options.yaml has exclude *.g.dart and *.
freezed.dart. just disable exclude and it will work

Vào 0:50, Th 3, 4 thg 8, 2020 Phil Quitslund <notifications@github.com> đã
viết:

**Comment by pq** [comment]
Ah.   Fantastic.  Thanks  for  following  up @tbm98!
