### ISSUE TITLE
Missing File / Project Structure when opening vscode created flutter project

### ISSUE THREAD

**Issue by abulka** [flutter/flutter-intellij#4736]
Opening an exiting Flutter project (created in vscode) results in a project without a File / Project Structure menu item, meaning certain functionality e.g. Opening Device File Explorer etc. fails.

## Steps to Reproduce

1. In vscode, CMD SHIFT P, flutter new project. This creates a new flutter project which can be run etc.
2. Close vscode, In Android Studio File / Open the directory created above.
3. Notice File / Project Structure is missing.  

whereas if the flutter project is created inside Android Studio in the first place, File / Project Structure does exist.

## Version info

```
$ flutter doctor -v
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.14.6 18G6020, locale en-AU)
    • Flutter version 1.20.0-3.0.pre at /Users/andy/Devel/flutter
    • Framework revision 0af027f805 (4 weeks ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/andy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/Andy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/Andy/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • Mac OS X 10.14.6 18G6020
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

**Comment by pq** [comment]
Hmmmm... I believe there are a few ways to import sources and at least one should create IntelliJ's expected metadata.

Maybe @stevemessick or @alexander-doroshko can advise?

**Comment by stevemessick** [comment]
I don't have vscode so I cannot directly reproduce this problem. However, using `flutter create` to create a project does seem to cause this problem to occur in Android Studio stable and beta. It works as expected in the canary build. I'm not going to investigate further.

**Comment by alexander-doroshko** [comment]
There might be some special logic in Android Studio regarding Project Structure item presence in the main menu. As far as I know, the item is always there in IntelliJ IDEA, regardless of the way the project has been created.

There are other ways to open Project Structure: using a direct shortcut, and using Help -> Find Action. Anyway, I think we should investigate whether it's Android Studio-specific and what's the underlying reason.

**Comment by stevemessick** [comment]
@alexander-doroshko This is specific to Android Studio. It adds the `ProjectSystem` concept and makes this menu item dependent on having a proper kind of project system. Since it works properly for projects created in Android Studio and works for other projects in the canary build I'm not going to pursue this unless it starts breaking in the canary build.

Leaving it open as a reminder to continue checking the canary build.

**Comment by jacob314** [comment]
It looks like we have another user reporting the same issue. Did something regress?

**Comment by stevemessick** [comment]
From the M48 release notes:
> In Android Studio Beta 5 and later the Project Structure item is missing from the File menu.

It is not a problem for stable and canary.

**Comment by abulka** [comment]
The Andoid studio I was using which has the issue is

```
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, com.google.services.firebase, io.flutter
```

which presumably is stable?  

I just tried it again `flutter create junk11` then opened in the newly created project in Android Studio 4.0.1 and cannot see the Project Structure menu item.

**Comment by fnicastri** [comment]
Even if you create the project thru Studio 4.1 Beta the project structure is not present.
It's not about how you create the project.

**Comment by stevemessick** [comment]
Android Studio added the concept of Project System back in version 3.3 or 3.4. The `Project Structure` menu was hidden if the current project system was not what they expected to see. I added a work-around to make it visible for projects created in Android Studio. Projects created outside AS haven't shown that menu for a year or so. The work-around broke in 4.1. In 4.2 they stopped hiding that menu item, so it is no longer even needed.

**Comment by fnicastri** [comment]
> Android Studio added the concept of Project System back in version 3.3 or 3.4. The `Project Structure` menu was hidden if the current project system was not what they expected to see. I added a work-around to make it visible for projects created in Android Studio. Projects created outside AS haven't shown that menu for a year or so. The work-around broke in 4.1. In 4.2 they stopped hiding that menu item, so it is no longer even needed.

Are you saying that this issue will not be addressed?
