### ISSUE TITLE
ANSI support in console

### ISSUE THREAD

**Issue by vmeretin** [flutter/flutter-intellij#4743]
## Steps to Reproduce
* I'm using this package https://pub.dev/packages/ansicolor

* And print with this function

```
 String _colorMessage(LogLevel logLevel, String message) {
    AnsiPen pen;
    switch (logLevel) {
      case LogLevel.error:
        pen = AnsiPen()..red();
        break;
      case LogLevel.warning:
        pen = AnsiPen()..yellow();
        break;
      case LogLevel.debug:
        pen = AnsiPen()..white();
        break;
      case LogLevel.trace:
        pen = AnsiPen()..gray(level: 0.5);
        break;
    }

    return pen(message);
  }
```

* "Run" tool window

<img width="1190" alt="Снимок экрана 2020-08-05 в 22 24 23" src="https://user-images.githubusercontent.com/10262963/89449787-a308f580-d76a-11ea-88dc-b755ba1f026a.png">

* `flutter logs`

<img width="1190" alt="Снимок экрана 2020-08-05 в 22 24 36" src="https://user-images.githubusercontent.com/10262963/89449862-bd42d380-d76a-11ea-8d7b-0d7f2d9461d0.png">

## Version info

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale ru-RU)
    • Flutter version 1.17.5 at /Users/vmeretin/dev/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/vmeretin/dev/android-sdk/
    • Platform android-29, build-tools 30.0.1
    • ANDROID_HOME = /Users/vmeretin/dev/android-sdk/
    • ANDROID_SDK_ROOT = /Users/vmeretin/dev/android-sdk/
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 2207B74B-0056-43BB-A0AD-6B97703D8176 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

**Comment by pq** [comment]
I think this is a limitation of the core IntelliJ console (see for example, https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000172019-IDEA-Run-Debug-Console-not-displaying-RGB-Ansi-codes-correctly-) but maybe @alexander-doroshko knows more?

/fyi @devoncarew

**Comment by alexander-doroshko** [comment]
@pq @devoncarew For Dart Test and Dart Command Line App run configurations, it was fixed by using `ColoredProcessHandler` instead of `OSProcessHandler`. See this commit: https://github.com/JetBrains/intellij-plugins/commit/7c61483984e702013f794ce0600870267adfca09.

**Comment by pq** [comment]
Fantastic.  Thanks!

**Comment by KlausJokinen** [comment]
Any news on this?

**Comment by devoncarew** [comment]
From looking at this, it will require changes to the Flutter plugin (minor changes, as outlined by @alexander-doroshko above), as well as changes to the flutter command line tool. Somewhere in the pipeline it looks like we're escaping the escape char (into `\^`?), so the ansi handling in the `ColoredProcessHandler` class doesn't have the right info to act on.

As part of fixing the escaping issue, we can probably also do something about the leading `flutter: ` text on print output from flutter apps.

**Comment by AlexV525** [comment]
If there are more issues about the ANSI handling, please file new issues and let me know, thanks! Before that, enjoy the colorful console. :-)

**Comment by danielgomezrico** [comment]
It is now working great, thanks! 👍🏻

**Comment by neoRiley** [comment]
@danielgomezrico could you tell *how* you got it working?  I've installed the ansicolor plugin, copied the example code and this is what I see: 
![image](https://user-images.githubusercontent.com/138747/109102570-c9828400-76ee-11eb-8ee5-9a79d7ef2713.png)

Samples / insight on how to get this working would be greatly appreciated - thanks in advance

**Comment by AlexV525** [comment]
iOS has a different console IMO, so on Android it works fine currently.

**Comment by danielgomezrico** [comment]
@AlexV525 I dont have that plugin, I just updated intellij and the flutter plugin and the console shows colors

**Comment by neoRiley** [comment]
@danielgomezrico Hey thanks for the reply - wondering if you could tell me if you're on Mac or PC and what version IntelliJ you're running?  Thanks again

**Comment by neoRiley** [comment]
@danielgomezrico also, I hate to bug you - but can you post an example of your your sending colored output to the console?

**Comment by KlausJokisuo** [comment]
@neoRiley 
Does this work for you ` print("\x1B[38;5;${10}m Green foreground text");`

**Comment by neoRiley** [comment]
@KlausJokisuo no, this is what I see with that: 
![image](https://user-images.githubusercontent.com/138747/109274969-b7314480-77d9-11eb-92f3-74e56aaebf5f.png)

**Comment by KlausJokisuo** [comment]
> @KlausJokisuo no, this is what I see with that:
> ![image](https://user-images.githubusercontent.com/138747/109274969-b7314480-77d9-11eb-92f3-74e56aaebf5f.png)

What Flutter Plugin version you have? I'm using 53.1.5

**Comment by neoRiley** [comment]
@KlausJokisuo Same 53.1.5 - Gotta be something simple, right?

**Comment by KlausJokisuo** [comment]
> @KlausJokisuo Same 53.1.5 - Gotta be something simple, right?

@devoncarew Can this be because he/she is using Mac?

**Comment by neoRiley** [comment]
@devoncarew yes (he) I'm on Mac - Is that the issue?

**Comment by neoRiley** [comment]
Hey I appreciate everyone's help and patience, thanks very much for that.  In the end, I'm guessing being on Mac is the issue, so I went after [Grep Console](https://plugins.jetbrains.com/plugin/7125-grep-console) and that's actually working decently well.  

To anyone else coming across this on a Mac - I'm using IntelliJ IDEA Ultimate 2020.3, but I assume this works with Android Studio as well:
1.  Install Grep Console Plugin
2. In the output console, right click and choose "Grep" - this will bring up a tab that has an "Expression" field, type "flutter:" in there and hit "Apply".  You'll now see all of the flutter console logging in this new tab.  
3. Add colors to possible string values in the Grep Console Settings.  I added a ton that I use for logging in Unity.  
4. Then, to see the color, just append the string value to your print() call: `print("My test message [ORANGE]");`
 
It's the entire line and I you have to live with "[colorName]" at the end of your statements, but it does work.

![image](https://user-images.githubusercontent.com/138747/109383396-eadc9f00-78ab-11eb-8109-57a881e94b6d.png)

**Comment by sososdk** [comment]
Android only 😂 . @neoRiley

**Comment by kasperpeulen** [comment]
For me, this seems more like a flutter issue.

Running the following, both in the terminal:
```dart
void main() {
  print("\x1B[38;5;${10}m Green foreground text");
}
```
![image](https://user-images.githubusercontent.com/1035299/112821035-879a8400-9086-11eb-85da-37eecf4d4086.png)

**Comment by AlexV525** [comment]
iOS console is not following the standard console sequence. So there won't be any native colored output come out when you're running with iOS devices.
