### ISSUE TITLE
Unable to run Flutter test in Android Studio 4.0.1 / flutter plugin 48.0.2

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter-intellij#4750]
## Steps to Reproduce

Right click on the Flutter test and select "Debug '<test name>'"

## Expected behavior

You expect the test to run.

## Actual behavior

```
Testing started at 7:17 PM ...
/path/to/flutter/bin/flutter --no-color test --machine --start-paused test/widget_test.dart
Your Flutter application is created using an older version of the Android embedding. It's being deprecated in favor of Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration to migrate your project.
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.

Failed to connect to the VM observatory service at: ws://127.0.0.1:53074/JBcmmNfapt4=/ws
java.io.IOException: Failed to connect: ws://127.0.0.1:53074/JBcmmNfapt4=/ws
Caused by: de.roderick.weberknecht.WebSocketException: connection failed: unknown status code 302
```

## Version info

Android Studio 4.0.1

```
[✓] Flutter (Channel master, 1.21.0-7.0.pre, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.21.0-7.0.pre at /Users/tvolkert/project/flutter/flutter
    • Framework revision d261f1ef58 (6 days ago), 2020-08-03 00:59:36 -0400
    • Engine revision 083282e33b
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 365525432a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tvolkert/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode_11.6.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

## Other info

I verified in my run configurations that the configuration in question is a "Flutter Test".

**Comment by devoncarew** [comment]
This:

> Failed to connect to the VM observatory service at: ws://127.0.0.1:53074/JBcmmNfapt4=/ws
> java.io.IOException: Failed to connect: ws://127.0.0.1:53074/JBcmmNfapt4=/ws
> Caused by: de.roderick.weberknecht.WebSocketException: connection failed: unknown status code 302

Indicates to me that perhaps DDS has been enabled in the flutter repo - see the `status code 302` portion. cc @bkonyi 

You're on `d261f1ef58 (6 days ago)` - can you try syncing to another commit and see if that works?

Ben, if this is related to DDS, that likely indicates that the websocket library we're using in IntelliJ does not support http redirects. We can look for a different websocket library to use, but I think that generally we'll want to consider handing the DDS url to `flutter run` / `flutter test` clients by default. Happy to talk through the implications of that - to see if we can solve the edge cases w/ flutter attach and such.

**Comment by bkonyi** [comment]
> Ben, if this is related to DDS, that likely indicates that the websocket library we're using in IntelliJ does not support http redirects. We can look for a different websocket library to use, but I think that generally we'll want to consider handing the DDS url to `flutter run` / `flutter test` clients by default. Happy to talk through the implications of that - to see if we can solve the edge cases w/ flutter attach and such.

DDS shouldn't be enabled in the Flutter repo right now (it was disabled in https://github.com/flutter/flutter/pull/62508 12 days ago), so that shouldn't be it unless I disabled it incorrectly. Do you happen to have verbose logs @tvolkert? If DDS is enabled, it'll be mentioned in the logs. If it's not, there should be a warning message printed with a link to an issue.

**Comment by bkonyi** [comment]
This appears to happen when attempting to connect via Observatory as well.

**Comment by bkonyi** [comment]
Ah this is the one case I forgot to remove that Mehmet fixed in https://github.com/flutter/flutter/pull/62792. @tvolkert if you pull to a newer branch this should be resolved.

**Comment by devoncarew** [comment]
@bkonyi - thanks for looking into this!

@tvolkert - I did verify that I don't see this behavior on flutter master at head.

**Comment by tvolkert** [comment]
(closing old tabs). I verified that I can no longer repro this against ToT with updated plugin.  Thanks!
