### ISSUE TITLE
Web Server run configuration hangs

### ISSUE THREAD

**Issue by noelmansour** [flutter/flutter-intellij#4751]
## Steps to Reproduce

1. Create flutter project (using flutter beta channel)
2. Select "Web Server" run configuration
3. Run

It seems to hang while waiting for a connection:
```
Launching lib/main.dart on Web Server in debug mode...
Syncing files to device Web Server...
Waiting for connection from Dart debug extension at http://localhost:58974
```

Note that the CLI equivalent works fine:

`flutter run -d web-server`

## Version info

Note: I tested this with IntelliJ (not Android Studio)

[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.5 19F101, locale en-CA)
    • Flutter version 1.20.0 at /Users/noel/dev/flutter
    • Framework revision 916c3ac648 (8 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Users/noel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6392135/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/noel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Users/noel/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 48.0.3
    • Dart plugin version 201.8538.45

[✓] Connected device (4 available)
    • Pixel 2 (mobile)         • FA7A21A02351              • android-arm64  • Android 10 (API 29)
    • Noel’s iPad (2) (mobile) • 00008027-000E38D63AE3002E • ios            • iOS 13.6
    • Web Server (web)         • web-server                • web-javascript • Flutter Tools
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 84.0.4147.105

• No issues found!

**Comment by stevemessick** [comment]
@helin24 could this be related to the `--start-paused` mods?

**Comment by helin24** [comment]
It seems likely, I'll look into this.
