### ISSUE TITLE
Im trying to generate a variable for the controller field of my TextField widget , it is generated as var not as TextEditingController.

### ISSUE THREAD

**Issue by harisvm** [flutter/flutter-intellij#4760]
![Annotation 2020-08-13 141302](https://user-images.githubusercontent.com/39512292/90122886-a0fef200-dd7b-11ea-9705-88d7aa32d391.jpg)
![Annotation 2020-08-13 141242](https://user-images.githubusercontent.com/39512292/90122954-b7a54900-dd7b-11ea-9e61-fdd1a7947ddc.jpg)

**Comment by jacob314** [comment]
Thanks for filing the bug. This is a good polish case for us to get right. We know what type newController should have so we should do a better job than just generating `var`.
