### ISSUE TITLE
Flutter 48.1.2 plugin is not installing in Android Studio

### ISSUE THREAD

**Issue by pluzmedia** [flutter/flutter-intellij#4764]
Hi,

Flutter 48.1.2 plugin is not installing in Android Studio. It keeps asking me to configure plugin is not detecting after restart.

Android Version: 4.0.1

**Comment by stevemessick** [comment]
Using Android Studio 4.0.1 I just did these steps:
- Uninstall the Flutter plugin
- Restart the IDE
- Install the Flutter plugin
- Restart the IDE

I have Flutter version 48.1.2 installed now. I suggest trying those steps. If that doesn't help then attach a screen shot of the UI when it asks to configure plugin and attach the output of CLI command `flutter doctor -v`.

**Comment by pluzmedia** [comment]
Plugin is not installing correct directory, I have changed config & system path in idea.properties.

**Comment by stevemessick** [comment]
Sorry, but you'll need to contact [JetBrains](https://youtrack.jetbrains.com/issues) for support. We don't control the installation process.
