### ISSUE TITLE
packages folder is added as ignored in "Project Structure -> Modules"

### ISSUE THREAD

**Issue by angelcervera** [flutter/flutter-intellij#4768]
I'm following a few tutorials like [bloclibrary.dev](https://bloclibrary.dev/#/flutterlogintutorial) where `packages` folder is used to group local packages used by the application.

The issue is that every time that `flutter pub get` is executed, IntelliJ/Android Studio adds the `packages` folder into `Project Structure -> Modules -> Excluded Folders` so the code is not included in the source.

## Steps to Reproduce
1. Create a project flutter project.
2. Create a folder `packages`
3. From inside of that folder, create a flutter package. For example: `flutter create --template package pack1`
4. Add the package into the main `pubspec.yaml`. For example: 
    ```
   dependencies:
     flutter:
       sdk: flutter
     auth_repository:
       path: packages/pack1
    ```
5. From the root of the project, execute `flutter pub get`
6. Regress the project in IntelliJ/Android Studio with `reload from Disk` option, for example.
7. Check `Project Structure -> Modules -> Excluded Folders` and `packages` folder will be in the list of the excluded folders.

## Version info
```
/home/angelcc/apps/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, 1.20.0, on Linux, locale en_IE.UTF-8)
    • Flutter version 1.20.0 at /home/angelcc/apps/flutter
    • Framework revision 916c3ac648 (3 weeks ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/angelcc/apps/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_SDK_ROOT = /home/angelcc/apps/Android/Sdk
    • Java binary at: /home/angelcc/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/angelcc/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server (web)             • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

**Comment by alexander-doroshko** [comment]
For the reference, the same request: https://github.com/flutter/flutter-intellij/issues/4383

**Comment by alexander-doroshko** [comment]
Fixed. The latest Dart plugin won't change `packages` folder exclusion state automatically. Users may exclude or unexclude `packages` folders manually as needed.
