### ISSUE TITLE
Create project using 'New Flutter Application', 'Flutter SDK PATH' cannot be identified

### ISSUE THREAD

**Issue by guominfang** [flutter/flutter-intellij#4770]
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.20.2 at /Users/mac/Library/Flutter/flutter
    • Framework revision bbfbf1770c (8 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```
Create project using 'New Flutter Application', 'Flutter SDK PATH' cannot be identified.

This causes' Module flutter_app_android: invalid item 'Flutter for Android' in the dependencies list 'in' Project Structure '->' Problems'.

![image](https://user-images.githubusercontent.com/24568042/90945369-0ecfab80-e457-11ea-9876-802b9ebd74e8.png)
![image](https://user-images.githubusercontent.com/24568042/90945381-227b1200-e457-11ea-9fac-ed52caf18c12.png)
![image](https://user-images.githubusercontent.com/24568042/90945399-36267880-e457-11ea-9373-b7c49232d489.png)

**Comment by jacob314** [comment]
Fyi @stevemessick

**Comment by stevemessick** [comment]
@guominfang What happens if you type `flutter precache` in a terminal?

**Comment by galloperx** [comment]
@stevemessick I'm having almost exactly same problem on Windows (though at this point I don't think it has anything to do with the OS), flutter precache didn't help.

Please note that there are SO questions popping up in August that also point at such problem, like these:
https://stackoverflow.com/questions/63567088/how-do-i-fix-a-flutter-for-android-issue
https://stackoverflow.com/questions/63533922/module-example-android-invalid-item-flutter-for-android-in-the-dependencies-l
https://stackoverflow.com/questions/63475619/invalid-item-flutter-for-android-in-the-dependencies-list

So it's not like a single case thing.

**Comment by guominfang** [comment]
run flutter precache.
![image](https://user-images.githubusercontent.com/24568042/91634668-981d4a00-ea24-11ea-8a70-509e771ff7c3.png)

And setting：
Android stuido -> Flie -> Invalidate and Restart.
The problem remains

**Comment by stevemessick** [comment]
@guominfang Thanks for the update. I have two follow-up questions.

First, can you give me more information about this symptom?
> 'Flutter SDK PATH' cannot be identified.

I'm not sure what that means. Another screen shot would probably help.

Second, since MacOS treats ~/Library specially, could you try installing the Flutter SDK in a different place, just to see if Flutter is getting tripped up by the special directory?

**Comment by guominfang** [comment]
@stevemessick 
Create a flutter project using Android Studio. The  `Flutter  SDK` is not recognized in these Windows.
![image](https://user-images.githubusercontent.com/24568042/91737033-1fafb800-ebe1-11ea-87e9-ad3a4b98c187.png)

=====================
I have tried to migrate the 'Flutter SDK' to the ~ / flutter/flutter directory. The problem remains.

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale
    zh-Hans-CN)
    • Flutter version 1.20.2 at /Users/mac/flutter/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by stevemessick** [comment]
@guominfang Thanks for the info. I'm not sure this is actually a problem. Those errors have been there since the plugin was created. There is an experimental option that causes them to go away, but the recommended way to edit Android code is to open the Android module as a project in its own window.

Does your Flutter app run? If it runs then this is working as expected (not as wanted, but it's a compromise).

**Comment by galloperx** [comment]
@stevemessick Not to highjack the discussion, but since I get same errors, I'd like to add that my Flutter app runs indeed, but ONLY if I remove
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
in manifest. Otherwise I can't use any of the Java code that I need for my app (which is in Flutter), with those lines present I can't use MethodChannel, nothing is recognized and it's a cascade of errors. Comment those two lines out - everything just works. As a side note: yes, almost everything is still red in the MainActivity.

**Comment by stevemessick** [comment]
@galloperx If that <meta-data> tag is something added by Flutter then you should report it to the Flutter repo, flutter/flutter. It wasn't added by the IDE (unless I forgot something).

**Comment by guominfang** [comment]
@stevemessick 
Yes, my Flutter App is working normally, only showing red in 'Flutter Project Window'

**Comment by stevemessick** [comment]
Thanks for the confirmation. I'm closing this because we've already published the work-around (open the Android module as a project in its own window) and don't have plans to address it further.
