### ISSUE TITLE
Flutter Test shows <no name> instead of file name in Android Studio and IntelliJ

### ISSUE THREAD

**Issue by Peng-Qian** [flutter/flutter-intellij#4771]
### Problem
1. Run any test will show as following
![Screen Shot 2020-08-23 at 8 21 49 AM](https://user-images.githubusercontent.com/37643086/90965142-b6151700-e519-11ea-82ad-755ac349e669.png)

2. when running a single/group test by clicking the icon in the editor. 'SILENT_OBSERVATORY' will show up.
![Screen Shot 2020-08-23 at 8 27 10 AM](https://user-images.githubusercontent.com/37643086/90965233-76026400-e51a-11ea-8274-5145647cc25a.png)

**Comment by jacob314** [comment]
Can you provide some details on what version of Flutter you are on and what action you took to run the tests?

**Comment by Peng-Qian** [comment]
Hi @jacob314 ,

Thanks for your reply, please see the following details.

#### Flutter doctor
```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G2021, locale en-NZ)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] VS Code (version 1.46.0)
[✓] Connected device (1 available)
```
#### Plugin and IDE version
```
Flutter 48.1.2 for Android Studio 4.0.1 Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Flutter 48.1.4 for IntelliJ IDEA 2020.2 (Ultimate Edition) Build #IU-202.6397.94, built on July 27, 2020
```

**Comment by stevemessick** [comment]
@Peng-Qian does this problem occur if you use the stable channel of Flutter?

**Comment by Peng-Qian** [comment]
Hi @stevemessick ,

In the stable channel, tests can display the filename, but the second problem still there.
![Screen Shot 2020-09-03 at 3 47 15 PM](https://user-images.githubusercontent.com/37643086/92069296-17cc5f80-edfd-11ea-9d55-68c016ac13dd.png)

**Comment by stevemessick** [comment]
I'm using the master channel. It looks like the name is there but is hidden by "no name".

<img width="647" alt="Screen Shot 2020-09-11 at 10 16 39 AM" src="https://user-images.githubusercontent.com/8518285/92954219-f03a5000-f417-11ea-865d-692ab676faaf.png">

cc @jacob314 @devoncarew

**Comment by stevemessick** [comment]
The name of a virtual group changed from `null` to `""` in beta.
From master:
```json
{"group":{"id":2,"suiteID":0,"parentID":null,"name":"","metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":1840}
```
From stable:
```json
{"group":{"id":2,"suiteID":0,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":1800}
```
I think we need to change line 595 of DartTestEventsConverterZ.java to check for an empty string. Unfortunately, I have to debug why I can't run tests from the debugger right now...

**Comment by DFelten** [comment]
Issue still occurs on the latest version of IntelliJ IDEA 2020.2.3 (Ultimate Edition).

**Comment by fernando-s97** [comment]
I'm still facing this issue.

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-72-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Non-Bundled Plugins: mobi.hsz.idea.gitignore (4.1.0), Dart (211.7179), andrasferenczi.dart-data-plugin (0.1.0), izhangzhihao.rainbow.brackets (6.17), io.flutter (55.1.5), de.mariushoefler.flutter_enhancement_suite (1.5.0)
Kotlin: 211-1.4.32-release-IJ6693.72
Current Desktop: ubuntu:GNOME

$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.0.2 at /home/fernando/fvm/versions/stable
    • Framework revision 8962f6dc68 (6 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/fernando/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /snap/intellij-idea-ultimate/289
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7179

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-ultimate/285
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

• No issues found!

**Comment by renatoathaydes** [comment]
I have the same problem using IntelliJ Community Edition:

```
IntelliJ IDEA 2021.1.1 (Community Edition)
Build #IC-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Non-Bundled Plugins: com.jetbrains.webstorm.web-assembly-plugin (1.3.211), com.thvardhan.gradianto (4.4), name.kropp.intellij.makefile (211.6693.108), Dart (211.7233), org.toml.lang (0.2.147.3871-211), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45), org.rust.lang (0.4.147.3871-211)
Kotlin: 211-1.5.10-release-891-IJ7142.45
```

With Dart Plugin version `211.7233` (So I think this problem is not limited to the Flutter plugin).

This becomes a serious problem when there's a problem in the test setup, as in such cases I can't click on the failed test and can't figure out even where the test failure is occurring!

<img width="469" alt="Screen Shot 2021-06-01 at 21 34 25" src="https://user-images.githubusercontent.com/1901277/120380294-47bf7980-c321-11eb-8ec8-4695f986186b.png">

**Comment by renatoathaydes** [comment]
The bug has been reported by another user already to Jetbrains: https://youtrack.jetbrains.com/issue/WEB-51106

Please vote there for them to fix this.
