### ISSUE TITLE
Android Studio stuck on Generating Sources window when creating new activity 

### ISSUE THREAD

**Issue by Looni13** [flutter/flutter-intellij#4772]
I'm currently developing an App on Android Studio. When I try to create an Empty or Fullscreen Activity, my Android Studio gets stuck on the Generating Sources Window after I click "Finish".
![WhatsApp Image 2020-08-23 at 8 52 19 PM](https://user-images.githubusercontent.com/70111892/90987459-0ffdf700-e583-11ea-9137-f1ee67513970.jpeg)

**Comment by jacob314** [comment]
Did you mean to file this bug on the Flutter IntelliJ activity. It looks like you were creating an Android activity not a Flutter activity. If you remove the flutter plugin do you still see this hang?
