### ISSUE TITLE
The popup list of color swatches for black & white are wrong

### ISSUE THREAD

**Issue by rivendell1984** [flutter/flutter-intellij#4779]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

The popup list of color for black & white are wrong.

Colors.black tips

![black tips](https://i.imgur.com/LKSTrcb.png)

Colors.white tips

![white tips](https://i.imgur.com/UtNJRt8.png)

## Version info

Flutter version 1.20.2
Dart version 2.9.1

Android Studio (version 4.0)
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547

**Comment by stevemessick** [comment]
@alexander-doroshko It does look odd :)

**Comment by alexander-doroshko** [comment]
@stevemessick @rivendell1984 That's what Flutter API docs have :)
https://api.flutter.dev/flutter/material/Colors/black-constant.html
https://api.flutter.dev/flutter/material/Colors/white-constant.html

**Comment by stevemessick** [comment]
haha that's funny. As long as we are all consistent then I think we can close this issue.
