### ISSUE TITLE
hashCode generator enhancement

### ISSUE THREAD

**Issue by mzdm** [flutter/flutter-intellij#4784]
When the built-in generator (_ALT + Insert on Windows_) is used for example in model classes, we can use it for generating ==, hashCode and toString() methods.

Let's say we have this model class:

``` dart
class Example {
  const Example({
    this.category,
    this.id,
    this.isFavorite,
    this.name,
    this.price,
    this.startDate,
    this.expirationDate,
  });

  final Category category;
  final int id;
  final bool isFavorite;
  final String name;
  final int price;
  final DateTime startDate;
  final DateTime expirationDate;
}
```

**Generated hashCode** method for this example is:

``` dart
@override
  int get hashCode =>
      category.hashCode ^
      id.hashCode ^
      isFavorite.hashCode ^
      name.hashCode ^
      price.hashCode ^
      startDate.hashCode ^
      expirationDate.hashCode;
```

**Instead, I think it would be better if it was generating this**
[using hashValues](https://api.flutter.dev/flutter/dart-ui/hashValues.html)
(if it would have more than 1 argument and less than 20)

``` dart
@override
  int get hashCode => hashValues(category, id, isFavorite, name, price, startDate, expirationDate);
```

**Comment by mzdm** [comment]
**Additional details:**
combining hashes with XOR operation may cause issues (see felangel/equatable#39).

> ``` dart
> class Point {
>   final int x = 3;
>   final int y = 4;
> }
> ```
> and
> 
> ``` dart
> class Point {
>   final int x = 4;
>   final int y = 3;
> }
> ```
> will hash to the same value.

`hashValues` method uses [Jenkins hash function](https://en.wikipedia.org/wiki/Jenkins_hash_function) but to use it the `import 'dart:ui'` is needed.

however ...

[there's now some activity](https://dart-review.googlesource.com/c/sdk/+/73360/20) hinting that this method is moving from `ui` package to main sdk `core` so it can be used without importing.
related: dart-lang/sdk#11617 dart-lang/sdk#25217

**Comment by bwilkerson** [comment]
Yes, and when the new static methods in `Object` land, we should definitely update the generator to make use of them. Given how soon they will likely land, I don't think it's worth changing it to use `hashValues`.

**Comment by stevemessick** [comment]
@mzdm it is actually acceptable to have two non-equal objects that hash to the same value, although always better if they don't.

Closing since the is an issue for the Dart SDK.

**Comment by bwilkerson** [comment]
Actually, I believe that the generator is implemented in IntelliJ, though it's probably in the Dart plugin. (On the Mac it's command-M.) It uses a dialog to query which fields to include in the comparisons and that isn't something that server-based tools can do.

@alexander-doroshko

**Comment by alexander-doroshko** [comment]
True, items from the `Generate` popup (`hashCode`, `==()`, `toString()`, `Override Methods`, `Implement Methods`) are implemented in the Dart plugin.

**Comment by stevemessick** [comment]
https://youtrack.jetbrains.com/issue/IDEA-249561

**Comment by lukepighetti** [comment]
How do we determine when `Object.hashAll` will be available?
