### ISSUE TITLE
Tree indent guides are shown for other languages and projects

### ISSUE THREAD

**Issue by sergeyplishka** [flutter/flutter-intellij#4792]
Tree indent guides are shown for other languages and projects, for instance in TypeScript code. And there is no ability to disable it.

Maybe it is possible to use guides only for flutter projects or dart files only?

**Comment by stevemessick** [comment]
@jacob314 Can you please confirm that this problem is related to the Flutter plugin?

**Comment by sergeyplishka** [comment]
Yes, it is related. When plugin disabled, problem gone.

**Comment by devoncarew** [comment]
@sergeyplishka - can you provide a bit more details about your setup? The project you're working on - I assume it's separate projects for the Flutter and TypeScript code.

Also, a screenshot with the issue would help - the guides showing in the typescript file; thanks!

**Comment by sergeyplishka** [comment]
I cant provide a project. Just create any angular  based project.

**Comment by devoncarew** [comment]
Can you provide a screenshot showing the issue? From looking at the source, it does look like we're only applying the custom UI guides decorations to Dart files.

**Comment by sergeyplishka** [comment]
I have disabled indent guides.
![image](https://user-images.githubusercontent.com/55875212/96655686-c34a5880-1346-11eb-944e-12d042c8e680.png)

But still have it in the code.
![image](https://user-images.githubusercontent.com/55875212/96655750-e37a1780-1346-11eb-9cc1-1da5366e4523.png)

Does not matter what language to use. This is JS.

Then I go to plugins settings. Disable Flutter plugin. And have no more indent guides.

![image](https://user-images.githubusercontent.com/55875212/96655890-48ce0880-1347-11eb-9633-904c1841b176.png)
