### ISSUE TITLE
Plugin template now requires --platforms

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#4796]
We should add android and ios for now. Eventually add platform selection to the wizard.

**Comment by stevemessick** [comment]
This is with master, 1.22.0-10.0.pre.23.

**Comment by stevemessick** [comment]
The --platform option was added in 1.20.0-7.3.pre.

**Comment by devoncarew** [comment]
Does `flutter create` not generate any platforms w/o this flag?

Do you know the PR / commit in flutter that changed this? From early discussions, any change to the `create` defaults was going to be coordinated with the IDEs.

**Comment by stevemessick** [comment]
https://github.com/flutter/flutter/pull/59507

It was released to stable with 1.20.0.
