### ISSUE TITLE
Pass args to flutter compiler in test runner

### ISSUE THREAD

**Issue by flukejones** [flutter/flutter-intellij#4805]
I need to pass args to flutter which don't affect test reproducibility, only the build.

For example `flutter test --enable-experiment=non-nullable --no-sound-null-safety`. But there appears to be no way of passing this arg to the flutter test runner. In VSCode I edit for the `launch.json` for this.

**Comment by flukejones** [comment]
This would also be useful in cases where one must run a test such as:
```
flutter test -dart-define=MOCK=true,OFFLINE=true test/some_test.dart
```

**Comment by helin24** [comment]
We have this in the backlog: https://github.com/flutter/flutter-intellij/issues/3570, so I encourage you to upvote that issue!
