### ISSUE TITLE
Not working "Android" tab in "Project" tool window, Flutter plugin 49.0.4

### ISSUE THREAD

**Issue by syrop** [flutter/flutter-intellij#4806]
## Steps to Reproduce

The tab "Android" in "Project" tool window doesn't work in Flutter plugin 49.0.4 and Android Studio 4.2 Canary 9. 

It continuously shows "Loading", and when I try to quit Android Studio it shows me that there are still tasks running in background.

Attached is the screenshot from plugin version 48.1.4. It doesn't work in 49.0.4.

![Screenshot at 2020-09-05 18-35-42](https://user-images.githubusercontent.com/19635111/92310297-4db04600-efad-11ea-8743-a480c0089922.png)

## Version info

Flutter version 1.20.3 at /home/wiktor/snap/flutter/common/flutter
    • Framework revision 216dee60c0 (4 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

**Comment by helin24** [comment]
The Android tab is added by Android Studio, and we don't have any control of it. The tab doesn't display Dart files, so it can't be used for Flutter.
