### ISSUE TITLE
Sometimes Refactor -> Rename doesn't work

### ISSUE THREAD

**Issue by acbelter** [flutter/flutter-intellij#4807]
## Steps to Reproduce
Refactor-> Rename doesn't work in Flutter plugin 49.0.1 and Android Studio 3.6.3

It continuously shows "Checking availability at the selection" window
![image](https://user-images.githubusercontent.com/4152363/92329445-2a9a9a80-f070-11ea-90fe-6fed57c9dc75.png)

## Version info
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.14.4 18E227, locale en-RU)
    • Flutter version 1.17.2 at /Users/acbelter/flutter
    • Framework revision 5f21edf8b6 (3 months ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 3.6.3 Stable.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

p.s. after combination of Android Studio restarting, reinstalling Dart/Flutter plugins and Invalidate Caches and Restart Refactor-> Rename worked again =/

**Comment by helin24** [comment]
Thanks for the info! I'm glad you were able to resolve it but having an intermittent problem is certainly annoying.


I'm not able to reproduce with this combination of Android Studio, Flutter plugin, and Flutter, so it may help if you can provide further details on what type of renaming you were trying to do (variables, classes, etc.?) and whether this was happening for every type of renaming. Or if you are able to recreate this later on with a particular sequence of actions.

**Comment by acbelter** [comment]
I tried to rename an abstract class. Unfortunately, I couldn't reproduce the bug again. If I reproduce it again, I will try to write some additional information or reproduce steps. p.s. I use Android Studio without Flutter plugin every day, but I have never seen such bug before :(

**Comment by helin24** [comment]
Thanks for writing back! Yes, do keep us updated if you see this again. I'm going to close for now.
