### ISSUE TITLE
Android makes all line red without error

### ISSUE THREAD

**Issue by hamid3d** [flutter/flutter-intellij#4808]
for multiple days android studio shows all line in red color without error I do not know what is problem I do not know how to solve my problem

![image](https://user-images.githubusercontent.com/23220213/92408138-db2c9b00-f151-11ea-8a1b-5a70c10809dd.png)

flutter version

![image](https://user-images.githubusercontent.com/23220213/92408154-e8498a00-f151-11ea-95ad-78c17cbcd582.png)

install version

![image](https://user-images.githubusercontent.com/23220213/92408212-0a430c80-f152-11ea-961f-1085f9dc6014.png)

flutter version

![image](https://user-images.githubusercontent.com/23220213/92408234-17f89200-f152-11ea-9d5e-416edc16d36a.png)

file status color

![image](https://user-images.githubusercontent.com/23220213/92408260-28a90800-f152-11ea-8556-403c6578aab9.png)

I do not have any problem in building, but now I can not program in android studio it is so hard to detect error from this red line 
please show me how o solve it.

**Comment by helin24** [comment]
@hamid3d thanks for this report.

Some additional info that may help:
- Can you send your `flutter doctor -v` output? 
- Is this happening on one project or multiple projects?
- Is this in a particular file or in all files?
- Is there an error associated with the red lines, if you hover over them?
