### ISSUE TITLE
Developer experience still sucks after 9 years!!

### ISSUE THREAD

**Issue by basxib** [flutter/flutter-intellij#4811]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I used android studio 9 years ago and the experience was very bad,, now I used it again and it still the same!!
Just abandon this whole IDE and build on top of VSC instead.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment]
@basxib, this issue doesn't meet the standards of our code of conduct (https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md). Please review it before communicating again, on this or other issues.
