### ISSUE TITLE
Package imports ignored by autocomplete, forcing relative imports even when path is outside of project 

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter-intellij#4814]
## Steps to Reproduce
1. Have Flutter library and Flutter app on disk in the same folder (Lets say /git/myLib, and /git/myApp)
2. Import /git/myLib using git or pub in pubspec of /git/myApp
3. When typing, autocomplete attempts to use relative imports outside of the current project, even when a package import is already available in the same file. Additionally none of the package import items are showing in autocomplete

When I have the package import already and I am coding:
![Screen Shot 2020-09-09 at 8 33 56 AM](https://user-images.githubusercontent.com/7351329/92599371-29d45500-f278-11ea-8b14-247981d4fb6e.png)

After I pick one of the options (see both imports):
![imports](https://user-images.githubusercontent.com/7351329/92599430-3f497f00-f278-11ea-9d96-41901d5e5671.png)

## Version info
```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-CA)
    • Flutter version 1.20.3 at /Users/jrai/dev/flutter
    • Framework revision 216dee60c0 (8 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jrai/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/jrai/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/jrai/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • DF38EA89-62A3-43B5-9AE9-0122E487F43D • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7
      (simulator)
```

**Comment by helin24** [comment]
@MisterJimson I'm not able to reproduce this issue, but my setup is likely different somewhere. Could you provide some more details on how you've set up the myLib folder and pubspec.yaml file, and how you're requiring the package in myApp? Alternatively, could you recreate this problem with a sample repo?

**Comment by MisterJimson** [comment]
Sure, here is what I got.

from myApp pubspec
```
myLib:
    git:
      url: git@github.com:myOrg/myLib.git
      ref: 1.0.2
```

And the folder is just:
/git/myApp
/git/myLib

**Comment by MisterJimson** [comment]
If I get some time I'll try a sample repo

**Comment by helin24** [comment]
Thanks for the additional info. I tried to reproduce using git URL here, but was unsuccessful: https://github.com/helin24/package_test

Let me know if you see the issue from my test repo, and feel free to modify that if it helps us reproduce the problem.
