### ISSUE TITLE
Display correct errors and warnings while editing Android code on Flutter project in Android Studio

### ISSUE THREAD

**Issue by omatt** [flutter/flutter-intellij#4819]
Errors seems to be always displayed on Android-specific code in the Flutter project. Correct errors and warnings are displayed if 'Open for Editing in Android Studio' was clicked. The Flutter app runs as expected though.

## Steps to Reproduce

Edit Android code in Flutter project.

<img width="1028" alt="Screen Shot 2020-09-10 at 4 28 38 AM" src="https://user-images.githubusercontent.com/4143153/92811632-38924780-f3f1-11ea-8681-2bab2cf6d094.png">

Clicking 'Open for Editing in Android Studio', the errors displayed goes away. 

<img width="793" alt="Screen Shot 2020-09-10 at 4 28 59 AM" src="https://user-images.githubusercontent.com/4143153/92811711-48aa2700-f3f1-11ea-94cf-cae7767379af.png">

## Version info

/Users/{USER}/Downloads/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6)
    • Flutter version 1.20.3 at /Users/{USER}/Downloads/flutter
    • Framework revision 216dee60c0 (9 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/{USER}/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/{USER}/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
Process finished with exit code 0

**Comment by stevemessick** [comment]
Have you enabled the experimental feature that supports this? To check, open Flutter Preferences/Settings and make sure the check box is ticked for `Enable code completion, navigation, etc. for Java / Kotlin`. You'll need to restart Android Studio to trigger a Gradle sync.

That option has been around for a while but it will probably always be experimental. It is really difficult to keep it working. It depends on APIs that both Jetbrains and Android Studio frequently modify. And the Flutter team often restructures their libraries, which is another source of breakage.

**Comment by omatt** [comment]
Could you provide the steps so I can navigate to `Enable code completion...` settings? I can't seem to find this option on Android Studio Preferences. Do I need to be on a specific build of Flutter or Android Studio?

**Comment by stevemessick** [comment]
It's toward the bottom.

<img width="995" alt="Screen Shot 2020-09-10 at 3 52 27 PM" src="https://user-images.githubusercontent.com/8518285/92819509-b9176080-f37d-11ea-8fc5-f4c9bdc62c28.png">

**Comment by omatt** [comment]
Thanks for the steps @stevemessick. It worked for me.

**Comment by stevemessick** [comment]
Great! Thanks for verifying that it still works :)
