### ISSUE TITLE
Flutter Hot Reload on Save for all devices

### ISSUE THREAD

**Issue by md-weber** [flutter/flutter-intellij#4822]
Currently there is no option to hot reload all devices on save, it will only execute hot reload on one device.
![image](https://user-images.githubusercontent.com/8026644/92928723-cbf26980-f43f-11ea-82ba-54c934f46a94.png)

It would be great to have the option to choose if I want to hot reload one application or all of them with saving the project.
![image](https://user-images.githubusercontent.com/8026644/92928778-e2002a00-f43f-11ea-984e-dd00dd6b81dd.png)

**Comment by stevemessick** [comment]
Also see #956.

**Comment by md-weber** [comment]
I will close this issue because it is already discussed in #956, thanks @stevemessick
