### ISSUE TITLE
New project "hot reload" does "restart" instead

### ISSUE THREAD

**Issue by dlazerka** [flutter/flutter-intellij#4832]
## Steps to Reproduce

1. Have the latest IntelliJ Ultimate or Android Studio and Flutter plugin, latest version.
1. Create new Flutter project in latest IntelliJ.
1. Run it as Chrome or Web.
1. Click to `+` icon couple of times. Observe counter in the middle is not `0`.
1. Open main.dart in IDE, change `primarySwatch: Colors.blue` to `primarySwatch: Colors.green`.
1. Save the file.
1. Observe browser counter in the middle goes to `0` again.

Comment in main.dart says ```Notice that the counter didn't reset back to zero; the application is not restarted.```
However, the counter clearly resets back to zero for me. 

## Version info

```
$ flutter doctor -v

[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.2.pre at /home/dl/snap/flutter/common/flutter
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

⣽Error 1 retrieving device properties for ro.product.cpu.abi:
adb: insufficient permissions for device: user in plugdev group; are your udev rules wrong?
See [http://developer.android.com/tools/device.html] for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/dl/opt/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/dl/opt/android-sdk
    • Java binary at: /media/dl/nvme/home/dl/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /media/dl/nvme/home/dl/opt/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /media/dl/nvme/home/dl/opt/idea-IU
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • 912X1U9KH (mobile) • 912X1U9KH  • android-arm    • Android null (API null)
    • Web Server (web)   • web-server • web-javascript • Flutter Tools
    • Chrome (web)       • chrome     • web-javascript • Google Chrome 85.0.4183.102

```

**Comment by devoncarew** [comment]
> Comment in main.dart says Notice that the counter didn't reset back to zero; the application is not restarted.
However, the counter clearly resets back to zero for me.

Thanks for the report! This is currently working as expected. That sample would correctly maintain state across reloads while running on flutter mobile. Flutter web currently maps a 'reload' operation as a restart - a quick restart of the app - and restores the pages url from before the restart. The state of the app is not retained (modulo the navigation location).

**Comment by raquelhortab** [comment]
Hi! so, just to confirm, hot reload does not actually work on web version? The app is completely restarted at every change we make? Even if we only change a bit of text, we lose everything?  The whole hot reload advantages are lost here then?
