### ISSUE TITLE
License Problem

### ISSUE THREAD

**Issue by Montanajim** [flutter/flutter-intellij#4863]
If you run flutter doctor, you get this.  Please note that I am running Oped JDK.  I've tried about everything on StackOverflow, GitHub, and Medium. - PLEASE FIX.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\goudyj\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

**Comment by devoncarew** [comment]
Hi - this issue tracker is for the Flutter plugin for IntelliJ and Android Studio. I not sure how to resolve the android sdk license problem issue you're seeing, but it's likely android specific; I suspect a search would turn up people who've also encountered (and resolved) this.
