### ISSUE TITLE
Allow platform selection when creating a new project

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter-intellij#4868]
I'd like to select my desired platforms when creating a new Flutter project.

I typically want to target mobile, or web, or desktop, but usually not multiples, and never all of them. As a result, after I create a new project I have to go delete the directories for platforms that I don't want to support. It would be helpful to select these platforms during the project setup wizard.

**Comment by stevemessick** [comment]
Thanks for the request! I'm working on a rewrite of the new project wizard. I plan to support this feature.

It will also allow updating the project template by re-running `flutter create` for an existing project, something that is not currently possible from IntelliJ.

**Comment by stevemessick** [comment]
This was fixed in #5070.
