### ISSUE TITLE
Run in IntelliJ does not launch app correct on iPhone

### ISSUE THREAD

**Issue by yakuraku** [flutter/flutter-intellij#4879]
## Steps to Reproduce

I updated XCode today to Version 12. When I now want to start the App from IntelliJ, it does compile and launch it on the device but only displays a white screen. In XCode the app can be started correctly.

## Version info

The output of running flutter doctor -v

> [✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
>     • Flutter version 1.20.4 at /Users/mj/Workspaces/flutter/flutter
>     • Framework revision fba99f6cf9 (8 days ago), 2020-09-14 15:32:52 -0700
>     • Engine revision d1bc06f032
>     • Dart version 2.9.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at /Users/mj/Library/Android/sdk
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: /Users/mj/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.0, Build version 12A7209
>     • CocoaPods version 1.9.0
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Users/mj/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
>     • IntelliJ at /Users/mj/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
>     • Flutter plugin version 49.0.4
>     • Dart plugin version 202.7319.5
> 
> [✓] VS Code (version 1.47.3)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.13.2
> 
> [✓] Connected device (2 available)
>     • moto g 8 power (mobile) • xxx                • android-arm64 • Android 10 (API 29)
>     • iPhone-Dev (mobile)     • xxx• ios           • iOS 14.0
> 
> • No issues found!

**Comment by pq** [comment]
What happens when you  `flutter -v run` from  the  commandline?

**Comment by yakuraku** [comment]
After setting the iOS target version to iOS 12 (did is because of a dependency) it starts now normally again.

**Comment by pq** [comment]
Thanks for following up.  Glad you're up and running.
