### ISSUE TITLE
Running start-pause hangs

### ISSUE THREAD

**Issue by ccadieux** [flutter/flutter-intellij#4882]
## Steps to Reproduce
Running the following test hangs when run as a single or the file. I've seen there have been a bunch of tickets and PRs around start-paused. Figured I'd add this simple test to highlight the issue.

```
import 'package:flutter/foundation.dart';
import 'package:test/test.dart';

void main() {
  Future<double> computeMethod() async {
    return await compute(double.parse, '1.1');
  }

  test('hanging test', () async {
    expect(await computeMethod(), 1.1);
  });
}
```

## Version info
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2021, locale en-CA)
    • Flutter version 1.17.5
    • Framework revision 8af6b2f038 (3 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.6397.47

**Comment by stevemessick** [comment]
@helin24 You've been doing some work in this area, I believe.

**Comment by devoncarew** [comment]
I _believe_ this should be addressed by https://github.com/flutter/flutter-intellij/pull/4977 (available in the next release).
