### ISSUE TITLE
Wrong icons displayed in editor sidebar

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter-intellij#4889]
## Steps to Reproduce

1. Type any `Icons` reference, eg. `Icons.tag_faces`
2. Use _Go to Declaration_ to open up `Icons.dart`
3. The icons in the sidebar don't match the actual icon definitions:

![Screenshot 2020-09-25 201354](https://user-images.githubusercontent.com/2234271/94302196-21646580-ff6c-11ea-959f-ff4e3e36b22c.png)

AS was restarted, caches cleared, etc. No difference.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

```
E:\Android\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.4 at E:\Android\flutter
    • Framework revision fba99f6cf9 (11 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:/Android/Sdk
    • ANDROID_SDK_ROOT = e:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0
```

**Comment by stevemessick** [comment]
@devoncarew This is reproducible with M50.

**Comment by devoncarew** [comment]
Thanks for the report! I suspect - but haven't checked - that the code points for the icons has changed between releases. We're shipping icons compatible with `1.22.0-12.0.pre dev` (https://github.com/flutter/tools_metadata/blob/master/resources/version.json).

**Comment by devoncarew** [comment]
Yeah, I think the preview icons are correct for 1.22 dev and beta channels, but not for 2.10 stable. We should open an issue to track that - to map from a flutter version+code point, to a logical icon name, to a preview icon.

**Comment by devoncarew** [comment]
@deakjahn - this should be resolved now if you're running on the latest stable flutter sdk. I'll open an issues to for properly handling code point changes between flutter sdk versions.

**Comment by deakjahn** [comment]
Yes, thanks. I spotted some new, pandemic-related additions in the icon set, that must have been the culprit. :-)

**Comment by beriaanirudh** [comment]
I am facing this issue on Android Studio: 4.1.1 in Ubuntu 18.04. `flutter --version` is

```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (13 days ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

```
