### ISSUE TITLE
Filter library / verbos logs from Run tab in AndroidStudio

### ISSUE THREAD

**Issue by crtl** [flutter/flutter-intellij#4895]
This was once the case on stable but has been removed sometime.
The problem is the Browser DevTools are not really efficient but show the output how it should be.
On the other hand AndroidStudio is easier to use but only shows verbose logs.

There was a Flag in Preferences to disable verbose output but this was removed (https://stackoverflow.com/questions/55437643/flutter-disable-system-debug-messages-in-run-tab).

Is it even possible to enable this again or is this somehow planed?
This is throwing me back every day when working with flutter.

## Steps to Reproduce

1. Make an app
2. Install `video_player` and include a view with running video and some `print` or `log` statements
3. Your log output is spammend with verbose output and it is very hard to even find what you intended to log

## Version info

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.385, on Microsoft Windows [Version 10.0.18363.1082], locale en-DE)
    • Flutter version 1.22.0-10.0.pre.385 at D:\dev\flutter\sdk
    • Framework revision 73b6398932 (10 hours ago), 2020-09-28 11:07:32 +0800
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

```

**Comment by stevemessick** [comment]
Have you tried using the [logging](https://pub.dev/packages/logging) package? You can log your messages to their own file.

Sorry, but we don't have any plans to restore the preference you mentioned.

**Comment by crtl** [comment]
@stevemessick but why not? Wasnt it available as an expiremtal option in the first place?
What speaks against adding it again and disable it by default?
Nothing changes but you can still decide to switch it on.

**Comment by stevemessick** [comment]
I was not involved in the decision to remove it. Perhaps @devoncarew knows more?
