### ISSUE TITLE
Keyboard shortcut for Flutter Inspector (e.g. Show debug paint

### ISSUE THREAD

**Issue by amitkot** [flutter/flutter-intellij#4904]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
dup of #4905

**Comment by amitkot** [comment]
Oops, sorry about that!
