### ISSUE TITLE
consider adding a 'Flutter' view

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#491]
Docked to the right:

<img width="295" alt="screen shot 2016-12-04 at 12 00 50 am" src="https://cloud.githubusercontent.com/assets/1269969/20868276/a032808a-ba0c-11e6-910f-e1b005c956ef.png">

Some use cases could be:
- assist with UI construction - creating, editing, and refactoring nested Flutter widget constructors
- showing UI state for a running app - either an editable tree view of the component hierarchy, or a symbolic rendering of component layout - where components are on screen, and their relationship to other components

**Comment by mit-mit** [comment]
I've had a similar idea. I think it would be super useful to have a tree-based view of the source code file, somewhat similar to what Android Studio has:

![screen shot 2016-12-05 at 10 32 28](https://cloud.githubusercontent.com/assets/13644170/20879958/601d29c6-bad6-11e6-963d-b452b1c2e13f.png)

**Comment by devoncarew** [comment]
Cool! Dart does provide content for the `Structure` view. This would be similar, but optimized and specialized for Flutter UI code patterns (nested ctors using named args).

**Comment by mit-mit** [comment]
Yup, exactly what I had in mind.

Do you know if we can add actions in this pane? For example, moving a widget node up/down/out/in in the tree, and adding a new node around an existing node?

**Comment by eseidelGoogle** [comment]
FYI @lukechurch

**Comment by devoncarew** [comment]
> Do you know if we can add actions in this pane?

Yup, we have a lot of flexibility here. Actions in the toolbar, actions in the gear menu, arbitrary content in the view, and the ability to support tabs (different views on the content).

I did talk with @lukechurch Friday briefly, to get a better sense for where flit is, and to figure out how this view may relate to flit.

**Comment by pq** [comment]
@devoncarew can we close this for now and open targeted issues here on out?

**Comment by devoncarew** [comment]
sgtm
