### ISSUE TITLE
Select widget mode in new Flutter Inspector no longer navigates editor to the Flutter code

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter-intellij#4929]
## Steps to Reproduce

1. Open the widget inspector. 
2. Select a widget on your screen.
3. Notice that the inspector shows the widget, but no longer shows the code for the widget.
![2020-09-30 20 08 29](https://user-images.githubusercontent.com/23037821/94761885-125e2880-035b-11eb-9bf5-2b01796338e1.gif)
## Version info

> ❯ flutter doctor -v   

> [✓] Flutter (Channel stable, 1.20.4, on Mac OS X 
10.15.7 19H2, locale en-US)
>     • Flutter version 1.20.4 at /Users/thinkdigital/development/flutter_stable
>     • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
>     • Engine revision d1bc06f032
>     • Dart version 2.9.2
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
>     • Android SDK at /Users/thinkdigital/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.0-rc4
>     • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
>     • ANDROID_SDK_ROOT = /Users/thinkdigital/Library/Android/sdk
>     • Java binary at: /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.5, Build version 11E608c
>     • CocoaPods version 1.9.3
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
>     • Flutter plugin version 48.0.2-dev.3
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.49.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.14.1
> 
> [✓] Connected device (1 available)
>     • SM N975U (mobile) • R38M906TG0Z • android-arm64 • Android 10 (API 29)
> 
> • No issues found!
> 
>

**Comment by stevemessick** [comment]
@jacob314 @helin24 Looks like the complement of #4924

**Comment by vasilich6107** [comment]
This issue is very disappointing...
It forces me to downgrade to v48 of plugin

**Comment by devoncarew** [comment]
It looks like this is specific to the DevTools version of the inspector, not the IntelliJ native version.

To work around this issue, you should be able to uncheck the experimental setting, `Enable embedded DevTools inspector`.

cc @helin24 @jacob314

**Comment by ThinkDigitalSoftware** [comment]
> It looks like this is specific to the DevTools version of the inspector, not the IntelliJ native version.
> 
> To work around this issue, you should be able to uncheck the experimental setting, `Enable embedded DevTools inspector`.
> 
> cc @helin24 @jacob314 

Uncheck it from where?

**Comment by vasilich6107** [comment]
@ThinkDigitalSoftware https://tppr.me/NR9Cx

**Comment by Wang946654036** [comment]
I have a similary problom but I don't have the experimental setting: **Enable embedded DevTools inspector.**
It cannot "Jump to Source".
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.1139], locale zh-CN)
    • Flutter version 1.12.13+hotfix.9 at D:\src\flutter
    • Framework revision f139b11009 (7 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\androidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 30.0.1
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Redmi K20 Pro • 15fe7827 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by Wang946654036** [comment]
OK,I update flutter&dart to newest and uncheck the experimental setting: **Enable embedded DevTools inspector.**
It still cannot jump to source.

**Comment by helin24** [comment]
@Wang946654036 thanks for the report. Did you restart after unchecking the experimental setting and get the inspector that looks like this?
![Screen Shot 2020-10-28 at 11 06 54 AM](https://user-images.githubusercontent.com/6379305/97478112-bcef4a00-190d-11eb-99e6-3369e4103f0c.png)

**Comment by Wang946654036** [comment]
> @Wang946654036 thanks for the report. Did you restart after unchecking the experimental setting and get the inspector that looks like this?
> ![Screen Shot 2020-10-28 at 11 06 54 AM](https://user-images.githubusercontent.com/6379305/97478112-bcef4a00-190d-11eb-99e6-3369e4103f0c.png)

I did,but it still cannot jump to source
![image](https://user-images.githubusercontent.com/36040831/97515572-46fde800-19cc-11eb-9342-0037ed789139.png)

**Comment by helin24** [comment]
@Wang946654036 I see, can you also try upgrading your version of flutter? https://flutter.dev/docs/development/tools/sdk/upgrading

**Comment by helin24** [comment]
@marcglasberg I wanted to keep info about this issue together, so can you post some additional details:
- Are you seeing this problem for all components or for some components?
- Can you post a screenshot of your summary and detail trees (probably in DevTools opened in your normal browser, for larger view)

**Comment by Wang946654036** [comment]
I found this problem before using ‘Get from Version Control’ of AndroidStudio to download and run the project. Before I used TortoiseSVN to download and open the project with AndroidStudio, I could have the project go smoothly. I hope this can help you

**Comment by marcglasberg** [comment]
@helin24 I was seeing this problem for all widgets. I clicked them and nothing happened. I since them reverted to the old dev Inspector, and can't see the problem anymore.

**Comment by helin24** [comment]
Okay, sounds good. Thanks for the reports - if anyone encounters this in the future, please post details on the below.

> * Are you seeing this problem for all components or for some components?
> * Can you post a screenshot of your summary and detail trees (probably in DevTools opened in your normal browser, for larger view)

**Comment by Technogeekpro** [comment]
Open the code in vscode instead, it's not the best solution I know, but the best alternative

**Comment by AkkiKosmonk** [comment]
I have tried and succeeded by changing following things
1. I have invalidate cache and restart android studio
2. I have tried flutter clean and flutter pub get
--- No success---
Finally
3. I have moved project to different  directory and that helps me to solve the issue

**Comment by helin24** [comment]
@AkkiKosmonk that's interesting, are you able to share what your directory structure looked like before and after?

**Comment by AkkiKosmonk** [comment]
> @AkkiKosmonk that's interesting, are you able to share what your directory structure looked like before and after?

Actually i have't done anything with coding part .i simply create a empty folder and paste the entire code there that's it.
