### ISSUE TITLE
Support for DartDoc macros (Android Studio)

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter-intellij#4930]
Original issue is #2524

I haven't seen this feature work on Android Studio since it was closed.

**Comment by devoncarew** [comment]
Can you post the version of the flutter sdk and flutter IntelliJ plugin in use, and a screen shot demonstrating the issue? Thanks!

**Comment by guidezpl** [comment]
```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.74, on Mac OS X 10.15.6 19G2021 x86_64, locale
    en-US)
    • Flutter version 1.23.0-8.0.pre.74 at /Users/plg/development/flutter
    • Framework revision fe22d196fc (2 days ago), 2020-09-30 11:15:49 -0700
    • Engine revision a6a6fd163b
    • Dart version 2.11.0 (build 2.11.0-177.0.dev)


[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```
On cmd+click:
<img width="433" alt="Screen Shot 2020-10-02 at 9 47 05 AM" src="https://user-images.githubusercontent.com/6655696/94899834-45580780-0494-11eb-88af-0ff3e7791f6e.png">

On hover:
<img width="440" alt="Screen Shot 2020-10-02 at 9 44 57 AM" src="https://user-images.githubusercontent.com/6655696/94899828-438e4400-0494-11eb-9260-4c7b8d3b4c5e.png">

I also checked that I have the Android Studio 'Show quick documentation on mouse move' setting enabled.

**Comment by stevemessick** [comment]
@alexander-doroshko After reading some code, I believe go-to-declaration is driven by the IntelliJ index. If you can confirm, I'll move this to your issue tracker. Hover text is not being displayed although there is a dart-lang issue that claims it should be. Does that text come from the analysis server?

**Comment by alexander-doroshko** [comment]
@stevemessick Go-to-declaration feature in Dart is based on the navigation data from the Analysis Server. I can confirm that the server doesn't provide navigation data for macros in comments.

**Comment by stevemessick** [comment]
Thanks, Alex!
