### ISSUE TITLE
In package name _ is missing and - is allowed when entering package name for flutter 

### ISSUE THREAD

**Issue by SmartManoj** [flutter/flutter-intellij#4951]
From https://issuetracker.google.com/issues/170141110, add a report button in the tool itself.

## Steps to Reproduce:
1. Create a flutter project
2. Use the same name
3. The _ in the name is missing but  will reflect in the package

## Version info

[√] Flutter (Channel beta, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.22.0 at C:\tools\flutter_windows_1.22.0-stable\flutter
    • Framework revision d408d302e2 (7 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Smart\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

![image](https://user-images.githubusercontent.com/7231077/95278541-0ba94700-086e-11eb-82e3-68f529156024.png)

Isn't flutter doctor -d  --version should include this info?

**Comment by kenzieschmoll** [comment]
Can you give an example with specific names that demonstrate the problem you're seeing?

FYI @stevemessick @helin24

**Comment by SmartManoj** [comment]
App name: fluter_app
com.rooster-tech.fluterapp <- _ missed and - is allowed
After finish - is removed and _ is showing again

**Comment by helin24** [comment]
@SmartManoj thanks for the report, can you clarify the steps you're following to create your app?

My guess was the following, but I cannot replicate your issue this way:
1. Go to File -> New -> Project
2. Select flutter SDK path
3. Enter for "Project name" a name that has an underscore, e.g. `underscore_test`
4. Click "Finish"
(when I try this, I see underscore_test in the project menu and in the generated README.md)

Can you also describe/screenshot where you've been seeing this value within IntelliJ? `com.rooster-tech.fluterapp`

**Comment by SmartManoj** [comment]
can't confirm now
![image](https://user-images.githubusercontent.com/7231077/97072098-ed797000-15fd-11eb-9786-f64ec675d36b.png)

**Comment by stevemessick** [comment]
This appears to have been fixed. If you still have this problem we can re-open it.
