### ISSUE TITLE
Flutter plugin version 50.0 swallows errors that happen inside of widgets

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#4952]
For example, instead of this:

The ones who are not experiencing the problem are actually getting the error twice, once with the stacktrace and once without it:

```
════════ Exception caught by widgets library ════════ 
The following assertion was thrown building MyWidget(dirty):
Failed assertion: boolean expression must not be null
The relevant error-causing widget was: 
  MyWidget file:///C:/Users/Me/flutter_app/lib/my_widget/my_widget.dart:117:13
When the exception was thrown, this was the stack: 
#0      MyWidget.preambulo (package:xyz/participantes_widget.dart:44:27)
#1      MyWidget._varios (package:xyz/my_widget.dart:71:14)
#2      MyWidget.build (package:xyz/my_widget.dart:56:14)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
...
════════════════════════════════════

════════ Exception caught by widgets library ════════ 
Failed assertion: boolean expression must not be null
The relevant error-causing widget was: 
  MyWidget file:///C:/Users/Me/flutter_app/lib/my_widget/my_widget.dart:117:13
══════════════════════════════════════ 
```

You get only this:

```
════════ Exception caught by widgets library ════════ 
Failed assertion: boolean expression must not be null
The relevant error-causing widget was: 
  MyWidget file:///C:/Users/Me/flutter_app/lib/my_widget/my_widget.dart:117:13
══════════════════════════════════════ 
```

Note, it happens only in the IDE run tab. The terminal gives the complete information.

Also, if you downgrade the Flutter plugin from 50.0 to 49.04 the problem is gone. You can download the plugin in this page:
https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/96118

And the direct download link is this:
https://plugins.jetbrains.com/files/9212/96118/flutter-intellij.zip?updateId=96118&pluginId=9212&family=INTELLIJ

**Comment by marcglasberg** [comment]
(ported this issue from https://github.com/flutter/flutter/issues/67418)

**Comment by devoncarew** [comment]
Thanks for the report! We did do work in this area in the last month (https://github.com/flutter/flutter-intellij/pull/4870, https://github.com/flutter/flutter-intellij/pull/4867), but I don't see anything that would have changed behavior here.

We do try and elide errors that are considered derivative - that are caused by a primary error (one error causes us to display an inline error message in the UI, which then causes an overflow error). That's likely what we're hitting here, but I don't believe this code has changed recently.

**Comment by devoncarew** [comment]
Can you include a small repro case?

**Comment by marcglasberg** [comment]
@devoncarew It's not necessary. Just create any widget and `throw AssertionError` in its `build` method. It's as simple as that.

**Comment by wonpyohong** [comment]
same here!
