### ISSUE TITLE
Flutter projects show a 'New Package' option, where they should show a 'New Folder' option.

### ISSUE THREAD

**Issue by lewcianci** [flutter/flutter-intellij#4955]
## Steps to Reproduce

1. Make a new Flutter project
2. Right click on the 'lib' folder or wherever
3. Try to make a new folder by clicking New > Folder
4. Observe that only the option for a new 'package' exists

## Version info
[√] Flutter (Channel beta, 1.22.0-12.3.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-AU)
    • Flutter version 1.22.0-12.3.pre at E:\flutter
    • Framework revision d408d302e2 (8 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at E:\android
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = E:\android
    • ANDROID_SDK_ROOT = E:\android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\lewci\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 85.0.564.63

! Doctor found issues in 1 category.

**Comment by lewcianci** [comment]
I suspect this is a holdover from Android Studio being used to create Android projects, and 'New Package' may mean more in the context of a Java/Kotlin development mindset. However, it makes creating new folders in Flutter projects and unnecessary pain.

For example, if you create a new package (folder), and then create *another* package in that package, you wind up with one long name of both of your folders separated by a dot. It's non-straightforward to create files in the root directory after creating the second folder.

There are ways to mitigate this, like marking the folder as non-source in Android Studio but then you're marking your source code as 'non-source' which also seems counter-intuitive.

**Comment by stevemessick** [comment]
This is working as intended. You might want to uncheck the "Compact Middle Packages" option in the Project view.

**Comment by lewcianci** [comment]
Can I ask for the rationale behind this design choice? One of the very first things I've done in Android Studio for Flutter is to create a new folder for my services and I've never used any language or framework that refers to folders as 'packages'.

Rebadging the new folder option as 'new package' is confusing as the user is actually just making a new folder. Surely it should be the default to call it a folder?

**Comment by stevemessick** [comment]
I'm glad you asked. I think this is a hold-over from when directories were referred to as "packages". It got a bit confusing when "package" was used to describe project structure *and* units of sharable Dart code, as seen in the pubspec.yaml file. IIRC the former was dropped a few years ago. I'd forgotten about that.

I'll re-open this issue since it does seem like a real problem.

@pq @devoncarew Do you have any further insights?

**Comment by lewcianci** [comment]
That's the first time anyone has ever said "I'm glad you asked" in a GitHub issue when I challenged them for their rationale for a certain decision. You guys are the best. 🌟

**Comment by devoncarew** [comment]
Hmm, I see a `New > Directory` option, but not a New > Package one (or a New > Folder one). I'm using IntelliJ and Android Studio - the latest non-EAP versions - on macos. This is from a Flutter project, in the 'Project' tool window, with the 'Project" filter selected.

**Comment by stevemessick** [comment]
@devoncarew This happens when you have a Dart source directory or file selected.

**Comment by stevemessick** [comment]
This feature is implemented in the Dart plugin, not Flutter. In the latest Dart plugin it shows `Directory` not `Package`.

**Comment by ahmdt** [comment]
Right click on project folder -> Mark Directory as -> Unmark as Resources root -> Enjoy life without java glasses

**Comment by nayanAubie** [comment]
Thanks @ahmdt, this is the correct solution. worked for me 👍

<img width="450" alt="Image" src="https://github.com/user-attachments/assets/48775520-c5c9-4cb4-9439-ea9a5fc764b6" />

**Comment by nayanbabariya** [comment]
Thanks @ahmdt, this is the correct solution. worked for me 👍

<img width="450" alt="Image" src="https://github.com/user-attachments/assets/fc3553c1-6511-4acd-9595-fe30dd1f488a" />
