### ISSUE TITLE
Flutter Inspector - clicking a different widget should change the selected widget

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter-intellij#4959]
The selected widget widget should change when the user is clicking different widgets in inspect mode.

## Steps to Reproduce

1. Open IntelliJ
2. Run a Flutter app
3. Open Flutter Inspector
4. Click on a widget to view it in the Widget outline
5. Click on a different widget
6. Observe the selected widget hasn't changed.

## Version info
Plugin version: 50.0

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.269, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.23.0-8.0.pre.269 at /Users/ryjohn/code/github/flutter/flutter
    • Framework revision 759ddb1ccd (3 days ago), 2020-10-09 22:28:25 +0200
    • Engine revision 36769af310
    • Dart version 2.11.0 (build 2.11.0-203.0.dev)
```

**Comment by stevemessick** [comment]
Are you using the experimental version of the inspector or the old one? There's an option in Flutter preferences to control it.

Are you clicking in the editor or the inspector?
