### ISSUE TITLE
Plugin testing punchlist.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#496]
Tracking issue for filling in tests for plugin functionality.

**Infra:**
  * [ ] run unit tests on the bots (https://github.com/flutter/flutter-intellij/issues/726)
  * [ ] investigate FEST for integration tests
  * [ ] write integration tests for critical use cases
  * [ ] get integration tests running on the bots

**Unit tests:**

  * [ ] folding (a la `DartFoldingTest`)
  * [ ] console filtering (a la `DartConsoleFilterTest`)
  * [ ] inspections
  * [ ] actions?
  * [ ] sdk (validation, config, etc)
  * [ ] daemon?
  * [ ] runner?

**Integration:**

  * [ ] workflow (a la `DartWorkflowTest`)
    * [ ] project creation

**Comment by devoncarew** [comment]
assumed stale -
