### ISSUE TITLE
Flutter isolate test hangs

### ISSUE THREAD

**Issue by enchikiben** [flutter/flutter-intellij#4960]
## Steps to Reproduce

After plugin update> 45, flutter isolate test hangs:
```
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';


dynamic testFunGlobal(var s) {
  return 111;
}

Future<dynamic> testFun() async {
  return await compute(testFunGlobal, "11");
}

void main() {
  test('test', () async {
    var a = await testFun();
    print(a);
  });
}
```

Run test icon:
![image](https://user-images.githubusercontent.com/1251978/95871653-56075800-0d87-11eb-9f4f-757e60c796ee.png)

Will be executed indefinitely and will not return any result.

## Version info

C:\projects\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.546], locale ru-RU)
    • Flutter version 1.22.1 at C:\projects\flutter
    • Framework revision f30b7f4db9 (5 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\enchikiben\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by devoncarew** [comment]
Thanks for the report! Can you try the latest plugin - version 50.0? That's only available in Android Studio 4.0 and later (I see that you're on AS 3.6 and Flutter plugin version 49.0).

**Comment by enchikiben** [comment]
![image](https://user-images.githubusercontent.com/1251978/95881290-e2b71380-0d91-11eb-9aaa-008052e247c9.png)
I have the last one

**Comment by devoncarew** [comment]
This might be the same issue as https://github.com/flutter/flutter-intellij/issues/4967.
