### ISSUE TITLE
Android Studio File/Project Structure settings missing

### ISSUE THREAD

**Issue by AndrewByk** [flutter/flutter-intellij#4961]
After Android Studio 4.1. update I missing Project Structure option in File menu
![pic5](https://user-images.githubusercontent.com/53439982/95876400-e71c0600-0d6a-11eb-8c29-7b2d5a131f13.png)

And for each new project, I need to manually update Gradle to 6.+
![pic7](https://user-images.githubusercontent.com/53439982/95876442-f602b880-0d6a-11eb-8f0c-0b4a2b05ed0a.png)

flutter doctor -v
![pic0](https://user-images.githubusercontent.com/53439982/95876485-03b83e00-0d6b-11eb-84bd-00c1c56ec227.png)

**Comment by stevemessick** [comment]
Dup of #4736 
Also see https://issuetracker.google.com/issues/169608635
