### ISSUE TITLE
Error updating Android Studio

### ISSUE THREAD

**Issue by ManuelCardonaS** [flutter/flutter-intellij#4965]
After updating to version 4.1.0.0 I get the error:

Plugin Error: Plugin "Flutter App Template Generato" in incompatible (supported only in Intellij IDEA). // Plugin "FlutterAssetAutoCompletion" is not compatible "

And it does not allow you to do anything at all.

**Comment by ManuelCardonaS** [comment]
![image](https://user-images.githubusercontent.com/66150816/96001181-5d694880-0dfd-11eb-8837-e8d432587ce3.png)

**Comment by stevemessick** [comment]
We don't support either of those plugins.
