### ISSUE TITLE
plugin pbroblem with Android Studio 4.1

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter-intellij#4973]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Since I upgraded to Android Studio 4.1, there is this permanent error:

Plugin Error: Plugin "Mapfile" is incompatible (supported only in IntelliJ IDEA).

Moreover, Flutter doctor gives info from where Flutter and Dart can be installed but the fact is that on plugins.jetbrains.com, there is nothing for the build#AI-201.8743.12.41.(...) built on September 23, 2020, open-source software Android Studio (stable)

What can be done?

## Version info

```
`[√] Flutter (Channel master, 1.23.0-19.0.pre.90, on Microsoft Windows [version 10.0.19041.572], locale
    fr-FR)
    • Flutter version 1.23.0-19.0.pre.90 at C:\
    • Framework revision 4aa1154b09 (2 hours ago), 2020-10-16 19:17:05 -0400
    • Engine revision d03b759d04
    • Dart version 2.11.0 (build 2.11.0-229.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\
    • Java binary at : C:\
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Users\bened\Desktop\bmcintellij\IntelliJ IDEA Community Edition 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [version 10.0.19041.572]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.43

• No issues found!
```
`

**Comment by stevemessick** [comment]
We don't support any plugins other than Flutter and Dart. You should file an issue with Mapfile:
https://github.com/dnltsk/intellij-mapfile-plugin

**Comment by benedicte69** [comment]
Thank you, @stevemessick, for taking time to answer. I can understand that map file is related to an  Android Studio problem and I will ask the author why suddenly this error appears even if I have not a clue of it is for. But what's about those new links appearing in flutter doctor -v:
    .Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
It was not like that before and there is no flutter or dart plugging corresponding to the build#AI-201.8743.12.41. of Android Studio 4.1. on JetBrains site

So please, what does mean those links? 

N.B.: gradle 7 is not so far.... keep the good work! courage!

**Comment by stevemessick** [comment]
See https://flutter.dev/docs/get-started/editor

**Comment by benedicte69** [comment]
After reinstalling, the 'Mapfile error' has gone but links are still there:
master channel:
[√] Android Studio (version 4.1.0)
    • Android Studio at C:\XXXXXXXXXX
    • Flutter plugin can be installed from:
       **https://plugins.jetbrains.com/plugin/9212-flutter**
    • Dart plugin can be installed from:
       **https://plugins.jetbrains.com/plugin/6351-dart**
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
By the way and I am not only the one in, stable channel:
[!] Android Studio (version 4.1.0)
    • Android Studio at C:\xxxxxx
    **X Flutter plugin not installed; this adds Flutter specific functionality.**
    **X Dart plugin not installed; this adds Dart specific functionality.**
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
and to come back to those links; there is nothing for the 4.1 Android Studio build

![steeve](https://user-images.githubusercontent.com/19499129/97227113-4f400280-17d5-11eb-8f8d-ef1ecfe9009f.PNG)
