### ISSUE TITLE
devices menu is missing the open iOS simulator menu item

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#498]
<img width="159" alt="screen shot 2016-12-05 at 11 25 52 am" src="https://cloud.githubusercontent.com/assets/1269969/20899067/aca2fbde-badd-11e6-81f9-6e5805def40d.png">

**Comment by devoncarew** [comment]
And, new devices aren't detected (don't show up in the menu).

**Comment by devoncarew** [comment]
This is for a newly created project. Restarting seems to fix the issue.

**Comment by pq** [comment]
Reproed. 👍    Taking a look.

**Comment by pq** [comment]
Looks like this snuck in w/ 0e9a28a5acdb1043ee9d1d09fb5f3acb7f16596d.  Looks like we're neglecting to setup initial action state.  PR on the way.
