### ISSUE TITLE
Can't turn off color gutter icons

### ISSUE THREAD

**Issue by westito** [flutter/flutter-intellij#4986]
Color gutter icons stay visible, although it is turned off in settings. Only completly disable gutter icons hide the colors.

I tested with stable and EAP Intellij too. Neihter works.

IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.4818.26, built on October 14, 2020
Flutter plugin 50.0

IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Flutter plugin 50.1.4

<img width="786" alt="" src="https://user-images.githubusercontent.com/536799/96580599-d1619000-12d8-11eb-9358-741bd853cf36.png">

## Steps to Reproduce
Open project

## Version info

[✓] Flutter (Channel dev, 1.24.0-1.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale hu-HU)
    • Flutter version 1.24.0-1.0.pre at /Users/westito/flutter
    • Framework revision 12bea61c29 (6 days ago), 2020-10-14 15:57:04 -0700
    • Engine revision 069b3cf8f0
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/westito/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/westito/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • SM N950F (mobile) • ce0617165383e716027e • android-arm64  • Android 9 (API 28)
    • macOS (desktop)   • macos                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)  • web-server           • web-javascript • Flutter Tools
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 86.0.4240.80

• No issues found!

**Comment by stevemessick** [comment]
@devoncarew You've been working in this area recently, haven't you?

**Comment by devoncarew** [comment]
We're not currently looking for a preference setting. It looks like there's a std. pref page for the gutter contributions; we should probably ensure ours can be toggled there (and has a reasonable name, like `Flutter color previews`).
