### ISSUE TITLE
Flutter doctor not detecting Flutter and Dart plugins even after installing them.

### ISSUE THREAD

**Issue by Mohitmadhav** [flutter/flutter-intellij#4989]
## Steps to Reproduce

On running flutter doctor I get:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18362.1139], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.50.1)
[!] Connected device
    ! No devices available

But both the plugins are already installed. I tried manually installing the plugins I get this message:
"Fail to load plugin descriptor from file flutter-studio.jar"

I tried restarting Android Studio and my laptop multiple times but that didn't work.
I even uninstalled and reinstalled Android Studio but the result remained the same.
Due to which I am unable to build my apk file and run my file too from my flutter project.

Please help!!
![Screenshot (2234)](https://user-images.githubusercontent.com/59333817/96679497-64f69780-1391-11eb-85b3-221c26c38972.png)
![Screenshot (2231)](https://user-images.githubusercontent.com/59333817/96679732-db939500-1391-11eb-8c60-fd8901e11bb3.png)

## Version info

√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18362.1139], locale en-IN)
    • Flutter version 1.22.2 at C:\flutter_windows_1.22.2-stable\flutter
    • Framework revision 84f3d28555 (5 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Mohit\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Mohit\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    X Could not determine java version

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\Mohit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • Eluga I9 (mobile) • 9TM79TPNKJQOK7AY • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 2 categories.

**Comment by stevemessick** [comment]
The `flutter` tool is part of the Flutter SDK.

It appears this was fixed by https://github.com/flutter/flutter/pull/58853, but I'm not sure when that will be in the stable channel.

**Comment by Mohitmadhav** [comment]
> The `flutter` tool is part of the Flutter SDK.
> 
> It appears this was fixed by [flutter/flutter#58853](https://github.com/flutter/flutter/pull/58853), but I'm not sure when that will be in the stable channel.

I think that was only for IntelliJ, but I use Android Studio
