### ISSUE TITLE
[Feature Request] Add "new dart class" option to new file options

### ISSUE THREAD

**Issue by danielgomezrico** [flutter/flutter-intellij#4990]
In Kotlin we have an option when you go to "File / new / Kotlin File/Class" or with `cmd + n` in mac:

1.
![image](https://user-images.githubusercontent.com/76348/96730563-ec391080-137b-11eb-8d1e-f3e740807f72.png)

2.
![image](https://user-images.githubusercontent.com/76348/96730624-0115a400-137c-11eb-808b-62717762a4ea.png)

This is really useful because it creates the file with the class name with the proper format.

# Current
When you are going to create a class in intellij, you have to:

1. Write the file name in snake case,
2. Then write it again with pascal case.

Current option:
![image](https://user-images.githubusercontent.com/76348/96730595-f65b0f00-137b-11eb-8b7f-0327e9abbd45.png)

# Proposal
Add an option like with Kotlin to add a Dart class, and it will create the file in snake case, and a class with that same name in pascal case already in the file.

I believe this can be automatically done from intellij and it will be really usefull as I see it.

**Comment by stevemessick** [comment]
Good idea, thanks!

**Comment by stevemessick** [comment]
@alexander-doroshko is this something that should be done in the Dart plugin?
[https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores](https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores)

**Comment by alexander-doroshko** [comment]
Yes, this is controlled by the Dart plugin. Feature requests are welcome in https://youtrack.jetbrains.com/issues/WEB (Subsystem: Dart). 

We may think about other templates, except a simple Dart class. Maybe some Flutter-related templates.

**Comment by danielgomezrico** [comment]
thanks, I moved this into https://youtrack.jetbrains.com/issue/WEB-49221
