### ISSUE TITLE
Run all tests in file

### ISSUE THREAD

**Issue by danielgomezrico** [flutter/flutter-intellij#5000]
## Steps to Reproduce

1. Create a `something_test.dart` file.
2. Create multiple groups like the image below shows.
3. Try to find a way to run all groups in the same file at once.

There's no way to run all tests in one file, we are able to run only one of the groups on it.
  
As you can see there is no green arrow in main (line 6) and so I can not run all tests in one file.
![image](https://user-images.githubusercontent.com/76348/97429797-e98f6b80-18e5-11eb-91d2-8eb071fb2ff8.png)

Currently I am creating one big group that groups all the tests in one file per file to be able to do it but it looks bad too me.

## Version info
```bash
$ f doctor -v

[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-CO)
    • Flutter version 1.22.0 at /Users/danielgomez/projects/dev/flutter
    • Framework revision d408d302e2 (4 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/danielgomez/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/danielgomez/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

⣯
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[!] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by helin24** [comment]
Thanks for the report. Are you able to run a full file by manually setting up configuration? The steps for this are:
1. Go to Edit configurations
![Screen Shot 2020-10-28 at 9 12 28 AM](https://user-images.githubusercontent.com/6379305/97464085-b5c04000-18fd-11eb-931a-de252358b84a.png)
2. Add a flutter test
![Screen Shot 2020-10-28 at 9 13 05 AM](https://user-images.githubusercontent.com/6379305/97464164-cbce0080-18fd-11eb-99c2-f4aab2184a05.png)
3. For Dart entrypoint, select the full file.
4. Run the tests by selecting the new configuration and using the top menu buttons

Either way, I agree having a green button by 'main' would make sense.

**Comment by danielgomezrico** [comment]
@helin24 your advise works, it will be cool to have it there, vs code plugin already allows this.
