### ISSUE TITLE
flutter plugin not installed in Android Studio

### ISSUE THREAD

**Issue by mefahimrahman** [flutter/flutter-intellij#5014]
I've installed flutter using this -
`git clone https://github.com/flutter/flutter.git -b stable`
command. Then I've installed flutter plugin from marketplace in my VS Code and Android Studio. Then I run 
`flutter doctor` in cmd.

Its gives an error for Android Studio -

![Capture](https://user-images.githubusercontent.com/25373224/97799239-01a11b00-1c57-11eb-925b-4c4c9bda3e34.PNG)

How can I solve this problem?

## Version info
Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used options.

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

![Capture](https://user-images.githubusercontent.com/25373224/97799352-fc909b80-1c57-11eb-9595-33298d4d51f5.PNG)

**Comment by mefahimrahman** [comment]
Added the output of `flutter doctor -v` in my issue.

**Comment by helin24** [comment]
This is unfortunately a known issue for Android Studio 4.1 (see https://github.com/flutter/flutter/issues/67986). flutter and the flutter plugin should work even though `flutter doctor` isn't detecting it. Is the lack of detection causing any other problems for you?

**Comment by mefahimrahman** [comment]
Yes, although it's showing the error but flutter works in Android Studio. Thank you @helin24 for your time.
