### ISSUE TITLE
Theme tracking tool

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#5018]
I am not sure if this is the right repo for this feature request, so please move it if necessary.

Sometimes I want to understand why a text is white, while it should be black. Or some color is not what it's supposed to be. 

Currently we are very limited on how to track why a widget has a particular color. We can look the color value in the Flutter Inspector, but if we want to see where the color is coming from we need to setup some breakpoints and dive deep into the widget's build or RenderBox code.

A tool that shows the origin of a particular theme property (color, typography etc.) would be very helpful. 

I imagine this won't be simple to create, maybe will need changes into the widget's source code to provide debug theming information, but still it could be very valuable.

**Comment by devoncarew** [comment]
Thanks for the feedback! The place something like this would likely be implemented is in DevTools.

**Comment by devoncarew** [comment]
Issue moved to [flutter/devtools #2483](https://github.com/flutter/devtools/issues/2483) via [**ZenHub**](https://www.zenhub.com/)

**Comment by feinstein** [comment]
Thanks @devoncarew.
