### ISSUE TITLE
Resource Manager - Waiting for Build to Finish...

### ISSUE THREAD

**Issue by llaenowyd** [flutter/flutter-intellij#5027]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I reached that point to try to put a beta test up on the play store and that means I have to navigate the icon review gauntlet.

Unfortunately, it looks like it's _Waiting for ~~Godot~~ the build to finish_

I installed Android Studio Canary but I think that was not the solution I had hoped for and caused a lot of settings to get slightly messed, some involving the installation of a 2nd Android SDK at `c:\users\me\AppSettings\Local`

I deleted that and tried to go back to Android Studio stable but now flutter doctor tells me the flutter plugin is not installed.  I removed the Flutter and Dart plugins and restarted the IDE and installed them again but flutter doctor hasn't changed from what it was.

I'm not sure perhaps I need to start from a new Windows install at this point 😢 

## Version info

```
λ d:\bin\flutter\flutter\bin\flutter.bat doctor -v
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.22.3 at d:\bin\flutter\flutter
    • Framework revision 8874f21e79 (8 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\bin\android_sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\bin\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\bin\AndroidStudio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

(the problems about the plugins are kind of a lie, I'm sure it's some setting that's messed up but they are installed and show up as such in settings/plugins)

**Comment by llaenowyd** [comment]
One question I have is basic - some google searching shows there are a lot of odd solutions for "Waiting for the build to finish..." and it seems like this diagnostic is not really very accurate to what is going wrong, that may be different in each case.

So is there a way to get more verbose diagnostics from the thing that fails when trying to display the Resource Manager?

**Comment by pq** [comment]
Sorry for the hassle @llaenowyd.  I wonder, @stevemessick: any advice?

**Comment by stevemessick** [comment]
JetBrains changed the location where plugins are stored. The Flutter SDK hasn't caught up to that change yet. Obviously the plugin is installed if you are seeing any Flutter support in the IDE.

What version of the Flutter plugin are you using?

Please attach a screen shot of the "Waiting for the build to finish" message. This may be an issue with the SDK rather than the plugin.

If you can, your quickest resolution may be a complete re-install. Be sure to remove the cache files added by the IDE. [https://www.jetbrains.com/help/idea/2020.1/uninstall.html](https://www.jetbrains.com/help/idea/2020.1/uninstall.html) If you decide to do that please let us know the result.

**Comment by llaenowyd** [comment]
> What version of the Flutter plugin are you using?

51.0.2.

> Please attach a screen shot of the "Waiting for the build to finish" message.

![android_studio_resource_manager](https://user-images.githubusercontent.com/41239783/98839507-9a802500-2413-11eb-9f13-d42e6e7a0523.png)
![android_studio_resource_manager_show_ide_version](https://user-images.githubusercontent.com/41239783/98839521-9ce27f00-2413-11eb-9991-0e948025270a.png)

> a complete re-install

Android Studio only or also IntelliJ Ultimate or all IntelliJ IDEs?  (the settings I'll have to wipe out become more of a loss at each step)

**Comment by stevemessick** [comment]
Flutter projects do not use the Android Studio resource manager. Switch to `Project` and you'll be good.

**Comment by llaenowyd** [comment]
Ok, I wonder how to arrive at the Asset Studio, I can reach it by trying to add a new image asset in a React Native app, but the menus seem a bit different when opened on a Flutter App.  Honestly the only reason I was mucking around in the Resource Manager was trying to find a way to here:

![android_studio_asset_studio](https://user-images.githubusercontent.com/41239783/98859756-a6c6ab00-2430-11eb-8a76-42cf139e0f23.png)
