### ISSUE TITLE
Smart code completion not able to infer the type. 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#5028]
## Steps to Reproduce

```
// Create a function. 
Future<int> _future() async => 0;
```

```
// Use it like:
final foo = _future().then<double>((i) => i.toDouble());
```

**Screenshot:** 

![image](https://user-images.githubusercontent.com/40364434/98430496-0a0db180-20ae-11eb-8dcc-d908129968ba.png)

The type of `foo` should be `Future<double>` and not `dynamic`, even if I don't use `then<double>`. However, I just did that to show strong mode. 

## Version info

```

[✓] Flutter (Channel dev, 1.24.0-6.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-6.0.pre at /Users/chocolate/fd
    • Framework revision 13896b3bd1 (9 days ago), 2020-10-28 19:43:19 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chocolate/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2
```

**Comment by pq** [comment]
Thanks for the report @dark-chocolate!

I'm not seeing this reproduce on an SDK built from HEAD.

![image](https://user-images.githubusercontent.com/67586/98687378-83abd680-231e-11eb-871b-3187eb137677.png)

Hopefully that fix will get picked up in the next dev release... 🤞

**Comment by dark-chocolate** [comment]
@pq You're right sir, sometimes it works and sometimes it doesn't. On that day, I did restart my IDE to check if it works, and it didn't. Today, it's working. Shall we close the issue then? 

This time I even omitted the type cast and it infers the type as expected. 

![image](https://user-images.githubusercontent.com/40364434/98750471-544ca680-23be-11eb-9f97-35d1f6cc9e3e.png)

**Comment by pq** [comment]
Ok, so that's weird.  I'm not sure what could have caused that inconsistency and certainly sorry for the hassle. Let's close for now but please re-open if anything recurs?

Thanks!
