### ISSUE TITLE
GrepConsole plugin support

### ISSUE THREAD

**Issue by krasa** [flutter/flutter-intellij#5030]
The console is not highlighted by my plugin - https://github.com/krasa/GrepConsole/issues/180

The problem is `setUsePredefinedMessageFilter(false);` in `io.flutter.run.common.ConsoleProps#ConsoleProps`, it needs to be true.
The same problem in `io.flutter.run.daemon.DaemonConsoleView#DaemonConsoleView` constructor.

Any reason why it is false, and could you please change it?

Thanks.

**Comment by pq** [comment]
@devoncarew ?

**Comment by blasko** [comment]
Hopefully we'll be seeing some updates on this soon.

**Comment by rockingdice** [comment]
Still no update?

**Comment by nerder** [comment]
It seems like it works now with the latest version of Grep Console (https://github.com/krasa/GrepConsole/issues/180#issuecomment-834309151).

Probably this issue can be closed for now

**Comment by krasa** [comment]
@nerder Hi, sorry I missed this. It works because of a hack, a bad hack that has to be removed. Could you please quickfix this?
