### ISSUE TITLE
[Android Studio] Flutter inspector overlap embedded emulator view

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter-intellij#5038]
Hello, 

I try the new Android studio version with his new feature : embedded emulator instead of external window.
I'm on Windows 10 pro 20H2.

I found an issue : The flutter inspector overlap the emulator view instead of split when enabling experimental "embedding DevTools webview"

![emolatorview](https://user-images.githubusercontent.com/37028599/98829000-00cb6e80-2439-11eb-8ba7-592e52c9591a.PNG)
![inspector](https://user-images.githubusercontent.com/37028599/98829006-032dc880-2439-11eb-933d-f47ec3c4f12f.PNG)

## Android

Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: com.thoughtworks.gauge, org.intellij.plugins.markdown, com.intellij.marketplace, org.jetbrains.kotlin, BashSupport, com.intellij.plugin.adernov.powershell, pl.pszklarska.pubversionchecker, Dart, io.flutter

## Flutter plugin : 

flutter.dev 51.0.2

## Flutter

[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [version 10.0.19042.610], locale fr-FR)
    • Flutter version 1.22.3 at C:\Users\engue\Documents\Softwares\flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\engue\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by stevemessick** [comment]
@helin24

**Comment by helin24** [comment]
I think this should be fixed by the same change as https://github.com/flutter/flutter-intellij/issues/5042
