### ISSUE TITLE
hello_services is missing IntelliJ project metadata

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#504]
`//examples/`

**Comment by pq** [comment]
This will address #466.

**Comment by pq** [comment]
Fixed as of https://github.com/flutter/flutter/pull/7025.

**Comment by mit-mit** [comment]
@abarth @pw we seem to be missing an .iml file in `/examples/hello_services/` -- is that intentional?

**Comment by pq** [comment]
`hello_services` is sort of special so I'm guessing it's intentional.  @abarth ?

**Comment by abarth** [comment]
Not intentional.  The goal is to make hello_services non-special.
