### ISSUE TITLE
[Feature Request] add all required params option

### ISSUE THREAD

**Issue by danielgomezrico** [flutter/flutter-intellij#5040]
When a method has some `@required` params and you try to call it without the labels on the call it shows a warning or error based on your lint, if you hit `alt + enter` in there a list of options to fix the lint is shown with some options.

Example to reproduce it:
```dart
void doSomething({@required int id, @required String name}) {
}

void main() {
  doSomething();
}
```

This is cool but when you have a lot of params it is a little bit cumbersome to do it one by one.

# Current
It shows one option per required file:

![image](https://user-images.githubusercontent.com/76348/98858290-5e0df280-242e-11eb-8ceb-0c8be0e55516.png)
![image](https://user-images.githubusercontent.com/76348/98858001-e0e27d80-242d-11eb-84fd-98dcde43e2ea.png)

# Expected
Shows all of those plus one option that allows you to pull all of them with one action.

# Environment
- Flutter plugin: `51.0.3`
- Intellij: `2020.2`

**Comment by Dxree** [comment]
Hey, I would like to work on that.
