### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by PartapSBimrah** [flutter/flutter-intellij#5041]
I have already installed the flutter and dart plugins in Android studio. When I run the `flutter doctor -v` command then it shows me that you've not installed the plugins in Android studio. Please fix this error.

**Comment by stevemessick** [comment]
It is fixed in the master channel of the Flutter SDK.

**Comment by PartapSBimrah** [comment]
I have updated flutter but as the result same. See the screenshot below

![Screenshot (314)](https://user-images.githubusercontent.com/39325207/99136381-7c503a00-264a-11eb-8713-3f34753e5d90.png)
