### ISSUE TITLE
Flutter Inspector Appearance Bug in Android Studio 4.1

### ISSUE THREAD

**Issue by vishwasobra** [flutter/flutter-intellij#5042]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

![flutter_bug](https://user-images.githubusercontent.com/19964861/98902585-05952e80-24dc-11eb-8dda-b9098b042d36.PNG)
![flutter_bug2](https://user-images.githubusercontent.com/19964861/98902697-38d7bd80-24dc-11eb-8b09-66b45bae6485.PNG)
## Steps to Reproduce

When I open flutter inspector in android studio, the panel of flutter inspector is not contained in the window container.

## Version info

[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.572], locale en-IN)
    • Flutter version 1.22.3 at C:\src\flutter\flutter
    • Framework revision 8874f21e79 (13 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\vishw\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.49.3)
    • VS Code at C:\Users\vishw\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 2 categories.

**Comment by EArminjon** [comment]
https://github.com/flutter/flutter-intellij/issues/5038

**Comment by stevemessick** [comment]
@helin24 Could you take a look at this one, too? I think it is using JxBrowser but am not positive.

**Comment by helin24** [comment]
Yes, both of these are the issue of JxBrowser being shifted on Windows. They recommended using off screen mode for Windows, so I will try that.

**Comment by stevemessick** [comment]
Thanks @helin24, feel free to change the milestone if my guess is unrealistic.

**Comment by helin24** [comment]
Hopefully the change to off screen mode fixes this issue, the next dev release will include the change (you can set up receiving dev releases [here](https://github.com/flutter/flutter-intellij/wiki/Dev-Channel)). For now I recommend starting DevTools from the Run/Debug panel or turning off 'Enable embedding DevTools' in Preferences > Languages & Frameworks > Flutter.

**Comment by helin24** [comment]
Please reopen if the next dev release doesn't fix though!
