### ISSUE TITLE
Syntax highlighting doesn't work in tests

### ISSUE THREAD

**Issue by RenatFakhrutdinov** [flutter/flutter-intellij#5049]
## Steps to Reproduce

Working in AndroidStudio I found that syntax highlighting stopped working in test dart files today. Highlighting works well in regular dart files. Also test run buttons are gone. Tests from the console are run. But writing tests without syntax highlighting is very inconvenient. Flutter doctor shows that flutter plugin is not installed but it's actually installed.

## Version info

```
[✓] Flutter (Channel unknown, 1.20.4, on Mac OS X 10.15.7 19H15, locale ru-RU)
    • Flutter version 1.20.4 at /Users/macbookpro/flutter
    • Framework revision fba99f6cf9 (8 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.193
```

**Comment by stevemessick** [comment]
Is the directory that contains your test files marked as "Test Sources Root"? If you select the test directory and bring up the context menu (right mouse click in most cases) you should see something like this at the bottom:

<img width="734" alt="Screen Shot 2020-11-16 at 9 07 58 AM" src="https://user-images.githubusercontent.com/8518285/99284576-45655a00-27eb-11eb-97af-691a266369f4.png">

**Comment by RenatFakhrutdinov** [comment]
@stevemessick I tryed to mark and unmark test directories. But nothing happen. Syntax highlighting still doesn't work.

**Comment by stevemessick** [comment]
Can you add a screen shot similar to the one below? Use the `File > Project Structure` menu to open the dialog. Select the module that does *not* have "_android" in its name. Ignore errors. If proprietary information would be included, please collapse any folders that would reveal it.

<img width="1019" alt="Screen Shot 2020-11-16 at 5 03 58 PM" src="https://user-images.githubusercontent.com/8518285/99326985-cb09f980-282d-11eb-925f-39fa73200c11.png">

**Comment by RenatFakhrutdinov** [comment]
Hi!
I dunno what happen but the problem has gone. I think you can close the issue. Thank you for the concern.

**Comment by stevemessick** [comment]
Great, thanks for the update.
