### ISSUE TITLE
Android Studio completely blocked when Android module is opened using `Flutter -> Open Android module in Android Studio`

### ISSUE THREAD

**Issue by neokree** [flutter/flutter-intellij#5051]
## Steps to Reproduce

Open a plugin project. 
Right click on the `android` folder in the root of the project
Select `Flutter -> Open Android module in Android Studio`
When the "Open project" modal appears, choose "This Window".
The new project will open without any files opened and showing "Loading", but the project will never load. 

Any menu buttons will not work either, and using "Close" will not close the project. 
The only way is to force close it

## Version info

Tested on a MacBook Pro 2018, running Mac Catalina 10.15.7

Flutter doctor
```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H15, locale it-IT)
    • Flutter version 1.22.2 at /Users/neokree/Library/Flutter
    • Framework revision 84f3d28555 (4 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/neokree/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • F1 (mobile) • F120190100010790 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

```

Android Studio version
```
Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: com.thoughtworks.gauge, uk.co.itmoore.intellisubsteps, org.jetbrains.kotlin, gherkin, name.kropp.intellij.makefile, Dart, io.flutter, ru.adelf.idea.dotenv
```

**Comment by neokree** [comment]
@stevemessick Thank you for your response. 

I just started opening projects using "File -> Open", which works as expected. 
Probably it doesn't work in my case because I have added, for my Project Module (under Project Structure) multiple "Content Root", in order to see all my linked projects from the same Android Studio Project. 

To explain my situation, I have a repo that is similar to the [flutter/plugins](https://github.com/flutter/plugins) repo, and my primary project is dependent on project in the same `packages` folder. In order to look at the code without opening/closing projects every time I added them as "Content Root"s.

**Comment by stevemessick** [comment]
Missed this earlier, sorry.

Unfortunately, due to some ancient assumptions in the Flutter code, your configuration is not fully supported by the Flutter plugin. It assumes (in some places) that the top-level directory is the project root. We're working to relax that assumption but aren't quite there yet.
