### ISSUE TITLE
Flutter Inspector Tab is broken on Android Studio 4.1.1

### ISSUE THREAD

**Issue by afkhalid** [flutter/flutter-intellij#5056]
- Steps to reproduce the problem (including sample code if appropriate).

Update to 4.1.1 and try to open the flutter inspector when an app is running

- What happened.

After updating my Android Studio to 4.1.1 the Flutter Inspector is not showing on the right tab anymore and it looks like the screenshot attached. This was not happening in the previous version and happening only on the inspector tab. PLEASE HELP.

- What you think the correct behavior should be.

It should be like always the UI is docked on the tab like the Outline and Performance tabs

![image](https://user-images.githubusercontent.com/24521000/99353641-98074a80-28ad-11eb-9655-7d94a2609b7f.png)

**Comment by tgpsantos** [comment]
I had the same issue a few days ago

**Comment by stevemessick** [comment]
@helin24 Could you investigate?

**Comment by helin24** [comment]
It looks like this is on windows and is the same issue as https://github.com/flutter/flutter-intellij/issues/5042. Hopefully this will be fixed in the next dev release.
