### ISSUE TITLE
Auto import not working

### ISSUE THREAD

**Issue by tgpsantos** [flutter/flutter-intellij#5058]
## Steps to Reproduce

In the past days my Android Studio has been having difficulties finding and automatically importing files to a particular Dart file.

Example, I'm working in `user.dart`, and decide to use `Age` from `age.dart` in `user.dart`. What normally happens is that I only need to type `Age`, and intellij detects that there is an Age class and automatically suggest me to import that file.

Unfortunately now I only get that behaviour in the first few minutes of Android Studio. After some time it simply stops automatically looking for and importing dart files. I don't know exactly what's causing this (there are no errors whatsoever).  

## Version info
```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale pt-PT)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pro\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\pro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • SM G960F (mobile) • 1cf59660af0d7ece • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

In spite of what is said here, I have Flutter plugin installed and working ([see here](https://user-images.githubusercontent.com/48353485/99380943-841a1380-28c2-11eb-8506-528e19e78cd2.png)). Could this be an issue of paths / is it relevant to my problem?

PS: Other functionalities seem to be working flawlessly (example: Widget Refactor)

Thanks for all the help!

**Comment by guit4eva** [comment]
Same issue here after updating to 1.22.4 Stable

**Comment by serzhikdnepr** [comment]
I also had such a problem after updating to 1.22.4 Stable
I fixed the problem by updating to the latest version android studio

**Comment by tgpsantos** [comment]
Which Android Studio version? I have `4.1.1` (most up-to-date in stable channel)

**Comment by agadev** [comment]
Same Problem

**Comment by chrisDK1977** [comment]
Have the same problem with intellij idea ultimate. When deleting .packages the autoimport works for a short time

**Comment by stevemessick** [comment]
@devoncarew Is auto-import handled by the analyzer?

**Comment by devoncarew** [comment]
Yup; this is likely an analysis server issue; I'll move this to the sdk repo.

cc @scheglov
