### ISSUE TITLE
stanim template should put the super.initState in the first line

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#5063]
`stanim` creates `initState` like this: 

```dart
@override
void initState() {
  _controller = AnimationController(vsync: this);
  super.initState();
} 
```

But if you read the [docs of initState](https://api.flutter.dev/flutter/widgets/State/initState.html), it clearly mentions that 

>If you override this, make sure your method starts with a call to super.initState().

**Comment by jacob314** [comment]
This should be a trivial fix and will avoid putting users on the wrong path.
Fyii @pq would be nice if we had lints for this and we verified that all our templates were lint free.
