### ISSUE TITLE
Android studio always show preview of MaterialIcons for IconData

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter-intellij#5071]
Android studio always show preview of MaterialIcons for IconData
![image](https://user-images.githubusercontent.com/19644997/99899375-2fa9d600-2cbe-11eb-8a27-2a305b85f863.png)

## Steps to Reproduce

Add a custom font in `pubspec.yaml` and define a `IconData`

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

I installed latest version of plugin (Ignore not installed in the following)

```dart
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (9 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\PC\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\PC\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```

**Comment by jacob314** [comment]
Thanks for the feature request. We should at minimum detect when icon data is not for a material font and hide the icons. Ideally we would render icons from all fonts probably using flutter desktop to render the icons to a cache.

**Comment by sm2017** [comment]
@jacob314 There is another related bug, Outside of custom icons definition class, the preview is not shown

![image](https://user-images.githubusercontent.com/19644997/100840438-1efe1a80-348b-11eb-8ca1-7ee0ae410ed3.png)

**Comment by stevemessick** [comment]
The related bug is covered by #2334

**Comment by BetterB0y** [comment]
Will it be supported? To show custom icons preview?
