### ISSUE TITLE
Android studio not responding while I creating a new dart file.

### ISSUE THREAD

**Issue by boffincoders** [flutter/flutter-intellij#5074]
Not responding issue: Android studio not responding while I created new dart file. Every time open new tab with add to git or not confirmation and I am unable to click anywhere. Every I force quit android studio and reopen my application. It happened every time. Performance is very low after my last update. I have 4.1.1 android studio version. 
IDE not responding when I create new file, copy a file, open new project in new tab, even deleting a file. Click event not responding. Please see in video gif.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30718659/100190838-16e72d80-2f15-11eb-8a44-05e27a9c3fb4.gif)

**Comment by jacob314** [comment]
Sorry to hear you are having this issue. Do you see the issue when creating all fiiles or just Dart files?
Can you attach a screenshot of the activity monitor on mac so we can see whether it is a CPU or memory issue.
If you uninstall the dart and flutter plugin do you still see the issue or is performance fine?

**Comment by boffincoders** [comment]
@jacob314 thanks for reply. I checked and get this issue with all files. I think there is no any memory issue because android studio work file before my last update. Yes, If i uninstall the dart and flutter plugin still  issue is there.
I also opened issue [here](https://issuetracker.google.com/issues/174173650)  but I think someone not take is serious.

**Comment by jacob314** [comment]
If you see the issue even when the Dart and Flutter plugins are uninstalled then there is nothing my team can do to fix the issue. I would suggest uninstalling android studio and reinstalling it to see if that fixes your problem. You should clarify on that other issue that the issue still occurs when you uninstall the Dart and Flutter plugins. They will assume it is a Dart or Flutter issue until they have that information.

**Comment by boffincoders** [comment]
I completely uninstall android studio and reinstall it. After that I created a new android project but the issue is same.
