### ISSUE TITLE
Unused methods aren't getting darkened if they are not referenced. 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#5075]
The method is local to the library, if it's not used, it should have been darkened (not sure what the actual term should be) as it used to do. 
I tried restarting the IntelliJ Idea but nothing changed. 

![image](https://user-images.githubusercontent.com/40364434/100206039-214dfb00-2f06-11eb-826b-51b1dad976c6.png)

### Flutter doctor:
```
[✓] Flutter (Channel dev, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    ! CocoaPods 1.8.4 out of date (1.9.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
[✓] VS Code (version 1.49.0)
```

**Comment by stevemessick** [comment]
@dark-chocolate I can't reproduce this. Have you tried using the menu `Edit > Find > Find in Path...` to search for "_showAd"?

**Comment by dark-chocolate** [comment]
@stevemessick Sir, in the attached video, you can see I'm creating a new method (obviously it wasn't referenced anywhere before) and still the method isn't getting darkened. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/40364434/100833969-48a74980-346b-11eb-819d-db9f3a8a9cd5.gif)

**Comment by stevemessick** [comment]
Is this with Android Studio or IntelliJ?

I just duplicated your example and the syntax highlighting looks correct.

<img width="354" alt="Screen Shot 2020-12-02 at 4 45 21 PM" src="https://user-images.githubusercontent.com/8518285/100948963-e461a580-34bd-11eb-8a16-2c8f20b84bd8.png">

Could you confirm that unused symbols are supposed to be grayed-out? The setting is here:

<img width="992" alt="Screen Shot 2020-12-02 at 4 52 08 PM" src="https://user-images.githubusercontent.com/8518285/100949327-dc563580-34be-11eb-9c8b-c3e97845a982.png">

**Comment by dark-chocolate** [comment]
First of all thanks for the word "greyed-out". 

I checked the settings and to me it looks like everything is good. 

![image](https://user-images.githubusercontent.com/40364434/101228181-d61cb080-369a-11eb-82f7-7e081d1f282d.png)

This happens in IntelliJ IDEA 2020.3 (Community Edition)

**Comment by dark-chocolate** [comment]
@stevemessick Sincere apologies. I just found that I was using:
```
// ignore_for_file: unused_element
```

**Comment by stevemessick** [comment]
Haha, np. Thanks for closing.
