### ISSUE TITLE
Incompatibility with IntelliJ 2020.2.4

### ISSUE THREAD

**Issue by g123k** [flutter/flutter-intellij#5077]
Hello,

A new release of IntelliJ is available: 2020.2.4 (202.8194.7 build).
However the Flutter plugin is incompatible with this version.

Any ETA when it will be?

**Comment by feinstein** [comment]
Just to add some info, we are seeing this notification:

![image](https://user-images.githubusercontent.com/8120472/100293704-46248b80-2f63-11eb-992f-8b1f6f8da415.png)

**Comment by shaun0203** [comment]
<img width="737" alt="Screenshot 2020-11-26 at 14 41 47" src="https://user-images.githubusercontent.com/47631316/100352345-86344e80-2ff5-11eb-8a14-7984822f69a1.png">

**Comment by pruidong** [comment]
I also encountered this problem, you need to uninstall and reinstall the Flutter plugin. Version: 50.0 supports idea 2020.2.4. Reference: https://plugins.jetbrains.com/plugin/9212-flutter/versions

**Comment by pruidong** [comment]
> I also encountered this problem, you need to uninstall and reinstall the Flutter plugin. Version: 50.0 supports idea 2020.2.4. Reference: https://plugins.jetbrains.com/plugin/9212-flutter/versions

After I reinstall it, it can be used normally.

**Comment by jacob314** [comment]
Fyi @stevemessick

**Comment by stevemessick** [comment]
There is a new version available now for IntelliJ 2020.2.4. This one won't automatically update. You need to uninstall version 51 then look for the version named SNAPSHOT.

1. Open Settings/Preferences
2. Select `Plugins`
3. Select `Installed`
4. Select Flutter
5. Click the drop-down arrow next to `Disable` and choose `Uninstall`
6. Close the modal window
7. IntelliJ uninstalls the plugin; I did not have to restart
8. Re-open Settings/Preferences and re-install the plugin with the SNAPSHOT version
9. Restart IntelliJ

We plan to release version 52 at the end of the week. If you have already switched to version 50, as suggested above, you might want to wait for that.
