### ISSUE TITLE
Flutter New Projects leads to 'Pub get' prompt

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#508]
This can be a little hard to repro -- I have found that it rarely repros if doing File-New with IntelliJ already open, but seems to repro every so often like this:

1. Start IntelliJ if not already running
1. File > Close Project, for all open projects
1. Exit IntelliJ 
1. Start IntelliJ
1. Click Create New Project from the Welcome dialog
1. Select Flutter, Next, enter name, Next

=> After a few seconds this appears:

![screen shot 2016-12-07 at 15 40 20](https://cloud.githubusercontent.com/assets/13644170/21004787/6b7dc8f8-bd32-11e6-8d48-21ccfa25a2a3.png)

=> After a few more tens of seconds it disappears again

**Comment by mit-mit** [comment]
cc @pq

**Comment by alexander-doroshko** [comment]
see https://github.com/flutter/flutter-intellij/issues/336#issuecomment-254877414

**Comment by mit-mit** [comment]
Thanks @alexander-doroshko that explains why it's only happening sometimes. Will close this and track this in #336.
