### ISSUE TITLE
Too many chromium.exe

### ISSUE THREAD

**Issue by tree1891** [flutter/flutter-intellij#5082]
android studio 4.1.1
    • Flutter version 1.22.4
    • Dart version 2.10.4

![image](https://user-images.githubusercontent.com/1282201/100742798-541c5580-3416-11eb-8c51-81e73365b66b.png)

**Comment by devoncarew** [comment]
Thanks for the report! Can you also include the version of the Flutter IntelliJ plugin you're using? That info is available in the android studio settings dialog, in the plugins page.

cc @helin24 - it looks like there are situations where we either start too many copies of the JXBrowser browser, or don't properly clean up instances for all situations.

**Comment by devoncarew** [comment]
This is likely a dup of https://github.com/flutter/flutter-intellij/issues/5083.

**Comment by tree1891** [comment]
flutter plugin: 51.0.2
dart plugin: 201.9245

**Comment by helin24** [comment]
This does look like a duplicate, closing this one.

**Comment by helin24** [comment]
@tree1891 you can try our dev channel release, which should be opening only one instance of the browser for each project. See instructions here: https://github.com/flutter/flutter-intellij/wiki/Dev-Channel

If that doesn't work I'll investigate whether we need to close the browser more explicitly.
