### ISSUE TITLE
DevTools Chromium memory leak

### ISSUE THREAD

**Issue by vlkigdm** [flutter/flutter-intellij#5083]
Oh god please revert back to vanilla DevTools/Flutter Inspector on dev channel.

https://imgur.com/a/BInvJO5

Flutter (Channel dev, 1.23.0-18.0.pre, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)

**Comment by devoncarew** [comment]
cc @helin24

**Comment by devoncarew** [comment]
Note that both the the reports we've seen of this issue happen on windows.

**Comment by helin24** [comment]
@vlkigdm and anyone else having this problem, you can disable embedded DevTools by going to Preferences -> Languages & Frameworks -> Flutter and unchecking "Enable embedding DevTools ..." under Experiments.

**Comment by helin24** [comment]
This may have been fixed with https://github.com/flutter/flutter-intellij/pull/5035, which should mean one browser instance is reused. @vlkigdm can you let me know what version of the Flutter IntelliJ plugin you're using?

**Comment by dvird** [comment]
big issue on my computer too

**Comment by helin24** [comment]
@dvird is this happening after a restart with the latest version of the Flutter IntelliJ plugin (v52)? If so please send your `flutter doctor -v` output also.

**Comment by dvird** [comment]
im working with the latest android studio
@helin24 
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)

**Comment by helin24** [comment]
@dvird there have been changes to the plugin recently, so can you send your Flutter plugin version as well? This is in Preferences -> Plugins (e.g. mine is 53.0.1-dev.1):
![Screen Shot 2020-12-21 at 7 50 35 AM](https://user-images.githubusercontent.com/6379305/102795171-4bf26e80-4361-11eb-8a35-1b8cf7d9291d.png)

Another thing that may help us debug - could you check "verbose logging" (Preferences -> Languages and Frameworks -> Flutter):
![Screen Shot 2020-12-21 at 7 54 00 AM](https://user-images.githubusercontent.com/6379305/102796395-1058a400-4363-11eb-9a02-785500aea596.png)

then send us the logs while having this problem? The logs are at Help -> Show Log in finder -> idea.log
