### ISSUE TITLE
Flutter run window unable to show output when using the language pack plugin

### ISSUE THREAD

**Issue by floating-cat** [flutter/flutter-intellij#5086]
## Steps to Reproduce

1. Install a language pack (https://plugins.jetbrains.com/plugin/13710-chinese-simplified-language-pack----) and enable it.
2. Install the Flutter plugin.
3. Run a Flutter app.

Result:
Unable to see the output in Flutter's run window.
![image](https://user-images.githubusercontent.com/6748077/100877713-2271c000-34e4-11eb-8ff7-db3d4f8b519d.png)

There is also a related issue reported in the IDEA's issue tracker: https://youtrack.jetbrains.com/issue/IDEA-256495

## Version info

I can reproduce this issue in the IDEA 2020.3 (Flutter plugin version: 51.0.4, Chinese language pack plugin version: 203.500.
The below info is provided from the `Tools > Flutter > Flutter Doctor`, but I have no idea why it failed to detect the IDEA 2020.3 in my local.
```
/home/clj/Downloads/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/clj/Downloads/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/clj/SDK/android
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/clj/SDK/android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /home/clj/Soft/Toolbox/apps/IDEA-U/ch-0/193.7288.26
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

! Doctor found issues in 3 categories.
```

**Comment by stevemessick** [comment]
I can't reproduce this problem with the Japanese language pack. (My Japanese is not good, but better than my Chinese.)

I'll try with Chinese, but if it is specific to the language pack I don't know how to prioritize this.

@csells for input.

**Comment by stevemessick** [comment]
I guess the language pack has been updated to solve this problem. I verified that all three language packs published by JetBrains (Chinese, Japanese, and Korean) work properly now.

**Comment by floating-cat** [comment]
@stevemessick Hi, thanks for looking at this issue. I have tested the issue again, and I can still see this problem in the IDEA 2020.3.1 and Android Studio 4.1.1 with the latest Japanese language pack & Flutter plugin.
Is there a possibility that we use different OSes so that you can't reproduce this issue? I use Linux, and the original issue user uses Windows. Do you use the macOS?

I also noticed that I could see output if I click the debug button, but I can't see the output if I click the run button.

**Comment by stevemessick** [comment]
> I also noticed that I could see output if I click the debug button, but I can't see the output if I click the run button.

Since I almost always use the debug button I'll take another look using the run button.

**Comment by stevemessick** [comment]
I can reproduce the problem using the Run button. Since the Debug button works as expected I'm lowering the priority.

**Comment by floating-cat** [comment]
A user [here](https://youtrack.jetbrains.com/issue/IDEA-269187) told that deleting the translated `debugger.session.tab.console.content.name` property in `XDebuggerBundle.properties` in language pack plugin helps.
I haven't tried it. But the original value of the `debugger.session.tab.console.content.name` is `Console`. You may check if the related flutter code uses hardcoded value like below (not sure if it is root cause) https://github.com/flutter/flutter-intellij/blob/f16fb41436ed8aa88e62a224fb84a511a5eca271/src/io/flutter/run/FlutterDebugProcess.java#L150

**Comment by stevemessick** [comment]
Thanks! #5483
