### ISSUE TITLE
Can't run tests in Unsound Null Safety Mode

### ISSUE THREAD

**Issue by sarbagyastha** [flutter/flutter-intellij#5089]
## Steps to Reproduce
Running individual tests requires adding `--no-sound-null-safety` argument. And currently there's no way to pass the argument. 

Even if there was a way to pass the argument through configuration, it'll still be a bit of a hassle as we would need to update configuration for individual tests with the argument.

It'll be nice if a switch in **Settings** could be added, where users would be able to force using Sound or Unsound Null Safety mode for tests.

## Version info
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-4.0.pre at ***
    • Framework revision a7f5fd5360 (3 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

![image](https://user-images.githubusercontent.com/9782008/100959996-8679a000-3547-11eb-8cb5-768a9f4cd9d2.png)

**Comment by devoncarew** [comment]
Thanks for the report!

We do have a way to pass CLI args to regular app invocations, but not to test runs. It sounds like we should add an additional CLI args field to the test launch config page.

> it'll a bit of a hassle as we would need to update configuration for individual tests with the argument.

They would have to update this for a few test configurations likely, but I think this setting is naturally a pre-test (or perhaps per-project) thing.

**Comment by stevemessick** [comment]
Also see the work-around mentioned here: https://github.com/flutter/flutter-intellij/issues/3835

**Comment by sarbagyastha** [comment]
> They would have to update this for a few test configurations likely, but I think this setting is naturally a pre-test (or perhaps per-project) thing.

A per project flag would be great. 

> Also see the work-around mentioned here: #3835

@stevemessick Sadly, the workaround is no better than running tests through command-line. :confused:

**Comment by devoncarew** [comment]
Update: if we get to this in the near term, we should patch the change into the current (M52) release

**Comment by stevemessick** [comment]
This is in 52.1

**Comment by sarbagyastha** [comment]
@stevemessick How can we set `--no-sound-null-safety` argument  for every test without having to add the argument manually to each test configuration?
