### ISSUE TITLE
Pub vs flutter get

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#509]
Should this lead to `flutter packages` commands, not `pub` commands?

1. Create new Flutter project
1. Open pubspec.yaml
1. Click the Get/Upgrade actions in the action strip

**Comment by mit-mit** [comment]
cc @pq

**Comment by pq** [comment]
Good catch.  Behind the scenes we *are* calling the Flutter pub actions (by setting `FLUTTER_ROOT` as described here https://flutter.io/upgrading/) which is why those actions actually work but the labels might be confusing.  The tricky bit is that the labels are provided by the Dart plugin and we'd have to update them there.  That said, it'd be easy enough...  

Do you feel more specific labels would help here?

**Comment by mit-mit** [comment]
It's not just the labels -- it also seems to have differently. If I create a new project (with File > Create), and the run `flutter packages get` in a terminal no changes are created in my local project dir, but if I click 'Get dendencies' in the action ribbon, then I get a `.pub` folder in my project dir.

**Comment by pq** [comment]
Hmmmm.  Maybe @danrubel can speak to how `flutter packages get` is invoking `pub` but I think it's using the `--[no-]pub` option.  To be really consistent, we could do that too.

**Comment by danrubel** [comment]
```
flutter packages get
```
invokes pub as ...
```
pub --verbosity=warning get --no-packages-dir --no-precompile
```

**Comment by devoncarew** [comment]
I don't think the dart plugin is calling `flutter packages get`, I think it's calling `pub get` with a special flutter env. var set. So we're getting the default value for the no packages flag (and flutter packages get passes in its own desired pref).

**Comment by pq** [comment]
Mulling this over a bit, I'm OK with how we have it implemented but happy to explore refinements.

@mit-mit @devoncarew ?

**Comment by devoncarew** [comment]
sgtm. The default value for `--no-packages-dir` in pub will catch up with what flutter's doing today. But we may also want to expose these flutter specific options in a few places (a context menu, a top-level menu item). I'll create some issues for that.

**Comment by pq** [comment]
Closing this in favor of #515 and #516.

Feel free to re-open if you feel they don't cover it.

**Comment by mit-mit** [comment]
Can you elaborate on how this is covered by #515 and #516? Those look like just adding more ways of invoking this, not a fix of what it's doing.

My core issue is that these actions behave differently from running `flutter packages` commands in a terminal. They should not.

**Comment by pq** [comment]
Wishful thinking I guess. Especially in light of @devoncarew's comment:

> The default value for --no-packages-dir in pub will catch up with what flutter's doing today. 

The rub is that making the pub actions retargetable would require more coordination with the Dart plugin which I was hoping to avoid.  That said, if this is a nagging issue we can keep it open and I can work on a better solution.  I'm cool either way.

**Comment by mit-mit** [comment]
I'm generally worried about the UI not invoking what we expect from the terminal. Who known how 'flutter packages' and 'pub' might diverge in the future...

**Comment by pq** [comment]
Ideal scenario: butterbar is not presented for pubspecs in flutter projects.  We present our own butterbar (same as for flutter.yaml?)

**Comment by pq** [comment]
Closing as fixed by a host of changes, the last bit being tracked in #660.
