### ISSUE TITLE
Flutter inspector window is messed up, any help would be nice.

### ISSUE THREAD

**Issue by MasterMufasa** [flutter/flutter-intellij#5093]
![2020-12-02](https://user-images.githubusercontent.com/33850425/101070653-ddd43c00-3558-11eb-8680-7520b13c47d4.png)
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
I just installed flutter and did everything that the website told me to do. I can run programs just fine but there are a few problems. Flutter doctor says that the flutter and dart plugins do not exist and the flutter inspector window is messed up. The window isn't in its own space, and when I try to resize the page it doesn't go back to normal it just stretches. I have tried reinstalling android studio.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
C:\Users\hyrum>flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\hyrum\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
![2020-12-03](https://user-images.githubusercontent.com/33850425/101071152-71a60800-3559-11eb-9282-e36c1d5b1db9.png)

**Comment by stevemessick** [comment]
@helin24 Have we seen something like this before?

**Comment by helin24** [comment]
Yes, this is similar to https://github.com/flutter/flutter-intellij/issues/5042

@MasterMufasa the JxBrowser team recommended a fix that is part of our upcoming release. In the meantime, you can try out the dev channel release (which already has the fix, see https://github.com/flutter/flutter-intellij/wiki/Dev-Channel) or you can disable the embedded browser (Settings -> Languages & Frameworks -> Flutter, then uncheck "Enable embedding DevTools... " under experiments).

Closing as a duplicate for now; if the dev channel release or the next release (52) does not solve this problem for you, please re-open.

**Comment by stevemessick** [comment]
FWIW the next release will be published early Dec 4, Pacific time.
