### ISSUE TITLE
Exception: Cannot run program "C:\Android\flutter\bin\flutter.bat" (in directory "F:\Flutterprograms"): CreateProcess error=2, The system cannot find the file specified" is showing during creating a new project Android studio. #2986

### ISSUE THREAD

**Issue by gunu-mishra** [flutter/flutter-intellij#5098]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

And if that doesn't display the version of the Flutter plugin, please include the version as well.

Do you get a stack trace? If so, please include that.

**Comment by yinde0** [comment]
I coloned a github repo using the version control, after downloading I opened it as an existing project and boom, I got this same error.

**Comment by yinde0** [comment]
Runing flutter doctor doesn't work both on cmd and my Andriod studio.

**Comment by yinde0** [comment]
Solved.
It was my antivirus that was stopping it from working.

**Comment by vivekpunjabi1** [comment]
> Solved. It was my antivirus that was stopping it from working.

how did you stopped your anivirus from it
