### ISSUE TITLE
The  devices selector is stuck on "Loading Devices" and it stays like that. 

### ISSUE THREAD

**Issue by AbdulSamadgithub** [flutter/flutter-intellij#5099]
<----Problem-----> 
I've just started learning flutter and im setting up my device to run my app. Ive setup the emulator and the device as my instructor says. but it do not detect it. It detects the emulator and my mobile device on android project, but not on flutter. 

Flutter doctor says "unable to locate android sdk" ive set the correct path to android sdk, ive double checked it. Ive installed both plugins dart and flutter.

I tried this solution : 
Link : https://github.com/flutter/flutter-intellij/issues/4761
and updated the plugin. restarted the adb, restarted my computer. unplugged my device several times. restarted android studio and than adb several times. used 1.17.3 version of flutter to check, and nothing works. 

I tried this too: 
Link : https://stackoverflow.com/questions/51101178/android-studio-device-list-stuck-on-loading
started android studio as admin, and ive my sdk in my D: directory. 

Please help. I'll be grateful.

<-----FLUTTER DOCTOR------>

D:\Flutter SDK\flutter_windows_1.22.4-stable\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-GB)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

<------ SS of android studio ------>

![Screenshot (14)](https://user-images.githubusercontent.com/40419515/101262066-a387bc00-375d-11eb-98a2-b5381229ee94.png)

**Comment by AbdulSamadgithub** [comment]
Email : Abdulsamad5sam@gmail.com

**Comment by stevemessick** [comment]
Use this on the command line to tell Flutter where your Android SDK is located:
`flutter config --android-sdk <path>`

Use this to ensure all Android licenses have been accepted:
`flutter doctor --android-licenses`

Your Android Studio should be upgraded to 4.1.1 and version 52 of the Flutter plugin. Let us know if this helps.

**Comment by AbdulSamadgithub** [comment]
I did as you said. even after updating them flutter doctor says flutter and dart plugins are missing. 
my flutter plugin version : 52.0.1.
i've 4.1.1 version of android studio.

this exceptions occured with jdk15 with jdk 8 it is working correct. idk why.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema

im using jdk 8. I want to use the latest version of jdk.

**Comment by stevemessick** [comment]
Android Studio includes its own Java JDK. Don't try to use a different one.

Make sure the `<path>` given to `flutter config --android-sdk` points to you Android SDK, not a Java JDK.

Consult your instructor for further installation help.

**Comment by ivankragoff** [comment]
Encountered this bug with latest release of flutter
![image](https://user-images.githubusercontent.com/5884218/111856729-ba28dc00-8924-11eb-8ba8-84be6cc726cf.png)

**Comment by andrewvmail** [comment]
same here

**Comment by RossHS** [comment]
exactly the same issue

![image](https://user-images.githubusercontent.com/30704653/127130115-3dd798b0-ca19-487f-b1cb-b55e156463e1.png)
