### ISSUE TITLE
`out` is shown in project view

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#510]
Repro steps:

1. Create new Flutter project
1. Hit run
1. Hit stop

=> `out` appears in the project view

We have `<exclude-output />`, so should we not be hiding `out` in the project view?

**Comment by pq** [comment]
Hmmmm...  I'm not seeing this in a repro.  Could you add a screenshot?

**Comment by mit-mit** [comment]
Did you hit 'stop'? It don't happen until you do that.

Here is a screenshot before stop:
![screen shot 2016-12-08 at 15 31 25](https://cloud.githubusercontent.com/assets/13644170/21013768/9243fdee-bd5b-11e6-9189-30e05770282f.png)

And after:
![screen shot 2016-12-08 at 15 32 31](https://cloud.githubusercontent.com/assets/13644170/21013767/90f751a2-bd5b-11e6-9b0c-48fb484b2671.png)

**Comment by pq** [comment]
I did.  It occurs to me though that I'm using the iOS simulator and maybe it doesn't occur there?

**Comment by mit-mit** [comment]
Ah, wait, I know what is going on now! For historical reasons I have a custom flutter settings file:

```
mit-macbookpro2:~ mit$ cat .flutter_settings
{
  "build-dir" : "out"
}
```

I just removed that and `out` is gone, but I still get a `build` folder. And that folder is indeed hidden as expected (when 'show excluded files' is 'off') :-)

**Comment by mit-mit** [comment]
Closing
