### ISSUE TITLE
Crash when showing suggestions on macOS

### ISSUE THREAD

**Issue by Andreigr0** [flutter/flutter-intellij#5103]
## Steps to Reproduce

Can't say exactly how to reproduce it just crashes when it tries to receive suggestions. Sometimes I can work for several hours without crashing and sometimes it could be 2-3 crashes within 10 minutes (!)

I've already tried to completely uninstall Android Studio but it didn't help (https://stackoverflow.com/a/18458893/9586934)
First time it happened about 2-3 months ago

Android Studio 4.1.1 and Flutter plugin 52.0.1

P.S. I've tried to search for this problem but haven't succeed in it, but I asked in Russian community in Telegram and there some people also facing this issue

## Version info
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-10.2.pre at /Users/andrey/flutter
    • Framework revision 022b333a08 (2 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 50.0.2
    • Dart plugin version 201.9002

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • 3997FAF8-563B-4DE0-9BA7-AFF7BF40F2CF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Comment by stevemessick** [comment]
What do you mean by "crash"? Does Android Studio shut down? Or does it generate an error message? If you can attach a stack trace that might help. The log file, especially right after a crash, might also help. Use this menu to find the log file: `Help > Show Log in Finder`

**Comment by Andreigr0** [comment]
Oh, sorry for not exact formulation, I've meant it just freezes after showing a suggestions popup and thats all. So I have to force quite the app and from time to time it shows a dialog to send a stacktrace to Apple.
Next time I get this freeze I'll see the log and send it

**Comment by stevemessick** [comment]
The log will probably be helpful. What do you mean by a suggestions popup? Code completion? Balloon message in bottom right? What did you do that caused the popup? Some possibilities: type a '.', hit alt-return, or ctrl-space. Or maybe a menu selection? Thanks for following up.

**Comment by Andreigr0** [comment]
Code completion. It appears when I just type some code, maybe I press `control+space`, I didn't pay attention to it. Next time I will say exactly.
Also there is a bug with extracting variables
![Screen Recording 2020-12-07 at 23 33 45](https://user-images.githubusercontent.com/44437712/101402898-71a16180-38e5-11eb-89e3-1da7750d0930.gif)

**Comment by Andreigr0** [comment]
Here it is, error at 18:50. I didn't press `control+space`
[idea.log](https://github.com/flutter/flutter-intellij/files/5660315/idea.log)

**Comment by stevemessick** [comment]
The log says the error is caused by the GitToolBox plugin:
`Plugin to blame: GitToolBox version: 201.4.2`

It is out of date, by the way.
