### ISSUE TITLE
Quick action to convert StatelessWidget to StatefulWidget not work

### ISSUE THREAD

**Issue by Mabsten** [flutter/flutter-intellij#5113]
## Steps to Reproduce

Write a StatelessWidget subclass and press Alt+Enter ("Show Context Actions") on the class definition.

## Expected behavior

The "Context Actions" menu shows the "Convert StatelessWidget to StatefulWidget" action.
This "quick action" has been provided with the issue ["Quick action to convert simple StatefullWidget to StatelessWidget"](https://github.com/flutter/flutter-intellij/issues/779), and it worked well, with my previous versions of IntelliJ and Flutter Sdk (unfortunately, I don't remember which ones).

## Actual behavior

The "Context Actions" menu shows "No context actions available at this location".

## Version info

Flutter version 1.24.0-10.2.pre (the last beta release)
IntelliJ IDEA Ultimate Edition version 2020.3
IntelliJ Plugins:
- Flutter plugin version 52.0.5
- Dart plugin version 203.5981.152
- Other plugins enabled: I have disabled all the not bundled plugins except Flutter and Dart.

**flutter doctor -v**
```
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Versione 10.0.19041.572], locale it-IT)
    • Flutter version 1.24.0-10.2.pre at C:\FlutterSdk\flutter_1.24.0-10.2.pre-beta
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\mabsten\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\AndroidStudioCanary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\AndroidStudioCanary
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

**Comment by stevemessick** [comment]
Is this the feature that does not work for you? This is just the sample app from a newly-created project.
<img width="351" alt="Screen Shot 2020-12-09 at 4 01 43 PM" src="https://user-images.githubusercontent.com/8518285/101703665-e5538380-3a37-11eb-8c3f-d6100b047fb6.png">

I tried with the stable channel and with master. Both work. I don't have beta, but I doubt that's the problem.

If the cursor is over the `extends` or farther to the right I see a simpler menu.
<img width="353" alt="Screen Shot 2020-12-09 at 4 10 52 PM" src="https://user-images.githubusercontent.com/8518285/101704289-3dd75080-3a39-11eb-8b3a-dd2cebd49fd4.png">

Perhaps a screen shot would help, if it doesn't reveal proprietary info. Does it work if you create a new project?

**Comment by Mabsten** [comment]
Thanks for your attention.
Yes, it's that feature that doesn't work.
My screenshoot, with a new flutter project:

![2020-12-11 (6)](https://user-images.githubusercontent.com/68533494/101947774-496d7780-3bf1-11eb-99b5-4fee3f01eea2.png)

Even the quick action "convert class to a mixin" does not appear to me.

I did many tests, among which I mention the most important:
- In the same ide (IntelliJ 2020.3) with the **stable** flutter sdk (1.22.4), disabling **all** plugins (even bundled ones, with the exception of flutter and dart): the problem persists .
- In **Android Studio** 4.1.1: the problem does not occur (I see the 2 quick actions as in your screenshoot).
- I have installed **IntelliJ 2019.3.1**, without importing cache and settings: the problem does not occur.
Could the problem be in my settings or cache? Do you know if there is an easy way to give it a try by reinstalling IJ 2020.3 without importing cache and settings? In the installation process of IJ 2020.3 the import always takes place, unlike with the old version (2019.3.1).

**Comment by Mabsten** [comment]
Considering the tests I have done, and since the problem seems to concern only me, I guess the problem was caused by some error in my cache.
I fixed it with a fresh reinstall (It will take me a long time to re-set the ide, but I consider the quick actions important). 
Thank you for your attention.

**Comment by stevemessick** [comment]
I'm glad you got it resolved.
