### ISSUE TITLE
Run tests with coverage option in Android Studio

### ISSUE THREAD

**Issue by yulkin2002** [flutter/flutter-intellij#5117]
## Steps to Reproduce

I would like to run my tests with coverage and I have seen and used (albeit unsuccessfully) the "run with coverage" option in Android Studio.  But not this option has disappeared completely and I am not able to find any instructions on the web on how to bring it back. I am not sure if this is a bug or lack of documentation.

Also, when I was able to run tests with coverage in the past, I was getting coverage info displayed next to each folder and each file, but it always showed 0 coverage. Again, not sure if a bug, but unable to find any more information on the intended behaviour or how to re-produce it.

NOTE: flutter doctor states that Flutter and Dart plugins are not installed, however it's not correct as both are installed and I believe this is some kind of Android Studio bug

## Version info

[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 6.1.7601], locale en-CA)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Yuliya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code
    • VS Code at C:\Users\Yuliya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.0

[√] Connected device (1 available)
    • TA 1004 (mobile) • NB1GAD1832601470 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by helin24** [comment]
@yulkin2002 this isn't a feature we support for Flutter; that's probably why it has shown 0 coverage when the button has worked in the past.

**Comment by stevemessick** [comment]
This is a dup of #518. Keeping open for 2020 planning purpses.

**Comment by stevemessick** [comment]
Fixed in #5463
