### ISSUE TITLE
Regressions in project creation

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#5132]
Creating a new project in Android Studio has recently been giving us two new events that should not be needed.
```
1:30 PM	Flutter pub get.
				The pubspec.yaml file has been modified since the last time 'flutter pub get' was run.
				Run 'flutter pub get'

1:30 PM	Frameworks Detected
				Android framework is detected.
				Configure
```
The first is likely due to some change in the Flutter SDK. The second should have been prevented by special code in flutter-studio to turn off detection.

**Comment by stevemessick** [comment]
The first is done by Dart. The second was disabled because it was causing too many problems.

When the framework configure message shows, click it to open the dialog, deselect all check boxes, and accept the changes. That turns it off for the project.

**Comment by alexander-doroshko** [comment]
```
1:30 PM Flutter pub get.
				The pubspec.yaml file has been modified since the last time 'flutter pub get' was run.
				Run 'flutter pub get'
```
I think it comes from https://github.com/flutter/flutter-intellij/blob/156f828cd308a09276455da24edb260b4d42ef11/src/io/flutter/ProjectOpenActivity.java#L121

**Comment by stevemessick** [comment]
That's right. It is triggered by `io.flutter.pub.PubRoot.hasUpToDatePackages()`, which is comparing file time stamps. The Dart SDK (`pub`) is not setting time stamps the way it used to.
