### ISSUE TITLE
Port over Dart IntelliJ support for debugger list expansion fix

### ISSUE THREAD

**Issue by jwren** [flutter/flutter-intellij#5133]
debugger list expansion fix:

https://github.com/JetBrains/intellij-plugins/commit/ccf36ae6fa0454723335c5a77508ef02913c2559

**Comment by stevemessick** [comment]
This requires a version of XCompositeNode that is only available starting with 2020.3. We need to wait until Android Studio uses 2020.3 for its stable version.
