### ISSUE TITLE
Port over Dart IntelliJ support for displaying special lists

### ISSUE THREAD

**Issue by jwren** [flutter/flutter-intellij#5134]
Now supports displaying special lists (UInt8List, ...), Dart-related part of IDEA-255861:

https://github.com/JetBrains/intellij-plugins/commit/7f1df8521fbda0980e92fba2b4fe4405870d1a0e

**Comment by stevemessick** [comment]
This requires a version of XCompositeNode that is only available starting with 2020.3. We need to wait until Android Studio uses 2020.3 for its stable version.
