### ISSUE TITLE
on project creation, there's a race condition for display flutter create output in the Messages view

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#514]
To repro:

- from IntelliJ, `File > New > Project...`; create a Flutter project
- a new window opens; it shows some project contents
- after a delay, a Messages pane opens. it displays some contents from `flutter create` - sometimes the tail end of it, sometimes an empty view
- the Dart Analysis view often pops up, obscuring the Messages view (not sure that this part of the bug report is actionable)

**Comment by mit-mit** [comment]
I have seen this aswell

**Comment by pq** [comment]
Is the desired goal simply to ensure that the all the `flutter create` contents are in the messages view or also to fix interference from the Analysis View?

**Comment by pq** [comment]
Ok, thanks.  I did some digging and found the race. Working on a fix! 👍
