### ISSUE TITLE
"Create New Flutter Project" the text slightly invade upper text

### ISSUE THREAD

**Issue by jacgyver** [flutter/flutter-intellij#5149]
![image](https://user-images.githubusercontent.com/3636955/102991120-f3d38c00-455b-11eb-97f1-59082fc13875.png)

I don't know if this is an issue.

**Comment by stevemessick** [comment]
@jacgyver Thanks for the report. This is actually a problem with Android Studio. The Flutter plugin just adds an action which AS formats for the dialog. I was going to copy your screen shot and add an issue to the Android Studio bug tracker but decided not to bother. I doubt they will fix it for 4.1.x and the whole New Project Wizard is completely re-written for 4.2. So I'm going to close this.
