### ISSUE TITLE
consider adding a Flutter top-level menu item

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#515]
Perhaps under the `Tools` menu? It could collect some flutter related things, like collecting feedback, pointing to documentation, running flutter doctor, flutter packages get, ...

/cc @pq, @mit-mit

**Comment by pq** [comment]
I actually played with this.  I'll see if I can dig up my stash.

I think the *Tools* menu is the right place. 👍

**Comment by devoncarew** [comment]
Cool - I saw that's where they put the Kotlin stuff:

<img width="304" alt="screen shot 2016-12-09 at 8 26 11 am" src="https://cloud.githubusercontent.com/assets/1269969/21062178/7b33b76c-be04-11e6-8ade-db87e6a0a3ca.png">

**Comment by mit-mit** [comment]
Same for Android stuff in Studio!

**Comment by pq** [comment]
Perfect.  As for actions, we've got:

* doctor
* packages get
* docs
* feedback

What else?

**Comment by devoncarew** [comment]
I'd add `flutter packages upgrade` for symmetry with `get`.
