### ISSUE TITLE
flutter run succeeds but Xcode build from AS 4.1.1 on MacOS 11.1 fails

### ISSUE THREAD

**Issue by dm1090** [flutter/flutter-intellij#5157]
When I run `flutter run` from root of Flutter project, it builds and the app runs on iOS Simulator. From Android Studio 4.1.1 (MacOS 11.1) it fails every time. Error message:

```
Error output from Xcode build:
↳
     ** BUILD FAILED **


Xcode's output:
↳
    ld: unknown option: -target
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

## Steps to Reproduce

Hit **Run** button with iOS Simulator selected as target. It **works** for Android Emulator. Always **fails** for iOS Simulator.

## Version info

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/dm109/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dm109/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! Error: DM’s iPad is not connected. Xcode will continue when DM’s iPad is connected. (code
      -13)
```

**Comment by helin24** [comment]
@dm1090 thanks for the report. We've seen other inconsistencies between the command line and Android studio that seem to be related to environment differences. Does this problem persist when you open Android Studio from the command line as this comment recommends? https://github.com/flutter/flutter/issues/54962#issuecomment-672578610

It's also concerning that the flutter doctor output you posted does not show an iPhone 12 Pro Max in connected devices - is this output from AS or from the command line?

**Comment by dm1090** [comment]
@helin24 Great suggestion to start Android Studio **from command line**. That **worked.**
`open /Applications/Android\ Studio.app`.

The Android 12 is the simulator. I had no physical device attached (iOS and Android) when I ran `flutter doctor`.

**Comment by helin24** [comment]
@dm1090 oh good, I'm glad that worked for you.

It's strange that your simulator wouldn't show up during `flutter doctor`. For example, this is the device portion of my output:
```

**Comment by dm1090** [comment]
@helin24 After I accepted certificates on my iPad, flutter doctor sees them. Thanks for your help.
```
[✓] Connected device (2 available)
    • DM iPad (mobile)           • 00008020-001538211AA2402E            • ios • iOS 14.2
    • iPhone 12 Pro Max (mobile) • A08CA5C7-514F-418E-B808-C6B3024469B4 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
```
