### ISSUE TITLE
Application ID / Bundle ID does not match to the package name entered in the project wizard.

### ISSUE THREAD

**Issue by kunny** [flutter/flutter-intellij#5158]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

1. Select **Create New Flutter Project** from the Android Studio.
2. Select **Flutter Application** as a project type.
3. Enter **flutter_app** as a project name.
4. Enter **com.androidhuman.flutterapp** as a package name.

### Expected Behavior

- Application ID for Android project and Bundle ID for iOS project should be set to **com.androidhuman.flutterapp** (the one that a user entered as a package name)

### Actual Behavior

- Android app ID: **com.androidhuman.flutter_app**
- iOS Bundle ID: **com.androidhuman.flutterApp**

## Version info

- Flutter: `52.1.1`
- Dart: `201.9317`

**Comment by helin24** [comment]
@stevemessick is this naming pattern expected?

**Comment by stevemessick** [comment]
Yes, if the user is using AS 4.1. The Flutter plugin generates the Android package name or iOS bundle ID by combining the organization with the app name. Technically, this example should have been `com.androidhuman.flutterapp.flutter_app` and `com.androidhuman.flutterapp.flutterApp`, which is what is generated using 4.2. The OP's step 4 is incorrect, the package name is not in the UI of the NPW.

**Comment by kunny** [comment]
@stevemessick Hmm that does not make sense to me. I thought that the plugin should respect the package name that I provided in the project creation step. (adding `flutter_app` to Android's app ID and `flutterApp` to iOS bundle ID does not make any sense to me)

For example, if you create a new Android project from Android Studio or Xcode, if you provide an application ID or a bundle identifier during the project creation step, it will become an app ID/bundle ID as-is, without any modification.

Also, is there any reason why the plugin adds those postfix? Also, it's hard to understand why its naming convention is inconsistent between Android and iOS. (snake case vs. camel case)
