### ISSUE TITLE
consider adding a flutter context menu on flutter.yaml files

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#516]
We have some Pub actions on the context menu for pubspec.yaml files. This would be similar, and expose things that acted on the project, like packages get, upgrade, ...

**Comment by pq** [comment]
(Looking at this now.)

**Comment by pq** [comment]
AIs:

* [ ] move actions to butter bar
* [ ] add "Flutter" context menu to `flutter.yaml` files

**Comment by pq** [comment]
Closing in favor of tracking the new file context menu in #537.
