### ISSUE TITLE
Plugin stuck when I try to add new abstract method to abstract class

### ISSUE THREAD

**Issue by mozhaiskyi** [flutter/flutter-intellij#5160]
## Steps to Reproduce

Each time when I try to add new method to existing abstract class plugin stuck. Autocomplete or any other feature of plugin does not work. It start to work properly after IDEA restart only.

## Version info

[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/mmozhaiskyi/Development/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/mmozhaiskyi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

**Comment by helin24** [comment]
@mozhaiskyi thanks for the report. I'm unable to reproduce with the description, but do you have sample code or a mini project you can share that demonstrates this problem? 

You can also enable verbose logging (Preferences -> Languages and Frameworks -> Flutter -> (General) enable verbose logging) and send along your logs (from Help -> show log in finder)
