### ISSUE TITLE
Flutter Inspector windows do not close after the app being debugged is terminated

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#5162]
## Steps to Reproduce
Run a flutter desktop app such as DevTools (probably any app works)
Stop the app from IntelliJ.
The Flutter Inspector tab remains open. Expected behavior would be for the Flutter Inspector tab to close.
## Version info

[✓] Flutter (Channel unknown, 1.26.0-2.0.pre.157, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
    • Flutter version 1.26.0-2.0.pre.157 at /Users/jacobrichman/git/flutter/1/flutter
    • Framework revision 4b83be6c23 (7 days ago), 2020-12-30 02:09:03 -0500
    • Engine revision 0e5a25d779
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jacobrichman/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.0 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A03EE7DE-1E04-435F-A10B-1CB2030A8F24 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS
      11.0.1 20B29 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 87.0.4280.88

! Doctor found issues in 2 categories.

**Comment by jacob314** [comment]
Fyi @helin24

**Comment by helin24** [comment]
We decided to restart the DevTools inspector on window close and reopen instead of closing on app termination
