### ISSUE TITLE
Flutter Inspector font size does not apply correct scale factor on HiDPI displays

### ISSUE THREAD

**Issue by raju-bitter** [flutter/flutter-intellij#5164]
## Steps to Reproduce

Using two displays with Windows 10, main display is 5k (5120x2880) at 200%, secondary display QHD (2560x1440) at 100%. Installed Android Studio 4.1 with Flutter and Dart plugin. Created new Flutter project, launched app on a 5k display.  Flutter Inspector opened with incorrect font size. The font on the 5k display is double of what it is for the QHD display in on screen size, as seen in the screenshots.
This seems to be a Windows specific problem. Running Android Studio 4.1 on Ubuntu 20.04, the Flutter Inspector font scaling works for both 5k and QHD, even when I drag the Android Studio window from one screen to the other.
When the 5k display is running without scaling at 100%, the font and icon sizes for the Flutter Inspector are rendered correctly.

![Flutter-Inspector-on-5k-Display-with-info](https://user-images.githubusercontent.com/296926/104002901-f9f37a80-51a1-11eb-9313-06a0f54aa42b.PNG)

![Flutter-Inspector-on-QHD-Display-with-info](https://user-images.githubusercontent.com/296926/104002909-feb82e80-51a1-11eb-86db-a6f6b0c707e3.PNG)

## Version info
C:\Users\Raju\dev\flutter\stable\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.22.5 at C:\Users\Raju\dev\flutter\stable
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Raju\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

Flutter Plugin version: 52.1.1

**Comment by stevemessick** [comment]
@helin24 This is a JxBrowser issue, right?

**Comment by helin24** [comment]
Hmm.. I'm not sure yet, will check.

**Comment by raju-bitter** [comment]
Just added this info: The problem is caused by the 200% scaling setting for the 5k display. If I don't apply the scaling - running at 100% - the font and icon sizes are corrected. At 400% scaling the text and icon size for the Inspector increases accordingly. 

Switching between different scaling settings messes up the x-axis position of the Flutter Inspector area. Here's what the rendering looks like after going from 200% to 400% and back:
![image](https://user-images.githubusercontent.com/296926/104421413-98eded00-557b-11eb-8a7e-659668ed405d.png)

There is a report on Stackoverflow describing similar problems with JxBrowser in IntelliJ. There the problem was the combination of JDK/JVM used [https://stackoverflow.com/questions/51871468/](https://stackoverflow.com/questions/51871468/jxbrowser-browserview-component-scaled-incorrectly-within-intellij-plugin-on-hid)

**Comment by HubKing** [comment]
I came to report the exact same thing. Windows, 4K monitor, 200% DPI. It looks ridiculously big, as if it is 200% zoomed. Whenever I see this kind of high-DPI bugs in famous applications that is developed by a multi-billion-dollar mega corporations and used by millions of people, I can't help but to wonder there isn't a single developer in that team that uses a 4K monitor. I mean, a 4K monitor isn't even expensive any more.

![Capture](https://user-images.githubusercontent.com/10900489/104474409-540c9980-5601-11eb-926f-e1bd9f08bd33.PNG)

**Comment by raju-bitter** [comment]
Can someone from the Flutter team give me a JxBrowser license key? I want to test if upgrading to JxBrowser 7.12.1 and using the `jxbrowser.force.dpi.awareness` property fixes the problem. But I need a JxBrowser license key to be able to test, based on the [Contributing guide](https://github.com/flutter/flutter-intellij/blob/master/CONTRIBUTING.md).

**Comment by helin24** [comment]
@raju-bitter thanks for the detail! You probably already checked this, but does DevTools opened in your normal Chrome browser have the right scale?

The dpi awareness property sounds promising, and I'll look into this solution. I'm sorry to say that we've decided to keep our license key internal only, so I can't provide that to you to try it out. (You may be able to register for your own trial key on the jxbrowser site)

**Comment by raju-bitter** [comment]
@helin24 Thanks for the quick response. Yes, DevTools run fine in Chrome with Windows scaling applied.

I applied for a JxBrowser evaluation license, and will do some testing tomorrow. You might want to update the Contribution.MD, regarding the JxBrowser license.

**Comment by helin24** [comment]
Okay, thanks for checking. Good point about contributing.md; I'm going to check with jxbrowser also to see if they have an alternative recommendation for this license situation.

**Comment by helin24** [comment]
I'm going to add the DPI awareness flag on our side, but the JxBrowser team has let me know that the underlying setting this affects may or may not work depending on if the bundled JRE has set it before our plugin does.

They also recommend using the JREs officially supported by JxBrowser (Oracle and OpenJDK) when running IntelliJ (although the normally bundled JDK 11 should also work). Article on how to do that: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by djgj57** [comment]
this works for me: https://github.com/flutter/flutter-intellij/issues/5104#issuecomment-764322821
