### ISSUE TITLE
Consider nudging IntelliJ users to Invalidate Caches & Restart when "Installing DevTools" takes too long

### ISSUE THREAD

**Issue by filiph** [flutter/flutter-intellij#5172]
After installing the new version of Android Studio (4.1), I got the dreaded "Installing Devtools" message. (Explained in https://github.com/flutter/flutter-intellij/issues/5032, but basically, the Flutter Inspector pane just shows "Installing DevTools".)

> ![screenshot](https://user-images.githubusercontent.com/13332110/99406498-b3358280-28cc-11eb-884e-00f65fd87cb5.jpg)

This was incredibly frustrating. Not only was I not able to do my work, I didn't know whether it's actually working or not. Whether I should wait a few more minutes or if it's a bug and no amount of waiting will help.

What helped was to run `File > Invalidate Caches & Restart`, as proposed by https://github.com/flutter/flutter-intellij/issues/5032#issuecomment-724919401. (This worked for me in the past, too, for an unrelated issue.)

I think the string should be something like:

> Installing DevTools...
>
> (If this takes more than a few seconds, please run File > Invalidate Caches & Restart.)

**Comment by helin24** [comment]
We decided that invalidating caches is unlikely to make a difference for this problem, so we're instead going to trigger a DevTools restart on reopening this tool window (see https://github.com/flutter/flutter-intellij/issues/5162)
