### ISSUE TITLE
Dart Run Configations not working when double quotes are present

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#5174]
Already [opened here](https://youtrack.jetbrains.com/issue/WEB-48644?replyTo=27-4629487), copied bellow:

I am trying to make a Run Configuration like this:

```
flutter run --dart-define=EXAMPLE_APP_NAME="My App" --dart-define=EXAMPLE_APP_SUFFIX=.dev
```

This command works fine.

It will look like this:

![image](https://user-images.githubusercontent.com/8120472/104456555-9b564400-5587-11eb-9bba-1eaab9f447d8.png)

But the double quotes are being ignored and the terminal interprets `My` as a command, so I get this error:

![image](https://user-images.githubusercontent.com/8120472/104456588-a8733300-5587-11eb-8684-90384b7467e5.png)

I tried to escape it with `\"`, `""` and `^"` but none worked

**Comment by stevemessick** [comment]
This is a dup of #4588. You might want to upvote that one.
