### ISSUE TITLE
Can't use extension methods in Evaluation

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter-intellij#5178]
## Steps to Reproduce
Create a project and add an extension method.
Put a breakpoint somewhere in the project and when the debugger pauses, attempt to call the extension method.
Get the error that the class you're calling the method on has no method named _X_

## Version info

[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/thinkdigital/development/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM N975U (mobile) • R38M906TG0Z • android-arm64 • Android 10 (API 29)
    ! Error: Think Digital’s iPhone is not connected. Xcode will continue when Think Digital’s iPhone is connected. (code -13)

! Doctor found issues in 1 category.
<img width="1011" alt="Screen Shot 2021-01-15 at 12 25 54 PM" src="https://user-images.githubusercontent.com/23037821/104775340-08efa500-572d-11eb-9d33-d06728ef4124.png">

**Comment by stevemessick** [comment]
@jacob314 I believe this is an issue in the Flutter SDK, VM service implementation. Can you confirm?

**Comment by stevemessick** [comment]
@devoncarew Can you confirm?

**Comment by devoncarew** [comment]
This is almost certainly a limitation of the VM's eval implementation. It likely needs to take into account the extensions brought in by the imports for the current file.

@ThinkDigitalSoftware - can you include the source code for a minimal example?

**Comment by devoncarew** [comment]
We'll need to move this issue to the dart-lang/sdk repo -

**Comment by ThinkDigitalSoftware** [comment]
I mean. I could throw together a main.dart with an extension method in it
