### ISSUE TITLE
Issue evaluating multiline expressions for Flutter projects

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter-intellij#5179]
This was suggested to be filed here from https://youtrack.jetbrains.com/issue/WEB-47340
## Steps to Reproduce

Write code like the following. Any "evaluatable" expression will do. And it does seem to be the fact that it's a single line. I've attached 2 examples.
:
```dart

[1, 2, 3].where((a){return a <=2;}).toList() // evaluates.

dart
[1, 2, 3].where((a) {
  return a <=2;
}).toList()
```
**What is the expected result?**
The same evaluation if the code had new lines removed

**What happens instead?**
If you highlight and evaluate it or use alt/option-click it for inline evaluation, you get an error. When this same expression has the new lines removed, it evaluates fine.
E.g. `[1, 2, 3].where((a){return a <=2;}).toList() `

Note: This doesn't happen on dart command line applications, just Flutter
## Version info
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/thinkdigital/development/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM N975U (mobile) • R38M906TG0Z • android-arm64 • Android 10 (API 29)
    ! Error: Think Digital’s iPhone is not connected. Xcode will continue when Think Digital’s iPhone is connected. (code -13)

! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
I didn't reproduce this exactly but I think I know how to fix it. My result for the multi-line expression was a `WhereIterable`, not an error. But if I hack the code to convert newlines to spaces it works correctly. This is actually a bug in the Flutter SDK (VM service implementation) but I can fix it in the plugin.

cc @jacob314 for confirmation.

**Comment by ThinkDigitalSoftware** [comment]
Thanks for your hard work, @stevemessick!
