### ISSUE TITLE
WEB DEVICE NOT SHOWING

### ISSUE THREAD

**Issue by jmpavan** [flutter/flutter-intellij#5182]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

I cannot compile for the web as the device is not displayed.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [VersiÃ³n 10.0.19041.746],
    locale es-AR)
    • Flutter version 1.25.0-8.2.pre at C:\flutter
    • Framework revision b0a2299859 (12 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Jorge\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Users\Jorge\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API
      29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome
      87.0.4280.141
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge
      87.0.664.75

• No issues found!

**Comment by stevemessick** [comment]
It sounds like you did not tell Flutter you wanted to use the web platform when you created the project. A UI for selecting platforms has been added to Android Studio 4.2 and later but is not available for 4.1 (your version). To create a project using platforms other than iOS and Android you need to use the beta version of Android Studio or do it on the command line.

**Comment by jmpavan** [comment]
Steve: I was able to compile via command line, but I still can't see the web device using "flutter devices".
I have Android Studio 4.2 Beta 3, but I don't know where to find the option you mention. Could you tell me please?.

Thank you.

**Comment by stevemessick** [comment]
Perhaps it has not been enabled? Do this on the command line:
`flutter config --enable-web`
and see if `flutter devices` shows it.

And, to answer your question, platform selection is done at project creation. In the new project wizard you can select platforms (if they have been enabled) on the second page of the wizard. We want to add a UI for adding additional platforms to an existing project but have not implemented it yet. You can, however, add platforms using the command line. See the Flutter docs for details. Or check the command line help by `flutter help create`.

**Comment by jmpavan** [comment]
It's the first thing I did but it only shows:
Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
Edge (web) • edge • web-javascript • Microsoft Edge 87.0.664.75
In previous versions of flutter it did show the web device.

Jorge Mario Paván
+54 9 11 5327 9247
jorge.pavan@pavanconsultores.com.ar

[pavan.jpg]

Sobre 20/01/2021 12:46:50, stevemessick <notifications@github.com> escribió:
Perhaps it has not been enabled? Do this on the command line:
flutter config --enable-web
and see if flutter devices shows it.
And, to answer your question, platform selection is done at project creation. In the new project wizard you can select platforms (if they have been enabled) on the second page of the wizard. We want to add a UI for adding additional platforms to an existing project but have not implemented it yet. You can, however, add platforms using the command line. See the Flutter docs for details. Or check the command line help by flutter help create.

**Comment by devoncarew** [comment]
```
Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
Edge (web) • edge • web-javascript • Microsoft Edge 87.0.664.75
```

The above looks correct. There was a change to not list the web-server device. That is generally only used for special cases and was confusing for most users wrt when should they choose web chrome vs web server. It's still available for those special cases, you just have to pass the device id explictly (when running from the command line).

**Comment by jmpavan** [comment]
Thank you.

Jorge Mario Paván
+54 9 11 5327 9247
jorge.pavan@pavanconsultores.com.ar

[pavan.jpg]

Sobre 22/01/2021 16:00:33, Devon Carew <notifications@github.com> escribió:
Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141 Edge (web) • edge • web-javascript • Microsoft Edge 87.0.664.75
The above looks correct. There was a change to not list the web-server device. That is generally only used for special cases and was confusing for most users wrt when should they choose web chrome vs web server. It's still available for those special cases, you just have to pass the device id explictly (when running from the command line).
