### ISSUE TITLE
I faceing a problem in flutter at android studio that is the" android emulator or physical device both or not connected its shows error or notification" it shows "no device connected please check" but "i already install android emulator" but "why flutter is not connected the devices to run the program" please help me and solve my problem

### ISSUE THREAD

**Issue by anjan816** [flutter/flutter-intellij#5185]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
I think this is a dup of #1525
