### ISSUE TITLE
Missing x86_64 ABIs when building from Android Studio 

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter-intellij#5196]
Copied from https://github.com/flutter/flutter/issues/66885.

This seems to be a request for documentation, but is there a bug here?  Why is this different from `flutter build apk --release`?

@darek607 said:
******************
According to the [official guide](https://flutter.dev/docs/deployment/android) (_How do I build a release from within Android Studio?_), we can also build release apk from within Android Studio.  However, these builds (I tested release builds) are missing x86_64 so files as opposed to `flutter build apk --release` which generates ABIs correctly for all 3 architectures.

## Steps to Reproduce
1. Create a sample Flutter application with Android Studio (File -> New -> new Flutter Project -> Flutter Application)
2. Open the "android" folder for editing in Android Studio (I'm using Tools -> Flutter -> Open for Editing in Android Studio option).
3. Build a release APK either by "Generate Signed Bundle / APK" **or** by choosing the release build variant and Build -> Make project **or** by executing `assembleRelease` task.

**Expected results:** 
I expect the generated apk contains all 3 supported ABIs: `arm64-v8a`,` armeabi-v7a,` `x86_64` because these architectures are default according to Flutter docs.

**Actual results:**
The resulting APK file does not contain `x86_64` ABIs. I tested it by unzipping the APK.

<details>
  <summary>Logs</summary>

- flutter analyze (no issues)

- flutter doctor -v

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale pl-PL)
    • Flutter version 1.20.4 at /Users/darek/flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/darek/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

</details>

**Comment by stevemessick** [comment]
After doing this you are no longer using the Flutter plugin
> Open the "android" folder for editing in Android Studio

We can't help with Android Studio issues.

**Comment by jmagman** [comment]
Thanks for the clarification @stevemessick!
