### ISSUE TITLE
IntelliJ/AS "Do Refactor" results in absolute path imports instead of package imports

### ISSUE THREAD

**Issue by ScottS2017** [flutter/flutter-intellij#5200]
## Steps to Reproduce

Ensure your dart file depends on files that are in various directories in the app

Drag and drop your file into a different directory

If the IDE responds with a popup in the center of your screen that says "Move", escape out of that. That's not the issue.

You want the IDE to open a "Refactoring Preview" section in the Find tab of the editor, usually in the lower left of the IDE. It should offer two buttons, "Do Refactor" and Cancel.

When you click Do Refactor, the IDE/Plugin will reconstruct your imports, but it will use absolute paths from your drive letter instead of package imports that are reference from your project root. This can cause many issues that have been known for some time but are outside the scope of this issue.

## Version info

[√] Flutter (Channel dev, 1.26.0-8.0.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-8.0.pre at C:\SDKs\flutter
    • Framework revision b9d06fffb2 (2 weeks ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\scott\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\scott\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.1
    • Flutter plugin installed
    • Dart plugin version 203.6912

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 87.0.664.75

**Comment by stevemessick** [comment]
@alexander-doroshko @jwren Is this issue related to the Dart plugin or the analysis server?

**Comment by alexander-doroshko** [comment]
@ScottS2017 I'm afraid we need a sample project + steps to reproduce the issue. I think it's enough to have just 2 files, one imports another, and then one of them is moved.

I tried with the following example. Two files located in `lib` folder. One imports another. Then I move one of the files to `lib/src/`. Import is updated correctly to me, regardless of the file that I move.

@stevemessick IDE uses Analysis Server to update imports. But there might be corner cases. With a simple experiment described above, I couldn't reproduce the issue.
