### ISSUE TITLE
Cannot search for any classes in the flutter package

### ISSUE THREAD

**Issue by boyan01** [flutter/flutter-intellij#5206]
As shown in the figure, enter the `StatefulWidget` keyword, but no class can be found...

I don't know if this feature has been removed deliberately, but it is really annoying.

![image](https://user-images.githubusercontent.com/17426470/105712209-7503b180-5f54-11eb-86d0-d67b16f0382c.png)

## Steps to Reproduce

1. open a flutter project with IDEA
2. wait it indexing done.
3. press `Ctrl + N` open search tool box, input  `StatefulWidget`.

## Version info

```
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.26.0-8.0.pre at /home/boyan/dev/flutter
    • Framework revision b9d06fffb2 (2 周前), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /home/boyan/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at
      /home/boyan/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.6682.168
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 2 categories.
```

**Comment by stevemessick** [comment]
I cannot reproduce this problem.

<img width="571" alt="Screen Shot 2021-01-25 at 8 14 11 AM" src="https://user-images.githubusercontent.com/8518285/105732527-6631e600-5ee5-11eb-8914-1f4af48723b9.png">

I do not recall exactly how this is implemented, but it might be using the IntelliJ index. If so, then `File > Invalidate Caches / Restart` might solve the problem. Select `Invalidate and Restart` from the dialog. Please let us know if that solves your problem.

**Comment by boyan01** [comment]
I just reproduce.

1. create a flutter plugin: `flutter create -t plugin my_plugin`
2. `cd my_plugin/`
3. create web platform sources: `flutter create -t plugin --platforms=web .`
4. open this project with idea. such: `idea .`

then we can not search any flutter class anymore...

![image](https://user-images.githubusercontent.com/17426470/105736095-65de2d00-5f6f-11eb-85ca-99ea4a6c1e07.png)

**Comment by stevemessick** [comment]
Thanks for the detailed repro instructions.

When you do `flutter create -t plugin --platforms=web .` it prints:
> You need to update ./pubspec.yaml to support web.

It even includes a URL with instructions on how to edit the file. Unfortunately, the instructions are not very clear. The file at the URL contains this line
> If this command displays a message about updating the pubspec.yaml file, follow the provided instructions.

Since the provided instructions are a link to the file, it is circular and not helpful.

I've attached the correct yaml file. Once you've edited the file you need to do `flutter pub get` and restart the analysis server in the IDE. Or just use button at the top of the yaml file editor labeled `Pub Get`.
[pubspec.yaml.zip](https://github.com/flutter/flutter-intellij/files/5868225/pubspec.yaml.zip)
