### ISSUE TITLE
 Android Studio is ignoring `Editor`->`Code Style`->`Hard wrap at` option when reformat code

### ISSUE THREAD

**Issue by sla-000** [flutter/flutter-intellij#5216]
## Steps to Reproduce

When I'm trying to Reformat code with context menu and select `Reformat code` or `Reformat code with dartfmt` text is formatted totally ignoring `Hard wrap at` option in `Code Style`. It is true for both cases when EditorConfig support is enabled or not.

Also line wrap setting is ignored when I set `Format code on save` option on Flutter settings page and then save changed file.  

Expected behavior is to call `flutter format $FILE -l 120` for example, when 'Hard wrap at' in 'Code Style'  is set to 120

## Version info

I don't know why flutter doctor don't know about Android Studio Dart and Flutter plugins version, but believe in Studio all needed is installed and working fine:
Flutter plugin version is: 52.2.1
Dart plugin version is: 201.9317

flutter doctor output:

[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.26.0-12.0.pre at /Users/Shared/google/flutter/flutter-dev
    • Framework revision a706cd2112 (13 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/Shared/android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/Shared/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

**Comment by stevemessick** [comment]
Formatting is done by the Dart plugin. You can create an issue at youtrack.jetbrains.com if you like. However, the Dart style guide fixes line width at 80, which is what dartfmt uses.

**Comment by masus04** [comment]
The line width can now be set unser `Settings` -> `Code Style` -> `Dart` -> `Line Width`, but the global setting is still ignored.
