### ISSUE TITLE
"Flutter attach" do not work with build flavor

### ISSUE THREAD

**Issue by imReker** [flutter/flutter-intellij#5217]
## Steps to Reproduce
1. Run app.
2. Click "Flutter attach" button.
3. Stop app.
4. Set a valid "Build flavor" in "Run/Debug Configurations" window, eg, "MyFlavor".
5. Run app.
6. Click "Flutter attach" button.
7. Open "Run/Debug Configurations" window, check the configurations and close the window.
8. Click "Flutter attach" button.
9. Open "Run/Debug Configurations" window.

After Step 2, debugger attached to app successfully.

After Step 6, attach failed and Debug Console print: "Could not find an option named "flavor".

After Setp 7, "Additional arguments" became from empty to "--flavor=MyFlavor".

After Setp 9, "Additional arguments" became to "--flavor=MyFlavor --flavor=MyFlavor".

**Related:** #4521 

![screenshot](https://user-images.githubusercontent.com/4949937/105997608-c643aa80-60e6-11eb-9f0c-eb6f8c245ae3.png)

## Version info
Flutter: 1.26.0-2.0.pre.137 • channel master •
Flutter plugin: 52.2.1 in Intellij Marketplace.

**Comment by stevemessick** [comment]
`flutter attach` does not have a `--flavor` option.
