### ISSUE TITLE
Flutter autocomplete stops working after launching Android emulator

### ISSUE THREAD

**Issue by SarunasDaubaris** [flutter/flutter-intellij#5220]
I ran into a problem where Android Studio/IntelliJ Flutter/Dart autocomplete and imports suggestion stops working. Once AS is restarted the problem disappears.

Description and steps to reproduces are given below.

**Steps to reproduce**
 1. Open existing Flutter project in Android Studio;
 2. Create a new variable;
 3. Click Alt+Enter to import the variable's class;
 4. The Dart package is imported;
 5. Launch Android emulator
 6. Create another variable;
 7. Click Alt+Enter to import the variable's class;
 *Expected*: class is imported
 *Actual*: No import suggestions are given. When writing the class name, no autocomplete

**Software versions**
Windows 10 Pro x64
Android Studio 4.1.2
Android Emulator 30.3.5 version

**Flutter doctor**
Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale lt-LT)

**System**
Dell Precision 7540

I tried googling for this but haven't found similar questions. I guess this is related to what ports are used by the Dart analysis server and the Android emulator. Restarting AS 20 times per day doesn't seem like an efficient solution.

**Comment by stevemessick** [comment]
I cannot reproduce this problem. Please give more detailed reproduction steps, including class names and emulator choice. Are the classes standard with Flutter or custom for you project? A sample project that illustrates the problem would be great. Also include the output of `flutter doctor -v`. Thanks!

**Comment by SarunasDaubaris** [comment]
Output of `flutter doctor -v`

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale lt-LT)
    • Flutter version 1.22.6 at C:\Development\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\sdaubaris\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Development\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Development\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)
```

It happens with any Flutter class or my class.
Try a new dart file, create a widget that extends StatelessWidget from material package. Try importing the material package and there isn't such suggestion when pressing Alt+Enter.

I think there occurs a conflict between Dart analysis server and the Android emulator.

**Comment by hazem-ibtikar** [comment]
I think this happens when creating the app from Mac machine and then developing it on windows.

**Comment by SarunasDaubaris** [comment]
> I think this happens when creating the app from Mac machine and then developing it on windows.

No. It's being developed on Windows.

**Comment by stevemessick** [comment]
@SarunasDaubaris this is a puzzling problem. Can you give us a sample project that demonstrates the issue? Especially including class names in comments so we can do exactly what you do. We can see if our Windows environment can reproduce the problem.

**Comment by rorystephenson** [comment]
FWIW I have the same issue running on Mac.

**Comment by SarunasDaubaris** [comment]
Hi. Sorry for the slow reply. I can't upload the production project that I'm working on because it belongs to my employer.
But I tried creating a new Flutter project and I didn't encounter the problem with that new project.

I'm attaching the sample project.

I guess the problem is related to some IntelliJ-specific files. Maybe some file is missing/old project configuration conflicting with newer IntelliJ Flutter plugin version/etc. Should I look for any specific files and try to delete them so new ones are generated? (Btw, I tried multiple times restart IntelliJ and clean cache).

Flutter doctor ouput:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.867], locale lt-LT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by helin24** [comment]
@SarunasDaubaris this could be due to your production project having been generated from an older template. If you'd like to recreate this project from a new template, follow these steps:
1. Back up the project or make sure it's in version control so you can recover in its current state
2. Open terminal and cd into your project
3. Run `flutter create .` - this should recreate your project

Let us know if this works for the autocomplete problem.
