### ISSUE TITLE
Could not find an option named "devtools-server-address". when trying to run flutter app from AndroidStudio

### ISSUE THREAD

**Issue by cope2012** [flutter/flutter-intellij#5229]
I just updated Flutter plugin to 53.0.1, restarted Android Studio and hit "run" button and the error below show up:

Could not find an option named "devtools-server-address".

## 53.0.1
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.307, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by Endeline** [comment]
@cope2012 This so simple... Open terminal type `flutter channel dev` this solve your problem

**Comment by anindyadesi** [comment]
> @cope2012 This so simple... Open terminal type `flutter channel dev` this solve your problem

I have the same issue after upgrade flutter plugin through android studio, it's still not working. Anybody solved this issue please?

**Comment by chacham** [comment]
In my case, the problem solved by running `flutter upgrade`
I'm using master channel now.

**Comment by MariiaS** [comment]
> In my case, the problem solved by running `flutter upgrade`
> I'm using master channel now.

`flutter upgrade` worked for me too, thank you!

**Comment by anindyadesi** [comment]
I don't understand what happen, this only occurs when I run through button run in Android Studio. Everything is good when I run through terminal 'flutter run'.

**Comment by mshanak** [comment]
> > In my case, the problem solved by running `flutter upgrade`
> > I'm using master channel now.
> 
> `flutter upgrade` worked for me too, thank you!

Worked for me too

**Comment by jagritjkh** [comment]
Changed from master to stable channel, now I am having the same issue!
flutter upgrade also not solving this issue for me.

**Comment by devoncarew** [comment]
@helin24 - is the code which passes in the `--devtools-server-address` guarded by a Flutter SDK version check?

**Comment by helin24** [comment]
There is a version check against `1.26.0-11.0.pre`, but we assume that 1.26.0 versions on master are more recent than this point. There were some complications about comparing master to dev versions due to branching, so essentially our gating check assumes that users on master are rebasing frequently - this will be changing soon though, so I think I'll update so that master compares more precisely before our next release.

@cope2012 you can either change to another flutter channel, or update your master to the latest version.

**Comment by cope2012** [comment]
> @cope2012 This so simple... Open terminal type `flutter channel dev` this solve your problem

thanks, that solved my problem!. sorry for not answering sooner.

**Comment by omidraha** [comment]
Same issue here.

Fixed by:
```bash 
$ flutter upgrade
$ flutter clean
$ flutter pub get
$ flutter run
```
Info:
```bash
Flutter is already up to date on channel master
Flutter 1.26.0-18.0.pre.128 • channel master • https://github.com/flutter/flutter.git
Framework • revision 502ff3dbfe (6 hours ago) • 2021-02-02 05:41:03 -0500
Engine • revision 7334085fc1
Tools • Dart 2.12.0 (build 2.12.0-281.0.dev)
```
But now I have a lot of errors for installed packages. ([nullOK](https://github.com/dnfield/flutter_svg/issues/479), ...)

**Comment by Mereep** [comment]
Had the same problem, which presumably happened due to switching to `dev` channel back to `stable`. However, `flutter upgrade` and restarting Android Studio afterwards did the trick for me..

**Comment by mrflowwww** [comment]
Hm? This can't be true. Since 7 days no answer? We try to get our release running and got stucked by this issue. How can we support, to get this issue closed? What can we do? Thx a lot for help.

**Comment by helin24** [comment]
@mrflowwww I recommend either pulling from flutter master or switching to another flutter channel (dev or stable).

**Comment by thepelican** [comment]
happens when switching back to stable channel.

flutter clean
invalidate and restart AD cache (from File/..)

**Comment by cwxorochi** [comment]
For those who are configured at VSC, after complete the steps provided by @omidraha , do restart your vsc program to see the changes up

**Comment by helin24** [comment]
This should be fixed for the next release with https://github.com/flutter/flutter-intellij/pull/5254

Until the next release comes out, pull from flutter master or switch to another flutter channel (dev, beta, or stable) if you're having this problem.

**Comment by lewcianci** [comment]
@helin24 Are you really telling people to switch to a pre-release channel to work around this issue? Switching channels to non-stable versions of Flutter is a bad idea. So many people are like 'ah I switched to the master channel and it solved it!' without realising they are switching to the alpha version of Flutter.

You can switch to a pre-release channel if you have no interest in releasing an app to the stores. Otherwise, it's a bad idea.

**Comment by helin24** [comment]
@lewcianci For people who are intending to use the master channel, this problem will be fixed if they pull the latest changes. (This problem only occurred for people using flutter on the master channel within a narrow window of commits.)

To be clear, we recommend using the more stable versions of Flutter unless there's a specific reason to use master.

**Comment by YatsenkoDev** [comment]
Looks like this is somehow related to Flutter plugin in the IDE.
Try to relaunch your IDE, if didn't help reinstall flutter plugin.

**Comment by helin24** [comment]
@YatsenkoDev this should only happen if you're on the flutter master channel (but not recently updated) with the plugin v53. If you're having this problem, either change to another flutter channel or update your master to latest.

**Comment by jjosenaldo** [comment]
I am in VSCode, but the exact same message popped up on the editor. I have two projects using different Flutter versions. This error appeared when I was in 1.22.6, upgraded to 2.0 and then came back to 1.22.6 (always in the stable channel). Similarly to @jagritjkh suggested, I reinstalled the Flutter plugin for VScode and everything worked.

**Comment by zyllus17** [comment]
I downgraded from `Flutter 2.0` to `Flutter 1.22.5` and got this error.
To solve it,
 Go to your terminal and write `flutter channel stable`.
Then run `flutter doctor`.
Now you may get another error like this - 
![image](https://user-images.githubusercontent.com/50977126/111028509-17042e00-841d-11eb-9492-fb119e0f6db1.png)
If you have Flutter & Dart plugins already install, just ignore this error. This is a bug in `Flutter 1.22.5` .
Just run the app and it will work fine!

**Comment by va-living-moosebrook** [comment]
I also had to downgrade from flutter 2 to 1.22.5 as well and @zyllus17 's recommendation worked but I had to restart Intellij as the error persisted until I did that.

**Comment by eslamwael74** [comment]
Just disable and enable the Flutter plugin from your plugins in Android Studio

**Comment by huynguyennovem** [comment]
> Just disable and enable the Flutter plugin from your plugins in Android Studio

LOL. I need to read all comments before seen this. I did @jagritjkh solution (-_-)

**Comment by mithunmqb** [comment]
Strated getting this after downgrading to Flutter 1.22.6 from Flutter 2.x.x. 
Restarting Android Studio fixed it without any other changes

**Comment by BahiElfeky** [comment]
Invalidate Caches / Restart solved the problem.

**Comment by dinethsiriwardana** [comment]
Open project with Android Studio (If you use VScode) and run the app
