### ISSUE TITLE
Not working with Grep Console

### ISSUE THREAD

**Issue by nerder** [flutter/flutter-intellij#5238]
It seems to be related to this issue:

https://github.com/krasa/GrepConsole/issues/180

**Comment by helin24** [comment]
@nerder what theme are you using in Preferences > Appearance & Behavior > Appearance > Theme?

**Comment by nerder** [comment]
The default: Darcula

**Comment by helin24** [comment]
@nerder thanks, so this is happening with all themes? Is this something particular to the combination of the Flutter plugin and the grep console plugin, i.e. does this only happen with the grep console when using the Flutter plugin too? (I'm not able to produce with only the Flutter plugin)

**Comment by nerder** [comment]
Sorry for the late reply @helin24 if you see in the https://github.com/krasa/GrepConsole/issues/180 issue they put it as a wontfix since this seems to be an issue your side. 

Are you able to reproduce the issue?

**Comment by stevemessick** [comment]
Dup of #5030
