### ISSUE TITLE
Flutter hot reload

### ISSUE THREAD

**Issue by TechHelper** [flutter/flutter-intellij#5241]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

While developing flutter apps when we hot reload it works 1st time with infinite hot reload process going on (Means buttons disabled). Hence can not hot reload 2nd time and need to restart app.

## Version info

flutter doctor output:
[✓] Flutter (Channel master, 1.26.0-13.0.pre.142, on macOS 11.1 20C69 darwin-arm, locale en-IN)
    • Flutter version 1.26.0-13.0.pre.142 at /Users/mayurchandrakantaouti/Development/Tools/flutter
    • Framework revision c87f15fe09 (10 days ago), 2021-01-23 23:11:15 -0800
    • Engine revision fdddf87080
    • Dart version 2.12.0 (build 2.12.0-253.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mayurchandrakantaouti/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mayurchandrakantaouti/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • ONEPLUS A6000 (mobile) • 192.168.1.2:5555 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

**Comment by helin24** [comment]
@TechHelper thanks for the report. A few things:
- Can you provide your Flutter plugin version from Preferences > Plugins?
- A video of your running app and trying to hot reload could be helpful
- Is there any error output in your console? And if not, you could try sending us your logs from Help > Show log in finder > idea.log after reproducing this problem.

**Comment by TechHelper** [comment]
- Flutter plugin: 53.0.1
- Sorry, can not send video but hot reload was working in VSCode throughout app. In Android Studio it's not working on any screen.
- idea.log file attached
[idea.log](https://github.com/flutter/flutter-intellij/files/5925598/idea.log)

**Comment by katerinka77** [comment]
I faced the same issue both on Android Studio, and on VS Code IDE, with the same Flutter plugin (version: 53.0.1)

flutter doctor output:
[✓] Flutter (Channel unknown, 1.26.0-12.0.pre, on Mac OS X 10.13.6 17G14042 darwin-x64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.0)
[✓] Connected device (2 available)

No errors in console. I will appreciate any help.


Thanks!

**Comment by helin24** [comment]
@katerinka77 are you also having problems with hot reload when you run your application on the command line? 

@TechHelper I don't see anything suspicious in your logs and I'm unable to reproduce on my system. I wonder if you can reproduce the problem with a small app, e.g. if you use the flutter demo project? (https://flutter.dev/docs/get-started/test-drive)

**Comment by TechHelper** [comment]
@helin24 Not able to reproduce in sample flutter app. But I tried hot reload using command line and I got this output when hot reload failed.
**Ignoring terminal input: "r" because we are busy.*

I am also attaching some log files generated to help you fix issues.
[flutter_02.log](https://github.com/flutter/flutter-intellij/files/5949001/flutter_02.log)
[flutter_03.log](https://github.com/flutter/flutter-intellij/files/5949002/flutter_03.log)

Please let me know if you need anything else.
