### ISSUE TITLE
Flutter Doctor not detecting Plug in

### ISSUE THREAD

**Issue by m1narul** [flutter/flutter-intellij#5242]
Android Studio Dev Status: Won't Fix (Infeasible)
Flutter Doctor not detecting X Flutter plugin not installed; this adds Flutter specific functionality. X Dart plugin not installed; this adds Dart specific functionality.

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-US) • Flutter version 1.22.6 at D:\Dev\flutter • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800 • Engine revision 2f0af37152 • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) • Android SDK at C:\Users\I0435\AppData\Local\Android\sdk • Platform android-30, build-tools 30.0.3 • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01) • All Android licenses accepted.

[!] Android Studio (version 4.1.0) • Android Studio at C:\Program Files\Android\Android Studio X Flutter plugin not installed; this adds Flutter specific functionality. X Dart plugin not installed; this adds Dart specific functionality. • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1) • VS Code at C:\Users\I0435\AppData\Local\Programs\Microsoft VS Code • Flutter extension version 3.16.0

[√] Connected device (1 available) • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

Build: AI-201.8743.12.41.7042882, 202012200039,

AI-201.8743.12.41.7042882, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768

AS: 4.1.2; Kotlin plugin: 1.4.21-release-Studio4.1-1; Android Gradle Plugin: (plugin information not found); Gradle: (gradle version information not found); NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: 3.10.2, from PATH: (not found)

IMPORTANT: Please read https://developer.android.com/studio/report-bugs.html carefully and supply all required information.

Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment]
Thanks for the report! As of the next stable version of flutter, flutter doctor will no longer check for specific plugin versions.
