### ISSUE TITLE
Since version 53.0.5 it won't show the available emulators unless I start them

### ISSUE THREAD

**Issue by lsalazarm99** [flutter/flutter-intellij#5244]
It was working well in 52.2.5. I could even downgrade the plugin to that version and it worked again. But in 53.0.5 it is not showing the available emulators.

![image](https://user-images.githubusercontent.com/42286051/106905830-925e1b80-66ca-11eb-8ee4-871300829901.png)

I have them correctly created:

![image](https://user-images.githubusercontent.com/42286051/106905913-a6a21880-66ca-11eb-8c5b-837e1afacb9c.png)

It only detects them when I start them.

It's not a big issue, but it is there.

## Version info

```
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale es-PE)
    • Flutter version 1.25.0-8.3.pre at C:\tools\flutter
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\leozx\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\leozx\.jdks\openjdk-15.0.1\bin\java
    • Java version OpenJDK Runtime Environment (build 15.0.1+9-18)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\leozx\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57
    • Flutter plugin version 53.0.5
    • Dart plugin version 203.6912

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by helin24** [comment]
@lsalazarm99 thanks for the report. Can you post a screenshot of what this looks like for the previous version? On windows I also see "nothing here" for version 52.

**Comment by lsalazarm99** [comment]
Sure. This is what it looks like.

![image](https://user-images.githubusercontent.com/42286051/107651155-30169500-6c4d-11eb-965b-25268b8fa05a.png)
