### ISSUE TITLE
Device not listed 

### ISSUE THREAD

**Issue by arttobe** [flutter/flutter-intellij#5248]
Hello Everyone,

my device is not list in menu, but when i use the cli I can use it.

Fedora 33 64Bit

![Screenshot from 2021-02-06 15-36-29](https://user-images.githubusercontent.com/38989619/107121197-6ccf3e80-6891-11eb-816f-a73332f3dcf8.png)
![Screenshot from 2021-02-06 15-35-52](https://user-images.githubusercontent.com/38989619/107121199-6e006b80-6891-11eb-8d59-dfc597bc7e21.png)

## Version info

[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-8.3.pre at /home/moritz/dev/flutter
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/moritz/dev/android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/moritz/dev/android
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /opt/idea-IU-203.6682.168
    • Flutter plugin version 53.0.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM G770F (mobile) • RF8N21RBH9K • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 87.0.4280.141

• No issues found!

**Comment by helin24** [comment]
@arttobe thanks for the report. Potentially the daemon searching for devices is having a problem. Can you enable verbose logging (Settings > Languages & Frameworks > Flutter > General) and send us your logs after this happens? (Logs can be found by going to Help > show log in explorer > idea.log).

**Comment by arttobe** [comment]
What do you need exactly from the log ? Or can I send you the whole?

**Comment by arttobe** [comment]
ff

**Comment by helin24** [comment]
@arttobe yes, go ahead and attach your entire log. Make sure verbose logging is turned on first. Thanks!

**Comment by arttobe** [comment]
[idea.log](https://github.com/flutter/flutter-intellij/files/6027533/idea.log)
Here is my log file

Thank you for your help

**Comment by helin24** [comment]
I don't see any errors, but it is odd that only Chrome was returned from the daemon. 

Here's something else you can try:
1. On the command line, run `flutter daemon`. This should print out something like:
```
[{"event":"daemon.connected","params":{"version":"0.6.0","pid":60943}}]
[{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
```
and the process will wait for input
2. Type `[{"id":1,"method":"device.enable"}]` After a bit, you should see lines like:
```
[{"id":1}]
[{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null}}]
[{"event":"device.added","params":{"id":"287E1F39-AE03-44BD-ACDB-7F668B1E32EA","name":"iPhone SE (2nd generation)","platform":"ios","emulator":true,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":"apple_ios_simulator"}}]
```

From your logs, only Chrome was returned as a device, but I wonder if you get a different result in your terminal. If you continue to get only Chrome in your terminal, then I think there may be an issue in flutter that causes `flutter devices` to return different results than `flutter daemon`.

Another thing you could try is adding an Android emulator (I think you have a real device connected?) and seeing if this shows up in IntelliJ.

**Comment by arttobe** [comment]
At the moment flutter runs just fine over the command line on my android phone (galaxy s10 lite android 11)

Tomorrow I can add an Simulator and send you the results. do you has any other ideas?

**Comment by arttobe** [comment]
I get my phone over the commandline 
Like in the picture at top oft this issue

**Comment by helin24** [comment]
@arttobe so to be clear, I know you were already getting multiple devices using `flutter devices`, but I want to check that you can also get multiple devices using `flutter daemon` as I described above.

**Comment by arttobe** [comment]
Ah sorry I had a long day I will check it tomorrow. Thank you for your help

**Comment by arttobe** [comment]
This is my output from flutter deamon an it looks like that my Phone is there

[{"event":"daemon.connected","params":{"version":"0.6.0","pid":326520}}]
[{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[{"id":1,"method":"device.enable"}]
[{"id":1}]
[{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null}}]
[{"event":"device.added","params":{"id":"RF8N21RBH9K","name":"SM G770F","platform":"android-arm64","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]

**Comment by arttobe** [comment]
I have also added a Emulator, but it also not works.

**Comment by helin24** [comment]
@arttobe really strange! I'm not sure what could cause this discrepancy between calling `flutter daemon` on the command line and within the plugin. It looks like from your IDE logs that the same command is being used. Sorry this is not apparent.

One more thing you could try is disabling web by calling on command line: `flutter config --no-enable-web` (you can later reverse this with `flutter config --enable-web`. This should remove Chrome from your list of devices (e.g. if you try `flutter devices`). Then you can restart your IDE and get logs the same way as before. I'm suggesting this in case there's a problem with the plugin processing multiple devices or if somehow the environment is different within the plugin.

**Comment by arttobe** [comment]
I have tried this and the result is the same. I also tried AndroidStudio but is the same result. I also tried to run it as root and alos the same result

Do you has any further ideas

**Comment by helin24** [comment]
We're thinking there may be potential race conditions with daemon startup. You could try killing all of the running daemons and see if you get the correct devices when the IDE restarts them.

You can find the processes to kill with this on the command line: `ps xa | grep flutter | grep daemon | grep -v java`

**Comment by arttobe** [comment]
It is still not working anymore advices
