### ISSUE TITLE
The "--platforms" argument is not supported in package template.

### ISSUE THREAD

**Issue by kuglee** [flutter/flutter-intellij#5252]
## Steps to Reproduce
Create a new package:

<img width="844" alt="Képernyőfotó 2021-02-09 - 7 40 37" src="https://user-images.githubusercontent.com/1316211/107325613-5819c300-6aaa-11eb-8e08-11e5dc4e78fc.png">
<img width="598" alt="Képernyőfotó 2021-02-09 - 7 37 52" src="https://user-images.githubusercontent.com/1316211/107325658-6d8eed00-6aaa-11eb-9007-58e49e99f4e9.png">

## Version info

[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on macOS 11.1 20C69 darwin-arm, locale hu-HU)
    • Flutter version 1.26.0-17.3.pre at /opt/flutter
    • Framework revision 4b50ca7f7f (4 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.0.5
    • Dart plugin version 203.6912

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 2 categories.

**Comment by devoncarew** [comment]
cc @stevemessick

**Comment by Lazizbek97** [comment]
> ## Steps to Reproduce
> Create a new package:
> 
> <img alt="Képernyőfotó 2021-02-09 - 7 40 37" width="844" src="https://user-images.githubusercontent.com/1316211/107325613-5819c300-6aaa-11eb-8e08-11e5dc4e78fc.png">
> 
> <img alt="Képernyőfotó 2021-02-09 - 7 37 52" width="598" src="https://user-images.githubusercontent.com/1316211/107325658-6d8eed00-6aaa-11eb-9007-58e49e99f4e9.png">
> 
> ## Version info
> [✓] Flutter (Channel beta, 1.26.0-17.3.pre, on macOS 11.1 20C69 darwin-arm, locale hu-HU) • Flutter version 1.26.0-17.3.pre at /opt/flutter • Framework revision 4b50ca7f7f (4 days ago), 2021-02-04 19:44:27 -0800 • Engine revision 2c527d6c7e • Dart version 2.12.0 (build 2.12.0-259.8.beta)
> 
> [✗] Android toolchain - develop for Android devices ✗ Unable to locate Android SDK. Install Android Studio from: https://developer.android.com/studio/index.html On first launch it will assist you in installing the Android SDK components. (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions). If the Android SDK has been installed to a custom location, please use `flutter config --android-sdk` to update to that location.
> 
> [✓] Xcode - develop for iOS and macOS • Xcode at /Applications/Xcode.app/Contents/Developer • Xcode 12.3, Build version 12C33 • CocoaPods version 1.10.0
> 
> [✓] Chrome - develop for the web • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [!] Android Studio (not installed) • Android Studio not found; download from https://developer.android.com/studio/index.html (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
> 
> [✓] IntelliJ IDEA Community Edition (version 2020.3.2) • IntelliJ at /Applications/IntelliJ IDEA CE.app • Flutter plugin version 53.0.5 • Dart plugin version 203.6912
> 
> [✓] Connected device (1 available) • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150
> 
> ! Doctor found issues in 2 categories.

Maybe you should run `flutter create --platforms ios .` in terminal. I have also tried to create a new module(iOS) in vs code but that failed. Then I run the code into the terminal and  it worked.

**Comment by Joematpal** [comment]
How do you create unit tests for a "package" if it prompts you to add linux when you press the run button in the tests folder?

**Comment by zjamshidi** [comment]
I want to add mac support to an existing project and I get the same error even in terminal!

**Comment by tolland** [comment]
for adding support, I found if you go into `.metadata` and change the project_type to "app" you can add the platform support....
