### ISSUE TITLE
Internal error (java.util.concurrent.ExecutionException): com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class org.jetbrains.android.facet.AndroidFacetProperties java.util.concurrent

### ISSUE THREAD

**Issue by NishantKrishali** [flutter/flutter-intellij#5260]
Hi,

I can run my app in Andriod studio but I am gettting Java issues in Flutter/Intellij. Error Attached
[JavaBuildError.pdf](https://github.com/flutter/flutter-intellij/files/5982993/JavaBuildError.pdf)

**Comment by stevemessick** [comment]
@NishantKrishali What kind of project is this? Does the problem go away if you disable the Flutter plugin? If this is a Flutter project and the problem persists even when the Flutter plugin is disabled then we can't fix it. You may need to create a new project and copy your files into it.

**Comment by stevemessick** [comment]
Glad to know it is working.
