### ISSUE TITLE
Make it obvious when Flutter commands finish.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#527]
Following up from #525, we should make sure all commands display something on finish.

**Comment by pq** [comment]
(Got this.)

**Comment by devoncarew** [comment]
FYI, the Dart plugin suffixes processes with `Process finished with exit code 0`.

**Comment by pq** [comment]
Cool.  I'm tempted to add this for all commands.  (Unless you think otherwise?)

**Comment by devoncarew** [comment]
Yeah, making it uniform sounds great.
