### ISSUE TITLE
Can't save project into folder containing hyphens (must be a valid Dart package name)

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [flutter/flutter-intellij#5272]
## Steps to Reproduce

1. Create New Flutter project
   - Project name: jet_browser
   - Project location: C:\jet-browser-flutter
2. Click Finish 
3. Error appears:
![image](https://user-images.githubusercontent.com/3907898/108336401-48019200-71d4-11eb-9455-1776cac0eed8.png)

From my POV, the location should be independent on project name.  

## Version info

[√] Flutter (Channel master, 1.26.0-18.0.pre.202, on Microsoft Windows [Version 10.0.19041.746], locale en-US)
    • Flutter version 1.26.0-18.0.pre.202 at C:\flutter-sdk\flutter
    • Framework revision dd67318be3 (2 weeks ago), 2021-02-04 16:51:03 -0500
    • Engine revision 8076607c3e
    • Dart version 2.12.0 (build 2.12.0-286.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\j.tosovsky\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\RedHat\java-11-openjdk-11.0.8-2\bin\java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\j.tosovsky\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 79.0.309.65

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by stevemessick** [comment]
It looks like we're a bit over-zealous about this check. The following command line does exactly what it should:
`flutter create --project-name=t_t t-t`

@pq
