### ISSUE TITLE
Add support for the new Flutter project template

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#5281]
See https://github.com/flutter/flutter/pull/76519 for details.

**Comment by filiph** [comment]
In terms of Android Studio UI, here's a terrible mock that I made:

<img width="800" alt="new-app-template" src="https://user-images.githubusercontent.com/919717/108786585-c0e05100-7528-11eb-91e2-0d6efe77c1e1.png">

It asks for a bit more "descriptive" icon for the two app templates (the starter app with it's FAB button, and possibly a number, the "full" app with a list view).

My initial suggestions is to have:

* "Starter app" (the current Counter template)
* "Full app" (the proposed new template https://github.com/flutter/flutter/issues/76379)

I was initially thinking about "complex app", but Ian's idea to call the template "full" is better, imho. Though the naming is still very much uncertain, and will probably be discussed in https://github.com/flutter/flutter/issues/76379.

**Comment by stevemessick** [comment]
Thanks @filiph ! That will probably work. We'll use whatever name is finally chosen.

**Comment by stevemessick** [comment]
The template PR was closed without merging, and still needs some work.

**Comment by filiph** [comment]
Yes, thanks for punting!

**Comment by stevemessick** [comment]
This is based on https://github.com/flutter/flutter/pull/83530 now.

**Comment by stevemessick** [comment]
Fixed by #5765
