### ISSUE TITLE
flutter hot reload and restart not working on more than 1 device

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter-intellij#5297]
When I run flutter on 2 devices like 2 mobile emulators or 1 mobile emulator and Linux, the last one, which is the second one is running doesn't hot reload, when I hit the hot restart button, the new run starts. It's hard to explain this situation, so I made a video for 2 devices, Linux and mobile. This happens as same as mobile and mobile.

https://user-images.githubusercontent.com/20153831/109770724-28755b00-7c11-11eb-9c5c-4b8662fce246.mp4

**Comment by EArminjon** [comment]
![image](https://user-images.githubusercontent.com/37028599/109794131-d71b9a80-7c15-11eb-9eb6-fc8fcbce5571.png)

Maybe you used it wrong. Hot reload is the yellow icon. Green play button is the hard reload.

**Comment by aliyazdi75** [comment]
@EArminjon 
Yes that works, I've never used those buttons there's, I've always used `ctrl+s` for hot reload and run button for hot restart :smile: 
Thank you.

**Comment by EArminjon** [comment]
In fact ctrl s will hot reload the current device. You need to select an other to apply the chance ;). 
I useful to test a bug on a specific device. But it's a pain to test something on all :).

**Comment by aliyazdi75** [comment]
@EArminjon
Yes, it's so painful but I have to test socket handling and need to test on more than one device at a time.
