### ISSUE TITLE
Intellij IDEA plugin doesn't enable Linux as platform for Flutter projects

### ISSUE THREAD

**Issue by abelardolg** [flutter/flutter-intellij#5304]
## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
Steps:

* New | project | Flutter | click on next screen
* At that second screen (picture#1) there is a message that tell us how to enable Linux. I executed that command (picture#2) then I restart Intellij IDEA but it doesn't allow us to choose Linux yet.
![image](https://user-images.githubusercontent.com/22522883/110174184-08f05500-7e00-11eb-922b-f0e37b3126ee.png)
![image](https://user-images.githubusercontent.com/22522883/110174078-d9d9e380-7dff-11eb-9689-ea3436f1100f.png)
![image](https://user-images.githubusercontent.com/22522883/110174117-f0803a80-7dff-11eb-9970-2f6e3668581e.png)

**Comment by kyancey** [comment]
Am I reading the code wrong or is it simply because the IDE is pulling cached platform config values every time in PlatformsForm.kt on line 33?
