### ISSUE TITLE
Reload not performed on save, even without any issue

### ISSUE THREAD

**Issue by vitorhm** [flutter/flutter-intellij#5309]
## Steps to Reproduce

The following code makes reloading on save not working:
`contactWrapper.contact.displayName?[0] ?? ''`

![Reload not performed](https://user-images.githubusercontent.com/13134788/110491058-aa60fa80-80cf-11eb-9625-c91d301e6f82.png)

If I replace the above code with a `Container()`, for example, the hot reload works.

**Here are the full code:**
```
class ContactItem extends StatelessWidget {
  final ContactWrapper contactWrapper;

  const ContactItem({
    Key? key,
    required this.contactWrapper,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BaseView<ContactCheckModel>(
      onModelReady: (model) => model.init(contactWrapper),
      builder: (context, model, child) {
        return ListTile(
          leading: CircleAvatar(
            backgroundColor: Theme.of(context).primaryColor,
            child: Text(
              contactWrapper.contact.displayName?[0] ?? '',
              style: TextStyle(color: Colors.white),
            ),
          ),
          title: Text(
            contactWrapper.contact.displayName ?? '',
            style: Theme.of(context).textTheme.subtitle1,
          ),
          trailing: Checkbox(
            onChanged: (bool? value) {
              model.checkContact(contactWrapper, value ?? false);
            },
            value: contactWrapper.isChecked,
          ),
        );
      },
    );
  }
}
```

Here is a image of the Dart Analysis not showing any error:
![Dart Analysis](https://user-images.githubusercontent.com/13134788/110491047-a8973700-80cf-11eb-88a1-aa4476b0220d.png)

I've tried to do a **Flutter Clean** and restart the **Dart Analysis**, but the error persist.

## Version info

[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.13.6 17G66 darwin-x64, locale en-AF)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode 10.3.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
[✓] Connected device (2 available)

**Comment by vitorhm** [comment]
Just more information, if I go to another class and save, the hot reload works. The problem only occurs if I save the above class.

**Comment by stevemessick** [comment]
In your screenshot, there is a button labeled `view issues`. Can you add a screenshot of what gets displayed when you click it?

**Comment by vitorhm** [comment]
> In your screenshot, there is a button labeled `view issues`. Can you add a screenshot of what gets displayed when you click it?

It shows the **Dart Analysis** with no issues:
![Untitled](https://user-images.githubusercontent.com/13134788/111501152-7c109a00-8723-11eb-9483-7b990c25a151.png)

**Comment by vitorhm** [comment]
I think it's a bug with the conditional (**?**) operator, because if I put the assert (**!**) operator then it works:
`contactWrapper.contact.displayName![0] ?? ''`

**Comment by stevemessick** [comment]
@alexander-doroshko It looks like this is due to a bug in the PSI-based Dart parser. `FlutterReloadManager.hasErrorsInFile()` uses it to check for errors, and it is reporting a problem with the conditional access operator.

@vitorhm If no one responds here, you might want to open as issue at [youtrack.jetbrains.com](https://youtrack.jetbrains.com/newissue) since the Dart plugin is a Jetbrains product.

**Comment by alexander-doroshko** [comment]
@stevemessick Sorry, I'm offline until 3/29.

**Comment by alexander-doroshko** [comment]
I confirm it's an issue in Dart plugin. Here's an issue to track progress: https://youtrack.jetbrains.com/issue/WEB-50212

**Comment by stevemessick** [comment]
Thanks @alexander-doroshko !
