### ISSUE TITLE
new projects are not picking up the Flutter SDK to use

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#5313]
New projects are no longer picking up the Flutter SDK to use; we'd previously discovered the correct flutter sdk setting by parsing the .packages file. This code still exists in the plugin, so we'll need to look into why this workflow regressed.

**Comment by stevemessick** [comment]
Looks like we need to add a new implementation of that feature. The `.packages` file of a new project starts with:
```
# This file is deprecated. Tools should instead consume 
# `.dart_tools/package_config.json`.
```
It looks like `.dart_tool/package_config.json` (no 's' after 'tool') has enough info we can find it.

**Comment by devoncarew** [comment]
Interestingly enough, from here:

https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/utils/FlutterModuleUtils.java#L364

`DartPlugin.isDartSdkEnabled(module)` is returning true, so we're not trying to parse the .packages file and look for the flutter sdk location. For the created project however - when I use it - it does not have a dart sdk (or a flutter sdk) set, nor have the 'enable dart support for this project' setting set.
