### ISSUE TITLE
New Project Wizard not recognizing that Desktop platforms are enabled.

### ISSUE THREAD

**Issue by kyancey** [flutter/flutter-intellij#5315]
I'm not the first to spot this. See this issue submitted on Jetbrains' tracker: https://youtrack.jetbrains.com/issue/IDEA-263698 which includes screenshots.

The issue is that the Wizard will now allow you to create a Desktop project. Obviously, the wizard tells you that you have to enable desktop options with flutter config, and I did that, but even when they're verifiably enabled and every checkbox is ticked in flutter doctor, the options will not enable in the new project wizard.

**Comment by jacob314** [comment]
This is making it harder for users to get started with desktop.

**Comment by kyancey** [comment]
I may be misreading the code, but it appears to me that PlatformsForm.kt is querying only cached values for configured platforms on line 33.

**Comment by stevemessick** [comment]
Dup of #5304
