### ISSUE TITLE
Flutter is great but need something more like auto firebase connection and google apis and maps integration for pick and drop so that less code more things

### ISSUE THREAD

**Issue by Shaban-ali** [flutter/flutter-intellij#5317]
please provide a service with flutter like auto firebase connectivity .. Google maps APis .. for particular use.. like pick and drop geo locator all these should be in one click direct connect to project..

hope that

**Comment by stevemessick** [comment]
For enhancements to the Flutter SDK, please submit an issue at https://github.com/flutter/flutter/issues
