### ISSUE TITLE
Support FVM 

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#5323]
Hello,

I use FVM to quickly change flutter and dart version for my project. Currently it's impossible to use flutter from FVM with this plugin. 

The result is giving: 
<img width="749" alt="Capture d’écran 2021-03-16 à 16 08 47" src="https://user-images.githubusercontent.com/2970449/111332237-e5d06b80-8671-11eb-933f-a1ad32fafc6b.png">

Would be nice that we can use it as it's a working version. That's the minimum, another cool things would be that if the folder `.fvm/flutter_sdk` exist, it's used by default as it mean the project is using FVM.

**Comment by jaumard** [comment]
Is there any workaround possible in the time being ?

**Comment by jaumard** [comment]
The VS plugin doesn't have this issue if it can help

**Comment by stevemessick** [comment]
We actually do some strict configuration checking, which evolved over years of error reporting. I don't think we'll be changing that. It looks like your SDK is missing this directory: `bin/cache/dart-sdk/lib`.

I checked with my Mac and verified that symlinks work for both `bin/cache/dart-sdk/lib` and the root of the SDK.

I'd recommend filing an issue with FVM.

**Comment by jaumard** [comment]
Ok thanks I'll investigate why I have this missing directory! Thanks for the tips!
