### ISSUE TITLE
Future stoping code analyze, intelisense, code completion in Android Studio

### ISSUE THREAD

**Issue by d-apps** [flutter/flutter-intellij#5324]
## Steps to Reproduce

Sometimes when I'm specifying the type of Future or just typing Future, the Android Studio stops analyzing the code and no matter what I type, intelisense, code completion, analyze, they doesn't work anymore.

![Tue Mar 16 2021 19_27_53 GMT-0300 (Horário Padrão de Brasília)](https://user-images.githubusercontent.com/20110433/111393322-46be6a80-8697-11eb-9560-7617597513b6.png)

## Version info

[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [versÃ£o 10.0.19042.867], locale pt-BR)
    • Flutter version 2.0.2 at C:\src\flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Djalma\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\Djalma\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!

**Comment by stevemessick** [comment]
I believe the root problem here is the same as https://github.com/dart-lang/sdk/issues/44477

However, that fix is in the Flutter 2.0 SDK, so maybe this is different.
