### ISSUE TITLE
Stuck on "Activating Dart Devtools"

### ISSUE THREAD

**Issue by schisms** [flutter/flutter-intellij#5342]
Since upgrading to the latest version of Flutter, I cannot debug my apps while connected to the internet. It simply gets stuck on "Activating Dart Devtools...". If I disconnect from the internet, and then debug, it's fine. My internet speed is around 50mbit.

Also, if I try to debug while connected to the internet, the "Activating Dart Devtools" does not go away. I have to close my IDE and terminate all dart related processes.

[✓] Flutter (Channel beta, 2.0.2, on macOS 11.2.2 20D80 darwin-arm, locale
en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.1)

**Comment by helin24** [comment]
@schisms what is your Flutter plugin version? (Can find this in Settings > Plugins)

Also, are you able to open DevTools from a link in console output when you run your app on the command line?

**Comment by schisms** [comment]
Problem has been resolved. I think the issue was on server side as I didn't make any changes.

Closed.

**Comment by schisms** [comment]
Issue started again just now. Can't run DevTools from console output or VS code. I tried to await an error message in console, but after 5-10 minutes nothing. Are the servers having issue? Somebody else reported they were encountering the same issue on my old thread.

**Comment by helin24** [comment]
Closing this and continuing issue discussion on DevTools. Sorry about the confusion here.
