### ISSUE TITLE
ANSI color not work in console.

### ISSUE THREAD

**Issue by sososdk** [flutter/flutter-intellij#5356]
Environment:

- Android Studio: 4.1.3
- Flutter Plugin: 54.1.1
- System: macos

Code:
```dart
ansiColorDisabled = false;
print((AnsiPen()..red()).write('msg'));
```

Console Output:
```
flutter: \^[[38;5;1mmsg<…>
```

**Comment by sososdk** [comment]
Android only 😂 .

**Comment by mhrst** [comment]
Why though? VSCode can provide ANSI colors from an iOS device.
