### ISSUE TITLE
Enable starting an Android simulator from IntelliJ

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#536]
If no Android virtual device is running, you have to start it from the Android AVD Manager. Would be good to have en entry in tools to open that, similar to what Android Studio has (we should probably call it `Android AVD Manager`):

<img width="568" alt="screen shot 2016-12-13 at 12 14 37" src="https://cloud.githubusercontent.com/assets/13644170/21138322/c9a0d8c2-c12d-11e6-97c2-9027f1345726.png">

**Comment by mit-mit** [comment]
Upon closer look, looks like the AVD Manager is an Android Studio dialog, so would we have to recreate that also?

**Comment by devoncarew** [comment]
There's probably a way to interact with the command-line tool. We may not (easily) get device creation, but we should be able to launch them,

**Comment by mit-mit** [comment]
OK. Launching is definitely the most important part.

**Comment by mit-mit** [comment]
Looks like the following might work?

```
> $ANDROID_HOME\tools\emulator -list_avds
Nexus_5X

> $ANDROID_HOME\tools\emulator -avd Nexis_5X
```

**Comment by devoncarew** [comment]
That worked for me locally (`$ANDROID_HOME/tools/emulator -list-avds`). Seems like a good addition, and a nice parallel to the iOS support.

**Comment by devoncarew** [comment]
(just fyi, I ran into a case yesterday where I could have used this)

**Comment by pq** [comment]
👍 Looking at it now!

**Comment by pq** [comment]
I'm thinking we'll depend on `$ANDROID_HOME` being set. In case it's not... should we simply tell them that?  I'm assuming we don't want to support path setting.  For instance like:

<img width="713" alt="screen shot 2017-01-27 at 10 33 03 am" src="https://cloud.githubusercontent.com/assets/67586/22382774/045287ce-e47c-11e6-8228-3085831250f0.png">

I guess another approach would be configuring an external tool?

<img width="265" alt="screen shot 2017-01-27 at 10 32 50 am" src="https://cloud.githubusercontent.com/assets/67586/22382802/24ce113a-e47c-11e6-88ac-9e1ecbfd2a39.png">

(On second thought I don't think this is quite right.)

@devoncarew

**Comment by devoncarew** [comment]
Yeah, don't know. We should, in as much as is possible, use the android sdk that flutter_tools will use. Flutter tools locates that three different ways; using `ANDROID_HOME`, using `PATH`, and using the value the user might have set in `flutter config  --android-studio-dir`. We don't really want to replicate this logic in intellij.

We may want to add some way for the flutter tool to communicate basic settings back to a caller. `flutter doctor --json`? `flutter config --dump-settings`?

**Comment by mit-mit** [comment]
Re-titeling to make a little less implementation specific.

**Comment by mit-mit** [comment]
This came up with several participants in the recent developer event. They thought their installation was "broken" as the Device Selected had an iOS entry but no Android entry.

**Comment by brianegan** [comment]
+1 to this ticket -- I have a Flutter project and I'd love to use AVD Manager right there within the project. For some reason, when I open up a flutter project, the Android menu no longer appears in the Tools menu, which means I can't run AVD manager easily from within the project as a work-around either.

**Comment by mit-mit** [comment]
@pq what is this blocked on?

**Comment by pq** [comment]
@mit-mit : Really just prioritization.  Ideally this should happen in the flutter tools layer.  Alternatively we can shim it into the plugin.

**Comment by devoncarew** [comment]
As a partial step, let's:

- list existing emulator devices
- offer to open emulators

**Comment by BandarTheMonkey** [comment]
i started android emulator from android studio but intellij still doesn't load any devices.
