### ISSUE TITLE
Flutter Inspector not showing correctly

### ISSUE THREAD

**Issue by d-apps** [flutter/flutter-intellij#5365]
## Steps to Reproduce

Android Studio is not showing Fluter Inspector correctly, the items are too big,

![image](https://user-images.githubusercontent.com/20110433/113205790-0d642e00-9245-11eb-8062-9bf76d8eede9.png)

## Version info

[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [versÃ£o 10.0.19041.867], locale pt-BR)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [versÃ£o
      10.0.19041.867]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!

**Comment by helin24** [comment]
@d-apps can you check your display settings and tell me your scaling and resolution values (or a screenshot if that's easier)?
