### ISSUE TITLE
Poor display of embedded DevTools

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#5366]
This may be related to #5365 

Here are two images for comparison.

DevTools in Chrome:
![devtools](https://user-images.githubusercontent.com/8518285/113225665-09371100-9243-11eb-99e8-e6a3db98f7b1.png)

Embedded DevTools in Android Studio:
![embedded](https://user-images.githubusercontent.com/8518285/113225716-24098580-9243-11eb-921b-5123989fadf3.png)

I should have grabbed the entire window so you could see the DevTools elements were larger than native Android Studio, although you can get the idea from the title bar. This was on my Windows machine, a "gaming laptop" which should have good graphics (and does, elsewhere).

Display settings:
Scaling is 125% (default, recommended)
Resolution is 1920x1080 (default, recommended)

Flutter plugin v55.0.1
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 2.0.3 at C:\Users\steve\flutter\flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\steve\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.1
    • Flutter plugin version 55.0.3
    • Dart plugin version 203.7759

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\steve\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!

**Comment by devoncarew** [comment]
@helin24 - is this perhaps an issue with screen density detection and JxBrowser?

**Comment by helin24** [comment]
@stevemessick when I've asked about this in the past, the JxBrowser team suggested it could be an issue of what JRE is being used to run IntelliJ. Next time you're at this machine, can you check on this? ([instructions on how to check version](https://stackoverflow.com/questions/30631286/how-to-specify-the-jdk-version-in-android-studio/49425010#49425010))

Last time this came up we tried adjusting a dpi setting but it seems that doesn't work. Following up with JxBrowser to see if there are any other options.

**Comment by stevemessick** [comment]
@helin24 Here's the info you requested:
>steve@MSI MINGW64 /c/Program Files/JetBrains/IntelliJ IDEA 2019.2.1/jbr/bin
$ ./java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment JBR-11.0.9.1.11-1145.63-jcef (build 11.0.9.1+11-b1145.63)
OpenJDK 64-Bit Server VM JBR-11.0.9.1.11-1145.63-jcef (build 11.0.9.1+11-b1145.63, mixed mode)

Ignore the "2019.2.1" -- I upgraded in place and didn't rename the directory. It's on 2020.3.

**Comment by stevemessick** [comment]
@helin24 I think I was actually using Android Studio. Here's its version:

> openjdk version "1.8.0_242-release"
OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)

Confirmed that switching display resolution from 125% to 100% cleaned it up nicely.

**Comment by stevemessick** [comment]
I checked with both Android Studio 4.1 and IntelliJ 2021.1. The Java versions of each are posted above. It does not scale properly only in Android Studio; it is fine in IntelliJ. So yes, this problem is fixed by upgrading Java. We'll just have to wait for the next release of Android Studio.

**Comment by helin24** [comment]
We may want to reopen this; my previous instruction for finding the version was incorrect, as that version should match the JDK used when we run an application from IntelliJ, not the version that IntelliJ is using when it's running.

The JxBrowser team sent me this link describing how to change what version IntelliJ is run with: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under. They recommend Oracle and OpenJDK versions instead of the default Idea JRE.

However, either way I don't think we have a way to solve this for users universally, since this is a user setting.
