### ISSUE TITLE
"Jump to source" on widget test open widget_tester.dart instead of test definition

### ISSUE THREAD

**Issue by woprandi** [flutter/flutter-intellij#5367]
## Steps to Reproduce

Run any **widget** test, then use "jump to source" (F4). The `widget_tester.dart` file from flutter_test library will be opened instead of the test definition. The behavior is correct on unit test.

## Version info

```
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale fr_FR.UTF-8)
    • Flutter version 2.0.3 at /home/william/Documents/flutter
    • Framework revision 4d7946a68d (il y a 2 semaines), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/william/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.0.0 (Fedora 11.0.0-2.fc33)
    • cmake version 3.19.7
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /home/william/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/203.7717.56
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90
```

**Comment by stevemessick** [comment]
Here's what `DartTestEventsConverterZ.process()` has for its `obj` argument:
```json
 {"test":{"id":3,"name":"Counter increments smoke test","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":126,"column":5,"url":"package:flutter_test/src/widget_tester.dart","root_line":14,"root_column":3,"root_url":"file:///Users/messick/AndroidStudioProjects/flutter_app/test/widget_test.dart"},"type":"testStart","time":115818}
```

Note that the value of the `url` property is `package:flutter_test/src/widget_tester.dart`.

The IDE is jumping to the location given by `flutter_tool`. The question is, who owns (or knows about) the code that is giving us the wrong URL?

@devoncarew @jacob314 for advice.

**Comment by woprandi** [comment]
@stevemessick I see so the issue is in `flutter_tools` package not here

**Comment by stevemessick** [comment]
Yes, I think so. We haven't had time to investigate further yet, but we will.

**Comment by devoncarew** [comment]
Wrt `package:flutter_test/src/widget_tester.dart`, I think this is because that's the location that's actually calling `package:test`s `test` definition method; Flutter's `testWidgets` definition method just wraps it.

I think that package:test would need to handle when there was indication like this. These wrapper test methods are generally marked with `@isTest` annotations (from package:meta), so there should be a way to do this w/ having to special case things.

cc @natebosch who would likely know the impl. here

**Comment by natebosch** [comment]
> These wrapper test methods are generally marked with `@isTest` annotations - from package:meta - so there should be a way to do this w/ having to special case things.

That's true for the platforms that support mirrors but won't help us on the web. It would be a big jump in complexity over our current implementation which assumes a constant number of stack frames between the user's test definition and the `package:test` libraries.

https://github.com/dart-lang/test/blob/4f90091595ef4e82b883507947df204ee9a139fe/pkgs/test_api/lib/src/backend/declarer.dart#L204

**Comment by natebosch** [comment]
I filed https://github.com/dart-lang/test/issues/1514 to track this. I don't expect an easy solution.

**Comment by stevemessick** [comment]
Thanks @natebosch ! Closing this one.

**Comment by jakemac53** [comment]
Note that we do include the desired information today - it is in the `root_column`, `root_line`, and `root_url` fields. These are optional fields that are provided if the call to `test` is not in the root test url.

If you jump to these locations when present, I think that would resolve this?

**Comment by stevemessick** [comment]
Thanks @jakemac53 ! PR incoming.
