### ISSUE TITLE
Setting up the flutter-intellij for first build

### ISSUE THREAD

**Issue by Jaineel-Mamtora** [flutter/flutter-intellij#5379]
Hello flutter-intellij team,

I am new to opensource and I was trying to build the flutter-intellij plugin for the first time. I was getting few errors for which I have found some fixes which I would like to share.

Firstly, here's my Version Info:

```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_IN)
    • Flutter version 2.0.4 at /home/jaineel/src/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/jaineel/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at
      /home/jaineel/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/211.6693.111
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

> NOTE: Please follow the [CONTRIBUTING.md](https://github.com/flutter/flutter-intellij/blob/master/CONTRIBUTING.md) and if you are stuck somewhere... you can follow along.
> Also make sure that you have configured IntelliJ Platform Plugin SDK properly.

Steps I followed:

 1. Opened the flutter-intellij repository in IntelliJ IDEA. I got a dialog box asking to `Load Gradle Project`. I accepted that.

 2. Clicked on `Build -> Build Project` on Toolbar. Got these errors: 

	- `java: package com.google.common.base does not exist`
		-> Please add `com.google.guava:guava:28.2-jre` maven dependency.

	 - `java: package org.apache.commons.lang does not exist`
		-> I found this error was generated on every import statement:
		`import org.apache.commons.lang.StringUtils;`
		So, I did a global 'Find and Replace' of above import statement to:
		`import org.apache.commons.lang3.StringUtils;`
		And the error was gone.

	- `java: package org.yaml.snakeyaml does not exist`
		-> Go to 
		File -> Project Structure -> Modules -> flutter-intellij -> Dependencies Tab -> Press '+' and add  [snakeyaml JAR](https://jar-download.com/artifacts/org.yaml/snakeyaml/1.23/source-code) dependency (please make sure to download 1.23 version only).

	- `package net.miginfocom.swing does not exist`
		-> Go to 
		File -> Project Structure -> Modules -> flutter-intellij -> Dependencies Tab -> Press '+' and add  [net.miginfocom.swing JAR](https://jar-download.com/maven-repository-class-search.php?search_box=net.miginfocom.swing) dependency (I have downloaded 5.2 version).

3. Converted `testCompile` to `testImplementation` in `build.gradle`.

And after all these steps, all the errors were gone. However few warnings were there stating:
`Kotlin: Classpath entry points to a non-existent location`
You can ignore them.

And finally, I ran the `flutter-intellij` Run/Debug Configuration and it ran successfully!

Hope this was helpful.

**Comment by stevemessick** [comment]
Thanks for the report!

When opening the Flutter plugin project, you should not use the Gradle version. It is better to open the project using `flutter-intellij.iml'. We used to use Linux for CI but switched to MacOS. It is possible the Linux build is no longer working, but we need to look into that before making any changes.

**Comment by AlexV525** [comment]
I've noticed that you accept the "Load Gradle Project", as it turns out we don't actually need it. Could you help us to verify that not loading the gradle script fixes your issue? Thanks a lot.

**Comment by AlexV525** [comment]
Also there are few steps updated in the contributing doc, which explicitly asked user to ignore or skip the gradle load popup.

**Comment by Jaineel-Mamtora** [comment]
Yes, I can see @AlexV525 you made the changes to the CONTRIBUTING.md.

Also, yes, the build is working without loading Gradle project.

**Comment by AlexV525** [comment]
> Also, yes, the build is working without loading Gradle project.

Glad to hear that!
