### ISSUE TITLE
flutter packages get action in flutter.yaml butter bar doesn't do anything

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#538]
<img width="267" alt="screen shot 2016-12-13 at 12 38 12 pm" src="https://cloud.githubusercontent.com/assets/1269969/21158200/19a22ad0-c131-11e6-9021-8653d33e782c.png">

I have not tried debugging, but `packages get` and `packages upgrade` didn't seem to do anything (`flutter upgrade` and `flutter doctor` do work).

/cc @pq

**Comment by pq** [comment]
Ha.  Yeah.  It looks like my clever (and obsolete) enablement logic when these were in a context menu was shooting us in the foot.

#539 should fix it.

Thanks for the catch!
