### ISSUE TITLE
Feature Request - include the data of a constant when hovering over a constant.

### ISSUE THREAD

**Issue by atreeon** [flutter/flutter-intellij#5392]
In other languages and IDEs when a constant variable is hovered over the data of the constant is shown in the popup help box.  Would this be possible in flutter intellij idea?

```
const MY_CONST = const MyClass(5);

class MyClass {
  final int value;
  const MyClass(this.value);
}
```
![Screenshot 2021-04-10 at 14 30 31](https://user-images.githubusercontent.com/4139336/114271449-54061500-9a09-11eb-8e69-ff8091c57bf6.png)

**Comment by jwren** [comment]
I created a tracking issue in YouTrack: https://youtrack.jetbrains.com/issue/WEB-50553
