### ISSUE TITLE
"Open in Xcode" when looking at Podfile runs flutter build ios

### ISSUE THREAD

**Issue by cadaniel** [flutter/flutter-intellij#5408]
https://user-images.githubusercontent.com/5515671/114622291-02f55b80-9c6b-11eb-9b59-794a06619a09.mov

Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I tried to open the XCode project from the Podfile, and it tried to build the project instead. 

## Version info
casey@Caseys-Mac-mini normative % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-arm, locale en-CA)
    • Flutter version 2.0.4 at /Users/casey/flutter
    • Framework revision b1395592de (12 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/casey/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • SM G960W (mobile)  • 3338385647453098                     • android-arm64  • Android 10 (API 29)
    • iPhone 12 (mobile) • C8D93A11-7B38-44AF-8136-B57BFD537DA9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

**Comment by stevemessick** [comment]
We need a completed Xcode build to open the project in Xcode. The recovery instructions seem pretty clear, if you can pause the video at just the right moment.

@jmagman Do you know if Xcode has changed its default profiles? This user has three debug profiles but none have the name expected by flutter_tool. LMK if I should transfer this to flutter/flutter.

**Comment by cadaniel** [comment]
I wouldn't expect it to run anything and just give me an error? You can see in the video it tried to build it rather than an error?

**Comment by stevemessick** [comment]
@cadaniel Did you try the suggested remedy? It is printed in red text in the video.

**Comment by cadaniel** [comment]
The error is actually I have custom schemes in the iOS project. 

I knew I needed open the Xcode project, and that's what I was trying to do. I had to open a swift file and use that link instead.

**Comment by jmagman** [comment]
@stevemessick there's a new `flutter build --config-only` flag https://github.com/flutter/flutter/pull/64848 available in `1.22.0-12.0.pre` which will set up the Xcode project, but not actually compile anything.

https://github.com/flutter/flutter-intellij/blob/aef6bd5e9287b21d3ef5c2167991724916e11edd/src/io/flutter/actions/OpenInXcodeAction.java#L80 

The user will still need to go into Xcode and swap their scheme.  But at least they won't see any errors.

**Comment by cadaniel** [comment]
That's awesome! I don't care that the build failed, I just wanted to open straight to Xcode.

**Comment by cadaniel** [comment]
Also I don't buy the Xcode wasn't set up enough to open Xcode. Because switching to a .swift file and opening using the same link worked, and the bug still happened even after Xcode was actually already open.

**Comment by jmagman** [comment]
> Also I don't buy the Xcode wasn't set up enough to open Xcode. Because switching to a .swift file and opening using the same link worked, and the bug still happened even after Xcode was actually already open.

I mean, it'll open, but it won't actually build in Xcode unless you (or your IDE) run `flutter build ios` at least once to populate the Xcode build settings.  It worked for you because the IDE did that for you and populated the build settings.  You can run `flutter clean` then `open ios/Runner.xcworkspace` and see for yourself.

 If you're using schemes, you're probably better off using the command line so you can pass in your flavor names.

**Comment by cadaniel** [comment]
The problem is it didn't open. I had to go to a different file to open Xcode. 

I know flutter needs to build first, but I'm chasing some unrelated Xcode madness to test some iOS specific features.

**Comment by jmagman** [comment]
> The problem is it didn't open. I had to go to a different file to open Xcode.

Just open the project directly in Xcode, `open ios/Runner.xcworkspace`.

**Comment by cadaniel** [comment]
That's still harder. 

The point is why did it work on a swift file and not Podfile

**Comment by stevemessick** [comment]
> @stevemessick there's a new flutter build ios --config-only flag flutter/flutter#64848 available in 1.22.0-12.0.pre which will set up the Xcode project, but not actually compile anything.

Thanks @jmagman ! I did not know about that. We'll use that instead.

@cadaniel wrote:
> The error is actually I have custom schemes in the iOS project.

Exactly. The flutter command line tool doesn't know how to use your custom schemes. If you want to make things work for you now just perform the steps needed by the command line tool. If you do not want to perform those steps then you will continue to see this error.

Future work tracked in #5411
