### ISSUE TITLE
Open in Xcode no longer needs to do a full build

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#5411]
As mentioned in https://github.com/flutter/flutter-intellij/issues/5408#issuecomment-819118860 there is a new option to prepare a project for Xcode prior to opening it. We need to change the `Open in Xcode` function to use it.

**Comment by jmagman** [comment]
@stevemessick I don't think https://github.com/flutter/flutter-intellij/pull/5474 is quite right.  I wouldn't rely on `DART_OBFUSCATION=true` unless `--obfuscate` is explicitly passed in.  I'm happy to review any PRs.

**Comment by stevemessick** [comment]
Fixed in #5489, and reviewed by @jmagman.
