### ISSUE TITLE
Flutter plugin version 55.15 swallows errors 

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#5421]
This is a regression. Please see: https://github.com/flutter/flutter-intellij/issues/4952

You are forcing me to catch my errors and print the stackTrace myself. I appreciate the effort, but I think you are just trying to be "too smart". I want to have the complete stacktrace, always. You can't try to decide for me which part is important, because you can never know that for sure, and even if you are right 99% of the time, the other 1% will create terrible problems and make my team waste countless hours. Stacktrace is free, while my programmers' time is not.

I have broken our app into independent packages/modules, and now you are not giving me the part of the stacktrace that's inside another package (when the error crosses package boundaries). Also, when I use third-party packages I can't know where certain problems happen, so it doesn't help me anymore to fix the problem, or even to allow me to help the package author to solve it. Even when the error is inside of Flutter itself, I do want to see all of the stacktrace.

Flutter's Stacktrace is full of useless info from Gradle and Flutter initialization. The useful part, which are the stacktraces, you are cutting out. Please don't. Please, let me have all of my stacktrace.

**Comment by marcglasberg** [comment]
Workaround: 
Add this to your app start: 

```dart
FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.dumpErrorToConsole(details, forceReport: true);
  };
```

**Comment by stevemessick** [comment]
@devoncarew Is this something done by the plugin or is it something the Flutter engine does?

**Comment by devoncarew** [comment]
This is _likely_ in the Flutter IntelliJ plugin, although we haven't changed the behavior here in several releases.

@marcglasberg - can you include the version of Flutter that you're using?

**Comment by marcglasberg** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [versÃ£o 10.0.19041.928], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] Connected device (2 available)
