### ISSUE TITLE
Android Framework is not getting detected

### ISSUE THREAD

**Issue by vishnuagbly** [flutter/flutter-intellij#5431]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
1) Upgrade to the latest Android Studio version.
2) Import a new flutter project.

After the above steps, one can notice that now the android framework is not being detected and hence you cannot configure it. Even though it maybe was annoying for some, but It helped a lot, in my case I want to use an emulator inside the android studio itself with the emulator tab, and for that android studio need to detect and configure the Android framework, but due to the latest update it is not possible now. This auto-detection of the android framework was disabled in #5336, which just created problems for me, instead of helping.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at D:\flutter
    • Framework revision adc687823a (7 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.dev

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\vishnu Agarwal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.42

• No issues found!

```
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
I don't follow your workflow. Can you give more detail?

**Comment by vishnuagbly** [comment]
> I don't follow your workflow. Can you give more detail?

@stevemessick I guess u must already know about the new feature of the android studio emulator release with v4.0 I guess, that one can now also open android emulator directly inside the android studio itself, with the emulator tab here is the [link to doc](https://developer.android.com/studio/run/emulator).

To use this feature in my flutter project android studio need to detect and configure the Android framework, but it is not doing that anymore. Earlier also I could not use this feature even by following the steps provided in the above doc, but when I did configure the android framework (from notification of "android framework detected") it start working, that is why I need to detect and configure android framework.

**Comment by vishnuagbly** [comment]
I found out that about emulator tab it is a known issue. But when I would configure android framework after it would get detected it worked great for me. So I guess that could be the solution to this known issue [#3815](https://github.com/flutter/flutter-intellij/issues/3815).

**Comment by stevemessick** [comment]
If this is what you are looking for, you do not need Android framework detection.

<img width="1398" alt="Screen Shot 2021-04-23 at 8 55 47 AM" src="https://user-images.githubusercontent.com/8518285/115897935-d92df880-a411-11eb-9326-60bdc1b4097f.png">

Is that what you want?

**Comment by vishnuagbly** [comment]
> If this is what you are looking for, you do not need Android framework detection.
> 
> <img alt="Screen Shot 2021-04-23 at 8 55 47 AM" width="1398" src="https://user-images.githubusercontent.com/8518285/115897935-d92df880-a411-11eb-9326-60bdc1b4097f.png">
> 
> Is that what you want?

Yes

**Comment by stevemessick** [comment]
Use the menu `View > Tool Windows > Emulator` then launch the emulator from the AVD Manager. We do not plan to change framework detection.
