### ISSUE TITLE
[Enhancement] Display color icon for variables that can be dereferenced to known colors

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#5436]
Currently, the color selector can be parsed and displayed only when the value of the variable explicit starts with "Color" or "Colors", or "CupertinoColors".

Found a related code at https://github.com/flutter/flutter-intellij/blob/28aaecc3078f0f5d065194d64292e920941640d2/src/io/flutter/editor/FlutterColorProvider.java#L41 which abandoned all values other than these patterns.

## Steps to Reproduce

```dart
import 'package:flutter/material.dart' hide Colors;

const Color _c1 = Color(0xff000000);

void test() {
  const Color c1 = _c1;
  const Color c2 = Color(0xffffffff);
  const Color c3 = Color.fromARGB(255, 123, 231, 31);
  const Color c4 = Color(0xff923998);
  const Color c5 = c2;
  const Color c6 = TC.c1;
  const Color c7 = TC.c2;
  const Color c8 = Colors.black;
}

class TC {
  static const Color c1 = Color(0xff449978);
  static const Color c2 = Color(0xffdb2f7f);
}

class Colors {
  static const Color black = Color(0xffcccccc);
}
```

![image](https://user-images.githubusercontent.com/15884415/115981423-32d72400-a5c6-11eb-9bfc-f385e7fa6e7f.png)

## Version info

Flutter 2.0.5.

**Comment by stevemessick** [comment]
That's a good idea. It may have performance issues, though.

**Comment by AlexV525** [comment]
Not sure how much performance regression will raise if we look up it's superclass to see whether it's a `Color` or `CupertinoColor`, but at least this is a proper way I think.

**Comment by stevemessick** [comment]
I agree. My concern is that we have to start looking at RHS expressions of assignments and dereferencing field references, and possibly more. The implementation will have to carefully code that because this detector gets called a lot. Fortunately, we already have the PSI model to use.

**Comment by AlexV525** [comment]
Any plans to implement this recently?

**Comment by AlexV525** [comment]
Maybe we can benefit from this: https://github.com/dart-lang/sdk/commit/3238b2c09c1e2fc023363ea33902d93bcc8b3d79
