### ISSUE TITLE
Strange overwrite problem with auto complete

### ISSUE THREAD

**Issue by atreeon** [flutter/flutter-intellij#5439]
Autocomplete sometimes overwrites text that I don't want it to overwrite as in the video below.  Can this be fixed please?

https://user-images.githubusercontent.com/4139336/116049062-c31c7400-a66d-11eb-8b22-8a16eb014df1.mov

**Comment by stevemessick** [comment]
Positioning of pop-up text is controlled by the IDE (or, perhaps, the Dart plugin, but I don't think so). It is not controlled by the Flutter plugin. I'd suggest checking https://youtrack.jetbrains.com for an existing request, and if not found, creating one.
