### ISSUE TITLE
Add hot restart icon to top-bar when run debug

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter-intellij#5441]
when I run debug. in top-bar not show hot restart icon but showing in bottom-bar

in bottom-bar
<img width="514" alt="Screen Shot 2021-04-27 at 12 07 48" src="https://user-images.githubusercontent.com/52562340/116188206-3814aa00-a751-11eb-8215-242798f33d36.png">
in top-bar
<img width="233" alt="Screen Shot 2021-04-27 at 12 07 39" src="https://user-images.githubusercontent.com/52562340/116188212-3a770400-a751-11eb-9f72-c706b173d08b.png">

**Comment by stevemessick** [comment]
There isn't enough space in the toolbar to put everything that could be useful. You can use the Preferences/Settings window to adjust it to your preferences. See `Menus and Toolbars` under `Appearance and Behavior`.

You can also use the keybinding. In Preferences/Settings, select `Keymap`. Type "hot restart" into the search bar to see what it is on your platform.
