### ISSUE TITLE
Support auto running tests that are in a non-standard location

### ISSUE THREAD

**Issue by matejthetree** [flutter/flutter-intellij#5442]
Other languages in intelliJ allow you to directly run tests from the file.

https://www.jetbrains.com/help/idea/performing-tests.html

For dart, I have to create new test configuration manually, and even then I cannot rerun individual tests.

Is it possible to leverage this IntelliJ power in dart as well?

Thank you

**Comment by matejthetree** [comment]
at least having a quick create configuration option would help

<img width="409" alt="Screen Shot 2021-04-27 at 11 30 40 AM" src="https://user-images.githubusercontent.com/10059426/116219607-1533c700-a74c-11eb-8653-9c8a478f972b.png">

**Comment by stevemessick** [comment]
What version of the plugin do you have? This feature was restored in version 55. It was there previously, too, but disappeared for some reason.

**Comment by matejthetree** [comment]
I have the latest 55.1 version.

I can see now that the issue is when having the tests outside of the flutter folder.

I keep my tests next to the class I am testing.
Even marking the folder as test sources root does not allow the IntelliJ to recognize it.

Is there a an option to recognize any file that either ends with `_test.dart` or that imports `test` or `flutter_test` since those will certainly not be used in production.

The reason for keeping it next to the class is that we have huge codebase and the test are important as a documentation tool as well.

**Comment by matejthetree** [comment]
In vscode, part of the dart extension is to recognize tests outside of dart folder

<img width="883" alt="Screen Shot 2021-04-29 at 6 25 02 AM" src="https://user-images.githubusercontent.com/10059426/116547786-a1ccb980-a8f3-11eb-9517-ea623d3bdb02.png">

**Comment by stevemessick** [comment]
The plugin should look for directories marked as test sources.

**Comment by stevemessick** [comment]
Fixed in #5770
