### ISSUE TITLE
Navigation to dependency info at pub.dev from pubspec editor

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter-intellij#5448]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

The editor used for pubspec.yaml provides hyperlinks on plugins declared under dependencies, dependency_overrides, dev_dependencies, etc.

Unfortunately those links are navigating to the pubspec's json schema, which isn't that useful.
It would be great if those links would navigate to pub.dev page for that dependency. E.g. https://pub.dev/packages/flutter_platform_widgets

![image](https://user-images.githubusercontent.com/440954/116419523-242d7e80-a80b-11eb-929b-1934f6f1fa8a.png)

## Version info

Flutter doctor doesn't show IDEA plugin info for the last few months. Here is what I see in IDEA plugins system settings

![image](https://user-images.githubusercontent.com/440954/116420303-dcf3bd80-a80b-11eb-9d3d-38891e7eee5a.png)

**Comment by stevemessick** [comment]
Moving to https://youtrack.jetbrains.com/issue/IDEA-274183
