### ISSUE TITLE
Debugger: Step to the next line in an async function.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#5449]
Debugging async functions in Dart is super annoying.

I am at line 10. I want to go to line 11:

```
10   var x = await getSomething(); ➜ I am here
11   print(x); ➜ Just want to go here
```

But the `await` means some other code will have the chance to run, and we go to a completely different part of the code.

If I want to go to line 11, I am forced to add a breakpoint there or "force run" to line 11. That's painful. Sometimes I don't even notice there is an await in the middle of the line, and when I try to go the the next line it goes somewhere else and don't even know where I was anymore. I have to restart and pay double attention, which wastes my brain CPU and makes it harder for me to reason about the code.

I was told by Simon Binder that the Dart VM protocol has a "step to the next line in an async function" command (and that is accessible from the observatory), but somehow all IDEs don't use that. 

Please add this to the debugger.

**Comment by stevemessick** [comment]
Yes, StepOption.OverAsyncSuspension was added in version 3.3, so it has been around a while. We should add this.

cc: @devoncarew @jacob314 @kenzieschmoll @DanTup

**Comment by DanTup** [comment]
Thanks for the ping - seems in VS Code we're already using it:

https://github.com/Dart-Code/Dart-Code/blame/a8f34dff86a771727f70057655d1746a2e7a23d6/src/debug/dart_debug_impl.ts#L546

**Comment by stevemessick** [comment]
Well, it seems the Flutter plugin is already using it, too:

https://github.com/flutter/flutter-intellij/blob/906e6db8bb8a50aa99c672a5a1b77137b6f2424e/src/io/flutter/vmService/DartVmServiceDebugProcess.java#L296

@DanTup Do you know if it works correctly in VS Code? I wonder if `suspendContext` is null for some reason.

**Comment by DanTup** [comment]
It does seem to work correctly in VS Code (tested with Dart v2.12.4):

![stepping](https://user-images.githubusercontent.com/1078012/116509232-dd975d00-a8ba-11eb-8a71-6154f2e8f5cf.gif)

**Comment by marcglasberg** [comment]
I am using IntelliJ. The options I have are:

```
F8 - Step Over 
F7 - Step Into 
Alt-Shift-F7 - Force step Into ➜ doesn't work
Shif-F8 - Step Out
Alt-F9 - Run to cursor
```

None of this options work. Code I am using is:

```
void main() async {
  print("INI");
  int x = await getValue();
  print('x = $x');
  print("END");
}

Future<int> getValue() async {
  await Future.delayed(Duration(seconds: 1));
  return 42;
}
```

When I am in the line that says `int x = await getValue();` I want to press some key that will send me straight to the `print('x = $x');` line.

**Comment by stevemessick** [comment]
The problem in the plugin is that `suspendContext.getAtAsyncSuspension()` is returning `false`. We'll have to look into it further.

@marcglasberg In both VS Code and IntelliJ the "Step Over" function is supposed to do what you want. It's broken in IntelliJ, but working in VS Code.

**Comment by stevemessick** [comment]
@marcglasberg If you are using the dev channel of the Flutter plugin then this fix will be available May 17.

**Comment by DanTup** [comment]
@stevemessick sorry for the delay. I tested this but it did seem to work as I expected. I see you pushed a fix here -does that mean it was IntelliJ-specific, or do you think VS Code may need a change too? (I'm curious why the whitespace seemed to affect this if that's the case though).

**Comment by stevemessick** [comment]
Thanks for checking. It was a bug in the Flutter and Dart plugins. Fixed in
both now.
