### ISSUE TITLE
[Request] add suggestion when abstract keyword error

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter-intellij#5458]
I just got this message:

`Members of classes can't be declared to be 'abstract'.  Try removing the 'abstract' keyword. You can add the 'abstract' keyword before the class declaration.`

![image](https://user-images.githubusercontent.com/351125/116929346-aca98600-ac34-11eb-9a40-1aecd0700430.png)

How do I solve my issue? Well, I just need remove the abstract keyword, which is already highlighted and there is even a red lamp.

However... can't the IDE suggest this (i.e. let the IDE remove it)? It should be a veeery small implementation to make this possible, but would help a lot of people.

Suggestion 2:

```dart
abstract class MyClass {

abstract void method() {};

}
```

instead of just removing the "abstract", it could infer from the empty {} that the user wants a ; (since it is common in this scenario, when coming from other languages). Therefore, it could remove the abstract and add a ;.

**Comment by stevemessick** [comment]
This is something that would be handled by the Dart plugin, not Flutter. You can make a request at https://youtrack.jetbrains.com.
