### ISSUE TITLE
The project template in flutter_tools is no longer creating an Android module

### ISSUE THREAD

**Issue by anburocky3** [flutter/flutter-intellij#5464]
Emulator not opening inside the windows toolbar.

## Steps to Reproduce
1. I turned on "Launch in a tool window" in settings `Tools/Emulator`
2. Started the emulator using AVD window.
3. Instead of opening the emulator inside the toolbar(right toolbar), it is opening independently.

## Version info
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.928], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)

• No issues found!

S:\project-name>flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.928], locale en-IN)
    • Flutter version 2.0.3 at S:\flutter
    • Framework revision 4d7946a68d (7 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Anbu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Anbu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!

**Comment by anburocky3** [comment]
While in Flutter Project: "Launch in a tool window" doesn't work and no emulator menu is showing in the right bar.

**Comment by stevemessick** [comment]
Does it work if you use the menu `View > Tool Windows > Emulator` then launch the emulator from the AVD Manager?

**Comment by anburocky3** [comment]
I have enabled it here:
![image](https://user-images.githubusercontent.com/15264938/117352071-24451280-aecc-11eb-98a0-4aa07be2c405.png)

And I don't find the options when clicking `View`
![image](https://user-images.githubusercontent.com/15264938/117352148-3f178700-aecc-11eb-9f53-ac35dd2e48e3.png)

**Comment by anburocky3** [comment]
Any update from the team?

**Comment by saturov** [comment]
Same issue. Everything worked previously, but a few days ago this problem appeared.

**Comment by stevemessick** [comment]
Something has changed in the project template used by the `flutter` tool to generate projects.

It appears possible to work around the problem, but it might be risky so proceed with caution.
The steps. are:
- Open the Project Structure dialog (`File > Project Structure`).
- Select `Modules` in the list.
- Click the `+` to add a new module of type `Android`.

<img width="600" alt="Screen Shot 2021-05-10 at 8 28 39 AM" src="https://user-images.githubusercontent.com/8518285/117684723-1ca29980-b16a-11eb-82ad-8729293dc44b.png">

(This view is from a Mac. The `+` may be located elsewhere for Windows. If you have the `Dependencies` tab selected then it will also have a `+` and that one is not what you want.)

You don't need to change the defaults. Click `OK`, and you should see the `Emulator` tab appear in the right tool window bar.

**Comment by anburocky3** [comment]
> Something has changed in the project template used by the `flutter` tool to generate projects.
> 
> It appears possible to work around the problem, but it might be risky so proceed with caution.
> The steps. are:
> 
> * Open the Project Structure dialog (`File > Project Structure`).
> * Select `Modules` in the list.
> * Click the `+` to add a new module of type `Android`.
> 
> <img alt="Screen Shot 2021-05-10 at 8 28 39 AM" width="600" src="https://user-images.githubusercontent.com/8518285/117684723-1ca29980-b16a-11eb-82ad-8729293dc44b.png">
> 
> (This view is from a Mac. The `+` may be located elsewhere for Windows. If you have the `Dependencies` tab selected then it will also have a `+` and that one is not what you want.)
> 
> You don't need to change the defaults. Click `OK`, and you should see the `Emulator` tab appear in the right tool window bar.

I can confirm, it works in a hacky way!

**Comment by stevemessick** [comment]
The template files need to be updated. We didn't get to this for the M61 release so moving to M62, since it involves changing the Flutter SDK.

**Comment by salmankhilji** [comment]
This issue is fixed by upgrading to Bumblebee.
