### ISSUE TITLE
W/ResourceType(3712):Bad XML block : header size 28257 or total size 1936025193 is larger than data size 486

### ISSUE THREAD

**Issue by wangzp-sccba** [flutter/flutter-intellij#5485]
When I tried to run the newly pulled flutter code, I got an error   W/ResourceType(3712):Bad XML block : header size 28257 or total size 1936025193 is larger than data size 486
error: resource androidManifest.xml  is corrupt....
please give me some help ,thanks!

## Version info

flutter version 2.0.1
dart version 2.12.0
android sdk  29.0.3
android studio 3.6

no issues found

**Comment by stevemessick** [comment]
Android Studio 3.6 is not supported. Please update to 4.1 and try again. If you continue to have problems please add the output of `flutter doctor --verbose` here, and include a screen shot of the error, or copy and paste the stack trace.
