### ISSUE TITLE
We wish for a way to easily wrap a set of widgets in a new parent widget

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#549]
We are watching UX engineers learn Flutter. They have a large build() method, and now we need to wrap a column in a Flexible. We don't have an easy way to ask our tools "wrap this widget in a new widget".

We'd like to do something like highlight a widget (and all of its deep indentation with its children) and then say "wrap in a new parent widget". When that's done, the indentations are correct, the trailing commas are correct, and the choice of child or children attribute is correct.

Right now, it's a pain to manually do this :(

Thanks!

**Comment by sethladd** [comment]
Hopefully, this is done in the analysis server so any editor can offer this refactor. Should I move this to Dart SDK?

**Comment by sethladd** [comment]
cc @lukechurch @johnmccutchan

**Comment by sethladd** [comment]
I think @HansMuller asked for this at one point, too?

**Comment by devoncarew** [comment]
Adding @danrubel as well.

**Comment by HansMuller** [comment]
This is feature is among my editor wishes: https://github.com/flutter/flutter/issues/2016; which now appears to be https://github.com/flutter/flutter-intellij/issues/443

**Comment by pq** [comment]
@scheglov and I were chatting about this just yesterday.  Support definitely belongs in DAS.

**Comment by pq** [comment]
@stevemessick : is this done with the new "wrap widget" assist?

**Comment by stevemessick** [comment]
@pq To a first approximation, yes. The UX isn't exactly what was requested so I'm wondering if there will be feedback on that.

**Comment by pq** [comment]
The only thing I might consider is some word-smithing.  I don't have suggestions but I did notice @eseidelGoogle hesitate before selecting it in his demo making me think it wasn't immediately obvious to him that he'd selected the right action.  (He may deny this though -- in which case please ignore!)

For reference, here's what we've got.

<img width="357" alt="screen shot 2017-03-09 at 1 55 07 pm" src="https://cloud.githubusercontent.com/assets/67586/23772509/0934ebfa-04d0-11e7-9e3c-66702c85e1b4.png">

cc @LarkAscending who may have input on more natural wording

To reiterate, what we've got is awesome.  Cheers! 👍

**Comment by eseidelGoogle** [comment]
I only use it some of the time (because it assumes child: and sometimes I want children:[widget]).  But it seems to work well and I plan to continue demoing it. :)

**Comment by stevemessick** [comment]
@eseidelGoogle I'm not sure how best to handle the child:/children: issue. I set the template up with linked-editing so you can quickly tab to the named parameter and add the "ren" but I know that's not optimal, and not too discoverable, either. Plus, I just added a surround-with-brackets function to IntelliJ, which will help with converting a single arg to a list. That's in the Dart plugin so it won't be available immediately.

**Comment by HansMuller** [comment]
What if there were two "Wrap new-expression ..." entries. Like
```
Make new-expression a new widget child
Make new-expression the first child of a new widget
```

**Comment by stevemessick** [comment]
I think the initial request has been satisfied, so time to close this out. We have some ideas for additional assists & quick fixes that will address the child/children issue.

**Comment by mit-mit** [comment]
We have a new 'make child children' assist, so now you can chain these to get this:
![assists](https://cloud.githubusercontent.com/assets/13644170/24541386/7aa9b350-15f7-11e7-8c65-95a39046e32c.gif)
