### ISSUE TITLE
pub get failed (1; So, because xxx depends on flutter_test any from sdk, version solving failed.)

### ISSUE THREAD

**Issue by codex-pro** [flutter/flutter-intellij#5493]
![Screenshot 2021-05-19 at 7 23 35 PM](https://user-images.githubusercontent.com/51110842/118824744-b808dc80-b8d7-11eb-90dd-1336c2be1e0d.png)
![Screenshot 2021-05-19 at 7 24 09 PM](https://user-images.githubusercontent.com/51110842/118824838-cc4cd980-b8d7-11eb-9618-957077b76b54.png)
after upgrading Async i m. getting more error 
code was working in master channel but when i changed channel it is not working in any channel

**Comment by stevemessick** [comment]
It looks like you cannot use Flutter 2.2 yet, because `fstore` has not been updated. Since `fstore` is not available on `pub.dev` I don't think we can help. You might try `flutter pub upgrade` to see if resetting all version info helps.
