### ISSUE TITLE
Allow for the creation of multiple Flutter SDKs

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#55]
Before long we'll want to allow users to move between multiple SDKs (possibly allowing for per-project configuration a la the conversation in #54).  To facilitate this, we should support SDK configuration like the Java tooling does.

For example, where for Java we might see:

<img width="329" alt="screen shot 2016-08-23 at 10 05 29 am" src="https://cloud.githubusercontent.com/assets/67586/17901648/2902cc7a-6919-11e6-9323-e56e4aa27596.png">

we could imagine something similar for Flutter like:

<img width="332" alt="screen shot 2016-08-23 at 10 02 48 am" src="https://cloud.githubusercontent.com/assets/67586/17901678/4ef4110a-6919-11e6-9678-477c7c559fc5.png">

**Comment by pq** [comment]
This issue is well understood.  Closing in favor of opening more targeted tracking issues down the line.

**Comment by alexander-doroshko** [comment]
It depends on Dart SDK per module support that is not yet done. It's in my list for 2017.1. Tracked as https://youtrack.jetbrains.com/issue/WEB-20870
