### ISSUE TITLE
Completions on named arguments should include trailing comma

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#551]
*Repro steps*:

1. Create a new Flutter project in IJ
1. In `main.dart` place the cursor at the end of line 77 (` title: new Text(config.title),`)
1. Press Enter to add a new line
1. Type `back` and then Enter to select the `backgroundColor` completion

*Expected result*: 
  - Editor completes to `backgroundColor: ,` and the caret is placed just before `,`
  - The completed line is properly indented

*Actual result*: 
  - Editor adds just `backgroundColor:` resulting in the completed code triggering an analyzer error
  - Line is not properly indented

**Comment by mit-mit** [comment]
I speculate this was not done before as the last named argument was not allowed to have a terminating comma, but now that this is allowed I think this would be very valuable.

**Comment by devoncarew** [comment]
A thought (from @mit-mit): what if we always insert trailing commas for methods w/ named params w/ two or more args?

**Comment by pq** [comment]
WIP: https://github.com/JetBrains/intellij-plugins/pull/520

**Comment by alexander-doroshko** [comment]
> Actual result: Line is not properly indented

This seems to be already fixed, can you please double check?

> Actual result: Editor adds just `backgroundColor: ` resulting in the completed code triggering an analyzer error

With auto-inserted comma or without it analyzer is giving an error `identifier expected` which absolutely expected in this case and it disappears as soon as you type in the arg value, regardless of the comma presence.

> Expected result: Editor completes to `backgroundColor: ,` and the caret is placed just before `,`

Phil's PR is almost ready, but before finishing it up and landing I'd like to understand the rationale behind this feature. Sorry, I failed to guess what becomes better with this feature :).

**Comment by pq** [comment]
I'll take a quick stab but hopefully @mit-mit will chime in.

A compelling benefit in ensuring trailing commas for Flutter is in how they trigger the formatter.  The formatter is trained to handle trailing commas in such a way that makes formatted constructor invocations that include lots of nested args look like idiomatic Flutter if there are trailing commas.  For example, compare with trailing commas,

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```
to without:

```
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        title: 'Flutter Demo',
        theme: new ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: new MyHomePage(title: 'Flutter Demo Home Page'));
  }
```

The nested structure is clearer in the first.

**Comment by pq** [comment]
OK, great.  We agree!  

I also think this would better implemented on the server side. 👍  I talked myself out of it since I thought we might want a preference and that lead to me thinking it would all be easier on the client side.  But anyway, I agree, so I'll go back to that approach since it has a bunch of other advantages.

As for your experience, I'm curious what version of the SDK you have.  I'm on `1.23.0-dev.11.7` and not seeing the trailing commas:

<img width="623" alt="screen shot 2017-04-26 at 6 54 30 am" src="https://cloud.githubusercontent.com/assets/67586/25438116/5021d030-2a4d-11e7-8c8c-aefcc38cd429.png">

**Comment by alexander-doroshko** [comment]
tried the freshest sdk and brand-new project
```
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 21f57a85e8 (14 hours ago) • 2017-04-25 17:40:28 -0700
Engine • revision a5b64899c9 
Tools • Dart 1.23.0-dev.11.11
```
![image](https://cloud.githubusercontent.com/assets/4499789/25439709/d7f2142c-2aa5-11e7-9481-9bbbebd20f1b.png)

**Comment by alexander-doroshko** [comment]
however, even the old Dart SDK 1.19 does the same

**Comment by mit-mit** [comment]
The behavior appears to differ depending on whether you complete on "nothing" (ctrl-space) or on an actual completion such as 'b' in Phil's screenshot?

**Comment by alexander-doroshko** [comment]
>  I thought we might want a preference ... easier on the client side

We may want a preference and may implement all on the client side. But we should agree with server first. What I think we definitely wouldn't like to have is to have trailing commas in some cases coming from the server, in other cases - added by client.

> The behavior appears to differ depending on whether you complete on "nothing" (ctrl-space) or on an actual completion such as 'b'

Wow, indeed! Not sure what rationale is behind.

**Comment by pq** [comment]
> What I think we definitely wouldn't like to have is to have trailing commas in some cases coming from the server, in other cases - added by client.

👍  I'll look into this as I move towards implementing this support on the server side.

**Comment by pq** [comment]
WIP (https://codereview.chromium.org/2839273002/):

![key_arg_compl](https://cloud.githubusercontent.com/assets/67586/25505434/7d146fda-2b56-11e7-813c-c325eaa53ced.gif)

**Comment by pq** [comment]
Implemented w/ https://github.com/dart-lang/sdk/commit/bfc071e515808221f924623dd35fdc14040e1e39.

**Comment by mit-mit** [comment]
@pq when will we see this in the product?

**Comment by pq** [comment]
The next push of the flutter SDK.
