### ISSUE TITLE
Embedding DevTools show notifications confirm every time after reboot on macOS

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#5512]
![image](https://user-images.githubusercontent.com/15884415/119426970-c83c1400-bd3c-11eb-8df1-9136c18c0b0a.png)

(These words means the user need to confirm whether allow notifications from the Chromium process.)

## Steps to Reproduce

They'll display every time after a reboot.

## Version info

[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)

IntelliJ Plugin Version: 56.0.5

**Comment by jacob314** [comment]
Fyi @helin24 can we stop showing notifications from JxBrowser? I don't believe DevTools should be showing any notifications.

**Comment by helin24** [comment]
@jacob314 I asked JxBrowser about this in the past, but this is a Chromium notification that they can't disable either.

I'm surprised that this is coming up after every reboot, though (this is not something I can reproduce). I wonder if this means JxBrowser is getting downloaded multiple times somehow? @AlexV525 if you're able to send me your logs (Help > Show log in explorer), I can check if something odd is happening during installation.

**Comment by AlexV525** [comment]
Basically, the chromium executable seems disappeared from the notification center after every reboot.

[idea.log](https://github.com/flutter/flutter-intellij/files/6543904/idea.log)

| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/15884415/119604155-2e9a6280-be21-11eb-8748-7f81bb773548.png) | ![image](https://user-images.githubusercontent.com/15884415/119604148-2c380880-be21-11eb-8010-09538acaf3ff.png) |

**Comment by helin24** [comment]
@AlexV525 I spoke too soon, actually I am able to reproduce this myself on 2021.1. I'm going to try out a few things on my computer and also contacting JxBrowser to see if they have suggestions.

**Comment by AlexV525** [comment]
Any progress with this one?

**Comment by helin24** [comment]
@AlexV525 I just made a change that should shut off these notifications. It should be part of the dev release of the plugin this weekend, but you'll have to follow the instructions to set up that channel [here](https://github.com/flutter/flutter-intellij/wiki/Dev-Channel)
