### ISSUE TITLE
Saving read-only files throws an exception

### ISSUE THREAD

**Issue by alfhad** [flutter/flutter-intellij#5518]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.  ---  ## What happened  (please describe what you were doing when this exception occurred)  ## Version information  IntelliJ IDEA `2021.1.1` • Flutter plugin `io.flutter 56.0.5` • Dart plugin `211.7233`  Error getting Flutter sdk information.  ## Exception  null  ``` com.intellij.openapi.editor.ReadOnlyModificationException: Attempt to modify read-only document: guardClass=com.jetbrains.rdserver.permissions.impl.BackendDocumentWriteAccessGuard, failureReason=There is no project for client (ClientId(value=944DB0E86027B1B5710464242A901F75CE6D7614075FEB1BD087920F0376228B-1622016611954)). 	at com.intellij.openapi.editor.impl.DocumentImpl.assertWriteAccess(DocumentImpl.java:704) 	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:605) 	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:597) 	at io.flutter.editor.FlutterSaveActionsManager$3.run(FlutterSaveActionsManager.java:188) 	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:322) 	at com.intellij.openapi.application.RunResult.run(RunResult.java:36) 	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$1(WriteCommandAction.java:266) 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:959) 	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:265) 	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$3(WriteCommandAction.java:295) 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216) 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:182) 	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:297) 	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:265) 	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:246) 	at io.flutter.editor.FlutterSaveActionsManager.lambda$performFormat$1(FlutterSaveActionsManager.java:202) 	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218) 	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21) 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200) 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781) 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319) 	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135) 	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt) 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81) 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133) 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46) 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189) 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 	at java.base/java.security.AccessController.doPrivileged(Native Method) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969) 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839) 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449) 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808) 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448) 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781) 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496) 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ```

**Comment by jacob314** [comment]
Looks like we just need to not throw a user visible exception when a user saves a read only document although I may be misinterpreting the issue.

**Comment by stevemessick** [comment]
I think this was fixed in #5624. We'll have a new version of the plugin available in August that includes the patch.
