### ISSUE TITLE
Would like different restart behavior in Flutter Plugin

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter-intellij#5521]
recently we've noticed several `flutter daemon` crashes that look like repeated failures due to running out of file handles. Because the plugin will restart the daemon in a loop, this has been hammering our crash reporting backend, and likely not providing the user with any actionable feedback or surfacing the crash reports from the tool.

c.f. https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/run/daemon/DeviceDaemon.java#L51

The behavior that I would like is either for a prompt before a restart or at least some variety of backoff. We'd also like to display some notification to the user that the tool has crashed.

If need be the tool could surface the crash report information in a more structured format.

**Comment by stevemessick** [comment]
@jonahwilliams When you say "running out of file handles", do you mean globally, and a reboot is required? Or do you mean the daemon ran out of file handles? I'm trying to write a recovery suggestion to display to the user after repeated crashes.

**Comment by jonahwilliams** [comment]
globally. A reboot isn't necessarily required and may not help, depending on what sorts of other programs a user is running. For example, running `flutter test` in the flutter framework repo will exhaust the file descriptors on macOS if the user has not configured a higher limit. In that case, the advice would probably be something like https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard

**Comment by stevemessick** [comment]
Thanks!
