### ISSUE TITLE
Flutter inspector not jump to source

### ISSUE THREAD

**Issue by araafat3** [flutter/flutter-intellij#5523]
Flutter inspector not jump to source code

## Version info
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.1 at /media/ahmed/New Volume/flutter_linux_2.0.3-stable/flutter
    • Framework revision 02c026b03c (15 hours ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ahmed/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /media/ahmed/New Volume/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /media/ahmed/New Volume/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /media/ahmed/New Volume/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by stevemessick** [comment]
Fixed in #5486, available June 1.

**Comment by araafat3** [comment]
@stevemessick 
so what i need to get fix ?
update android studio or what
and if it is only update android studio which version i should have to get fix

**Comment by SyedUsmanAkhlaq** [comment]
Any fix for this?
