### ISSUE TITLE
"Usage of a variable" not able to filter the "Show write access" option. 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#5533]
### Minimal reproducible code:

```dart
String foo;

void main() {
  foo = 'foo';
  print(foo);
}
```

![Screen Shot 2021-05-30 at 1 17 23 PM](https://user-images.githubusercontent.com/40364434/120102103-c497fb00-c149-11eb-8358-7eb0e9c16c56.png)

In the yellow box I chose "Show write access" (yellow colored icon) but it doesn't filter the write operations. The `Usage of foo` window should only show the line # 33. 

### Flutter doctor:

```
[✓] Flutter (Channel dev, 2.3.0-12.1.pre, on macOS 11.2.3)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

```

**Comment by stevemessick** [comment]
This is done by the Dart plugin. If @alexander-doroshko sees this he might create an issue for you. Or you can create it at https://youtrack.jetbrains.com.

**Comment by dark-chocolate** [comment]
Created an issue at

https://youtrack.jetbrains.com/issue/IDEA-270621
