### ISSUE TITLE
Android Studio 4.2.1 Device Explorer missing again

### ISSUE THREAD

**Issue by tremp-m** [flutter/flutter-intellij#5549]
Hi
I think the problem is related to the plugin, but if I'm wrong, please direct me.
## Steps to Reproduce

Update Android Studio to 4.2.1 version. After that when i make new project 'Flutter Demo', there is no Device Explorer. I tried on win 10 and MacOS 10.15.7 - no matter. What could be the problem?

## Version info

/Users/oleg/developer/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H1217 darwin-x64, locale ru-RU)
    • Flutter version 2.0.4 at /Users/oleg/developer/flutter
    • Framework revision b1395592de (9 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/oleg/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/oleg/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.77

• No issues found!

**Comment by stevemessick** [comment]
Dup of #4994
