### ISSUE TITLE
Flutter plugin version 57.0.5 swallows errors in test code

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#5552]
This is a regression (maybe). Please see: #4952 and https://github.com/flutter/flutter-intellij/issues/5421

I have an error that happens **in a test**, but inside of a package (in this case, in https://pub.dev/packages/fast_immutable_collections).

I can't see the line, I just get the file:

```
package:fast_immutable_collections/src/ilist/ilist.dart  IList.contains
package:business/canais/canais_STATE.dart 25:51          new CanaisState
test\canais\canais_STATE_SIMPLE_test.dart 42:31          main.<fn>
```

You are not giving me the part of the stacktrace that's inside another package (when the error crosses package boundaries). Also, when I use third-party packages I can't know where certain problems happen, so it doesn't help me anymore to fix the problem, or even to allow me to help the package author to solve it. 

Am I filling this issue in the right place? Maybe this time I am not, because now even if I print the stacktrace myself I get no more info:

```
#0      IList.contains (package:fast_immutable_collections/src/ilist/ilist.dart)
#1      new CanaisState (package:business/canais/canais_STATE.dart:25:51)
#2      main.<anonymous closure> (file:///C:/Users/.../business/test/canais/canais_STATE_SIMPLE_test.dart:42:31)
#3      Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:200:19)
<asynchronous suspension>
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>
```

Could you please check if the problem is in flutter-intellij, or if it's not direct me to the appropriate repo to post this, please?

**Comment by helin24** [comment]
@stevemessick it looks like the last related change was #5443, but since there isn't additional info in the printed stacktrace, maybe this is something flutter controls?

**Comment by marcglasberg** [comment]
@stevemessick Yes, exactly.
