### ISSUE TITLE
With the latest Flutter plugin I don't the DevTools based inspector

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#5557]
<img width="1020" alt="Screen Shot 2021-06-08 at 8 52 10 PM" src="https://user-images.githubusercontent.com/1226812/121290480-88783f00-c89b-11eb-85de-2937a209765c.png">
I was expecting to automatically switch to the DevTools based inspector with the latest version of the Flutter IntelliJ plugin as I am a BigSur user.

Fyi @helin24

**Comment by helin24** [comment]
@jacob314 do you remember if you saw a notification about the embedded browser being turned on?

**Comment by helin24** [comment]
Looking at my change now (https://github.com/flutter/flutter-intellij/pull/5490/files), I'm confused because it looks like maybe it's NOT setting the embedded browser field?? I'll test it out again.
