### ISSUE TITLE
Possible flutter plugin crash

### ISSUE THREAD

**Issue by the-ginger-geek** [flutter/flutter-intellij#5558]
Not sure if there is already an issue for this, I couldn't find one.

I can recreate the bug when running commands in this order, in the IDE terminal, sometimes it happens when only running the `build_runner` command. The exact same thing happens on VS Code when following the below steps.

## Steps to reproduce
1. run `flutter pub run build_runner build --delete-conflicting-outputs`
2. run `flutter clean`
3. run `flutter pub get`

https://user-images.githubusercontent.com/2182638/121373356-486a9800-c93f-11eb-8fae-1b19f4883fae.mov

## Version info

flutter doctor -v
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/mukuru/development/flutter
    • Framework revision 02c026b03c (13 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mukuru/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • iPhone 12 (mobile) • 72346AAE-1AA5-4496-AE43-77940685EB36 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.4 20F71 darwin-x64

• No issues found!

---

### IntelliJ version 

```
IntelliJ IDEA 2021.1.2 (Community Edition)
Build #IC-211.7442.40, built on June 1, 2021
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), com.xinkun.theme.md (1.7.12), Dart (211.7233), org.toml.lang (0.2.148.3911-211), io.flutter (57.0.5), Docker (211.7442.9), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45), pl.pszklarska.pubversionchecker (1.2.5), com.chrisrm.idea.MaterialThemeUI (6.6.0)
Kotlin: 211-1.5.10-release-891-IJ7142.45
```

**Comment by stevemessick** [comment]
@the-ginger-geek Do you have a sample project that will reproduce this issue? I have not been able to reproduce it.

**Comment by the-ginger-geek** [comment]
@stevemessick I'll have to set up a project similar to the one I'm using when I get some time, my source is fintech stuff so I can't really share this specific source code.

**Comment by the-ginger-geek** [comment]
@stevemessick I invited you to a another repo of mine that I could reproduce it on. I followed the same steps as listed above and experienced the same result.

**Comment by the-ginger-geek** [comment]
Something else I noticed, if the project is open in another IDE, IE VS Code the exact same thing happens to that instance. I have to close both IDEs and open them again to get them back to a working state.

**Comment by stevemessick** [comment]
@the-ginger-geek Thanks for the link. Yeah, I'm pretty sure this isn't a plugin issue, I'm just trying to figure out where to re-route it. It might be the Dart SDK or possibly the Flutter tool. So, having a repro case should help me determine where to move it to.

**Comment by the-ginger-geek** [comment]
Yes restarting the dart analysis server brings it back to life! I don't see the editor highlighting errors but it does appear in the console. If I subsequently run `pub get` then everything is working again.

**Comment by stevemessick** [comment]
Thanks for the additional info, @the-ginger-geek. This looks like an analyzer issue, so I'll move it to that repo.
