### ISSUE TITLE
Device selector disappears after project close and open

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#556]
Haven't tried to debug, but to repro:

1. open a project `foo`
2. close the project
3. open a project `bar`

No device selector.

I confirmed that the preference to see it is set:

<img width="855" alt="screen shot 2016-12-15 at 11 27 57 am" src="https://cloud.githubusercontent.com/assets/67586/21238973/eaca77d2-c2b9-11e6-9210-d3a9237f8041.png">

cc @devoncarew

**Comment by pq** [comment]
I then created another project and still no selector.

**Comment by devoncarew** [comment]
Yeah, likely a bug; let me look.

**Comment by pq** [comment]
So I think I have an idea what's happening here.  In `DeviceSelectorAction.update` we register a listener that updates state and are careful not to register it multiple times.   In this case though I think we need to re-register.  

As a quick test,

remove this check:

    if (!isListening) { 

and life is good again (albeit with gratuitous updates).

**Comment by pq** [comment]
One more thought is that it might be good for us to consolidate our project-scoped listeners in the `FlutterDaemonService` as it's doing some disposing based on project lifecycle.  Specifically, see the constructor where this registration happens:

    Disposer.register(project, this::stopControllers);
    Disposer.register(project, this::stopListeningForSdkChanges);

**Comment by devoncarew** [comment]
Cool, sounds like good cleanup.

**Comment by devoncarew** [comment]
OK, it looks like the action has a lifetime of the application, not the project.
