### ISSUE TITLE
Can't find plugin for Android Studio Bumblebee | 2021.1.1 Canary 2

### ISSUE THREAD

**Issue by Darkos-den** [flutter/flutter-intellij#5578]
## Steps to Reproduce

Open Android Studio plugin settings, find Flutter plugin. Plugin not found.

## Version info

Any version

**Comment by stevemessick** [comment]
It isn't supported yet.

See #5575, which should make it available in the [dev channel](https://github.com/flutter/flutter-intellij/wiki/Dev-Channel) next week.

**Comment by HiPipilu** [comment]
Thanks!
