### ISSUE TITLE
[Clarification/Documentation] version comparison from repo and intellij?

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter-intellij#5582]
tl&dr: how does one know what version will include a merged PR?

I currently have an issue with the exceptions, and I found a PR that fixed it: https://github.com/flutter/flutter-intellij/pull/5443/files#
I can see it was merged on `28 Apr`, but how do I know which is the latest version since that? I see some tags about versions such as "23.0", but I believe it's a bit outdated since there were newer releases since then (2month difference), and evne if so I don't know how to match the version between "23.0" and "57.0" for example.

p.s.
Specifically in this case a member mentioned the released version, but I'm looking for a generic solution, rather than keep asking members for this info.

**Comment by stevemessick** [comment]
We use monthly milestones for planning, as described in the [wiki](https://github.com/flutter/flutter-intellij/wiki/Milestones). Everything that is merged prior to beginning the release process will be included in the next release. Generally, all work from one month is available at the beginning of the next month, although something that was merged after the build started might not be included.

In this case #5443 addresses a problem different than the one you reported in #5583

**Comment by stevemessick** [comment]
Also, the plugin includes a change log that lists all the PRs included in the build. You can see it by opening Settings > Plugins and selecting the Flutter plugin.
