### ISSUE TITLE
Flutter inspector using embedded DevTools is resized and moved (linux)

### ISSUE THREAD

**Issue by fmmarzoa** [flutter/flutter-intellij#5584]
So this is happening to me in Ubuntu right now when trying to use the Flutter Inspector with a sample app in a Pixel emulator. You'll see the inspector with its layout explorer gets in the middle of the window instead of its intended place at the top right under the tab:

![Screenshot from 2021-06-16 22-19-52](https://user-images.githubusercontent.com/6368385/122287241-03bb9f80-cef1-11eb-84d7-f444aea179f1.png)

The view mode in the gear is at its default "Dock pinned".

Android Studio 4.2
Build #AI-202.7660.26.42.7322048, built on April 29, 2021
Runtime version: 11.0.8+0-b944-P17168821 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 5.8.0-56-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.thoughtworks.gauge, Dart, org.jetbrains.kotlin, io.flutter, org.intellij.plugins.markdown
Current Desktop: ubuntu:GNOME

Emulator info:

Name: Pixel_3a_API_30
CPU/ABI: Google Play Intel Atom (x86)
Path: /home/fran/.android/avd/Pixel_3a_API_30.avd
Target: google_apis_playstore [Google Play] (API level 30)
Skin: pixel_3a
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_3a
hw.lcd.width: 1080
hw.initialOrientation: Portrait
image.androidVersion.api: 30
tag.id: google_apis_playstore
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Pixel 3a API 30
hw.gpu.mode: auto
hw.ramSize: 1536
PlayStore.enabled: true
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 2220
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images/android-30/google_apis_playstore/x86/
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: Pixel_3a_API_30
hw.lcd.density: 440
hw.arc: false
hw.device.hash2: MD5:0e6953ebf01bdc6b33a2f54746629c50
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google Play
runtime.network.latency: none
disk.dataPartition.size: 6442450944
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

OS info:

```
$ neofetch 
            .-/+oossssoo+/-.               fran@oso 
        `:+ssssssssssssssssss+:`           -------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: MACHC-WAX9 M1150 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.8.0-56-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 day, 52 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2450 (dpkg), 21 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 3000x2000 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Prof-Gnome-Dark-3.6 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Prof-Gnome-Dark-3.6 [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: kora [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-10510U (8) @ 4.900GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel UHD Graphics 
      -+sssssssssssssssssyyyssss+-         GPU: NVIDIA GeForce MX250 
        `:+ssssssssssssssssss+:`           Memory: 7765MiB / 15755MiB 
            .-/+oossssoo+/-.
```

Flutter doctor output:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.2)
[✓] Android Studio (version 4.1)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by helin24** [comment]
@fmmarzoa could you follow these steps to send us verbose logs?
1. Enable verbose logging (Preferences > Languages & Frameworks > Flutter, under 'General')
2. Reproduce this issue
3. Find the logs in Help > Show log in finder (should be called `idea.log`)

**Comment by fmmarzoa** [comment]
Hey @helin24,

Find the requested log attached.

BTW, I found out it happens also when using an actual Android device connected to my laptop, so the device seems not to be relevant.

Kind Regards,
Fran

[idea.zip](https://github.com/flutter/flutter-intellij/files/6689667/idea.zip)

**Comment by helin24** [comment]
@fmmarzoa okay, it makes sense this would not be device-specific. However, I don't see anything about the flutter plugin or jxbrowser inside the log you attached and it seems to be from March instead of recently. I'm not sure how to fix that assuming you saw flutter functionality in the IDE and followed the logging instructions above. Perhaps restart your IDE and verify the logging setup, then make sure the `idea.log` file is receiving new logs?

**Comment by fmmarzoa** [comment]
Oops, maybe I picked the wrong log. I'll try again ASAP, I apologize for the confusion.

**Comment by fmmarzoa** [comment]
@helin24 find attached a log I just got a minute ago. I deleted all the previous idea.log files in my system first to make sure I got the right one this time, so I hope this time is right... :)

[idea.zip](https://github.com/flutter/flutter-intellij/files/6720199/idea.zip)

**Comment by helin24** [comment]
@fmmarzoa thanks! I see the logs we're expecting. I don't notice anything suspect from first glance, but I'm hoping that the JxBrowser team will have more insight about why this might be happening.

**Comment by helin24** [comment]
@fmmarzoa I made a change hoping to address this problem but I don't have a physical linux device to test. This change should be available in the dev version of our plugin if you want to try it out and let me know if you continue to have this problem: https://github.com/flutter/flutter-intellij/wiki/Dev-Channel

**Comment by fmmarzoa** [comment]
@helin24 Thanks! Sure, I'll be glad to give it a try ASAP. I'll keep you updated.

**Comment by fmmarzoa** [comment]
@helin24 just tried 59.0.1-dev.3 version following those instructions and I'm sorry to inform you that it did **not** solve the issue.

![Screenshot from 2021-07-20 19-50-10](https://user-images.githubusercontent.com/6368385/126371779-efea6010-fd0c-417d-a00b-f097d7670e51.png)

**Comment by helin24** [comment]
@fmmarzoa thanks for checking! Sorry to hear it didn't fix the problem; I'll keep investigating.
