### ISSUE TITLE
Support for per project Flutter SDKs.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#56]
A breakout from #54.

In an ideal world we should support per-project (or in IntelliJ vernacular _per-module_) SDKs.

**Comment by alexander-doroshko** [comment]
Tracked as https://youtrack.jetbrains.com/issue/WEB-20870, planned for 2017.1

**Comment by mit-mit** [comment]
> Tracked as https://youtrack.jetbrains.com/issue/WEB-20870, planned for 2017.1

Does that include the 'per-project sdk' approach, or the workaround with the combo boxes?

**Comment by alexander-doroshko** [comment]
Combo is already there in the Dart plugin, but changing SDK in one project affects all others.
So yes, that request is for true per-project sdk approach.

**Comment by sethladd** [comment]
Great to hear!

**Comment by pq** [comment]
Being tracked in https://youtrack.jetbrains.com/issue/WEB-20870.

**Comment by mit-mit** [comment]
Opened https://github.com/flutter/flutter-intellij/issues/822 to make sure we get the full end-to-end experience for this completed and verified when 2017.1 ships.
