### ISSUE TITLE
Flutter Inspector Stuck at Installing DevTools, won't display

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#5611]
## Steps to Reproduce

When I run a Flutter app in IntelliJ, with the "Open Flutter Inspector view on app launch" setting set to true (or if I just open it by clicking on the sidebar tab), it will put up a progress bar that says "Starting DevTools" for about 15-20 seconds, and then it will show the following:

![image](https://user-images.githubusercontent.com/8867023/124022012-1cbc5a00-d9a1-11eb-98ed-87133a05a1f2.png)

I've tried following those instructions multiple times, restarting IntelliJ and clearing caches, restarting my app, and uninstalling and reinstalling the Flutter and Dart plugins (restarting in between), and it still won't start the inspector.

When I run with verbose output, it does print the following once the app starts:
```json
[{"event":"app.started","params":{"appId":"cf719a58-20d4-4b61-b0bb-ed39d4cfd839"}}]
Activating Dart DevTools...
[{"event":"app.progress","params":{"appId":"cf719a58-20d4-4b61-b0bb-ed39d4cfd839","id":"2","progressId":null,"message":"Activating Dart DevTools...","finished":false}}]
[{"event":"app.progress","params":{"appId":"cf719a58-20d4-4b61-b0bb-ed39d4cfd839","id":"2","progressId":null,"finished":true}}]
[{"id":0,"result":{"value":"linux","type":"_extensionType","method":"ext.flutter.platformOverride"}}]
[{"id":1,"result":{"timeDilation":"1.0","type":"_extensionType","method":"ext.flutter.timeDilation"}}]
[{"id":2,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaint"}}]
[{"id":3,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaintBaselinesEnabled"}}]
[{"id":4,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.repaintRainbow"}}]
[{"id":5,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.showPerformanceOverlay"}}]
[{"id":6,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.debugAllowBanner"}}]
[{"id":7,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":8,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.show"}}]
[{"id":9,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":10,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
[{"id":11,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":12,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":13,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
```

## Version info

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.576, on Debian GNU/Linux rodete 5.10.28-1rodete2-amd64, locale en_US.UTF-8)
    • Flutter version 2.3.0-17.0.pre.576 at /home/gspencer/code/flutter
    • Upstream repository git@github.com:gspencergoog/flutter.git
    • Framework revision 1c92e84865 (20 hours ago), 2021-06-29 16:21:02 -0700
    • Engine revision aa939d4cf9
    • Dart version 2.14.0 (build 2.14.0-256.0.dev)

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /opt/idea-IC-202.7660.26
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7665

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 5.10.28-1rodete2-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114
```

**Comment by helin24** [comment]
@gspencergoog are you able to open DevTools from the toolbar in the run/debug window? 

Can you also reproduce this issue and send us your logs (internally) from Help > Show log in finder?

**Comment by gspencergoog** [comment]
Clicking the DevTools button in the run/debug window does nothing.

Here's a [Drive link](https://drive.google.com/file/d/1NgboaLByQTpamT1Ev39lgim-AMsJImdj/view?usp=sharing&resourcekey=0-n9XH5RhEl0hWRmaKo843RA) to a tar file with my logs. You should have access.

**Comment by helin24** [comment]
@gspencergoog thanks for the logs! I see an error with parsing the results from the daemon API method `devtools.serve`. I wonder if you get similar results when you run the daemon on the command line? To try that, run these steps:
1. Run `flutter daemon` on the command line
2. Once you see `[{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]`, paste to stdin: `[{"id":1,"method":"devtools.serve"}]`
3. I expect to then see a stdout response that looks like `[{"id":1,"result":{"host":"127.0.0.1","port":9100}}]` - if you see this, then you should be able to open devtools in your browser at 127.0.0.1:9100.

If that works, then potentially we're starting the daemon incorrectly; if not, let me know what sort of output you're getting from the daemon.

**Comment by gspencergoog** [comment]
OK, so I tried what you suggested, and here's the output I received:

```json
[{"event":"daemon.connected","params":{"version":"0.6.1","pid":2508951}}]
[{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[{"id":1,"method":"devtools.serve"}]
[{"event":"daemon.logMessage","params":{"level":"status","message":"Activating Dart DevTools..."}}]
[{"id":1,"result":{"host":null,"port":null}}]
```

**Comment by gspencergoog** [comment]
I get the same output regardless of whether an app is currently running or not.

**Comment by gspencergoog** [comment]
I also tried killing any other `flutter daemon` instances and restarting, but got the same result.
