### ISSUE TITLE
flutter inspector widget tree

### ISSUE THREAD

**Issue by evanholt1** [flutter/flutter-intellij#5630]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
Run the application, and check the Flutter Inspector window on the right.
_Please tell us what you were doing and what went wrong_
I was writing code normally, then checked the Flutter Inspector window, and found it to be a Huge widget tree, unlike what i'm used to seeing. 
I researched this, and found an arguement for "flutter run" called "track-widget-creation", and tried in and it worked. when i use that arguement the widget tree is short and concise, consisting on the widgets i made.
I tried to run the app this way in android studio, but it just ignores the arugment completely.
I have restarted the pc, re-invalidated android studio's cache. yet this occures constantly and can't be fixed.
This error is veery bad for me as with such as long widget tree, it's really impossible for me to find a single widget i am looking for, breaking the purpose of 'flutter inspector'.

**_Widget tree when running the app with android studio:_**
![error1](https://user-images.githubusercontent.com/40251685/125276416-dbb93380-e318-11eb-809a-6c60aed2a7fc.png)

**_![error2](https://user-images.githubusercontent.com/40251685/125276484-f12e5d80-e318-11eb-9421-c3c939dc6d3e.png)_**

**_configuration in android studio:_**
![error3](https://user-images.githubusercontent.com/40251685/125276535-03100080-e319-11eb-868f-1f4190de70f2.png)

### (NOTE: i am using fvm to run 2.2.3 on this project)

[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.1083], locale en-US)
    • Flutter version 2.0.4 at C:\src\flutter
    • Framework revision b1395592de (3 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\adiga\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.58.0)
    • VS Code at C:\Users\adiga\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.67

**Comment by helin24** [comment]
@evanholt1 it seems that the native inspector does not respond to the flag for some reason. You can instead use the embedded DevTools inspector by going to Settings > Languages & Frameworks > Flutter > "Enable embedding devtools...", which by default should show the second image with the more condensed tree.

**Comment by evanholt1** [comment]
@helin24  
  Tried it, and it did work. 
  Although it is painfully laggy & slow compared to normal, but it did work at least, and now i have the condensed tree focused on my widgets.
  Thanks Alot!
