### ISSUE TITLE
[Feature Request] Separate flutter sdk per project

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter-intellij#5639]
## Steps to Reproduce

Currently it seems when changing the flutter sdk path, it is changed for all projects.

It would be great if I could override it on a specific project

## Use Case

The use case is when contributing to the flutter project it self.
When doing that, the flutter sdk path needs to be changed to the one installed on the windows
to the project one.

However, after changing it and opening a project of mine that is using the stable channel,
I need to go into settings and change the paths.

## Version info

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.2 at C:\Flutter\SDK
    • Framework revision d79295af24 (5 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.67

• No issues found!
```

**Comment by stevemessick** [comment]
We already have per-project SDKs. There must be something else going wrong. Can you give us more detailed steps to reproduce the problem?

**Comment by matanshukry** [comment]
@stevemessick you're right, I do see a "For current project" as well. Although I can't seem to find a way to change that so I can set the default value for new projects.

Regarding the steps, not really sure what caused it since it was working. but generally speaking:

1. I had a project I was working on, with path set to the stable path. `C:\Flutter\SDK`
2. at some point in time after that, I cloned the flutter repo and set it, and changed the path to it - so it was `C:\development\flutter`
3. some time after that, I cloned a new project and opened it. The path was then set to the flutter one `C:\development\flutter`

When cloning new projects and loading them for the time, the path seems to be the correct one - `C:\Flutter\SDK`

I also added few env variables such as `FLUTTER_ROOT` though, which wasn't set before - not sure if that changed anything or not.

Since it's now working from me we can close this issue, although it would be nice to know which env variables affect the path and which don't.

**Comment by stevemessick** [comment]
In the New Project Wizard, the default value for the Flutter SDK path is whatever was used the last time the wizard ran. It is saved in a settings file managed by the IDE. Is it possible that you didn't notice the value when you created the latest project? I also have two Flutter repos, and I seldom look at that field when I'm creating a project.

**Comment by matanshukry** [comment]
@stevemessick I don't think I ever used the new project wizard actually.
I always clone or start projects from the CLI (git bash), and then just open the project using IntelliJ.

**Comment by stevemessick** [comment]
I see. The SDK would be set by flutter_tool then, not the plugin.
