### ISSUE TITLE
Device detection not working (for iOS Simulator)

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#564]
With the latest, device detection seems to have issues.

Repro:

1. Open project
2. Open Simulator
3. Device detector doesn't see it...

<img width="631" alt="screen shot 2016-12-16 at 10 35 39 am" src="https://cloud.githubusercontent.com/assets/67586/21274168/a45d726e-c37b-11e6-84fa-f3185e578769.png">

@devoncarew

**Comment by devoncarew** [comment]
I'm unable to repro :(

Can you debug this locally? See if we're not getting the notification, see if there's some error propagation that to the device UI, ...

**Comment by pq** [comment]
Hmmm.  Looking!

**Comment by pq** [comment]
Consistently reproing here.  It looks like I'm not getting any device added or removed events.

I'm starting to suspect that it's coming from my Flutter build.  Re-syncing now...

**Comment by pq** [comment]
> I'm starting to suspect that it's coming from my Flutter build. Re-syncing now...

That fixed it. 👍 

Onward!
