### ISSUE TITLE
"Create Flutter Bug Report" button active even if bug reports are not supported

### ISSUE THREAD

**Issue by koral--** [flutter/flutter-intellij#5649]
It makes a little sense to provide ability to create bug reports if there are not supported.
Look here: https://github.com/flutter/flutter-intellij/issues/5648#issuecomment-882589390

Creating a bug report is a feature of this plugin: https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/FlutterErrorReportSubmitter.java#L50

So it should also check Android Studio version and don't offer "Create Flutter Bug Report" on Canary.

## Steps to Reproduce

Trigger any unhandled exception eg. like here: https://github.com/flutter/flutter-intellij/issues/5648

## Version information

Android Studio `Bumblebee | 2021.1.1 Canary 3` • Flutter plugin `io.flutter 58.0.3` • Dart plugin `211.7727`

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by stevemessick** [comment]
This is not something we will do, because normally we do have some level of support for canary. However, it isn't working right now. When we do get it working, if this suggestion was implemented, we'd have to remember to undo it.

**Comment by koral--** [comment]
I don't get it. Could you elaborate what is worth reporting and what isn't?
