### ISSUE TITLE
Clarify what is and what isn't supported in terms of AS Canary

### ISSUE THREAD

**Issue by koral--** [flutter/flutter-intellij#5655]
My recent issues related to AS Canary: https://github.com/flutter/flutter-intellij/issues/5653 and https://github.com/flutter/flutter-intellij/issues/5652 and https://github.com/flutter/flutter-intellij/issues/5648 were closed.

However, here: https://github.com/flutter/flutter-intellij/issues/5649#issuecomment-882852715 @stevemessick said:
> we do have some level of support for canary

Is there some explanation what is and what isn't supported in terms of Canary? What is worth reporting and what isn't? To avoid such ping pongs.

**Comment by stevemessick** [comment]
That quote is taken out of context. The correct quote is:
>This is not something we will do, because normally we do have some level of support for canary. However, it isn't working right now.

It is clear from the full quote that we do not currently support canary, and that we do intend to do so. It should also be clear that canary is not supported from my comment on #5649, which I repeat here:
>Android Studio canary version is not currently supported.

Continuing to file issues on this topic is not productive.
