### ISSUE TITLE
Creating a new project with an incorrect organization name should be prevented

### ISSUE THREAD

**Issue by g123k** [flutter/flutter-intellij#5674]
## Steps to Reproduce

1. Open IntelliJ and create a new project
2. In the Organization field, type something simple, with just one part:

<img width="802" alt="Screen Shot 2021-07-26 at 11 11 05" src="https://user-images.githubusercontent.com/246838/126964749-a2bfaccb-7487-48c8-bbaf-8b139d95995d.png">

It is considered as correct by IntelliJ.
3. Click on the Finish button
4. The project folder will be created, but the process will fail with this error:

<img width="410" alt="Screen Shot 2021-07-26 at 11 11 51" src="https://user-images.githubusercontent.com/246838/126964859-6f299fe5-9d82-45ee-95fa-a6e65ae9c016.png">

I think a fix here would be to prevent an organization not containing any '.' character

**Comment by stevemessick** [comment]
Related: #5272

**Comment by stevemessick** [comment]
Unfortunately, this validation is only done after the OK button has been clicked. The best we can do is to delete the new directory when the message is displayed.
