### ISSUE TITLE
Plugin 'Dart' and Plugin 'Flutter' is not compatible with the latest version of Android Studio Arctic Fox. Windows

### ISSUE THREAD

**Issue by HaardikBhagtani** [flutter/flutter-intellij#5682]
## Steps to Reproduce

Plugin 'Dart' (version 'null') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is AI-203.7717.56
	Plugin 'Flutter' (version '58.0.1') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is AI-203.7717.56

![dart](https://user-images.githubusercontent.com/72184541/127540087-99228ea9-5bf0-4d38-80a5-d50de78e8c3c.png)

![flutter](https://user-images.githubusercontent.com/72184541/127540122-1905aa48-6ead-4bfd-9818-ac56ccad8c9b.png)

## Version info
flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-IN)
    • Flutter version 2.2.3 at C:\Users\Haardik\Documents\flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Haardik\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at D:\Android
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\Android
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Haardik\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 9
2.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge
92.0.902.55

• No issues found!

**Comment by ling9400** [comment]
why closed? how to fix this?

**Comment by HaardikBhagtani** [comment]
> why closed? how to fix this?

It was solved.
Un-install dart and flutter plugin, then restart pc and android studio. 
After then re-install plugins, it should work now.
