### ISSUE TITLE
Windows 10 controlled folder access does not let Flutter build the APK

### ISSUE THREAD

**Issue by alexmro** [flutter/flutter-intellij#5689]
## Steps to Reproduce

In Windows 10 with controlled folder access try to build the APK (_Build > Flutter > APK_). The building task will fail with the following output:

```
Running Gradle task 'assembleRelease'...                        
Error: Unable to write snapshot file

Dart snapshot generator failed with exit code 255
Error: Unable to write snapshot file

Dart snapshot generator failed with exit code 255
Error: Unable to write snapshot file

Dart snapshot generator failed with exit code 255


FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\user\AppData\Roaming\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1052

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Users\user\AppData\Roaming\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Running Gradle task 'assembleRelease'...                           51,2s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
```

If I disable the annoying controlled access folder from the security settings it works. What I notice is that after failing, the menu option to build the APK (_Build > Flutter_) is no longer there. I only see a _Recompile_ menu item which is greyed out so I have to restart the IDE before building again.

## Version info

[✓] Flutter (Channel dev, 2.4.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.1052], locale ro-RO)
    • Flutter version 2.4.0-4.0.pre at C:\Users\user\AppData\Roaming\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (3 weeks ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • Windows (desktop)       • windows            • windows-x64     • Microsoft Windows [Version 10.0.19042.1052]
    • Windows (UWP) (desktop) • winuwp             • windows-uwp-x64 •
    • Chrome (web)            • chrome             • web-javascript  • Google Chrome 92.0.4515.107
    • Edge (web)              • edge               • web-javascript  • Microsoft Edge 92.0.902.62

**Comment by alexmro** [comment]
I would add the flutter executable to the exceptions list but it only allows EXE and COM files to be added. What is strange is that this does not happens when building and running in debug mode.

**Comment by stevemessick** [comment]
Can you build from the command line? If so, what command do you use?

I have a question about this:
> the menu option to build the APK (Build > Flutter) is no longer there

If you open the menu `File > Project Structure` and select Modules, what do you see?

**Comment by alexmro** [comment]
Interesting. After upgrading to version 2.5.0-1.0.pre, Windows started complaining about the actual executables that where blocked from accessing the Documents folder.

One is **font-subset.exe** from _build\app\intermediates\flutter\release\flutter_assets\fonts\_.
Another one is **get_snapshot.exe** from _\.dart_tool\flutter_build\b1a2a97062a38cb09caaecca62070638\{ARCHITECTURE}\_

Given the permission I suppose it should work now. Yet, I still cannot rebuild the APK unless I restart the IDE. What I see when I go to _Project Structure > Modules_ is this:

![modules](https://user-images.githubusercontent.com/74217337/128297166-531e579b-1532-4a14-93e2-a3a21052411f.jpg)

**Comment by stevemessick** [comment]
I think the Flutter tool has a problem, so I created an issue: https://github.com/flutter/flutter/issues/88192

When the Build menu disappears, do you have anything selected in the Project view? Another way of asking is, does the menu re-appear if you select a file in the Project view?

**Comment by alexmro** [comment]
> I think the Flutter tool has a problem, so I created an issue: [flutter/flutter#88192](https://github.com/flutter/flutter/issues/88192)
> 
> When the Build menu disappears, do you have anything selected in the Project view? Another way of asking is, does the menu re-appear if you select a file in the Project view?

Interesting, yes it does re-appear if I open a file from the Project view

**Comment by stevemessick** [comment]
Thanks for the update. See also https://github.com/flutter/flutter-intellij/issues/5712
