### ISSUE TITLE
 Frame-rendering-times is incorrectly on OnePlus machines

### ISSUE THREAD

**Issue by canluhuang** [flutter/flutter-intellij#5696]
I found a problem when using the frame-rendering-times on OnePlus machines.

![image](https://user-images.githubusercontent.com/7105187/128014441-dbc5e2fd-e650-4569-b653-ee8e0b03e8f2.png)

As shown in FIG, when I set the device's screen refresh rate to 90HZ,  the target cost per frame is 11ms. But in fact, due to the optimization strategy of the OnePlus system, the screen refresh rate on the Flutter application will be reduced to 60HZ, which will cause the frame rendering to be time-consuming and inaccurate. [flutter/flutter#35162](https://github.com/flutter/flutter/issues/35162)

I check the source code, the plugin get target cost per frame from [FlutterJNI#refreshRateFPS](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java) . The value set by Android Api `windowManager.getDefaultDisplay().getRefreshRate()`  when the engine is initialized. But, in OnePlus machines, this value will be changed when Flutter starts rendering.

I think it can be optimized by update the value after Flutter starts rendering to avoid this problem.

**Comment by stevemessick** [comment]
@kenzieschmoll I see you've done some work in this area. Could you take a look at this?

**Comment by kenzieschmoll** [comment]
From some offline discussion, sounds like we'll be removing this chart soon in favor of embedding the DevTools frames chart. @canluhuang can you check whether you see this same behavior with the DevTools performance page?

I do not have a OnePlus device to reproduce, but I suspect if we have someway to detect whether a device is a OnePlus device, we can clear the cached display refresh rate and request again at the time of the first flutter frame.

**Comment by canluhuang** [comment]
@kenzieschmoll 
Sorry for not responding in time. In fact, DevTools also has this problem: 
![image](https://user-images.githubusercontent.com/7105187/130230470-ca6b1216-e68d-4493-ac4a-2677400f640c.png)

The root cause of the problem lies in the order in which DevTools obtains the screen fps. Before Flutter starts rendering, the screen fps is 90, and it becomes 60 after starting to render.

**Comment by jacob314** [comment]
Thanks for investigating. I'm closing as the corresponding DevTools problem has an existing bug tracking it.
https://github.com/flutter/devtools/issues/3269
