### ISSUE TITLE
Flutter doctor on intellij doesn't recognize android sdk

### ISSUE THREAD

**Issue by 1hitOVER** [flutter/flutter-intellij#571]
Help me please!

intellij doesn't recognize the android sdk but from my terminal it does! why?
![instantanea7](https://cloud.githubusercontent.com/assets/15723713/21341836/34b0720a-c654-11e6-919e-6ec5b82b4e41.png)

**Comment by pq** [comment]
@danrubel : any thoughts?

**Comment by danrubel** [comment]
My guess is that the env var ANDROID_HOME is not set when IJ runs `flutter doctor`.

**Comment by devoncarew** [comment]
When we shell out, we may need to set up the PATH env variable.

@1hitOVER, how are you starting IntelliJ? From the command-line or from a launcher / dock app? And from the screen-shot, it looks like you're running on Linux?

**Comment by 1hitOVER** [comment]
@devoncarew  I'm starting Intellij from launcher (.desktop entry), I'm running Linux. I don't know what happen but  I reinstalled flutter and restart pc and now all works fine :)

**Comment by devoncarew** [comment]
Closing this, but will open a more specific bug about PATH detection.
