### ISSUE TITLE
Android Studio Arctic Fox (2021/03/01) autocomplete too slow with flutter

### ISSUE THREAD

**Issue by MohamedSlama** [flutter/flutter-intellij#5716]
Hello i'm facing a problem after updating `android studio to arctic fox`, Autocomplete is take about 10 second to display!!
Although it working fine with native java and kotlin and i don't have any issues with `flutter doctor`.

I have tried to delete cache and tried also deleting `flutter sdk` and `flutter && dart plugins` then re-install doesn't solve my problem.
I have also disabled `Add unambiguous imports on the fly` and `Optimize imports on the fly` from auto import
My Laptop is lenovo ideapad z500 / core i5 / 12 gb ram / 120 hyperx kingston ssd with ubuntu 20.04 stable.
Dart plugin is: `203.8292` and flutter plugin is: `59.0.2`.

**Comment by stevemessick** [comment]
Please paste the output of running `flutter doctor -v` from the command line. Also attach your `idea.log` file; you can find it from `Help > Show log in files` (or something similar).

The options you disabled only apply to Java. The is a Dart option on that page, but I don't think it will change anything for you.

Can you give us an estimate of how large or complex your project is?

**Comment by stevemessick** [comment]
Thanks. Can you do an experiment? Disable all optional plugins except Dart and Flutter, and restart. Does the problem still occur?

**Comment by jacob314** [comment]
Sorry to hear autocomplete is running so much slower. If you open a different Flutter application are you still able to repro the slowness?
`git clone https://github.com/flutter/gallery.git`
would be a good sample medium sized application to test.

**Comment by MohamedSlama** [comment]
Thanks For replay i have already tested that and again i re-test but unfortunately the same issue i also downloaded premium `IntelliJ idea ultimate edition` i'm facing the same issue, i don't know why after upgrading i'm facing this issue.
I also tried on `vscode` it works fine without any problems and i said before native java and kotlin and also `Jetpack compose` works fine without any problems.

**Comment by stevemessick** [comment]
Can you do an experiment? Disable all optional plugins except Dart and Flutter, and restart. Does the problem still occur?

**Comment by MohamedSlama** [comment]
Sir as i told you on the previous comment i have already done that and i have also installed `IntelliJ` without any plugin no thing changed, I have notice something when i write comment `CPU` record about 90% and `Memory` record about 60% although i'm running only `android studio` and No Emulator or Web Browser.

**Comment by xshiwei** [comment]
It may be caused by the Flutter 2.5.0 version. I also have this problem, so I have to use Vscode, hoping to solve this problem soon. thanks

**Comment by stevemessick** [comment]
This is being tracked in #5761

**Comment by arieffajargemilang** [comment]
> It may be caused by the Flutter 2.5.0 version. I also have this problem, so I have to use Vscode, hoping to solve this problem soon. thanks

me too.. T_T

**Comment by arieffajargemilang** [comment]
> It may be caused by the Flutter 2.5.0 version. I also have this problem, so I have to use Vscode, hoping to solve this problem soon. thanks

after i upgrande to 2.5.2 autocomplete become normally..

**Comment by xshiwei** [comment]
> > 可能是 Flutter 2.5.0 版本导致的。我也有这个问题，所以只好用Vscode，希望早日解决这个问题。谢谢
> 
> 在我升级到 2.5.2 自动完成后变得正常..

thanks, I am also normal

**Comment by MohamedSlama** [comment]
Thanks a lot fixed on version `2.6.0`
