### ISSUE TITLE
Open android project in Android Studio

### ISSUE THREAD

**Issue by Pareshoct7** [flutter/flutter-intellij#5717]
## Steps to Reproduce

1. Android Studio project tab.
2. Right click on project name and select "Flutter"
3. after that select "Open android project in Android Studio"

**Expected results:** 
Run android app normally by pressing Run button

**Actual results:** 
Not showing run button in android studio but flutter code runs properly

Gives following builld warning and not able to run project from android code but if I run from flutter code it runs normally

<details>
  <summary>Logs</summary>

```
Configure project :get_version
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 7s
```

</details>

**Comment by jacob314** [comment]
@stevemessick is this the expected behavior?

**Comment by stevemessick** [comment]
Yes, the android module is not expected to run stand-alone, but rather as part of a Flutter app. Opening the module in Android Studio is useful for editing the Android code, but not for running. Use the Flutter project to launch the app. It is fine to have multiple Android Studio windows open at the same time.

**Comment by Pareshoct7** [comment]
@stevemessick It is very deficult when I change Android code and run from flutter in this case I can not able to debug my Android code which is very bad
