### ISSUE TITLE
Show setUp() and tearDown() in Flutter outline

### ISSUE THREAD

**Issue by berdroid** [flutter/flutter-intellij#5718]
When writing tests using flutter_test, the _Flutter Outline_ and _Structure_ views helpfully show group() and test() calls in a hierarchical view.

It would like to ask that these views also show calls to setUp(), tearDown(), etc. in the same view. 

This feature would greatly enhance navigation within larger test files.

## Steps to Reproduce

Create a test file using flutter_test, including a call to setUp().

The Flutter Outline view does not show the call to setUp()

## Version info

IDE: 2020.3.1 patch 1
Flutter plugin: 59.0.2
Flutter doctor:

**Comment by stevemessick** [comment]
Good idea. Thanks for the suggestion.

**Comment by helin24** [comment]
Closing because we expect this to be done in the analyzer in Dart SDK: https://github.com/flutter/flutter-intellij/issues/5718
