### ISSUE TITLE
 Intellij does not show collapse code button to integration tests in Flutter

### ISSUE THREAD

**Issue by lamkr** [flutter/flutter-intellij#5721]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I noticed that Intellij doesn't show the collapse icon on source codes for testing integration in Flutter. However, for unit tests it does. Please see the figures and note the red circle and question mark.

IC-212.4746.92, JRE 11.0.11+9-b1504.13x64 JetBrains s.r.o., OS Windows 10(amd64) v10.0 , screens 1920.0x1080.0

## Version info

flutter doctor --verbose
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale pt-BR)
    • Flutter version 2.2.3 at C:\Users\luciano\fvm\versions\2.2.3
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\luciano\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\luciano\apps\jdk\8\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\luciano\apps\android\studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Users\luciano\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\211.7442.40
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7665

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Users\luciano\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\212.4746.92
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[√] VS Code (version 1.49.3)
    • VS Code at C:\Users\luciano\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 5.1.1 (API 22) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 92.0.902.78
--

**Comment by lamkr** [comment]
Attached images
![flutter-integration-test](https://user-images.githubusercontent.com/13645700/130670821-19d79d5e-7181-4aa7-9632-ce775bebe5d8.PNG)
![flutter-unit-test](https://user-images.githubusercontent.com/13645700/130670824-667e1624-6b02-4868-b932-d8830512c740.PNG)

**Comment by stevemessick** [comment]
Currently, all code folding is done by the Dart plugin, in class `DartFoldingBuilder`. It makes sense that we'd add a similar class to the Flutter plugin, since `testWidget` is specific to Flutter.

But first, I want to ask @alexander-doroshko if this would be a trivial change to make? And if so, perhaps the Dart plugin could be modified.

**Comment by alexander-doroshko** [comment]
Yes, `"test"` and `"group"` method names are hardcoded in https://github.com/JetBrains/intellij-plugins/blob/0f07ca63355d5530b441ca566c98f17c560e77f8/Dart/src/com/jetbrains/lang/dart/folding/DartFoldingBuilder.java#L341. We may add `"testWidgets"` there as well.

**Comment by stevemessick** [comment]
@jwren this looks like it would be a simple change, if you are set up to work on the Dart plugin. (I'm not.)

**Comment by Gustl22** [comment]
I think this is the wrong approach, we should be able to fold all anonymous functions, independently without exceptions. I made a PR for this in  https://github.com/JetBrains/intellij-plugins/pull/866

**Comment by lamkr** [comment]
> I think this is the wrong approach, we should be able to fold all anonymous functions, independently without exceptions. I made a PR for this in [JetBrains/intellij-plugins#866](https://github.com/JetBrains/intellij-plugins/pull/866)

I agree. The specified problem occurs also with methods `setUpAll` and `tearDownAll`

**Comment by Gustl22** [comment]
This is now fixed / available by https://github.com/JetBrains/intellij-plugins/pull/866
Just need to wait for the next major release I think.

**Comment by stevemessick** [comment]
Thanks @Gustl22 !
