### ISSUE TITLE
Sometimes the autocomplete does not work

### ISSUE THREAD

**Issue by Evoswork** [flutter/flutter-intellij#5732]
Thanks for the feedback! If your issue is related to the Flutter frame![1](https://user-images.githubusercontent.com/66563284/131213093-c6a0e3aa-1fca-47c7-b458-e1a1bf92b1af.png) itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Sometimes the autocomplete does not work
![2](https://user-images.githubusercontent.com/66563284/131213095-38281fe7-8a4a-4ace-bde6-7e3bed5bbc2e.png)
![3](https://user-images.githubusercontent.com/66563284/131213098-7eac3af9-9939-401e-9879-99c7da5e601b.png)
![4](https://user-images.githubusercontent.com/66563284/131213100-acc9c6f2-faf0-41d9-93bd-5419536f38cc.png)

## Version info

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale ru-RU)
    • Flutter version 2.2.3 at /Users/evgenii/flutter
    • Frame![1](https://user-images.githubusercontent.com/66563284/131213093-c6a0e3aa-1fca-47c7-b458-e1a1bf92b1af.png) revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/evgenii/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/evgenii/Library/Android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2 EAP)
    • IntelliJ at /Users/evgenii/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 58.0.4
    • Dart plugin version 212.4535.15

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by stevemessick** [comment]
I can't reproduce this. Could you enable verbose logging in the Flutter preferences and send us the log the next time this happens?

**Comment by Evoswork** [comment]
The problem appears spontaneously, there's no exact scenario of its playback. Os rebooting helps.
How do I enable detailed log?

**Comment by stevemessick** [comment]
You probably do not have to reboot. Try restarting the analysis server. Open the Dart Analysis tool window (`View > Tool Windows > Dart Analysis`) then click the red circle-arrows icon in it. Let us know if that restarts the completion.

Also, please attach your current log file (nevermind the detailed logging). `Help > Show Log in Finder` will reveal it (if not MacOS then "Finder" will be something different, like "Files"). If you are concerned about confidential information in the log, all I need is to know if this phrase is present: "completion_getSuggestions() took longer than". If it is, then let us know what the number following "than" is.

**Comment by Tom3652** [comment]
I would add that with the ```flutter: 2.5.0``` release yesterday, the autocomplete works much slower than before (1-2second VS 200ms). 
I have tried the restart of the dart analysis server and Android Studio but it "almost" doesn't change anything but improves the autocomplete time a bit.

But i have no issue regarding the autocomplete that works, just much slower
