### ISSUE TITLE
flutter-intellij  is opening some files with obsolete statements in Android Studio and VScode (Android Part)

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter-intellij#5736]
This is what is set:
GRADLE WRAPPER PROPERTIES: 
distributions/gradle-6.7     Why not =>minimum 7.0.2  or...7.2 .... or... but something more recent?

BUILD GRADLE
build:gradle:4.1.0, kotlin-gradle-plugin:1.3.50   Why not=>minimum  build:gradle:7.0.1, kotlin-gradle-plugin:1.5.30 or... but something more recent?

APP SRC BUILD GRADLE
compileSdkVersion 30      Why not =>31
targetSdkVersion 30     Why not =>31
minSdkVersion 16        Why not =>21 which fits 94% of android devices (it would imply some v24 and v26 res)

That really gives the feeling to use an obsolete SDK which Flutter is not meant to be

## Version info

**The flutter-intellij plugings is among the others in the dedicated place:**
C:\xxxxx\AppData\Roaming\Google\AndroidStudio2020.3\plugins\flutter-intellij

![vvv](https://user-images.githubusercontent.com/19499129/131527013-1cf876f7-500a-4cd8-ad48-1bc3ec4ca935.PNG)

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
[√] Flutter (Channel master, 2.6.0-1.0.pre.118, on Microsoft Windows [version 10.0.19043.1165], locale fr-FR)
    • Flutter version 2.6.0-1.0.pre.118 at C:\xxxxx
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dd9169ec71 (21 hours ago), 2021-08-30 13:54:54 -0400
    • Engine revision 78c4963075
    • Dart version 2.15.0 (build 2.15.0-66.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\xxxxx
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\xxxxx
    • Java binary at: C:\xxxxx
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\xxxxx

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\xxxxx
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\xxxxx
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [version 10.0.19043.1165]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 92.0.4515.159
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 92.0.902.84

• No issues found!

**Comment by stevemessick** [comment]
I don't see anything here that could change by modifying the Flutter plugin. If you want to discuss Gradle and Android versions you can create an issue in Flutter SDK [repository](https://github.com/flutter/flutter/issues). The `flutter doctor -v` output has a known problem detecting plugins, also tracked in the SDK.
