### ISSUE TITLE
[Android Studio]  plugin version 60.0.2 cannot select new flutter project type.

### ISSUE THREAD

**Issue by NeoLuk** [flutter/flutter-intellij#5737]
After updated to Android Studio Arctic Fox  2020.3.1 Patch 2, the ui of creating a new Flutter project is changed. There is no more an option to create Flutter Plugin or Package (see the attachment below) etc.. The only way you can do is to use `flutter create --template=xxx` in terminal.

Android Studio Info
```
Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 27, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, io.flutter, pl.pszklarska.pubversionchecker
```
![android_studio_new_flutter](https://user-images.githubusercontent.com/22671239/131843169-b3314ed6-f1cc-4a54-afd5-5be056b96500.png)

**Comment by WizNeo6** [comment]
some Updates:
The actual problem is updating Flutter plugin version to `60.0.2`. the same issue occurred as above

**Comment by stevemessick** [comment]
Update to version 60.1.x. Then click Next. The project type selection is on the second page now.
