### ISSUE TITLE
Auto complete is not working

### ISSUE THREAD

**Issue by luisgustavoo** [flutter/flutter-intellij#5738]
When I start a `Future<List...>` method in an abstract class the auto complete simply stops working

![image](https://user-images.githubusercontent.com/59834387/131860160-95671bb9-86f0-402a-89ab-2e4c9147b09f.png)

I have to restart the IDE in the "Invalidate Caches / Restart" options, it just so it works again.

**Comment by stevemessick** [comment]
I see this in the IntelliJ log:
completion_getSuggestions() took longer than 5000ms

It works fine unless you have recently typed a character. I used `File > Close Project` to close my test project, then re-opened it. Placing the cursor after "Fo" as in the screenshot, the completion worked. Deleting and retyping "o" caused it to hang.

@luisgustavoo You don't need to restart. Open the Dart Analysis tool window then click the red circle-arrow icon to restart the analysis server.
