### ISSUE TITLE
After latest upgrade my Android Studio keep informing error in cocoapods. Tries uninstall and install many times, from gem and brew but nothing works. But the app compile with no problem in xcode, so I can only think its a Android Studio problem.

### ISSUE THREAD

**Issue by thiagosoaress2** [flutter/flutter-intellij#5744]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
The Flutter plugin does not use cocopods at all. This is likely a PATH problem. Make sure your PATH definition points to your cocopods installation in your shell script that gets run when you log in. Shell scripts that only run when a terminal emulator is opened will not work.
