### ISSUE TITLE
Source code does not get updated when changing SDK paths in Android Studio

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter-intellij#5749]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

This issue is same as https://github.com/Dart-Code/Dart-Code/issues/3540 for Android Studio IDE, I have different versions of flutter sdk located at

```
$HOME/Documents/
```
as shown in the image

![image](https://user-images.githubusercontent.com/31410839/132670322-5a6f876d-8b7c-45bf-9cb7-b6a589262b16.png)

when I change the flutter sdk and look at the definition of any source code it points to the old source code. The code references only update when we call `flutter pub get`.

## Steps to Reproduce

1. Open a  flutter project in Android Studio
2. run `flutter pub get`
3. Click on Any class and see the source code file location 
4. Change the flutter SDK path
5. repeat step 3 again
  
### Expected Output

Updated source code must be shown when looking at the Class definition

### Actual Output

Old source code is shown when looking at the Class definition.

### Proposal

To automatically call `flutter pub get` when the SDK path updates

## Version info

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (29 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

Let me know if you need any further info.

Thanks

**Comment by stevemessick** [comment]
Dup of https://github.com/flutter/flutter-intellij/issues/5222
