### ISSUE TITLE
Dart SDK path not updated when installing flutter plugin in IntelliJ idea,

### ISSUE THREAD

**Issue by mohammed-rampurawala** [flutter/flutter-intellij#575]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

Prequiste:
You should already have dart sdk installed
## Steps to Reproduce
1. Install IntelliJ idea and install dart and flutter plugin.
2. Then add flutter sdk path 

_Please tell us what you were doing and what went wrong_
Dart sdk path not added

## Version info

Please paste the output of running `flutter doctor` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by devoncarew** [comment]
Can you provide the version of the Dart plugin that you're using? Locally, I am able to set the flutter sdk path, and that is updating the dart sdk path setting.

/cc @pq

**Comment by skybrian** [comment]
The way we handle the Dart SDK changed with #646, so I think this should be fixed. Please reopen if it's still not working for you with the latest version.
