### ISSUE TITLE
Android studio flutter inspector tool failed

### ISSUE THREAD

**Issue by newpersonniu** [flutter/flutter-intellij#5754]
## Steps to Reproduce

flutter debug project, inspector tool failed. 

Other info
Build: AI-203.7717.56.2031.7583922, 202107261959,

AI-203.7717.56.2031.7583922, JRE 11.0.10+0-b96-7249189x64 JetBrains s.r.o., OS Mac OS X(aarch64) v11.4, screens 2880.0x1800.0, 5120.0x2880.0; Retina

AS: Arctic Fox | 2020.3.1; Kotlin plugin: 203-1.5.30-release-411-AS7717.8; Android Gradle Plugin: (plugin information not found); Gradle: (gradle version information not found); Gradle JDK: version 11.0.10; NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)Source: user_sentiment_feedback

## Version info
Android studio version: Mac with Apple chip android-studio-2020.3.1.24-mac_arm

**Comment by stevemessick** [comment]
The embedded browser is not yet supported for Macs using the M1 chip.

You can turn that off in Preferences. Type "devtools" in the search bar, then uncheck the highlighted item in the Flutter preferences. It might have been better if the plugin automatically did that.
