### ISSUE TITLE
Flutter plugin incompatible with android studio

### ISSUE THREAD

**Issue by FadyFouad** [flutter/flutter-intellij#5756]
I updated Android studio to the latest version but unfortunately, After the update some plugins were disabled flutter plugin is one of them Flutter "Incompatible (Since build 203.6682.168 > AI-202.7660.26.42.7486908)".

Flutter version (60.1.2) 

And no update option

![id6XL.png](https://user-images.githubusercontent.com/26604339/132947946-80032708-c457-4a6c-af48-79078882a979.png)

**Comment by stevemessick** [comment]
You are using Android Studio version 202.7660.26 (not the latest stable version) and somehow have the Flutter plugin for Arctic Fox (2020.3) installed. You'll need to re-install Android Studio, or uninstall and re-install the Flutter plugin (and others that are disabled) then restart Android Studio.

**Comment by FadyFouad** [comment]
Thanks, I removed the plugin and reinstalled it now it works fine.
