### ISSUE TITLE
Support/offer to rename file when renaming a class if the names match

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter-intellij#5758]
I recently added support for VS Code/LSP to rename files when renaming classes if the names match. For example if you have `class Person` in `person.dart` and rename the class, it can prompt (or automatically) rename the file too (which updates the imports):

https://github.com/Dart-Code/Dart-Code/issues/3354

https://github.com/dart-lang/sdk/commit/3aa464af26a4467d3977150108c1a9c7b0b1a53a

@jacob314 mentioned it could be nice to support the same here. For VS Code it's handled in the LSP layer but for IntelliJ I'm not sure if it would be best handled in the client extension, or a change to the server protocol to allow passing a flag through with the rename request.

(note: for VS Code this is currently off by default, and can be set to "prompt" or "always".. in the future the default may change, but for now it's opt-in).

**Comment by stevemessick** [comment]
Great idea, thanks. I copied this to the JetBrains issue tracker since rename is part of the Dart plugin.
https://youtrack.jetbrains.com/issue/IDEA-278095
