### ISSUE TITLE
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1029/89AGRYqn_pA=/)

### ISSUE THREAD

**Issue by Mahajan91** [flutter/flutter-intellij#5760]
-I am using flutter & dart for development of android application using android studio arctic. But when i start build application i am getting error. (Error connecting to the service protocol: failed to connect to http://127.0.0.1:1029/89AGRYqn_pA=/)
- Not able to run application on emulator of android

I am using Android studio Arctic version

Using device Pixel 2 XL (Android 4.4)

**Comment by Mahajan91** [comment]
Hello this is the output i get

[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19041.1110], locale en-IN)
    • Flutter version 2.5.0 at E:\Software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Android\android-sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.47

! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
According to the output of `flutter doctor` you have not followed all the instructions for setting up Flutter. You need to perform all the steps described at https://flutter.dev/docs/get-started/install/windows.

**Comment by Mahajan91** [comment]
This issue resolve by me but still it create same error.
