### ISSUE TITLE
Support SDK per module

### ISSUE THREAD

**Issue by nguyenxndaidev** [flutter/flutter-intellij#5767]
Nowaday, [FVM](https://fvm.app) allows to specify independent flutter version per flutter project easily and convenient.

Even though, IntelliJ Flutter plugin does support multiple flutter modules per IntelliJ project, it doesn't allow to have different SDK per module.

It would be nice if beside the default flutter configuration per project, we can overwrite this configuration per each module. It's similar to have different Java SDK for each module.

**Comment by stevemessick** [comment]
If FVM features are adopted by the Flutter SDK then we will support them.

**Comment by nguyenxndaidev** [comment]
> If FVM features are adopted by the Flutter SDK then we will support them.

@stevemessick I am not sure if we misunderstood each other.

* In case you misunderstood my first description:

    I am not talking about supporting FVM. I only mention FVM as an example of how we can nowaday manage different flutter SDKs on the same machine for different flutter projects.

    I update the description to avoid misunderstanding.

* In case I misunderstood your sentence:

Do you mean, Flutter team plan to implement similar features in the future natively? If yes, do you have link to that issue?
