### ISSUE TITLE
Log user interactions with the survey prompt 

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#5772]
Data from Q3 survey suggests that a lot more users responded to the survey from VS Code than IntelliJ, which didn't match the distribution of Flutter's userbase between the two IDEs. We'd like to better understand where the difference came from and fix any bugs that might have prevented users on IntelliJ from seeing the prompt. The preliminary idea is to log events such as showing the prompt, clicking on the survey link, and dismissing the prompt. We should do the same on the VS Code side to enable comparison. 

Cc: @jacob314 @jayoung-lee

**Comment by stevemessick** [comment]
@DanTup How does VS Code interact with users regarding the survey?

**Comment by DanTup** [comment]
It pops up as a toast when the user opens a Flutter project like this:

<img width="772" alt="Screenshot 2021-09-23 at 17 18 43" src="https://user-images.githubusercontent.com/1078012/134545470-9ffa4e4c-1222-4efc-b63f-934878693529.png">

Clicking either button will mark that survey as seen and never show it again. If it's just ignored (VS Code will hide it after about 10 seconds), then after 40 hours it will re-show when opening the next Flutter project.

**Comment by stevemessick** [comment]
Thanks! @pq does the IntelliJ plugin re-show the prompt after 40 hours or so?

**Comment by pq** [comment]
It *should*...  Or at least it **did**?  I'd be a little surprised if this bit-rotted but worth testing.

**Comment by DanTup** [comment]
What are the useful events to know here? Would it just be:

1. Survey prompt shown
2. "Take Survey" action taken
3. "Skip This Survey" action taken

From these I think you could infer that `1 - (2+3)` is the number of prompts shown but either not seen, or ignored.
