### ISSUE TITLE
Because "MyApp" depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

### ISSUE THREAD

**Issue by rehman20281** [flutter/flutter-intellij#5807]
Run this command in your project

flutter pub upgrade

**Comment by stevemessick** [comment]
Run `flutter doctor -v` and append the output here.
What app are you working with, your own or a sample?
`flutter pub upgrade` works for me; I use it almost daily trying to diagnose these issues.
It sounds like your Flutter SDK is not installed properly.
