### ISSUE TITLE
Support running with coverage

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#581]
Need to figure out how we want code coverage to to work, see discussion in https://github.com/flutter/flutter/issues/7119

**Comment by devoncarew** [comment]
This probably is in conjunction with `flutter test` support.

**Comment by Panthro** [comment]
Even though I'm a TDD advocate when the tooling is not the best we lose focus and it's hard to keep on the right track.

I started a project with flutter and working TDD style, but after several weeks working in the project and having to parse and show coverage manually, somehow I didn't get the same motivation to keep writing the tests upfront (or even after the code was done).

I know is a really stupid excuse and a bad habit more than an issue with the tool, but I'm an intellij user for years already and the habit of running my test suites with coverage, seeing the results and adapting to cover more was broken with flutter, and made me a worst developer :-(

Just sharing some developer sad story to give more motivation to build this!

Keep up the good work

**Comment by zoechi** [comment]
dup of #718 ?

**Comment by MisterJimson** [comment]
Also looking for options for this.

**Comment by stevemessick** [comment]
Fixed in #5463
