### ISSUE TITLE
Code inspector is stopped after typing nested generic data types

### ISSUE THREAD

**Issue by javaherisaber** [flutter/flutter-intellij#5814]
## Steps to Reproduce
- Type in some data type with nested generics eg. `final Stream<List<UserData>> data;`
- Voila, now IDE stop's inspecting errors and syntax highlighting

## Version info
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.1237], locale en-US)
    • Flutter version 2.2.0 at C:\sdk\flutter
    • Framework revision b22742018b (5 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\sdk\android
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

**Comment by stevemessick** [comment]
I believe this was fixed long ago. Update to the latest of everything and let us know if the problem still exists.
