### ISSUE TITLE
Tooltips cancel current text selection

### ISSUE THREAD

**Issue by BurningAXE** [flutter/flutter-intellij#5835]
## Steps to Reproduce
1. Start selecting text in the editor by clicking with the mouse's left button and dragging
2. During dragging mouse over a named parameter
3. Drag over to the desired location and release mouse button

Expected result:
Text is selected between the start and end points of the drag

Actual result:
Selection is cancelled when mouse goes over a named parameter which triggers a tooltip to appear

See attached video: https://user-images.githubusercontent.com/5779978/138716203-b9680507-0c5e-4144-9a0b-b94ae5b458af.mov

## Version info

Android Studio 2020.3.1
Flutter Plugin 61.2.2

**Comment by stevemessick** [comment]
I cannot reproduce this. Please attach as simple a project as you can that demonstrates the problem. Also include the output of `flutter doctor -v`. Specifically, we need the Flutter and Dart SDK versions. This may have been fixed already.
