### ISSUE TITLE
Adjusting base HREF for flutter web apps to anything by '/' breaks debugging.

### ISSUE THREAD

**Issue by ajunkala** [flutter/flutter-intellij#5837]
I have a pair of flutter clients running on the same server. In order to access them separately I adjust their respective `<base href="/">` in their index.html to be unique. However when I do this and I set a breakpoint, the breakpoints will no longer be hit while running the web version.

## Steps to Reproduce

Change `<base href="/">` to anything else (e.g. `<base href="/test/">`
Set a breakpoint in dart code
Debug run to chrome
Execute code that passes through the breakpoint

## Version info

[✓] Flutter (Channel stable, 2.0.5, on Linux, locale en_CA.UTF-8)
    • Flutter version 2.0.5 at /home/august/Dev/Tools/flutter
    • Framework revision adc687823a (6 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/august/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/lib/jvm/java-8-oracle/jre/bin/java/bin/java
    ✗ Cannot execute /usr/lib/jvm/java-8-oracle/jre/bin/java/bin/java to determine the version

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.81

Note: Android Studio field is invalid. I have: Arctic Fox | 2020.3.1 Patch 2

**Comment by Nazacheres** [comment]
Hello, having the same issue here. 

```[✓] Flutter (Channel master, 2.9.0-1.0.pre.201, on macOS 11.6 20G165 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.5)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

breakpoints work fine with  `<base href="/">` and don't work with anything else for href.
By running build command with `--verbose` and having at **one** breakpoint. I can see following right before app is started:
```
Debug service listening on ws://127.0.0.1:57969/8ZhyFZDIr44=/ws
[+1373 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 21, error: {code: -32603, message: addBreakpointWithScriptUri: NoSuchMethodError: The getter 'length' was called on null.
           Receiver: null
           Tried calling: length, data: {details: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
           #1      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1737:69)
           #2      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
           #3      Utf8Decoder.convert (package:flutter_tools/src/convert.dart:50:33)
           #4      Codec.decode (dart:convert/codec.dart:26:34)
           #5      WebAssetServer.sourceMapContents (package:flutter_tools/src/isolated/devfs_web.dart:592:17)
           #6      Locations._locationsForModule.<anonymous closure> (package:dwds/src/debugging/location.dart:221:30)
           <asynchronous suspension>
           #7      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
           <asynchronous suspension>
           }}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 22, error: {code: -32603, message: addBreakpointWithScriptUri: NoSuchMethodError: The getter 'length' was called on null.
           Receiver: null
           Tried calling: length, data: {details: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
           #1      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1737:69)
           #2      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
           #3      Utf8Decoder.convert (package:flutter_tools/src/convert.dart:50:33)
           #4      Codec.decode (dart:convert/codec.dart:26:34)
           #5      WebAssetServer.sourceMapContents (package:flutter_tools/src/isolated/devfs_web.dart:592:17)
           #6      Locations._locationsForModule.<anonymous closure> (package:dwds/src/debugging/location.dart:221:30)
           <asynchronous suspension>
           #7      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
           <asynchronous suspension>
           }}}
``` 

When trying to solve this, I also found this https://github.com/flutter/flutter/issues/68660#issuecomment-726436014 - could be related.

P.S. @ajunkala you saved my day by connecting href and this bug, I had a bug, and couldn't find the reason, now I at least know the workaround.

**Comment by Nazacheres** [comment]
This one is directly connected.
https://github.com/flutter/flutter/issues/85035
