### ISSUE TITLE
No error shown in debug mode but the error appears in release mode

### ISSUE THREAD

**Issue by arkanmgerges** [flutter/flutter-intellij#5849]
Hi I recently opened an issue at [flutter/flutter](https://github.com/flutter/flutter/issues/92903) related to problem that Android Studio not showing error in debug mode when using flutter.

The source code is also available at the link above.
Also I tried VSCode and it showed the error in debug mode, but in Android Studio it does not show the error.

**Comment by stevemessick** [comment]
This [appears](https://github.com/flutter/flutter/issues/92903#issuecomment-960270302) to be another case where the `--machine` argument causes problems. Closing this, since the problem is tracked in flutter/flutter.
