### ISSUE TITLE
concurrent modification issue while closing/opening IDE.  flutter build may have been running also.

### ISSUE THREAD

**Issue by hhkk** [flutter/flutter-intellij#5854]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by hhkk** [comment]
concurrent modification issue while closing/opening IDE.  flutter build may have been running also.

**Comment by stevemessick** [comment]
(looks like my comment got lost)

We need more information to debug this issue. Please attach a stack trace. If you have a sample project that reproduces the issue, including that could help a lot.
