### ISSUE TITLE
Something wrong in CONTRIBUTING.MD

### ISSUE THREAD

**Issue by chewenkai** [flutter/flutter-intellij#5859]
Dear, developer and friends:

Here's my experience:

I want to build this project, so I read CONTRIBUTING.MD.

At first, everything going well, I check the step one by one.

But when I run Build at last, all `import com.google.dart.*` cannot found references.

Finally, I found the solution which is I have to add Dart.jar into `ClassPath` manually. 

I am sure I install Dark plugin correctly, and I do restarted the IDEA.

In my case, Dart.jar located in the path of `$HOME/Library/ApplicationSupport/JetBrains/IdeaIC2021.1/plugins/Dart/lib/Dart.jar`

In conclude, I post this with the purpose of:
- If someone encountering the same problem, you can fix it by import dart.jar manually.
- Developer please check this problem, or amend the document CONTRIBUTING.MD soon.

*Wish you all the best,*
*Yours,*
*Calvin*

**Comment by stevemessick** [comment]
The project file `flutter-intellij.iml` includes a definition for the Dart library, but it is out of date in the current version.
