### ISSUE TITLE
Survey announcement is shown when the survey is not supposed to be available

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/flutter-intellij#5866]
The Q4 survey is supposed to be available from Nov 22, 9:00 AM PST (https://docs.flutter.dev/f/flutter-survey-metadata.json). 

However, the earliest a dev started the Q4 survey from IntelliJ was Nov 21, 7:41 AM PST, based on the Qualtrics record. It's over 24 hours before the planned launch time.

Since the Q4 survey was published on the 19th, the devs should have been able to see the questions and answer them. But this needs to be fixed for the future surveys.

**Comment by stevemessick** [comment]
@jayoung-lee I looked at the code that controls when the announcement is shown. It uses standard Java library functions. There's nothing special about it. I don't see how the code could have made this mistake. The only explanation I can find is that someone had the date and time on their computer set incorrectly. That could happen if someone is testing date-sensitive code. Does that seem reasonable?

**Comment by jayoung-lee** [comment]
Thanks for checking! That's interesting. VS Code user may be testing date and time too, but they don't seem to open the survey before it launches. Is it unique to IntelliJ? Can we make it use the server time instead of local time?  Opening a survey but unable to answer it is a bad experience.

**Comment by stevemessick** [comment]
How many surveys were opened early?

**Comment by jayoung-lee** [comment]
The surveys used to become available on time, but after I realized that some users opened the survey early (a few quarters ago), I tried to make it available as soon as possible, like 1-2 days before the launch date, just in case.

**Comment by stevemessick** [comment]
How many are submitted early? One or two, dozens, hundreds?

**Comment by jayoung-lee** [comment]
When it's open a day early, it usually ranges from 200-300.

**Comment by stevemessick** [comment]
OK, that is not consistent with my earlier hypothesis. Thanks for the info!

**Comment by stevemessick** [comment]
@jayoung-lee asked
> Can we make it use the server time instead of local time?

We would need to know the user's location. That is not enabled on some computers -- and on Macs it is off by default.
