### ISSUE TITLE
"Flutter inspector the embedded browser failed to load" 

### ISSUE THREAD

**Issue by Sarahcalbez2** [flutter/flutter-intellij#5869]
Looking at the terminal, is everything ok with the Flutter and other sdk on my computer. 
I'm using a macbook M1. 

<img width="610" alt="Screen Shot 2021-11-24 at 15 01 28" src="https://user-images.githubusercontent.com/56567293/143291356-58ab5295-b0a0-40b1-8458-b614f71bacb5.png">

That is the issue I saw on my screen using the Flutter inspector. 
<img width="543" alt="Screen Shot 2021-11-24 at 14 43 56" src="https://user-images.githubusercontent.com/56567293/143291488-45852173-8eee-46c3-a91c-b7805c7f495e.png">

I have been searching about, and I found other people with the same issue and the same situation, using the macbook M1.
If there anyone here to help me, I will be thankfully.

**Comment by princestha** [comment]
I have the same issue

**Comment by tallinn1960** [comment]
For flutter plugin version 62.0.x there is a workaround described in #5853.

Do not update to plugin version 63.0.x unless you need to (which is the case if you update Intellij to 2021.3). It is even more broken (see #5876 or #5880).

I build a version from release tag release_62 including the update fix https://github.com/flutter/flutter-intellij/commit/8ae9356609a39b93f0309eff7816f6aa2049fdca which works with 2021.3 on M1.

**Comment by stevemessick** [comment]
This should be fixed in version 63 of the Flutter plugin. If you still have problems please re-open this issue and include the plugin version number.
