### ISSUE TITLE
Add Dart file type in Structural Search Dialog in Intellij Idea

### ISSUE THREAD

**Issue by kevintorch** [flutter/flutter-intellij#5873]
Please add Dart file type in Structural Search Dialog in Intellij Idea. it would be really helpful.

**Comment by stevemessick** [comment]
@alexander-doroshko do you have an issue open for this?

**Comment by alexander-doroshko** [comment]
Yes, here it is: https://youtrack.jetbrains.com/issue/WEB-22130.
Unfortunately, it's not on the roadmap at the moment. For some reason, it has collected only 2 votes in 5 years.

**Comment by stevemessick** [comment]
Got it, thanks! Since it is being tracked elsewhere I'm closing this issue.
@kevintorch you might want to upvote the youtrack issue.
