### ISSUE TITLE
Dart members do not show in Navigation Bar

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter-intellij#5879]
## Steps to Reproduce

Create/open a flutter project
Open a .dart file in the editor
Check Navigation Bar
Note that dart members do not show here even though the setting is on and members show up correctly in Structure window
Note that VSCode shows members in its navigation bar correctly as well

![image](https://user-images.githubusercontent.com/1481807/144553578-7f503d0e-d7f1-4619-9b35-8935b06e6d5d.png)

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
This is tracked as https://youtrack.jetbrains.com/issue/WEB-33823

**Comment by duzenko** [comment]
@stevemessick I'm sorry, why is it tracked in jetbrains tracker? Is it their job to add support for dart language in Android Studio?
