### ISSUE TITLE
Flutter plugin still not downloads JxBrowser

### ISSUE THREAD

**Issue by westito** [flutter/flutter-intellij#5885]
## Steps to Reproduce

I installed latest (63.1.4) Flutter plugin that says "Enable downloading Mac M1 version of JxBrowser (#5871)" but still not downloads. There is no jxbrowser jar in plugin folder, no error in idea.log related to JxBrowser and there is no Flutter Tool Windows in list nor side of the IDE

## Version info

[flutter]
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale hu)
    • Flutter version 2.8.0 at /Users/westito/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (15 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/westito/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/westito/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.

[intellij]
IntelliJ IDEA 2021.3 (Ultimate Edition)
Build #IU-213.5744.223, built on November 27, 2021
Licensed to Marcell Nemeth
Subscription is active until October 21, 2022.
For educational use only.
Runtime version: 11.0.13+7-b1751.19 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.gmike.visual-studio-2019-dark (1.5.3)
    com.chimerapps.moorinspector (0.2.0)
    cn.neday.excavator (1.9)
    pl.pszklarska.pubversionchecker (1.3.1)
    com.chrisrm.idea.MaterialThemeUI (6.10.1)
    io.codiga.plugins.jetbrains-plugin (1.1.10)
    com.mallowigi (50.2.0)
    Dart (213.5744.122)
    io.flutter (63.1.4)
    de.mariushoefler.flutter_enhancement_suite (1.6.0)
    com.localizely.flutter-intl (1.16.0-2020.3)
    com.github.hayoi.haystack (1.3.01)
    com.github.ArtsiomCh.NestedBracketsColorer (0.6.0)
    andrasferenczi.dart-data-plugin (0.2.0)

Kotlin: 213-1.5.10-release-949-IJ5744.223

**Comment by westito** [comment]
The FormatException: Unexpected extension byte (at offset 5) error in flutter doctor relates to Dart plugin, not Flutter 
#5872

**Comment by tallinn1960** [comment]
Share your idea.log. As the plugin is working on my M1 mac mini since 63.1.4 without the need for a workaround I found for 62.0.13 (not sure about the specific 62.0 version number).

This is how it should read:

```
2021-12-09 14:53:50,211 [  15851]   INFO - lutter.run.daemon.DeviceDaemon - starting Flutter device daemon #1: /Users/tallinn/Downloads/flutter/bin/flutter daemon 
2021-12-09 14:53:50,347 [  15987]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=io.flutter.editor.ActiveEditorsOutlineService) 
2021-12-09 14:53:50,955 [  16595]   INFO - ter.jxbrowser.JxBrowserManager - elstersecure: JxBrowser file downloaded: /Users/tallinn/Library/Application Support/JetBrains/IntelliJIdea2021.3/plugins/flutter-idea/jxbrowser/jxbrowser-mac-arm-7.19.jar 
2021-12-09 14:53:51,552 [  17192]   INFO - ter.jxbrowser.JxBrowserManager - elstersecure: JxBrowser file downloaded: /Users/tallinn/Library/Application Support/JetBrains/IntelliJIdea2021.3/plugins/flutter-idea/jxbrowser/jxbrowser-7.19.jar 
2021-12-09 14:53:51,565 [  17205]   INFO - lutter.run.daemon.DeviceDaemon - flutter device daemon #1: Starting device daemon... 
2021-12-09 14:53:51,764 [  17404]   INFO - ter.jxbrowser.JxBrowserManager - elstersecure: JxBrowser file downloaded: /Users/tallinn/Library/Application Support/JetBrains/IntelliJIdea2021.3/plugins/flutter-idea/jxbrowser/jxbrowser-swing-7.19.jar 
2021-12-09 14:53:51,766 [  17406]   INFO - ter.jxbrowser.JxBrowserManager - Loaded JxBrowser files successfully: [/Users/tallinn/Library/Application Support/JetBrains/IntelliJIdea2021.3/plugins/flutter-idea/jxbrowser/jxbrowser-mac-arm-7.19.jar, /Users/tallinn/Library/Application Support/JetBrains/IntelliJIdea2021.3/plugins/flutter-idea/jxbrowser/jxbrowser-7.19.jar, /Users/tallinn/Library/Application Support/JetBrains/IntelliJIdea2021.3/plugins/flutter-idea/jxbrowser/jxbrowser-swing-7.19.jar] 
```

but probably won't.

**Comment by stevemessick** [comment]
@westito Did you disable downloading of JxBrowser at some point? Looking at your log output, it seems that nothing regarding JxBrowser is ever performed. Check your preferences and re-enable it if necessary. Also, you can turn off verbose logging for now.

Thanks @tallinn1960, for requesting the log output.

**Comment by westito** [comment]
This was enabled. I tried turn off/on many times. But! Today it suddenly started working! I opened an other project and JxBrowser downloaded. The issue: My project is a multi-library project. The opened root folder contains more than one application and not have pubspec.yaml in the project root. The plugin doesn't recognise the project as a Flutter project and Flutter related tool windows not showing. This is worked before the plugin update.

**Comment by westito** [comment]
I created a mock pubspec.yaml in root folder, now it's working. I think there is a new "feature" that hides Flutter tools when the project is not a Flutter project. Would be a nice feature indeed, but not detects Flutter project properly. The solution is a recursive pubspec.yaml search.

**Comment by westito** [comment]
I added subfolders as module in project settings. That way working too without pubspec. May it can be an IntelliJ issue that not creates module from source when opened first time?

**Comment by stevemessick** [comment]
The Flutter plugin does not work with monorepo projects. See #5291
