### ISSUE TITLE
Android studio high cpu usage (130% to 1000%) on mac when working on Flutter project

### ISSUE THREAD

**Issue by albertocappellina** [flutter/flutter-intellij#5906]
As stated, while working on flutter project android studio uses high cpu percentage (from 130% to 1000% according activity monitor). With time passing by cpu percentage increase and android studio performance get worse (lag, stuttering). the only thing that helps (for a while) is to close it and to re-open it .

After some time a popup show up telling about high number of internal exceptions and a clean reinstallation is suggested. Already did twice but nothing changed.

Checking on memory indicator i can see that it grows really fast from 140 mg to 4gb (max heap) without having any tab open. i can see that garbage collector is working very hard bringing the occupation to 2g but it goes up to 4gb very fast

also i can no longer quit android studio but i have to kill it

## Version info

➜  flutter git:(stable) flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/alberto.cappellina/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/alberto.cappellina/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/alberto.cappellina/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/alberto.cappellina/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • IPhone Xr (mobile) • 00008020-00066D2C3C99002E • ios            • iOS 14.1 18A8395
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 11.6 20G165 darwin-x64

**Comment by stevemessick** [comment]
What versions of the Flutter and Dart plugins do you have installed?

Please share your log file. You can find it from `Help > Show Log in Finder`.

**Comment by stevemessick** [comment]
Thanks for the reply @albertocappellina.
