### ISSUE TITLE
Android Studio Emulator cannot be embedded for Flutter project

### ISSUE THREAD

**Issue by Gabriel2048** [flutter/flutter-intellij#5910]
This issue is a parity inconsistency between regular Android projects and Flutter Android projects.
Apparently this is not a bug within Android Studio as there are some complains ([here](https://issuetracker.google.com/issues/213617230) or [here(this also has an technical explanation that might be valuable)](https://issuetracker.google.com/issues/203683935#comment6)) about it in the Android Studio's issue tracker and they mention this should be addressed to the Flutter Plugin team.

## Steps to Reproduce

1)Create a new Flutter project using the flutter plugin
2) Go to Settings > Tools > Emulator
3) Check "Launch in a tool window" option
4) Save changes and close the settings window.
5) Go to AVD manager and start an emulator

Actual result: The emulator is being started as a new windows app (see attached screenshot).
Expected result: The emulator is started in the tools section of Android Studio (embedded).
![image](https://user-images.githubusercontent.com/60075087/150201048-591db1eb-ba2c-436a-8fea-8249c2803b39.png)

## Version info
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
    • Flutter version 2.8.1 at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\iliec\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\iliec\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 96.0.1054.62

! Doctor found issues in 1 category.

**Comment by Gabriel2048** [comment]
@stevemessick Thank you, the fix you mentioned in [here](https://github.com/flutter/flutter-intellij/issues/5464) is working, I am now able to launch the emulator in the tools window.
However, wouldn't it make sense to have the flutter plugin add the module automatically when creating the project in the first place?

**Comment by stevemessick** [comment]
Yes, that is the topic of #5464. I'm leaving this issue open as a reminder to added embedded launch mode to the Flutter plugin.

**Comment by Gabriel2048** [comment]
@stevemessick I see you closed https://github.com/flutter/flutter-intellij/issues/5464 so I assume this item can also be closed

**Comment by stevemessick** [comment]
@Gabriel2048 I don't know. I have not tested this feature yet.

**Comment by stevemessick** [comment]
No, this issue is not fixed. However, I'm closing it as a dup of #5917, since that one is asking for even more.

**Comment by stevemessick** [comment]
Re-opening since the other has two topics and this isn't the first.

**Comment by pedromassango** [comment]
@stevemessick isn this fixed by https://github.com/flutter/flutter-intellij/pull/6279?

**Comment by stevemessick** [comment]
Yes, thanks. Closing.
