### ISSUE TITLE
 i can create new flutter project and there are many problem with flutter  after update Android studio  also emeulater device 

### ISSUE THREAD

**Issue by KhuloodBatis** [flutter/flutter-intellij#5930]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
Please add the output of running `flutter doctor -v`.

Also, we'll need a more specific description of the problem in order to help.
