### ISSUE TITLE
Device Manager fails to open

### ISSUE THREAD

**Issue by kismet-** [flutter/flutter-intellij#5941]
In Android Studio Bumblebee | 2021.1.1 projects that don't contain an .iml file can't open the device manager from the toolbar.

## Version info

[!] Flutter (Channel master, 2.10.0-1.0.pre.424, on macOS 12.2 21D49 darwin-arm, locale en-US)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.1)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[!] Connected device
    ! No devices available
[✓] HTTP Host Availability

**Comment by stevemessick** [comment]
This is caused by the problem reported in #5464. The latest version of the plugin fixes it for new projects, but not for existing ones. That work is scheduled for later
