### ISSUE TITLE
New upgrade Android Studio BumbleBee 2021.1.1 Patch 1 on Mac M1 ARM: App Flutter, Error not finding the cause when analyzing or archiving on Xcode.

### ISSUE THREAD

**Issue by tuemaytinh1981** [flutter/flutter-intellij#5946]
Flutter app using android studio before build XCode without error. I just updated to Android Studio BumbleBee 2021.1.1 Patch 1, open Xcode analysis or archive failed for unknown reason. Even though I did clean and install Pod and remove all catch...
I just removed Patch 1 to install Android Studio earlier 2021.1.1.20-mac-arm.dmg and clean and build again. Open Xcode analyze and archive successfully. I do not understand why.
Run Android Studio from Terminal: open /Applications/Android\ Studio.app. If running directly fails when building iOS.

**Comment by tuemaytinh1981** [comment]
I don't understand why since Bumblebee Android studio version has to run the line of code from terminal (Mac M1): open /Applications/Android\ Studio.app otherwise will get the following error:

> Launching lib/main.dart on iPhone 13 in debug mode...
> Warning: CocoaPods not installed. Skipping pod install.
>   CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
>   Without CocoaPods, plugins will not work on iOS or macOS.
>   For more info, see https://flutter.dev/platform-plugins
> To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
> 
> CocoaPods not installed or not in valid state.
> Error launching application on iPhone 13.

**Comment by stevemessick** [comment]
There appear to be problems with the Android Studio installation. This is not something that can be fixed by changing the Flutter plugin.

I see from reading bug reports that some users are switching back to Arctic Fox for a while.
