### ISSUE TITLE
`stful` macro should not generates public API with private type

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#5962]
The `stful` macro generates a `StatefulWidget` with the following problematic `createState` implementation (assuming the generated widget has been named `Foo`):

```dart
@override
_FooState createState() => _FooState();
```

This is violating the [`library_private_types_in_public_api`](https://dart-lang.github.io/linter/lints/library_private_types_in_public_api.html) lint and bad style because among other things it exposes the private `_FooState` type in the API docs. Private types shouldn't be exposed in public API. Instead, the macro should generate the following `createState` getter:

```dart
@override
State<Foo> createState() => _FooState();
```

(That's also the what we use for that getter in the framework.)

**Comment by goderbauer** [comment]
`stanim` is also affected by this.

**Comment by goderbauer** [comment]
@DanTup Does VSCode have a similar macro feature? If so, we should check that it doesn't use private types in public API.

**Comment by goderbauer** [comment]
Additional context: The lint `library_private_types_in_public_api` will be added to package:lints in the future (https://github.com/dart-lang/lints/issues/23) so a broader audience will run into this.

**Comment by fzyzcjy** [comment]
Agree. Face this problem today when upgrading to 3.0

**Comment by DanTup** [comment]
@fzyzcjy can you clarify what you're seeing and what editor you're using? Also confirm the version of the IDE and version of the Dart/Flutter extensions. Thanks!

**Comment by fzyzcjy** [comment]
@DanTup I am not facing it anymore using latest plugin etc. So ignore my comments above :)
