### ISSUE TITLE
Slow import library suggestion on IntelliJ 2021.1+

### ISSUE THREAD

**Issue by kefasjw** [flutter/flutter-intellij#5969]
## Description

Slow import library suggestion on IntelliJ 2021.1 (and higher). It's instant on IntelliJ 2020.3 (and lower).

## Steps to Reproduce

1. Create a new flutter project
2. Wait for the initializer and analyzer to finish
3. Create a new dart file inside the `lib` directory
4. Copy paste this code into the file
    ```
    class MyWidget extends StatelessWidget {
      const MyWidget({Key? key}) : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return Container();
      }
    }
    ```
5. Click the `StatelessWidget` and press `ALT` + `Enter`

### Actual result

Pop up `Inspection 'Annotator' options` will be shown instead of import library suggestion. The import library suggestion will be shown after 2-3 times (2-5 seconds) after closing this pop up.

![image](https://user-images.githubusercontent.com/11681703/153743956-c73b1771-b5ec-47d2-8fba-c2781e81fea5.png)

### Expected result

Import library suggestion should be shown immediately

![image](https://user-images.githubusercontent.com/11681703/153744109-9dfa2755-7529-4ea6-8026-1f577201b704.png)

### 2021.1 (slow suggestion)
https://user-images.githubusercontent.com/11681703/153744299-b84426a6-79c2-4f0f-a179-e53278b0d6ae.mp4

### 2020.3 (instant suggestion)
https://user-images.githubusercontent.com/11681703/153745068-8b6030f3-fb8e-448a-92fa-eda7ca9d581f.mp4

## Version info

- Windows 11
- Dart Plugin = 203.8452
- Flutter Plugin = 64.1.1
- Flutter doctor
    <details><summary>Show Flutter doctor</summary>
    <p>

    ```
    C:\Users\xxx>flutter doctor -v
    [√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22000.469], locale en-ID)
        • Flutter version 2.10.1 at C:\Users\xxx\Downloads\test\flutter_windows_2.10.1-stable\flutter
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision db747aa133 (3 days ago), 2022-02-09 13:57:35 -0600
        • Engine revision ab46186b24
        • Dart version 2.16.1
        • DevTools version 2.9.2
    
    [X] Android toolchain - develop for Android devices
        X Unable to locate Android SDK.
          Install Android Studio from: https://developer.android.com/studio/index.html
          On first launch it will assist you in installing the Android SDK components.
          (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
          If the Android SDK has been installed to a custom location, please use
          `flutter config --android-sdk` to update to that location.
    
    
    [√] Chrome - develop for the web
        • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
    
    [X] Visual Studio - develop for Windows
        X Visual Studio not installed; this is necessary for Windows development.
          Download at https://visualstudio.microsoft.com/downloads/.
          Please install the "Desktop development with C++" workload, including all of its default components
    
    [!] Android Studio (not installed)
        • Android Studio not found; download from https://developer.android.com/studio/index.html
          (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
    
    [√] IntelliJ IDEA Community Edition (version 2020.3)
        • IntelliJ at C:\Users\xxx\Downloads\test\ideaIC-2020.3.4.win
        • Flutter plugin version 64.1.1
        • Dart plugin version 203.8452
    
    [√] IntelliJ IDEA Community Edition (version 2021.1)
        • IntelliJ at C:\Users\xxx\Downloads\test\ideaIC-2021.1.3.win
        • Flutter plugin version 64.1.2
        • Dart plugin version 211.7798
    
    [√] Connected device (3 available)
        • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.469]
        • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.80
        • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.43
    
    [√] HTTP Host Availability
        • All required HTTP hosts are available
    
    ! Doctor found issues in 3 categories.
    ```
    </p>
    </details>
- Also tested on Ubuntu 20.04, macOS Monterey 12.2. They all produce the same result.

**Comment by stevemessick** [comment]
@kefasjw Have you tried this with 2021.3.2? I just did and got results similar to your 2020.3 video.

My plugin version are
Dart: 213.5744.122
Flutter: 64.1.4

**Comment by kefasjw** [comment]
Yes, I've tried with 2021.3.2, here's the video recording. 

Dart: 213.5744.122
Flutter: 64.1.4 

https://user-images.githubusercontent.com/11681703/153994655-cc41c325-45d6-4ab2-8f78-2dad173e03dc.mp4

**Comment by kefasjw** [comment]
I've seen others also experience this, like https://stackoverflow.com/questions/70420125/intellij-altenter-doesnt-show-correctly-on-the-first-key-press

**Comment by stevemessick** [comment]
I cannot reproduce this problem on either the current or previous stable version of IntelliJ. My Mac has a *lot* of memory, which might be a factor.

Unfortunately, this is a problem that cannot be fixed by modifying the Flutter plugin. It might be an issue with the Dart plugin, but since you eventually see the correct result, I think it is a problem with the Dart analyzer. I used to be able to move issues to [dart-lang/sdk](https://github.com/dart-lang/sdk/issues) but lost that ability. I know that some people have been looking into completion performance (e.g. @bwilkerson) but I don't know if this specific problem is being considered. I suggest posting your slow video to [dart-lang/sdk](https://github.com/dart-lang/sdk/issues).

**Comment by kefasjw** [comment]
Thanks @stevemessick for your help, I've created the issue on https://github.com/dart-lang/sdk/issues/48407
