### ISSUE TITLE
flutter install error in Intellij IDEA

### ISSUE THREAD

**Issue by ZhongGuanbin** [flutter/flutter-intellij#6003]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
I just installed the Flutter plugin into the latest stable and EAP versions of IntelliJ. There were no errors.

Closing this, since there is no actionable information.

**Comment by ZhongGuanbin** [comment]
来信获悉，感谢您的支持！耑此奉复                                                                           钟冠彬This is an automatic reply, confirming that your e-mail was received.Thank you
