### ISSUE TITLE
Breakpoints not working on 65.0.2

### ISSUE THREAD

**Issue by sleewok** [flutter/flutter-intellij#6013]
Running BumbleeBee 2021.1.1 patch 2. 

upgrading to 65.0.2 breaks breakpoints. Downgrading to 64.1.2 fixes it.

**Comment by SreeHarsha1** [comment]
Any breakpoints are not being hit in BumbleeBee 2021.1.1 patch 2. Create a new flutter project and check it to recreate the issue, I just uninstalled and installed everything to re-check the error, can anyone suggest to me how to downgrade?

**Comment by Wesleychung93** [comment]
> Any breakpoints are not being hit in BumbleeBee 2021.1.1 patch 2. Create a new flutter project and check it to recreate the issue, I just uninstalled and installed everything to re-check the error, can anyone suggest to me how to downgrade?

Someone already provided the downgrade solution. Please visit 
1. https://github.com/flutter/flutter-intellij/issues/6002#issuecomment-1056675050
2. https://github.com/flutter/flutter-intellij/issues/6002#issuecomment-1057533470

**Comment by friedScotch** [comment]
As far as I know this has been fixed in a 65.1.X  Please take a look at #6002 and where it has been fixed:  #6010

**Comment by SreeHarsha1** [comment]
Yes seems to be fixed in new version

**Comment by stevemessick** [comment]
Yes, 65.1 fixes breakpoints and the error a some saw due to trying to add a duplicate module.
