### ISSUE TITLE
Flutter Plugin error

### ISSUE THREAD

**Issue by Arik39** [flutter/flutter-intellij#6025]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
Open the latest version of the android studio.

Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart (211.7808), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), io.flutter (65.1.2), org.intellij.plugins.markdown (211.7142.37)

 

## Version info

[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.527], locale en-US)
    • Flutter version 2.10.3 at D:\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (6 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[bug-report_1.md](https://github.com/flutter/flutter-intellij/files/8206525/bug-report_1.md)

**Comment by stevemessick** [comment]
Dup of #6019
