### ISSUE TITLE
I have a problem whit textFromFild , can you help me !?

### ISSUE THREAD

**Issue by ibr-ashraf-0** [flutter/flutter-intellij#6035]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by ibr-ashraf-0** [comment]
D/InputConnectionAdaptor(20077): The input method toggled cursor monitoring off
this wrong happens when I try to write anything in TextFromFild after that the keyboard hait, I now I cant write in TextFild 

// The Code 


  body: Container(
        // height: double.infinity,
        color: const Color.fromRGBO(243, 244, 252, 1),
        child: Form(
          key: formKey,
          child: ListView(
            children: [
              const SizedBox(
                height: 25,
              ),
              Stack(
                alignment: Alignment.center,
                children: [
                  Container(
                    alignment: Alignment.center,
                    padding: const EdgeInsets.only(top: 20),
                    child: GestureDetector(
                      onTap: _pickImage,
                      child: CircleAvatar(
                        radius: 40,
                        backgroundColor: const Color.fromRGBO(243, 244, 252, 1),
                        backgroundImage: profilFile != null
                            ? FileImage(File(profilFile!.path))
                        as ImageProvider<Object>?
                            : const AssetImage(
                          'assets/images/noImage.png',
                        ),
                      ),
                    ),
                  ),
                  Container(
                    padding: const EdgeInsets.only(bottom: 25, left: 77),
                    // alignment: Alignment.centeerRight,
                    child: Icon(
                      profilFile == null ? Icons.add_circle : Icons.done,
                      size: 22,
                      color: const Color.fromRGBO(241, 76, 76, 1),
                    ),
                  ),
                ],
              ),
              const SizedBox(
                height: 40,
              ),
              const SizedBox(height: 20,),
              Padding(
                padding: const EdgeInsets.only(right: 30.0, left: 30),
                child: TextFormField(
                  key: const ValueKey('name'),
                  autocorrect: false,
                  controller: newNameController,
                  autofocus: true,
                  // onTap: (){
                  //   FocusScope.of(context).autofocus;
                  // },
                  obscureText: false,
                  enableSuggestions: true,
                  textCapitalization: TextCapitalization.words,
                  validator: (val) {
                    if (val!.isEmpty || val.length < 4) {
                      return "Please enter at least 4 characters";
                    }
                    return null;
                  },
                  onSaved: (val) => newUserName = val!,
                  keyboardType: TextInputType.text,
                  decoration: InputDecoration(
                    fillColor: Colors.white,
                    filled: true,
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(15.0),
                      borderSide:
                      const BorderSide(width: 0.0, color: Colors.white),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(25.0),
                      borderSide:
                      const BorderSide(width: 3, color: Colors.redAccent),
                    ),
                    label: const Text(
                      'Name',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 18,
                      ),
                    ),
                    prefixIcon: const Icon(
                      Icons.person,
                      color: Color.fromRGBO(241, 76, 76, 1),
                    ),
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(right: 30.0, left: 30, top: 20),
                child: TextFormField(
                  showCursor: true,
                  autofocus: true,

                  key: const ValueKey('email'),
                  autocorrect: true,
                  obscureText: false,
                  enableSuggestions: true,
                  textCapitalization: TextCapitalization.none,
                  validator: (val) {
                    if (val!.isEmpty || val.length < 4) {
                      return "Please enter a valid email address";
                    }
                    return null;
                  },
                  onSaved: (val) => newEmail = val!,
                  keyboardType: TextInputType.emailAddress,
                  decoration: InputDecoration(
                    fillColor: Colors.white,
                    filled: true,
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(15.0),
                      borderSide:
                      const BorderSide(width: 0.0, color: Colors.white),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(25.0),
                      borderSide:
                      const BorderSide(width: 3, color: Colors.redAccent),
                    ),
                    label: const Text(
                      'Email',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 18,
                      ),
                    ),
                    prefixIcon: const Icon(
                      Icons.lock,
                      color: Color.fromRGBO(241, 76, 76, 1),
                    ),
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(right: 30.0, left: 30, top: 20),
                child: TextFormField(
                  key: const ValueKey('location'),
                  autocorrect: true,
                  obscureText: false,
                  enableSuggestions: true,
                  textCapitalization: TextCapitalization.words,
                  validator: (val) {
                    if (val!.isEmpty || val.length < 4) {
                      return "Please enter your business location";
                    }
                    return null;
                  },
                  onSaved: (val) => newLoction = val!,
                  keyboardType: TextInputType.text,
                  decoration: InputDecoration(
                    fillColor: Colors.white,
                    filled: true,
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(15.0),
                      borderSide:
                      const BorderSide(width: 0.0, color: Colors.white),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(25.0),
                      borderSide:
                      const BorderSide(width: 3, color: Colors.redAccent),
                    ),
                    label: const Text(
                      'Location',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 18,
                      ),
                    ),
                    prefixIcon: const Icon(
                      Icons.location_on_outlined,
                      color: Color.fromRGBO(241, 76, 76, 1),
                    ),
                  ),
                ),
              ),
              const SizedBox(
                height: 40,
              ),
              Container(
                width: 850,
                // padding: const EdgeInsets.only(right: 0.5, left: 0.5),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Container(
                      width: 370,
                      height: 52,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20),
                        boxShadow: [
                          BoxShadow(
                              color: Colors.red.withOpacity(0.6),
                              spreadRadius: 0,
                              blurRadius: 30,
                              offset: const Offset(0, 15)),
                        ],
                      ),
                      child: RawMaterialButton(
                        splashColor: Colors.red,
                        // for long pees color
                        fillColor: const Color.fromRGBO(241, 76, 76, 1),
                        highlightColor: Colors.red[200],
                        // padding: const EdgeInsets.symmetric(horizontal: 35, vertical: 20),
                        focusColor: const Color.fromRGBO(241, 76, 76, 1),
                        autofocus: true,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        child: Row(
                          children: const [
                            Expanded(
                              flex: 3,
                              child: Text(
                                'Save',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 15,
                                    fontWeight: FontWeight.w400),
                              ),
                            ),
                          ],
                        ),
                        onPressed: () async {
                          final user = FirebaseAuth.instance.currentUser;
                          final storage = FirebaseStorage.instance
                              .ref()
                              .child('UserData')
                              .child(user!.uid + 'profilePicture');
                          await storage
                              .putFile(File(profilFile!.path))
                              .then((_) async {
                            isAddProfileImage = true;
                            SharedPreferences prefs =
                            await SharedPreferences.getInstance();
                            prefs.setBool(
                                'isAddProfileImage', isAddProfileImage!);
                          });
                          String url = await storage.getDownloadURL();
                          FocusScope.of(context).unfocus();
                          await FirebaseFirestore.instance
                              .collection('users')
                              .doc(user.uid)
                              .set({
                            'name': newNameController,
                            'email': newEmailController,
                            'location': newLoctionController,
                            'profileImageUrl': url,
                          }).then((_) async {
                            // FirebaseAuth.instance.currentUser!
                            //     .updateEmail(newEmailController);
                            ScaffoldMessenger.of(context)
                                .showSnackBar(const SnackBar(
                              content: Text('your information are updated'),
                              backgroundColor: Colors.green,
                            ));
                          });
                        },
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),

**Comment by stevemessick** [comment]
This is a good place to report problems with the Flutter plugin for Android Studio.

Help with programming questions is better asked at https://stackoverflow.com/questions/tagged/flutter
