### ISSUE TITLE
Error opening Android module in Android Studio on Windows

### ISSUE THREAD

**Issue by asashour** [flutter/flutter-intellij#6043]
## Steps to Reproduce

1. Have a new project
2. In `Project` view, right click -> Flutter -> Opening Android module in Android Studio
<img src=https://user-images.githubusercontent.com/2410127/158564407-efe765df-621b-407f-afb7-e7c232ab58a2.png height=400>

### Expected
Android Studio is open

### Actual
![image](https://user-images.githubusercontent.com/2410127/158560729-4b63d2e3-d7fc-46c3-bd3d-2b3d71659663.png)

## Version info

<details>
<summary>flutter doctor -v`</summary>

```
[√] Flutter (Channel master, 2.13.0-0.0.pre.114, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
    • Flutter version 2.13.0-0.0.pre.114 at C:\use\flutter
    • Upstream repository https://github.com/asashour/flutter.git
    • Framework revision b4040c867b (10 hours ago), 2022-03-17 10:15:13 +0800
    • Engine revision 46c2ccae24
    • Dart version 2.17.0 (build 2.17.0-202.0.dev)
    • DevTools version 2.11.4

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\ahmed_ashour\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = C:\Users\ahmed_ashour\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin version 65.2.4
    • Dart plugin version 213.7227

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 221.3427.89
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 221.3427.93

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\ahmed_ashour\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • SM A505FN (mobile) • R58MA65MFJF • android-arm64  • Android 11 (API 30)
    • Windows (desktop)  • windows     • windows-x64    • Microsoft Windows [Version 10.0.19042.1466]
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 99.0.4844.74
    • Edge (web)         • edge        • web-javascript • Microsoft Edge 99.0.1150.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details.

**Comment by stevemessick** [comment]
New projects are being created with the Android module file located in the `android` directory. The plugin only looks in the top-level project directory so it does not find it.

@asashour You may have additional issues. You might need to use `flutter config` to tell it where to find Android Studio. You might also need to accept the Android licenses, as reported by `flutter doctor -v`, but I'm not sure about that.

**Comment by stevemessick** [comment]
Oops, I forgot we already made that change. Something else is going wrong here.

I can't quite reproduce this problem, because I don't get an error. But Android Studio does not open, either, so it is still P1.

Works fine on my Mac, but not my Windows machine.

@asashour Does the problem occur if you use `flutter config` to tell Flutter where Android Studio is located?

**Comment by asashour** [comment]
Ever after fixing all `flutter doctor` issues, and setting `flutter config`, the error happens.

- In IntelliJ logs there is:

```
WARN - vdmanager.AvdManagerConnection - No Android SDK Found 
```

- If it is the Android SDK, then it is already defined in IntelliJ community Edition and Android Studio. The user shouldn't do something else
<image src=https://user-images.githubusercontent.com/2410127/158804463-fe800639-2b3d-45a0-979f-302af2d57aa5.png height=200>

- `flutter config` now shows:
```
Settings:
  android-sdk: C:\Users\ahmed_ashour\AppData\Local\Android\Sdk
```

- The original post `flutter doctor` has been updated

**Comment by stevemessick** [comment]
This actually works for me. It was not working because of a configuration issue, which might affect you @asashour. Check your environment variables:  STUDIO_JDK, JDK_HOME, or JAVA_HOME. Only one of them should be defined, and it should point to a valid JBR. There is one in the IntelliJ distribution.

If that doesn't help try doing this on the command line:
`flutter config --android-studio-dir "C:\Program Files\Android\Android Studio"`

Let us know if that helps.
