### ISSUE TITLE
Flutter app crash after loading the model "mapper 3.x is not supported"

### ISSUE THREAD

**Issue by Abrmalkawi** [flutter/flutter-intellij#6045]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
The app tried to detect live objects. The camera is opened and start to capture the scene then the app is crashed and stop with  long info some of them are:-
W/Gralloc3(15254): mapper 3.x is not supported
W/Gralloc3(15254): allocator 3.x is not supported
W/System  (15254): A resource failed to call close. 
W/System  (15254): A resource failed to call close. 
E/flutter (15254): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(Failed to run model, Interpreter busy, java.lang.RuntimeException: Interpreter busy.
.
.
.
I/Process (15254): Sending signal. PID: 15254 SIG: 9
Lost connection to device.

## Version info
 Connected device (3 available)
    • SM N960F (mobile) • 285914913a3f7ece • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 98.0.1108.62

• No issues found!

Please, any help to solve that.

**Comment by stevemessick** [comment]
This is not an issue with the Flutter plugin.

It looks similar to these issues: 
- https://github.com/flutter/flutter/issues/52405
- https://github.com/flutter/flutter/issues/50405
- https://www.reddit.com/r/flutterhelp/comments/p7c6vo/mapper_3x_is_not_supported/

I hope you can find something useful in those.
