### ISSUE TITLE
Inconsistent/Broken behavior when running unit tests in Bumblebee Patch 2

### ISSUE THREAD

**Issue by firephreek** [flutter/flutter-intellij#6048]
## Description
Running Flutter unit tests inside a folder returns various errors including 'pubspec.yaml file not found' or  'No Tests Found'. The later results in a large body of JSON content with numerous references to 'dart:ui' not found.

## Steps to Reproduce
1. Open an existing Flutter Project and ensure either of the following two dependencies are included in `pubspec.yaml`:
    -  `test: ^1.17.10`
    - `bloc_test: ^9.0.23`
2. Right click on the `test` folder or any sub-folder and Choose `Run Tests in your_app`

## Expected
Unit tests should run successfully and the output presented correctly (tree like structure) using the flutter test harness like they have in the past.

## Actual
Unit tests are run using `dart.exe run test -r json <target_folder>` and either of the two error messages in the description are shown.
  - 'pubspec.yaml not found' can often be resolved by running `flutter pub cache repair && flutter clean && flutter pub get`

## Additional Info
This behavior _seems_ to be the result of something in the new Bumblebee patch in conflict with the Flutter plugin. Specifically, adding either `test` or `bloc_test` as `dev_dependencies` in `pubspec.yaml` create a transitive reference that Android Studio picks up which causes it to present the Run/Debug options when right clicking a folder. Previously, this wasn't a problem and a user could safely run those tests via that menu or using the short cut option `Ctrl+Shift+F10`.  Now, however, all tests in the folder are run using the dart executable as mentioned above. Individual files can still be run as unit tests however the Run/Debug option has a sub option to run them as either dart or flutter tests. The former causes issues for flutter tests and requires the configuration to be deleted before it can be re-tried as a flutter test.

## Version info
Info attached: [flutter_doctor.txt](https://github.com/flutter/flutter-intellij/files/8318178/flutter_doctor.txt)

**Comment by stevemessick** [comment]
How do you get a Run menu item from right-clicking a folder? I don't get one.

The Dart plugin adds a Run option when a Dart file is selected. Flutter adds one, too, but it can't delete the one from the Dart plugin. We'd have to work with JetBrains to change that.

Also, see my comment in [#6046](https://github.com/flutter/flutter-intellij/issues/6046#issuecomment-1076886402). There *may* be tips to mitigate the issue.

**Comment by firephreek** [comment]
Try adding one of the packages I mentioned in the report. I also tested the process with a brand new flutter project and was able to replicate the problem.  Right-clicking on a test folder is standard IDEA behavior, I think it's just something about how flutter is returning action items is stopping it.  

I tried #6406 but it doesn't change anything it seems.
