### ISSUE TITLE
I don't see the hot reload and restart icons in the main toolbar

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#605]
When running an app, I don't see the hot reload and restart icons in the main toolbar:

<img width="552" alt="screen shot 2017-01-09 at 8 04 04 pm" src="https://cloud.githubusercontent.com/assets/1269969/21793499/d00d139a-d6a6-11e6-88e3-00533d997b86.png">

@pq

**Comment by devoncarew** [comment]
Ah, I use the smaller version of the toolbar (toggleable from the View menu). The actions are visible when I switch to the full toolbar: 

<img width="384" alt="screen shot 2017-01-09 at 8 05 01 pm" src="https://cloud.githubusercontent.com/assets/1269969/21793537/16ab9326-d6a7-11e6-880e-510c6afebaa2.png">

but we should support both locations.

**Comment by mit-mit** [comment]
I hit the same issue, and wasn't ever aware that there was a thing as a "fuller" toolbar, so I would have been stuck on this. I also think the nav toolbar is the default setting for new users.

**Comment by pq** [comment]
Yep.  That was an oversight and I missed the Nav Toolbar. 

Thanks for the fix Devon!
