### ISSUE TITLE
Unable to resolve usages with flutter's global methods

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#6058]
## Steps to Reproduce

![image](https://user-images.githubusercontent.com/15884415/160269817-9d4bcaef-ec71-4a49-b67b-ad57fe771a00.png)
![image](https://user-images.githubusercontent.com/15884415/160269826-4f14d1fc-4db2-4c6f-94d2-2334e1405989.png)

All global methods have no usage found when trying to inspect. However, when I doing a global search, there are many usages displays:
![image](https://user-images.githubusercontent.com/15884415/160269893-88992805-9991-4e5d-8702-6177081b5fb1.png)
![image](https://user-images.githubusercontent.com/15884415/160269862-6ee616e9-ebe9-47ae-9ecc-72346a2a303d.png)

## Version info

IDEA version: 2021.3.2#IU-213.6777.52
IDEA plugin version: 65.2.4

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.556], locale zh-CN)
    • Flutter version 2.10.3 at X:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
```

**Comment by stevemessick** [comment]
@AlexV525 Have you tried restarting the analysis server? Or restarting the IDE?

**Comment by stevemessick** [comment]
Also, I can't reproduce the problem.

<img width="342" alt="Screen Shot 2022-03-28 at 2 21 54 PM" src="https://user-images.githubusercontent.com/8518285/160489572-c2ac28b1-6a64-4c7c-8376-ca0512b72d66.png">

I used a sample project that already had imported material. I opened 1Dialog.dart1, navigated to 1showDialog1, then did 1Find Usages1 from the pop-up menu. Could you try doing it from a new sample project?

**Comment by AlexV525** [comment]
I can't reproduce this today.
![image](https://user-images.githubusercontent.com/15884415/160517586-310b81cd-c88f-481d-8751-68e5017039ab.png)
Closing as it's not reproducible. Thanks for the look.

Though I can still reproduce this issue: #5469 (moved to dart-lang/sdk#45972)
Please take a look if you're available. @stevemessick
