### ISSUE TITLE
ChromeProxyService: Failed to evaluate expression 

### ISSUE THREAD

**Issue by hiddenMonster** [flutter/flutter-intellij#6063]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
A new error in debug mode after a few days from upgrading chrome and android studio. No flutter doctor issues. thank you

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

ste@ste-HP:~/flutter_projects/chrome_proxy_service_error$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.4.0-105-generic, locale it_IT.UTF-8)
    • Flutter version 2.10.3 at /home/ste/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 settimane fa), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ste/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /home/ste/Android/Sdk
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (2 available)
    • WAS LX1A (mobile) • 2XJDU18104001819 • android-arm64  • Android 8.0.0 (API 26)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by stevemessick** [comment]
Was there a stack trace reported?

What steps will reproduce the problem?

**Comment by hhkk** [comment]
I get I guess the same: 

after upgrading and including a switch from master to stable, i can no longer debug my flutter project. I hit false breakpoints, I do not break correctly at breaks I set. and i see these errors.

...
[ ] ChromeProxyService: Failed to evaluate expression 'index': InternalError: No frame with index 348.
[ ] ChromeProxyService: Failed to evaluate expression 's': InternalError: No frame with index 348.
[ ] ChromeProxyService: Please follow instructions at https://github.com/dart-lang/webdev/issues/956 to file a bug.
[ ] ChromeProxyService: Please follow instructions at https://github.com/dart-lang/webdev/issues/956 to file a bug.
...

previous version - in which debugging worked
# Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
# Framework • revision c860cba910 (2 weeks ago) • 2022-03-25 00:23:12 -0500
# Engine • revision 57d3bac3dd
# Tools • Dart 2.16.2 • DevTools 2.9.2

new version - debugger not working
# Flutter 2.6.0-12.0.pre.3 • channel master •
# https://github.com/flutter/flutter.git
# Framework • revision fa9790ca47 (3 months ago) • 2021-09-17 01:37:03 -0400
# Engine • revision e70febab63
# Tools • Dart 2.15.0 (build 2.15.0-118.0.dev)

if you need logs from me, pls tell me the exact sequence of which buttons and menu items to press and which file to look for. I find the documentation on capturing logs confusing as to whether I need to enable logging before inducing the error or only to capture logs after the error has just occurred. Also I don't know how to delete the old logs in order not to send a relevant information.

https://github.com/dart-lang/webdev/issues/956 

https://github.com/flutter/flutter/issues/72094

**Comment by Gerard-Yeboua** [comment]
Bonjour, voici mes erreurs que j'ai eu lorsque j'ai lancé mon code flutter en web :
ChromeProxyService: Failed to evaluate expression 'entrypoint.main': InternalError: Expression evaluation in async frames is not supported. No frame with index 125..
