### ISSUE TITLE
Opening existing projects no longer works

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#607]
I can no longer open the flutter example projects; they are not properly detected as flutter projects.

This is a regression, I think in 0.1.8.

Note that this is *not* the same as issue https://github.com/flutter/flutter-intellij/issues/316. The *present* issue covers the flutter example projects, which do have an `.iml` file and a `.idea. dir.

## Steps to Reproduce

1. Upgrade flutter to latest build (I have `Framework revision 684259794b (8 hours ago), 2017-01-09 21:35:43`)
1. Start IntelliJ
1. File > Open
1. Select /flutter-sdk-dir/examples/flutter-gallery/

Expected result: Project loads, and I can hit Run to see the app
Actual result: Projects loads, but is not detected as a flutter project so run is disabled

## Version info

Flutter doctor:

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/mit/dev/github/flutter
    • Framework revision 684259794b (8 hours ago), 2017-01-09 21:35:43
    • Engine revision f13518d7e7
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/mit/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/mit/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002

[-] IntelliJ IDEA Ultimate Edition (version 2016.3.2)
    • Dart plugin version 163.11306
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • iPhone 6 • F1198136-43B5-4184-B548-A36956F6FA15 • ios • iOS 9.3 (simulator)```

**Comment by pq** [comment]
Interesting!

FWIW: the inspection that does the detection is associated with an open editor.  If you open a pubspec or dart file you should see this banner:

<img width="1239" alt="screen shot 2017-01-10 at 6 48 19 am" src="https://cloud.githubusercontent.com/assets/67586/21810512/fadf7018-d700-11e6-9728-de0ed9fc42d6.png">

Looking into why it's not opening right in the first place now.

**Comment by mit-mit** [comment]
Not sure if this is relevant, but I noticed that if I `File > New > Project` on top of the existing example, then it works. And if I then diff to see what the differences are (I would have expected none), I see:

```
$ git diff
diff --git a/examples/flutter_gallery/.idea/runConfigurations/flutter_gallery.xml b/examples/flutter_gallery/.idea/runConfigurations/flutter_gallery.xml
deleted file mode 100644
index 2135973ba..000000000
--- a/examples/flutter_gallery/.idea/runConfigurations/flutter_gallery.xml
+++ /dev/null
@@ -1,6 +0,0 @@
-<component name="ProjectRunConfigurationManager">
-  <configuration default="false" name="flutter_gallery" type="FlutterRunConfigurationType" factoryName="Flutter">
-    <option name="filePath" value="$PROJECT_DIR$/lib/main.dart" />
-    <method />
-  </configuration>
-</component>
\ No newline at end of file
diff --git a/examples/flutter_gallery/flutter_gallery.iml b/examples/flutter_gallery/flutter_gallery.iml
index 984d8a6e7..3e9be6592 100644
--- a/examples/flutter_gallery/flutter_gallery.iml
+++ b/examples/flutter_gallery/flutter_gallery.iml
@@ -9,7 +9,6 @@
       <excludeFolder url="file://$MODULE_DIR$/test/calculator/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/packages" />
     </content>
-    <orderEntry type="inheritedJdk" />
     <orderEntry type="sourceFolder" forTests="false" />
     <orderEntry type="library" name="Dart SDK" level="application" />
     <orderEntry type="library" name="Dart Packages" level="project" />
```

**Comment by pq** [comment]
Do you have an `.idea` folder too?  That seems to be the ticket for me.  (Note that the `.idea` folder is not in the flutter repo --- but possibly should be.)

**Comment by pq** [comment]
To summarize:

1. The IML file in (for example) `hello_world` is not sufficient to identify to IDEA that it is a Flutter project.  (Note that at one point it _may have been_ --- we've updated to a new version of the Community Edition platform and it's possible that we're being affected by a change there.)
1. Adding an `.idea` directory with the right metadata within seems to resolve the issue.

An `idea` directory can be created by:

* opening the project using the **New Project** flow, or by
* opening a dart file (`.dart`, `pubspec.yaml` or `flutter.yaml`) and accepting the IDE's offer to add a Flutter module type to the project

A few things to do:

1. add `.idea` metadata to the Flutter repo
1. document the work-arounds above
1. improve the open flow in general (as captured in #316 et al)

FWIW: I'm not confident that updating the metadata in the repo will ever be sufficient to ensure that an example Flutter project is reliably recognized as having a Flutter module in all IDEA platforms.  From what I can tell we're depending on internal (and un-documented) implementation details that are subject to change. I think we'll have to double-down on the flow for opening projects missing metadata regardless.

**Comment by pq** [comment]
> add .idea metadata to the Flutter repo

https://github.com/flutter/flutter/pull/7428

**Comment by mit-mit** [comment]
Confirmed all working after pulling latest changes in flutter repro. Closing!

Samples tested:
  * `flutter_gallery`
  *  `hello_world`
  * `layers`
  * `stocks`

**Comment by pq** [comment]
👍 Thanks!
