### ISSUE TITLE
Unable to fold multiline method signatures and calls and other blocks

### ISSUE THREAD

**Issue by crtl** [flutter/flutter-intellij#6089]
I have already opened the same issue #6008 previously which was reported to be fixed but in my current environment it still persists and I am using the latest Android Studio and Flutter Plugin versions.

## Steps to Reproduce
Create a multiline method signature
```dart

myFn({ // I cannot hold the function including signature
  required String firstArg,
  required String secondArg,
}) {  // I can fold the contents of function body here

}
```

## Version info

```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-DE)
    • Flutter version 2.10.3 at C:\Users\User\fvm\versions\2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8193401
    • Flutter plugin version 66.0.1
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

```

**Comment by helin24** [comment]
@stevemessick was #6011 merged into the latest plugin version? It appears to be part of a separate branch and isn't listed in the changelog.

**Comment by stevemessick** [comment]
My git history shows it having been merged in. I don't think it relates to this issue; this is in the Dart plugin. It looks like `DartFoldingBuilder` does not handle multi-line method signatures. (Although I didn't look too closely.) The Flutter plugin does some folding in the console but does not define the `lang.foldingBuilder` EP.

@jwren might know more.

**Comment by helin24** [comment]
Oops yes, I see it. So this should stay open?

**Comment by stevemessick** [comment]
I re-opened #6008 so we can close this one.
