### ISSUE TITLE
Project creation should validate legal project names.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#609]
In particular, we should make sure names are pub-friendly:

<img width="727" alt="screen shot 2017-01-10 at 9 51 45 am" src="https://cloud.githubusercontent.com/assets/67586/21817860/8c89ac7c-d71a-11e6-9041-5497dd9b243b.png">

**Comment by pq** [comment]
Putting on-deck as it's hit a few folks (besides me!) --- see #687.

**Comment by eseidelGoogle** [comment]
We already do some of this in `flutter create`, maybe it should do more?
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart#L179

**Comment by pq** [comment]
Good thinking @eseidelGoogle.  Probably we should.  The rub here is that we've already created the project in IntelliJ when we call `flutter create` so it will just bomb out on us when run.  A better flow would be live validation in the wizard (e.g., before running `create`).  IOW: I think we probably need validation in both places unfortunately.  But anyway, yeah, both validations should totally agree!

**Comment by pq** [comment]
Forward pointer:  Section "16.33 Identifier Reference" of the [Dart language spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf) has the grammar we want to crib.

**Comment by mit-mit** [comment]
@pq did you complete this?

**Comment by pq** [comment]
Not yet.  My PR is hung up on build issues.  It's also won't do anything in the context of WebStorm and other "small IDEs". I'll do some more poking later this week.
