### ISSUE TITLE
IntelliJ IDE - how to send feedback

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter-intellij#610]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I wanted to leave feedback via the IntelliJ IDE (I'm using Community Edition), but I couldn't find a way to do that.

## Version info

~ $ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/shaza/GoogleDrive/TMP-flutter/flutter
    • Framework revision 98016b1c4a (7 weeks ago), 2016-11-21 09:21:49
    • Engine revision cea5ed2b9b
    • Tools Dart version 1.21.0-dev.6.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/shaza/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • iPhone 6s Plus • 00A1718E-C7AA-4B05-B650-6AFA1BA1F84B • ios • iOS 9.3 (simulator)

**Comment by devoncarew** [comment]
You should be able to via `Tools > Flutter > Submit Feedback...`:

<img width="511" alt="screen shot 2017-01-10 at 12 42 49 pm" src="https://cloud.githubusercontent.com/assets/1269969/21824027/6a3ab40a-d732-11e6-94b5-e9f8a9a88099.png">

Does that menu show up for you?
