### ISSUE TITLE
Error: Template not found: Dart File

### ISSUE THREAD

**Issue by ivk1800** [flutter/flutter-intellij#6111]
## Steps to Reproduce

1) Right click for folder of file
2) Select: New-> Dart File
3) type name and press enter

result:
error:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/11444783/163631366-dedf9823-49fa-460e-a7a7-b75fabe1fd36.png">

## Version info

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
    Dart (221.5480)
    io.flutter (66.0.4)

Kotlin: 221-1.6.20-release-285-IJ5080.210

**Comment by AunThuYeinTun** [comment]
I found  this issues and stuck at creating dart file today t.Do u find any solution about it yet ?.Thank u

**Comment by ivk1800** [comment]
@AunThuYeinTun just copy already existing dart file for workaround

**Comment by AunThuYeinTun** [comment]
Yes.I solved like this. Created the dart file from "file" (eg test.dart) not from  dart file.
BTW Thank u for u solution.
Cheers

**Comment by kaustav07** [comment]
I am also facing this issue from today..

**Comment by dchandrani** [comment]
I am facing the same issue today. The solution from @AunThuYeinTun works but should be able to create dart file from New -> Dart file

**Comment by lgl-fengwang** [comment]
I have this problem after updating IDEA to IntelliJ IDEA 2022.1 (Ultimate Edition)

**Comment by zaypen** [comment]
facing the same one.

> Build #IU-221.5080.210, built on April 12, 2022
> Runtime version: 11.0.14.1+1-b2043.25 aarch64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Dart: 221.5480
Flutter: 66.0.4

**Comment by mahad-ahmed** [comment]
I too am a fellow sufferer.
Can of course create a dart file manually but I'm slightly inconvenienced :disappointed: .
```
IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-107-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1994M
Cores: 8
Non-Bundled Plugins:
    Dart (221.5480)
    io.flutter (66.0.4)

Kotlin: 221-1.6.20-release-285-IJ5080.210
Current Desktop: ubuntu:GNOME
```

**Comment by KnucklesEQ** [comment]
Same problem here.

The problem appeared when I installed the latest version (v221.5480) of the Dart plugin for IntelliJ IDEA.

**Comment by stevemessick** [comment]
This problem also appears in version 221.5177. It did not happen in IntelliJ 2021.3, even after updating the Dart plugin. It appears in a Dart project, i.e. not Flutter. It is a problem in the Dart plugin.

@jwren @alexander-doroshko where should this problem be reported to get it fixed?

**Comment by alexander-doroshko** [comment]
Sorry about the problem. It's tracked as https://youtrack.jetbrains.com/issue/WEB-55484 and will be fixed ASAP.

For now, a workaround is to use the 'New File' action. It's the same as 'New Dart File' with the only difference that you'll need to type the file extension manually.

**Comment by stevemessick** [comment]
Thanks, Alex!

Closing this as it is now a dup.

**Comment by ArslanAsghar123** [comment]
i think intelliJ has some kinda bug
what you say about it?

**Comment by michael-shields** [comment]
I too have this issue.... for the record!

**Comment by SarangrVAASITS** [comment]
I am also facing this issue from today.. how to fix this

**Comment by alexander-doroshko** [comment]
The Dart plugin with the fix has been published (v. 221.5588), please update.

Note that this problem happens only in IntelliJ IDEA 2022.1. So the plugin update for older IDE versions hasn't been published.

**Comment by ahsanultu** [comment]
Same Problem In **Android Studio** After Dart Plugin Update.

**Comment by fatduckling** [comment]
Having the same issue as well!

**Comment by shubhamsinghshubham777** [comment]
> Same Problem In **Android Studio** After Dart Plugin Update.

+1

**Comment by alexander-doroshko** [comment]
Sorry about the problem that happened again. The issue is tracked as [IDEA-371045](https://youtrack.jetbrains.com/issue/IDEA-371045). The workaround is to use New -> File action and write a file name with the `.dart` extension.

**Comment by alexander-doroshko** [comment]
The Dart plugin updates with the fix have been published (plugin versions 243.26753.1 and 251.25267.1).

Please comment if there are any issues with the new plugin builds

**Comment by shubhamsinghshubham777** [comment]
> The Dart plugin updates with the fix have been published (plugin versions 243.26753.1 and 251.25267.1).
> 
> Please comment if there are any issues with the new plugin builds

Thank you. It has been fixed for me now 👍

**Comment by Chopperz** [comment]
> The Dart plugin updates with the fix have been published (plugin versions 243.26753.1 and 251.25267.1).
> 
> Please comment if there are any issues with the new plugin builds

@alexander-doroshko  This problem is appearing again when I've updated the Dart plugin latest version.

- Android Studio Narwhal | 2025.1.1 Patch 1
- Flutter plugin version 86.0.2
- Dart plugin version 251.27623

**Comment by alexander-doroshko** [comment]
The problem happened again with the Dart plugin build 251.27623. The problematic build has been removed from the Marketplace, so updating the Dart plugin one again will help

**Comment by Chopperz** [comment]
Thank you, I've updated new version and it works fine now 🎉

**Comment by tazik561** [comment]
I have this issue with this version of the plugin 251.27623. 
Now I have to create a new file and manually add .dart

**Comment by alexander-doroshko** [comment]
> I have this issue with this version of the plugin 251.27623

Update to 251.27623.5
