### ISSUE TITLE
see also 6063.   ChromeProxyService: Failed to evaluate expression 'index': InternalError: No frame with index ...

### ISSUE THREAD

**Issue by hhkk** [flutter/flutter-intellij#6122]
I don't know how to compare this with #6063.  Perhaps this should be deleted.  I also added this content as a note in 6063.

after upgrading and including a switch from master to stable, i can no longer debug my flutter project. I hit false breakpoints, I do not break correctly at breaks I set. and i see these errors.

...
[ ] ChromeProxyService: Failed to evaluate expression 'index': InternalError: No frame with index 348.
[ ] ChromeProxyService: Failed to evaluate expression 's': InternalError: No frame with index 348.
[ ] ChromeProxyService: Please follow instructions at https://github.com/dart-lang/webdev/issues/956 to file a bug.
[ ] ChromeProxyService: Please follow instructions at https://github.com/dart-lang/webdev/issues/956 to file a bug.
...

previous version - in which debugging worked
# Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
# Framework • revision c860cba910 (2 weeks ago) • 2022-03-25 00:23:12 -0500
# Engine • revision 57d3bac3dd
# Tools • Dart 2.16.2 • DevTools 2.9.2

new version - debugger not working
# Flutter 2.6.0-12.0.pre.3 • channel master •
# https://github.com/flutter/flutter.git
# Framework • revision fa9790ca47 (3 months ago) • 2021-09-17 01:37:03 -0400
# Engine • revision e70febab63
# Tools • Dart 2.15.0 (build 2.15.0-118.0.dev)

if you need logs from me, pls tell me the exact sequence of which buttons and menu items to press and which file to look for. I find the documentation on capturing logs confusing as to whether I need to enable logging before inducing the error or only to capture logs after the error has just occurred. Also I don't know how to delete the old logs in order not to send a relevant information.

https://github.com/dart-lang/webdev/issues/956

https://github.com/flutter/flutter/issues/72094

**Comment by stevemessick** [comment]
Update your Flutter SDK to fix this problem.
