### ISSUE TITLE
No completion or Navigate to Declaration

### ISSUE THREAD

**Issue by beders** [flutter/flutter-intellij#613]
I'm unable to get Dart completion working in the flutter project.

## Steps to Reproduce

I followed the instructions in the flutter Set up and Getting Started guide.
I then created a new flutter Project.
Everything works fine. I can start the app in the simulator, hot reload works fine.
BUT, I can't get code completion to work, nor can I go to any declaration.
In Properties, Dart and Flutter settings are looking fine. Project support is enabled for my test project.

This is flutter-related as I can create a new Dart project fine and get completion working if I point IDEA to my Dart SDK (outside of the flutter distribution)

## Version info

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/beders/dev/flutter
    • Framework revision bba6bff66b (3 hours ago), 2017-01-10 16:08:51
    • Engine revision f13518d7e7
    • Tools Dart version 1.22.0-dev.5.0

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.2)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.7

[✓] Connected devices
    • iPhone 6 • XXXXX-XXXX-XXXX-XXXX-XXXXXXXXX • ios • iOS 10.0 (simulator)

**Comment by devoncarew** [comment]
> Tools Dart version 1.22.0-dev.5.0

Can you update flutter (from the cli: `flutter upgrade`), and re-test?

**Comment by devoncarew** [comment]
Some tips on diagnosing analysis server issues here: https://github.com/flutter/flutter-intellij/wiki/Analysis-Server

**Comment by pq** [comment]
Interestingly, this is *exactly* what I was seeing when testing `1.22.0-dev.5.0` that @devoncarew and @scheglov could not reproduce!

@beders : I think the change that integrated `1.22.0-dev.5.0` was reverted.  Can you resync your flutter repo and try again?

**Comment by beders** [comment]
Looks like a `flutter upgrade` fixed it.
Thank you guys!

(now I hope you'll have something like a repository of flutter components and native service integrations on your roadmap next :)

**Comment by devoncarew** [comment]
@pq, we may need to do a bisect on the sdk repo, building the sdk and testing it with flutter, looking for the regression.

**Comment by pq** [comment]
> @pq, we may need to do a bisect on the sdk repo, building the sdk and testing it with flutter, looking for the regression.

Well I could reliably repro on `dev-5.0` as of a few days ago so I wonder if this is the same snag I hit?  Otherwise, I'm hoping to roll out an integration of the `dev-6.0` Dart SDK into Flutter today and will test with that.  Let's chat about whether a bisect makes sense.

Thanks!

**Comment by devoncarew** [comment]
I suspect it may be related, and possibly a regression in dart:io. We'll need to take a closer look.
