### ISSUE TITLE
There is no inscription "New Flutter Project"

### ISSUE THREAD

**Issue by MrKlarki** [flutter/flutter-intellij#6133]
## Steps to Reproduce

Hello

I am using Android Studio Bumblebee |2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 16, 2022

If I go to "Plugins - marketplace" and find "Flutter" to install, then everything works.

But I install it from disk. I download it from the link https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/165970
Select "Compatibility: Android Studio" and version 66.0.1
Next in Android Studio in "Plugins - Install plugin from disk..." and select "flutter-idea-66.0.1.jar "
After installation, I don't have a "New Flutter Project"
Am I doing the right thing ?

Screenshot of the plugin selection:
![](https://i.imgur.com/OmJr7Ol.png)
Screenshot of the project creation (if through the marketplace):
![](https://i.imgur.com/2Kgt9Dt.png)

**Comment by stevemessick** [comment]
The file you downloaded from the JetBrains plugin page should be named `flutter-intellij.zip`. That is the file to install from disk. It looks like you unpacked that file and only installed the IntelliJ-specific module. That one will not have the Android Studio support, like "New Flutter Project".

**Comment by MrKlarki** [comment]
> The file you downloaded from the JetBrains plugin page should be named `flutter-intellij.zip`. That is the file to install from disk. It looks like you unpacked that file and only installed the IntelliJ-specific module. That one will not have the Android Studio support, like "New Flutter Project".

I'm sorry that I opened issued
Thanks. It really helped. Safari browser unpacks the archive by default

**Comment by stevemessick** [comment]
Great! Glad you're back on track. And thanks, I did not know Safari did that.
