### ISSUE TITLE
Run button in intelliJ fails, just says "Starting device daemon..."

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#616]
This started for @sfshaza yesterday, but I just reproduced it.

@devoncarew @pq.

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /src/flutter
    • Framework revision 7f2915d331 (3 hours ago), 2017-01-11 10:54:42
    • Engine revision f13518d7e7
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002

[✓] IntelliJ IDEA Community Edition (version 2016.3.2)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.3

[✓] Connected devices
    • iPhone 6s • FF0E5127-3490-4297-9313-C4776D7950D4 • ios • iOS 10.0 (simulator)
```

**Comment by pq** [comment]
It looks like you've got a pretty old Flutter Plugin installed.  `0.1.8` is the latest:

```
[✓] IntelliJ IDEA Community Edition (version 2016.3.2)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.8
```

You should be able to provoke update via the menu:

<img width="210" alt="screen shot 2017-01-12 at 5 27 13 am" src="https://cloud.githubusercontent.com/assets/67586/21891501/cd571e88-d887-11e6-9c62-5cc383b5c5da.png">

If that doesn't get things moving, let me know!

(I just tested w/ `0.1.8` with flutter `HEAD` and it works for me.)

**Comment by pq** [comment]
We should also confirm that IntelliJ is treating the project as a Flutter-y.  If it is we'd expect to see a Flutter icon in the project explorer:

<img width="381" alt="screen shot 2017-01-12 at 5 37 25 am" src="https://cloud.githubusercontent.com/assets/67586/21891854/79e9f6a6-d889-11e6-97b0-f1623c67a64d.png">

**Comment by mit-mit** [comment]
> It looks like you've got a pretty old Flutter Plugin installed.

Eric, did you perhaps install the flutter plugin at some point from a file, rather than from the JetBrains server? That would explain why you didn't get updated. 

If so, to resolve it, just uninstall it, and then install it again from the server (aka 'repository').

**Comment by devoncarew** [comment]
We did solve the out-of-date-plugin issue for him an hour or two after this issue was filed; I'll close this optimistically, since I don't think Eric is seeing this particular problem anymore.
