### ISSUE TITLE
Documentation comment symbol links not recognized when in subsequent lines of bulleted lists.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#6164]
## Steps to Reproduce

Create a documentation comment like the following:

```dart
/// See also:
///
///  * There is a great class you should really know about, [String]. If you don't
///    know about the [String] class, you've not been paying attention.
```

If you paste this into IntelliJ, it will linkify the first instance of `[String]`, but not the second one. It seems that any reference on the subsequent lines of a bulleted list are not recognized as being symbols, probably because the parser is assuming that any line beginning with three spaces is a &lt;pre&gt; section in Markdown.  I think it's supposed to be four or more, really, but only if it's not part of a bulleted or numbered list. Maybe that's not the cause, but in any case, it doesn't work.

And it's not just linking: rename operations on any symbol that isn't recognized in this way will also fail: it'll skip renaming those symbols referenced in subsequent lines of the list.

## Version info

<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel shortcuts_registry, 3.1.0-0.0.pre.671, on Debian GNU/Linux rodete 5.16.18-1rodete2-amd64, locale en_US.UTF-8)
    • Flutter version 3.1.0-0.0.pre.671 at /usr/local/google/home/gspencer/code/flutter
    • Upstream repository git@github.com:gspencergoog/flutter.git
    • Framework revision 4aaaa5a9ba (7 minutes ago), 2022-05-13 09:22:43 -0700
    • Engine revision b8ca6a5e0e
    • Dart version 2.18.0 (build 2.18.0-106.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /usr/local/google/home/gspencer/Android/Sdk
    • Java binary at: /usr/local/google/home/gspencer/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 13.0.1-3+build2
    • cmake version 3.22.1
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /usr/local/google/home/gspencer/Android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /opt/idea-IC-212.4746.92
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5588

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 5.16.18-1rodete2-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by stevemessick** [comment]
This is done by the Dart plugin. I'll create an issue in their repo later. I noticed that if the second line was indented at the same level as the star (three spaces) then the link was enabled.

@jwren

**Comment by stevemessick** [comment]
https://youtrack.jetbrains.com/issue/WEB-55914/Documentation-comment-symbol-links-not-recognized-when-in-subseq

**Comment by alexander-doroshko** [comment]
@stevemessick I see that the Analysis Server doesn't give navigation data for the second `[String]` in this example.
Cc @bwilkerson, @scheglov.

```
/// See also:
///
///  * There is a great class you should really know about, [String]. If you don't
///    know about the [String] class, you've not been paying attention.
class A {}
```
<img width="951" alt="image" src="https://user-images.githubusercontent.com/4499789/168875763-4196af0d-ab85-4c5c-9113-6a377e9a9146.png">

**Comment by stevemessick** [comment]
This is an issue in the analyzer, not the plugin. The proper repo is dart-lang/sdk. I used to be able to move issues but lost that ability as security was tightened.

@alexander-doroshko sorry for the noise in YouTrack.

**Comment by scheglov** [comment]
I can reproduce this with:
```dart
///    know [String]
void f() {}
```

Maybe we consider a line with so many spaces a block of code and disable parsing comment references for it?

**Comment by gspencergoog** [comment]
I'm happy to re-file in dart-lang/sdk.

**Comment by scheglov** [comment]
Yes, apparently it is intentionally disabled in the parser.
https://github.com/dart-lang/sdk/blob/28e8202c1408c3dc066cc5c93b10026b17b75095/pkg/_fe_analyzer_shared/lib/src/parser/parser_impl.dart#L8478

**Comment by gspencergoog** [comment]
Yes, that's correct, but only if the line isn't part of a dartdoc paragraph with a bullet marker.

**Comment by gspencergoog** [comment]
For instance, in the Markdown view in IntelliJ:

![image](https://user-images.githubusercontent.com/8867023/168917985-6a97b78a-fc97-49ee-a745-746a8f519eae.png)

**Comment by gspencergoog** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/49047

**Comment by stevemessick** [comment]
Thanks @gspencergoog !
