### ISSUE TITLE
Code suggestion for initState/dispose/setState no longer works in Flutter3

### ISSUE THREAD

**Issue by keybow007** [flutter/flutter-intellij#6167]
With Flutter 3.0, code suggestion for initState/dispose/setState no longer works. It worked for Flutter 2.10.
This issue was found in both Windows(10) and Mac(12.3.1).

## Steps to Reproduce

1. Start typing in ini.
2. Hit control-space for auto suggestions
3. Nothing comes up yet.

![スクリーンショット 2022-05-16 7 52 53](https://user-images.githubusercontent.com/12907755/168500713-3e691dbe-75c9-423c-bb37-d7dac649f2a6.png)

（It worked in Flutter 2.10.x）
![スクリーンショット 2022-05-16 7 52 39](https://user-images.githubusercontent.com/12907755/168500746-91588056-14f2-41ee-a2e4-3c6c3d478fa1.png)

The screenshots are for initState, but the same thing happens with dispose and setState.

## Version info

`Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
[✓] VS Code (version 1.67.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
`

**Comment by stevemessick** [comment]
This is not a Flutter plugin issue, but it is serious (IMO). I copied this to a new issue in the Dart SDK repo:
https://github.com/dart-lang/sdk/issues/49027

**Comment by khanahsan** [comment]
i'm also facing this issue, if you get any solution please let me  know also.

**Comment by khanahsan** [comment]
i'm also facing this issue, if you get any solution please let me know also.

**Comment by Nathan617** [comment]
Hi, having the same issue. setState and Colors are not autocompleting anymore. for example if I type setS I have no autocomplete. Same if I type red it doesn't propose Colors.red anymore. Just 2 examples I have here.

**Comment by lore-co** [comment]
setState still isn't showing

**Comment by funmise** [comment]
initState not working on VsCode flutter 3.32.6
