### ISSUE TITLE
Embedded inspector cannot display

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#6168]
```
2022-05-16 09:34:19,571 [  80616]   INFO - #i.f.j.EmbeddedBrowserEngine - JxBrowser user data path: X:\IDEs\apps\IDEA-U\ch-0\221.5080.210.plugins\flutter-idea\jxbrowser\user-data
2022-05-16 09:34:33,433 [  94478]   INFO - #i.f.j.JxBrowserManager - Browser message(WARNING): The page requested an origin-keyed agent cluster using the Origin-Agent-Cluster header, but could not be origin-keyed since the origin 'http://127.0.0.1:9101' had previously been placed in a site-keyed agent cluster. Update your headers to uniformly request origin-keying for all pages on the origin.
```

## Steps to Reproduce

Just open a Flutter app.
I tried to reinstall the plugin but it doesn't help.

## Version info

Flutter: 2.10.5 (Windows)
IDEA: 2022.1 (221.5080.210)
Plugin: 67.1.4

**Comment by AlexV525** [comment]
This is what it looks like now:
![image](https://user-images.githubusercontent.com/15884415/168505854-f756982e-60c0-4d23-8771-f251905310ea.png)

**Comment by AlexV525** [comment]
Still not working after `.idea` was deleted.

**Comment by stevemessick** [comment]
Was this working for you before?
Do you use an internet proxy?

This might help understand the problem:
https://web.dev/origin-agent-cluster/

@helin24

**Comment by AlexV525** [comment]
> Was this working for you before?

Yes, it always works before, and after something idk it starts to not work.

> Do you use an internet proxy?

Yes, but it's not applied to the IDEA or globally.

**Comment by AlexV525** [comment]
Besides, opening the Devtools with the same address (starts with `http://127.0.0.1:9101`) works, which means it shouldn't relate to the proxy.

**Comment by AlexV525** [comment]
@helin24 [log.zip](https://github.com/flutter/flutter-intellij/files/8712993/log.zip)

**Comment by AlexV525** [comment]
After I switched to Flutter 3, it starts to work, Maybe the issue is caused by a downgrade from 3 to 2.10.

**Comment by stevemessick** [comment]
Just to confirm, it is working and we can close this issue?

**Comment by AlexV525** [comment]
Sorry for not providing additional information these days. I can confirm that after using Flutter 3 for the project, switching back to 2.10 will cause the embedded inspector not to be functional.
If switching between Flutter versions will cause this issue, then I don't think it's safe to close. Because versions switching sounds like a common request.

**Comment by AlexV525** [comment]
I believe this is somehow the same as #6611. Closing as it's been tracked in another issue.
