### ISSUE TITLE
CupertinoIcons have no preview

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter-intellij#6170]
## Steps to Reproduce

Place the cursor on the word `CupertinoIcons`, use Ctrl+B or whatever to go to the source file and observe: no icon previews. Regular `Icons` have it.

![Screenshot 2022-05-16 105014](https://user-images.githubusercontent.com/2234271/168555684-f5c28c7f-c297-4a80-91ec-f9071f7cdc50.png)

**Comment by stevemessick** [comment]
Cupertino icons don't show up in user code either.

<img width="448" alt="Screen Shot 2022-05-16 at 10 52 02 AM" src="https://user-images.githubusercontent.com/8518285/168653241-7109c568-f8b0-4fe6-aeb2-e172eb439df0.png">

This used to work.

**Comment by deakjahn** [comment]
Interestingly, it does for me in this particular case:

![Screenshot 2022-05-16 204141](https://user-images.githubusercontent.com/2234271/168660745-6f825b13-8177-4b5c-9cfb-da93e5607e0d.png)

`byPlatform()` is a simple function with a ternary ?:
