### ISSUE TITLE
Flutter daemon keep runing after android studio ide close (On Windows 10)

### ISSUE THREAD

**Issue by qicrosoft** [flutter/flutter-intellij#6178]
Every time you shut down android studio, a dart.exe process (Flutter Daemon) remains in the system. After multiple operations, there will be many flutterer daemons running in the background.

**Comment by stevemessick** [comment]
Please add the result of running `flutter doctor -v` here.

**Comment by qicrosoft** [comment]
I:\>flutter doctor -v
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本 10.0.19044.1288], locale zh-CN)
    • Flutter version 3.0.0 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (9 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at E:\Android\Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = E:\Android\Sdk
    • Java binary at: D:\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Nick\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.2)
    • Android Studio at D:\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Nick\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 101.0.1210.47

HTTP Host availability check is taking a long time...[!] HTTP Host Availability
    X HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到

    X HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到


! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
This looks like a bug in Android Studio Chipmunk. I can reproduce it with Chipmunk but not with Bumblebee.

@qicrosoft How do you determine which dart.exe does not exit? There are two, and one does exit, but I couldn't find anything saying the one left behind was the Flutter daemon, and not the Dart analyzer.

Using Bumblebee, I could see in the Task Manager that one dart.exe exited immediately, but the other took a few seconds to go away.

**Comment by gustav3d** [comment]
Its the same problem on Linux for me using IntelliJ IDEA 2022.1 .
One dart process per IDE exit stays alive forever it seems.
My solution is that i manually do kill -9 on the leftover dart process :(

I have tested with both latest stable, and now master flutter:
$ flutter doctor -v
[✓] Flutter (Channel master, 3.1.0-0.0.pre.964, on Manjaro Linux 5.18.0-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.1.0-0.0.pre.964 at /home/gustavt/stuff/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ebda49f4b (42 minutes ago), 2022-05-27 04:03:07 -0400
    • Engine revision 8bb09b5952
    • Dart version 2.18.0 (build 2.18.0-149.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/gustavt/Android/Sdk/
    • Platform android-Tiramisu, build-tools 32.1.0-rc1
    • ANDROID_HOME = /home/gustavt/Android/Sdk
    • Java binary at: /home/gustavt/stuff/jdk-17/bin/java
    • Java version OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.2
    • ninja version 1.11.0
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /home/gustavt/stuff/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 221.5787.3

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux 5.18.0-1-MANJARO
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by qicrosoft** [comment]
> @qicrosoft How do you shut down Android Studio?

Create a new or open flutter project, the task manager will appear several dart .exe processes, write code normally or do nothing, directly turn off Android Studio, a process with daemon parameters will not end, no matter how long it will not end.

**Comment by qicrosoft** [comment]
> This looks like a bug in Android Studio Chipmunk. I can reproduce it with Chipmunk but not with Bumblebee.
> 
> @qicrosoft How do you determine which dart.exe does not exit? There are two, and one does exit, but I couldn't find anything saying the one left behind was the Flutter daemon, and not the Dart analyzer.
> 
> Using Bumblebee, I could see in the Task Manager that one dart.exe exited immediately, but the other took a few seconds to go away.

With Windows Task Manager I can see the dart.exe process contains the "daemon" option. This process will never exit, no matter how long it takes. Could it be due to China's network problems? But Visual Studio Code doesn't have that problem.

**Comment by PJPAC** [comment]
Hi, 
I use Android Studio Koala 2024.1.1 Beta 1 () on a Windows PC. 
I've just counted 31 dart.exe in the task manager. I'm not if it is related but the more I count and the more I need to restart the IDE, as otherwise I cannot run any code.  
It seems to be the same issue as described here, but @stevemessick closed it as [completed] about 2 years ago. 
Would you have any suggestion ?
Thanks
