### ISSUE TITLE
Add new configuration (for a flutter project) doesn't show flutter by default

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#618]
Opening the flutter/examples/flutter_gallery example.

<img width="266" alt="screen shot 2017-01-11 at 1 38 13 pm" src="https://cloud.githubusercontent.com/assets/11857803/21867486/422a9c4c-d803-11e6-891f-4464996f0807.png">

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /src/flutter
    • Framework revision 7f2915d331 (3 hours ago), 2017-01-11 10:54:42
    • Engine revision f13518d7e7
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002

[✓] IntelliJ IDEA Community Edition (version 2016.3.2)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.8

[✓] Connected devices
    • iPhone 6s • FF0E5127-3490-4297-9313-C4776D7950D4 • ios • iOS 10.0 (simulator)
```

**Comment by mit-mit** [comment]
Odd, I get a much longer list which does include Flutter:
![screen shot 2017-01-12 at 13 23 28](https://cloud.githubusercontent.com/assets/13644170/21889667/5fdd72a6-d8ca-11e6-962e-88dc57350f34.png)

**Comment by mit-mit** [comment]
Theory: This bug was opened 15 hours ago, but the fixes to the project templates just landed 11 hours ago: https://github.com/flutter/flutter/pull/7428

Maybe the list of configs only includes ones from a plugin if that plugin is active?

@eseidelGoogle can you try to `git pull` the examples folder and see if that fixes it?

**Comment by pq** [comment]
I think @mit-mit is on to something.  It looks to me like the project is not being treated as a Flutter module.  One way to quickly check is whether it shows a Flutter icon in the project explorer.

For example:

<img width="381" alt="screen shot 2017-01-12 at 5 37 25 am" src="https://cloud.githubusercontent.com/assets/67586/21891793/3e7e6afc-d889-11e6-926b-074f9df6675b.png">

**Comment by eseidelGoogle** [comment]
It's all better after running `git clean -xdf`, `flutter` (to pull artifacts) And then opening examples/flutter_gallery.  (Without doing the clean it was still in a differently broken state.)

**Comment by pq** [comment]
Great. Thanks for following up!
