### ISSUE TITLE
IDE shows "'Pub get' has not been run" when it has.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#6187]
## Steps to Reproduce

When working on the Flutter framework, I've noticed a recent problem where once I've run `flutter update-packages` on all of the packages in the Flutter repo, the IDE continues to show the "'Pub get' has not been run" banner at the top of the file.

Waiting doesn't seem to fix it, neither does clicking on the "Reload all from disk" button, or closing the editor tab and reopening it. Clicking on the "Get Dependencies" button in the banner also does not remove it, even though it runs `flutter pub get` in the package. Running 'Invalidate caches..." and clearing out some of the caches and restarting also doesn't fix it.

I've noticed this on both Linux and macOS.

## Version info

<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel remove_shortcut_manager_of, 3.1.0-0.0.pre.842, on macOS
    12.4 21F79 darwin-x64, locale en)
    • Flutter version 3.1.0-0.0.pre.842 at /Users/gspencer/code/flutter
    • Upstream repository git@github.com:gspencergoog/flutter.git
    • Framework revision dc3ec68da0 (18 hours ago), 2022-05-19 16:32:57 -0700
    • Engine revision 8863b483b9
    • Dart version 2.18.0 (build 2.18.0-136.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gspencer/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/gspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio with Blaze
      Beta.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio with Blaze
      Beta.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/gspencer/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Users/gspencer/Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5744

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by stevemessick** [comment]
This only occurs in the master branch (or custom branch, like you have). The new version of pub no longer generates `.packages` and we still have one or more places that rely on it instead of the file in `.dart_tool`. I have a fix for this that will be in the June release. LMK if you want a custom build to get rid of the banner earlier.

**Comment by gspencergoog** [comment]
Oh, good.  Nah, I can wait: I can just click "ignore" on the banner for now.
