### ISSUE TITLE
Project opened through a symlink do not have functional breakpoints

### ISSUE THREAD

**Issue by mullerch** [flutter/flutter-intellij#6196]
## Steps to Reproduce

1. Create a new flutter desktop project in a directory /a/1/project
2. Create a symlink to the parent directory /b/1/project
3. Open the project at /b/1/project
4. Add a breakpoint
5. Run the project in debug mode
6. Add another breakpoint

I would expect the breakpoints to work.

Instead, the breakpoints are shown normally in red in the left margin of the text editor,  the first gets a gray cross at app startup. If you remove and add it it is shown normally again. None of them is hit at execution.

## Version info

flutter doctor
```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 22.04 LTS 5.15.0-33-generic, locale en_US.UTF-8)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```
Only flutter desktop is used.

`Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "linux_x64"`

Plugins:

- Dart 221.5591.58 Jetbrains
- Flutter 67.1.4 flutter.dev

**Comment by stevemessick** [comment]
@helin24 Do you have any ideas about this?

@mullerch Please attach the output from `Tools > Flutter > Flutter Doctor` (or run `flutter doctor -v`) so we can see the details.

**Comment by helin24** [comment]
@mullerch thanks for this new issue! I tried using symlinks on web and Android but had not tried Desktop. I'll run it this way and see if I can reproduce.

**Comment by helin24** [comment]
Actually I'm able to reproduce on all platforms in Linux. It seems on mac projects don't open from symlinks, so this problem doesn't occur. I'll think about whether we can fix this in IntelliJ or if this will require a change in VM service.
