### ISSUE TITLE
Auto-completion and snippets inside StatefulWidget do not work

### ISSUE THREAD

**Issue by r-i-c-o** [flutter/flutter-intellij#6200]
Auto-completion and snippets do not work inside "State" class for methods like "initState", "dispose", "setState" etc.

## Steps to Reproduce
1. create stateful widget
2. start typing "initState" or "setState" methods inside "State" class

![image](https://user-images.githubusercontent.com/54285735/170638808-9a28f054-2839-4479-a5b4-f6100c383575.png)
![image](https://user-images.githubusercontent.com/54285735/170638977-10549c64-e58f-40a8-9634-1e9efb9be928.png)

## Version info
Please paste the output of running `flutter doctor -v` here 
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1706], locale ru-RU)
    • Flutter version 3.0.1 at D:\~\AppData\Roaming\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (7 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\~\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: D:\Programs\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
    • Visual Studio at D:\Programs\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Programs\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by stevemessick** [comment]
Dup of #6167. Tracked as https://github.com/dart-lang/sdk/issues/49027
