### ISSUE TITLE
Opening samples leads to lots of analysis errors

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#621]
When a user opens `examples\flutter_gallery` for the first time, they will see 73 errors and 14 hints. I speculate this can be quite intimidating to a new user.

Could we just auto-run `flutter packages get` if we detect these are missing in the cache?

**Comment by pq** [comment]
> Could we just auto-run flutter packages get if we detect these are missing in the cache?

👍 I think we could add something like this to our custom project open support (#316).

**Comment by pq** [comment]
Fixed w/ #638 and #648.
