### ISSUE TITLE
Support build 222.*

### ISSUE THREAD

**Issue by wnstngs** [flutter/flutter-intellij#6219]
The plugin is incompatible with the latest version of Intellij Idea (https://www.jetbrains.com/idea/nextversion/#section=windows with support for https://blog.jetbrains.com/idea/2022/05/take-part-in-the-new-ui-preview-for-your-jetbrains-ide/)

![image](https://user-images.githubusercontent.com/64602598/172632857-22df26b0-9385-4e3e-b1f0-3ec3d1369f83.png)

**Comment by liasica** [comment]
You can modify until version manually :)

**Comment by liasica** [comment]
[flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/8866409/flutter-intellij.zip)
You can use this version (compiled myself)

**Comment by liasica** [comment]
> @liasica Did you use 2022.1 to build the plugin?
> 
> I always use LATEST_EAP_SNAPSHOT for EAP builds. But this one is not working.
> 
> PR that should build the plugin on the dev channel: #6224

No, I used ideaIC222.2889.14 build
