### ISSUE TITLE
ios development team  not recognized in intellij

### ISSUE THREAD

**Issue by freedreamer82** [flutter/flutter-intellij#6226]
hi ,

I've been using intelliJ with a flutter app. Everything on command line works  and when it builds it uses the development team cert like it should.

`Automatically signing iOS for device deployment using specified development team in Xcode project`

 When  I use the debugger from the IDE  it says from the console
`Signing iOS app for device deployment using developer identity`

and it not runs correctly...it seems it switches to personal profile.

anyone can help me?

plugin version is 68.1.4 on apple macbook M1

thanks

**Comment by stevemessick** [comment]
@jmagman Are there any environment variables involved in signing?

Having different envar values between IDE and command line is the most common source of incompatibilities, but I don't know how signing works.

**Comment by freedreamer82** [comment]
as I know , no specific environment involved .
I didn't specify but from Xcode it works.

**Comment by jmagman** [comment]
@freedreamer82 Can you attach the full logs of what you're seeing? `Signing iOS app for device deployment using developer identity` is only the first part of that log statement.

**Comment by jmagman** [comment]
Note feel free to redact anything, I just want to see all the lines around it.  The saved codesigning settings come from `flutter config` which shouldn't change based on environment.

**Comment by freedreamer82** [comment]
I guess I fixed it. If I delete the APP from iphone and try again it works properly....
I hope this fix can help anyone with my own issue , for now I close ..thanks

M.
