### ISSUE TITLE
Issue while opening Database Inspector

### ISSUE THREAD

**Issue by rishabh-hk** [flutter/flutter-intellij#6234]
## What i have done: 
After opening app inspection. Select the device and process in database inspector.

## What i want to have and what i get:
Want to view SQLite database. But it is consistently showing nothing to show.

## Run Window Output:

Run Exception:
java.lang.Throwable

W/InputMethodManager(20989): 	at android.view.inputmethod.InputMethodManager.getInstance(InputMethodManager.java:1436)

W/InputMethodManager(20989): 	at java.lang.reflect.Method.invoke(Native Method)

W/InputMethodManager(20989): 	at com.android.tools.profiler.support.profilers.EventProfiler$InputConnectionHandler.run(EventProfiler.java:261)

W/InputMethodManager(20989): 	at java.lang.Thread.run(Thread.java:923)

W/InputMethodManager(20989): InputMethodManager.peekInstance() is deprecated because it cannot be compatible with multi-display. Use context.getSystemService(InputMethodManager.class) instead.

W/InputMethodManager(20989): java.lang.Throwable

W/InputMethodManager(20989): 	at android.view.inputmethod.InputMethodManager.peekInstance(InputMethodManager.java:1455)

W/InputMethodManager(20989): 	at android.view.inputmethod.InputMethodManager.getInstance(InputMethodManager.java:1441)

W/InputMethodManager(20989): 	at java.lang.reflect.Method.invoke(Native Method)

W/InputMethodManager(20989): 	at com.android.tools.profiler.support.profilers.EventProfiler$InputConnectionHandler.run(EventProfiler.java:261)

W/InputMethodManager(20989): 	at java.lang.Thread.run(Thread.java:923)

## Version info

-> IntelliJ IDEA Version and Info:

IntelliJ IDEA 2022.1.2 (Community Edition)
Build #IC-221.5787.30, built on June 1, 2022
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2032M
Cores: 4
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    org.jetbrains.kotlin (221-1.7.0-release-281-IJ5591.52)
    String Manipulation (9.5.0)
    com.mallowigi (64.0.0)
    Dart (221.5787.37)
    io.flutter (68.1.4)
    zielu.gittoolbox (212.9.0)
    com.developerphil.adbidea (1.6.4)
    com.chrisrm.idea.MaterialThemeUI (7.5.2.2)
    izhangzhihao.rainbow.brackets (6.24)

Kotlin: 221-1.7.0-release-281-IJ5591.52

-> Flutter Doctor Output 

[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19044.1766], locale en-IN)
    • Flutter version 3.0.2 at C:\src\flutter                                                    
    • Upstream repository https://github.com/flutter/flutter.git                                 
    • Framework revision cd41fdd495 (12 days ago), 2022-06-08 09:52:13 -0700                     
    • Engine revision f15f824b57                                                                 
    • Dart version 2.17.3                                                                        
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.1.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.1.32228.430
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[√] VS Code (version 1.68.0)
    • VS Code at C:\Users\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (4 available)
    • SM M127G (mobile)  • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

Sample Image:
![image](https://user-images.githubusercontent.com/96161211/174542750-97404382-7a3c-4ef2-8363-b7314c057270.png)

**Comment by stevemessick** [comment]
I'm not sure the database inspector works with Flutter apps. There are two things to try.

First, does your Flutter project have an Android module? You can check by opening the Project Structure editor (`File > Project Structure` menu). Click the Modules pane. If you don't see a module named `Android` then just add one using the `+` icon.

If that doesn't help, the second possibility is to open your `android` project as a top-level project in Android Studio. Select `android` in the Project pane then use the menu `Tool > Flutter > Open Android module in Android Studio`. Now we get to the speculative part; I'm not sure if you can even do what I have in mind. In the Android project (in Android Studio) try to attach the debugger to your running Flutter app. If you can do that, then maybe the database will show up, but I don't know.

Please let us know how things turn out.

**Comment by rishabh-hk** [comment]
I have android module in the project. Also, it was working with previous built where i can see the database and do operation respectively. Recent update of IDE causes the issue. 

![image](https://user-images.githubusercontent.com/96161211/174944546-c4180958-56b4-4123-b780-3cd809dd51a3.png)

**Comment by stevemessick** [comment]
That screen shot does not show an IntelliJ module named "android". It shows your Flutter project supports the Android platform. I posted instructions to check for a module above.

If the IDE update broke this feature, then either they started requiring an `android` module (and you don't have one, which we do not yet know), or they changed something about the database inspector that made it incompatible with Flutter projects. You might want to try using an older version of the IDE to work with databases. You can try filing an issue with the Android Studio issue tacker, but they are often reluctant to address problems with Flutter projects.
