### ISSUE TITLE
Inserted suggestions shouldn't include TODO, and perhaps not throw UnimplementedError either

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#6239]
I would like to suggest that the inserted suggestions for overrides and switch cases do NOT include the comment that says `// TODO: implement <function>`, since 100% of the time I just immediately delete it, making it more work to do (100% of the time, since it doesn't match our TODO style guide requirement anyhow).

I feel the same way about the "throw UnimplementedError();" lines too: I'd rather it insert non-functional code than make me delete it every single time. There is a valid case to be made that the suggestions shouldn't insert non-functional code though so, alternatively, once inserted, it could automatically select the body of the function (excluding things like a required `super` call because of `@mustCallSuper`) so I could just immediately hit delete or start typing to delete the throw line.

I still wouldn't want the TODO comments though.

<details>
<summary>flutter doctor -v</summary>
<pre>
[!] Flutter (Channel menu_bar_in_progress, 3.1.0-0.0.pre.1363, on macOS 12.4 21F79 darwin-x64, locale en)
    • Flutter version 3.1.0-0.0.pre.1363 on channel menu_bar_in_progress at /Users/gspencer/code/flutter
    ! Upstream repository git@github.com:gspencergoog/flutter.git is not a standard remote
    • Framework revision dcab7d9a2d (14 hours ago), 2022-06-22 19:29:43 -0700
    • Engine revision ceac23d7a9
    • Dart version 2.18.0 (build 2.18.0-190.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gspencer/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/gspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze Beta.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/gspencer/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Users/gspencer/Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5744

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
</pre>
</details>

**Comment by stevemessick** [comment]
@jwren The `TODO` comes from the analyzer, right? I'm pretty sure quick fixes (Cmd-Enter on Mac) is a service of the Dart analyzer. (And I think I actually did get the syntax right in the previous sentence; "quick fixes" is a single service.)

@gspencergoog Auto-select could be done, I suppose, but I worry people would be confused at having multiple selections added automatically. (I think IntelliJ supports multiple selections, but I have never used it.) However, that would be a feature implemented by the Dart plugin. And, switching back to analyzer modifications, I suspect you'd have an up-hill battle to not generate the `throw` because it would likely introduce analysis errors.

**Comment by gspencergoog** [comment]
> I suspect you'd have an up-hill battle to not generate the throw because it would likely introduce analysis errors.

Sure, makes sense.  Just removing the TODO's would be an improvement.

**Comment by stevemessick** [comment]
Filed https://github.com/dart-lang/sdk/issues/49331, so I'm closing this one.

BTW the other linked issue (generate overrides) is really a problem in the Dart plugin. I'm not sure why I added it to the Flutter plugin milestones before.
