### ISSUE TITLE
Code suggestion for setState still not showing on IntelliJ

### ISSUE THREAD

**Issue by lore-co** [flutter/flutter-intellij#6251]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Try creating a project with flutter 3.0.3 and create a Stateful Widget.
Try typing setState, the hint will not appear.

## Version info

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

#6167

**Comment by sanitrajula** [comment]
Same issue

**Comment by AlexV525** [comment]
Duplicate with #6167, also should be fixed by the pending cherry-pick https://github.com/dart-lang/sdk/issues/49239.

**Comment by lore-co** [comment]
> Duplicate with #6167, also should be fixed by the pending cherry-pick [dart-lang/sdk#49239](https://github.com/dart-lang/sdk/issues/49239).

The issue has been opened since the duplicate was marked as closed but the problem was still there.

**Comment by AlexV525** [comment]
> The issue has been opened since the duplicate was marked as closed but the problem was still there.

Yes, please subscribe to the cherry-pick issue, and you can submit new issues if it's still reproducible after https://github.com/dart-lang/sdk/issues/49239 gets merged.
