### ISSUE TITLE
Request for proper features for flutter

### ISSUE THREAD

**Issue by JulianHSC** [flutter/flutter-intellij#6255]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
Flutter 3.0.4 as seen in your website.
1 - No proper documentation to install flutter. I had to check the internet to get everything done.
2 - I sent email to your team and no one bothered answering. The internet solved all my problems. Your email and your team is plain useless.
3 - After removing it from my android studio, I still see android can detect traces of flutter in the plugin. This is bad design.
4 - I was redirected here after logging a case with the android development team.

**Comment by stevemessick** [comment]
> 1 - No proper documentation to install flutter. I had to check the internet to get everything done.

Please report the problem here: https://github.com/dart-lang/sdk/issues

> 2 - I sent email to your team and no one bothered answering. The internet solved all my problems. Your email and your team is plain useless.

Please report the problem here: https://github.com/dart-lang/sdk/issues

> 3 - After removing it from my android studio, I still see android can detect traces of flutter in the plugin. This is bad design.

What did you remove from Android Studio? I do not understand what "I still see android can detect traces of flutter in the plugin" means. Can you elaborate?

> 4 - I was redirected here after logging a case with the android development team.

SOP
