### ISSUE TITLE
Android emulator would not minimize.

### ISSUE THREAD

**Issue by ShlokBharadwaj** [flutter/flutter-intellij#6272]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
1. Open a flutter project in VS Code.
2. Open the Command Pallet( Control+Shift+P).
3. Select Flutter: Select Device.
4. Create an Android Emulator from Android AVD images(if haven't already).
5. Choose an Android emulator.
6. Wait till the emulator starts.
7. The emulator cannot be minimized.

### Even if I start the emulator with **flutter emulators --launch flutter_emulator**

Proof: 

https://user-images.githubusercontent.com/79036875/180995750-ebfc8023-063e-4aba-b3a4-90a2ff07d676.mp4

### Even if I try to do it with cmd then also the problem persists:

1. Run flutter config --machine.
2. Find android-sdk path.
3. Run /home/shlok/Android/Sdk/emulator/emulator -avd flutter_emulator but replace /home/shlok/Android/Sdk/ with the android-sdk path and flutter_emulator with the emulator name.

## What I expected to happen:

1. Emulator should minimize when pressing the minimize button.

## What actually happens:

1. The emulator minimizes and opens automatically although it should have been minimized.

## Proof: 

https://user-images.githubusercontent.com/79036875/180995369-74a823de-2787-4c33-8439-85f159eb7ab6.mp4

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|5.73GB (0.12GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id ac2a9ee4-7023-4d78-be8f-230bafddad07|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30525688
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
841h4636:30532337

```

</details>

https://user-images.githubusercontent.com/79036875/180786514-07770184-eed9-4556-886b-dff280ebda33.mp4

![image](https://user-images.githubusercontent.com/79036875/180784347-ace407c5-2ce2-40ad-a896-6b92d1bf0538.png)

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

❯ flutter doctor -v       
[✓] Flutter (Channel beta, 3.3.0-0.0.pre, on Ubuntu 20.04.4 LTS
    5.15.0-41-generic, locale en_IN)
    • Flutter version 3.3.0-0.0.pre on channel beta at
      /home/shlok/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f90da9b167 (7 days ago), 2022-07-18 18:59:23
      -0700
    • Engine revision 1388adb442
    • Dart version 2.18.0 (build 2.18.0-271.2.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /home/shlok/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at:
      /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome
      executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • Pixel (mobile)  • 1e7242fc • android-arm64 • Android 11 (API 30)
    • Linux (desktop) • linux    • linux-x64     • Ubuntu 20.04.4 LTS
      5.15.0-41-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
I appreciate the detailed report. Unfortunately, I don't think this is the best place to report it. It looks like a problem with the emulator. Have you tried using Android Studio to launch the emulator? If it won't minimize in that config, then you should report a problem to the Android Studio team. If it does minimize, then I think the problem should be reported to the Flutter framework team, since launching from the Flutter tool causes it to not minimize.

**Comment by stevemessick** [comment]
I see. What you need to do is file a new issue with Android Studio and be sure to _not_ mention Flutter. Ideally, include a video of launching the emulator from Android Studio and trying to minimize the emulator window. That will make it clear that the problem is entirely with Android Studio.
