### ISSUE TITLE
about flutter ;Code alerts for missing ‘Wrap with’ 

### ISSUE THREAD

**Issue by potterLee** [flutter/flutter-intellij#6280]
about flutter ;Code alerts for missing ‘Wrap with’ 

<img width="507" alt="WechatIMG325" src="https://user-images.githubusercontent.com/15892545/184049519-f8b3fa98-abc3-422f-aaa8-38fc44f01469.png">

![WechatIMG319](https://user-images.githubusercontent.com/15892545/184049634-444e504d-1ca3-4299-96b0-18b6cb5222b5.png)
![1660012675728](https://user-images.githubusercontent.com/15892545/184049649-3655f6eb-4fe0-4ee4-b73e-59868f6a29e5.jpg)

**Comment by potterLee** [comment]
![image](https://user-images.githubusercontent.com/15892545/184052668-a1f62bd7-7b55-4e0e-b400-68c859759ef2.png)
Vscode can be used on the same computer
![image](https://user-images.githubusercontent.com/15892545/184053138-75d1bc5a-d8dd-48a0-aefb-e916126f3206.png)

**Comment by stevemessick** [comment]
Please explain the problem.

**Comment by potterLee** [comment]
Flutter error (missing 'Wrap with') on the MAC version of androidstudio, VSCode on the same computer can indicate 'Wrap with' normally；
Uninstalling and reinstalling the AS does not work。

**Comment by stevemessick** [comment]
Quick fixes are a feature of the Dart plugin, not the Flutter plugin. However, both the Dart plugin for IntelliJ and the Dart extension for VS Code implement quick fixes by requesting them from the Dart analyzer. I'm surprised there is such a big difference, but I can confirm that the results do vary a lot.

Filed https://github.com/dart-lang/sdk/issues/49688
