### ISSUE TITLE
Unable to Extract Widget Android studio 

### ISSUE THREAD

**Issue by Wahab-Khan** [flutter/flutter-intellij#6282]
Build: AI-212.5712.43.2112.8609683, 202205181650,

AI-212.5712.43.2112.8609683, JRE 11.0.12+0-b1504.28-7817840x64 JetBrains s.r.o., OS Mac OS X(aarch64) v12.4, screens 3456.0x2234.0; Retina

AS: Chipmunk | 2021.2.1 Patch 1; Kotlin plugin: 212-1.7.10-release-333-AS5457.46; Android Gradle Plugin: (plugin information not found); Gradle: (gradle version information not found); Gradle JDK: version 11.0.12; NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)Source: send_feedback_icon

Unable to Extract Widget directly from Double click and Extract Widget (show popup but nothing happens after clicking on refactor)option and from Flutter Outline.

All buttons are disabled in the Flutter outline except the extract method.

![image](https://user-images.githubusercontent.com/20702445/185043568-fac97a4a-812d-463c-8eb0-d409ab93dc19.png)

Unable to rename any variable.

![image](https://user-images.githubusercontent.com/20702445/185043595-9f97847d-e371-4410-9368-b6ef9bafdaab.png)

## Steps to Reproduce
This happens only for one project every single time I try to export Widget, unable to make it right for this project. And also unable to reproduce this issue for other projects. Creating a new project or importing any project from Github works fine.

## Version info
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.5 21G72 darwin-arm, locale en-PK)
• Flutter version 3.0.3 at /Users/macbookpro/Developer/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/676cefaaff197f27424942307668886253e1ec35 (8 weeks ago), 2022-06-22 11:34:49 -0700
• Engine revision ffe7b86a1e
• Dart version 2.17.5
• DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
• Android SDK at /Users/macbookpro/Library/Android/sdk
• Platform android-32, build-tools 31.0.0
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
• macOS (desktop) • macos • darwin-arm64 • macOS 12.5 21G72 darwin-arm
• Chrome (web) • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
• All required HTTP hosts are available

**Comment by stevemessick** [comment]
It sounds like your Dart analysis cache has been corrupted. I don't know if there is a way to clear it for just one project. You can delete all of it by removing the `~/.dartServer` directory. @bwilkerson for confirmation.

If that doesn't work I'd suggest rebuilding the project. Create a new project from the same Flutter template, then move your project-specific files into the new one.

Let us know if that helps.
