### ISSUE TITLE
Where can I download the plugin manually?

### ISSUE THREAD

**Issue by RovshikDev** [flutter/flutter-intellij#6287]
Hello!

I can't install the Flutter plugin in IntelliJ or Android Studio, and I can't download it from plugins.jetbrains.com either.
Could you please tell me if I can download the plugin from some other source?

Thank you!

**Comment by stevemessick** [comment]
The plugin can be downloaded from:
https://plugins.jetbrains.com/plugin/9212-flutter/versions

If you have trouble downloading, try using a private or incognito window. You don't have to be logged in to download it.

The only other option is to build it yourself, which is rather difficult if you've never done it before.

**Comment by RovshikDev** [comment]
Thank you!
