### ISSUE TITLE
Let us open the Android emulator as it was before, a standalone window

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#6290]
Hey, I really don't like that now the Android emulator is now always inside an IntelliJ window, with a lot of useless (to me) buttons and information. It was not broken before, and I don't see the current situation as an improvement. Also:

* The scaling has no anti-alias, making it very ugly when the window is small. 
* The zoom controls are overlapping the phone screen, forcing us to make the window larger to avoid the overlap. And then the window gets bigger and wastes a lot of screen space.

Could you please let us open the emulator just as before, as one of the options? Let's call it a "plain mode". As a simple window, with no opinionated bells and whistles. Thank you!

**Comment by marcglasberg** [comment]
@stevemessick Thank you so much! I missed this setting.

**Comment by stevemessick** [comment]
No problem! I realize now that I should have mentioned it in the release
notes.
