### ISSUE TITLE
Flutter hot reload is not automatically triggered when VS Code Keymap plugin is in use.

### ISSUE THREAD

**Issue by aaronblondeau** [flutter/flutter-intellij#6294]
## Steps to Reproduce

1. Create a new Flutter project
3. Make changes to code and verify hot reload works upon save
3. Install VSCode Keymap plugin (https://plugins.jetbrains.com/plugin/12062-vscode-keymap)
4. Change Keymap to VSCode (File -> Settings -> Keymap -> Choose VS Code from select box, then Apply)
5. Make changes to code and verify that hot reload not longer works upon save (manually clicking hot reload button will still work)
6. Change Keymap back to Windows (File -> Settings -> Keymap -> Choose Windows from select box, then Apply)
7. Make changes to code and verify hot reload works again upon file save

## Version info

    • Flutter version 3.0.1 at C:\Users\ablon\opt\flutter_windows_2.10.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

Android Studio Chipmunk | 2021.2.1 Patch 2
on Windows 11

**Comment by stevemessick** [comment]
I'm guessing you use Crtl-S to save your work. I'm on a Mac, not Windows, but I believe they work equivalently. In the standard keymap, Cmd-S (your Crtl-S) is bound to "Save All". In the VS Code keymap (for Windows), Crtl-S is bound to "Save" -- that is, save a single file. Hot Reload is triggered by a "Save All" action. The equivalent keystroke in the VS Code keymap is a two-stroke sequence: Ctrl-K, S.

Does Ctrl-K, S trigger hot reload?
