### ISSUE TITLE
Background task for building app never ends

### ISSUE THREAD

**Issue by alevinetx** [flutter/flutter-intellij#6295]
## Steps to Reproduce
Same issue as opened here:  https://issuetracker.google.com/issues/242420860

Building an APK from within AS produces a background task that never ends
![image](https://user-images.githubusercontent.com/5067356/189008650-ae79fb83-2a3f-4a5d-8eee-366dea703b18.png)

![image](https://user-images.githubusercontent.com/5067356/189008573-65bace73-a127-410e-b1f8-ccea25f6c062.png)

## Version info

[!] Flutter (Channel @upstream, 3.3.0, on Microsoft Windows [Version 10.0.19044.1766], locale en-US)
    • Flutter version 3.3.0 on channel @upstream at C:\dev\languages\flutter
    ! Upstream repository unknown
    • Framework revision ffccd96b62 (9 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\dev\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = C:\dev\Android\sdk
    • Java binary at: c:\dev\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32811.315
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\dev\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio
    • Android Studio at c:\dev\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = c:\dev\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by Tahmid79274** [comment]
![AppBuildingEndlessTime](https://user-images.githubusercontent.com/39722429/191159350-9ec1c5c4-4264-4c88-9209-dbfe3104de43.png)
I am also getting same problem but my flutter doctor didn't get any issue.
