### ISSUE TITLE
'Canary versions are unsupported' message comes too late to be useful

### ISSUE THREAD

**Issue by strangedreamsNY** [flutter/flutter-intellij#6298]
[The](https://github.com/flutter/flutter/issues/url) error message that the Flutter Plugin doesn't support canary versions of Android Studio appears only after starting a new Flutter Project and is too late to be helpful or useful. This is a warning that should appear on the 'New Flutter Project' screen to warn a user first. Further, it's unclear whether this message is accurate given the release notes on the [Flutter Plugin home page](https://plugins.jetbrains.com/plugin/9212-flutter) which suggests that as of version 69, Canary Build 221 is supported in addition to the 2022.2.2 EAP.

Flutter Plugin 70.0.4

Android Studio Electric Eel | 2022.1.1 Canary 10

Build #AI-221.6008.13.2211.8963757, built on August 18, 2022
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.8
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
external.system.auto.import.disabled=true
ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
Dart (221.6008.17)
io.flutter (70.0.4)
Jetbrains TeamCity Plugin (2022.4.108706)

[flutter_doctor.txt](https://github.com/flutter/flutter-intellij/files/9536197/flutter_doctor.txt)

**Comment by stevemessick** [comment]
This message is intended to remind Canary users that things might break more than would be expected when using the stable release. It is working as intended.

**Comment by strangedreamsNY** [comment]
All the more reason then to improve the messaging or have it appear earlier in the workflow so that users are aware of the lack of support prior to starting/creating a project, no?
