### ISSUE TITLE
Directory renaming refactor doesn't identify `import` references.

### ISSUE THREAD

**Issue by strangedreamsNY** [flutter/flutter-intellij#6299]
## Steps to Reproduce
- Create a project and have a widget/class that uses imports classes in local sub-folders
- Highlight the directory from the project window and press `Ctrl+F6` to rename/refactor the folder.
- Ensure that 'Search for references` is selected. `Search in comments and strings` shouldn't be relevant, but does not impact the results.
- Change the folder name and Click `Refactor`

## Expected
Classes and references that import the changed directory should be updated.

## Actual 
References used in import statements are unchanged.

## Version info

[flutter_doctor.txt](https://github.com/flutter/flutter-intellij/files/9537739/flutter_doctor.txt)

## Demo project 
- `main.dart` and two 'pages' in `lib/pages` folder referenced from `DemoApp`
[demo.zip](https://github.com/flutter/flutter-intellij/files/9537741/demo.zip)

**Comment by stevemessick** [comment]
The rename refactoring is implemented by the Dart plugin.

Closing as this is a dup of https://github.com/flutter/flutter-intellij/issues/6276 and https://youtrack.jetbrains.com/issue/WEB-44785/Renaming-a-folder-in-a-Dart-or-Flutter-project-doesnt-update-imports
