### ISSUE TITLE
Autocomplete only works with bracket

### ISSUE THREAD

**Issue by ranierjardim** [flutter/flutter-intellij#6302]
I having problems to use autocomplete on flutter 2.10.5 with flutter_background_geolocation:4.2.1 package. When i put bracket before the dot and do a CTRL + SPACE it works, but don't works as expected without bracket.

## Steps to Reproduce

https://user-images.githubusercontent.com/12734534/189781216-becfa74b-d969-4ade-a193-84cab15baff8.mov

## Version info

/Users/ranierribeiro/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale en-BR)
    • Flutter version 2.10.5 at /Users/ranierribeiro/flutter
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (5 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/ranierribeiro/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • iPhone 13 mini (mobile) • 4DEF2A1B-4839-4B3E-8144-BDA57B7BA913 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0

**Comment by stevemessick** [comment]
The current version of Flutter is 3.3.2. This problem may have been fixed, but it will not be addressed in Flutter 2.x.
