### ISSUE TITLE
Android Studio consumes 30% of CPU without started device and without actions from developer 

### ISSUE THREAD

**Issue by ArthurHarkivsky** [flutter/flutter-intellij#6303]
What steps will reproduce the issue?

Windows 11 Pro + Core i5 12600, Docker, WSL2.
Latest Android Studio + new Flutter with Dart "hellow world" app with Flutter and Dart plugins. What is the expected result?
Very low CPU usage.

What happens instead?

JIT compiler uses 30% of CPU used **NOT** during compilation, started by user.

Did not helped with invalidated cache and restart:

Power Saving Mode in AS. -XX:CICompilerCount=2 Disabled all VCS background stuff.

[Logs.](https://www.dropbox.com/s/68jzwcyqlucp2qn/studio-logs-20220912-230604.zip?dl=0)

**Comment by stevemessick** [comment]
Does this happen if you restart the IDE? If so, does it happen if you disable the Flutter plugin and restart?

**Comment by ArthurHarkivsky** [comment]
Works well without plugin.

**Comment by stevemessick** [comment]
Cannot reproduce.
