### ISSUE TITLE
Inspector opens somewhere else

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter-intellij#6317]
## Steps to Reproduce

I opened the flutter inspector and saw this result. It used to be in the correct place some versions ago:

![image](https://user-images.githubusercontent.com/20153831/192051386-fb2ff228-8fd2-4165-83e2-1b6737799f00.png)

## Version info
My Laptop's resolution is `3200x1800` if that helps.
```
[✓] Flutter (Channel stable, 3.3.2, on Ubuntu 22.04.1 LTS 5.15.0-48-generic, locale en_US.UTF-8)
    • Flutter version 3.3.2 on channel stable at /home/yazdidev/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (9 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/yazdidev/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/yazdidev/Applications/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/yazdidev/Applications/android-studio
    • Flutter plugin version 70.0.3
    • Dart plugin version 213.7371
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-48-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by stevemessick** [comment]
@aliyazdi75 The version of Linux you are using would have been in the first line of the `flutter doctor -v` output, but that line is missing. Which version of Linux do you use?

@helin24 Can you take a look at this?

**Comment by aliyazdi75** [comment]
> @aliyazdi75 The version of Linux you are using would have been in the first line of the `flutter doctor -v` output, but that line is missing. Which version of Linux do you use?

It was there but idk why github removed it. I fixed it.

**Comment by stevemessick** [comment]
Thanks for the update, @aliyazdi75. Do you use 200% zoom, like in #6318?

**Comment by aliyazdi75** [comment]
> Thanks for the update, @aliyazdi75. Do you use 200% zoom, like in #6318?

Yes, exactly as same as the mentioned issue.

**Comment by helin24** [comment]
@aliyazdi75 can you download the Flutter plugin v69 and see if the problem exists there?

If not, it's likely this caused the problem: https://github.com/flutter/flutter-intellij/pull/6283 and I'd revert back to the `OFFSCREEN` rendering mode.

**Comment by stevemessick** [comment]
Thanks!

**Comment by aliyazdi75** [comment]
@helin24 Sorry I can't test in:
![image](https://user-images.githubusercontent.com/20153831/192898883-864ac8bd-97c0-4efd-bfd6-1a08319fe97c.png)

**Comment by helin24** [comment]
@aliyazdi75 I think you'll need to download 69.0.3, because 69.0.1 is meant for an older version of Android Studio. Sorry, I should have specified the version!

**Comment by aliyazdi75** [comment]
@helin24 Yes, worked perfectly:
![image](https://user-images.githubusercontent.com/20153831/192900256-b85d90a2-e176-423f-bbc1-f03a256ee7be.png)

**Comment by helin24** [comment]
Thanks for checking! I have never been able to reproduce this problem on my system. I'll revert the change I made.
