### ISSUE TITLE
Wrong zoom component when use 200% of screen zoom in Linux (Xorg)

### ISSUE THREAD

**Issue by yhojann-cl** [flutter/flutter-intellij#6318]
I use Ubuntu 22.04 LTS over Xorg session and have a 4k display with 200% of zoom (from gnome control). The editor works fine, but Flutter inspector is visible using 100% instead of 200%.

Attach a image with example:

![Captura desde 2022-09-26 00-53-28](https://user-images.githubusercontent.com/2144779/192309402-33960a19-aa15-469c-9ed5-151429ea6dac.png)

**Comment by stevemessick** [comment]
This may be the same as #6317. The image in that issue looks like it is also using 200%.

@helin24 Can you take a look at this one?

**Comment by stevemessick** [comment]
@yhojann-cl Can you attach the output of `flutter doctor v`?

**Comment by yhojann-cl** [comment]
I just updated the Flutter plugin for Intelij and now it works fine :)
