### ISSUE TITLE
Migrate IML files to the .idea directory.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#632]
... rather than in the project root.  This will allow us to easily hide it in the explorer.  More context in https://github.com/flutter/flutter-intellij/issues/630.

**Comment by mit-mit** [comment]
I have a CL for this

**Comment by pq** [comment]
👍 @mit-mit 

Do you mean for the examples or for project creation?  We'll want both.

**Comment by mit-mit** [comment]
Both

**Comment by pq** [comment]
Great!
