### ISSUE TITLE
Example API links should be rendered in a "link" color

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#6320]
In the Flutter repo API docs, when the editor is showing a documentation comment like this:

```dart
/// {@tool dartpad}
/// This example shows various [ClipRRect]s applied to containers.
///
/// ** See code in examples/api/lib/widgets/basic/clip_rrect.0.dart **
/// {@end-tool}
```

If you hold down Ctrl/Cmd and point at the path in the "See code in" line, the path lights up as a link.  It's useful, but also fairly undiscoverable, since the navigation link is rendered just as regular comment text.  Ideally, the link would show as a different color, as the bracketed symbol references do.

**Comment by stevemessick** [comment]
Thanks for the suggestion. I created https://youtrack.jetbrains.com/issue/WEB-57495/Dart-Example-API-links-should-be-rendered-in-a-link-color for the Dart plugin.
