### ISSUE TITLE
Flutter Project cannnot connect to device in VSCode or AS

### ISSUE THREAD

**Issue by pegasustian** [flutter/flutter-intellij#6323]
flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19044.1889], locale zh-CN)
    • Flutter version 1.22.5 at E:\Fultter\flutter
    • Framework revision 7891006299 (1 year, 10 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Administrator\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! 

! Doctor found issues in 1 category.

In AS：

![image](https://user-images.githubusercontent.com/91168673/192666684-20038e5c-e184-4a7a-aaa9-84f418977262.png)

![image](https://user-images.githubusercontent.com/91168673/192666748-b0109a71-f3ff-4dc2-b7b8-8c6524ddc5c9.png)

Run Error：
![image](https://user-images.githubusercontent.com/91168673/192666785-15450aa0-6fc1-4f4f-8237-95834a1ee71b.png)

The project cannot identify the real machine，nor can it be connected to the simulator.  I haven't found the reason. 
Please help~

**Comment by stevemessick** [comment]
The "Error Opening Emulator" message indicates that the emulator is already running. Use the Task Manager to stop it.

Generally, we do not support out-of-date software. I suggest updating everything.
