### ISSUE TITLE
dart:developer.log getting truncated (again?)

### ISSUE THREAD

**Issue by oravecz** [flutter/flutter-intellij#6333]
I'm seeing the problem with debug logs being truncated. 

![image](https://user-images.githubusercontent.com/297712/193118074-ead9aa58-a466-4240-a2bb-807ba40d93d2.png)

This was last brought up in 2019 (#3052), and merged in #3057. 

Is there a setting I am missing to turn it on, or is this a regression error?

## Version Info
IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Build #IU-222.4167.29, built on September 13, 2022
Licensed to ...
Subscription is active until December 9, 2022.
Runtime version: 17.0.4+7-b469.53 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    suggest.all.run.configurations.from.context=true
    documentation.show.toolbar=true
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    org.intellij.plugins.hcl (222.4167.21)
    com.jinsihou.react.snippets (1.1.1)
    me.serce.solidity (2.3.10)
    String Manipulation (9.5.1)
    org.jetbrains.plugins.vue (222.4167.35)
    intellij.prettierJS (222.4167.21)
    dev.blachut.svelte.lang (0.22.1)
    com.nekofar.milad.intellij.nextjs (1.2.3)
    com.intellij.lang.jsgraphql (3.2.1)
    com.deadlock.scsyntax (222.4167.21)
    Dart (222.4167.21)
    aws.toolkit (1.50-222)
    io.flutter (70.0.5)
    izhangzhihao.rainbow.brackets (6.26)

Kotlin: 222-1.7.10-release-334-IJ4167.29

**Comment by stevemessick** [comment]
All the code that was modified in #3057 has been removed. The Flutter plugin log handling has not changed recently.

Is this something that used to work and recently changed? If so, the change was probably made in the Dart SDK.

Have you tried enabling verbose logging in the plugin preferences?

IntelliJ allows any plugin to modify log output. Does the problem persist if all plugins other than Dart and Flutter are disabled?

**Comment by oravecz** [comment]
I'm not sure it worked before, just started using debug logging. If I use `printDebug(message)` I can see everything, so I switched to this.
