### ISSUE TITLE
Intellij fails to see connected devices

### ISSUE THREAD

**Issue by amugofjava** [flutter/flutter-intellij#634]
IntelliJ fails to see connected devices. Running 'flutter doctor' from the command line correctly shows the connected device. Running 'flutter doctor' from within IntelliJ shows that it is unable to find the Android toolchain or the connected device.

Running IntelliJ 2016.3.2 on Ubuntu 16.04 LTS. Flutter plugin 0.1.8.1.

flutter doctor from the command line:

`[✓] Flutter (on Linux, channel master)`
`    • Flutter at /home/ben/Development/flutter`
`    • Framework revision fcc9df719f (3 days ago), `
`    • Engine revision b3ed79122e`
`    • Tools Dart version 1.21.0`

`[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)`
`    • Android SDK at /home/ben/Development/android/sdk`
`    • Platform android-25, build-tools 25.0.2`
`    • java version "1.8.0_112"`

`[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)`
`    • Dart plugin version 163.11306`
`    • Flutter plugin version 0.1.8.1`

`[✓] Connected devices`
`    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.0 (API 24) (emulator)`

Running flutter doctor from within IntelliJ

`[✓] Flutter (on Linux, channel master)`
`    • Flutter at /home/ben/Development/flutter`
`    • Framework revision fcc9df719f (3 days ago), `
`    • Engine revision b3ed79122e`
`    • Tools Dart version 1.21.0`

`[x] Android toolchain - develop for Android devices`
`    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).`

`[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)`
`    • Dart plugin version 163.11306`
`    • Flutter plugin version 0.1.8.1`

`[✓] Connected devices`
`    • None`

**Comment by devoncarew** [comment]
I _think_ this is a dup of https://github.com/flutter/flutter-intellij/issues/601.
