### ISSUE TITLE
[Question] How to add command line argument as a result from another script?

### ISSUE THREAD

**Issue by nerder** [flutter/flutter-intellij#6354]
In order to run a local configuration I need to fetch the local IP of the development machine and then pass it as `--dart-define` to make it available for Flutter.

What I'm trying to do right now is add inside the `additionalArguments` the following line:

```
--flavor=dev --dart-define FLAVOR=local --dart-define LOCAL_IP="$(ipconfig getifaddr en0)"
```

What I'm doing wrong here?

NOTE: without the quotes, I simply get `Target file "getifaddr" not found.`

**Comment by stevemessick** [comment]
The additional arguments are not evaluated. The IDE launches dart directly, without going through a shell. You'll have to evaluate LOCAL_IP and insert its value in the run config.
