### ISSUE TITLE
Remove "Platform availability might depend on your Flutter SDK channel" warning

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter-intellij#6355]
## Steps to Reproduce

All platforms are available and enabled by default since [Flutter 3](https://medium.com/flutter/whats-new-in-flutter-3-8c74a5bc32d0).  Remove the warning, and instructions "Additional desktop platforms can be enabled by, for example, running "flutter config --enable-linux-desktop" on the command line."

<img width="540" alt="Screen Shot 2022-10-21 at 2 30 08 PM" src="https://user-images.githubusercontent.com/682784/197291668-79de94a2-98dd-4f9a-89db-a74b1f01ca1d.png">

https://github.com/flutter/flutter-intellij/blob/2a58c987e9c7b0e2c1c749076b218908f017bbba/flutter-idea/src/io/flutter/FlutterBundle.properties#L240-L241

See #5070

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
It is possible that there are still users on Flutter 2.x. However, I don't think that's reason enough to keep this complex configuration. I already approved your PR, so this is effectively fixed.
