### ISSUE TITLE
No error message if Dart SDK is not set or is set incorrectly

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#636]
Currently we find the Flutter SDK from the Dart SDK. If the Dart SDK is not set or it's set to a non-Flutter SDK, we don't show any error message, but any Run Configurations for Flutter are disabled.

We need to somehow tell the user that they should set the Dart SDK to the one in $FLUTTER_SDK/bin/cache/dart-sdk and then everything will work.

**Comment by pq** [comment]
Good catch!  We actually used to have a check for this.  (I'll try and dig those old bits up.)

Moving on, we might add a check for this condition here:

    io.flutter.inspections.SdkConfigurationNotificationProvider#createNoFlutterSdkPanel

(`flutterSdk` will be `null` but `DartSdk.getDartSdk(project)` won't be.)

Self-assigning as I may tackle this quickly.  Feel free to ping me if you want to snag it.

**Comment by skybrian** [comment]
I'm about to send a pull request, might want to wait for that. (Although I'm sure you'll do it better.)

**Comment by skybrian** [comment]
https://github.com/flutter/flutter-intellij/pull/637

**Comment by pq** [comment]
Cool!  (And don't be too sure of that!)
