### ISSUE TITLE
android studio auto import dart

### ISSUE THREAD

**Issue by anjiuzhe** [flutter/flutter-intellij#6382]
## Steps to Reproduce

Is there a way to make Android Studio auto import packages from external libraries? What I mean by that is I got to pub.dev getting package I want and then in Android Studio I can write name of the class I want to use from that package and IDE would auto import it for me...

thank you

## Version info

[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.3.5 on channel stable at /Users/btgo/Flutter/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (13 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/btgo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] Connected device (4 available)
    • V2024A (mobile)          • a8bf8349                                 •
      android-arm64  • Android 12 (API 31)
    • “Admin”的 iPhone (mobile) • c91d90a0075bce7a8ba2d38333f625480180183c • ios
      • iOS 16.0.3 20A392
    • macOS (desktop)          • macos                                    •
      darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)             • chrome                                   •
      web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by stevemessick** [comment]
It already does this; I just tested it and it worked. You need to update `pubspec.yaml`, run `pub get` (there will be a butter bar above the editor with a button to do it), then wait for the Dart analyzer to update its index (doesn't take long, but it is possible to get "No suggestions" before it is done). Have you done all that and it still does not work?

**Comment by anjiuzhe** [comment]
sorroy,it working now,maybe there was something wrong。thanks
