### ISSUE TITLE
Allow project imports first before package imports

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#6387]
## Steps to Reproduce
1. Import [`firebase_auth`](https://www.pub.dev/packages/firebase_auth) package
2.  Create a `User` class. 
3. In a different directory, type `User`. 

Try to import the `User` class. 

**Screenshot:** 

<img width="480" alt="Screen Shot 2022-11-03 at 11 51 42" src="https://user-images.githubusercontent.com/40364434/199702690-6f06899c-77aa-4bbb-88ca-b81150fb0670.png">

The options show the package imports first before the project's import. I think we should first prioritize the project's imports. 

## Flutter doctor 
```
[✓] Flutter (Channel master, 3.5.0-10.0.pre.17, on macOS 12.6 21G115 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by stevemessick** [comment]
Closing this one since the issue has been duplicated in the proper repo. Thanks for the suggestion!
