### ISSUE TITLE
Allow an option to add all the required arguments at once. 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#6392]
## Steps to Reproduce

<img width="339" alt="image" src="https://user-images.githubusercontent.com/40364434/200115044-0545b75c-e11e-445f-a94e-80753cfe5f06.png">

It'd be nice if we can have an option to add all the required arguments at once. 

## Version info

```
[✓] Flutter (Channel master, 3.5.0-10.0.pre.17, on macOS 12.6 21G115 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by stevemessick** [comment]
I added https://github.com/dart-lang/sdk/issues/50445 that references this. If you still have that screen shot handy you might want to add it there.
