### ISSUE TITLE
Identify what IntelliJ products we want to support (and how).

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#64]
The sooner we get clear on what we want to support the better.

It would also be good to clarify whether we want tiers of support in order to provide the best experience in each product or shoot for a lowest common denominator that works equally well in all but sub-optimally in some.

cc @devoncarew

**Comment by pq** [comment]
> @pq do you have a concrete example of what kind of issue we might get?

This is something we should carve out some time to explore.

The main things I'm aware of are largely UI and flow-centered.  In particular, project creation and management is different in IDEs that support multiple modules per project (IDEA) versus only one (the "smaller" IDE offerings (such as I presume CE).

**Comment by pq** [comment]
> I'd like to understand the likely workflows in Android Studio better. 

Me too! :)  Sounds like an AI... 👍

**Comment by devoncarew** [comment]
Let's assume IntelliJ CE and ultimate for now, and open specific issues for additional platforms (Android Studio, AppCode) to track the work for those products, when we do want to support them.
