### ISSUE TITLE
support the device pulldown for bazel launch configs

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#640]
The bazel launch config currently can work when we have a dart sdk configured but no flutter sdk. In these cases, it would be nice to be able to have a device pulldown as well, so the user doesn't have to specify the `-d` device in the launch config (`-- -d <deviceid>`).

**Comment by devoncarew** [comment]
Or, support specifying the device ID in the bazel launch config.

**Comment by devoncarew** [comment]
@skybrian, is this done?

**Comment by skybrian** [comment]
Mostly, but there is still the progress indicator. So, if we close this then I'll open another bug.

**Comment by skybrian** [comment]
Actually that is now #777 so closing this.
