### ISSUE TITLE
Weird IntelliJ Error

### ISSUE THREAD

**Issue by Herddex** [flutter/flutter-intellij#6400]
## Steps to Reproduce

I just created a brand new Flutter project and after roughly 10 - 20 minutes I ran the "Format" command (CTRL + ALT + L) and I got the exception. Another plugin (Discord Integration) experienced the exact same exception multiple times before, without any input from me. So it might be something caused by the IDE
[bug-report.md](https://github.com/flutter/flutter-intellij/files/9995317/bug-report.md)

## Version info
Flutter plugin version 71.0.5. Dart plugin version 222.4345.14
By the way, `Tools > Flutter > Flutter Doctor` had no effect in IntelliJ.

**Comment by stevemessick** [comment]
The stack trace in the linked file contains "(see the cause for stacktrace)" which makes me think there may have been another stack trace that could help identify the source of the problem. It looks like another project had been created and closed or deleted. Could you tell us more about what you did prior to creating the new Flutter project? If possible, finding that other stack trace might be helpful.
