### ISSUE TITLE
Android Studio freezing on Mac M1 chip

### ISSUE THREAD

**Issue by jszental** [flutter/flutter-intellij#6411]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
Every time I run Android Studio on my mac M1 the program freezes and needs to be force closed
I submitted a bug to google but they directed me here: https://issuetracker.google.com/issues/259993791
Attached files are before I upgraded flutter to 3.3.9 but same issue is happening

## Version info
Android Studio 2021.3.1 Patch 1, build AI-213.7172.25.2113.9123335

[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-AU)
    • Flutter version 3.3.9 on channel stable at /Users/Josh/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (8 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/Josh/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 37861884-DC07-488D-8672-A4D6DF0510CC • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
[idea.log](https://github.com/flutter/flutter-intellij/files/10129198/idea.log)

https://user-images.githubusercontent.com/64125098/204965391-cf84eb91-c312-49a8-991f-255516b10d3e.mov

[threadDump-20221115-141756.txt](https://github.com/flutter/flutter-intellij/files/10129199/threadDump-20221115-141756.txt)

**Comment by stevemessick** [comment]
Search in your log file for `GET_NAVIGATION_INVALID_FILE` and make note of the full file path that is reported. Does that file exist? If not, what happens if you create an empty file with that path? If it does exist, what happens if you remove it?

**Comment by jszental** [comment]
The file does exist. This freezing occurs with other projects too.

**Comment by stevemessick** [comment]
What happens if you remove it? (Backup and restore after testing, of course.)

**Comment by jszental** [comment]
I have removed it but I am still getting errors. I think this is an issue with the IDE not the project files. Any other way I can try to resolve this?

Thanks,
Josh

**Comment by stevemessick** [comment]
Since changing the problem reported by the plugin has no affect, I doubt this is a issue with the Flutter plugin.

Your movie shows a blinking icon in the tool bar. Actually, it seems to be a quarter-circle that grows in three steps, continuously. What is that? Do you have other plugins installed, other than Dart and Flutter? If so, does the problem persist after the other plugins are disabled and the IDE restarted?
