### ISSUE TITLE
Using live preview? Is it still here?

### ISSUE THREAD

**Issue by princestha** [flutter/flutter-intellij#6412]
https://github.com/flutter/flutter-intellij/wiki/Using-live-preview

I see the article but is this feature still here? I have been wondering how I can get this working for the latest intelliJ.

**Comment by stevemessick** [comment]
That feature was removed but the page was not. I fixed it.

**Comment by princestha** [comment]
@stevemessick  is there anything comparable or practices which you might know about? I looked into the vscode and intellij plugins, but the packages for those are not up to date. 
Thank you

**Comment by stevemessick** [comment]
The Dart plugin for VS Code is actually quite good. VS Code plugins cannot add new UI elements, so something like live preview could only be added if Microsoft adds it.
