### ISSUE TITLE
bazel launch config should have more info pre-populated

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#643]
From feedback:

> You should be able to derive working directory and list of targets etc from the project. launch script location also should probably be pre-populated.

There are several things we can infer here or pre-populate.

**Comment by devoncarew** [comment]
@skybrian, this is largely done, right? The directory and the launch script are pre-populated, and we're punting on the target discovery?

**Comment by skybrian** [comment]
Yes, I don't plan to do more work. For the remainder (that we're punting on), should we keep this bug open or start a new one?

**Comment by devoncarew** [comment]
> list of targets etc

If we don't plan to do that work, I think we should just close the issue. If we do think we'll get to it, then opening another issue for the backlog makes sense.
