### ISSUE TITLE
At least one platform must be selected while creating flutter package

### ISSUE THREAD

**Issue by tashigeekyants** [flutter/flutter-intellij#6431]
Getting **"At least one platform must be selected while creating flutter package"**

## Steps to Reproduce

- Update plugin version to `71.0.3`
- Create new package

## Version info
`71.0.3`

## Screenshot
![image](https://user-images.githubusercontent.com/113091088/206180481-13ed72cc-0f00-4b1b-831d-bdceb06655ae.png)

**Comment by stevemessick** [comment]
This happens when project type "Package" is selected in the new project wizard dialog. For now, please use the CLI tool to create new packages. All other project types can be created from the IDE.

**Comment by tashigeekyants** [comment]
> This happens when project type "Package" is selected in the new project wizard dialog. For now, please use the CLI tool to create new packages. All other project types can be created from the IDE.

sure, Would be great if we can downgrade the version of the plugin.

**Comment by keybow007** [comment]
Same problem for me at 71.1.3

![スクリーンショット 2022-12-16 14 30 42](https://user-images.githubusercontent.com/12907755/208029127-d41ecdc6-2411-4937-93f6-c3d63232d331.png)

**Comment by tolotrasamuel** [comment]
71.2.3 not yet fixed
