### ISSUE TITLE
Error getting Flutter sdk information

### ISSUE THREAD

**Issue by Pyrek1991** [flutter/flutter-intellij#6449]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I have updated intelliJ IDEA to the latest version

## Version info

[√] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3
    • Flutter plugin version 71.0.6
    • Dart plugin version 223.7571.203

[bug-report_3.md](https://github.com/flutter/flutter-intellij/files/10201579/bug-report_3.md)

**Comment by stevemessick** [comment]
Dup of #6403
