### ISSUE TITLE
Crash on startup after 2022.3 and dart plugin 223.7571.203

### ISSUE THREAD

**Issue by mrorabau** [flutter/flutter-intellij#6458]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Upgraded to 2022.3 and then opened a flutter project.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

```
flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.3.5, on Microsoft Windows [Version 10.0.19044.2251], locale en-US)
    • Flutter version 3.3.5 on channel stable at C:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (8 weeks ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:/Users/mark/AppData/Local/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:/Users/mark/AppData/Local/Android/Sdk
    • Java binary at: C:\Users\mark\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32505.173
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Users\mark\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Users\mark\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4345.14
    • Flutter plugin version 70.2.5
    • Dart plugin version 222.4345.14

[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\mark\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.7571.182
    • Flutter plugin version 71.0.6
    • Dart plugin version 223.7571.203

[√] VS Code (version 1.72.0)
    • VS Code at C:\Users\mark\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0
```

**Comment by mrorabau** [comment]
@stevemessick out of curiosity, why do you have intellij prompt users to report these bugs if support just closes them?

**Comment by stevemessick** [comment]
It's possible I was a bit hasty in closing this. There was a bug in the plugin that caused everyone who upgraded to 2022.3 to see an error when starting IntelliJ. Many people filed bug reports. For those that included a stack trace, I marked them as a duplicate of the first one to be filed. Those that had no actionable content I just closed, assuming it was the same problem. If you had a problem that included `FAST_TRACK` in the stack trace then it was a dup. If it was something else then please add the stack trace and we'll re-open this one. As it is, there's nothing to work with.

Version 71.1 of the plugin fixes the `FAST_TRACK` problem. However, if you rely on the embedded devtools then you might want to wait. There's a problem with licensing that surfaced in 71.1 and the embedded devtools does not work. The implementation in the plugin still works (disable the check box in preferences to switch) but it does not have the full functionality of embedded devtools. Of course, you can also run devtools in the browser, so you're not completely cut off, it is just less convenient for some people.

**Comment by mrorabau** [comment]
Ah, I got it. My bad, I thought that when I posted it through Intellij it automatically attached the stack trace (It showed it to me). Anyways, I appreciate all the hard work you are doing, just not always  sure whether I'm helping by submitting the bug reports or not.

**Comment by stevemessick** [comment]
No problem! I'll have to check if anyone has created an issue asking the stack trace to automatically be included.

**Comment by stevemessick** [comment]
I recall now that we did discuss doing that but decided against it because there could be proprietary information included that people would not want to share.
