### ISSUE TITLE
JxBrowser's distribution link should use `FLUTTER_STORAGE_BASE_URL` instead of hard-coded `storage.googleapis.com`

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#6462]
https://github.com/flutter/flutter-intellij/blob/88735eae6874e96306c8bc99111e749e19267ea9/flutter-idea/src/io/flutter/utils/JxBrowserUtils.java#L55-L58

There was a hard-coded distribution of the JxBrowser, which may lead to unreachable issues when users have set the `FLUTTER_STORAGE_BASE_URL` environment.

## Proposal

We should use `FLUTTER_STORAGE_BASE_URL` instead if it's valid.

**Comment by stevemessick** [comment]
Good catch.

@helin24 might get to this before I do.
