### ISSUE TITLE
No more device selector when going back to old UI

### ISSUE THREAD

**Issue by rxseb** [flutter/flutter-intellij#6466]
## Steps to Reproduce

1. Enable new UI in settings.
2. Restart.
3. Disable new UI in settings.
4. Restart.
5. Device selector is gone.

## Version info

[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19045.2251], locale en-GB)
    • Flutter version 3.3.9 on channel stable at D:\install\software\flutter\3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\install\software\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = D:/install/software/Android/Sdk
    • Java binary at: C:\Program Files\Eclipse Adoptium\jdk-11.0.14.101-hotspot\bin\java.exe
    • Java version OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.4.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.1.3
    • Flutter plugin version 71.1.6
    • Dart plugin version 223.7571.203

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.123
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
I cannot reproduce this. I just switched between new and old, twice, and the device selector always appeared.

Two things come to mind.
- I'm using the preview version of 2022.3.1. If you're able to switch to that, does it help?
- Some people manually added the device selector prior to plugin version 71.1 being available. Did you? If so, perhaps undoing whatever that manual step was could help.

**Comment by rxseb** [comment]
I didn't add the device selector manually.

But I noticed a strange behaviour that could be linked to the issue. If I open a non mobile Java project with the new UI, it shows a blinking device selector displaying devices used by Flutter. That's why I wanted to come back to old UI.

I managed to show the device selector again by invalidating caches, but just once. I switched UI again and now the trick doesn't work anymore.

I don't understand what's going on here and couldn't tell if it is an issue from the plugin or IntelliJ.

**Comment by ksilz** [comment]
@rxseb I'm using the latest version of IntelliJ Ultimate 2022.3 and the Flutter plugin. In a Java project (Spring Boot & Gradle), the Flutter device selector erroneously shows up, blinking. My project doesn't have an Android or Flutter facet. Is that what you see as well?

https://user-images.githubusercontent.com/1061209/208108683-2f0b27e4-7906-45e1-84a5-900d28296e95.mp4

**Comment by rxseb** [comment]
@ksilz Yes but for me it happens only with the new UI.

**Comment by ksilz** [comment]
@stevemessick For me, the blinking device selector shows up in the **old** UI. Do you want me to file a new issue for it?

**Comment by alexander-doroshko** [comment]
Blinking device selector is already filed as #6467

**Comment by ksilz** [comment]
@alexander-doroshko Thank you! Added my comment there.

**Comment by stevemessick** [comment]
Has anyone who cannot see the device selector tried using IntelliJ 2022.3.1 Preview?

See #6467 for an update on the blinking device selector.

**Comment by stevemessick** [comment]
@rxseb Could you try this again using plugin version 71.2? I have not be able to reproduce the problem. However, I'm now using the latest release candidate for IntelliJ 2022.3.1, which could possibly explain it.

**Comment by rxseb** [comment]
@stevemessick Updating IntelliJ to 2022.3.1 and Flutter plugin to 71.2 solved the issue.
I still have an empty device selector for non mobile projects but at least it is not blinking anymore.

**Comment by stevemessick** [comment]
Great! Thanks for the update.
