### ISSUE TITLE
Code Completion not working properly anymore after upgrading to 2021.3

### ISSUE THREAD

**Issue by S-Man42** [flutter/flutter-intellij#6470]
Hi,

I am not quite sure whether this is a Flutter or an Android Studio issue. Hopefully somebody can help me here, when it is a 

I upgraded my Android Studio from 4.x to 2021.3 at the same time I upgraded from Flutter 2.x to 3.3.9) a few weeks ago. From that point my auto completion has not been working properly anymore.

* [CTRL] + [SPACE] still opens and display a suggestion list containing
  * Flutter internal classes (I assume this is because of already imported flutter/material.dart package)
  * Classes from current file
  * Classes from explicitly imported files

Everything, which is not already explicitly imported into the current working file is ignored. So I am not able to use automatical imports, I need to find the correct file path by myself and have to include it manually before further writing.

What works:
* I observed, an older version of my project works fine on the same setting. So I am wondering, whether a project may becomes too huge? (currently > 1000 files in the `lib` directory and > 40 external libs in `pubspec.yaml`) But why did the setup before the upgrade worked properly?
* When I open the project on a pure IntelliJ (with installed Flutter/Dart plugins, of course), the code completion works as well

What I tried:
* Cleared/Removed every possible cache directory I could find (Flutter, Pub, Android Studio, Gradle, ...)
* Completely upgraded, removed and reinstalled the entire setup
* No PowerSafe mode
* My mates have no problems with the project having similar setups

Flutter doctor:

```
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19045.2251], locale de-DE)
    • Flutter version 3.3.9 on channel stable at E:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at E:\Android\sdk                                                                      
    • Platform android-33, build-tools 33.0.1                                                            
    • ANDROID_HOME = E:\Android\sdk                                                                      
    • Java binary at: E:\Android\Android Studio\jre\bin\java                                             
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)                        
    • All Android licenses accepted.                                                                     

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2251]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 103.0.1264.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
(AS Dart Plugin: 213.7433, Flutter Plugin: 71.1.3)

If relevant: https://github.com/S-Man42/GCWizard/tree/master

Thanks in advance,
Mark

**Comment by stevemessick** [comment]
@S-Man42 just wanted to let you know we're trying to get you some help, but have a couple urgent problems to tend to first. The fact that others do not have a problem, but you do, suggests something is not set up correctly on your computer.

**Comment by stevemessick** [comment]
There were a few versions of the Flutter SDK that had a problem with completion, just as you described. The problem was fixed, though. Do you have any older versions of Flutter or Dart on your computer? Check the Flutter plugin settings and ensure that the correct Flutter SDK is showing in the top panel. Also, I'm not too familiar with Windows, but I believe it allows you to specify where to find applications (which is done in Linux by setting the PATH environment variable). Check that configuration option to make sure there are no alternative SDKs on the path.

**Comment by S-Man42** [comment]
Thanks, Steve.

I cleaned my entire systems concerning Android/Flutter/IntelliJ. So tried to remove Flutter as well. Currently the correct (and I am pretty sure the only installed) version is selected in the IDE and the PATH environment variable. Although I tried to find every related cache directory, maybe there's still one left I didn't find? Could you tell me, where Flutter creates caches in Window?

**Comment by stevemessick** [comment]
@scheglov Do you know where the analysis server cache is located in Windows?

**Comment by stevemessick** [comment]
@S-Man42 There's an environment variable named `LOCALAPPDATA ` that holds a number of caches. I don't know exactly what the name of the Dart cache is, but it should be obvious. (On Mac it is `~/.dartServer/.analysis-driver`) It has a bunch of subdirectories that have two-letter names. You can delete it and it will be rebuilt the next time it is needed. It's probably best to shut down the IDE before deleting it. (We already have an open issue about deleting that directory when the IDE clears caches.)

As for Flutter itself, it caches build info in the project, in a directory called `build`. It is safe to delete, but that won't affect completion. Let us know if that helps.

**Comment by S-Man42** [comment]
@stevemessick Unfortunately I have no such environment variable... there's only the AppData/Local directory in the user path. But there I cannot find anything like a dartServer cache or similar.

These are the cache directories I killed:

```
Gradle (Windows: user/.gradle)
Pub cache (Windows: user/appdata/local/pub)
Android Studio
    Windows: 
        user/.android
        user/appdata/local/google/androidstudioX
            caches
            compiler
            compiler-server
            conversion
            frameworks
IntelliJ (Project Path ./.idea)
Build Path (Project Path ./build)
```

**Comment by jensjoha** [comment]
On my Windows machine (and I'd think that's the standard) it's in `C:\Users\<USERNAME>\AppData\Local\.dartServer`.

**Comment by stevemessick** [comment]
Thanks, @jensjoha ! 

@S-Man42 does that help?

**Comment by S-Man42** [comment]
No unfortunately it doesn't help.

I currently tried at an Ubuntu VM, which works fine. So there's no project issue here...

**Comment by jensjoha** [comment]
As a small update for this issue, I'm actively investigating, but can't promise anything just yet.

**Comment by jacob314** [comment]
Sorry to hear imports of files not in scope is not working in IntelliJ.

One other thing that could help us debug this issue is if you could try opening your project in VSCode.
https://docs.flutter.dev/development/tools/vs-code
If code completion of names not in scope works in VSCode but not IntelliJ that will help us narrow down where our bug is.

Fyi @jwren as the issue for this is likely in the Dart IntelliJ plugin of the Analysis Server rather than the Flutter IntelliJ plugin.

**Comment by jensjoha** [comment]
My status so far:

On a test query - asking for completion after the `m` in an added line `print(Cryptm);` in the `main` method in `lib/main.dart` - I experience the same as you.

I've modified the analyzer to have a much larger timeout and then I start getting the wanted results. On subsequent calls (it has to do some stuff the first time) it takes ~400 ms. Most of this time is spent sending log data to the plugin that seemingly does not use it. I've created https://github.com/flutter/flutter-intellij/issues/6574 to hopefully get that disabled. For my testing, disabling the flutter intellij plugin so that I only have the dart intellij plugin enabled (which doesn't ask for the same log data) the query is now answered in ~150 ms instead.

The default timeout is 100 ms so this is still not fast enough, though I would argue for increasing the timeout. I've created https://github.com/dart-lang/sdk/issues/51065 for that.

I have another thread to pull to see if I can make it faster and we'll see what happens.

**Comment by S-Man42** [comment]
@jacob314 In VSCode it works fine!

@jensjoha Sounds good so far.

**Comment by stevemessick** [comment]
@jensjoha Thanks for digging into this! I suspect the main problem was the log data. I've removed that. The 100ms timeout is probably fine, although I don't see why doubling it would be a problem (but maybe the SDK engineers have a different idea). See the code in the [Dart plugin](https://github.com/JetBrains/intellij-plugins/tree/master/Dart) that handles completion: [`DartServerCompletionContributor.handleCompletion2()`](https://github.com/JetBrains/intellij-plugins/blob/78dddf6757e60510342efd2068be4a8894aced30/Dart/src/com/jetbrains/lang/dart/ide/completion/DartServerCompletionContributor.java#L182). Apparently, the UX requires typing Ctrl+Space multiple times to get the full completion list. I'm not sure how well users understand that. It was news to me. In any case, further improvements will be in the Dart SDK or the Dart plugin, not the Flutter plugin. So I think this issue can be closed.

@S-Man42 Do you get the results you want if you type Ctrl+Space several times? It may take 5-6 tries today, but with the next plugin update it should drop to 2.

**Comment by S-Man42** [comment]
I tested it. The autocompletion never appears, not even after 10 tries atm.

**Comment by stevemessick** [comment]
Thanks for checking. We have a new plugin ready for release Wed. (I'm doing som final testing today.) That should help with completions, but @jensjoha has already made some improvements to the analyzer that help even more. However, I don't know when that will be available in Flutter. After version 72 is available, could you update and check again?

**Comment by hschaeufler** [comment]
> Thanks for checking. We have a new plugin ready for release Wed. (I'm doing som final testing today.) That should help with completions, but @jensjoha has already made some improvements to the analyzer that help even more. However, I don't know when that will be available in Flutter. After version 72 is available, could you update and check again?

I had the same problems with another Flutter project. After updating to version 72.0.4 of the plugin, I can now use Autocompletion again. Thank you so much for fixing the problem.

**Comment by stevemessick** [comment]
It sounds like the plugin update has helped, and we'll get even better performance once Flutter is updated with the latest analyzer changes. Closing this now.
