### ISSUE TITLE
Please remove usages of `setExceptionPauseMode`

### ISSUE THREAD

**Issue by derekxu16** [flutter/flutter-intellij#6500]
That VM Service procedure is deprecated and we intend to remove it in v4.0 of the VM Service spec. Please use `setIsolatePauseMode` instead.

**Comment by stevemessick** [comment]
Some of our users are still using very old versions of Flutter. When was `setIsolatePauseMode` introduced? If it was very recent then we cannot simply replace one with the other. We'll have to check the SDK version and use whichever is appropriate, which could be a lot of overhead.

cc @jwren

**Comment by derekxu16** [comment]
It was added in version 3.53 of the VM Service spec, on Nov 17, 2021.

https://github.com/dart-lang/sdk/commit/0cad0e722483310a995732b44cc83c5689f9f7c9

**Comment by stevemessick** [comment]
@jacob314 This looks like it will be a fair bit of work to implement. We're going to have to change at least six call sites. We'll have to find a reference to the current SDK from whatever debug info is available (I don't have details or even know if that's possible, but I suspect it is). We'll have to check the SDK to see if it is capable of using the new API, and dispatch accordingly.

@derekxu16 This also affects the Dart plugin. Hopefully, you've already informed JetBrains, but I didn't see it on YouTrack.

**Comment by stevemessick** [comment]
We should also update to v4.0.

cc @alexander-doroshko

**Comment by derekxu16** [comment]
@stevemessick Thanks for the reminder, I just created an issue on YouTrack. I mentioned wanting to remove the proceudre in v4.0 of the VM Service spec in the initial description of this issue, but that isn't accurate. We would just ideally like to delete the procedure before Dart 3.0 is released.

**Comment by jacob314** [comment]
Migrating from the old to new APIs seems straightforward as it looks like this is mostly just a name change as far as we are concerned. There are some places where we check the Flutter version to determine which API to use. As there was over a year where both APIs were supported any Flutter version within that year should be ok as a point where we start using the new API.

It would be helpful to have a clear SLA for how long we support old Flutter SDKs. This change landed in the Dart SDK over a year ago but after Flutter 2.0.
