### ISSUE TITLE
Hot Restart (All Devices) and Hot Reload (All Devices) keyboard shortcuts don't work

### ISSUE THREAD

**Issue by rohan20** [flutter/flutter-intellij#6504]
## Steps to Reproduce

1. Run your Flutter app on multiple devices in debug mode
2. Perform the keyboard shortcut to  "Hot Reload (All Devices)" / "Hot Restart (All Devices)"
3. Observe that nothing happens

There is no problem with single device shortcuts.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/8232573/209455815-4e3fc59a-157f-486a-a854-de5341119e50.png">

<img width="747" alt="image" src="https://user-images.githubusercontent.com/8232573/209455812-b96bed5a-f3a1-41ac-8c69-2cc3a5fa6103.png">

## Version info

<details>
    <summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.5 21G72 darwin-arm, locale en-DE)
    • Flutter version 3.3.3 on channel stable at /Users/r.taneja/fvm/versions/3.3.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (3 months ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/r.taneja/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/r.taneja/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.0.6
    • Dart plugin version 223.7571.203

[✓] Connected device (3 available)
    • iPhone 14 Plus (mobile) • 8470846E-3AAB-4453-992D-5507EA2E63CB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by stevemessick** [comment]
This works for me. I even changed the shortcut to match yours. I tried with both old UI and new UI. No problems.

Try creating a new sample project. Does it work then? If not, I'm out of ideas. If it does work correctly then you might try un-installing IntelliJ and re-installing. Or add another user and try it there.

**Comment by rohan20** [comment]
I upgraded to `Build #IU-223.8214.52, built on December 20, 2022` today and now all hot-restart and hot-reload shortcuts work fine. Thank you for triaging this though :) 

Closing this issue.

**Comment by stevemessick** [comment]
Great! Thanks for the update.

**Comment by rohan20** [comment]
In case someone else is still running into this, you're not alone, it's happening to me again too. Build #IU-223.8214.52.

I just cannot figure out how to reproduce it :/
