### ISSUE TITLE
Flutter clean and build fail to complete

### ISSUE THREAD

**Issue by JustinWeru12** [flutter/flutter-intellij#6532]
## Steps to Reproduce

I'm not sure there is an exact way to reproduce this issue as it seems  to happen at random instances when building or running the project on a physical device.
I hope this is the right place to post this.
 Here is an outline of how it occurs.

I have looked at issue [#36763](https://github.com/flutter/flutter/issues/36763) and its not resolving the issue. 

1. You run a project on an ADB connected device. The app will successfully build and/or  run on the devices. 
2. Step 1 will randomly get stuck on assembling the project. This will not complete even if you wait for hours(tried it)
3. Ordinarily when you have a problem you will go for _flutter clean_ . if you try this it gets also stuck for hours with no completion. 
4. Upon inspecting this you find a file in your assembled assets with a number like "8043e5b2" but no extension.  This might be an svg, png , or jpeg image which was stripped off the extension and renamed, I found  out by looking inside the file or copying it outside of build and adding the extension.  This file will not rename, delete or be modified on any application on windows and yes that includes the IDEs.
5. The only solution that I found to delete this was to boot into safe mode with CMD and delete it from there.
6. If you pick to go with step 5 you are going to build the app successfully for a couple of times and then it happens again. The you have to go to safe boot to delete the build again.

## Version info

$ flutter doctor -v
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2364], locale en-UK)
    • Flutter version 3.3.10 on channel stable at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Usname\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\xxxxx\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\xxx\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.2)
    • VS Code at C:\mypathtoinstallation\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (4 available)
    •X683 (mobile) • 192.168.xx.xx:xxxx • android-arm64  • Android 
    • Windows (desktop)     • windows             • windows-x64    • Microsoft Windows [Version 10.0.19045.2364]
    • Chrome (web)          • chrome              • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)            • edge                • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by stevemessick** [comment]
It sounds like something is going wrong during image asset generation. That kinda sounds like an Android bug. There is a new version of Android Studio that is almost ready for release. Electric Eel RC 3 is available now. If you can, it might be worth giving it a try to see if the problem was fixed. Please let us know.
