### ISSUE TITLE
Device selector doesn't show when IDEA new UI is enabled

### ISSUE THREAD

**Issue by sky96111** [flutter/flutter-intellij#6551]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

1. Install IDEA 2022.3.1 edition.
2. Enable **New UI** in setting->new ui->enable new ui

Device selector, Flutter Hot Reload, Flutter Attach Buttons doesn't show in toolbar. 

## Version info

<details>
<summary>flutter doctor -v</summary>
<pre>
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 3.3.10, on openSUSE Tumbleweed 6.1.2-1-default, locale zh_CN.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/sky96111/sdk/flutter_linux_3.3.10-stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 周前), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /home/sky96111/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52
    • Flutter plugin version 71.3.6
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • openSUSE Tumbleweed 6.1.2-1-default
    • Chrome (web)    • chrome • web-javascript • Chromium 108.0.5359.124 stable

[✓] HTTP Host Availability
    • All required HTTP hosts are available
! Doctor found issues in 2 categories.
</pre>
</details>

**Comment by sky96111** [comment]
> @sky96111 What action is Shift+F10 bound to?

By default, it is build and run project

**Comment by stevemessick** [comment]
Odd, I cannot find an action named "Build and run project". Normally, Flutter projects are launched using the Run or Debug buttons, to the right of the run config drop-down.

The Flutter device selector is on the other side of the run config drop-down. Click it and you should see `Refresh`. Try that, and see if your devices are detected. Does that help?

**Comment by sky96111** [comment]
I got it. It is because I enabled IDEA new UI,  the device selector doesn't show.

Disabling new UI and I can select Linux Desktop now.

So the bug is flutter idea plugin isn't compatible with IDEA new UI. I will correct the issue title.

**Comment by stevemessick** [comment]
Yes, that is a known problem. Thanks for the update.

**Comment by sky96111** [comment]
> Yes, that is a known problem. Thanks for the update.

Need I close this duplicate issue?

**Comment by bernaferrari** [comment]
I can't develop with Flutter in the new UI :(

**Comment by stevemessick** [comment]
> Need I close this duplicate issue?

I can do it.

> I can't develop with Flutter in the new UI since yesterday :(

Known problem. I can't even work on it until JetBrains fixes a bug in their Gradle plugin that drives the compiler.
