### ISSUE TITLE
Dart files icons missing after update Android Studio 2022.1 stable

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter-intellij#6568]
After recent Android Studio update I am getting this in my project view:

![6mWXl](https://user-images.githubusercontent.com/26817206/212403433-8a2ead96-2c86-4b17-80be-1c0e7806e181.png)

Dart files are shown without any icon. The same effect is on opened source code tabs. Other files (gradle, yaml etc) are fine.

Please take a look, is there any workaround?

**Comment by beginner1010** [comment]
Yeah, the same here. Also, I noticed the green run icon next to void main disappeared, and I see no red line under a wrong code.

**Comment by beginner1010** [comment]
I'm surprised.. I really wonder how they set up their testing so while these changes obviously break UI, but still can go to production!

**Comment by MostafaSolimanMO** [comment]
Here's how it looks on Mac
![image](https://user-images.githubusercontent.com/43101916/212490002-9e9aa4e1-3d49-4840-9d3a-bcaa519a0309.png)

**Comment by giaur500** [comment]
It sounds like only light theme is affected? Can anybody confirm?

**Comment by giaur500** [comment]
> Yeah, the same here. Also, I noticed the green run icon next to void main disappea) red, and I see no red line under a wrong code.

Ok, I think I will look for way to downgrade for now. If anybody know any painless way (without lost all settings) on Linux, please let me know.

**Comment by kaushik-sharma** [comment]
It's due to a problem with the latest version of the dart plugin.

**Comment by giaur500** [comment]
Can I downgrade that plugin?

**Comment by kaushik-sharma** [comment]
You'll have to manually install a previous version from disk. You can download previous versions from their website.

**Comment by A7MeDG0L0L** [comment]
On MacOS

![image](https://user-images.githubusercontent.com/33913003/212529430-6147614a-adb4-4124-91b4-8a7920958d48.png)

**Comment by ycherniavskyi** [comment]
Also, it seems that the **High contrast** theme is not affected:
<img width="140" alt="image" src="https://user-images.githubusercontent.com/552025/212533250-03849457-725b-4fb3-ae47-9d22bdf2f7f7.png">
<img width="167" alt="image" src="https://user-images.githubusercontent.com/552025/212533274-c4f984c3-8984-4226-9325-5f3b7c213c2c.png">

**Comment by giaur500** [comment]
Should we report that to InteliJ? They have their own bugtracker: https://github.com/JetBrains/intellij-plugins/tree/master/Dart

**Comment by alexander-doroshko** [comment]
The Dart plugin with the fix for Android Studio 2022.1.1 has been published, please update.

**Comment by ycherniavskyi** [comment]
I can confirm that the issue is fixed!

**Comment by giaur500** [comment]
Yes fixed, actually it was not even realated to Flutter.

**Comment by nicks258** [comment]
On Android Studio `Android Studio Electric Eel | 2022.1.1 Patch 2` with updated Dart plugin `Version 222.4560 ` again this is happening Dart file icons is missing.

**Comment by giaur500** [comment]
221.6096 is still fine. Android Studio updater does not prompt for update in my case.
