### ISSUE TITLE
Decoded string from `0x0` does not display `NUL` in the "Varaiables" window

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#6572]
But the IDEA's editor window does.

![image](https://user-images.githubusercontent.com/15884415/212808134-cf0ef9e4-4bd2-4851-80c2-8908c3ec8d86.png)

## Steps to Reproduce

```dart
final Uint8List test = Uint8List.fromList([0x0]);
final String decoded = utf8.decode(test);
print(decoded);
```

## Version info

N/A

**Comment by stevemessick** [comment]
Using the master channel with the latest Dart and Flutter plugins in IJ 2022.3.1, I get a slightly different variables view.

<img width="121" alt="Screenshot 2023-01-19 at 12 50 11 PM" src="https://user-images.githubusercontent.com/8518285/213556976-0ecb2c7e-98db-4564-98b8-b41e0703ef34.png">

What do you expect to see?

**Comment by AlexV525** [comment]
> What do you expect to see?

 Could be `NUL` which is similar to the IDEA, I don't know how to type it out directly, you can found it in the screenshot.

**Comment by stevemessick** [comment]
I think this is fixed already. But it isn't available in the stable channel yet.

**Comment by stevemessick** [comment]
This is not fixed, but it is not a Flutter issue. I can reproduce it using the Dart plugin (Flutter is not installed).

It might get fixed if you create an issue in the JetBrains issue tracker:
https://youtrack.jetbrains.com
