### ISSUE TITLE
Please consider making "Format code on save" project-specific

### ISSUE THREAD

**Issue by tjarvstrand** [flutter/flutter-intellij#6576]
Please consider making "Format code on save" project-specific. The option is super useful and I really want to have it enabled in all my projects but this becomes a pain when trying to contribute to OSS projects that don't follow the dartfmt standard (which is more common than one might think).

## Steps to Reproduce

Try to contribute to a project which doesn't follow Dart formatting conventions.

**Comment by stevemessick** [comment]
Originally, all options were specific to the project. People were complaining that it was too much trouble to keep resetting the same options for every project. Now, only the Flutter SDK is saved on a per-project basis.

Your point about OSS formatting standards is good. We'll keep this suggestion open, but I can't promise when it will be addressed. I think VS Code already supports this.

**Comment by alexander-doroshko** [comment]
Note that IntelliJ IDEA / Android Studio now have native support of the "Format code on save" feature. It's independent from the feature in the Flutter plugin. See Settings (Preferences) -> Tools -> Actions on Save.

I know that the two equivalent features don't play well together when both enabled. But all should be fine if you enable only one of them. So you are welcome to disable "Format code on save" on the Flutter page and enable on the Actions on Save page. The latter is configured per project.

Starting from IDE version 2022.3.3 (not yet available), it will also be possible to configure the default values on the Actions on Save page. So those who need the same settings for all projects, will be able to configure them via File -> New Projects Setup -> Preferences (Settings) for the New Projects.

**Comment by tjarvstrand** [comment]
> Note that IntelliJ IDEA / Android Studio now have native support of the "Format code on save" feature

That's great to know! Will definitely check it out. Thanks!

**Comment by stevemessick** [comment]
Thanks, Alex. I'll add an issue to remind us to remove the Flutter setting. BTW, did you notice Apple changed "Preferences" to "Settings" recently? We can all stop doing the "Settings/Preferences" thing.

**Comment by stevemessick** [comment]
We're not going to make the Flutter setting project-specific, since the Dart plugin already does that.
