### ISSUE TITLE
look into compatibility with windows

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#658]
As a pair to this PR: https://github.com/flutter/flutter/pull/7613, we should look into what OS dependent code we have in the plugin (should be minimal).

**Comment by devoncarew** [comment]
Started a branch (https://github.com/flutter/flutter-intellij/compare/windows_support?expand=1) but will need to run through some things on a windows machine, and look at getting appveyor set up for CI testing.

**Comment by goderbauer** [comment]
Two things I noticed on Windows:
* Settings > Languages & Frameworks > Flutter doesn't show version info even when a valid Flutter SDK path is selected. 
* When I load a Flutter project, I am getting exceptions: `Unable to poll for Flutter devices: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\src\flutter\bin\flutter" (in directory "C:\src\flutter"): CreateProcess error=193, %1 is not a valid Win32 application`

**Comment by devoncarew** [comment]
Thanks for digging in! My branch fixes the 2nd issue - we're shelling out to the wrong script. The 1st issue is likely related.

**Comment by pq** [comment]
At this point we're caught up with `flutter_tools`.

**Comment by devoncarew** [comment]
Good support for opening (and creating) the android emulator will be important here (it'd not as critical for macos - we have good support there for opening the iOS simulator).

**Comment by devoncarew** [comment]
We're working! Any problems can be tracked as more specific issues.
