### ISSUE TITLE
Plugin not really compatible with the intellij new UI

### ISSUE THREAD

**Issue by mikehearn** [flutter/flutter-intellij#6590]
## Steps to Reproduce

1. Enable new UI.
2. Create a new project that's only for desktop platforms and web, _no mobile_.
3. Try to run it.
4. Get an error about no Android devices being connected.
5. Search for how to tell the plugin that this isn't a mobile project.
6. ?!?!

The problem is, the device selector dropdown doesn't appear in the new UI anymore, and there's no other way to choose the target. This feels maybe more like an intellij bug - the new UI shouldn't make existing plugins unusable - but maybe it needs adapting on the plugin side too.

**Comment by mariusvn** [comment]
related to https://github.com/flutter/flutter-intellij/issues/6549

**Comment by mariusvn** [comment]
you have to downgrade to flutter-intellij 71.2.6 or use the old UI

**Comment by stevemessick** [comment]
Thanks @mariusvn for the response.

@mikehearn Which version of IntelliJ and the Flutter plugin are you using?

**Comment by mikehearn** [comment]
flutter plugin 71.3.6

intellij 2022.3.1 (Ultimate Edition)

**Comment by stevemessick** [comment]
You can use the instructions from @mariusvn to install v71.2, which will show the device selector in the new UI. If you do, be aware that if you work in a non-Flutter project you will get errors frequently (like, each right menu button click plus other UI refreshes). We expect to publish v72.0 Wednesday, and it fixes these problems.

**Comment by stevemessick** [comment]
Do these problems still occur after updating the Flutter plugin to. v72?

**Comment by mariusvn** [comment]
not on my side, thanks for the work !

**Comment by stevemessick** [comment]
Thanks for checking. I'll close this now.
