### ISSUE TITLE
Hover stops working frequently

### ISSUE THREAD

**Issue by gisborne** [flutter/flutter-intellij#6596]
## Steps to Reproduce

Use IntelliJ to edit Flutter code for half an hour or so.

Try to get hover info about a red or white squiggly line.

## Version info

% flutter doctor -v
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64, locale en-AU)
    • Flutter version 3.7.0 on channel stable at /Users/gisborne/dev/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (8 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gisborne/Library/Android/sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/gisborne/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/gisborne/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /Users/gisborne/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.7571.182/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

Possibly related from the IntelliJ Help menu log:
`2023-01-31 11:45:42,127 [ 119130]   INFO - #c.i.o.a.i.PopupMenuPreloader - 3032 ms since showing to preload popup menu 'Editor Popup Menu' at 'EditorPopup(preload-bgt)' in 104 ms
`

**Comment by stevemessick** [comment]
I'll be pushing version 72 of the plugin to the JetBrains marketplace Feb 1. It has made some changes that might affect this. Once available, can you update and let us know if the problem still occurs?

If it does, there may be an issue with your project. You may recall the Dec release had two point releases. One of them had the side-effect of adding a Flutter-specific menu item to the `Other` menu. I think it was the device selector, which may display as `Nothing here` or the name of the selected device. You can use the `Settings > Appearance and Behavior > Menus and Toolbars` to check. Expand the `Main Menu` and see if `Other` has anything under it. I think it should be empty. If it isn't then it could be causing a slow-down, so just remove it. (Note, I'm not an expert on IntelliJ UI and could be mistaken about all this.) It (or something else) might also have gotten attached to the `Main Menu > Run` menu. There should be sub-menu with id `Flutter.MenuActions.Run`, but not a `Nothing here` or the name of whatever device you have selected. Also check the `Editor Popup Menu` (top level) since that's what the log says took 3s to refresh. If you have any questions about whether something belongs, show me a screen shot and I'll let you know.

**Comment by gisborne** [comment]
What does the "Other" menu refer to here? There are so many menus for various things in IntelliJ…

I don't see a "Other" option in the Device popup. If you meant that it was in the Appearance and Behavior > Menus and Toolbars, I do find a "Other" in the Main Menu settings (but I don't see it in the menu bar). I deleted that.

Since I don't yet have your update, I'll keep an eye out for changes when it drops.

**Comment by stevemessick** [comment]
Yes, everything I mentioned in the previous reply referred to the UI customization page in Settings. That page shows you everything that is available, regardless of visibility. The UI (e.g. right-click pop-up menu) shows only what is visible in a given context.

Version 72 is available now.

**Comment by gisborne** [comment]
Problem still occurs with 72.0.4

**Comment by stevemessick** [comment]
Are you able to try it on the master channel? There were some recent changes in the Dart SDK that might have an effect. To switch, use the command-line tool.
`flutter channel master`
`flutter channel stable`

Also, could you attach your log file (after removing confidential paths, if necessary)?

I just pushed a point release, 72.1. It won't affect this, but it wouldn't hurt to install it.

**Comment by gisborne** [comment]
Using master channel and 72.1, if anything it stopped working faster.
[hover-not-showing-idea.log.zip](https://github.com/flutter/flutter-intellij/files/10738858/hover-not-showing-idea.log.zip)

Here is the log since I restarted (more or less…).

**Comment by stevemessick** [comment]
Thanks for the log. Hopefully, this is unrelated, but I have to ask. I saw a lot of lines in the log tagged `#copilot`. If you disable that plugin do you still have this problem? I also saw some exceptions related to template presentations that I need to investigate.

**Comment by TabooSun** [comment]
Not sure if related, I don't see the documentation popup in the `Intellij Idea 2022.3.2` build. I have disabled all the plugins except `Flutter` & `Dart` plugins.

**Comment by hbock-42** [comment]
I have the same problem here.
I cannot tell exactly when it started but between 1 and 2 years ago.

Documentation on hover works great when I don't run flutter app trough intellij.
If I start working for a bit of time and run the app, after some time, when hovering a class, it opens the documentation for 100ms then close it instantly. If I want to see it, it have to click on the small circular warning icon at the end of UI that appears just under the class I am hovering.

For the `DateTime` class, the new hovering menue replacing the documentation says:
`{_Type} DateTime` and the icon is at the end of the line.
The warning icon says `Documentation and Problems  cmd F1` if I hover it
