### ISSUE TITLE
Android SDK and device icons missing from IntelliJ toolbar

### ISSUE THREAD

**Issue by davoutuk** [flutter/flutter-intellij#6599]
I've noticed that with the most recent IntelliJ versions, for my Flutter project the Android SDK and device icons are not longer present in the toolbar

**Comment by stevemessick** [comment]
In the IDE, please use the menu `Tools > Flutter > Flutter Doctor`. It will print to the console. Append that output here so we know your configuration. If available, also let us know if you are using the new UI. If the Flutter doctor doesn't show it, also let us know the version of the Flutter plugin you are using.

This problem sounds like the Android module is not loaded. You can confirm that in the Project Structure dialog. Open `Files > Project Structure` and select the left-side tab named `Modules`. Is there a module with "_android" in its name?

**Comment by davoutuk** [comment]
Flutter Doctor output shown below..

```
D:\Ian\Documents\sdk\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19044.2486], locale en-GB)
    • Flutter version 3.7.0 on channel stable at D:\Ian\Documents\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (9 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:/Users/Ian/AppData/Local/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:/Users/Ian/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.1
    • Flutter plugin version 72.0.4
    • Dart plugin version 223.8617.8

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Also screen shots from Files/Project structure/Modules

![image](https://user-images.githubusercontent.com/25985256/216275128-23b46b25-346e-4acc-82c2-4379d4f0b77f.png)

![image](https://user-images.githubusercontent.com/25985256/216275203-e2dcda52-18fa-4a86-86a2-bf5135998091.png)

**Comment by stevemessick** [comment]
Thanks. You clearly do have the Android module. TBH I'm not sure those tools are expected to show up in IntelliJ. Can you check with Android Studio? I know they are supposed to show up there.

**Comment by davoutuk** [comment]
The equivalent icons are displaying within Android Studio

**Comment by stevemessick** [comment]
This may be working as intended. I created an Android project in IntelliJ and did not see any SDK icon. Could you check that?

**Comment by davoutuk** [comment]
The missing icon is the basis of this ticket.   To recap the problem:

1. The icons were appearing in the IntelliJ IDE
2. With a new release of IntelliJ and/or a new release of the Intellij Flutter plugin the icons now no longer appear
3. When I reported this to the IntelliJ folks they suggested that I report this as a bug with the Flutter plugin

**Comment by stevemessick** [comment]
If you create an Android project with IntelliJ, do the icons appear in that project? They do not, for me. If they do appear for you, could you add a screen shot so I can be certain I'm looking for the correct icons?
