### ISSUE TITLE
Run flutter unit tests (flutter test)

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#66]
Need a way to run unit tests for Flutter apps. Assuming flutter continues to use package:test we probably want similar support to what Dart already has. Dart tests are presented in the IntelliJ test UI with linkage back to source and ability to filter pass/fail/skip.

**Comment by eseidelGoogle** [comment]
It's not clear how IntelliJ will know to run tests in `sky_shell` (flutter's test harness) or the `dart` command line (pure package:test).  The differences are that `sky_shell` exposes `dart:ui` but `dart` exposes `dart:mirrors` (as well as dart native library extension loading).  All non-mirrors dart code works in just the same in `sky_shell` so one could always use `sky_shell`.  IntelliJ could also tell which test needed which based on it being a flutter project vs. a dart project, or if we put one typ of test in a different directory.  It's also possible from analyzing the code to know if it depends on dart:ui or not.

**Comment by devoncarew** [comment]
Yup. Another resolution would be to have a different test launch configuration for flutter tests (`Flutter Test` instead of `Dart Test`). It would be good in general to avoid a parallel everything for flutter however, and just try and adapt and use existing Dart functionality where possible.

**Comment by branflake2267** [comment]
It would be nice to see launching the the flutter tests, `flutter test` execution if a right click and debug unit tests on, unite_test.dart. 
![screen shot 2017-05-21 at 12 50 49 pm](https://cloud.githubusercontent.com/assets/1326504/26286925/ef53d212-3e24-11e7-9e03-99eab15ac57c.png)

And if I could right click on the unit test, it would be nice to run the single test. 
![screen shot 2017-05-21 at 12 58 42 pm](https://cloud.githubusercontent.com/assets/1326504/26286943/4d0b59e8-3e25-11e7-9cd6-7bf3ff36f6a1.png)

**Comment by devoncarew** [comment]
So we don't lose track: PR out to allow for debugging `flutter test` tests: https://github.com/flutter/flutter/pull/10520

**Comment by skybrian** [comment]
Debugging tests was implemented in #1106.

Still to do: implement the test UI (instead of showing progress on the console) and add the ability to run a single test (rather than all tests in a file).

**Comment by devoncarew** [comment]
Initial version done! We'll track any additional work in more specific issues.

**Comment by xster** [comment]
I may have missed it but is there some documentation for how to use it? 

I'm on v15.0. 
![screen shot 2017-07-05 at 3 53 33 pm](https://user-images.githubusercontent.com/156888/27888359-6c11328e-619a-11e7-9252-36f260276c74.png)

Choosing run/debug on a test file shows 2 template configurations. One does dart run test and the other tries to run it as a full flutter app. 

Maybe I did something wrong.

**Comment by skybrian** [comment]
This sounds like a bug where the Flutter run config is triggering for tests. It didn't do this for a simple "hello world" test file, but perhaps it triggers for more complicated tests.

Relevant code:
https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/run/FlutterRunConfigurationProducer.java#L49

By calling getFlutterEntryFile(), it checks for a flutter import, but it should also check that the file is not a test. (Maybe check that there is no package:test import?)

**Comment by devoncarew** [comment]
From a brief look at the code, I think this issue is specific to trying to run tests from the flutter repo, in `//packages/flutter/` - i.e., just to the defining package for `package:flutter`. I'll open an issue -

**Comment by devoncarew** [comment]
You could try working around the issue by manually creating a launch configuration (from `Run > Edit Configurations...`).
