### ISSUE TITLE
Update Dart plugin to suppress explorer pub actions for flutter pubspecs.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#660]
We should only offer the `flutter package ...` commands.

<img width="587" alt="screen shot 2017-01-24 at 1 28 21 pm" src="https://cloud.githubusercontent.com/assets/67586/22267849/235b464a-e23a-11e6-9da5-745a6f4714f5.png">

@alexander-doroshko : how do you feel about adding logic to the Dart plugin that suppresses these contributions in the Flutter module case?

Incidentally, we should do the same for the editor notification for `pubspec.yaml`s (#509) and once we do, we can re-contribute `FlutterYamlNotificationProvider.java` removed in #661.

**Comment by alexander-doroshko** [comment]
SGTM. Some simple Flutter-specific things (like labels) can be fully done by the Dart plugin. Others can be suppressed by the Dart plugin and contributed by the Flutter plugin.

**Comment by pq** [comment]
Great.  Thanks @alexander-doroshko !

Do you want to tackle that or should we throw together a PR?

**Comment by alexander-doroshko** [comment]
PR is welcome!

**Comment by pq** [comment]
👍

**Comment by pq** [comment]
PR up for review: https://github.com/JetBrains/intellij-plugins/issues/472.

* suppresses pub actions in the editor, explorer and menu for Flutter module pubspecs in case Flutter is installed

**Comment by pq** [comment]
https://github.com/JetBrains/intellij-plugins/pull/472 landed. 👍 

This will be in the next stable plugin push.
