### ISSUE TITLE
Cannot run Flutter after updating

### ISSUE THREAD

**Issue by AMDphreak** [flutter/flutter-intellij#6608]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Reinstalled IntelliJ after it was acting bad. It would not show the 'create virtual device' dialog when the button was clicked, would not connect to my phone via wifi-debug dialog (while Android Studio had no problem doing so), I could not uninstall IntelliJ via uninstaller in Windows. I had to use Bulk Crap Uninstaller to forcefully remove it from the system, then I reinstalled IntelliJ using chocolatey package manager. After running it, flutter did not work.

## Plugin output for this bug

> ---
> 
> ## What happened
> 
> (please describe what you were doing when this exception occurred)
> 
> ## Version information
> 
> IntelliJ IDEA `2022.3.2` • Flutter plugin `io.flutter 72.0.4` • Dart plugin `223.8617.8`
> 
> Error getting Flutter sdk information.
> 
> ## Exception
> 
> null
> 
> ```
> com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\Users\rjamd\AppData\Roaming\flutter_windows_3.0.5-stable\flutter\bin\cache\dart-sdk\bin\dart" (in directory "C:\Users\rjamd\AppData\Roaming\flutter_windows_3.0.5-stable\flutter\bin\cache\dart-sdk"): CreateProcess error=2, The system cannot find the file specified
> 	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:359)
> 	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:84)
> 	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
> 	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
> 	at com.intellij.execution.process.ColoredProcessHandler.<init>(ColoredProcessHandler.java:23)
> 	at io.flutter.utils.MostlySilentColoredProcessHandler.<init>(MostlySilentColoredProcessHandler.java:49)
> 	at io.flutter.utils.MostlySilentColoredProcessHandler.<init>(MostlySilentColoredProcessHandler.java:44)
> 	at io.flutter.run.daemon.DevToolsService.setUpWithDart(DevToolsService.java:143)
> 	at io.flutter.run.daemon.DevToolsService.lambda$startServer$2(DevToolsService.java:127)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.io.IOException: Cannot run program "C:\Users\rjamd\AppData\Roaming\flutter_windows_3.0.5-stable\flutter\bin\cache\dart-sdk\bin\dart" (in directory "C:\Users\rjamd\AppData\Roaming\flutter_windows_3.0.5-stable\flutter\bin\cache\dart-sdk"): CreateProcess error=2, The system cannot find the file specified
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
> 	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:435)
> 	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:349)
> 	... 18 more
> Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
> 	at java.base/java.lang.ProcessImpl.create(Native Method)
> 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
> 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
> 	... 21 more
> ```

## Version info

```PowerShell 7.3.2
PS C:\Users\rjamd> flutter doctor -v
[✓] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22622.598], locale en-US)
    • Flutter version 3.7.1 on channel stable at C:\Users\rjamd\AppData\Roaming\flutter_windows_3.0.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (6 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\rjamd\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.2
    • Flutter plugin version 72.0.4
    • Dart plugin version 223.8617.8

[✓] VS Code (version 1.73.1)
    • VS Code at C:\Users\rjamd\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.598]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.78

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!```

**Comment by stevemessick** [comment]
According to your stack trace you are trying to run a program in `C:\Users\rjamd\AppData\Roaming\flutter_windows_3.0.5-stable\flutter`. Your installed Flutter version is 3.7.1, from the Flutter Doctor output. Is version 3.0.5 the one you uninstalled? Did you change the Flutter SDK version in the Flutter plugin settings after updating the SDK?

**Comment by AMDphreak** [comment]
> 

OK right now Flutter is working. There were some notices and when I clicked one of them it produced the error log in the Exception block above. I wish I took a screenshot of the notices that showed up when I launched the reinstalled IntelliJ. It would be good to make sure I'm not overlooking a potential problem but as it stands I think you can close this ticket.
