### ISSUE TITLE
Add a way to enable JXBrowser DevTools

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter-intellij#6612]
For debugging issues with embedded DevTools (such as https://github.com/flutter/flutter-intellij/issues/6406) it would be useful to be able to connect Chrome devtools (`chrome://inspect`) and see exactly what's being loaded (for example if DevTools redirected due to using an older URL format).

JXBrowser has an option to set a remote debugging port for this:

https://jxbrowser-support.teamdev.com/docs/guides/engine.html#remote-debugging-port

It would be good if this was exposed in some way so end users (or us) can turn it on/off to debug.

@helin24

**Comment by vlad-lubenskyi** [comment]
The remote debugging port is deprecated, and the port may be taken. I would recommend this instead: https://jxbrowser-support.teamdev.com/docs/guides/browser.html#devtools

**Comment by DanTup** [comment]
Ah, even better - thanks :-)
