### ISSUE TITLE
Get dependency button is invalid

### ISSUE THREAD

**Issue by zxy-c** [flutter/flutter-intellij#6620]
## Steps to Reproduce
Click get dependency button on top bar of dart file , Nothing appended.
So I navigate to pubspec.yml file and click Pub get button, It's working.
<img width="342" alt="image" src="https://user-images.githubusercontent.com/32016329/218349570-194544e6-2334-435e-8791-e136a4306876.png">

## Version info
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

**Comment by stevemessick** [comment]
I'm not sure what "get dependency button" refers to. Can you add a screenshot?
