### ISSUE TITLE
required and super keyword parse error

### ISSUE THREAD

**Issue by liugangnhm** [flutter/flutter-intellij#6631]
got error

```
'(', ':', <, <qualified reference expression>, '=', '?' or IDENTIFIER expected, got 'super'
```

![image](https://user-images.githubusercontent.com/743845/219992222-df7f4135-c457-4336-9c7f-76bd6b2ea8cb.png)

## Steps to Reproduce

just open /flutter/3.7.3/packages/flutter/lib/src/widgets/framework.dart

## Version info

Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-60-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 4
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.github.copilot (1.2.3.2385)
    Dart (221.6096)
    io.flutter (72.1.2)

Current Desktop: X-Cinnamon

**Comment by alexander-doroshko** [comment]
This was fixed in the Dart plugin (tracked as https://youtrack.jetbrains.com/issue/WEB-59361). The plugin update with the fix will be published shortly.
