### ISSUE TITLE
run button not display in each command

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter-intellij#6632]
It appears that there is a green "run" button located on line number 1 on my screenshot. My question is whether it is feasible to include a run button for each individual command? this is Flutter project.

![Screenshot 2023-02-21 at 10 35 33](https://user-images.githubusercontent.com/34953062/220252791-e7b71007-c120-49c3-9c6e-3aaabf7e3afb.png)

**Comment by stevemessick** [comment]
I don't know what you are asking for. Could you give more detail? Generally, the `Run` button used to launch a Flutter app is on the main tool bar. `Run` buttons for testing are associated with test files and the `Run` menu.

**Comment by bhanuka96** [comment]
No, it appears that there is a green "run" button located on line number 1. My question is whether it is feasible to include a run button for each individual command.

**Comment by bhanuka96** [comment]
Or need create separate .sh files for each command?

**Comment by alexander-doroshko** [comment]
Gutter icons in `.sh` files is not something that the Flutter plugin controls. It's a generic feature of IntelliJ IDEA. Its issue tracker is https://youtrack.jetbrains.com/issues/IDEA. You may search there if such request already exists. To my knowledge, such feature is not planned, `.sh` file can only run as a whole, not partially.
