### ISSUE TITLE
Error running 'main.dart': Language Language: Dart doesn't participate in view provider

### ISSUE THREAD

**Issue by VladimirCores** [flutter/flutter-intellij#6633]
Facing a problem running app on Fedora 37:
```
Error running 'main.dart': Language Language: Dart doesn't participate in view provider com.jetbrains.lang.dart.psi.impl.DartExpressionCodeFragmentImpl$1{vFile=LightVirtualFile: /dummy.dart, content=VirtualFileContent{size=0}, eventSystemEnabled=true}: [Language: TEXT]
```
![Screenshot from 2023-02-21 14-04-18](https://user-images.githubusercontent.com/442111/220329128-9d5944d7-5935-4e3a-ae0a-76bac41d51cd.png)

Dart & Flutter plugins versions:
![image](https://user-images.githubusercontent.com/442111/220328387-7d517cd1-53c9-4768-8dc0-e05ee73d1ffe.png)

![image](https://user-images.githubusercontent.com/442111/220329412-ab3e4949-0e50-453a-b835-5aee4185ae5f.png)

However running from terminal with `flutter run -d emulator-5554` works. 
Need help.

**Comment by stevemessick** [comment]
Can you run your app using the same emulator you use in the terminal?

**Comment by VladimirCores** [comment]
Yes, application runs, but the Debug section of the IDE is not working.

 ![image](https://user-images.githubusercontent.com/442111/220547763-bfddc58d-e060-4535-bc72-1a1764605de1.png)

**Comment by alexander-doroshko** [comment]
@VladimirCores Please open Settings ->  Editor -> File Types and check `Text` file type. What file names patterns are associated with text files? By default there's only `*.txt`. I guess you have something related to Dart there. Remove that pattern and you won't see the problem again.

**Comment by VladimirCores** [comment]
Yes, it has:

![Screenshot from 2023-02-22 12-22-07](https://user-images.githubusercontent.com/442111/220577442-05f41f62-6a74-4201-aa6e-da3723d878af.png)

And file type `*.dart` was missed in the Dart section

![Screenshot from 2023-02-22 12-24-42](https://user-images.githubusercontent.com/442111/220577997-8e05b5fd-dc04-45d8-9062-5d9f441bc8e8.png)

**Adding `*.dart` to that section fixed the issue**.

Thank you @alexander-doroshko for the hint! : )
(BTW how you guessed about that?)

**Comment by alexander-doroshko** [comment]
I'm from JetBrains =)

**Comment by stevemessick** [comment]
@alexander-doroshko Thanks! I suspected this was not an issue with either plugin but wasn't sure where to look next.

**Comment by VladimirCores** [comment]
Actually on initial plugin installation it did not recognize the file format `*.dart`.
