### ISSUE TITLE
Code completion does not work in IntelliJ 2022.3 (2022.2 works)

### ISSUE THREAD

**Issue by fhensley** [flutter/flutter-intellij#6635]
This is a reopening of the issue located at https://github.com/flutter/flutter-intellij/issues/3338

## Steps to Reproduce

Editing a dart file and when asking for code completion, a tooltip showing up saying "no suggestions" furthermore, getting errors on basic getters of flutter classes:

The getter 'body1' isn't defined for the type 'TextTheme'. (Documentation)

where
final originalTextTheme = ThemeData.dark().textTheme;
final originalBody1 = originalTextTheme.**body1**;

I am able to click through to the ThemeData class and dark method as well as textTheme, but cannot (cmd+) click through to body1.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022

Dart Plugin: 223.8214.16
Flutter Plugin: 72.1.4
Flutter (Channel stable, 3.7.4, on macOS 13.2.1 22D68 darwin-arm64, locale en-AU)
Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "macos_arm64"

**Comment by stevemessick** [comment]
I cannot reproduce this problem.
<img width="294" alt="Screenshot 2023-02-22 at 9 15 08 AM" src="https://user-images.githubusercontent.com/8518285/220705277-d0baae99-1639-487f-b47c-afaf6a33528e.png">
`cmd-B` takes me to the source.

I'm not sure how to diagnose the problem, but let's start with some more info. Please go to the `Dart Analysis` tool window and click the settings button (gear icon on the left side tool bar). Then select the `View analyzer diagnostics` option at the bottom of the menu. I'd like to see the contents of two pages: 
- Code Completion 
- Environment Variables

Please add screen shots.

**Comment by fhensley** [comment]
Sure. Here you go.
<img width="1196" alt="Screenshot 2023-02-23 at 1 37 11 pm" src="https://user-images.githubusercontent.com/4284274/220809780-892e6acb-65d6-4043-a934-683238ffd3c3.png">
<img width="1155" alt="Screenshot 2023-02-23 at 1 36 19 pm" src="https://user-images.githubusercontent.com/4284274/220809792-39b260b7-1078-4bc8-ac14-b7a54f36e4a5.png">
<img width="1155" alt="Screenshot 2023-02-23 at 1 36 06 pm" src="https://user-images.githubusercontent.com/4284274/220809796-5b1681a0-c4b2-4e76-b7ee-de8b200ea00f.png">

**Comment by fhensley** [comment]
Here's more weirdness
<img width="964" alt="Screenshot 2023-02-23 at 1 50 28 pm" src="https://user-images.githubusercontent.com/4284274/220811233-68a0a2f4-9473-4af3-833c-ef984d402def.png">
<img width="964" alt="Screenshot 2023-02-23 at 1 50 13 pm" src="https://user-images.githubusercontent.com/4284274/220811238-841a021a-014c-4976-b895-db46c044493d.png">

**Comment by fhensley** [comment]
<img width="639" alt="Screenshot 2023-02-23 at 1 52 11 pm" src="https://user-images.githubusercontent.com/4284274/220811471-f68b73bd-e282-4bde-a6ac-bfacc5225fc3.png">

**Comment by fhensley** [comment]
<img width="964" alt="Screenshot 2023-02-23 at 1 50 28 pm" src="https://user-images.githubusercontent.com/4284274/220811636-fd388c23-a1fa-437c-9664-8d0ed3c628d8.png">

**Comment by fhensley** [comment]
<img width="1080" alt="Screenshot 2023-02-23 at 1 56 22 pm" src="https://user-images.githubusercontent.com/4284274/220811883-c353effc-5e6e-4e41-9eb3-6e5af6a02a33.png">

**Comment by jacob314** [comment]
It looks like you are using the wrong Dart SDK for the project.
You are using the Dart SDK from Flutter 3.3.10 while elsewhere you are using Flutter 3.7.4.
Can you fix the Dart SDK specified in the settings dialog you sent a screenshot of to use the Dart SDK from the Flutter stable channel? Please let us know if that doesn't fix your issue.

**Comment by VB10** [comment]
i've some issues..
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.75.1)
[✓] VS Code (version 1.76.0-insider)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

`


![image](https://user-images.githubusercontent.com/17102578/221195894-f993d30f-dfcd-45e2-884c-a28c148445f6.png)

![image](https://user-images.githubusercontent.com/17102578/221195951-13a435da-62c4-4d7a-94e3-fcc5cea09d0d.png)

**Comment by MehmetKaranlik** [comment]
Im also having same issue with @VB10

**Comment by VB10** [comment]
i downgrade version to 2022.2.4. that's work for me 
<img width="589" alt="image" src="https://user-images.githubusercontent.com/17102578/221218221-c6bebc93-600c-4243-bbcb-77b376125dc0.png">

**Comment by fhensley** [comment]
I can confirm that downgrading to Build #IU-222.4459.24, built on November 22, 2022 works. Code completion now works as expected.

**Comment by stevemessick** [comment]
@fhensley @VB10 @MehmetKaranlik Do you have a sample project that reproduces this problem? Completion works for my sample projects. I'll keep trying, but if I cannot reproduce it then it will be difficult to fix. Also, for those who downgraded to IntelliJ 2022.2, what version of the Flutter plugin are you using, and which version of the Flutter SDK?

**Comment by VB10** [comment]
@stevemessick Whenever I create a basic project, this situation occurs. It doesn't seem like there is a project-specific problem. i left the flutter environment in below

<img width="697" alt="image" src="https://user-images.githubusercontent.com/17102578/222287277-222367ab-d0f5-447e-84f4-a43fccae3708.png">

**Comment by stevemessick** [comment]
@fhensley I just checked with Flutter SDK 3.3.10 (shown in one of your screen shots). The errors that are reported are legitimate. `body1` and `textSelectionColor` are no longer defined.

However, the version of Dart that is in 3.3.10 is 2.18.6, but the same screen shot that shows Flutter 3.3.10 also says it uses Dart 2.19.2. That first appeared in Flutter 3.7.2 and was in use through 3.7.5.

I'm not sure which Flutter SDK you have, but none of the possibilities define `body1` or `textSelectionColor`. Nor is `toggleableActiveColor` defined in 3.3.10.

There may be a mis-match between the SDK you use for command-line work and the SDK in your IDE. Using IntelliJ 2022.3, please select the menu item `Tools > Flutter > Flutter Doctor`. That will print to the console, and I'd appreciate it if you would append that output here.

Finally, can you give an example of code completion that works when using IntelliJ 2022.2 and does not work in IntelliJ 2022.3?

**Comment by stevemessick** [comment]
@VB10 Can you give me an example of code completion that works when using IntelliJ 2022.2 and does not work in IntelliJ 2022.3? 

Also, since the terminal and IDE have different environment variables, can you use IntelliJ 2022.3, and select the menu item `Tools > Flutter > Flutter Doctor`? That will print to the console, and I'd appreciate it if you would append that output here.

**Comment by VB10** [comment]
I made a video for you @stevemessick, maybe it will be helpful.

https://user-
images.githubusercontent.com/17102578/222289305-ca42920e-284e-4e55-9e67-1e52d94a66cc.mp4

**Comment by stevemessick** [comment]
@VB10 Thanks, I think the video is helpful, but it is a bit hard for me to read. Just to confirm, you're using Flutter 3.7.5 in both IDEs? And did you just create a sample project, or had you been using it for a while?

**Comment by fhensley** [comment]
> @fhensley @VB10 @MehmetKaranlik Do you have a sample project that reproduces this problem? Completion works for my sample projects. I'll keep trying, but if I cannot reproduce it then it will be difficult to fix. Also, for those who downgraded to IntelliJ 2022.2, what version of the Flutter plugin are you using, and which version of the Flutter SDK?

Thanks for looking into this @stevemessick. I didn't downgrade anything else. I just installed 2022 and let intellij copy the existing plugins.

**Comment by VB10** [comment]
Sure, testtxxx is an empty sample project and I opened both IDEs. (When I open my business project, it does not work again, but older versions and VSCode do.) @stevemessick

**Comment by fhensley** [comment]
@stevemessick, silly question. Are you testing this on a windows or a mac?

**Comment by stevemessick** [comment]
> Are you testing this on a windows or a mac?

macOS 13.2.1

**Comment by stevemessick** [comment]
@VB10 Could you zip up your `testxxx` project and attach it here? Even after doing the same thing you did in the video I still can't break completion.

**Comment by VB10** [comment]
@stevemessick the project in my video is a starter project (-> flutter create only)

**Comment by stevemessick** [comment]
@fhensley @VB10 I noticed you both have M1 Macs. I don't, but I asked a co-worker to try to repro this. Completion worked, so this is not a problem due to the M1 chips. Would either of you be willing to try a custom-built plugin that has more logging enabled?

**Comment by fhensley** [comment]
Absolutely
