### ISSUE TITLE
[Infra] Unable to build the plugin from Windows

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter-intellij#6640]
Because the plugin involves too many UNIX platform commands, such as `rm`, `unzip`, etc.
Consider refactoring those commands using Dart methods like `Directory.delete` and package:archive/`extractArchiveToDisk`.

## Steps to Reproduce

Run `dart tool\plugin\bin\main.dart make` on Windows.

## Related
- #6052

**Comment by AlexV525** [comment]
> Are you able to install https://gitforwindows.org/ ? There is no need to modify the build script when git-bash is available.

Sure. I checked again with the install steps of Git for Windows, it requires integrating Unix tools during the installation.

![image](https://user-images.githubusercontent.com/15884415/221746929-7d235c61-dce7-4054-8fe1-4361ac6eec93.png)

This might be worth to add into the `CONTRIBUTING.md`.

However, `rm` is still corresponding to the `Remove-Item` if the PowerShell is the default shell.

![image](https://user-images.githubusercontent.com/15884415/221747301-7132b3cd-a90e-4eef-a8d0-11fefb0a2991.png)

And it will throw exceptions if the deleted files do not exist. We need to modify the plugin a little bit. I'll send another PR.

> Also see: #6308 It is out-of-date and not currently being worked on (I think) but does show how to solve this problem.

I can pick it up if necessary.

**Comment by stevemessick** [comment]
Git for Windows includes a Linux-like shell, which is what I use. I don't know anything about PowerShell. In the Git setup dialog, I think I chose the top option (Git-only) but I can't remember for sure. I doubt I chose the bottom option, though.

We should check with the author of #6308 to see if he wants some help.

**Comment by stevemessick** [comment]
@AlexV525 If you're still interested in this, #6308 has been closed so no one is currently working on it.

**Comment by AlexV525** [comment]
> @AlexV525 If you're still interested in this, #6308 has been closed so no one is currently working on it.

Great, I'll try to refactor the tool if possible. Thanks for the reminder.
