### ISSUE TITLE
Android Studio Flutter & Dart support stops for unknown reasons.

### ISSUE THREAD

**Issue by aleks5751** [flutter/flutter-intellij#6656]
Hi,

I am using the Flutter plugin in Android Studio for creating an Android / iOS app. Since our team is big we decided to separate the app into local stand-alone packages. Meaning we have the repository's main lib folder which houses all the dependency injection logic. AND we have a packages/ folder which houses separate packages for features. For instance feature_sign in package houses sign_in logic, models package houses all the models in the project and use_cases package houses all the use cases used by the project.

The issue I am writing about today is that at some point my project ceases dart support for some of the above mentioned packages. Meaning that if I try to cmnd + click on a class nothing happens. When I click on an enclosing class's class name then it says no usages found for class. I can not pinpoint when this happens. However it is not very good having to spend days trying to debug the issue. To top it all off when it happens and I restart Android Studio then dart support stops in all packages, including the root lib folder.

Environment:
Mac OS 13.2.1 (22D68). 2,6 GHz 6-Core Intel Core i7
Android Studio: Build #AI-221.6008.13.2211.9477386, built on January 11, 2023.
Dart plugin: 221.6096
Flutter plugin: 72.1.2
Flutter version 3.7.0 on channel stable.
Flutter doctor - everything green and OK!

I know now that there used to be an issue that android studio can start behaving weirdly if packages are put into a folder called packages/. However I found that the issue was fixed about a year ago, so possibly that is not the issue. Especially considering that dart support stops for all files, even the main lib folder, which is not in the packages/ folder. However there is not much I can do about this... if it turns out being the issue.. Any comment?

Things I have tried:
1. flutter clean -> we are using the melos package, to run commands in all packages, and have also done melos clean to clean all packages -> invalidate caches, restart. Come back into android studio nothing changes.
2. Dart plugin in settings -> disable dart support for all packages. Invalidate caches, restart. Come back into project, turn dart support back on. Restart again. Did not help..
3. Copy root .iml files into some other folder and delete them from project. Restart android studio. Put .iml files back. Restart Android Studio. A few times dart support has come back for some packages. However if already at the point where all files dont have dart support then this does not help at all..
4. Clone project into a new directory from source control and set everything up anew. This usually fixes things... however it happens again after a while. And I am forced to do it again... Quite a pain to do, as I have to set the project up locally again. Need to add any things omitted from source control back in etc. Not very good having to spend an hour on this each time..

What I can also say is that this been happening for about a month now. So its not anything to do with the current version of the plugin. I would really appreciate some sort of help on this, thank you in advance!

**Comment by aleks5751** [comment]
I found one more issue on the melos plugin page:
https://github.com/invertase/melos/issues/379

Perhaps I can get a comment on whose problem it is then. The last comment in the issue that I referenced above suggests that its a bug with AS or the dart plugin? 
Will try not using melos and see if that fixes things. Will write a script for doing pub get, etc in packages..

**Comment by aleks5751** [comment]
Had some progress by doing this:
1. Copy both root folder .iml files somewhere and delete them from the project.
2. Restart android studio.
3. Run melos clean and flutter clean.
4. Paste the .iml files back in.
5. Restart android studio. Run melos bootstrap.

Seems that what differs from what I detailed above is running flutter and melos clean..

**Comment by stevemessick** [comment]
Please attach your log file. You can find it from the menu `Help > Show Log in Finder`. Be aware that it might contain confidential information, so check for that first.

**Comment by aleks5751** [comment]
[idea.1.log](https://github.com/flutter/flutter-intellij/files/10907834/idea.1.log)
[idea.log](https://github.com/flutter/flutter-intellij/files/10907836/idea.log)
Hey, thank you for the response!
Attached both log files I currently have. I think its best to look at the dates around 2023-03-05, +-1 1 day. 
Around that time I was experiencing the problem.

**Comment by stevemessick** [comment]
@aleks5751 Thanks for the logs. I see a couple places where an `INVALID_FILE_PATH_FORMAT` error similar to this is logged:
```
2023-03-05 00:03:33,889 [ 297776]   INFO - #c.j.l.d.a.DartAnalysisServerService - Error from unknown, SDK version = 2.19.0, server version = 1.33.4, error code = INVALID_FILE_PATH_FORMAT: Invalid file path format: /Users/.../my_projects/tf-inspection/.
```
The problem seems to be that your path has a dot at the end. Do you have any idea how that could happen? I can't think of any place the plugin would do that. I suspect that since the root of the project is invalid nothing gets analyzed. It might be worth checking your project files to see if a path ending in a dot is defined somewhere. Also check environment variables like PATH and anything melos uses.

I took a quick look at the melos package. It appears to do much the same things as the [mono_repo](https://pub.dev/packages/mono_repo) package does, although it might do a bit more. The Flutter plugin provides some support for monorepo projects. See the release notes for details on setting it up:
https://groups.google.com/g/flutter-announce/c/on6eKqmhD3A

I noticed in the melos bug you linked that you have `flutter analyze .` in the yaml file. I wonder if that could somehow be involved? I think the dot could be omitted, but I don't think that would write paths anyway so probably wouldn't matter.

@bwilkerson I see many errors identical to this (modulo timestamp). Could that be related to the `INVALID_FILE_PATH_FORMAT` problem? And do you have any idea what might cause the dot to be appended?
```
2023-03-05 00:02:46,555 [ 250442]   INFO - #c.j.l.d.a.DartAnalysisServerService - Error from unknown, SDK version = 2.19.0, server version = 1.33.4, error code = FILE_NOT_ANALYZED: File is not analyzed: /Users/.../my_projects/tf-inspection/lib/initial_navigation_screen.dart.
2023-03-05 00:02:46,556 [ 250443]   INFO - #c.j.l.d.a.DartAnalysisServerService - Error from analysis_getHover(), file = /Users/.../my_projects/tf-inspection/lib/initial_navigation_screen.dart, SDK version = 2.19.0, server version = 1.33.4, error code = FILE_NOT_ANALYZED: File is not analyzed: /Users/.../my_projects/tf-inspection/lib/initial_navigation_screen.dart.
```

**Comment by stevemessick** [comment]
The log message is `Invalid file path format: /Users/.../my_projects/tf-inspection/.` so searching for `dart.` wouldn't find it. The dot is immediately after a slash, so searching is tricky.

Sounds like your problem has been resolved, so I'm closing this.
