### ISSUE TITLE
Color swatches not rendering for new switch expressions

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#6661]
```dart
enum Color {
  red, orange, yellow
}

String name(Color color) {
  return switch (color) {
    // Uh-oh.
    Color.red => throw 'red!',
    Color.orange
      // Tangerine?
      => 'orange',
    Color.yellow => 'yellow'
  };
}
```

Produces:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/67586/222572413-f9b25e3a-09df-4e2b-b1ee-f3165d62f5b1.png">

Contrast w/ old switch statements:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/67586/222572668-02fcd991-ec3e-4f9b-b914-624453aec7f8.png">

**Comment by jacob314** [comment]
Copied this issue from https://github.com/dart-lang/sdk/issues/51613

**Comment by alexander-doroshko** [comment]
The feature is implemented in the Flutter plugin, but it depends on the Dart plugin's parser.

I've just published the Dart plugin updates with the patterns syntax support. It should work fine now. Please update the Dart plugin and check. Thank you.

**Comment by stevemessick** [comment]
Thanks @alexander-doroshko !

<img width="373" alt="Screenshot 2023-03-10 at 1 52 28 PM" src="https://user-images.githubusercontent.com/8518285/224435466-7754c8ff-3057-4ff4-8362-b76475674d5e.png">
