### ISSUE TITLE
multiple local dependent package，How to specify the main project？

### ISSUE THREAD

**Issue by yimao009** [flutter/flutter-intellij#6662]
There are multiple local dependent packages in my project, and there is a main app package. How to configure the app in android studio is the main project. Now I can only specify main.dart in app/lib, but I cannot use the debugging tool.

### my project structure
*  proj
     * app
     * package1
     * package2
     * package3

more detail https://github.com/flutter/flutter/issues/121983

**Comment by stevemessick** [comment]
The Flutter plugin provides some support for monorepo projects. See the release notes for details on setting it up.
https://groups.google.com/g/flutter-announce/c/on6eKqmhD3A

**Comment by yimao009** [comment]
Very Nice~ 6666😂
