### ISSUE TITLE
Please remove usages of the `decl` property of VM Service `BoundField`s

### ISSUE THREAD

**Issue by derekxu16** [flutter/flutter-intellij#6666]
That property has been deprecated in v4.0 of the VM Service spec, and the DWDS team says that their `decl` responses aren't fully populated, so we would like to delete that property from the spec.

cc @annagrin

**Comment by stevemessick** [comment]
Congrats on getting 6666 :)

**Comment by stevemessick** [comment]
`BoundField.getDecl()` returns a `FieldRef`, which is used to determine which icon to show for various field types, and for computing source locations for navigate-to-source features. We'll need to find an alternate source for that.

**Comment by jwren** [comment]
@derekxu16 @annagrin Release 76 is happening soon without this change.  Bumping to M77.
