### ISSUE TITLE
Reformat file. Organize imports by scope when package imports are used. 

### ISSUE THREAD

**Issue by ph55** [flutter/flutter-intellij#6668]
### Description

Package imports are used inside internal package called `flutter_core`.
Reformat file given following settings and imports inside package file:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/1386622/224379161-10eaf415-3671-4f79-9fc2-4d2e5c1ed3e7.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/1386622/224383274-28bab397-4669-41d2-8a4a-112af81b9532.png">

### Current Behavior 
When "Optimize Imports" checkbox is checked external package like `http` treated the same way as the current package `flutter_core` and sorted alphabetically only.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1386622/224383052-b9f02d3e-67c8-45c1-8138-df67158d98f6.png">

### Expected Behavior 
When "Optimize Imports" checkbox is checked it should first organize by scope:
1. Dart core libraries.
2. Non-project external packages. 
3. Project files including package imports.

And only then organize each of the blocks alphabetically:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1386622/224382997-8b1ce7d9-b11f-4cb2-a55a-87002e050962.png">

**Comment by stevemessick** [comment]
I think this is working as intended. However, this behavior is controlled by the Dart analysis server. If you think it should be changed, please open an issue with the [Dart SDK](https://github.com/dart-lang/sdk/issues). (Sorry, I used to be able to move issues but no longer can.)
