### ISSUE TITLE
Out of date pubspec inspection lags behind local filesystem changes.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#667]
To repro, click `get` or `update`:

<img width="979" alt="screen shot 2017-01-27 at 5 35 25 am" src="https://cloud.githubusercontent.com/assets/67586/22372597/720a4970-e452-11e6-8e89-9f258001f225.png">

And watch the inspection *not* go away...

The issue appears to be this check:

`pubspec.getTimeStamp() > packages.getTimeStamp()`

which takes a long time to catch up with the time stamps on the local file system.

Oddly, I *thought* I was addressing this exact issue with this code:

      sdk.run(COMMAND, pair.first, workingDir, new ProcessAdapter() {
        @Override
        public void processTerminated(ProcessEvent event) {
          // Refresh to ensure Dart Plugin sees .packages and doesn't mistakenly nag to run pub.
          LocalFileSystem.getInstance().refreshAndFindFileByPath(workingDir.getPath() + "/" + FlutterConstants.PACKAGES_FILE);
        }
      });

(in `io.flutter.actions.FlutterPackagesGetAction#perform`).

@alexander-doroshko : any thoughts?  Is there a better way to refresh the `.packages` file?  I don't think doing it in the inspection is correct (since it's a read action).

**Comment by alexander-doroshko** [comment]
Inspection doesn't rerun when IDE understands that .packages file has been updated. Need to fix.

**Comment by pq** [comment]
So this is a platform bug?  Thanks for clarifying that.

@alexander-doroshko : if you find a tracking bug, maybe link here?

**Comment by pq** [comment]
In the meantime, since this is pretty frustrating for new users especially, is there any way to dismiss or force an inspection to re-run?

**Comment by alexander-doroshko** [comment]
Need to think about a fix at Dart plugin level. BTW it looks flaky. Sometimes I can't reproduce the problem.

**Comment by pq** [comment]
FWIW this problem changes a bit if we transition to using an editor notification instead (#670).

@alexander-doroshko : is the flakiness that the timestamps are lagging or that the inspection doesn't get re-run?

**Comment by alexander-doroshko** [comment]
Inspection. But it could be fixable at plugin end, not in platform.

**Comment by pq** [comment]
While the underlying problem doesn't appear to have gone away, https://github.com/flutter/flutter-intellij/commit/75ee5755fd1d5c10764f02200d51e1f18f335aba effectively works around it.  Optimistically closing.

**Comment by Lootwig** [comment]
@pq I'm currently experiencing this with a plain dart project (no flutter) in IntelliJ 2019.3.1. Manually opening the ".packages" file resolves the issue. Can your fix be applied to vanilla dart projects too?

**Comment by pq** [comment]
Hi @Lootwig.

I'll defer to @alexander-doroshko on whether this should make it's way into the Dart plugin or if there's a better approach.

Sorry for the trouble!

**Comment by alexander-doroshko** [comment]
I'm afraid I can't reproduce it.

**Comment by Lootwig** [comment]
Can I provide you with any information from my system apart from the doctor output to help?

```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.17763.914], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code, 64-bit edition (version 1.40.1)
[√] Connected device (1 available)
```

**Comment by alexander-doroshko** [comment]
IntelliJ Logs (Help - > Compress Logs...)
