### ISSUE TITLE
Relative Dart entrypoint

### ISSUE THREAD

**Issue by HELL-i** [flutter/flutter-intellij#6678]
## Steps to Reproduce
1. Edit Configuration
2. Want to use $PROJECT_DIR instead of the absolute path in Dart entrypoint

![Screenshot 2023-03-14 at 11 54 34](https://user-images.githubusercontent.com/122999920/224980267-12189ac4-f593-41a8-b77c-d79469a07020.png)

## Version info
Flutter Plugin: 72.1.4
IntelliJ IDEA 2022.3.2(Ultimate Edition)

**Comment by stevemessick** [comment]
Dup of #4561
