### ISSUE TITLE
Assists & quick fixes not working in android studio flutter

### ISSUE THREAD

**Issue by sasikanta222** [flutter/flutter-intellij#6700]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Assists & quick fixes not working in android studio flutter

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
I can't reproduce the problem. It sounds like you have a configuration issue; it can be tricky to get everything set up correctly. Check that the Flutter SDK is installed correctly and your path is configured to find the executables. You may need to reboot your computer to get that working in the IDE (on Linux and Mac the IDE uses the shell settings from the login, which may be different from a terminal emulator).

Can you run the menu item `Tools > Flutter > Flutter Doctor`? If so, please append the output here. If not, your path is not set correctly.

If you still need help then please include detailed steps to reproduce the problem.
