### ISSUE TITLE
Android studio overheating m1 macbooks

### ISSUE THREAD

**Issue by Karim-Monir** [flutter/flutter-intellij#6734]
Hello! there..

I'm using the latest version of android studio (Flamengo) on an m1 macbook air (macOS Ventura 13.3.1 )for mobile application development using the flutter framework and Kotlin as well. The device overheats substantially while using the android studio for absolutely no reason and it seems like there is a memory leakage in android studio as it substantially utilizes the double of normal CPU and RAM.
I checked with every single friend who uses android studio for application development and they all confirmed having the same problem. The heat drops down to normal after closing android studio and restarting the device or stopping every single background process of the android studio.

so, what's wrong? and what should we do now as we can't use android studio without the device reaching 90+ degrees celsius!
hope to hear from you soon enough.

thanks in advance..

**Comment by stevemessick** [comment]
It's hard to say what's going on without some actual data. You should be able to get more info from the Activity Monitor. Launch it and switch to the "Energy" tab. Sort by "Energy Impact". Expand the Android Studio group. Add a screen shot here. The switch to the "CPU" tab. Sort by "% CPU". Add another screen shot here. Finally, repeat that process for he "Memory" tab, sorting by "Memory". Before posting screen shots, please ensure they contain no confidential info.

**Comment by stevemessick** [comment]
Some of my colleagues have suggested other things to check.

- How much memory do you have? Apparently, 8GB is borderline unusable with Android Studio.
- Is there any chance you are using Rosetta? Make sure your emulator is arm64 not x64, and make sure your JDK is arm64. Rosetta is great but it'll definitely use more CPU, especially on heavy things like that.

**Comment by Karim-Monir** [comment]
> Some of my colleagues have suggested other things to check.
> 
>     * How much memory do you have? Apparently, 8GB is borderline unusable with Android Studio.
> 
>     * Is there any chance you are using Rosetta? Make sure your emulator is arm64 not x64, and make sure your JDK is arm64. Rosetta is great but it'll definitely use more CPU, especially on heavy things like that.

I have a 16 gb RAM m1 macbook and I'm not using Rosetta, My emulator and JDK are already arm64 and everything is okay, the issue is with Android Studio Flamengo, and not surprisingly when I downgraded it to its previous version, the overheating Stopped and the machine is back to normal.

**Comment by Karim-Monir** [comment]
> Why do you think this is an issue with the Flutter plugin? Without actual data (as requested above) I'll have to close this issue.

it's not an issue with Flutter plugin.. it's an issue with android studio (Flamengo version)

**Comment by stevemessick** [comment]
Thanks. Closing.
