### ISSUE TITLE
Opening flutter.git in IntelliJ doesn't show me all the files

### ISSUE THREAD

**Issue by abarth** [flutter/flutter-intellij#674]
## Steps to Reproduce

1. git clone git@github.com:flutter/flutter.git
2. idea flutter

Notice that not all the files are show in the project explorer.  For example, a bunch of the stuff in the "dev" directory is missing.

Also, a bunch of the top-level directories are smashed together.  For example, hello_world and flutter_test are peers even though one is in the `examples` folder and one is in the `packages` folder.  This is important because the examples directory are just examples but the `packages` directory contains the actual shipping code.

Maybe I shouldn't be using the project explorer and instead should use some sort of file-based view?

**Comment by devoncarew** [comment]
Here's a PR to add `dev/bots` (https://github.com/flutter/flutter/pull/7712). Generally we'll need one intellij module for each dart (or flutter) project.

> Also, a bunch of the top-level directories are smashed together. For example, hello_world and flutter_test are peers even though one is in the examples folder and one is in the packages folder.
> Maybe I shouldn't be using the project explorer and instead should use some sort of file-based view?

I'm not sure there's a view that corresponds to what you want. Another option for editing the repo w/ IntelliJ would be to create separate projects (dev, examples, packages) for the different main directories - each would be open in a separate intellij windows. I'm not sure that's an improvement, as a refactoring in one project wouldn't affect the other projects.

**Comment by abarth** [comment]
I'm willing to believe this is a case of the tool not matching the workflow I'm used to in another tool.  Thanks.

**Comment by alexander-doroshko** [comment]
As I see currently the project is configured in such a way that the root 'flutter' folder doesn't belong to the project at all (it is not a content root of any module). I guess it is done on purpose. That's why you see individual module roots in the Project View.

**Comment by alexander-doroshko** [comment]
If you want root flutter folder to be shown in the Project View and all files to be indexed and browsable it's ok to add one more module with a content root pointing to the root folder. Nested content roots are ok.

**Comment by alexander-doroshko** [comment]
Also, I'm not sure about intelilj-flutter plugin, but Dart plugin doesn't care much about Dart project location relative to the content root. So in case of folder structure like
![image](https://cloud.githubusercontent.com/assets/4499789/22396755/6bbd5578-e572-11e6-836c-370556dbf75e.png)
you have a lot of ways how to configure the project:
- single-module project with a single content root pointing to someFolder
- single-module project with 3 content roots pointing to `dart_project1`, `dart_project2` and `dart_project_3`
- single-module project with 2 content roots pointing to `dart_project1` and `subfolder`
- project with 2 modules, one with a single content root pointing to `dart_project1` and another with 2 content roots pointing to `dart_project2` and `dart_project_3`
- project with 2 modules, one with a single content root pointing to `dart_project1` and another with a 
single content root pointing to `subfolder`
- project with 3 modules, each with a single content root pointing to the corresponding `dart_project_x`
- project with 4 modules, 3 of them are like in the previous example and the 4th is a fake module with a single content root pointing to the `someFolder`, just to have a better file structure view in the Project tool window.

There are many more other variants, I think you got the idea. Dart plugin functionality doesn't care which one you take. 
Not sure about Flutter plugin, you could implicitly assume that flutter project root has to be equal to the module content root. And I do not know if flutter plugin works well with multiple content roots per module.
