### ISSUE TITLE
Kotlin dist downloading failed

### ISSUE THREAD

**Issue by danielesk** [flutter/flutter-intellij#6743]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Problems after upgrading androidstudio

#### **Current androidstudio version information**
Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 20, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins:
    krasa.CpuUsageIndicator (1.15)
    ee.carlrobert.chatgpt (1.10.7)
    com.tabnine.TabNine (1.0.9)
    com.intellij.marketplace (222.4459.28)
    com.github.copilot (1.2.5.2507)
    Key Promoter X (2022.3.1)
    org.sonarlint.idea (8.2.0.68615)
    mobi.hsz.idea.gitignore (4.4.2)
    Dart (222.4560)
    zielu.gittoolbox (500.0.6+213)
    com.developerphil.adbidea (1.6.9)
    io.flutter (73.0.2)
    shop.itbug.FlutterCheckVersionX (3.3.1.as)
    com.crzsc.FlutterAssetsGenerator (2.4.2)
    cn.yiiguxing.plugin.translate (3.4.2)

#### **error info**
Failed to download Kotlin Compiler Maven artifact (org.jetbrains.kotlin:kotlin-dist-for-jps-meta:1.8.0-release). The search was performed in the following repos: https://repo1.maven.org/maven2 https://repository.jboss.org/nexus/content/repositories/public/ You can use Kotlin compiler which is bundled into your IDE. Select 'Bundled' version in 'File | Settings | Build, Execution, Deployment | Compiler | Kotlin Compiler | Kotlin Compiler version'

## Version info

D:\flutter\bin\flutter.bat doctor --verbose
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.7.11, on Microsoft Windows [ 10.0.22621.1635], locale zh-CN)
    • Flutter version 3.7.11 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (3 weeks ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\AndroidStudio\SDK
    • Platform android-UpsideDownCake, build-tools 33.0.2
    • Java binary at: D:\Java\jdk-11\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at D:\AndroidStudio\studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.1635]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.64
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.48

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
Process finished with exit code 0

**Comment by Sun3** [comment]
Did you open a ticket on the Flutter git?

**Comment by maurovanetti** [comment]
I filed this on the main Flutter repo: [Kotlin dist downloading failed](https://github.com/flutter/flutter/issues/126248)

It's the same bug.

**Comment by stevemessick** [comment]
The solution to this problem is described in https://github.com/flutter/flutter/issues/126248. Closing this, since it is not a plugin issue.

**Comment by Sun3** [comment]
@maurovanetti That solution works great.
