### ISSUE TITLE
Flutter Inspector: Layout Explorer doesn't fit the screen. Can't see width/height.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#6759]
I would like to obtain the dimensions (width and height) of certain widgets. Previously, this task was easily accomplished using the old Flutter Inspector. However, with the new version, the Layout Explorer has a bug: the whole layout is not entirely visible on the screen, and there is no scrollbar. Even if I resize the screen, the layout just gets bigger and continues out of the screen.

I have attached an image: 

![LayoutInspector](https://github.com/flutter/flutter-intellij/assets/13332110/b96a76d7-be25-47e0-8c17-d7c40671a623)

Secondly, there was a Setting in a previous plugin version that allowed me to switch back to the old Flutter Inspector. I found the older tool better, mainly because it was free from bugs, and was faster to turn on. Could you kindly guide me if there is still an option in the settings to revert to this version?

Lastly, I'd like to propose the addition of a dedicated tab, preferably positioned between the Layout Explorer and the Widget Details Tree, named 'Dimensions.' It would just display the width and height, providing a simpler view for those who may not require the complex layout details. This was present in the old Flutter Inspector.

Thank you.

**Comment by stevemessick** [comment]
@marcglasberg Could you attach your `flutter doctor -v` output? If your Flutter plugin version is 73.1 then you must be using an IDE built on IntelliJ 2023.1. You can use an earlier one, say 2022.3 to get the old inspector, but it is going away with the next general release (June 1). Also, are you using the new or old UI?

@helin24 Is there possibly a scaling issue in that screen shot? Seems odd there are no scroll bars.

@kenzieschmoll Marc has an enhancement request for you.

**Comment by marcglasberg** [comment]
```
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19044.2965], locale pt-BR)
    • Flutter version 3.7.12 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (4 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Marcelo\AppData\Local\Android\sdk                 
    • Platform android-33-ext5, build-tools 33.0.2                              
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java     
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe     

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.2)   
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community  
    • Visual Studio Community 2022 version 17.5.33502.453
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 4.1)
    • Android Studio at C:\Users\Marcelo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119
    • Flutter plugin version 57.0.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.2965]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 113.0.5672.126
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 113.0.1774.35

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by marcglasberg** [comment]
@stevemessick 
> Also, are you using the new or old UI?

Sorry, I don't know what you mean by that, UI of what. How do I select this?

**Comment by stevemessick** [comment]
@marcglasberg Thanks for the update!

In IJ, open Settings and expand Appearance and Behavior. You should see New UI there. It's opt-in, so you're using the old UI.

**Comment by helin24** [comment]
@marcglasberg we've seen this in the past when using Windows display scaling larger than 100% - do you know if you have a different scaling setting?

We should be able to adjust sizing regardless of scale, but another potential concern is using a JRE that isn't officially supported by IntelliJ (see https://github.com/flutter/flutter-intellij/issues/5164#issuecomment-765659073 for more context).

**Comment by marcglasberg** [comment]
@helin24 Yes, it's a 4k monitor, so 100% is way too small. It's using 200% scaling.

**Comment by stevemessick** [comment]
@marcglasberg Do you know which JDK is driving IntelliJ? If it is the one bundled with the IDE it should be OK. But if it is OpenJDK then that could be causing problems. I see you have at least two OpenJDK's installed -- but neither of them could be running IntelliJ since it needs JDK 17.

**Comment by stevemessick** [comment]
Thanks! @helin24 the JDK seems to not be a problem.

**Comment by helin24** [comment]
Thanks for the additional detail! I'm going to work on adding a JCEF option for the browser, but I'm not sure if I'll make it into this next release.

**Comment by AlexV525** [comment]
I just tested with #6787 and the issues seem to be resolved. The screenshot was taken with the scale set to 200% of the display on Windows 11.
![image](https://github.com/flutter/flutter-intellij/assets/15884415/4cc18829-5925-4e2f-b7c1-72ac832163de)

**Comment by marcglasberg** [comment]
@AlexV525 But this screenshot is not showing the correct screen. The problem is in the Layout Explorer, not the Widget Details Tree.

**Comment by stevemessick** [comment]
@marcglasberg We have a new release scheduled for Aug 1. Once you have it, could you check to see if this problem has been fixed?

**Comment by marcglasberg** [comment]
@stevemessick Sure!

**Comment by marcglasberg** [comment]
@stevemessick @helin24 @AlexV525 

Sorry for the delayed response, but unfortunately the problem still exists. It's exactly the same, when there is more than 100% zoom in Windows.

Could you please reopen this issue? It's a very serious one, and I can't use the inspector.

Just tested:

```
IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4074M
Cores: 16
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  Dart (233.13763.5)
  com.github.copilot (1.4.18.4775)
  org.jetbrains.android (233.14475.28)
  io.flutter (78.1.1)
Kotlin: 233.14475.28-IJ
```

**Comment by marcglasberg** [comment]
Pinging this, to avoid it being closed by the bot.

**Comment by kenzieschmoll** [comment]
Can you use the Inspector in the browser as a workaround?
![Screenshot 2024-05-15 at 9 14 43 AM](https://github.com/flutter/flutter-intellij/assets/43759233/2b30c69a-f68d-47df-aa54-ec89026c6aab)

We have planned work to make the Layout Explorer more dense to provide a better IDE-embedded experience: https://github.com/flutter/devtools/issues/7758.

@helin24 is there any work on the IntelliJ side for this issue? Or is it all in DevTools?

**Comment by helin24** [comment]
It sounds like on the IJ side there is an issue with zoom on Windows; this doesn't sound like entirely a DevTools issue. 

@marcglasberg since you are using IntelliJ, are you able to use the JCEF browser? I wonder if that will have the same issue. Go to Settings > Languages & Frameworks: Flutter > Experiments: Use JCEF browser.

**Comment by marcglasberg** [comment]
@kenzieschmoll @helin24 

Using the JCEF browser solved it for me. Does it have any limitations in comparison with the JxBrowser.

**Comment by helin24** [comment]
> Using the JCEF browser solved it for me. Does it have any limitations in comparison with the JxBrowser.

We tried making it the default for the plugin, but Android Studio does not use a JDK with JCEF by default, so it fails on Android Studio. It sounds like it should be okay for you on IntelliJ though, so I'll close for now.
