### ISSUE TITLE
Dart Analysis errors are too subtle

### ISSUE THREAD

**Issue by abarth** [flutter/flutter-intellij#676]
## Steps to Reproduce

Open a Flutter project and introduce some analysis errors.  Now close the file you're editing (and collapse the project explorer if you have it open).  Now there are zero indications in the UI that you have any analysis errors.

In order to be notified that analysis errors exist, I need to either open the project explorer (and notice the subtle squiggly lines) or open the Dart Analysis panel.

## Possible solution

Badge the collapsed Dart Analysis panel with the number (or even existence) of analysis errors.  (This is what we do in Atom, and it's quite effective.)

## Version info

```
[✓] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.9166.22
    • Flutter plugin version 0.1.8.1
```

**Comment by pq** [comment]
@alexander-doroshko @jwren

**Comment by devoncarew** [comment]
@alexander-doroshko, what are some possible ways we could expose through the UI (as a status line item for instance)?

**Comment by alexander-doroshko** [comment]
If Project View is in 'Project' mode you should see red squiggles
![image](https://cloud.githubusercontent.com/assets/4499789/22396099/ffb5516a-e561-11e6-8416-697f4c285060.png)

May be it is possible to update Dart Analysis tool window icon, need to investigate.

As for the status line - I do not see a good place for it.

**Comment by abarth** [comment]
Yes, I see the red squiggles.  There are two issues with that:

1. In a dark theme (which I use), they're hard to see.
2. I don't always have the project view open.

Empirically, I often send pull requests that contain analyzer errors when I used IntelliJ.  That doesn't happen when I use Atom.  I attribute the difference to the analyzer errors being more prominent in Atom because the button that brings up the analyzer panel has a red badge with the number of errors.  Obviously, we don't need to use exactly the same UI in IntelliJ, but the UI we've got now is too subtle.

**Comment by pq** [comment]
@abarth : do you have the **Dart Analysis** view active?

<img width="450" alt="screen shot 2017-01-29 at 5 20 43 pm" src="https://cloud.githubusercontent.com/assets/67586/22410003/5bbcec9e-e647-11e6-85c5-a2aceb3867d4.png">

(I'm guessing not.)

That gives you a kind of familiar problems view:

<img width="1009" alt="screen shot 2017-01-29 at 5 22 49 pm" src="https://cloud.githubusercontent.com/assets/67586/22410029/a02ab636-e647-11e6-9872-c6a07d9b0e81.png">

@alexander-doroshko : can we auto-activate this view?  Are there already conditions where we do?

**Comment by abarth** [comment]
@pq I have it collapsed.  I know that I can open it and see the errors, but it takes up too much space to keep open all the time.

**Comment by pq** [comment]
Thanks @abarth 👍 

@devoncarew : maybe we should consider a message bus notification?  Does atom do something like that?

**Comment by alexander-doroshko** [comment]
> can we auto-activate this view?

It is auto-activated on first project open/creation. Next time IDE remembers tool window states and restores as user left them.

BTW Tool buttons are hidden by default. So even if changing an icon on the fly is possible it will have an effect only if a user enables View -> Tool buttons or clicks the button in the bottom-left of the IDE frame.

**Comment by alexander-doroshko** [comment]
>  I often send pull requests that contain analyzer errors when I used IntelliJ

@abarth I can share my experience how I avoid this problem. I mostly write Java code and for Java we do not have Global Problems View at all. So I:
- when editing a file I watch color stripes at the right side of the editor and also at the editor status (color square in the editor's top-right). To move between problems in a file use F2 / Shift+F2.
- before committing code I review it once again using IntelliJ's Diff view. Cmd+D in the Local Changes tool window or right in the Commit dialog. Editor status in Diff view helps.

**Comment by abarth** [comment]
@alexander-doroshko It's often the case that a change in one file will trigger an analysis error in a different file.  Without the project explorer or analysis pane open, these errors are completely invisible.

**Comment by mit-mit** [comment]
I have personally struggled with this also, and have heard of many others. The core problem is that the IDE "main chrome" has no accordance for seeing warnings when the project view and analysis pane are closed.

I think we should consider adding a status button up next to run/debug. Something like this:
![pane](https://cloud.githubusercontent.com/assets/13644170/22423629/d03a1f00-e6f2-11e6-9164-57ccdf66bc6a.png)


Clicking the 'indicator' would open the Dart Analysis pane leading the developer to more details.

@abarth would that work for your use case?

**Comment by pq** [comment]
@mit-mit I wonder if that isn't still too subtle?  @abarth: what do you think?

FWIW I'd love to experiment with a notification (either in the editor or on the bottom right).  But in particular, when the list of problems changes in an interesting way (loosely I mean _grows_ but we'd have to hash out what that means -- any non-subtractive changes is maybe closer to what I mean).

**Comment by pq** [comment]
In Atom, we contributed our own custom status-line.  Should we consider this?

**Comment by abarth** [comment]
@mit-mit Looks worth a try.

**Comment by alexander-doroshko** [comment]
I checked that it is possible to change the tool window icon as frequently as we want. I'd prefer this solution.

**Comment by devoncarew** [comment]
I filed https://youtrack.jetbrains.com/issue/WEB-25226 to track that solution (updating the tool window icon). I'll keep this issue open as a proxy for the jetbrains one.

**Comment by alexander-doroshko** [comment]
For standard resolution monitors we have only 13x13 pixels for the tool window icon (26x26 for HiDPI). Red dot would look smth like this. Ideas about better presentation are welcome.
![image](https://cloud.githubusercontent.com/assets/4499789/22509152/e0f11306-e89d-11e6-8736-b4e10dbc5c04.png)

**Comment by devoncarew** [comment]
It does seem a bit subtle, but we'd probably need to live with it a bit to see. Perhaps changing the text as well would help?

`Dart Analysis (3)`, or `Dart Issues (3)`

I don't know if that would look alien in the IntelliJ UI (updating tool window labels) or not.

I can experiment with an icon if you like, perhaps based on badging the Dart icon with a small version of `AllIcons.General.Error`?

**Comment by alexander-doroshko** [comment]
Both icon and title are not changed on the fly anywhere else in IntelliJ IDEA, but experiments with icon look more innocent to me. Changing title would mean oscillating width, not stable name in Switcher / Go To Recent, etc.

**Comment by devoncarew** [comment]
Cool, that all makes sense.

**Comment by devoncarew** [comment]
@alexander-doroshko, if it helps I create some icons and put them in a PR (https://github.com/JetBrains/intellij-plugins/pull/475).

**Comment by devoncarew** [comment]
Somewhat ironically, I just hit this myself on https://github.com/flutter/flutter/pull/7960.

**Comment by devoncarew** [comment]
Some work for this has landed in the Dart plugin; will continue to evaluate our issue UX.

**Comment by jacob314** [comment]
The analysis window now makes it clear if there are errors and the red squiggles on file names are quite nice. Closing unless there is more work we plan to do here.
