### ISSUE TITLE
Hot reload fails when there are Dart 3 records on currently opened file

### ISSUE THREAD

**Issue by zorazafi** [flutter/flutter-intellij#6760]
Hello,

Since I upgraded to Dart 3, a weird issue happened to Android Studio with Flutter/Dart plugin (Flutter plugin version 72.1.1 / Dart plugin version 213.7433)

## Steps to Reproduce

- Create a widget file. On my project, this extends a StatefulWidget
- Add some code with [Dart records](https://dart.dev/language/records)
`class _ProductsYearlyState extends State<ProductsYearly> {
  final pages = <int, (int, int)>{}; // page, (year begin, year end)

  @override
  void initState() {
    super.initState();

    pages.addAll({
      0: (DateTime.now().year - 5, DateTime.now().year),
    });
  }
}`
- Make sure on Dart Analysis that there is no error
- Run project
- Get back to the code and make some changes (maybe just add a comment somewhere)
- Save. Now hot reload should fail with the message : **Reload not performed. Analysis issues found**. But obviously, there are no issue on Dart Analysis

Bonus : 
- Close the file which is leading to hot reload failure
- Make some changes anywhere in another file
- Save.
- Now, hot reload works.
(There is no such issue on VSCode)

## Version info

[✓] Flutter (Channel stable, 3.10.1, on Ubuntu 23.04 6.2.0-20-generic, locale en_US.UTF-8)
    • Flutter version 3.10.1 on channel stable at .../flutter/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (2 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at .../android
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = .../android
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.7
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 72.1.1
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.04 6.2.0-20-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0

**Comment by alexander-doroshko** [comment]
Hi @zorazafi. Android Studio and Dart plugin from year 2021 definitely don't work great with the "Dart records" syntax, introduced 2 years later. Please update to Android Studio Flamingo, Giraffe, or Hedgehog. It will work fine.

**Comment by zorazafi** [comment]
My bad.
Thanks for your comment.
I just updated Android Studio.
I mark this as resolved
