### ISSUE TITLE
Problem with Android Studio run App on Chrome 

### ISSUE THREAD

**Issue by Rudy1677** [flutter/flutter-intellij#6771]
On Android Studio 3.6.3 (see below all the details) I've create a "Flutter project" with the default code of "Flutter Demo Home Page" and, when I try to Run main.dart with Crome Web device, I receid the error reported below.

This problem happens only when I try to use a "StatefulWidget". I created and run without problems a lot of project with only "StatelessWidget".

Below you could see:
1. Log Error
2. Android Studio version details
3. Flutter SDK and Dart SDK details

1. LOG ERROR
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://[127.0.0.1:50518/ETm5XwGqDGo=/ws](https://www.google.com/url?q=http://127.0.0.1:50518/ETm5XwGqDGo%3D/ws&sa=D&source=buganizer&usg=AOvVaw1ge4gom42YhFSa2XIRUsDl)
Debug service listening on ws://[127.0.0.1:50518/ETm5XwGqDGo=/ws](https://www.google.com/url?q=http://127.0.0.1:50518/ETm5XwGqDGo%3D/ws&sa=D&source=buganizer&usg=AOvVaw1ge4gom42YhFSa2XIRUsDl)
Debug service listening on ws://[127.0.0.1:50518/ETm5XwGqDGo=/ws](https://www.google.com/url?q=http://127.0.0.1:50518/ETm5XwGqDGo%3D/ws&sa=D&source=buganizer&usg=AOvVaw1ge4gom42YhFSa2XIRUsDl)
Incompatible protocol version: client=3.26 vm=4.4
Failed to connect to the VM observatory service at: ws://[127.0.0.1:50518/ETm5XwGqDGo=/ws](https://www.google.com/url?q=http://127.0.0.1:50518/ETm5XwGqDGo%3D/ws&sa=D&source=buganizer&usg=AOvVaw1ge4gom42YhFSa2XIRUsDl)
java.io.IOException: Incompatible protocol version: client=3.26 vm=4.4
Unhandled exception:
PathNotFoundException: Cannot open file, path = 'C:\Users\u399366\AppData\Local\Temp\1\flutter_tools.5d18719\flutter_tool.b2612df9\app.dill.incremental.dill' (OS Error: The system cannot find the path specified.

, errno = 3)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#2      FrontendCompiler.compileExpressionToJs (package:frontend_server/frontend_server.dart:1053:5)
<asynchronous suspension>
#3      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1464:9)
<asynchronous suspension>

2. Android Studio version details
Android Studio 3.6.3
Build #AI-192.7142.36.36.6392135, built on April 14, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: IdeaVIM, PythonCore, com.google.services.firebase, Dart, io.flutter

3. Flutter SDK and Dart SDK details
- Flutter SDK 3.10.2
- Dart SDK 3.0.1

**Comment by stevemessick** [comment]
The problem is in the log output: "Incompatible protocol version: client=3.26 vm=4.4". We updated the VM service protocol from 3 to 4 when Dart 3.0 was released. (That's what the plugin uses to communicate with the Dart VM.) If you want to use Flutter 3.10+ (which includes all the new language features in Dart 3.0) you will need a newer IDE. Yours is several years out-of-date. Install Android Studio 2022.2 or newer with the latest Flutter and Dart plugins. (If that is too big then try IntelliJ 2023.1.) If you cannot update the IDE then you will have to downgrade your Flutter SDK to 3.7.9, or possibly earlier.
