### ISSUE TITLE
Corrupted Dart packages and or Cache not detected by any analysis procedure

### ISSUE THREAD

**Issue by Hivepop** [flutter/flutter-intellij#6776]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

NOTE:  I have spent days trying to debug why none of my projects would run!  IDE's, Flutter Doctor and DART utilities did not recognise an issue with the DART Pub cache or its internal packages!

WORKAROUND: Deleted the Flutter folder, re-installed via Brew; deleted the DART folder at usr/...bin and it's cache at ~/<here> in MacOS.  I did this an all of my projects work again.  What happened?  This is a clean system, new Hard Drive, things were working and then broke and no analysis caught the fact that internal packages of either Flutter or DART were corrupted. 

1. Corrupt DART internal packages or its cache.
2. Try and build an iOS or Android project

RESULT:

iOS: there should be strange errors about internal packages not functioning or crashing at line numbers etc.
Errors like:
CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
----------------------------

OR:
Failed to build iOS app
Error (Xcode): ../../../../../flutter/packages/flutter/lib/src/widgets/context_menu_button_item.dart:49:9: Error: Type 'VoidCallback' not found.

Could not build the application for the simulator.
-----------------------------------
many other cocopod errors and issues as well as missing scripts, very strange.

ANDROID: a huge list of reference errors such as these:

Running Gradle task 'assembleDebug'...
../../flutter/packages/flutter/lib/src/services/text_input.dart:713:1: Error: Type 'TextAffinity' not found.
TextAffinity? _toTextAffinity(String? affinity) {
^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_input.dart:1038:22: Error: Type 'TextPosition' not found.
  void bringIntoView(TextPosition position);
                     ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_input.dart:716:14: Error: Undefined name 'TextAffinity'.
      return TextAffinity.downstream;
             ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_input.dart:718:14: Error: Undefined name 'TextAffinity'.
      return TextAffinity.upstream;
             ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_input.dart:781:77: Error: Undefined name 'TextAffinity'.
      affinity: _toTextAffinity(encoded['selectionAffinity'] as String?) ?? TextAffinity.downstream,
                                                                            ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_input.dart:1038:22: Error: 'TextPosition' isn't a type.
  void bringIntoView(TextPosition position);
                     ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/painting/placeholder_span.dart:54:9: Error: Type 'TextBaseline' not found.
  final TextBaseline? baseline;
        ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/painting/placeholder_span.dart:54:9: Error: 'TextBaseline' isn't a type.
  final TextBaseline? baseline;
        ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/painting/placeholder_span.dart:89:33: Error: 'TextBaseline' isn't a type.
    properties.add(EnumProperty<TextBaseline>('baseline', baseline, defaultValue: null));
                                ^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/painting/star_border.dart:377:3: Error: Type 'Path' not found.
  Path getInnerPath(Rect rect, {TextDirection? textDirection}) {
  ^^^^
../../flutter/packages/flutter/lib/src/painting/star_border.dart:377:21: Error: Type 'Rect' not found.
  Path getInnerPath(Rect rect, {TextDirection? textDirection}) {
                    ^^^^
../../flutter/packages/flutter/lib/src/painting/star_border.dart:377:33: Error: Type 'TextDirection' not found.
  Path getInnerPath(Rect rect, {TextDirection? textDirection}) {
                                ^^^^^^^^^^^^^

_Please tell us what you were doing and what went wrong_

## Version info
[✓] Flutter (Channel stable, 3.10.2, on macOS 11.7.7 20G1345 darwin-x64, locale en-GB)
    • Flutter version 3.10.2 on channel stable at /usr/local/Caskroom/flutter/3.10.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (7 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/marlonmehr/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/marlonmehr/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /Users/marlonmehr/The Werck Group Dropbox/!Magento Studio/222.3345.118/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • VOG L29 (mobile)       • 22X7N19327004306                     • android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro (mobile) • 32C21B77-D6F7-4CCF-9D12-F2F175C7A5DF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.7.7 20G1345 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
This is an issue in the Dart SDK; the Flutter plugin cannot be changed in a way that would fix it. Please report it here:
https://github.com/dart-lang/sdk/issues
