### ISSUE TITLE
Some color previews flashes on Android Studio 2022.2+

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#6777]
Screen shot with version 73 of the Flutter plugin.
<img width="679" alt="Screenshot 2023-05-31 at 10 57 51 AM" src="https://github.com/flutter/flutter-intellij/assets/8518285/837fe209-5e36-4dd5-a9f5-4b9c900835c5">

With version 74 the `fromRGBO` and `fromARGB` constructors are not recognized.

Sample code:
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

main1() { Color(0xffd7dce0); }
main2() { const Color(0xFFE3F2FD);}
main3() { const [Color(0xFFE3F2FD )]; }
main4() { const Color( 0xFFE3F2FD); }
main5() { const Color.fromARGB(255, 255, 0, 0); }
main6() { Color.fromARGB(255, 255, 0, 0); }
main7() { const Color.fromRGBO(255, 0, 0, 1.0); }
main8() { Color.fromRGBO(255, 255, 0, 1.0); }

main9() { Colors.blue.shade700; }
maina() { Colors.blue[200]; }
mainb() { CupertinoColors.systemGreen; }
mainc() { foo(Color.fromRGBO(0, 255, 0, 0.5)); }

main1w() { Color ( 0xFFE3F2FD); }
main2w() { const Color ( 0xff00ff00 /* green */) ;}
main5w() { const Color . fromARGB ( 255, 255, 0, 0 ) ; }
main6w() { Color . fromARGB (255, 255, 0, 0 ) ; }
main9w() { Colors . blue . /* darkish */ shade700; }
mainaw() { Colors . blue [ 200 ]; }
mainbw() { CupertinoColors . systemGreen; }
maincw() { foo ( Color . fromRGBO ( 0, 255 /* still green */, 0, 0.5 ) ) ; }

void foo(Color x) {}
```
cc @AlexV525

**Comment by AlexV525** [comment]
I cannot reproduce the issue on IDEA 2023.1.2.

![image](https://github.com/flutter/flutter-intellij/assets/15884415/8d6d348b-92c6-4787-a258-adccab14335d)

**Comment by AlexV525** [comment]
In https://github.com/flutter/flutter-intellij/pull/6779#issuecomment-1571085413, is the issue related to Android Studio only?

**Comment by AlexV525** [comment]
How can I run a debug instance of AS directly from our configurations? I didn't find helpful explanations in our doc.

**Comment by AlexV525** [comment]
I think this is an issue related to the AS itself. @alexander-doroshko Could you help us identify if the problem is related to the AS or the new implementation? See #6782 for implementation details.

**Comment by alexander-doroshko** [comment]
Hard to say anything without deep diving into the problem.
I believe, the corresponding versions of Android Studio and IntelliJ IDEA should work similarly, as both are based on the same IntelliJ Platform version.

IntelliJ IDEA version that matches AS 2022.2.1 is 2022.2.4. So you may try to reproduce/debug it there.

Is it flashing on typing or just without any reason?

**Comment by AlexV525** [comment]
> Is it flashing on typing or just without any reason?

The resolved color will be "hidden" once the opened file tab is switched to another and then switched back. And when I triggered a "save" action to the file by pressing "Ctrl+S", the color display will flashes to show only once.

> IntelliJ IDEA version that matches AS 2022.2.1 is 2022.2.4. So you may try to reproduce/debug it there.

Good to know. How can start a specific version of IDEA instance to debug though? Also cc @stevemessick

**Comment by alexander-doroshko** [comment]
I don't know how Flutter plugin is usually started from sources. Maybe there's a step that specifies which IDE version to use. Note that to debug the IDE itself you'll need to have source code of the specific version of the IDE.

If it's hard to start something from sources, its always possible to connect with a debugger to a running IDE. You only need to make sure that you have the source code configured that matches the running IDE. At least the part, you are you are going to debug.

For example, if you weant to debug IntelliJ Platform that is used by IntelliJ Community 2022.2.4:
- checkout IntelliJ Community sources at branch 222.4459.
- configure Remote JVM Debug run configuration, copy VM options needed for the external process
- run IntelliJ Community 2022.2.4, click Help -> Edit Custom VM Options, paste required line there, restart it
- run Remote Debug in your working IDE. Debugger should attach, you should be able to debug the IDE itself.

Useful link with Android Studio versions: https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html

**Comment by AlexV525** [comment]
> I don't know how Flutter plugin is usually started from sources. Maybe there's a step that specifies which IDE version to use. Note that to debug the IDE itself you'll need to have source code of the specific version of the IDE.

Thanks for these tips. I was able to start the instance but the plugin did not appear in the plugin list.
![image](https://github.com/flutter/flutter-intellij/assets/15884415/ba6b2cec-bef1-4a27-86ed-d52cde1c70bd)

**Comment by stevemessick** [comment]
@AlexV525 Sorry for the late reply; I didn't see your questions before.

To debug the plugin, I open the project in IntelliJ 2023.1.2, as a Gradle project. Once Gradle sync has finished I then go to the Project Structure and make sure all modules use the inherited compiler output path. Then I click the debug button and it starts up. I spent quite some time in the debugger last week trying to find the root of this problem, so it is not specific to Android Studio.

My comment about Android Studio 2022.1 *not* having the problem should not mean I only saw it in Android Studio. I was doing release testing last week, and I do that primarily in Android Studio. That old version doesn't show the problem, so I was thinking this may be something introduced in IntelliJ 2022.2. If you do decide to debug the IntelliJ sources, be sure to use an SDK created as an IntelliJ Platform Plugin SDK. That will get you the sources without having to run IntelliJ from sources. You just won't have source code for the Dart plugin.

I notice that your `gradle.properties` is configured to use Android Studio for debugging.  I find it slightly easier to debug IntelliJ than Android Studio. I only use Android Studio if I'm working on code that only runs in Android Studio -- the `flutter-studio` module.

I don't know why the Flutter plugin didn't appear in your plugins list, but it might be due to not having the compiler output in the expected place. I don't know if that setting is not preserved because of a problem in the plugin's Gradle script, or if there is an issue with the IntelliJ plugin for Gradle. It's tricky to get all the dependencies in a consistent state, so maybe it would be better to use IntelliJ. I just patched in your change and launched the debugger. The problem is still there.

Also, I haven't bothered to report it yet, but there is an exception thrown. Here's the stack trace:
```java
java.lang.StringIndexOutOfBoundsException: begin 21, end 20, length 20
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602)
	at java.base/java.lang.String.substring(String.java:2705)
	at java.base/java.lang.String.substring(String.java:2678)
	at io.flutter.editor.FlutterColorProvider.getColorFrom(FlutterColorProvider.java:97)
	at com.intellij.ui.ColorLineMarkerProvider.lambda$collectSlowLineMarkers$0(ColorLineMarkerProvider.java:47)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.kt:57)
	at com.intellij.ui.ColorLineMarkerProvider.collectSlowLineMarkers(ColorLineMarkerProvider.java:46)
```

**Comment by AlexV525** [comment]
> Also, I haven't bothered to report it yet, but there is an exception thrown. Here's the stack trace:
> 
> ```java
> java.lang.StringIndexOutOfBoundsException: begin 21, end 20, length 20
> 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602)
> 	at java.base/java.lang.String.substring(String.java:2705)
> 	at java.base/java.lang.String.substring(String.java:2678)
> 	at io.flutter.editor.FlutterColorProvider.getColorFrom(FlutterColorProvider.java:97)
> 	at com.intellij.ui.ColorLineMarkerProvider.lambda$collectSlowLineMarkers$0(ColorLineMarkerProvider.java:47)
> 	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
> 	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.kt:57)
> 	at com.intellij.ui.ColorLineMarkerProvider.collectSlowLineMarkers(ColorLineMarkerProvider.java:46)
> ```

Thanks for the report. I've managed to solve it.

**Comment by AlexV525** [comment]
I think I'm making progress. If there are multiple express involved such as `const Color.fromARGB`, the color provider will resolve the color multiple times, which increases the duration cost of the line marker gathering.

**Comment by AlexV525** [comment]
![image](https://github.com/flutter/flutter-intellij/assets/15884415/2d425382-fbc6-4236-a8fc-51ab8b5b4b5b)
