### ISSUE TITLE
missing flutter tools menu

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#678]
I don't see the flutter Tools menu w/ the latest source base. Am running on windows, but will re-verify on mac.

<img width="232" alt="tools_menu" src="https://cloud.githubusercontent.com/assets/1269969/22393012/a8de6c94-e4b4-11e6-816b-c8e108c6df9b.PNG">

@pq

**Comment by devoncarew** [comment]
I can repo on mac as well.

**Comment by pq** [comment]
Do you have a Flutter project open?

**Comment by pq** [comment]
Fix in flight: https://github.com/flutter/flutter-intellij/pull/679
