### ISSUE TITLE
Code completion not work in Android Studio

### ISSUE THREAD

**Issue by CoderBuck** [flutter/flutter-intellij#6785]
when type "ACl", not show "AClass" tips.
<img width="753" alt="image" src="https://github.com/flutter/flutter-intellij/assets/17465838/0d87823d-ebea-4986-bd4c-222406d61a64">

if type "AClass", wait some seconds(slow)，it can show the import tips
<img width="1117" alt="image" src="https://github.com/flutter/flutter-intellij/assets/17465838/d5b70818-c2ab-4b20-948c-4f5f07de70e7">

but in vscode, is ok and fast
<img width="899" alt="image" src="https://github.com/flutter/flutter-intellij/assets/17465838/9cb1705b-9b46-4d5e-b7a8-e63e75de35be">

more info:
This is not a recent issue, it has been an issue for the last six months and would not have happened if Android studio, dart plugin, flutter plugin had been rolled back to an older version.

We have over a million lines of dart code on our project, and I haven't had this problem on any other small project
```
Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 20, 2023

dart plugin: 222.4582
flutter plugin: 73.0.2

flutter 3.3.6
dart 2.18.2
```

**Comment by stevemessick** [comment]
Are you migrating to Dart 3 (that is, null safety)?

I think this problem was fixed in the Dart SDK version 2.19 or 3.0. Android Studio and VS Code use different mechanisms to communicate with the Dart analyzer, so a problem that shows in only one might not indicate a problem in the other IDE.

**Comment by CoderBuck** [comment]
We haven't moved to dart3 yet, it may require a bit more work, I will try it sometime later.

**Comment by stevemessick** [comment]
Thanks for the info. Once you get onto Dart 3 please check again. If the problem occurs again then it would be good to open a new issue here.
