### ISSUE TITLE
Clicking widget in browser-based  flutter  inspector  cause switch to IDEA editor. 

### ISSUE THREAD

**Issue by MangoIceCup** [flutter/flutter-intellij#6801]
### Clicking widget in browser-based  flutter  inspector  cause switch to IDEA editor. 

I think the issue  related to the flutter inspector integrated with IDEA.

Clicking a widget in integrated inspector  , the cursor in editor area will focus related widget. 

## Steps to Reproduce

- creating an flutter android only project
- create some custom widget 
- create an app with custom widget and build-in widget
- debug or run it.
- open browser-based flutter inspector
- single click some widget . (click fist , click second, click 3rd. .........)

_Please tell us what you were doing and what went wrong_
Clicking widget in browser-based  flutter  inspector  cause switch to IDEA editor. 

## Version info
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to xxx xxxx
You have a perpetual fallback license for this version.
Subscription is active until March 9, 2025.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.2.8.2631)
    Dart (231.9065)
    io.flutter (74.0.4)
    com.baomidou.plugin.idea.mybatisx (1.5.5)

Kotlin: 231-1.8.21-IJ9011.34

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

C:\programs\flutter\bin\flutter.bat doctor --verbose
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.22621.1848], locale zh-CN)
    • Flutter version 3.10.4 on channel stable at C:\programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (10 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\fards\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\fards\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\fards\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Users\fards\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Users\fards\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\231.9011.34
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\fards\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 114.0.1823.43

[√] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0

**Comment by stevemessick** [comment]
In this screen shot, I clicked the "Scaffold" item in the widget tree (which is highlighted) and text editor selected the corresponding "Scaffold" item in the code. Is this your issue?
<img width="942" alt="Screenshot 2023-06-16 at 8 47 44 AM" src="https://github.com/flutter/flutter-intellij/assets/8518285/618c70a0-1bd7-4c07-916e-1f74232ca787">
If so, then this is working as intended.

**Comment by MangoIceCup** [comment]
In browser inspector
![image](https://github.com/flutter/flutter-intellij/assets/12372172/79c7d428-74f3-428a-b923-e0be06d569ed)

If you clicking some widget  (like. click the 1st widget , 2nd widget, 3 .... .... ...)  , the IDEA window will be open. 😁


Thank you.

**Comment by stevemessick** [comment]
I see. Clicking a widget in the browser-based inspector causes the IntelliJ window to react.

I'm pretty sure this is working as intended, as it takes some effort to make this connection. @helin24 is there an option in DevTools to disable this feature? Or maybe @kenzieschmoll would know?

**Comment by helin24** [comment]
I'm unclear on whether the issue is that the IntelliJ editor window is navigating to the associated code, or that IntelliJ pops up as the focused application.

The former is intended behavior, but I suppose we could add an option to disable if this is a common use case. @MangoIceCup can you describe why this doesn't fit your purposes (if this is the issue)?

I haven't been able to reproduce IntelliJ becoming the focused application, but is this what's happening for @MangoIceCup then it's a bug. I don't know if it would be something we could change in the plugin or if it would instead be a computer setting.

**Comment by MangoIceCup** [comment]
Uh, The problem is that the IntelliJ window pops up as the focused application when i checking detail of some widget  in flutter inspector in chrome browser.

The problem produced in specific order of clicking some widgets. 
1. Run app
2. In Run panel click open Flutter DevTools
3. In Chrome clicking Column widget
4. click Center widget.
5. And you will find that Intellij window will be focus and bring in front.


 

There are a project file to reproduce problem.
And a video to show the problem.

[flutter_project_1.zip](https://github.com/flutter/flutter-intellij/files/11810852/flutter_project_1.zip)

https://github.com/flutter/flutter-intellij/assets/12372172/4833fcb3-d248-4579-adf7-be5692d2baba


Thanks for your response.

**Comment by kenzieschmoll** [comment]
> is there an option in DevTools to disable this feature? Or maybe @kenzieschmoll would know?

There is not currently an option to disable this feature. It sounds like IntelliJ is grabbing focus when the inspect event is received from the flutter framework. This makes sense for the embedded use case, but perhaps not when DevTools is opened in a separate browser window.

**Comment by helin24** [comment]
Thanks for clarifying @MangoIceCup. I'm able to reproduce this in Windows - after clicking an element the first time, the IntelliJ icon in the taskbar starts to blink; after clicking another element, focus goes to IntelliJ.

Would using the registry setting described here prevent this? https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008273200-IDEA-randomly-steals-focus-while-still-in-background (`suppress.focus.stealing.disable.auto.request.focus`)

**Comment by MangoIceCup** [comment]
The registry setting `suppress.focus.stealing.disable.auto.request.focus` not work.
After setting the registry setting, and restart Intellij , the Intellij window still popup when clicking widgets in Flutter Dev Tools running in chrome browser  in same order as described above.

**Comment by helin24** [comment]
@MangoIceCup  thanks for trying it out and sorry it didn't work for you! I can't reproduce the problem with the registry setting checked, so we may have something else different on our respective systems.

I wonder, how come you're using a separate instance of DevTools? Are you not able to use the embedded instance? I'm hoping we can find an alternative setup that works conveniently for you.

**Comment by MangoIceCup** [comment]
As Intelij IDEA windows size is too,small . And too slow in response to action.
If you can't reproduce, you may need try again maybe several times.

**Comment by MangoIceCup** [comment]
This is my registry setting.
![image](https://github.com/flutter/flutter-intellij/assets/12372172/8acb566a-2bb2-4f9a-8cc8-31a5d7f4bef6)


This is problem video

https://github.com/flutter/flutter-intellij/assets/12372172/e4467079-6308-4492-af99-2e052ea80764


As Intelij IDEA windows size is too,small . And too slow in response to action.

Thank you for you response.

**Comment by helin24** [comment]
This won't address the issue of slower response, but I noticed there is an option to use the embedded browser in a separate window:
<img width="508" alt="Screenshot 2023-07-24 at 3 38 06 PM" src="https://github.com/flutter/flutter-intellij/assets/6379305/80a7c844-1e07-4db7-a805-d072cf30c117">

I wonder if you could also try checking the option in Flutter settings to use the JCEF browser? This is a different browser, I'm not sure if the response rate will differ.

**Comment by MangoIceCup** [comment]
**I think it's time to clear this issue that  when you inspect widgets in separate window,  you will lose focus on inspector window and IDEA window pops up. This will annoy you, as you want to check  widget's properties but a window pops up.**


I using windows sandbox to install  a latest version IDEA ultimate edition with latest dart and flutter plugin. this problem still exist.

So if you can't reproduced this problem, i  suggest you using virtual os, like windows sandbox, virtual box, vmware player.

And I think this issue not related to JCEF. As JCEF is available and enabled by default since 2020.2. And i have no change anything about JCEF. 

Although using separate window, the issue still annoy you,  as you don't expect losing focus on inspector window and idea pops up while you inspect widget detail.

Maybe you should flag session to distinguish external browser , embed inspector or embed inspector in separate window.

Or maybe add a toggle to manually  switch.

The windows version in sandbox.
> Edition	Windows 11 Enterprise
> Version	22H2
> OS build	22621.1992

**Comment by MangoIceCup** [comment]
And setting `suppress.focus.stealing.disable.auto.request.focus` still not work in sandbox

**Comment by MangoIceCup** [comment]
The problem is disappear when upgrade to IntelliJ IDEA 2023.2 (Ultimate Edition)

Even without check `suppress.focus.stealing.disable.auto.request.focus` option.

Thank you,
