### ISSUE TITLE
the intelij did an update

### ISSUE THREAD

**Issue by Mhadar79** [flutter/flutter-intellij#6802]
IntelliJ IDEA 2022.3.2 • Flutter plugin io.flutter 72.0.4 • Dart plugin 223.8617.8

[IDE.txt](https://github.com/flutter/flutter-intellij/files/11784875/IDE.txt)

**Comment by stevemessick** [comment]
This looks like an internal problem in IntelliJ. The cached tests appear to be corrupt (I think, not sure). Try the menu `File > Invalidate Caches...' and let us know if that helps.
