### ISSUE TITLE
Flutter Inspector does not show in View>Tools Windows

### ISSUE THREAD

**Issue by ifsygn** [flutter/flutter-intellij#6804]
I newly start to learn Flutter. In some projects, Flutter Inspector and Flutter Outline do not show. 

### it seems in this
![opened](https://github.com/flutter/flutter-intellij/assets/49685601/d8b93d3b-47de-47fd-ac9d-ac01a169eb2a)

### it does not seem in this
![closed](https://github.com/flutter/flutter-intellij/assets/49685601/db2881c7-4b10-4595-b628-069a0ec9ddac)

### why
I searched on the Internet but can not find an answer. Please help me. Thanks.

## Version info
Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
![image](https://github.com/flutter/flutter-intellij/assets/49685601/44c70cca-1a7e-4247-957b-0e404838f3ec)

**Comment by stevemessick** [comment]
What is the origin of the project in the second screen shot?

**Comment by ifsygn** [comment]
### origin of the project
![image](https://github.com/flutter/flutter-intellij/assets/49685601/2a3ca245-7f98-4c70-ac1a-039b1b06a585)

### Another project with the same issue
![image](https://github.com/flutter/flutter-intellij/assets/49685601/c77618bb-fd7a-49ec-9d8e-af3aed4c878f)

**Comment by ifsygn** [comment]
@stevemessick I look the origin and I checked the plugins so you are right, origin affects this.
And also Project Structure > Module > Flutter Plugins must be checked.

![image](https://github.com/flutter/flutter-intellij/assets/49685601/de751458-0b24-4f04-b3c7-82ffc5a758e1)

My issue is solved. Thanks @stevemessick
