### ISSUE TITLE
Requires plugin 'org.jetbrains.android' to be installed

### ISSUE THREAD

**Issue by bretbas** [flutter/flutter-intellij#6808]
I installed your flutter plugin on rider, but it's not working.
I have an error:
Requires plugin 'org.jetbrains.android' to be installed

What i do wrong?

**Comment by stevemessick** [comment]
The Flutter plugin works with IntelliJ and Android Studio. Rider is not supported.

**Comment by marcvanbreemen** [comment]
> The Flutter plugin works with IntelliJ and Android Studio. Rider is not supported.

Why does this page say that it's compatible with Rider?

https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable

**Comment by eydrent** [comment]
This plugin may be of help: https://plugins.jetbrains.com/plugin/22989-android
It might work.

**Comment by pbruins84** [comment]
> The Flutter plugin works with IntelliJ and Android Studio. Rider is not supported.

IntelliJ gives the same error when installing the Flutter plugin.

**Comment by MeltdownInteractive** [comment]
> This plugin may be of help: https://plugins.jetbrains.com/plugin/22989-android It might work.

That plugin is not compatible with Rider. 
Did anyone else figure out how to get the Flutter plugin working with Rider?
