### ISSUE TITLE
Flutter SDK ComboBox use wrong cached path

### ISSUE THREAD

**Issue by dasRicardo** [flutter/flutter-intellij#6811]
Hello,

There is a problem with fvm and the sdk path. The problem in my opinion is the cacheKey. Projects have a symlink and all projects with the same flutter version have the same canonical path like: fvm/versions/3.10.5. If u set the path for the first project, the key is created and saved the path for this project. But if u go into another project, set the path and the symlink points to the same flutter version, the code produces the same canonical path and will find an entry in the 'projectSdkCache' map and return this entry (first project with the same flutter version).

This function is in FlutterSdk.java line 149 actual master branch.

private static FlutterSdk saveSdkInCache(VirtualFile home) { // this is the problem because all projects with the same version got the same canonical path final String cacheKey = home.getCanonicalPath(); synchronized (projectSdkCache) { if (!projectSdkCache.containsKey(cacheKey)) { projectSdkCache.put(cacheKey, new FlutterSdk(home, FlutterSdkVersion.readFromSdk(home))); } } return projectSdkCache.get(cacheKey); }
Sorry for my english.

## Version info

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale de-DE)
    • Flutter version 3.10.5 on channel stable at /Users/Ricardo.Kelling/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/Ricardo.Kelling/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/Ricardo.Kelling/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • Pixel 6 (mobile) • 21121FDF600DU9 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by stevemessick** [comment]
Dup of #6616
