### ISSUE TITLE
Flutter plugin does not build with recent IntelliJ EAP

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#6814]
IJ 2023.2 build fails due to being configured to use an old Dart plugin.

**Comment by stevemessick** [comment]
After updating the Dart version the build fails with: Cannot find builtin plugin 'com.android.tools.idea.smali'

@alexander-doroshko do you know if that plugin has been removed? Or was the latest EAP unintentionally packaged without it?

**Comment by alexander-doroshko** [comment]
I have found [this issue](https://youtrack.jetbrains.com/issue/IDEA-230089), [this commit](https://github.com/JetBrains/intellij-community/commit/09dfe569aa3164f96f03778e9cdea682bd43dabe), and [this plugin](https://plugins.jetbrains.com/plugin/22067-smali-support/versions). So, looks like it was unbundled intentionally.

**Comment by stevemessick** [comment]
Thanks @alexander-doroshko. Fixed in #6817
