### ISSUE TITLE
Help Regarding Adding Unique identifier in mobile native or flutter native views 

### ISSUE THREAD

**Issue by Rahul1970** [flutter/flutter-intellij#6828]
Hi Team,
               I am working on mobile automation using Java 8, Android Studio, Appium 2.0. Is there any way to add unique identifier like mobile id in flutter native pages so that it can help in writing automation tests scripts. Do let me know if there is anything so that I can work with my development team.

Thanks
Rahul Singh

**Comment by stevemessick** [comment]
This issue tracker is for dealing with problems related to the Flutter plugin for IntelliJ.
