### ISSUE TITLE
Document pub notification pile-up.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#686]
Until a fresh Dart Plugin is published, users will see multiple messages indicating they should update packages when pubspecs get edited.

![screen shot 2017-01-30 at 1 58 48 pm](https://cloud.githubusercontent.com/assets/67586/22443686/a4ccb556-e6f4-11e6-922f-cfaa5acd5fa2.png)

(Ours will run `flutter packages` commands while the Dart one, soon to be suppressed, simply runs `pub`.)

#670 proposes moving these inspections to editor notifications which will at least give us icons as a means to differentiate notifications.  Short-term maybe a little word-smithing would be good?

@devoncarew @mit-mit

**Comment by mit-mit** [comment]
When would an updated Dart plugin be published? I.e., for users that actually upgrade fast, how long would they see this problem?

**Comment by pq** [comment]
Great question.

I believe we have a short list of cherry-picks we'd like to see in a stable Dart Plugin release  (@stevemessick and @alexander-doroshko's text-editing themed fixes notably).

@alexander-doroshko : are you thinking of (or willing to think of) releasing a fresh plugin soon?  Thanks in advance!

**Comment by alexander-doroshko** [comment]
Already cherry-picked and released the plugin yesterday. Do you still see the problem after the plugin update?

**Comment by pq** [comment]
> Already cherry-picked and released the plugin yesterday. 

Amazing.  Best answer ever.  Thank you!

Confirmed fixed.  Much appreciated @alexander-doroshko !

<img width="763" alt="screen shot 2017-01-31 at 6 12 13 am" src="https://cloud.githubusercontent.com/assets/67586/22468164/3b6c823e-e77c-11e6-889e-2977bc7e9475.png">
