### ISSUE TITLE
Argument for @NotNull parameter 'name' of io/flutter/vmService/frame/DartVmServiceValue.<init> must not be null

### ISSUE THREAD

**Issue by tasselx** [flutter/flutter-intellij#6862]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

The plugin version is 75.0.4, and when using breakpoints it says
"Argument for @NotNull parameter 'name' of io/flutter/vmService/frame/DartVmServiceValue.<init> must not be null" and The breakpoint property shows collecting data...

I tried to rollback the plugin version to 74.0.5 and everything works fine again!

![520492101](https://github.com/flutter/flutter-intellij/assets/2656142/37fece6c-f1a3-42bf-950c-a0f14cca9656)

## Version info

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 13.2.1 22D68 darwin-arm, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] VS Code (version 1.80.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

**Comment by AlexV525** [comment]
This seems to be version-specific. I cannot reproduce this on Flutter 3.12.

**Comment by tasselx** [comment]
This is a demo that can be reproduced, I am using a newly created project @AlexV525 

[mylody.zip](https://github.com/flutter/flutter-intellij/files/12247896/mylody.zip)

**Comment by AlexV525** [comment]
By saying reproduced, do you mean it can be reproduced in all Flutter versions?

**Comment by AlexV525** [comment]
Labelling for further investigation.

**Comment by eggp** [comment]
I also have the error

OS: LinuxMint 21 

![image](https://github.com/flutter/flutter-intellij/assets/1015211/bb1294ec-3b4c-44a5-8fb6-32fdd8c84625)
![image](https://github.com/flutter/flutter-intellij/assets/1015211/7d71bd7d-edff-43b2-be25-cbbafc807617)
![image](https://github.com/flutter/flutter-intellij/assets/1015211/1529ce29-3d6d-4190-be89-7d280cc02d98)

**Comment by froccawork** [comment]
I tried to rollback from flutter plugin version 75.0.3 to 74.0.4 and it works for me

**Comment by eggp** [comment]
> I tried to rollback from flutter plugin version 75.0.3 to 74.0.4 and it works for me

I did that too

**Comment by stevemessick** [comment]
Could you update to version 75.1 and let us know if the problem has been fixed?

**Comment by PedroTicGal** [comment]
I had that exact problem with version 75.0.4 of the plugin. 
Now with 75.1.4, it is working as expected. 
Thank you.

**Comment by stevemessick** [comment]
Thanks @PedroTicGal !

**Comment by tasselx** [comment]
> Could you update to version 75.1 and let us know if the problem has been fixed?

I upgraded to the 75.1.4 version of the plugin and it works fine now, thank you very much!

**Comment by eggp** [comment]
working, thanks
