### ISSUE TITLE
Missing field names while debugger stopped on breakpoint

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter-intellij#6863]
When watching values while debugger is on breakpoint, I can only see fields values, field names are missing:

![image](https://i.stack.imgur.com/5a3J8.png)

[!] Flutter (Channel stable, 3.7.5, on Debian GNU/Linux bullseye/sid
    5.19.0-0.slh.1-aptosid-amd64, locale pl_PL.UTF-8)
    • Flutter version 3.7.5 on channel stable at /home/michal/android/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (5 miesięcy temu), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/michal/Android/Sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /home/michal/Android/Sdk
    • Java binary at: /home/michal/android/studio_old/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • clang version 9.0.1-14+b1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install
      libgtk-3-dev)

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/michal/android/studio
    • Flutter plugin version 75.0.1
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.3)
    • Android Studio at /home/michal/android/studio_old
    • Flutter plugin version 75.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /home/michal/Pobrane/InteliJ/ideaIC-2020.2/idea-IC-202.6397.94
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[✓] VS Code (version 1.50.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12
      (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Debian
      GNU/Linux bullseye/sid 5.19.0-0.slh.1-aptosid-amd64
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 115.0.5790.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

Bug is found in Flutter plugin version  75.0.2. After downgrading plugin to 73.0.2 field names are visible again:

![image](https://github.com/flutter/flutter-intellij/assets/26817206/ba773f58-ae96-4778-93fc-fccbc46a3fbd)

Can you confirm a bug and provide possible workaround?

**Comment by stevemessick** [comment]
Could you update to version 75.1 and let us know if the problem has been fixed?

**Comment by giaur500** [comment]
75.1.1 problem fixed.
