### ISSUE TITLE
Remove setting that enables indexing of Java and Kotlin

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#6866]
The experimental setting that enables indexing for Java and Kotlin has been disabled because it is no longer maintainable. The UI should be updated to hide that check box.

**Comment by jwren** [comment]
Looking through the new Flutter dialog as well as the Flutter settings I don't see such a setting.  @stevemessick is this a duplicate of https://github.com/flutter/flutter-intellij/pull/6815?
