### ISSUE TITLE
Completion for generic type broken in some conditions unless an identifier is inserted after.

### ISSUE THREAD

**Issue by gsouf** [flutter/flutter-intellij#6867]
## Steps to Reproduce

I noticed that sometimes the completion for the generic type of the type of a property/method is not working. Unfortunately I couldn't find the exact conditions that lead to this issue, but I found that using the annotation `immutable` on the class will help to reproduce the issue.

----------

Here is a working  example where I'm trying to autocomplete `bool`:

```dart
class Foo {
  final List<bo>
}
```
When  my cursor is here after `<bo` and before `>`,  I press `ctrl + space` to autocomplete it works as expected, it will complete to become `bool`.

---------

Now the same example when I apply the annotation `immutable` from `flutter/widget.dart`. 
It will **NOT** work.

```dart
import 'package:flutter/widgets.dart';

@immutable
class Foo {
  final List<bo>
}
```
 
When  my cursor is here after `<bo` and before `>`, I press `ctrl + space` to autocomplete, **nothing happens**.

------------

Now the previous example but modified with the name of the properties (I added `foo` after `List<bo>`). It doesn't matter if there is a final semicolon or not `;`.
It will work.

```dart
import 'package:flutter/widgets.dart';

@immutable
class Foo {
  final List<bo> foo
}
```

When  my cursor is here after `<bo` and before `>`, I press `ctrl + space` to autocomplete it works as expected

## Version info

```
[✓] Flutter (Channel stable, 3.10.6, on Ubuntu 22.04.2 LTS 5.19.0-50-generic, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at xxxxxxx/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android Studio (version 2022.3)
    • Android Studio at xxxxx/AndroidStudio/ch-0/223.8836.35.2231.10406996
    • Flutter plugin version 75.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
```

**Comment by jwren** [comment]
Closing here, opened https://github.com/dart-lang/sdk/issues/53302
