### ISSUE TITLE
Add shorcut for adding a field as a named parameter

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#6868]
Currently when I create a class with a `final` parameter, I have a hint from the IDE to add that field into the constructor. Currently it creates as a simple parameter, such as `MyClass(this.myField)`, and I can also change it to a normal parameter, where it goes into the initialization list.

Since Flutter uses lots of named parameters, it will be very helpful if we could have the option to also have that field being added into the constructor as a named parameter.

**Comment by jwren** [comment]
Closing, captured in new issue on the analysis sever here: https://github.com/dart-lang/sdk/issues/53301
