### ISSUE TITLE
Plugin FlutterAssetAutoCompletion is not compatible with the current version of IDE

### ISSUE THREAD

**Issue by ascentman** [flutter/flutter-intellij#6869]
## Steps to Reproduce

After upgrading to new version Android Studio Giraffe I got error saying that FlutterAssetAutoCompletion is not compatible with the current version of IDE and as a result autocompletion doesn't work:

<img width="352" alt="Screenshot 2023-08-15 at 14 11 50" src="https://github.com/flutter/flutter-intellij/assets/16058309/131f6ea1-fcdd-4c15-a613-d0becf1cdf5c">

## Version info

Android Studio Giraffe | 2022.3.1
Build #AI-223.8836.35.2231.10406996, built on June 29, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 10
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.gionchat (1.3.4)
    OpenGL-Plugin (1.0.71)
    com.giancarlocode.built-value-snippets (1.2.0)
    com.intellij.marketplace (223.8836.56)
    com.bloc.intellij_generator_plugin (3.4.0)
    Dart (223.8950)
    andrasferenczi.dart-data-plugin (0.2.0)
    org.tbm98.flutter-riverpod-snippets (2.232.1)
    com.github.fawaz.flutter-freezed-snippets (1.0.6)
    cn.neday.excavator (2.4.4)
    izhangzhihao.rainbow.brackets (2023.3.2)
    ru.adelf.idea.dotenv (2022.3)
    zielu.gittoolbox (500.0.13+213)
    io.flutter (75.1.2)

```flutter doctor -v
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.5 22G74 darwin-arm64, locale
    en-UA)
    • Flutter version 3.10.5 on channel stable at
      /Users/vrykhva/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (9 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc2)
    • Android SDK at /Users/vrykhva/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 528C315A-7EA6-4346-BA82-4706E5BA9713 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                •
      darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by stevemessick** [comment]
You'll need to uninstall the `FlutterAssetAutoCompletion` plugin. It hasn't been updated in almost a year.
https://plugins.jetbrains.com/plugin/13971-flutterassetautocompletion/versions
