### ISSUE TITLE
Widget inspector doest jump to source code

### ISSUE THREAD

**Issue by YaserH25** [flutter/flutter-intellij#6875]
Hello
After i upgraded to Flutter 3.13, widget inspector stopped jumping to source code,  i tried a new projects and still having the same issue 
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.0 / stable
Framework / Engine: efbf63d9c6 / 1ac611c64e
Connected app type: Flutter native (debug build)

**Comment by xkeyC** [comment]
+1  
Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale zh-Hans-CN)

Android Studio Giraffe | 2022.3.1
Build #AI-223.8836.35.2231.10406996, built on June 29, 2023

Flutter intellij 75.1.2 Aug 04, 2023

**Comment by CoderDake** [comment]
@redfieldchristabel and @satishs22 have also reported this behaviour back in the DevTools repo: https://github.com/flutter/devtools/issues/6222

**Comment by itsJoKr** [comment]
This was working before. I had an update yesterday to Inspector ("What's new" was shown) and since then it doesn't work. (using IntelliJ idea).

**Comment by redfieldchristabel** [comment]
@CoderDake hi there, i upgrade to flutter latest version again today. the problem still presist .

**Comment by helin24** [comment]
An upcoming change to the plugin will fix this, but in the current plugin, you will need to revert to an older Flutter SDK version (works for me on 3.7.0). Sorry about the inconvenience!

**Comment by Maslan34** [comment]
ı had same issue. Downgrading flutter to 3.10.5 version also worked for me.

**Comment by Pisey-Nguon** [comment]
I had the same issue on Flutter version 3.13.6

**Comment by muhsinzyne** [comment]
is there any fixes for this ??

**Comment by muhsinzyne** [comment]
I am also facing the same issue. when i revert back to flutter version 3.10.2 it's working but during the time i am having error while i run debug mode in ios physical devise 

Could not run build/ios/iphoneos/myapp.app on 00008101-XXXXXXX.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on xxxx's iPhone.

**Comment by redfieldchristabel** [comment]
> An upcoming change to the plugin will fix this, but in the current plugin, you will need to revert to an older Flutter SDK version (works for me on 3.7.0). Sorry about the inconvenience!

its been a month, dart tool also fail on android studio, sometimes i need to rerun with vscode just to use this feature. please fix it it really needed feature and with this feature i can flex with other stack developer at my office but now i cant hahaha.

**Comment by kenzieschmoll** [comment]
> An upcoming change to the plugin will fix this, but in the current plugin, you will need to revert to an older Flutter SDK version (works for me on 3.7.0). Sorry about the inconvenience!

@helin24 @jwren has the new plugin version with the fix been released?

**Comment by xkeyC** [comment]
There is still no new version to fix this problem:https://plugins.jetbrains.com/plugin/9212-flutter/versions

It's been almost two months since the issue was reported, and it's hard not to wonder if flutter-intellij has been forgotten.

Before releasing a new version, we may need to manually compile and install: https://github.com/flutter/flutter-intellij/tree/master/tool/plugin

**Comment by kenzieschmoll** [comment]
@jwren and @helin24 are actively working on getting this plugin rolled out. We appreciate your patience. In the meantime, consider using VS Code to unblock your immediate Flutter Inspector needs.

**Comment by CoderDake** [comment]
Just to close the loop, there are a couple of ways that one could get this working until a new release is made.

You could try any of the following based on your needs:
1. Use VSCode (it is actively supported for Dart/Flutter Development)
2. Keep Flutter SDK under 3.7.0 until an intellij plugin release can occur
3. Do a Dev build of the intellij plugin so you can get the new fix. See the instructions in the comment https://github.com/flutter/flutter-intellij/issues/6894#issuecomment-1714549150

**Comment by muhsinzyne** [comment]
> @jwren and @helin24 are actively working on getting this plugin rolled out. We appreciate your patience. In the meantime, consider using VS Code to unblock your immediate Flutter Inspector needs.

please when i can expect this to be available ?

**Comment by muhsinzyne** [comment]
> @muhsinzyne I am currently manually testing a new roll of the Flutter plugin to be released as early as this upcoming Monday.

happy to hear... waiting for the rollout....

**Comment by muhsinzyne** [comment]
is this issues fixed ???

**Comment by muhsinzyne** [comment]
> @muhsinzyne I am currently manually testing a new roll of the Flutter plugin to be released as early as this upcoming Monday.

Hi @jwren  could you please update me the status i was searching for a new plugin support to resolve this issue. but as i  can see that no plugin updates till now..  if you are in the testphase, could you please provide me the beta version or any early access options. as i am really stuck due to this and it's very hard to switch my IDE...

**Comment by jwren** [comment]
@muhsinzyne I uploaded a new version before you posted this 5 hours ago. See https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/423005.  I am not sure why it isn't updating in the IDEs yet.  (No downloads yet for the new versions.)

**Comment by DanTup** [comment]
FWIW the new version shows for me in Android Studio on Windows

![image](https://github.com/flutter/flutter-intellij/assets/1078012/4cbee8e7-fa30-4c13-b749-e5a57ae0a40c)

**Comment by jwren** [comment]
Thanks Danny.

all-- Do let me know if this issue is not resolved in this release.

**Comment by satishs22** [comment]
![image](https://github.com/flutter/flutter-intellij/assets/124110600/a4a2584b-1131-477c-83be-4bad9ca5fdeb)
im getting this message, any idea how to solve this?

**Comment by sarope** [comment]
@jwren also getting the same error as @satishs22 above. The link to open in the browser works as expected though

**Comment by satishs22** [comment]
@Hactieuho thanks, after following the steps mentioned, i'm able to use the flutter inspector now

**Comment by muhsinzyne** [comment]
hey still the fix does not did any value addition to the developer as instead of jumping the code to layout it' goes to the directory or library view files. it should be the screen as per my understanding and my previous experience. now the jump to souce code is working like overperfromed till the basic flutter layout libraries.

**Comment by muhsinzyne** [comment]
> hey still the fix does not did any value addition to the developer as instead of jumping the code to layout it' goes to the directory or library view files. it should be the screen as per my understanding and my previous experience. now the jump to souce code is working like overperfromed till the basic flutter layout libraries.

i tried with both newest android studio version as well as Flamingo

**Comment by TheMaverickProgrammer** [comment]
> Is there a way to disable this behavior? The "jump to source code" is not desired for me and makes DevTools almost unusable for my use case of inspecting the widget tree.
> 
> Feel free to mark as off topic.

Did you ever find a solution for this? We're having the same issue when we only have one monitor available at a time.

**Comment by rayliverified** [comment]
Unfortunately not, it's infuriating because you lose the widget your inspecting if you click somewhere else in your code.

**Comment by TheMaverickProgrammer** [comment]
> Unfortunately not, it's infuriating because you lose the widget your inspecting if you click somewhere else in your code.

We completely agree. Often times we just want to look at the widget highlighting in our app next to the widget tree docked on the right side of the screen. When our editor jumps to the code, it dominates the layout and we can no longer read the widget tree.

**Comment by lecaro** [comment]
```
Android Studio Meerkat | 2024.3.1 Patch 1
Build #AI-243.24978.46.2431.13208083, built on March 13, 2025
Runtime version: 21.0.6+9-b631.42 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.4
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 16
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  Dart (243.23654.44)
  io.flutter (85.0.4)
```

After updating to the latest version of Android Studio at this moment,

**Everything works in the Flutter Inspector!... except that it doesn't open the source file.**

I've tried everything—I even uninstalled all the environments... and started from scratch, and nothing works.

Does anyone know if there's an option somewhere where this might be disabled?

**Comment by Hactieuho** [comment]
> ```
> Android Studio Meerkat | 2024.3.1 Patch 1
> Build #AI-243.24978.46.2431.13208083, built on March 13, 2025
> Runtime version: 21.0.6+9-b631.42 aarch64 (JCEF 122.1.9)
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Toolkit: sun.lwawt.macosx.LWCToolkit
> macOS 15.4
> GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
> Memory: 2048M
> Cores: 16
> Metal Rendering is ON
> Registry:
>   ide.experimental.ui=true
> Non-Bundled Plugins:
>   Dart (243.23654.44)
>   io.flutter (85.0.4)
> ```
> 
> After updating to the latest version of Android Studio at this moment,
> 
> **Everything works in the Flutter Inspector!... except that it doesn't open the source file.**
> 
> I've tried everything—I even uninstalled all the environments... and started from scratch, and nothing works.
> 
> Does anyone know if there's an option somewhere where this might be disabled?

https://github.com/flutter/flutter-intellij/issues/6875#issuecomment-1778332489

**Comment by lecaro** [comment]
> [#6875 (comment)](https://github.com/flutter/flutter-intellij/issues/6875#issuecomment-1778332489)

Thank you, Le. I had already tried this, and I tried it again just in case... and nothing... it's something strange. I've tried everything, even with old versions of Android Studio and the Flutter plugin... and nothing. The inspector works perfectly, except that it doesn't go to the source... however, it works fine with VS Code... but I'm used to AS...

**Comment by Hactieuho** [comment]
> > [#6875 (comment)](https://github.com/flutter/flutter-intellij/issues/6875#issuecomment-1778332489)
> 
> Thank you, Le. I had already tried this, and I tried it again just in case... and nothing... it's something strange. I've tried everything, even with old versions of Android Studio and the Flutter plugin... and nothing. The inspector works perfectly, except that it doesn't go to the source... however, it works fine with VS Code... but I'm used to AS...

Try older flutter plugin version:
https://plugins.jetbrains.com/plugin/9212-flutter/versions
or another Boot Java Runtime version

**Comment by lecaro** [comment]
> Try older flutter plugin version: https://plugins.jetbrains.com/plugin/9212-flutter/versions or another Boot Java Runtime version

Thanks again, Le. I kept trying, did what you last suggested and more, but no luck. I've given up for now. I'll be working with VS Code... every now and then I'll update AS, hoping it'll get fixed someday.

**Comment by daehan-lim** [comment]
> > Try older flutter plugin version: https://plugins.jetbrains.com/plugin/9212-flutter/versions or another Boot Java Runtime version
> 
> Thanks again, Le. I kept trying, did what you last suggested and more, but no luck. I've given up for now. I'll be working with VS Code... every now and then I'll update AS, hoping it'll get fixed someday.

I am having the same issue as you, same Android Studio version, and nothing seems to fix it

**Comment by AlexThunder2000** [comment]
> > Try older flutter plugin version: https://plugins.jetbrains.com/plugin/9212-flutter/versions or another Boot Java Runtime version
> 
> Thanks again, Le. I kept trying, did what you last suggested and more, but no luck. I've given up for now. I'll be working with VS Code... every now and then I'll update AS, hoping it'll get fixed someday.

I have this problem too. I don't even know when exactly or why it started. Nothing helps(

If anyone can find a solution, please help

**Comment by daehan-lim** [comment]
> > > Try older flutter plugin version: https://plugins.jetbrains.com/plugin/9212-flutter/versions or another Boot Java Runtime version
> > 
> > 
> > Thanks again, Le. I kept trying, did what you last suggested and more, but no luck. I've given up for now. I'll be working with VS Code... every now and then I'll update AS, hoping it'll get fixed someday.
> 
> I have this problem too. I don't even know when exactly or why it started. Nothing helps(
> 
> If anyone can find a solution, please help

Apparently, they are working on a fix
https://github.com/flutter/flutter-intellij/issues/8041

**Comment by AlexThunder2000** [comment]
> > > Try older flutter plugin version: https://plugins.jetbrains.com/plugin/9212-flutter/versions or another Boot Java Runtime version
> > 
> > 
> > Thanks again, Le. I kept trying, did what you last suggested and more, but no luck. I've given up for now. I'll be working with VS Code... every now and then I'll update AS, hoping it'll get fixed someday.
> 
> Try the older Flutter Plugin Version (76.0.1) (Please don't update the Flutter Plugin Version if needed!!!): https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/423006 ![Image](https://github.com/user-attachments/assets/f8ccf291-d3dc-4f47-a80f-12c58d22603a)

Plugin 'Flutter' (version '76.0.1') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is AI-243.24978.46
