### ISSUE TITLE
`Wrap with Widget...` wraps the `switch` expression, not the widget.

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#6877]
When we have a `switch` expression like:

```dart
BlocBuilder<MyCubit, MyState>(
  bloc: bloc,
  builder: (context, state) {
    return switch (state) {
      MyStateLoading() => const SliverToBoxAdapter(
          child: Center(
            child: CircularProgressIndicator(),
          ),
        ),
      MyStateEmpty() => const SliverToBoxAdapter(child: EmptySection()),
      MyStateLoaded() => const MySliver(),
    };
  },
)
```

and we try to use `Wrap with Widget...` to, let's say, wrap the `const MySliver()` on the last match line for the `switch`, the IDE will wrap the `switch` statement, applying this widget into all the switch returns, and not just the `MySliver`.

**Comment by AlexanderFarkas** [comment]
Before: 
<img width="564" alt="Screenshot 2023-09-02 at 10 17 41" src="https://github.com/flutter/flutter-intellij/assets/35890159/163c2633-4b97-43c2-89e9-a0a215536011">


After:
<img width="632" alt="Screenshot 2023-09-02 at 10 17 08" src="https://github.com/flutter/flutter-intellij/assets/35890159/45b7c60b-92d6-4572-84e4-400096679eb0">

**Comment by jacob314** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/53412 which tracks the underlying analyzer issue.
