### ISSUE TITLE
Duplicated .iml files

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#689]
## Steps to Reproduce

1. In the Terminal, run `flutter create test1`

Expected and actual behaviour: The `test1` folder has no `.iml` file directly inside it; this is located in `test1/.idea/`.

2. Inside IntelliJ, File>Create a new Flutter project `test2`

Expected result: Same as from terminal
Actual result: There is an `.iml` file both inside `test2/` and inside `test2/.idea/`.

## Version info

IJ plugin 0.1.9

Flutter:
    • Framework revision 6469b475d2 (7 hours ago), 2017-01-30 23:32:44
    • Engine revision 9de4d1530b
    • Tools Dart version 1.22.0-dev.9.1

**Comment by mit-mit** [comment]
Related change: https://github.com/flutter/flutter/pull/7501

**Comment by mit-mit** [comment]
@pq any idea what is going on here?

**Comment by pq** [comment]
Project creation (from IntelliJ) creates it's own metadata and _then_ runs `flutter create`, which is to say the only time the metadata from `flutter create` is used is in the project "open" flow. The default location for IntelliJ-created IMLs appears to be the root directory (and not `.idea/`?)  It would be hard (and probably not advisable) to use the metadata created by the commandline tool in the "create" flow but I think we should definitely strive to have them agree with each other as best we can.  (Behind the scenes I think this will involve changes to `FlutterModuleBuilder` though at a quick glance I'm not seeing where...)

Happy to dig further if you want.

**Comment by mit-mit** [comment]
I think we have to dig; the current state is very confusing (why are there 2? which file do I edit? will changes sync? can I delete one? etc.)

**Comment by pq** [comment]
Sounds good.  I'll take a look.

**Comment by devoncarew** [comment]
Perhaps we can have `flutter create` only conditionally create the IntelliJ metadata, if it doesn't already exist in the root project dir? Alternatively we could move back to creating the metadata in the project dir (and not the .idea subdir).

**Comment by mit-mit** [comment]
Is there no way to tell IJ to create the .iml inside .idea?

**Comment by pq** [comment]
> Is there no way to tell IJ to create the .iml inside .idea?

I'm not sure.  Maybe @alexander-doroshko knows?

**Comment by alexander-doroshko** [comment]
IML file location is selected at the next Flutter Project Wizard step after providing a path to the Flutter SDK.
![image](https://cloud.githubusercontent.com/assets/4499789/22475654/b38ab636-e7f0-11e6-9218-c7726d7fe836.png)
You can debug where default paths come from. May be you can tweak defaults before this step is shown; or ignore what is set at this step somewhere later. Both ways are not perfect though.

**Comment by alexander-doroshko** [comment]
> Inside IntelliJ, File>Create a new Flutter project test2
Expected result: Same as from terminal
Actual result: There is an .iml file both inside test2/ and inside test2/.idea/

Is it because Flutter Project Wizard creates a new copy of IntelliJ project files? It means wizard fights itself. 
When creating a project using a wizard the IDE cares about project files **creation** itself. Your module builder may tweak module settings and create sample files.

**Comment by mit-mit** [comment]
Adjusting the default path for the .iml file sounds like the desired behavoir if possible without being to hacky.

**Comment by devoncarew** [comment]
From a very very cursory look at AppCode, it looks like it gets unhappy with .iml files not in the module root.

**Comment by pq** [comment]
> From a very very cursory look at AppCode, it looks like it gets unhappy with .iml files not in the module root.

To be clear, @devoncarew: you mean it does not like IML files in the `.idea` dir as we've been leaning?

**Comment by devoncarew** [comment]
That was what it looked like from the error I saw; I didn't dig in to be certain.

**Comment by pq** [comment]
@alexander-doroshko does this sound familiar to you?

**Comment by alexander-doroshko** [comment]
I never ran AppCode. @devoncarew do you have a screenshot of the error?
