### ISSUE TITLE
Compatibility with CLion

### ISSUE THREAD

**Issue by ruifengx** [flutter/flutter-intellij#6899]
Flutter has support for developing desktop applications, but in IntelliJ IDEA it is very painful to edit the C++ files for e.g. the Windows runner because its lack of support for C++ and CMake. Is it possible for this plug-in to also support CLion?

**Comment by Gustl22** [comment]
One can run IntelliJ / Android Studio side by side with CLion, similar to the Windows approach [described here](https://docs.flutter.dev/testing/native-debugging?tab=from-vscode-to-android-studio#debug-dart-and-c-code-using-visual-studio).

I made a draft for adapting the docs, the one way works. Starting the app in Android Studio and attach the debugger in CLion, but I found no solution to how to start the process from within CLion (and then attach Android Studio).
https://github.com/flutter/website/compare/main...Gustl22:flutter-website:patch-1

Refs: 
- https://docs.flutter.dev/packages-and-plugins/developing-packages#step-2d-add-linux-platform-code-hcc
- https://docs.flutter.dev/testing/native-debugging?tab=from-vscode-to-android-studio#debug-dart-and-c-code-using-visual-studio
- https://www.jetbrains.com/help/clion/attach-to-process.html
- https://github.com/flutter/flutter/issues/79179

**Comment by AldoMX** [comment]
CLion is supported if you downgrade it to version 2022 and use version 69.0.5 of the plugin:
https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/191250

I remember that Jetbrains did an update in the past that broke too many plugins, so Flutter team probably didn't want to spend time fix it outside IntelliJ & Android Studio.

**Comment by jwren** [comment]
Builds for CLion are currently out of scope for the Flutter team.
