### ISSUE TITLE
I just opened the IDE and got this error !!! 

### ISSUE THREAD

**Issue by beautybird** [flutter/flutter-intellij#7006]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

I updated the IDE to latest version today and this is the 3rd error today.
I just opened the IDE and got this error !!! 

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by AlexV525** [comment]
Which is? You didn't paste any errors here.

**Comment by beautybird** [comment]
Hi,
I thought  the error  details should be embedded with the message.
Apology.
