### ISSUE TITLE
Error getting Flutter sdk information.

### ISSUE THREAD

**Issue by weirdsir** [flutter/flutter-intellij#7016]
What happened
Happens upon opening IntelliJ IDEA with the Flutter plugin

Version information
IntelliJ IDEA 2023.2.4 • Flutter plugin io.flutter 76.1.4 • Dart plugin 232.10072.19
[bug-report_3.md](https://github.com/flutter/flutter-intellij/files/13185314/bug-report_3.md)

Error getting Flutter sdk information.

**Comment by AlexV525** [comment]
It has been fixed by https://github.com/flutter/flutter-intellij/pull/7002 and will soon be published.
