### ISSUE TITLE
Hot reload on save stopped working on 76.1.x

### ISSUE THREAD

**Issue by jorgevvr** [flutter/flutter-intellij#7027]
I updated the flutter plugin to the last version (76.1.x) and it stop making hot reload on save (ctrl+s), then i download and installed manually (76.0.x) on android studio stable and cannary and both works correctly.

## Version info

flutter doctor -v
[✓] Flutter (Channel stable, 3.13.9, on Microsoft Windows [versÆo 10.0.22621.2506], locale pt-BR)
    • Flutter version 3.13.9 on channel stable at D:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\jorge\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: D:\Dev\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.8+0--10799086)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] Android Studio (version 2023.2)
    • Android Studio at D:\Dev\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.8+0--10799086)

[✓] VS Code (version 1.83.1)
    • VS Code at C:\Users\jorge\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [versÆo 10.0.22621.2506]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 118.0.5993.118
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 118.0.2088.61

[✓] Network resources
    • All expected network resources are available.

**Comment by jwren** [comment]
See https://github.com/flutter/flutter-intellij/issues/6996  Closing this issue out.  If there is still a regression here, open a new issue and tag me to escalate.
