### ISSUE TITLE
Run 'flutter doctor' automatically and display warnings in IDEA

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#705]
For example, if Flutter can't find the Android SDK then we should probably warn about that and give a hint about how to fix it. (Currently this is by setting ANDROID_HOME in your startup script and restarting IDEA; the second step is unintuitive.)

This probably involves implementing 'flutter doctor --json' and defining a schema for the data.

**Comment by devoncarew** [comment]
assumed stale -
