### ISSUE TITLE
Hot reload is not working in a specific file - Flutter

### ISSUE THREAD

**Issue by Sahilbhayani** [flutter/flutter-intellij#7056]
Hot reload is not working for specific file. When i change something in code and press cltr + s hot reload is not perform.
But It's working very well in main.dart file.

flutter version :  3.13.9
Dart version : 3.1.5
Android studio version : 3.1.20

**Comment by AlehSabadashGmail** [comment]
+1, I downgraded plugin to 75 version to fix it

**Comment by Sahilbhayani** [comment]
It spend me several hours to figure out the reason, so I hope this would help to save your time

Downloading the 76.0.x or earlier zip file from this link
https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable

And install the plugin manually from file, which will make the hot reload works again..

For android studio Go : follow this
![Screenshot from 2023-11-06 18-34-10](https://github.com/flutter/flutter-intellij/assets/77524691/7d8709be-5e66-4114-8469-6ab940386c81)
