### ISSUE TITLE
[Reproducible] Cannot find declaration to go to

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter-intellij#7067]
Make a file named bug.dart:
```dart
import 'package:flutter/widgets.dart';

Widget totalBuilder(List<(String, String)> none) {
  return Container();
}
```

Expected result: command+click on Container goes to Container.
Result: no declarations.
<img width="560" alt="image" src="https://github.com/flutter/flutter-intellij/assets/351125/b20802e0-d8bc-4f4b-80a3-240e42da15b1">

Reproducible project:
[bug.zip](https://github.com/flutter/flutter-intellij/files/13291730/bug.zip)

## Version info

[!] Flutter (Channel master, 3.17.0-4.0.pre.20, on macOS 13.6 22G120 darwin-x64, locale en-BR)
    • Flutter version 3.17.0-4.0.pre.20 on channel master at /Users/bernardoferrari/Downloads/flutter
    • Framework revision 89692884a1 (2 hours ago), 2023-11-07 17:53:22 -0800
    • Engine revision 3e3be5e33b
    • Dart version 3.3.0 (build 3.3.0-102.0.dev)
    • DevTools version 2.30.0-dev.1

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.4)
    • IntelliJ at /Users/bernardoferrari/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.2.4
    • Dart plugin version 232.10072.19

**Comment by jacob314** [comment]
Fyi @jwren. Likely this is a bug related to how the Dart IntelliJ plugin parses record types. Note the record type in the method signature.

**Comment by alexander-doroshko** [comment]
True, it was a Dart plugin issue. I've just uploaded the Dart plugin version 232.10248, which contains the fix.

For the IDE version 2023.1.x, the Dart plugin with the fix has version 231.9409.

**Comment by bernaferrari** [comment]
Should I close this issue? Thanks a lot!

**Comment by alexander-doroshko** [comment]
> Should I close this issue? 

As you wish =). I don't have permissions in this repository, so I can't close it myself. You may verify the fix first. BTW, has the IDE auto-suggested that you update the Dart plugin to version 232.10248? For some reason, my instance of IntelliJ IDEA 2023.2.5 hasn't noticed the Dart plugin update yet.

**Comment by bernaferrari** [comment]
I updated here, perfect. Thanks a lot!
