### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#71]
Some thoughts:

  * [x] How to build
  * [ ] How to deploy

and points of inspiration:

* https://github.com/Microsoft/vscode/wiki
* https://github.com/Microsoft/vscode/wiki/Smoke-Test

**Comment by mit-mit** [comment]
Would also be nice to have a 'How to build' page.

**Comment by pq** [comment]
> Would also be nice to have a 'How to build' page.

👍  @mit-mit I added a punch list to the main topic.  Feel free to add ideas there!

**Comment by devoncarew** [comment]
Closing as we've re-done the wiki a few times since this was filed.
