### ISSUE TITLE
Update the Flutter Plugin for AS Iguana 2023.3, as well as the IJ Platform if there are not API breaking changes

### ISSUE THREAD

**Issue by jwren** [flutter/flutter-intellij#7113]
This PR is the first step here but not sufficient for Android Studio Iguana: https://github.com/flutter/flutter-intellij/pull/7112

![Screenshot 2023-12-05 at 2 27 03 PM](https://github.com/flutter/flutter-intellij/assets/1533520/d05765d8-cc84-4c69-8e0d-dd69cdc8e54a)

This is the start of the product matrix update for IJ EAP, 2023.3:

```
    {
      "channel": "stable",
      "comments": "IntelliJ 2023.2, Android Studio 2023.2",
      "name": "2023.2",
      "version": "2023.2",
      "isUnitTestTarget": "true",
      "ideaProduct": "android-studio",
      "ideaVersion": "2023.2.1.11",
      "baseVersion": "232.10203.10",
      "dartPluginVersion": "232.10072.19",
      "sinceBuild": "232.10072.19",
      "untilBuild": "232.*"
    }
```

**Comment by jwren** [comment]
The error screenshot above was due to me trying to install into the incorrect AS version.  With https://github.com/flutter/flutter-intellij/pull/7112, I now have the Flutter plugin running successfully in AS 2023.3, Iguana:

```
Android Studio Iguana | 2023.2.1 Canary 16
Build #AI-232.10227.8.2321.11161997, built on November 30, 2023
Runtime version: 17.0.9+0-17.0.9b1000.46-11084592 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
    Dart (232.10248)
    io.flutter (77.0.3)
```

Additional testing and possibly additional PRs to land before I push out this version.

**Comment by newfantoski** [comment]
Thank you for this update @jwren, how can we use it on our end ? Do we have to wait for the plugins.jetbrains.com plugin Jetbrains to update or can we build from source in any way ? 

Thank you so much.

**Comment by jwren** [comment]
For full transparency here, I have `2022.3`, `2023.1` and `2023.2` successfully building with the change I landed yesterday (https://github.com/flutter/flutter-intellij/pull/7112).  I have been trying to get `2023.3` to build with the Flutter plugin today, but am hitting an issue with either Gradle, Maven, or the published IntelliJ Community zip on maven:

```
Could not determine the dependencies of task ':prepareSandbox'.  > Failed to query the value of task ':prepareSandbox' property 'pluginDependencies'.
> Cannot find builtin plugin 'org.jetbrains.android' for IDE: ...  
```

The IJ Community is downloading, all plugins are there, except this required plugin.  I have reached out to various folks to start to troubleshoot.

I have posted this on Discord as well on the hackers-intellij channel here: https://discord.com/channels/608014603317936148/1174870334231552070.

**Comment by jwren** [comment]
Posting separately to stay under limits. This is version `2023.1`, this should work on community, ultimate, and AS. The changelog hasn't yet been updated (see git change history).
[flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/13592404/flutter-intellij.zip)

**Comment by jwren** [comment]
Posting separately to stay under limits. This is version 2023.1, this should work on community, ultimate, and AS. The changelog hasn't yet been updated (see git change history).

The Android Studio compatibility here is new, do post here or email me if there are found exceptions, etc.
[flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/13592418/flutter-intellij.zip)

**Comment by AnggaSP** [comment]
> For full transparency here, I have `2022.3`, `2023.1` and `2023.2` successfully building with the change I landed yesterday (#7112). I have been trying to get `2023.3` to build with the Flutter plugin today, but am hitting an issue with either Gradle, Maven, or the published IntelliJ Community zip on maven:
> 
> ```
> Could not determine the dependencies of task ':prepareSandbox'.  > Failed to query the value of task ':prepareSandbox' property 'pluginDependencies'.
> > Cannot find builtin plugin 'org.jetbrains.android' for IDE: ...  
> ```
> 
> The IJ Community is downloading, all plugins are there, except this required plugin. I have reached out to various folks to start to troubleshoot.
> 
> I have posted this on Discord as well on the hackers-intellij channel here: https://discord.com/channels/608014603317936148/1174870334231552070.

This is because starting in 2023.3, they've changed the distribution of Android plugins from built-in to become a marketplace plugins https://plugins.jetbrains.com/plugin/22989-android

See the plugin updates on the bottom of this what's new in intellij 2023.3 https://www.jetbrains.com/idea/whatsnew/

**Comment by jwren** [comment]
Posting separately to stay under MB limits. This is version 2023.3 for anyone willing to give feedback before I push out a version hopefully early next week.  The change required, see PR, requires changes to the flutter-intellij GitHub presubmits.

Do let me know if you try this on version 2023.3 of Ultimate or Community and you are unsuccessful.

[flutter-intellij.zip](https://github.com/flutter/flutter-intellij/files/13606146/flutter-intellij.zip)

**Comment by kvenn** [comment]
That worked. To save anyone unfamiliar a Google, you can install that zip with the gear on plugins.
![image](https://github.com/flutter/flutter-intellij/assets/1782467/fcd2b16c-48a8-4082-823d-befb59d69739)

**Comment by jwren** [comment]
This has been resolved with the stable releases under `77.x` and `77.1.x`, https://plugins.jetbrains.com/plugin/9212-flutter/edit/versions/stable/453511
