### ISSUE TITLE
Flutter Inspector is not working with flutter plugin version 77.1.2 Hedgehog 2023.1.1

### ISSUE THREAD

**Issue by HamadaAllipy** [flutter/flutter-intellij#7147]
### Problem
When attempting to open the Flutter Inspector in Android Studio on a MacBook Air 2020 with an M1 chip, I encountered the following error:

"The embedded browser failed to load error: JSEF is not supported in this env or failed to initialize."

![Screenshot 2023-12-18 at 7 22 51 AM](https://github.com/flutter/flutter-intellij/assets/48868414/c8fe855a-760d-430f-a410-2e938efbf3c8)

### Environment
- **Flutter Version:** 3.16.4
- **Dart Version:**  3.2.3
- **Android Studio Version:** Android Studio Hedgehog | 2023.1.1
- **Operating System:** macOS Sonoma 14.2 (23C64)

### Steps to Reproduce
1. Open Android Studio.
2. Navigate to the Flutter Inspector.
3. Attempt to open the Flutter Inspector.
4. Observe the error message.

### Expected Behavior
The Flutter Inspector should open without encountering the mentioned error.

### Possible Workarounds
- Downgrade the Flutter plugin to version 76.3.3.

**Comment by zinon-software** [comment]
the same issue

**Comment by amrhassann** [comment]
same issue

**Comment by git-boya** [comment]
same issue

**Comment by mdddj** [comment]
some issue

**Comment by kazbeksultanov** [comment]
same issue

**Comment by Abdulvaliy** [comment]
Same issue, tried older versions and jxbrowser worked smoothly but "Hot Reload" on save (⌘+S) is not working. Please, fix the issue. @jwren is there any solutions or update for this?

**Comment by alexregiani** [comment]
same issue here as well, did a full reinstall of Android Studiio and nothing, doing some research it has apparently something to do with JX Browser

**Comment by jaiswal4sudeep** [comment]
same issue

**Comment by helin24** [comment]
It seems often Android Studio uses a JDK that does not include JCEF, which is how we're now displaying the embedded inspector. However, I'm not sure how the JDK is determined; it seems to vary by individual machine.

**For all of you who are having the issue, could you post what version of JDK Android Studio is using?** Go to Help > Find Action > Choose boot runtime for the IDE. (I'm trying to figure out what JDKs are common, to gauge whether it's likely this problem will resolve in the next version of Android Studio.)

**If you are able to select a different runtime from that menu that includes JCEF, then this will likely fix your issue.**

**Comment by Abdulvaliy** [comment]
@helin24, It shows 17.0.7

**Comment by kazbeksultanov** [comment]
@helin24 17.0.7
I changed to 17.0.7+10-829.16-jcef, and now my app is not launching. Stuck on native splash screen.
```
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/flutter ( 5454): [ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
E/flutter ( 5454): [ERROR:flutter/runtime/runtime_controller.cc(463)] Could not create root isolate.
E/flutter ( 5454): [ERROR:flutter/shell/common/shell.cc(645)] Could not launch engine with configuration.
```
Tried `flutter clean`, didn't work.
Switched back to default runtime.

**Comment by NijatNaghiyev** [comment]
@helin24 it worked. Thank you.
I changed  17.0.7+10-829.16-jcef.

**Comment by peterlauri** [comment]
> **For all of you who are having the issue, could you post what version of JDK Android Studio is using?** Go to Help > Find Action > Choose boot runtime for the IDE. (I'm trying to figure out what JDKs are common, to gauge whether it's likely this problem will resolve in the next version of Android Studio.)

My env with problem: 17.0.7

Swapped to 17.0.7+10-829.16-jcef and all fine :)

**Comment by philos3** [comment]
which one to choose in mac M2 evn @peterlauri 
![image](https://github.com/flutter/flutter-intellij/assets/8424317/d29222a6-1d0e-4c31-8032-f4ca9a83a900)

**Comment by HamadaAllipy** [comment]
Thanks to Flutter, this issue has been resolved by updating the Flutter plugin to version 78.0.1.

**Comment by HamadaAllipy** [comment]
Thanks to Flutter, this issue has been resolved by updating the Flutter plugin to version 78.0.1.
