### ISSUE TITLE
Editing pubspec.yaml leads to persistent 'pub get' banner

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#715]
## Steps to Reproduce

1. Create a new project in IJ
1. Open pubspec.yaml and add an empty line between existing lines 1 and 2
1. Open `lib/main.dart`
1. Wait for the 'Pubspec has been edited' banner, and hit 'Get dependencies'
1. Close and then re-open `lib/main.dart`

Expected result: No pub banner
Actual result: You get the 'Pubspec has been edited' banner again

**Comment by pq** [comment]
This looks like a dup of #667.   The rub is that IDEA is lagging behind the local filesystem.  A way I can reliably get it back up to date is by manually opening the `.packages` file.  I'm trying to do the equivalent thing in source already but that appears flaky too:

        LocalFileSystem.getInstance().refreshAndFindFileByPath(workingDir.getPath() + "/" + FlutterConstants.PACKAGES_FILE);

@alexander-doroshko : any thoughts on your end?

**Comment by pq** [comment]
Incidentally, just noticed an update waiting:

<img width="642" alt="screen shot 2017-02-08 at 5 00 05 am" src="https://cloud.githubusercontent.com/assets/67586/22738275/9887a8dc-edbb-11e6-94de-48b0969aab6d.png">

Will apply and re-try.  Fingers-crossed!

**Comment by pq** [comment]
After a little more investigation I think this inspection was always a little fishy.  The docs for `com.intellij.openapi.vfs.VirtualFile#getTimeStamp` are clear that the value may get cached:

    Gets the timestamp for this file. Note that this value may be cached and may differ from
    the timestamp of the physical file.

cc @alexander-doroshko : since I think this applies equally to similar checks in the Dart Plugin.

**Comment by alexander-doroshko** [comment]
As I wrote in #667 I think the problem is not with the timeStamp, but more likely with the inspection that is not rerun after timeStamp changes. So it simply doesn't check the updated timeStamp and continues to show the warning that was calculated previously. I didn't investigate it further, though.

**Comment by pq** [comment]
Thanks for chiming in @alexander-doroshko!

> As I wrote in #667 I think the problem is not with the timeStamp,

I'm pretty confident the timestamp is lagging.  Like I said, I can reliably get it to update by manually opening the lagging file.  I can also confirm it with printfs.  Moreover, if I skip right to using `java.io.File` I don't see the issue.

**Comment by alexander-doroshko** [comment]
Ok, thanks, I'll check once again.

**Comment by Zarainia** [comment]
I'm still experiencing this on Flutter plugin v72.1.4 and IntelliJ IDEA 2022.3.3. Any ideas?
