### ISSUE TITLE
add docs for recommended settings for completions and doc display

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#720]
We should update our docs to recommend two additional settings:

<img width="455" alt="screen shot 2017-02-09 at 8 45 21 am" src="https://cloud.githubusercontent.com/assets/1269969/22793414/a078910c-eea4-11e6-86cb-6d15ba5b0486.png">

<img width="469" alt="screen shot 2017-02-09 at 8 47 31 am" src="https://cloud.githubusercontent.com/assets/1269969/22793413/a07796a8-eea4-11e6-9263-230654d4a1f4.png">

This shows dartdoc in code completions, and displays docs in tooltips on hover respectively.

**Comment by pq** [comment]
On second thought, maybe not?  Closing for now.
