### ISSUE TITLE
Where do I file IntelliJ Dart-lang issues

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter-intellij#721]
It's in youtrack, but never remember where the template link is.
Could we add it to our README.md or other places where we mention https://github.com/flutter/flutter-intellij/issues/new.

**Comment by devoncarew** [comment]
It's here: https://youtrack.jetbrains.com/issues?q=%23dart; we should update the docs and the new issue template.

**Comment by devoncarew** [comment]
You can also file against the dart sdk repo - there is a label for IntelliJ. Those will often get triaged to include a companion bug on the youtrack tracker.

**Comment by pq** [comment]
Plan of record: encourage folks to report issues here and we can triage and move.

AI: update readme.

**Comment by devoncarew** [comment]
fixed here: https://github.com/flutter/flutter-intellij/commit/233505d71bbcd92a59e3b0b0226ac37f109e36fd
