### ISSUE TITLE
Add a way to copy the DTD URI from the IntelliJ plugin

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#7242]
This is implemented in the VS Code extension: https://github.com/Dart-Code/Dart-Code/issues/5013

The Dart VS Code extension supports the same for the VM service URI, which we should also consider adding for feature parity.

**Comment by helin24** [comment]
It sounds like this will be mostly developer-facing and could be surfaced by an action. So will it be sufficient to make it accessible from Help > Find action, but we don't add discoverable UI (e.g. a button or menu item)? That seems equivalent to command palette in VS Code.

**Comment by kenzieschmoll** [comment]
Is there a standard place in IntelliJ to put plugin commands / actions like VS Code has? What you described SGTM, but I'm not an expert on IntelliJ affordances. CC @jwren

**Comment by kenzieschmoll** [comment]
This should live in the Dart IntelliJ plugin so that both Dart and Flutter users have access to the action

**Comment by kenzieschmoll** [comment]
![Screenshot 2024-03-22 at 12 16 35 PM](https://github.com/flutter/flutter-intellij/assets/43759233/fac1d246-b0ea-42fb-81e9-3a69b491a579)

**Comment by jwren** [comment]
Fixed in the Dart Plugin, pushed in versions 2023.2.x, 2023.3.x. and 2024.1 IDE versions, on april 5th
