### ISSUE TITLE
Unsupported Android Studio version

### ISSUE THREAD

**Issue by anasshahin** [flutter/flutter-intellij#7244]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by anasshahin** [comment]
[√] Flutter (Channel master, 3.20.0-15.0.pre.1, on Microsoft Windows [Version 10.0.22621.3155], locale en-GB)
    • Flutter version 3.20.0-15.0.pre.1 on channel master at C:\src\flutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b2a3075fa5 (2 days ago), 2024-02-27 08:20:19 -0800
    • Engine revision 0bc21ea7bc
    • Dart version 3.4.0 (build 3.4.0-179.0.dev)
    • DevTools version 2.33.0-dev.11

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\emran\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11446219)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34003.232
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11446219)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\emran\Documents\app study\IntelliJ IDEA Community Edition 2022.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 221.5787.37

[√] VS Code (version 1.86.0)
    • VS Code at C:\Users\emran\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3155]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.189
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.52

[√] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0

**Comment by jwren** [comment]
Closing issue, which version of AS.  We are currently working on getting rolls out for Iguana, Jellyfish and Koala.
