### ISSUE TITLE
re-enable unit testing on the bots

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#726]
Context here: https://github.com/flutter/flutter-intellij/pull/723.

We need to add the ability to reference IntelliJ classes from unit tests (blocked on installing the Dart plugin into the products when testing on the bots).

**Comment by devoncarew** [comment]
Re: installing the Dart plugin into IntelliJ on the bots, we should be able to just unzip it into the plugins folder:

https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

So something like `~/IntelliJIdea2016.3.1/config/plugins`.

**Comment by stevemessick** [comment]
Unit tests have been running on the bots for quite a while.
