### ISSUE TITLE
Support IntelliJ 2024.1

### ISSUE THREAD

**Issue by thoradam** [flutter/flutter-intellij#7269]
IntelliJ 2024.1 has been in EAP since January 18th and went into beta on March 7th.

## Steps to Reproduce

Use this plugin (version 78.3.1) with IntelliJ 2024.1. Plugin screen says:
> Incompatible: requires IDE build 233.* or earlier.

**Comment by jwren** [comment]
Started this work.  Hitting a first issue that the expected POM file key does not exist:

```
 Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.jetbrains.intellij.idea:ideaIC:2024.1.
  Searched in the following locations:
    - file:/Users/jwren/.m2/repository/com/jetbrains/intellij/idea/ideaIC/2024.1/ideaIC-2024.1.pom
    - https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/2024.1/ideaIC-2024.1.pom
    - https://oss.sonatype.org/content/repositories/snapshots/com/jetbrains/intellij/idea/ideaIC/2024.1/ideaIC-2024.1.pom
    - https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2024.1/ideaIC-2024.1.pom
    - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2024.1/ideaIC-2024.1.pom
    - https://repo.maven.apache.org/maven2/com/jetbrains/intellij/idea/ideaIC/2024.1/ideaIC-2024.1.pom
  Required by:
      project :
  
  
  BUILD FAILED in 11s

```

`product-matrix.json` change to date:


```
{
      "channel": "stable",
      "comments": "IntelliJ 2024.1",
      "name": "2024.1",
      "version": "2024.1",
      "isUnitTestTarget": "true",
      "ideaProduct": "ideaIC",
      "ideaVersion": "2024.1",
      "baseVersion": "241.14494.17",
      "androidPluginVersion": "241.14494.17",
      "dartPluginVersion": "241.14768",
      "sinceBuild": "241.14494.17",
      "untilBuild": "241.*"
    }
```

**Comment by jwren** [comment]
Currently waiting for non-EAP version of 2024.1 to be posted https://www.jetbrains.com/intellij-repository/snapshots/.

**Comment by countfloyd** [comment]
It would be so helpful if the flutter plugin was available for EAP releases. I have to switch back and forth between EAP and release versions to use flutter and other languages that work better with EAP.

**Comment by RGarrido03** [comment]
> It would be so helpful if the flutter plugin was available for EAP releases. I have to switch back and forth between EAP and release versions to use flutter and other languages that work better with EAP.

I agree, EAP implicitly comes with potential bugs, and I think us testers are willing to take the risk. It’s not a good experience to switch between versions just because of Flutter.

**Comment by jwren** [comment]
APIs need to migrated, https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/ui/layout/Cell.kt

**Comment by jwren** [comment]
Thank you all for your patience here.

`78.5.1` has been pushed to the marketplace which supports `2024.1`.  https://plugins.jetbrains.com/plugin/9212-flutter/edit/versions/stable/515514

The release also has very recent work done to incorporate a new "Deep Links" tool from DevTools.
