### ISSUE TITLE
Update deprecated JxBrowser link in Flutter JetBrains plugin documentation

### ISSUE THREAD

**Issue by dmytro-kashcheiev** [flutter/flutter-intellij#7271]
The Flutter [JetBrains Plugin documentation](https://plugins.jetbrains.com/plugin/9212-flutter) currently includes a deprecated link to the JxBrowser library. 

This outdated link may lead to confusion and prevent users from accessing the most current compliance information and source code available.

**Current Link**: `https://cloud.teamdev.com/downloads/jxbrowser/7.10/jxbrowser-7.10-relink.zip`

**Suggested Link**: Please replace it with the following updated link to ensure users have access to the correct information regarding LGPL compliance and source code: `https://teamdev.com/jxbrowser/lgpl-compliance/#source-code`.

**Comment by jwren** [comment]
This landed with https://github.com/flutter/flutter-intellij/pull/7289
