### ISSUE TITLE
[!] Your project requires a newer version of the Kotlin Gradle plugin.                          │ │ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then      │ │ update D:\Codings Programming\Flutter Projects\roadbuddy\roadbuddy_center\android\build.gradle: │ │ ext.kotlin_version = '<latest-version>'

### ISSUE THREAD

**Issue by http-rixhi** [flutter/flutter-intellij#7273]
`Thanks` for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by jwren** [comment]
Please reopen with specific versions here.
