### ISSUE TITLE
show analysis issues on app run

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#729]
When running apps, if there are analysis issues, should we increase the visibility of errors. THis could be:

- showing the Dart Analysis view
- opening a toast telling the users about the errors
- stopping the launch?

**Comment by eseidelGoogle** [comment]
Other mobile development contexts (e.g. Xcode or Android Studio) don't even let you run with compile errors (due to constraints of their development languages).  It's kinda neat that Dart does... but might cause confusion for the user.

**Comment by pq** [comment]
Java Run Configurations perform a "build" pre-flight (which includes an error-check):

<img width="744" alt="screen shot 2017-02-14 at 6 12 27 am" src="https://cloud.githubusercontent.com/assets/67586/22932410/ab7f5e9c-f27c-11e6-8cc1-a7ad92387487.png">

<img width="235" alt="screen shot 2017-02-14 at 6 14 52 am" src="https://cloud.githubusercontent.com/assets/67586/22932491/f555d2f8-f27c-11e6-8769-f07144fac79a.png">

we could consider something similar?

**Comment by alexander-doroshko** [comment]
For example, you can proceed with the app launch but show a yellow balloon stuck to the Dart Analysis tool window saying that it contains errors.
We already show such a balloon to attract user attentions when some error is printed to the Pub Serve tool window.

**Comment by devoncarew** [comment]
> you can proceed with the app launch but show a yellow balloon stuck to the Dart Analysis tool window

Sounds like a good solution! Do you have a link to the impl. for the pub server window? And what would the behavior be like if the user was not showing tool buttons?

**Comment by alexander-doroshko** [comment]
> Do you have a link to the impl. for the pub server window?

see `PubServerService#NOTIFICATION_GROUP`

> And what would the behavior be like if the user was not showing tool buttons?

As I remember they are shown anyway while balloon is there

**Comment by devoncarew** [comment]
(hereabouts: https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/pubServer/PubServerService.java#L411)

**Comment by devoncarew** [comment]
The resolution here is:

- show a notification if you run and there are errors
- force open of the Dart Analysis view

We should also show the notification on a reload.

**Comment by devoncarew** [comment]
We need to figure out the right state machine here so that we have a speed-bump if there are analysis issues, but it's not too intrusive to their flow.

**Comment by pq** [comment]
Work ongoing in the Dart Plugin.

**Comment by devoncarew** [comment]
One possible implementation is out for review here: https://github.com/JetBrains/intellij-plugins/pull/491.

**Comment by pq** [comment]
We have a good lead on improved error notification on run.  Not for this Milestone though.

**Comment by devoncarew** [comment]
redux (into the Dart plugin) here: https://github.com/JetBrains/intellij-plugins/pull/519
