### ISSUE TITLE
Can Android Studio automatically execute hot reload after modifying the code? 

### ISSUE THREAD

**Issue by GanZhiXiong** [flutter/flutter-intellij#7309]
I've seen on other sites that VSCode seems to be able to do this.

Automatically executing hot reload will greatly improve coding efficiency.

**Comment by GanZhiXiong** [comment]
https://github.com/Dart-Code/Dart-Code/issues/3110#issuecomment-873599639

VSCode has supported it for a long time. When will Android Studio also support this function? It is too troublesome to press the shortcut key every time to hot reload.

**Comment by jacob314** [comment]
This is supported and I believe enabled by default. See "Perform hot reload on save" under the settings for the Flutter Android Studio plugin.
 
<img width="976" alt="Screenshot 2024-04-08 at 8 25 10 AM" src="https://github.com/flutter/flutter-intellij/assets/1226812/fdabe6ba-646c-4b4c-aa33-5608916cf024">
