### ISSUE TITLE
Deep links tab appears in two places

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#7320]
The deep links page has its own tool window:
![Screenshot 2024-04-04 at 8 21 47 AM](https://github.com/flutter/flutter-intellij/assets/43759233/3b8c5bd5-c50f-49fc-8456-4a449fbe381c)

but it also shows up as a tab in the inspector, which we probably don't want:
![Screenshot 2024-04-04 at 8 18 43 AM](https://github.com/flutter/flutter-intellij/assets/43759233/5fd5a95f-0741-4e07-95d5-30597ffdafb4)

@helin24

**Comment by helin24** [comment]
Fixed by #7325
