### ISSUE TITLE
Cannot open other tool window in top of Deep Links tool window on first try

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#7324]
In this gif, you can see the flash that occurs when I click the Flutter Inspector tool window while the Deep Links tool window is open. The second click works as expected.

![deep-links-flash](https://github.com/flutter/flutter-intellij/assets/43759233/1aa7af06-602a-437e-938e-dbab29a847f7)

@helin24

**Comment by helin24** [comment]
Fixed with https://github.com/flutter/flutter-intellij/pull/7325
