### ISSUE TITLE
change the UX around project creation

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#734]
When we create a new flutter project, the `flutter create` scrolls by, then gets replaced by the Dart Analysis view. Instead, we may want to do something like:

- show `flutter create` progress in a progress job (we shouldn't open a message panel at all; it fights with the analysis view)
- show a toast when the project create is finished

**Comment by mit-mit** [comment]
Could we do the `flutter create` step as a new last page (displaying the output we currently print to the message panel) in the New Project wizard? I find it a little odd that we do so much work after the wizard has closed (leading to a long time after the wizard until the developer can actually start coding).

**Comment by mit-mit** [comment]
While we are at it, can we also reconsider the first page in the wizard that asks for the SDK path every time I create project?

**Comment by devoncarew** [comment]
+1 to both of those ideas!

**Comment by devoncarew** [comment]
Closing as we've done some work here, and have other issues tracking this as.
