### ISSUE TITLE
Flutter Deep Links / Flutter Inspector not loading - JX Browser engine failed to start

### ISSUE THREAD

**Issue by thildebrand1** [flutter/flutter-intellij#7343]
## Steps to Reproduce
It seems since upgrading to IntelliJ 2024.1 my Flutter Deep Links and Flutter Inspector no longer work.

![Screenshot 2024-04-10 at 10 59 47 AM](https://github.com/flutter/flutter-intellij/assets/156224596/a1a45717-0305-4e0c-9db3-94dcbe6d71a4)
![Screenshot 2024-04-10 at 10 59 53 AM](https://github.com/flutter/flutter-intellij/assets/156224596/d27e883c-f769-44b8-a1cf-c558220d941f)

Perhaps related to #5683 and fix #5685?

## Version info

[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-CA)
    • Flutter version 3.19.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.16.7/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (5 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sweetie-pie/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 78.5.1
    • Dart plugin version 241.15845

[✓] Connected device (4 available)
    • iPhone (mobile)            • 00008130-001654E13413803A            • ios            • iOS 17.4.1 21E236
    • iPhone 15 Pro Max (mobile) • E05366EF-E793-4B48-951E-DCA02D9D3FDE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 123.0.6312.107
    ! Error: Browsing on the local area network for Tim’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by helin24** [comment]
Can you go to help > show log in finder and see if there are jx browser errors in idea.log?

**Comment by helin24** [comment]
Hmm would you mind sending me the full file? helinx@google.com

I suspect there could be an earlier error.

**Comment by CrazyCoder** [comment]
This issue was originally reported at https://youtrack.jetbrains.com/issue/IDEA-351402/JX-Browser-engine-failed-to-start and there were errors in `jxbrowser.log`:

```
9:26:57.128 INFO Mac OS X 14.4.1
9:26:57.128 INFO Java 17.0.10  64-bit (aarch64)
9:26:57.128 INFO JxBrowser version: 7.27
9:26:57.128 INFO Chromium version: 102.0.5005.167
9:26:57.128 INFO Temp folder: /var/folders/jb/hdssvyrs3lj4vjz9lq91xnlm0000gp/T
9:26:57.133 DEBUG Creating target directory...
9:26:57.133 DEBUG Acquiring an exclusive lock...
9:26:57.133 DEBUG Verifying Chromium binaries...
9:26:57.134 DEBUG Using ChromiumVerifierMac verifier...
9:26:57.134 DEBUG Verifying /var/folders/jb/hdssvyrs3lj4vjz9lq91xnlm0000gp/T/JxBrowser/7.27/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/102.0.5005.167/Resources/hr.lproj/locale.pak...
9:26:57.134 DEBUG Verifying /var/folders/jb/hdssvyrs3lj4vjz9lq91xnlm0000gp/T/JxBrowser/7.27/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/102.0.5005.167/Resources/hr.lproj/locale.pak... [FAIL] File does not exist
9:26:57.134 DEBUG Verifying Chromium binaries... [FAIL]
9:26:57.134 DEBUG Finding Chromium binaries in JARs...
9:26:57.134 DEBUG Finding chromium-mac-arm.7z...
9:26:57.134 DEBUG Extracting Chromium binaries...
9:26:58.369 INFO 
7-Zip (z) 21.06 (arm64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-11-24
 64-bit arm_v:8 locale=en_US.UTF-8 Threads:10, ASM

Scanning the drive for archives:
1 file, 71750816 bytes (69 MiB)

Extracting archive: /var/folders/jb/hdssvyrs3lj4vjz9lq91xnlm0000gp/T/JxBrowser/7.27/chromium-mac-arm.7z
--
Path = /var/folders/jb/hdssvyrs3lj4vjz9lq91xnlm0000gp/T/JxBrowser/7.27/chromium-mac-arm.7z
Type = 7z
Physical Size = 71750816
Headers Size = 3816
Method = LZMA2:24
Solid = +
Blocks = 1


Sub items Errors: 317

Archives with Errors: 1

Sub items Errors: 317

9:26:58.369 DEBUG ERROR: Cannot set file attribute : errno=1 : Operation not permitted : /var/folders/jb/hdssvyrs3lj4vjz9lq91xnlm0000gp/T/JxBrowser/7.27/Chromium.app
ERROR: Cannot set file attribute : errno=1 : Operation not permitted : /var/folders/jb/hdssvyrs3lj4vjz9lq91xnlm0000gp/T/JxBrowser/7.27/Chromium.app/Contents
ERROR: Cannot set file attribute : errno=1 : Operation not permitted : /var/folders/jb/hdssvyrs3lj4vjz9lq91xnlm0000gp/T/JxBrowser/7.27/Chromium.app/Contents/Frameworks
ERROR: Cannot set file attribute : errno=1 : Operation not permitted : /var/folders/jb/hdssvyrs3lj4vjz9lq91xnlm0000gp/T/JxBrowser/7.27/Chromium.app/Contents/Frameworks/Chromium Framework.framework
...
```

**Comment by helin24** [comment]
Ah I've seen this before as well, but we're not sure what the solution is yet. To fix this temporarily, you can run `rm -rf <path to>/JxBrowser/7.27`.

**Comment by jwren** [comment]
@thildebrand1 Is this still an issue with recent versions of the Flutter plugin and JXBrowser?

**Comment by zonggexu** [comment]
After restarting the computer, it returned to normal.
