### ISSUE TITLE
Exception in Flutter plugin

### ISSUE THREAD

**Issue by sebasrobert** [flutter/flutter-intellij#7346]
## Steps to Reproduce

This exception occurs a lot just doing normal flutter dev. I got ~20 occurrences of this since upgrading to 2024.1. I had to restart intellij a couple of times since the plugin seems to stop parsing code correctly. Errors on half a keyword, etc...

## Version info

❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4 23E214 darwin-arm64, locale en-CA)
    • Flutter version 3.19.5 on channel stable at /Users/sebastienrobert/.asdf/installs/flutter/3.19.5-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (2 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sebastienrobert/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/sebastienrobert/Library/Android/sdk
    • Java binary at: /Users/sebastienrobert/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/sebastienrobert/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /Users/sebastienrobert/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 78.5.1
    • Dart plugin version 241.15845

[✓] VS Code (version 1.88.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone de Sébastien (mobile) • 00008101-0011649C3EB8001E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)              • macos                     • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)                 • chrome                    • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by jwren** [comment]
What is the exception?  Please re-open with additional actionable information.
