### ISSUE TITLE
Breakpoints don't work for the Web

### ISSUE THREAD

**Issue by pavvet** [flutter/flutter-intellij#7351]
I'm not sure if this problem is related to the Android Studio plugin, Flutter itself, or my project.
The error is as follows. 

When I run a project in Chrome in Debug mode, breakpoints are triggered only in the main file. Breakpoints don't work after runApp(). 
But when running Android on the emulator, breakpoints work in the entire project.

I also noticed that when running DevTools, I can't open the project files there, but in the structure I can see them
![image](https://github.com/flutter/flutter-intellij/assets/87531160/01d35575-2588-45c2-80b7-7171c1525cc0)

Flutter plugin version 78.4.1 
Dart plugin version 232.10313

flutter doctor -v
[!] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3447], locale ru-RU)
    • Flutter version 3.19.5 on channel stable at E:\Programms\Flutter\default
    ! Warning: `flutter` on your path resolves to E:\Programms\Flutter\versions\3.19.5\bin\flutter, which is not inside your current Flutter SDK checkout at E:\Programms\Flutter\default. Consider adding E:\Programms\Flutter\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to E:\Programms\Flutter\versions\3.19.5\bin\dart, which is not inside your current Flutter SDK checkout at E:\Programms\Flutter\default. Consider adding E:\Programms\Flutter\default\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (2 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at E:\Programms\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = E:\Programms\Android\Sdk
    • ANDROID_SDK_ROOT = E:\Programms\Android\.android
    • Java binary at: E:\Programms\JetBrains\Toolbox\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.5)
    • Visual Studio at E:\Programms\VisualStudio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    ! Unable to locate a Windows 10 SDK. If building fails, install the Windows 10 SDK in Visual Studio.

[√] Android Studio (version 2023.2)
    • Android Studio at E:\Programms\JetBrains\Toolbox\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.88.1)
    • VS Code at C:\Users\vetly\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.123
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.81

[√] Network resources
    • All expected network resources are available.

**Comment by jacob314** [comment]
Fyi @elliette.
Are you able to set breakpoints using VSCode on Flutter Web?

**Comment by elliette** [comment]
> Fyi @elliette. Are you able to set breakpoints using VSCode on Flutter Web?

Yes, I'm able to set breakpoints in VS Code, so this issue is most likely restricted to intellij
