### ISSUE TITLE
SEVERE: Intellij IDEA Ultimate crashes during editor input

### ISSUE THREAD

**Issue by acheronian** [flutter/flutter-intellij#7354]
Updated to latest plugin version of flutter with newest version of Intellij, random crashes happening after several seconds of trying to code which makes it unusable. Cannot downgrade to previous version without downgrading Intellij IDEA.

Disabling the plugin does not result in crashes.

## Steps to Reproduce

1. Open intellij IDEA
2. Wait for IDEA to complete indexing
3. Try to add code in .dart file
4. Crash

## Version info

Intellij IDEA: Build #IU-241.14494.240
Flutter plugin: 79.0.3

## Intellij Log
[idea.log](https://github.com/flutter/flutter-intellij/files/14995998/idea.log)

EDIT: 

This error message popped up, catched it this time:
![grafik](https://github.com/flutter/flutter-intellij/assets/41775099/2a079c81-377f-4e58-9364-d9e1ca0a8d8d)

**Comment by jwren** [comment]
Looking through the logs I don't have enough information to figure out what is happening.  There is no unknown exception out of the Flutter plugin.  There is not an exception at the end of your logs.  I cannot reproduce using this version of the flutter plugin and Ultimate myself.

Consider changing to an older more stable version of the platform, such as AS 2023.2 Iguana or AS 2023.3 Jellyfish.

**Comment by acheronian** [comment]
Thank you for the quick answer.

After further investigation and downgrading to an earlier version of both intellij and flutter plugin, the issue did not resolve itself, random crashes without warning still happen.
