### ISSUE TITLE
release  0.1.10

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#737]
We should push out the latest (`0.1.10`) release.

**Comment by pq** [comment]
👍 

I'm tempted to tag this before https://github.com/flutter/flutter-intellij/commit/03b5fc417b8f697a46320ba30b9ddbd0b51e1fcd, since that's when we tested.  Does that sound right?

@devoncarew @mit-mit

**Comment by mit-mit** [comment]
Sure. Can you help me with some content for the g+ post?

**Comment by pq** [comment]
To start, here's what we have in the changelog:

* fixes to pubspec timestamp checking
* analytics events for run, debug, and process stop
* fix to `flutter doctor` to better support multiple runs
* fix to the reload action for apps launched from 'run'

**Comment by pq** [comment]
Published.  Awaiting approval. 🤘

**Comment by pq** [comment]
Approved; we're live!
