### ISSUE TITLE
Auto-gen a run config for imported projects with a `lib/main.dart`

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#739]
Opening projects with no IntelliJ metadata is a lot better with the recent fixes. Code analysis works as expected!

However, the project still has no run config, and adding one is a number of steps, incl. having to know some specific paths. Should we consider always adding a run config if there are none?

## Steps to Reproduce

1. Create a new project: `flutter create ijtest`
1. Delete IJ metadata: `cs ijtest; rm ijtest.iml; rm -rf .idea`
1. Open project: `idea .`

-> Project analyses but cannot be run

## Version info

```
Running flutter doctor...
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/mit/dev/github/flutter
    • Framework revision 77e53016f2 (2 hours ago), 2017-02-15 09:27:05
    • Engine revision b64c88766d
    • Tools Dart version 1.22.0-dev.10.6

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/mit/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/mit/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.0

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.9.1
```

**Comment by pq** [comment]
@devoncarew : is it true that the canonical entry-point will (always) be `lib/main.dart`?  If so, any reason we couldn't auto-generated a run config if that file exists?

**Comment by mit-mit** [comment]
Some apps might now have that file (for example /examples/layers/ doesn't), but if that file exists it's pretty likely it's the entry point,.

**Comment by devoncarew** [comment]
Auto-generation if lib/main.dart exists sounds good -

**Comment by mit-mit** [comment]
Tentatively tagging this for next release

**Comment by ajharry69** [comment]
Kindly check @omar1betar answer from here https://github.com/flutter/flutter-intellij/issues/943
