### ISSUE TITLE
duplicate entries in device menu when running two emulators

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#742]
Use "android avd" to create two emulators and launch them both at the same time.

In the device menu, I see two entries, both named "Android SDK built for x86 64". I expected to see the names that I picked in avd when I created these emulators.

Looking at the FlutterDevice class, it appears we display whatever is in myDeviceName, which is populated from the "name" field sent by the "flutter daemon" command. So, getting a useful name back probably requires modifying flutter.

A workaround might be to display myDeviceId if that's necessary to distinguish them. But this isn't so useful either; in this case the ids are "emulator-5554" and "emulator-5556".

**Comment by devoncarew** [comment]
What does `flutter devices` or `adb devices -l` show? I'm wondering if the issue is getting the device names to flutter_tools, or getting the name from flutter_tools to IntelliJ.

**Comment by skybrian** [comment]
```
$ flutter devices
2 connected devices:

Android SDK built for x86 64 • emulator-5556 • android-x64 • Android 7.0 (API 24) (emulator)
Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.0 (API 24) (emulator)
```

```
$ adb devices -l
List of devices attached
emulator-5556          device product:sdk_google_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64
emulator-5554          device product:sdk_google_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64
```

So I guess the best we can do short-term is show the unique id for emulators (if there is more than one).

In the android emulator's title bar, it says:

```
Android Emulator - sample:5554
```

So, the id will help the user figure out which window is which.

**Comment by devoncarew** [comment]
It's probably a good idea for the UI to do some de-duping for identical names. '$name - $id' would probably get a bit long; perhaps just appending an count would be enough? `foo-1`, `foo-2`?

**Comment by skybrian** [comment]
If the id starts with "emulator-" then maybe it should just use the id and ignore the name? I don't think "Android SDK built for x86 64" is very useful anyway.

Alternatively, it could extract the number after "emulator-" and show it as "Android Emulator 5554"

**Comment by stevemessick** [comment]
The names in the device selector are unique now.
