### ISSUE TITLE
A issue about launching on device.

### ISSUE THREAD

**Issue by s2mh** [flutter/flutter-intellij#743]
I can launch my demo from command-line (using `flutter run -d deviceID`), but I can not launch it from IDEA. `flutter devices` tells me that there is only one device connected, but I find 2 devices (with different deviceID) in IDEA’s device menu.

**Comment by s2mh** [comment]
I have changed nothing, `flutter devices` now tells me:
```
2 connected devices:

 • 412a6579010ea728bb7e119cf8bf60451e760cd2 • ios • iOS  ()
 • 700f02e8ef71e8d153e74483d0a6dc186ac4d123 • ios • iOS  ()
```  

`412a6579010ea728bb7e119cf8bf60451e760cd2` is my only device connected with USB cable. I have no idea about `700f02e8ef71e8d153e74483d0a6dc186ac4d123 `.

IDEA still has 2 device selections, both of them can not lauch the demo:

```
2017-02-16 16:07:45.413 ios-deploy[12413:85323] [ !! ] Error 0xe8008015: A valid provisioning profile for this executable was not found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not install build/ios/Release-iphoneos/Runner.app on 700f02e8ef71e8d153e74483d0a6dc186ac4d123.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcodeproj

Error launching application on .
```

**Comment by devoncarew** [comment]
Thanks for the report! Can you run (and include the output for) `flutter device -v` and `flutter doctor`?

**Comment by s2mh** [comment]
yanweichendeMacBook-Pro:FlutterInIDEA yanweichen$ flutter devices -v
[  +22 ms] Unable to locate an Android SDK.
[  +18 ms] Unable to locate an Android SDK.
[  +27 ms] Unable to locate an Android SDK.
[  +10 ms] idevice_id -h
[   +9 ms] which idevice_id
[   +4 ms] Exit code 0 from: which idevice_id
[        ] /usr/local/bin/idevice_id
[        ] /usr/local/bin/idevice_id -l
[   +9 ms] Exit code 0 from: /usr/local/bin/idevice_id -l
[        ] c47207e8de40371cf9568a4a4104cc749d03329e
           412a6579010ea728bb7e119cf8bf60451e760cd2
           700f02e8ef71e8d153e74483d0a6dc186ac4d123
[   +2 ms] which ideviceinfo
[   +4 ms] Exit code 0 from: which ideviceinfo
[        ] /usr/local/bin/ideviceinfo
[        ] /usr/local/bin/ideviceinfo -k DeviceName -u c47207e8de40371cf9568a4a4104cc749d03329e
[  +40 ms] Exit code 255 from: /usr/local/bin/ideviceinfo -k DeviceName -u c47207e8de40371cf9568a4a4104cc749d03329e
[        ] ERROR: Could not connect to lockdownd, error code -13
[   +1 ms] which ideviceinstaller
[   +7 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] which iproxy
[   +5 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[        ] which idevicedebug
[   +5 ms] Exit code 0 from: which idevicedebug
[        ] /usr/local/bin/idevicedebug
[        ] which idevicesyslog
[   +8 ms] Exit code 0 from: which idevicesyslog
[        ] /usr/local/bin/idevicesyslog
[        ] which ios-deploy
[  +10 ms] Exit code 0 from: which ios-deploy
[        ] /usr/local/bin/ios-deploy
[        ] /usr/local/bin/ideviceinfo -k DeviceName -u 412a6579010ea728bb7e119cf8bf60451e760cd2
[ +324 ms] Exit code 255 from: /usr/local/bin/ideviceinfo -k DeviceName -u 412a6579010ea728bb7e119cf8bf60451e760cd2
[   +1 ms] ERROR: Could not connect to lockdownd, error code -21
[        ] /usr/local/bin/ideviceinfo -k DeviceName -u 700f02e8ef71e8d153e74483d0a6dc186ac4d123
[ +429 ms] Exit code 255 from: /usr/local/bin/ideviceinfo -k DeviceName -u 700f02e8ef71e8d153e74483d0a6dc186ac4d123
[        ] ERROR: Could not connect to lockdownd, error code -13
[   +3 ms] /usr/bin/xcrun simctl list --json devices
[  +93 ms] 3 connected devices:
           
[   +1 ms] /usr/local/bin/ideviceinfo -k ProductVersion -u c47207e8de40371cf9568a4a4104cc749d03329e
[  +56 ms] Exit code 255 from: /usr/local/bin/ideviceinfo -k ProductVersion -u c47207e8de40371cf9568a4a4104cc749d03329e
[        ] ERROR: Could not connect to lockdownd, error code -13
[        ] /usr/local/bin/ideviceinfo -k BuildVersion -u c47207e8de40371cf9568a4a4104cc749d03329e
[  +71 ms] Exit code 255 from: /usr/local/bin/ideviceinfo -k BuildVersion -u c47207e8de40371cf9568a4a4104cc749d03329e
[        ] ERROR: Could not connect to lockdownd, error code -13
[        ] /usr/local/bin/ideviceinfo -k ProductVersion -u 412a6579010ea728bb7e119cf8bf60451e760cd2
[ +414 ms] Exit code 255 from: /usr/local/bin/ideviceinfo -k ProductVersion -u 412a6579010ea728bb7e119cf8bf60451e760cd2
[        ] ERROR: Could not connect to lockdownd, error code -21
[        ] /usr/local/bin/ideviceinfo -k BuildVersion -u 412a6579010ea728bb7e119cf8bf60451e760cd2
[ +688 ms] Exit code 255 from: /usr/local/bin/ideviceinfo -k BuildVersion -u 412a6579010ea728bb7e119cf8bf60451e760cd2
[        ] ERROR: Could not connect to lockdownd, error code -21
[        ] /usr/local/bin/ideviceinfo -k ProductVersion -u 700f02e8ef71e8d153e74483d0a6dc186ac4d123
[ +181 ms] Exit code 255 from: /usr/local/bin/ideviceinfo -k ProductVersion -u 700f02e8ef71e8d153e74483d0a6dc186ac4d123
[        ] ERROR: Could not connect to lockdownd, error code -13
[        ] /usr/local/bin/ideviceinfo -k BuildVersion -u 700f02e8ef71e8d153e74483d0a6dc186ac4d123
[  +33 ms] Exit code 255 from: /usr/local/bin/ideviceinfo -k BuildVersion -u 700f02e8ef71e8d153e74483d0a6dc186ac4d123
[        ] ERROR: Could not connect to lockdownd, error code -13
[   +2 ms]  • c47207e8de40371cf9568a4a4104cc749d03329e • ios • iOS  ()
[        ]  • 412a6579010ea728bb7e119cf8bf60451e760cd2 • ios • iOS  ()
[        ]  • 700f02e8ef71e8d153e74483d0a6dc186ac4d123 • ios • iOS  ()
[        ] 'flutter devices' took 2471ms.
[   +4 ms] exiting with code 0

**Comment by s2mh** [comment]
yanweichendeMacBook-Pro:FlutterInIDEA yanweichen$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/yanweichen/private/github/flutter
    • Framework revision 77e53016f2 (24 hours ago), 2017-02-15 09:27:05
    • Engine revision b64c88766d
    • Tools Dart version 1.22.0-dev.10.6

[✗] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    x libimobiledevice is incompatible with the installed Xcode version. To update, run:
      brew uninstall libimobiledevice
      brew install --HEAD libimobiledevice

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.9.1

[✗] Cannot determine if IntelliJ is installed
    x Directory listing failed

[✓] Connected devices
    •  • c47207e8de40371cf9568a4a4104cc749d03329e • ios • iOS  ()
    •  • 412a6579010ea728bb7e119cf8bf60451e760cd2 • ios • iOS  ()
    •  • 700f02e8ef71e8d153e74483d0a6dc186ac4d123 • ios • iOS  ()

**Comment by devoncarew** [comment]
I think that libimobiledevice error above is the issue. Can you uninstall and reinstall? There are some instructions in-line above.

**Comment by s2mh** [comment]
After running 3 commands:
```
brew uninstall libimobiledevice
brew uninstall --ignore-dependencies libimobiledevice
brew install --HEAD libimobiledevice
```

```
yanweichendeMacBook-Pro:FlutterInIDEA yanweichen$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/yanweichen/private/github/flutter
    • Framework revision 77e53016f2 (24 hours ago), 2017-02-15 09:27:05
    • Engine revision b64c88766d
    • Tools Dart version 1.22.0-dev.10.6

[✗] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.9.1

[✗] Cannot determine if IntelliJ is installed
    x Directory listing failed

[✓] Connected devices
    • “Administrator”的 iPhone (3) • 412a6579010ea728bb7e119cf8bf60451e760cd2 • ios • iOS 10.2.1 (14D27)
    • iphone5Ca                   • 700f02e8ef71e8d153e74483d0a6dc186ac4d123 • ios • iOS 10.1.1 (14B100)
```

` • iphone5Ca                   • 700f02e8ef71e8d153e74483d0a6dc186ac4d123 • ios • iOS 10.1.1 ` may be  connected before

**Comment by s2mh** [comment]
IDEA flutter plugin shows the same devices now.

**Comment by devoncarew** [comment]
OK, looks resolved? You can list devices correctly now.

@cbracken, @chinmaygarde, the failure mode for listing iOS devices w/ a broken libimobiledevice isn't great - the device list is failure broken:

```
    •  • c47207e8de40371cf9568a4a4104cc749d03329e • ios • iOS  ()
    •  • 412a6579010ea728bb7e119cf8bf60451e760cd2 • ios • iOS  ()
    •  • 700f02e8ef71e8d153e74483d0a6dc186ac4d123 • ios • iOS  ()
```

and we don't mention the issues w/ the libimobiledevice install.
