### ISSUE TITLE
can't create new project in PyCharm

### ISSUE THREAD

**Issue by xufuzhi** [flutter/flutter-intellij#7438]
## Steps to Reproduce

pycharm
file -> new project, no flutter option.
![QQ截图20240517200715](https://github.com/flutter/flutter-intellij/assets/58159882/3c7a74a9-0ed7-4b23-bfaa-1f1d47ec80f9)

## Version info

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [版本 10.0.19045.4412], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X cmdline-tools component is missing                                     
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`              
      See https://developer.android.com/studio/command-line for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.3)
[√] Connected device (3 available)
[!] Network resources                   
    X A network error occurred while checking "https://maven.google.com/": 信号灯超时时间已到

    X An HTTP error occurred while checking "https://github.com/": Connection closed before full header was received

! Doctor found issues in 3 categories.

**Comment by jwren** [comment]
Unfortunately, this is working as intended, we roll versions of the Flutter IJ plugin only for Android Studio, Ultimate and Community versions of the IDEA platform.
