### ISSUE TITLE
Remove iOS languages from new project creation

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter-intellij#7439]
## Steps to Reproduce

The flutter tool will be removing the option to create a new Flutter app using Objective-C with `flutter create --ios-language`
https://github.com/flutter/flutter/issues/148586

Remove "iOS languages" from the project creation wizard, and stop passing in the `--ios-language` flag
![Screenshot 2024-05-17 at 3 52 20 PM](https://github.com/flutter/flutter-intellij/assets/682784/7618c711-3e9d-4494-98b3-629eb59048de)

https://github.com/flutter/flutter-intellij/blob/9536817e680a91ce1e7c738420f098a87839f9f6/flutter-idea/src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java#L83-L84

https://github.com/flutter/flutter-intellij/blob/9536817e680a91ce1e7c738420f098a87839f9f6/flutter-idea/src/io/flutter/sdk/FlutterCreateAdditionalSettings.java#L137-L140

**Comment by jwren** [comment]
Thanks @jmagman for creating this issue.

My first natural question here is if we want a similar decision for Android.  @reidbaker

**Comment by jwren** [comment]
Thanks @reidbaker, not maintenance burden, just wanted the question asked since it felt natural.

**Comment by jwren** [comment]
@jmagman  PR is put together, but do keep in mind that users do use old versions of the Flutter IJ plugin, it would be wise to not crash if the flag is passed in the future.  (Perhaps just ignore the setting and display a warning on the CLI.)

@DanTup, are these flags passed anywhere from the VS Code plugin?

**Comment by DanTup** [comment]
Thanks for the ping - yes, VS Code uses this and we should probably not remove it before it's been gone from the plugins for at least for a little while. I'll add a note to the flutter/flutter issue.

**Comment by jmagman** [comment]
@DanTup Apologies for not filing an issue directly, I didn't spot it being used in the VS Code UI but I must have missed it, I should have grepped the repo.

**Comment by DanTup** [comment]
@jmagman np! Feel free to just ping me if it's easier than grepping or trying to understand the details (with things like LSP, DAP and DTD, it's also often the case that all the code isn't in the extension repo, so even a grep might not give the whole picture).
