### ISSUE TITLE
Run button is disabled after importing project

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#744]
Steps:

* Import new project from existing sources
* Open lib/main.dart
* Enable Dart
* Enable the Flutter mode

Expected:

* The Run button is green and I can click it.

Actual:

* It appears that the Run button is disabled.

![screen shot 2017-02-16 at 4 12 28 pm](https://cloud.githubusercontent.com/assets/5479/23047185/fe8a4d3a-f462-11e6-9dea-207d584374c0.png)

**Comment by devoncarew** [comment]
How was this project created? From `flutter create`? It looks like there are no launch configurations; flutter create will create one when building the project.

We should in any case create a launch configuration when importing an existing project. I think that's tracked here: https://github.com/flutter/flutter-intellij/issues/739.

**Comment by sethladd** [comment]
From `flutter create` right before the holiday break. I believe IntelliJ said "do you want to overwrite <some file required by IntelliJ>" which I said Yes because I assumed the version of that file was old.

maybe the necessary file wasn't replaced?

Probably fixing #739 would be sufficient. I think my particular case is going to be rare.

Thanks for taking a look! I'll close this because it sounds like for a new user, you expect this to work.

**Comment by devoncarew** [comment]
> From flutter create right before the holiday break.

We've since started creating launch configs with new projects, but the other issue would have caught this case.

**Comment by sri-nandhan123** [comment]
dont think too much just cpy and paste in new project
