### ISSUE TITLE
When I Hit a breakpoint it opens on another tab

### ISSUE THREAD

**Issue by gabriel-primesw** [flutter/flutter-intellij#7449]
Whenever i hit a breakpoint  it open the file in another tab, without any syntax and also without the breakpoints i've setted before.
It happened after i updated the flutter plugin to 79.0.2 on android studio and ij ultimate
![image](https://github.com/flutter/flutter-intellij/assets/116582652/f8b773bf-f419-472f-b91c-ebc761d03dff)
![image](https://github.com/flutter/flutter-intellij/assets/116582652/588e3d3a-e3c6-4ed2-a7f6-b2688e402340)

**Comment by alexander-doroshko** [comment]
Until the Flutter plugin build with the fix is available, the workaround is to downgrade the Dart plugin to the previous version. Depending on the IDE version it is one of these:
- [241.15845](https://plugins.jetbrains.com/plugin/6351-dart/edit/versions/stable/518124)
- [233.15123](https://plugins.jetbrains.com/plugin/6351-dart/edit/versions/stable/517946)
- [232.10313](https://plugins.jetbrains.com/plugin/6351-dart/edit/versions/stable/517944)

**Comment by alexander-doroshko** [comment]
@gabriel-primesw The issue is not yet fixed, let's keep it open :).

**Comment by gabriel-primesw** [comment]
> @gabriel-primesw The issue is not yet fixed, let's keep it open :).

allright, thank you!

**Comment by jwren** [comment]
Thanks @gabriel-primesw working on getting this resolved and pushed with a point release soon.

**Comment by gabriel-primesw** [comment]
> Thanks @gabriel-primesw working on getting this resolved and pushed with a point release soon.

Thanks Mr. Wren!

**Comment by jwren** [comment]
Re-opening, just mentioned in the closed PR, this is not yet fixed.

**Comment by codelovercc** [comment]
I'm still facing this issue.

Android Studio Koala | 2024.1.1
Dart plugin version 241.17502
Flutter plugin version 80.0.2

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by Nacho-Larreta** [comment]
@jwren I don't know if helps but to make work all again even the outline that it doesn't work too I had to downgrade to Dart Plugin to 241.15845 and Flutter Plugin to 78.5.1

**Comment by therybrian** [comment]
Issue has resurfaced with 
Dart plugin 242.22855.32
Flutter plugin 82.1.3
Android Studio Ladybug 2023.2.1 Patch 2

**Comment by therybrian** [comment]
New info, apparently a fellow developer named a folder with 2 words with a space in between instead of a underscore (ex. 'home new'). This was the cause for another tab opening that was non writable .
