### ISSUE TITLE
Debug mode opens new duplicate file in read only mode

### ISSUE THREAD

**Issue by khushal-chothani** [flutter/flutter-intellij#7477]
After updating new version i was facing issue in debug mode
while we put some debug breakpoint on suppose file A.dart 
 then it open in side tab same file A.dart but in read only mode 
 
 I'm not sure what settings might have changed

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.1.2 23B92 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.87.2)
[✓] Connected device (4 available)
[!] Network resources
    ✗ A network error occurred while checking "https://github.com/": Failed host lookup: 'github.com'

**Comment by aswanath** [comment]
@khushal-chothani  I am also facing the same issue from yesterday as I upgraded Android studio to Jellyfish and I haven't changed any other settings also..

**Comment by alexander-doroshko** [comment]
Duplicate of #7449. See a workaround in the first comment there or wait for the Flutter plugin update.

**Comment by aswanath** [comment]
I have just downgraded Android studio to Iguana and it is working fine. I think this will be the better workaround until android studio fixes the issue in the Jellyfish.

**Comment by khushal-chothani** [comment]
> @khushal-chothani I am also facing the same issue from yesterday as I upgraded Android studio to Jellyfish and I haven't changed any other settings also..

I think it resolved now after flutter plugin new update

**Comment by khushal-chothani** [comment]
Issue resolved after new plugin update
Thanks flutter team.
