### ISSUE TITLE
re-consider how we define flutterness for a module

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#748]
Several times I've run into a situation where I open a flutter project/module in a copy of IntelliJ that has the Dart plugin installed but not the Flutter plugin. IntelliJ displays an error message about not understanding the module type.

I think we want the Flutter modules to be a slightly different flavor of Dart modules, not an entirely different module type. So, the Dart plugin could work with Flutter modules just fine, even in the absence of the Flutter plugin. Having the Flutter plugin installed would give you additional capabilities, above and beyond just static analysis, refactorings, ... available from the Dart plugin.

**Comment by skybrian** [comment]
Sounds good in principle. For Bazel, we don't use the Flutter module type at all.

Do we gain anything from it in pub-based projects? (Seems like we just need to cache what we learned from pubspec.yaml?)

**Comment by pq** [comment]
Early on we had some conversations about [facets](https://www.jetbrains.com/help/idea/2016.2/facet.html), which on the surface look promising.  Curious what @alexander-doroshko thinks?

**Comment by alexander-doroshko** [comment]
There are no facets in Small IDEs.

**Comment by pq** [comment]
Ah!  Well that explains why we didn't push harder. Any thoughts on @devoncarew's question?

**Comment by alexander-doroshko** [comment]
`[Dart support enabled for the module] === [The module has an order entry pointing to a 'Dart SDK' project-level library that in its turn contains valid Dart SDK roots]`.

So one option is to try to extend this rule:
`[Flutter support enabled for a module] === [Dart support enabled + referenced Dart SDK is the one inside a Flutter SDK]`. An obvious downside is that it will be impossible to create a regular Dart project without downloading a separate standalone Dart SDK.

Another thought is Module's setOption/getOptionValue. Module options are serialized in IMLs. I didn't play much with them.

Any other way to detect that the given Dart module is also a Flutter one could be considered as well.

**Comment by pq** [comment]
Cool.  Thanks for the ideas!

**Comment by devoncarew** [comment]
> Also it will be impossible to have both Flutter and Dart modules within one IntelliJ IDEA project.

I don't understand this one. If the two modules had different values for their Dart SDK, one pointed to a non-flutter dart and one to a flutter dart sdk, wouldn't re recognize the first module as a Dart one, and the 2nd as a Dart+Flutter one?

**Comment by skybrian** [comment]
As I understand it, Dart SDK's will soon be per-project, not per-module. We aren't planning to switch this to per-module, are we?

**Comment by skybrian** [comment]
Ideally the user shouldn't have to do anything and we should autodetect this without having a Flutter module type. We could still detect this per-module, but the module type can go away entirely.

For pub packages, I see there is a flutter constraint [1] but I don't know if it's required.

Are there other non-IDEA files we can look at? I suppose we could look at lib/main.dart to detect this.

[1] https://www.dartlang.org/tools/pub/pubspec#flutter-sdk-constraints

**Comment by alexander-doroshko** [comment]
> Dart SDK's will soon be per-project, not per-module

Yes, that's the answer, thanks!
will soon be -> already for a long time in 2017.1 EAP :)

> Ideally the user shouldn't have to do anything and we should autodetect this

👍

**Comment by pq** [comment]
fyi @jwren

**Comment by jwren** [comment]
The current plan here is to follow @alexander-doroshko's advice above (March 13th) and have a Flutter module be determined by the following:

`[Flutter support enabled for a module] === [Dart support enabled + referenced Dart SDK is the one inside a Flutter SDK]`.

Start of work is here: https://github.com/jwren/flutter-intellij/tree/rm-module-type

**Comment by alexander-doroshko** [comment]
How do you rate the downsides? Especially the 2nd one that has no workaround.

>An obvious downside is that it will be impossible to disable flutterness for a regular Dart project without downloading a separate standalone Dart SDK. Also, it will be impossible to have both Flutter and Dart modules within one IntelliJ IDEA project.

**Comment by skybrian** [comment]
It seems like checking the pubspec file for a flutter dependency would be pretty reasonable?

**Comment by jwren** [comment]
Resolved in master branch now with https://github.com/flutter/flutter-intellij/pull/1213
