### ISSUE TITLE
Flutter plugin config requires user to locate the Dart SDK

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#750]
During a getting started with Flutter study, the participant needed to configure the Flutter Plugin to provide it with the Dart SDK path.

However in following the instructions the participant had run flutter doctor which had installed dart for them. So at the point where they were asked for the Dart-SDK path, they hadn't really heard of Dart, and had no idea where the SDK had been installed. They didn't successfully locate it without an intervention.

They had expected the plugin to be 'more like the Python plugin' that searches for possible SDKs and offers you a choice of which one to use.

**Comment by devoncarew** [comment]
Totally agree that this experience should be more on the rails.

> the participant needed to configure the Flutter Plugin to provide it with the Dart SDK path

Were they following some docs for this? We should update such to talk about the Flutter SDK instead. In an older process, they did need to point the flutter plugin to the dart sdk.

**Comment by lukechurch** [comment]
Thanks @devoncarew 

They started with the Flutter install doc, but just decided it meant that this meant they needed the 'Flutter' and 'Dart' plugins and went to add those. 

Ah, after looking in more detail at the video, I see that IntelliJ complained that they needed to configure both the Dart and Flutter plugins, they selected the *dart* plugin to configure first. After doing that both warnings went away - so it's possible that this is really a bug for the Dart Plugin to IntelliJ rather than the Flutter plugin.
However, the 'where is the SDK' conceptual problem still occurs.

Sorry for the misfiling, is there somewhere you would like me to move this to?

**Comment by mit-mit** [comment]
@lukechurch can you share a screenshot? I am not sure what error message that might be -- you should only need to enter the Flutter SDK path.

**Comment by lukechurch** [comment]
@mit-mit 

![image](https://cloud.githubusercontent.com/assets/2978182/24173829/a849f1b8-0e85-11e7-946f-a95cd503b7ed.png)

**Comment by pq** [comment]
This flow has changed enough that I think this report is stale.  (I'm sure we're not out of the woods w/ the UX yet but we can open issues against the current flow as they arise.)
