### ISSUE TITLE
Run test gutter icons no longer showing 

### ISSUE THREAD

**Issue by alexander-doroshko** [flutter/flutter-intellij#7505]
(originally filed as https://youtrack.jetbrains.com/issue/IDEA-354564, but this needs to be fixed in the Flutter plugin)

After updating the Dart plugin to 241.17502, the Run gutter icons for tests and test groups are no longer shown. Only the main method run icon is showing.

Downgrading to version 241.15989.9 fixes the issue and the icons show again.

See attached screenshots:
![image](https://github.com/flutter/flutter-intellij/assets/4499789/4bee5965-36b3-4fe7-b916-a957bf855783)
![image](https://github.com/flutter/flutter-intellij/assets/4499789/492d9947-1436-41bc-9ad0-675f5bbf6761)
![image](https://github.com/flutter/flutter-intellij/assets/4499789/af90818f-7431-4721-9c85-84d1c5830850)
![image](https://github.com/flutter/flutter-intellij/assets/4499789/446d3f12-12a4-48ee-9e5a-2c0d0a1e095b)

**Comment by josh-burton** [comment]
I'm the original author of the bug. Happy to provide any more info that is required.

**Comment by bobekos** [comment]
Same error here on my configuration:
Android Studio Koala | 2024.1.1 RC 2
Build #AI-241.15989.150.2411.11932844, built on June 6, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11609105 x86_64

Flutter and Dart plugins:
  Dart (241.17502)
  io.flutter (80.0.2)
