### ISSUE TITLE
re-examine our hot reload keybinding

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#751]
Keybindings in IntelliJ are a bit of a land-mine - many common ones are already taken and the less common ones require hard to remember key-mashing.

We're using `cmd-\` and `cmd-option-;` (with `shift` for the full restart versions). We could look into re-using the run and debug keybindings. This would likely be implemented by intercepting a request to run a new app, and instead issuing a request to reload an existing session.

**Comment by mit-mit** [comment]
Suggestion: `ctrl-u` (as in *u*pdate) for hot reload, and `ctrl-shift-u` for restart.

**Comment by mit-mit** [comment]
@devoncarew any thoughts on that suggestion?

**Comment by devoncarew** [comment]
From a quick look, ctrl-u will conflict w/ something (which we could chose to be ok with), ctrl-shift-u will not. But my initial comment for this issue was that we could use the ctrl-d (debug) or ctrl-r (run) as is - we wouldn't have to have a separate keybinding for a reload. That's what I'd like to investigate :)

**Comment by mit-mit** [comment]
Phil to experiment with u just to see what it feels like.

**Comment by pq** [comment]
Quick experiment w/

        <keyboard-shortcut keymap="$default" first-keystroke="ctrl u"/>

for reload, the pre-existing mapping (navigate to super method) wins.

That said, looking at their docs even these semantics are not guaranteed.

> Although you can ignore conflict and bind a shortcut with several actions, it is strictly recommended to avoid binding two actions with the same shortcut, because the order of performing such actions is not defined.

(From the [configuring key bindings docs](https://www.jetbrains.com/help/idea/2016.3/configuring-keyboard-shortcuts.html).)

Net-net: I think we need to find non-conflicting mappings. 😞 

cc @mit-mit

**Comment by mit-mit** [comment]
Got it, punting to 0.1.12 where we can look into Devons ctrl-d/-r suggestion.

**Comment by devoncarew** [comment]
I think we can close this now that we have reload on save.
