### ISSUE TITLE
Context action is disappeared in v80

### ISSUE THREAD

**Issue by adamglin0** [flutter/flutter-intellij#7526]
## Steps to Reproduce

1. install IntelliJ IDEA Community (version 2024.1.2)
2. install Flutter plugin (version 80.0.2)
3. click opt+enter shortcut 
4. or right click Widget,and select show context action.
<img width="386" alt="image" src="https://github.com/flutter/flutter-intellij/assets/149357973/b3f891a9-e6f0-4672-9ced-88694c5779bf">

## Version info

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64 (Rosetta),
    locale zh-Hans-CN)
    • Flutter version 3.22.2 on channel stable at
      /Users/adamglin/.version-fox/cache/flutter/v-3.22.2/flutter-3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (8 天前), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/adamglin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Users/adamglin/Applications/Android Studio Koala Feature
      Drop 2024.1.2 Nightly.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/adamglin/Applications/Android Studio Koala 2024.1.1
      RC 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/adamglin/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Community Edition (version 2024.1.2)
    • IntelliJ at /Users/adamglin/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17502

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 14.5 23F79 darwin-arm64 (Rosetta)
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 14.5 23F79 darwin-arm64 (Rosetta)
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 125.0.6422.176

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by adamglin0** [comment]
after restart several times, context actions works again.

**Comment by adamglin0** [comment]
If cursor is in the front of Widget name, it works.
<img width="161" alt="image" src="https://github.com/flutter/flutter-intellij/assets/149357973/f68d9ef9-2c39-4199-ab2d-5ecc62126165">
<img width="230" alt="image" src="https://github.com/flutter/flutter-intellij/assets/149357973/f165d581-2c6d-4246-b569-4da0fa748749">



IF NOT
<img width="321" alt="image" src="https://github.com/flutter/flutter-intellij/assets/149357973/38769ebc-9d3a-46cf-9674-99a7e39c3cb1">

**Comment by hbock-42** [comment]
I have describe the problem accurately here https://youtrack.jetbrains.com/issue/MP-6657/Context-action-only-work-at-then-end-of-string
I'll copy past but to sum up -> 
- context actions DOES NOT work if the caret is between the first and last letters. ✅
- context actions WORK if the caret is not between the first and last letters. 🚫

**Comment by jwren** [comment]
Thanks @hbock-42

**Comment by tfitzke** [comment]
Why was this closed? Was this problem somehow solved?
