### ISSUE TITLE
Android emulator doesn't disappear from device menu when shut down

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#754]
The problem seems to be that 'flutter daemon' reports an inconsistent 'platform' field when starting up versus shutting down.

In the debugger, when a device is added, I see:
```
id: emulator-5554
name: Android SDK built for x86 64
platform: android-x64
```

On shutdown, the "id" and "name" fields are the same, but platform is incorrectly reported as:
```
platform:  android-arm
```

This seems like a bug in 'flutter daemon'. However, we can also fix it in the Flutter plugin by just comparing device entries using the id.

**Comment by eseidelGoogle** [comment]
Sorry, read these in the wrong order.  Please file with https://github.com/flutter/flutter/issues/new as well and we're happy to fix. :)  Or @devoncarew might just know where already (given how much of flutter_tools he wrote).
