### ISSUE TITLE
Not compatible with the version of your running IDE (Rider 2024.1.4, IntelliJ IDEA 2024.2 EAP)

### ISSUE THREAD

**Issue by AlaJaber97** [flutter/flutter-intellij#7543]
![image](https://github.com/flutter/flutter-intellij/assets/40597191/396e6ade-737c-40b7-90f9-0cc038684e0d)

**Comment by jwren** [comment]
Rider is not currently supported by the Flutter IJ plugin.  Community and Ultimate 2024.2 will be available in future Flutter IJ rolls.

**Comment by 20156284** [comment]
How about now?
![WX20240807-165126@2x](https://github.com/user-attachments/assets/d13c599d-19dc-4f6d-bf99-41d8a5ec7418)

**Comment by SnoozeFreddo** [comment]
+1

**Comment by dodger82** [comment]
+1 intelliJ 2024.2 !
