### ISSUE TITLE
The Flutter Inspector toggle select widget mode works the first time, but it does not work the second time.

### ISSUE THREAD

**Issue by Hactieuho** [flutter/flutter-intellij#7545]
The Flutter Inspector toggle select widget mode works the first time, but it does not work the second time.

## Version info

Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    • Framework revision 5dcb86f68f (8 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

Android Studio Jellyfish | 2023.3.1
Build #AI-233.14808.21.2331.11709847, built on April 13, 2024
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.ankit.mahadik.json.dart.class (2.16)
  Dart (233.15271)
  net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
  com.tao.getx (3.3.2)
  com.mistamek.drawablepreview.drawable-preview (1.1.6)
  org.sonarlint.idea (10.6.2.78685)
  io.flutter (80.0.1)

**Comment by jwren** [comment]
I was not able to reproduce on my Mac. I first launched the counter app to the web and then to a Pixel 7, in both cases I had access to the Flutter Inspector in the Flutter IJ plugin.
