### ISSUE TITLE
When expand a variable at a breakpoint, cannot view the specific property value of the variable.

### ISSUE THREAD

**Issue by jiangkang** [flutter/flutter-intellij#7553]
## Steps to Reproduce

<img width="1492" alt="image" src="https://github.com/flutter/flutter-intellij/assets/12570868/44db2289-c5d5-456c-82df-97a1c5e0b31e">

When the breakpoint is reached, the variable cannot be expanded to view specific information。

## Version info

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    35.0.0-rc3)
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)
[✓] Network resources

```

Flutter Plugin version: 80.0.2
Dart Plugin version: 24.1.17502

**Comment by emodeqidao** [comment]
I also encountered this problem

**Comment by thermoworker** [comment]
+1

**Comment by Bruce-7** [comment]
+1

**Comment by Bruce-7** [comment]
> +1

Android Studio Koala | 2024.1.1 Patch 1
Build #AI-241.18034.62.2411.12071903, built on July 11, 2024
macOS 14.2.1

Plugins:
  Dart (241.18808)
  io.flutter (80.0.2)

**Comment by w467364316** [comment]
Since I upgraded Android Studio to 2024.1.1 and reinstalled the Flutter and Dart plugins, I've been able to see the values of variables at breakpoints. Maybe you can try reinstalling Studio or the Flutter and Dart plugins.

**Comment by jiangkang** [comment]
> Since I upgraded Android Studio to 2024.1.1 and reinstalled the Flutter and Dart plugins, I've been able to see the values of variables at breakpoints. Maybe you can try reinstalling Studio or the Flutter and Dart plugins.

it still doesn't work

**Comment by jiangkang** [comment]
Is there a plan to fix this bug?

**Comment by lugeek** [comment]
Is anyone solved this?

**Comment by lugeek** [comment]
+1 +1 +1

**Comment by jwren** [comment]
With new and recent versions of Flutter, i.e. `3.22.2`, I cannot reproduce this issue.

With older versions it is reproducible.  I would recommend upgrading your Flutter SDK to resolve this issue, or to use an older Android Studio and Flutter IJ plugins until you can upgrade.

Do let me know if this issue is encountered with recent SDK versions.
