### ISSUE TITLE
cant able to find editing in android studio

### ISSUE THREAD

**Issue by shubhammaloo0** [flutter/flutter-intellij#7565]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by jwren** [comment]
The "Open in Android Studio" action was removed due to changing Android Studio APIs.  The larger arc of work here is a work in progress for the Flutter IJ project.
