### ISSUE TITLE
Dev Channel is not updated. Documentation states that it is.

### ISSUE THREAD

**Issue by wispborne** [flutter/flutter-intellij#7582]
## Steps to Reproduce

1. Navigate to https://github.com/flutter/flutter-intellij/blob/master/docs/Dev-Channel.md in a web browser.
1. Follow the instructions.
1. Note that there is no updated plugin.

Additionally, you may navigate to and download https://plugins.jetbrains.com/plugins/list?channel=dev&pluginId=9212-flutter.
The most recent dev version is 72, over 7 months ago.
The most recent stable version is 80.

Request: Fix dev builds or remove the documentation about dev builds.

**Comment by helin24** [comment]
This should be fixed after https://github.com/flutter/flutter-intellij/pull/7610

Let me know if you have any issues with the dev builds from there.
