### ISSUE TITLE
No run button on individual testWidget on Android Studio

### ISSUE THREAD

**Issue by huycozy** [flutter/flutter-intellij#7591]
## Steps to Reproduce

Given that I have many `testWidgets` inside `main()` on a test file. I remember it was able to run testWidget individually by clicking on a run button on the left panel of the corresponding testWidget line (this screenshot is from https://github.com/flutter/flutter-intellij/issues/5852, the run button was showing beside testWidget as desired):

![140378115-67de2632-6834-44a1-943d-2562aca0a2b6](https://github.com/user-attachments/assets/7fae2244-987c-4a56-ab6d-88f1df22eee8)

But currently that run button is missing on my Android Studio IDE:

![Screenshot 2024-08-03 at 23 03 25](https://github.com/user-attachments/assets/1973ce46-6a3e-4169-a3b1-157b0637b489)

I tried putting all tests into a group but the run button didn't appear as well:

![Screenshot 2024-08-03 at 23 16 43](https://github.com/user-attachments/assets/57cbf975-916e-4712-b878-cd19926ddadb)

So I have to run all test cases on the file by clicking on run button from `main()`. Is this a regression issue or is it removed intentionally?

## Version info

Flutter plugin version: 80.0.1
Dart plugin version: 233.15271

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6 23G80 darwin-x64, locale en-VN)
    • Flutter version 3.22.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (2 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.6 23G80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by tuinui** [comment]
@huycozy  This issue will be solved in plugin version 81

**Comment by huycozy** [comment]
@tuinui Yeah, it's back. Thanks!

 ![Screenshot 2024-08-08 at 10 28 22](https://github.com/user-attachments/assets/d86113e8-f163-4ca1-91b4-b63fc528a6d7)
