### ISSUE TITLE
Not compatible with the version of your running IDE Build #IU-242.20224.300, built on August 7, 2024

### ISSUE THREAD

**Issue by 20156284** [flutter/flutter-intellij#7595]
![Uploading WX20240807-165126@2x.png…]()

**Comment by westito** [comment]
Same here. It's actually an IntelliJ bug/missing feature I think. However Flutter team should release a compatible plugin before the a new IntelliJ version released. 

Please comment to make it priority: https://youtrack.jetbrains.com/issue/IDEA-357261/IntelliJ-automatically-install-update-without-ensure-all-plugins-have-compatible-version

There is an older issue (3 years old!!) with this problem but JetBrains doesn't deal with it.

**Comment by dodger82** [comment]
Plugin not available for IDEA 2024.2.

**Comment by mitsh** [comment]
same here

**Comment by bcihanc** [comment]
2024.2 includes many improvements. We are looking forward to.

**Comment by cosminm-affnd** [comment]
Same here

**Comment by chardinson** [comment]
Message error:

> Plugin 'Flutter' (version '81.0.2') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is IC-242.20224.300

**Comment by 0xJAS** [comment]
Same here

**Comment by cavar** [comment]
Same here

**Comment by Apokalypser** [comment]
Same here

**Comment by Frodonche** [comment]
Same here

**Comment by synstin** [comment]
Same here

**Comment by endruszeit** [comment]
Same here

**Comment by bbapplications** [comment]
Same here

**Comment by RafaelFontes** [comment]
+1

**Comment by jwren** [comment]
Thank you all for the comments and +1's.  Yes, this roll does not yet include support for `2024.2`. The Flutter plugin builds have been more robust in recent quarters when compiled directly against the Android Studio IDE, which we cannot yet be built against yet.

While this page, https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html, indicates that Android Studio Ladybug 2024.2.1.1 was available to download starting this past Monday (August 6th, 2024), when I try to validate the Flutter IJ sources against this version of Android Studio with Gradle to do a build (even today, August 8th, 2024), I am still seeing the following:

```
verifyPluginConfiguration for BuildSpec(android-studio 2024.2.1.1 242.20629 242.20629 242.* version: "null"):  
./third_party/gradlew verifyPluginConfiguration    
FAILURE: Build failed with an exception.
    * What went wrong:
    *   A problem occurred configuring root project 'flutter-intellij'.
    *   > Failed to query the value of task ':runIde' property 'ideDir'.
    *      > Cannot resolve Android Studio with provided version: 2024.2.1.1
```

As soon as we can create a roll and test it, we will push out a point-release version of the Flutter IntelliJ plugin which works with `2024.2`.

**Comment by ygc182** [comment]
+1

**Comment by xweiba** [comment]
Temporary solution: Download the offline package, open `flutter-intellij.zip\flutter-intellij\lib\instrumented-flutter-idea-80.0.2.jar\META-INF\plugin.xml`, change the `until-build` value to be greater than or equal to 242.*, then save and perform a local installation.

I spent the entire morning on this and haven't encountered any issues so far, but I still hope for an update soon.

**Comment by kiratheone** [comment]
it's been quite a long wait to get the latest plugin version :(

> Temporary solution: Download the offline package, open flutter-intellij.zip\flutter-intellij\lib\instrumented-flutter-idea-80.0.2.jar\META-INF\plugin.xml, change the until-build value to be greater than or equal to 242.*, then save and perform a local installation.
> 
> I have been using it for a morning and haven't encountered any issues so far, but I still hope for an update soon.

Thank you for temporary solution @xweiba

**Comment by mitsh** [comment]
> Temporary solution: Download the offline package, open `flutter-intellij.zip\flutter-intellij\lib\instrumented-flutter-idea-80.0.2.jar\META-INF\plugin.xml`, change the `until-build` value to be greater than or equal to 242.*, then save and perform a local installation.
> 
> I have been using it for a morning and haven't encountered any issues so far, but I still hope for an update soon.

@xweiba you are life saver! thanks.

**Comment by Apokalypser** [comment]
I always get an error after trying to locally install the modified plugin. Could someone upload a working modified zip? Thank you very much.

**Comment by mitien** [comment]
@Apokalypser not sure posting "hijacked" plugin is appropriate here, but there is step by step for windows:
1)download https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/582965
2) open with 7zip and perform changes mentioned above:
  2a) navigate to flutter-intellij.zip\flutter-intellij\lib\instrumented-flutter-idea-80.0.2.jar\META-INF\plugin.xml
  2b) press F4 (it will open file in your editor. eg. notepad)
  2c)  search for "until-build"
  2d) change it to 242.*
  2e) close editor and selected "save" ( it might be temp folded but doesn`t matter)
3) close 7zip and accept changes and archive updates
4) Open IntelliJ or Android Studio and install that plugin from local zip (gear icon) 
5) Wait for official plugin update

**Comment by cHAuHaNz** [comment]
Here's the temporary fix:
1. Download the file from here: [flutter-intellij.zip](https://github.com/user-attachments/files/16571232/flutter-intellij.zip)
2. Open your 2024.2 IDE
3. Go to Plugins section in settings
4. Click on ⚙️ icon next to `Installed` tab
5. Choose `🔌 Install Plugin from Disk...`
6. Select the file and restart your IDE
7. Benefit 🫰🏻

> Keep an eye on official plugin for updates

**Comment by tasselx** [comment]
It's been so many days and no adaptation has been done, are you ready to drop support?

**Comment by TheQuyen97ht** [comment]
We're hoping to get the update soon since the plugin stops us from doing anything on our ongoing Flutter projects

**Comment by cHAuHaNz** [comment]
@TheQuyen97ht You can continue working on your flutter projects using [this](https://github.com/flutter/flutter-intellij/issues/7595#issuecomment-2282331704) meanwhile

**Comment by hpoul** [comment]
Or just downgrade intellij, which takes like 5 seconds in jetbrains toolbox 🤷🏻

**Comment by enisingec** [comment]
&gt; Or just downgrade intellij, which takes like 5 seconds in jetbrains toolbox 🤷🏻

can you help me how to downgrade please

**Comment by enisingec** [comment]
> Here's the temporary fix:
> 
> 1. Download [flutter-intellij.zip](https://github.com/user-attachments/files/16571232/flutter-intellij.zip)
> 2. Open your 2024.2 IDE
> 3. Go to Plugins section in settings
> 4. Click on ⚙️ icon next to `Installed` tab
> 5. Choose `🔌 Install Plugin from Disk...`
> 6. Select the file and restart your IDE
> 7. Benefit 🫰🏻
> 
> > Keep an eye on official plugin for updates

I applied exactly what you said, I wonder why it stays on the white page when I run my project ?

**Comment by cHAuHaNz** [comment]
> I applied exactly what you said, I wonder why it stays on the white page when I run my project ?

Getting anything in logs or something? All of my projects are running just fine.
```
Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (13 days ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2
```

**Comment by enisingec** [comment]
> Getting anything in logs or something?

it was my fault because of the stupid antivirus program that was blocking flutter :/ thanks a lot and sorry for disturbing you. 👍

**Comment by rajrushilmakkar** [comment]
Is there any ETA on when the new plugin version would be released?

**Comment by palmerovicdev** [comment]
How can I change that? How do you manage to open the `.jar` and change that and then have it right?

**Comment by Angeloem** [comment]
Flutter package is usually late when Intellij does a major version shift. This is not the first time I experience this.

I'm wondering why they usually set current Idea version as max supported version(Or so I think). Other packages dont do this

**Comment by bernaferrari** [comment]
Yep, happens very often, but this is the first time in a while that takes more than 6 days.

**Comment by rafaeltoledo** [comment]
Instead of all this workaround, use [JetBrains Toolbox](https://www.jetbrains.com/toolbox-app/), and download the 2024.1.x version
<img width="418" alt="Captura de Tela 2024-08-13 às 13 43 22" src="https://github.com/user-attachments/assets/d8e7b043-2d38-4437-b476-d68039fcdb55">

After that, check the option to continue using `2024.1` until there's a new release of the plugin.
<img width="414" alt="Captura de Tela 2024-08-13 às 13 45 56" src="https://github.com/user-attachments/assets/9d514f68-5d33-4a2c-9ced-2267cfdba40c">

**Comment by rolando3412** [comment]
> Lo mismo aquí. En realidad es un error de IntelliJ/característica perdida, creo. Sin embargo, el equipo de Flutter debería lanzar un complemento compatible antes de que se lance una nueva versión de IntelliJ.
> 
> Comente para que sea prioritario: https://youtrack.jetbrains.com/issue/IDEA-357261/IntelliJ-automatically-install-update-without-ensure-all-plugins-have-compatible-version
> 
> Hay un problema más antiguo (3 años!!) con este problema, pero JetBrains no se ocupa de ello.

lo mismo aquí y pensaba que era el único

![Image](https://github.com/user-attachments/assets/f43c39eb-e229-48a6-bf03-159ef86eb7c6)
