### ISSUE TITLE
Flutter IntelliJ plugin incompatible with latest IntelliJ Idea release 2024.2

### ISSUE THREAD

**Issue by thermoworker** [flutter/flutter-intellij#7606]
Plugin 'Flutter' (version '81.0.2') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is IU-242.20224.300.

## Steps to Reproduce

Update IntelliJ IDE to newest version:

IntelliJ IDEA 2024.2 (Ultimate Edition)
Build #IU-242.20224.300, built on August 6, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  eslint.additional.file.extensions=svelte
  ide.images.show.chessboard=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.plugins.xwinkeymap (211.4961.30)
  IdeaVIM (2.15.3)
  com.github.xwsg (1.3.0)
  dev.j-a.swift (1.1.0.354-242)
  com.tylerthrailkill.intellij.solarized (3.0.0)
  Dummy Text Generator (1.2.0)
  name.kropp.intellij.makefile (242.20224.155)
  org.intellij.plugins.hcl (242.20224.159)
  ua.in.dej.myEmmet (1.2.5)
  io.codearte.props2yaml (1.0.2)
  de.docksnet.puml.syntaxchecker (0.2.0)
  org.jetbrains.plugins.hocon (2024.2.0)
  com.kn.diagrams.generator.generator (2022.2.0)
  com.intellij.lang.graql (1.4.1)
  com.intellij.ideolog (242.20224.385)
  DevKit (242.20224.159)
  PlantUML integration (7.10.1-IJ2023.2)
  com.intellij.guice (242.20224.159)
  com.haulmont.jpab (242.20224.300)
  com.intellij.spring.websocket (242.20224.159)
  com.android.tools.idea.smali (242.20224.159)
  com.herbert.george.flutter-snippets (2.0.0-stable-1)
  uk.co.itmoore.intellisubsteps (1.1.0)
  com.intellij.spring.batch (242.20224.159)
  org.asciidoctor.intellij.asciidoc (0.42.2)
  com.intellij.aqua (242.20224.361)
  GrepConsole (13.1.0-IJ2023.3)
  com.intellij.ml.llm (242.20224.385)
  mobi.hsz.idea.gitignore (4.5.3)
  Dart (242.20629)
  dev.blachut.svelte.lang (242.20224.155)
  org.mapstruct.intellij (1.7.0)
  plantuml-parser (0.0.9)
  org.jetbrains.android (242.20224.300)
  ru.adelf.idea.dotenv (2024.2)
  org.intellij.prisma (242.20224.159)
  com.intellij.lang.jsgraphql (242.20224.155)
  com.netflix.graphql.dgs.intellijplugin (1.3.10)
  com.dmarcotte.handlebars (242.20224.159)
  org.sonarlint.idea (10.8.1.79205)
  com.mallowigi (97.0.0)
  org.intellij.scala (2024.2.20)
  com.intellij.spring.graphql (242.20224.159)
  Osmorc (242.20224.159)
  com.intellij.plugins.html.instantEditing (242.20224.155)
Kotlin: 242.20224.300-IJ

## Version info

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ The Google Privacy Policy describes how data is handled in this service.   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/to/crash-reporting                                     ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ║                                                                            ║
  ║ To disable animations in this tool, use                                    ║
  ║ 'flutter config --no-cli-animations'.                                      ║
  ╚════════════════════════════════════════════════════════════════════════════╝

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/user/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/user/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/user/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at /Users/user/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 81.0.2
    • Dart plugin version 242.20629

[✓] Connected device (5 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by stMerlHin** [comment]
+1

**Comment by eschnabel-ers** [comment]
+1

**Comment by zhoujia456888** [comment]
+1

IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)

**Comment by vogttho** [comment]
+1

**Comment by acheronian** [comment]
+1

**Comment by Johannes-Schiel** [comment]
+1

**Comment by YassinoZoldyck** [comment]
+1

**Comment by JaredEzz** [comment]
+1

**Comment by jwren** [comment]
Please re-open and ping me if this wasn't resolved with this version: https://plugins.jetbrains.com/plugin/9212-flutter/edit/versions/stable/587884
