### ISSUE TITLE
Please add support for latest IntelliJ Idea 2024.2

### ISSUE THREAD

**Issue by mateuszboryn** [flutter/flutter-intellij#7607]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Please add support for Idea 2024.2. Current plugin version supports 2024.1.

## Version info

N/A

**Comment by thermoworker** [comment]
This ticket duplicates: https://github.com/flutter/flutter-intellij/issues/7606

**Comment by jwren** [comment]
Please ping me if this wasn't resolved with this version: https://plugins.jetbrains.com/plugin/9212-flutter/edit/versions/stable/587884

**Comment by mateuszboryn** [comment]
Excellent. Thank you.
