### ISSUE TITLE
Tool window icons do not scale appropriately for zoom

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#7620]
![Screenshot 2024-08-21 at 4 44 11 PM](https://github.com/user-attachments/assets/6f3c45d9-973b-4bbc-b20f-19aa3a39d30f)

When selected, the icons are the proper size, but when the tool window is not focused the icons are too small.

**Comment by helin24** [comment]
Do you recall how you got into this mode? Is this using IJ View > Appearance > Zoom IDE?

It looks like the default icons are also wrong, so I wonder if this is a platform issue.

**Comment by kenzieschmoll** [comment]
IJ View > Appearance > Zoom IDE is what I did.

**Comment by helin24** [comment]
Additional context on this issue for @jwren:
- While investigating this, I found that the 20x20 icons aren't being used when the IDE isn't in compact mode. You can test this out by running the IDE workbench and changing a 20x20 icon (e.g. `icons/expui/deepLinks@20x20.svg`) to have weird colors, then seeing if the color shows up in non-compact mode.
- I've been in touch with Chris Sinco about this and other UI issues. Apparently there are some other problems with zoom in Android Studio at the moment, which may or may not be related to the 20x20 icon issue.
- Chris suggested that next person to contact on this may be sepb (internal ldap), who might be able to run our workbench to investigate further.

**Comment by jwren** [comment]
Thanks @helin24 for the context.

This appears to be fixed in later versions of the of the IDEA platform, this is a screenshot from `2024.3` showing the icons are now scaling:

<img width="1118" alt="Screenshot 2024-11-15 at 12 58 53 PM" src="https://github.com/user-attachments/assets/1d99f51e-cd40-4ffa-bd09-5d6b0fb6bf2e">
