### ISSUE TITLE
Tool window icons should be monochrome when selected

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#7621]
![Screenshot 2024-08-21 at 4 46 41 PM](https://github.com/user-attachments/assets/82cde343-12cf-4ee8-9a5d-3ab29c9ac48e)

The Flutter icon is not visible when the tool window is selected because it blends into the blue background. When selected we should use a version of the icon that is monochrome.

**Comment by c5inco** [comment]
See this comment: https://github.com/flutter/flutter-intellij/pull/7574#issuecomment-2311515115
