### ISSUE TITLE
Do not reload Tool Windows when theme is changed

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#7626]
Performing a full reload of the DevTools tool window when the IDE theme is changed is disruptive to the user's workflow and may cause them to lose any debugging data they were looking at before the theme change.

Now that we have DTD to communicate over, we should send an event when the IDE theme changes that DevTools can listen for. DevTools can then update itself for the new IDE theme values.

**Comment by helin24** [comment]
There may be some situations where DTD isn't available, e.g. internal usages. Do you have an opinion on whether we should continue to update theme with a refresh or ignore theme changes in those cases? (or something else)

**Comment by kenzieschmoll** [comment]
If DTD is not available, I recommend we do not update the theme. Having a mismatched theme is a better result than the user potentially losing state in their tool if we force refresh IMO.

**Comment by helin24** [comment]
With the latest changes to DevTools this issue is now resolved
