### ISSUE TITLE
Hot reload buttons become unavailable after reloading once

### ISSUE THREAD

**Issue by MODE83-PROJET-DEV** [flutter/flutter-intellij#7632]
Good morning,

On the dev tools built into Android Studio, hot reloading only happens once, while the web console is fully functioning.

___
**DevTools version**: 2.37.2
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.1
Flutter Version: 3.24.1 / stable
Framework / Engine: 5874a72aa4 / c9b9d5780d

Here orders are unavailable
![Capture d’écran 2024-08-28 115056](https://github.com/user-attachments/assets/d3a90554-ed47-421a-94f2-2120c223fdc1)
![Capture d’écran 2024-08-28 115111](https://github.com/user-attachments/assets/48266315-c79f-4c27-b2c8-2385d6c86e37)

Here the commands work well :)
![Capture d’écran 2024-08-28 115146](https://github.com/user-attachments/assets/e1228d53-aaf6-47dc-a5c9-f9c91f1a5618)

**Comment by helin24** [comment]
@MODE83-PROJET-DEV hopefully my retitling of this issue is accurate - it sounds like you are able to reload successfully the first time, but following that the icons become greyed out?

Do you have a small app that you could share that reproduces this issue?
