### ISSUE TITLE
the new flutter project wizard should offer to install the flutter sdk

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#764]
The new flutter project wizard should offer to install the flutter sdk in-line if there's not one configured.

**Comment by pq** [comment]
#1105: 

![image](https://user-images.githubusercontent.com/67586/27148434-238a95ce-50f5-11e7-9dff-5020011c9fae.png)

**Comment by pq** [comment]
First cut done.  We can track refinements in separate issues.
