### ISSUE TITLE
Problem when push codes to GitHub

### ISSUE THREAD

**Issue by shazzadshojol** [flutter/flutter-intellij#7664]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

Enumerating objects: 132, done.
Counting objects:   0% (1/132)
Counting objects:   1% (2/132)
Counting objects:   2% (3/132)
Counting objects:   3% (4/132)
Counting objects:   4% (6/132)
Counting objects:   5% (7/132)
Counting objects:   6% (8/132)
Counting objects:   7% (10/132)
Counting objects:   8% (11/132)
Counting objects:   9% (12/132)
Counting objects:  10% (14/132)
Counting objects:  11% (15/132)
Counting objects:  12% (16/132)
Counting objects:  13% (18/132)
Counting objects:  14% (19/132)
Counting objects:  15% (20/132)
Counting objects:  16% (22/132)
Counting objects:  17% (23/132)
Counting objects:  18% (24/132)
Counting objects:  19% (26/132)
Counting objects:  20% (27/132)
Counting objects:  21% (28/132)
Counting objects:  22% (30/132)
Counting objects:  23% (31/132)
Counting objects:  24% (32/132)
Counting objects:  25% (33/132)
Counting objects:  26% (35/132)
Counting objects:  27% (36/132)
Counting objects:  28% (37/132)
Counting objects:  29% (39/132)
Counting objects:  30% (40/132)
Counting objects:  31% (41/132)
Counting objects:  32% (43/132)
Counting objects:  33% (44/132)
Counting objects:  34% (45/132)
Counting objects:  35% (47/132)
Counting objects:  36% (48/132)
Counting objects:  37% (49/132)
Counting objects:  38% (51/132)
Counting objects:  39% (52/132)
Counting objects:  40% (53/132)
Counting objects:  41% (55/132)
Counting objects:  42% (56/132)
Counting objects:  43% (57/132)
Counting objects:  44% (59/132)
Counting objects:  45% (60/132)
Counting objects:  46% (61/132)
Counting objects:  47% (63/132)
Counting objects:  48% (64/132)
Counting objects:  49% (65/132)
Counting objects:  50% (66/132)
Counting objects:  51% (68/132)
Counting objects:  52% (69/132)
Counting objects:  53% (70/132)
Counting objects:  54% (72/132)
Counting objects:  55% (73/132)
Counting objects:  56% (74/132)
Counting objects:  57% (76/132)
Counting objects:  58% (77/132)
Counting objects:  59% (78/132)
Counting objects:  60% (80/132)
Counting objects:  61% (81/132)
Counting objects:  62% (82/132)
Counting objects:  63% (84/132)
Counting objects:  64% (85/132)
Counting objects:  65% (86/132)
Counting objects:  66% (88/132)
Counting objects:  67% (89/132)
Counting objects:  68% (90/132)
Counting objects:  69% (92/132)
Counting objects:  70% (93/132)
Counting objects:  71% (94/132)
Counting objects:  72% (96/132)
Counting objects:  73% (97/132)
Counting objects:  74% (98/132)
Counting objects:  75% (99/132)
Counting objects:  76% (101/132)
Counting objects:  77% (102/132)
Counting objects:  78% (103/132)
Counting objects:  79% (105/132)
Counting objects:  80% (106/132)
Counting objects:  81% (107/132)
Counting objects:  82% (109/132)
Counting objects:  83% (110/132)
Counting objects:  84% (111/132)
Counting objects:  85% (113/132)
Counting objects:  86% (114/132)
Counting objects:  87% (115/132)
Counting objects:  88% (117/132)
Counting objects:  89% (118/132)
Counting objects:  90% (119/132)
Counting objects:  91% (121/132)
Counting objects:  92% (122/132)
Counting objects:  93% (123/132)
Counting objects:  94% (125/132)
Counting objects:  95% (126/132)
Counting objects:  96% (127/132)
Counting objects:  97% (129/132)
Counting objects:  98% (130/132)
Counting objects:  99% (131/132)
Counting objects: 100% (132/132)
Counting objects: 100% (132/132), done.
Delta compression using up to 8 threads
Compressing objects:   0% (1/111)
Compressing objects:   1% (2/111)
Compressing objects:   2% (3/111)
Compressing objects:   3% (4/111)
Compressing objects:   4% (5/111)
Compressing objects:   5% (6/111)
Compressing objects:   6% (7/111)
Compressing objects:   7% (8/111)
Compressing objects:   8% (9/111)
Compressing objects:   9% (10/111)
Compressing objects:  10% (12/111)
Compressing objects:  11% (13/111)
Compressing objects:  12% (14/111)
Compressing objects:  13% (15/111)
Compressing objects:  14% (16/111)
Compressing objects:  15% (17/111)
Compressing objects:  16% (18/111)
Compressing objects:  17% (19/111)
Compressing objects:  18% (20/111)
Compressing objects:  19% (22/111)
Compressing objects:  20% (23/111)
Compressing objects:  21% (24/111)
Compressing objects:  22% (25/111)
Compressing objects:  23% (26/111)
Compressing objects:  24% (27/111)
Compressing objects:  25% (28/111)
Compressing objects:  26% (29/111)
Compressing objects:  27% (30/111)
Compressing objects:  28% (32/111)
Compressing objects:  29% (33/111)
Compressing objects:  30% (34/111)
Compressing objects:  31% (35/111)
Compressing objects:  32% (36/111)
Compressing objects:  33% (37/111)
Compressing objects:  34% (38/111)
Compressing objects:  35% (39/111)
Compressing objects:  36% (40/111)
Compressing objects:  37% (42/111)
Compressing objects:  38% (43/111)
Compressing objects:  39% (44/111)
Compressing objects:  40% (45/111)
Compressing objects:  41% (46/111)
Compressing objects:  42% (47/111)
Compressing objects:  43% (48/111)
Compressing objects:  44% (49/111)
Compressing objects:  45% (50/111)
Compressing objects:  46% (52/111)
Compressing objects:  47% (53/111)
Compressing objects:  48% (54/111)
Compressing objects:  49% (55/111)
Compressing objects:  50% (56/111)
Compressing objects:  51% (57/111)
Compressing objects:  52% (58/111)
Compressing objects:  53% (59/111)
Compressing objects:  54% (60/111)
Compressing objects:  55% (62/111)
Compressing objects:  56% (63/111)
Compressing objects:  57% (64/111)
Compressing objects:  58% (65/111)
Compressing objects:  59% (66/111)
Compressing objects:  60% (67/111)
Compressing objects:  61% (68/111)
Compressing objects:  62% (69/111)
Compressing objects:  63% (70/111)
Compressing objects:  64% (72/111)
Compressing objects:  65% (73/111)
Compressing objects:  66% (74/111)
Compressing objects:  67% (75/111)
Compressing objects:  68% (76/111)
Compressing objects:  69% (77/111)
Compressing objects:  70% (78/111)
Compressing objects:  71% (79/111)
Compressing objects:  72% (80/111)
Compressing objects:  73% (82/111)
Compressing objects:  74% (83/111)
Compressing objects:  75% (84/111)
Compressing objects:  76% (85/111)
Compressing objects:  77% (86/111)
Compressing objects:  78% (87/111)
Compressing objects:  79% (88/111)
Compressing objects:  80% (89/111)
Compressing objects:  81% (90/111)
Compressing objects:  82% (92/111)
Compressing objects:  83% (93/111)
Compressing objects:  84% (94/111)
Compressing objects:  85% (95/111)
Compressing objects:  86% (96/111)
Compressing objects:  87% (97/111)
Compressing objects:  88% (98/111)
Compressing objects:  89% (99/111)
Compressing objects:  90% (100/111)
Compressing objects:  91% (102/111)
Compressing objects:  92% (103/111)
Compressing objects:  93% (104/111)
Compressing objects:  94% (105/111)
Compressing objects:  95% (106/111)
Compressing objects:  96% (107/111)
Compressing objects:  97% (108/111)
Compressing objects:  98% (109/111)
Compressing objects:  99% (110/111)
Compressing objects: 100% (111/111)
Compressing objects: 100% (111/111), done.
Writing objects:   0% (1/132)
Writing objects:   1% (2/132)
Writing objects:   2% (3/132)
Writing objects:   3% (4/132)
Writing objects:   4% (6/132)
Writing objects:   5% (7/132)
Writing objects:   6% (8/132)
Writing objects:   7% (10/132)
Writing objects:   8% (11/132)
Writing objects:   9% (12/132)
Writing objects:  10% (14/132)
Writing objects:  11% (15/132)
Writing objects:  12% (16/132)
Writing objects:  13% (18/132)
Writing objects:  14% (19/132)
Writing objects:  15% (20/132)
Writing objects:  16% (22/132)
Writing objects:  17% (23/132)
Writing objects:  18% (24/132)
Writing objects:  19% (26/132)
Writing objects:  20% (27/132)
Writing objects:  21% (28/132)
Writing objects:  22% (30/132)
Writing objects:  23% (31/132)
Writing objects:  24% (32/132)
Writing objects:  25% (33/132)
Writing objects:  26% (35/132)
Writing objects:  27% (36/132)
Writing objects:  28% (37/132)
Writing objects:  29% (39/132)
Writing objects:  30% (40/132)
Writing objects:  31% (41/132)
Writing objects:  32% (43/132)
Writing objects:  33% (44/132)
Writing objects:  34% (45/132)
Writing objects:  35% (47/132)
Writing objects:  36% (48/132)
Writing objects:  37% (49/132)
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
send-pack: unexpected disconnect while reading sideband packet
Writing objects:  38% (51/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  39% (52/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  40% (53/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  41% (55/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  42% (56/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  43% (57/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  44% (59/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  45% (60/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  46% (61/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  47% (63/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  48% (64/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  49% (65/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  50% (66/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  51% (68/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  52% (69/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  53% (71/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  54% (72/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  55% (73/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  56% (74/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  57% (76/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  58% (77/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  59% (78/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  60% (80/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  61% (81/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  62% (82/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  63% (84/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  64% (85/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  65% (86/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  66% (88/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  67% (89/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  68% (90/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  69% (92/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  70% (93/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  71% (94/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  72% (96/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  73% (97/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  74% (98/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  75% (99/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  76% (101/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  77% (102/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  78% (103/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  79% (105/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  80% (106/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  81% (107/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  82% (109/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  83% (110/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  84% (112/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  85% (113/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  86% (114/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  87% (115/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  89% (118/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  90% (119/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  91% (121/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  92% (122/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  93% (123/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  94% (125/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  95% (126/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  96% (127/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  97% (129/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  98% (130/132), 1.11 MiB | 1.18 MiB/s
Writing objects:  99% (131/132), 1.11 MiB | 1.18 MiB/s
Writing objects: 100% (132/132), 1.11 MiB | 1.18 MiB/s
Writing objects: 100% (132/132), 8.56 MiB | 7.48 MiB/s, done.
Total 132 (delta 10), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly

**Comment by jwren** [comment]
There isn't anything actionable in the Flutter IJ plugin with this issue, closing.
