### ISSUE TITLE
indent issue in a line comment in the flutter create sample app

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#767]
I see some odd indent behavior in line comments in the `flutter create` sample app. This repros on TOT of the Dart plugin, so I think is still an issue. To repro:

- in IntelliJ, create a new flutter project
- set your cursor to the end of line 16, `'Try running your application with "flutter run". You'll see'`
- hit return
- the cursor ends up on column 6, but I would have expected column 8 (lined up with the line comment)

@stevemessick, @alexander-doroshko

**Comment by stevemessick** [comment]
Yep, definitely a formatter bug. If you reformat the code using the built-in formatter that comment is aligned with the named parameter (col 6). The dart_style formatting aligns it with the parameter value (col 8).

**Comment by devoncarew** [comment]
👍 :)
