### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon (again/still)

### ISSUE THREAD

**Issue by sean-hammon** [flutter/flutter-intellij#7749]
This is slightly different from previous reports of this ActionUpdateThread issue because it is specifically mentioning 'andrasferenczi.action.NamedArgumentConstructorAction'.

Multiple interactions with IntelliJ produce this error. CMD+insert to open the generate chooser will do it. Right clicking to open the popup menu will also do it. Doesn't have to be in a Dart project. I don't even have the Flutter project open when this happens. It's not really a breaking bug. I just get the error alert in the bottom right corner of the IDE.

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'andrasferenczi.action.NamedArgumentConstructorAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: andrasferenczi.dart-data-plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

[✓] Flutter (Channel stable, 3.24.3, on macOS 14.4.1 23E224 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.4)
[✓] Connected device (2 available)
[✓] Network resources

Plugin version is 82.0.3

**Comment by jwren** [comment]
The class `andrasferenczi.action.NamedArgumentConstructorAction` is not in the Flutter IJ plugin.  I suspect that you have an additional flutter related plugin installed.
