### ISSUE TITLE
Refactor StatelessWidget to StatefulWidget

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#779]
Very common to start with something simple then realize that state is needed. Would be nice to press one button and have the State object and the createState() hookup and the build() move etc to be done automatically with a refactor.

**Comment by pq** [comment]
FYI @stevemessick:  a nice candidate for an assist.

**Comment by stevemessick** [comment]
Sounds interesting but I'm not a Flutter programmer. @xster Can you show before and after code?

**Comment by HansMuller** [comment]
I wrote up a similar request yesterday. It includes before and after (and etc) code: https://github.com/flutter/flutter-intellij/issues/814

**Comment by scheglov** [comment]
We [implemented](https://dart-review.googlesource.com/c/sdk/+/39921) a Quick Assist (activated using Alt+Enter) to convert `StatelessWidget` to `StatefulWidget`. This is input-less code transformation, so it does not have to be a full refactoring, and can be lightweight.
