### ISSUE TITLE
Missing add @required arg quickfix for FloatingActionButton.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#788]
A `FloatingActionButton` with no `onPressed` gets a warning but no associated quick-fix.

![screen shot 2017-03-07 at 2 46 31 pm](https://cloud.githubusercontent.com/assets/67586/23681735/044de1dc-0345-11e7-840a-af33eb7a09a6.png)

**Comment by pq** [comment]
Doing some spelunking.

Interestingly, the fix appears to be created by DAS:

```
{"error"::{"severity"::"INFO","type"::"HINT","location"::{"file"::"/Users/pquitslund/IdeaProjects/untitled9_111/untitled9_111_OVERRIDDEN/lib/main.dart","offset"::2156,"length"::20,"startLine"::66,"startColumn"::22},"message"::"The parameter 'onPressed' is required.","correction"::"","code"::"missing_required_param","hasFix"::false},"fixes"::[{"message"::"Add required argument 'onPressed'","edits"::[{"file"::"/Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/material/floating_action_button.dart","fileStamp"::0,"edits"::[{"offset"::2177,"length"::0,"replacement"::"onPressed:: null"}]}],"linkedEditGroups"::[]}]}]}}
```

Also interesting is that the fixes to suppress the error are missing:

![screen shot 2017-03-14 at 11 56 29 am](https://cloud.githubusercontent.com/assets/67586/23917647/50288338-08ad-11e7-8146-b514511b40ab.png)
![screen shot 2017-03-14 at 11 56 36 am](https://cloud.githubusercontent.com/assets/67586/23917648/5029bd8e-08ad-11e7-85b8-e9d9bab0f150.png)

Current hypothesis is that something is happening on the Dart Plugin side to filter out these fixes.  Still digging...

**Comment by pq** [comment]
@alexander-doroshko: I wonder if you have any ideas?

I'm stepping through things in the Dart Plugin but the flow is unfamiliar to me (and it's looking a bit complex).

I've confirmed that I'm getting these fixes back from DAS in `com.jetbrains.lang.dart.analyzer.DartAnalysisServerService#askForFixesAndWaitABitIfReceivedQuickly`

<img width="499" alt="screen shot 2017-03-15 at 5 52 06 am" src="https://cloud.githubusercontent.com/assets/67586/23949199/93890bb6-0943-11e7-9fa6-67db89fb1d2b.png">

and that `onError` is not being called but somehow these fixes are not showing up and we're only seeing the assists.

<img width="463" alt="screen shot 2017-03-15 at 5 53 33 am" src="https://cloud.githubusercontent.com/assets/67586/23949243/c14f5e38-0943-11e7-91d7-3cafdd5e6726.png">

Any thoughts?

If you want to reproduce, this is my test file:

```
import 'package:flutter/material.dart';

main() {
  FloatingActionButton button = new FloatingActionButton();
}
```

**Comment by pq** [comment]
More context @alexander-doroshko.  This fix does appear when the `@required` parameter is defined locally.

![screen shot 2017-03-15 at 10 15 26 am](https://cloud.githubusercontent.com/assets/67586/23961518/6fbc3c24-0968-11e7-8daa-bcd6ecd458e2.png)


So at least _sometimes_ it is available.  Also notable is that the suppress action is still not visible.

**Comment by alexander-doroshko** [comment]
With SDK 1.23.0-dev.5.0 I get a quick fix:
![image](https://cloud.githubusercontent.com/assets/4499789/23962022/d6296b8a-09bd-11e7-8cb7-1fc2fc91505c.png)

Try to add and remove some insignificant space, move caret and press Alt+Enter again, will it appear?

**Comment by alexander-doroshko** [comment]
Oh, didn't read you comment before writing mine :)

**Comment by alexander-doroshko** [comment]
Bingo!
See the quick fix received from the server that you pasted in your 1st comment. It suggests to edit the file from the Flutter SDK! Luckily the IDE is smart enough to ignore this buggy quick fix :)
```
"file"::"/Users/pquitslund/src/git/clones/flutter/packages/flutter/lib/src/material/floating_action_button.dart"
```

**Comment by pq** [comment]
AHA!

Thanks a million for helping track this down.  I'll go fix the fix in the SDK.

Looks like I owe you another beer! :)  🍻

**Comment by pq** [comment]
https://codereview.chromium.org/2749373002/ 🤘

**Comment by pq** [comment]
![screen shot 2017-03-15 at 1 41 12 pm](https://cloud.githubusercontent.com/assets/67586/23969863/29475bda-0985-11e7-8134-38a5d0a1cc40.png)

🎉
