### ISSUE TITLE
Still breaking at removed breakpoint

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#790]
Encountered when setting (and unsetting) a breakpoint in the demo app.

<img width="392" alt="screen shot 2017-03-08 at 11 54 20 am" src="https://cloud.githubusercontent.com/assets/67586/23721321/2c954552-03f6-11e7-8fb3-5f8716a2c8b5.png">

Debugger stops even though IDEA doesn't see the breakpoint anymore.

<img width="974" alt="screen shot 2017-03-08 at 11 54 35 am" src="https://cloud.githubusercontent.com/assets/67586/23721325/2f158fb2-03f6-11e7-82d4-1f9ce4d20763.png">

cc @devoncarew

**Comment by pq** [comment]
I couldn't immediately repro but I recall I did a reload somewhere in there when this happened...

**Comment by devoncarew** [comment]
note: the sticking point here is getting an easy repo

**Comment by branflake2267** [comment]
Not sure this helps. Something I've noticed but haven't confirmed yet. 
1. Debug and cause a break on a break point. 
2. Shut down the app with out a continuing off the break point. 
3. Try to restart, launch debugging.
4. This is where the hang is, either it won't launch debugging.
- I think it may be hung on the last break point even though the process has restarted. 

Anyway, I've been aiming to drill this more before I said something so it may be different steps here.

**Comment by devoncarew** [comment]
Some good repro instructions here: https://github.com/flutter/flutter-intellij/issues/983; closing this bug in favor of that one.
