### ISSUE TITLE
Flutter IDE Wish: Define a Stateful/Stateless widget class

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter-intellij#800]
There are several basic bits of widget class boilerplate that Flutter app developers are likely to write repeatedly: define a stateless widget class, define a stateful widget class. It's also common to start with a stateless widget and then convert it to a stateful widget later on.  Finally, when a Stateful widget class is defined, you may want to have it create an AnimationController.

The IDE could generate the boilerplate automatically. Perhaps, in some cases, it could also automatically convert a stateless widget to a stateful one (and back).

The boilerplate for a stateless widget Foo
```
class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Container(); // YOUR CODE HERE
  }
}
```

The boilerplate for a stateful widget Foo
```
class Foo extends StatefulWidget {
  @override
  _FooState createState() => new _FooState();
}

class _FooState extends State<Foo> {
  @override
  Widget build(BuildContext context) {
    return new Container(); // YOUR CODE HERE
  }
}
```

The boilerplate for a stateful widget Foo, with an AnimationController:
```
class Foo extends StatefulWidget {
  @override
  _FooState createState() => new _FooState();
}

class _FooState extends State<Foo> with SingleTickerProviderStateMixin {
  AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = new AnimationController(vsync: this);
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return new Container(); // YOUR CODE HERE
  }
}
```

**Comment by stevemessick** [comment]
Here's a possible solution that I'd like feedback regarding usability. If this is usable we can build this, and others, into the Flutter plugin.

The basic idea is to create a custom live template that expands into the definition of a new StatelessWidget subclass. Open Preferences/Settings and search for the Live Templates page. Here's what mine looks like when finished.

<img width="1117" alt="screen shot 2017-03-14 at 10 53 40 am" src="https://cloud.githubusercontent.com/assets/8518285/23914889/8f3741a8-08a4-11e7-9f2f-6c450738e47d.png">

Getting there requires a few steps.
* First, create a new template group by clicking the `+` (under "Reset" on the right side) and select option 2. Call it "Flutter".
* Select it and click the `+` again.
* Choose option 1. You can put anything you want in the `<abbreviation>` field. I chose "stless" (more about that later).
* Give it a description like "Stateless widget" that will show up in the menu.
* Paste your expansion code into the text pane.
* Change "Foo" to "$SELECTION$" and insert "$END$" where the user should start typing.
* At the bottom click the `Define` button next to "No applicable contexts yet."
* Expand `Dart` and select the `Other` beneath it. (This is a bit flakey, I think. I had to deselect `Dart` and reselect `Other` to eliminate statement applicability.)
* Click `OK` to save the new template.

You can use the template in two ways: select the template from a menu or type "stless" and hit Tab. Your cursor needs to be outside a class definition for the template to be available.

If you type "stless<tab>" the template will be expanded and your cursor will be left at the position of the new class name. If you select the template from a menu then you can get an additional shortcut by typing the name of the new class, selecting it, then selecting the template from the menu (Cmd-Opt-J on Mac or Cmd-Opt-T on Mac). Cmd-Opt-J has the advantage of putting `stless` at the top of the list. Once the template is expanded your new class is defined and the cursor is left in the arguments of `new Container()`.

I know it is asking a lot to have someone experiment with this. But if this is actually useful it would be simple to add templates for all the suggestions in this issue to the Flutter plugin.

/cc @sethladd @mit-mit

**Comment by HansMuller** [comment]
So, if I'm understanding this correctly, you're proposing adding an IDE feature that enables creating a code fragment template of one parameter as well as a marker that indicates where the cursor should end up.  We'd use this feature to create a bunch of useful templates, like the three outlined in this issue's description. Is that right?

I do have some thoughts about functionality and usability; wanted to make sure I understood the proposal first though.

**Comment by stevemessick** [comment]
That's about right, I think. We'll use the existing IDE template creation mechanism to pre-populate some Flutter-specific templates. The $SELECTION$ and $END$ variables are magic, and work as you describe. You can create additional variables so we might define more variables for more complex templates. The values for the additional variables would be filled-in after the template had been expanded.

My question is whether pre-defined templates will be useful enough to justify adding them to the plugin. I'll be happy to answer any additional questions you have.

**Comment by HansMuller** [comment]
I think this could be a useful feature, particularly for new developers.  It doesn't address two of the use cases mentioned at the outset:
- Make this stateless widget stateful
- Add an AnimationController to this stateful widget
- And I suppose since this is a wish after all, moving a new widget expression from stateful back to stateless, etc.

That said, there's plenty of utility in providing the standard boilerplate for common 'new widget expressions'.  

Inserting an expanded template seems a little clunky:

>  ...typing the name of the new class, selecting it, then selecting the template from the menu (Cmd-Opt-J on Mac or Cmd-Opt-T on Mac). 

It's not clear where the name would go, it seems like temporary text that you'd delete after the template was selected/expanded? The whole process might be more intuitive and informative if you gave the user a dialog with a brief explanation of what the template was for and fields for the template variables (the stateful widget with an animation controller template could have variables for both the class name and the animation controller variable name). 

Similarly a template dialog might enable making an informed decision about selecting a different template. For example: the user selects the basic 'new stateless widget' template which says: if the widget's layout is to be animated, then use the 'new Animated widget' template instead. Clicking that would switch templates and help educate developers about the options.

If wishes were horses.

**Comment by stevemessick** [comment]
Here's a short movie showing two of the three requested templates in action:
[template_demo.zip](https://github.com/flutter/flutter-intellij/files/845444/template_demo.zip)
To keep file size down I only recorded a small part of the IntelliJ editing pane. I used Cmd-Shift-RightArrow to select the word and Cmd-Opt-J to bring up the menu.

If you think this would be useful we'd probably just add some of these templates to the next release. They are quite easy to define.

Creating a tool to automatically convert stateless to state-full, or add an animation controller, is a lot more work. The conversions would probably be useful to more people, though. As you indicate, using the IntelliJ "assist" (Alt-Newline) feature to implement the conversion may not be optimal. Defining a new refactoring operation would allow displaying a form where various bits could be filled in. It would be a lot more discoverable if we add something to the `Refactor` menu.

/cc @pq

**Comment by HansMuller** [comment]
I uploaded the video to YouTube because Linux: https://youtu.be/6Yan2pNSwU0

What you've got looks pretty useful and I'm sure we could define quite a few templates this way.  Making the templates easy to discover and configure would be really helpful.

**Comment by pq** [comment]
Awesome!  I especially like how this mechanism allows folks to define their own templates for their own widgets (and other boilerplate).  The discoverability problem is a tough one but since this is so low cost, I'm up for exploring it and seeing if, with training/docs, we can get folks on the happy path to using them.

**Comment by stevemessick** [comment]
With PR https://github.com/flutter/flutter-intellij/pull/834 there are now three templates defined to generate the boilerplate shown above. The templates are named: stless, stful, stanim.

To generate a new StatefulWidget, for example, you would type `stful` then `tab`, then type the name of the class once. That name will be inserted everywhere it needs to be in the expanded text.

To see all the available IntelliJ templates, open Preferences/Settings and navigate to Editor > Live Templates. We're taking requests for more templates. :) And we're tying to find better ways to publicize them.

We're still thinking about how to convert a widget from one type to another.

**Comment by sethladd** [comment]
Thanks! Should we open a documentation issue so we mention this new capability in our website docs?

**Comment by pq** [comment]
@sethladd : yes please!  @LarkAscending FYI.

**Comment by stevemessick** [comment]
For clarity, we've done the work to address widget creation, with the boilerplate templates. We have not yet done any work on a refactoring tool that would convert one kind of widget to another. That would involve determining which parts of the boilerplate are present and which absent and then generating new source to add/remove parts as needed, without breaking anything.

**Comment by scheglov** [comment]
We [implemented](https://dart-review.googlesource.com/c/sdk/+/39921) a Quick Assist (activated using Alt+Enter) to convert `StatelessWidget` to `StatefulWidget`.
