### ISSUE TITLE
bazel: verify breakpoints work for untracked and generated files

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#807]
Generated files are found in bazel-bin and bazel-genfiles, not in the user's working directory. 

There may be similar issues with untracked files (in ../READONLY).

The source file mapping code doesn't seem to handle this case. But it's also possible we pick this up by delegating to the analysis server, which understands package: uris.

**Comment by skybrian** [comment]
@jwren still open but probably low priority, since it's only an issue for generated files in the same package. (PositionMapper is the class to look at.)

**Comment by pq** [comment]
@jwren: if you're actively working on this, feel free to move to M24.

**Comment by jwren** [comment]
Closing out issue, breakpoints in framework are hit.  Issues for other kinds of files can be looked at if we get issues filed against us.
