### ISSUE TITLE
Windows: Stop button is missing

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#809]
The stop button in the navigation/tool bar is missing on Windows:

![image](https://cloud.githubusercontent.com/assets/13644170/23849437/ec25a86a-07db-11e7-8adc-fa4d8288ade5.png)

![image](https://cloud.githubusercontent.com/assets/13644170/23849476/0bfa501e-07dc-11e7-8eb6-bab19a74aae4.png)

**Comment by devoncarew** [comment]
I don't see it there when doing Java development either, just a stop button in the Run/Debug view.

**Comment by devoncarew** [comment]
@mit-mit, can you confirm this under 2017.1? I do see the button:

<img width="257" alt="screen shot 2017-03-29 at 3 16 49 pm" src="https://cloud.githubusercontent.com/assets/1269969/24479166/c87874d8-1492-11e7-9401-603d958b728f.png">

**Comment by mit-mit** [comment]
I do not see this in 2017.1 either. Closing!
