### ISSUE TITLE
I have Flutter, but IntelliJ is telling me to download Dart SDK ?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#813]
Just booting up my IntelliJ and configuring it. I have Flutter installed, thus I have a dart sdk under the covers. I just installed the Dart plugin and rebooted IntelliJ. I see this:

<img width="1055" alt="screen shot 2017-03-13 at 9 38 53 am" src="https://cloud.githubusercontent.com/assets/5479/23864902/37c51b94-07d1-11e7-8405-7b02b1cc4a31.png">

Do I need to download another Dart SDK? Or, can the Dart plugin find the Dart SDK that's already on my system from the Flutter SDK?

As a new Flutter developer, I'm not sure what to do here. What's the best way to keep going?

Here's a flow that might best help our users:

* Open a Flutter project that already has the intellij metadata files.
* IntelliJ tells me to download the plugins. I do that.
* Maybe reboot IntelliJ.
* Done.

Ideally:

* No need to "enable Dart support for this project", because the intellij metadata file already has this turned on.
* No need to manually configure the Dart SDK for any flutter project. It's auto-detected.

**Comment by mit-mit** [comment]
@sethladd I am curious about how you got into this state! Did you have IntelliJ with just Dart plugin and no Flutter plugin, and then you opened `examples/gallery`?

**Comment by sethladd** [comment]
This is on a brand-new Mac, brand-new IntelliJ. I opened examples/flutter_gallery first (or maybe I imported? I can't remember), and IntelliJ prompted me to install plugins. I can't remember if I installed both plugins at that time, or only one, sorry.

**Comment by sethladd** [comment]
This happened to me again, on my first install of INtelliJ CE on my Windows machine. Here's what I did:

* Flutter is already installed
* My app is already created (created from `flutter create`)
* Install IntelliJ CE
* Install Flutter (and Dart plugins)
* Restart IntelliJ
* Open my app
* See this:
![capture4](https://cloud.githubusercontent.com/assets/5479/25775664/3e900f02-325f-11e7-81e6-8ea8dd79d75b.PNG)

Can we have the Flutter plugin auto-detect that the Dart SDK that comes with Flutter? Ideally, we don't have to ask our users to also download and install a separate and likely misversioned Dart SDK. We really want our users to install Flutter and then install the IntelliJ plugin and that's it. :)

If I click "Open Dart settings", then I'm shown this:
![capture5](https://cloud.githubusercontent.com/assets/5479/25775674/79631ebc-325f-11e7-8e95-7483d74b01d7.PNG)

For Flutter projects, could we:

* Auto-detect the Dart SDK that flutter already download, and use that.
* Don't default to ask to auto-detect new versions of Dart SDK. That doesn't apply to Flutter.
* Auto-enable Dart support for a Flutter project.

**Comment by devoncarew** [comment]
@sethladd, I think this (and the other new issues created recently) is due to us not detecting that the project is a flutter project. I'll ask for more info on one of the other issues.

**Comment by sethladd** [comment]
Thanks

**Comment by mit-mit** [comment]
@devoncarew do we still need this bug after your investigation?

**Comment by devoncarew** [comment]
No, I think this was covered by other issues.
