### ISSUE TITLE
make it easier to run dartfmt

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#816]
There's no keybinding for dartfmt - the default binding invokes the IntelliJ formatter. We should make it easier to run dartfmt; one idea here is to add an option to format on save.

**Comment by devoncarew** [comment]
Note that one implementation of save actions is here: https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/src/com/dubreuia/SaveActionManager.java.

**Comment by jwren** [comment]
One idea/ possible progress: https://github.com/JetBrains/intellij-plugins/pull/510

**Comment by dvdwasibi** [comment]
Is there an update on this?

We are doing some live coding on stage for Google I/O using intellij and this would be nice.

**Comment by devoncarew** [comment]
It's a surprisingly difficult problem. We're working on an API so that another plugin (the Flutter plugin) can expose a user preference for this. We may also change the Dart plugin to invoke dartfmt when the user requests a full file format (there are several different formatting modes in IntelliJ).

> We are doing some live coding on stage for Google I/O using intellij and this would be nice.

For now, you can edit your settings to create a local keybinding to the dartfmt action. In the 'Keymap' setting, you can search for the dartfmt action, and add a new keybinding to it.

**Comment by mit-mit** [comment]
Can we make that dartfmt option on by default?

**Comment by devoncarew** [comment]
In the Dart plugin, the resolution was not to. We may be able to change that decision w/ sufficient user input.

We can also choose to set that option from the flutter plugin as a one-time thing, so flutter users do see whole-file formats using dartfmt by default, but can adjust the setting if they choose.

**Comment by InMatrix** [comment]
Will our analytics/logs include how many users turned on that option? In addition, do we know the percentage of users who have used dartfmt? I'm trying to understand how we might get "user input".

**Comment by devoncarew** [comment]
> I'm trying to understand how we might get "user input".

I suspect it's going to be more anecdotal rather than data driven. @alexander-doroshko can speak to the data available via IntelliJ's analytics. In the Flutter plugin, we're not currently tracking user preferences (we also have very few to potentially track).

**Comment by alexander-doroshko** [comment]
As for now, no dartfmt metrics gathered. We'll probably have to make the decision about the default value based on the user feedback and expert feelings.

**Comment by mit-mit** [comment]
@devoncarew can we close this bug now that we have https://github.com/flutter/flutter-intellij/issues/1108 ?

**Comment by devoncarew** [comment]
Yup, closing.
