### ISSUE TITLE
Verify the Flutter plugin works with a separate SDK than web Dart projects

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#822]
As discussed in https://github.com/flutter/flutter-intellij/issues/54, we currently get into broken territory if a developer has both Flutter and Dart plugins installed, as their Dart SDK setting is shared.

https://github.com/flutter/flutter-intellij/issues/56 gives us the platform support for separating that. This bug tracks any Flutter plugin updates needed, and verifying that the solution works end-to-end.

**Comment by devoncarew** [comment]
> and verifying that the solution works end-to-end

This work has landed and is in use. I think the only part that remains is the verification portion.

**Comment by devoncarew** [comment]
@mit-mit I have verified this; do you want to test this as well before we close the issue?

**Comment by mit-mit** [comment]
I did some quick verification as well, and this works great! Really nice to have Flutter and Web projects open at the same time, each on their own SDK!
