### ISSUE TITLE
support 2017.1

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#823]
We'll need to have support for 2017.1 fairly soon (and continue to support 2016.3 for a bit after that).

**Comment by pq** [comment]
As discussed, we should probably bump this to `M12`.

**Comment by pq** [comment]
And a good place to start might be to get us building against `2017.1` PDQ.

**Comment by mit-mit** [comment]
@pq @devoncarew what is the status of this?

This launched yesterday:
https://www.jetbrains.com/idea/whatsnew/

**Comment by b-strauss** [comment]
I just updated and flutter is gone in the "create new project" dialog.

**Comment by pq** [comment]
Sorry for the inconvenience @b-strauss!  A bit changed in our dependencies between releases and we need to do some fancy footwork to accommodate. @devoncarew was looking at this earlier in the week; not sure of status but will follow-up.

**Comment by pq** [comment]
Chatting w/ @devoncarew just now and the rub is that it won't merge cleanly into an older branch and will take more doing than we can swing in a quick patch release.  Folks should hold off on upgrading to `2017.1` until we get things sorted.

Sorry for the continued inconvenience!

**Comment by mit-mit** [comment]
Website updated in https://github.com/flutter/website/pull/472

**Comment by b-strauss** [comment]
Has this yet been released? I can't find flutter in 2017.1's plugin repository.

**Comment by mit-mit** [comment]
No, it has not been released yet. But we are getting close; currently testing a first release candidate, and hope to release an update soon!

**Comment by devoncarew** [comment]
The new version is available now; thanks for your patience!

**Comment by devoncarew** [comment]
Please note the one known issue when upgrading to 2017.1 - older projects may need to re-configure their Dart SDK: https://github.com/flutter/flutter-intellij#known-issues.
