### ISSUE TITLE
It's not obvious to new users where their code is in IntelliJ 

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#824]
_From @lukechurch on March 15, 2017 9:40_

In studies we've seen participants clicking around the structure of the project in IntelliJ to try and find their code, looking in the android, ios and build folders.

It would be helpful if there was an obvious separation between 'things they should edit a lot' and 'things which the systems needs that they should leave alone' were stronger. 
Alternatively if they never need to edit the other folders, perhaps we could hide them altogether?

_Copied from original issue: flutter/flutter#8784_

**Comment by pq** [comment]
@lukechurch : curious if you have any recommendations here.  Examples of places where this is done better?  (Not disagreeing mind you; just looking for guidance!)

**Comment by lukechurch** [comment]
@pq IIRC Ye Goode Olde Dart Editor did some things along this line, sorting some folders to the bottom?

I think Visual Studio separates 'files in project' from 'files in disk' and has the option of switching (https://blogs.msdn.microsoft.com/benwilli/2015/05/21/visual-studio-tip-8-adding-existing-files-with-show-all-files/) 

My recommendation somewhat depends on how often users need to know about all the android and iOS stuff. If it's basically never then I'd recommend hiding it and putting a 'show all files' somewhere in a menu.

If it's 'sometimes' then I'd recommend sorting the files and folders to the end and making them partially transparent.

**Comment by pq** [comment]
Good recall @lukechurch.  The olde editor of yore did some sorting and hiding to make sense of all this.  I believe we can do similar things in IDEA but I'm not sure the details.  I do recall there are restrictions on what we can hide (folders: yes, files : no) see: https://github.com/flutter/flutter-intellij/issues/630#issuecomment-272430576.

@alexander-doroshko : can you confirm whether we can control sort order?

**Comment by alexander-doroshko** [comment]
I'm not aware of extension points that affect Project View sorting. There's one standard sorting action under gear, and I do not think the view is designed to be sorted alternatively.
If files in these folders are of no interest you can exclude these folders. As you know there's an option whether to show excluded folders or not in the Project View. Excluded files are considered to be outside of the project and are not indexed.
There are extension points that allow changing node presentation including icon, text, colors and all the rest. It is even possible to add or remove any kind of nodes to/from the Project View. Be careful if you go this way: you never can make 100% of users happy with unpredictable project tree.

**Comment by pq** [comment]
Thank you @alexander-doroshko!

**Comment by devoncarew** [comment]
> There are extension points that allow changing node presentation

Perhaps this would be a good way to go - to de-emphasize certain folders we likely didn't want users to edit in IntelliJ.

**Comment by pq** [comment]
Circling back to this, let's talk about ideal presentations.

Here's what we see today:

<img width="447" alt="screen shot 2017-04-12 at 6 46 37 am" src="https://cloud.githubusercontent.com/assets/67586/24960817/cea55358-1f4b-11e7-941a-b0a77b042b6c.png">

For inspiration, here's what we see for a Java project:

<img width="388" alt="screen shot 2017-04-12 at 6 49 45 am" src="https://cloud.githubusercontent.com/assets/67586/24961006/51af3426-1f4c-11e7-9ec4-ed4e3e39b5e8.png">

Minimally, we could emphasis the `lib` directory (as the `src` is in Java).

Thoughts welcome!

**Comment by pq** [comment]
#908 proposes this incremental improvement:

![screen shot 2017-04-12 at 12 11 04 pm](https://cloud.githubusercontent.com/assets/67586/24978945/4ecf8e46-1f87-11e7-8c4d-9012e727d4a8.png)

* emphasizes `lib` dir
* tags `.idea` as generated

Comments welcome!

**Comment by InMatrix** [comment]
Is it possible to automatically open the lib folder upon opening/creating a project? That would make it real obvious where your code is.

**Comment by pq** [comment]
Good thinking.  When we create a project we do that.  (We open `main.dart`.)  We may not do that reliably for opened projects though.

**Comment by LarkAscending** [comment]
That's what I did to the screenshot for the codelab - highlighted main.dart
in the left nav.
Good to be in sync...

**Comment by alexander-doroshko** [comment]
I like the idea of having `lib` node expanded and `main.dart` file focused in the Project View when opening a newly created project for the first time. This could be done by project generator - it could add the corresponding state to the generated `.idea/workspace.xml`. Of course on existing project opening, no magic should happen, IDE restores the previous state as it always does.

I don't like the idea of reusing 'source folder' icon for a folder that is not a source folder according to the IntelliJ project model. Unlikely it can greatly help newcomers who do not know icons meaning. OTOH experienced users may be confused by project model and presentation inconsistency. 
Also, suggested change affects non-Flutter Dart projects, but there sources are usually located in multiple folders: `lib`, `web`, `bin`, `tool`, `benchmark`, `example`, etc.

My $0.02.

**Comment by pq** [comment]
As always, thanks for the $0.02 @alexander-doroshko!

My thinking is that the emphasis will help new users since it emphasizes where their source lives.  At a high level it feels very much like what's being done for source folders as captured in the IDEA model.  That said, it would be unfortunate to create any unnecessary confusion.  (Luckily this is something we can at least be mindful of when we do studies.)

My resistance to using another decoration is that it's just another thing and worry that it would be overwhelming especially when in practice the distinction is quite subtle.

Curious though if folks have other thoughts?

(As for folder opening and initial project selection, I think we're in agreement.)

@lukechurch @InMatrix @sethladd @mit-mit @devoncarew

**Comment by devoncarew** [comment]
Would it help to have the `lib/` folder be a source folder, from an IntelliJ perspective? Is this just some metadata for the module that we need to create on module creation?

**Comment by mit-mit** [comment]
Here is the current state:
![image](https://user-images.githubusercontent.com/13644170/27475719-78bc42aa-5806-11e7-9421-f5dec9affb82.png)

Looks like we got the lib folder highlighted @pq? Shall we close this bug?

**Comment by pq** [comment]
Yep. https://github.com/flutter/flutter-intellij/commit/cbea96c9af01cd1e352988d140d2fe0ea520f8fb did that.
