### ISSUE TITLE
Make the project import path work as well as the project open path

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#825]
_From @lukechurch on March 15, 2017 10:1_

If a user selects 'import project' instead of 'open project' from the IntelliJ start page menu and selects a flutter project it seems to cause a lot of problems:

- The dialogs about what kind of project it isn't don't make sense to a Flutter user (gradle?)
- It replaces the iml file

Is it possible to detect that the project being imported should have been opened, and open it anyway?

_Copied from original issue: flutter/flutter#8787_

**Comment by sethladd** [comment]
_From @eseidelGoogle on March 15, 2017 13:58_

I have no data as to if this was just a one-off confusion I saw or if this will be at all common.

**Comment by sethladd** [comment]
_From @lukechurch on March 15, 2017 14:4_

@eseidelGoogle I saw this independently. GS-P4 study participant ran into this.

Given that on a sample of < 100 people we've seen multiple instances, I suspect that it will be fairly common.

**Comment by sethladd** [comment]
_From @pq on March 15, 2017 14:14_

@alexander-doroshko : I'm curious what you think here.  This is a common confusion about what import does vs. open.  It's not strictly wrong what IDEA is doing but people are definitely getting confused.  Thoughts?

**Comment by sethladd** [comment]
_From @alexander-doroshko on March 15, 2017 14:43_

Agree about confusion.
I guess there should be an extension point that we could implement in the Dart and Flutter plugins to detect Dart or Flutter project and handle its importing in the same way as its opening.

**Comment by pq** [comment]
@alexander-doroshko: I'm guessing you're proposing adding a `ProjectImportProvider`?

**Comment by alexander-doroshko** [comment]
Yup.
Another option is to make is obvious that user started with the wrong path clicking 'Import' (the same is File -> New -> Project from existing sources. This is a question to IntelliJ Platform. Pull request or concrete and detailed suggestion in YouTrack would be a good start for this path. However, it might be tricky to suggest a perfect UX on this way.

**Comment by devoncarew** [comment]
@pq recently improved project import.
