### ISSUE TITLE
IntelliJ is taking too long to index on first run of Plugin

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#826]
_From @lukechurch on March 15, 2017 9:47_

After installing the Flutter plugin for the first time we're frequently seeing IntelliJ report that it is 'indexing' for several minutes.

E.g. in a recent study, it took 4 minutes 20s on a 2016 MBP i7, 16Gb RAM, 1Tb SSD. (note that Quicktime screen recording was also running). This experience of multi-minute delays has been repeated across several other studies, often with even longer delays on older hardware.

This is sufficiently long that participants have got to the point where they're trying to write code before it's finished indexing, and sometimes confused as to why some features (e.g. jump to declaration) don't work, so they start trying to 'fix' their setup.

_Copied from original issue: flutter/flutter#8785_

**Comment by sethladd** [comment]
Should we move this over to https://github.com/flutter/flutter-intellij ?

**Comment by pq** [comment]
FYI @alexander-doroshko @jwren

**Comment by alexander-doroshko** [comment]
See idea.log file(s) in Help | Show Log. Grep for "unindexed files update". You'll see how many files were indexed and how long it took. Having this numbers we'll be able to proceed with the issue evaluation.

**Comment by devoncarew** [comment]
To update: @alexander-doroshko has done some work here which should speed up indexing, and improve the typing delay it very large files as well.

**Comment by alexander-doroshko** [comment]
My recent changes improve typing in huge files only, not indexing. Indexing should be already ok. I need "unindexed files update" lines from log to proceed with this issue. If logs prove too long indexing I'll need sample project to reproduce or at least a CPU snapshot.

**Comment by pq** [comment]
@devoncarew I'm thinking this one is stale?

**Comment by MartinHlavna** [comment]
Idea is constantly indexing for few minutes after generating reflection via reflectable lib, which generates some source code via build runner. Biggest problem for me is that I cannot run while I am stuck on indexing.

**Comment by alexander-doroshko** [comment]
@MartinHlavna you may mark folders with generated files as 'excluded' (right-click on it in the Project View). However, you may lose some functionality for these files.

Another option is to pause indexing. The button is to the right from the progress bar. Don't forget to resume later.

But 'few minutes' sounds like quite a while. How many files are generated? How many lines of code in total (or what's the total size in kB)?
