### ISSUE TITLE
(Admin) Normalize Label names.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#827]
As discussed, we've got a few different naming conventions for labels and we should strive for some consistency.

One thought is to make ours parallel those in the Flutter repo closely.  This may also help with issue moving (so metadata sticks).

@devoncarew : thoughts?

**Comment by devoncarew** [comment]
consistency sgtm. I have noticed that some repos choose to not use spaces in labels names; I believe this makes it very slightly easier with manually entering search terms for issues. No strong thoughts on labels names though -

**Comment by pq** [comment]
Cool.  I took a quick pass and normalized ones that have corresponding labels in [Flutter](https://github.com/flutter/flutter/labels).

We can update and tweak as we see fit.
