### ISSUE TITLE
Potential issue with debugging from IDE into iOS simulator

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#828]
From a recent study with developers:

"When using iOS simulator, a breakpoint in the build function for initial main widget of an app would lead an error message. We continued past the breakpoint and the screen was black until the app is restarted. This was reproducing consistently. I suspect there’s a race condition on surface setup that the breakpoint is causing to work out not in our favor."

**Comment by sethladd** [comment]
cc @collinjackson

**Comment by mit-mit** [comment]
Closing; this no longer repros.
