### ISSUE TITLE
Plugin on Windows claims that git is not in the PATH even though it is

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#830]
Git is in the PATH, but Flutter plugin thinks it isn't (see screenshot). This is on Windows.

![bug](https://cloud.githubusercontent.com/assets/1227763/23968303/6ab7d578-097f-11e7-97d9-597ee74bac6e.png)

**Comment by stevemessick** [comment]
We're running `flutter -version` here now.
