### ISSUE TITLE
Code-completion options for children: omit the List as (only) option

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#832]
Not sure exactly what we should do here, but since `List<Widget>` is the only thing I can given to `children:`, should we provide a single code-completion option, when trying to code-complete after `children:` ?

![screen shot 2017-03-16 at 2 39 50 pm](https://cloud.githubusercontent.com/assets/5479/24019769/a81c3616-0a56-11e7-9bc7-f6b34e841a54.png)

I think I would expect a single response, something like: `<Widget>[]` and if I select that, my cursor is inserted in between the brackets.

**Comment by pq** [comment]
I think we could do a slight variation and get us a lot of the way there and maybe make it even simpler for the user.  What if we expanded the `children:` completion here

<img width="522" alt="screen shot 2017-03-16 at 3 10 59 pm" src="https://cloud.githubusercontent.com/assets/67586/24020746/cbc808ac-0a5a-11e7-9240-529ef6d3761a.png">

to produce code like:

    new Row(children: <Widget>[])

Then the wouldn't need to perform a second completion...

How does this sound @sethladd ?

**Comment by stevemessick** [comment]
Do both? I can type children: fast enough I probably wouldn't use the completion.

**Comment by pq** [comment]
> Do both? I can type children: fast enough I probably wouldn't use the completion.

but how fast can you type `children: <Widget>[]`? 😉 

By "do both" do you mean have the `Row` completion fill out the `children:` bits too?  If so, working on that as well!

**Comment by stevemessick** [comment]
What I meant was:
If you're going to complete 'child' then go ahead and insert the empty
list, too.
If you're asking for completion after 'children:' then just insert the list.

**Comment by pq** [comment]
Got it. Cool.  I think we agree!

**Comment by pq** [comment]
Given that we now complete `children:` with an empty `Widget` list, I think this is a non-issue.  In any event, let's see how people get on in the new world and re-visit if needed.
