### ISSUE TITLE
The "hot reload" button and the "restart" button are hard to visually distinguish

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#833]
## Steps to Reproduce

We observed in a user study that the participant clicked the "restart" button while murmuring “Hot reload” to himself. He found hot reload, and used it a couple of times. But after a while he seemed to unconsciously switch to “restart”.

I suggest we redesign the two icons and make them easy to distinguish and remember. 

## Version info

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/taodong/flutter/flutter
    • Framework revision 7b9cefb3be (2 hours ago), 2017-03-09 20:45:40
    • Engine revision 6e54f5e31f
    • Tools Dart version 1.23.0-dev.2.0

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

**Comment by Sfshaza** [comment]
I had this same problem! I was using the wrong button for weeks before I realized.

**Comment by mit-mit** [comment]
This is covered by #803
