### ISSUE TITLE
Feature Request: Gutter bar UI for selecting content

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#835]
During a study the participant was delighted to find the gutter bar content helping them see which colours they had selected etc. However they then wanted to be able to click on the icon/the colour and have a UI appear that helped them selecting new values. e.g. being able to select from a list of icons, or being able to select a colour from a colour picker. At the moment this interacts with breakpoints instead.

See screenshot:

![screen shot 2017-03-24 at 12 19 30](https://cloud.githubusercontent.com/assets/2978182/24293991/5b95d22a-108c-11e7-82e9-5cc4aba8fdc3.png)

**Comment by stevemessick** [comment]
This is fixed for colors. IntelliJ doesn't support icon selection.
