### ISSUE TITLE
Callback function names won't autocomplete

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#836]
I saw this in a recent user study. The problem caused the participant to suspect that he put the callback in a wrong place. This seems to be an IntelliJ problem and I'm not sure if you guys have control over this behavior, but I'll describe it anyway. 

## Steps to Reproduce

1. Create a default starter project
2. Locate this the following lines (83-87):

```
floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
```
3. Remove `_incrementCounter` and then invoke autocomplete by typing `_`
4. You will not see `_incrementCounter` in the list of suggestions:
![image](https://cloud.githubusercontent.com/assets/348942/24317610/12f6c9aa-10b6-11e7-8d3f-d3f9115762d6.png)

## Version info
```

[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/taodong/Code/flutter_repos/flutter
    • Framework revision 51ea62c143 (4 hours ago), 2017-03-24 15:34:43
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/taodong/Library/Android/sdk
    • Platform android-24, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • None
```

**Comment by devoncarew** [comment]
@danrubel, can you take a look?

**Comment by pq** [comment]
AI (@pq): duplicated by #862 ?

**Comment by pq** [comment]
> AI (@pq): duplicated by #862 ?

👍 

Also confirmed on SDK HEAD still no completions for `_incrementCounter`.

**Comment by pq** [comment]
https://codereview.chromium.org/2883363002/: 

![screen shot 2017-05-16 at 11 02 47 am](https://cloud.githubusercontent.com/assets/67586/26120925/457431ac-3a27-11e7-918c-94ca8eebf516.png)

🤘
