### ISSUE TITLE
Improve signature display when jumping to declaration

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#838]
Compare Dart:

<img width="1423" alt="sign" src="https://cloud.githubusercontent.com/assets/67586/24367817/e1464970-12d2-11e7-8613-4ded96f575a3.png">

to Java:

<img width="803" alt="jsig" src="https://cloud.githubusercontent.com/assets/67586/24367873/18117b0a-12d3-11e7-9fb5-3b78aa8e3982.png">

I expect linking elements should be straight-forward?  Otherwise, I wonder what we can do to tame signatures that are super long (as they often are for Flutter).

cc @jwren @alexander-doroshko

**Comment by alexander-doroshko** [comment]
Analysis Server (and its `getHover()` method) doesn't return any info that would help to render links in this tooltip, so the task is not trivial.
As for better presentation - ideas are welcome.

**Comment by jwren** [comment]
Not only is not trivial, it has been an anti-goal of the Dart Plugin to have resolution data.

My suggestion here is that cleaner text info should be passed from the Analysis Server protocol.  Perhaps some new lines for help in the presentation, then on the IJ side we can make sure we present it correctly.

Also, I don't see the hyperlinks in the hover as being super critical.

**Comment by stevemessick** [comment]
Closing as obsolete.
