### ISSUE TITLE
set up a CI system

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#84]
Set up a CI system to:

- analyze the code
- build the plugin
- run tests

and validate that things are good from commit-to-commit.

**Comment by pq** [comment]
A couple resources I stumbled over when I was trying to fix the build:
  * http://blog.xebia.com/building-intellij-plugins-from-the-command-line/
  * http://arhipov.blogspot.nl/2013/10/managing-dependencies-for-intellij-idea.html

Might be handy?

**Comment by pq** [comment]
Can we close #77  in favor of this one?

**Comment by devoncarew** [comment]
Fixed! We have a build running in travis, building against the lastest stable intellij and latest stable dart plugin. (https://travis-ci.org/flutter/flutter-intellij/builds/157941178 - runtime approx. 5 mins)

We'll need to get tests running on travis as well; I'll file a separate issue.

**Comment by pq** [comment]
w00t!

PR to add badge here: https://github.com/flutter/flutter-intellij/pull/97 👯

**Comment by eseidelGoogle** [comment]
If you're looking for information on how to set up continuous integration for your Flutter app https://medium.com/flutter-io/test-flutter-apps-on-travis-3fd5142ecd8c and https://flutter.io/testing/ have more information.
