### ISSUE TITLE
No need for duplicate assist and quick fix

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#841]
With 2017.1 I'm seeing both assists and quick fixes for the same symbol. I don't recall ever seeing this before.
<img width="268" alt="screen shot 2017-03-27 at 2 42 33 pm" src="https://cloud.githubusercontent.com/assets/8518285/24379422/dcf862f8-12fb-11e7-9a06-c67a406353bf.png">
So far we have only one quick fix so there is only one possible dup, but we really should (IMO) display one item with the label "Convert to children:".

**Comment by pq** [comment]
@stevemessick : are you still looking at this one?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/41060
