### ISSUE TITLE
breakpoint ignored after hot reload

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#843]
This is while testing the prerelease for version 12.0, using Bazel integration.

In a hello world:
  - set breakpoint at _counter++
  - press the button.
  - See that it stops at the breakpoint. Resume.
  - Modify some text and hit hot reload.
  - See that the text changed.
  - Press the button. It should stop at the breakpoint but doesn't.

**Comment by skybrian** [comment]
(This isn't in our manual test script; I just happened to try it. So I don't know if it's a regression.)

**Comment by skybrian** [comment]
I don't know how relevant it is, but I see this error shortly after the hot reload. There are breakpoints being set.

```
{"jsonrpc":"2.0",
  "error":{
        "code":106,
        "message":"Isolate must be paused",
        "data":{"request":{"method":"resume","params":{"isolateId":"isolates\/484144288"}}}
      },"id":"54"}
```

**Comment by skybrian** [comment]
The remoteBaseUri is:
/data/user/0/com.example.helloflutter/cache/hello_flutterotrwcv/hello_flutter

So one of the breakpoint URL's we add is:
/data/user/0/com.example.helloflutter/cache/hello_flutterotrwcv/hello_flutter/mobile/flutter/dart/samples/hello_flutter/lib/main.dart

But the location of main is:
/data/user/0/com.example.helloflutter/cache/hello_flutterotrwcv/hello_flutter/lib/main.dart

This appears to be because in the Run Configuration, I set "working directory" to the workspace root. If I set it to the location of the BUILD file containing the Flutter app, it works.

So, I don't think this is a regression. We're just not very clear about how you should set the working directory.

I would guess that most users will get it wrong. It might make more sense to ask them to set the location of main.dart, and calculate the work directory automatically.

**Comment by pq** [comment]
#790 might be related?

**Comment by skybrian** [comment]
Fixed, because the user no longer sets the working directory. (We calculate it from the Dart entry point.)
