### ISSUE TITLE
`Pub get` banner persists after project creation

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#851]
This repros in the latest M12 RC in Idea 2017.1:

1. Install plugin, restart Idea
1. Create a new project
1. Wait until it's done initialising

=> main.dart appears, but has a Pub Get banner:
![screen shot 2017-03-29 at 09 57 33](https://cloud.githubusercontent.com/assets/13644170/24444309/293242ea-1466-11e7-9ea6-ae55d2245301.png)

**Comment by devoncarew** [comment]
I'm unable to repro this in 2017.1. Let's keep the issue open, but given the relative level of impact I don't think it's a M12 bocker.

**Comment by mit-mit** [comment]
I have seen this again several times today

**Comment by mit-mit** [comment]
And I have now seen it on both macOS and Windows. On macOS the banner only stays up for a few seconds, and then disappears. Some kind of timing issue?

**Comment by devoncarew** [comment]
I feel like we've seen (and fixed this) before; /cc @pq.

**Comment by pq** [comment]
I've seen this too but it's not reliably reproducible.

@alexander-doroshko : any thoughts on how we might improve this?  I've seen a similar issue with our module type inspection.  (It appears briefly before disappearing.)  How often does `createNotificationPanel` get called?  Can we skip the update until the project is fully loaded?  (And how would we detect that?)

**Comment by alexander-doroshko** [comment]
'Packages get has not been run' is not an editor notification, it is an inspection, isn't it? I don't have an answer off the top of my head. Need to debug when such inspections are run/rerun and how to control it.

"Wrong module type" in its turn is not an inspection, it is an editor notification. This mechanism is pretty simple, see `EditorNotifications.update*` methods. TL;DR: executed on editor creation and when explicitly asked to.

**Comment by pq** [comment]
Thanks!

**Comment by pq** [comment]
Not able to reproduce.  If anyone else sees this, please re-open!
