### ISSUE TITLE
Flutter plugin installation error: unknown plugin Dart

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#856]
On Windows, with IDEA CE 2017.1:

1. Use a "clean" IDEA with no plugins installed
1. Click 'install plugin from disk' and select the RC .jar

=> This error:

![image](https://cloud.githubusercontent.com/assets/13644170/24497302/41b3ec80-153b-11e7-9c88-c2944d9e1a67.png)

**Comment by mit-mit** [comment]
Also get an error after restarting that Flutter plugin can't find it's dependent plugin

**Comment by mit-mit** [comment]
Does not repro on macOS

**Comment by devoncarew** [comment]
Just to confirm, you do have the Dart plugin installed?

**Comment by mit-mit** [comment]
Yes, I had the Dart plugin installed. But it seems this only repros if you have an older version of the Dart plugin. If I update it to 171.4006 first, then restart, then install the Flutter plugin, then things work OK.

**Comment by skybrian** [comment]
Based on the error message, looks like it comes from [1]. This doesn't look particularly Windows-specific.

[1] https://github.com/JetBrains/intellij-community/blob/6e7540aae6d97e48bc4fd4f19e82f4fb25edf154/platform/platform-impl/src/com/intellij/ide/plugins/InstalledPluginsManagerMain.java#L188

**Comment by devoncarew** [comment]
My guess is that the version of the Dart plugin you had installed was not compatible with 2017.1?

Can we triage this out of M12? I don't think this is a regression in the Flutter plugin or to 12.0 release.

**Comment by mit-mit** [comment]
Yes, we can! I just tested again on Windows: Uninstalled both Dart and Flutter, and then installed Flutter from repositories and it correctly triggered the install of Dart.
