### ISSUE TITLE
Flutter plugin looses Flutter SDK setting when File->Opening a project

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#859]
This is a 100% repro with these steps in 2017.1:

1. Install RC plugin
1. Create a new project 'project1' with IntelliJ

=> Everything works as expected

1. In the terminal, `flutter create project2`
1. Back in IJ, File->Close all open projects, then click 'Open' and select project2

=> Get this banner:

![image](https://cloud.githubusercontent.com/assets/13644170/24500524/014c6b12-1546-11e7-8cea-b841d8987c1a.png)

And importantly, after this, File>Settings will no longer take the Flutter SDK path setting; when you add one and press Apply it just gets removed again. The only fix I have found to uninstall the plugin, restart, install again.

**Comment by mit-mit** [comment]
Reproed on both macOS and Windows.

**Comment by alexander-doroshko** [comment]
probably #844

**Comment by devoncarew** [comment]
@mit-mit, the workaround for the apply problem is in our known issues list: https://github.com/flutter/flutter-intellij#known-issues

**Comment by mit-mit** [comment]
I'm OK with existing projects requiring an extra step to open. But it seems really bad that after doing this, you can't even manually fix your SDK settings.

**Comment by mit-mit** [comment]
Also, this is now some arbitrary old project. This is a project created with `flutter create` updated to master. If additional settings are needed now, we should get the template updated.

**Comment by devoncarew** [comment]
> you can't even manually fix your SDK settings

You can fix them; the workaround is to use the Dart SDK settings page. This is still a bug, but there is a workaround.

> we should get the template updated

Yes, agreed.

**Comment by devoncarew** [comment]
> after this, File>Settings will no longer take the Flutter SDK path setting; when you add one and press Apply it just gets removed again

https://github.com/flutter/flutter-intellij/pull/865 should address that issue

**Comment by devoncarew** [comment]
The `flutter create` path should be helped by this PR: https://github.com/flutter/flutter/pull/9131.

**Comment by devoncarew** [comment]
@mit-mit, good to close?

**Comment by mit-mit** [comment]
Yup, seems to work now, closing
