### ISSUE TITLE
Missing code completion on _incrementCounter

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#862]
Repro steps:

1. Create a new Flutter project in IDEA 2017.1
1. Delete lines 79-81
1. Inside `Center(` type `new Fla` and press Tab and get the expected completion to `new FlatButton(onPressed: null)`
1. While `null` is still selected, type `_`

=> Would expect to be offered a code completion to `_incrementCounter` but no such completion is offered

**Comment by mit-mit** [comment]
@devoncarew do you think this is analyzer or IJ? (Or me missing something?)

**Comment by pq** [comment]
cc @danrubel

**Comment by pq** [comment]
AI(@pq): investigate if this still repros on SDK head.

**Comment by pq** [comment]
Confirmed.  On SDK HEAD, still no completions for `_incrementCounter`.

**Comment by pq** [comment]
Duplicate of #836.
