### ISSUE TITLE
Color indicator in gutter doesn't work with new short color syntax

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#866]
From @mravn-google:

![screen shot 2017-03-31 at 11 51 01](https://cloud.githubusercontent.com/assets/13644170/24545668/568d07ea-1608-11e7-9af0-3dc94a7d1cc4.png)

**Comment by devoncarew** [comment]
We don't work with a color swatch (`red`), but do with a specific color (`red[500]`). That said we should definitely add support for this.
