### ISSUE TITLE
Point IDE at flutter repo, modifies flutter_tools.iml

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter-intellij#867]
If I open the root of my copy of the packages/flutter_tools/flutter_tools.iml ends up modifed

```
git status
...
Your branch is up-to-date with 'upstream/master'.
...

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   packages/flutter_tools/flutter_tools.iml
```
The diff refers to a non-existent directory:
```
diff --git a/packages/flutter_tools/flutter_tools.iml b/packages/flutter_tools/flutter_tools.iml
index 2efda708b..bacc36a42 100644
--- a/packages/flutter_tools/flutter_tools.iml
+++ b/packages/flutter_tools/flutter_tools.iml
@@ -41,6 +41,7 @@
       <excludeFolder url="file://$MODULE_DIR$/test/src/base/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/src/ios/packages" />
       <excludeFolder url="file://$MODULE_DIR$/test/src/packages" />
+      <excludeFolder url="file://$MODULE_DIR$/test/src/runner/packages" />
       <excludeFolder url="file://$MODULE_DIR$/tool/packages" />
     </content>
     <orderEntry type="inheritedJdk" />
```

```
find . -name runner
./packages/flutter_tools/test/src/runner
./packages/flutter_tools/lib/src/runner

ls ./packages/flutter_tools/test/src/runner
flutter_command_test.dart
```

It seems like this shouldn't happen. Flutter and my IDE are up to date ("check for updates" says there aren't any updates).

**Comment by devoncarew** [comment]
My guess is that the file `packages/flutter_tools/test/src/runner/flutter_command_test.dart` was added to the repo recently, and that `flutter_tools.iml` hasn't been updated w/ the change. The `runner/packages` exclusion in that file is for a potential packages dir - it doesn't have to exist for IntelliJ to want to create that exclusion (just the parent `runner/` dir).

We're tracking the the issue to reduce the amount of SCM churn in this jetbrains issue: https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FWEB-25293.

**Comment by HansMuller** [comment]
The latest IDE still modifies `flutter_tools.iml` and now also modifies:

```
examples/flutter_gallery/android/app/src/main/java/
examples/flutter_gallery/ios/Runner/PluginRegistry.h
examples/flutter_gallery/ios/Runner/PluginRegistry.m
```

**Comment by devoncarew** [comment]
@HansMuller, I think the issue with the new files you're running into is discussed at the end of this bug: https://github.com/flutter/flutter/issues/9299.

**Comment by devoncarew** [comment]
(but we should update the .iml files as well)

**Comment by HansMuller** [comment]
This problem seems to have gotten worse. Now when I open the entire flutter repo the following files are reported as modified:
```
Your branch is up-to-date with 'upstream/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   dev/bots/bots.iml
	modified:   dev/devicelab/devicelab.iml
	modified:   examples/flutter_gallery/flutter_gallery.iml
	modified:   examples/hello_world/hello_world.iml
	modified:   packages/flutter/flutter.iml
	modified:   packages/flutter_driver/flutter_driver.iml
	modified:   packages/flutter_markdown/flutter_markdown.iml
	modified:   packages/flutter_test/flutter_test.iml
	modified:   packages/flutter_tools/flutter_tools.iml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	examples/flutter_gallery/android/app/src/main/java/
	examples/flutter_gallery/ios/Runner/PluginRegistry.h
	examples/flutter_gallery/ios/Runner/PluginRegistry.m
```

Running the latest version as far as I know:
```
IntelliJ IDEA 2016.3.1
Build #IC-163.9166.29, built on December 9, 2016
JRE: 1.8.0_112-release-408-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by devoncarew** [comment]
Ah, the files committed are for `2017.1` - looks like you're on `2016.3.1`. I believe the version of IntelliJ that you're on will be upgraded early next week.

**Comment by devoncarew** [comment]
I filed https://github.com/flutter/flutter/issues/9460 to take care of those untracked files; I'm not sure if we want to commit them or gitignore them.

**Comment by pq** [comment]
Given the resolution of https://github.com/flutter/flutter/issues/9460, is this safe to close?

**Comment by devoncarew** [comment]
Yup, the soon-to-be-released Dart plugin will reduce the churn quite a bit.

**Comment by gspencergoog** [comment]
Reopening because this is still a problem.  I have a bunch of .iml files that are immediately modified when I open a newly-cloned repo in Intellij:
```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   dev/bots/bots.iml
	modified:   dev/devicelab/devicelab.iml
	modified:   examples/flutter_gallery/flutter_gallery.iml
	modified:   examples/hello_world/hello_world.iml
	modified:   packages/flutter/flutter.iml
	modified:   packages/flutter_driver/flutter_driver.iml
	modified:   packages/flutter_test/flutter_test.iml
	modified:   packages/flutter_tools/flutter_tools.iml

no changes added to commit (use "git add" and/or "git commit -a")
```
Can we put them into the .gitignore and just update them occasionally when a new package is added?  Can we automate updating them by just opening a recent IntelliJ on a newly-cloned repo every so often and committing the changes?

**Comment by devoncarew** [comment]
This will still be an issue for 2017.1 versions of intellij - the fix was in the version of the dart plugin that's compatible with 2017.2. (the internal intellij is still on 2017.1, so you'll still see it with that version).

**Comment by yjbanov** [comment]
I've been using 2017.2 for a while and it hasn't touched my `.iml` files, until today. I reopened IntelliJ today and saw this diff applied to some of my `.iml` files:

```diff
$ git diff examples/flutter_gallery/flutter_gallery.iml
diff --git a/examples/flutter_gallery/flutter_gallery.iml b/examples/flutter_gallery/flutter_gallery.iml
index fe958dffb..6beca6a06 100644
--- a/examples/flutter_gallery/flutter_gallery.iml
+++ b/examples/flutter_gallery/flutter_gallery.iml
@@ -8,7 +8,7 @@
       <excludeFolder url="file://$MODULE_DIR$/build" />
     </content>
     <orderEntry type="sourceFolder" forTests="false" />
-    <orderEntry type="library" name="Dart Packages" level="project" />
     <orderEntry type="library" name="Dart SDK" level="project" />
+    <orderEntry type="library" name="Dart Packages" level="project" />
   </component>
-</module>
+</module>
\ No newline at end of file
```

Workaround: I closed IntelliJ, reverted the `.iml` files then opened again and so far it has not applied this change again 🤞

**Comment by devoncarew** [comment]
The iml files are now ignored.
