### ISSUE TITLE
we should have an easy way to open XCode from a flutter project

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#880]
- in the Tools > Flutter menu
- as a context menu item off the <project>/ios directory

**Comment by pq** [comment]
First cut in #1079.  We can swizzle UI bits around as needed.

Navigator:

![image](https://cloud.githubusercontent.com/assets/67586/26505237/d0ded38c-41fc-11e7-9f8b-f31071a25ca9.png)

Top-level menu:

![image](https://cloud.githubusercontent.com/assets/67586/26505266/ee2a692e-41fc-11e7-8dae-64bf3cb7d3b6.png)

**Comment by pq** [comment]
From @mit-mit , it looks like we're opening the wrong project... Look at:  

 https://flutter.io/platform-plugins/#ios-platform-code-hmswift

for details.

**Comment by pq** [comment]
@mit-mit : I may have misunderstood when we chatted earlier.  Could you verify?  Currently, given a project called `hello_world`, this action will open `hello_world/ios/Runner.xcodeproj`.  Is that correct?

**Comment by mit-mit** [comment]
Sorry, I answered out of context. The issue is that it depends on whether you are editing a Flutter app, or a Flutter plugin. For an app, you have it right. For a plugin, you need to open the native projects for the `/example/` app located *inside* the plugin project.

**Comment by pq** [comment]
Ah OK, thanks.  Let's follow-up on plugin support in another set of issues.

**Comment by mit-mit** [comment]
@pq did you open that second bug?

**Comment by pq** [comment]
No.  Feel free to open plugin support enhancements.  I'm guessing there will be a host of them...
