### ISSUE TITLE
Remove working directory field from run config?

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#882]
The SDK run config asks for the file containing main() and also asks for a working directory.

But usually you can find the Flutter application's directory by looking for 'lib' in the ancestors of the main file. (You don't even need the pubspec.yaml file, though we look for that too.) I suppose main.dart could be outside lib but still within a directory containing pubspec.yaml, though that seems rare too.

I'm wondering if we should just drop the working directory field altogether and require that main.dart either live within a "lib" directory, or live above a pubspec.yaml file. Is there any reason the user would need to override this?

Rationale: one less thing for the user to think about, and one less corner case to handle in the code.

**Comment by skybrian** [comment]
@mit-mit

**Comment by mit-mit** [comment]
Sounds good to me. I don't think the terminal tools have any notion of a 'working directory' either, just a target you are running. From a bit of experimenting:

1. `flutter create testmain`
1. `mv lib lib2`
1. `flutter run`
    =>`Target file "lib/main.dart" not found.`
1. `flutter run -t lib2/main.dart`
    => works fine

**Comment by skybrian** [comment]
Well, every command line tool has the working directory provided by the shell; it's less meaningful for IDE's though.

If we look for either a pubspec.yaml or a BUILD file, I think that will cover all the cases. Maybe look for a .packages file too.

**Comment by mit-mit** [comment]
What I meant was: I don't think the flutter terminal tool actually *uses* the working directory for anything.

**Comment by skybrian** [comment]
Actually, it seems to be picky about this. If I run it from a different directory it doesn't find pubspec.yaml:

```
$ cd lib
$ ../../../bin/flutter run main.dart 
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
```

Similarly if I go to a a higher directory. It's not a big deal though, if we find the app dir and pass it in.

**Comment by devoncarew** [comment]
done?

**Comment by skybrian** [comment]
Done.
