### ISSUE TITLE
Rename wrap assist to 'Wrap with new widget'

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#889]
The 'wrap new-expression with new widget' assist is inconsistently named compared to the 'wrap widget list with new widget' assist, and new-expression is a little too language specific.

Can we rename it to 'wrap widget with new widget'?

**Comment by stevemessick** [comment]
That's pretty easy. What about renaming both 'wrap' assists to 'Wrap with new widget'? I like shorter names.

The only drawback I see is that having some specificity to the name might help people new to Flutter remember where these (undiscoverable) assists are to be found.

**Comment by mit-mit** [comment]
Shortening the names sounds good to me

**Comment by devoncarew** [comment]
So, from:

- `wrap new-expression with new widget`
- `wrap widget list with new widget`

to:

- `Wrap with new widget`
- `Wrap with new widget`

?

**Comment by mit-mit** [comment]
Yes, each of them show up in different contexts, but do the same, so having
the same name makes sense to me

**Comment by stevemessick** [comment]
I think using the same name makes it easier to explain, too. And if we come up with other cases that ought to support re-parenting we can just use the same name there, as well.

**Comment by mit-mit** [comment]
I still see the old name in M13 RC:
![screen shot 2017-04-19 at 12 30 44](https://cloud.githubusercontent.com/assets/13644170/25175682/09aa2fe0-24fc-11e7-827d-dca53b9128ea.png)

**Comment by stevemessick** [comment]
The name is determined by the Dart SdK, not the Flutter plugin. As of today, it is still not in the dev channel release, but is in the bleeding-edge build.
