### ISSUE TITLE
breakpoint stops working if you hot reload while stopped at it

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#892]
Reproduced on Mac with iOS simulator.

To reproduce:
  - create a new Flutter app (click counter)
  - change some text and use hot reload (warmup)
  - set breakpoint at _counter++
  - press the button (to stop at the breakpoint)
  - while stopped, edit something and choose hot reload
  - continue from breakpoint
  - press button again. It doesn't stop.
 
Removing the breakpoint and adding it back again fixes the problem.
It seems to only happen if you set the breakpoint *after* the first hot reload.

**Comment by skybrian** [comment]
Reproduced with 12.1. Sometimes it takes a couple tries.

**Comment by jacob314** [comment]
This has been fixed. Verified it is working with the latest build.
