### ISSUE TITLE
spurious problem report: "invalid item 'Dart SDK' in the dependencies list"

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#914]
To reproduce, create a Flutter app from the command line:

```
flutter create click
```

Then open in IDEA and go to Project Structure. The "Problems" tab is highlighted with one problem. If you click on it, you see a message:

```
Module click: invalid item 'Dart SDK' in the dependencies list
```

This can be fixed by editing click.iml and removing the application-level Dart SDK.

Assuming we only support 2017.1 from now on, perhaps we should remove the application-level SDK from any .iml templates and checked-in files for sample projects?

**Comment by skybrian** [comment]
Thanks! Should we do these too?
https://github.com/flutter/flutter/commit/9493df2da8975c68feaf99476febf11e5185a2ec

**Comment by pq** [comment]
Yeah.  Working on it! 👍
