### ISSUE TITLE
Research approaches to android emulator interop

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#923]
Feasibility work for #536.

**Comment by mit-mit** [comment]
@pq any news?

**Comment by pq** [comment]
Not yet.  Adding to the current milestone.

**Comment by devoncarew** [comment]
from a discussion:

- listing emulator devices is easy; we should do this
- opening existing emulators is easy, we should also do this
- creating an emulator is error prone and requires a lot of configuration; even adding a 'you have no emulators create; follow this link for the instructions to create one' would lead to a link requiring a lot of knowledge and steps to create an emulator

For now, we should prefer (in documentation) android devices and the iOS simulator.
