### ISSUE TITLE
projects without Flutter project metadata don't open properly

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#927]
Seen when testing this:

https://github.com/flutter/flutter-intellij/blob/master/testing.md#project-open-verification

when following those steps, the project opens, but no Flutter SDK is assigned, and I don't believe the project has a Dart nature. To remedy I had to go into the Flutter settings and set up a sdk.

I believe this regressed when we moved to 2017.1 and per-project SDKs. When creating flutter metadata for a project, we should assign an SDK.

**Comment by pq** [comment]
Yeah.  I was looking at this too.  Things are a little different in the new world where SDKs are project-scoped.  I'm digging around to see if there's a quick fix.
