### ISSUE TITLE
Refactor daemon process management

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#93]
The flutter daemon process manager should be a long-lived process. It does not necessarily have to run forever, like the Dart analyzer process, but that might be the simplest model. The current model of starting flutter each time the user wants to run or debug an app is too limiting. The daemon should be allowed to manage multiple devices and apps, and the IntelliJ manager should work with it, rather than control it so tightly.

**Comment by devoncarew** [comment]
implemented!
