### ISSUE TITLE
Delay after hitting Run/Debug and seeing any feedback

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#931]
This was reproed with M13 RC on Windows with IDEA 2017.1 Not sure if it's a regression.

After I hit Run or Debug, several (~5) seconds pass before I see any feedback in the Console and window chrome.

**Comment by pq** [comment]
@devoncarew to take a look and triage.

**Comment by skybrian** [comment]
I created a bug for this on the flutter side:
https://github.com/flutter/flutter/issues/9435

I think this is a flutter issue, but as a workaround, it would be easy enough to print a message to the console immediately after opening it.

**Comment by devoncarew** [comment]
Thanks! Will address in the flutter repo.
