### ISSUE TITLE
disable hot reload icon when there are no changes?

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#932]
Seems like we should give the user feedback as to whether there are any changes that are not hot-reloaded into the currently running Flutter App. One possibility would be to disable the lightning bolt when there are no changes to make.  So, behavior would be that it starts out greyed out, you type something, the lightning bolt lights up, and then you know to press it to see your changes in the app, and this becomes a way to train users to press the lightning bolt.

So the UI is simple. However, behind the scenes, calculating whether there are changes to make might be tricky.

**Comment by devoncarew** [comment]
Interesting idea; https://github.com/flutter/flutter-intellij/issues/896 seems related.

**Comment by InMatrix** [comment]
If we can reliably do this, I think it will help users discover Hot Reload and provide feedback to signal a hot reload is completed. The latter was an issue observed in the most recent study session where the participant complained that he had to look for clues of completing a hot reload in the console.  It's hard to tell when there were messages from previous hot reloads in the console.

**Comment by devoncarew** [comment]
I'm going to close this in favor of the issue to badge the hot reload icon when there are changes. I  think that will accomplish the same thing as this issue in terms of drawing the user's eye to the reload icon.
