### ISSUE TITLE
IntelliJ should support creating plugins

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#936]
We have completed enough of the plugin story, that you can now publish plugins. Thus, it would be great if we could add support for creating plugins (this is the `--plugin` arg to `flutter create`) in IntelliJ.

**Comment by devoncarew** [comment]
Sounds like this would be a new project creation wizard. We'd want to make sure that we emphasized the regular (non-plugin) wizard, as I suspect that will be the 90% use-case and the one that all new users should choose.

**Comment by mit-mit** [comment]
@stevemessick is this the same as https://github.com/flutter/flutter-intellij/issues/1187 ?
