### ISSUE TITLE
Add a stful-page live template

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#940]
## Suggestion
Add a stful-page live template. 

https://gist.github.com/branflake2267/3a27c6597bf8e1819228178b924f433c - source
https://www.youtube.com/watch?v=Me7n92nH6FY&index=13&list=PLBbgqtDgdc_RUWUCInIqxpY--C94C6Xjh - used in this video

## Version info
13

## Example
Something like this would be useful for creating pages quickly. 
```
class $NAME$ extends StatefulWidget {
  $NAME$({Key key, this.title}) : super(key: key);

  static const String routeName = "/$NAME$";

  final String title;

  @override
  _$NAME$State createState() => new _$NAME$State();
}

/// // 1. After the page has been created, register it with the app routes 
/// routes: <String, WidgetBuilder>{
///   $NAME$.routeName: (BuildContext context) => new $NAME$(title: "$NAME$"),
/// },
///
/// // 2. Then this could be used to navigate to the page.
/// Navigator.pushNamed(context, $NAME$.routeName);
///

class _$NAME$State extends State<$NAME$> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Container($END$),
      floatingActionButton: new FloatingActionButton(
        onPressed: _onFloatingActionButtonPressed,
        tooltip: 'Add',
        child: new Icon(Icons.add),
      ),
    );
  }

  void _onFloatingActionButtonPressed() {
  }
}
```

**Comment by devoncarew** [comment]
I watched your video last night! Very cool.

/cc @stevemessick who wrote our IntelliJ live templates. My only concern would be whether this template is a common use case (as in, would be used roughly as frequently as the three we have currently), and whether this impl is what we'd want the template to look like. @Hixie and @HansMuller would be good resources for that info :)

**Comment by branflake2267** [comment]
Thanks. Those thoughts had occurred to me as well, one of the reasons I figured it'd be great to just show how to do it. You're teams would have a better feel for the best implementation, but I have a feeling having a stful-page could be useful. I'll let that boil it self out. 

I have noticed that none of the page implementations are consistent between the samples, and could be nifty to help guide a consistency, and maybe more time is needed to get there. Now folks are asking about MVC, and so I wonder how that my play apart. Like using the flux api too. Best of luck, on thinking about how you want to guide the process.

**Comment by stevemessick** [comment]
Wow, another excellent video! Thanks for doing that. I'd really like to see more people using live templates. My initial hope was to show how to create `stful`, etc. and let everyone do their own, with the expectation that more and better templates (like `stful-page`) would be created. I think a lot of people don't want to bother with creating templates, though. I wonder if there is a simple way to share files that define templates and can just be dropped into an IntelliJ installation?

If it looks like enough people would use (some version of) `stful-page` I'd have no problem adding it to the pre-defined set. The trade-off is that each new template increases the pop-up menu length. But this one is so complex that, if useful, it would easily earn a place. My totally uninformed opinion is this one would get a lot of use. I'd like to hear what people who write real Flutter apps have to say.

**Comment by alexander-doroshko** [comment]
> I wonder if there is a simple way to share files that define templates and can just be dropped into an IntelliJ installation?

File -> Export Settings (uncheck all except Live Templates), File ->Import Settings.

**Comment by branflake2267** [comment]
Thanks @stevemessick. Good tips on sharing with export/import. The patterns are young, it'll be fun to see how they grow.
