### ISSUE TITLE
Cannot find runner for flutter

### ISSUE THREAD

**Issue by thosakwe** [flutter/flutter-intellij#943]
## Issue
I cannot execute any Flutter run configurations - the run button is disabled. When I used Alt+Shift+F10 to force run, I saw the underlying error: "Cannot find runner for angel_flutter".

So, for some reason, there is no runner available for the run configuration. I have also created other configurations, and receive the same result every time.

I don't know what a "runner" is here, but it's missing. No idea why.

## Steps to Reproduce
1. Create an IntelliJ (using WebStorm 2017.1 here) project, with more than one Dart project in it.
My structure right now:

```
backend/ - Backend server with Angel framework
client/ Virtually untouched base Flutter app from 'flutter create' - just changed title, added one dependency
common/ - Shared model files
```
See the project: https://github.com/angel-example/flutter

## Version info
```
[✓] Flutter (on Mac OS X 10.12 16A323, channel alpha)
    • Flutter at /Users/tobe/flutter
    • Framework revision 70536223ee (8 days ago), 2017-04-14 10:37:19 -0700
    • Engine revision c24a0e5175
    • Tools Dart version 1.23.0-dev.11.7

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /Users/tobe/Library/Android/sdk
    • Platform android-24, build-tools 24.0.1
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      To install, run:
        brew update
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[-] Android Studio (version 2.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Gradle version 2.14.1 required. Found version 2.10.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[-] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] WebStorm (version 2017.1)
    • Flutter plugin version 13.0

[✓] Connected devices
    • LG K330 • LGK3302f6a56ec • android-arm • Android 5.1.1 (API 22)
```

I have since upgraded to Dart `1.23.0`, not sure if that has anything to do with it.

`ideviceinstaller` is actually installed - I've installed it literally dozens of times, but it always reports that.

**Thanks in advance!!!**

**Comment by mit-mit** [comment]
Looking at the git repo, looks like you have three elements here: 2 dart (backend and common) and 1 flutter (client)?

I believe what you need is an IntelliJ project with three modules in it; 2 dart modules and 1 flutter module. I also believe this is only supported in IDEA, and not WebStorm. @devoncarew can you confirm?

Also note that you need to install the Flutter and Dart plugins into your IDEA; looks like they are missing.

**Comment by devoncarew** [comment]
As @mit-mit, said, I would confirm in your IntelliJ that you have the Dart and Flutter plugin installed, that you have version 13.0 of the Flutter plugin, and then would create a new launch configuration for your flutter app, and connect a device or start the iOS simulator. With all that, you should see a device pulldown on the IntelliJ toolbar, and when the Flutter launch configuration is selected, the run and debug buttons should be enabled.

**Comment by thosakwe** [comment]
@mit-mit @devoncarew I have both plug-ins. I'll try this in IntelliJ IDEA, though, maybe it doesn't work for WebStorm.

Also, @devoncarew, my phone was connected while I was receive these errors. I'll try again with the iOS Simulator running, hopefully that will work.

**Comment by thosakwe** [comment]
Update: There's actually nothing wrong with the project configuration.

It turns out that you can't run a Flutter application unless it is at the root of your application. Please correct me if I am wrong.

I have mine in `client/` and thus have to run it via the command-line.

**Comment by mit-mit** [comment]
@thosakwe not sure I fully understand what is not working for you. The following works for me:

1. Start IntelliJ IDEA
1. File > New > Project
1. Select Flutter, click Next
1. Set Project name to `ProjectOne`
1. Expand More Settings, and change Module name to `client`. Leave remaining values as they are. Hit Finish
1. Run > Edit Configurations, rename from main.dart to `client`
1. File > New > *Module*
1. Select Dart + console template
1. Change module name to `server`, and hit Finish
1. Run > Edit Configurations, expand Dart, rename from main.dart to `client`

=> you can now either launch client or server by selecting the config and hitting Run or Debug

**Comment by thosakwe** [comment]
Okay, thank you! I'll have to run this in IDEA, rather than WebStorm.

**Comment by omar1betar** [comment]
you can try this ,
tools>> flutter>> flutter packages get >>*enter your flutter sdk path* >>finish .

**Comment by helenkapatsa** [comment]
Each time this thing happens in my Android Studio, I restart IDE and make it update, as well as Flutter and Dart plugins. Bad UX, of course.

**Comment by sart1991** [comment]
> you can try this ,
> tools>> flutter>> flutter packages get >>_enter your flutter sdk path_ >>finish .

this will get you to a configuration window, where you can select the location of the flutter installation. this will do the trick in some cases
