### ISSUE TITLE
IntelliJ appears to hang after last step in New Project wizard

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#946]
I think this is a recent regression; I don't recall exactly when I started seeing this:

1. Start IJ, and close all projects so you are at the Welcome dialog
1. File > New Project
1. Next on Flutter path
1. Enter name, click Finish

=> The New Project dialog disappears and Welcome dialog appears. Nothing happens for ~ 10 seconds. New Project then suddenly appears.

**Comment by devoncarew** [comment]
Is it consistent? It's likely that flutter_tools is doing some one-time work, like downloading a new Dart sdk.

**Comment by mit-mit** [comment]
Yes, it's consistent. I.e., I can create a project, run it (and by now everything should be initialized). and the run the repro steps and see the delay.

**Comment by mit-mit** [comment]
This still repros. I have made sure I can run `flutter doctor`, etc. in the terminal and nothing is pending there.

**Comment by devoncarew** [comment]
Update on this: this happens for `pub get` is slow - likely for slower connections or for when the pub server is acting up. We have a fix for this in master already - we do a better job of showing progress during project creation. This will be pushed out in an M13.1 patch.

**Comment by gmalagutti** [comment]
When I create a new project the dialog 'Creating Flutter Project' pops up but then nothing happens, also after 10 minutes.
Note that I have an issue with flutter that I can't solve:
✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
If I try to install it looks like it did - no error messages - but next time I run flutter doctor CocoaPods is still missing. Both issues are frustrating because I don't really know what to do

**Comment by gmalagutti** [comment]
OK, for everybody else this line solved the issue on my Mac, executed from the installation folder of flutter
sudo chmod -R 777 *
