### ISSUE TITLE
Packages get runs off stale file info

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#947]
It appears that 'packages get' in IJ on the `pubspec.yaml` file runs off the last explicitly saved file, not the current file contents at the time the button is pressed.

This was highly surprising; @szakarias had concluded that the button was likely entirely broken until we figured out that is what was happening.

## Steps to Reproduce

1. Create a new project in IJ
1. Open `pubspec.yaml`
1. Hit Packages Get

=> succeeds as expected

1. Replace:
```
  flutter:
    sdk: flutter
```
with:
```
  flutter:
    sdk: flutter
  url_launche:
```
1. Hit Packages get

=> succeeds, but url_launcher is not listed under Dart Packages in the External Libraries node

1. Hit cmd-s
1. Hit Packages get

=> pub get failure

1. Correct `url_launche:` to `url_launcher:`
1. Hit Packages get

=> still fails

1. Hit cmd-s
1. Hit Packages get

=> finally succeeds

**Comment by mit-mit** [comment]
Marking this as I/O adoption blocker, as codelabs will use plugins and this require edits to `pubspec.yaml`.

**Comment by alexander-doroshko** [comment]
You need to invoke `FileDocumentManager.getInstance().saveAllDocuments();` before calling any command line tool that reads files from the disk.
For example 'pub get' action provided by the Dart plugin does it here: https://github.com/JetBrains/intellij-plugins/blob/c9e52bf8c08c1d592d3497e98fae8538594b6280/Dart/src/com/jetbrains/lang/dart/ide/actions/DartPubActionBase.java#L190

**Comment by devoncarew** [comment]
Sounds like this will be an easy fix. We'll just want to determine whether it makes sense to save all files before every flutter tool operation.
