### ISSUE TITLE
automatically open lib/main.dart

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#952]
After creating a new project or opening an example, automatically opening lib/main.dart would help new users know what to do.

**Comment by devoncarew** [comment]
We try to, by writing some metadata to the workspace file (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/.idea/workspace.xml.tmpl#L5), but a more consistent mechanism would be good.

**Comment by skybrian** [comment]
Okay, I vaguely remember this happening before and it isn't happening now. I think this regressed and it had something to do with changes to the project open code.
