### ISSUE TITLE
Simulator or device detection is not occurring.

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#954]
The IOS emulator and AVD emulators are not getting detected. So I can't debug with the IDE. 

## Steps to Reproduce
1. Create a new flutter app in intellij

## Version info
```
/Users/branflake2267/git/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision 21f57a85e8 (5 hours ago), 2017-04-25 17:40:28 -0700
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.0

[✓] Connected devices
    • iPhone SE • 1C15BC7F-DA25-4E71-B479-B601B549CAA0 • ios • iOS 10.3 (simulator)
```

![screen shot 2017-04-25 at 10 35 06 pm](https://cloud.githubusercontent.com/assets/1326504/25419469/bdd01f24-2a07-11e7-8090-2c4115713026.png)

## Workaround
I can use `flutter run` as a workaround.

**Comment by branflake2267** [comment]
When I created a couple more projects I notice these issues:

![screen shot 2017-04-25 at 11 05 29 pm](https://cloud.githubusercontent.com/assets/1326504/25420223/f5be35ac-2a0b-11e7-8a9d-51b074246b34.png)

![screen shot 2017-04-25 at 11 05 14 pm](https://cloud.githubusercontent.com/assets/1326504/25420225/f790b4fe-2a0b-11e7-8282-8bb5541a857f.png)

**Comment by daharper** [comment]
I have the same problem on Linux:

![image](https://cloud.githubusercontent.com/assets/2164086/25444784/ebb0a0e4-2ade-11e7-9d12-1af914dff019.png)

The Atom Editor is also unable to detect the devices.

I have two devices:

1. GenyMotion
2. Samsung Note 3 Phone

Flutter doctor can detect both, and flutter run is able to successfully deploy to both devices.

**Comment by devoncarew** [comment]
Thanks for the report! We're tracking over in https://github.com/flutter/flutter/issues/9612; closing this as a dup.

**Comment by sajjadyousefnia** [comment]
why wy flutter cant detect Genymotion virtual device?
