### ISSUE TITLE
hot reload doesn't work when stopped at a breakpoint

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#969]
To reproduce:
  - create a new Flutter project
  - set a breakpoint at _counter++;
  - launch in debugger
  - press button to stop at breakpoint
  - press hot reload icon

At this point, a background task spins: "Intializing hot reload..." and that Flutter app is still frozen. Pressing "Resume Program" doesn't help.

A message is logged:
```
[ 984658]   WARN - o.flutter.run.daemon.DaemonApi - Flutter process returned an error: {"id":1,"error":"TimeoutException: Request to Dart VM Service timed out: _flutter.listViews({})"} 
```

Versions:
----

Flutter plugin at HEAD, 
```
$ flutter --version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 1d6a8249f8 (4 days ago) • 2017-04-27 13:34:48 -0700
Engine • revision c0f1e3b47b
Tools • Dart 1.23.0-dev.11.11
```

**Comment by devoncarew** [comment]
This has been working. My guess here is that we could bisect this to a commit in flutter_tools, which introduces a call to `listViews()`, or changes the timing of when it's called.

**Comment by skybrian** [comment]
I tried some different flutter SDK version.

Broken with:
 head ffa8483f3b4d7be09e6d4e5076c580a7780e3b62
 12 days ago: 311d35354a94c51a9a21375d713e6e5b24001682

It worked a month ago: ab6df3af40495c00f5a56013edecc212877d0d08

First guess is that it has something to do with redoing "flutter run" to use Gradle?

**Comment by skybrian** [comment]
The culprit seems to be: https://github.com/flutter/flutter/commit/71d80fbd3f788e8cf7c53c8d28100a24d6a1865e

Reverting it fixes the bug.

**Comment by devoncarew** [comment]
Good find. We shouldn't call refreshViews() if we're paused. There already code (a bit further down in that method) that checks the pause state.
