### ISSUE TITLE
IntelliJ choosing indent of 4 spaces when 2 is more appropriate

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter-intellij#970]
In https://www.youtube.com/watch?v=Kg6wo50XOkg#t=01m05s, a Flutter user is adding a constructor argument to an existing list of argumentss that are all indented 2 spaces (due to trailing comma).  Yet when he inserts a newline, IntelliJ indents it 4 spaces.  When he hits backspace to remove the two superfluous spaces, it backs him up to the previous line, which is not what he wanted.

**Comment by devoncarew** [comment]
I can repo this. If you hit return after `Scaffold(`:

```dart
  Widget build(BuildContext context) {
    return new Scaffold(drawer: null,
      body: new Text('Button tapped'),
    );
  }
```

you see the (undesired) 4 space indent. If you hit return after `Scaffold(` here:

```dart
  Widget build(BuildContext context) {
    return new Scaffold(
      drawer: null,
      body: new Text('Button tapped'),
    );
  }
```

The indent is correct - you do see a 2 space indent.

/cc @stevemessick, @alexander-doroshko

**Comment by alexander-doroshko** [comment]
Fixed in the Dart plugin.

**Comment by pq** [comment]
Confirmed fixed. 👍 

![jun-28-2017 10-27-12](https://user-images.githubusercontent.com/67586/27651225-6a28b1bc-5bec-11e7-9480-9f5cb85a45a8.gif)
