### ISSUE TITLE
have the run button active when there are no devices connected

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#971]
It's accurate that we can't run, but users then don't have any real indication as to why the button isn't enabled. We should change to have the button enabled when there are no devices connected, but on a run, display a dialog telling them how to resolve (connect a device, start the simulator, ...).

At some point, if we're able to detect properly configured simulators or emulators, we could instead choose to auto-start an emulator if there are no devices.

**Comment by skybrian** [comment]
Perhaps the device dropdown should show "No Devices" when there are no devices. Clicking on it could reveal a better error message.

**Comment by devoncarew** [comment]
+1
