### ISSUE TITLE
onPressed autocomplete

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter-intellij#975]
Right now, when you add something with a required onPressed argument, and then tell the IDE to add all the required arguments, we add onPressed with the default value `null`.

It would be super helpful if instead of defaulting to null, it defaulted to a lambda with the given arguments but an empty body, as in:

```dart
  onPressed: () { },
```

cc @abarth

**Comment by devoncarew** [comment]
This sounds similar to work that @pq is doing for auto-complete and `child:` / `children:` args.

**Comment by pq** [comment]
> This sounds similar to work that @pq is doing for auto-complete and child: / children: args.

👍  Right.  That one is tracked in #463.

@abarth  Am I right that in general the `onPressed` property is a `VoidCallback`?  Any exceptions?  Besides the presence of an `onPressed` required arg, any other triggers?  Maybe we should do this for all args that take callbacks?

**Comment by Hixie** [comment]
> Am I right that in general the `onPressed` property is a `VoidCallback`?

Yes.

> Any exceptions?

ExpandIcon.onPressed takes a bool argument.

> Besides the presence of an `onPressed` required arg, any other triggers?
> Maybe we should do this for all args that take callbacks?

I think it would make sense to automatically provide an empty lambda with the right types and argument names whenever you automatically add an argument that has a typedef, yes.

onPressed is special only because it's @required.

**Comment by pq** [comment]
https://codereview.chromium.org/2862623002/: 

![onpressed](https://cloud.githubusercontent.com/assets/67586/25679522/87480fd8-3002-11e7-8ab4-4f072eb03d6b.gif)

**Comment by pq** [comment]
Callback with an arg:

![expand_icon](https://cloud.githubusercontent.com/assets/67586/25679713/2178ad2e-3003-11e7-8460-1afa5a53fbe7.gif)

**Comment by Hixie** [comment]
Do we want to add the type of arguments when expanding in this way? It helps document what it is you're receiving...

**Comment by pq** [comment]
> Do we want to add the type of arguments when expanding in this way? It helps document what it is you're receiving...

If that's idiomatic, sure.  (Though a general rule for the analyzer has been to add as little as possible.)

To be clear, you mean:

    onPressed: (boolean value) { }

?

**Comment by Hixie** [comment]
Whether it's idiomatic is an interesting question, but yes, that's what I meant.

**Comment by pq** [comment]
https://github.com/dart-lang/sdk/commit/1a394e975f3e95d8bae01a1327a4883a92b1cace:

![closure_types](https://cloud.githubusercontent.com/assets/67586/25722278/6c907628-30c8-11e7-9b56-6210c408eb36.gif)

🤘

**Comment by Hixie** [comment]
yay
