### ISSUE TITLE
Add an option to show more `flutter run --machine` output in the console

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter-intellij#976]
Sometimes, we get bug reports from users that turns into a dialog with the user whereby we try to ascertain what's happening on their machine.  In these circumstances, it'd often be useful to see the output of `flutter daemon` that IntelliJ is seeing.

Talking about this with @skybrian, perhaps we could add a checkbox option to the plugin settings that would cause us to show the output of `flutter daemon` in the same console that we show the `flutter run` output?  Maybe if this checkbox is checked, we also run `flutter daemon --verbose`?

**Comment by skybrian** [comment]
Technically we are using "flutter run --machine" which speaks the daemon protocol. (The only code that runs "flutter daemon" anymore is the device menu.)

**Comment by skybrian** [comment]
But in this particular case, printing ANDROID_HOME probably would have been most useful, since that's affecting how the "flutter run" command looks for devices.

**Comment by tvolkert** [comment]
Well, `getAdbDevices()` will print what adb it's using when run with `--verbose`, which is more useful than `ANDROID_HOME`, since flutter tools doesn't always use `ANDROID_HOME` (if it thinks it's an invalid project structure, for example).

Seeing the output of the device menu chatter is specifically what we're looking for in this case.  Maybe it should go to a different console than what `flutter run` goes to?

**Comment by skybrian** [comment]
Okay, currently the device menu process doesn't use a console at all, but maybe we could add an option to show it, along with --verbose.

**Comment by tvolkert** [comment]
+1

**Comment by devoncarew** [comment]
Another option here is to somehow leverage the IntelliJ log -

**Comment by skybrian** [comment]
Another idea: if we can't find any devices, "flutter run" currently prints "Unable to locate a development device; Please run 'flutter doctor' for more information..."

It seems like it could print more info right there? (Such as whether ANDROID_HOME is set, etc.) Basically a more-relevant subset of what "flutter doctor" prints. Then the user doesn't have to do anything special; they already have the information.

**Comment by tvolkert** [comment]
Ok, after getting to the bottom of the internal issue that spawned this, I think we want two new features (will file them separately in a moment).  The ability to see the output of the daemon call may still be useful, so I'll leave this open.

**Comment by tvolkert** [comment]
Filed https://github.com/flutter/flutter-intellij/issues/980 and https://github.com/flutter/flutter-intellij/issues/981

I think this one still may provide some value, but those two are bigger bang for the buck.

**Comment by devoncarew** [comment]
Closing - you can now run apps in verbose mode (flutter run -v), and see the daemon protocol traffic. (this is configurable from a toggle in the setting panel)
