### ISSUE TITLE
Respond to 'daemon.showMessage' events by showing toast

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter-intellij#980]
If we added a `--machine` flag to `flutter doctor`, then IntelliJ could invoke that and provide preemptive warnings to the user (more than just console output seen by the user when triggering doctor manually).

Like https://github.com/flutter/flutter-intellij/issues/976, this is in response to a report from a user whereby IntelliJ didn't pick up the `ANDROID_HOME` environment variable, which (combined with them having a non-standard Android SDK install location) meant that `flutter daemon` couldn't locate an Android SDK, and the devices dropdown was empty.  If IntelliJ had the doctor metadata handy, it could have provided a way better user experience in guiding them towards success.

**Comment by tvolkert** [comment]
Related: https://github.com/flutter/flutter-intellij/issues/981

**Comment by tvolkert** [comment]
After discussion and resulting changes in https://github.com/flutter/flutter/pull/9749, I'm re-purposing this issue to make it cover the IntelliJ side of the `'daemon.showMessage'` event.

**Comment by devoncarew** [comment]
👍
