### ISSUE TITLE
Add an option for the user to specify their Android SDK location

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter-intellij#981]
If we added a `--android-sdk` flag to flutter tools to allow the user to explicitly specify the location of their Android SDK, then we could likewise add a UI in the IntelliJ plugin whereby the user could enter the SDK location, and the plugin would wire it up to the flag when it invoked the tools.

**Comment by devoncarew** [comment]
The `flutter config` command does support `--gradle-dir` and `--android-studio-dir`. We probably want to kill the gradle dir option, but could add an `--android-sdk` one.

Exposing that config in IntelliJ makes sense to me.
