### ISSUE TITLE
Breakpoint reactivate after hot reload

### ISSUE THREAD

**Issue by ksdboasit** [flutter/flutter-intellij#983]
Summary:
Doing a hot reload after removing a breakpoint, during a debug session, seems to reactivate the breakpoint. The red dot on the left is still gone, but the app still pauses when it gets there. Placing a new breakpoint on the same line and then removing it, fixes the problem.

What steps will reproduce the problem?
1. Create a new project.
2. Set a breakpoint at the line with _counter++;
3. Run in debug mode (I used iOS SE simulator, but it also happened with an android simulator).
4. Tab the button and resume a couple of times
5. Remove the breakpoint and verify that the app no longer pauses.
6. Do a hot reload.
7. Tab the button again.

What is the expected output? What do you see instead?
Expected:
The number should increase by one without any interruption.

Actual:
The app pauses where the breakpoint used to be.

What version of the product are you using?
Flutter framework revision 87d0010adb, 2017-05-02 22:20:14 -0700
Tools Dart version 1.23.0-dev.11.11

IntelliJ IDEA CE 2017.1.2
Flutter plugin version 13.0

On what operating system?
macOS Sierra 10.12.3

Please provide any additional information below.
Note that this might have been the case for earlier versions as well, since I've seen this before, but was unable to reproduce it.

**Comment by pq** [comment]
Thanks!

This sounds related or the same as the elusive #790?

FYI @skybrian @devoncarew

**Comment by devoncarew** [comment]
We have seen this, but haven't been able to get a reliable repro; thanks for the steps above! Those will hopefully let us track this down.

**Comment by skybrian** [comment]
I noticed something sort of similar. I opened a project I hadn't used a while, ran the debugger, and it stopped at a breakpoint that I hadn't set. In the debugger, clicking on the "View breakpoints" icon showed it, but it did not appear in the gutter in the source file. So it seems like there's a rendering issue?

**Comment by skybrian** [comment]
Reproduced. Debugging this, so far I haven't noticed anything obviously wrong on the plugin side.

It creates three vm breakpoints and deletes them.

After the hot reload, it doesn't restore any breakpoints. After pressing the button, there is a `BreakpointResolved` event followed by `PauseBreakpoint`.

The breakpoint is `breakpoint/1` (which I thought was deleted) and source location is: `/data/user/0/com.yourcompany.click/cache/clickWyFLs4/click/lib/main.dart`

**Comment by skybrian** [comment]
Looking at this in Observatory, things look about the same:

At program startup I see:

```
$ info breakpoints
Future breakpoint 3 at main.dart:59
```

When stopped at the breakpoint:

```
$ info breakpoints
Breakpoint 3 at main.dart:59:11
```

After removing the breakpoint:
```
$ info breakpoints
No breakpoints
```

After hot reload:

```
$ info breakpoints
No breakpoints
```

After pressing the button:
```
Breakpoint 1 resolved at main.dart:59:7
Paused at breakpoint 1 at main.dart:59:7
$ info breakpoints
Breakpoint 1 at main.dart:59:7
```

**Comment by devoncarew** [comment]
Interesting. What are the script IDs? Breakpoints are associated with scripts; after a reload we should have a new scriptId for the reloaded file. So, set bp in script/1, removed bp on script/1, reload, and there should be a new script/2 for the same url.

@a-siva, we're seeing an issue with removed breakpoints still being hit after a reload; who's the best person to look at this?

**Comment by a-siva** [comment]
Is this observed only when the IDE is used or also with command line flutter?

**Comment by skybrian** [comment]
I attempted to reproduce it with command line flutter but was unsuccessful. It seems to have something to do with setting the breakpoint before the program starts, which doesn't have an exact equivalent.

**Comment by skybrian** [comment]
This is not happening for me on my Mac with iPhone SE simulator. (I am not using exactly the same versions, though.)

Yesterday I reproduced it on Linux using an Android emulator.

**Comment by skybrian** [comment]
Okay, I figured out the difference and I'm able to reproduce on my Mac now.

When using an iPhone, if hit hot reload, it prints:

```
Reloaded 0 of 427 libraries in 422ms.
```

In this case the bug doesn't happen.

If I edit the file (below the breakpoint, so the line didn't change) and hot reload, then I see:

```
Reloaded 1 of 426 libraries in 513ms.
```

In this case the bug triggers. So the breakpoint doesn't reappear until after the library is reloaded.

When testing using Android, a large number of libraries get reloaded even though nothing has changed:

```
Reloaded 411 of 426 libraries in 1,143ms.
```

So it happens even though there were no file edits.

This is using Flutter Plugin 13.1 and flutter version:

```
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision ba4bba7498 (13 hours ago) • 2017-05-03 22:50:24 -0700
Engine • revision da8ebf40bd Tools • Dart 1.23.0-dev.11.11
```

**Comment by skybrian** [comment]
When setting the breakpoint we actually try to put it in four possible locations in the VM:

```
remoteBaseUri: /data/user/0/com.yourcompany.click/cache/clickAd4j1X/click
getUrisForFile: file:///Users/skybrian/tmp/click/lib/main.dart ->
  package:click/main.dart
  /Users/skybrian/tmp/click/lib/main.dart
  file:///Users/skybrian/tmp/click/lib/main.dart
  /data/user/0/com.yourcompany.click/cache/click61dwH6/click/lib/main.dart
```
Of those, only three seem to be used (for Android):
```
vmBreakpointAdded: 1 at package:click/main.dart (unresolved)
vmBreakpointAdded: 3 at /data/user/0/com.yourcompany.click/cache/clickAd4j1X/click/lib/main.dart (unresolved)
breakpointResolved: 2 at file:///Users/skybrian/tmp/click/lib/main.dart
```

Before hot reload, we stop here:
 `file:///Users/skybrian/tmp/click/lib/main.dart `
After hot reload, the /data URI resolves and stop at it:
  `/data/user/0/com.yourcompany.click/cache/clickAd4j1X/click/lib/main.dart`

I found that after this happens, modifying main.dart and doing a hot reload would make the phantom breakpoint disappear.

**Comment by skybrian** [comment]
Found a related issue: #991

**Comment by devoncarew** [comment]
I believe fixed in https://github.com/flutter/flutter-intellij/issues/991.
