### ISSUE TITLE
removing breakpoint while stopped leaves phantom breakpoint

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#991]
To reproduce:

- create new Flutter app
- Start the debugger
- set breakpoint at line main.dart line 59 (_counter++)
- press button to stop at breakpoint
- while stopped, remove breakpoint
- resume
- press button

It stops again at the breakpoint, even though it's been removed.

To get rid of the phantom breakpoint, create and remove the breakpoint again while the app is running.

**Comment by skybrian** [comment]
We attempt to add 4 vm breakpoints:

```
getUrisForFile: file:///Users/skybrian/tmp/click/lib/main.dart->
  package:click/main.dart
  /Users/skybrian/tmp/click/lib/main.dart
  /data/user/0/com.yourcompany.click/cache/clickM35MgY/click/lib/main.dart
  file:///Users/skybrian/tmp/click/lib/main.dart
```

Two are added. A third one is apparently not added yet, but it's resolved later:
```
vmBreakpointAdded: 1 at package:click/main.dart (unresolved)
vmBreakpointAdded: 3 at /data/user/0/com.yourcompany.click/cache/clickM35MgY/click/lib/main.dart (unresolved)
breakpointResolved: 2 at file:///Users/skybrian/tmp/click/lib/main.dart
```

When removing the breakpoint, it removes vm breakpoints 1 and 3 but not 2.

**Comment by skybrian** [comment]
One problem might be that VmServiceBase.consumerMap is not accessed in a thread-safe way.  The call to remove() on line 409 should lock consumerMapLock but it doesn't. (I don't know if this is really the issue, but I do see odd behavior where adding entries to consumerMap field doesn't work as I'd expect.)

Another problem seems to be that for some VM breakpoints, when we send the addBreakpointWithScriptUri call it simply returns a Success response. In that case, we drop it on the floor and never remove it later. (We have no breakpoint id to remember, so it's not clear what else the Observatory client could do.)

**Comment by skybrian** [comment]
It's looking like the VM lets you add a breakpoint that you can't remove. It lets you add a breakpoint for /data, but deleting it within the first session (without hot reload) fails.

**Comment by skybrian** [comment]
We are suppressing this error in DartVmServiceDebugProcessZ [1]. But if you attempt to remove a breakpoint and it fails, that can mean it's still there and come back to haunt us.

[1] https://github.com/flutter/flutter-intellij/blob/master/third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java#L134

**Comment by devoncarew** [comment]
Awesome work tracking this down! Should we close in favor of https://github.com/dart-lang/sdk/issues/29566?

**Comment by skybrian** [comment]
Well, I assume we'll wait for the Dart SDK fix, but the bug is still there. If it's not fixed quickly, we might be able to work around it by setting fewer VM breakpoints before the first hot reload.

**Comment by skybrian** [comment]
Confirmed fixed (while testing M15).
