### ISSUE TITLE
Triple slash dart comments can't be removed with key command

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter-intellij#995]
## Steps to Reproduce
1. select a line with triple slash `/// some test`
2. try to use the keyboard shortcut for removing the, `command + ?`. 
3. Notice it removes 2 of the comment slashes and not the third. 

![screen shot 2017-05-06 at 9 07 37 am](https://cloud.githubusercontent.com/assets/1326504/25774007/95430142-323c-11e7-8aef-9df3c0505183.png)

![flutter-ide-comments-issue](https://cloud.githubusercontent.com/assets/1326504/25774010/a212a72e-323c-11e7-9910-7a6760206f55.gif)

## Version info

```
/Users/branflake2267/git/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision d1e895224e (12 hours ago), 2017-05-05 21:44:46 -0700
    • Engine revision 1b01211ee6
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • iPhone SE • 1C15BC7F-DA25-4E71-B479-B601B549CAA0 • ios • iOS 10.3 (simulator)
```

**Comment by devoncarew** [comment]
@branflake2267, I think that command is specifically for commenting in and out code w/ line comments (`//`), so likely not intended to work with dartdoc (`///`) comments.

**Comment by branflake2267** [comment]
Gotcha, I figured at much.

**Comment by pq** [comment]
@branflake2267 : I think @devoncarew's right.  Unless you can think of an improved (and unsurprising) refinement, you OK if we close this one?

**Comment by branflake2267** [comment]
Closing is ok. Go for it. :)

**Comment by pq** [comment]
Thanks @branflake2267 !  And do keep the feedback coming.  It's much appreciated!

🍻
