### ISSUE TITLE
Flutter configuration missing in "Add New Configuration" list (it's under irrelevant)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#996]
Could we put the Flutter configuration (not the Flutter Bazel configuration, but the main Flutter configuration) into the main list of "Add New Configuration" ?

![capture7](https://cloud.githubusercontent.com/assets/5479/25775731/e966ff48-3260-11e7-879c-8e747b8b7aa3.PNG)

I'm trying to add a run configuration for my newly created app, but I need to click the "4 items more (irrelevant)" to see the plain Flutter configuration:

![capture8](https://cloud.githubusercontent.com/assets/5479/25775735/ffbeacc8-3260-11e7-8e53-aed38d7e4981.PNG)

The way it's worded now, it appears to new users as "Flutter (Bazel)" is what they should use. But this is not true for public developers.

**Comment by devoncarew** [comment]
Will ask for more details in https://github.com/flutter/flutter-intellij/issues/997, but this is due to us not seeing this as a Flutter project.

**Comment by sethladd** [comment]
Hm, if that's the case, why does "Flutter (Bazel)" show up?

**Comment by devoncarew** [comment]
The regular flutter run configuration is more specific about which project types it applies to.
