### ISSUE TITLE
Code completing a named parameter doesn't show me the types that could go there

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#998]
I wonder if we could show all the types of Decoration we have, when trying to code complete `decoration: ` in a Container?

Here's what we see now:

![capture10](https://cloud.githubusercontent.com/assets/5479/25775822/101de9d8-3263-11e7-8bca-b768e1e75b2d.PNG)

Those options aren't useful, unfortunately. However, since we know that `decoration:` takes a `Decoration`, could we show the options for Decoration here? (e.g. BoxDecoration)

I'm still learning the Flutter APIs, and bouncing back and forth between API docs and my IDE is less than efficient. I want to code complete my way to success! :)

Thanks!

**Comment by sethladd** [comment]
Because Flutter loves to use named parameters in constructors, this would be a big win. Thank you! :)

**Comment by pq** [comment]
We could do some better filtering (false doesn't make sense for example) but really we want the user to type `new`... and once they do, we want _really good_ completions.  Here we could do some filtering and possibly sorting based on good bets.

cc @lukechurch

**Comment by pq** [comment]
AI @pq: look at what proposals we get from `new`.

**Comment by sethladd** [comment]
why do I need to type new? Sometimes I might want const. Or, sometimes it's a static or enum that goes here.

**Comment by pq** [comment]
Well, `new` (or `const`) are a good cue (and currently required to get the completion engine thinking that you're in a creation mind-set).  It's an interesting question whether we should get more opinionated here.

@sethladd : in an ideal world what completions would you like to see?  All extenders/implementers of `Decoration`?

@danrubel : thoughts?

**Comment by sethladd** [comment]
> All extenders/implementers of Decoration?

Yup! Even if they come from statics or enums available to me.

**Comment by pq** [comment]
From chatting with Dan, this could be improved with suggestions based on type matching.  Infrastructure is in place and the issue can be solved generally.  That said, will investigate with the decorations case as a driving force.

**Comment by pq** [comment]
@danrubel to investigate.

**Comment by sethladd** [comment]
Great, thanks!

**Comment by mit-mit** [comment]
@pq is this an analyzer issue or an IJ issue?

**Comment by pq** [comment]
Analysis server.

cc @danrubel

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/42882

Without the change:
![image](https://user-images.githubusercontent.com/384794/36509524-d5867212-1714-11e8-9aa9-a6ff21705cc4.png)

With the change:
![image](https://user-images.githubusercontent.com/384794/36509412-82a27f50-1714-11e8-8e19-68ebc6692944.png)

**Comment by sethladd** [comment]
Nice improvement!

What happens if I try to complete without first typing "new" or "const" ?

For example:

`padding: <code complete>`

**Comment by scheglov** [comment]
No changes here.
Do you have ideas?

**Comment by sethladd** [comment]
As long as we don't do what the screenshot in https://github.com/flutter/flutter-intellij/issues/998#issue-226803150 is doing, then I'm happy :)

(Put another way, if I try to code complete immediately after a named parameter, show me ONLY what I can put there (both variables whose types match, as well as constructor calls that apply), don't show me variables whose types don't even match.)

**Comment by scheglov** [comment]
It always raises a question of "transitive applicability".
In the code below `b` is not of type `A`, but it has something of type `A`.
If we don't help users to complete `b` (a  long name in real cases), it would be not nice.

```dart
class A {}
class B {
  A a;
}

void foo({A a}) {}

main(B b) {
  foo(a: ^);
}
```

**Comment by sethladd** [comment]
Oh, bummer. That was the original request. :)

In a world with optional new/const, we can expect that developers won't first type 'new' or 'const' in order to trigger the useful code completions.

Are there other completion models here that assume new and const won't be used, but also return the more likely/useful options?

true/false/const/etc just aren't useful :(

**Comment by danrubel** [comment]
IMO it's all about the "relevance" of the suggestion. In this situation, types that match should have a higher relevance than suggestions that do not, and the IDE should display suggestions ranked by the relevance returned by the analysis server.

**Comment by bwilkerson** [comment]
Well, `const` might be useful if it isn't in a constant context so that the user needs to be explicit.

But that aside, there are two things I can think of that we could do. The first is what Dan said: to prioritize suggestions that already have the right type over those that don't, so that less useful ones show up lower in the list. I _do_ think we should do that.

The second is to special case `true` and `false` and just don't show them unless the target type is `bool`, `Object` or `dynamic`. I dislike special casing things, and I suspect that if we get the relevance right we won't need to.

**Comment by devoncarew** [comment]
> In this situation, types that match should have a higher relevance than suggestions that do not

This sounds like a pretty elegant solution - we'll still show all correct suggestions (and allow users to compete through a few expressions to their end goal) but will show the most immediately useful suggestions first.

**Comment by mit-mit** [comment]
+1 for sorting matching types higher!

**Comment by scheglov** [comment]
No prioritizing matching types yet, but [this CL](https://dart-review.googlesource.com/c/sdk/+/43080) will include constructor invocations for implicit creation. So, you can complete `padding: ^` to `EdgeInsets.all()`.

![image](https://user-images.githubusercontent.com/384794/36553043-30c43c72-17b0-11e8-9192-a561b67a72b0.png)

**Comment by sethladd** [comment]
Nice! I see this screenshot starts with "EdIn" ... Does the same result happen if you code complete immediately after the `:` ?

**Comment by scheglov** [comment]
Yes, I actually activated completion right after `:` and then typed `EdIn` to filter the list. Alternatively I could scroll it down to these items.

**Comment by sethladd** [comment]
Well then, double nice! :) Thank you!

**Comment by scheglov** [comment]
OK, we can [prioritize completion suggestions](https://dart-review.googlesource.com/c/sdk/+/43263) in Dart Analysis Server.

Unfortunately IntelliJ has its own opinions about completions and their relevance.
I had to make some hacks into IntelliJ code itself to make it closer to the behavior I would like.
Actual change of IntelliJ completion behavior might happen, or not, I don't know. @alexander-doroshko 

Here, nothing is typed yet, but the suggestions with compatible types are on the top, and sorted alphabetically.

![image](https://user-images.githubusercontent.com/384794/36570537-61f0034e-17e7-11e8-9651-84d046b03e43.png)

**Comment by sethladd** [comment]
Wow! The top results look very relevant and useful.

**Comment by mit-mit** [comment]
Very nice!

**Comment by scheglov** [comment]
And one more fix, for completing [imported enums](https://dart-review.googlesource.com/c/sdk/+/43485).

So, you can complete `Column(crossAxisAlignment: ^)` and get all of the CrossAxisAlignment right away for selection. Or you can start typing `center` and by the time when you typed first letters, you get several completion suggestions. There are several enums with `center`, but because we give compatible types higher relevance, the correct one is always the first.

Don't pay attention to `CrossAxisAlignment` in the middle, it is still the same hiccup of IntelliJ's attempt to re-prioritize our already prioritized suggestions. Hopefully this can be disabled, Analysis Server really knows better about types.

![image](https://user-images.githubusercontent.com/384794/36611433-41b5a7ae-1888-11e8-8cb5-9f756c97ffc7.png)

**Comment by sethladd** [comment]
@scheglov yes yes yes yes yes you are on 🔥

**Comment by scheglov** [comment]
I consider this issue fixed now, at least Analysis Server side of it.
We now prioritize useful suggestions.
If there is anything else, please open new issues.

**Comment by sethladd** [comment]
Thank you very much!

**Comment by InMatrix** [comment]
This is awesome! Thank you.
